FastLED: loop
loop()
void loop ()
Definition at line 64 of file AudioInput.h.
            {
    EVERY_N_MILLIS(1000) { Serial.println("loop active."); }
    // Check if audio source is valid
    if (!audioSource) {
        Serial.println("Audio source is null!");
        delay(1000);
        return;
    }
    // Check for audio errors
    fl::string errorMsg;
    if (audioSource->error(&errorMsg)) {
        Serial.print("Audio error: ");
        Serial.println(errorMsg.c_str());
        delay(100);
        return;
    }
    // Read audio data
    fl::AudioSample sample = audioSource->read();
    if (sample.isValid()) {
        EVERY_N_MILLIS(100) {
            const auto& audioBuffer = sample.pcm();
            const i16* max_sample = fl::max_element(audioBuffer.begin(), audioBuffer.end());
            const i16* min_sample = fl::min_element(audioBuffer.begin(), audioBuffer.end());
            fl::sstream ss;
            ss << "\nRead " << audioBuffer.size() << " samples, timestamp: " << sample.timestamp() << "ms\n";
            ss << "Max sample: " << *max_sample << "\n";
            ss << "Min sample: " << *min_sample << "\n";
            ss << "RMS: " << sample.rms() << "\n";
            ss << "ZCF: " << sample.zcf() << "\n";
            FL_WARN(ss.str());
        }
    }
}
References audioSource, fl::StrN< SIZE >::c_str(), EVERY_N_MILLIS, FL_WARN, fl::AudioSample::isValid(), fl::max_element(), fl::min_element(), fl::AudioSample::pcm(), fl::AudioSample::rms(), fl::StrStream::str(), fl::AudioSample::timestamp(), and fl::AudioSample::zcf().