FastLED: loop
loop()
void loop ()
Definition at line 152 of file AnimartrixRing.ino.
            {
    // Manual audio pump fallback (e.g. WASM / when FastLED.add() didn't take).
    if (!gAutoPump) {
        fl::audio::Sample sample = audio.next();
        if (sample.isValid() && enableOrchestrator.value()) {
            gAudioProcessor->update(sample);
        }
    }
    // Per-frame orchestrator tick. When disabled, fall back to plain manual
    // speed so the sketch still behaves like a non-audio Animartrix demo.
    if (enableOrchestrator.value()) {
        // Apply UI overrides cheaply on every tick.
        animartrix_ring::OrchestratorConfig cfg = gOrchestrator->config();
        cfg.minDwellMs = static_cast<fl::u32>(orchestratorDwellMs.value());
        cfg.classifierHysteresisMs =
            static_cast<fl::u32>(orchestratorHysteresisMs.value());
        gOrchestrator->setConfig(cfg);
        const fl::u32 now = millis();
        gOrchestrator->tick(now, timeSpeed.value());
        // Log state transitions.
        static animartrix_ring::SoundState sLast =
            animartrix_ring::SoundState::Silence;
        if (gOrchestrator->state() != sLast) {
            sLast = gOrchestrator->state();
            printf("AnimartrixRing: state -> %s (engine speed=%.2f)\n",
                   animartrix_ring::toString(sLast),
                   gOrchestrator->lastEngineSpeed());
        }
    } else {
        fxEngine.setSpeed(timeSpeed.value());
    }
    // Draw the effect
    fxEngine.draw(millis(), leds);
    // Calculate final brightness
    uint8_t finalBrightness;
    if (autoBrightness.value()) {
        float avgBri = getAverageBrightness(leds, NUM_LEDS);
        finalBrightness = applyBrightnessCompression(
            avgBri, static_cast<uint8_t>(autoBrightnessMax.value()),
            autoBrightnessLowThreshold.value(),
            autoBrightnessHighThreshold.value());
    } else {
        finalBrightness = static_cast<uint8_t>(brightness.value());
    }
    FastLED.setBrightness(finalBrightness);
    FastLED.show();
}
References applyBrightnessCompression(), audio, autoBrightness, autoBrightnessHighThreshold, autoBrightnessLowThreshold, autoBrightnessMax, brightness, animartrix_ring::OrchestratorConfig::classifierHysteresisMs, enableOrchestrator, FastLED, fxEngine, gAudioProcessor, gAutoPump, getAverageBrightness(), gOrchestrator, leds, animartrix_ring::OrchestratorConfig::minDwellMs, NUM_LEDS, orchestratorDwellMs, orchestratorHysteresisMs, animartrix_ring::Silence, timeSpeed, and animartrix_ring::toString().