FastLED: XY
XY()
uint16_t XY (uint8_t x, uint8_t y)
Examples
Noise.ino, NoisePlusPalette.ino, SmartMatrix.ino, and XYMatrix.ino.
Definition at line 26 of file colorutils.cpp.
{
    FASTLED_UNUSED(x);
    FASTLED_UNUSED(y);
    assert(false);  // The user didn't provide an XY function, so we'll assert here.
    return 0;
}
References assert, FASTLED_UNUSED, x, and y.
Referenced by DrawOneFrame(), loop(), mapNoiseToLEDsUsingPalette(), FASTLED_NAMESPACE_BEGIN::xy_legacy_wrapper(), and XYsafe().