FastLED: loop
loop()
void loop ()
Definition at line 112 of file ElPanelReactive.ino.
            {
    // Decay filters when audio is silent OR paused (no callbacks arriving).
    uint32_t now = millis();
    bool audioTimedOut = (now - lastAudioMs) > kAudioTimeoutMs;
    if (isSilent || audioTimedOut) {
        float dt = (now - lastMillis) / 1000.0f;
        lastMillis = now;
        filterHigh.update(0.0f, dt);
        filterLow.update(0.0f, dt);
    }
    setPanelHigh(filterHigh.value());
    setPanelLow(filterLow.value());
    showPanels();
}
References filterHigh, filterLow, isSilent, kAudioTimeoutMs, lastAudioMs, lastMillis, setPanelHigh(), setPanelLow(), and showPanels().