FastLED: setup
setup()
void setup ()
Definition at line 62 of file ElPanelReactive.ino.
             {
    Serial.begin(115200);
    initPanels();
    auto audio = FastLED.add(audio_ui);
    if (audio) {
        audio->onSilence([&](u8 silent) {
            isSilent = (silent != 0);
            if (isSilent) {
                filterHigh.reset();
                filterLow.reset();
            }
        });
        audio->onVibeLevels(
            [&](const fl::audio::detector::VibeLevels &levels) {
                if (isSilent) return;
                lastAudioMs = millis();
                // Vibe's self-normalizing bass: ~1.0 = average level.
                // Subtract 1.0 so silence/average → 0, beats → positive.
                float signal = (levels.bass - 1.0f) * sensitivity.value();
                signal = fl::clamp(signal, 0.0f, 1.0f);
                uint32_t now = millis();
                float dt = (now - lastMillis) / 1000.0f;
                lastMillis = now;
                // Apply UI-driven attack/decay settings
                filterHigh.setAttackTau(attack1.value());
                filterHigh.setDecayTau(decay1.value());
                filterLow.setAttackTau(attack2.value());
                filterLow.setDecayTau(decay2.value());
                // Per-panel thresholds keep staggered levels.
                // Remap [threshold..1] → [0..1], clamped.
                float t1 = threshold1.value();
                float sig1 = fl::map_range_clamped(signal, t1, 1.0f, 0.0f, 1.0f);
                float t2 = threshold2.value();
                float sig2 = fl::map_range_clamped(signal, t2, 1.0f, 0.0f, 1.0f);
                // Panel 1: stronger signal (squared for contrast)
                filterHigh.update(sig1 * sig1, dt);
                // Panel 2: more responsive (linear)
                filterLow.update(sig2, dt);
            });
    }
}
References attack1, attack2, audio, audio_ui, fl::audio::detector::VibeLevels::bass, fl::clamp(), decay1, decay2, FastLED, filterHigh, filterLow, initPanels(), isSilent, lastAudioMs, lastMillis, fl::map_range_clamped(), sensitivity, Serial, threshold1, and threshold2.