FastLED: fl::WaveSimulation1D::geti16
geti16()
int16_t fl::WaveSimulation1D::geti16 (size_t x) const
Definition at line 259 of file wave_simulation.cpp.
{
    if (!has(x))
        return 0;
    int32_t sum = 0;
    for (uint32_t i = 0; i < mMultiplier; ++i) {
        sum += mSim->geti16(x * mMultiplier + i);
    }
    return static_cast<int16_t>(sum / mMultiplier);
}
References has(), mMultiplier, mSim, and x.
Referenced by geti16All(), geti8(), and getu8().