FastLED: fl::WaveSimulation1D::init
init()
void fl::WaveSimulation1D::init (u32 length, SuperSample factor, float speed, int dampening)
Definition at line 269 of file wave_simulation.cpp.
{
    mOuterLength = length;
    mMultiplier = static_cast<u32>(factor);
    mSim.reset(); // clear out memory first.
    mSim.reset(
        new WaveSimulation1D_Real(length * mMultiplier, speed, dampening));
    // Extra updates (frames) are applied because the simulation slows down in
    // proportion to the supersampling factor.
    mExtraFrames = static_cast<u8>(factor) - 1;
}
References dampening(), length(), mExtraFrames, mMultiplier, mOuterLength, mSim, and speed.
Referenced by WaveSimulation1D(), and setSuperSample().