FastLED: fl::WaveSimulation1D::setf
setf()
void fl::WaveSimulation1D::setf (fl::size x, float value)
Definition at line 376 of file wave_simulation.cpp.hpp.
{
    if (!has(x))
        return;
    value = fl::clamp(value, -1.0f, 1.0f);
    u8 mult = fl::max(1, mMultiplier);
    for (u32 i = 0; i < mult; ++i) {
        mSim->set(x * mult + i, value);
    }
}
References fl::clamp(), has(), fl::max(), mMultiplier, mSim, fl::type_rank< T >::value, and fl::x.
Referenced by ~WaveSimulation1D().