FastLED: Rgbw::Rgbw
Rgbw()
Rgbw::Rgbw (uint16_t white_color_temp = kRGBWDefaultColorTemp, RGBW_MODE rgbw_mode = kRGBWExactColors, EOrderW _w_placement = WDefault) inline explicit
Definition at line 29 of file rgbw.h.
        : white_color_temp(white_color_temp), w_placement(_w_placement),
          rgbw_mode(rgbw_mode) {}
References kRGBWDefaultColorTemp, kRGBWExactColors, rgbw_mode, w_placement, WDefault, and white_color_temp.
Referenced by RgbwDefault::value(), RgbwInvalid::value(), and RgbwWhiteIsOff::value().