FastLED: mapNoiseToLEDsUsingPalette
mapNoiseToLEDsUsingPalette()
void mapNoiseToLEDsUsingPalette ()
Examples
NoisePlusPalette.ino.
Definition at line 148 of file NoisePlusPalette.ino.
{
  static uint8_t ihue=0;
  for(int i = 0; i < kMatrixWidth; i++) {
    for(int j = 0; j < kMatrixHeight; j++) {
      // We use the value at the (i,j) coordinate in the noise
      // array for our brightness, and the flipped value from (j,i)
      // for our pixel's index into the color palette.
      uint8_t index = noise[j][i];
      uint8_t bri =   noise[i][j];
      // if this palette is a 'loop', add a slowly-changing base value
      if( colorLoop) {
        index += ihue;
      }
      // brighten up, as the color palette itself often contains the
      // light/dark dynamic range desired
      if( bri > 127 ) {
        bri = 255;
      } else {
        bri = dim8_raw( bri * 2);
      }
      CRGB color = ColorFromPalette( currentPalette, index, bri);
      leds[XY(i,j)] = color;
    }
  }
  ihue+=1;
}
References ColorFromPalette(), colorLoop, currentPalette, dim8_raw(), kMatrixHeight, kMatrixWidth, leds, noise, and XY().
Referenced by fl::NoisePalette::draw(), and loop().