FastLED: loop
loop()
void loop ()
Definition at line 248 of file NoisePlusPalette.ino.
            {
  // The main program loop that runs continuously
  // Periodically choose a new palette, speed, and scale
  // This creates variety in the animation over time
  ChangePaletteAndSettingsPeriodically();
  // Generate new noise data for this frame
  fillnoise8();
  // Convert the noise data to colors in the LED array
  // using the current palette
  mapNoiseToLEDsUsingPalette();
  // Send the color data to the actual LEDs
  FastLED.show();
  // No delay is needed here as the calculations already take some time
  // Adding a delay would slow down the animation
  // delay(10);
}
References ChangePaletteAndSettingsPeriodically(), FastLED, fillnoise8(), and mapNoiseToLEDsUsingPalette().