FastLED: fl::audio::fft::Context::fastDb
fastDb()
static float fl::audio::fft::Context::fastDb (u32 x) inline static private
Definition at line 350 of file fft_impl.cpp.hpp.
{
        if (x == 0) return 0.0f;
        // Find highest set bit (integer part of log2)
        int msb = 0;
        {
            u32 v = x;
            if (v >= 0x10000u) { v >>= 16; msb += 16; }
            if (v >= 0x100u)   { v >>= 8;  msb += 8; }
            if (v >= 0x10u)    { v >>= 4;  msb += 4; }
            if (v >= 0x4u)     { v >>= 2;  msb += 2; }
            if (v >= 0x2u)     { msb += 1; }
        }
        // Normalized mantissa in [0, 1) as u16x16
        u32 t_raw;
        if (msb >= 16) {
            t_raw = (x >> (msb - 16)) - 65536u;
        } else {
            t_raw = (x << (16 - msb)) - 65536u;
        }
        u16x16 t = u16x16::from_raw(t_raw);
        // log2(1+t) ~= t + 0.345 * t * (1-t)  [max error ~0.008]
        // 22610 = 0.345 * 65536 (from_raw preserves exact original constant)
        static constexpr u16x16 one(1.0f);
        static constexpr u16x16 kCorrection = u16x16::from_raw(22610u);
        u16x16 complement = one - t;
        u16x16 prod = t * complement;
        u16x16 correction = prod * kCorrection;
        u16x16 frac = t + correction;
        // log2(x) = msb + frac, assembled as u16x16
        u16x16 log2_val = u16x16::from_raw(
            (static_cast<u32>(msb) << 16) + frac.raw());
        // 20*log10(x) = 6.02060 * log2(x)
#if FASTLED_FFT_PRECISION == FASTLED_FFT_FIXED16
        // 394593 = 6.02060 * 65536 (from_raw preserves exact original constant)
        static constexpr u16x16 kDbScale = u16x16::from_raw(394593u);
        u16x16 db = log2_val * kDbScale;
        return db.to_float();
#else
        return 6.02060f * log2_val.to_float();
#endif
    }
References fl::u16x16::from_raw(), fl::u16x16::raw(), fl::t, fl::u16x16::to_float(), and fl::x.