FastLED: fl::audio::fft::Context::logRebinRange
logRebinRange()
void fl::audio::fft::Context::logRebinRange (const u16 * mag, int fftN, float fs, int binStart, int binEnd, u32 * rawBinsI, const fl::vector< u8 > & lut) inline private
Definition at line 1010 of file fft_impl.cpp.hpp.
{
        const int numRawBins = fftN / 2 + 1;
        // Compute loop bounds to skip out-of-range FFT bins
        const u16x16 rawBinHz(fs / static_cast<float>(fftN));
        const u16x16 halfBin = rawBinHz >> 1;
        const u16x16 loEdge(mLogBinEdges[binStart]);
        const u16x16 hiEdge(mLogBinEdges[binEnd]);
        int kStart = 0;
        if (loEdge > halfBin) {
            kStart = static_cast<int>(
                u16x16::ceil((loEdge - halfBin) / rawBinHz).to_int());
        }
        int kEnd = static_cast<int>(
            u16x16::ceil((hiEdge + halfBin) / rawBinHz).to_int());
        if (kEnd > numRawBins) kEnd = numRawBins;
        for (int k = kStart; k < kEnd; ++k) {
            rawBinsI[lut[k]] += static_cast<u32>(mag[k]);
        }
    }
References fl::u16x16::ceil(), mLogBinEdges, and fl::u16x16::to_int().
Referenced by runHybrid(), and runLogRebin().