FastLED: fl::audio::fft::Context::buildLinearBinLut
buildLinearBinLut()
void fl::audio::fft::Context::buildLinearBinLut (fl::vector< u8 > & lut, int fftN) inline private
Definition at line 452 of file fft_impl.cpp.hpp.
{
        const int numRawBins = fftN / 2 + 1;
        const int numLinearBins = mTotalBands;
        lut.resize(numRawBins);
        const u16x16 rawBinHz(static_cast<float>(mSampleRate) /
                              static_cast<float>(fftN));
        const u16x16 halfBin = rawBinHz >> 1;
        const u16x16 fminFP(mFmin);
        const u16x16 fmaxFP(mFmax);
        const u16x16 linearBinHz(
            (mFmax - mFmin) / static_cast<float>(numLinearBins));
        // Pre-compute loop bounds (stored for runtime use)
        mLinearKStart = 0;
        if (fminFP > halfBin) {
            mLinearKStart = static_cast<int>(
                u16x16::ceil((fminFP - halfBin) / rawBinHz).to_int());
        }
        mLinearKEnd = static_cast<int>(
            u16x16::ceil((fmaxFP + halfBin) / rawBinHz).to_int());
        if (mLinearKEnd > numRawBins) mLinearKEnd = numRawBins;
        for (int k = 0; k < numRawBins; ++k) {
            u16x16 freq = rawBinHz * static_cast<u32>(k);
            if (freq < fminFP) {
                lut[k] = 0;
                continue;
            }
            int linIdx = static_cast<int>(
                ((freq - fminFP) / linearBinHz).to_int());
            if (linIdx >= numLinearBins)
                linIdx = numLinearBins - 1;
            lut[k] = static_cast<u8>(linIdx);
        }
    }
References fl::u16x16::ceil(), mFmax, mFmin, mLinearKEnd, mLinearKStart, mSampleRate, mTotalBands, fl::vector< T >::resize(), and fl::u16x16::to_int().
Referenced by initHybrid(), initLogRebin(), initNaive(), and initOctaveWise().