FastLED: fl::audio::fft::Context::run
run()
void fl::audio::fft::Context::run (span< const i16 > buffer, Bins * out) inline
Definition at line 117 of file fft_impl.cpp.hpp.
{
        switch (mMode) {
        case Mode::LOG_REBIN:
            runLogRebin(buffer, out);
            break;
        case Mode::CQ_NAIVE:
            runNaive(buffer, out);
            break;
        case Mode::CQ_OCTAVE:
            runOctaveWise(buffer, out);
            break;
        case Mode::CQ_HYBRID:
            runHybrid(buffer, out);
            break;
        case Mode::AUTO:
            FL_WARN("Mode::AUTO should have been resolved");
            break;
        }
    }
References fl::audio::fft::AUTO, fl::audio::fft::CQ_HYBRID, fl::audio::fft::CQ_NAIVE, fl::audio::fft::CQ_OCTAVE, FL_WARN, fl::audio::fft::LOG_REBIN, mMode, runHybrid(), runLogRebin(), runNaive(), and runOctaveWise().