FastLED: fl::audio::fft::Context::Context
Context()
fl::audio::fft::Context::Context (int samples, int bands, float fmin, float fmax, int sample_rate, Mode mode, Window window) inline
Definition at line 61 of file fft_impl.cpp.hpp.
        : mFftrCfg(nullptr), mInputSamples(samples),
          mKernels(nullptr),
          mMode(mode), mTotalBands(bands), mFmin(fmin), mFmax(fmax),
          mSampleRate(sample_rate), mWindow(window) {
        Args::resolveModeEnums(mMode, mWindow, bands, samples, fmin, fmax);
        fl::memset(&mCqCfg, 0, sizeof(mCqCfg));
        mFftrCfg = kiss_fftr_alloc(samples, 0, nullptr, nullptr);
        if (!mFftrCfg) {
            FL_WARN("Failed to allocate Impl context");
            return;
        }
        switch (mMode) {
        case Mode::LOG_REBIN:
            initLogRebin();
            break;
        case Mode::CQ_NAIVE:
            initNaive(samples, bands, fmin, fmax, sample_rate);
            break;
        case Mode::CQ_HYBRID:
            initHybrid(samples, bands, fmin, fmax, sample_rate);
            break;
        case Mode::CQ_OCTAVE:
            initOctaveWise(samples, bands, fmin, fmax, sample_rate);
            break;
        case Mode::AUTO:
            FL_WARN("Mode::AUTO should have been resolved");
            break;
        }
    }
References fl::audio::fft::AUTO, fl::audio::fft::CQ_HYBRID, fl::audio::fft::CQ_NAIVE, fl::audio::fft::CQ_OCTAVE, FL_WARN, initHybrid(), initLogRebin(), initNaive(), initOctaveWise(), kiss_fftr_alloc(), fl::audio::fft::LOG_REBIN, mCqCfg, fl::memset(), mFftrCfg, mFmax, mFmin, mInputSamples, mKernels, mMode, mSampleRate, mTotalBands, mWindow, and fl::audio::fft::Args::resolveModeEnums().