FastLED: fl::audio::fft::Context::runNaive
runNaive()
void fl::audio::fft::Context::runNaive (span< const i16 > buffer, Bins * out) inline private
Definition at line 295 of file fft_impl.cpp.hpp.
{
        out->setParams(mFmin, mFmax, mSampleRate);
        const int fftSize = mInputSamples;
        const int numRawBins = fftSize / 2 + 1;
        FftScratch &s = scratch();
        s.fftOut.resize(fftSize);
        s.re.resize(numRawBins);
        s.im.resize(numRawBins);
        s.mag.resize(numRawBins);
        fl_fft_real_forward(mFftrCfg, mInputSamples, buffer.data(), s.fftOut.data());
        // Deinterleave AoS → SoA and batch-compute magnitudes
        deinterleave(s.fftOut.data(), s.re.data(), s.im.data(), numRawBins);
        batchMag(s.re.data(), s.im.data(), s.mag.data(), numRawBins);
        computeLinearBins(s.mag.data(), fftSize, out);
        FASTLED_STACK_ARRAY(kiss_fft_cpx, cq, mCqCfg.bands);
        apply_kernels(s.fftOut.data(), cq, mKernels, mCqCfg);
        const int bands = mCqCfg.bands;
        fl::vector<float> &rawBins = out->raw_mut();
        rawBins.resize(bands);
        for (int i = 0; i < bands; ++i) {
            i32 real = cq[i].r;
            i32 imag = cq[i].i;
#ifdef FIXED_POINT
            rawBins[i] = static_cast<float>(fastMag(real, imag));
#else
            float r2 = float(real * real);
            float i2 = float(imag * imag);
            rawBins[i] = sqrt(r2 + i2);
#endif
        }
    }
References apply_kernels(), batchMag(), computeLinearBins(), fl::span< T, Extent >::data(), fl::vector< T >::data(), deinterleave(), FASTLED_STACK_ARRAY, fastMag(), fl::audio::fft::Context::FftScratch::fftOut, fl::audio::fft::fl_fft_real_forward(), fl::audio::fft::Context::FftScratch::im, fl::audio::fft::Context::FftScratch::mag, mCqCfg, mFftrCfg, mFmax, mFmin, mInputSamples, mKernels, mSampleRate, fl::audio::fft::Bins::raw_mut(), fl::audio::fft::Context::FftScratch::re, fl::vector< T >::resize(), scratch(), fl::audio::fft::Bins::setParams(), and fl::sqrt().
Referenced by run().