FastLED: fl::audio::fft::Context::runLogRebin
runLogRebin()
void fl::audio::fft::Context::runLogRebin (span< const i16 > buffer, Bins * out) inline private
Definition at line 237 of file fft_impl.cpp.hpp.
{
        out->setParams(mFmin, mFmax, mSampleRate);
        const int N = mInputSamples;
        const int bands = mTotalBands;
        const int numRawBins = N / 2 + 1;
        // Use thread-local scratch buffers to avoid stack overflow on
        // ESP32 tasks with limited stack (~4-8 KB).
        FftScratch &s = scratch();
        s.windowed.resize(N);
        s.fftOut.resize(N);
        s.re.resize(numRawBins);
        s.im.resize(numRawBins);
        s.mag.resize(numRawBins);
        s.rawBinsI.resize(bands);
        applyWindow(buffer.data(), mWindowBuf.data(), s.windowed.data(), N);
        fl_fft_real_forward(mFftrCfg, mInputSamples, s.windowed.data(), s.fftOut.data());
        // Deinterleave AoS → SoA and batch-compute magnitudes
        deinterleave(s.fftOut.data(), s.re.data(), s.im.data(), numRawBins);
        batchMag(s.re.data(), s.im.data(), s.mag.data(), numRawBins);
        // Linear bins (same as other paths)
        computeLinearBins(s.mag.data(), N, out);
        // Group FFT bins into log-spaced output bins (integer accumulation)
        fl::memset(s.rawBinsI.data(), 0, sizeof(u32) * bands);
        logRebinRange(s.mag.data(), N, static_cast<float>(mSampleRate),
                      0, bands, s.rawBinsI.data(), mLogBinLut);
        // Store raw magnitudes (dB computed lazily by Bins::db())
        fl::vector<float> &rawBins = out->raw_mut();
        rawBins.resize(bands);
        for (int i = 0; i < bands; ++i) {
            rawBins[i] = static_cast<float>(s.rawBinsI[i]);
        }
        // Store bin-width normalization factors so consumers can optionally
        // normalize (e.g. for equalization display). Raw output is unchanged.
        out->setNormFactors(mLogBinNormFactors);
    }
References applyWindow(), batchMag(), computeLinearBins(), fl::span< T, Extent >::data(), fl::vector< T >::data(), deinterleave(), fl::audio::fft::Context::FftScratch::fftOut, fl::audio::fft::fl_fft_real_forward(), fl::audio::fft::Context::FftScratch::im, logRebinRange(), fl::audio::fft::Context::FftScratch::mag, fl::memset(), mFftrCfg, mFmax, mFmin, mInputSamples, mLogBinLut, mLogBinNormFactors, mSampleRate, mTotalBands, mWindowBuf, fl::audio::fft::Bins::raw_mut(), fl::audio::fft::Context::FftScratch::rawBinsI, fl::audio::fft::Context::FftScratch::re, fl::vector< T >::resize(), scratch(), fl::audio::fft::Bins::setNormFactors(), fl::audio::fft::Bins::setParams(), and fl::audio::fft::Context::FftScratch::windowed.
Referenced by run().