FastLED: fl::audio::fft::Context::initLogRebin
initLogRebin()
void fl::audio::fft::Context::initLogRebin () inline private
Definition at line 178 of file fft_impl.cpp.hpp.
{
        // Pre-compute bin edges aligned with CQ center frequencies.
        // CQ center[i] = fmin * exp(logRatio * i / (bands-1)), so
        // binToFreq(i) returns these centers for both modes.
        //
        // Edges are placed at the geometric mean of adjacent centers:
        //   edge[i] = sqrt(center[i-1] * center[i])
        //           = fmin * exp(logRatio * (2*i - 1) / (2*(bands-1)))
        //
        // edge[0] and edge[bands] extend half a bin beyond fmin/fmax.
        const int bands = mTotalBands;
        mLogBinEdges.resize(bands + 1);
        float logRatio = logf(mFmax / mFmin);
        if (bands <= 1) {
            mLogBinEdges[0] = mFmin;
            mLogBinEdges[1] = mFmax;
        } else {
            float denom = 2.0f * static_cast<float>(bands - 1);
            // Edge below first center (half-bin below fmin)
            mLogBinEdges[0] =
                mFmin * expf(-logRatio / denom);
            // Intermediate edges: geometric mean of adjacent CQ centers
            for (int i = 1; i < bands; i++) {
                mLogBinEdges[i] =
                    mFmin *
                    expf(logRatio * (2.0f * static_cast<float>(i) - 1.0f) /
                         denom);
            }
            // Edge above last center (half-bin above fmax)
            mLogBinEdges[bands] =
                mFmax * expf(logRatio / denom);
        }
        // Clamp top bin edge to Nyquist — prevents incomplete bin coverage
        // and bad normalization when fmax is close to Nyquist.
        float nyquist = static_cast<float>(mSampleRate) / 2.0f;
        if (mLogBinEdges[bands] > nyquist) {
            mLogBinEdges[bands] = nyquist;
        }
        computeBinEdgesQ16();
        // Pre-compute bin mapping LUTs
        buildLogBinLut(mLogBinLut, mInputSamples,
                       static_cast<float>(mSampleRate), 0, mTotalBands);
        buildLinearBinLut(mLinearBinLut, mInputSamples);
        // Pre-compute window as Q15 integer coefficients
        computeWindow(mWindowBuf, mInputSamples, mWindow);
        // Pre-compute bin-width normalization factors for LOG_REBIN.
        // Without normalization, wider high-frequency bins accumulate more
        // sidelobe energy than narrow low-frequency bins, creating visible
        // "aliasing" artifacts during a tone sweep.
        computeLogRebinNormFactors(mLogBinNormFactors, mLogBinLut,
                                   mInputSamples, static_cast<float>(mSampleRate),
                                   0, mTotalBands);
    }
References buildLinearBinLut(), buildLogBinLut(), computeBinEdgesQ16(), computeLogRebinNormFactors(), computeWindow(), fl::expf(), fl::logf(), mFmax, mFmin, mInputSamples, mLinearBinLut, mLogBinEdges, mLogBinLut, mLogBinNormFactors, mSampleRate, mTotalBands, mWindow, and mWindowBuf.
Referenced by Context().