FastLED: fl::audio::fft::Context::computeLinearBins
computeLinearBins()
void fl::audio::fft::Context::computeLinearBins (const u16 * mag, int , Bins * out) inline private
Definition at line 1034 of file fft_impl.cpp.hpp.
{
        const int numLinearBins = mTotalBands;
        fl::vector<float> &linBins = out->linear_mut();
        linBins.resize(numLinearBins);
        out->setLinearParams(mFmin, mFmax);
        // Integer accumulation using pre-computed LUT
        FASTLED_STACK_ARRAY(u32, linBinsI, numLinearBins);
        for (int i = 0; i < numLinearBins; ++i) {
            linBinsI[i] = 0;
        }
        for (int k = mLinearKStart; k < mLinearKEnd; ++k) {
            linBinsI[mLinearBinLut[k]] += static_cast<u32>(mag[k]);
        }
        // Convert to float
        for (int i = 0; i < numLinearBins; ++i) {
            linBins[i] = static_cast<float>(linBinsI[i]);
        }
    }
References FASTLED_STACK_ARRAY, fl::audio::fft::Bins::linear_mut(), mFmax, mFmin, mLinearBinLut, mLinearKEnd, mLinearKStart, mTotalBands, fl::vector< T >::resize(), and fl::audio::fft::Bins::setLinearParams().
Referenced by runHybrid(), runLogRebin(), runNaive(), and runOctaveWise().