FastLED: fl::u8x24::pow
pow()
static FASTLED_FORCE_INLINE u8x24 fl::u8x24::pow (u8x24 base, u8x24 exp) inline static
Definition at line 169 of file u8x24.h.
{
        if (base.mValue == 0) return u8x24();
        constexpr u8x24 one(1.0f);
        if (exp.mValue == 0) return one;
        if (base == one) return one;
        // Snap base values within ~2 ULPs of 1.0 to exactly 1.0 to dodge the
        // log2(1+t) minimax polynomial's upper-endpoint residual (#2969).
        constexpr u32 kOneRaw = static_cast<u32>(SCALE);
        if (base.mValue >= (kOneRaw - 2u) && base.mValue <= kOneRaw) {
            return one;
        }
        return exp2_fp(exp * log2_fp(base));
    }
References u8x24(), fl::exp(), exp2_fp(), FASTLED_FORCE_INLINE, FL_NOEXCEPT, log2_fp(), and SCALE.