FastLED: fl::u8x24::from_raw
from_raw()
static constexpr FASTLED_FORCE_INLINE u8x24 fl::u8x24::from_raw (u32 raw) inline static constexpr
Definition at line 53 of file u8x24.h.
{
        return u8x24(raw, RawTag());
    }
References u8x24(), FASTLED_FORCE_INLINE, FL_NOEXCEPT, and raw().
Referenced by ceil(), exp2_fp(), floor(), fract(), log2_fp(), mod(), operator*(), operator*, operator*(), operator+(), operator-(), operator/(), operator<<(), operator>>(), rsqrt(), and sqrt().