FastLED: fl::Scheduler::update
update()
void fl::Scheduler::update ()
Definition at line 105 of file async.cpp.
                       {
    uint32_t current_time = fl::time();
    // Use index-based iteration to avoid iterator invalidation issues
    for (fl::size i = 0; i < mTasks.size();) {
        task& t = mTasks[i];
        auto impl = t.get_impl();
        if (!impl || impl->is_canceled()) {
            // erase() returns bool in HeapVector, not iterator
            mTasks.erase(mTasks.begin() + i);
            // Don't increment i since we just removed an element
        } else {
            // Check if task is ready to run (frame tasks will return false here)
            bool should_run = impl->ready_to_run(current_time);
            if (should_run) {
                // Update last run time for recurring tasks
                impl->set_last_run_time(current_time);
                // Execute the task
                if (impl->has_then()) {
                    impl->execute_then();
                } else {
                    warn_no_then(impl->id(), impl->trace_label());
                }
                // Remove one-shot tasks, keep recurring ones
                bool is_recurring = (impl->type() == TaskType::kEveryMs || impl->type() == TaskType::kAtFramerate);
                if (is_recurring) {
                    ++i; // Keep recurring tasks
                } else {
                    // erase() returns bool in HeapVector, not iterator
                    mTasks.erase(mTasks.begin() + i);
                    // Don't increment i since we just removed an element
                }
            } else {
                ++i;
            }
        }
    }
}
References fl::kAtFramerate, fl::kEveryMs, mTasks, t, fl::time(), and warn_no_then().
Referenced by fl::async_run().