FastLED: MaxFadeTracker::operator()
operator()()
float MaxFadeTracker::operator() (const int16_t * samples, size_t length) inline
Process one 512-sample block; returns [0…1] with inertia.
Definition at line 29 of file fx_audio.h.
{
        assert(length == 512);
        // 1) block peak
        float peak = 0.0f;
        for (size_t i = 0; i < length; ++i) {
            float v = fl::abs(samples[i]) * (1.0f/32768.0f);
            peak = fl::max(peak, v);
        }
        // 2) time delta
        float dt = static_cast<float>(length) / mSampleRate;
        // 3) update mCurrentLevel with attack/decay
        if (peak > mCurrentLevel) {
            float riseFactor = 1.0f - fl::exp(-mAttackRate * dt);
            mCurrentLevel += (peak - mCurrentLevel) * riseFactor;
        } else {
            float decayFactor = fl::exp(-mDecayRate * dt);
            mCurrentLevel *= decayFactor;
        }
        // 4) output inertia: smooth mSmoothedOutput → mCurrentLevel
        float outFactor = 1.0f - fl::exp(-mOutputRate * dt);
        mSmoothedOutput += (mCurrentLevel - mSmoothedOutput) * outFactor;
        return mSmoothedOutput;
    }
References fl::abs(), fl::exp(), length(), mAttackRate, fl::max(), mCurrentLevel, mDecayRate, mOutputRate, mSampleRate, and mSmoothedOutput.