FastLED: fl::WeakReferent::WeakReferent
WeakReferent() [1/3]
fl::WeakReferent::WeakReferent () inline
Definition at line 264 of file ptr.h.
: mRefCount(0), mReferent(nullptr) {}
References mRefCount, and mReferent.
Referenced by WeakReferent(), WeakReferent(), operator=(), and operator=().