FastLED: gen.gen_points
gen_points()
list[Point] gen.gen_points (list[HexagonAngle] input, int leds_per_strip, Point startPos, list[int] | None exclude = None, bool add_last = False)
Definition at line 68 of file gen.py.
) -> list[Point]:
    points: list[Point] = []
    if (not input) or (not leds_per_strip):
        return points
    exclude = exclude or []
    # Start FSM. Start pointer get's put into the accumulator.
    curr_point: Point = Point(startPos.x, startPos.y)
    # points.append(curr_point)
    last_angle = input[0]
    for i,angle in enumerate(input):
        excluded = i in exclude
        values = list(range(leds_per_strip))
        last_angle = angle
        for v in values:
            last_angle = angle
            curr_point = next_point(curr_point, angle, SPACE_PER_LED)
            if not excluded:
                points.append(curr_point)
        #if i == len(input) - 1:
        #    break
        # Next starting point
        curr_point = next_point(curr_point, last_angle, SPACE_PER_LED)
        #if not excluded:
        #    points.append(curr_point)
    if add_last:
        points.append(curr_point)
    return points
References next_point().
Referenced by find_green_anchore_point(), find_red_anchor_point(), generate_black_points(), generate_blue_points(), generate_green_points(), generate_red_points(), main(), simple_test(), two_angle_test(), and two_angle_test2().