FastLED: gen.unit_test
unit_test()
None gen.unit_test ()
Definition at line 252 of file gen.py.
def unit_test() -> None:
    #simple_test()
    #two_angle_test()
    out = {}
    map = out.setdefault("map", {})
    map.update({
        "red_segment": Point.toJson(generate_red_points()),
        "back_segment": Point.toJson(generate_black_points()),
        "green_segment": Point.toJson(generate_green_points()),
        "blue_segment": Point.toJson(generate_blue_points()),
    })
    print(json.dumps(out))
    # write it out to a file
    with open("output.json", "w") as f:
        f.write(json.dumps(out))
References generate_black_points(), generate_blue_points(), generate_green_points(), generate_red_points(), and unit_test().
Referenced by unit_test().