FastLED: fl::FFTContext::fft_unit_test
fft_unit_test()
void fl::FFTContext::fft_unit_test (Slice< const int16_t > buffer, FFTBins * out) inline
Definition at line 67 of file fft_impl.cpp.
{
        // FASTLED_ASSERT(512 == m_cq_cfg.samples, "FFTImpl samples mismatch and
        // are still hardcoded to 512");
        out->clear();
        // allocate
        FASTLED_STACK_ARRAY(kiss_fft_cpx, fft, m_cq_cfg.samples);
        FASTLED_STACK_ARRAY(kiss_fft_cpx, cq, m_cq_cfg.bands);
        // initialize
        kiss_fftr(m_fftr_cfg, buffer.data(), fft);
        apply_kernels(fft, cq, m_kernels, m_cq_cfg);
        const float maxf = m_cq_cfg.fmax;
        const float minf = m_cq_cfg.fmin;
        const float delta_f = (maxf - minf) / m_cq_cfg.bands;
        // begin transform
        for (int i = 0; i < m_cq_cfg.bands; ++i) {
            int32_t real = cq[i].r;
            int32_t imag = cq[i].i;
            float r2 = float(real * real);
            float i2 = float(imag * imag);
            float magnitude = sqrt(r2 + i2);
            float magnitude_db = 20 * log10(magnitude);
            float f_start = minf + i * delta_f;
            float f_end = f_start + delta_f;
            FASTLED_UNUSED(f_start);
            FASTLED_UNUSED(f_end);
            if (magnitude <= 0.0f) {
                magnitude_db = 0.0f;
            }
            // FASTLED_UNUSED(magnitude_db);
            // FASTLED_WARN("magnitude_db: " << magnitude_db);
            // out->push_back(magnitude_db);
            out->bins_raw.push_back(magnitude);
            out->bins_db.push_back(magnitude_db);
        }
    }
References apply_kernels(), fl::FFTBins::bins_db, fl::FFTBins::bins_raw, fl::FFTBins::clear(), fl::Slice< T >::data(), FASTLED_STACK_ARRAY, FASTLED_UNUSED, fft, kiss_fftr(), m_cq_cfg, m_fftr_cfg, and m_kernels.