FastLED: fl::Pacifica::pacifica_one_layer
pacifica_one_layer()
void fl::Pacifica::pacifica_one_layer (CRGB * leds, CRGBPalette16 & p, uint16_t cistart, uint16_t wavescale, uint8_t bri, uint16_t ioff) private
Definition at line 90 of file pacifica.h.
{
    uint16_t ci = cistart;
    uint16_t waveangle = ioff;
    uint16_t wavescale_half = (wavescale / 2) + 20;
    for (uint16_t i = 0; i < mNumLeds; i++) {
        waveangle += 250;
        uint16_t s16 = sin16(waveangle) + 32768;
        uint16_t cs = scale16(s16, wavescale_half) + wavescale_half;
        ci += cs;
        uint16_t sindex16 = sin16(ci) + 32768;
        uint8_t sindex8 = scale16(sindex16, 240);
        CRGB c = ColorFromPalette(p, sindex8, bri, LINEARBLEND);
        leds[i] += c;
    }
}
References fl::ColorFromPalette(), leds, fl::Fx::mNumLeds, p, scale16(), and sin16.
Referenced by draw().