FastLED: fl::Pacifica::draw
draw()
void fl::Pacifica::draw (DrawContext context) override virtual
Parameters
now The current time in milliseconds. Fx writers are encouraged to use this instead of millis() directly as this will more deterministic behavior.
Implements fl::Fx.
Definition at line 45 of file pacifica.h.
{
    CRGB *leds = ctx.leds;
    uint32_t now = ctx.now;
    if (leds == nullptr || mNumLeds == 0) {
        return;
    }
    // Update the hue each time through the loop
    uint32_t ms = now;
    uint32_t deltams = ms - sLastms;
    sLastms = ms;
    uint16_t speedfactor1 = beatsin16(3, 179, 269);
    uint16_t speedfactor2 = beatsin16(4, 179, 269);
    uint32_t deltams1 = (deltams * speedfactor1) / 256;
    uint32_t deltams2 = (deltams * speedfactor2) / 256;
    uint32_t deltams21 = (deltams1 + deltams2) / 2;
    sCIStart1 += (deltams1 * beatsin88(1011, 10, 13));
    sCIStart2 -= (deltams21 * beatsin88(777, 8, 11));
    sCIStart3 -= (deltams1 * beatsin88(501, 5, 7));
    sCIStart4 -= (deltams2 * beatsin88(257, 4, 6));
    // Clear out the LED array to a dim background blue-green
    fill_solid(leds, mNumLeds, CRGB(2, 6, 10));
    // Render each of four layers, with different scales and speeds, that vary
    // over time
    pacifica_one_layer(leds, pacifica_palette_1, sCIStart1,
                       beatsin16(3, 11 * 256, 14 * 256), beatsin8(10, 70, 130),
                       0 - beat16(301));
    pacifica_one_layer(leds, pacifica_palette_2, sCIStart2,
                       beatsin16(4, 6 * 256, 9 * 256), beatsin8(17, 40, 80),
                       beat16(401));
    pacifica_one_layer(leds, pacifica_palette_3, sCIStart3, 6 * 256,
                       beatsin8(9, 10, 38), 0 - beat16(503));
    pacifica_one_layer(leds, pacifica_palette_3, sCIStart4, 5 * 256,
                       beatsin8(8, 10, 28), beat16(601));
    // Add brighter 'whitecaps' where the waves lines up more
    pacifica_add_whitecaps(leds);
    // Deepen the blues and greens a bit
    pacifica_deepen_colors(leds);
}
References beat16(), beatsin16(), beatsin8(), beatsin88(), fl::fill_solid(), fl::_DrawContext::leds, leds, fl::Fx::mNumLeds, fl::_DrawContext::now, pacifica_add_whitecaps(), pacifica_deepen_colors(), pacifica_one_layer(), pacifica_palette_1, pacifica_palette_2, pacifica_palette_3, sCIStart1, sCIStart2, sCIStart3, sCIStart4, and sLastms.