FastLED: fl::Pacifica::pacifica_add_whitecaps
pacifica_add_whitecaps()
void fl::Pacifica::pacifica_add_whitecaps (CRGB * leds) private
Definition at line 110 of file pacifica.h.
{
    uint8_t basethreshold = beatsin8(9, 55, 65);
    uint8_t wave = beat8(7);
    for (uint16_t i = 0; i < mNumLeds; i++) {
        uint8_t threshold = scale8(sin8(wave), 20) + basethreshold;
        wave += 7;
        uint8_t l = leds[i].getAverageLight();
        if (l > threshold) {
            uint8_t overage = l - threshold;
            uint8_t overage2 = qadd8(overage, overage);
            leds[i] += CRGB(overage, overage2, qadd8(overage2, overage2));
        }
    }
}
References beat8(), beatsin8(), leds, fl::Fx::mNumLeds, qadd8(), scale8(), and sin8.