FastLED: applyFancyEffect
applyFancyEffect()
void applyFancyEffect (uint32_t now, bool button_active)
Definition at line 139 of file FxWave2d.ino.
{
    uint32_t total =
        map(fancySpeed.as<uint32_t>(), 0, fancySpeed.getMax(), 1000, 100);
    static TimeRamp pointTransition = TimeRamp(total, 0, 0);
    if (button_active) {
        pointTransition.trigger(now, total, 0, 0);
    }
    if (!pointTransition.isActive(now)) {
        // no need to draw
        return;
    }
    int mid_x = WIDTH / 2;
    int mid_y = HEIGHT / 2;
    // now make a cross
    int amount = WIDTH / 2;
    int start_x = mid_x - amount;
    int end_x = mid_x + amount;
    int start_y = mid_y - amount;
    int end_y = mid_y + amount;
    int curr_alpha = pointTransition.update8(now);
    int left_x = map(curr_alpha, 0, 255, mid_x, start_x);
    int down_y = map(curr_alpha, 0, 255, mid_y, start_y);
    int right_x = map(curr_alpha, 0, 255, mid_x, end_x);
    int up_y = map(curr_alpha, 0, 255, mid_y, end_y);
    float curr_alpha_f = curr_alpha / 255.0f;
    float valuef = (1.0f - curr_alpha_f) * fancyIntensity.value() / 255.0f;
    int span = fancyParticleSpan.value() * WIDTH;
    for (int x = left_x - span; x < left_x + span; x++) {
        waveFxLower.addf(x, mid_y, valuef);
        waveFxUpper.addf(x, mid_y, valuef);
    }
    for (int x = right_x - span; x < right_x + span; x++) {
        waveFxLower.addf(x, mid_y, valuef);
        waveFxUpper.addf(x, mid_y, valuef);
    }
    for (int y = down_y - span; y < down_y + span; y++) {
        waveFxLower.addf(mid_x, y, valuef);
        waveFxUpper.addf(mid_x, y, valuef);
    }
    for (int y = up_y - span; y < up_y + span; y++) {
        waveFxLower.addf(mid_x, y, valuef);
        waveFxUpper.addf(mid_x, y, valuef);
    }
}
References fancyIntensity, fancyParticleSpan, fancySpeed, HEIGHT, fl::TimeRamp::isActive(), fl::TimeRamp::trigger(), fl::TimeRamp::update8(), waveFxLower, waveFxUpper, WIDTH, x, and y.
Referenced by loop().