FastLED: loop
loop()
void loop ()
Definition at line 258 of file FxWave2d.ino.
            {
    // Your code here
    uint32_t now = millis();
    ui_state state = ui();
    if (state.button) {
        triggerRipple();
    }
    applyFancyEffect(now, state.bigButton);
    processAutoTrigger(now);
    Fx::DrawContext ctx(now, leds);
    fxBlend.draw(ctx);
    FastLED.show();
}
References applyFancyEffect(), ui_state::bigButton, ui_state::button, FastLED, fxBlend, leds, processAutoTrigger(), triggerRipple(), and ui().