FastLED: fl::audio::detector::DynamicsAnalyzer::update
update()
void fl::audio::detector::DynamicsAnalyzer::update (shared_ptr< Context > context) override virtual
Implements fl::audio::Detector.
Definition at line 33 of file dynamics_analyzer.cpp.hpp.
{
    mCurrentRMS = context->getRMS();
    u32 timestamp = context->getTimestamp();
    // Update peak with decay
    updatePeak(mCurrentRMS);
    // Add to history
    if (mRMSHistory.size() < mHistorySize) {
        mRMSHistory.push_back(mCurrentRMS);
        mHistoryIndex = mRMSHistory.size();
    } else {
        mRMSHistory[mHistoryIndex] = mCurrentRMS;
        mHistoryIndex = (mHistoryIndex + 1) % mHistorySize;
    }
    // Calculate average RMS from history
    float sum = 0.0f;
    for (fl::size i = 0; i < mRMSHistory.size(); i++) {
        sum += mRMSHistory[i];
    }
    mAverageRMS = (mRMSHistory.size() > 0) ? sum / mRMSHistory.size() : 0.0f;
    // Track minimum RMS (with slow rise to handle changing environments)
    if (mCurrentRMS < mMinRMS) {
        mMinRMS = mCurrentRMS;
    } else {
        mMinRMS += (mCurrentRMS - mMinRMS) * 0.001f;  // Very slow rise
    }
    // Calculate dynamic trend
    float newTrend = calculateTrend();
    // Smooth the trend
    mTrend = mSmoothingFactor * mTrend + (1.0f - mSmoothingFactor) * newTrend;
    // Determine crescendo/diminuendo state
    mPrevIsCrescendo = mIsCrescendo;
    mPrevIsDiminuendo = mIsDiminuendo;
    mIsCrescendo = (mTrend > mTrendThreshold);
    mIsDiminuendo = (mTrend < -mTrendThreshold);
    // Update compression ratio
    updateCompression();
    mLastUpdateTime = timestamp;
}
References DynamicsAnalyzer(), calculateTrend(), mAverageRMS, mCurrentRMS, mHistoryIndex, mHistorySize, mIsCrescendo, mIsDiminuendo, mLastUpdateTime, mMinRMS, mPrevIsCrescendo, mPrevIsDiminuendo, mRMSHistory, mSmoothingFactor, mTrend, mTrendThreshold, update(), updateCompression(), and updatePeak().
Referenced by ~DynamicsAnalyzer(), and update().