FastLED: fl::JsonValue::operator[]
operator[]() [2/2]
JsonValue & fl::JsonValue::operator[] (size_t idx) inline
Definition at line 1363 of file json.h.
{
        if (!is_array()) data = JsonArray{};
        // Handle regular JsonArray
        if (data.is<JsonArray>()) {
            auto ptr = data.ptr<JsonArray>();
            if (!ptr) return get_null_value(); // Handle error case
            auto &arr = *ptr;
            if (idx >= arr.size()) {
                // Resize array and fill with null values
                for (size_t i = arr.size(); i <= idx; i++) {
                    arr.push_back(fl::make_shared<JsonValue>());
                }
            }
            if (idx >= arr.size()) return get_null_value(); // Handle error case
            return *arr[idx];
        }
        // For packed arrays, we need to convert them to regular arrays first
        // This is needed for compatibility with existing code that expects JsonArray
        if (data.is<fl::vector<int16_t>>() ||
            data.is<fl::vector<uint8_t>>() ||
            data.is<fl::vector<float>>()) {
            // Convert to regular JsonArray
            auto arr = as_array();
            if (arr) {
                data = fl::move(*arr);
                auto ptr = data.ptr<JsonArray>();
                if (!ptr) return get_null_value();
                auto &jsonArr = *ptr;
                if (idx >= jsonArr.size()) {
                    // Resize array and fill with null values
                    for (size_t i = jsonArr.size(); i <= idx; i++) {
                        jsonArr.push_back(fl::make_shared<JsonValue>());
                    }
                }
                if (idx >= jsonArr.size()) return get_null_value();
                return *jsonArr[idx];
            }
        }
References JsonValue(), as_array(), data, fl::get_null_value(), is_array(), fl::make_shared(), and fl::move().