FastLED: fl::CRGB::nscale8
nscale8() [2/2]
CRGB & CRGB::nscale8 (fl::u8 scaledown)
Scale down a RGB to N/256ths of its current brightness, using "plain math" dimming rules.
"Plain math" dimming rules means that the low light levels may dim all the way to 100% black.
See also
nscale8x3
Definition at line 88 of file crgb.cpp.hpp.
{
    nscale8x3(r, g, b, scaledown);
    return *this;
}
References CRGB().
Referenced by fl::gfx::blur1d(), fl::gfx::blur2d(), fl::gfx::blurColumns(), fl::gfx::blurColumns(), fl::gfx::blurRows(), fl::gfx::blurRows(), draw(), fl::Particles1d::Particle::draw(), FL_DISABLE_WARNING(), loop(), nscale(), fl::PerlinParticlePunch::renderAmbient(), fl::PerlinParticlePunch::renderDebris(), and fl::PerlinParticlePunch::renderMeteor().