FastLED: fl::Particles1d::Particle::getPower
getPower()
float fl::Particles1d::Particle::getPower (u32 now) const
Returns
Power level from 1.0 (birth) to 0.0 (death)
Definition at line 90 of file particles.cpp.hpp.
{
    if (!active || !lifetime) return 0.0f;
    float power = 1.0f - (float)(now - birthTime) / lifetime;
    return fl::clamp(power, 0.0f, 1.0f);
}
References active, birthTime, fl::clamp(), and lifetime.
Referenced by draw(), and update().