FastLED: loop
loop()
void loop ()
Definition at line 109 of file FireCylinder.ino.
            {
    FastLED.setBrightness(brightness);
    CRGBPalette16 myPal = getPalette();
    uint32_t now = millis();
    timeScale.setSpeed(speedY);
    uint32_t y_speed = timeScale.update(now);
    for (int width = 0; width < WIDTH; width++) {
        for (int height = 0; height < HEIGHT; height++) {
            uint8_t palette_index =
                getPaletteIndex(now, width, WIDTH, height, HEIGHT, y_speed);
            CRGB c = ColorFromPalette(myPal, palette_index, BRIGHTNESS);
            int index = xyMap((WIDTH - 1) - width, (HEIGHT - 1) - height);
            leds[index] = c;
        }
    }
    FastLED.show();
}
References BRIGHTNESS, brightness, fl::ColorFromPalette(), FastLED, getPalette(), getPaletteIndex(), HEIGHT, leds, speedY, timeScale, WIDTH, xyMap, and y_speed.