FastLED: fl::TimeRamp::update8
update8()
uint8_t fl::TimeRamp::update8 (uint32_t now) override virtual
Compute current 0–255 output based on how much time has elapsed since trigger().
Implements fl::TimeAlpha.
Definition at line 83 of file time_alpha.cpp.
{
    if (!isActive(now)) {
        return 0;
    }
    // uint32_t elapsed = now - mStart;
    uint8_t out = 0;
    if (now < mFinishedRisingTime) {
        out = time_alpha8(now, mStart, mFinishedRisingTime);
    } else if (now < mFinishedPlateauTime) {
        // plateau
        out = 255;
    } else if (now < mFinishedFallingTime) {
        // ramp down
        uint8_t alpha =
            time_alpha8(now, mFinishedPlateauTime, mFinishedFallingTime);
        out = 255 - alpha;
    } else {
        // finished
        out = 0;
    }
    mLastValue = out;
    return out;
}
References isActive(), mFinishedFallingTime, mFinishedPlateauTime, mFinishedRisingTime, mLastValue, mStart, and fl::time_alpha8().
Referenced by applyFancyEffect().