FastLED: fl::anonymous_namespace{istream.cpp.hpp}::parse_i32
parse_i32()
bool fl::anonymous_namespace{istream.cpp.hpp}::parse_i32 (const char * str, fl::i32 & result)
Definition at line 24 of file istream.cpp.hpp.
{
        if (!str) return false;
        // Skip leading whitespace
        while (*str && isSpace(*str)) {
            str++;
        }
        if (*str == '\0') return false;
        bool negative = false;
        if (*str == '-') {
            negative = true;
            str++;
        } else if (*str == '+') {
            str++;
        }
        if (*str == '\0' || !isDigit(*str)) return false;
        fl::u32 value = 0;
        const fl::u32 max_div_10 = 214748364U; // INT32_MAX / 10
        const fl::u32 max_mod_10 = 7U;         // INT32_MAX % 10
        const fl::u32 max_neg_div_10 = 214748364U; // -INT32_MIN / 10
        const fl::u32 max_neg_mod_10 = 8U;         // -INT32_MIN % 10
        while (*str && isDigit(*str)) {
            fl::u32 digit = *str - '0';
            // Check for overflow
            if (negative) {
                if (value > max_neg_div_10 || (value == max_neg_div_10 && digit > max_neg_mod_10)) {
                    return false; // Overflow
                }
            } else {
                if (value > max_div_10 || (value == max_div_10 && digit > max_mod_10)) {
                    return false; // Overflow
                }
            }
            value = value * 10 + digit;
            str++;
        }
        // Check if we stopped at a non-digit character (should be end of string for valid parse)
        if (*str != '\0') return false;
        if (negative) {
            result = -static_cast<fl::i32>(value);
        } else {
            result = static_cast<fl::i32>(value);
        }
        return true;
    }
References isDigit(), isSpace(), parse_i32(), and fl::type_rank< T >::value.
Referenced by parse_i32().