FastLED: fl::fill_gradient_RGB
fill_gradient_RGB() [4/4]
void fl::fill_gradient_RGB (CRGB * leds, uint16_t startpos, CRGB startcolor, uint16_t endpos, CRGB endcolor)
Fill a range of LEDs with a smooth RGB gradient between two RGB colors.
Unlike HSV, there is no "color wheel" in RGB space, and therefore there's only one "direction" for the gradient to go. This means there's no TGradientDirectionCode parameter for direction.
Parameters
leds a pointer to the LED array to fill
startpos the starting position in the array
startcolor the starting color for the gradient
endpos the ending position in the array
endcolor the end color for the gradient
Definition at line 107 of file fill.cpp.
{
    // if the points are in the wrong order, straighten them
    if (endpos < startpos) {
        uint16_t t = endpos;
        CRGB tc = endcolor;
        endcolor = startcolor;
        endpos = startpos;
        startpos = t;
        startcolor = tc;
    }
    saccum87 rdistance87;
    saccum87 gdistance87;
    saccum87 bdistance87;
    rdistance87 = (endcolor.r - startcolor.r) << 7;
    gdistance87 = (endcolor.g - startcolor.g) << 7;
    bdistance87 = (endcolor.b - startcolor.b) << 7;
    uint16_t pixeldistance = endpos - startpos;
    int16_t divisor = pixeldistance ? pixeldistance : 1;
    saccum87 rdelta87 = rdistance87 / divisor;
    saccum87 gdelta87 = gdistance87 / divisor;
    saccum87 bdelta87 = bdistance87 / divisor;
    rdelta87 *= 2;
    gdelta87 *= 2;
    bdelta87 *= 2;
    accum88 r88 = startcolor.r << 8;
    accum88 g88 = startcolor.g << 8;
    accum88 b88 = startcolor.b << 8;
    for (uint16_t i = startpos; i <= endpos; ++i) {
        leds[i] = CRGB(r88 >> 8, g88 >> 8, b88 >> 8);
        r88 += rdelta87;
        g88 += gdelta87;
        b88 += bdelta87;
    }
}
References leds, and saccum87.
Referenced by fill_gradient_RGB(), fill_gradient_RGB(), and fill_gradient_RGB().