FastLED: fl::AsyncLogger::disableBackgroundFlush
disableBackgroundFlush()
void fl::AsyncLogger::disableBackgroundFlush ()
Disable background flushing.
Definition at line 184 of file async_logger.cpp.hpp.
{
    detail::BackgroundFlushState& state = Singleton<detail::BackgroundFlushState>::instance();
    if (state.mEnabled && state.mTimerHandle.is_valid()) {
        fl::isr::detach_handler(state.mTimerHandle);
        state.mTimerHandle = fl::isr::handle();  // Reset to default (invalid) handle
        state.mEnabled = false;
        state.mNeedsFlush = false;
    }
}
References fl::isr::detach_handler(), fl::Singleton< T, N >::instance(), and state.
Referenced by ~AsyncLogger(), and enableBackgroundFlush().