FastLED: fl::AsyncLogger::enableBackgroundFlush
enableBackgroundFlush()
bool fl::AsyncLogger::enableBackgroundFlush (fl::u32 interval_ms, fl::size messages_per_tick = 5)
Enable background timer-based flushing (opt-in)
Parameters
interval_ms Flush interval in milliseconds (e.g., 100 = 10 Hz)
messages_per_tick Maximum messages to flush per timer tick (default 5)
Returns
true if enabled successfully, false if platform doesn't support timers
Definition at line 156 of file async_logger.cpp.hpp.
{
    detail::BackgroundFlushState& state = Singleton<detail::BackgroundFlushState>::instance();
    // If already enabled, disable first
    if (state.mEnabled) {
        disableBackgroundFlush();
    }
    // Configure flush parameters
    state.mMessagesPerTick = messages_per_tick;
    // Setup ISR timer configuration
    fl::isr::config config;
    config.handler = detail::async_log_flush_timer_isr;
    config.user_data = &state;
    config.frequency_hz = 1000 / interval_ms;  // Convert ms to Hz
    config.priority = fl::isr::ISR_PRIORITY_LOW;  // Low priority to avoid interfering with LED timing
    config.flags = fl::isr::ISR_FLAG_IRAM_SAFE;
    // Attach timer ISR (returns 0 on success, negative on error)
    if (fl::isr::attach_timer_handler(config, &state.mTimerHandle) != 0) {
        return false;  // Platform doesn't support timers or attachment failed
    }
    state.mEnabled = true;
    return true;
}
References fl::detail::async_log_flush_timer_isr(), fl::isr::attach_timer_handler(), disableBackgroundFlush(), fl::isr::config::flags, fl::isr::config::frequency_hz, fl::isr::config::handler, fl::Singleton< T, N >::instance(), fl::isr::ISR_FLAG_IRAM_SAFE, fl::isr::ISR_PRIORITY_LOW, fl::isr::config::priority, state, and fl::isr::config::user_data.
Referenced by ~AsyncLogger().