FastLED: fl::audio::detector::ChordDetector::update
update()
void fl::audio::detector::ChordDetector::update (shared_ptr< Context > context) override virtual
Implements fl::audio::Detector.
Definition at line 61 of file chord.cpp.hpp.
{
    mRetainedFFT = context->getFFT(32);  // Higher resolution for pitch detection
    const fft::Bins& fft = *mRetainedFFT;
    u32 timestamp = context->getTimestamp();
    // Calculate chroma features
    calculateChroma(fft);
    // Detect current chord
    Chord detected = detectChord(mChroma, timestamp);
    // Check if chord changed
    if (detected.isValid() && detected.confidence >= mConfidenceThreshold) {
        if (!mCurrentChord.isValid() || !isSimilarChord(detected, mCurrentChord)) {
            // New chord detected
            if (mCurrentChord.isValid()) {
                mFireChordEnd = true;
            }
            mPreviousChord = mCurrentChord;
            mCurrentChord = detected;
            mChordStartTime = timestamp;
            mFireChordChange = true;
            FL_DBG("Chord detected: " << mCurrentChord.getRootName()
                   << mCurrentChord.getTypeName()
                   << " (conf: " << mCurrentChord.confidence << ")");
        } else {
            // Same chord, update confidence
            mCurrentChord.confidence = detected.confidence;
            mCurrentChord.timestamp = timestamp;
        }
        // Set flag for onChord callback every frame when chord is active
        mFireChord = true;
    } else {
        // No valid chord or low confidence
        if (mCurrentChord.isValid()) {
            u32 duration = timestamp - mChordStartTime;
            if (duration >= mMinChordDuration) {
                mChordEndTime = timestamp;
                mFireChordEnd = true;
            }
            mCurrentChord = Chord();  // Reset to invalid
        }
    }
    // Save chroma for next frame
    for (int i = 0; i < 12; i++) {
        mPrevChroma[i] = mChroma[i];
    }
}
References calculateChroma(), fl::audio::detector::Chord::confidence, detectChord(), FL_DBG, isSimilarChord(), fl::audio::detector::Chord::isValid(), mChordEndTime, mChordStartTime, mChroma, mConfidenceThreshold, mCurrentChord, mFireChord, mFireChordChange, mFireChordEnd, mMinChordDuration, mPrevChroma, mPreviousChord, and mRetainedFFT.
Referenced by ~ChordDetector().