FastLED: Interp
Interp()
template<typename KeyT, typename ValT> ValT Interp (const KeyT & k, const InterpData< KeyT, ValT > * array, const int n) inline
Definition at line 54 of file ApproximatingFunction.h.
{
  if (n < 1) {
    return ValT(0);
  }
  int low_idx = -1;
  int high_idx = -1;
  SelectInterpPoints<KeyT, ValT>(k, array, n, &low_idx, &high_idx);
  if (low_idx == high_idx) {
    return array[low_idx].val;
  }
  const InterpData<KeyT, ValT>* curr = &array[low_idx];
  const InterpData<KeyT, ValT>* next = &array[high_idx];
  // map(...) only works on integers. MapT<> is the same thing but it works on
  // all datatypes.
  return MapT<KeyT, ValT>(k, curr->key, next->key, curr->val, next->val);
}
References InterpData< KeyT, ValT >::key, MapT(), SelectInterpPoints(), and InterpData< KeyT, ValT >::val.
Referenced by AttackRemapFactor(), anonymous_namespace{Painter.cpp}::LuminanceDecay(), MapDecayTime(), and ToBrightness().