FastLED: inoise8_raw
inoise8_raw() [3/3]
fl::i8 inoise8_raw (fl::u16 x, fl::u16 y, fl::u16 z) extern
Parameters
z z-axis coordinate on noise map (3D)
Definition at line 534 of file noise.cpp.hpp.
{
    // Find the unit cube containing the point
    fl::u8 X = x>>8;
    fl::u8 Y = y>>8;
    fl::u8 Z = z>>8;
    // Hash cube corner coordinates
    fl::u8 A = NOISE_P(X)+Y;
    fl::u8 AA = NOISE_P(A)+Z;
    fl::u8 AB = NOISE_P(A+1)+Z;
    fl::u8 B = NOISE_P(X+1)+Y;
    fl::u8 BA = NOISE_P(B) + Z;
    fl::u8 BB = NOISE_P(B+1)+Z;
    // Get the relative position of the point in the cube
    fl::u8 u = x;
    fl::u8 v = y;
    fl::u8 w = z;
    // Get a signed version of the above for the grad function
    fl::i8 xx = ((fl::u8)(x)>>1) & 0x7F;
    fl::i8 yy = ((fl::u8)(y)>>1) & 0x7F;
    fl::i8 zz = ((fl::u8)(z)>>1) & 0x7F;
    fl::u8 N = 0x80;
    u = EASE8(u); v = EASE8(v); w = EASE8(w);
    fl::i8 X1 = lerp7by8(grad8(NOISE_P(AA), xx, yy, zz), grad8(NOISE_P(BA), xx - N, yy, zz), u);
    fl::i8 X2 = lerp7by8(grad8(NOISE_P(AB), xx, yy-N, zz), grad8(NOISE_P(BB), xx - N, yy - N, zz), u);
    fl::i8 X3 = lerp7by8(grad8(NOISE_P(AA+1), xx, yy, zz-N), grad8(NOISE_P(BA+1), xx - N, yy, zz-N), u);
    fl::i8 X4 = lerp7by8(grad8(NOISE_P(AB+1), xx, yy-N, zz-N), grad8(NOISE_P(BB+1), xx - N, yy - N, zz - N), u);
    fl::i8 Y1 = lerp7by8(X1,X2,v);
    fl::i8 Y2 = lerp7by8(X3,X4,v);
    fl::i8 ans = lerp7by8(Y1,Y2,w);
    return ans;
}
References grad8(), lerp7by8(), NOISE_P, x, y, and z.
Referenced by inoise8(), inoise8(), and inoise8().