FastLED: inoise8_raw
inoise8_raw() [3/3]
int8_t inoise8_raw (uint16_t x, uint16_t y, uint16_t z) extern
8-bit, fixed point implementation of Perlin's noise without scaling.
Coordinates are 8.8 fixed point values, 16-bit integers with integral coordinates in the high 8-bits and fractional in the low 8-bits.
Returns
unscaled noise value as a signed integer, roughly -70 to 70
Parameters
x x-axis coordinate on noise map (1D)
y y-axis coordinate on noise map (2D)
z z-axis coordinate on noise map (3D)
Definition at line 529 of file noise.cpp.
{
    // Find the unit cube containing the point
    uint8_t X = x>>8;
    uint8_t Y = y>>8;
    uint8_t Z = z>>8;
    // Hash cube corner coordinates
    uint8_t A = NOISE_P(X)+Y;
    uint8_t AA = NOISE_P(A)+Z;
    uint8_t AB = NOISE_P(A+1)+Z;
    uint8_t B = NOISE_P(X+1)+Y;
    uint8_t BA = NOISE_P(B) + Z;
    uint8_t BB = NOISE_P(B+1)+Z;
    // Get the relative position of the point in the cube
    uint8_t u = x;
    uint8_t v = y;
    uint8_t w = z;
    // Get a signed version of the above for the grad function
    int8_t xx = ((uint8_t)(x)>>1) & 0x7F;
    int8_t yy = ((uint8_t)(y)>>1) & 0x7F;
    int8_t zz = ((uint8_t)(z)>>1) & 0x7F;
    uint8_t N = 0x80;
    u = EASE8(u); v = EASE8(v); w = EASE8(w);
    int8_t X1 = lerp7by8(grad8(NOISE_P(AA), xx, yy, zz), grad8(NOISE_P(BA), xx - N, yy, zz), u);
    int8_t X2 = lerp7by8(grad8(NOISE_P(AB), xx, yy-N, zz), grad8(NOISE_P(BB), xx - N, yy - N, zz), u);
    int8_t X3 = lerp7by8(grad8(NOISE_P(AA+1), xx, yy, zz-N), grad8(NOISE_P(BA+1), xx - N, yy, zz-N), u);
    int8_t X4 = lerp7by8(grad8(NOISE_P(AB+1), xx, yy-N, zz-N), grad8(NOISE_P(BB+1), xx - N, yy - N, zz - N), u);
    int8_t Y1 = lerp7by8(X1,X2,v);
    int8_t Y2 = lerp7by8(X3,X4,v);
    int8_t ans = lerp7by8(Y1,Y2,w);
    return ans;
}
References grad8(), lerp7by8(), NOISE_P, x, y, and z.
Referenced by inoise8(), inoise8(), and inoise8().