FastLED: fl::ChannelData::writeWithPadding
writeWithPadding()
void fl::ChannelData::writeWithPadding (fl::span< u8 > dst)
Write encoded data with padding to destination buffer.
This method separates the concern of data preparation from memory format. It writes the encoded data with padding applied to a caller-provided span, allowing the caller to control the destination memory type (DRAM, DMA, etc.)
Parameters
dst Destination buffer to write to (size determines target padding size)
The destination buffer size must be >= current data size. If a padding generator is configured, it will be used to extend the data to fill the entire destination buffer.
Definition at line 62 of file data.cpp.hpp.
{
    size_t targetSize = dst.size();
    size_t currentSize = mEncodedData.size();
    // Destination must be at least as large as current data
    if (targetSize < currentSize) {
        return; // or throw? For now, silently fail
    }
    // Create source span from encoded data
    fl::span<const u8> src(mEncodedData.data(), currentSize);
    if (mPaddingGenerator) {
        // Use custom padding generator (writes directly to dst)
        mPaddingGenerator(src, dst);
    } else {
        // Default behavior: left-pad with zeros, then memcopy data
        // Padding bytes go out first to non-existent pixels
        size_t paddingSize = targetSize - currentSize;
        if (paddingSize > 0) {
            fl::fill(dst.begin(), dst.begin() + paddingSize, u8(0));
        }
        fl::memcopy(dst.data() + paddingSize, src.data(), currentSize);
    }
}
References fl::span< T, Extent >::data(), fl::fill(), FL_NOEXCEPT, fl::memcopy(), mEncodedData, and mPaddingGenerator.