FastLED: fl::VorbisDecoderImpl::begin
begin()
bool fl::VorbisDecoderImpl::begin (fl::filebuf_ptr stream)
Definition at line 139 of file vorbis.cpp.hpp.
{
    end();  // Clean up any previous state
    if (!stream) {
        mError = "Null stream";
        return false;
    }
    // stb_vorbis pulldata API requires entire file in memory
    // Read entire stream into buffer
    mFileData.clear();
    fl::u8 buffer[1024];
    while (stream->available(1)) {
        fl::size bytesRead = stream->read(buffer, sizeof(buffer));
        if (bytesRead == 0) break;
        for (fl::size i = 0; i < bytesRead; ++i) {
            mFileData.push_back(buffer[i]);
        }
    }
    if (mFileData.empty()) {
        mError = "Empty stream";
        return false;
    }
    // Open decoder
    if (!mDecoder.openMemory(mFileData)) {
        mError = "Failed to decode Vorbis stream";
        return false;
    }
    mEndOfStream = false;
    mError.clear();
    return true;
}
References fl::filebuf::available(), end(), mDecoder, mEndOfStream, mError, mFileData, and fl::filebuf::read().