FastLED: fl::audio::detector::EqualizerDetector::configure
configure()
void fl::audio::detector::EqualizerDetector::configure (const EqualizerConfig & config)
Reconfigure equalizer tuning parameters at runtime.
Definition at line 58 of file equalizer.cpp.hpp.
{
    mConfig = config;
    // Rebuild normalization filters
    mBinMaxFilters.clear();
    for (int i = 0; i < kNumBins; ++i) {
        mBinMaxFilters.push_back(AttackDecayFilter<float>(mConfig.normAttack, mConfig.normDecay, 0.0f));
    }
    mVolumeMax = AttackDecayFilter<float>(mConfig.normAttack, mConfig.normDecay, 0.0f);
    // Configure output smoothing: attack/decay or simple exponential
    mUseAttackDecaySmoothing = (mConfig.outputAttack > 0.0f && mConfig.outputDecay > 0.0f);
    mBinSmoothers.clear();
    mBinOutputFilters.clear();
    if (mUseAttackDecaySmoothing) {
        for (int i = 0; i < kNumBins; ++i) {
            mBinOutputFilters.push_back(
                AttackDecayFilter<float>(mConfig.outputAttack, mConfig.outputDecay, 0.0f));
        }
    } else {
        for (int i = 0; i < kNumBins; ++i) {
            mBinSmoothers.push_back(ExponentialSmoother<float>(mConfig.smoothing));
        }
    }
    // Configure spectral equalizer
    if (mConfig.curve != EqualizationCurve::Flat) {
        SpectralEqualizerConfig eqConfig;
        eqConfig.curve = mConfig.curve;
        eqConfig.numBands = kNumBins;
        mSpectralEq.configure(eqConfig);
    }
    // Recompute mic gains if a profile is set (handles freq range changes)
    if (mCurrentMicProfile != MicProfile::None) {
        setMicProfile(mCurrentMicProfile);
    }
    // Recompute pink noise gains (freq range may have changed)
    recomputePinkNoiseGains();
}
References EqualizerDetector(), configure(), fl::audio::SpectralEqualizerConfig::curve, fl::audio::Flat, kNumBins, mBinMaxFilters, mBinOutputFilters, mBinSmoothers, mConfig, mCurrentMicProfile, mSpectralEq, mUseAttackDecaySmoothing, mVolumeMax, fl::audio::None, fl::audio::SpectralEqualizerConfig::numBands, recomputePinkNoiseGains(), and setMicProfile().
Referenced by ~EqualizerDetector(), and configure().