FastLED: fl::audio::detector::EqualizerDetector::computeBinCenters
computeBinCenters()
void fl::audio::detector::EqualizerDetector::computeBinCenters (float * out) const private
Definition at line 114 of file equalizer.cpp.hpp.
{
    // Log-spaced bin centers matching Bins::binToFreq formula
    float fmin = mConfig.minFreq;
    float fmax = mConfig.maxFreq;
    if (fmax <= fmin) fmax = fmin * 2.0f;
    float m = fl::logf(fmax / fmin);
    for (int i = 0; i < kNumBins; ++i) {
        out[i] = fmin * fl::expf(m * static_cast<float>(i) / static_cast<float>(kNumBins - 1));
    }
}
References fl::expf(), kNumBins, fl::logf(), and mConfig.
Referenced by recomputePinkNoiseGains(), and setMicProfile().