FastLED: fl::audio::detector::EqualizerDetector::update
update()
void fl::audio::detector::EqualizerDetector::update (shared_ptr< Context > context) override virtual
Implements fl::audio::Detector.
Definition at line 131 of file equalizer.cpp.hpp.
{
    mSampleRate = context->getSampleRate();
    span<const i16> pcm = context->getPCM();
    if (pcm.size() == 0) return;
    const float dt = computeAudioDt(pcm.size(), mSampleRate);
    // Use Context's cached fft::FFT (shared across detector)
    mRetainedFFT = context->getFFT(kNumBins, mConfig.minFreq, mConfig.maxFreq);
    if (!mRetainedFFT) return;
    const fft::Bins& fftBins = *mRetainedFFT;
    const auto& raw = fftBins.raw();
    const int numBins = fl::min(static_cast<int>(raw.size()), kNumBins);
    float scaledBins[kNumBins] = {};
    // Fused loop: Steps 1-4 (Copy, mic correction, pink noise, gain, scaling)
    // Combined for better cache locality and reduced memory bandwidth
    const bool applyMicCorrection = mHasMicCorrection;
    const bool applyScalingMode = (mConfig.scalingMode != FFTScalingMode::None &&
                                    mConfig.scalingMode != FFTScalingMode::Linear);
    const bool applyGain = (mGain != 1.0f);
    for (int i = 0; i < numBins; ++i) {
        // Step 1: Copy raw and apply fft::FFT downscale
        float val = raw[i] * kFFTDownscale;
        // Step 2: Microphone correction
        if (applyMicCorrection) {
            val *= mMicGains[i];
        }
        // Step 2.5: Pink noise spectral tilt compensation
        val *= mPinkNoiseGains[i];
        // Step 3: Apply gain
        if (applyGain) {
            val *= mGain;
        }
        // Step 4: Apply fft::FFT scaling mode
        if (applyScalingMode) {
            val = applyScaling(val, mConfig.scalingMode);
        }
        scaledBins[i] = val;
    }
    // Step 5: Apply spectral equalization curve (if not flat)
    if (mConfig.curve != EqualizationCurve::Flat) {
        span<const float> inSpan(scaledBins, numBins);
        span<float> outSpan(mEqBuffer, numBins);
        mSpectralEq.apply(inSpan, outSpan);
        for (int i = 0; i < numBins; ++i) {
            scaledBins[i] = mEqBuffer[i];
        }
    }
    // Step 6: Smooth → track running max → normalize to 0.0-1.0
    for (int i = 0; i < numBins; ++i) {
        float smoothed;
        if (mUseAttackDecaySmoothing) {
            smoothed = mBinOutputFilters[i].update(scaledBins[i], dt);
        } else {
            smoothed = mBinSmoothers[i].update(scaledBins[i], dt);
        }
        float runningMax = mBinMaxFilters[i].update(smoothed, dt);
        if (runningMax < 0.001f) runningMax = 0.001f;
        mBins[i] = fl::min(1.0f, smoothed / runningMax);
    }
    // Zero any remaining bins
    for (int i = numBins; i < kNumBins; ++i) {
        mBins[i] = 0.0f;
    }
    // Bass = average of bins 0-3
    float bassSum = 0;
    for (int i = kBassStart; i <= kBassEnd; ++i) bassSum += mBins[i];
    mBass = bassSum / static_cast<float>(kBassEnd - kBassStart + 1);
    // Mid = average of bins 4-10
    float midSum = 0;
    for (int i = kMidStart; i <= kMidEnd; ++i) midSum += mBins[i];
    mMid = midSum / static_cast<float>(kMidEnd - kMidStart + 1);
    // Treble = average of bins 11-15
    float trebleSum = 0;
    for (int i = kTrebleStart; i <= kTrebleEnd; ++i) trebleSum += mBins[i];
    mTreble = trebleSum / static_cast<float>(kTrebleEnd - kTrebleStart + 1);
    // Volume = RMS of sample, normalized to 0.0-1.0
    float rms = context->getRMS();
    float volumeMax = mVolumeMax.update(rms, dt);
    if (volumeMax < 0.001f) volumeMax = 0.001f;
    mVolume = fl::min(1.0f, rms / volumeMax);
    // Volume normalization factor: 1/volumeMax tells the caller how much the
    // volume was scaled to reach 0-1 range. Higher = quieter input was amplified more.
    mVolumeNormFactor = (rms > 0.001f) ? (mVolume / rms) : 1.0f;
    // Silence detection: signal is silent when RMS is very low
    mIsSilence = (rms < mConfig.silenceThreshold);
    // Zero-crossing factor (already 0.0-1.0 from Sample)
    mZcf = context->getZCF();
    // P2: Dominant frequency detection from pre-normalization data (scaledBins).
    // Using scaledBins avoids the self-normalization bias where consistently
    // active bins always read as 1.0 regardless of actual magnitude.
    int peakBin = 0;
    float peakVal = 0.0f;
    float scaledSum = 0.0f;
    for (int i = 0; i < numBins; ++i) {
        scaledSum += scaledBins[i];
        if (scaledBins[i] > peakVal) {
            peakVal = scaledBins[i];
            peakBin = i;
        }
    }
    // Magnitude: peak relative to average across all bins (0-1 range).
    // Reflects how much the peak dominates the spectrum.
    float scaledAvg = (numBins > 0) ? (scaledSum / static_cast<float>(numBins)) : 0.0f;
    mDominantMagnitude = (scaledAvg > 0.001f)
        ? fl::min(1.0f, peakVal / (scaledAvg * static_cast<float>(numBins)))
        : 0.0f;
    mDominantFreqHz = fftBins.binToFreq(peakBin);
    // P2: Volume in dB referenced to full-scale i16 (32767.0)
    constexpr float kFullScale = 32767.0f;
    if (rms > mConfig.silenceThreshold) {
        mVolumeDb = 20.0f * fl::logf(rms / kFullScale) / fl::logf(10.0f);
        if (mVolumeDb < -100.0f) mVolumeDb = -100.0f;
    } else {
        mVolumeDb = -100.0f;
    }
}
References fl::audio::fft::Bins::binToFreq(), fl::audio::computeAudioDt(), fl::audio::Flat, kFFTDownscale, kNumBins, fl::audio::detector::Linear, fl::logf(), mBass, mBinMaxFilters, mBinOutputFilters, mBins, mBinSmoothers, mConfig, mDominantFreqHz, mDominantMagnitude, mEqBuffer, mGain, mHasMicCorrection, fl::min(), mIsSilence, mMicGains, mMid, mPinkNoiseGains, mRetainedFFT, mSampleRate, mSpectralEq, mTreble, mUseAttackDecaySmoothing, mVolume, mVolumeDb, mVolumeMax, mVolumeNormFactor, mZcf, fl::audio::detector::None, fl::audio::fft::Bins::raw(), rms(), and fl::span< T, Extent >::size().
Referenced by ~EqualizerDetector().