FastLED: fl::MultiSetTree::insert
insert() [1/4]
template<typename Key, typename Compare = less<Key>, typename Allocator = allocator<Key>> iterator fl::MultiSetTree< Key, Compare, Allocator >::insert (const value_type & value) inline
Definition at line 211 of file multi_set.h.
{
        ValueWithId vwid(value, mNextId++);
        auto result = mTree.insert(vwid);
        return iterator(result.first);
    }
Referenced by fl::MultiSetTree< Key, Compare, fl::allocator_slab< char > >::MultiSetTree(), fl::MultiSetTree< Key, Compare, fl::allocator_slab< char > >::insert(), and fl::MultiSetTree< Key, Compare, fl::allocator_slab< char > >::insert().