FastLED: fl::gfx::blur_detail::hpass_row
hpass_row()
template<int R, typename RGB_T, typename acc_t, bool ApplyAlpha, typename AlphaT> FL_ALWAYS_INLINE void fl::gfx::blur_detail::hpass_row (RGB_T * pad, RGB_T * out, int w, AlphaT alpha)
Definition at line 1063 of file blur.cpp.hpp.
{
#if defined(FL_IS_AVR)
    if (ApplyAlpha)
        apply_pass_alpha_1ch<R>(pad, out, w, 1, alpha);
    else
        apply_pass_1ch<R>(pad, out, w, 1);
#else
    // SIMD fast path: u8-channel (CRGB), no alpha on this pass.
    if (sizeof(typename RGB_T::fp) == 1 && !ApplyAlpha) {
        constexpr int S = (int)sizeof(RGB_T);
        const int nbytes = w * S;
        const u8 *pb = (const u8 *)pad;
        u8 *ob = (u8 *)out;
        simd_hconv_dispatch<R>::apply(
            pb, S, ob, nbytes, (u8 *)(pad + 2 * R + w), w);
    } else if (ApplyAlpha) {
        apply_pass_alpha<R, RGB_T, acc_t>(pad, out, w, 1, alpha);
    } else {
        apply_pass<R, RGB_T, acc_t>(pad, out, w, 1);
    }
#endif
}
References apply_pass(), and apply_pass_alpha().
Referenced by fl::gfx::blurGaussianImpl().