FastLED: fl::gfx::blur_detail Namespace Reference
fl::gfx::blur_detail Namespace Reference
Classes
struct interior_row
struct interior_row< 0, RGB_T, acc_t >
struct interior_row< 1, RGB_T, acc_t >
struct interior_row< 2, RGB_T, acc_t >
struct interior_row< 3, RGB_T, acc_t >
struct interior_row< 4, RGB_T, acc_t >
struct pixel_ops
struct pixel_ops< CRGB >
struct pixel_ops< CRGB16 >
struct simd_hconv_dispatch
struct simd_hconv_dispatch< 0 >
struct simd_hconv_dispatch< 1 >
struct simd_hconv_dispatch< 2 >
struct simd_hconv_dispatch< 3 >
struct simd_hconv_dispatch< 4 >
struct simd_vconv_dispatch
struct simd_vconv_dispatch< 0 >
struct simd_vconv_dispatch< 1 >
struct simd_vconv_dispatch< 2 >
struct simd_vconv_dispatch< 3 >
struct simd_vconv_dispatch< 4 >
struct vpass_pixel_kernel
struct vpass_pixel_kernel< 0, RGB_T, acc_t >
struct vpass_pixel_kernel< 1, RGB_T, acc_t >
struct vpass_pixel_kernel< 2, RGB_T, acc_t >
struct vpass_pixel_kernel< 3, RGB_T, acc_t >
struct vpass_pixel_kernel< 4, RGB_T, acc_t >
Functions
template<typename AlphaT>
constexpr AlphaT alpha_identity ()
template<>
constexpr alpha16 alpha_identity< alpha16 > ()
template<>
constexpr alpha8 alpha_identity< alpha8 > ()
template<int R, typename RGB_T, typename acc_t>
FL_NO_INLINE_IF_AVR static FL_OPTIMIZE_FUNCTION void apply_pass (const RGB_T *pad, RGB_T *out, int count, int stride)
template<int R, typename RGB_T, typename acc_t, typename AlphaT>
FL_NO_INLINE_IF_AVR static FL_OPTIMIZE_FUNCTION void apply_pass_alpha (const RGB_T *pad, RGB_T *out, int count, int stride, AlphaT alpha)
template<int hR, int vR, typename RGB_T>
static int compute_pad_size (int w, int h)
template<typename RGB_T>
static fl::span< RGB_T > get_padbuf (int minSize)
template<int R, typename RGB_T, typename acc_t, bool ApplyAlpha, typename AlphaT>
FL_ALWAYS_INLINE void hpass_row (RGB_T *pad, RGB_T *out, int w, AlphaT alpha)
static void simd_conv_121 (const u8 *FL_RESTRICT_PARAM a, const u8 *FL_RESTRICT_PARAM b, const u8 *FL_RESTRICT_PARAM c, u8 *FL_RESTRICT_PARAM out, int nbytes)
static void simd_conv_14641 (const u8 *p0, const u8 *p1, const u8 *p2, const u8 *p3, const u8 *p4, u8 *out, int nbytes)
static void simd_conv_r3 (const u8 *p0, const u8 *p1, const u8 *p2, const u8 *p3, const u8 *p4, const u8 *p5, const u8 *p6, u8 *out, int nbytes)
static void simd_conv_r4 (const u8 *p0, const u8 *p1, const u8 *p2, const u8 *p3, const u8 *p4, const u8 *p5, const u8 *p6, const u8 *p7, const u8 *p8, u8 *out, int nbytes)
template<int R, typename RGB_T, typename acc_t, bool ApplyAlpha, typename AlphaT>
static void vpass_full (RGB_T *pixels, int w, int h, RGB_T *scratch, AlphaT alpha)
template<int R, typename RGB_T, typename acc_t, bool ApplyAlpha, typename AlphaT>
static FL_OPTIMIZE_FUNCTION void vpass_rowmajor_impl (RGB_T *pixels, int w, int h, RGB_T *scratch, AlphaT alpha)
fl::gfx::blur_detail::pixel_ops
struct fl::gfx::blur_detail::pixel_ops
fl::gfx::blur_detail::simd_hconv_dispatch
struct fl::gfx::blur_detail::simd_hconv_dispatch
fl::gfx::blur_detail::simd_vconv_dispatch
struct fl::gfx::blur_detail::simd_vconv_dispatch
fl::gfx::blur_detail::vpass_pixel_kernel
struct fl::gfx::blur_detail::vpass_pixel_kernel
Function Documentation
alpha_identity()
template<typename AlphaT> AlphaT fl::gfx::blur_detail::alpha_identity () constexpr
Referenced by fl::gfx::blurGaussianImpl(), and fl::gfx::blurGaussianMappedImpl().
alpha_identity< alpha16 >()
template<> alpha16 fl::gfx::blur_detail::alpha_identity< alpha16 > () constexpr
Definition at line 290 of file blur.cpp.hpp.
{ return alpha16(65535); }
alpha_identity< alpha8 >()
template<> alpha8 fl::gfx::blur_detail::alpha_identity< alpha8 > () constexpr
Definition at line 289 of file blur.cpp.hpp.
{ return alpha8(255); }
apply_pass()
template<int R, typename RGB_T, typename acc_t> FL_NO_INLINE_IF_AVR static FL_OPTIMIZE_FUNCTION void fl::gfx::blur_detail::apply_pass (const RGB_T * pad, RGB_T * out, int count, int stride) static
Definition at line 563 of file blur.cpp.hpp.
{
    constexpr int shift = 2 * R;
    using P = pixel_ops<RGB_T>;
    for (int i = 0; i < count; ++i) {
        acc_t r, g, b;
        interior_row<R, RGB_T, acc_t>::apply(pad, R + i, r, g, b);
        *out = P::make(static_cast<acc_t>(r >> shift),
                       static_cast<acc_t>(g >> shift),
                       static_cast<acc_t>(b >> shift));
        out += stride;
    }
}
References fl::P().
Referenced by hpass_row().
apply_pass_alpha()
template<int R, typename RGB_T, typename acc_t, typename AlphaT> FL_NO_INLINE_IF_AVR static FL_OPTIMIZE_FUNCTION void fl::gfx::blur_detail::apply_pass_alpha (const RGB_T * pad, RGB_T * out, int count, int stride, AlphaT alpha) static
Definition at line 578 of file blur.cpp.hpp.
{
    constexpr int shift = 2 * R;
    using P = pixel_ops<RGB_T>;
    for (int i = 0; i < count; ++i) {
        acc_t r, g, b;
        interior_row<R, RGB_T, acc_t>::apply(pad, R + i, r, g, b);
        *out = P::make(static_cast<acc_t>(r >> shift),
                       static_cast<acc_t>(g >> shift),
                       static_cast<acc_t>(b >> shift), alpha);
        out += stride;
    }
}
References fl::P().
Referenced by hpass_row().
compute_pad_size()
template<int hR, int vR, typename RGB_T> static int fl::gfx::blur_detail::compute_pad_size (int w, int h) static
Definition at line 1049 of file blur.cpp.hpp.
{
    int hPad = 2 * hR + w;
#if defined(FL_IS_AVR)
    int vPad = 2 * vR + h;
#else
    int vPad = vR > 0 ? (vR + 2) * w : 0;
#endif
    return hPad > vPad ? hPad : vPad;
}
Referenced by fl::gfx::blurGaussianImpl(), and fl::gfx::blurGaussianMappedImpl().
get_padbuf()
template<typename RGB_T> static fl::span< RGB_T > fl::gfx::blur_detail::get_padbuf (int minSize) static
Definition at line 349 of file blur.cpp.hpp.
{
    fl::vector<RGB_T> &buf = SingletonThreadLocal<fl::vector<RGB_T>>::instance();
    if (static_cast<int>(buf.size()) < minSize) {
        buf.resize(minSize);
    }
    return buf;
}
References fl::vector< T >::resize(), and fl::vector_basic::size().
Referenced by fl::gfx::blurGaussianImpl(), and fl::gfx::blurGaussianMappedImpl().
hpass_row()
template<int R, typename RGB_T, typename acc_t, bool ApplyAlpha, typename AlphaT> FL_ALWAYS_INLINE void fl::gfx::blur_detail::hpass_row (RGB_T * pad, RGB_T * out, int w, AlphaT alpha)
Definition at line 1063 of file blur.cpp.hpp.
{
#if defined(FL_IS_AVR)
    if (ApplyAlpha)
        apply_pass_alpha_1ch<R>(pad, out, w, 1, alpha);
    else
        apply_pass_1ch<R>(pad, out, w, 1);
#else
    // SIMD fast path: u8-channel (CRGB), no alpha on this pass.
    if (sizeof(typename RGB_T::fp) == 1 && !ApplyAlpha) {
        constexpr int S = (int)sizeof(RGB_T);
        const int nbytes = w * S;
        const u8 *pb = (const u8 *)pad;
        u8 *ob = (u8 *)out;
        simd_hconv_dispatch<R>::apply(
            pb, S, ob, nbytes, (u8 *)(pad + 2 * R + w), w);
    } else if (ApplyAlpha) {
        apply_pass_alpha<R, RGB_T, acc_t>(pad, out, w, 1, alpha);
    } else {
        apply_pass<R, RGB_T, acc_t>(pad, out, w, 1);
    }
#endif
}
References apply_pass(), and apply_pass_alpha().
Referenced by fl::gfx::blurGaussianImpl().
simd_conv_121()
static void fl::gfx::blur_detail::simd_conv_121 (const u8 *FL_RESTRICT_PARAM a, const u8 *FL_RESTRICT_PARAM b, const u8 *FL_RESTRICT_PARAM c, u8 *FL_RESTRICT_PARAM out, int nbytes) static
Definition at line 605 of file blur.cpp.hpp.
{
    namespace fsimd = fl::simd; // ok bare using
    int i = 0;
    for (; i + 63 < nbytes; i += 64) {
        auto va0 = fsimd::load_u8_32(a+i), vb0 = fsimd::load_u8_32(b+i), vc0 = fsimd::load_u8_32(c+i);
        auto va1 = fsimd::load_u8_32(a+i+32), vb1 = fsimd::load_u8_32(b+i+32), vc1 = fsimd::load_u8_32(c+i+32);
        fsimd::store_u8_32(out+i, fsimd::avg_round_u8_32(fsimd::avg_round_u8_32(va0, vc0), vb0));
        fsimd::store_u8_32(out+i+32, fsimd::avg_round_u8_32(fsimd::avg_round_u8_32(va1, vc1), vb1));
    }
    for (; i + 31 < nbytes; i += 32) {
        auto va = fsimd::load_u8_32(a+i), vb = fsimd::load_u8_32(b+i), vc = fsimd::load_u8_32(c+i);
        fsimd::store_u8_32(out+i, fsimd::avg_round_u8_32(fsimd::avg_round_u8_32(va, vc), vb));
    }
    for (; i + 15 < nbytes; i += 16) {
        auto va = fsimd::load_u8_16(a+i), vb = fsimd::load_u8_16(b+i), vc = fsimd::load_u8_16(c+i);
        fsimd::store_u8_16(out+i, fsimd::avg_round_u8_16(fsimd::avg_round_u8_16(va, vc), vb));
    }
    for (; i < nbytes; ++i)
        out[i] = (u8)(((u16)a[i] + ((u16)b[i] << 1) + (u16)c[i]) >> 2);
}
References FL_RESTRICT_PARAM.
Referenced by fl::gfx::blur_detail::simd_hconv_dispatch< 1 >::apply(), and fl::gfx::blur_detail::simd_vconv_dispatch< 1 >::apply().
simd_conv_14641()
static void fl::gfx::blur_detail::simd_conv_14641 (const u8 * p0, const u8 * p1, const u8 * p2, const u8 * p3, const u8 * p4, u8 * out, int nbytes) static
Definition at line 633 of file blur.cpp.hpp.
{
    namespace fsimd = fl::simd; // ok bare using
    const auto w4w = fsimd::set1_u16_16(4), w6w = fsimd::set1_u16_16(6);
    const auto w4 = fsimd::set1_u16_8(4), w6 = fsimd::set1_u16_8(6);
    int i = 0;
    for (; i + 31 < nbytes; i += 32) {
        auto v0 = fsimd::load_u8_32(p0+i), v1 = fsimd::load_u8_32(p1+i);
        auto v2 = fsimd::load_u8_32(p2+i), v3 = fsimd::load_u8_32(p3+i), v4 = fsimd::load_u8_32(p4+i);
        auto s04 = fsimd::add_u16_16(fsimd::widen_lo_u8x32_to_u16(v0), fsimd::widen_lo_u8x32_to_u16(v4));
        auto s13 = fsimd::add_u16_16(fsimd::widen_lo_u8x32_to_u16(v1), fsimd::widen_lo_u8x32_to_u16(v3));
        auto lo = fsimd::add_u16_16(s04, fsimd::add_u16_16(fsimd::mullo_u16_16(s13, w4w), fsimd::mullo_u16_16(fsimd::widen_lo_u8x32_to_u16(v2), w6w)));
        lo = fsimd::srli_u16_16(lo, 4);
        auto s04h = fsimd::add_u16_16(fsimd::widen_hi_u8x32_to_u16(v0), fsimd::widen_hi_u8x32_to_u16(v4));
        auto s13h = fsimd::add_u16_16(fsimd::widen_hi_u8x32_to_u16(v1), fsimd::widen_hi_u8x32_to_u16(v3));
        auto hi = fsimd::add_u16_16(s04h, fsimd::add_u16_16(fsimd::mullo_u16_16(s13h, w4w), fsimd::mullo_u16_16(fsimd::widen_hi_u8x32_to_u16(v2), w6w)));
        hi = fsimd::srli_u16_16(hi, 4);
        fsimd::store_u8_32(out+i, fsimd::narrow_u16x16_to_u8(lo, hi));
    }
    for (; i + 15 < nbytes; i += 16) {
        auto v0 = fsimd::load_u8_16(p0+i), v1 = fsimd::load_u8_16(p1+i);
        auto v2 = fsimd::load_u8_16(p2+i), v3 = fsimd::load_u8_16(p3+i), v4 = fsimd::load_u8_16(p4+i);
        auto s04 = fsimd::add_u16_8(fsimd::widen_lo_u8_to_u16(v0), fsimd::widen_lo_u8_to_u16(v4));
        auto s13 = fsimd::add_u16_8(fsimd::widen_lo_u8_to_u16(v1), fsimd::widen_lo_u8_to_u16(v3));
        auto lo = fsimd::add_u16_8(s04, fsimd::add_u16_8(fsimd::mullo_u16_8(s13, w4), fsimd::mullo_u16_8(fsimd::widen_lo_u8_to_u16(v2), w6)));
        lo = fsimd::srli_u16_8(lo, 4);
        auto s04h = fsimd::add_u16_8(fsimd::widen_hi_u8_to_u16(v0), fsimd::widen_hi_u8_to_u16(v4));
        auto s13h = fsimd::add_u16_8(fsimd::widen_hi_u8_to_u16(v1), fsimd::widen_hi_u8_to_u16(v3));
        auto hi = fsimd::add_u16_8(s04h, fsimd::add_u16_8(fsimd::mullo_u16_8(s13h, w4), fsimd::mullo_u16_8(fsimd::widen_hi_u8_to_u16(v2), w6)));
        hi = fsimd::srli_u16_8(hi, 4);
        fsimd::store_u8_16(out+i, fsimd::narrow_u16_to_u8(lo, hi));
    }
    for (; i < nbytes; ++i) {
        u16 s04 = (u16)p0[i] + (u16)p4[i];
        u16 s13 = (u16)p1[i] + (u16)p3[i];
        out[i] = (u8)((s04 + s13 * 4 + (u16)p2[i] * 6) >> 4);
    }
}
Referenced by fl::gfx::blur_detail::simd_hconv_dispatch< 2 >::apply(), and fl::gfx::blur_detail::simd_vconv_dispatch< 2 >::apply().
simd_conv_r3()
static void fl::gfx::blur_detail::simd_conv_r3 (const u8 * p0, const u8 * p1, const u8 * p2, const u8 * p3, const u8 * p4, const u8 * p5, const u8 * p6, u8 * out, int nbytes) static
Definition at line 674 of file blur.cpp.hpp.
{
    namespace fsimd = fl::simd; // ok bare using
    const auto w6w = fsimd::set1_u16_16(6), w15w = fsimd::set1_u16_16(15), w20w = fsimd::set1_u16_16(20);
    const auto w6 = fsimd::set1_u16_8(6), w15 = fsimd::set1_u16_8(15), w20 = fsimd::set1_u16_8(20);
    int i = 0;
    for (; i + 31 < nbytes; i += 32) {
        auto v0 = fsimd::load_u8_32(p0+i), v1 = fsimd::load_u8_32(p1+i), v2 = fsimd::load_u8_32(p2+i);
        auto v3 = fsimd::load_u8_32(p3+i), v4 = fsimd::load_u8_32(p4+i), v5 = fsimd::load_u8_32(p5+i);
        auto v6v = fsimd::load_u8_32(p6+i);
        auto s06 = fsimd::add_u16_16(fsimd::widen_lo_u8x32_to_u16(v0), fsimd::widen_lo_u8x32_to_u16(v6v));
        auto s15 = fsimd::add_u16_16(fsimd::widen_lo_u8x32_to_u16(v1), fsimd::widen_lo_u8x32_to_u16(v5));
        auto s24 = fsimd::add_u16_16(fsimd::widen_lo_u8x32_to_u16(v2), fsimd::widen_lo_u8x32_to_u16(v4));
        auto lo = fsimd::add_u16_16(s06, fsimd::add_u16_16(fsimd::mullo_u16_16(s15, w6w),
                   fsimd::add_u16_16(fsimd::mullo_u16_16(s24, w15w), fsimd::mullo_u16_16(fsimd::widen_lo_u8x32_to_u16(v3), w20w))));
        lo = fsimd::srli_u16_16(lo, 6);
        auto s06h = fsimd::add_u16_16(fsimd::widen_hi_u8x32_to_u16(v0), fsimd::widen_hi_u8x32_to_u16(v6v));
        auto s15h = fsimd::add_u16_16(fsimd::widen_hi_u8x32_to_u16(v1), fsimd::widen_hi_u8x32_to_u16(v5));
        auto s24h = fsimd::add_u16_16(fsimd::widen_hi_u8x32_to_u16(v2), fsimd::widen_hi_u8x32_to_u16(v4));
        auto hi = fsimd::add_u16_16(s06h, fsimd::add_u16_16(fsimd::mullo_u16_16(s15h, w6w),
                   fsimd::add_u16_16(fsimd::mullo_u16_16(s24h, w15w), fsimd::mullo_u16_16(fsimd::widen_hi_u8x32_to_u16(v3), w20w))));
        hi = fsimd::srli_u16_16(hi, 6);
        fsimd::store_u8_32(out+i, fsimd::narrow_u16x16_to_u8(lo, hi));
    }
    for (; i + 15 < nbytes; i += 16) {
        auto v0 = fsimd::load_u8_16(p0+i), v1 = fsimd::load_u8_16(p1+i), v2 = fsimd::load_u8_16(p2+i);
        auto v3 = fsimd::load_u8_16(p3+i), v4 = fsimd::load_u8_16(p4+i), v5 = fsimd::load_u8_16(p5+i);
        auto v6v = fsimd::load_u8_16(p6+i);
        auto s06 = fsimd::add_u16_8(fsimd::widen_lo_u8_to_u16(v0), fsimd::widen_lo_u8_to_u16(v6v));
        auto s15 = fsimd::add_u16_8(fsimd::widen_lo_u8_to_u16(v1), fsimd::widen_lo_u8_to_u16(v5));
        auto s24 = fsimd::add_u16_8(fsimd::widen_lo_u8_to_u16(v2), fsimd::widen_lo_u8_to_u16(v4));
        auto lo = fsimd::add_u16_8(s06, fsimd::add_u16_8(fsimd::mullo_u16_8(s15, w6),
                   fsimd::add_u16_8(fsimd::mullo_u16_8(s24, w15), fsimd::mullo_u16_8(fsimd::widen_lo_u8_to_u16(v3), w20))));
        lo = fsimd::srli_u16_8(lo, 6);
        auto s06h = fsimd::add_u16_8(fsimd::widen_hi_u8_to_u16(v0), fsimd::widen_hi_u8_to_u16(v6v));
        auto s15h = fsimd::add_u16_8(fsimd::widen_hi_u8_to_u16(v1), fsimd::widen_hi_u8_to_u16(v5));
        auto s24h = fsimd::add_u16_8(fsimd::widen_hi_u8_to_u16(v2), fsimd::widen_hi_u8_to_u16(v4));
        auto hi = fsimd::add_u16_8(s06h, fsimd::add_u16_8(fsimd::mullo_u16_8(s15h, w6),
                   fsimd::add_u16_8(fsimd::mullo_u16_8(s24h, w15), fsimd::mullo_u16_8(fsimd::widen_hi_u8_to_u16(v3), w20))));
        hi = fsimd::srli_u16_8(hi, 6);
        fsimd::store_u8_16(out+i, fsimd::narrow_u16_to_u8(lo, hi));
    }
    for (; i < nbytes; ++i) {
        u16 s06=(u16)p0[i]+(u16)p6[i], s15=(u16)p1[i]+(u16)p5[i], s24=(u16)p2[i]+(u16)p4[i];
        out[i]=(u8)((s06+s15*6+s24*15+(u16)p3[i]*20)>>6);
    }
}
Referenced by fl::gfx::blur_detail::simd_hconv_dispatch< 3 >::apply(), and fl::gfx::blur_detail::simd_vconv_dispatch< 3 >::apply().
simd_conv_r4()
static void fl::gfx::blur_detail::simd_conv_r4 (const u8 * p0, const u8 * p1, const u8 * p2, const u8 * p3, const u8 * p4, const u8 * p5, const u8 * p6, const u8 * p7, const u8 * p8, u8 * out, int nbytes) static
Definition at line 724 of file blur.cpp.hpp.
{
    namespace fsimd = fl::simd; // ok bare using
    const auto w8w = fsimd::set1_u16_16(8), w28w = fsimd::set1_u16_16(28);
    const auto w56w = fsimd::set1_u16_16(56), w70w = fsimd::set1_u16_16(70);
    const auto w8 = fsimd::set1_u16_8(8), w28 = fsimd::set1_u16_8(28);
    const auto w56 = fsimd::set1_u16_8(56), w70 = fsimd::set1_u16_8(70);
    int i = 0;
    for (; i + 31 < nbytes; i += 32) {
        auto v0 = fsimd::load_u8_32(p0+i), v1 = fsimd::load_u8_32(p1+i), v2 = fsimd::load_u8_32(p2+i);
        auto v3 = fsimd::load_u8_32(p3+i), v4 = fsimd::load_u8_32(p4+i), v5 = fsimd::load_u8_32(p5+i);
        auto v6v = fsimd::load_u8_32(p6+i), v7 = fsimd::load_u8_32(p7+i), v8v = fsimd::load_u8_32(p8+i);
        auto s08 = fsimd::add_u16_16(fsimd::widen_lo_u8x32_to_u16(v0), fsimd::widen_lo_u8x32_to_u16(v8v));
        auto s17 = fsimd::add_u16_16(fsimd::widen_lo_u8x32_to_u16(v1), fsimd::widen_lo_u8x32_to_u16(v7));
        auto s26 = fsimd::add_u16_16(fsimd::widen_lo_u8x32_to_u16(v2), fsimd::widen_lo_u8x32_to_u16(v6v));
        auto s35 = fsimd::add_u16_16(fsimd::widen_lo_u8x32_to_u16(v3), fsimd::widen_lo_u8x32_to_u16(v5));
        auto lo = fsimd::add_u16_16(s08, fsimd::add_u16_16(fsimd::mullo_u16_16(s17, w8w),
                   fsimd::add_u16_16(fsimd::mullo_u16_16(s26, w28w),
                   fsimd::add_u16_16(fsimd::mullo_u16_16(s35, w56w), fsimd::mullo_u16_16(fsimd::widen_lo_u8x32_to_u16(v4), w70w)))));
        lo = fsimd::srli_u16_16(lo, 8);
        auto s08h = fsimd::add_u16_16(fsimd::widen_hi_u8x32_to_u16(v0), fsimd::widen_hi_u8x32_to_u16(v8v));
        auto s17h = fsimd::add_u16_16(fsimd::widen_hi_u8x32_to_u16(v1), fsimd::widen_hi_u8x32_to_u16(v7));
        auto s26h = fsimd::add_u16_16(fsimd::widen_hi_u8x32_to_u16(v2), fsimd::widen_hi_u8x32_to_u16(v6v));
        auto s35h = fsimd::add_u16_16(fsimd::widen_hi_u8x32_to_u16(v3), fsimd::widen_hi_u8x32_to_u16(v5));
        auto hi = fsimd::add_u16_16(s08h, fsimd::add_u16_16(fsimd::mullo_u16_16(s17h, w8w),
                   fsimd::add_u16_16(fsimd::mullo_u16_16(s26h, w28w),
                   fsimd::add_u16_16(fsimd::mullo_u16_16(s35h, w56w), fsimd::mullo_u16_16(fsimd::widen_hi_u8x32_to_u16(v4), w70w)))));
        hi = fsimd::srli_u16_16(hi, 8);
        fsimd::store_u8_32(out+i, fsimd::narrow_u16x16_to_u8(lo, hi));
    }
    for (; i + 15 < nbytes; i += 16) {
        auto v0 = fsimd::load_u8_16(p0+i), v1 = fsimd::load_u8_16(p1+i), v2 = fsimd::load_u8_16(p2+i);
        auto v3 = fsimd::load_u8_16(p3+i), v4 = fsimd::load_u8_16(p4+i), v5 = fsimd::load_u8_16(p5+i);
        auto v6v = fsimd::load_u8_16(p6+i), v7 = fsimd::load_u8_16(p7+i), v8v = fsimd::load_u8_16(p8+i);
        auto s08 = fsimd::add_u16_8(fsimd::widen_lo_u8_to_u16(v0), fsimd::widen_lo_u8_to_u16(v8v));
        auto s17 = fsimd::add_u16_8(fsimd::widen_lo_u8_to_u16(v1), fsimd::widen_lo_u8_to_u16(v7));
        auto s26 = fsimd::add_u16_8(fsimd::widen_lo_u8_to_u16(v2), fsimd::widen_lo_u8_to_u16(v6v));
        auto s35 = fsimd::add_u16_8(fsimd::widen_lo_u8_to_u16(v3), fsimd::widen_lo_u8_to_u16(v5));
        auto lo = fsimd::add_u16_8(s08, fsimd::add_u16_8(fsimd::mullo_u16_8(s17, w8),
                   fsimd::add_u16_8(fsimd::mullo_u16_8(s26, w28),
                   fsimd::add_u16_8(fsimd::mullo_u16_8(s35, w56), fsimd::mullo_u16_8(fsimd::widen_lo_u8_to_u16(v4), w70)))));
        lo = fsimd::srli_u16_8(lo, 8);
        auto s08h = fsimd::add_u16_8(fsimd::widen_hi_u8_to_u16(v0), fsimd::widen_hi_u8_to_u16(v8v));
        auto s17h = fsimd::add_u16_8(fsimd::widen_hi_u8_to_u16(v1), fsimd::widen_hi_u8_to_u16(v7));
        auto s26h = fsimd::add_u16_8(fsimd::widen_hi_u8_to_u16(v2), fsimd::widen_hi_u8_to_u16(v6v));
        auto s35h = fsimd::add_u16_8(fsimd::widen_hi_u8_to_u16(v3), fsimd::widen_hi_u8_to_u16(v5));
        auto hi = fsimd::add_u16_8(s08h, fsimd::add_u16_8(fsimd::mullo_u16_8(s17h, w8),
                   fsimd::add_u16_8(fsimd::mullo_u16_8(s26h, w28),
                   fsimd::add_u16_8(fsimd::mullo_u16_8(s35h, w56), fsimd::mullo_u16_8(fsimd::widen_hi_u8_to_u16(v4), w70)))));
        hi = fsimd::srli_u16_8(hi, 8);
        fsimd::store_u8_16(out+i, fsimd::narrow_u16_to_u8(lo, hi));
    }
    for (; i < nbytes; ++i) {
        u16 s08=(u16)p0[i]+(u16)p8[i], s17=(u16)p1[i]+(u16)p7[i];
        u16 s26=(u16)p2[i]+(u16)p6[i], s35=(u16)p3[i]+(u16)p5[i];
        out[i]=(u8)((s08+s17*8+s26*28+s35*56+(u16)p4[i]*70)>>8);
    }
}
Referenced by fl::gfx::blur_detail::simd_hconv_dispatch< 4 >::apply(), and fl::gfx::blur_detail::simd_vconv_dispatch< 4 >::apply().
vpass_full()
template<int R, typename RGB_T, typename acc_t, bool ApplyAlpha, typename AlphaT> static void fl::gfx::blur_detail::vpass_full (RGB_T * pixels, int w, int h, RGB_T * scratch, AlphaT alpha) static
Definition at line 1088 of file blur.cpp.hpp.
{
#if defined(FL_IS_AVR)
    // AVR: column-by-column with per-channel noinline + O3.
    FL_BUILTIN_MEMSET(scratch, 0, R * sizeof(RGB_T));
    FL_BUILTIN_MEMSET(scratch + R + h, 0, R * sizeof(RGB_T));
    for (int x = 0; x < w; ++x) {
        // Linearize column into padded region.
        {
            const RGB_T *src = pixels + x;
            RGB_T *dst = scratch + R;
            for (int i = 0; i < h; ++i) {
                *dst++ = *src;
                src += w;
            }
        }
        if (ApplyAlpha)
            apply_pass_alpha_1ch<R>(scratch, pixels + x, h, w, alpha);
        else
            apply_pass_1ch<R>(scratch, pixels + x, h, w);
    }
#else
    // Non-AVR: row-major vertical pass for cache efficiency.
    // Direct R=2 V-pass using exact [1,4,6,4,1] kernel (no cascaded R=1).
    if (ApplyAlpha) {
        vpass_rowmajor_impl<R, RGB_T, acc_t, true>(
            pixels, w, h, scratch, alpha);
    } else {
        vpass_rowmajor_impl<R, RGB_T, acc_t, false>(
            pixels, w, h, scratch, alpha);
    }
#endif
}
References FL_BUILTIN_MEMSET, vpass_rowmajor_impl(), and fl::x.
Referenced by fl::gfx::blurGaussianImpl().
vpass_rowmajor_impl()
template<int R, typename RGB_T, typename acc_t, bool ApplyAlpha, typename AlphaT> static FL_OPTIMIZE_FUNCTION void fl::gfx::blur_detail::vpass_rowmajor_impl (RGB_T * pixels, int w, int h, RGB_T * scratch, AlphaT alpha) static
Definition at line 967 of file blur.cpp.hpp.
{
    constexpr int shift = 2 * R;
    using P = pixel_ops<RGB_T>;
    // Ring buffer: bufs[0..R-1] = saved previous rows, bufs[R] = save slot.
    // Extra zero_row for bottom-boundary padding.
    RGB_T *bufs[5] = {nullptr, nullptr, nullptr, nullptr, nullptr};
    for (int i = 0; i <= R; ++i)
        bufs[i] = scratch + i * w;
    RGB_T *zero_row = scratch + (R + 1) * w;
    // Zero all: first R buffers (top-boundary padding) + zero_row.
    FL_BUILTIN_MEMSET(scratch, 0, (R + 2) * w * sizeof(RGB_T));
    for (int y = 0; y < h; ++y) {
        RGB_T *out_row = pixels + y * w;
        // Save current row before we overwrite it.
        FL_BUILTIN_MEMCPY(bufs[R], out_row, w * sizeof(RGB_T));
        // Forward row pointers (rows y+1 .. y+R, or zero_row if OOB).
        const RGB_T *fwd[4] = {zero_row, zero_row, zero_row, zero_row};
        for (int k = 0; k < R; ++k)
            fwd[k] = (y + 1 + k < h) ? (pixels + (y + 1 + k) * w) : zero_row;
        // Prefetch the furthest-ahead row needed by the NEXT iteration.
        // At row y, next iteration needs fwd[R-1] = row y+1+R.
        // Prefetching 2 rows ahead gives the memory subsystem time to fetch.
        {
            const int prefetch_y = y + R + 2;
            if (prefetch_y < h) {
                const char *pf = (const char *)(pixels + prefetch_y * w);
                const int row_bytes = w * (int)sizeof(RGB_T);
                for (int off = 0; off < row_bytes; off += 64)
                    __builtin_prefetch(pf + off, 0, 3);
            }
        }
        // Process all pixels in this output row.
        // For u8-channel types (CRGB), process as raw byte stream — all
        // channels use the same kernel weights, so we treat the row as a
        // flat u8 array of w*sizeof(RGB_T) bytes. This produces a simpler
        // loop that the compiler can optimize better at low -O levels.
        if (sizeof(typename RGB_T::fp) == 1 && !ApplyAlpha) {
            // Raw byte fast path (CRGB without alpha).
            const int nbytes = w * (int)sizeof(RGB_T);
            u8 *ob = (u8 *)out_row;
            simd_vconv_dispatch<R>::apply(bufs, fwd, ob, nbytes);
        } else {
            // Generic path: per-pixel struct access (CRGB16 or alpha case).
            for (int x = 0; x < w; ++x) {
                acc_t r, g, b;
                vpass_pixel_kernel<R, RGB_T, acc_t>::apply(bufs, fwd, x, r, g, b);
                if (ApplyAlpha) {
                    out_row[x] = P::make(static_cast<acc_t>(r >> shift),
                                         static_cast<acc_t>(g >> shift),
                                         static_cast<acc_t>(b >> shift), alpha);
                } else {
                    out_row[x] = P::make(static_cast<acc_t>(r >> shift),
                                         static_cast<acc_t>(g >> shift),
                                         static_cast<acc_t>(b >> shift));
                }
            }
        }
        // Rotate ring buffer: discard oldest, current becomes newest saved.
        RGB_T *recycled = bufs[0];
        for (int i = 0; i < R; ++i) bufs[i] = bufs[i + 1];
        bufs[R] = recycled;
    }
}
References FL_BUILTIN_MEMCPY, FL_BUILTIN_MEMSET, fl::P(), fl::x, and fl::y.
Referenced by vpass_full().