FastLED: fl::H264::parseH264Info
parseH264Info()
H264Info fl::H264::parseH264Info (fl::span< const fl::u8 > mp4Data, fl::string * error_message = nullptr) static
Definition at line 196 of file h264.cpp.hpp.
{
    H264Info info;
    Mp4TrackInfo track = parseMp4(mp4Data, error_message);
    if (!track.isValid) return info;
    // Use dimensions from avc1 box
    info.width = track.width;
    info.height = track.height;
    info.profile = track.profile;
    info.level = track.level;
    // Parse SPS for more detailed info if available
    if (!track.sps.empty()) {
        fl::string spsError;
        H264Info spsInfo = parseSPS(track.sps[0], &spsError);
        if (spsInfo.isValid) {
            // SPS-parsed dimensions are more authoritative
            info.width = spsInfo.width;
            info.height = spsInfo.height;
            info.profile = spsInfo.profile;
            info.level = spsInfo.level;
            info.numRefFrames = spsInfo.numRefFrames;
        }
    }
    info.isValid = true;
    return info;
}
References fl::vector_basic::empty(), fl::H264Info::height, fl::Mp4TrackInfo::height, fl::H264Info::isValid, fl::Mp4TrackInfo::isValid, fl::H264Info::level, fl::Mp4TrackInfo::level, fl::H264Info::numRefFrames, fl::parseMp4(), parseSPS(), fl::H264Info::profile, fl::Mp4TrackInfo::profile, fl::Mp4TrackInfo::sps, fl::H264Info::width, and fl::Mp4TrackInfo::width.
Referenced by AutoResearchRemoteControl::registerFunctions().