FastLED: MidiInterface::sendCommon
sendCommon()
template<class Transport, class Settings, class Platform> void MidiInterface< Transport, Settings, Platform >::sendCommon (MidiType inType, unsigned inData1 = 0) inline
Send a Common message. Common messages reset the running status.
Parameters
inType The available Common types are: TimeCodeQuarterFrame, SongPosition, SongSelect and TuneRequest.
See also
MidiType
Parameters
inData1 The byte that goes with the common message.
Definition at line 443 of file MIDI.hpp.
{
    switch (inType)
    {
        case TimeCodeQuarterFrame:
        case SongPosition:
        case SongSelect:
        case TuneRequest:
            break;
        default:
            // Invalid Common marker
            return;
    }
    if (mTransport.beginTransmission(inType))
    {
            mTransport.write((byte)inType);
            switch (inType)
            {
            case TimeCodeQuarterFrame:
                mTransport.write(inData1);
                break;
            case SongPosition:
                mTransport.write(inData1 & 0x7f);
                mTransport.write((inData1 >> 7) & 0x7f);
                break;
            case SongSelect:
                mTransport.write(inData1 & 0x7f);
                break;
            case TuneRequest:
                break;
            default:
                break; // LCOV_EXCL_LINE - Coverage blind spot
        }
        mTransport.endTransmission();
        UpdateLastSentTime();
    }
    if (Settings::UseRunningStatus)
        mRunningStatus_TX = InvalidType;
}
References InvalidType, mRunningStatus_TX, mTransport, SongPosition, SongSelect, TimeCodeQuarterFrame, TuneRequest, and UpdateLastSentTime().
Referenced by sendSongPosition(), sendSongSelect(), sendTimeCodeQuarterFrame(), and sendTuneRequest().