FastLED: MidiInterface::send
send() [2/2]
template<class Transport, class Settings, class Platform> void MidiInterface< Transport, Settings, Platform >::send (MidiType inType, DataByte inData1, DataByte inData2, Channel inChannel)
Generate and send a MIDI message from the values given.
Parameters
inType The message type (see type defines for reference)
inData1 The first data byte.
inData2 The second data byte (if the message contains only 1 data byte, set this one to 0).
inChannel The output channel on which the message will be sent (values from 1 to 16). Note: you cannot send to OMNI.
This is an internal method, use it only if you need to send raw data from your code, at your own risks.
Definition at line 160 of file MIDI.hpp.
{
    if (inType <= PitchBend)  // Channel messages
    {
        // Then test if channel is valid
        if (inChannel >= MIDI_CHANNEL_OFF  ||
            inChannel == MIDI_CHANNEL_OMNI ||
            inType < 0x80)
        {
            return; // Don't send anything
        }
        // Protection: remove MSBs on data
        inData1 &= 0x7f;
        inData2 &= 0x7f;
        const StatusByte status = getStatus(inType, inChannel);
        if (mTransport.beginTransmission(inType))
        {
            if (Settings::UseRunningStatus)
            {
                if (mRunningStatus_TX != status)
                {
                    // New message, memorise and send header
                    mRunningStatus_TX = status;
                    mTransport.write(mRunningStatus_TX);
                }
            }
            else
            {
                // Don't care about running status, send the status byte.
                mTransport.write(status);
            }
            // Then send data
            mTransport.write(inData1);
            if (inType != ProgramChange && inType != AfterTouchChannel)
            {
                mTransport.write(inData2);
            }
            mTransport.endTransmission();
            UpdateLastSentTime();
        }
    }
    else if (inType >= Clock && inType <= SystemReset)
    {
        sendRealTime(inType); // System Real-time and 1 byte.
    }
}
References AfterTouchChannel, Clock, getStatus(), MIDI_CHANNEL_OFF, MIDI_CHANNEL_OMNI, mRunningStatus_TX, mTransport, PitchBend, ProgramChange, sendRealTime(), SystemReset, and UpdateLastSentTime().