FastLED: MidiInterface::send
send() [1/2]
template<class Transport, class Settings, class Platform> void MidiInterface< Transport, Settings, Platform >::send (const MidiMessage & inMessage) inline
Send a MIDI message.
Parameters
inMessage The message
This method is used when you want to send a Message that has not been constructed by the library, but by an external source. This method does not check against any of the constraints. Typically this function is use by MIDI Bridges taking MIDI messages and passing them thru.
Definition at line 118 of file MIDI.hpp.
{
    if (!inMessage.valid)
        return;
    if (mTransport.beginTransmission(inMessage.type))
    {
        const StatusByte status = getStatus(inMessage.type, inMessage.channel);
        mTransport.write(status);
        if (inMessage.type != MidiType::SystemExclusive)
        {
            if (inMessage.length > 1) mTransport.write(inMessage.data1);
            if (inMessage.length > 2) mTransport.write(inMessage.data2);
        } else
        {
            // sysexArray does not contain the start and end tags
            mTransport.write(MidiType::SystemExclusiveStart);
            for (size_t i = 0; i < inMessage.getSysExSize(); i++)
                mTransport.write(inMessage.sysexArray[i]);
            mTransport.write(MidiType::SystemExclusiveEnd);
        }
    }
    mTransport.endTransmission();
    UpdateLastSentTime();
}
References Message< SysExMaxSize >::channel, Message< SysExMaxSize >::data1, Message< SysExMaxSize >::data2, getStatus(), Message< SysExMaxSize >::getSysExSize(), Message< SysExMaxSize >::length, mTransport, Message< SysExMaxSize >::sysexArray, SystemExclusive, SystemExclusiveEnd, SystemExclusiveStart, Message< SysExMaxSize >::type, UpdateLastSentTime(), and Message< SysExMaxSize >::valid.
Referenced by sendAfterTouch(), sendAfterTouch(), sendControlChange(), sendNoteOff(), sendNoteOn(), sendPitchBend(), sendPolyPressure(), sendProgramChange(), and thruFilter().