FastLED: fl::Module_Experiment2_FP::draw
draw()
void fl::Module_Experiment2_FP::draw (Context & ctx) override virtual
Implements fl::IAnimartrix2Viz.
Definition at line 55 of file module_experiment2.cpp.hpp.
{
    using FP = fl::s16x16;
    auto *e = ctx.mEngine.get();
    e->get_ready();
    mState.ensureCache(e);
    const fl::i32 *fade_lut = fl::assume_aligned<16>(mState.fade_lut);
    const fl::u8 *perm = PERLIN_NOISE;
    e->timings.master_speed = 0.02;
    e->timings.ratio[0] = 0.0025;
    e->timings.ratio[1] = 0.0027;
    e->timings.ratio[2] = 0.029;
    e->timings.ratio[3] = 0.033;
    e->calculate_oscillators(e->timings);
    const int total_pixels = mState.count;
    // Per-frame constants converted to s16x16 raw once
    constexpr fl::i32 FP_ONE = static_cast<fl::i32>(1) << FP::FRAC_BITS;
    constexpr fl::i32 scale_xy_raw = FP(0.1f).raw();
    const fl::i32 cx_raw = FP(e->animation.center_x).raw();
    const fl::i32 cy_raw = FP(e->animation.center_y).raw();
    // dist = distance[x][y] - (16 + directional[0] * 16)
    // The subtracted term is per-frame constant
    const fl::i32 dist_offset_raw = FP(16.0f + e->move.directional[0] * 16.0f).raw();
    // angle = noise_angle[0] + noise_angle[1] + polar_theta[x][y]
    // The first two are per-frame constants
    const fl::i32 angle_offset_raw = FP(e->move.noise_angle[0] + e->move.noise_angle[1]).raw();
    render_parameters_fp p = {};
    p.scale_x_raw = scale_xy_raw;
    p.scale_y_raw = scale_xy_raw;
    p.scale_z_raw = 0; // scale_z not set in float version (default 0)
    p.offset_x_raw = FP(10.0f).raw();
    p.offset_y_raw = FP(20.0f * e->move.linear[2]).raw();
    p.offset_z_raw = FP(-10.0f).raw();
    p.z_raw = FP(5.0f).raw();
    p.center_x_raw = cx_raw;
    p.center_y_raw = cy_raw;
    p.low_limit_raw = 0;
    p.high_limit_raw = FP_ONE;
    fl::span<CRGB> leds = e->mCtx->leds;
    for (int i = 0; i < total_pixels; i++) {
        // Per-pixel: dist and angle
        p.dist_raw = mState.distance_raw[i] - dist_offset_raw;
        p.angle_raw = angle_offset_raw + mState.polar_theta_raw[i];
        fl::i32 show1 = render_value_fp(p, fade_lut, perm);
        fl::i32 r = show1;
        fl::i32 g = show1 - 80;
        fl::i32 b = show1 - 150;
        rgb_sanity_check_fp(r, g, b);
        leds[mState.pixel_idx[i]] = CRGB(
            static_cast<fl::u8>(r),
            static_cast<fl::u8>(g),
            static_cast<fl::u8>(b));
    }
}
References fl::render_parameters_fp::angle_raw, fl::fl::assume_aligned(), fl::render_parameters_fp::center_x_raw, fl::render_parameters_fp::center_y_raw, fl::render_parameters_fp::dist_raw, fl::FP_ONE, fl::render_parameters_fp::high_limit_raw, leds, fl::render_parameters_fp::low_limit_raw, fl::Context::mEngine, mState, fl::render_parameters_fp::offset_x_raw, fl::render_parameters_fp::offset_y_raw, fl::render_parameters_fp::offset_z_raw, fl::s16x16::raw(), fl::render_value_fp(), fl::rgb_sanity_check_fp(), fl::render_parameters_fp::scale_x_raw, fl::render_parameters_fp::scale_y_raw, fl::render_parameters_fp::scale_z_raw, and fl::render_parameters_fp::z_raw.