FastLED: SelectColor
SelectColor()
const ColorHSV SelectColor (int midi_note, float brightness, int color_selector_val)
Definition at line 166 of file color_mapper.cpp.
{
  const uint8_t fun_note = FundamentalNote(midi_note);
  const ColorScheme& color_scheme = SelectColorScheme(color_selector_val);
  ColorHSV color = color_scheme.data[fun_note];
  color.v_ = brightness;
  return color;
}
References brightness, ColorScheme::data, FundamentalNote(), SelectColorScheme(), and ColorHSV::v_.
Referenced by KeyboardState::HandleNoteOn().