FastLED: wavefx_loop
wavefx_loop()
void wavefx_loop ()
Definition at line 370 of file wavefx.cpp.
                   {
    // The main program loop that runs continuously
    // Get the current time in milliseconds
    uint32_t now = millis();
    // set the x cyclical
    waveFxLower.setXCylindrical(xCyclical.value());  // Set whether lower wave wraps around x-axis
    // Apply all UI settings and get button states
    ui_state state = ui();
    // Check if the regular ripple button was pressed
    if (state.button) {
        triggerRipple();  // Create a single ripple
    }
    // Apply the fancy cross effect if its button is pressed
    applyFancyEffect(now, state.bigButton);
    // Handle automatic triggering of ripples
    processAutoTrigger(now);
    // Create a drawing context with the current time and LED array
    Fx::DrawContext ctx(now, leds);
    // Draw the blended result of both wave layers to the LED array
    fxBlend.draw(ctx);
    // Send the color data to the actual LEDs
    FastLED.show();
}
References applyFancyEffect(), ui_state::bigButton, ui_state::button, FastLED, fxBlend, leds, processAutoTrigger(), triggerRipple(), ui(), waveFxLower, and xCyclical.
Referenced by loop().