FastLED: fl::RxDevice::getRawEdgeTimes
getRawEdgeTimes()
virtual size_t fl::RxDevice::getRawEdgeTimes (fl::span< EdgeTime > out, size_t offset = 0) pure virtual
Get raw edge timings in universal format (for debugging)
Parameters
out Output span to write EdgeTime entries (span.size() = max edges to read)
offset Starting edge index to read from (default: 0)
Returns
Number of EdgeTime entries written (may be less than out.size() if insufficient data)
Converts internal platform-specific format (RMT ticks, ISR timestamps, etc.) to universal EdgeTime format with nanosecond durations.
For RMT devices: Each RMT symbol produces 2 EdgeTime entries (high/low phases)
Example:
auto rx = RxDevice::create<RxDeviceType::RMT>(6);  // GPIO 6
RxConfig config;
config.buffer_size = 512;
rx->begin(config);
rx->wait(100);
// Get first 100 edges
EdgeTime edges[100];
size_t count = rx->getRawEdgeTimes(edges);  // offset defaults to 0
// Get 10 edges starting at offset 50
EdgeTime edges[10];
size_t count = rx->getRawEdgeTimes(edges, 50);
References FL_NOEXCEPT, getRawEdgeTimes(), and offset().
Referenced by getRawEdgeTimes().