FastLED: DMXSimpleController::showPixels
showPixels()
template<uint8_t DATA_PIN, EOrder RGB_ORDER = RGB> virtual void DMXSimpleController< DATA_PIN, RGB_ORDER >::showPixels (PixelController< RGB_ORDER > & pixels) inline protected virtual
Send the LED data to the strip.
Parameters
pixels the PixelController object for the LED data
Definition at line 35 of file dmx.h.
{
        int iChannel = 1;
        while(pixels.has(1)) {
            DmxSimple.write(iChannel++, pixels.loadAndScale0());
            DmxSimple.write(iChannel++, pixels.loadAndScale1());
            DmxSimple.write(iChannel++, pixels.loadAndScale2());
            pixels.advanceData();
            pixels.stepDithering();
        }
    }
References PixelController< RGB_ORDER, LANES, MASK >::advanceData(), PixelController< RGB_ORDER, LANES, MASK >::has(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale0(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale1(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale2(), and PixelController< RGB_ORDER, LANES, MASK >::stepDithering().