FastLED: brightness
brightness
fl::UISlider brightness("Brightness", BRIGHTNESS, 0, 255) ("Brightness" , BRIGHTNESS , 0 , 255)
Examples
Animartrix.ino, and FxNoiseRing.ino.
Referenced by anonymous_namespace{AutoResearchRemote.cpp}::ScopedFastLedBrightness::ScopedFastLedBrightness(), fl::UCS7604CurrentControl::UCS7604CurrentControl(), fl::FastLEDAdapter::~FastLEDAdapter(), fl::detail::ScaledPixelIteratorBrightness::advance(), fl::detail::ScaledPixelIteratorRGB16::advance(), fl::applyGamma_video(), fl::audio::detector::MoodAnalyzer::calculateValence(), RGBWEmulatedController< CONTROLLER, RGB_ORDER >::ControllerT::callShow(), fl::ColorFromPalette(), fl::ColorFromPalette(), fl::ColorFromPalette(), fl::ColorFromPalette(), fl::ColorFromPalette(), fl::ColorFromPalette(), fl::ColorFromPalette(), fl::ColorFromPalette(), fl::ColorFromPaletteExtended(), fl::ColorFromPaletteExtended(), fl::ColorFromPaletteExtended(), fl::ColorFromPaletteExtended(), fl::ColorFromPaletteExtended(), fl::ColorFromPaletteHD(), fl::ColorFromPaletteHD(), fl::ColorFromPaletteHD(), fl::ColorFromPaletteHD(), fl::ColorFromPaletteHD(), fl::anonymous_namespace{colorutils.cpp.hpp}::ColorFromPaletteHDImpl(), displayControls(), fl::video::VideoImpl::draw(), fl::encodeAPA102_AutoBrightness(), fl::encodeHD108_HD(), fl::encodeSK9822_AutoBrightness(), FillLEDsFromPaletteColors(), fl::anonymous_namespace{five_bit_hd_gamma.cpp.hpp}::five_bit_impl::five_bit_pixel(), FL_DISABLE_WARNING(), fl::CLEDController::getAdjustmentData(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::getGlobalBrightnessAndScalingFactors(), KeyboardState::HandleNoteOn(), loop(), map_power_value(), MyColorFromPaletteExtended(), renderGroup(), scale_power_for_brightness(), fl::anonymous_namespace{colorutils.cpp.hpp}::scale_rgb_hd(), SelectColor(), fl::third_party::ezWS2812::set_brightness(), fl::third_party::ezWS2812gpio::set_brightness(), fl::FastLEDAdapter::setBrightness(), fl::IFastLED::setBrightness(), fl::WLEDClient::setBrightness(), setPanelHigh(), setPanelLow(), setup(), CPixelLEDController< RGB_ORDER, LANES, MASK >::show(), fl::CLEDController::show(), fl::FastLEDAdapter::show(), fl::IFastLED::show(), CPixelLEDController< RGB_ORDER, LANES, MASK >::showColor(), fl::CLEDController::showColor(), fl::CLEDController::showColorInternal(), fl::CLEDController::showColorInternal(), showGenerative(), fl::CLEDController::showInternal(), fl::Channel::showLeds(), fl::CLEDController::showLeds(), fl::CLEDController::showLedsInternal(), and APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::writeLed().