FastLED: LoopbackTestRunner::runTest
runTest()
void LoopbackTestRunner::runTest (const char * name, const char * url, const char * expected, TestSequenceState next_state) inline private
Definition at line 122 of file LoopbackTestRunner.h.
{
        FL_WARN("[LOOPBACK] Running test: " << name << " -> " << url);
        Serial.print("Running test: ");
        Serial.println(name);
        tests_run++;
        // Launch async HTTP request with non-blocking .then()/.catch_() callbacks
        fl::net::http::fetch_get(url)
            .then([this, expected, next_state](const fl::net::http::Response& resp) {
                // Success callback - validate response
                if (resp.status() == 200 && resp.text() == expected) {
                    tests_passed++;
                    Serial.println("  ✓ PASSED");
                } else {
                    has_failure = true;
                    Serial.print("  ✗ FAILED - ");
                    if (resp.status() != 200) {
                        Serial.print("Status: ");
                        Serial.print(static_cast<int>(resp.status()));
                    } else {
                        Serial.print("Expected: '");
                        Serial.print(expected);
                        Serial.print("', Got: '");
                        Serial.print(resp.text().c_str());
                        Serial.print("'");
                    }
                    Serial.println();
                }
                // Advance to next test state
                state = next_state;
            })
            .catch_([this](const fl::task::Error& err) {
                // Error callback - network/connection failure
                has_failure = true;
                Serial.print("  ✗ FAILED - Error: ");
                Serial.println(err.message.c_str());
                // Abort remaining tests on network error
                state = COMPLETED;
            });
        // Immediately transition to waiting state (non-blocking)
        state = static_cast<TestSequenceState>(state + 1);  // RUNNING_X -> WAITING_X
    }
References fl::basic_string::c_str(), COMPLETED, fl::net::http::fetch_get(), FL_WARN, has_failure, fl::task::Error::message, Serial, state, fl::net::http::Response::status(), tests_passed, tests_run, and fl::net::http::Response::text().
Referenced by update().