FastLED: fl::unique_ptr< T[], Deleter >::operator=
operator=() [6/8]
template<typename T, typename Deleter> unique_ptr & fl::unique_ptr< T[], Deleter >::operator= (unique_ptr< T[], Deleter > && u) inline
Definition at line 161 of file unique_ptr.h.
{
        if (this != &u) {
            reset(u.release());
            mDeleter = fl::move(u.mDeleter);
        }
        return *this;
    }
References unique_ptr(), FL_NOEXCEPT, mDeleter, fl::move(), and reset().