FastLED: fl::third_party::vorbis::compute_codewords
compute_codewords()
static int32_t fl::third_party::vorbis::compute_codewords (Codebook * c, uint8 * len, int32_t n, uint32 * values) static
Definition at line 816 of file stb_vorbis.cpp.hpp.
{
   int32_t i,k,m=0;
   uint32 available[32];
   memset(available, 0, sizeof(available));
   // find the first entry
   for (k=0; k < n; ++k) if (len[k] < NO_CODE) break;
   if (k == n) { FL_ASSERT(c->sorted_entries == 0, "sorted_entries must be 0"); return true; }
   FL_ASSERT(len[k] < 32, "len must be < 32"); // no error return required, code reading lens checks this
   // add to the list
   add_entry(c, 0, k, m++, len[k], values);
   // add all available leaves
   for (i=1; i <= len[k]; ++i)
      available[i] = 1U << (32-i);
   // note that the above code treats the first case specially,
   // but it's really the same as the following code, so they
   // could probably be combined (except the initial code is 0,
   // and I use 0 in available[] to mean 'empty')
   for (i=k+1; i < n; ++i) {
      uint32 res;
      int32_t z = len[i], y;
      if (z == NO_CODE) continue;
      FL_ASSERT(z < 32, "z must be < 32"); // no error return required, code reading lens checks this
      // find lowest available leaf (should always be earliest,
      // which is what the specification calls for)
      // note that this property, and the fact we can never have
      // more than one free leaf at a given level, isn't totally
      // trivial to prove, but it seems true and the assert never
      // fires, so!
      while (z > 0 && !available[z]) --z;
      if (z == 0) { return false; }
      res = available[z];
      available[z] = 0;
      add_entry(c, bit_reverse(res), i, m++, len[i], values);
      // propagate availability up the tree
      if (z != len[i]) {
         for (y=len[i]; y > z; --y) {
            FL_ASSERT(available[y] == 0, "available must be 0");
            available[y] = res + (1 << (32-y));
         }
      }
   }
   return true;
}
References add_entry(), fl::available(), bit_reverse(), FL_ASSERT, FL_NOEXCEPT, memset(), NO_CODE, fl::y, and z.
Referenced by start_decoder().