FastLED: fl::third_party::vorbis::vorbis_decode_initial
vorbis_decode_initial()
static int32_t fl::third_party::vorbis::vorbis_decode_initial (vorb * f, int32_t * p_left_start, int32_t * p_left_end, int32_t * p_right_start, int32_t * p_right_end, int32_t * mode) static
Definition at line 2854 of file stb_vorbis.cpp.hpp.
{
   Mode *m;
   int32_t i, n, prev, next, window_center;
   f->channel_buffer_start = f->channel_buffer_end = 0;
  retry:
   if (f->eof) return false;
   if (!maybe_start_packet(f))
      return false;
   // check packet type
   if (get_bits(f,1) != 0) {
      if (FL_STBV_IS_PUSH_MODE(f))
         return error(f,VORBIS_bad_packet_type);
      while (EOP != get8_packet(f));
      goto retry;
   }
   if (f->alloc.alloc_buffer)
      FL_ASSERT(f->alloc.alloc_buffer_length_in_bytes == f->temp_offset, "alloc_buffer_length must equal temp_offset");
   i = get_bits(f, ilog(f->mode_count-1));
   if (i == EOP) return false;
   if (i >= f->mode_count) return false;
   *mode = i;
   m = f->mode_config + i;
   if (m->blockflag) {
      n = f->blocksize_1;
      prev = get_bits(f,1);
      next = get_bits(f,1);
   } else {
      prev = next = 0;
      n = f->blocksize_0;
   }
// WINDOWING
   window_center = n >> 1;
   if (m->blockflag && !prev) {
      *p_left_start = (n - f->blocksize_0) >> 2;
      *p_left_end   = (n + f->blocksize_0) >> 2;
   } else {
      *p_left_start = 0;
      *p_left_end   = window_center;
   }
   if (m->blockflag && !next) {
      *p_right_start = (n*3 - f->blocksize_0) >> 2;
      *p_right_end   = (n*3 + f->blocksize_0) >> 2;
   } else {
      *p_right_start = window_center;
      *p_right_end   = n;
   }
   return true;
}
References fl::third_party::vorbis::Mode::blockflag, EOP, error(), FL_ASSERT, FL_NOEXCEPT, FL_STBV_IS_PUSH_MODE, get8_packet(), get_bits(), ilog(), maybe_start_packet(), and VORBIS_bad_packet_type.
Referenced by peek_decode_initial(), and vorbis_decode_packet().