FastLED: fl::third_party::vorbis::start_page
start_page()
static int32_t fl::third_party::vorbis::start_page (vorb * f) static
Definition at line 1225 of file stb_vorbis.cpp.hpp.
{
   if (!capture_pattern(f)) return error(f, VORBIS_missing_capture_pattern);
   return start_page_no_capturepattern(f);
}
References capture_pattern(), error(), FL_NOEXCEPT, start_page_no_capturepattern(), and VORBIS_missing_capture_pattern.
Referenced by next_segment(), seek_to_sample_coarse(), start_decoder(), and start_packet().