FastLED: fl::third_party::vorbis::vorbis_finish_frame
vorbis_finish_frame()
static int32_t fl::third_party::vorbis::vorbis_finish_frame (stb_vorbis * f, int32_t len, int32_t left, int32_t right) static
Definition at line 3186 of file stb_vorbis.cpp.hpp.
{
   int32_t prev,i,j;
   // we use right&left (the start of the right- and left-window sin()-regions)
   // to determine how much to return, rather than inferring from the rules
   // (same result, clearer code); 'left' indicates where our sin() window
   // starts, therefore where the previous window's right edge starts, and
   // therefore where to start mixing from the previous buffer. 'right'
   // indicates where our sin() ending-window starts, therefore that's where
   // we start saving, and where our returned-data ends.
   // mixin from previous window
   if (f->previous_length) {
      int32_t i,j, n = f->previous_length;
      float *w = get_window(f, n);
      if (w == nullptr) return 0;
      for (i=0; i < f->channels; ++i) {
         for (j=0; j < n; ++j)
            f->channel_buffers[i][left+j] =
               f->channel_buffers[i][left+j]*w[    j] +
               f->previous_window[i][     j]*w[n-1-j];
      }
   }
   prev = f->previous_length;
   // last half of this data becomes previous window
   f->previous_length = len - right;
   // @OPTIMIZE: could avoid this copy by double-buffering the
   // output (flipping previous_window with channel_buffers), but
   // then previous_window would have to be 2x as large, and
   // channel_buffers couldn't be temp mem (although they're NOT
   // currently temp mem, they could be (unless we want to level
   // performance by spreading out the computation))
   for (i=0; i < f->channels; ++i)
      for (j=0; right+j < len; ++j)
         f->previous_window[i][j] = f->channel_buffers[i][right+j];
   if (!prev)
      // there was no previous packet, so this data isn't valid...
      // this isn't entirely true, only the would-have-overlapped data
      // isn't valid, but this seems to be what the spec requires
      return 0;
   // truncate a short frame
   if (len < right) right = len;
   f->samples_output += right-left;
   return right - left;
}
References FL_NOEXCEPT, and get_window().
Referenced by stb_vorbis_decode_frame_pushdata(), stb_vorbis_get_frame_float(), and vorbis_pump_first_frame().