FastLED: fl::third_party::vorbis::get8_packet_raw
get8_packet_raw()
static int32_t fl::third_party::vorbis::get8_packet_raw (vorb * f) static
Definition at line 1291 of file stb_vorbis.cpp.hpp.
{
   if (!f->bytes_in_seg) {  // CLANG!
      if (f->last_seg) return EOP;
      else if (!next_segment(f)) return EOP;
   }
   FL_ASSERT(f->bytes_in_seg > 0, "bytes_in_seg must be > 0");
   --f->bytes_in_seg;
   ++f->packet_bytes;
   return get8(f);
}
References EOP, FL_ASSERT, FL_NOEXCEPT, get8(), and next_segment().
Referenced by flush_packet(), get8_packet(), get_bits(), and prep_huffman().