FastLED: fl::third_party::vorbis::setup_temp_malloc
setup_temp_malloc()
static void * fl::third_party::vorbis::setup_temp_malloc (vorb * f, int32_t sz) static
Definition at line 703 of file stb_vorbis.cpp.hpp.
{
   sz = (sz+7) & ~7; // round up to nearest 8 for alignment of future allocs.
   if (f->alloc.alloc_buffer) {
      if (f->temp_offset - sz < f->setup_offset) return nullptr;
      f->temp_offset -= sz;
      return (char *) f->alloc.alloc_buffer + f->temp_offset;
   }
   return fl::malloc(sz);
}
References FL_NOEXCEPT, and fl::malloc().
Referenced by fl_stbv_temp_alloc_impl(), and start_decoder().