FastLED: fl::third_party::vorbis::stb_vorbis_stream_length_in_samples
stb_vorbis_stream_length_in_samples()
uint32_t fl::third_party::vorbis::stb_vorbis_stream_length_in_samples (stb_vorbis * f)
Definition at line 4704 of file stb_vorbis.cpp.hpp.
{
   uint32_t restore_offset, previous_safe;
   uint32_t end, last_page_loc;
   if (FL_STBV_IS_PUSH_MODE(f)) return error(f, VORBIS_invalid_api_mixing);
   if (!f->total_samples) {
      uint32_t last;
      uint32 lo,hi;
      char header[6];
      // first, store the current decode position so we can restore it
      restore_offset = stb_vorbis_get_file_offset(f);
      // now we want to seek back 64K from the end (the last page must
      // be at most a little less than 64K, but let's allow a little slop)
      if (f->stream_len >= 65536 && f->stream_len-65536 >= f->first_audio_page_offset)
         previous_safe = f->stream_len - 65536;
      else
         previous_safe = f->first_audio_page_offset;
      set_file_offset(f, previous_safe);
      // previous_safe is now our candidate 'earliest known place that seeking
      // to will lead to the final page'
      if (!vorbis_find_page(f, &end, &last)) {
         // if we can't find a page, we're hosed!
         f->error = VORBIS_cant_find_last_page;
         f->total_samples = 0xffffffff;
         goto done;
      }
      // check if there are more pages
      last_page_loc = stb_vorbis_get_file_offset(f);
      // stop when the last_page flag is set, not when we reach eof;
      // this allows us to stop short of a 'file_section' end without
      // explicitly checking the length of the section
      while (!last) {
         set_file_offset(f, end);
         if (!vorbis_find_page(f, &end, &last)) {
            // the last page we found didn't have the 'last page' flag
            // set. whoops!
            break;
         }
         //previous_safe = last_page_loc+1; // NOTE: not used after this point, but note for debugging
         last_page_loc = stb_vorbis_get_file_offset(f);
      }
      set_file_offset(f, last_page_loc);
      // parse the header
      getn(f, (unsigned char *)header, 6);
      // extract the absolute granule position
      lo = get32(f);
      hi = get32(f);
      if (lo == 0xffffffff && hi == 0xffffffff) {
         f->error = VORBIS_cant_find_last_page;
         f->total_samples = SAMPLE_unknown;
         goto done;
      }
      if (hi)
         lo = 0xfffffffe; // saturate
      f->total_samples = lo;
      f->p_last.page_start = last_page_loc;
      f->p_last.page_end   = end;
      f->p_last.last_decoded_sample = lo;
     done:
      set_file_offset(f, restore_offset);
   }
   return f->total_samples == SAMPLE_unknown ? 0 : f->total_samples;
}
References done, fl::end(), error(), FL_NOEXCEPT, FL_STBV_IS_PUSH_MODE, get32(), getn(), SAMPLE_unknown, set_file_offset(), stb_vorbis_get_file_offset(), VORBIS_cant_find_last_page, vorbis_find_page(), and VORBIS_invalid_api_mixing.
Referenced by seek_to_sample_coarse(), and stb_vorbis_stream_length_in_seconds().