FastLED: fl::third_party::vorbis::stb_vorbis_seek_start
stb_vorbis_seek_start()
int32_t fl::third_party::vorbis::stb_vorbis_seek_start (stb_vorbis * f)
Definition at line 4694 of file stb_vorbis.cpp.hpp.
{
   if (FL_STBV_IS_PUSH_MODE(f)) { return error(f, VORBIS_invalid_api_mixing); }
   set_file_offset(f, f->first_audio_page_offset);
   f->previous_length = 0;
   f->first_decode = true;
   f->next_seg = -1;
   return vorbis_pump_first_frame(f);
}
References error(), FL_NOEXCEPT, FL_STBV_IS_PUSH_MODE, set_file_offset(), VORBIS_invalid_api_mixing, and vorbis_pump_first_frame().
Referenced by seek_to_sample_coarse().