FastLED: fl::third_party::vorbis::codebook_decode_scalar_raw
codebook_decode_scalar_raw()
static int32_t fl::third_party::vorbis::codebook_decode_scalar_raw (vorb * f, Codebook * c) static
Definition at line 1384 of file stb_vorbis.cpp.hpp.
{
   int32_t i;
   prep_huffman(f);
   if (c->codewords == nullptr && c->sorted_codewords == nullptr)
      return -1;
   // cases to use binary search: sorted_codewords && !c->codewords
   //                             sorted_codewords && c->entries > 8
   if (c->entries > 8 ? c->sorted_codewords!=nullptr : !c->codewords) {
      // binary search
      uint32 code = bit_reverse(f->acc);
      int32_t x=0, n=c->sorted_entries, len;
      while (n > 1) {
         // invariant: sc[x] <= code < sc[x+n]
         int32_t m = x + (n >> 1);
         if (c->sorted_codewords[m] <= code) {
            x = m;
            n -= (n>>1);
         } else {
            n >>= 1;
         }
      }
      // x is now the sorted index
      if (!c->sparse) x = c->sorted_values[x];
      // x is now sorted index if sparse, or symbol otherwise
      len = c->codeword_lengths[x];
      if (f->valid_bits >= len) {
         f->acc >>= len;
         f->valid_bits -= len;
         return x;
      }
      f->valid_bits = 0;
      return -1;
   }
   // if small, linear search
   FL_ASSERT(!c->sparse, "codebook must not be sparse");
   for (i=0; i < c->entries; ++i) {
      if (c->codeword_lengths[i] == NO_CODE) continue;
      if (c->codewords[i] == (f->acc & ((1 << c->codeword_lengths[i])-1))) {
         if (f->valid_bits >= c->codeword_lengths[i]) {
            f->acc >>= c->codeword_lengths[i];
            f->valid_bits -= c->codeword_lengths[i];
            return i;
         }
         f->valid_bits = 0;
         return -1;
      }
   }
   error(f, VORBIS_invalid_stream);
   f->valid_bits = 0;
   return -1;
}
References bit_reverse(), error(), FL_ASSERT, FL_NOEXCEPT, NO_CODE, prep_huffman(), VORBIS_invalid_stream, and fl::x.