FastLED: fl::third_party::vorbis::stb_vorbis_decode_frame_pushdata
stb_vorbis_decode_frame_pushdata()
int32_t fl::third_party::vorbis::stb_vorbis_decode_frame_pushdata (stb_vorbis * f, const uint8 * data, int32_t data_len, int32_t * channels, float *** output, int32_t * samples)
Definition at line 4202 of file stb_vorbis.cpp.hpp.
{
   int32_t i;
   int32_t len,right,left;
   if (!FL_STBV_IS_PUSH_MODE(f)) return error(f, VORBIS_invalid_api_mixing);
   if (f->page_crc_tests >= 0) {
      *samples = 0;
      return vorbis_search_for_page_pushdata(f, (uint8 *) data, data_len);
   }
   f->stream     = (uint8 *) data;
   f->stream_end = (uint8 *) data + data_len;
   f->error      = VORBIS__no_error;
   // check that we have the entire packet in memory
   if (!is_whole_packet_present(f)) {
      *samples = 0;
      return 0;
   }
   if (!vorbis_decode_packet(f, &len, &left, &right)) {
      // save the actual error we encountered
      enum STBVorbisError error = f->error;
      if (error == VORBIS_bad_packet_type) {
         // flush and resynch
         f->error = VORBIS__no_error;
         while (get8_packet(f) != EOP)
            if (f->eof) break;
         *samples = 0;
         return (int32_t) (f->stream - data);
      }
      if (error == VORBIS_continued_packet_flag_invalid) {
         if (f->previous_length == 0) {
            // we may be resynching, in which case it's ok to hit one
            // of these; just discard the packet
            f->error = VORBIS__no_error;
            while (get8_packet(f) != EOP)
               if (f->eof) break;
            *samples = 0;
            return (int32_t) (f->stream - data);
         }
      }
      // if we get an error while parsing, what to do?
      // well, it DEFINITELY won't work to continue from where we are!
      stb_vorbis_flush_pushdata(f);
      // restore the error that actually made us bail
      f->error = error;
      *samples = 0;
      return 1;
   }
   // success!
   len = vorbis_finish_frame(f, len, left, right);
   for (i=0; i < f->channels; ++i)
      f->outputs[i] = f->channel_buffers[i] + left;
   if (channels) *channels = f->channels;
   *samples = len;
   *output = f->outputs;
   return (int32_t) (f->stream - data);
}
References EOP, error(), FL_NOEXCEPT, FL_STBV_IS_PUSH_MODE, get8_packet(), is_whole_packet_present(), stb_vorbis_flush_pushdata(), VORBIS__no_error, VORBIS_bad_packet_type, VORBIS_continued_packet_flag_invalid, vorbis_decode_packet(), vorbis_finish_frame(), VORBIS_invalid_api_mixing, and vorbis_search_for_page_pushdata().