FastLED: fl::third_party::vorbis::stb_vorbis_seek_frame
stb_vorbis_seek_frame()
int32_t fl::third_party::vorbis::stb_vorbis_seek_frame (stb_vorbis * f, uint32_t sample_number)
Definition at line 4638 of file stb_vorbis.cpp.hpp.
{
   uint32 max_frame_samples;
   if (FL_STBV_IS_PUSH_MODE(f)) return error(f, VORBIS_invalid_api_mixing);
   // fast page-level search
   if (!seek_to_sample_coarse(f, sample_number))
      return 0;
   FL_ASSERT(f->current_loc_valid, "current_loc must be valid");
   FL_ASSERT(f->current_loc <= sample_number, "current_loc must be <= sample_number");
   // linear search for the relevant packet
   max_frame_samples = (f->blocksize_1*3 - f->blocksize_0) >> 2;
   while (f->current_loc < sample_number) {
      int32_t left_start, left_end, right_start, right_end, mode, frame_samples;
      if (!peek_decode_initial(f, &left_start, &left_end, &right_start, &right_end, &mode))
         return error(f, VORBIS_seek_failed);
      // calculate the number of samples returned by the next frame
      frame_samples = right_start - left_start;
      if (f->current_loc + frame_samples > sample_number) {
         return 1; // the next frame will contain the sample
      } else if (f->current_loc + frame_samples + max_frame_samples > sample_number) {
         // there's a chance the frame after this could contain the sample
         vorbis_pump_first_frame(f);
      } else {
         // this frame is too early to be relevant
         f->current_loc += frame_samples;
         f->previous_length = 0;
         maybe_start_packet(f);
         flush_packet(f);
      }
   }
   // the next frame should start with the sample
   if (f->current_loc != sample_number) return error(f, VORBIS_seek_failed);
   return 1;
}
References error(), FL_ASSERT, FL_NOEXCEPT, FL_STBV_IS_PUSH_MODE, flush_packet(), maybe_start_packet(), peek_decode_initial(), seek_to_sample_coarse(), VORBIS_invalid_api_mixing, vorbis_pump_first_frame(), and VORBIS_seek_failed.
Referenced by stb_vorbis_seek().