FastLED: fl::third_party::vorbis::stb_vorbis_get_frame_short
stb_vorbis_get_frame_short() [2/2]
int32_t fl::third_party::vorbis::stb_vorbis_get_frame_short (stb_vorbis * f, int32_t num_c, short ** buffer, int32_t num_samples)
Definition at line 5025 of file stb_vorbis.cpp.hpp.
{
   float **output = nullptr;
   int32_t len = stb_vorbis_get_frame_float(f, nullptr, &output);
   if (len > num_samples) len = num_samples;
   if (len)
      convert_samples_short(num_c, buffer, 0, f->channels, output, 0, len);
   return len;
}
References convert_samples_short(), FL_NOEXCEPT, and stb_vorbis_get_frame_float().
Referenced by stb_vorbis_get_frame_short_interleaved().