FastLED: fl::third_party::vorbis::codebook_decode_step
codebook_decode_step()
static int32_t fl::third_party::vorbis::codebook_decode_step (vorb * f, Codebook * c, float * output, int32_t len, int32_t step) static
Definition at line 1562 of file stb_vorbis.cpp.hpp.
{
   int32_t i,z = codebook_decode_start(f,c);
   float last = FL_STBV_CODEBOOK_ELEMENT_BASE(c);
   if (z < 0) return false;
   if (len > c->dimensions) len = c->dimensions;
#ifdef FL_STB_VORBIS_DIVIDES_IN_CODEBOOK
   if (c->lookup_type == 1) {
      int32_t div = 1;
      for (i=0; i < len; ++i) {
         int32_t off = (z / div) % c->lookup_values;
         float val = FL_STBV_CODEBOOK_ELEMENT_FAST(c,off) + last;
         output[i*step] += val;
         if (c->sequence_p) last = val;
         div *= c->lookup_values;
      }
      return true;
   }
#endif
   z *= c->dimensions;
   for (i=0; i < len; ++i) {
      float val = FL_STBV_CODEBOOK_ELEMENT_FAST(c,z+i) + last;
      output[i*step] += val;
      if (c->sequence_p) last = val;
   }
   return true;
}
References codebook_decode_start(), FL_NOEXCEPT, FL_STBV_CODEBOOK_ELEMENT_BASE, FL_STBV_CODEBOOK_ELEMENT_FAST, fl::step(), and z.
Referenced by residue_decode().