FastLED: fl::third_party::vorbis::stb_vorbis_get_frame_short_interleaved
stb_vorbis_get_frame_short_interleaved() [2/2]
int32_t fl::third_party::vorbis::stb_vorbis_get_frame_short_interleaved (stb_vorbis * f, int32_t num_c, short * buffer, int32_t num_shorts)
Definition at line 5061 of file stb_vorbis.cpp.hpp.
{
   float **output;
   int32_t len;
   if (num_c == 1) return stb_vorbis_get_frame_short(f,num_c,&buffer, num_shorts);
   len = stb_vorbis_get_frame_float(f, nullptr, &output);
   if (len) {
      if (len*num_c > num_shorts) len = num_shorts / num_c;
      convert_channels_short_interleaved(num_c, buffer, f->channels, output, 0, len);
   }
   return len;
}
References convert_channels_short_interleaved(), FL_NOEXCEPT, stb_vorbis_get_frame_float(), and stb_vorbis_get_frame_short().
Referenced by stb_vorbis_decode_filename(), and stb_vorbis_decode_memory().