FastLED: fl::third_party::vorbis::error
error()
static int32_t fl::third_party::vorbis::error (vorb * f, enum STBVorbisError e) static
Definition at line 586 of file stb_vorbis.cpp.hpp.
{
   f->error = e;
   if (!f->eof && e != VORBIS_need_more_data) {
      f->error=e; // breakpoint for debugging
   }
   return 0;
}
References FL_NOEXCEPT, and VORBIS_need_more_data.
Referenced by codebook_decode_deinterleave_repeat(), codebook_decode_scalar_raw(), codebook_decode_start(), do_floor(), init_blocksize(), is_whole_packet_present(), maybe_start_packet(), next_segment(), seek_to_sample_coarse(), start_decoder(), start_packet(), start_page(), start_page_no_capturepattern(), stb_vorbis_decode_filename(), stb_vorbis_decode_frame_pushdata(), stb_vorbis_decode_memory(), stb_vorbis_decode_memory(), stb_vorbis_get_frame_float(), stb_vorbis_open_file(), stb_vorbis_open_file_section(), stb_vorbis_open_filename(), stb_vorbis_open_memory(), stb_vorbis_open_pushdata(), stb_vorbis_seek_frame(), stb_vorbis_seek_start(), stb_vorbis_stream_length_in_samples(), vorbis_decode_initial(), and vorbis_decode_packet_rest().