FastLED: fl::third_party::vorbis::stb_vorbis_get_file_offset
stb_vorbis_get_file_offset()
uint32_t fl::third_party::vorbis::stb_vorbis_get_file_offset (stb_vorbis * f)
Definition at line 4303 of file stb_vorbis.cpp.hpp.
{
   #ifndef FL_STB_VORBIS_NO_PUSHDATA_API
   if (f->push_mode) return 0;
   #endif
   if (FL_STBV_USE_MEMORY(f)) return (uint32_t) (f->stream - f->stream_start);
   #ifndef FL_STB_VORBIS_NO_STDIO
   return (uint32_t) (fl::ftell(f->f) - f->f_start);
   #endif
}
References FL_NOEXCEPT, FL_STBV_USE_MEMORY, and fl::ftell().
Referenced by get_seek_page_info(), go_to_page_before(), seek_to_sample_coarse(), start_decoder(), start_page_no_capturepattern(), stb_vorbis_stream_length_in_samples(), and vorbis_find_page().