FastLED: fl::third_party::vorbis::stb_vorbis_open_pushdata
stb_vorbis_open_pushdata()
stb_vorbis * fl::third_party::vorbis::stb_vorbis_open_pushdata (const unsigned char * data, int32_t data_len, int32_t * data_used, int32_t * error, const stb_vorbis_alloc * alloc)
Definition at line 4272 of file stb_vorbis.cpp.hpp.
{
   stb_vorbis *f, p;
   vorbis_init(&p, alloc);
   p.stream     = (uint8 *) data;
   p.stream_end = (uint8 *) data + data_len;
   p.push_mode  = true;
   if (!start_decoder(&p)) {
      if (p.eof)
         *error = VORBIS_need_more_data;
      else
         *error = p.error;
      vorbis_deinit(&p);
      return nullptr;
   }
   f = vorbis_alloc(&p);
   if (f) {
      *f = p;
      *data_used = (int32_t) (f->stream - data);
      *error = 0;
      return f;
   } else {
      vorbis_deinit(&p);
      return nullptr;
   }
}
References fl::third_party::vorbis::stb_vorbis::eof, error(), fl::third_party::vorbis::stb_vorbis::error, FL_NOEXCEPT, fl::third_party::vorbis::stb_vorbis::push_mode, start_decoder(), fl::third_party::vorbis::stb_vorbis::stream, fl::third_party::vorbis::stb_vorbis::stream_end, vorbis_alloc(), vorbis_deinit(), vorbis_init(), and VORBIS_need_more_data.