FastLED: fl::third_party::vorbis::peek_decode_initial
peek_decode_initial()
static int32_t fl::third_party::vorbis::peek_decode_initial (vorb * f, int32_t * p_left_start, int32_t * p_left_end, int32_t * p_right_start, int32_t * p_right_end, int32_t * mode) static
Definition at line 4613 of file stb_vorbis.cpp.hpp.
{
   int32_t bits_read, bytes_read;
   if (!vorbis_decode_initial(f, p_left_start, p_left_end, p_right_start, p_right_end, mode))
      return 0;
   // either 1 or 2 bytes were read, figure out which so we can rewind
   bits_read = 1 + ilog(f->mode_count-1);
   if (f->mode_config[*mode].blockflag)
      bits_read += 2;
   bytes_read = (bits_read + 7) / 8;
   f->bytes_in_seg += bytes_read;
   f->packet_bytes -= bytes_read;
   skip(f, -bytes_read);
   if (f->next_seg == -1)
      f->next_seg = f->segment_count - 1;
   else
      f->next_seg--;
   f->valid_bits = 0;
   return 1;
}
References FL_NOEXCEPT, ilog(), skip(), and vorbis_decode_initial().
Referenced by stb_vorbis_seek_frame().