FastLED: fl::third_party::vorbis::vorbis_decode_packet_rest
vorbis_decode_packet_rest()
static int32_t fl::third_party::vorbis::vorbis_decode_packet_rest (vorb * f, int32_t * len, Mode * m, int32_t left_start, int32_t left_end, int32_t right_start, int32_t right_end, int32_t * p_left) static
Definition at line 2910 of file stb_vorbis.cpp.hpp.
{
   Mapping *map;
   int32_t i,j,k,n,n2;
   int32_t zero_channel[256];
   int32_t really_zero_channel[256];
// WINDOWING
   FL_UNUSED(left_end);
   n = f->blocksize[m->blockflag];
   map = &f->mapping[m->mapping];
// FLOORS
   n2 = n >> 1;
   FL_STBV_CHECK(f);
   for (i=0; i < f->channels; ++i) {
      int32_t s = map->chan[i].mux, floor;
      zero_channel[i] = false;
      floor = map->submap_floor[s];
      if (f->floor_types[floor] == 0) {
         return error(f, VORBIS_invalid_stream);
      } else {
         Floor1 *g = &f->floor_config[floor].floor1;
         if (get_bits(f, 1)) {
            short *finalY;
            uint8 step2_flag[256];
            static int32_t range_list[4] = { 256, 128, 86, 64 };
            int32_t range = range_list[g->floor1_multiplier-1];
            int32_t offset = 2;
            finalY = f->finalY[i];
            finalY[0] = get_bits(f, ilog(range)-1);
            finalY[1] = get_bits(f, ilog(range)-1);
            for (j=0; j < g->partitions; ++j) {
               int32_t pclass = g->partition_class_list[j];
               int32_t cdim = g->class_dimensions[pclass];
               int32_t cbits = g->class_subclasses[pclass];
               int32_t csub = (1 << cbits)-1;
               int32_t cval = 0;
               if (cbits) {
                  Codebook *c = f->codebooks + g->class_masterbooks[pclass];
                  FL_STBV_DECODE(cval,f,c);
               }
               for (k=0; k < cdim; ++k) {
                  int32_t book = g->subclass_books[pclass][cval & csub];
                  cval = cval >> cbits;
                  if (book >= 0) {
                     int32_t temp;
                     Codebook *c = f->codebooks + book;
                     FL_STBV_DECODE(temp,f,c);
                     finalY[offset++] = temp;
                  } else
                     finalY[offset++] = 0;
               }
            }
            if (f->valid_bits == INVALID_BITS) goto error; // behavior according to spec
            step2_flag[0] = step2_flag[1] = 1;
            for (j=2; j < g->values; ++j) {
               int32_t low, high, pred, highroom, lowroom, room, val;
               low = g->neighbors[j][0];
               high = g->neighbors[j][1];
               //neighbors(g->Xlist, j, &low, &high);
               pred = predict_point(g->Xlist[j], g->Xlist[low], g->Xlist[high], finalY[low], finalY[high]);
               val = finalY[j];
               highroom = range - pred;
               lowroom = pred;
               if (highroom < lowroom)
                  room = highroom * 2;
               else
                  room = lowroom * 2;
               if (val) {
                  step2_flag[low] = step2_flag[high] = 1;
                  step2_flag[j] = 1;
                  if (val >= room)
                     if (highroom > lowroom)
                        finalY[j] = val - lowroom + pred;
                     else
                        finalY[j] = pred - val + highroom - 1;
                  else
                     if (val & 1)
                        finalY[j] = pred - ((val+1)>>1);
                     else
                        finalY[j] = pred + (val>>1);
               } else {
                  step2_flag[j] = 0;
                  finalY[j] = pred;
               }
            }
#ifdef FL_STB_VORBIS_NO_DEFER_FLOOR
            do_floor(f, map, i, n, f->floor_buffers[i], finalY, step2_flag);
#else
            // defer final floor computation until _after_ residue
            for (j=0; j < g->values; ++j) {
               if (!step2_flag[j])
                  finalY[j] = -1;
            }
#endif
         } else {
           error:
            zero_channel[i] = true;
         }
         // So we just defer everything else to later
         // at this point we've decoded the floor into buffer
      }
   }
   FL_STBV_CHECK(f);
   // at this point we've decoded all floors
   if (f->alloc.alloc_buffer)
      FL_ASSERT(f->alloc.alloc_buffer_length_in_bytes == f->temp_offset, "alloc_buffer_length must equal temp_offset");
   // re-enable coupled channels if necessary
   memcpy(really_zero_channel, zero_channel, sizeof(really_zero_channel[0]) * f->channels);
   for (i=0; i < map->coupling_steps; ++i)
      if (!zero_channel[map->chan[i].magnitude] || !zero_channel[map->chan[i].angle]) {
         zero_channel[map->chan[i].magnitude] = zero_channel[map->chan[i].angle] = false;
      }
   FL_STBV_CHECK(f);
// RESIDUE DECODE
   for (i=0; i < map->submaps; ++i) {
      float *residue_buffers[FL_STB_VORBIS_MAX_CHANNELS];
      int32_t r;
      uint8 do_not_decode[256];
      int32_t ch = 0;
      for (j=0; j < f->channels; ++j) {
         if (map->chan[j].mux == i) {
            if (zero_channel[j]) {
               do_not_decode[ch] = true;
               residue_buffers[ch] = nullptr;
            } else {
               do_not_decode[ch] = false;
               residue_buffers[ch] = f->channel_buffers[j];
            }
            ++ch;
         }
      }
      r = map->submap_residue[i];
      decode_residue(f, residue_buffers, ch, n2, r, do_not_decode);
   }
   if (f->alloc.alloc_buffer)
      FL_ASSERT(f->alloc.alloc_buffer_length_in_bytes == f->temp_offset, "alloc_buffer_length must equal temp_offset");
   FL_STBV_CHECK(f);
// INVERSE COUPLING
   for (i = map->coupling_steps-1; i >= 0; --i) {
      int32_t n2 = n >> 1;
      float *m = f->channel_buffers[map->chan[i].magnitude];
      float *a = f->channel_buffers[map->chan[i].angle    ];
      for (j=0; j < n2; ++j) {
         float a2,m2;
         if (m[j] > 0)
            if (a[j] > 0)
               m2 = m[j], a2 = m[j] - a[j];
            else
               a2 = m[j], m2 = m[j] + a[j];
         else
            if (a[j] > 0)
               m2 = m[j], a2 = m[j] + a[j];
            else
               a2 = m[j], m2 = m[j] - a[j];
         m[j] = m2;
         a[j] = a2;
      }
   }
   FL_STBV_CHECK(f);
   // finish decoding the floors
#ifndef FL_STB_VORBIS_NO_DEFER_FLOOR
   for (i=0; i < f->channels; ++i) {
      if (really_zero_channel[i]) {
         memset(f->channel_buffers[i], 0, sizeof(*f->channel_buffers[i]) * n2);
      } else {
         do_floor(f, map, i, n, f->channel_buffers[i], f->finalY[i], nullptr);
      }
   }
#else
   for (i=0; i < f->channels; ++i) {
      if (really_zero_channel[i]) {
         memset(f->channel_buffers[i], 0, sizeof(*f->channel_buffers[i]) * n2);
      } else {
         for (j=0; j < n2; ++j)
            f->channel_buffers[i][j] *= f->floor_buffers[i][j];
      }
   }
#endif
// INVERSE MDCT
   FL_STBV_CHECK(f);
   for (i=0; i < f->channels; ++i)
      inverse_mdct(f->channel_buffers[i], n, f, m->blockflag);
   FL_STBV_CHECK(f);
   // this shouldn't be necessary, unless we exited on an error
   // and want to flush to get to the next packet
   flush_packet(f);
   if (f->first_decode) {
      // assume we start so first non-discarded sample is sample 0
      // this isn't to spec, but spec would require us to read ahead
      // and decode the size of all current frames--could be done,
      // but presumably it's not a commonly used feature
      f->current_loc = 0u - n2; // start of first frame is positioned for discard (NB this is an intentional unsigned overflow/wrap-around)
      // we might have to discard samples "from" the next frame too,
      // if we're lapping a large block then a small at the start?
      f->discard_samples_deferred = n - right_end;
      f->current_loc_valid = true;
      f->first_decode = false;
   } else if (f->discard_samples_deferred) {
      if (f->discard_samples_deferred >= right_start - left_start) {
         f->discard_samples_deferred -= (right_start - left_start);
         left_start = right_start;
         *p_left = left_start;
      } else {
         left_start += f->discard_samples_deferred;
         *p_left = left_start;
         f->discard_samples_deferred = 0;
      }
   } else if (f->previous_length == 0 && f->current_loc_valid) {
      // we're recovering from a seek... that means we're going to discard
      // the samples from this packet even though we know our position from
      // the last page header, so we need to update the position based on
      // the discarded samples here
      // but wait, the code below is going to add this in itself even
      // on a discard, so we don't need to do it here...
   }
   // check if we have ogg information about the sample # for this packet
   if (f->last_seg_which == f->end_seg_with_known_loc) {
      // if we have a valid current loc, and this is final:
      if (f->current_loc_valid && (f->page_flag & PAGEFLAG_last_page)) {
         uint32 current_end = f->known_loc_for_packet;
         // then let's infer the size of the (probably) short final frame
         if (current_end < f->current_loc + (right_end-left_start)) {
            if (current_end < f->current_loc) {
               // negative truncation, that's impossible!
               *len = 0;
            } else {
               *len = current_end - f->current_loc;
            }
            *len += left_start; // this doesn't seem right, but has no ill effect on my test files
            if (*len > right_end) *len = right_end; // this should never happen
            f->current_loc += *len;
            return true;
         }
      }
      // otherwise, just set our sample loc
      // guess that the ogg granule pos refers to the _middle_ of the
      // last frame?
      // set f->current_loc to the position of left_start
      f->current_loc = f->known_loc_for_packet - (n2-left_start);
      f->current_loc_valid = true;
   }
   if (f->current_loc_valid)
      f->current_loc += (right_start - left_start);
   if (f->alloc.alloc_buffer)
      FL_ASSERT(f->alloc.alloc_buffer_length_in_bytes == f->temp_offset, "alloc_buffer_length must equal temp_offset");
   *len = right_end;  // ignore samples after the window goes to 0
   FL_STBV_CHECK(f);
   return true;
}
References fl::third_party::vorbis::Floor1::class_dimensions, fl::third_party::vorbis::Floor1::class_masterbooks, fl::third_party::vorbis::Floor1::class_subclasses, decode_residue(), do_floor(), error(), FL_ASSERT, FL_NOEXCEPT, FL_STB_VORBIS_MAX_CHANNELS, FL_STBV_CHECK, FL_STBV_DECODE, FL_UNUSED, floor(), fl::third_party::vorbis::Floor1::floor1_multiplier, flush_packet(), get_bits(), ilog(), INVALID_BITS, inverse_mdct(), memcpy(), memset(), fl::third_party::vorbis::Floor1::neighbors, offset(), PAGEFLAG_last_page, fl::third_party::vorbis::Floor1::partition_class_list, fl::third_party::vorbis::Floor1::partitions, predict_point(), fl::third_party::vorbis::Floor1::subclass_books, fl::third_party::vorbis::Floor1::values, VORBIS_invalid_stream, and fl::third_party::vorbis::Floor1::Xlist.
Referenced by vorbis_decode_packet().