FastLED: fl::third_party::vorbis::set_file_offset
set_file_offset()
static int32_t fl::third_party::vorbis::set_file_offset (stb_vorbis * f, uint32_t loc) static
Definition at line 1121 of file stb_vorbis.cpp.hpp.
{
   #ifndef FL_STB_VORBIS_NO_PUSHDATA_API
   if (f->push_mode) return 0;
   #endif
   f->eof = 0;
   if (FL_STBV_USE_MEMORY(f)) {
      // Original check commented out: pointer overflow check triggers -Wtautological-compare
      // because compiler assumes no undefined behavior (pointer arithmetic overflow is UB).
      // Replaced with equivalent buffer size check using integer arithmetic.
      // if (f->stream_start + loc >= f->stream_end || f->stream_start + loc < f->stream_start) {
      if (loc >= (size_t)(f->stream_end - f->stream_start)) {
         f->stream = f->stream_end;
         f->eof = 1;
         return 0;
      } else {
         f->stream = f->stream_start + loc;
         return 1;
      }
   }
   #ifndef FL_STB_VORBIS_NO_STDIO
   if (loc + f->f_start < loc || loc >= 0x80000000) {
      loc = 0x7fffffff;
      f->eof = 1;
   } else {
      loc += f->f_start;
   }
   if (!fl::fseek(f->f, loc, fl::io::seek_set))
      return 1;
   f->eof = 1;
   fl::fseek(f->f, f->f_start, fl::io::seek_end);
   return 0;
   #endif
}
References FL_NOEXCEPT, FL_STBV_USE_MEMORY, fl::fseek(), fl::io::seek_end, and fl::io::seek_set.
Referenced by get_seek_page_info(), go_to_page_before(), seek_to_sample_coarse(), stb_vorbis_seek_start(), stb_vorbis_stream_length_in_samples(), and vorbis_find_page().