FastLED: fl::third_party::vorbis::get_bits
get_bits()
static uint32 fl::third_party::vorbis::get_bits (vorb * f, int32_t n) static
Definition at line 1327 of file stb_vorbis.cpp.hpp.
{
   uint32 z;
   if (f->valid_bits < 0) return 0;
   if (f->valid_bits < n) {
      if (n > 24) {
         // the accumulator technique below would not work correctly in this case
         z = get_bits(f, 24);
         z += get_bits(f, n-24) << 24;
         return z;
      }
      if (f->valid_bits == 0) f->acc = 0;
      while (f->valid_bits < n) {
         int32_t z = get8_packet_raw(f);
         if (z == EOP) {
            f->valid_bits = INVALID_BITS;
            return 0;
         }
         f->acc += z << f->valid_bits;
         f->valid_bits += 8;
      }
   }
   FL_ASSERT(f->valid_bits >= n, "valid_bits must be >= n");
   z = f->acc & ((1 << n)-1);
   f->acc >>= n;
   f->valid_bits -= n;
   return z;
}
References EOP, FL_ASSERT, FL_NOEXCEPT, get8_packet_raw(), get_bits(), INVALID_BITS, and z.
Referenced by get_bits(), start_decoder(), vorbis_decode_initial(), and vorbis_decode_packet_rest().