FastLED: fl::third_party::vorbis::get_seek_page_info
get_seek_page_info()
static int32_t fl::third_party::vorbis::get_seek_page_info (stb_vorbis * f, ProbedPage * z) static
Definition at line 4401 of file stb_vorbis.cpp.hpp.
{
   uint8 header[27], lacing[255];
   int32_t i,len;
   // record where the page starts
   z->page_start = stb_vorbis_get_file_offset(f);
   // parse the header
   getn(f, header, 27);
   if (header[0] != 'O' || header[1] != 'g' || header[2] != 'g' || header[3] != 'S')
      return 0;
   getn(f, lacing, header[26]);
   // determine the length of the payload
   len = 0;
   for (i=0; i < header[26]; ++i)
      len += lacing[i];
   // this implies where the page ends
   z->page_end = z->page_start + 27 + header[26] + len;
   // read the last-decoded sample out of the data
   z->last_decoded_sample = header[6] + (header[7] << 8) + ((uint32)header[8] << 16) + ((uint32)header[9] << 24);
   // restore file state to where we were
   set_file_offset(f, z->page_start);
   return 1;
}
References FL_NOEXCEPT, getn(), set_file_offset(), stb_vorbis_get_file_offset(), and z.
Referenced by seek_to_sample_coarse().