FastLED: fl::third_party::vorbis::go_to_page_before
go_to_page_before()
static int32_t fl::third_party::vorbis::go_to_page_before (stb_vorbis * f, uint32_t limit_offset) static
Definition at line 4433 of file stb_vorbis.cpp.hpp.
{
   uint32_t previous_safe, end;
   // now we want to seek back 64K from the limit
   if (limit_offset >= 65536 && limit_offset-65536 >= f->first_audio_page_offset)
      previous_safe = limit_offset - 65536;
   else
      previous_safe = f->first_audio_page_offset;
   set_file_offset(f, previous_safe);
   while (vorbis_find_page(f, &end, nullptr)) {
      if (end >= limit_offset && stb_vorbis_get_file_offset(f) < limit_offset)
         return 1;
      set_file_offset(f, end);
   }
   return 0;
}
References fl::end(), FL_NOEXCEPT, set_file_offset(), stb_vorbis_get_file_offset(), and vorbis_find_page().
Referenced by seek_to_sample_coarse().