FastLED: fl::third_party::vorbis::vorbis_init
vorbis_init()
static void fl::third_party::vorbis::vorbis_init (stb_vorbis * p, const stb_vorbis_alloc * z) static
Definition at line 4036 of file stb_vorbis.cpp.hpp.
{
   memset(p, 0, sizeof(*p)); // nullptr out all malloc'd pointers to start
   if (z) {
      p->alloc = *z;
      p->alloc.alloc_buffer_length_in_bytes &= ~7;
      p->temp_offset = p->alloc.alloc_buffer_length_in_bytes;
   }
   p->eof = 0;
   p->error = VORBIS__no_error;
   p->stream = nullptr;
   p->codebooks = nullptr;
   p->page_crc_tests = -1;
   #ifndef FL_STB_VORBIS_NO_STDIO
   p->close_on_free = false;
   p->f = nullptr;
   #endif
}
References FL_NOEXCEPT, memset(), VORBIS__no_error, and z.
Referenced by stb_vorbis_open_file_section(), stb_vorbis_open_memory(), and stb_vorbis_open_pushdata().