FastLED: fl::third_party::vorbis::maybe_start_packet
maybe_start_packet()
static int32_t fl::third_party::vorbis::maybe_start_packet (vorb * f) static
Definition at line 1246 of file stb_vorbis.cpp.hpp.
{
   if (f->next_seg == -1) {
      int32_t x = get8(f);
      if (f->eof) return false; // EOF at page boundary is not an error!
      if (0x4f != x      ) return error(f, VORBIS_missing_capture_pattern);
      if (0x67 != get8(f)) return error(f, VORBIS_missing_capture_pattern);
      if (0x67 != get8(f)) return error(f, VORBIS_missing_capture_pattern);
      if (0x53 != get8(f)) return error(f, VORBIS_missing_capture_pattern);
      if (!start_page_no_capturepattern(f)) return false;
      if (f->page_flag & PAGEFLAG_continued_packet) {
         // set up enough state that we can read this packet if we want,
         // e.g. during recovery
         f->last_seg = false;
         f->bytes_in_seg = 0;
         return error(f, VORBIS_continued_packet_flag_invalid);
      }
   }
   return start_packet(f);
}
References error(), FL_NOEXCEPT, get8(), PAGEFLAG_continued_packet, start_packet(), start_page_no_capturepattern(), VORBIS_continued_packet_flag_invalid, VORBIS_missing_capture_pattern, and fl::x.
Referenced by stb_vorbis_seek_frame(), and vorbis_decode_initial().