FastLED: fl::third_party::vorbis::vorbis_deinit
vorbis_deinit()
static void fl::third_party::vorbis::vorbis_deinit (stb_vorbis * p) static
Definition at line 3966 of file stb_vorbis.cpp.hpp.
{
   int32_t i,j;
   setup_free(p, p->vendor);
   for (i=0; i < p->comment_list_length; ++i) {
      setup_free(p, p->comment_list[i]);
   }
   setup_free(p, p->comment_list);
   if (p->residue_config) {
      for (i=0; i < p->residue_count; ++i) {
         Residue *r = p->residue_config+i;
         if (r->classdata) {
            for (j=0; j < p->codebooks[r->classbook].entries; ++j)
               setup_free(p, r->classdata[j]);
            setup_free(p, r->classdata);
         }
         setup_free(p, r->residue_books);
      }
   }
   if (p->codebooks) {
      FL_STBV_CHECK(p);
      for (i=0; i < p->codebook_count; ++i) {
         Codebook *c = p->codebooks + i;
         setup_free(p, c->codeword_lengths);
         setup_free(p, c->multiplicands);
         setup_free(p, c->codewords);
         setup_free(p, c->sorted_codewords);
         // c->sorted_values[-1] is the first entry in the array
         setup_free(p, c->sorted_values ? c->sorted_values-1 : nullptr);
      }
      setup_free(p, p->codebooks);
   }
   setup_free(p, p->floor_config);
   setup_free(p, p->residue_config);
   if (p->mapping) {
      for (i=0; i < p->mapping_count; ++i)
         setup_free(p, p->mapping[i].chan);
      setup_free(p, p->mapping);
   }
   FL_STBV_CHECK(p);
   for (i=0; i < p->channels && i < FL_STB_VORBIS_MAX_CHANNELS; ++i) {
      setup_free(p, p->channel_buffers[i]);
      setup_free(p, p->previous_window[i]);
      #ifdef FL_STB_VORBIS_NO_DEFER_FLOOR
      setup_free(p, p->floor_buffers[i]);
      #endif
      setup_free(p, p->finalY[i]);
   }
   for (i=0; i < 2; ++i) {
      setup_free(p, p->A[i]);
      setup_free(p, p->B[i]);
      setup_free(p, p->C[i]);
      setup_free(p, p->window[i]);
      setup_free(p, p->bit_reverse[i]);
   }
   #ifndef FL_STB_VORBIS_NO_STDIO
   if (p->close_on_free) fl::fclose(p->f);
   #endif
}
References fl::third_party::vorbis::Residue::classbook, fl::third_party::vorbis::Residue::classdata, fl::third_party::vorbis::Codebook::codeword_lengths, fl::third_party::vorbis::Codebook::codewords, fl::fclose(), FL_NOEXCEPT, FL_STB_VORBIS_MAX_CHANNELS, FL_STBV_CHECK, fl::third_party::vorbis::Codebook::multiplicands, fl::third_party::vorbis::Residue::residue_books, setup_free(), fl::third_party::vorbis::Codebook::sorted_codewords, and fl::third_party::vorbis::Codebook::sorted_values.
Referenced by stb_vorbis_close(), stb_vorbis_open_file_section(), stb_vorbis_open_memory(), and stb_vorbis_open_pushdata().