FastLED: fl::third_party::vorbis::next_segment
next_segment()
static int32_t fl::third_party::vorbis::next_segment (vorb * f) static
Definition at line 1267 of file stb_vorbis.cpp.hpp.
{
   int32_t len;
   if (f->last_seg) return 0;
   if (f->next_seg == -1) {
      f->last_seg_which = f->segment_count-1; // in case start_page fails
      if (!start_page(f)) { f->last_seg = 1; return 0; }
      if (!(f->page_flag & PAGEFLAG_continued_packet)) return error(f, VORBIS_continued_packet_flag_invalid);
   }
   len = f->segments[f->next_seg++];
   if (len < 255) {
      f->last_seg = true;
      f->last_seg_which = f->next_seg-1;
   }
   if (f->next_seg >= f->segment_count)
      f->next_seg = -1;
   FL_ASSERT(f->bytes_in_seg == 0, "bytes_in_seg must be 0");
   f->bytes_in_seg = len;
   return len;
}
References error(), FL_ASSERT, FL_NOEXCEPT, PAGEFLAG_continued_packet, start_page(), and VORBIS_continued_packet_flag_invalid.
Referenced by get8_packet_raw(), and start_decoder().