FastLED: fl::third_party::vorbis::init_blocksize
init_blocksize()
static int32_t fl::third_party::vorbis::init_blocksize (vorb * f, int32_t b, int32_t n) static
Definition at line 1010 of file stb_vorbis.cpp.hpp.
{
   int32_t n2 = n >> 1, n4 = n >> 2, n8 = n >> 3;
   f->A[b] = (float *) setup_malloc(f, sizeof(float) * n2);
   f->B[b] = (float *) setup_malloc(f, sizeof(float) * n2);
   f->C[b] = (float *) setup_malloc(f, sizeof(float) * n4);
   if (!f->A[b] || !f->B[b] || !f->C[b]) return error(f, VORBIS_outofmem);
   compute_twiddle_factors(n, f->A[b], f->B[b], f->C[b]);
   f->window[b] = (float *) setup_malloc(f, sizeof(float) * n2);
   if (!f->window[b]) return error(f, VORBIS_outofmem);
   compute_window(n, f->window[b]);
   f->bit_reverse[b] = (uint16 *) setup_malloc(f, sizeof(uint16) * n8);
   if (!f->bit_reverse[b]) return error(f, VORBIS_outofmem);
   compute_bitreverse(n, f->bit_reverse[b]);
   return true;
}
References compute_bitreverse(), compute_twiddle_factors(), compute_window(), error(), FL_NOEXCEPT, setup_malloc(), and VORBIS_outofmem.
Referenced by start_decoder().