FastLED: fl::third_party::vorbis::compute_window
compute_window()
static void fl::third_party::vorbis::compute_window (int32_t n, float * window) static
Definition at line 995 of file stb_vorbis.cpp.hpp.
{
   int32_t n2 = n >> 1, i;
   for (i=0; i < n2; ++i)
      window[i] = (float) sin(0.5 * FL_PI * square((float) sin((i - 0 + 0.5) / n2 * 0.5 * FL_PI)));
}
References FL_NOEXCEPT, FL_PI, sin(), and square().
Referenced by init_blocksize().