FastLED: fl::third_party::vorbis::compute_bitreverse
compute_bitreverse()
static void fl::third_party::vorbis::compute_bitreverse (int32_t n, uint16 * rev) static
Definition at line 1002 of file stb_vorbis.cpp.hpp.
{
   int32_t ld = ilog(n) - 1; // ilog is off-by-one from normal definitions
   int32_t i, n8 = n >> 3;
   for (i=0; i < n8; ++i)
      rev[i] = (bit_reverse(i) >> (32-ld+3)) << 2;
}
References bit_reverse(), FL_NOEXCEPT, and ilog().
Referenced by init_blocksize().