FastLED: fl::third_party::vorbis::bit_reverse
bit_reverse()
static uint32_t fl::third_party::vorbis::bit_reverse (uint32_t n) static
Definition at line 744 of file stb_vorbis.cpp.hpp.
{
  n = ((n & 0xAAAAAAAA) >>  1) | ((n & 0x55555555) << 1);
  n = ((n & 0xCCCCCCCC) >>  2) | ((n & 0x33333333) << 2);
  n = ((n & 0xF0F0F0F0) >>  4) | ((n & 0x0F0F0F0F) << 4);
  n = ((n & 0xFF00FF00) >>  8) | ((n & 0x00FF00FF) << 8);
  return (n >> 16) | (n << 16);
}
References FL_NOEXCEPT.
Referenced by codebook_decode_scalar_raw(), compute_accelerated_huffman(), compute_bitreverse(), compute_codewords(), and compute_sorted_huffman().