FastLED: fl::detail::gamma_constexpr::log2_with_msb
log2_with_msb()
i32 fl::detail::gamma_constexpr::log2_with_msb (u32 val, int msb) constexpr
Definition at line 101 of file gamma_lut.h.
{
    // Use multiplication instead of left-shift to avoid UB when (msb - FRAC)
    // is negative (left-shifting a negative value is undefined in C++).
    return static_cast<i32>(
        static_cast<i64>(msb - FRAC) * static_cast<i64>(1LL << FRAC) +
        log2_h0(static_cast<i64>(log2_t(val, msb)))
    );
}
References FL_NOEXCEPT, FRAC, log2_h0(), and log2_t().
Referenced by log2_fp().