FastLED: fl::detail::gamma_constexpr::exp2_pos
exp2_pos()
u32 fl::detail::gamma_constexpr::exp2_pos (u32 x) constexpr
Definition at line 136 of file gamma_lut.h.
{
    return (x >> FRAC) >= 8 ? 0xFFFFFFFFu
        : static_cast<u32>(
            (static_cast<u64>(SCALE << (x >> FRAC)) *
             exp2_frac(x & (SCALE - 1))) >> FRAC
          );
}
References exp2_frac(), FL_NOEXCEPT, FRAC, SCALE, and fl::x.
Referenced by exp2_fp(), and exp2_neg().