FastLED: Key::UpdateIntensity
UpdateIntensity()
void Key::UpdateIntensity (uint32_t now_ms, uint32_t delta_ms)
Definition at line 71 of file Keyboard.cpp.
{
  if (on_) {
    // Intensity can be calculated by a
    float intensity =
        CalcAttackDecayFactor(now_ms - event_time_) *
        VelocityFactor() *
        AttackRemapFactor(now_ms);
    // This is FRAME RATE DEPENDENT FUNCTION!!!!
    // CHANGE TO TIME INDEPENDENT BEFORE SUBMIT.
    intensity_ = (.9f * intensity) + (.1f * intensity_);
  } else if(intensity_ > 0.0f) {  // major cpu hotspot.
    if (sustain_pedal_on_) {
      float delta_s = delta_ms / 1000.f;
      if (intensity_ > .5f) {
        const float kRate = .12f;
        // Time flexible decay function. Stays accurate
        // even as the frame rate changes.
        // Formula: A = Pe^(r*t)
        intensity_ = intensity_ * exp(-delta_s * kRate);
      } else {
        // Quickly fade at the bottom end of the transition.
        const float kRate = .05f;
        intensity_ -= delta_s * kRate;
      }
    } else {
      float delta_s = delta_ms / 1000.f;
      if (intensity_ > .5f) {
        const float kRate = 12.0f;
        // Time flexible decay function. Stays accurate
        // even as the frame rate changes.
        // Formula: A = Pe^(r*t)
        intensity_ = intensity_ * exp(-delta_s * kRate);
      } else {
        // Quickly fade at the bottom end of the transition.
        const float kRate = 2.0f;
        intensity_ -= delta_s * kRate;
      }
    }
    intensity_ = constrain(intensity_, 0.0f, 1.0f);
  }
}
References AttackRemapFactor(), CalcAttackDecayFactor(), event_time_, intensity_, on_, sustain_pedal_on_, and VelocityFactor().
Referenced by Update().