FastLED: setup
setup()
void setup ()
Definition at line 78 of file ServerReal.h.
             {
    Serial.begin(115200);
    Serial.println("HTTP Server Example");
    FastLED.addLeds<WS2812, DATA_PIN, GRB>(leds, NUM_LEDS);
    FastLED.setBrightness(64);
    // ROUTE 1: GET / - Hello message
    server.get("/", [](const fl::http_request& req) {
        Serial.println("[GET /] Hello request");
        fl::http_response response;
        response.status(200)
                .header("Content-Type", "text/plain")
                .body("Hello from FastLED!\n");
        return response;
    });
    // ROUTE 2: GET /status - LED status as JSON
    server.get("/status", [](const fl::http_request& req) {
        Serial.println("[GET /status] Status request");
        fl::json status = fl::json::object();
        status.set("num_leds", NUM_LEDS);
        status.set("brightness", FastLED.getBrightness());
        status.set("uptime_ms", static_cast<fl::i64>(fl::millis()));
        return fl::http_response::ok().json(status);
    });
    // ROUTE 3: POST /color - Set LED color
    server.post("/color", [](const fl::http_request& req) {
        Serial.println("[POST /color] Color change request");
        fl::json body = fl::json::parse(req.body());
        if (body.is_null()) {
            return fl::http_response::bad_request("Invalid JSON");
        }
        int r = body["r"] | 0;
        int g = body["g"] | 0;
        int b = body["b"] | 0;
        fill_solid(leds, NUM_LEDS, fl::CRGB(r, g, b));
        Serial.print("Color set to RGB(");
        Serial.print(r); Serial.print(", ");
        Serial.print(g); Serial.print(", ");
        Serial.print(b); Serial.println(")");
        return fl::http_response::ok("Color updated\n");
    });
    // ROUTE 4: GET /ping - Health check
    server.get("/ping", [](const fl::http_request& req) {
        return fl::http_response::ok("pong\n");
    });
    // Start server
    if (server.start(8080)) {
        Serial.println("Server started on http://localhost:8080/");
        state = RUNNING;
    } else {
        Serial.println("ERROR: Failed to start server");
        Serial.print("Error: ");
        Serial.println(server.last_error().c_str());
        state = ERROR;
    }
    updateLEDs();
    FastLED.show();
}
References fl::asio::http::Response::bad_request(), fl::asio::http::Request::body(), DATA_PIN, ERROR, FastLED, fill_solid(), GRB, fl::json::is_null(), fl::asio::http::Response::json(), leds, fl::millis(), NUM_LEDS, fl::json::object(), fl::asio::http::Response::ok(), fl::json::parse(), RUNNING, Serial, server, fl::json::set(), state, and updateLEDs().