FastLED: updateLEDs
updateLEDs()
void updateLEDs ()
Definition at line 50 of file ServerReal.h.
                  {
    switch (state) {
        case STARTING:
            fill_solid(leds, NUM_LEDS, fl::CRGB(0, 0, beatsin8(60)));  // Blue pulse
            break;
        case RUNNING:
            fill_solid(leds, NUM_LEDS, fl::CRGB(0, 64, 0));  // Green
            break;
        case REQUEST_RECEIVED:
            fill_solid(leds, NUM_LEDS, fl::CRGB(0, 128, 128));  // Cyan
            break;
        case RESPONDED:
            fill_solid(leds, NUM_LEDS, fl::CRGB(64, 0, 64));  // Purple
            break;
        case ERROR:
            fill_solid(leds, NUM_LEDS, fl::CRGB(64, 0, 0));  // Red
            break;
    }
}
References beatsin8(), ERROR, fill_solid(), leds, NUM_LEDS, REQUEST_RECEIVED, RESPONDED, RUNNING, STARTING, and state.
Referenced by loop(), and setup().