FastLED: loop
loop()
void loop ()
Definition at line 152 of file ServerReal.h.
            {
    // Update server multiple times per loop for better responsiveness
    // Process up to 10 update cycles per loop iteration
    fl::size total_processed = 0;
    for (int i = 0; i < 10; ++i) {
        fl::size processed = server.update();
        total_processed += processed;
        if (processed == 0) break;  // No more pending requests
    }
    if (total_processed > 0) {
        Serial.print("Processed ");
        Serial.print(static_cast<int>(total_processed));
        Serial.println(" request(s)");
        state = REQUEST_RECEIVED;
        lastEventTime = fl::millis();
        // After processing, flash purple for "responded"
        state = RESPONDED;
    }
    autoReset();
    updateLEDs();
    FastLED.show();
    delay(10);  // 10ms delay between cycles - up to 1000 requests/second possible
}
References autoReset(), FastLED, lastEventTime, fl::millis(), REQUEST_RECEIVED, RESPONDED, Serial, server, state, and updateLEDs().