FastLED: setup
setup()
void setup ()
Definition at line 182 of file Chromancer.ino.
             {
    Serial.begin(115200);
    Serial.println("*** LET'S GOOOOO ***");
    Serial.println("JSON SCREENMAP");
    Serial.println(JSON_SCREEN_MAP);
    fl::flat_map<fl::string, fl::ScreenMap> segmentMaps;
    fl::ScreenMap::ParseJson(JSON_SCREEN_MAP, &segmentMaps);
    fl::printf("Parsed %d segment maps\n", int(segmentMaps.size()));
    for (auto kv : segmentMaps) {
        Serial.print(kv.first.c_str());
        Serial.print(" ");
        Serial.println(kv.second.getLength());
    }
    // fl::ScreenMap screenmaps[4];
    fl::ScreenMap red, black, green, blue;
    bool ok = true;
    auto red_it = segmentMaps.find("red_segment");
    ok = (red_it != segmentMaps.end()) && ok;
    if (red_it != segmentMaps.end()) red = red_it->second;
    auto black_it = segmentMaps.find("back_segment");
    ok = (black_it != segmentMaps.end()) && ok;
    if (black_it != segmentMaps.end()) black = black_it->second;
    auto green_it = segmentMaps.find("green_segment");
    ok = (green_it != segmentMaps.end()) && ok;
    if (green_it != segmentMaps.end()) green = green_it->second;
    auto blue_it = segmentMaps.find("blue_segment");
    ok = (blue_it != segmentMaps.end()) && ok;
    if (blue_it != segmentMaps.end()) blue = blue_it->second;
    if (!ok) {
        Serial.println("Failed to get all segment maps");
        return;
    }
    CRGB* red_leds = leds[RedStrip];
    CRGB* black_leds = leds[BlackStrip];
    CRGB* green_leds = leds[GreenStrip];
    CRGB* blue_leds = leds[BlueStrip];
    FastLED.addLeds<WS2812, 2>(black_leds, lengths[BlackStrip]).setScreenMap(black);
    FastLED.addLeds<WS2812, 3>(green_leds, lengths[GreenStrip]).setScreenMap(green);
    FastLED.addLeds<WS2812, 1>(red_leds, lengths[RedStrip]).setScreenMap(red);
    FastLED.addLeds<WS2812, 4>(blue_leds, lengths[BlueStrip]).setScreenMap(blue);
    FastLED.show();
}
References BlackStrip, BlueStrip, fl::flat_map< Key, Value, Less >::end(), FastLED, fl::flat_map< Key, Value, Less >::find(), GreenStrip, JSON_SCREEN_MAP, leds, lengths, fl::ScreenMap::ParseJson(), fl::printf(), RedStrip, Serial, and fl::flat_map< Key, Value, Less >::size().