FastLED: fl::s4x12::atan2
atan2()
static FASTLED_FORCE_INLINE s4x12 fl::s4x12::atan2 (s4x12 y, s4x12 x) inline static
Definition at line 177 of file s4x12.h.
{
        constexpr s4x12 pi(3.1415926f);
        constexpr s4x12 pi_over_2(1.5707963f);
        if (x.mValue == 0 && y.mValue == 0) return s4x12();
        if (x.mValue == 0) return y.mValue > 0 ? pi_over_2 : -pi_over_2;
        if (y.mValue == 0) return x.mValue > 0 ? s4x12() : pi;
        s4x12 ax = abs(x);
        s4x12 ay = abs(y);
        s4x12 a;
        if (ax >= ay) {
            a = atan_unit(ay / ax);
        } else {
            a = pi_over_2 - atan_unit(ax / ay);
        }
        if (x.mValue < 0) a = pi - a;
        if (y.mValue < 0) a = -a;
        return a;
    }
References s4x12(), abs(), atan_unit(), FASTLED_FORCE_INLINE, FL_NOEXCEPT, fl::x, and fl::y.
Referenced by acos(), and asin().