FastLED: CalcDecayFactor
CalcDecayFactor()
float CalcDecayFactor (bool sustain_pedal_on, bool key_on, int key_idx, float velocity, bool dampened_key, float time_elapsed_ms)
Definition at line 70 of file util.cpp.
{
  static const float kDefaultDecayTime = .2f * 1000.f;
  static const float kBias = 1.10;
  float decay_time = kDefaultDecayTime;  // default - no sustain.
  if (key_on || sustain_pedal_on || !dampened_key) {
    decay_time = MapDecayTime(key_idx) * max(0.25f, velocity);
  }
  // decay_interp is a value which starts off as 1.0 to signify the start of the
  // key press and gradually decreases to 0.0. For example, if the decay time is 1 second
  // then at the time = 0s, decay_interp is 1.0, and after one second decay_interp is 0.0
  float intensity_factor = mapf(time_elapsed_ms,
                                0.0, decay_time * kBias,
                                1.0, 0.0);  // Startup at full brightness -> no brighness.
  // When decay_interp reaches 0, the lighting sequence is effectively finished. However
  // because this is time based and time keeps on going this value will move into negative
  // territory, we take care of this by simply clamping all negative values to 0.0.
  intensity_factor = constrain(intensity_factor, 0.0f, 1.0f);
  return intensity_factor;
}
References MapDecayTime(), and mapf().
Referenced by Key::CalcAttackDecayFactor(), and anonymous_namespace{Painter.cpp}::CalcLuminance().