FastLED: fl::test::Approx::Approx
Approx()
fl::test::Approx::Approx (double value) inline explicit
Definition at line 398 of file fltest.h.
        : mValue(value)
        , mEpsilon(1e-5)  // Default relative epsilon
        , mMargin(0.0)    // Default no absolute margin
        , mScale(1.0)
    {}
References FL_NOEXCEPT, mEpsilon, mMargin, mScale, mValue, and value().
Referenced by epsilon(), margin(), operator!=, operator!=, operator<, operator<=, operator==, operator==, operator>, operator>=, and scale().