FastLED: fl::Corkscrew::readFrom
readFrom()
void fl::Corkscrew::readFrom (const fl::Grid< CRGB > & source_grid, bool use_multi_sampling = true) private
Definition at line 251 of file corkscrew.cpp.
{
    if (use_multi_sampling) {
        readFromMulti(source_grid);
        return;
    }
    // Get or create the input surface
    auto target_surface = getOrCreateInputSurface();
    // Clear surface first
    target_surface->clear();
    // Iterate through each LED in the corkscrew
    for (fl::size led_idx = 0; led_idx < mNumLeds; ++led_idx) {
        // Get the rectangular coordinates for this corkscrew LED
        vec2f rect_pos = at_no_wrap(static_cast<fl::u16>(led_idx));
        // Convert to integer coordinates for indexing
        vec2i16 coord(static_cast<fl::i16>(rect_pos.x + 0.5f),
                      static_cast<fl::i16>(rect_pos.y + 0.5f));
        // Clamp coordinates to grid bounds
        coord.x = MAX(0, MIN(coord.x, static_cast<fl::i16>(source_grid.width()) - 1));
        coord.y = MAX(0, MIN(coord.y, static_cast<fl::i16>(source_grid.height()) - 1));
        // Sample from the source fl::Grid using its at() method
        CRGB sampled_color = source_grid.at(coord.x, coord.y);
        // Store the sampled color directly in the target surface
        if (led_idx < target_surface->size()) {
            target_surface->data()[led_idx] = sampled_color;
        }
    }
}
References fl::Grid< T >::at(), at_no_wrap(), getOrCreateInputSurface(), fl::Grid< T >::height(), MAX, MIN, mNumLeds, readFromMulti(), size(), fl::Grid< T >::width(), fl::vec2< T >::x, and fl::vec2< T >::y.