FastLED: fl::Corkscrew::getOrCreateInputSurface
getOrCreateInputSurface()
fl::shared_ptr< fl::Grid< CRGB > > & fl::Corkscrew::getOrCreateInputSurface ()
Definition at line 473 of file corkscrew.cpp.
{
    if (!mInputSurface) {
        // Create a new Grid with cylinder dimensions using PSRAM allocation
        mInputSurface = fl::make_shared<fl::Grid<CRGB>>(mWidth, mHeight);
    }
    return mInputSurface;
}
References fl::make_shared(), mHeight, mInputSurface, and mWidth.
Referenced by data(), draw(), fillInputSurface(), rawData(), readFrom(), readFromMulti(), and surface().