FastLED: fl::Corkscrew::calculateTileAtWrap
calculateTileAtWrap()
Tile2x2_u8_wrap fl::Corkscrew::calculateTileAtWrap (float i) const private
Definition at line 177 of file corkscrew.cpp.hpp.
{
    // This is a splatted pixel, but wrapped around the cylinder.
    // This is useful for rendering the corkscrew in a cylindrical way.
    Tile2x2_u8 tile = at_splat_extrapolate(i);
    Tile2x2_u8_wrap::Entry data[2][2];
    vec2<u16> origin = tile.origin();
    for (fl::u8 x = 0; x < 2; x++) {
        for (fl::u8 y = 0; y < 2; y++) {
            // For each pixel in the tile, map it to the cylinder so that each subcomponent
            // is mapped to the correct position on the cylinder.
            vec2<u16> pos = origin + vec2<u16>(x, y);
            // now wrap the x-position
            pos.x = fl::fmodf(pos.x, static_cast<float>(mWidth));
            data[x][y] = {pos, tile.at(x, y)};
        }
    }
    return Tile2x2_u8_wrap(data);
}
References fl::Tile2x2_u8::at(), at_splat_extrapolate(), data(), fl::fmodf(), mWidth, fl::Tile2x2_u8::origin(), pos, fl::x, and fl::y.
Referenced by at_wrap(), and initializeCache().