FastLED: fl::Corkscrew::draw
draw()
void fl::Corkscrew::draw (bool use_multi_sampling = true)
Definition at line 317 of file corkscrew.cpp.
{
    // The draw method should map from the rectangular surface to the LED pixel data
    // This is the reverse of readFrom - we read from our surface and populate LED data
    auto source_surface = getOrCreateInputSurface();
    // Make sure we have pixel storage
    if (mPixelStorage.empty()) {
        // If no pixel storage is configured, there's nothing to draw to
        return;
    }
    CRGB* led_data = rawData();
    if (!led_data) return;
    if (use_multi_sampling) {
        // Use multi-sampling to get better accuracy
        for (fl::size led_idx = 0; led_idx < mNumLeds; ++led_idx) {
            // Get the wrapped tile for this LED position
            Tile2x2_u8_wrap tile = at_wrap(static_cast<float>(led_idx));
            // Accumulate color from the 4 sample points with their weights
            fl::u32 r_accum = 0, g_accum = 0, b_accum = 0;
            fl::u32 total_weight = 0;
            // Sample from each of the 4 corners of the tile
            for (fl::u8 x = 0; x < 2; x++) {
                for (fl::u8 y = 0; y < 2; y++) {
                    const auto& entry = tile.at(x, y);
                    vec2<u16> pos = entry.first;
                    fl::u8 weight = entry.second;
                    // Bounds check for the source surface
                    if (pos.x < source_surface->width() && pos.y < source_surface->height()) {
                        // Sample from the source surface
                        CRGB sample_color = source_surface->at(pos.x, pos.y);
                        // Accumulate weighted color components
                        r_accum += static_cast<fl::u32>(sample_color.r) * weight;
                        g_accum += static_cast<fl::u32>(sample_color.g) * weight;
                        b_accum += static_cast<fl::u32>(sample_color.b) * weight;
                        total_weight += weight;
                    }
                }
            }
            // Calculate final color by dividing by total weight
            CRGB final_color = CRGB::Black;
            if (total_weight > 0) {
                final_color.r = static_cast<fl::u8>(r_accum / total_weight);
                final_color.g = static_cast<fl::u8>(g_accum / total_weight);
                final_color.b = static_cast<fl::u8>(b_accum / total_weight);
            }
            // Store the result in the LED data
            led_data[led_idx] = final_color;
        }
    } else {
        // Simple non-multi-sampling version
        for (fl::size led_idx = 0; led_idx < mNumLeds; ++led_idx) {
            // Get the rectangular coordinates for this corkscrew LED
            vec2f rect_pos = at_no_wrap(static_cast<fl::u16>(led_idx));
            // Convert to integer coordinates for indexing
            vec2i16 coord(static_cast<fl::i16>(rect_pos.x + 0.5f),
                          static_cast<fl::i16>(rect_pos.y + 0.5f));
            // Clamp coordinates to surface bounds
            coord.x = MAX(0, MIN(coord.x, static_cast<fl::i16>(source_surface->width()) - 1));
            coord.y = MAX(0, MIN(coord.y, static_cast<fl::i16>(source_surface->height()) - 1));
            // Sample from the source surface
            CRGB sampled_color = source_surface->at(coord.x, coord.y);
            // Store the sampled color in the LED data
            led_data[led_idx] = sampled_color;
        }
    }
}
References fl::Tile2x2_u8_wrap::at(), at_no_wrap(), at_wrap(), CRGB::Black, getOrCreateInputSurface(), MAX, MIN, mNumLeds, mPixelStorage, pos, rawData(), fl::vec2< T >::x, x, fl::vec2< T >::y, and y.