FastLED: fl::Corkscrew::rawData
rawData()
CRGB * fl::Corkscrew::rawData ()
Definition at line 219 of file corkscrew.cpp.
{
    // Use variant storage if available, otherwise fall back to input surface
    if (!mPixelStorage.empty()) {
        if (mPixelStorage.template is<fl::span<CRGB>>()) {
            return mPixelStorage.template get<fl::span<CRGB>>().data();
        } else if (mPixelStorage.template is<fl::vector<CRGB, fl::allocator_psram<CRGB>>>()) {
            return mPixelStorage.template get<fl::vector<CRGB, fl::allocator_psram<CRGB>>>().data();
        }
    }
    // Fall back to input surface data
    auto surface = getOrCreateInputSurface();
    return surface->data();
}
References data(), fl::get(), getOrCreateInputSurface(), mPixelStorage, and surface().
Referenced by draw().