FastLED: fl::Corkscrew::readFromMulti
readFromMulti()
void fl::Corkscrew::readFromMulti (const fl::Grid< CRGB > & target_grid) const private
Definition at line 396 of file corkscrew.cpp.
{
    // Get the target surface and clear it
    auto target_surface = const_cast<Corkscrew*>(this)->getOrCreateInputSurface();
    target_surface->clear();
    const u16 width = static_cast<u16>(source_grid.width());
    const u16 height = static_cast<u16>(source_grid.height());
    // Iterate through each LED in the corkscrew
    for (fl::size led_idx = 0; led_idx < mNumLeds; ++led_idx) {
        // Get the wrapped tile for this LED position
        Tile2x2_u8_wrap tile = at_wrap(static_cast<float>(led_idx));
        // Accumulate color from the 4 sample points with their weights
        fl::u32 r_accum = 0, g_accum = 0, b_accum = 0;
        fl::u32 total_weight = 0;
        // Sample from each of the 4 corners of the tile
        for (fl::u8 x = 0; x < 2; x++) {
            for (fl::u8 y = 0; y < 2; y++) {
                const auto& entry = tile.at(x, y);
                vec2<u16> pos = entry.first;   // position is the first element of the pair
                fl::u8 weight = entry.second; // weight is the second element of the pair
                // Bounds check for the source grid
                if (pos.x >= 0 && pos.x < width &&
                    pos.y >= 0 && pos.y < height) {
                    // Sample from the source grid
                    CRGB sample_color = source_grid.at(pos.x, pos.y);
                    // Accumulate weighted color components
                    r_accum += static_cast<fl::u32>(sample_color.r) * weight;
                    g_accum += static_cast<fl::u32>(sample_color.g) * weight;
                    b_accum += static_cast<fl::u32>(sample_color.b) * weight;
                    total_weight += weight;
                }
            }
        }
        // Calculate final color by dividing by total weight
        CRGB final_color = CRGB::Black;
        if (total_weight > 0) {
            final_color.r = static_cast<fl::u8>(r_accum / total_weight);
            final_color.g = static_cast<fl::u8>(g_accum / total_weight);
            final_color.b = static_cast<fl::u8>(b_accum / total_weight);
        }
        // Store the result in the target surface at the LED index position
        auto target_surface = const_cast<Corkscrew*>(this)->getOrCreateInputSurface();
        if (led_idx < target_surface->size()) {
            target_surface->data()[led_idx] = final_color;
        }
    }
}
References Corkscrew(), fl::Grid< T >::at(), fl::Tile2x2_u8_wrap::at(), at_wrap(), CRGB::Black, fl::Grid< T >::clear(), getOrCreateInputSurface(), fl::Grid< T >::height(), mNumLeds, pos, size(), fl::Grid< T >::width(), x, and y.
Referenced by readFrom().