FastLED: fl::noiseCylinderCRGB
noiseCylinderCRGB()
CRGB fl::noiseCylinderCRGB (float angle, float height, u32 time, float radius = 1.0f)
Generate CRGB noise for a cylinder pattern.
Samples three z-slices of 3D Perlin noise to create independent red, green, and blue components (direct RGB, not HSV conversion). Maps the angle around the circumference using sin/cos, and samples height directly.
Parameters
angle Position around the cylinder (radians, 0 to 2π)
height Vertical position on the cylinder
time Animation time parameter
radius Noise zoom level (level of detail). Larger values = coarser pattern, smaller = more detail (default 1.0)
Returns
CRGB color with 8-bit components
Definition at line 208 of file noise.cpp.hpp.
{
  // Convert cylindrical coordinates to cartesian
  // angle: azimuth around cylinder (0 to 2π)
  // height: vertical position (used directly)
  // x = cos(angle)
  // y = sin(angle)
  // z = height
  float x = fl::cosf(angle);
  float y = fl::sinf(angle);
  // Map sin/cos values from [-1, 1] to [0, 0xFFFF]
  // This ensures positive values for uint32_t conversion
  u32 nx = static_cast<u32>((x + 1.0f) * 0.5f * radius * 0xffff);
  u32 ny = static_cast<u32>((y + 1.0f) * 0.5f * radius * 0xffff);
  u32 nz = static_cast<u32>(height * radius * 0xffff);
  // Sample three different t-slices for R, G, B components (direct RGB)
  // Using offsets 0x0, 0x10000, 0x20000 to separate them in noise space
  u16 r16_raw = inoise16(nx, ny, nz, time);
  u16 g16_raw = inoise16(nx, ny, nz, time + 0x10000);
  u16 b16_raw = inoise16(nx, ny, nz, time + 0x20000);
  // Rescale from observed noise range to full 0-65535 range using global extents
  u16 r16 = rescaleNoiseValue16(r16_raw);
  u16 g16 = rescaleNoiseValue16(g16_raw);
  u16 b16 = rescaleNoiseValue16(b16_raw);
  // Scale down to 8-bit
  u8 r = fl::int_scale<u16, u8>(r16);
  u8 g = fl::int_scale<u16, u8>(g16);
  u8 b = fl::int_scale<u16, u8>(b16);
  return CRGB(r, g, b);
}
References cosf(), height, inoise16(), rescaleNoiseValue16(), sinf(), time(), x, and y.