FastLED: fl::noiseCylinderHSV16
noiseCylinderHSV16()
HSV16 fl::noiseCylinderHSV16 (float angle, float height, u32 time, float radius = 1.0f)
Cylinder noise functions - sample three z-slices for independent component evolution.
Generate HSV16 noise for a cylinder pattern.
Samples three z-slices of 3D Perlin noise (at time, time+0x10000, time+0x20000) to create independent hue, saturation, and value components. Maps the angle around the circumference using sin/cos, and samples height directly.
Parameters
angle Position around the cylinder (radians, 0 to 2π)
height Vertical position on the cylinder
time Animation time parameter
radius Noise zoom level (level of detail). Larger values = coarser pattern, smaller = more detail (default 1.0)
Returns
HSV16 color with 16-bit components
Definition at line 166 of file noise.cpp.hpp.
{
  // Convert cylindrical coordinates to cartesian
  // angle: azimuth around cylinder (0 to 2π)
  // height: vertical position (used directly)
  // x = cos(angle)
  // y = sin(angle)
  // z = height
  float x = fl::cosf(angle);
  float y = fl::sinf(angle);
  // Map sin/cos values from [-1, 1] to [0, 0xFFFF]
  // This ensures positive values for uint32_t conversion
  u32 nx = static_cast<u32>((x + 1.0f) * 0.5f * radius * 0xffff);
  u32 ny = static_cast<u32>((y + 1.0f) * 0.5f * radius * 0xffff);
  u32 nz = static_cast<u32>(height * radius * 0xffff);
  // Sample three different t-slices for H, S, V components
  // Using offsets 0x0, 0x10000, 0x20000 to separate them in noise space
  u16 h_raw = inoise16(nx, ny, nz, time);
  u16 s_raw = inoise16(nx, ny, nz, time + 0x10000);
  u16 v_raw = inoise16(nx, ny, nz, time + 0x20000);
  // Rescale from observed noise range to full 0-65535 range using global extents
  u16 h = rescaleNoiseValue16(h_raw);
  u16 s = rescaleNoiseValue16(s_raw);
  u16 v = rescaleNoiseValue16(v_raw);
  return HSV16(h, s, v);
}
References cosf(), height, inoise16(), rescaleNoiseValue16(), sinf(), time(), x, and y.
Referenced by noiseCylinderHSV8().