FastLED: fl::UINumberFieldImpl::setValue
setValue()
void fl::UINumberFieldImpl::setValue (double value) inline
Definition at line 152 of file ui_impl.h.
{ mValue = MAX(mMin, MIN(mMax, value)); }
References MAX, MIN, mMax, mMin, mValue, and value().
Referenced by operator=(), operator=(), and fl::UINumberField::setValue().