FastLED: fl::SpiEncoder::spiEncoderForChipset
spiEncoderForChipset()
static SpiEncoder fl::SpiEncoder::spiEncoderForChipset (SpiChipset chipset, u32 speed_hz_override = 0) inline static
Look up the default SpiEncoder for a given chipset.
Parameters
chipset The SPI chipset enum value
speed_hz_override If nonzero, overrides the chipset's default clock speed
Returns
SpiEncoder with correct chipset and clock speed
Definition at line 151 of file spi.h.
{
        SpiEncoder enc = {chipset, 6000000}; // fallback
        switch (chipset) {
            case SpiChipset::APA102:    enc = apa102(); break;
            case SpiChipset::APA102HD:  enc = apa102HD(); break;
            case SpiChipset::DOTSTAR:   enc = dotstar(); break;
            case SpiChipset::DOTSTARHD: enc = dotstarHD(); break;
            case SpiChipset::SK9822:    enc = sk9822(); break;
            case SpiChipset::SK9822HD:  enc = sk9822HD(); break;
            case SpiChipset::HD107:     enc = hd107(); break;
            case SpiChipset::HD107HD:   enc = hd107HD(); break;
            case SpiChipset::HD108:     enc = hd108(); break;
            case SpiChipset::WS2801:    enc = ws2801(); break;
            case SpiChipset::WS2803:    enc = ws2803(); break;
            case SpiChipset::P9813:     enc = p9813(); break;
            case SpiChipset::LPD8806:   enc = lpd8806(); break;
            case SpiChipset::LPD6803:   enc = lpd6803(); break;
            case SpiChipset::SM16716:   enc = sm16716(); break;
            default: break; // unknown chipset: keep fallback
        }
        if (speed_hz_override != 0) {
            enc.clock_hz = speed_hz_override;
        }
        return enc;
    }
References fl::APA102, apa102(), fl::APA102HD, apa102HD(), chipset, clock_hz, fl::DOTSTAR, dotstar(), fl::DOTSTARHD, dotstarHD(), FL_NOEXCEPT, fl::HD107, hd107(), fl::HD107HD, hd107HD(), fl::HD108, hd108(), fl::LPD6803, lpd6803(), fl::LPD8806, lpd8806(), fl::P9813, p9813(), fl::SK9822, sk9822(), fl::SK9822HD, sk9822HD(), fl::SM16716, sm16716(), fl::WS2801, ws2801(), fl::WS2803, and ws2803().