FastLED: fl::anonymous_namespace{json.cpp.hpp}::JsonBuilder::push_value
push_value()
void fl::anonymous_namespace{json.cpp.hpp}::JsonBuilder::push_value (const fl::shared_ptr< json_value > & val) inline private
Definition at line 893 of file json.cpp.hpp.
{
        if (mStack.empty()) {
            mRoot = val;
        } else {
            StackFrame& top = mStack.back();
            if (top.type == StackFrame::OBJECT) {
                // Attach to object with pending key
                auto obj = top.value->data.ptr<json_object>();
                if (obj && !top.pending_key.empty()) {
                    (*obj)[top.pending_key] = val;
                    top.pending_key.clear();
                }
            } else {
                // Attach to array
                auto arr = top.value->data.ptr<json_array>();
                if (arr) {
                    arr->push_back(val);
                }
            }
        }
    }
References fl::basic_string::clear(), fl::basic_string::empty(), mRoot, mStack, fl::anonymous_namespace{json.cpp.hpp}::JsonBuilder::StackFrame::OBJECT, fl::anonymous_namespace{json.cpp.hpp}::JsonBuilder::StackFrame::pending_key, fl::anonymous_namespace{json.cpp.hpp}::JsonBuilder::StackFrame::type, and fl::anonymous_namespace{json.cpp.hpp}::JsonBuilder::StackFrame::value.
Referenced by on_token().