FastLED: fl::anonymous_namespace{json.cpp.hpp}::JsonBuilder::parse_float_array
parse_float_array()
template<typename T> bool fl::anonymous_namespace{json.cpp.hpp}::JsonBuilder::parse_float_array (const fl::span< const char > & span, fl::vector< T > & out_vec) inline private
Definition at line 834 of file json.cpp.hpp.
{
        const char* p = span.data();
        const char* end = p + span.size();
        while (p < end) {
            // Skip whitespace
            while (p < end && (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r')) p++;
            if (p >= end) break;
            // Parse number
            const char* num_start = p;
            bool is_float = false;
            if (*p == '-') p++;
            while (p < end && *p >= '0' && *p <= '9') p++;
            if (p < end && *p == '.') {
                is_float = true;
                p++;
                while (p < end && *p >= '0' && *p <= '9') p++;
            }
            if (p < end && (*p == 'e' || *p == 'E')) {
                is_float = true;
                p++;
                if (p < end && (*p == '+' || *p == '-')) p++;
                while (p < end && *p >= '0' && *p <= '9') p++;
            }
            T val;
            if (is_float) {
#if FL_PLATFORM_HAS_LARGE_MEMORY
                // Bit-twiddling parse -> IEEE 754 bit pattern -> bit-cast to float.
                // The `static_cast<T>` from `float` is the caller's responsibility
                // (e.g. T=float costs nothing; T=int pulls one __aeabi_f2iz at the
                // call site, which we accept per the "user opts in" mandate).
                const u32 bits = fl::ieee754_parse_decimal(num_start, p - num_start);
                val = static_cast<T>(fl::bit_cast<float>(bits));
#else
                // Low-memory gate per FastLED #3082: float JSON literals in
                // packed-array parse path saturate to zero. The integer-only
                // RPC contract on LPC8xx / AVR never emits floats here.
                val = static_cast<T>(0);
#endif
            } else {
                val = static_cast<T>(fl::parseInt(num_start, p - num_start));
            }
            out_vec.push_back(val);
            // Skip whitespace
            while (p < end && (*p == ' ' || *p == '\t' || *p == '\n' || *p == '\r')) p++;
            // Skip comma
            if (p < end && *p == ',') p++;
        }
        return true;
    }
References fl::bit_cast(), fl::span< T, Extent >::data(), fl::end(), fl::ieee754_parse_decimal(), fl::parseInt(), fl::vector< T >::push_back(), and fl::span< T, Extent >::size().
Referenced by on_token().