#!/bin/bash

# cd to the directory of the script
cd "$(dirname "$0")"

rm -rf .venv
rm -rf .build
rm -rf .pio
rm -rf ci/tmp
rm -rf tests/.build

# remove any CMakeCache.txt files
find . -name "CMakeCache.txt" -type f -delete