#!/bin/bash
set -e

cd "$(dirname "$0")"

# if .venv not found
if [ ! -d .venv ]; then
    # create virtual environment
    ./install
fi

if [ "$1" = "--cpp" ]; then
    if [ -n "$2" ]; then
        # Compile and run specific C++ test
        time uv run ci/cpp_test_run.py --test "$2"
    else
        # Compile all C++ tests
        # uv run ci/cpp_test_compile.py
        time uv run ci/cpp_test_run.py
    fi
else
    # Run all tests
    uv run ci/cpp_test_compile.py
    uv run ci/cpp_test_run.py
    uv run ci/ci-compile-native.py
    uv run pytest ci/tests
    uv run pio check --skip-packages --src-filters="+<src/>" --severity=medium --fail-on-defect=high --flags "--inline-suppr --enable=all --std=c++17"
fi
