#!/bin/bash

# Push instructions (x86_64)
#   0. Only do this on x86_64.
#   1. docker login
#   2. ./wasm (builds the image and then runs a container)
#     a. This will create an image tagged by fastled-wasm-compiler
#   3. docker tag fastled-wasm-compiler:latest niteris/fastled-wasm:latest
#   4. docker push niteris/fastled-wasm:latest
#
# Pull instructions (arm)
#   0. Only do this on Mac-arm.
#   1. docker login
#   2. ./wasm (builds the image and then runs a container)
#     a. This will create an image tagged by fastled-wasm-compiler
#   3. docker tag fastled-wasm-compiler:latest niteris/fastled-wasm:latest-arm
#   4. docker push niteris/fastled-wasm:latest-arm


echo "Compiles sketch for wasm"
build_flag="-b"
uv run ci/wasm_compile.py $build_flag --open "$@"
