FastLED: setup
setup()
void setup ()
Definition at line 106 of file Corkscrew.h.
             {
    int width = corkscrew.cylinderWidth();
    int height = corkscrew.cylinderHeight();
    frameBuffer.reset(width, height);
    XYMap xyMap = XYMap::constructRectangularGrid(width, height, 0);
    CRGB *leds = frameBuffer.data();
    size_t num_leds = frameBuffer.size();
    CLEDController *controller =
        &FastLED.addLeds<WS2812, 3, BGR>(leds, num_leds);
    // NEW: Create ScreenMap directly from Corkscrew using toScreenMap()
    // This maps each LED index to its exact position on the cylindrical surface
    fl::ScreenMap corkscrewScreenMap = corkscrew.toScreenMap(0.2f);
    // Alternative: Create ScreenMap from rectangular XYMap (old way)
    // fl::ScreenMap screenMap = xyMap.toScreenMap();
    // screenMap.setDiameter(.2f);
    // Set the corkscrew screen map for the controller
    // This allows the web interface to display the actual corkscrew shape
    controller->setScreenMap(corkscrewScreenMap);
    // Initialize caching based on UI setting
    corkscrew.setCachingEnabled(cachingEnabled.value());
}
References fl::BGR, cachingEnabled(), XYMap::constructRectangularGrid(), controller, corkscrew(), FastLED, frameBuffer, leds, and xyMap.