FastLED: loop
loop()
void loop ()
Definition at line 132 of file Corkscrew.h.
            {
    fl::clear(frameBuffer);
    static float pos = 0; // okay static in header
    pos += speed.value();
    if (pos > corkscrew.size() - 1) {
        pos = 0; // Reset to the beginning
    }
    // Update caching setting if it changed
    static bool lastCachingState = cachingEnabled.value(); // okay static in header
    if (lastCachingState != cachingEnabled.value()) {
        corkscrew.setCachingEnabled(cachingEnabled.value());
        lastCachingState = cachingEnabled.value();
    }
    if (allWhite) {
        for (size_t i = 0; i < frameBuffer.size(); ++i) {
            frameBuffer.span()[i] = CRGB(8, 8, 8);
        }
    }
    if (splatRendering) {
        fl::Tile2x2_u8_wrap pos_tile = corkscrew.at_wrap(pos);
        const fl::CRGB color = fl::CRGB::Blue;
        // Draw each pixel in the 2x2 tile using the new wrapping API
        for (int dx = 0; dx < 2; ++dx) {
            for (int dy = 0; dy < 2; ++dy) {
                auto data = pos_tile.at(dx, dy);
                fl::vec2<fl::u16> wrapped_pos = data.first; // Already wrapped position
                uint8_t alpha = data.second;      // Alpha value
                if (alpha > 0) { // Only draw if there's some alpha
                    fl::CRGB c = color;
                    c.nscale8(alpha); // Scale the color by the alpha value
                    frameBuffer.at(wrapped_pos.x, wrapped_pos.y) = c;
                }
            }
        }
    } else {
        // None splat rendering, looks aweful.
        fl::vec2f pos_vec2f = corkscrew.at_no_wrap(pos);
        fl::vec2<fl::u16> pos_i16 = fl::vec2<fl::u16>(round(pos_vec2f.x), round(pos_vec2f.y));
        // Now map the cork screw position to the cylindrical buffer that we
        // will draw.
        frameBuffer.at(pos_i16.x, pos_i16.y) =
            fl::CRGB::Blue; // Draw a blue pixel at (w, h)
    }
    FastLED.show();
}
References allWhite, fl::Tile2x2_u8_wrap::at(), fl::CRGB::Blue, cachingEnabled(), fl::clear(), corkscrew(), FastLED, frameBuffer, fl::CRGB::nscale8(), pos, round, speed, splatRendering(), fl::vec2< T >::x, and fl::vec2< T >::y.