// AUTO-GENERATED by ci/color_profile_generator.py -- DO NOT EDIT.
//
// Source: FastLED/datasheets measured-profiles/
// Datasheets commit: dfb9a6457d8e2cfff6f6392f115ec52d3b204ab0
// Generated on: 2026-09-09
//
//   fixture/rgb/none/synthetic-r1  sha256:f0c26100906d5eaaf9c8027f8c922fd4cf09aaca30629cab36cf76edabc653cf

#include "fl/gfx/colorimetric_response.h"

namespace fl {
namespace generated_profiles {

// fixture/rgb/none/synthetic-r1
// sha256:f0c26100906d5eaaf9c8027f8c922fd4cf09aaca30629cab36cf76edabc653cf
constexpr colorimetric_response::EmitterProfile FIXTURE_RGB_NONE_SYNTHETIC_R1 = colorimetric_response::EmitterProfile::rgb(
    "fixture/rgb/none/synthetic-r1",
    Chromaticity(0.691500f, 0.308300f),
    Chromaticity(0.170000f, 0.796900f),
    Chromaticity(0.135500f, 0.039900f),
    0.212600f, 0.715200f, 0.072200f,
    "measured", "synthetic-r1");
// native code depth: 8
// floating alias candidate: FIXTURE_RGB_NONE

// Catalogued, and deliberately not generated. Each of these
// is a real part whose published optical data cannot support an
// EmitterProfile; see ci/color_profile_generator.py.
//
//   ws2812b/5050/none/datasheet-r1
//     - runtime_admissible is not true (absent counts as false, even when channels carry usable observations)
//     - topology is absent or unknown; firmware generation requires one of rgb, rgbw, rgbww
//     - channel 'red' lacks runtime_admissible: true, a finite chromaticity {x, y}, a finite relative_y
//     - channel 'green' lacks runtime_admissible: true, a finite chromaticity {x, y}, a finite relative_y
//     - channel 'blue' lacks runtime_admissible: true, a finite chromaticity {x, y}, a finite relative_y
//
//   ws2816b/2121/none/datasheet-r1
//     - runtime_admissible is not true (absent counts as false, even when channels carry usable observations)
//     - topology is absent or unknown; firmware generation requires one of rgb, rgbw, rgbww
//     - channel 'red' lacks runtime_admissible: true, a finite chromaticity {x, y}, a finite relative_y
//     - channel 'green' lacks runtime_admissible: true, a finite chromaticity {x, y}, a finite relative_y
//     - channel 'blue' lacks runtime_admissible: true, a finite chromaticity {x, y}, a finite relative_y

}  // namespace generated_profiles
}  // namespace fl
