FastLED: fl::fixed_point_base::exp2_fp
exp2_fp()
template<typename Derived, int IntBits, int FracBits> static FASTLED_FORCE_INLINE Derived fl::fixed_point_base< Derived, IntBits, FracBits >::exp2_fp (Derived x) inline static private
Definition at line 408 of file base.h.
{
        constexpr int IFRAC = traits::IFRAC;
        Derived fl_val = floor(x);
        Derived fr = x - fl_val;
        raw_type n = fl_val.mValue >> FRAC_BITS;
        if (n >= INT_BITS - 1) return Derived::from_raw(traits::MAX_OVERFLOW);
        if (n < -FRAC_BITS) return Derived();
        raw_type int_pow;
        if (n >= 0) {
            int_pow = static_cast<raw_type>(static_cast<unsigned_raw_type>(1) << FRAC_BITS) << n;
        } else {
            int_pow = static_cast<raw_type>(static_cast<unsigned_raw_type>(1) << FRAC_BITS) >> (-n);
        }
        // 4-term minimax coefficients for 2^t - 1, t in [0,1).
        // Coefficients scaled by 2^IFRAC.
        using poly_type = poly_intermediate_type;
        constexpr poly_type d0 = static_cast<poly_type>(0.69316 * (1LL << IFRAC));
        constexpr poly_type d1 = static_cast<poly_type>(0.24071 * (1LL << IFRAC));
        constexpr poly_type d2 = static_cast<poly_type>(0.05336 * (1LL << IFRAC));
        constexpr poly_type d3 = static_cast<poly_type>(0.01276 * (1LL << IFRAC));
        // Extend fr to IFRAC fractional bits
        poly_type fr_ifrac = static_cast<poly_type>(fr.mValue) << (IFRAC - FRAC_BITS);
        // Horner: 1 + fr * (d0 + fr * (d1 + fr * (d2 + fr * d3)))
        return exp2_horner(int_pow, fr_ifrac, d0, d1, d2, d3, fl::bool_constant<(IFRAC <= 16)>());
    }
References exp2_horner(), FASTLED_FORCE_INLINE, floor(), FRAC_BITS, fl::fixed_point_traits< IntBits, FracBits >::IFRAC, INT_BITS, fl::fixed_point_traits< IntBits, FracBits >::MAX_OVERFLOW, and fl::x.
Referenced by pow().