FastLED: fl::s8x8::acos
acos() [2/2]
static FASTLED_FORCE_INLINE s8x8 fl::s8x8::acos (s8x8 x) inline static
Definition at line 201 of file s8x8.h.
{
        constexpr s8x8 one(1.0f);
        return atan2(sqrt(one - x * x), x);
    }
References s8x8(), atan2(), FASTLED_FORCE_INLINE, FL_NOEXCEPT, sqrt(), and fl::x.