FastLED: fl::s8x8::exp2_fp
exp2_fp()
static FASTLED_FORCE_INLINE s8x8 fl::s8x8::exp2_fp (s8x8 x) inline static private
Definition at line 357 of file s8x8.h.
{
        s8x8 fl_val = floor(x);
        s8x8 fr = x - fl_val;
        i32 n = fl_val.mValue >> FRAC_BITS;
        if (n >= INT_BITS - 1) return from_raw(0x7FFF);
        if (n < -FRAC_BITS) return s8x8();
        i32 int_pow;
        if (n >= 0) {
            int_pow = static_cast<i32>(SCALE) << n;
        } else {
            int_pow = static_cast<i32>(SCALE) >> (-n);
        }
        // 4-term minimax coefficients for 2^t - 1, t in [0,1).
        // Stored as i32 with 16 fractional bits.
        constexpr int IFRAC = 16;
        constexpr i32 d0 = 45427;    // 0.69316 * 2^16
        constexpr i32 d1 = 15775;    // 0.24071 * 2^16
        constexpr i32 d2 = 3497;     // 0.05336 * 2^16
        constexpr i32 d3 = 836;      // 0.01276 * 2^16
        // Extend fr from 8 to 16 frac bits.
        i32 fr16 = static_cast<i32>(fr.mValue) << (IFRAC - FRAC_BITS);
        // Horner: 1 + fr * (d0 + fr * (d1 + fr * (d2 + fr * d3)))
        i32 acc = d3;
        acc = d2 + static_cast<i32>((static_cast<i64>(acc) * fr16) >> IFRAC);
        acc = d1 + static_cast<i32>((static_cast<i64>(acc) * fr16) >> IFRAC);
        acc = d0 + static_cast<i32>((static_cast<i64>(acc) * fr16) >> IFRAC);
        constexpr i32 one16 = static_cast<i32>(1) << IFRAC;
        i32 frac_pow16 = one16 + static_cast<i32>((static_cast<i64>(acc) * fr16) >> IFRAC);
        // Convert from 16 frac bits to 8 frac bits, then scale by int_pow.
        i32 frac_pow8 = frac_pow16 >> (IFRAC - FRAC_BITS);
        i32 result =
            (int_pow * frac_pow8) >> FRAC_BITS;
        return from_raw(static_cast<i16>(result));
    }
References s8x8(), FASTLED_FORCE_INLINE, FL_NOEXCEPT, floor(), FRAC_BITS, from_raw(), INT_BITS, mValue, SCALE, and fl::x.
Referenced by pow().