FastLED: fl::s8x8::log2_fp
log2_fp()
static FASTLED_FORCE_INLINE s8x8 fl::s8x8::log2_fp (s8x8 x) inline static private
Definition at line 321 of file s8x8.h.
{
        u32 val = static_cast<u32>(x.mValue);
        int msb = highest_bit(val);
        i32 int_part = msb - FRAC_BITS;
        i32 t;
        if (msb >= FRAC_BITS) {
            t = static_cast<i32>(
                (val >> (msb - FRAC_BITS)) - (SCALE));
        } else {
            t = static_cast<i32>(
                (val << (FRAC_BITS - msb)) - (SCALE));
        }
        // 4-term minimax coefficients for log2(1+t), t in [0,1).
        // Stored as i32 with 16 fractional bits. Max product ~2^29, fits i32 after shift.
        constexpr int IFRAC = 16;
        constexpr i32 c0 = 94528;    // 1.44179 * 2^16
        constexpr i32 c1 = -45814;   // -0.69907 * 2^16
        constexpr i32 c2 = 23821;    // 0.36348 * 2^16
        constexpr i32 c3 = -6986;    // -0.10660 * 2^16
        // Extend t from 8 to 16 frac bits.
        i32 t16 = static_cast<i32>(t) << (IFRAC - FRAC_BITS);
        // Horner: t * (c0 + t * (c1 + t * (c2 + t * c3)))
        i32 acc = c3;
        acc = c2 + static_cast<i32>((static_cast<i64>(acc) * t16) >> IFRAC);
        acc = c1 + static_cast<i32>((static_cast<i64>(acc) * t16) >> IFRAC);
        acc = c0 + static_cast<i32>((static_cast<i64>(acc) * t16) >> IFRAC);
        i32 frac_part = static_cast<i32>((static_cast<i64>(acc) * t16) >> IFRAC);
        // Convert from 16 frac bits back to 8.
        i16 frac8 = static_cast<i16>(frac_part >> (IFRAC - FRAC_BITS));
        // Use multiplication instead of shift to avoid UB with negative int_part
        return from_raw(static_cast<i16>(int_part * SCALE + frac8));
    }
References s8x8(), FASTLED_FORCE_INLINE, FL_NOEXCEPT, FRAC_BITS, from_raw(), highest_bit(), SCALE, fl::t, and fl::x.
Referenced by pow().