FastLED: loop
loop()
void loop ()
Definition at line 378 of file RpcBidirectional.ino.
            {
    uint32_t now = millis();
    // Server is managed by serverThread - no update needed here
    // Update client
    clientTransport->update(now);
    clientRemote->update(now);
    // Process client responses
    fl::optional<fl::json> response = clientTransport->readRequest();
    if (response) {
        handleClientResponse(*response);
    }
    // Send requests periodically
    if (!waitingForResponse && (now - lastRequestTime >= REQUEST_INTERVAL)) {
        lastRequestTime = now;
        switch (currentMode) {
            case TEST_SYNC:
                sendSyncRequest();
                currentMode = TEST_ASYNC;
                break;
            case TEST_ASYNC:
                sendAsyncRequest();
                currentMode = TEST_ASYNC_STREAM;
                break;
            case TEST_ASYNC_STREAM:
                sendAsyncStreamRequest();
                currentMode = TEST_SYNC;
                Serial.println("\n--- Test cycle complete, starting over ---\n");
                break;
        }
    }
    delay(10);
}
References clientRemote, clientTransport, currentMode, handleClientResponse(), lastRequestTime, REQUEST_INTERVAL, sendAsyncRequest(), sendAsyncStreamRequest(), sendSyncRequest(), Serial, TEST_ASYNC, TEST_ASYNC_STREAM, TEST_SYNC, and waitingForResponse.