FastLED: fl::Gamma8Impl::lerpLut
lerpLut()
u16 fl::Gamma8Impl::lerpLut (const fl::ufixed_point< 8, 8 > & fp) const inline private
Definition at line 446 of file ease.cpp.hpp.
{
        u16 raw = fp.raw();
        u8 idx = static_cast<u8>(raw >> 8);    // integer part (LUT index)
        u8 frac = static_cast<u8>(raw & 0xFF); // fractional part (0-255)
        u16 a = mLut[idx];
        u16 b = (idx < 255) ? mLut[idx + 1] : mLut[idx];
        i32 diff = static_cast<i32>(b) - static_cast<i32>(a);
        return static_cast<u16>(a + ((diff * frac) >> 8));
    }
References fl::fixed_point< IntBits, FracBits, S >::raw().
Referenced by convert(), and convert().