FastLED: autoresearch::simd_check::benchSimd4
benchSimd4()
template<typename Op> int64_t autoresearch::simd_check::benchSimd4 (int iters, Op op) inline
Definition at line 1162 of file AutoResearchSimd.h.
{
    fl::s16x16x4 a = fl::s16x16x4::from_raw(
        set_u32_4(as_u32(fl::s16x16(1.5f).raw()), as_u32(fl::s16x16(2.3f).raw()),
                  as_u32(fl::s16x16(0.7f).raw()), as_u32(fl::s16x16(3.1f).raw())));
    fl::s16x16x4 b = fl::s16x16x4::from_raw(
        set_u32_4(as_u32(fl::s16x16(0.5f).raw()), as_u32(fl::s16x16(1.2f).raw()),
                  as_u32(fl::s16x16(2.0f).raw()), as_u32(fl::s16x16(0.9f).raw())));
    fl::s16x16x4 bump = fl::s16x16x4::set1(fl::s16x16::from_raw(1));
    uint32_t t0 = micros();
    for (int i = 0; i < iters; i++) {
        a = op(a, b);
        b = a + bump;
    }
    uint32_t t1 = micros();
    g_bench_sink = extract_u32_4(a.raw, 0);
    return static_cast<int64_t>(t1 - t0);
}
References as_u32(), fl::s16x16::from_raw(), fl::s16x16x4::from_raw(), g_bench_sink, fl::micros(), fl::s16x16x4::raw, and fl::s16x16x4::set1().
Referenced by runMultiplyBenchmark().