FastLED: autoresearch::simd_check::runMultiplyBenchmark
runMultiplyBenchmark()
BenchmarkResult autoresearch::simd_check::runMultiplyBenchmark (int iters = 10000) inline
Definition at line 1238 of file AutoResearchSimd.h.
{
    BenchmarkResult r;
    r.iterations = iters;
    // Add
    r.add_float_us   = benchFloat4(iters, OpAdd());
    r.add_s8x8_us    = benchS8x8_4(iters, OpAdd());
    r.add_s16x16_us  = benchS16x16_4(iters, OpAdd());
    r.add_u16x16_us  = benchU16x16_4(iters, OpAdd());
    r.add_simd_us    = benchSimd4(iters, OpAdd());
    // Sub
    r.sub_float_us   = benchFloat4(iters, OpSub());
    r.sub_s8x8_us    = benchS8x8_4(iters, OpSub());
    r.sub_s16x16_us  = benchS16x16_4(iters, OpSub());
    r.sub_u16x16_us  = benchU16x16_4(iters, OpSub());
    r.sub_simd_us    = benchSimd4(iters, OpSub());
    // Mul
    r.mul_float_us   = benchFloat4(iters, OpMul());
    r.mul_s8x8_us    = benchS8x8_4(iters, OpMul());
    r.mul_s16x16_us  = benchS16x16_4(iters, OpMul());
    r.mul_u16x16_us  = benchU16x16_4(iters, OpMul());
    r.mul_simd_us    = benchSimd4(iters, OpMul());
    // Div (no SIMD div for s16x16x4)
    r.div_float_us   = benchFloat4(iters, OpDivFloat());
    r.div_s8x8_us    = benchS8x8_4(iters, OpDivS8x8());
    r.div_s16x16_us  = benchS16x16_4(iters, OpDivS16x16());
    r.div_u16x16_us  = benchU16x16_4(iters, OpDivU16x16());
    return r;
}
References autoresearch::simd_check::BenchmarkResult::add_float_us, autoresearch::simd_check::BenchmarkResult::add_s16x16_us, autoresearch::simd_check::BenchmarkResult::add_s8x8_us, autoresearch::simd_check::BenchmarkResult::add_simd_us, autoresearch::simd_check::BenchmarkResult::add_u16x16_us, benchFloat4(), benchS16x16_4(), benchS8x8_4(), benchSimd4(), benchU16x16_4(), autoresearch::simd_check::BenchmarkResult::div_float_us, autoresearch::simd_check::BenchmarkResult::div_s16x16_us, autoresearch::simd_check::BenchmarkResult::div_s8x8_us, autoresearch::simd_check::BenchmarkResult::div_u16x16_us, autoresearch::simd_check::BenchmarkResult::iterations, autoresearch::simd_check::BenchmarkResult::mul_float_us, autoresearch::simd_check::BenchmarkResult::mul_s16x16_us, autoresearch::simd_check::BenchmarkResult::mul_s8x8_us, autoresearch::simd_check::BenchmarkResult::mul_simd_us, autoresearch::simd_check::BenchmarkResult::mul_u16x16_us, autoresearch::simd_check::BenchmarkResult::sub_float_us, autoresearch::simd_check::BenchmarkResult::sub_s16x16_us, autoresearch::simd_check::BenchmarkResult::sub_s8x8_us, autoresearch::simd_check::BenchmarkResult::sub_simd_us, and autoresearch::simd_check::BenchmarkResult::sub_u16x16_us.
Referenced by AutoResearchRemoteControl::registerFunctions().