FastLED: autoresearch::simd_check::runSimdTests
runSimdTests()
int autoresearch::simd_check::runSimdTests () inline
Run the full SIMD test suite. Returns the number of failures.
Definition at line 1394 of file AutoResearchSimd.h.
{
    const SimdTestEntry* tests = nullptr;
    int num_tests = 0;
    getTests(&tests, &num_tests);
    int passed = 0;
    int failed = 0;
    FL_PRINT("\n[SIMD AUTORESEARCH]");
    FL_PRINT("────────────────────────────────────────────────────────────────");
#if defined(__x86_64__) || defined(_M_X64) || defined(__i386__) || defined(_M_IX86)
    FL_PRINT("  SIMD Backend: x86 SSE2");
#elif defined(__XTENSA__) && FL_XTENSA_HAS_PIE
    FL_PRINT("  SIMD Backend: Xtensa PIE (ESP32-S3)");
#elif defined(__XTENSA__)
    FL_PRINT("  SIMD Backend: Xtensa scalar");
#elif defined(__riscv)
    FL_PRINT("  SIMD Backend: RISC-V scalar");
#else
    FL_PRINT("  SIMD Backend: Scalar fallback");
#endif
    fl::sstream ss;
    ss << "  Running " << num_tests << " SIMD tests...\n";
    FL_PRINT(ss.str());
    for (int i = 0; i < num_tests; i++) {
        bool ok = tests[i].func();
        if (ok) {
            passed++;
            ss.clear();
            ss << "  [PASS] " << tests[i].name;
            FL_PRINT(ss.str());
        } else {
            failed++;
            ss.clear();
            ss << "  [FAIL] " << tests[i].name;
            FL_ERROR(ss.str());
        }
    }
    ss.clear();
    ss << "\n[SIMD RESULTS] " << passed << "/" << num_tests << " passed";
    if (failed > 0) {
        ss << ", " << failed << " FAILED";
        FL_ERROR(ss.str());
    } else {
        ss << " - ALL PASSED";
        FL_PRINT(ss.str());
    }
    return failed;
}
References fl::sstream::clear(), FL_ERROR, FL_PRINT, autoresearch::simd_check::SimdTestEntry::func, getTests(), autoresearch::simd_check::SimdTestEntry::name, and fl::sstream::str().