FastLED: autoresearch::simd_check::getTests
getTests()
void autoresearch::simd_check::getTests (const SimdTestEntry ** out_tests, int * out_count) inline
Get the static test table. Used by both runSimdTests() and the RPC handler.
Definition at line 1282 of file AutoResearchSimd.h.
{
    static const SimdTestEntry tests[] = {
        // Load/Store u8x16
        {"load/store u8x16",               test_load_store_u8_16},
        {"load/store u8x16 boundary",      test_load_store_u8_16_boundary},
        // Load/Store u32x4
        {"load/store u32x4",               test_load_store_u32_4},
        {"load/store u32x4 boundary",      test_load_store_u32_4_boundary},
        {"load/store u32x4 aligned",       test_load_store_u32_4_aligned},
        // Load/Store f32x4
        {"load/store f32x4",               test_load_store_f32_4},
        {"load/store f32x4 special",       test_load_store_f32_4_special},
        // Saturating Arithmetic u8x16
        {"add_sat u8x16",                  test_add_sat_u8_16},
        {"add_sat u8x16 full saturate",    test_add_sat_u8_16_full_saturate},
        {"sub_sat u8x16",                  test_sub_sat_u8_16},
        {"sub_sat u8x16 full clamp",       test_sub_sat_u8_16_full_clamp},
        // Scale / Blend u8x16
        {"scale u8x16",                    test_scale_u8_16},
        {"scale u8x16 zero",              test_scale_u8_16_zero},
        {"scale u8x16 full",              test_scale_u8_16_full},
        {"blend u8x16",                    test_blend_u8_16},
        {"blend u8x16 endpoints",          test_blend_u8_16_endpoints},
        // Comparison u8x16
        {"min u8x16",                      test_min_u8_16},
        {"max u8x16",                      test_max_u8_16},
        {"avg u8x16",                      test_avg_u8_16},
        {"avg_round u8x16",               test_avg_round_u8_16},
        // Bitwise u8x16
        {"and u8x16",                      test_and_u8_16},
        {"or u8x16",                       test_or_u8_16},
        {"xor u8x16",                      test_xor_u8_16},
        {"andnot u8x16",                   test_andnot_u8_16},
        // Broadcast / Construct u32x4
        {"set1 u32x4",                     test_set1_u32_4},
        {"set1 u32x4 zero",               test_set1_u32_4_zero},
        {"set u32x4",                      test_set_u32_4},
        {"set1 f32x4",                     test_set1_f32_4},
        // Extract u32x4
        {"extract u32x4",                  test_extract_u32_4},
        // Bitwise u32x4
        {"xor u32x4",                      test_xor_u32_4},
        {"and u32x4",                      test_and_u32_4},
        {"or u32x4",                       test_or_u32_4},
        // Arithmetic i32x4
        {"add i32x4",                      test_add_i32_4},
        {"sub i32x4",                      test_sub_i32_4},
        // Shift u32x4 / i32x4
        {"srl u32x4",                      test_srl_u32_4},
        {"sll u32x4",                      test_sll_u32_4},
        {"sra i32x4",                      test_sra_i32_4},
        // Min/Max i32x4 (signed)
        {"min i32x4",                      test_min_i32_4},
        {"max i32x4",                      test_max_i32_4},
        // Fixed-Point Multiply
        {"mulhi i32x4 (Q16.16)",           test_mulhi_i32_4},
        {"mulhi u32x4 (Q16.16)",           test_mulhi_u32_4},
        {"mulhi su32x4 (Q16.16)",          test_mulhi_su32_4},
        {"mulhi32 i32x4 (>>32)",           test_mulhi32_i32_4},
        // Interleave / Unpack
        {"unpacklo u32x4",                 test_unpacklo_u32_4},
        {"unpackhi u32x4",                 test_unpackhi_u32_4},
        {"unpacklo u64 as u32x4",          test_unpacklo_u64_as_u32_4},
        {"unpackhi u64 as u32x4",          test_unpackhi_u64_as_u32_4},
        // Float Arithmetic
        {"add f32x4",                      test_add_f32_4},
        {"add f32x4 negative",            test_add_f32_4_negative},
        {"sub f32x4",                      test_sub_f32_4},
        {"mul f32x4",                      test_mul_f32_4},
        {"mul f32x4 negative",            test_mul_f32_4_negative},
        {"div f32x4",                      test_div_f32_4},
        {"sqrt f32x4",                     test_sqrt_f32_4},
        {"sqrt f32x4 zero",              test_sqrt_f32_4_zero},
        {"min f32x4",                      test_min_f32_4},
        {"max f32x4",                      test_max_f32_4},
        // Cross-AutoResearch: SIMD vs Scalar Reference (adversarial patterns)
        {"crossval scale u8x16",            test_crossval_scale_u8_16},
        {"crossval add_sat u8x16",          test_crossval_add_sat_u8_16},
        {"crossval sub_sat u8x16",          test_crossval_sub_sat_u8_16},
        {"crossval aligned load/store",     test_crossval_aligned_load_store},
        {"crossval AND u8x16",             test_crossval_and_u8_16},
        {"crossval OR u8x16",              test_crossval_or_u8_16},
        {"crossval XOR u8x16",             test_crossval_xor_u8_16},
        {"crossval ANDNOT u8x16",          test_crossval_andnot_u8_16},
        {"crossval XOR u32x4",             test_crossval_xor_u32_4},
        {"crossval AND u32x4",             test_crossval_and_u32_4},
        {"crossval OR u32x4",              test_crossval_or_u32_4},
        {"crossval broadcast u32x4",       test_crossval_set1_u32_4},
        // Cross-AutoResearch: i32 arithmetic, shifts, min/max, multiply, u8 min/max, float
        {"crossval add i32x4",              test_crossval_add_i32_4},
        {"crossval sub i32x4",              test_crossval_sub_i32_4},
        {"crossval srl u32x4",              test_crossval_srl_u32_4},
        {"crossval sll u32x4",              test_crossval_sll_u32_4},
        {"crossval sra i32x4",              test_crossval_sra_i32_4},
        {"crossval min i32x4",              test_crossval_min_i32_4},
        {"crossval max i32x4",              test_crossval_max_i32_4},
        {"crossval mulhi i32x4",            test_crossval_mulhi_i32_4},
        {"crossval mulhi u32x4",            test_crossval_mulhi_u32_4},
        {"crossval mulhi32 i32x4",          test_crossval_mulhi32_i32_4},
        {"crossval min u8x16",              test_crossval_min_u8_16},
        {"crossval max u8x16",              test_crossval_max_u8_16},
        {"crossval float ops",              test_crossval_float_ops},
        // Pipeline / Chained Operation Tests
        {"pipeline u8 scale+add+clamp",    test_u8_pipeline_scale_add_clamp},
        {"pipeline i32 shift+add+mask",    test_i32_pipeline_shift_add_mask},
        {"pipeline f32 mul+add+clamp",     test_f32_pipeline_mul_add_clamp},
    };
    *out_tests = tests;
    *out_count = sizeof(tests) / sizeof(tests[0]);
}
References test_add_f32_4(), test_add_f32_4_negative(), test_add_i32_4(), test_add_sat_u8_16(), test_add_sat_u8_16_full_saturate(), test_and_u32_4(), test_and_u8_16(), test_andnot_u8_16(), test_avg_round_u8_16(), test_avg_u8_16(), test_blend_u8_16(), test_blend_u8_16_endpoints(), test_crossval_add_i32_4(), test_crossval_add_sat_u8_16(), test_crossval_aligned_load_store(), test_crossval_and_u32_4(), test_crossval_and_u8_16(), test_crossval_andnot_u8_16(), test_crossval_float_ops(), test_crossval_max_i32_4(), test_crossval_max_u8_16(), test_crossval_min_i32_4(), test_crossval_min_u8_16(), test_crossval_mulhi32_i32_4(), test_crossval_mulhi_i32_4(), test_crossval_mulhi_u32_4(), test_crossval_or_u32_4(), test_crossval_or_u8_16(), test_crossval_scale_u8_16(), test_crossval_set1_u32_4(), test_crossval_sll_u32_4(), test_crossval_sra_i32_4(), test_crossval_srl_u32_4(), test_crossval_sub_i32_4(), test_crossval_sub_sat_u8_16(), test_crossval_xor_u32_4(), test_crossval_xor_u8_16(), test_div_f32_4(), test_extract_u32_4(), test_f32_pipeline_mul_add_clamp(), test_i32_pipeline_shift_add_mask(), test_load_store_f32_4(), test_load_store_f32_4_special(), test_load_store_u32_4(), test_load_store_u32_4_aligned(), test_load_store_u32_4_boundary(), test_load_store_u8_16(), test_load_store_u8_16_boundary(), test_max_f32_4(), test_max_i32_4(), test_max_u8_16(), test_min_f32_4(), test_min_i32_4(), test_min_u8_16(), test_mul_f32_4(), test_mul_f32_4_negative(), test_mulhi32_i32_4(), test_mulhi_i32_4(), test_mulhi_su32_4(), test_mulhi_u32_4(), test_or_u32_4(), test_or_u8_16(), test_scale_u8_16(), test_scale_u8_16_full(), test_scale_u8_16_zero(), test_set1_f32_4(), test_set1_u32_4(), test_set1_u32_4_zero(), test_set_u32_4(), test_sll_u32_4(), test_sqrt_f32_4(), test_sqrt_f32_4_zero(), test_sra_i32_4(), test_srl_u32_4(), test_sub_f32_4(), test_sub_i32_4(), test_sub_sat_u8_16(), test_sub_sat_u8_16_full_clamp(), test_u8_pipeline_scale_add_clamp(), test_unpackhi_u32_4(), test_unpackhi_u64_as_u32_4(), test_unpacklo_u32_4(), test_unpacklo_u64_as_u32_4(), test_xor_u32_4(), and test_xor_u8_16().
Referenced by AutoResearchRemoteControl::registerFunctions(), and runSimdTests().