FastLED: autoresearch::simd_check::benchU16x16_4
benchU16x16_4()
template<typename Op> int64_t autoresearch::simd_check::benchU16x16_4 (int iters, Op op) inline
Definition at line 1209 of file AutoResearchSimd.h.
{
    fl::u16x16 a0(1.5f), a1(2.3f), a2(0.7f), a3(3.1f);
    fl::u16x16 b0(0.5f), b1(1.2f), b2(2.0f), b3(0.9f);
    fl::u16x16 bump = fl::u16x16::from_raw(1);
    uint32_t t0 = micros();
    for (int i = 0; i < iters; i++) {
        a0 = op(a0, b0); a1 = op(a1, b1);
        a2 = op(a2, b2); a3 = op(a3, b3);
        b0 = a0 + bump; b1 = a1 + bump;
        b2 = a2 + bump; b3 = a3 + bump;
    }
    uint32_t t1 = micros();
    g_bench_sink = static_cast<uint32_t>(a0.raw());
    return static_cast<int64_t>(t1 - t0);
}
References fl::u16x16::from_raw(), g_bench_sink, and fl::micros().
Referenced by runMultiplyBenchmark().