FastLED: fl::AudioSample::fft
fft()
void fl::AudioSample::fft (FFTBins * out)
Definition at line 112 of file audio.cpp.
{
    fl::Slice<const int16_t> sample = pcm();
    FFT_Args args;
    args.samples = sample.size();
    args.bands = out->size();
    args.fmin = FFT_Args::DefaultMinFrequency();
    args.fmax = FFT_Args::DefaultMaxFrequency();
    args.sample_rate =
        FFT_Args::DefaultSampleRate(); // TODO: get sample rate from AudioSample
    gFlexFFT.run(sample, out, args);
}
References fl::FFT_Args::bands, fl::FFT_Args::DefaultMaxFrequency(), fl::FFT_Args::DefaultMinFrequency(), fl::FFT_Args::DefaultSampleRate(), fl::FFT_Args::fmax, fl::FFT_Args::fmin, fl::gFlexFFT, pcm(), fl::FFT_Args::sample_rate, fl::FFT_Args::samples, fl::FFTBins::size(), and fl::Slice< T >::size().