FastLED: fl::s12x4::s12x4
s12x4() [1/4]
fl::s12x4::s12x4 () constexpr default
References FL_NOEXCEPT.
Referenced by s12x4(), abs(), abs(), acos(), acos(), angle_to_a24(), asin(), asin(), atan(), atan(), atan2(), atan_unit(), ceil(), ceil(), clamp(), cos(), cos(), exp2_fp(), floor(), floor(), fract(), fract(), from_raw(), lerp(), log2_fp(), mod(), operator!=(), operator*(), operator*, operator*(), operator+(), operator-(), operator-(), operator/(), operator<(), operator<=(), operator==(), operator>(), operator>=(), operator>>(), pow(), rsqrt(), rsqrt(), sign(), sin(), sin(), sincos(), smoothstep(), sqrt(), sqrt(), and step().