FastLED: LedRopeTCL::DrawRepeat
DrawRepeat()
void LedRopeTCL::DrawRepeat (const int * value_array, int array_length) virtual
Implements LedRopeInterface.
Definition at line 161 of file LedRopeTCL.cpp.
{
  RawBeginDraw();
  // Make sure that the number of colors to repeat does not exceed the length
  // of the rope.
  const int len = MIN(array_length, frame_buffer_.length());
  for (int i = 0; i < len; ++i) {
     const Color3i* cur_color = GetIterator(i);  // Current color.
     const int repeat_count = value_array[i];
     // Repeatedly send the same color down the led rope.
     for (int k = 0; k < repeat_count; ++k) {
       RawDrawPixel(cur_color->r_, cur_color->g_, cur_color->b_);
     }
  }
  // Finish the drawing.
  RawCommitDraw();
}
References Color3i::b_, frame_buffer_, Color3i::g_, GetIterator(), MIN, Color3i::r_, RawBeginDraw(), RawCommitDraw(), and RawDrawPixel().