FastLED: LedRopeTCL::Draw
Draw()
void LedRopeTCL::Draw ()
Definition at line 122 of file LedRopeTCL.cpp.
                      {
  RawBeginDraw();
  const Color3i* begin = GetIterator(0);
  const Color3i* middle = GetIterator(draw_offset_);
  const Color3i* end = GetIterator(length() - 1);
  for (const Color3i* it = middle; it != end; ++it) {
    RawDrawPixel(*it);
  }
  for (const Color3i* it = begin; it != middle; ++it) {
    RawDrawPixel(*it);
  }
  RawCommitDraw();
}
References draw_offset_, GetIterator(), length(), RawBeginDraw(), RawCommitDraw(), and RawDrawPixel().