FastLED: LedRopeTCL::RawCommitDraw
RawCommitDraw()
void LedRopeTCL::RawCommitDraw () virtual
Implements LedRopeInterface.
Definition at line 100 of file LedRopeTCL.cpp.
{
  FASTLED_WARN("\n\n############## COMMIT DRAW ################\n\n");
  if (!controller_added_) {
    controller_added_ = true;
    CRGB* leds = led_buffer_.data();
    size_t n_leds = led_buffer_.size();
    FastLED.addLeds<APA102, PIN_DATA, PIN_CLOCK>(leds, n_leds).setScreenMap(mScreenMap);
  }
  FASTLED_WARN("FastLED.show");
  FastLED.show();
}
References APA102, controller_added_, FastLED, FASTLED_WARN, led_buffer_, leds, mScreenMap, PIN_CLOCK, and PIN_DATA.
Referenced by Draw(), DrawRepeat(), and DrawSequentialRepeat().