FastLED: fl::StrN::trim
trim()
template<size_t SIZE = 64> StrN fl::StrN< SIZE >::trim () const inline
Definition at line 368 of file str.h.
                      {
        StrN out;
        size_t start = 0;
        size_t end = mLength;
        while (start < mLength && StringFormatter::isSpace(c_str()[start])) {
            start++;
        }
        while (end > start && StringFormatter::isSpace(c_str()[end - 1])) {
            end--;
        }
        return substring(start, end);
    }
References StrN(), c_str(), fl::end(), fl::StringFormatter::isSpace(), mLength, and substring().