FastLED: fl::StrN::copy
copy() [3/3]
template<size_t SIZE = 64> template<size_t M> void fl::StrN< SIZE >::copy (const StrN< M > & other) inline
Definition at line 181 of file str.h.
{
        size_t len = other.size();
        if (len + 1 <= SIZE) {
            memcpy(mInlineData, other.c_str(), len + 1);
            mHeapData.reset();
        } else {
            if (other.mHeapData) {
                mHeapData = other.mHeapData;
            } else {
                mHeapData = StringHolderPtr::New(other.c_str());
            }
        }
        mLength = len;
    }
References StrN(), c_str(), mHeapData, mInlineData, mLength, and size().