FastLED: fl::StrN::substring
substring()
template<size_t SIZE = 64> StrN fl::StrN< SIZE >::substring (size_t start, size_t end) const inline
Definition at line 352 of file str.h.
{
        if (start >= mLength) {
            return StrN();
        }
        if (end > mLength) {
            end = mLength;
        }
        if (start >= end) {
            return StrN();
        }
        StrN out;
        out.copy(c_str() + start, end - start);
        return out;
    }
References StrN(), c_str(), copy(), and mLength.
Referenced by trim().