FastLED: fl::StrN::write
write() [7/8]
template<size_t SIZE = 64> size_t fl::StrN< SIZE >::write (const uint8_t * data, size_t n) inline
Definition at line 174 of file str.h.
{
        const char *str = reinterpret_cast<const char *>(data);
        return write(str, n);
    }
References write().
Referenced by fl::StringFormatter::append(), write(), write(), write(), write(), write(), and write().