FastLED: fl::StrN::write
write() [3/8]
template<size_t SIZE = 64> size_t fl::StrN< SIZE >::write (const int32_t & val) inline
Definition at line 229 of file str.h.
{
        StrN<64> dst;
        StringFormatter::append(val, &dst); // Inlined size should suffice
        return write(dst.c_str(), dst.size());
    }
References StrN(), fl::StringFormatter::append(), c_str(), size(), and write().