FastLED: CFastLED::clear
clear() [2/2]
void CFastLED::clear (ClearFlags flags) static
Clear/reset FastLED state based on the provided flags.
Waits for all pending channel bus transmissions to complete, then clears the specified settings. Multiple flags can be combined using bitwise OR (|).
Parameters
flags Settings to clear (REQUIRED). Can be OR'd together:
ClearFlags::CHANNELS - Remove all channels from controller list
ClearFlags::POWER_SETTINGS - Reset power management to defaults
ClearFlags::BRIGHTNESS - Reset brightness to 255
ClearFlags::REFRESH_RATE - Reset refresh rate limiting
ClearFlags::FPS_COUNTER - Reset FPS tracking
ClearFlags::CHANNEL_ENGINES - Clear all channel engines
// Clear only channels
FastLED.clear(ClearFlags::CHANNELS);
// Clear power settings and brightness
FastLED.clear(ClearFlags::POWER_SETTINGS | ClearFlags::BRIGHTNESS);
Definition at line 161 of file FastLED.cpp.hpp.
{
    // Lambda to check if flag is set, clear it, and return true if it was set
    auto clearFlag = [&flags](ClearFlags flag) -> bool {
        if ((flags & flag) != ClearFlags::NONE) {
            flags = static_cast<ClearFlags>(static_cast<fl::u32>(flags) & ~static_cast<fl::u32>(flag));
            return true;
        }
        return false;
    };
    // Reset POWER_SETTINGS - reset power management to defaults
    if (clearFlag(ClearFlags::POWER_SETTINGS)) {
        FastLED.mPPowerFunc = nullptr;      // No power limiting function
        FastLED.mNPowerData = 0xFFFFFFFF;   // No power limit (max value)
    }
    // Reset BRIGHTNESS - reset global brightness to 255 (full brightness)
    if (clearFlag(ClearFlags::BRIGHTNESS)) {
        FastLED.mScale = 255;
    }
    // Reset REFRESH_RATE - reset refresh rate limiting to unlimited
    if (clearFlag(ClearFlags::REFRESH_RATE)) {
        FastLED.mNMinMicros = 0;  // No minimum delay between frames
    }
    // Reset FPS_COUNTER - reset FPS tracking counter to 0
    if (clearFlag(ClearFlags::FPS_COUNTER)) {
        FastLED.mNFPS = 0;
    }
    // Reset CHANNELS - remove all channels from controller list
    if (clearFlag(ClearFlags::CHANNELS)) {
        // Wait for engines to complete, with 2s timeout to prevent infinite hang
        // if an engine is permanently stalled (e.g. PARLIO on ESP32-C6 hw bug)
        FastLED.wait(2000);
        // Remove all channels by iterating through a copy of the vector
        // (we make a copy because remove() modifies channels())
        fl::vector<fl::ChannelPtr> channelsCopy = channels();
        for (auto& channel : channelsCopy) {
            remove(channel);
        }
        // Reset bus manager state (clear enqueued and transmitting channels)
        fl::ChannelManager& manager = fl::channelManager();
        manager.reset();
        // Clear the internal storage (should already be empty, but ensure it)
        channels().clear();
    }
    // Reset CHANNEL_ENGINES - clear all registered channel drivers
    if (clearFlag(ClearFlags::CHANNEL_ENGINES)) {
        // Always wait for all channel bus transmissions to complete first
        FastLED.wait();
        fl::ChannelManager& manager = fl::channelManager();
        manager.clearAllDrivers();
    }
    // Ensure all flags were handled - catches typos or missing implementations
    FL_ASSERT(flags == ClearFlags::NONE, "Unhandled flags in FastLED.clear()");
}
References BRIGHTNESS, CHANNEL_ENGINES, fl::channelManager(), CHANNELS, channels(), fl::ChannelManager::clearAllDrivers(), FastLED, FL_ASSERT, FPS_COUNTER, NONE, POWER_SETTINGS, REFRESH_RATE, remove(), and fl::ChannelManager::reset().