FastLED: CFastLED::add
add() [3/8]
fl::vector< fl::ChannelPtr > CFastLED::add (const fl::MultiChannelConfig & multiConfig) static
Add multiple LED channels from a MultiChannelConfig.
Creates and registers multiple Channel-based LED controllers from a MultiChannelConfig. Returns a vector of shared_ptrs for lifetime control.
Parameters
multiConfig MultiChannelConfig containing multiple channel configurations
Returns
Vector of ChannelPtrs (one per config), or empty elements if unsupported
Note
Supported platforms: ESP32, ESP32-S2, ESP32-S3, ESP32-C3, ESP32-C6, ESP32-P4
Example:
auto timing = fl::makeTimingConfig<fl::TIMING_WS2812_800KHZ>();
fl::MultiChannelConfig multiConfig = {
    fl::ChannelConfig(PIN1, timing, leds1, RGB),
    fl::ChannelConfig(PIN2, timing, leds2, RGB)
};
auto channels = FastLED.add(multiConfig);
Definition at line 670 of file FastLED.cpp.hpp.
{
    fl::vector<fl::ChannelPtr> channels;
    channels.reserve(multiConfig.mChannels.size());
    for (const auto& configPtr : multiConfig.mChannels) {
        if (configPtr) {
            channels.push_back(add(*configPtr));
        }
    }
    return channels;
}
References add(), channels(), fl::MultiChannelConfig::mChannels, and fl::vector_basic::size().