FastLED: CFastLED::delay
delay()
void CFastLED::delay (unsigned long ms)
Delay for the given number of milliseconds.
Provided to allow the library to be used on platforms that don't have a delay function (to allow code to be more portable).
Note
This will call show() constantly to drive the dithering engine (and will call show() at least once).
Parameters
ms the number of milliseconds to pause for
Definition at line 377 of file FastLED.cpp.hpp.
{
    unsigned long start = fl::millis();
        do {
#ifndef FASTLED_ACCURATE_CLOCK
        // make sure to allow at least one ms to pass to ensure the clock moves
        // forward
        fl::delay(1);
#endif
        show();
        fl::yield();
    }
    while((fl::millis()-start) < ms);
}
References fl::delay(), fl::millis(), show(), and fl::yield().