FastLED: CFastLED::setTemperature
setTemperature()
void CFastLED::setTemperature (const struct CRGB & temp)
Set a global color temperature.
Sets the color temperature for all added led strips, overriding whatever previous color temperature those controllers may have had.
Parameters
temp A CRGB structure describing the color temperature
Definition at line 265 of file FastLED.cpp.
{
    CLEDController *pCur = CLEDController::head();
    while(pCur) {
        pCur->setTemperature(temp);
        pCur = pCur->next();
    }
}
References CLEDController::head(), CLEDController::next(), and CLEDController::setTemperature().