FastLED: CFastLED::showColor
showColor() [2/2]
void CFastLED::showColor (const CRGB & color, fl::u8 scale)
Set all leds on all controllers to the given color/scale.
Parameters
color what color to set the leds to
scale what brightness scale to show at
Definition at line 315 of file FastLED.cpp.hpp.
{
    while(mNMinMicros && ((fl::micros()-lastshow) < mNMinMicros)) {
#if SKETCH_HAS_LARGE_MEMORY
        fl::task::run(250, fl::task::ExecFlags::SYSTEM);
#endif
    }
    lastshow = fl::micros();
    // If we have a function for computing power, use it!
    if(mPPowerFunc) {
        scale = (*mPPowerFunc)(scale, mNPowerData);
    }
    int length = 0;
    CLEDController *pCur = CLEDController::head();
    while(pCur && length < MAX_CLED_CONTROLLERS) {
        if (pCur->getEnabled()) {
            gControllersData[length] = pCur->beginShowLeds(pCur->size());
        } else {
            gControllersData[length] = nullptr;
        }
        length++;
        pCur = pCur->next();
    }
    pCur = CLEDController::head();
    while(pCur && length < MAX_CLED_CONTROLLERS) {
        if(mNFPS < 100) { pCur->setDither(0); }
        if (pCur->getEnabled()) {
            pCur->showColorInternal(color, scale);
        }
        pCur = pCur->next();
    }
    pCur = CLEDController::head();
    length = 0;  // Reset length to 0 and iterate again.
    while(pCur && length < MAX_CLED_CONTROLLERS) {
        if (pCur->getEnabled()) {
            pCur->endShowLeds(gControllersData[length]);
        }
        length++;
        pCur = pCur->next();
    }
    countFPS();
    onEndFrame();
}
References fl::CLEDController::beginShowLeds(), countFPS(), fl::CLEDController::endShowLeds(), gControllersData, fl::CLEDController::getEnabled(), fl::CLEDController::head(), lastshow, length(), MAX_CLED_CONTROLLERS, fl::micros(), mNFPS, mNMinMicros, mNPowerData, mPPowerFunc, fl::CLEDController::next(), onEndFrame(), fl::task::run(), scale, fl::CLEDController::setDither(), fl::CLEDController::showColorInternal(), fl::CLEDController::size(), and fl::task::SYSTEM.
Referenced by clear().