FastLED: CFastLED::showColor
showColor() [2/2]
void CFastLED::showColor (const struct CRGB & color, uint8_t scale)
Set all leds on all controllers to the given color/scale.
Parameters
color what color to set the leds to
scale what brightness scale to show at
Definition at line 193 of file FastLED.cpp.
{
    while(m_nMinMicros && ((micros()-lastshow) < m_nMinMicros));
    lastshow = micros();
    // If we have a function for computing power, use it!
    if(m_pPowerFunc) {
        scale = (*m_pPowerFunc)(scale, m_nPowerData);
    }
    int length = 0;
    CLEDController *pCur = CLEDController::head();
    while(pCur && length < MAX_CLED_CONTROLLERS) {
        if (pCur->getEnabled()) {
            gControllersData[length] = pCur->beginShowLeds(pCur->size());
        } else {
            gControllersData[length] = nullptr;
        }
        length++;
        pCur = pCur->next();
    }
    pCur = CLEDController::head();
    while(pCur && length < MAX_CLED_CONTROLLERS) {
        if(m_nFPS < 100) { pCur->setDither(0); }
        if (pCur->getEnabled()) {
            pCur->showColorInternal(color, scale);
        }
        pCur = pCur->next();
    }
    pCur = CLEDController::head();
    length = 0;  // Reset length to 0 and iterate again.
    while(pCur && length < MAX_CLED_CONTROLLERS) {
        if (pCur->getEnabled()) {
            pCur->endShowLeds(gControllersData[length]);
        }
        length++;
        pCur = pCur->next();
    }
    countFPS();
    onEndFrame();
}
References CLEDController::beginShowLeds(), countFPS(), CLEDController::endShowLeds(), gControllersData, CLEDController::getEnabled(), CLEDController::head(), lastshow, length(), m_nFPS, m_nMinMicros, m_nPowerData, m_pPowerFunc, MAX_CLED_CONTROLLERS, CLEDController::next(), onEndFrame(), scale, CLEDController::setDither(), CLEDController::showColorInternal(), and CLEDController::size().
Referenced by clear().