FastLED: hsv2rgb_dispatch
hsv2rgb_dispatch() [1/2]
FASTLED_FORCE_INLINE void hsv2rgb_dispatch (const CHSV & hsv, CRGB & rgb)
Definition at line 61 of file crgb.h.
{
#if defined(FASTLED_HSV_CONVERSION_SPECTRUM)
    hsv2rgb_spectrum(hsv, rgb);
#elif defined(FASTLED_HSV_CONVERSION_FULL_SPECTRUM)
    hsv2rgb_fullspectrum(hsv, rgb);
#elif defined(FASTLED_HSV_CONVERSION_RAINBOW)
    hsv2rgb_rainbow(hsv, rgb);
#else
    hsv2rgb_rainbow(hsv, rgb);
#endif
}
References FASTLED_FORCE_INLINE, hsv2rgb_fullspectrum(), hsv2rgb_rainbow(), and hsv2rgb_spectrum().