FastLED: loop
loop()
void loop ()
Definition at line 131 of file Downscale.h.
            {
    // Your code here
    clearLeds();
    const uint32_t now = fl::millis();
    uint32_t now_warped = time_warp.update(now);
    // Apply UI stencil choice to both wave layers.
    const fl::LaplacianStencil stencil = isotropicStencil
        ? fl::LaplacianStencil::NinePointIsotropic
        : fl::LaplacianStencil::FivePoint;
    wave_fx.wave_fx_low->setStencil(stencil);
    wave_fx.wave_fx_high->setStencil(stencil);
    auto shape = getShape(whichShape.as<int>());
    shape->setScale(scale.value());
    float curr_alpha = getAnimationTime(now_warped);
    static float s_prev_alpha = 0.0f; // okay static in header
    // unconditionally apply the circle.
    if (trigger) {
        // trigger the transition
        time_warp.reset(now);
        now_warped = time_warp.update(now);
        shapeProgress.trigger(now_warped);
        FL_WARN("Transition triggered on " << shape->name());
        curr_alpha = getAnimationTime(now_warped);
        s_prev_alpha = curr_alpha;
    }
    clearLeds();
    const fl::CRGB purple = fl::CRGB(255, 0, 255);
    const int number_of_steps = numberOfSteps.value();
    raster.reset();
    float diff = curr_alpha - s_prev_alpha;
    diff *= 1.0f;
    float factor = fl::max(s_prev_alpha - diff, 0.f);
    for (int i = 0; i < number_of_steps; ++i) {
        float a =
            fl::map_range<float>(i, 0, number_of_steps - 1, factor, curr_alpha);
        if (a < .04) {
            // shorter tails at first.
            a = fl::map_range<float>(a, 0.0f, .04f, 0.0f, .04f);
        }
        float diff_max_alpha = maxAnimation.value() - curr_alpha;
        if (diff_max_alpha < 0.94) {
            // shorter tails at the end.
            a = fl::map_range<float>(a, curr_alpha, maxAnimation.value(),
                                 curr_alpha, maxAnimation.value());
        }
        uint8_t alpha =
            fl::map_range<uint8_t>(i, 0.0f, number_of_steps - 1, 64, 255);
        fl::Tile2x2_u8 subpixel = shape->at_subpixel(a);
        subpixel.scale(alpha);
        // subpixels.push_back(subpixel);
        raster.rasterize(subpixel);
    }
    s_prev_alpha = curr_alpha;
    if (useWaveFx) {
        DrawRasterToWaveSimulator draw_wave_fx(&wave_fx);
        raster.draw(xyMap, draw_wave_fx);
    } else {
        raster.draw(purple, xyMap, leds);
    }
    int first = xyMap(1, 1);
    int last = xyMap(WIDTH - 2, HEIGHT - 2);
    leds[first] = fl::CRGB(255, 0, 0);
    leds[last] = fl::CRGB(0, 255, 0);
    if (useWaveFx) {
        // fxBlend.draw(fl::Fx::DrawContext(now, leds));
        wave_fx.draw(fl::Fx::DrawContext(now, leds));
    }
    // downscaleBilinear(leds, WIDTH, HEIGHT, leds_downscaled, WIDTH / 2,
    //                   HEIGHT / 2);
    downscaleHalf(leds, xyMap, leds_downscaled, xyMap_Dst);
    // Print out the first 10 pixels of the original and downscaled
    fl::vector_inlined<fl::CRGB, 10> downscaled_pixels;
    fl::vector_inlined<fl::CRGB, 10> original_pixels;
    for (int i = 0; i < 10; ++i) {
        original_pixels.push_back(leds[i]);
        downscaled_pixels.push_back(leds_downscaled[i]);
    }
    FastLED.show();
}
References clearLeds(), FastLED, fl::FivePoint, FL_WARN, getAnimationTime(), getShape(), HEIGHT, isotropicStencil(), leds, leds_downscaled, fl::map_range(), fl::max(), maxAnimation(), fl::millis(), fl::NinePointIsotropic, numberOfSteps(), fl::vector< T >::push_back(), raster(), fl::Tile2x2_u8::scale(), scale, shapeProgress(), time_warp, trigger(), useWaveFx(), wave_fx, whichShape(), WIDTH, xyMap, and xyMap_Dst().