FastLED: getAnimationTime
getAnimationTime()
float getAnimationTime (uint32_t now)
Definition at line 118 of file Downscale.h.
{
    float pointf = shapeProgress.updatef(now);
    return pointf + transition.value();
}
References shapeProgress(), and transition().
Referenced by loop().