FastLED: fl::blur2d
blur2d() [2/2]
void fl::blur2d (CRGB * leds, fl::u8 width, fl::u8 height, fract8 blur_amount, const fl::XYMap & xymap)
Two-dimensional blur filter.
Spreads light to 8 XY neighbors.
0 = no spread at all
64 = moderate spreading
172 = maximum smooth, even spreading
173..255 = wider spreading, but increasing flicker
Total light is NOT entirely conserved, so many repeated calls to 'blur' will also result in the light fading, eventually all the way to black; this is by design so that it can be used to (slowly) clear the LEDs to black.
Parameters
leds a pointer to the LED array to blur
width the width of the matrix
height the height of the matrix
blur_amount the amount of blur to apply
Definition at line 73 of file blur.cpp.
{
    blurRows(leds, width, height, blur_amount, xymap);
    blurColumns(leds, width, height, blur_amount, xymap);
}
References blurColumns(), blurRows(), leds, and xymap.
Referenced by blur2d(), fl::Blend2d::draw(), fl::Luminova::draw(), and loop().