FastLED: fl::blur2d
blur2d() [1/2]
void fl::blur2d (CRGB * leds, uint8_t width, uint8_t height, fract8 blur_amount)
Legacy version of blur2d, which does not require an XYMap but instead implicitly binds to XY() function.
If you are hitting a linker error here, then use blur2d(..., const fl::XYMap& xymap) instead.
Definition at line 77 of file blur.cpp.
{
    XYMap xy =
        XYMap::constructWithUserFunction(width, height, xy_legacy_wrapper);
    blur2d(leds, width, height, blur_amount, xy);
}
References blur2d(), fl::XYMap::constructWithUserFunction(), leds, and xy().