FastLED: loop
loop()
void loop ()
Definition at line 66 of file direct.h.
            {
    fl::clear(leds);
    // FASTLED_ASSERT(false, "This is a test");
    // leds(x,y) = CRGB(255, 0, 0);
    float from = offset;
    float to = length.value() + offset.value();
    heartPath->drawColor(CRGB(255, 0, 0), from, to, &leds, steps.as_int());
    FastLED.show();
}
References fl::clear(), FastLED, heartPath, leds, length(), offset(), and steps().