FastLED: fl::Singleton::instance
instance()
template<typename T, int N = 0> static T & fl::Singleton< T, N >::instance () inline static
Definition at line 41 of file singleton.h.
{
        // Aligned char buffer storage — never destroyed
        struct FL_ALIGN_AS_T(alignof(T)) AlignedStorage {
            char data[sizeof(T)];
        };
        static AlignedStorage storage;
        static T* ptr = nullptr;
        if (!ptr) {
#if FL_HAS_SANITIZER_LSAN
            __lsan::ScopedDisabler disabler;
#endif
            ptr = new (&storage.data) T();
        }
        return *ptr;
    }
Referenced by fl::audio::Sample::Sample(), fl::audio::Sample::~Sample(), fl::async_log_service(), fl::default_random(), fl::AsyncLogger::disableBackgroundFlush(), fl::AsyncLogger::enableBackgroundFlush(), fl::audio::Sample::fft(), fl::get_rgbw_colorimetric_profile(), fl::get_rgbww_colorimetric_profile(), fl::global_interner(), fl::audio::fft::FFT::globalCache(), gPowerModel(), fl::audio::AudioManager::instance(), fl::ChannelEvents::instance(), fl::ChannelManager::instance(), fl::net::http::FetchManager::instance(), fl::task::Executor::instance(), fl::task::Scheduler::instance(), fl::Singleton< AutoResearchRemoteControl >::instanceRef(), fl::SingletonShared< T, N >::instanceRef(), fl::AsyncLogger::isBackgroundFlushEnabled(), fl::audio::fft::Bins::pool(), fl::rgb_2_rgbw_user_function(), fl::rgb_2_rgbww_user_function(), fl::set_rgb_2_rgbw_function(), fl::set_rgb_2_rgbww_function(), fl::set_rgbw_colorimetric_profile(), fl::set_rgbww_colorimetric_profile(), and fl::pwm_state::state().