FastLED: fl::Ptr::weakRefNoCreate
weakRefNoCreate()
template<typename T> WeakPtr< T > fl::Ptr< T >::weakRefNoCreate () const inline
Definition at line 431 of file ptr.h.
{
    if (!referent_) {
        return WeakPtr<T>();
    }
    WeakReferent *tmp = get()->mWeakPtr.get();
    if (!tmp) {
        return WeakPtr<T>();
    }
    T *referent = static_cast<T *>(tmp->getReferent());
    if (!referent) {
        return WeakPtr<T>();
    }
    // At this point, we know that our weak referent is valid.
    // However, the template parameter ensures that either we have
    // an exact type, or are at least down-castable of it.
    WeakPtr<T> out;
    out.mWeakPtr = get()->mWeakPtr;
    return out;
}
References get(), fl::WeakReferent::getReferent(), fl::WeakPtr< T >::mWeakPtr, and referent_.
Referenced by fl::WeakPtr< T >::WeakPtr(), and fl::WeakPtr< T >::WeakPtr().