FastLED: fl::json_value::parse2_validate_only
parse2_validate_only() [1/2]
bool fl::json_value::parse2_validate_only (const fl::string & txt) static
Definition at line 1103 of file json.cpp.hpp.
{
    return parse2_validate_only(fl::string_view(txt.c_str(), txt.length()));
}
References fl::basic_string::c_str(), fl::basic_string::length(), and parse2_validate_only().
Referenced by parse2(), and parse2_validate_only().