FastLED: fl::anonymous_namespace{five_bit_hd_gamma.cpp.hpp}::five_bit_impl::five_bit_pixel
five_bit_pixel()
FL_ALWAYS_INLINE void fl::anonymous_namespace{five_bit_hd_gamma.cpp.hpp}::five_bit_impl::five_bit_pixel (u16 r16, u16 g16, u16 b16, u8 brightness, u16 bright_p1, bool apply_brightness, CRGB * out, u8 * out_power_5bit)
Definition at line 36 of file five_bit_hd_gamma.cpp.hpp.
{
    // All-zero fast path (rare but worth checking — writes are cheap).
    if ((r16 | g16 | b16) == 0) {
        *out = CRGB(0, 0, 0);
        *out_power_5bit = (brightness <= 31) ? brightness : 31;
        return;
    }
    // Apply brightness: branchless multiply, skip only if brightness==0xff.
    if (apply_brightness) {
        r16 = scale16by8_nozero(r16, bright_p1);
        g16 = scale16by8_nozero(g16, bright_p1);
        b16 = scale16by8_nozero(b16, bright_p1);
    }
    // max3 via branchless ternary (compiler emits cmov on x86, csel on ARM).
    u16 scale = r16;
    if (g16 > scale) scale = g16;
    if (b16 > scale) scale = b16;
    if (scale == 0) {
        *out = CRGB(0, 0, 0);
        *out_power_5bit = 0;
        return;
    }
    // 5-bit quantized scale at or above maximum value.
    scale = (scale + (2047 - (scale >> 5))) >> 11;
    u32 scalef = FL_PGM_READ_DWORD_ALIGNED(&BRIGHT_SCALE[scale]);
    u8 r8 = static_cast<u8>((r16 * scalef + 0x808000) >> 24);
    u8 g8 = static_cast<u8>((g16 * scalef + 0x808000) >> 24);
    u8 b8 = static_cast<u8>((b16 * scalef + 0x808000) >> 24);
    *out = CRGB(r8, g8, b8);
    *out_power_5bit = static_cast<u8>(scale);
}
References brightness, five_bit_pixel(), FL_ALWAYS_INLINE, FL_PGM_READ_DWORD_ALIGNED, scale, and scale16by8_nozero().
Referenced by five_bit_pixel().