FastLED: fl::task::Promise::reject
reject() [1/2]
template<typename T> static Promise< T > fl::task::Promise< T >::reject (const Error & error) inline static
Create a rejected Promise with error.
Definition at line 81 of file promise.h.
                                                             {  // okay static in header
        auto p = create();
        p.complete_with_error(error);
        return p;
    }
References Promise(), create(), error(), and FL_NOEXCEPT.
Referenced by fl::task::make_rejected_promise(), fl::task::make_rejected_promise(), and reject().