FastLED: fl::task::Promise::resolve
resolve() [2/2]
template<typename T> static Promise< T > fl::task::Promise< T >::resolve (T && value) inline static
Create a resolved Promise with value (move version)
Definition at line 74 of file promise.h.
                                                     {  // okay static in header
        auto p = create();
        p.complete_with_value(fl::move(value));
        return p;
    }
References Promise(), create(), FL_NOEXCEPT, fl::fl::move(), and value().