FastLED: fl::deque::push_back
push_back() [1/2]
template<typename T, typename Allocator = fl::allocator<T>> void fl::deque< T, Allocator >::push_back (const T & value) inline
Definition at line 298 of file deque.h.
{
        ensure_capacity(mSize + 1);
        fl::size back_index = get_index(mSize);
        mAlloc.construct(&mData[back_index], value);
        ++mSize;
    }
Referenced by fl::deque< int >::deque(), fl::deque< int >::operator=(), fl::deque< int >::resize(), and fl::Json::to_string_native().