FastLED: fl::Transform16::transform
transform()
vec2< alpha16 > fl::Transform16::transform (const vec2< alpha16 > & xy) const
Definition at line 92 of file transform.cpp.
{
    vec2<alpha16> out = xy;
    // 1) Rotate around the 16‑bit center first
    if (rotation != 0) {
        constexpr int32_t MID = 0x7FFF; // center of 0…0xFFFF interval
        // bring into signed centered coords
        int32_t x = int32_t(out.x) - MID;
        int32_t y = int32_t(out.y) - MID;
        // Q15 cosine & sine
        int32_t c = cos16(rotation); // [-32768..+32767]
        int32_t s = sin16(rotation);
        // rotate & truncate
        int32_t xr = (x * c - y * s) >> 15;
        int32_t yr = (x * s + y * c) >> 15;
        // shift back into [0…0xFFFF]
        out.x = alpha16(xr + MID);
        out.y = alpha16(yr + MID);
    }
    // 2) Then scale in X/Y (Q16 → map32_to_16)
    if (scale_x != 0xFFFF) {
        uint32_t tx = uint32_t(out.x) * scale_x;
        out.x = map32_to_16(tx);
    }
    if (scale_y != 0xFFFF) {
        uint32_t ty = uint32_t(out.y) * scale_y;
        out.y = map32_to_16(ty);
    }
    // 3) Finally translate
    if (offset_x)
        out.x = alpha16(out.x + offset_x);
    if (offset_y)
        out.y = alpha16(out.y + offset_y);
    return out;
}
References cos16(), map32_to_16(), offset_x, offset_y, rotation, scale_x, scale_y, sin16, fl::vec2< T >::x, x, xy(), fl::vec2< T >::y, and y.