FastLED: loop
loop()
void loop ()
Definition at line 52 of file Particles1d.h.
            {
    uint32_t now = fl::millis();
    // Update effect parameters from UI
    FastLED.setBrightness(uiBrightness.as<int>());
    particles.setSpeed(uiSpeed.as<float>());
    particles.setFadeRate(uiFadeAmount.as<int>());
    particles.setLifetime(uiLifetime.as<float>() * 1000);
    particles.setOverdrawCount(uiOverdrawCount.as<int>());
    particles.setCyclical(uiCyclical.value());
    // Manual spawn
    if (uiSpawnButton.clicked()) {
        particles.spawnRandomParticle();
    }
    // Auto spawn (external control)
    if (uiAutoSpawn.value() && now - lastSpawnTime >= uiSpawnInterval.as<float>() * 1000) {
        particles.spawnRandomParticle();
        lastSpawnTime = now;
    }
    // Draw particles
    particles.draw(fl::Fx::DrawContext(now, leds));
    FastLED.show();
    delay(20);
}
References FastLED, lastSpawnTime, leds, fl::millis(), particles(), uiAutoSpawn(), uiBrightness(), uiCyclical(), uiFadeAmount(), uiLifetime(), uiOverdrawCount(), uiSpawnButton(), uiSpawnInterval(), and uiSpeed().