FastLED: fl::ResponseSend::send
send()
void fl::ResponseSend::send (const fl::json & result) inline
Send a single response (for ASYNC mode)
Parameters
result The result payload (any JSON value)
Creates a JSON-RPC response: {"jsonrpc": "2.0", "result": <result>, "id": <requestId>}
Definition at line 68 of file response_send.h.
{
        if (!mResponseSink || mIsFinal) {
            return;
        }
        fl::json response = fl::json::object();
        response.set("jsonrpc", "2.0");
        response.set("result", result);
        response.set("id", mRequestId);
        mResponseSink(response);
    }
References mIsFinal, mRequestId, mResponseSink, fl::json::object(), and send().
Referenced by send(), and setup().