FastLED: fl::audio::detector::anonymous_namespace{equalizer.cpp.hpp}::applyScaling
applyScaling()
float fl::audio::detector::anonymous_namespace{equalizer.cpp.hpp}::applyScaling (float value, FFTScalingMode mode) inline
Apply fft::FFT scaling mode to a single bin value.
Definition at line 25 of file equalizer.cpp.hpp.
{
    switch (mode) {
    case FFTScalingMode::SquareRoot:
        return fl::sqrtf(value);
    case FFTScalingMode::Logarithmic:
        return fl::logf(1.0f + value);
    case FFTScalingMode::None:
    case FFTScalingMode::Linear:
    default:
        return value;
    }
}
References applyScaling(), fl::audio::detector::Linear, fl::audio::detector::Logarithmic, fl::logf(), fl::audio::detector::None, fl::sqrtf(), fl::audio::detector::SquareRoot, and fl::type_rank< T >::value.
Referenced by applyScaling().