FastLED: fl::HttpConnection::transitionTo
transitionTo()
void fl::HttpConnection::transitionTo (ConnectionState newState, u32 currentTimeMs) private
Definition at line 161 of file connection.cpp.hpp.
{
    mState = newState;
    // Handle state-specific initialization
    switch (newState) {
        case ConnectionState::DISCONNECTED:
            resetReconnectAttempts();  // Full reset on user disconnect
            break;
        case ConnectionState::CONNECTING:
            // Starting connection attempt
            break;
        case ConnectionState::CONNECTED:
            // Initialize data received timestamp (for timeout detection)
            mLastDataReceivedMs = currentTimeMs;
            // Initialize heartbeat timestamp to trigger immediate send on first check
            // Subtract interval from currentTimeMs to ensure timeSince >= interval
            if (mLastHeartbeatSentMs == 0) {
                // Use wrapping arithmetic: currentTimeMs - interval
                // Even if this underflows (currentTimeMs < interval), the unsigned
                // subtraction in shouldSendHeartbeat will wrap correctly
                mLastHeartbeatSentMs = currentTimeMs - mConfig.heartbeatIntervalMs;
            }
            break;
        case ConnectionState::RECONNECTING:
            // Calculate backoff delay BEFORE incrementing attempts
            mReconnectDelayMs = calculateBackoffDelay();
            mNextReconnectTimeMs = currentTimeMs + mReconnectDelayMs;
            // Increment attempts for next reconnection
            mReconnectAttempts++;
            break;
        case ConnectionState::CLOSED:
            resetReconnectAttempts();  // Full reset on close
            break;
    }
}
References calculateBackoffDelay(), fl::CLOSED, fl::CONNECTED, fl::CONNECTING, fl::DISCONNECTED, mConfig, mLastDataReceivedMs, mLastHeartbeatSentMs, mNextReconnectTimeMs, mReconnectAttempts, mReconnectDelayMs, mState, fl::RECONNECTING, and resetReconnectAttempts().
Referenced by close(), connect(), disconnect(), onConnected(), and onDisconnected().