FastLED: loop
loop()
void loop ()
Definition at line 158 of file FireMatrix.h.
            {
    // The main program loop that runs continuously
    // Set the overall brightness from the UI slider
    FastLED.setBrightness(brightness);
    // Get the selected color palette
    CRGBPalette16 myPal = getPalette();
    // Get the current time in milliseconds
    uint32_t now = millis();
    // Update the animation speed from the UI slider
    timeScale.setSpeed(speedY);
    // Calculate the current y-offset for animation (makes the fire move)
    uint32_t y_speed = timeScale.update(now);
    // Loop through every LED in our matrix
    for (int i = 0; i < WIDTH; i++) {
        for (int j = 0; j < HEIGHT; j++) {
            // Calculate which color to use from our palette for this LED
            uint8_t palette_index = getPaletteIndex(now, i, j, y_speed);
            // Get the actual RGB color from the palette
            // BRIGHTNESS ensures we use the full brightness range
            CRGB c = ColorFromPalette(myPal, palette_index, BRIGHTNESS);
            // Convert our 2D coordinates (i,j) to the 1D array index
            // We use (WIDTH-1)-i and (HEIGHT-1)-j to flip the coordinates
            // This makes the fire appear to rise from the bottom
            int index = xyMap((WIDTH - 1) - i, (HEIGHT - 1) - j);
            // Set the LED color in our array
            leds[index] = c;
        }
    }
    // Send the color data to the actual LEDs
    FastLED.show();
}
References BRIGHTNESS, brightness, fl::ColorFromPalette(), FastLED, getPalette(), getPaletteIndex(), HEIGHT, leds, speedY(), timeScale(), WIDTH, xyMap, and y_speed.