FastLED: fl::FixedSet::next
next()
template<typename Key, size_t N> bool fl::FixedSet< Key, N >::next (const Key & key, Key * next_key, bool allow_rollover = false) const inline
Definition at line 76 of file set.h.
{
        const_iterator it = find(key);
        if (it != end()) {
            ++it;
            if (it != end()) {
                *next_key = *it;
                return true;
            } else if (allow_rollover && !empty()) {
                *next_key = *begin();
                return true;
            }
        }
        return false;
    }
References begin(), empty(), end(), and find().