FastLED: fl::detail Namespace Reference
fl::detail Namespace Reference
Detailed Description
Compile-time linker keep-alive hook for a single fl::Bus.
SFINAE helpers for detecting a static ENCODER member on timing structs.
Used by the legacy FastLED.addLeds<..., fl::Bus B>(...) template path (see #2460). When B != Bus::AUTO, naming BusTraits<B>::instance here is what makes --gc-sections retain the named driver's translation unit even though the legacy controller body never invokes the singleton directly. The Bus::AUTO specialization is a no-op so calls without an explicit Bus param remain byte-for-byte identical to pre-#2460 code.
Namespaces
namespace anonymous_namespace{allocator.cpp.hpp}
namespace anonymous_namespace{singleton.cpp.hpp}
namespace anonymous_namespace{wait_spin_budget.cpp.hpp}
namespace gamma_constexpr
Classes
struct ActiveLoggerRegistry
Active logger registry for iteration (flush operations) Only tracks loggers that have been instantiated via template access.
class AlphaTrimmedMeanImpl
struct array_delete
class AsyncLoggerServiceTask
Auto-instantiating task for async logger servicing Registers itself with fl::task::Scheduler when first accessed Only instantiated if at least one async logger is used (linker removes if unused)
class AttackDecayFilterImpl
struct AudioLoggerInfo
struct BackgroundFlushState
class BilateralFilterImpl
class BiquadFilterImpl
struct BusKeepAliveImpl
struct BusKeepAliveImpl< fl::Bus::AUTO >
struct CallableHolderBase
class CascadedEMAImpl
struct control_block_alignment
struct ControlBlock
struct ControlBlockBase
class DCBlockerImpl
struct default_delete
class ErasedInvoker
class ErasedSchemaGenerator
class ExponentialSmootherImpl
struct FlexIOLoggerInfo
class GaussianFilterImpl
struct get_encoder
struct get_encoder< CHIPSET, true >
class HampelFilterImpl
struct has_copy_ctor
struct has_copy_ctor< T, decltype(void(T(fl::declval< const T & >())))>
struct has_default_ctor
struct has_default_ctor< T, decltype(void(T()))>
struct has_move_ctor
struct has_move_ctor< T, decltype(void(T(fl::declval< T && >())))>
struct int_to_fixed
struct int_to_fixed< IntBits, FracBits, false >
struct int_to_fixed< IntBits, FracBits, true >
struct integer_digits10_helper
struct integer_digits_helper
struct integer_max_helper
struct integer_max_helper< T, false >
struct integer_max_helper< T, true >
struct integer_min_helper
struct integer_min_helper< T, false >
struct integer_min_helper< T, true >
struct InterruptLoggerInfo
struct is_comparable_to_nullptr
struct is_dereferenceable
struct is_member_data_pointer
struct is_member_data_pointer< T C::* >
struct is_non_bool_integer
struct is_pointer_like
struct is_pointer_like< fl::unique_ptr< T, Deleter > >
struct is_pointer_like< T * >
struct is_reference
struct is_reference< T & >
struct is_reference< T && >
struct is_swappable
struct is_swappable< T, decltype(void(fl::declval< T & >()=fl::declval< T && >()))>
struct JsonToBoolVisitor
struct JsonToFloatVisitor
struct JsonToIntegerVisitor
struct JsonToStringVisitor
struct JsonToType
struct JsonToType< bool, void >
struct JsonToType< fl::ConstCharPtrWrapper, void >
struct JsonToType< fl::ConstSpanWrapper< T >, void >
struct JsonToType< fl::json, void >
struct JsonToType< fl::string, void >
struct JsonToType< fl::vector< fl::u8 >, void >
struct JsonToType< fl::vector< T >, void >
struct JsonToType< T, typename fl::enable_if< fl::is_floating_point< T >::value >::type >
struct JsonToType< T, typename fl::enable_if< fl::is_integral< T >::value &&!fl::is_same< T, bool >::value >::type >
class KalmanFilterImpl
class LeakyIntegratorImpl
struct LutArray
struct make_shared_tag
union max_align_with_ld
union max_align_without_ld
class MedianFilterImpl
class memorybuf
class MethodBuilder
struct MethodSchema
struct MethodSchema< R(Args...)>
struct MethodSchema< void(Args...)>
class MovingAverageImpl
struct no_op_deleter
struct no_tracking_tag
struct ObjectFLEDLoggerInfo
class OneEuroFilterImpl
struct ParlioLoggerInfo
Info providers for each logger category Used to supply category name, define name, and enabled status.
class posix_filebuf
struct resolve_bus
Resolve a possibly-Bus::AUTO template argument to the concrete platform default for the given Chipset family.
struct resolve_bus< Bus::AUTO, Chipset >
class ResponseAwareInvoker
Invoker for response-aware RPC methods.
class ResponseAwareInvoker< R(Args...)>
class ResponseAwareInvoker< void(Args...)>
struct RmtLoggerInfo
struct RpcEntry
class SavitzkyGolayFilterImpl
class ScaledPixelIteratorBrightness
Input iterator adapter for PixelIterator yielding brightness values.
class ScaledPixelIteratorRGB
Input iterator adapter for PixelIterator yielding 3-byte pixel data.
class ScaledPixelIteratorRGB16
Input iterator adapter for PixelIterator yielding 16-bit RGB pixel data.
class ScaledPixelIteratorRGBW
Input iterator adapter for PixelIterator yielding 4-byte pixel data.
class ScaledPixelIteratorRGBWW
Input iterator adapter yielding 5-byte RGBWW pixels (issue #2558).
class SpectralVarianceImpl
Multi-channel EMA with per-bin relative deviation measurement.
struct SpiLoggerInfo
class TriangularFilterImpl
struct TypedCallableHolder
class TypedInvoker
class TypedInvoker< R(Args...)>
class TypedInvoker< void(Args...)>
class TypedSchemaGenerator
struct TypeSchema
struct TypeSchema< bool, void >
struct TypeSchema< fl::string, void >
struct TypeSchema< T, typename fl::enable_if< fl::is_floating_point< T >::value >::type >
struct TypeSchema< T, typename fl::enable_if< fl::is_integral< T >::value &&!fl::is_same< T, bool >::value >::type >
struct TypeSchema< void, void >
struct TypeTag
struct TypeToJson
struct TypeToJson< fl::json >
struct TypeToJson< fl::string >
struct TypeToJson< fl::vector< fl::u8 > >
struct TypeToJson< fl::vector< T > >
struct TypeToJson< void >
struct use_pointer_syntax
class WeightedMovingAverageImpl
Typedefs
template<typename T>
using enable_if_integer_t
typedef const void * pgm_p
Enumerations
enum class HexIntWidth : u8 { Width8 = 8 , Width16 = 16 , Width32 = 32 , Width64 = 64 }
Integer width classification for hex conversion.
enum class log_kind : fl::u8 { WARN = 0 , ERROR = 1 , INFO = 2 }
Functions
void FL_IRAM async_log_flush_timer_isr (void *user_data)
template<typename F>
F atan2_full_ (F y, F x) FL_NOEXCEPT
template<typename F>
F atan_full_ (F u) FL_NOEXCEPT
template<typename F>
F atan_poly_unit_ (F u) FL_NOEXCEPT
template<Bus B>
int bus_register_one () FL_NOEXCEPT
Helper used by enableDrivers<Bus...>() to expand the parameter pack.
template<typename InfoProvider>
void checkLoggerEnabled ()
Check if logger is enabled and print error once if not.
template<typename F>
F cos_poly_quarterturn_ (F x) FL_NOEXCEPT
template<typename F>
F cos_reduce_ (F x) FL_NOEXCEPT
constexpr fl::u32 cycles_from_ns (fl::u32 ns, fl::u32 hz) FL_NOEXCEPT
Convert nanoseconds to CPU cycles.
constexpr fl::u32 cycles_from_ns_default (fl::u32 ns) FL_NOEXCEPT
Compute cycles using default CPU frequency (compile-time)
void delay_impl (u32 ms, bool run_async=true) FL_NOEXCEPT
Internal delay implementation used by the public fl::delay wrapper.
template<typename T>
fl::enable_if< fl::is_floating_point< T >::value, T >::type div_by_count (T sum, fl::size count)
template<typename T>
fl::enable_if< fl::is_integral< T >::value, T >::type div_by_count (T sum, fl::size count)
template<typename T>
fl::enable_if<!fl::is_floating_point< T >::value &&!fl::is_integral< T >::value, T >::type div_by_count (T sum, fl::size count)
template<typename T>
fl::enable_if< has_copy_ctor< T >::value, void(*)(void *, constvoid *) FL_NOEXCEPT >::type get_copy_construct_fn () FL_NOEXCEPT
template<typename T>
fl::enable_if<!has_copy_ctor< T >::value, void(*)(void *, constvoid *) FL_NOEXCEPT >::type get_copy_construct_fn () FL_NOEXCEPT
template<typename T>
fl::enable_if< has_default_ctor< T >::value, void(*)(void *) FL_NOEXCEPT >::type get_default_construct_fn () FL_NOEXCEPT
template<typename T>
fl::enable_if<!has_default_ctor< T >::value, void(*)(void *) FL_NOEXCEPT >::type get_default_construct_fn () FL_NOEXCEPT
template<size_t Size>
constexpr HexIntWidth get_hex_int_width () FL_NOEXCEPT
Compile-time integer width determination (default - triggers error)
template<>
constexpr HexIntWidth get_hex_int_width< 1 > () FL_NOEXCEPT
Specialization for 1-byte types (int8_t, uint8_t, char, etc.)
template<>
constexpr HexIntWidth get_hex_int_width< 2 > () FL_NOEXCEPT
Specialization for 2-byte types (int16_t, uint16_t, short, etc.)
template<>
constexpr HexIntWidth get_hex_int_width< 4 > () FL_NOEXCEPT
Specialization for 4-byte types (int32_t, uint32_t, int, etc.)
template<>
constexpr HexIntWidth get_hex_int_width< 8 > () FL_NOEXCEPT
Specialization for 8-byte types (i64, u64, long long, etc.)
template<typename T>
fl::enable_if< has_move_ctor< T >::value, void(*)(void *, void *) FL_NOEXCEPT >::type get_move_construct_fn () FL_NOEXCEPT
template<typename T>
fl::enable_if<!has_move_ctor< T >::value, void(*)(void *, void *) FL_NOEXCEPT >::type get_move_construct_fn () FL_NOEXCEPT
template<typename T>
fl::enable_if< is_swappable< T >::value, void(*)(void *, void *) FL_NOEXCEPT >::type get_swap_fn () FL_NOEXCEPT
template<typename T>
fl::enable_if<!is_swappable< T >::value, void(*)(void *, void *) FL_NOEXCEPT >::type get_swap_fn () FL_NOEXCEPT
template<typename T>
fl::enable_if< has_move_ctor< T >::value, void(*)(void *, void *, fl::size) FL_NOEXCEPT >::type get_uninitialized_move_n_fn () FL_NOEXCEPT
template<typename T>
fl::enable_if<!has_move_ctor< T >::value, void(*)(void *, void *, fl::size) FL_NOEXCEPT >::type get_uninitialized_move_n_fn () FL_NOEXCEPT
fl::u32 getWaitSpinBudgetUs () FL_NOEXCEPT
Get the current tiered-wait spin budget (microseconds).
template<typename Iterator, typename Compare>
void heap_sort (Iterator first, Iterator last, Compare comp) FL_NOEXCEPT
template<typename Iterator, typename Compare>
void heapify (Iterator first, Iterator last, Compare comp) FL_NOEXCEPT
fl::string hex (u64 value, HexIntWidth width, bool is_negative, bool uppercase, bool pad_to_width) FL_NOEXCEPT
Internal hex conversion function (implementation in charconv.cpp)
template<typename IntT>
constexpr bool in_unsigned_range (IntT n, u32 max_u) FL_NOEXCEPT
template<typename Iterator, typename Compare>
void insertion_sort (Iterator first, Iterator last, Compare comp) FL_NOEXCEPT
template<typename T>
constexpr int integer_digits10_func () FL_NOEXCEPT
template<typename T>
constexpr int integer_digits_func () FL_NOEXCEPT
void integer_out_of_range_for_fixed_point_type () FL_NOEXCEPT
template<typename F>
F ldexp_loop_ (F value, int exp) FL_NOEXCEPT
FL_NO_INLINE void log_emit (log_kind kind, const char *file, int line, fl::sstream &body) FL_NOEXCEPT
template<typename F>
F log_natural_ (F value) FL_NOEXCEPT
template<typename Iterator, typename T, typename Compare>
Iterator lower_bound_impl (Iterator first, Iterator last, const T &value, Compare comp) FL_NOEXCEPT
template<typename Fn, fl::size... Is>
constexpr LutArray< u16, sizeof...(Is)> make_lut_u16 (fl::index_sequence< Is... >) FL_NOEXCEPT
template<typename Fn, fl::size... Is>
constexpr LutArray< u8, sizeof...(Is)> make_lut_u8 (fl::index_sequence< Is... >) FL_NOEXCEPT
json makeJsonRpcError (int code, const fl::string &message, const json &id)
template<typename Iterator, typename Compare>
Iterator median_of_three (Iterator first, Iterator middle, Iterator last, Compare comp) FL_NOEXCEPT
template<typename Iterator, typename Compare>
void merge_inplace (Iterator first, Iterator middle, Iterator last, Compare comp) FL_NOEXCEPT
template<typename Iterator, typename Compare>
void mergesort_impl (Iterator first, Iterator last, Compare comp) FL_NOEXCEPT
void not_null_assert_failed (const char *message)
template<typename Iterator, typename Compare>
Iterator partition (Iterator first, Iterator last, Compare comp) FL_NOEXCEPT
void printLoggerDisabledError (const char *category_name, const char *define_name)
Print error message for disabled logger (non-template helper) Called from checkLoggerEnabled template function IMPORTANT: This must NOT be inline - needs external linkage for cross-TU calls.
void qsort_impl (char *base, size_t nmemb, size_t size, qsort_compare_fn compar)
void qsort_swap (char *a, char *b, size_t size)
template<typename Iterator, typename Compare>
void quicksort_impl (Iterator first, Iterator last, Compare comp) FL_NOEXCEPT
template<typename Iterator>
void rotate_impl (Iterator first, Iterator middle, Iterator last) FL_NOEXCEPT
void setWaitSpinBudgetUs (fl::u32 budget_us) FL_NOEXCEPT
Set the tiered-wait spin budget (microseconds).
template<typename Iterator, typename Compare>
void sift_down (Iterator first, Iterator start, Iterator end, Compare comp) FL_NOEXCEPT
template<typename F>
F sin_poly_quarterturn_ (F x) FL_NOEXCEPT
template<typename F>
F sin_reduce_ (F x) FL_NOEXCEPT
void * singleton_registry_get (const char *key)
void singleton_registry_set (const char *key, void *value)
void * slab_allocator_registry_get (fl::size block_size, fl::size slab_size)
void slab_allocator_registry_set (fl::size block_size, fl::size slab_size, void *allocator)
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void spread_transpose16_symbol (const u8 l[16], u8 out[16])
Transpose one symbol of 16 lanes (16 input bytes) into 16 output bytes: 8 pulses × 2 bytes, low byte = lanes 0-7, high byte = lanes 8-15, pulse order 7..0 (out[0] = pulse 7 low).
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void spread_transpose8_symbol (const u8 l[8], u8 out[8])
Transpose one symbol of 8 lanes (8 input bytes) into 8 output bytes: 8 pulses × 1 byte (bit L = lane L), pulse order 7..0 (out[0] = pulse 7).
FASTLED_FORCE_INLINE u32 spreadA (u8 v)
Pulses 7,6,5,4 of v (byte j = bit (7-j)). Depends only on the high nibble.
FASTLED_FORCE_INLINE u32 spreadB (u8 v)
Pulses 3,2,1,0 of v (byte j = bit (3-j)). Depends only on the low nibble.
template<typename F>
F sqrt_newton_ (F value) FL_NOEXCEPT
template<typename T>
constexpr bool test_encoder (...) FL_NOEXCEPT
template<typename T>
constexpr auto test_encoder (int) FL_NOEXCEPT -> decltype(T::ENCODER, true)
void to_string (const fl::u16 *bit_data, fl::u32 bit_count, string *dst)
template<typename TSrcPalette, typename TDestPalette>
void UpscalePaletteInterpolated (const TSrcPalette &srcpal, TDestPalette &destpal)
template<typename TSrcPalette, typename TDestPalette>
void UpscalePaletteRepeat (const TSrcPalette &srcpal, TDestPalette &destpal)
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void wave3_convert_byte_to_wave3byte (u8 byte_value, const Wave3BitExpansionLut &lut, Wave3Byte *output)
Helper: Convert byte to Wave3Byte using nibble LUT (internal use only)
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void wave3_transpose_16 (const Wave3Byte lane_waves[16], u8 output[16 *sizeof(Wave3Byte)])
Transpose 16 lanes of Wave3Byte data into interleaved format.
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void wave3_transpose_2 (const Wave3Byte lane_waves[2], u8 output[2 *sizeof(Wave3Byte)])
Transpose 2 lanes of Wave3Byte data into interleaved format.
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void wave3_transpose_4 (const Wave3Byte lane_waves[4], u8 output[4 *sizeof(Wave3Byte)])
Transpose 4 lanes of Wave3Byte data into interleaved format.
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void wave3_transpose_8 (const Wave3Byte lane_waves[8], u8 output[8 *sizeof(Wave3Byte)])
Transpose 8 lanes of Wave3Byte data into interleaved format.
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void wave8_convert_byte_to_wave8byte (u8 byte_value, const Wave8BitExpansionLut &lut, Wave8Byte *output)
Helper: Convert byte to Wave8Byte using nibble LUT (internal use only)
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void wave8_expand_byte (u8 byte_value, const Wave8ByteExpansionLut &lut, Wave8Byte *output)
Byte-indexed expansion (#2526): one indexed 8-byte copy.
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void wave8_transpose_16 (const Wave8Byte lane_waves[16], u8 output[16 *sizeof(Wave8Byte)])
Transpose 16 lanes of Wave8Byte data into interleaved format.
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void wave8_transpose_16_bf1 (const u8 lanes[16], u8 W0, u8 W1, u8 output[16 *sizeof(Wave8Byte)])
BF1: chipset-aware direct encode for Wave8 16-lane (#2548 deep-dive).
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void wave8_transpose_16x2_pipe2 (const Wave8Byte lane_waves_a[16], const Wave8Byte lane_waves_b[16], u8 output_a[16 *sizeof(Wave8Byte)], u8 output_b[16 *sizeof(Wave8Byte)])
Pipe2: transpose 16-lane × 2-byte-positions in one fused call.
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void wave8_transpose_16x4_bf1_pipe4 (const u8 lanes_a[16], const u8 lanes_b[16], const u8 lanes_c[16], const u8 lanes_d[16], u8 W0, u8 W1, u8 output_a[16 *sizeof(Wave8Byte)], u8 output_b[16 *sizeof(Wave8Byte)], u8 output_c[16 *sizeof(Wave8Byte)], u8 output_d[16 *sizeof(Wave8Byte)])
BF1 + pipe4: 4-position software-pipelined BF1 (#2548 deep-dive).
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void wave8_transpose_16x4_pipe4 (const Wave8Byte lane_waves_a[16], const Wave8Byte lane_waves_b[16], const Wave8Byte lane_waves_c[16], const Wave8Byte lane_waves_d[16], u8 output_a[16 *sizeof(Wave8Byte)], u8 output_b[16 *sizeof(Wave8Byte)], u8 output_c[16 *sizeof(Wave8Byte)], u8 output_d[16 *sizeof(Wave8Byte)])
Pipe4: transpose 16-lane × 4-byte-positions in one fused call.
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void wave8_transpose_2 (const Wave8Byte lane_waves[2], u8 output[2 *sizeof(Wave8Byte)])
Transpose 2 lanes of Wave8Byte data into interleaved format.
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void wave8_transpose_2_bf1 (const u8 lanes[2], u8 W0, u8 W1, u8 output[2 *sizeof(Wave8Byte)])
BF1 for 2-lane Wave8.
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void wave8_transpose_4 (const Wave8Byte lane_waves[4], u8 output[4 *sizeof(Wave8Byte)])
Transpose 4 lanes of Wave8Byte data into interleaved format.
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void wave8_transpose_4_bf1 (const u8 lanes[4], u8 W0, u8 W1, u8 output[4 *sizeof(Wave8Byte)])
BF1 for 4-lane Wave8.
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void wave8_transpose_8 (const Wave8Byte lane_waves[8], u8 output[8 *sizeof(Wave8Byte)])
Transpose 8 lanes of Wave8Byte data into interleaved format.
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void wave8_transpose_8_bf1 (const u8 lanes[8], u8 W0, u8 W1, u8 output[8 *sizeof(Wave8Byte)])
BF1 for 8-lane Wave8 — same algebraic identity as 16-lane BF1.
Variables
constexpr u32 kSpreadNibble [16]
kSpreadNibble[n] places the 4 bits of nibble n at bit 0 of 4 separate bytes: byte0 = bit3(n), byte1 = bit2(n), byte2 = bit1(n), byte3 = bit0(n).
constexpr u8 kTranspose2_4_LUT [4]
constexpr u8 kTranspose4_16_LUT [16]
fl::detail::integer_max_helper
struct fl::detail::integer_max_helper
fl::detail::integer_min_helper
struct fl::detail::integer_min_helper
fl::detail::LutArray
struct fl::detail::LutArray
Class Members
T values[N]
fl::detail::make_shared_tag
struct fl::detail::make_shared_tag
fl::detail::max_align_with_ld
union fl::detail::max_align_with_ld
Class Members
long double ld
long long ll
void * p
fl::detail::max_align_without_ld
union fl::detail::max_align_without_ld
Class Members
double d
long long ll
void * p
fl::detail::MethodSchema
struct fl::detail::MethodSchema
fl::detail::no_tracking_tag
struct fl::detail::no_tracking_tag
fl::detail::ResponseAwareInvoker
class fl::detail::ResponseAwareInvoker
fl::detail::RpcEntry
struct fl::detail::RpcEntry
Class Members
string mDescription
shared_ptr< ErasedInvoker > mInvoker
bool mIsResponseAware = false
RpcMode mMode = fl::RpcMode::SYNC
function< void(ResponseSend &, const json &)> mResponseAwareFn
shared_ptr< ErasedSchemaGenerator > mSchemaGenerator
vector< string > mTags
shared_ptr< CallableHolderBase > mTypedCallable
const void * mTypeTag = nullptr
fl::detail::TypedInvoker
class fl::detail::TypedInvoker
Typedef Documentation
enable_if_integer_t
template<typename T> using fl::detail::enable_if_integer_t
Initial value:
    typename fl::enable_if<is_non_bool_integer<T>::value, int>::type
Definition at line 28 of file traits.h.
pgm_p
typedef const void* fl::detail::pgm_p
Definition at line 114 of file cstring.h.
Enumeration Type Documentation
HexIntWidth
enum class fl::detail::HexIntWidth : u8 strong
Integer width classification for hex conversion.
Enumerator
Width8
Width16
Width32
Width64
Definition at line 42 of file charconv.h.
                       : u8 {
    Width8 = 8,
    Width16 = 16,
    Width32 = 32,
    Width64 = 64
};
log_kind
enum class fl::detail::log_kind : fl::u8 strong
Enumerator
WARN
ERROR
INFO
Definition at line 173 of file log.h.
                    : fl::u8 {
    WARN  = 0,
    ERROR = 1,
    INFO  = 2,
};
Function Documentation
async_log_flush_timer_isr()
void FL_IRAM fl::detail::async_log_flush_timer_isr (void * user_data)
Definition at line 44 of file async_logger.cpp.hpp.
{
        BackgroundFlushState* state = static_cast<BackgroundFlushState*>(user_data);
        state->mNeedsFlush = true;
        // Debug: Toggle a counter to verify ISR is firing (visible in debugger)
        static volatile fl::u32 isr_fire_count = 0;
        isr_fire_count = isr_fire_count + 1;
    }
References FL_IRAM, and state.
Referenced by fl::AsyncLogger::enableBackgroundFlush().
atan2_full_()
template<typename F> F fl::detail::atan2_full_ (F y, F x) inline
Definition at line 479 of file math.cpp.hpp.
{
    const F kPi     = F(3.14159265358979323846);
    const F kPiHalf = F(1.57079632679489661923);
    // x == 0 special case: angle is ±π/2 (sign of y), or 0 when both are 0.
    if (x == F(0)) {
        if (y > F(0)) return kPiHalf;
        if (y < F(0)) return -kPiHalf;
        return F(0);
    }
    F a = atan_full_(y / x);
    if (x < F(0)) {
        a += (y >= F(0)) ? kPi : -kPi;
    }
    return a;
}
References atan_full_(), FL_NOEXCEPT, fl::x, and fl::y.
Referenced by fl::atan2_impl_double(), and fl::atan2_impl_float().
atan_full_()
template<typename F> F fl::detail::atan_full_ (F u) inline
Definition at line 467 of file math.cpp.hpp.
{
    const F kPiHalf = F(1.57079632679489661923);
    // Reduce to |u| <= 1 via the reciprocal identity.
    if (u > F(1)) {
        return kPiHalf - atan_poly_unit_(F(1) / u);
    } else if (u < F(-1)) {
        return -kPiHalf - atan_poly_unit_(F(1) / u);
    }
    return atan_poly_unit_(u);
}
References atan_poly_unit_(), and FL_NOEXCEPT.
Referenced by fl::asin_impl_double(), fl::asin_impl_float(), atan2_full_(), fl::atan_impl_double(), and fl::atan_impl_float().
atan_poly_unit_()
template<typename F> F fl::detail::atan_poly_unit_ (F u) inline
Definition at line 454 of file math.cpp.hpp.
{
    // Polynomial approximation of atan on [-1, 1].
    // Coefficients from Padé-style minimax fit; max abs error ~1.5e-3.
    const F u2 = u * u;
    return u * (F(0.99997726) +
                u2 * (F(-0.33262347) +
                      u2 * (F(0.19354346) +
                            u2 * (F(-0.11643287) +
                                  u2 * (F(0.05265332) +
                                        u2 * F(-0.01172120))))));
}
References FL_NOEXCEPT.
Referenced by atan_full_().
bus_register_one()
template<Bus B> int fl::detail::bus_register_one () inline
Helper used by enableDrivers<Bus...>() to expand the parameter pack.
Each call ODR-uses BusTraits<B>::registerWithManager(), which lazily constructs the driver singleton AND registers it with ChannelManager.
Definition at line 54 of file bus_traits.h.
{
    BusTraits<B>::registerWithManager();
    return 0;
}
References FL_NOEXCEPT.
Referenced by fl::enableDrivers().
checkLoggerEnabled()
template<typename InfoProvider> void fl::detail::checkLoggerEnabled () inline
Check if logger is enabled and print error once if not.
Template Parameters
InfoProvider Type providing category name, define name, and enabled status
Definition at line 80 of file async_logger.h.
{
        if (!InfoProvider::isEnabled()) {
            static bool error_printed = false;
            if (!error_printed) {
                error_printed = true;
                printLoggerDisabledError(InfoProvider::categoryName(), InfoProvider::defineName());
            }
        }
    }
References checkLoggerEnabled(), and printLoggerDisabledError().
Referenced by checkLoggerEnabled(), and fl::get_async_logger_by_index().
cos_poly_quarterturn_()
template<typename F> F fl::detail::cos_poly_quarterturn_ (F x) inline
Definition at line 177 of file math.cpp.hpp.
{
    // cos(x) ≈ 1 - x²/2 + x⁴/24 - x⁶/720
    const F x2 = x * x;
    return F(1) - x2 * (F(0.5) - x2 * (F(1.0 / 24.0) - x2 * F(1.0 / 720.0)));
}
References FL_NOEXCEPT, and fl::x.
cos_reduce_()
template<typename F> F fl::detail::cos_reduce_ (F x) inline
Definition at line 202 of file math.cpp.hpp.
{
    // cos(x) = sin(π/2 - x)
    const F kPiHalf = F(1.57079632679489661923);
    return sin_reduce_(kPiHalf - x);
}
References FL_NOEXCEPT, sin_reduce_(), and fl::x.
Referenced by fl::cos_impl_double(), fl::cos_impl_float(), fl::tan_impl_double(), and fl::tan_impl_float().
cycles_from_ns()
fl::u32 fl::detail::cycles_from_ns (fl::u32 ns, fl::u32 hz) constexpr
Convert nanoseconds to CPU cycles.
Parameters
ns Number of nanoseconds
hz CPU frequency in Hz
Returns
Number of cycles (rounded up)
Definition at line 29 of file delay.h.
{
  // Round up: cycles = ceil(ns * hz / 1e9)
  // Using: (ns * hz + 999'999'999) / 1'000'000'000
  return ((fl::u64)ns * (fl::u64)hz + 999999999UL) / 1000000000UL;
}
References FL_NOEXCEPT.
Referenced by cycles_from_ns_default().
cycles_from_ns_default()
fl::u32 fl::detail::cycles_from_ns_default (fl::u32 ns) constexpr
Compute cycles using default CPU frequency (compile-time)
Parameters
ns Number of nanoseconds
Returns
Number of cycles using GET_CPU_FREQUENCY()
Definition at line 38 of file delay.h.
{
  return cycles_from_ns(ns, GET_CPU_FREQUENCY());
}
References cycles_from_ns(), and FL_NOEXCEPT.
delay_impl()
void fl::detail::delay_impl (u32 ms, bool run_async = true)
Internal delay implementation used by the public fl::delay wrapper.
Parameters
ms Milliseconds to delay
run_async If true, pump async tasks during delay (only on platforms with SKETCH_HAS_LARGE_MEMORY==1)
Definition at line 177 of file delay.cpp.hpp.
{
#if SKETCH_HAS_LARGE_MEMORY
  // Check if delay override is active (for fast testing with stub platform)
  // When override is active, skip async pumping and use platform delay directly
#if defined(FASTLED_STUB_IMPL) && (!defined(ARDUINO) || defined(FASTLED_USE_STUB_ARDUINO))
  if (isDelayOverrideActive()) {
    fl::platforms::delay(ms);  // Use platform override directly
    return;
  }
#endif
  if (run_async && ms > 0) {
    task::run(ms * 1000);
  } else {
    fl::platforms::delay(ms);  // Use platform layer for raw delay
  }
#else
  (void)run_async;  // Suppress unused parameter warning
  fl::platforms::delay(ms);  // Use platform layer for raw delay
#endif
}
References FL_NOEXCEPT, and fl::task::run().
Referenced by fl::delay(), fl::delayMillis(), and fl::delayMs().
div_by_count() [1/3]
template<typename T> fl::enable_if< fl::is_floating_point< T >::value, T >::type fl::detail::div_by_count (T sum, fl::size count) inline
Definition at line 11 of file div_by_count.h.
{ return sum / static_cast<T>(count); }
Referenced by fl::detail::SavitzkyGolayFilterImpl< T, N >::recompute(), fl::detail::AlphaTrimmedMeanImpl< T, N >::update(), fl::detail::AlphaTrimmedMeanImpl< T, N >::update(), and fl::detail::HampelFilterImpl< T, N >::update().
div_by_count() [2/3]
template<typename T> fl::enable_if< fl::is_integral< T >::value, T >::type fl::detail::div_by_count (T sum, fl::size count) inline
Definition at line 15 of file div_by_count.h.
{ return sum / static_cast<T>(count); }
div_by_count() [3/3]
template<typename T> fl::enable_if<!fl::is_floating_point< T >::value &&!fl::is_integral< T >::value, T >::type fl::detail::div_by_count (T sum, fl::size count) inline
Definition at line 20 of file div_by_count.h.
{ return sum / T(static_cast<float>(count)); }
get_copy_construct_fn() [1/2]
template<typename T> fl::enable_if< has_copy_ctor< T >::value, void(*)(void *, constvoid *) FL_NOEXCEPT >::type fl::detail::get_copy_construct_fn ()
Definition at line 223 of file basic_vector.h.
{
    return [](void* dst, const void* src) FL_NOEXCEPT {
        new (dst) T(*static_cast<const T*>(src));
    };
}
References FL_NOEXCEPT.
Referenced by fl::vector_element_ops_for().
get_copy_construct_fn() [2/2]
template<typename T> fl::enable_if<!has_copy_ctor< T >::value, void(*)(void *, constvoid *) FL_NOEXCEPT >::type fl::detail::get_copy_construct_fn ()
Definition at line 232 of file basic_vector.h.
{
    return nullptr;
}
References FL_NOEXCEPT.
get_default_construct_fn() [1/2]
template<typename T> fl::enable_if< has_default_ctor< T >::value, void(*)(void *) FL_NOEXCEPT >::type fl::detail::get_default_construct_fn ()
Definition at line 209 of file basic_vector.h.
{
    return [](void* ptr) FL_NOEXCEPT { new (ptr) T(); };
}
References FL_NOEXCEPT.
Referenced by fl::vector_element_ops_for().
get_default_construct_fn() [2/2]
template<typename T> fl::enable_if<!has_default_ctor< T >::value, void(*)(void *) FL_NOEXCEPT >::type fl::detail::get_default_construct_fn ()
Definition at line 216 of file basic_vector.h.
{
    return nullptr;
}
References FL_NOEXCEPT.
get_hex_int_width()
template<size_t Size> HexIntWidth fl::detail::get_hex_int_width () constexpr
Compile-time integer width determination (default - triggers error)
Definition at line 60 of file charconv.h.
{
    FL_STATIC_ASSERT(Size == 0, "Unsupported type size for hex conversion");
    return HexIntWidth::Width8; // Unreachable, but needed for compilation
}
References FL_NOEXCEPT, FL_STATIC_ASSERT, get_hex_int_width(), and Width8.
Referenced by get_hex_int_width(), get_hex_int_width< 1 >(), get_hex_int_width< 2 >(), get_hex_int_width< 4 >(), get_hex_int_width< 8 >(), and fl::to_hex().
get_hex_int_width< 1 >()
template<> HexIntWidth fl::detail::get_hex_int_width< 1 > () constexpr
Specialization for 1-byte types (int8_t, uint8_t, char, etc.)
Definition at line 67 of file charconv.h.
{
    return HexIntWidth::Width8;
}
References FL_NOEXCEPT, get_hex_int_width(), and Width8.
get_hex_int_width< 2 >()
template<> HexIntWidth fl::detail::get_hex_int_width< 2 > () constexpr
Specialization for 2-byte types (int16_t, uint16_t, short, etc.)
Definition at line 73 of file charconv.h.
{
    return HexIntWidth::Width16;
}
References FL_NOEXCEPT, get_hex_int_width(), and Width16.
get_hex_int_width< 4 >()
template<> HexIntWidth fl::detail::get_hex_int_width< 4 > () constexpr
Specialization for 4-byte types (int32_t, uint32_t, int, etc.)
Definition at line 79 of file charconv.h.
{
    return HexIntWidth::Width32;
}
References FL_NOEXCEPT, get_hex_int_width(), and Width32.
get_hex_int_width< 8 >()
template<> HexIntWidth fl::detail::get_hex_int_width< 8 > () constexpr
Specialization for 8-byte types (i64, u64, long long, etc.)
Definition at line 85 of file charconv.h.
{
    return HexIntWidth::Width64;
}
References FL_NOEXCEPT, get_hex_int_width(), and Width64.
get_move_construct_fn() [1/2]
template<typename T> fl::enable_if< has_move_ctor< T >::value, void(*)(void *, void *) FL_NOEXCEPT >::type fl::detail::get_move_construct_fn ()
Definition at line 255 of file basic_vector.h.
{
    return [](void* dst, void* src) FL_NOEXCEPT {
        new (dst) T(static_cast<T&&>(*static_cast<T*>(src)));
    };
}
References FL_NOEXCEPT.
Referenced by fl::vector_element_ops_for().
get_move_construct_fn() [2/2]
template<typename T> fl::enable_if<!has_move_ctor< T >::value, void(*)(void *, void *) FL_NOEXCEPT >::type fl::detail::get_move_construct_fn ()
Definition at line 263 of file basic_vector.h.
{
    return nullptr;
}
References FL_NOEXCEPT.
get_swap_fn() [1/2]
template<typename T> fl::enable_if< is_swappable< T >::value, void(*)(void *, void *) FL_NOEXCEPT >::type fl::detail::get_swap_fn ()
Definition at line 270 of file basic_vector.h.
{
    return [](void* a, void* b) FL_NOEXCEPT {
        T& ta = *static_cast<T*>(a);
        T& tb = *static_cast<T*>(b);
        T tmp(static_cast<T&&>(ta));
        ta = static_cast<T&&>(tb);
        tb = static_cast<T&&>(tmp);
    };
}
References FL_NOEXCEPT.
Referenced by fl::vector_element_ops_for().
get_swap_fn() [2/2]
template<typename T> fl::enable_if<!is_swappable< T >::value, void(*)(void *, void *) FL_NOEXCEPT >::type fl::detail::get_swap_fn ()
Definition at line 282 of file basic_vector.h.
{
    return nullptr;
}
References FL_NOEXCEPT.
get_uninitialized_move_n_fn() [1/2]
template<typename T> fl::enable_if< has_move_ctor< T >::value, void(*)(void *, void *, fl::size) FL_NOEXCEPT >::type fl::detail::get_uninitialized_move_n_fn ()
Definition at line 289 of file basic_vector.h.
{
    return [](void* dst, void* src, fl::size count) FL_NOEXCEPT {
        T* d = static_cast<T*>(dst);
        T* s = static_cast<T*>(src);
        for (fl::size i = 0; i < count; ++i) {
            new (&d[i]) T(static_cast<T&&>(s[i]));
        }
    };
}
References FL_NOEXCEPT.
Referenced by fl::vector_element_ops_for().
get_uninitialized_move_n_fn() [2/2]
template<typename T> fl::enable_if<!has_move_ctor< T >::value, void(*)(void *, void *, fl::size) FL_NOEXCEPT >::type fl::detail::get_uninitialized_move_n_fn ()
Definition at line 301 of file basic_vector.h.
{
    return nullptr;
}
References FL_NOEXCEPT.
getWaitSpinBudgetUs()
fl::u32 fl::detail::getWaitSpinBudgetUs ()
Get the current tiered-wait spin budget (microseconds).
Definition at line 29 of file wait_spin_budget.cpp.hpp.
{
    return sWaitSpinBudgetUs.load();
}
References FL_NOEXCEPT.
Referenced by CFastLED::_getWaitSpinBudgetUs(), fl::ChannelManager::waitForCondition(), and fl::IChannelDriver::waitForCondition().
heap_sort()
template<typename Iterator, typename Compare> void fl::detail::heap_sort (Iterator first, Iterator last, Compare comp)
Definition at line 398 of file algorithm.h.
{
    heapify(first, last, comp);
    Iterator end = last - 1;
    while (end > first) {
        swap(*end, *first);
        sift_down(first, first, end - 1, comp);
        --end;
    }
}
References fl::end(), FL_NOEXCEPT, heapify(), sift_down(), and fl::swap().
heapify()
template<typename Iterator, typename Compare> void fl::detail::heapify (Iterator first, Iterator last, Compare comp)
Definition at line 385 of file algorithm.h.
{
    Iterator start = first + (last - first - 2) / 2;
    while (true) {
        sift_down(first, start, last - 1, comp);
        if (start == first) {
            break;
        }
        --start;
    }
}
References FL_NOEXCEPT, and sift_down().
Referenced by heap_sort().
hex()
fl::string fl::detail::hex (u64 value, HexIntWidth width, bool is_negative, bool uppercase, bool pad_to_width)
Internal hex conversion function (implementation in charconv.cpp)
Parameters
value The unsigned 64-bit value to convert
width The bit width classification of the original type
is_negative Whether the original value was negative (for signed types)
uppercase If true, use uppercase hex digits (A-F), otherwise lowercase (a-f)
pad_to_width If true, pad with leading zeros to full type width
Returns
Hexadecimal string representation
Definition at line 12 of file charconv.cpp.hpp.
{
    // Determine target width in hex characters based on integer bit width
    size_t target_width = 0;
    switch (width) {
        case HexIntWidth::Width8:  target_width = 2; break;   // 8 bits = 2 hex chars
        case HexIntWidth::Width16: target_width = 4; break;   // 16 bits = 4 hex chars
        case HexIntWidth::Width32: target_width = 8; break;   // 32 bits = 8 hex chars
        case HexIntWidth::Width64: target_width = 16; break;  // 64 bits = 16 hex chars
    }
    fl::string result;
    const char* digits = uppercase ? "0123456789ABCDEF" : "0123456789abcdef";
    // Convert value to hex string (minimal representation)
    u64 temp_value = value;
    if (temp_value == 0) {
        // Special case: zero should be "0" not empty string
        result = fl::string("0");
    } else {
        while (temp_value > 0) {
            char ch = digits[temp_value % 16];
            // Convert char to string since fl::string::append treats char as number
            char temp_ch_str[2] = {ch, '\0'};
            fl::string digit_str(temp_ch_str);
            // Use += since + operator is not defined for fl::string
            fl::string temp = digit_str;
            temp += result;
            result = temp;
            temp_value /= 16;
        }
    }
    // Pad with leading zeros to target width (only if padding is requested)
    if (pad_to_width) {
        while (result.size() < target_width) {
            fl::string zero_str("0");
            zero_str += result;
            result = zero_str;
        }
    }
    // Add negative sign if needed
    if (is_negative) {
        fl::string minus_str("-");
        minus_str += result;
        result = minus_str;
    }
    return result;
}
References fl::numeric_limits< char >::digits, fl::type_rank< T >::value, fl::width, Width16, Width32, Width64, and Width8.
Referenced by fl::to_hex().
in_unsigned_range()
template<typename IntT> bool fl::detail::in_unsigned_range (IntT n, u32 max_u) constexpr
Definition at line 39 of file traits.h.
{
    return static_cast<i32>(fl::is_signed<IntT>::value ? (n >= IntT(0)) : 1) &&
           static_cast<u32>(n) <= max_u;
}
References FL_NOEXCEPT, and fl::fl::is_signed< T >::value.
Referenced by fl::detail::int_to_fixed< IntBits, FracBits, false >::from_unsigned(), and fl::detail::int_to_fixed< IntBits, FracBits, true >::from_unsigned().
insertion_sort()
template<typename Iterator, typename Compare> void fl::detail::insertion_sort (Iterator first, Iterator last, Compare comp)
Definition at line 298 of file algorithm.h.
{
    if (first == last) return;
    for (Iterator i = first + 1; i != last; ++i) {
        auto value = fl::move(*i);
        Iterator j = i;
        while (j != first && comp(value, *(j - 1))) {
            *j = fl::move(*(j - 1));
            --j;
        }
        *j = fl::move(value);
    }
}
References FL_NOEXCEPT, fl::fl::move(), and fl::type_rank< T >::value.
Referenced by mergesort_impl(), quicksort_impl(), and fl::sort_small().
integer_digits10_func()
template<typename T> int fl::detail::integer_digits10_func () constexpr
Definition at line 30 of file limits.h.
{
        return sizeof(T) == 1 ? 2 :
               sizeof(T) == 2 ? 4 :
               sizeof(T) == 4 ? 9 :
               sizeof(T) == 8 ? 19 : 0;
    }
References FL_NOEXCEPT.
integer_digits_func()
template<typename T> int fl::detail::integer_digits_func () constexpr
Definition at line 17 of file limits.h.
{
        return (sizeof(T) * 8) - (T(-1) < T(0) ? 1 : 0);
    }
References FL_NOEXCEPT.
integer_out_of_range_for_fixed_point_type()
void fl::detail::integer_out_of_range_for_fixed_point_type () inline
Definition at line 33 of file traits.h.
{}
References FL_NOEXCEPT.
Referenced by fl::detail::int_to_fixed< IntBits, FracBits, false >::from_signed(), fl::detail::int_to_fixed< IntBits, FracBits, true >::from_signed(), fl::detail::int_to_fixed< IntBits, FracBits, false >::from_unsigned(), and fl::detail::int_to_fixed< IntBits, FracBits, true >::from_unsigned().
ldexp_loop_()
template<typename F> F fl::detail::ldexp_loop_ (F value, int exp) inline
Definition at line 623 of file math.cpp.hpp.
{
    if (value == F(0)) return value;
    if (exp == 0) return value;
    if (exp > 0) {
        // Cap to avoid pathological loops; saturate to ±inf-ish via overflow
        // (these magnitudes are well outside the IEEE 754 finite range, and
        // returning a saturated value matches libm's behavior of producing
        // ±HUGE_VAL on overflow).
        if (exp > 1024) exp = 1024;
        while (exp >= 30) { value *= F(1073741824); exp -= 30; }  // 2^30
        while (exp > 0)  { value *= F(2); --exp; }
        return value;
    }
    // exp < 0
    int neg = -exp;
    if (neg > 1024) neg = 1024;
    while (neg >= 30) { value *= F(1.0 / 1073741824.0); neg -= 30; }
    while (neg > 0)  { value *= F(0.5); --neg; }
    return value;
}
References fl::exp(), FL_NOEXCEPT, and fl::type_rank< T >::value.
Referenced by fl::ldexp_impl_double(), and fl::ldexp_impl_float().
log_emit()
void fl::detail::log_emit (log_kind kind, const char * file, int line, fl::sstream & body)
Definition at line 31 of file log.cpp.hpp.
{
    const char* tag;
    switch (kind) {
    case log_kind::WARN:  tag = "): WARN: ";  break;
    case log_kind::ERROR: tag = "): ERROR: "; break;
    case log_kind::INFO:
    default:              tag = "): INFO: ";  break;
    }
    // Snapshot the user-supplied payload (the only thing `body`
    // contains at entry — the macro fed it only `<< X`).
    fl::string user_payload(body.str());
    // Reset body's buffer and rebuild prefix-then-payload INTO body.
    // body is in the caller's frame; the c_str() pointer we hand to
    // println below lives until the end of the FL_WARN expression.
    body.clear();
    body << file << "(" << line << tag << user_payload.c_str();
    fl::println(body.c_str());
}
References fl::basic_string::c_str(), ERROR, FL_NO_INLINE, FL_NOEXCEPT, INFO, fl::println(), and WARN.
log_natural_()
template<typename F> F fl::detail::log_natural_ (F value) inline
Definition at line 214 of file math.cpp.hpp.
{
    if (value <= F(0)) return F(-1e30);  // -inf surrogate
    int e = 0;
    while (value >= F(2)) { value *= F(0.5); ++e; }
    while (value < F(1))  { value *= F(2);   --e; }
    // value ∈ [1, 2); evaluate log(value) via Taylor around 1: let u = value - 1.
    // log(1+u) = u - u²/2 + u³/3 - u⁴/4 + ...
    // Use enough terms for ~5-decimal accuracy on [0, 1].
    const F u  = value - F(1);
    const F u2 = u * u;
    const F u3 = u2 * u;
    const F u4 = u2 * u2;
    const F u5 = u4 * u;
    const F u6 = u4 * u2;
    const F u7 = u6 * u;
    F log_m = u - u2 * F(0.5) + u3 * F(1.0 / 3.0) - u4 * F(0.25)
              + u5 * F(0.2) - u6 * F(1.0 / 6.0) + u7 * F(1.0 / 7.0);
    const F kLn2 = F(0.69314718055994530942);
    return log_m + F(e) * kLn2;
}
References FL_NOEXCEPT, and fl::type_rank< T >::value.
Referenced by fl::log10_impl_double(), fl::log10_impl_float(), fl::log_impl_double(), fl::log_impl_float(), fl::pow_impl_double(), and fl::pow_impl_float().
lower_bound_impl()
template<typename Iterator, typename T, typename Compare> Iterator fl::detail::lower_bound_impl (Iterator first, Iterator last, const T & value, Compare comp)
Definition at line 442 of file algorithm.h.
{
    auto count = last - first;
    while (count > 0) {
        auto step = count / 2;
        Iterator it = first + step;
        if (comp(*it, value)) {
            first = ++it;
            count -= step + 1;
        } else {
            count = step;
        }
    }
    return first;
}
References FL_NOEXCEPT, fl::step(), and fl::type_rank< T >::value.
Referenced by fl::lower_bound(), fl::lower_bound(), and merge_inplace().
make_lut_u16()
template<typename Fn, fl::size... Is> LutArray< u16, sizeof...(Is)> fl::detail::make_lut_u16 (fl::index_sequence< Is... >) constexpr
Definition at line 241 of file gamma_lut.h.
{
    return {{ Fn()(static_cast<u8>(Is))... }};
}
References FL_NOEXCEPT.
make_lut_u8()
template<typename Fn, fl::size... Is> LutArray< u8, sizeof...(Is)> fl::detail::make_lut_u8 (fl::index_sequence< Is... >) constexpr
Definition at line 235 of file gamma_lut.h.
{
    return {{ Fn()(static_cast<u8>(Is))... }};
}
References FL_NOEXCEPT.
makeJsonRpcError()
json fl::detail::makeJsonRpcError (int code, const fl::string & message, const json & id) inline
Definition at line 61 of file rpc_registry.h.
{
    json response = json::object();
    response.set("jsonrpc", "2.0");
    json error = json::object();
    error.set("code", code);
    error.set("message", message);
    response.set("error", error);
    if (id.has_value()) {
        response.set("id", id);
    }
    return response;
}
References fl::json::object(), and fl::json::set().
Referenced by fl::Rpc::handle().
median_of_three()
template<typename Iterator, typename Compare> Iterator fl::detail::median_of_three (Iterator first, Iterator middle, Iterator last, Compare comp)
Definition at line 316 of file algorithm.h.
{
    if (comp(*middle, *first)) {
        if (comp(*last, *middle)) {
            return middle;
        } else if (comp(*last, *first)) {
            return last;
        } else {
            return first;
        }
    } else {
        if (comp(*last, *first)) {
            return first;
        } else if (comp(*last, *middle)) {
            return last;
        } else {
            return middle;
        }
    }
}
References FL_NOEXCEPT.
Referenced by partition().
merge_inplace()
template<typename Iterator, typename Compare> void fl::detail::merge_inplace (Iterator first, Iterator middle, Iterator last, Compare comp)
Definition at line 459 of file algorithm.h.
{
    // If one of the ranges is empty, nothing to merge
    if (first == middle || middle == last) {
        return;
    }
    // If arrays are small enough, use insertion-based merge
    auto left_size = middle - first;
    auto right_size = last - middle;
    if (left_size + right_size <= 32) {
        // Simple insertion-based merge for small arrays
        Iterator left = first;
        Iterator right = middle;
        while (left < middle && right < last) {
            if (!comp(*right, *left)) {
                // left element is in correct position
                ++left;
            } else {
                // right element needs to be inserted into left part
                auto value = fl::move(*right);
                Iterator shift_end = right;
                Iterator shift_start = left;
                // Shift elements to make room
                while (shift_end > shift_start) {
                    *shift_end = fl::move(*(shift_end - 1));
                    --shift_end;
                }
                *left = fl::move(value);
                ++left;
                ++middle;  // middle has shifted right
                ++right;
            }
        }
        return;
    }
    // For larger arrays, use rotation-based merge
    if (left_size == 0 || right_size == 0) {
        return;
    }
    if (left_size == 1) {
        // Find insertion point for the single left element in right array
        Iterator pos = lower_bound_impl(middle, last, *first, comp);
        rotate_impl(first, middle, pos);
        return;
    }
    if (right_size == 1) {
        // Find insertion point for the single right element in left array
        Iterator pos = lower_bound_impl(first, middle, *(last - 1), comp);
        rotate_impl(pos, middle, last);
        return;
    }
    // Divide both arrays and recursively merge
    Iterator left_mid = first + left_size / 2;
    Iterator right_mid = lower_bound_impl(middle, last, *left_mid, comp);
    // Rotate to bring the two middle parts together
    rotate_impl(left_mid, middle, right_mid);
    // Update middle position
    Iterator new_middle = left_mid + (right_mid - middle);
    // Recursively merge the two parts
    merge_inplace(first, left_mid, new_middle, comp);
    merge_inplace(new_middle, right_mid, last, comp);
}
References FL_NOEXCEPT, lower_bound_impl(), merge_inplace(), fl::fl::move(), pos, rotate_impl(), and fl::type_rank< T >::value.
Referenced by merge_inplace(), and mergesort_impl().
mergesort_impl()
template<typename Iterator, typename Compare> void fl::detail::mergesort_impl (Iterator first, Iterator last, Compare comp)
Definition at line 534 of file algorithm.h.
{
    auto size = last - first;
    if (size <= 16) {  // Use insertion sort for small arrays (it's stable)
        insertion_sort(first, last, comp);
        return;
    }
    Iterator middle = first + size / 2;
    mergesort_impl(first, middle, comp);
    mergesort_impl(middle, last, comp);
    merge_inplace(first, middle, last, comp);
}
References FL_NOEXCEPT, insertion_sort(), merge_inplace(), and mergesort_impl().
Referenced by mergesort_impl(), and fl::stable_sort().
not_null_assert_failed()
void fl::detail::not_null_assert_failed (const char * message)
Definition at line 24 of file not_null.cpp.hpp.
{
    FL_ASSERT(false, message);
}
References FL_ASSERT.
Referenced by fl::not_null< StringHolderPtr >::not_null(), and fl::not_null< StringHolderPtr >::operator=().
partition()
template<typename Iterator, typename Compare> Iterator fl::detail::partition (Iterator first, Iterator last, Compare comp)
Definition at line 338 of file algorithm.h.
{
    Iterator middle = first + (last - first) / 2;
    Iterator pivot_iter = median_of_three(first, middle, last - 1, comp);
    // Move pivot to end
    swap(*pivot_iter, *(last - 1));
    Iterator pivot = last - 1;
    Iterator i = first;
    for (Iterator j = first; j != pivot; ++j) {
        if (comp(*j, *pivot)) {
            swap(*i, *j);
            ++i;
        }
    }
    swap(*i, *pivot);
    return i;
}
References FL_NOEXCEPT, median_of_three(), and fl::swap().
Referenced by quicksort_impl().
printLoggerDisabledError()
void fl::detail::printLoggerDisabledError (const char * category_name, const char * define_name)
Print error message for disabled logger (non-template helper) Called from checkLoggerEnabled template function IMPORTANT: This must NOT be inline - needs external linkage for cross-TU calls.
Definition at line 19 of file async_logger.cpp.hpp.
{
        FL_ERROR(category_name << " ASYNC LOGGING NOT ENABLED. "
            << "Add '#define " << define_name << "' before including FastLED.h");
    }
References FL_ERROR.
Referenced by checkLoggerEnabled().
qsort_impl()
void fl::detail::qsort_impl (char * base, size_t nmemb, size_t size, qsort_compare_fn compar)
Definition at line 417 of file cstdlib.cpp.hpp.
{
    if (nmemb <= 1) {
        return;
    }
    // Use insertion sort for small arrays (threshold of 16)
    if (nmemb <= 16) {
        qsort_insertion_sort(base, nmemb, size, compar);
        return;
    }
    size_t pivot_idx = qsort_partition(base, nmemb, size, compar);
    // Sort left partition
    qsort_impl(base, pivot_idx, size, compar);
    // Sort right partition
    if (pivot_idx + 1 < nmemb) {
        qsort_impl(base + (pivot_idx + 1) * size, nmemb - pivot_idx - 1, size, compar);
    }
}
References qsort_impl(), fl::qsort_insertion_sort(), and fl::qsort_partition().
Referenced by fl::qsort(), and qsort_impl().
qsort_swap()
void fl::detail::qsort_swap (char * a, char * b, size_t size)
Definition at line 330 of file cstdlib.cpp.hpp.
{
    if (a == b) return;
    constexpr size_t STACK_BUF_SIZE = 64;
    if (size <= STACK_BUF_SIZE) {
        char tmp[STACK_BUF_SIZE];
        memcpy(tmp, a, size);
        memcpy(a, b, size);
        memcpy(b, tmp, size);
    } else {
        for (size_t i = 0; i < size; ++i) {
            char t = a[i];
            a[i] = b[i];
            b[i] = t;
        }
    }
}
References fl::memcpy(), and fl::t.
Referenced by fl::qsort_insertion_sort(), and fl::qsort_partition().
quicksort_impl()
template<typename Iterator, typename Compare> void fl::detail::quicksort_impl (Iterator first, Iterator last, Compare comp)
Definition at line 411 of file algorithm.h.
{
    if (last - first <= 16) {  // Use insertion sort for small arrays
        insertion_sort(first, last, comp);
        return;
    }
    Iterator pivot = partition(first, last, comp);
    quicksort_impl(first, pivot, comp);
    quicksort_impl(pivot + 1, last, comp);
}
References FL_NOEXCEPT, insertion_sort(), partition(), and quicksort_impl().
Referenced by quicksort_impl(), and fl::sort().
rotate_impl()
template<typename Iterator> void fl::detail::rotate_impl (Iterator first, Iterator middle, Iterator last)
Definition at line 424 of file algorithm.h.
{
    if (first == middle || middle == last) {
        return;
    }
    Iterator next = middle;
    while (first != next) {
        swap(*first++, *next++);
        if (next == last) {
            next = middle;
        } else if (first == middle) {
            middle = next;
        }
    }
}
References FL_NOEXCEPT, and fl::swap().
Referenced by merge_inplace().
setWaitSpinBudgetUs()
void fl::detail::setWaitSpinBudgetUs (fl::u32 budget_us)
Set the tiered-wait spin budget (microseconds).
Definition at line 33 of file wait_spin_budget.cpp.hpp.
{
    sWaitSpinBudgetUs.store(budget_us);
}
References FL_NOEXCEPT.
Referenced by CFastLED::_setWaitSpinBudgetUs().
sift_down()
template<typename Iterator, typename Compare> void fl::detail::sift_down (Iterator first, Iterator start, Iterator end, Compare comp)
Definition at line 360 of file algorithm.h.
{
    Iterator root = start;
    while (root - first <= (end - first - 2) / 2) {
        Iterator child = first + 2 * (root - first) + 1;
        Iterator swap_iter = root;
        if (comp(*swap_iter, *child)) {
            swap_iter = child;
        }
        if (child + 1 <= end && comp(*swap_iter, *(child + 1))) {
            swap_iter = child + 1;
        }
        if (swap_iter == root) {
            return;
        } else {
            swap(*root, *swap_iter);
            root = swap_iter;
        }
    }
}
References fl::end(), FL_NOEXCEPT, and fl::swap().
Referenced by heap_sort(), and heapify().
sin_poly_quarterturn_()
template<typename F> F fl::detail::sin_poly_quarterturn_ (F x) inline
Definition at line 170 of file math.cpp.hpp.
{
    // sin(x) ≈ x - x³/6 + x⁵/120 - x⁷/5040
    const F x2 = x * x;
    return x * (F(1) - x2 * (F(1.0 / 6.0) - x2 * (F(1.0 / 120.0) - x2 * F(1.0 / 5040.0))));
}
References FL_NOEXCEPT, and fl::x.
Referenced by sin_reduce_().
sin_reduce_()
template<typename F> F fl::detail::sin_reduce_ (F x) inline
Definition at line 184 of file math.cpp.hpp.
{
    const F kPi      = F(3.14159265358979323846);
    const F kTwoPi   = F(6.28318530717958647692);
    const F kPiHalf  = F(1.57079632679489661923);
    // Reduce to [-π, π]: subtract floor(x / 2π) * 2π.
    // For the FastLED use cases we expect |x| < ~100, so this loop runs a
    // bounded number of times. For pathological inputs we cap iterations.
    int guard = 32;
    while (x > kPi && guard > 0) { x -= kTwoPi; --guard; }
    while (x < -kPi && guard > 0) { x += kTwoPi; --guard; }
    // Map to [-π/2, π/2] using sin(π - x) = sin(x).
    if (x > kPiHalf)  x = kPi - x;
    if (x < -kPiHalf) x = -kPi - x;
    // [-π/2, π/2] -- the polynomial works fine here (max |x| ≈ 1.57).
    return sin_poly_quarterturn_(x);
}
References FL_NOEXCEPT, sin_poly_quarterturn_(), and fl::x.
Referenced by cos_reduce_(), fl::sin_impl_double(), fl::sin_impl_float(), fl::tan_impl_double(), and fl::tan_impl_float().
singleton_registry_get()
void * fl::detail::singleton_registry_get (const char * key)
Definition at line 17 of file singleton.cpp.hpp.
{
    for (int i = 0; i < registry_count; i++) {
        if (fl::strcmp(registry[i].key, key) == 0) {
            return registry[i].value;
        }
    }
    return nullptr;
}
References fl::strcmp(), and fl::detail::anonymous_namespace{singleton.cpp.hpp}::RegistryEntry::value.
Referenced by fl::SingletonShared< T, N >::instance().
singleton_registry_set()
void fl::detail::singleton_registry_set (const char * key, void * value)
Definition at line 26 of file singleton.cpp.hpp.
{
    // Check if already registered (update)
    for (int i = 0; i < registry_count; i++) {
        if (fl::strcmp(registry[i].key, key) == 0) {
            registry[i].value = value;
            return;
        }
    }
    // Add new entry
    if (registry_count < REGISTRY_MAX) {
        registry[registry_count++] = {key, value};
    }
}
References fl::strcmp(), fl::type_rank< T >::value, and fl::detail::anonymous_namespace{singleton.cpp.hpp}::RegistryEntry::value.
Referenced by fl::SingletonShared< T, N >::instance().
slab_allocator_registry_get()
void * fl::detail::slab_allocator_registry_get (fl::size block_size, fl::size slab_size)
Definition at line 256 of file allocator.cpp.hpp.
{
    for (int i = 0; i < slab_registry_count; i++) {
        if (slab_registry[i].block_size == block_size &&
            slab_registry[i].slab_size == slab_size) {
            return slab_registry[i].allocator;
        }
    }
    return nullptr;
}
References fl::detail::anonymous_namespace{allocator.cpp.hpp}::SlabRegistryEntry::allocator.
Referenced by fl::allocator_slab< T, SLAB_SIZE >::get_allocator().
slab_allocator_registry_set()
void fl::detail::slab_allocator_registry_set (fl::size block_size, fl::size slab_size, void * allocator)
Definition at line 266 of file allocator.cpp.hpp.
{
    // Check if already registered (update)
    for (int i = 0; i < slab_registry_count; i++) {
        if (slab_registry[i].block_size == block_size &&
            slab_registry[i].slab_size == slab_size) {
            slab_registry[i].allocator = allocator;
            return;
        }
    }
    // Add new entry
    if (slab_registry_count < SLAB_REGISTRY_MAX) {
        slab_registry[slab_registry_count++] = {block_size, slab_size, allocator};
    }
}
References fl::detail::anonymous_namespace{allocator.cpp.hpp}::SlabRegistryEntry::allocator.
Referenced by fl::allocator_slab< T, SLAB_SIZE >::get_allocator().
spread_transpose16_symbol()
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void fl::detail::spread_transpose16_symbol (const u8 l[16], u8 out[16])
Transpose one symbol of 16 lanes (16 input bytes) into 16 output bytes: 8 pulses × 2 bytes, low byte = lanes 0-7, high byte = lanes 8-15, pulse order 7..0 (out[0] = pulse 7 low).
Matches the naive layout.
Definition at line 43 of file bit_spread_lut.hpp.
{
    const u32 aLo = spreadA(l[0]) | spreadA(l[1]) << 1 | spreadA(l[2]) << 2 | spreadA(l[3]) << 3 |
                    spreadA(l[4]) << 4 | spreadA(l[5]) << 5 | spreadA(l[6]) << 6 | spreadA(l[7]) << 7;
    const u32 bLo = spreadB(l[0]) | spreadB(l[1]) << 1 | spreadB(l[2]) << 2 | spreadB(l[3]) << 3 |
                    spreadB(l[4]) << 4 | spreadB(l[5]) << 5 | spreadB(l[6]) << 6 | spreadB(l[7]) << 7;
    const u32 aHi = spreadA(l[8]) | spreadA(l[9]) << 1 | spreadA(l[10]) << 2 | spreadA(l[11]) << 3 |
                    spreadA(l[12]) << 4 | spreadA(l[13]) << 5 | spreadA(l[14]) << 6 | spreadA(l[15]) << 7;
    const u32 bHi = spreadB(l[8]) | spreadB(l[9]) << 1 | spreadB(l[10]) << 2 | spreadB(l[11]) << 3 |
                    spreadB(l[12]) << 4 | spreadB(l[13]) << 5 | spreadB(l[14]) << 6 | spreadB(l[15]) << 7;
    out[0] = static_cast<u8>(aLo);        out[1] = static_cast<u8>(aHi);
    out[2] = static_cast<u8>(aLo >> 8);   out[3] = static_cast<u8>(aHi >> 8);
    out[4] = static_cast<u8>(aLo >> 16);  out[5] = static_cast<u8>(aHi >> 16);
    out[6] = static_cast<u8>(aLo >> 24);  out[7] = static_cast<u8>(aHi >> 24);
    out[8] = static_cast<u8>(bLo);        out[9] = static_cast<u8>(bHi);
    out[10] = static_cast<u8>(bLo >> 8);  out[11] = static_cast<u8>(bHi >> 8);
    out[12] = static_cast<u8>(bLo >> 16); out[13] = static_cast<u8>(bHi >> 16);
    out[14] = static_cast<u8>(bLo >> 24); out[15] = static_cast<u8>(bHi >> 24);
}
References spreadA(), and spreadB().
Referenced by wave3_transpose_16(), wave8_transpose_16(), wave8_transpose_16_bf1(), wave8_transpose_16x2_pipe2(), wave8_transpose_16x4_bf1_pipe4(), and wave8_transpose_16x4_pipe4().
spread_transpose8_symbol()
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void fl::detail::spread_transpose8_symbol (const u8 l[8], u8 out[8])
Transpose one symbol of 8 lanes (8 input bytes) into 8 output bytes: 8 pulses × 1 byte (bit L = lane L), pulse order 7..0 (out[0] = pulse 7).
Definition at line 65 of file bit_spread_lut.hpp.
{
    const u32 a = spreadA(l[0]) | spreadA(l[1]) << 1 | spreadA(l[2]) << 2 | spreadA(l[3]) << 3 |
                  spreadA(l[4]) << 4 | spreadA(l[5]) << 5 | spreadA(l[6]) << 6 | spreadA(l[7]) << 7;
    const u32 b = spreadB(l[0]) | spreadB(l[1]) << 1 | spreadB(l[2]) << 2 | spreadB(l[3]) << 3 |
                  spreadB(l[4]) << 4 | spreadB(l[5]) << 5 | spreadB(l[6]) << 6 | spreadB(l[7]) << 7;
    out[0] = static_cast<u8>(a);        out[1] = static_cast<u8>(a >> 8);
    out[2] = static_cast<u8>(a >> 16);  out[3] = static_cast<u8>(a >> 24);
    out[4] = static_cast<u8>(b);        out[5] = static_cast<u8>(b >> 8);
    out[6] = static_cast<u8>(b >> 16);  out[7] = static_cast<u8>(b >> 24);
}
References spreadA(), and spreadB().
Referenced by wave3_transpose_8(), wave8_transpose_8(), and wave8_transpose_8_bf1().
spreadA()
FASTLED_FORCE_INLINE u32 fl::detail::spreadA (u8 v)
Pulses 7,6,5,4 of v (byte j = bit (7-j)). Depends only on the high nibble.
Definition at line 35 of file bit_spread_lut.hpp.
{ return kSpreadNibble[v >> 4]; }
References FASTLED_FORCE_INLINE, and kSpreadNibble.
Referenced by spread_transpose16_symbol(), spread_transpose8_symbol(), and wave8_transpose_4_bf1().
spreadB()
FASTLED_FORCE_INLINE u32 fl::detail::spreadB (u8 v)
Pulses 3,2,1,0 of v (byte j = bit (3-j)). Depends only on the low nibble.
Definition at line 37 of file bit_spread_lut.hpp.
{ return kSpreadNibble[v & 0x0Fu]; }
References FASTLED_FORCE_INLINE, and kSpreadNibble.
Referenced by spread_transpose16_symbol(), spread_transpose8_symbol(), and wave8_transpose_4_bf1().
sqrt_newton_()
template<typename F> F fl::detail::sqrt_newton_ (F value) inline
Definition at line 151 of file math.cpp.hpp.
{
    if (value <= F(0)) return F(0);
    // Initial estimate: x_0 = value / 2. Pure-arithmetic, no bit-cast needed.
    // Newton converges quadratically so 5-6 iterations is plenty even from a
    // crude start.
    F x = value;
    if (x > F(1)) x = F(1) + (x - F(1)) * F(0.5);  // bias toward 1 for fast convergence
    for (int i = 0; i < 6; ++i) {
        if (x == F(0)) break;
        x = F(0.5) * (x + value / x);
    }
    return x;
}
References FL_NOEXCEPT, fl::type_rank< T >::value, and fl::x.
Referenced by fl::asin_impl_double(), fl::asin_impl_float(), fl::hypot_impl_double(), fl::hypot_impl_float(), fl::sqrt_impl_double(), and fl::sqrt_impl_float().
test_encoder() [1/2]
template<typename T> bool fl::detail::test_encoder (...) constexpr
Definition at line 33 of file clockless_encoder.h.
{ return false; }
References FL_NOEXCEPT.
test_encoder() [2/2]
template<typename T> auto fl::detail::test_encoder (int) -> decltype(T::ENCODER, true) constexpr
Definition at line 31 of file clockless_encoder.h.
{ return true; }
References FL_NOEXCEPT.
to_string()
void fl::detail::to_string (const fl::u16 * bit_data, fl::u32 bit_count, string * dst)
Definition at line 9 of file bitset.cpp.hpp.
{
    fl::string& result = *dst;
    constexpr fl::u32 bits_per_block = 8 * sizeof(fl::u16); // 16 bits per block
    for (fl::u32 i = 0; i < bit_count; ++i) {
        const fl::u32 block_idx = i / bits_per_block;
        const fl::u32 bit_offset = i % bits_per_block;
        // Extract the bit from the block
        bool bit_value = (bit_data[block_idx] >> bit_offset) & 1;
        result.append(bit_value ? "1" : "0");
    }
}
Referenced by FL_DISABLE_WARNING(), and fl::bitset_dynamic::to_string().
UpscalePaletteInterpolated()
template<typename TSrcPalette, typename TDestPalette> void fl::detail::UpscalePaletteInterpolated (const TSrcPalette & srcpal, TDestPalette & destpal)
Definition at line 1200 of file colorutils.cpp.hpp.
{
    const fl::u16 dest_size =
        sizeof(destpal.entries) / sizeof(destpal.entries[0]);
    for (fl::u16 i = 0; i < dest_size; ++i) {
        destpal[static_cast<fl::u8>(i)] =
            ColorFromPalette(srcpal, static_cast<fl::u8>(i));
    }
}
References fl::ColorFromPalette().
Referenced by fl::UpscalePalette(), fl::UpscalePalette(), fl::UpscalePalette(), and fl::UpscalePalette().
UpscalePaletteRepeat()
template<typename TSrcPalette, typename TDestPalette> void fl::detail::UpscalePaletteRepeat (const TSrcPalette & srcpal, TDestPalette & destpal)
Definition at line 1185 of file colorutils.cpp.hpp.
{
    const fl::u16 src_size = sizeof(srcpal.entries) / sizeof(srcpal.entries[0]);
    const fl::u16 dest_size =
        sizeof(destpal.entries) / sizeof(destpal.entries[0]);
    const fl::u16 repeat = dest_size / src_size;
    for (fl::u16 i = 0; i < src_size; ++i) {
        const fl::u16 start = i * repeat;
        for (fl::u16 j = 0; j < repeat; ++j) {
            destpal[static_cast<fl::u8>(start + j)] = srcpal[static_cast<fl::u8>(i)];
        }
    }
}
Referenced by fl::UpscalePalette(), and fl::UpscalePalette().
wave3_convert_byte_to_wave3byte()
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void fl::detail::wave3_convert_byte_to_wave3byte (u8 byte_value, const Wave3BitExpansionLut & lut, Wave3Byte * output)
Helper: Convert byte to Wave3Byte using nibble LUT (internal use only)
Note
Inline implementation for ISR performance
Definition at line 27 of file wave3.hpp.
{
    // High nibble → 12 bits, low nibble → 12 bits, total 24 bits = 3 bytes
    u16 high_pattern = lut.lut[(byte_value >> 4) & 0xF];
    u16 low_pattern = lut.lut[byte_value & 0xF];
    // Pack 24 bits into 3 bytes (MSB first):
    // Byte 0: bits [23..16] = high_pattern[11..4]
    // Byte 1: bits [15..8]  = high_pattern[3..0] | low_pattern[11..8]
    // Byte 2: bits [7..0]   = low_pattern[7..0]
    output->data[0] = (u8)(high_pattern >> 4);
    output->data[1] = (u8)(((high_pattern & 0xF) << 4) | ((low_pattern >> 8) & 0xF));
    output->data[2] = (u8)(low_pattern & 0xFF);
}
Referenced by fl::wave3(), fl::wave3Transpose_16(), fl::wave3Transpose_2(), fl::wave3Transpose_4(), and fl::wave3Transpose_8().
wave3_transpose_16()
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void fl::detail::wave3_transpose_16 (const Wave3Byte lane_waves[16], u8 output[16 *sizeof(Wave3Byte)])
Transpose 16 lanes of Wave3Byte data into interleaved format.
Parameters
lane_waves Array of 16 Wave3Byte structures
output Output buffer (48 bytes = 16 * 3)
Spread-LUT transpose (#2533): ~1.9× faster than the unrolled naive on the ESP32-P4 (RV32), bit-exact. See bit_spread_lut.hpp. Each 16-lane sample is 2 output bytes: low = lanes 0-7, high = lanes 8-15. (wave3 = 3 symbols.)
Definition at line 170 of file wave3.hpp.
{
    for (int symbol_idx = 0; symbol_idx < 3; symbol_idx++) {
        u8 l[16];
        for (int lane = 0; lane < 16; lane++) {
            l[lane] = lane_waves[lane].data[symbol_idx];
        }
        spread_transpose16_symbol(l, output + symbol_idx * 16);
    }
}
References fl::Wave3Byte::data, and spread_transpose16_symbol().
Referenced by fl::wave3Transpose_16().
wave3_transpose_2()
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void fl::detail::wave3_transpose_2 (const Wave3Byte lane_waves[2], u8 output[2 *sizeof(Wave3Byte)])
Transpose 2 lanes of Wave3Byte data into interleaved format.
Parameters
lane_waves Array of 2 Wave3Byte structures
output Output buffer (6 bytes = 2 * 3)
Definition at line 51 of file wave3.hpp.
{
    // Wave3 produces 3 symbols per LED byte (one byte per symbol for each lane).
    // For 2 lanes: interleave bits from both lanes into 2 bytes per symbol.
    // Each symbol byte has 8 bits. With 2 lanes we produce 2 bytes per symbol
    // using the same bit-spreading as wave8_transpose_2.
    for (int symbol_idx = 0; symbol_idx < 3; symbol_idx++) {
        u8 l0 = lane_waves[0].data[symbol_idx];
        u8 l1 = lane_waves[1].data[symbol_idx];
        // Interleave bits: for each bit position, lane0 goes to odd bits, lane1 to even bits
        u16 interleaved = 0;
        for (int bit = 0; bit < 8; bit++) {
            u16 b0 = (l0 >> bit) & 1;
            u16 b1 = (l1 >> bit) & 1;
            interleaved |= (b1 << (bit * 2));       // even positions
            interleaved |= (b0 << (bit * 2 + 1));   // odd positions
        }
        output[symbol_idx * 2] = (u8)(interleaved >> 8);
        output[symbol_idx * 2 + 1] = (u8)(interleaved & 0xFF);
    }
}
References fl::Wave3Byte::data.
Referenced by fl::wave3Transpose_2().
wave3_transpose_4()
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void fl::detail::wave3_transpose_4 (const Wave3Byte lane_waves[4], u8 output[4 *sizeof(Wave3Byte)])
Transpose 4 lanes of Wave3Byte data into interleaved format.
Parameters
lane_waves Array of 4 Wave3Byte structures
output Output buffer (12 bytes = 4 * 3)
Definition at line 84 of file wave3.hpp.
{
    for (int symbol_idx = 0; symbol_idx < 3; symbol_idx++) {
        u8 l0 = lane_waves[0].data[symbol_idx];
        u8 l1 = lane_waves[1].data[symbol_idx];
        u8 l2 = lane_waves[2].data[symbol_idx];
        u8 l3 = lane_waves[3].data[symbol_idx];
        // 4 output bytes per symbol (2 pulses per byte × 4 lanes)
        // Same bit layout as wave8_transpose_4
        output[symbol_idx * 4 + 0] =
            ((l3 >> 7) & 1) << 7 |
            ((l2 >> 7) & 1) << 6 |
            ((l1 >> 7) & 1) << 5 |
            ((l0 >> 7) & 1) << 4 |
            ((l3 >> 6) & 1) << 3 |
            ((l2 >> 6) & 1) << 2 |
            ((l1 >> 6) & 1) << 1 |
            ((l0 >> 6) & 1);
        output[symbol_idx * 4 + 1] =
            ((l3 >> 5) & 1) << 7 |
            ((l2 >> 5) & 1) << 6 |
            ((l1 >> 5) & 1) << 5 |
            ((l0 >> 5) & 1) << 4 |
            ((l3 >> 4) & 1) << 3 |
            ((l2 >> 4) & 1) << 2 |
            ((l1 >> 4) & 1) << 1 |
            ((l0 >> 4) & 1);
        output[symbol_idx * 4 + 2] =
            ((l3 >> 3) & 1) << 7 |
            ((l2 >> 3) & 1) << 6 |
            ((l1 >> 3) & 1) << 5 |
            ((l0 >> 3) & 1) << 4 |
            ((l3 >> 2) & 1) << 3 |
            ((l2 >> 2) & 1) << 2 |
            ((l1 >> 2) & 1) << 1 |
            ((l0 >> 2) & 1);
        output[symbol_idx * 4 + 3] =
            ((l3 >> 1) & 1) << 7 |
            ((l2 >> 1) & 1) << 6 |
            ((l1 >> 1) & 1) << 5 |
            ((l0 >> 1) & 1) << 4 |
            ((l3 >> 0) & 1) << 3 |
            ((l2 >> 0) & 1) << 2 |
            ((l1 >> 0) & 1) << 1 |
            ((l0 >> 0) & 1);
    }
}
References fl::Wave3Byte::data.
Referenced by fl::wave3Transpose_4().
wave3_transpose_8()
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void fl::detail::wave3_transpose_8 (const Wave3Byte lane_waves[8], u8 output[8 *sizeof(Wave3Byte)])
Transpose 8 lanes of Wave3Byte data into interleaved format.
Parameters
lane_waves Array of 8 Wave3Byte structures
output Output buffer (24 bytes = 8 * 3)
Spread-LUT transpose (#2533): ~1.9× faster than the unrolled naive on the ESP32-P4 (RV32), bit-exact. See bit_spread_lut.hpp. (wave3 = 3 symbols.)
Definition at line 147 of file wave3.hpp.
{
    for (int symbol_idx = 0; symbol_idx < 3; symbol_idx++) {
        u8 l[8];
        for (int lane = 0; lane < 8; lane++) {
            l[lane] = lane_waves[lane].data[symbol_idx];
        }
        spread_transpose8_symbol(l, output + symbol_idx * 8);
    }
}
References fl::Wave3Byte::data, and spread_transpose8_symbol().
Referenced by fl::wave3Transpose_8().
wave8_convert_byte_to_wave8byte()
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void fl::detail::wave8_convert_byte_to_wave8byte (u8 byte_value, const Wave8BitExpansionLut & lut, Wave8Byte * output)
Helper: Convert byte to Wave8Byte using nibble LUT (internal use only)
Note
Inline implementation for ISR performance
Definition at line 47 of file wave8.hpp.
{
    // ISR-optimized copy: Copy high nibble (4 bytes = 1 x uint32_t)
    const Wave8Bit *high_nibble_data = lut.lut[(byte_value >> 4) & 0xF];
    isr::memcpy_32(fl::bit_cast_ptr<u32>(&output->symbols[0]),
                  fl::bit_cast_ptr<const u32>(high_nibble_data),
                  1); // 4 bytes = 1 x uint32_t
    // ISR-optimized copy: Copy low nibble (4 bytes = 1 x uint32_t)
    const Wave8Bit *low_nibble_data = lut.lut[byte_value & 0xF];
    isr::memcpy_32(fl::bit_cast_ptr<u32>(&output->symbols[4]),
                  fl::bit_cast_ptr<const u32>(low_nibble_data),
                  1); // 4 bytes = 1 x uint32_t
}
References fl::bit_cast_ptr(), and fl::isr::memcpy_32().
Referenced by fl::wave8(), fl::wave8Transpose_16(), fl::wave8Transpose_2(), fl::wave8Transpose_4(), and fl::wave8Transpose_8().
wave8_expand_byte()
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void fl::detail::wave8_expand_byte (u8 byte_value, const Wave8ByteExpansionLut & lut, Wave8Byte * output)
Byte-indexed expansion (#2526): one indexed 8-byte copy.
Single lookup (no >>4/mask, no second index) into the 256×8 byte LUT; bit-identical to wave8_convert_byte_to_wave8byte(). ~half the index/issue work for the same memory traffic — the win on the in-order RV32 core.
Definition at line 69 of file wave8.hpp.
{
    isr::memcpy_32(fl::bit_cast_ptr<u32>(output),
                  fl::bit_cast_ptr<const u32>(&lut.lut[byte_value]),
                  2); // 8 bytes = 2 x uint32_t
}
References fl::bit_cast_ptr(), and fl::isr::memcpy_32().
Referenced by fl::wave8Transpose_16(), fl::wave8Transpose_16x2_pipe2(), fl::wave8Transpose_16x4_pipe4(), fl::wave8Transpose_2(), fl::wave8Transpose_4(), and fl::wave8Transpose_8().
wave8_transpose_16()
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void fl::detail::wave8_transpose_16 (const Wave8Byte lane_waves[16], u8 output[16 *sizeof(Wave8Byte)])
Transpose 16 lanes of Wave8Byte data into interleaved format.
Parameters
lane_waves Array of 16 Wave8Byte structures
output Output buffer (128 bytes)
Spread-LUT transpose (#2533): ~1.98× faster than the unrolled naive on the ESP32-P4 (RV32) — 6649→3353 us/frame, bit-exact. Two-pass (two 8x8 via u32), u64 SWAR, and Hacker's-Delight all lost to this on the in-order core; the winning shape is independent table-lookup + shift + OR-reduce (native u32, no dependency chain). See bit_spread_lut.hpp. Each 16-lane sample is 2 output bytes: low = lanes 0-7, high = lanes 8-15.
Definition at line 231 of file wave8.hpp.
{
    for (int symbol_idx = 0; symbol_idx < 8; symbol_idx++) {
        u8 l[16];
        for (int lane = 0; lane < 16; lane++) {
            l[lane] = lane_waves[lane].symbols[symbol_idx].data;
        }
        spread_transpose16_symbol(l, output + symbol_idx * 16);
    }
}
References spread_transpose16_symbol().
Referenced by fl::wave8Transpose_16(), and fl::wave8Transpose_16().
wave8_transpose_16_bf1()
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void fl::detail::wave8_transpose_16_bf1 (const u8 lanes[16], u8 W0, u8 W1, u8 output[16 *sizeof(Wave8Byte)])
BF1: chipset-aware direct encode for Wave8 16-lane (#2548 deep-dive).
Bypasses the byte_lut entirely by exploiting the algebraic identity: output_bit(s, p, lane) = M0_p XOR (input_bit_(7-s)_of_lane AND D_p) where W0/W1 are the bit-0 / bit-1 waveform patterns (chipset constants), M0_p = (W0 >> (7-p)) & 1, D_p = M0_p XOR M1_p. The bit-transpose of input lane bytes (giving the per-symbol column bytes) is computed ONCE by spread_transpose16_symbol — replacing the prior 8 calls (one per symbol) plus the 16 byte_lut expansions.
Bit-identical to wave8_transpose_16(expand(lanes_input), output). Works for ANY Wave8 chipset/timing — W0/W1 are derived from the byte_lut at runtime.
Measured 6 822 → 1 757 µs/frame (3.88× faster than pipe4, 5.49× vs baseline) when fused with pipe4 (#2548 final).
Definition at line 315 of file wave8.hpp.
{
    u8 d_mask[8];
    u8 m0_mask[8];
    const u8 D_byte = W0 ^ W1;
    for (int p = 0; p < 8; ++p) {
        const int shift = 7 - p;
        d_mask[p] = ((D_byte >> shift) & 1) ? 0xFFu : 0x00u;
        m0_mask[p] = ((W0 >> shift) & 1) ? 0xFFu : 0x00u;
    }
    // Bit-transpose: spread_transpose16_symbol on input bytes gives
    // cols[2s+h] = byte where bit L = bit(7-s) of lanes[L+8h].
    u8 cols[16];
    spread_transpose16_symbol(lanes, cols);
    for (int s = 0; s < 8; ++s) {
        const u8 col_lo = cols[2 * s + 0];
        const u8 col_hi = cols[2 * s + 1];
        for (int p = 0; p < 8; ++p) {
            output[s * 16 + p * 2 + 0] = m0_mask[p] ^ (col_lo & d_mask[p]);
            output[s * 16 + p * 2 + 1] = m0_mask[p] ^ (col_hi & d_mask[p]);
        }
    }
}
References spread_transpose16_symbol(), fl::W0, and fl::W1.
Referenced by fl::wave8Transpose_16_bf1().
wave8_transpose_16x2_pipe2()
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void fl::detail::wave8_transpose_16x2_pipe2 (const Wave8Byte lane_waves_a[16], const Wave8Byte lane_waves_b[16], u8 output_a[16 *sizeof(Wave8Byte)], u8 output_b[16 *sizeof(Wave8Byte)])
Pipe2: transpose 16-lane × 2-byte-positions in one fused call.
Result is bit-identical to two sequential wave8_transpose_16 calls; the win comes from interleaving the two independent OR-trees inside the symbol loop so the in-order RV32 P4 can fill load-use stall cycles from position A with ALU ops from position B (and vice versa). Measured +26% / frame vs sequential calls on P4 v1.3 (#2548).
Definition at line 249 of file wave8.hpp.
{
    for (int symbol_idx = 0; symbol_idx < 8; symbol_idx++) {
        u8 la[16];
        u8 lb[16];
        for (int lane = 0; lane < 16; lane++) {
            la[lane] = lane_waves_a[lane].symbols[symbol_idx].data;
            lb[lane] = lane_waves_b[lane].symbols[symbol_idx].data;
        }
        spread_transpose16_symbol(la, output_a + symbol_idx * 16);
        spread_transpose16_symbol(lb, output_b + symbol_idx * 16);
    }
}
References spread_transpose16_symbol().
Referenced by fl::wave8Transpose_16x2_pipe2().
wave8_transpose_16x4_bf1_pipe4()
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void fl::detail::wave8_transpose_16x4_bf1_pipe4 (const u8 lanes_a[16], const u8 lanes_b[16], const u8 lanes_c[16], const u8 lanes_d[16], u8 W0, u8 W1, u8 output_a[16 *sizeof(Wave8Byte)], u8 output_b[16 *sizeof(Wave8Byte)], u8 output_c[16 *sizeof(Wave8Byte)], u8 output_d[16 *sizeof(Wave8Byte)])
BF1 + pipe4: 4-position software-pipelined BF1 (#2548 deep-dive).
Combines BF1's algorithmic reduction (1 transpose per byte-position instead of 8) with pipe4's cross-position ILP. Empirical peak of all prototypes: 1 757 µs/frame vs 9 651 baseline (5.49×).
Definition at line 464 of file wave8.hpp.
{
    u8 d_mask[8];
    u8 m0_mask[8];
    const u8 D_byte = W0 ^ W1;
    for (int p = 0; p < 8; ++p) {
        const int shift = 7 - p;
        d_mask[p] = ((D_byte >> shift) & 1) ? 0xFFu : 0x00u;
        m0_mask[p] = ((W0 >> shift) & 1) ? 0xFFu : 0x00u;
    }
    u8 cols_a[16], cols_b[16], cols_c[16], cols_d[16];
    spread_transpose16_symbol(lanes_a, cols_a);
    spread_transpose16_symbol(lanes_b, cols_b);
    spread_transpose16_symbol(lanes_c, cols_c);
    spread_transpose16_symbol(lanes_d, cols_d);
    for (int s = 0; s < 8; ++s) {
        const u8 al = cols_a[2*s + 0], ah = cols_a[2*s + 1];
        const u8 bl = cols_b[2*s + 0], bh = cols_b[2*s + 1];
        const u8 cl = cols_c[2*s + 0], ch = cols_c[2*s + 1];
        const u8 dl = cols_d[2*s + 0], dh = cols_d[2*s + 1];
        for (int p = 0; p < 8; ++p) {
            const u8 dm = d_mask[p], mm = m0_mask[p];
            output_a[s*16 + p*2 + 0] = mm ^ (al & dm);
            output_a[s*16 + p*2 + 1] = mm ^ (ah & dm);
            output_b[s*16 + p*2 + 0] = mm ^ (bl & dm);
            output_b[s*16 + p*2 + 1] = mm ^ (bh & dm);
            output_c[s*16 + p*2 + 0] = mm ^ (cl & dm);
            output_c[s*16 + p*2 + 1] = mm ^ (ch & dm);
            output_d[s*16 + p*2 + 0] = mm ^ (dl & dm);
            output_d[s*16 + p*2 + 1] = mm ^ (dh & dm);
        }
    }
}
References spread_transpose16_symbol(), fl::W0, and fl::W1.
Referenced by fl::wave8Transpose_16x4_bf1_pipe4().
wave8_transpose_16x4_pipe4()
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void fl::detail::wave8_transpose_16x4_pipe4 (const Wave8Byte lane_waves_a[16], const Wave8Byte lane_waves_b[16], const Wave8Byte lane_waves_c[16], const Wave8Byte lane_waves_d[16], u8 output_a[16 *sizeof(Wave8Byte)], u8 output_b[16 *sizeof(Wave8Byte)], u8 output_c[16 *sizeof(Wave8Byte)], u8 output_d[16 *sizeof(Wave8Byte)])
Pipe4: transpose 16-lane × 4-byte-positions in one fused call.
Bit-identical to four sequential wave8_transpose_16 calls. Extends the pipe2 idea to 4 positions — empirically the peak of the curve on the in-order RV32 P4 core (#2548). pipe2 saved 26% over baseline, pipe3 36%, pipe4 41%, pipe6 regressed to 94% (register spill). Stays within the 32-GPR budget: 4 × 4 = 16 OR-tree accumulators + ~8 misc GPRs = ~24 live; pipe6 would push this past 32.
Definition at line 273 of file wave8.hpp.
{
    for (int symbol_idx = 0; symbol_idx < 8; symbol_idx++) {
        u8 la[16];
        u8 lb[16];
        u8 lc[16];
        u8 ld[16];
        for (int lane = 0; lane < 16; lane++) {
            la[lane] = lane_waves_a[lane].symbols[symbol_idx].data;
            lb[lane] = lane_waves_b[lane].symbols[symbol_idx].data;
            lc[lane] = lane_waves_c[lane].symbols[symbol_idx].data;
            ld[lane] = lane_waves_d[lane].symbols[symbol_idx].data;
        }
        spread_transpose16_symbol(la, output_a + symbol_idx * 16);
        spread_transpose16_symbol(lb, output_b + symbol_idx * 16);
        spread_transpose16_symbol(lc, output_c + symbol_idx * 16);
        spread_transpose16_symbol(ld, output_d + symbol_idx * 16);
    }
}
References spread_transpose16_symbol().
Referenced by fl::wave8Transpose_16x4_pipe4().
wave8_transpose_2()
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void fl::detail::wave8_transpose_2 (const Wave8Byte lane_waves[2], u8 output[2 *sizeof(Wave8Byte)])
Transpose 2 lanes of Wave8Byte data into interleaved format.
Parameters
lane_waves Array of 2 Wave8Byte structures (lane[0]=even bits, lane[1]=odd bits)
output Output buffer (16 bytes)
Definition at line 103 of file wave8.hpp.
{
    for (int symbol_idx = 0; symbol_idx < 8; symbol_idx++) {
        u16 interleaved = 0;
        // NOTE: FL_WAVE8_SPREAD_TO_16 macro treats first param as ODD bits, second as EVEN bits
        // This matches wave8Untranspose_2 expectations: lane[0]→odd, lane[1]→even
        FL_WAVE8_SPREAD_TO_16(lane_waves[0].symbols[symbol_idx].data,
                              lane_waves[1].symbols[symbol_idx].data,
                              interleaved);
        output[symbol_idx * 2] = (u8)(interleaved >> 8);         // High byte first (MSB pulses 4-7)
        output[symbol_idx * 2 + 1] = (u8)(interleaved & 0xFF);  // Low byte second (LSB pulses 0-3)
    }
}
References FL_WAVE8_SPREAD_TO_16.
Referenced by fl::wave8Transpose_2(), and fl::wave8Transpose_2().
wave8_transpose_2_bf1()
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void fl::detail::wave8_transpose_2_bf1 (const u8 lanes[2], u8 W0, u8 W1, u8 output[2 *sizeof(Wave8Byte)])
BF1 for 2-lane Wave8.
Output: 8 symbols × 2 bytes = 16 bytes. Each byte packs 4 pulses × 2 lanes bit-interleaved (lane 1 in even bit positions, lane 0 in odd). High byte (output[s*2 + 0]) holds bf1-pulse indices 0..3 with q=0 → pulse 3 and q=3 → pulse 0; low byte holds bf1-pulse indices 4..7 with q=0 → pulse 7 and q=3 → pulse 4. Layout matches wave8_transpose_2's LUT-based packing (see FL_WAVE8_SPREAD_TO_16 / kTranspose4_16_LUT).
Definition at line 417 of file wave8.hpp.
{
    u8 d_mask[8];
    u8 m0_mask[8];
    const u8 D_byte = W0 ^ W1;
    for (int p = 0; p < 8; ++p) {
        const int shift = 7 - p;
        d_mask[p] = ((D_byte >> shift) & 1) ? 0xFFu : 0x00u;
        m0_mask[p] = ((W0 >> shift) & 1) ? 0xFFu : 0x00u;
    }
    for (int s = 0; s < 8; ++s) {
        const int bit_idx = 7 - s;
        const u8 b0 = static_cast<u8>((lanes[0] >> bit_idx) & 1u);
        const u8 b1 = static_cast<u8>((lanes[1] >> bit_idx) & 1u);
        u8 byte_hi = 0;
        u8 byte_lo = 0;
        for (int q = 0; q < 4; ++q) {
            // Reference `wave8_transpose_2` lands chipset-byte bit (4+q) at
            // high-byte bit position (2*q) for lane 1 (even) / (2*q+1) for
            // lane 0 (odd). Chipset-byte bit (4+q) corresponds to bf1
            // pulse index (3 - q) because bf1 numbers pulse p ↔ chipset bit
            // (7 - p). Similarly the low byte uses chipset bits 0..3, which
            // map to bf1 pulses 7..4.
            const int p_hi = 3 - q;
            const int p_lo = 7 - q;
            const u8 m0_p_hi = static_cast<u8>(m0_mask[p_hi] & 1u);
            const u8 d_p_hi  = static_cast<u8>(d_mask[p_hi] & 1u);
            const u8 m0_p_lo = static_cast<u8>(m0_mask[p_lo] & 1u);
            const u8 d_p_lo  = static_cast<u8>(d_mask[p_lo] & 1u);
            const u8 v0_hi = static_cast<u8>(m0_p_hi ^ (b0 & d_p_hi));
            const u8 v1_hi = static_cast<u8>(m0_p_hi ^ (b1 & d_p_hi));
            const u8 v0_lo = static_cast<u8>(m0_p_lo ^ (b0 & d_p_lo));
            const u8 v1_lo = static_cast<u8>(m0_p_lo ^ (b1 & d_p_lo));
            byte_hi |= static_cast<u8>((v1_hi << (2 * q)) | (v0_hi << (2 * q + 1)));
            byte_lo |= static_cast<u8>((v1_lo << (2 * q)) | (v0_lo << (2 * q + 1)));
        }
        output[s * 2 + 0] = byte_hi;
        output[s * 2 + 1] = byte_lo;
    }
}
References fl::W0, and fl::W1.
Referenced by fl::wave8Transpose_2_bf1().
wave8_transpose_4()
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void fl::detail::wave8_transpose_4 (const Wave8Byte lane_waves[4], u8 output[4 *sizeof(Wave8Byte)])
Transpose 4 lanes of Wave8Byte data into interleaved format.
Parameters
lane_waves Array of 4 Wave8Byte structures
output Output buffer (32 bytes)
Definition at line 126 of file wave8.hpp.
{
    // Each symbol (Wave8Bit) has 8 pulses
    // With 4 lanes, we produce 4 bytes per symbol (2 pulses per byte × 4 lanes)
    // Output format: [L3_P7, L2_P7, L1_P7, L0_P7, L3_P6, L2_P6, L1_P6, L0_P6, ...]
    //
    // OPTIMIZED VERSION: Fully unrolled direct extraction (4.0x speedup vs baseline)
    // Based on successful 16-lane pattern that achieved 8x speedup
    // Eliminates triple-nested loops by explicitly extracting and packing bits
    // Process each symbol (8 iterations)
    for (int symbol_idx = 0; symbol_idx < 8; symbol_idx++) {
        // Pre-load all 4 lane bytes into registers
        u8 l0 = lane_waves[0].symbols[symbol_idx].data;
        u8 l1 = lane_waves[1].symbols[symbol_idx].data;
        u8 l2 = lane_waves[2].symbols[symbol_idx].data;
        u8 l3 = lane_waves[3].symbols[symbol_idx].data;
        // Explicitly construct all 4 output bytes
        // Each output byte contains 2 pulses from all 4 lanes
        // Bit layout: [L3_hi, L2_hi, L1_hi, L0_hi, L3_lo, L2_lo, L1_lo, L0_lo]
        // Byte 0: pulses 7 (hi) and 6 (lo)
        output[symbol_idx * 4 + 0] =
            ((l3 >> 7) & 1) << 7 |
            ((l2 >> 7) & 1) << 6 |
            ((l1 >> 7) & 1) << 5 |
            ((l0 >> 7) & 1) << 4 |
            ((l3 >> 6) & 1) << 3 |
            ((l2 >> 6) & 1) << 2 |
            ((l1 >> 6) & 1) << 1 |
            ((l0 >> 6) & 1);
        // Byte 1: pulses 5 (hi) and 4 (lo)
        output[symbol_idx * 4 + 1] =
            ((l3 >> 5) & 1) << 7 |
            ((l2 >> 5) & 1) << 6 |
            ((l1 >> 5) & 1) << 5 |
            ((l0 >> 5) & 1) << 4 |
            ((l3 >> 4) & 1) << 3 |
            ((l2 >> 4) & 1) << 2 |
            ((l1 >> 4) & 1) << 1 |
            ((l0 >> 4) & 1);
        // Byte 2: pulses 3 (hi) and 2 (lo)
        output[symbol_idx * 4 + 2] =
            ((l3 >> 3) & 1) << 7 |
            ((l2 >> 3) & 1) << 6 |
            ((l1 >> 3) & 1) << 5 |
            ((l0 >> 3) & 1) << 4 |
            ((l3 >> 2) & 1) << 3 |
            ((l2 >> 2) & 1) << 2 |
            ((l1 >> 2) & 1) << 1 |
            ((l0 >> 2) & 1);
        // Byte 3: pulses 1 (hi) and 0 (lo)
        output[symbol_idx * 4 + 3] =
            ((l3 >> 1) & 1) << 7 |
            ((l2 >> 1) & 1) << 6 |
            ((l1 >> 1) & 1) << 5 |
            ((l0 >> 1) & 1) << 4 |
            ((l3 >> 0) & 1) << 3 |
            ((l2 >> 0) & 1) << 2 |
            ((l1 >> 0) & 1) << 1 |
            ((l0 >> 0) & 1);
    }
}
Referenced by fl::wave8Transpose_4(), and fl::wave8Transpose_4().
wave8_transpose_4_bf1()
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void fl::detail::wave8_transpose_4_bf1 (const u8 lanes[4], u8 W0, u8 W1, u8 output[4 *sizeof(Wave8Byte)])
BF1 for 4-lane Wave8.
Output: 8 symbols × 4 bytes = 32 bytes. Each byte packs 2 pulses × 4 lanes — high nibble = earlier pulse, low nibble = later pulse; within each nibble, lanes 0..3 in bits 0..3.
Definition at line 370 of file wave8.hpp.
{
    u8 d_mask[8];
    u8 m0_mask[8];
    const u8 D_byte = W0 ^ W1;
    for (int p = 0; p < 8; ++p) {
        const int shift = 7 - p;
        d_mask[p] = ((D_byte >> shift) & 1) ? 0xFFu : 0x00u;
        m0_mask[p] = ((W0 >> shift) & 1) ? 0xFFu : 0x00u;
    }
    // Bit transpose: cols[s] (low nibble) = bit(7-s) of lanes 0..3.
    // spreadA(lanes[L]) puts the 4 high-nibble bits of lanes[L] into bit 0 of
    // 4 separate bytes; OR'd across lanes with shifts gives 4 bytes (cols[0..3]).
    const u32 aLo = spreadA(lanes[0]) | (spreadA(lanes[1]) << 1)
                  | (spreadA(lanes[2]) << 2) | (spreadA(lanes[3]) << 3);
    const u32 bLo = spreadB(lanes[0]) | (spreadB(lanes[1]) << 1)
                  | (spreadB(lanes[2]) << 2) | (spreadB(lanes[3]) << 3);
    u8 cols[8];
    cols[0] = static_cast<u8>(aLo);
    cols[1] = static_cast<u8>(aLo >> 8);
    cols[2] = static_cast<u8>(aLo >> 16);
    cols[3] = static_cast<u8>(aLo >> 24);
    cols[4] = static_cast<u8>(bLo);
    cols[5] = static_cast<u8>(bLo >> 8);
    cols[6] = static_cast<u8>(bLo >> 16);
    cols[7] = static_cast<u8>(bLo >> 24);
    for (int s = 0; s < 8; ++s) {
        const u8 col = cols[s];  // bits 0..3 = lanes 0..3
        for (int k = 0; k < 4; ++k) {
            const int p_hi = 2 * k;
            const int p_lo = 2 * k + 1;
            const u8 hi = static_cast<u8>((m0_mask[p_hi] & 0xF0u) ^ ((col << 4) & d_mask[p_hi]));
            const u8 lo = static_cast<u8>((m0_mask[p_lo] & 0x0Fu) ^ (col & d_mask[p_lo]));
            output[s * 4 + k] = static_cast<u8>(hi | lo);
        }
    }
}
References spreadA(), spreadB(), fl::W0, and fl::W1.
Referenced by fl::wave8Transpose_4_bf1().
wave8_transpose_8()
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void fl::detail::wave8_transpose_8 (const Wave8Byte lane_waves[8], u8 output[8 *sizeof(Wave8Byte)])
Transpose 8 lanes of Wave8Byte data into interleaved format.
Parameters
lane_waves Array of 8 Wave8Byte structures
output Output buffer (64 bytes)
Spread-LUT transpose (#2533): ~1.90× faster than the unrolled naive on the ESP32-P4 (RV32) — 3356→1764 us/frame, bit-exact. See bit_spread_lut.hpp.
Definition at line 205 of file wave8.hpp.
{
    for (int symbol_idx = 0; symbol_idx < 8; symbol_idx++) {
        u8 l[8];
        for (int lane = 0; lane < 8; lane++) {
            l[lane] = lane_waves[lane].symbols[symbol_idx].data;
        }
        spread_transpose8_symbol(l, output + symbol_idx * 8);
    }
}
References spread_transpose8_symbol().
Referenced by fl::wave8Transpose_8(), and fl::wave8Transpose_8().
wave8_transpose_8_bf1()
FASTLED_FORCE_INLINE FL_IRAM FL_OPTIMIZE_FUNCTION void fl::detail::wave8_transpose_8_bf1 (const u8 lanes[8], u8 W0, u8 W1, u8 output[8 *sizeof(Wave8Byte)])
BF1 for 8-lane Wave8 — same algebraic identity as 16-lane BF1.
Output: 8 symbols × 8 pulses × 1 byte = 64 bytes. Each pulse byte carries 8 lanes' bits at the corresponding pulse position. Uses spread_transpose8_symbol to compute the bit transpose in one call.
Definition at line 345 of file wave8.hpp.
{
    u8 d_mask[8];
    u8 m0_mask[8];
    const u8 D_byte = W0 ^ W1;
    for (int p = 0; p < 8; ++p) {
        const int shift = 7 - p;
        d_mask[p] = ((D_byte >> shift) & 1) ? 0xFFu : 0x00u;
        m0_mask[p] = ((W0 >> shift) & 1) ? 0xFFu : 0x00u;
    }
    u8 cols[8];
    spread_transpose8_symbol(lanes, cols);
    for (int s = 0; s < 8; ++s) {
        const u8 col = cols[s];
        for (int p = 0; p < 8; ++p) {
            output[s * 8 + p] = m0_mask[p] ^ (col & d_mask[p]);
        }
    }
}
References spread_transpose8_symbol(), fl::W0, and fl::W1.
Referenced by fl::wave8Transpose_8_bf1().
Variable Documentation
kSpreadNibble
u32 fl::detail::kSpreadNibble[16] constexpr
Initial value:
= {
    0x00000000u, 0x01000000u, 0x00010000u, 0x01010000u,
    0x00000100u, 0x01000100u, 0x00010100u, 0x01010100u,
    0x00000001u, 0x01000001u, 0x00010001u, 0x01010001u,
    0x00000101u, 0x01000101u, 0x00010101u, 0x01010101u,
}
kSpreadNibble[n] places the 4 bits of nibble n at bit 0 of 4 separate bytes: byte0 = bit3(n), byte1 = bit2(n), byte2 = bit1(n), byte3 = bit0(n).
A 16-entry literal table (C++11-valid, no constexpr loop, ~64 bytes, cache- resident). spreadA/spreadB only depend on one nibble each, so this one table serves both halves.
Definition at line 27 of file bit_spread_lut.hpp.
{
    0x00000000u, 0x01000000u, 0x00010000u, 0x01010000u,
    0x00000100u, 0x01000100u, 0x00010100u, 0x01010100u,
    0x00000001u, 0x01000001u, 0x00010001u, 0x01010001u,
    0x00000101u, 0x01000101u, 0x00010101u, 0x01010101u,
};
Referenced by spreadA(), and spreadB().
kTranspose2_4_LUT
u8 fl::detail::kTranspose2_4_LUT[4] constexpr
Initial value:
= {
    0x00,
    0x01,
    0x10,
    0x11
}
Definition at line 33 of file wave8.hpp.
{
    0x00,  // 0b00 → no bits set
    0x01,  // 0b01 → bit at position 0 (pulse 1)
    0x10,  // 0b10 → bit at position 4 (pulse 0)
    0x11   // 0b11 → bits at positions 0 and 4 (both pulses)
};
kTranspose4_16_LUT
u8 fl::detail::kTranspose4_16_LUT[16] constexpr
Initial value:
= {0x00, 0x01, 0x04, 0x05, 0x10, 0x11,
                                            0x14, 0x15, 0x40, 0x41, 0x44, 0x45,
                                            0x50, 0x51, 0x54, 0x55}
Definition at line 26 of file wave8.hpp.
                                      {0x00, 0x01, 0x04, 0x05, 0x10, 0x11,
                                            0x14, 0x15, 0x40, 0x41, 0x44, 0x45,
                                            0x50, 0x51, 0x54, 0x55};