FastLED: fl::detail::ldexp_loop_
ldexp_loop_()
template<typename F> F fl::detail::ldexp_loop_ (F value, int exp) inline
Definition at line 623 of file math.cpp.hpp.
{
    if (value == F(0)) return value;
    if (exp == 0) return value;
    if (exp > 0) {
        // Cap to avoid pathological loops; saturate to ±inf-ish via overflow
        // (these magnitudes are well outside the IEEE 754 finite range, and
        // returning a saturated value matches libm's behavior of producing
        // ±HUGE_VAL on overflow).
        if (exp > 1024) exp = 1024;
        while (exp >= 30) { value *= F(1073741824); exp -= 30; }  // 2^30
        while (exp > 0)  { value *= F(2); --exp; }
        return value;
    }
    // exp < 0
    int neg = -exp;
    if (neg > 1024) neg = 1024;
    while (neg >= 30) { value *= F(1.0 / 1073741824.0); neg -= 30; }
    while (neg > 0)  { value *= F(0.5); --neg; }
    return value;
}
References fl::exp(), FL_NOEXCEPT, and fl::type_rank< T >::value.
Referenced by fl::ldexp_impl_double(), and fl::ldexp_impl_float().