FastLED: fl::detail::qsort_impl
qsort_impl()
void fl::detail::qsort_impl (char * base, size_t nmemb, size_t size, qsort_compare_fn compar)
Definition at line 417 of file cstdlib.cpp.hpp.
{
    if (nmemb <= 1) {
        return;
    }
    // Use insertion sort for small arrays (threshold of 16)
    if (nmemb <= 16) {
        qsort_insertion_sort(base, nmemb, size, compar);
        return;
    }
    size_t pivot_idx = qsort_partition(base, nmemb, size, compar);
    // Sort left partition
    qsort_impl(base, pivot_idx, size, compar);
    // Sort right partition
    if (pivot_idx + 1 < nmemb) {
        qsort_impl(base + (pivot_idx + 1) * size, nmemb - pivot_idx - 1, size, compar);
    }
}
References qsort_impl(), fl::qsort_insertion_sort(), and fl::qsort_partition().
Referenced by fl::qsort(), and qsort_impl().