FastLED: fl::basic_string::write
write() [9/11]
template<typename T> fl::enable_if< fl::is_multi_byte_integer< T >::value, fl::size >::type fl::basic_string::write (const T & val) inline
Definition at line 210 of file basic_string.h.
{
        using target_t = typename int_cast_detail::cast_target<T>::type;
        char buf[64] = {0};
        int len;
        if (fl::is_signed<target_t>::value) {
            len = fl::itoa(static_cast<fl::i32>(val), buf, 10);
        } else {
            len = fl::utoa32(static_cast<fl::u32>(val), buf, 10);
        }
        return write(buf, len);
    }
References FL_NOEXCEPT, fl::itoa(), fl::utoa32(), fl::fl::is_signed< T >::value, and write().