FastLED: fl::basic_string::insert
insert() [5/5]
basic_string & fl::basic_string::insert (fl::size pos, fl::size count, char ch)
Definition at line 755 of file basic_string.cpp.hpp.
{
    if (pos > mLength) pos = mLength;
    if (count == 0) return *this;
    // Materialize non-owning storage before modifying
    if (isNonOwning()) {
        materialize();
    }
    fl::size newLen = mLength + count;
    // Handle COW
    if (hasHeapData() && heapData().get().use_count() > 1) {
        const NotNullStringHolderPtr& heap = heapData();
        NotNullStringHolderPtr newData = NotNullStringHolderPtr(fl::make_shared<StringHolder>(newLen));
        if (pos > 0) fl::memcpy(newData->data(), heap->data(), pos);
        for (fl::size i = 0; i < count; ++i) newData->data()[pos + i] = ch;
        if (pos < mLength) fl::memcpy(newData->data() + pos + count, heap->data() + pos, mLength - pos);
        newData->data()[newLen] = '\0';
        mStorage = newData;
        mLength = newLen;
        return *this;
    }
    // Inline buffer
    if (newLen + 1 <= mInlineCapacity && !hasHeapData()) {
        if (pos < mLength) {
            fl::memmove(inlineBufferPtr() + pos + count, inlineBufferPtr() + pos, mLength - pos);
        }
        for (fl::size i = 0; i < count; ++i) inlineBufferPtr()[pos + i] = ch;
        mLength = newLen;
        inlineBufferPtr()[mLength] = '\0';
        return *this;
    }
    // Heap in-place or new allocation
    bool canInsertInPlace = hasHeapData();
    if (canInsertInPlace) {
        NotNullStringHolderPtr& heap = heapData();
        canInsertInPlace = heap.get().use_count() <= 1 && heap->hasCapacity(newLen);
        if (canInsertInPlace) {
            char* data = heap->data();
            if (pos < mLength) fl::memmove(data + pos + count, data + pos, mLength - pos);
            for (fl::size i = 0; i < count; ++i) data[pos + i] = ch;
            mLength = newLen;
            data[mLength] = '\0';
        }
    }
    if (!canInsertInPlace) {
        NotNullStringHolderPtr newData = NotNullStringHolderPtr(fl::make_shared<StringHolder>(newLen));
        const char* src = c_str();
        if (pos > 0) fl::memcpy(newData->data(), src, pos);
        for (fl::size i = 0; i < count; ++i) newData->data()[pos + i] = ch;
        if (pos < mLength) fl::memcpy(newData->data() + pos + count, src + pos, mLength - pos);
        newData->data()[newLen] = '\0';
        mStorage = newData;
        mLength = newLen;
    }
    return *this;
}
References basic_string(), c_str(), data(), fl::get(), fl::not_null< T >::get(), hasHeapData(), heapData(), inlineBufferPtr(), isNonOwning(), fl::make_shared(), materialize(), fl::memcpy(), fl::memmove(), mInlineCapacity, mLength, mStorage, pos, and fl::shared_ptr< T >::use_count().
Referenced by insert(), insert(), and insert().