FastLED: fl::basic_string::c_str
c_str()
const char * fl::basic_string::c_str () const
Definition at line 32 of file basic_string.cpp.hpp.
{
    if (mStorage.is<ConstView>()) {
        const ConstView& view = mStorage.get<ConstView>();
        if (view.data && view.length > 0 && view.data[view.length] != '\0') {
            const_cast<basic_string*>(this)->materialize();
        }
    }
    return constData();
}
References basic_string(), constData(), fl::basic_string::ConstView::data, fl::basic_string::ConstView::length, materialize(), and mStorage.
Referenced by fl::ChannelManager::addDriver(), append(), fl::test::SerialReporter::assertResult(), assign(), at(), back(), begin(), cbegin(), cend(), charAt(), compare(), compare(), compare(), compare(), compare(), compare(), contains(), fl::detail::TypeToJson< fl::vector< fl::u8 > >::convert(), copy(), copy(), data(), end(), ends_with(), ends_with(), ends_with(), erase(), erase(), find(), find(), find(), find(), find(), find(), find_first_not_of(), find_first_not_of(), find_first_not_of(), find_first_of(), find_first_of(), find_last_not_of(), find_last_not_of(), find_last_not_of(), find_last_of(), find_last_of(), front(), fl::ChannelManager::getDriverByName(), fl::WLED::getState(), fl::Rpc::handle(), fl::Remote::has(), insert(), insert(), insert(), insert(), fl::StringInterner::intern(), fl::test::detail::TypeIterator< TypeList< T, Rest... >, TestFunc >::iterate(), fl::detail::log_emit(), loop(), anonymous_namespace{AutoResearchRemote.cpp}::measureTightTiming(), fl::test::detail::TypeNameHolder< T >::name(), openVideoEitherFormat(), operator!=(), operator!=(), fl::detail::JsonToFloatVisitor< T >::operator()(), fl::detail::JsonToIntegerVisitor< T >::operator()(), operator<(), fl::ostream::operator<<(), fl::ostream::operator<<(), fl::ostream::operator<<(), fl::ostream::operator<<(), operator<=(), operator==(), operator==(), fl::string::operator==(), operator>(), operator>=(), fl::istream_real::operator>>(), fl::istream_real::operator>>(), fl::istream_real::operator>>(), fl::istream_real::operator>>(), fl::istream_real::operator>>(), operator[](), fl::anonymous_namespace{json.cpp.hpp}::JsonTokenizer::parse(), fl::json_value::parse2_validate_only(), fl::net::http::HttpStreamTransport::parseChunkedMessages(), fl::net::http::ChunkedReader::parseChunkSize(), fl::wled::parseSegmentFields(), simd_test::print_test_result(), fl::printf(), DriverTestRunner::printHeader(), printJsonRaw(), printStreamRaw(), DriverTestRunner::printSummary(), CodecProcessor::processCodecWithTiming(), CodecProcessor::processGif(), CodecProcessor::processJpeg(), CodecProcessor::processMpeg1(), fl::Remote::processRpc(), fl::FileSystem::readScreenMap(), fl::FileSystem::readScreenMaps(), AutoResearchRemoteControl::registerFunctions(), replace(), replace(), replace(), replace(), reserve(), rfind(), rfind(), rfind(), AutoResearchRemoteControl::runParallelTestImpl(), AutoResearchRemoteControl::runSingleTestImpl(), LoopbackTestRunner::runTest(), setup(), starts_with(), starts_with(), starts_with(), fl::test::SerialReporter::subcaseStart(), fl::string::substring(), DriverTestRunner::testAllDrivers(), fl::test::SerialReporter::testCaseEnd(), fl::test::TAPReporter::testCaseEnd(), fl::test::SerialReporter::testCaseStart(), fl::test::SerialReporter::testRunEnd(), fl::test::TAPReporter::testRunEnd(), fl::test::TAPReporter::testRunStart(), DriverTestRunner::testSingleDriver(), toFloat(), fl::string::trim(), fl::Remote::unbind(), DriverTestRunner::validateExpectedDrivers(), fl::net::http::HttpStreamTransport::writeResponse(), and fl::writeSerialLine().