FastLED: fl::basic_string::replace
replace() [3/5]
basic_string & fl::basic_string::replace (fl::size pos, fl::size count, const char * s)
Definition at line 1026 of file basic_string.cpp.hpp.
{
    if (!s) return erase(pos, count);
    return replace(pos, count, s, fl::strlen(s));
}
References basic_string(), erase(), pos, replace(), and fl::strlen().