FastLED: fl::basic_string::size
size()
fl::size fl::basic_string::size () const inline
Definition at line 153 of file basic_string.h.
{ return mLength; }
References FL_NOEXCEPT, and mLength.
Referenced by basic_string(), append(), fl::SerializerVisitor::append_escaped(), fl::SerializerVisitor::append_str(), assign(), fl::base64_decode(), compare(), compare(), copy(), find_first_not_of(), find_first_of(), find_last_not_of(), find_last_of(), fl::format_detail::format_integer(), fl::format_detail::format_string(), fl::formatJsonResponse(), fl::anonymous_namespace{http_parser.cpp.hpp}::http_parser_trim(), insert(), insert(), fl::StringInterner::intern(), max_size(), operator=(), fl::string::operator==(), fl::anonymous_namespace{http_parser.cpp.hpp}::parseInt(), fl::HttpResponseParser::parseStatusLine(), fl::FileSystem::readText(), replace(), replace(), rfind(), setup(), fl::string::substr(), fl::string::substr(), fl::string::substring(), fl::SpiChannelEngineAdapter::transmitBatch(), fl::string::trim(), and fl::net::http::HttpStreamTransport::writeResponse().