FastLED: fl::basic_string::assign
assign() [5/6]
basic_string & fl::basic_string::assign (fl::size count, char c)
Definition at line 443 of file basic_string.cpp.hpp.
{
    if (count == 0) {
        clear();
        return *this;
    }
    mLength = count;
    if (count + 1 <= mInlineCapacity) {
        if (!isInline()) {
            mStorage.reset();
        }
        for (fl::size i = 0; i < count; ++i) {
            inlineBufferPtr()[i] = c;
        }
        inlineBufferPtr()[count] = '\0';
    } else {
        mStorage = NotNullStringHolderPtr(fl::make_shared<StringHolder>(count));
        NotNullStringHolderPtr& ptr = heapData();
        for (fl::size i = 0; i < count; ++i) {
            ptr->data()[i] = c;
        }
        ptr->data()[count] = '\0';
    }
    return *this;
}
References basic_string(), clear(), heapData(), inlineBufferPtr(), isInline(), fl::make_shared(), mInlineCapacity, mLength, and mStorage.