FastLED: fl::basic_string::basic_string
basic_string() [1/4]
fl::basic_string::basic_string (char * inlineBuffer, fl::size inlineCapacity) inline
Definition at line 455 of file basic_string.h.
        : mInlineOffset(static_cast<fl::size>(
              inlineBuffer -
              static_cast<char*>(static_cast<void*>(this))))
        , mInlineCapacity(inlineCapacity)
        , mLength(0)
        , mStorage() // empty variant = inline mode
    {}
References basic_string(), FL_NOEXCEPT, mInlineCapacity, mInlineOffset, mLength, mStorage, and size().
Referenced by basic_string(), basic_string(), basic_string(), basic_string(), fl::string_n< 32 >::string_n(), fl::string_n< 32 >::string_n(), fl::string_n< 32 >::string_n(), fl::string_n< 32 >::string_n(), append(), append(), append(), append(), append(), append(), append(), append(), append(), append(), append(), append(), append(), append(), append(), append(), appendHex(), appendHex(), appendHex(), appendHex(), appendHex(), appendHex(), appendHex(), appendHex(), appendOct(), appendOct(), appendOct(), appendOct(), appendOct(), appendOct(), appendOct(), appendOct(), assign(), assign(), assign(), assign(), assign(), c_str(), c_str_mutable(), compare(), compare(), compare(), contains(), copy(), ends_with(), erase(), find(), find(), find_first_not_of(), find_first_of(), find_last_not_of(), find_last_of(), insert(), insert(), insert(), insert(), insert(), moveAssign(), moveFrom(), operator!=(), operator<(), operator<=(), operator=(), operator=(), fl::string_n< 32 >::operator=(), fl::string_n< 32 >::operator=(), operator==(), operator>(), operator>=(), replace(), replace(), replace(), replace(), replace(), rfind(), starts_with(), and swapWith().