FastLED: fl::basic_string::materialize
materialize()
void fl::basic_string::materialize () protected
Definition at line 163 of file basic_string.cpp.hpp.
{
    if (mStorage.is<ConstLiteral>()) {
        const char* data = mStorage.get<ConstLiteral>().data;
        if (!data) {
            mLength = 0;
            mStorage.reset();
            inlineBufferPtr()[0] = '\0';
            return;
        }
        fl::size len = mLength;
        if (len + 1 <= mInlineCapacity) {
            fl::memcpy(inlineBufferPtr(), data, len);
            inlineBufferPtr()[len] = '\0';
            mStorage.reset();
        } else {
            mStorage = NotNullStringHolderPtr(fl::make_shared<StringHolder>(data, len));
        }
    } else if (mStorage.is<ConstView>()) {
        const ConstView& view = mStorage.get<ConstView>();
        if (!view.data) {
            mLength = 0;
            mStorage.reset();
            inlineBufferPtr()[0] = '\0';
            return;
        }
        fl::size len = view.length;
        mLength = len;
        if (len + 1 <= mInlineCapacity) {
            fl::memcpy(inlineBufferPtr(), view.data, len);
            inlineBufferPtr()[len] = '\0';
            mStorage.reset();
        } else {
            mStorage = NotNullStringHolderPtr(fl::make_shared<StringHolder>(view.data, len));
        }
    }
}
References fl::basic_string::ConstView::data, data(), inlineBufferPtr(), fl::basic_string::ConstView::length, fl::make_shared(), fl::memcpy(), mInlineCapacity, mLength, and mStorage.
Referenced by c_str(), c_str_mutable(), insert(), insert(), replace(), and replace().