FastLED: fl::basic_string::replace
replace() [5/5]
basic_string & fl::basic_string::replace (fl::size pos, fl::size count, fl::size count2, char ch)
Definition at line 1031 of file basic_string.cpp.hpp.
{
    if (pos > mLength) return *this;
    // Materialize non-owning storage before modifying
    if (isNonOwning()) {
        materialize();
    }
    fl::size actualCount = count;
    if (actualCount == npos || pos + actualCount > mLength) {
        actualCount = mLength - pos;
    }
    fl::size newLen = mLength - actualCount + count2;
    // Handle COW
    if (hasHeapData() && heapData().get().use_count() > 1) {
        const NotNullStringHolderPtr& heap = heapData();
        NotNullStringHolderPtr newData = NotNullStringHolderPtr(fl::make_shared<StringHolder>(newLen));
        if (pos > 0) fl::memcpy(newData->data(), heap->data(), pos);
        for (fl::size i = 0; i < count2; ++i) newData->data()[pos + i] = ch;
        fl::size remainingLen = mLength - pos - actualCount;
        if (remainingLen > 0) {
            fl::memcpy(newData->data() + pos + count2, heap->data() + pos + actualCount, remainingLen);
        }
        newData->data()[newLen] = '\0';
        mStorage = newData;
        mLength = newLen;
        return *this;
    }
    // Inline buffer
    if (newLen + 1 <= mInlineCapacity && !hasHeapData()) {
        if (count2 != actualCount) {
            fl::size remainingLen = mLength - pos - actualCount;
            if (remainingLen > 0) {
                fl::memmove(inlineBufferPtr() + pos + count2, inlineBufferPtr() + pos + actualCount, remainingLen);
            }
        }
        for (fl::size i = 0; i < count2; ++i) inlineBufferPtr()[pos + i] = ch;
        mLength = newLen;
        inlineBufferPtr()[mLength] = '\0';
        return *this;
    }
    // Heap in-place or new allocation
    bool canReplaceInPlace = hasHeapData();
    if (canReplaceInPlace) {
        NotNullStringHolderPtr& heap = heapData();
        canReplaceInPlace = heap.get().use_count() <= 1 && heap->hasCapacity(newLen);
        if (canReplaceInPlace) {
            char* data = heap->data();
            if (count2 != actualCount) {
                fl::size remainingLen = mLength - pos - actualCount;
                if (remainingLen > 0) {
                    fl::memmove(data + pos + count2, data + pos + actualCount, remainingLen);
                }
            }
            for (fl::size i = 0; i < count2; ++i) data[pos + i] = ch;
            mLength = newLen;
            data[mLength] = '\0';
        }
    }
    if (!canReplaceInPlace) {
        NotNullStringHolderPtr newData = NotNullStringHolderPtr(fl::make_shared<StringHolder>(newLen));
        const char* src = c_str();
        if (pos > 0) fl::memcpy(newData->data(), src, pos);
        for (fl::size i = 0; i < count2; ++i) newData->data()[pos + i] = ch;
        fl::size remainingLen = mLength - pos - actualCount;
        if (remainingLen > 0) {
            fl::memcpy(newData->data() + pos + count2, src + pos + actualCount, remainingLen);
        }
        newData->data()[newLen] = '\0';
        mStorage = newData;
        mLength = newLen;
    }
    return *this;
}
References basic_string(), c_str(), data(), fl::get(), fl::not_null< T >::get(), hasHeapData(), heapData(), inlineBufferPtr(), isNonOwning(), fl::make_shared(), materialize(), fl::memcpy(), fl::memmove(), mInlineCapacity, mLength, mStorage, npos, pos, and fl::shared_ptr< T >::use_count().