FastLED: fl::basic_string::clear
clear()
void fl::basic_string::clear (bool freeMemory = false)
Definition at line 490 of file basic_string.cpp.hpp.
{
    mLength = 0;
    if (isNonOwning() || (freeMemory && hasHeapData())) {
        mStorage.reset();
        inlineBufferPtr()[0] = '\0';
    } else {
        c_str_mutable()[0] = '\0';
    }
}
References c_str_mutable(), hasHeapData(), inlineBufferPtr(), isNonOwning(), mLength, and mStorage.
Referenced by assign(), assign(), assign(), fl::istream::getline(), fl::istream_real::getline(), fl::istream::operator>>(), fl::anonymous_namespace{json.cpp.hpp}::JsonBuilder::push_value(), and fl::istream_real::readToken().