FastLED: fl::basic_string::moveAssign
moveAssign()
void fl::basic_string::moveAssign (basic_string && other) protected
Definition at line 1218 of file basic_string.cpp.hpp.
{
    if (this == &other) return;
    if (other.isInline()) {
        mLength = other.mLength;
        mStorage.reset();
        fl::memcpy(inlineBufferPtr(), other.inlineBufferPtr(), other.mLength + 1);
    } else {
        mLength = other.mLength;
        mStorage = fl::move(other.mStorage);
    }
    other.mLength = 0;
    other.mStorage.reset();
    other.inlineBufferPtr()[0] = '\0';
}
References basic_string(), FL_NOEXCEPT, inlineBufferPtr(), fl::memcpy(), mLength, fl::fl::move(), and mStorage.
Referenced by assign(), operator=(), fl::string::operator=(), and fl::string_n< 32 >::operator=().