FastLED: makeScreenMap
makeScreenMap()
ScreenMap makeScreenMap ()
Definition at line 118 of file Fire2023.ino.
{
    fl::vector<vec2f> lut;
    for (uint16_t y = 0; y < WIDTH; y++) {
        for (uint16_t x = 0; x < HEIGHT; x++) {
            vec2f xy = {float(x) * 3, float(y) * 20};
            lut.push_back(xy);
        }
    }
    return ScreenMap(lut.data(), lut.size(), 1);
}
References fl::HeapVector< T >::data(), HEIGHT, fl::HeapVector< T >::push_back(), fl::HeapVector< T >::size(), WIDTH, x, xy(), and y.
Referenced by setup().