FastLED: fl::audio::fft::Args::Args
Args()
fl::audio::fft::Args::Args (int samples = DefaultSamples(), int bands = DefaultBands(), float fmin = DefaultMinFrequency(), float fmax = DefaultMaxFrequency(), int sample_rate = DefaultSampleRate(), Mode mode = Mode::AUTO, Window window = Window::AUTO) inline
Definition at line 139 of file fft.h.
             : samples(samples), bands(bands), fmin(fmin), fmax(fmax),
          sample_rate(sample_rate), mode(mode), window(window) {}
References fl::audio::fft::AUTO, bands, DefaultBands(), DefaultMaxFrequency(), DefaultMinFrequency(), DefaultSampleRate(), DefaultSamples(), FL_NOEXCEPT, fmax, fmin, mode, sample_rate, samples, and window.
Referenced by operator!=(), and operator==().