FastLED: fl::vector_basic::push_back_copy_impl
push_back_copy_impl()
void fl::vector_basic::push_back_copy_impl (const void * element)
Definition at line 152 of file basic_vector.cpp.hpp.
{
    ensure_capacity(mSize + 1);
    if (mSize >= mCapacity) return;  // allocation failed
    void* dst = element_ptr(mSize);
    if (mOps) {
        mOps->copy_construct(dst, element);
    } else {
        fl::memcpy(dst, element, mElementSize);
    }
    ++mSize;
}
References element_ptr(), ensure_capacity(), mCapacity, mElementSize, fl::memcpy(), mOps, and mSize.
Referenced by fl::vector< fl::i16 >::push_back().