FastLED: fl::vector_basic::insert_copy_impl
insert_copy_impl()
void fl::vector_basic::insert_copy_impl (fl::size index, const void * element)
Insert element at index by copy. Shifts subsequent elements right.
Definition at line 238 of file basic_vector.cpp.hpp.
{
    if (index > mSize) index = mSize;
    ensure_capacity(mSize + 1);
    if (mSize >= mCapacity) return;  // allocation failed
    if (mOps) {
        // Shift elements right, starting from the end
        if (mSize > index) {
            // Move-construct the last element into uninitialized space
            mOps->move_construct(element_ptr(mSize), element_ptr(mSize - 1));
            // Move-assign backwards for the rest
            for (fl::size i = mSize - 1; i > index; --i) {
                // Destroy dst, then move-construct from src
                mOps->destroy(element_ptr(i));
                mOps->move_construct(element_ptr(i), element_ptr(i - 1));
            }
            // Destroy the slot and copy-construct the new element
            mOps->destroy(element_ptr(index));
        }
        mOps->copy_construct(element_ptr(index), element);
    } else {
        // Trivial: memmove right, then memcpy
        if (mSize > index) {
            trivial_move_left(element_ptr(index + 1), element_ptr(index),
                              mSize - index);
        }
        fl::memcpy(element_ptr(index), element, mElementSize);
    }
    ++mSize;
}
References element_ptr(), ensure_capacity(), mCapacity, mElementSize, fl::memcpy(), mOps, mSize, and trivial_move_left().
Referenced by fl::vector< fl::i16 >::insert().