FastLED: fl::vector_basic::move_assign
move_assign()
void fl::vector_basic::move_assign (vector_basic & other) protected
Move-assign from another vector_basic (clears this first).
Definition at line 507 of file basic_vector.cpp.hpp.
{
    if (this == &other) return;
    clear_impl();
    if (!isInline() && mArray) {
        mResource->deallocate(mArray, mCapacity * mElementSize);
        mArray = nullptr;
        mCapacity = 0;
    }
    if (hasInlineBuffer()) {
        mArray = inlineBufferPtr();
        mCapacity = mInlineCapacity;
    }
    move_from(other);
}
References vector_basic(), clear_impl(), FL_NOEXCEPT, hasInlineBuffer(), inlineBufferPtr(), isInline(), mArray, mCapacity, mElementSize, mInlineCapacity, move_from(), and mResource.
Referenced by fl::vector< fl::i16 >::operator=(), operator=(), fl::vector_psram< T >::operator=(), and fl::VectorN< T, INLINED_SIZE >::operator=().