FastLED: fl::vector_basic::grow_to
grow_to()
void fl::vector_basic::grow_to (fl::size new_capacity) private
Grow to new_capacity. Moves existing elements.
Definition at line 58 of file basic_vector.cpp.hpp.
{
    // PATH 1: Try in-place reallocate if on heap and trivially copyable
    if (!isInline() && mArray && !mOps) {
        void* result = mResource->reallocate(mArray, mCapacity * mElementSize,
                                              new_capacity * mElementSize);
        if (result) {
            mArray = result;
            mCapacity = new_capacity;
            return;
        }
    }
    // PATH 2: Allocate new buffer, move elements, free old
    FASTLED_ASSERT(mResource != nullptr, "memory_resource is null");
    fl::size alloc_bytes = new_capacity * mElementSize;
    FASTLED_ASSERT(alloc_bytes > 0, "zero allocation in grow_to");
    void* new_buf = mResource->allocate(alloc_bytes);
    FASTLED_ASSERT(new_buf != nullptr, "allocation failed in grow_to");
    if (!new_buf) return;
    // Move existing elements to new buffer
    if (mSize > 0 && mArray) {
        if (mOps) {
            mOps->uninitialized_move_n(new_buf, mArray, mSize);
            mOps->destroy_n(mArray, mSize);
        } else {
            trivial_copy(new_buf, mArray, mSize);
        }
    }
    // Free old buffer (only if it's on the heap, not inline)
    if (!isInline() && mArray) {
        mResource->deallocate(mArray, mCapacity * mElementSize);
    }
    mArray = new_buf;
    mCapacity = new_capacity;
}
References isInline(), mArray, mCapacity, mElementSize, mOps, mResource, mSize, and trivial_copy().
Referenced by ensure_capacity(), and reserve_impl().