FastLED: fl::vector_basic::size
size()
fl::size fl::vector_basic::size () const inline
Examples
WasmScreenCoords.ino.
Definition at line 42 of file basic_vector.h.
{ return mSize; }
References FL_NOEXCEPT, and mSize.
Referenced by fl::spi::Device::Device(), fl::spi::MultiLaneDevice::MultiLaneDevice(), fl::spi::ParallelDevice::ParallelDevice(), fl::anonymous_namespace{channel.cpp.hpp}::ReorderingPixelIteratorAny::ReorderingPixelIteratorAny(), fl::Spi::Spi(), fl::UIDropdownImpl::UIDropdownImpl(), vector_basic(), CFastLED::add(), fl::detail::MethodSchema< R(Args...)>::addParams(), fl::detail::MethodSchema< void(Args...)>::addParams(), fl::audio::AutoGain::applyGain(), fl::third_party::SoftwareMpeg1Decoder::audioDecodeCallback(), fl::spi::anonymous_namespace{parallel_device.cpp.hpp}::buildDefaultLUT(), fl::audio::detector::Pitch::calculateConfidence(), fl::audio::Reactive::computeRMS(), fl::json_value::contains(), fl::SpiChannelEngineAdapter::create(), fl::Vorbis::decodeAll(), decodeSpiEdges(), fl::audio::detector::Pitch::findBestPeakLag(), FL_DISABLE_WARNING(), fl::validation::formatSummaryTable(), fl::gfx::blur_detail::get_padbuf(), fl::json_value::array_iterator< T >::get_size(), fl::SpiChannelEngineAdapter::groupByClockPin(), fl::third_party::SoftwareMpeg1Decoder::initializeDecoder(), fl::FileSystem::loadJpeg(), makeScreenMap(), anonymous_namespace{AutoResearchRemote.cpp}::maxLaneLeds(), anonymous_namespace{AutoResearchRemote.cpp}::measureTightTiming(), fl::TypeConversionResult::merge(), fl::vector< fl::i16 >::operator==(), fl::HttpRequestParser::parseBody(), fl::HttpResponseParser::parseBody(), fl::ScreenMap::ParseJson(), fl::wled::parseSegmentFields(), fl::parseV2SegmentArray(), CodecProcessor::processGif(), CodecProcessor::processJpeg(), CodecProcessor::processMpeg1(), fl::audio::Reactive::processSample(), fl::net::http::ChunkedReader::readChunk(), fl::third_party::TJpgInstanceDecoder::readStreamData(), AutoResearchRemoteControl::registerFunctions(), fl::iterator<, u8 >::rehash_internal(), runMultiTest(), AutoResearchRemoteControl::runParallelTestImpl(), AutoResearchRemoteControl::runSingleTestImpl(), fl::runSingleValidationTest(), runTest(), fl::audio::fft::Bins::setNormFactors(), fl::SpiChannelEngineAdapter::show(), and DriverTestRunner::validateExpectedDrivers().