FastLED: fl::audio::AutoGain::updatePIController
updatePIController()
float fl::audio::AutoGain::updatePIController (float targetGain, float dt) private
Update PI controller toward target gain.
Parameters
targetGain Desired gain
dt Time step in seconds
Returns
Smoothed gain output
Definition at line 159 of file auto_gain.cpp.hpp.
{
    const float error = targetGain - mLastGain;
    // Bug 4 fix: Use absolute error threshold when gain is small to avoid
    // huge errorRatio from dividing by tiny mLastGain
    const bool largeError = (mLastGain > 0.1f)
        ? (fl::abs(error) / mLastGain > 0.2f)  // Relative: >20% of current gain
        : (fl::abs(error) > 0.1f);              // Absolute: >0.1 when gain is tiny
    const float tau = largeError ? mGainFollowFastTau : mGainFollowSlowTau;
    // Proportional term
    const float pTerm = mKp * error;
    // Bug 1 fix: PI target is where we WANT gain to be (not mLastGain + delta + delta)
    // targetGain + pTerm + integrator = the desired gain level
    const float piTarget = targetGain + pTerm + mIntegrator;
    // Smooth with exponential filter using adaptive tau
    float alpha = 1.0f;
    if (tau > 0.0f && dt > 0.0f) {
        alpha = 1.0f - fl::exp(-dt / tau);
    }
    const float unclamped = mLastGain + alpha * (piTarget - mLastGain);
    // Bug 2 fix: Back-calculation anti-windup — only accumulate integrator
    // when output is NOT clamped. Decay integrator when saturated (WLED: *= 0.91)
    const bool saturated = (unclamped > mConfig.maxGain) || (unclamped < mConfig.minGain);
    if (saturated) {
        mIntegrator *= 0.91f;
    } else {
        mIntegrator += mKi * error * dt;
    }
    // Clamp integrator magnitude to prevent runaway in pathological cases
    const float maxIntegral = 4.0f * mConfig.maxGain;
    mIntegrator = fl::max(-maxIntegral, fl::min(maxIntegral, mIntegrator));
    return unclamped;
}
References fl::abs(), fl::exp(), fl::max(), mConfig, mGainFollowFastTau, mGainFollowSlowTau, fl::min(), mIntegrator, mKi, mKp, and mLastGain.
Referenced by process().