FastLED: fl::audio::AutoGain::process
process()
Sample fl::audio::AutoGain::process (const Sample & sample)
Process audio sample with automatic gain adjustment.
Parameters
sample Input audio sample
Returns
Gain-adjusted audio sample
Definition at line 78 of file auto_gain.cpp.hpp.
{
    // Pass through if disabled
    if (!mConfig.enabled) {
        return sample;
    }
    // Return empty sample if input is invalid or empty
    if (!sample.isValid() || sample.size() == 0) {
        return Sample();  // Return invalid sample
    }
    // Calculate input RMS
    const float inputRMS = sample.rms();
    mStats.inputRMS = inputRMS;
    // Compute dt from sample size and sample rate
    const float dt = (mSampleRate > 0 && sample.size() > 0)
        ? static_cast<float>(sample.size()) / static_cast<float>(mSampleRate)
        : 0.023f;
    // Silence detection: spin down integrator when input is essentially silent
    // (WLED: control_integrated *= 0.91 during silence)
    const float silenceThreshold = 10.0f;
    if (inputRMS < silenceThreshold) {
        mIntegrator *= 0.91f;
        if (fl::abs(mIntegrator) < 0.01f) mIntegrator = 0.0f;
    }
    // Step 1: Update peak envelope (fast attack, slow decay)
    mPeakEnvelope.update(inputRMS, dt);
    const float peakEnv = mPeakEnvelope.value();
    mStats.peakEnvelope = peakEnv;
    // Step 2: Compute target gain from peak envelope
    const float targetGain = computeTargetGain();
    mStats.targetGain = targetGain;
    // Step 3: PI controller smoothly drives gain toward target
    const float smoothedGain = updatePIController(targetGain, dt);
    // Step 4: Clamp to configured range
    const float clampedGain = fl::max(mConfig.minGain,
                                       fl::min(mConfig.maxGain, smoothedGain));
    mStats.currentGain = clampedGain;
    mLastGain = clampedGain;
    // Step 5: Apply gain to audio
    const auto& pcm = sample.pcm();
    mOutputBuffer.clear();
    mOutputBuffer.reserve(pcm.size());
    applyGain(pcm, clampedGain, mOutputBuffer);
    // Calculate output RMS for statistics
    i64 sumSq = 0;
    for (size i = 0; i < mOutputBuffer.size(); ++i) {
        i32 val = static_cast<i32>(mOutputBuffer[i]);
        sumSq += val * val;
    }
    mStats.outputRMS = sqrtf(static_cast<float>(sumSq) / static_cast<float>(mOutputBuffer.size()));
    // Update stats
    mStats.samplesProcessed += sample.size();
    mStats.integrator = mIntegrator;
    // Create new Sample from amplified PCM
    SampleImplPtr impl = fl::make_shared<SampleImpl>();
    impl->assign(mOutputBuffer.begin(), mOutputBuffer.end(), sample.timestamp());
    return Sample(impl);
}
References fl::abs(), applyGain(), computeTargetGain(), fl::make_shared(), fl::max(), mConfig, fl::min(), mIntegrator, mLastGain, mOutputBuffer, mPeakEnvelope, mSampleRate, mStats, fl::sample(), fl::sqrtf(), and updatePIController().
Referenced by ~AutoGain().