FastLED: fl::audio::detector::Silence::update
update()
void fl::audio::detector::Silence::update (shared_ptr< Context > context) override virtual
Implements fl::audio::Detector.
Definition at line 29 of file silence.cpp.hpp.
{
    mCurrentRMS = context->getRMS();
    u32 timestamp = context->getTimestamp();
    mLastUpdateTime = timestamp;
    // Build history
    if (mRMSHistory.size() < static_cast<fl::size>(mHistorySize)) {
        mRMSHistory.push_back(mCurrentRMS);
    } else {
        mRMSHistory[mHistoryIndex] = mCurrentRMS;
        mHistoryIndex = (mHistoryIndex + 1) % mHistorySize;
    }
    // Get smoothed RMS
    float smoothedRMS = getSmoothedRMS();
    // Check silence condition with hysteresis
    bool nowSilent = checkSilenceCondition(smoothedRMS);
    // State transition logic
    if (nowSilent && !mPreviousSilent) {
        // Entering silence
        mSilenceStartTime = timestamp;
        mPreviousSilent = true;
    } else if (!nowSilent && mPreviousSilent) {
        // Exiting silence
        mSilenceEndTime = timestamp;
        u32 duration = mSilenceEndTime - mSilenceStartTime;
        // Only fire callbacks if minimum duration was met
        if (mIsSilent && duration >= mMinSilenceDuration) {
            mPendingEvent = PendingSilenceEvent::kEnd;
            mPendingDuration = duration;
        }
        mIsSilent = false;
        mPreviousSilent = false;
        mSilenceStartTime = 0;
    } else if (nowSilent && mPreviousSilent) {
        // Continuing silence
        u32 duration = timestamp - mSilenceStartTime;
        // Check if we've reached minimum duration and should fire start event
        if (!mIsSilent && duration >= mMinSilenceDuration) {
            mIsSilent = true;
            mPendingEvent = PendingSilenceEvent::kStart;
        }
        // Check if we've exceeded maximum duration
        if (mIsSilent && mMaxSilenceDuration > 0 && duration >= mMaxSilenceDuration) {
            mPendingEvent = PendingSilenceEvent::kMaxDuration;
            mPendingDuration = duration;
        }
    }
}
References Silence(), checkSilenceCondition(), getSmoothedRMS(), kEnd, kMaxDuration, kStart, mCurrentRMS, mHistorySize, mIsSilent, mLastUpdateTime, mMaxSilenceDuration, mMinSilenceDuration, mPendingDuration, mPendingEvent, mPreviousSilent, mRMSHistory, mSilenceEndTime, mSilenceStartTime, and update().
Referenced by ~Silence(), and update().