/// @file _build.hpp
/// @brief Unity build header for fl/ directory
/// Includes all implementation files in alphabetical order

// Note: Teensy 3.x <new.h> compatibility is handled in _build.cpp
// which includes is_teensy.h before this header.

#include "fl/async.cpp.hpp"
#include "fl/audio.cpp.hpp"
#include "fl/audio_input.cpp.hpp"
#include "fl/audio_reactive.cpp.hpp"
#include "fl/blur.cpp.hpp"
#include "fl/bytestreammemory.cpp.hpp"
#include "fl/colorutils.cpp.hpp"
#include "fl/corkscrew.cpp.hpp"
#include "fl/delay.cpp.hpp"
#include "fl/downscale.cpp.hpp"
#include "fl/ease.cpp.hpp"
#include "fl/engine_events.cpp.hpp"
#include "fl/fastled_internal.cpp.hpp"
#include "fl/fft.cpp.hpp"
#include "fl/fft_impl.cpp.hpp"
#include "fl/file_system.cpp.hpp"
#include "fl/fill.cpp.hpp"
#include "fl/fixed_point/_build.cpp.hpp"
#include "fl/fltest.cpp.hpp"
#include "fl/gamma.cpp.hpp"
#include "fl/gradient.cpp.hpp"
#include "fl/hsv16.cpp.hpp"
#include "fl/id_tracker.cpp.hpp"
#include "fl/isr.cpp.hpp"
#include "fl/json.cpp.hpp"
#include "fl/leds.cpp.hpp"
#include "fl/line_simplification.cpp.hpp"
#include "fl/log.cpp.hpp"
#include "fl/memfill.cpp.hpp"
#include "fl/memory.cpp.hpp"
#include "fl/net/_build.cpp.hpp"
#include "fl/noise.cpp.hpp"
#include "fl/noise_woryley.cpp.hpp"
#include "fl/ota.cpp.hpp"
#include "fl/pin.cpp.hpp"
#include "fl/raster_sparse.cpp.hpp"
#include "fl/rectangular_draw_buffer.cpp.hpp"
#include "fl/remote/_build.cpp.hpp"
#include "fl/rgbw.cpp.hpp"
#include "fl/rx_device.cpp.hpp"
#include "fl/screenmap.cpp.hpp"
#include "fl/serial.cpp.hpp"
#include "fl/sin32.cpp.hpp"
#include "fl/spi.cpp.hpp"
#include "fl/splat.cpp.hpp"
#include "fl/static_constexpr_defs.cpp.hpp"
#include "fl/str_ui.cpp.hpp"
#include "fl/string_view.cpp.hpp"
#include "fl/task.cpp.hpp"
#include "fl/tile2x2.cpp.hpp"
#include "fl/time_alpha.cpp.hpp"
#include "fl/trace.cpp.hpp"
#include "fl/transform.cpp.hpp"
#include "fl/transposition.cpp.hpp"
#include "fl/ui.cpp.hpp"
#include "fl/upscale.cpp.hpp"
#include "fl/wave_simulation.cpp.hpp"
#include "fl/wave_simulation_real.cpp.hpp"
#include "fl/xmap.cpp.hpp"
#include "fl/xymap.cpp.hpp"
#include "fl/xypath.cpp.hpp"
#include "fl/xypath_impls.cpp.hpp"
#include "fl/xypath_renderer.cpp.hpp"
