FastLED: fl::detail::PromiseImpl::resolve
resolve() [2/2]
template<typename T> bool fl::detail::PromiseImpl< T >::resolve (T && value) inline
Definition at line 304 of file promise.h.
{
        if (mState != PromiseState_t::PENDING) return false;
        mValue = fl::move(value);
        mState = PromiseState_t::RESOLVED;
        // Process callback immediately if we have one
        if (mThenCallback && !mCallbacksProcessed) {
            process_callbacks();
        }
        return true;
    }
References mCallbacksProcessed, fl::move(), mState, mThenCallback, mValue, fl::detail::PENDING, process_callbacks(), fl::detail::RESOLVED, and value().