FastLED: fl::TwinkleFox::drawTwinkleFox
drawTwinkleFox()
void fl::TwinkleFox::drawTwinkleFox (fl::span< CRGB > leds) inline private
Definition at line 138 of file twinklefox.h.
{
        // "PRNG16" is the pseudorandom number generator
        // It MUST be reset to the same starting value each time
        // this function is called, so that the sequence of 'random'
        // numbers that it generates is (paradoxically) stable.
        u16 PRNG16 = 11337;
        fl::u32 clock32 = fl::millis();
        CRGB bg = backgroundColor;
        if (autoSelectBackgroundColor &&
            currentPalette[0] == currentPalette[1]) {
            bg = currentPalette[0];
            u8 bglight = bg.getAverageLight();
            if (bglight > 64) {
                bg.nscale8_video(16);
            } else if (bglight > 16) {
                bg.nscale8_video(64);
            } else {
                bg.nscale8_video(86);
            }
        }
        u8 backgroundBrightness = bg.getAverageLight();
        for (u16 i = 0; i < mNumLeds; i++) {
            PRNG16 = (u16)(PRNG16 * 2053) + 1384;
            u16 myclockoffset16 = PRNG16;
            PRNG16 = (u16)(PRNG16 * 2053) + 1384;
            u8 myspeedmultiplierQ5_3 =
                ((((PRNG16 & 0xFF) >> 4) + (PRNG16 & 0x0F)) & 0x0F) + 0x08;
            fl::u32 myclock30 =
                (fl::u32)((clock32 * myspeedmultiplierQ5_3) >> 3) +
                myclockoffset16;
            u8 myunique8 = PRNG16 >> 8;
            CRGB c = computeOneTwinkle(myclock30, myunique8);
            u8 cbright = c.getAverageLight();
            i16 deltabright = cbright - backgroundBrightness;
            if (deltabright >= 32 || (!bg)) {
                leds[i] = c;
            } else if (deltabright > 0) {
                leds[i] = blend(bg, c, deltabright * 8);
            } else {
                leds[i] = bg;
            }
        }
    }
References autoSelectBackgroundColor, backgroundColor, fl::blend(), computeOneTwinkle(), currentPalette, fl::CRGB::getAverageLight(), leds, fl::millis(), fl::Fx::mNumLeds, and fl::CRGB::nscale8_video().
Referenced by draw().