FastLED: fl::TwinkleFox::drawTwinkleFox
drawTwinkleFox()
void fl::TwinkleFox::drawTwinkleFox (CRGB * leds) inline private
Definition at line 142 of file twinklefox.h.
{
        // "PRNG16" is the pseudorandom number generator
        // It MUST be reset to the same starting value each time
        // this function is called, so that the sequence of 'random'
        // numbers that it generates is (paradoxically) stable.
        uint16_t PRNG16 = 11337;
        uint32_t clock32 = millis();
        CRGB bg = backgroundColor;
        if (autoSelectBackgroundColor &&
            currentPalette[0] == currentPalette[1]) {
            bg = currentPalette[0];
            uint8_t bglight = bg.getAverageLight();
            if (bglight > 64) {
                bg.nscale8_video(16);
            } else if (bglight > 16) {
                bg.nscale8_video(64);
            } else {
                bg.nscale8_video(86);
            }
        }
        uint8_t backgroundBrightness = bg.getAverageLight();
        for (uint16_t i = 0; i < mNumLeds; i++) {
            PRNG16 = (uint16_t)(PRNG16 * 2053) + 1384;
            uint16_t myclockoffset16 = PRNG16;
            PRNG16 = (uint16_t)(PRNG16 * 2053) + 1384;
            uint8_t myspeedmultiplierQ5_3 =
                ((((PRNG16 & 0xFF) >> 4) + (PRNG16 & 0x0F)) & 0x0F) + 0x08;
            uint32_t myclock30 =
                (uint32_t)((clock32 * myspeedmultiplierQ5_3) >> 3) +
                myclockoffset16;
            uint8_t myunique8 = PRNG16 >> 8;
            CRGB c = computeOneTwinkle(myclock30, myunique8);
            uint8_t cbright = c.getAverageLight();
            int16_t deltabright = cbright - backgroundBrightness;
            if (deltabright >= 32 || (!bg)) {
                leds[i] = c;
            } else if (deltabright > 0) {
                leds[i] = blend(bg, c, deltabright * 8);
            } else {
                leds[i] = bg;
            }
        }
    }
References autoSelectBackgroundColor, backgroundColor, blend(), computeOneTwinkle(), currentPalette, CRGB::getAverageLight(), leds, fl::Fx::mNumLeds, and CRGB::nscale8_video().
Referenced by draw().