FastLED: fl::TwinkleFox::computeOneTwinkle
computeOneTwinkle()
CRGB fl::TwinkleFox::computeOneTwinkle (uint32_t ms, uint8_t salt) inline private
Definition at line 189 of file twinklefox.h.
{
        uint16_t ticks = ms >> (8 - twinkleSpeed);
        uint8_t fastcycle8 = ticks;
        uint16_t slowcycle16 = (ticks >> 8) + salt;
        slowcycle16 += sin8(slowcycle16);
        slowcycle16 = (slowcycle16 * 2053) + 1384;
        uint8_t slowcycle8 = (slowcycle16 & 0xFF) + (slowcycle16 >> 8);
        uint8_t bright = 0;
        if (((slowcycle8 & 0x0E) / 2) < twinkleDensity) {
            bright = attackDecayWave8(fastcycle8);
        }
        uint8_t hue = slowcycle8 - salt;
        CRGB c;
        if (bright > 0) {
            c = ColorFromPalette(currentPalette, hue, bright, NOBLEND);
            if (coolLikeIncandescent) {
                coolLikeIncandescentFunction(c, fastcycle8);
            }
        } else {
            c = CRGB::Black;
        }
        return c;
    }
References attackDecayWave8(), CRGB::Black, fl::ColorFromPalette(), coolLikeIncandescent, coolLikeIncandescentFunction(), currentPalette, sin8, twinkleDensity, and twinkleSpeed.
Referenced by drawTwinkleFox().