FastLED: fl::audio::fft::fl_fft_real_forward
fl_fft_real_forward()
void fl::audio::fft::fl_fft_real_forward (kiss_fftr_cfg cfg, int N, const kiss_fft_scalar * in, kiss_fft_cpx * out) inline
Forward real-to-complex FFT.
Parameters
cfg Kiss FFT real-to-complex plan describing the size N. Used directly by the kiss backend; the ESP-DSP backend ignores cfg and uses its own cached context keyed by N.
N Logical FFT size (must match the size cfg was allocated for). Redundant for kiss (embedded in cfg) but required for ESP-DSP because kiss_fftr_cfg is opaque.
in Pointer to N real time-domain samples.
out Pointer to N/2 + 1 complex frequency-domain bins.
Output format matches kiss_fftr exactly regardless of backend.
Definition at line 237 of file fft_backend.h.
{
    // NOTE: even when FL_FFT_ESP_DSP_ACTIVE is 1, the dispatcher currently
    // stays on kiss_fftr. The ESP-DSP backend below is `float`-only but
    // kiss_fft_scalar is typedef'd to `int16_t` when FastLED's default
    // FASTLED_FFT_PRECISION=FASTLED_FFT_FIXED16 is in effect. Auto-routing
    // through ESP-DSP would break the int16 call sites in fft_impl.cpp.hpp.
    //
    // Future work: either (a) add an int16 packed-FFT variant using
    // dsps_fft2r_sc16 to match FIXED16 mode, or (b) auto-switch the library
    // to FASTLED_FFT_FLOAT when FL_FFT_ESP_DSP_AVAILABLE is on. Once wired,
    // replace the below with a conditional call to detail::espDspRealForward.
    //
    // The ESP-DSP code is compiled in whenever the ESP32 toolchain ships
    // esp_dsp.h (auto-detected via FL_HAS_INCLUDE) and exposed as
    // fl::audio::fft::detail::espDspRealForward() so the AudioFftParity
    // example can exercise it directly for validation.
    (void)N;
    kiss_fftr(cfg, in, out);
}
References FL_NOEXCEPT, kiss_fft_scalar, and kiss_fftr().
Referenced by fl::audio::fft::Context::runHybrid(), fl::audio::fft::Context::runLogRebin(), fl::audio::fft::Context::runNaive(), and fl::audio::fft::Context::runOctaveWise().