FastLED: fl::printf_detail::apply_width
apply_width()
fl::string fl::printf_detail::apply_width (const fl::string & str, const FormatSpec & spec, bool is_numeric = false) inline
Definition at line 220 of file stdio.h.
{
    int len = static_cast<int>(str.length());
    // No width specified or content already wider
    if (spec.width <= len) {
        return str;
    }
    int padding = spec.width - len;
    char pad_char = ' ';
    // Zero-padding only for numeric types and right-align
    if (spec.zero_pad && is_numeric && !spec.left_align) {
        pad_char = '0';
        // Handle sign for zero-padding: move sign to front
        if (!str.empty() && (str[0] == '-' || str[0] == '+' || str[0] == ' ')) {
            fl::string result;
            result += str[0]; // Sign first
            for (int i = 0; i < padding; ++i) {
                result += pad_char;
            }
            for (size_t i = 1; i < str.length(); ++i) {
                result += str[i];
            }
            return result;
        }
        // Handle 0x prefix for zero-padding
        if (str.length() >= 2 && str[0] == '0' && (str[1] == 'x' || str[1] == 'X')) {
            fl::string result;
            result += str[0]; // '0'
            result += str[1]; // 'x' or 'X'
            for (int i = 0; i < padding; ++i) {
                result += pad_char;
            }
            for (size_t i = 2; i < str.length(); ++i) {
                result += str[i];
            }
            return result;
        }
    }
    fl::string result;
    if (spec.left_align) {
        // Left-align: content then padding
        result = str;
        for (int i = 0; i < padding; ++i) {
            result += pad_char;
        }
    } else {
        // Right-align: padding then content
        for (int i = 0; i < padding; ++i) {
            result += pad_char;
        }
        result += str;
    }
    return result;
}
References fl::basic_string::empty(), FL_NOEXCEPT, fl::printf_detail::FormatSpec::left_align, fl::basic_string::length(), fl::printf_detail::FormatSpec::width, and fl::printf_detail::FormatSpec::zero_pad.
Referenced by format_arg(), and format_arg().