FastLED: fl::printf_detail::format_arg
format_arg() [3/3]
template<typename T> void fl::printf_detail::format_arg (StrStream & stream, const FormatSpec & spec, const T & arg)
Definition at line 225 of file printf.h.
{
    switch (spec.type) {
        case 'd':
        case 'i':
            if (fl::is_integral<T>::value) {
                stream << arg;
            } else {
                stream << "<type_error>";
            }
            break;
        case 'u':
            if (fl::is_integral<T>::value) {
                // Convert unsigned manually since StrStream treats all as signed
                unsigned int val = static_cast<unsigned int>(arg);
                if (val == 0) {
                    stream << "0";
                } else {
                    fl::string result;
                    while (val > 0) {
                        char digit = '0' + (val % 10);
                        char temp_str[2] = {digit, '\0'};
                        fl::string digit_str(temp_str);
                        fl::string temp = digit_str;
                        temp += result;
                        result = temp;
                        val /= 10;
                    }
                    stream << result;
                }
            } else {
                stream << "<type_error>";
            }
            break;
        case 'f':
            if (fl::is_floating_point<T>::value) {
                if (spec.precision >= 0) {
                    stream << format_float(static_cast<float>(arg), spec.precision);
                } else {
                    stream << arg;
                }
            } else {
                stream << "<type_error>";
            }
            break;
        case 'c':
            if (fl::is_integral<T>::value) {
                char ch = static_cast<char>(arg);
                // Convert char to string since StrStream treats char as number
                char temp_str[2] = {ch, '\0'};
                stream << temp_str;
            } else {
                stream << "<type_error>";
            }
            break;
        case 'x':
            stream << to_hex(arg, spec.uppercase);
            break;
        case 's':
            stream << arg; // StrStream handles string conversion
            break;
        default:
            stream << "<unknown_format>";
            break;
    }
}
References fl::printf_detail::FormatSpec::precision, to_hex(), fl::printf_detail::FormatSpec::type, fl::printf_detail::FormatSpec::uppercase, fl::is_floating_point< T >::value, and fl::is_integral< T >::value.
Referenced by format_arg(), and format_impl().