FastLED: fl::printf_detail::format_impl
format_impl() [2/2]
template<typename T, typename... Args> void fl::printf_detail::format_impl (sstream & stream, const char * format, const T & first, const Args &... rest)
Definition at line 586 of file stdio.h.
{
    while (*format) {
        if (*format == '%') {
            FormatSpec spec = parse_format_spec(format);
            if (spec.type == '%') {
                stream << "%";
                continue;
            } else {
                // Format the first argument and continue with the rest
                format_arg(stream, spec, first);
                format_impl(stream, format, rest...);
                return;
            }
        } else {
            // Create a single-character string since sstream treats char as number
            char temp_str[2] = {*format, '\0'};
            stream << temp_str;
            ++format;
        }
    }
    // If we get here, there are unused arguments
    // This is not an error in printf, so we just ignore them
}
References FL_NOEXCEPT, fl::format(), format_arg(), format_impl(), parse_format_spec(), and fl::printf_detail::FormatSpec::type.