FastLED: fl::printf_detail::format_impl
format_impl() [1/2]
void fl::printf_detail::format_impl (StrStream & stream, const char * format) inline
Definition at line 326 of file printf.h.
{
    while (*format) {
        if (*format == '%') {
            FormatSpec spec = parse_format_spec(format);
            if (spec.type == '%') {
                stream << "%";
            } else {
                // No argument for format specifier
                stream << "<missing_arg>";
            }
        } else {
            // Create a single-character string since StrStream treats char as number
            char temp_str[2] = {*format, '\0'};
            stream << temp_str;
            ++format;
        }
    }
}
References parse_format_spec(), and fl::printf_detail::FormatSpec::type.
Referenced by format_impl(), fl::printf(), and fl::snprintf().