FastLED: fl::printf_detail::format_arg
format_arg() [3/4]
template<typename T> fl::enable_if<!fl::is_pointer< T >::value >::type fl::printf_detail::format_arg (sstream & stream, const FormatSpec & spec, const T & arg)
Definition at line 364 of file stdio.h.
{
    fl::string result;
    bool is_numeric = false;
    switch (spec.type) {
        case 'd':
        case 'i': {
            if (!fl::is_integral<T>::value) {
                result = "<type_error>";
                break;
            }
            is_numeric = true;
            // Convert to string
            sstream temp;
            temp << arg;
            result = temp.str();
            // Handle sign flags
            bool is_negative = !result.empty() && result[0] == '-';
            if (!is_negative) {
                if (spec.show_sign) {
                    result = fl::string("+") + result;
                } else if (spec.space_sign) {
                    result = fl::string(" ") + result;
                }
            }
            break;
        }
        case 'u': {
            if (!fl::is_integral<T>::value) {
                result = "<type_error>";
                break;
            }
            is_numeric = true;
            // Convert to string
            sstream temp;
            temp << arg;
            result = temp.str();
            break;
        }
        case 'o': {
            if (!fl::is_integral<T>::value) {
                result = "<type_error>";
                break;
            }
            is_numeric = true;
            // Convert to octal
            result = to_octal(arg);
            // Alternate form: prefix with 0 (but not for zero itself)
            if (spec.alt_form && arg != 0) {
                result = fl::string("0") + result;
            }
            break;
        }
        case 'x': {
            is_numeric = true;
            // Convert to hex
            result = fl::to_hex(arg, spec.uppercase);
            // Alternate form: prefix with 0x or 0X
            if (spec.alt_form && arg != 0) {
                result = fl::string(spec.uppercase ? "0X" : "0x") + result;
            }
            break;
        }
        case 'f': {
            if (!fl::is_floating_point<T>::value) {
                result = "<type_error>";
                break;
            }
            is_numeric = true;
            if (spec.precision >= 0) {
                result = format_float(static_cast<float>(arg), spec.precision);
            } else {
                sstream temp;
                temp << static_cast<float>(arg);
                result = temp.str();
            }
            break;
        }
        case 'c': {
            if (!fl::is_integral<T>::value) {
                result = "<type_error>";
                break;
            }
            char ch = static_cast<char>(arg);
            char temp_str[2] = {ch, '\0'};
            result = temp_str;
            break;
        }
        case 's': {
            sstream temp;
            temp << arg;
            result = temp.str();
            break;
        }
        default:
            result = "<unknown_format>";
            break;
    }
    // Apply width and padding
    result = apply_width(result, spec, is_numeric);
    // Output final result
    stream << result;
}
References apply_width(), FL_NOEXCEPT, format_float(), fl::sstream::str(), fl::to_hex(), to_octal(), fl::fl::is_floating_point< T >::value, and fl::fl::is_integral< T >::value.
Referenced by format_arg(), and format_impl().