FastLED: fl::printf_detail::parse_format_spec
parse_format_spec()
FormatSpec fl::printf_detail::parse_format_spec (const char *& format) inline
Definition at line 109 of file stdio.h.
{
    FormatSpec spec;
    if (*format != '%') {
        return spec;
    }
    ++format; // Skip the '%'
    // Handle literal '%'
    if (*format == '%') {
        spec.type = '%';
        ++format;
        return spec;
    }
    // Parse flags: -, +, space, #, 0 (can be in any order)
    bool parsing_flags = true;
    while (parsing_flags) {
        switch (*format) {
            case '-':
                spec.left_align = true;
                ++format;
                break;
            case '+':
                spec.show_sign = true;
                ++format;
                break;
            case ' ':
                spec.space_sign = true;
                ++format;
                break;
            case '#':
                spec.alt_form = true;
                ++format;
                break;
            case '0':
                spec.zero_pad = true;
                ++format;
                break;
            default:
                parsing_flags = false;
                break;
        }
    }
    // Parse width (decimal number)
    if (*format >= '0' && *format <= '9') {
        spec.width = 0;
        while (*format >= '0' && *format <= '9') {
            spec.width = spec.width * 10 + (*format - '0');
            ++format;
        }
    }
    // Parse precision for floating point
    if (*format == '.') {
        ++format; // Skip the '.'
        spec.precision = 0;
        while (*format >= '0' && *format <= '9') {
            spec.precision = spec.precision * 10 + (*format - '0');
            ++format;
        }
    }
    // Skip length modifiers (l, ll, h, hh, L, z, t, j)
    // We don't use them in our simple printf, but we need to skip them
    // to get to the actual type character
    if (*format == 'h' || *format == 'l') {
        char first = *format;
        ++format;
        // Check for double character modifiers (hh, ll)
        if (*format == first) {
            ++format;
        }
    } else if (*format == 'L' || *format == 'z' || *format == 't' || *format == 'j') {
        ++format;
    }
    // Get the format type
    spec.type = *format;
    if (spec.type == 'X') {
        spec.uppercase = true;
        spec.type = 'x'; // Normalize to lowercase for processing
    }
    ++format;
    return spec;
}
References fl::printf_detail::FormatSpec::alt_form, FL_NOEXCEPT, fl::format(), fl::printf_detail::FormatSpec::left_align, fl::printf_detail::FormatSpec::precision, fl::printf_detail::FormatSpec::show_sign, fl::printf_detail::FormatSpec::space_sign, fl::printf_detail::FormatSpec::type, fl::printf_detail::FormatSpec::uppercase, fl::printf_detail::FormatSpec::width, and fl::printf_detail::FormatSpec::zero_pad.
Referenced by format_impl(), and format_impl().