FastLED: KeyboardState::HandleNoteOff
HandleNoteOff()
void KeyboardState::HandleNoteOff (uint8_t midi_note, uint8_t velocity, uint32_t now_ms)
Definition at line 149 of file Keyboard.cpp.
{
#ifdef DEBUG_KEYBOARD
  dprint("HandleNoteOff:");
  dprint("midi_note = ");
  dprint(midi_note);
  dprint(", velocity = ");
  dprintln(velocity);
#endif
  Key* key = GetKey(midi_note);
  if (sustain_pedal_) {
    key->SetSustained();
  } else {
    key->SetOff(now_ms);
  }
}
References dprint, dprintln, GetKey(), Key::SetOff(), Key::SetSustained(), and sustain_pedal_.
Referenced by HandleNoteOn().