FastLED: KeyboardState::HandleNoteOn
HandleNoteOn()
void KeyboardState::HandleNoteOn (uint8_t midi_note, uint8_t velocity, int color_selector_value, uint32_t now_ms)
Definition at line 116 of file Keyboard.cpp.
{
  if (0 == velocity) {
    // Some keyboards signify "NoteOff" with a velocity of zero.
    HandleNoteOff(midi_note, velocity, now_ms);
    return;
  }
#ifdef DEBUG_KEYBOARD
  dprint("HandleNoteOn:");
  dprint("midi_note = ");
  dprint(midi_note);
  dprint(", velocity = ");
  dprintln(velocity);
 #endif
  float brightness = ToBrightness(velocity);
  dprint("brightness: "); dprintln(brightness);
  ColorHSV pixel_color_hsv = SelectColor(midi_note, brightness,
                                         color_selector_value);
  // TODO: Give a key access to the Keyboard owner, therefore it could inspect the
  // sustained variable instead of passing it here.
  Key* key = GetKey(midi_note);
  dprint("key indx: "); dprintln(key->idx_);
  key->SetOn(velocity, pixel_color_hsv, now_ms);
}
References brightness, dprint, dprintln, GetKey(), HandleNoteOff(), Key::idx_, SelectColor(), Key::SetOn(), and ToBrightness().