FastLED: autoresearch::setupRpcAsyncTask
setupRpcAsyncTask()
fl::task::Handle autoresearch::setupRpcAsyncTask (AutoResearchRemoteControl & remote_control, int interval_ms = 10) inline
Setup async task for JSON-RPC processing.
Parameters
remote_control Reference to RemoteControl singleton
interval_ms Task interval in milliseconds (default: 10ms)
Returns
Task handle (auto-registered with scheduler)
This function creates an async task that polls the RPC system at regular intervals, allowing RPC commands to be processed without blocking the main loop.
The 10ms default interval balances:
Responsiveness: 115200 baud ≈ 100 bytes in 10ms
CPU overhead: Minimal impact on LED peripheral operations
The task is automatically registered with the scheduler via .then() and will run until the program exits.
THREAD SAFETY:
Safe to capture remote_control by reference (singleton lifetime)
ESP32 Arduino runs on single core - task switching is atomic
No additional synchronization needed
Definition at line 34 of file AutoResearchAsync.h.
{
    return fl::task::every_ms(interval_ms, FL_TRACE)
        .then([&remote_control]() {
            uint32_t current_time = millis();
            remote_control.tick(current_time);  // Calls Remote::update() which does pull + tick + push
        });
}
References fl::task::every_ms(), FL_TRACE, fl::task::Handle::then(), and AutoResearchRemoteControl::tick().
Referenced by setup().