FastLED: fl::scoped_ptr::scoped_ptr
scoped_ptr() [1/3]
template<typename T, typename Deleter = PointerDeleter<T>> fl::scoped_ptr< T, Deleter >::scoped_ptr (T * ptr = nullptr, Deleter deleter = Deleter()) inline explicit
Definition at line 30 of file scoped_ptr.h.
        : ptr_(ptr), deleter_(deleter) {}
References deleter_, and ptr_.
Referenced by scoped_ptr(), scoped_ptr(), operator=(), and operator=().