# CMake generated Testfile for 
# Source directory: /workspace/tests
# Build directory: /workspace/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_algorithm "/workspace/tests/.build/bin/test_algorithm")
set_tests_properties(test_algorithm PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_apa102_hd "/workspace/tests/.build/bin/test_apa102_hd")
set_tests_properties(test_apa102_hd PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_bitset "/workspace/tests/.build/bin/test_bitset")
set_tests_properties(test_bitset PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_brightness_bitshifter "/workspace/tests/.build/bin/test_brightness_bitshifter")
set_tests_properties(test_brightness_bitshifter PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_bytestream "/workspace/tests/.build/bin/test_bytestream")
set_tests_properties(test_bytestream PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_circular_buffer "/workspace/tests/.build/bin/test_circular_buffer")
set_tests_properties(test_circular_buffer PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_corkscrew "/workspace/tests/.build/bin/test_corkscrew")
set_tests_properties(test_corkscrew PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_dbg "/workspace/tests/.build/bin/test_dbg")
set_tests_properties(test_dbg PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_downscale "/workspace/tests/.build/bin/test_downscale")
set_tests_properties(test_downscale PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_easing "/workspace/tests/.build/bin/test_easing")
set_tests_properties(test_easing PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_fastled "/workspace/tests/.build/bin/test_fastled")
set_tests_properties(test_fastled PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_fft "/workspace/tests/.build/bin/test_fft")
set_tests_properties(test_fft PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_fixed_set "/workspace/tests/.build/bin/test_fixed_set")
set_tests_properties(test_fixed_set PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_frame "/workspace/tests/.build/bin/test_frame")
set_tests_properties(test_frame PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_frame_tracker "/workspace/tests/.build/bin/test_frame_tracker")
set_tests_properties(test_frame_tracker PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_function "/workspace/tests/.build/bin/test_function")
set_tests_properties(test_function PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_fx "/workspace/tests/.build/bin/test_fx")
set_tests_properties(test_fx PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_fx2d_blend "/workspace/tests/.build/bin/test_fx2d_blend")
set_tests_properties(test_fx2d_blend PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_fx_engine "/workspace/tests/.build/bin/test_fx_engine")
set_tests_properties(test_fx_engine PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_fx_time "/workspace/tests/.build/bin/test_fx_time")
set_tests_properties(test_fx_time PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_grid "/workspace/tests/.build/bin/test_grid")
set_tests_properties(test_grid PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_hashmap "/workspace/tests/.build/bin/test_hashmap")
set_tests_properties(test_hashmap PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_hashmap_lru "/workspace/tests/.build/bin/test_hashmap_lru")
set_tests_properties(test_hashmap_lru PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_hsv16 "/workspace/tests/.build/bin/test_hsv16")
set_tests_properties(test_hsv16 PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_hsv_conversion_accuracy "/workspace/tests/.build/bin/test_hsv_conversion_accuracy")
set_tests_properties(test_hsv_conversion_accuracy PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_intmap "/workspace/tests/.build/bin/test_intmap")
set_tests_properties(test_intmap PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_line_simplification "/workspace/tests/.build/bin/test_line_simplification")
set_tests_properties(test_line_simplification PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_lut "/workspace/tests/.build/bin/test_lut")
set_tests_properties(test_lut PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_map "/workspace/tests/.build/bin/test_map")
set_tests_properties(test_map PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_map_range "/workspace/tests/.build/bin/test_map_range")
set_tests_properties(test_map_range PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_math "/workspace/tests/.build/bin/test_math")
set_tests_properties(test_math PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_point "/workspace/tests/.build/bin/test_point")
set_tests_properties(test_point PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_priority_queue "/workspace/tests/.build/bin/test_priority_queue")
set_tests_properties(test_priority_queue PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_raster "/workspace/tests/.build/bin/test_raster")
set_tests_properties(test_raster PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_rectangular_buffer "/workspace/tests/.build/bin/test_rectangular_buffer")
set_tests_properties(test_rectangular_buffer PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_refptr "/workspace/tests/.build/bin/test_refptr")
set_tests_properties(test_refptr PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_screenmap "/workspace/tests/.build/bin/test_screenmap")
set_tests_properties(test_screenmap PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_sin32 "/workspace/tests/.build/bin/test_sin32")
set_tests_properties(test_sin32 PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_slice "/workspace/tests/.build/bin/test_slice")
set_tests_properties(test_slice PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_splat "/workspace/tests/.build/bin/test_splat")
set_tests_properties(test_splat PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_str "/workspace/tests/.build/bin/test_str")
set_tests_properties(test_str PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_strip_id_map "/workspace/tests/.build/bin/test_strip_id_map")
set_tests_properties(test_strip_id_map PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_strstream "/workspace/tests/.build/bin/test_strstream")
set_tests_properties(test_strstream PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_tile2x2 "/workspace/tests/.build/bin/test_tile2x2")
set_tests_properties(test_tile2x2 PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_transform "/workspace/tests/.build/bin/test_transform")
set_tests_properties(test_transform PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_transition_ramp "/workspace/tests/.build/bin/test_transition_ramp")
set_tests_properties(test_transition_ramp PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_traverse_grid "/workspace/tests/.build/bin/test_traverse_grid")
set_tests_properties(test_traverse_grid PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_type_traits "/workspace/tests/.build/bin/test_type_traits")
set_tests_properties(test_type_traits PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_ui "/workspace/tests/.build/bin/test_ui")
set_tests_properties(test_ui PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_variant "/workspace/tests/.build/bin/test_variant")
set_tests_properties(test_variant PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_vector "/workspace/tests/.build/bin/test_vector")
set_tests_properties(test_vector PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_video "/workspace/tests/.build/bin/test_video")
set_tests_properties(test_video PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_videofx_wrapper "/workspace/tests/.build/bin/test_videofx_wrapper")
set_tests_properties(test_videofx_wrapper PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
add_test(test_xypath "/workspace/tests/.build/bin/test_xypath")
set_tests_properties(test_xypath PROPERTIES  _BACKTRACE_TRIPLES "/workspace/tests/CMakeLists.txt;302;add_test;/workspace/tests/CMakeLists.txt;0;")
subdirs(".build/bin/fastled")
