FastLED: fl::pwm_state::ensureIsrActive
ensureIsrActive()
int fl::pwm_state::ensureIsrActive ()
Definition at line 175 of file pin.cpp.hpp.
                      {
    PwmStateData& st = state();
    if (st.isr_active) return 0;
    fl::isr::config cfg;
    cfg.handler = pwm_isr_handler;
    cfg.frequency_hz = ISR_FREQUENCY_HZ;
    cfg.priority = fl::isr::ISR_PRIORITY_MEDIUM;
    cfg.flags = fl::isr::ISR_FLAG_IRAM_SAFE;
    int result = fl::isr::attach_timer_handler(cfg, &st.isr_handle);
    if (result != 0) {
        FL_WARN("PWM: ISR attach failed: " << fl::isr::get_error_string(result));
        return result;
    }
    st.isr_active = true;
    return 0;
}
References fl::isr::attach_timer_handler(), FL_WARN, fl::isr::config::flags, fl::isr::config::frequency_hz, fl::isr::get_error_string(), fl::isr::config::handler, fl::pwm_state::PwmStateData::isr_active, fl::isr::ISR_FLAG_IRAM_SAFE, ISR_FREQUENCY_HZ, fl::pwm_state::PwmStateData::isr_handle, fl::isr::ISR_PRIORITY_MEDIUM, fl::isr::config::priority, pwm_isr_handler(), and state().
Referenced by fl::setPwmFrequency().