FastLED: fl::pwm_state::releaseChannel
releaseChannel()
void fl::pwm_state::releaseChannel (PwmPinState * ch)
Definition at line 205 of file pin.cpp.hpp.
{
    if (!ch || ch->pin < 0) return;
    fl::digitalWrite(ch->pin, fl::PinValue::Low);
    {
        fl::isr::critical_section cs;
        ch->pin = -1;
        ch->backend = PwmBackend::None;
        ch->frequency_hz = 0;
        ch->duty_cycle = 0;
    }
    maybeShutdownIsr();
}
References fl::pwm_state::PwmPinState::backend, fl::digitalWrite(), fl::pwm_state::PwmPinState::duty_cycle, fl::pwm_state::PwmPinState::frequency_hz, fl::Low, maybeShutdownIsr(), None, and fl::pwm_state::PwmPinState::pin.
Referenced by fl::pinMode(), fl::pwmEnd(), and fl::setPwmFrequency().