FastLED: fl::pwm_state::pwm_isr_handler
pwm_isr_handler()
void FL_IRAM fl::pwm_state::pwm_isr_handler (void * user_data)
Definition at line 114 of file pin.cpp.hpp.
{
    (void)user_data;
    PwmStateData& st = state();
    for (u8 i = 0; i < MAX_PWM_CHANNELS; i++) {
        PwmPinState& ch = st.channels[i];
        if (ch.pin < 0 || ch.backend != PwmBackend::IsrSoftware) continue;
        ch.tick_counter++;
        // Turn LOW at duty cycle boundary
        if (ch.tick_counter == ch.high_ticks && ch.pin_state) {
            fl::digitalWrite(ch.pin, fl::PinValue::Low);
            ch.pin_state = false;
        }
        // Start new period: reset counter, turn HIGH if duty > 0
        else if (ch.tick_counter >= ch.period_ticks) {
            ch.tick_counter = 0;
            if (ch.high_ticks > 0) {
                fl::digitalWrite(ch.pin, fl::PinValue::High);
                ch.pin_state = true;
            }
        }
    }
}
References fl::pwm_state::PwmPinState::backend, fl::pwm_state::PwmStateData::channels, fl::digitalWrite(), FL_IRAM, fl::High, fl::pwm_state::PwmPinState::high_ticks, IsrSoftware, fl::Low, MAX_PWM_CHANNELS, fl::pwm_state::PwmPinState::period_ticks, fl::pwm_state::PwmPinState::pin, fl::pwm_state::PwmPinState::pin_state, state(), and fl::pwm_state::PwmPinState::tick_counter.
Referenced by ensureIsrActive().