FastLED: MidiInterface::thruFilter
thruFilter()
template<class Transport, class Settings, class Platform> void MidiInterface< Transport, Settings, Platform >::thruFilter (byte inChannel) private
Definition at line 1400 of file MIDI.hpp.
{
    // If the feature is disabled, don't do anything.
    if (!mThruActivated || (mThruFilterMode == Thru::Off))
        return;
    // First, check if the received message is Channel
    if (mMessage.type >= NoteOff && mMessage.type <= PitchBend)
    {
        const bool filter_condition = ((mMessage.channel == inChannel) ||
                                       (inChannel == MIDI_CHANNEL_OMNI));
        // Now let's pass it to the output
        switch (mThruFilterMode)
        {
            case Thru::Full:
                send(mMessage.type,
                     mMessage.data1,
                     mMessage.data2,
                     mMessage.channel);
                break;
            case Thru::SameChannel:
                if (filter_condition)
                {
                    send(mMessage.type,
                         mMessage.data1,
                         mMessage.data2,
                         mMessage.channel);
                }
                break;
            case Thru::DifferentChannel:
                if (!filter_condition)
                {
                    send(mMessage.type,
                         mMessage.data1,
                         mMessage.data2,
                         mMessage.channel);
                }
                break;
            default:
                break;
        }
    }
    else
    {
        // Send the message to the output
        switch (mMessage.type)
        {
                // Real Time and 1 byte
            case Clock:
            case Start:
            case Stop:
            case Continue:
            case ActiveSensing:
            case SystemReset:
            case TuneRequest:
                sendRealTime(mMessage.type);
                break;
            case SystemExclusive:
                // Send SysEx (0xf0 and 0xf7 are included in the buffer)
                sendSysEx(getSysExArrayLength(), getSysExArray(), true);
                break;
            case SongSelect:
                sendSongSelect(mMessage.data1);
                break;
            case SongPosition:
                sendSongPosition(mMessage.data1 | ((unsigned)mMessage.data2 << 7));
                break;
            case TimeCodeQuarterFrame:
                sendTimeCodeQuarterFrame(mMessage.data1,mMessage.data2);
                break;
            default:
                break; // LCOV_EXCL_LINE - Unreacheable code, but prevents unhandled case warning.
        }
    }
}
References ActiveSensing, Clock, Continue, Thru::DifferentChannel, Thru::Full, getSysExArray(), getSysExArrayLength(), MIDI_CHANNEL_OMNI, mMessage, mThruActivated, mThruFilterMode, NoteOff, Thru::Off, PitchBend, Thru::SameChannel, send(), sendRealTime(), sendSongPosition(), sendSongSelect(), sendSysEx(), sendTimeCodeQuarterFrame(), SongPosition, SongSelect, Start, Stop, SystemExclusive, SystemReset, TimeCodeQuarterFrame, and TuneRequest.
Referenced by read().