FastLED: fl::audio::detector::Pitch::calculateConfidence
calculateConfidence() [2/2]
float fl::audio::detector::Pitch::calculateConfidence (const vector< float > & autocorr, int peakLag) const private
Definition at line 171 of file pitch.cpp.hpp.
{
    // Confidence based on:
    // 1. Strength of the autocorrelation peak
    // 2. Ratio of peak to nearby values (peak clarity)
    if (peakLag <= 0 || peakLag >= static_cast<int>(autocorr.size())) {
        return 0.0f;
    }
    float peakValue = autocorr[static_cast<size>(peakLag)];
    // Confidence is primarily based on peak strength
    // Autocorrelation ranges from -1 to 1, but we only care about positive peaks
    float confidence = fl::max(0.0f, fl::min(1.0f, peakValue));
    // Calculate clarity by comparing peak to surrounding values
    // Look at ±10% of the period
    int windowSize = fl::max(2, peakLag / 10);
    float neighborSum = 0.0f;
    int neighborCount = 0;
    for (int offset = -windowSize; offset <= windowSize; offset++) {
        if (offset == 0) continue;  // Skip the peak itself
        int lag = peakLag + offset;
        if (lag >= mMinPeriod && lag <= mMaxPeriod && lag < static_cast<int>(autocorr.size())) {
            neighborSum += fl::max(0.0f, autocorr[static_cast<size>(lag)]);
            neighborCount++;
        }
    }
    if (neighborCount > 0) {
        float neighborAvg = neighborSum / static_cast<float>(neighborCount);
        // Peak should be significantly higher than neighbors
        // If peak is 2x higher, that's good; if it's similar, reduce confidence
        if (neighborAvg > 1e-6f) {
            float clarity = fl::min(1.0f, (peakValue - neighborAvg) / neighborAvg);
            confidence *= (0.7f + 0.3f * clarity);  // Weight clarity at 30%
        }
    }
    return confidence;
}
References fl::max(), fl::min(), mMaxPeriod, mMinPeriod, offset(), and fl::vector_basic::size().
Referenced by calculateAutocorrelation().