FastLED: fl::audio::detector::Pitch::update
update() [2/2]
void fl::audio::detector::Pitch::update (shared_ptr< Context > context) override virtual
Implements fl::audio::Detector.
Definition at line 32 of file pitch.cpp.hpp.
{
    // Get PCM data from context
    span<const i16> pcm = context->getPCM();
    size numSamples = pcm.size();
    // Compute dt from actual audio buffer duration
    mLastDt = computeAudioDt(pcm.size(), static_cast<int>(mSampleRate));
    // Need at least 2x max period for autocorrelation
    if (numSamples < static_cast<size>(mMaxPeriod * 2)) {
        // Not enough samples for reliable pitch detection
        mConfidence = 0.0f;
        mIsVoiced = false;
        mVoicedStateChanged = (mIsVoiced != mPreviousVoiced);
        return;
    }
    // Calculate autocorrelation and find pitch
    float detectedPitch = calculateAutocorrelation(pcm.data(), numSamples);
    // Check if pitch is valid and confidence is sufficient
    if (detectedPitch > 0.0f && mConfidence >= mConfidenceThreshold) {
        mIsVoiced = true;
        mCurrentPitch = detectedPitch;
        updatePitchSmoothing(detectedPitch);
        mFirePitch = true;
        if (shouldReportPitchChange(detectedPitch)) {
            mFirePitchChange = true;
            mPreviousPitch = detectedPitch;
        }
    } else {
        mIsVoiced = false;
        mCurrentPitch = 0.0f;
        mFirePitch = false;
    }
    mVoicedStateChanged = (mIsVoiced != mPreviousVoiced);
}
References Pitch(), calculateAutocorrelation(), fl::audio::computeAudioDt(), fl::span< T, Extent >::data(), mConfidence, mConfidenceThreshold, mCurrentPitch, mFirePitch, mFirePitchChange, mIsVoiced, mLastDt, mMaxPeriod, mPreviousPitch, mPreviousVoiced, mSampleRate, mVoicedStateChanged, shouldReportPitchChange(), fl::span< T, Extent >::size(), update(), and updatePitchSmoothing().
Referenced by ~Pitch(), update(), and update().