"""
Post-compile mtime stabilization for DLL outputs.

Problem:
    When zccache caches link results, it restores cached outputs with their
    ORIGINAL mtime (from when the link first ran). This can produce DLLs with
    mtimes OLDER than the fastled.dll.symbols file, causing ninja to think the
    DLLs need relinking on the next build. Since zccache returns the same cached
    result each time, the DLLs never get a newer mtime — creating an infinite
    relink loop of ~190 DLLs on every build.

Solution:
    After ninja compile completes, check if any DLL outputs are older than
    the symbols file (their key input dependency). If so, touch them to NOW
    so ninja sees them as up-to-date on the next run.

    This is a lightweight post-build fixup (~5ms) that breaks the relink loop
    and saves ~1-2 seconds per build (190 unnecessary link operations).

    The stale outputs also trip the #3011 guard, which reads "artifact older
    than this build's start" as "the link failed and left an old DLL behind"
    and fails every affected test. See FastLED#4212.

Usage:
    Called automatically after stream_compile_only() completes in streaming.py.
"""

import os
import stat
import time
from pathlib import Path

from ci.util.global_interrupt_handler import handle_keyboard_interrupt
from ci.util.timestamp_print import ts_print as _ts_print


# Shared-library suffixes, by host. Meson emits .dll on Windows, .so on
# Linux, and .dylib on macOS -- matching only .dll made this whole module a
# no-op everywhere but Windows (FastLED#4212).
_DLL_SUFFIXES = ("dll", "so", "dylib")

# Glob patterns for shared-library outputs relative to the build directory
_DLL_PATTERNS: list[str] = []
for _directory in ("tests", "examples"):
    for _suffix in _DLL_SUFFIXES:
        _DLL_PATTERNS.append(f"{_directory}/*.{_suffix}")

# Key input files whose mtime triggers relinking. The symbols file is named
# after the core library, so its suffix varies with the host too.
# fastled.<suffix>.symbols — generated by SHSYM from the core library
_KEY_INPUT_GLOBS: list[str] = []
for _suffix in _DLL_SUFFIXES:
    _KEY_INPUT_GLOBS.append(
        f"ci/meson/native/fastled.{_suffix}.p/fastled.{_suffix}.symbols"
    )

_KEY_INPUTS = [
    # libcrash_handler.a — static library linked into the runners and DLLs
    Path("ci") / "meson" / "native" / "libcrash_handler.a",
]

# Runner executables that also depend on these inputs
_RUNNER_PATTERNS = [
    "tests/runner.exe",
    "tests/runner",
    "examples/example_runner.exe",
    "examples/example_runner",
]


def stabilize_dll_mtimes(build_dir: Path, verbose: bool = False) -> int:
    """
    Ensure all DLL outputs have mtimes newer than their key input dependencies.

    When zccache caches link results, it may restore outputs with old mtimes
    that are older than the symbols file, causing ninja to relink on every build.
    This function touches any such stale outputs to break the relink loop.

    Args:
        build_dir: Meson build directory (e.g., .build/meson-quick)
        verbose: Print details about touched files

    Returns:
        Number of files touched (0 if all mtimes were already stable)
    """
    # Find the maximum mtime across all key input files
    max_input_mtime: float = 0
    key_inputs: list[Path] = [build_dir / rel_path for rel_path in _KEY_INPUTS]
    for pattern in _KEY_INPUT_GLOBS:
        key_inputs.extend(build_dir.glob(pattern))
    for abs_path in key_inputs:
        if abs_path.exists():
            try:
                mtime = abs_path.stat().st_mtime
                if mtime > max_input_mtime:
                    max_input_mtime = mtime
            except KeyboardInterrupt as ki:
                handle_keyboard_interrupt(ki)
                raise
            except OSError:
                pass

    if max_input_mtime == 0:
        return 0  # No input files found, nothing to stabilize

    # Collect all DLL and runner outputs
    all_outputs: list[Path] = []
    for pattern in _DLL_PATTERNS:
        all_outputs.extend(build_dir.glob(pattern))
    for pattern in _RUNNER_PATTERNS:
        candidate = build_dir / pattern
        if candidate.exists():
            all_outputs.append(candidate)

    if not all_outputs:
        return 0

    # Touch any outputs that are older than the key inputs
    now = time.time()
    # Use a timestamp slightly after the max input mtime to ensure outputs
    # are newer. Using NOW is safest since it's guaranteed to be >= max_input_mtime.
    touch_time = max(now, max_input_mtime + 1)
    touched = 0

    for output_path in all_outputs:
        try:
            output_mtime = output_path.stat().st_mtime
            if output_mtime <= max_input_mtime:
                os.utime(str(output_path), (touch_time, touch_time))
                touched += 1
        except KeyboardInterrupt as ki:
            handle_keyboard_interrupt(ki)
            raise
        except OSError:
            pass

    if touched > 0 and verbose:
        _ts_print(
            f"[BUILD] ⚡ Stabilized {touched} DLL mtimes"
            f" (were older than input dependencies)"
        )
    elif touched > 0:
        _ts_print(f"[BUILD] ⚡ Stabilized {touched} output mtimes (zccache mtime fix)")

    return touched


# Object/library suffixes that are never meant to be executable.
_NON_EXECUTABLE_SUFFIXES = {".so", ".dylib", ".dll", ".a", ".o", ".obj", ".p"}

_ELF_MAGIC = b"\x7fELF"
_MACHO_MAGICS = {
    b"\xcf\xfa\xed\xfe",  # 64-bit little-endian
    b"\xce\xfa\xed\xfe",  # 32-bit little-endian
    b"\xca\xfe\xba\xbe",  # universal binary
}


def _is_native_executable(path: Path) -> bool:
    """Whether the file starts with a native executable magic number.

    Read errors propagate. Treating an unreadable file as "not an
    executable" would silently skip exactly the artifact this module exists
    to repair, and the run would then fail later on a PermissionError with
    no connection to the real cause.
    """
    try:
        with open(path, "rb") as handle:
            magic = handle.read(4)
    except KeyboardInterrupt as ki:
        handle_keyboard_interrupt(ki)
        raise
    except OSError as exc:
        raise OSError(f"cannot inspect {path} for an executable header: {exc}") from exc
    return magic == _ELF_MAGIC or magic in _MACHO_MAGICS


def restore_executable_bits(build_dir: Path, verbose: bool = False) -> int:
    """
    Ensure linked executables are still executable.

    Same cache-restore defect as the mtimes above, different attribute: when
    zccache serves a cached link result it writes the bytes back out and the
    executable bit is lost. The test runner then dies on the first binary it
    tries to spawn with `PermissionError: [Errno 13] Permission denied`,
    surfaced only as an opaque "Unhandled python OSError ... return code 13".
    See FastLED#4205.

    Only files carrying a native-executable magic number are touched, so data
    files sitting in these directories keep whatever mode they have.

    Returns:
        Number of files made executable (0 if all were already correct).
    """
    restored = 0
    # `tests/profile` is listed because `_resolve_test_command` spawns
    # profile binaries straight out of it, and the scan does not recurse:
    # a directory is not a file, so without naming it here every profile
    # executable is walked straight past.
    for directory in ("tests", "tests/profile", "examples"):
        target_dir = build_dir / directory
        # Path.is_dir() reports False for a directory it cannot stat, which
        # would silently skip every binary inside it. Distinguish "absent"
        # from "cannot inspect".
        try:
            is_dir = target_dir.is_dir()
        except KeyboardInterrupt as ki:
            handle_keyboard_interrupt(ki)
            raise
        except OSError as exc:
            raise OSError(f"cannot inspect {target_dir}: {exc}") from exc
        if not is_dir:
            continue
        try:
            entries = sorted(target_dir.iterdir())
        except KeyboardInterrupt as ki:
            handle_keyboard_interrupt(ki)
            raise
        except OSError as exc:
            raise OSError(f"cannot list {target_dir}: {exc}") from exc
        for candidate in entries:
            try:
                is_file = candidate.is_file()
            except KeyboardInterrupt as ki:
                handle_keyboard_interrupt(ki)
                raise
            except OSError as exc:
                raise OSError(f"cannot stat {candidate}: {exc}") from exc
            if not is_file or candidate.suffix in _NON_EXECUTABLE_SUFFIXES:
                continue
            # A stat failure is an inspection failure, not evidence that the
            # file needs nothing; swallowing it would skip a binary that the
            # runner then dies on.
            try:
                mode = candidate.stat().st_mode
            except KeyboardInterrupt as ki:
                handle_keyboard_interrupt(ki)
                raise
            except OSError as exc:
                raise OSError(f"cannot stat {candidate}: {exc}") from exc
            if mode & 0o111:
                continue
            if not _is_native_executable(candidate):
                continue
            # Fail loudly rather than continuing: an executable we cannot
            # chmod is one the test runner will die on later with an opaque
            # PermissionError, which is the exact failure this function
            # exists to prevent.
            try:
                # Mirror the read bits, the way a linker would.
                readable = mode & (stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH)
                os.chmod(candidate, mode | (readable >> 2))
            except KeyboardInterrupt as ki:
                handle_keyboard_interrupt(ki)
                raise
            except OSError as exc:
                raise OSError(
                    f"cannot restore the executable bit on {candidate}: {exc}"
                ) from exc
            restored += 1

    if restored > 0:
        _ts_print(
            f"[BUILD] ⚡ Restored {restored} executable bit(s) (zccache link-cache fix)"
        )
    return restored
