FastLED: initPanels
initPanels()
void initPanels ()
Definition at line 44 of file el_panel.cpp.
                  {
    fl::pinMode(EL_PIN_HIGH, fl::PinMode::Output);
    fl::pinMode(EL_PIN_LOW, fl::PinMode::Output);
    fl::setPwmFrequency(EL_PIN_HIGH, PWM_FREQ_HZ);
    fl::setPwmFrequency(EL_PIN_LOW, PWM_FREQ_HZ);
    fl::analogWrite(EL_PIN_HIGH, 0);
    fl::analogWrite(EL_PIN_LOW, 0);
}
References fl::analogWrite(), EL_PIN_HIGH, EL_PIN_LOW, fl::Output, fl::pinMode(), PWM_FREQ_HZ, and fl::setPwmFrequency().
Referenced by setup().