FastLED: fl::gfx::blurGaussianImpl
blurGaussianImpl()
template<int hRadius, int vRadius, typename RGB_T, typename AlphaT> FL_OPTIMIZE_FUNCTION void fl::gfx::blurGaussianImpl (Canvas< RGB_T > & canvas, AlphaT alpha)
Definition at line 1131 of file blur.cpp.hpp.
{
    const int w = canvas.width;
    const int h = canvas.height;
    if (w <= 0 || h <= 0)
        return;
    using P = blur_detail::pixel_ops<RGB_T>;
    // Accumulator: u16 for 8-bit channels (max per-pass sum: 255*256=65280),
    // u32 for wider channels.
    using acc_t = fl::conditional_t<sizeof(typename RGB_T::fp) == 1, u16, u32>;
    const bool applyAlpha = !(alpha == blur_detail::alpha_identity<AlphaT>());
    // Handle no-blur case (radius 0 in both dimensions).
    if (hRadius == 0 && vRadius == 0) {
        if (applyAlpha) {
            RGB_T *pixels = canvas.pixels;
            for (int i = 0; i < w * h; ++i) {
                RGB_T &p = pixels[i];
                p = P::make(P::ch(p.r), P::ch(p.g), P::ch(p.b), alpha);
            }
        }
        return;
    }
    fl::span<RGB_T> padbuf = blur_detail::get_padbuf<RGB_T>(
        blur_detail::compute_pad_size<hRadius, vRadius, RGB_T>(w, h));
    RGB_T *pad = padbuf.data();
    RGB_T *pixels = canvas.pixels;
    // ── Horizontal pass ──────────────────────────────────────────────
    if (hRadius > 0) {
        // Zero the fixed padding regions once (reused for every row).
        FL_BUILTIN_MEMSET(pad, 0, hRadius * sizeof(RGB_T));
        FL_BUILTIN_MEMSET(pad + hRadius + w, 0, hRadius * sizeof(RGB_T));
        for (int y = 0; y < h; ++y) {
            RGB_T *row = pixels + y * w;
            FL_BUILTIN_MEMCPY(pad + hRadius, row, w * sizeof(RGB_T));
            if (vRadius == 0 && applyAlpha)
                blur_detail::hpass_row<hRadius, RGB_T, acc_t, true>(
                    pad, row, w, alpha);
            else
                blur_detail::hpass_row<hRadius, RGB_T, acc_t, false>(
                    pad, row, w, alpha);
        }
    }
    // ── Vertical pass ──────────────────────────────────────────────────
    if (vRadius > 0) {
        if (applyAlpha)
            blur_detail::vpass_full<vRadius, RGB_T, acc_t, true>(
                pixels, w, h, pad, alpha);
        else
            blur_detail::vpass_full<vRadius, RGB_T, acc_t, false>(
                pixels, w, h, pad, alpha);
    }
}
References fl::gfx::blur_detail::alpha_identity(), fl::gfx::blur_detail::compute_pad_size(), fl::span< T, Extent >::data(), FL_BUILTIN_MEMCPY, FL_BUILTIN_MEMSET, fl::gfx::blur_detail::get_padbuf(), fl::gfx::Canvas< RGB_T >::height, fl::gfx::blur_detail::hpass_row(), fl::P(), fl::gfx::Canvas< RGB_T >::pixels, fl::gfx::blur_detail::vpass_full(), fl::gfx::Canvas< RGB_T >::width, and fl::y.
Referenced by blurGaussian(), blurGaussian(), and blurGaussianMappedImpl().