FastLED: fl::third_party::truetype::stbtt_IsGlyphEmpty
stbtt_IsGlyphEmpty()
int32_t fl::third_party::truetype::stbtt_IsGlyphEmpty (const stbtt_fontinfo * info, int32_t glyph_index)
Definition at line 1675 of file stb_truetype.cpp.hpp.
            {
   stbtt_int16 numberOfContours;
   int32_t g;
   if (info->cff.size)
      return stbtt__GetGlyphInfoT2(info, glyph_index, nullptr, nullptr, nullptr, nullptr) == 0;
   g = stbtt__GetGlyfOffset(info, glyph_index);
   if (g < 0) return 1;
   numberOfContours = ttSHORT(info->data + g);
   return numberOfContours == 0;
}
References FL_NOEXCEPT, stbtt__GetGlyfOffset(), stbtt__GetGlyphInfoT2(), and ttSHORT().