FastLED: fl::third_party::truetype::stbtt__new_buf
stbtt__new_buf()
static stbtt__buf fl::third_party::truetype::stbtt__new_buf (const void * p, size_t size) static
Definition at line 1194 of file stb_truetype.cpp.hpp.
            {
   stbtt__buf r;
   STBTT_assert(size < 0x40000000);
   r.data = (stbtt_uint8*) p;
   r.size = (int) size;
   r.cursor = 0;
   return r;
}
References fl::third_party::truetype::stbtt__buf::cursor, fl::third_party::truetype::stbtt__buf::data, FL_NOEXCEPT, fl::third_party::truetype::stbtt__buf::size, and STBTT_assert.
Referenced by stbtt__buf_range(), stbtt__cid_get_glyph_subrs(), stbtt__get_subr(), stbtt__get_subrs(), and stbtt_InitFont_internal().