FastLED: fl::third_party::truetype::stbtt__get_subrs
stbtt__get_subrs()
static stbtt__buf fl::third_party::truetype::stbtt__get_subrs (stbtt__buf cff, stbtt__buf fontdict) static
Definition at line 1380 of file stb_truetype.cpp.hpp.
            {
   stbtt_uint32 subrsoff = 0, private_loc[2] = { 0, 0 };
   stbtt__buf pdict;
   stbtt__dict_get_ints(&fontdict, 18, 2, private_loc);
   if (!private_loc[1] || !private_loc[0]) return stbtt__new_buf(nullptr, 0);
   pdict = stbtt__buf_range(&cff, private_loc[1], private_loc[0]);
   stbtt__dict_get_ints(&pdict, 19, 1, &subrsoff);
   if (!subrsoff) return stbtt__new_buf(nullptr, 0);
   stbtt__buf_seek(&cff, private_loc[1]+subrsoff);
   return stbtt__cff_get_index(&cff);
}
References FL_NOEXCEPT, stbtt__buf_range(), stbtt__buf_seek(), stbtt__cff_get_index(), stbtt__dict_get_ints(), and stbtt__new_buf().
Referenced by stbtt__cid_get_glyph_subrs(), and stbtt_InitFont_internal().