FastLED: fl::third_party::truetype::stbtt_GetKerningTable
stbtt_GetKerningTable()
int32_t fl::third_party::truetype::stbtt_GetKerningTable (const stbtt_fontinfo * info, stbtt_kerningentry * table, int32_t table_length)
Definition at line 2361 of file stb_truetype.cpp.hpp.
            {
   stbtt_uint8 *data = info->data + info->kern;
   int32_t k, length;
   // we only look at the first table. it must be 'horizontal' and format 0.
   if (!info->kern)
      return 0;
   if (ttUSHORT(data+2) < 1) // number of tables, need at least 1
      return 0;
   if (ttUSHORT(data+8) != 1) // horizontal flag must be set in format
      return 0;
   length = ttUSHORT(data+10);
   if (table_length < length)
      length = table_length;
   for (k = 0; k < length; k++)
   {
      table[k].glyph1 = ttUSHORT(data+18+(k*6));
      table[k].glyph2 = ttUSHORT(data+20+(k*6));
      table[k].advance = ttSHORT(data+22+(k*6));
   }
   return length;
}
References FL_NOEXCEPT, length(), ttSHORT(), and ttUSHORT().