FastLED: fl::third_party::truetype::stbtt_GetCodepointKernAdvance
stbtt_GetCodepointKernAdvance()
int32_t fl::third_party::truetype::stbtt_GetCodepointKernAdvance (const stbtt_fontinfo * info, int32_t ch1, int32_t ch2)
Definition at line 2651 of file stb_truetype.cpp.hpp.
            {
   if (!info->kern && !info->gpos) // if no kerning table, don't waste time looking up both codepoint->glyphs
      return 0;
   return stbtt_GetGlyphKernAdvance(info, stbtt_FindGlyphIndex(info,ch1), stbtt_FindGlyphIndex(info,ch2));
}
References FL_NOEXCEPT, stbtt_FindGlyphIndex(), and stbtt_GetGlyphKernAdvance().
Referenced by fl::FontImpl::getKerning().