FastLED: fl::third_party::truetype::stbtt_FindMatchingFont_internal
stbtt_FindMatchingFont_internal()
static int32_t fl::third_party::truetype::stbtt_FindMatchingFont_internal (unsigned char * font_collection, char * name_utf8, stbtt_int32 flags) static
Definition at line 4951 of file stb_truetype.cpp.hpp.
            {
   stbtt_int32 i;
   for (i=0;;++i) {
      stbtt_int32 off = stbtt_GetFontOffsetForIndex(font_collection, i);
      if (off < 0) return off;
      if (stbtt__matches((stbtt_uint8 *) font_collection, off, (stbtt_uint8*) name_utf8, flags))
         return off;
   }
}
References FL_NOEXCEPT, stbtt__matches(), and stbtt_GetFontOffsetForIndex().
Referenced by stbtt_FindMatchingFont().