FastLED: fl::third_party::truetype::stbtt_GetGlyphSVG
stbtt_GetGlyphSVG()
int32_t fl::third_party::truetype::stbtt_GetGlyphSVG (const stbtt_fontinfo * info, int32_t gl, const char ** svg)
Definition at line 2723 of file stb_truetype.cpp.hpp.
            {
   stbtt_uint8 *data = info->data;
   stbtt_uint8 *svg_doc;
   if (info->svg == 0)
      return 0;
   svg_doc = stbtt_FindSVGDoc(info, gl);
   if (svg_doc != nullptr) {
      *svg = (char *) data + info->svg + ttULONG(svg_doc + 4);
      return ttULONG(svg_doc + 8);
   } else {
      return 0;
   }
}
References FL_NOEXCEPT, stbtt_FindSVGDoc(), and ttULONG().
Referenced by stbtt_GetCodepointSVG().