FastLED: fl::third_party::truetype::stbtt_FindSVGDoc
stbtt_FindSVGDoc()
unsigned char * fl::third_party::truetype::stbtt_FindSVGDoc (const stbtt_fontinfo * info, int32_t gl)
Definition at line 2706 of file stb_truetype.cpp.hpp.
            {
   int32_t i;
   stbtt_uint8 *data = info->data;
   stbtt_uint8 *svg_doc_list = data + stbtt__get_svg((stbtt_fontinfo *) info);
   int32_t numEntries = ttUSHORT(svg_doc_list);
   stbtt_uint8 *svg_docs = svg_doc_list + 2;
   for(i=0; i<numEntries; i++) {
      stbtt_uint8 *svg_doc = svg_docs + (12 * i);
      if ((gl >= ttUSHORT(svg_doc)) && (gl <= ttUSHORT(svg_doc + 2)))
         return svg_doc;
   }
   return 0;
}
References FL_NOEXCEPT, stbtt__get_svg(), and ttUSHORT().
Referenced by stbtt_GetGlyphSVG().