FastLED: fl::third_party::truetype::stbtt__buf_range
stbtt__buf_range()
static stbtt__buf fl::third_party::truetype::stbtt__buf_range (const stbtt__buf * b, int32_t o, int32_t s) static
Definition at line 1207 of file stb_truetype.cpp.hpp.
            {
   stbtt__buf r = stbtt__new_buf(nullptr, 0);
   if (o < 0 || s < 0 || o > b->size || s > b->size - o) return r;
   r.data = b->data + o;
   r.size = s;
   return r;
}
References fl::third_party::truetype::stbtt__buf::data, FL_NOEXCEPT, fl::third_party::truetype::stbtt__buf::size, and stbtt__new_buf().
Referenced by stbtt__cff_get_index(), stbtt__cff_index_get(), stbtt__dict_get(), stbtt__get_subrs(), and stbtt_InitFont_internal().