FastLED: fl::third_party::truetype::stbtt_PackFontRangesGatherRects
stbtt_PackFontRangesGatherRects()
int32_t fl::third_party::truetype::stbtt_PackFontRangesGatherRects (stbtt_pack_context * spc, const stbtt_fontinfo * info, stbtt_pack_range * ranges, int32_t num_ranges, stbrp_rect * rects)
Definition at line 4179 of file stb_truetype.cpp.hpp.
            {
   int32_t i,j,k;
   int32_t missing_glyph_added = 0;
   k=0;
   for (i=0; i < num_ranges; ++i) {
      float fh = ranges[i].font_size;
      float scale = fh > 0 ? stbtt_ScaleForPixelHeight(info, fh) : stbtt_ScaleForMappingEmToPixels(info, -fh);
      ranges[i].h_oversample = (unsigned char) spc->h_oversample;
      ranges[i].v_oversample = (unsigned char) spc->v_oversample;
      for (j=0; j < ranges[i].num_chars; ++j) {
         int32_t x0,y0,x1,y1;
         int32_t codepoint = ranges[i].array_of_unicode_codepoints == nullptr ? ranges[i].first_unicode_codepoint_in_range + j : ranges[i].array_of_unicode_codepoints[j];
         int32_t glyph = stbtt_FindGlyphIndex(info, codepoint);
         if (glyph == 0 && (spc->skip_missing || missing_glyph_added)) {
            rects[k].w = rects[k].h = 0;
         } else {
            stbtt_GetGlyphBitmapBoxSubpixel(info,glyph,
                                            scale * spc->h_oversample,
                                            scale * spc->v_oversample,
                                            0,0,
                                            &x0,&y0,&x1,&y1);
            rects[k].w = (stbrp_coord) (x1-x0 + spc->padding + spc->h_oversample-1);
            rects[k].h = (stbrp_coord) (y1-y0 + spc->padding + spc->v_oversample-1);
            if (glyph == 0)
               missing_glyph_added = 1;
         }
         ++k;
      }
   }
   return k;
}
References FL_NOEXCEPT, scale, stbtt_FindGlyphIndex(), stbtt_GetGlyphBitmapBoxSubpixel(), stbtt_ScaleForMappingEmToPixels(), and stbtt_ScaleForPixelHeight().
Referenced by stbtt_PackFontRanges().