FastLED: fl::third_party::truetype::stbtt__matches
stbtt__matches()
static int32_t fl::third_party::truetype::stbtt__matches (stbtt_uint8 * fc, stbtt_uint32 offset, stbtt_uint8 * name, stbtt_int32 flags) static
Definition at line 4922 of file stb_truetype.cpp.hpp.
            {
   stbtt_int32 nlen = (stbtt_int32) STBTT_strlen((char *) name);
   stbtt_uint32 nm,hd;
   if (!stbtt__isfont(fc+offset)) return 0;
   // check italics/bold/underline flags in macStyle...
   if (flags) {
      hd = stbtt__find_table(fc, offset, "head");
      if ((ttUSHORT(fc+hd+44) & 7) != (flags & 7)) return 0;
   }
   nm = stbtt__find_table(fc, offset, "name");
   if (!nm) return 0;
   if (flags) {
      // if we checked the macStyle flags, then just check the family and ignore the subfamily
      if (stbtt__matchpair(fc, nm, name, nlen, 16, -1))  return 1;
      if (stbtt__matchpair(fc, nm, name, nlen,  1, -1))  return 1;
      if (stbtt__matchpair(fc, nm, name, nlen,  3, -1))  return 1;
   } else {
      if (stbtt__matchpair(fc, nm, name, nlen, 16, 17))  return 1;
      if (stbtt__matchpair(fc, nm, name, nlen,  1,  2))  return 1;
      if (stbtt__matchpair(fc, nm, name, nlen,  3, -1))  return 1;
   }
   return 0;
}
References FL_NOEXCEPT, offset(), stbtt__find_table(), stbtt__isfont(), stbtt__matchpair(), STBTT_strlen, and ttUSHORT().
Referenced by stbtt_FindMatchingFont_internal().