FastLED: fl::third_party::truetype::stbtt_GetFontNameString
stbtt_GetFontNameString()
const char * fl::third_party::truetype::stbtt_GetFontNameString (const stbtt_fontinfo * font, int32_t * length, int32_t platformID, int32_t encodingID, int32_t languageID, int32_t nameID)
Definition at line 4854 of file stb_truetype.cpp.hpp.
            {
   stbtt_int32 i,count,stringOffset;
   stbtt_uint8 *fc = font->data;
   stbtt_uint32 offset = font->fontstart;
   stbtt_uint32 nm = stbtt__find_table(fc, offset, "name");
   if (!nm) return nullptr;
   count = ttUSHORT(fc+nm+2);
   stringOffset = nm + ttUSHORT(fc+nm+4);
   for (i=0; i < count; ++i) {
      stbtt_uint32 loc = nm + 6 + 12 * i;
      if (platformID == ttUSHORT(fc+loc+0) && encodingID == ttUSHORT(fc+loc+2)
          && languageID == ttUSHORT(fc+loc+4) && nameID == ttUSHORT(fc+loc+6)) {
         *length = ttUSHORT(fc+loc+8);
         return (const char *) (fc+stringOffset+ttUSHORT(fc+loc+10));
      }
   }
   return nullptr;
}
References FL_NOEXCEPT, length(), offset(), stbtt__find_table(), and ttUSHORT().