FastLED: fl::third_party::truetype::stbtt_PackFontRanges
stbtt_PackFontRanges()
int32_t fl::third_party::truetype::stbtt_PackFontRanges (stbtt_pack_context * spc, const unsigned char * fontdata, int32_t font_index, stbtt_pack_range * ranges, int32_t num_ranges)
Definition at line 4332 of file stb_truetype.cpp.hpp.
            {
   stbtt_fontinfo info;
   int32_t i,j,n, return_value = 1;
   //stbrp_context *context = (stbrp_context *) spc->pack_info;
   stbrp_rect    *rects;
   // flag all characters as NOT packed
   for (i=0; i < num_ranges; ++i)
      for (j=0; j < ranges[i].num_chars; ++j)
         ranges[i].chardata_for_range[j].x0 =
         ranges[i].chardata_for_range[j].y0 =
         ranges[i].chardata_for_range[j].x1 =
         ranges[i].chardata_for_range[j].y1 = 0;
   n = 0;
   for (i=0; i < num_ranges; ++i)
      n += ranges[i].num_chars;
   rects = (stbrp_rect *) STBTT_malloc(sizeof(*rects) * n, spc->user_allocator_context);
   if (rects == nullptr)
      return 0;
   info.userdata = spc->user_allocator_context;
   stbtt_InitFont(&info, fontdata, stbtt_GetFontOffsetForIndex(fontdata,font_index));
   n = stbtt_PackFontRangesGatherRects(spc, &info, ranges, num_ranges, rects);
   stbtt_PackFontRangesPackRects(spc, rects, n);
   return_value = stbtt_PackFontRangesRenderIntoRects(spc, &info, ranges, num_ranges, rects);
   STBTT_free(rects, spc->user_allocator_context);
   return return_value;
}
References FL_NOEXCEPT, STBTT_free, stbtt_GetFontOffsetForIndex(), stbtt_InitFont(), STBTT_malloc, stbtt_PackFontRangesGatherRects(), stbtt_PackFontRangesPackRects(), stbtt_PackFontRangesRenderIntoRects(), and fl::third_party::truetype::stbtt_fontinfo::userdata.
Referenced by stbtt_PackFontRange().