FastLED: fl::third_party::truetype::stbtt_MakeGlyphBitmapSubpixel
stbtt_MakeGlyphBitmapSubpixel()
void fl::third_party::truetype::stbtt_MakeGlyphBitmapSubpixel (const stbtt_fontinfo * info, unsigned char * output, int32_t out_w, int32_t out_h, int32_t out_stride, float scale_x, float scale_y, float shift_x, float shift_y, int32_t glyph)
Definition at line 3788 of file stb_truetype.cpp.hpp.
            {
   int32_t ix0,iy0;
   stbtt_vertex *vertices;
   int32_t num_verts = stbtt_GetGlyphShape(info, glyph, &vertices);
   stbtt__bitmap gbm;
   stbtt_GetGlyphBitmapBoxSubpixel(info, glyph, scale_x, scale_y, shift_x, shift_y, &ix0,&iy0,0,0);
   gbm.pixels = output;
   gbm.w = out_w;
   gbm.h = out_h;
   gbm.stride = out_stride;
   if (gbm.w && gbm.h)
      stbtt_Rasterize(&gbm, 0.35f, vertices, num_verts, scale_x, scale_y, shift_x, shift_y, ix0,iy0, 1, info->userdata);
   STBTT_free(vertices, info->userdata);
}
References FL_NOEXCEPT, fl::third_party::truetype::stbtt__bitmap::h, fl::third_party::truetype::stbtt__bitmap::pixels, scale_x, scale_y, STBTT_free, stbtt_GetGlyphBitmapBoxSubpixel(), stbtt_GetGlyphShape(), stbtt_Rasterize(), fl::third_party::truetype::stbtt__bitmap::stride, and fl::third_party::truetype::stbtt__bitmap::w.
Referenced by stbtt_MakeCodepointBitmapSubpixel(), stbtt_MakeGlyphBitmap(), stbtt_MakeGlyphBitmapSubpixelPrefilter(), and stbtt_PackFontRangesRenderIntoRects().