FastLED: fl::third_party::truetype::stbtt_FlattenCurves
stbtt_FlattenCurves()
static stbtt__point * fl::third_party::truetype::stbtt_FlattenCurves (stbtt_vertex * vertices, int32_t num_verts, float objspace_flatness, int32_t ** contour_lengths, int32_t * num_contours, void * userdata) static
Definition at line 3648 of file stb_truetype.cpp.hpp.
            {
   stbtt__point *points=0;
   int32_t num_points=0;
   float objspace_flatness_squared = objspace_flatness * objspace_flatness;
   int32_t i,n=0,start=0, pass;
   // count how many "moves" there are to get the contour count
   for (i=0; i < num_verts; ++i)
      if (vertices[i].type == STBTT_vmove)
         ++n;
   *num_contours = n;
   if (n == 0) return 0;
   *contour_lengths = (int32_t *) STBTT_malloc(sizeof(**contour_lengths) * n, userdata);
   if (*contour_lengths == 0) {
      *num_contours = 0;
      return 0;
   }
   // make two passes through the points so we don't need to realloc
   for (pass=0; pass < 2; ++pass) {
      float x=0,y=0;
      if (pass == 1) {
         points = (stbtt__point *) STBTT_malloc(num_points * sizeof(points[0]), userdata);
         if (points == nullptr) goto error;
      }
      num_points = 0;
      n= -1;
      for (i=0; i < num_verts; ++i) {
         switch (vertices[i].type) {
            case STBTT_vmove:
               // start the next contour
               if (n >= 0)
                  (*contour_lengths)[n] = num_points - start;
               ++n;
               start = num_points;
               x = vertices[i].x, y = vertices[i].y;
               stbtt__add_point(points, num_points++, x,y);
               break;
            case STBTT_vline:
               x = vertices[i].x, y = vertices[i].y;
               stbtt__add_point(points, num_points++, x, y);
               break;
            case STBTT_vcurve:
               stbtt__tesselate_curve(points, &num_points, x,y,
                                        vertices[i].cx, vertices[i].cy,
                                        vertices[i].x,  vertices[i].y,
                                        objspace_flatness_squared, 0);
               x = vertices[i].x, y = vertices[i].y;
               break;
            case STBTT_vcubic:
               stbtt__tesselate_cubic(points, &num_points, x,y,
                                        vertices[i].cx, vertices[i].cy,
                                        vertices[i].cx1, vertices[i].cy1,
                                        vertices[i].x,  vertices[i].y,
                                        objspace_flatness_squared, 0);
               x = vertices[i].x, y = vertices[i].y;
               break;
         }
      }
      (*contour_lengths)[n] = num_points - start;
   }
   return points;
error:
   STBTT_free(points, userdata);
   STBTT_free(*contour_lengths, userdata);
   *contour_lengths = 0;
   *num_contours = 0;
   return nullptr;
}
References FL_NOEXCEPT, stbtt__add_point(), stbtt__tesselate_cubic(), stbtt__tesselate_curve(), STBTT_free, STBTT_malloc, STBTT_vcubic, STBTT_vcurve, STBTT_vline, STBTT_vmove, fl::x, and fl::y.
Referenced by stbtt_Rasterize().