FastLED: fl::third_party::truetype::stbtt__get_svg
stbtt__get_svg()
static int32_t fl::third_party::truetype::stbtt__get_svg (stbtt_fontinfo * info) static
Definition at line 1394 of file stb_truetype.cpp.hpp.
            {
   stbtt_uint32 t;
   if (info->svg < 0) {
      t = stbtt__find_table(info->data, info->fontstart, "SVG ");
      if (t) {
         stbtt_uint32 offset = ttULONG(info->data + t + 2);
         info->svg = t + offset;
      } else {
         info->svg = 0;
      }
   }
   return info->svg;
}
References FL_NOEXCEPT, offset(), stbtt__find_table(), fl::t, and ttULONG().
Referenced by stbtt_FindSVGDoc().