FastLED: fl::third_party::truetype::stbtt_GetFontOffsetForIndex_internal
stbtt_GetFontOffsetForIndex_internal()
static int32_t fl::third_party::truetype::stbtt_GetFontOffsetForIndex_internal (unsigned char * font_collection, int32_t index) static
Definition at line 1345 of file stb_truetype.cpp.hpp.
            {
   // if it's just a font, there's only one valid index
   if (stbtt__isfont(font_collection))
      return index == 0 ? 0 : -1;
   // check if it's a TTC
   if (stbtt_tag(font_collection, "ttcf")) {
      // version 1?
      if (ttULONG(font_collection+4) == 0x00010000 || ttULONG(font_collection+4) == 0x00020000) {
         stbtt_int32 n = ttLONG(font_collection+8);
         if (index >= n)
            return -1;
         return ttULONG(font_collection+12+index*4);
      }
   }
   return -1;
}
References FL_NOEXCEPT, stbtt__isfont(), stbtt_tag, ttLONG(), and ttULONG().
Referenced by stbtt_GetFontOffsetForIndex().