FastLED: fl::third_party::truetype::stbtt__GetGlyphKernInfoAdvance
stbtt__GetGlyphKernInfoAdvance()
static int32_t fl::third_party::truetype::stbtt__GetGlyphKernInfoAdvance (const stbtt_fontinfo * info, int32_t glyph1, int32_t glyph2) static
Definition at line 2388 of file stb_truetype.cpp.hpp.
            {
   stbtt_uint8 *data = info->data + info->kern;
   stbtt_uint32 needle, straw;
   int32_t l, r, m;
   // we only look at the first table. it must be 'horizontal' and format 0.
   if (!info->kern)
      return 0;
   if (ttUSHORT(data+2) < 1) // number of tables, need at least 1
      return 0;
   if (ttUSHORT(data+8) != 1) // horizontal flag must be set in format
      return 0;
   l = 0;
   r = ttUSHORT(data+10) - 1;
   needle = glyph1 << 16 | glyph2;
   while (l <= r) {
      m = (l + r) >> 1;
      straw = ttULONG(data+18+(m*6)); // note: unaligned read
      if (needle < straw)
         r = m - 1;
      else if (needle > straw)
         l = m + 1;
      else
         return ttSHORT(data+22+(m*6));
   }
   return 0;
}
References FL_NOEXCEPT, ttSHORT(), ttULONG(), and ttUSHORT().
Referenced by stbtt_GetGlyphKernAdvance().