FastLED: fl::third_party::truetype::stbtt__GetGlyphInfoT2
stbtt__GetGlyphInfoT2()
static int32_t fl::third_party::truetype::stbtt__GetGlyphInfoT2 (const stbtt_fontinfo * info, int32_t glyph_index, int32_t * x0, int32_t * y0, int32_t * x1, int32_t * y1) static
Definition at line 2315 of file stb_truetype.cpp.hpp.
            {
   stbtt__csctx c = STBTT__CSCTX_INIT(1);
   int32_t r = stbtt__run_charstring(info, glyph_index, &c);
   if (x0)  *x0 = r ? c.min_x : 0;
   if (y0)  *y0 = r ? c.min_y : 0;
   if (x1)  *x1 = r ? c.max_x : 0;
   if (y1)  *y1 = r ? c.max_y : 0;
   return r ? c.num_vertices : 0;
}
References FL_NOEXCEPT, fl::third_party::truetype::stbtt__csctx::max_x, fl::third_party::truetype::stbtt__csctx::max_y, fl::third_party::truetype::stbtt__csctx::min_x, fl::third_party::truetype::stbtt__csctx::min_y, fl::third_party::truetype::stbtt__csctx::num_vertices, STBTT__CSCTX_INIT, and stbtt__run_charstring().
Referenced by stbtt_GetGlyphBox(), and stbtt_IsGlyphEmpty().