FastLED: fl::third_party::truetype::stbtt_GetGlyphBox
stbtt_GetGlyphBox()
int32_t fl::third_party::truetype::stbtt_GetGlyphBox (const stbtt_fontinfo * info, int32_t glyph_index, int32_t * x0, int32_t * y0, int32_t * x1, int32_t * y1)
Definition at line 1654 of file stb_truetype.cpp.hpp.
            {
   if (info->cff.size) {
      stbtt__GetGlyphInfoT2(info, glyph_index, x0, y0, x1, y1);
   } else {
      int32_t g = stbtt__GetGlyfOffset(info, glyph_index);
      if (g < 0) return 0;
      if (x0) *x0 = ttSHORT(info->data + g + 2);
      if (y0) *y0 = ttSHORT(info->data + g + 4);
      if (x1) *x1 = ttSHORT(info->data + g + 6);
      if (y1) *y1 = ttSHORT(info->data + g + 8);
   }
   return 1;
}
References FL_NOEXCEPT, stbtt__GetGlyfOffset(), stbtt__GetGlyphInfoT2(), and ttSHORT().
Referenced by stbtt_GetCodepointBox(), and stbtt_GetGlyphBitmapBoxSubpixel().