FastLED: fl::third_party::truetype::stbtt_setvertex
stbtt_setvertex()
static void fl::third_party::truetype::stbtt_setvertex (stbtt_vertex * v, stbtt_uint8 type, stbtt_int32 x, stbtt_int32 y, stbtt_int32 cx, stbtt_int32 cy) static
Definition at line 1623 of file stb_truetype.cpp.hpp.
            {
   v->type = type;
   v->x = (stbtt_int16) x;
   v->y = (stbtt_int16) y;
   v->cx = (stbtt_int16) cx;
   v->cy = (stbtt_int16) cy;
}
References FL_NOEXCEPT, fl::x, and fl::y.
Referenced by stbtt__close_shape(), stbtt__csctx_v(), and stbtt__GetGlyphShapeTT().