FastLED: fl::third_party::truetype::stbtt__isfont
stbtt__isfont()
static int32_t fl::third_party::truetype::stbtt__isfont (stbtt_uint8 * font) static
Definition at line 1320 of file stb_truetype.cpp.hpp.
            {
   // check the version number
   if (stbtt_tag4(font, '1',0,0,0))  return 1; // TrueType 1
   if (stbtt_tag(font, "typ1"))   return 1; // TrueType with type 1 font -- we don't support this!
   if (stbtt_tag(font, "OTTO"))   return 1; // OpenType with CFF
   if (stbtt_tag4(font, 0,1,0,0)) return 1; // OpenType 1.0
   if (stbtt_tag(font, "true"))   return 1; // Apple specification for TrueType fonts
   return 0;
}
References FL_NOEXCEPT, stbtt_tag, and stbtt_tag4.
Referenced by stbtt__matches(), stbtt_GetFontOffsetForIndex_internal(), and stbtt_GetNumberOfFonts_internal().