FastLED: fl::third_party::truetype::stbtt__get_subr
stbtt__get_subr()
static stbtt__buf fl::third_party::truetype::stbtt__get_subr (stbtt__buf idx, int32_t n) static
Definition at line 1997 of file stb_truetype.cpp.hpp.
            {
   int32_t count = stbtt__cff_index_count(&idx);
   int32_t bias = 107;
   if (count >= 33900)
      bias = 32768;
   else if (count >= 1240)
      bias = 1131;
   n += bias;
   if (n < 0 || n >= count)
      return stbtt__new_buf(nullptr, 0);
   return stbtt__cff_index_get(idx, n);
}
References FL_NOEXCEPT, stbtt__cff_index_count(), stbtt__cff_index_get(), and stbtt__new_buf().
Referenced by stbtt__run_charstring().