FastLED: fl::third_party::truetype::stbtt_GetGlyphHMetrics
stbtt_GetGlyphHMetrics()
void fl::third_party::truetype::stbtt_GetGlyphHMetrics (const stbtt_fontinfo * info, int32_t glyph_index, int32_t * advanceWidth, int32_t * leftSideBearing)
Definition at line 2334 of file stb_truetype.cpp.hpp.
            {
   stbtt_uint16 numOfLongHorMetrics = ttUSHORT(info->data+info->hhea + 34);
   if (glyph_index < numOfLongHorMetrics) {
      if (advanceWidth)     *advanceWidth    = ttSHORT(info->data + info->hmtx + 4*glyph_index);
      if (leftSideBearing)  *leftSideBearing = ttSHORT(info->data + info->hmtx + 4*glyph_index + 2);
   } else {
      if (advanceWidth)     *advanceWidth    = ttSHORT(info->data + info->hmtx + 4*(numOfLongHorMetrics-1));
      if (leftSideBearing)  *leftSideBearing = ttSHORT(info->data + info->hmtx + 4*numOfLongHorMetrics + 2*(glyph_index - numOfLongHorMetrics));
   }
}
References FL_NOEXCEPT, ttSHORT(), and ttUSHORT().
Referenced by stbtt_BakeFontBitmap_internal(), stbtt_GetCodepointHMetrics(), and stbtt_PackFontRangesRenderIntoRects().