FastLED: fl::third_party::truetype::stbtt_InitFont_internal
stbtt_InitFont_internal()
static int32_t fl::third_party::truetype::stbtt_InitFont_internal (stbtt_fontinfo * info, unsigned char * data, int32_t fontstart) static
Definition at line 1409 of file stb_truetype.cpp.hpp.
            {
   stbtt_uint32 cmap, t;
   stbtt_int32 i,numTables;
   info->data = data;
   info->fontstart = fontstart;
   info->cff = stbtt__new_buf(nullptr, 0);
   cmap = stbtt__find_table(data, fontstart, "cmap");       // required
   info->loca = stbtt__find_table(data, fontstart, "loca"); // required
   info->head = stbtt__find_table(data, fontstart, "head"); // required
   info->glyf = stbtt__find_table(data, fontstart, "glyf"); // required
   info->hhea = stbtt__find_table(data, fontstart, "hhea"); // required
   info->hmtx = stbtt__find_table(data, fontstart, "hmtx"); // required
   info->kern = stbtt__find_table(data, fontstart, "kern"); // not required
   info->gpos = stbtt__find_table(data, fontstart, "GPOS"); // not required
   if (!cmap || !info->head || !info->hhea || !info->hmtx)
      return 0;
   if (info->glyf) {
      // required for truetype
      if (!info->loca) return 0;
   } else {
      // initialization for CFF / Type2 fonts (OTF)
      stbtt__buf b, topdict, topdictidx;
      stbtt_uint32 cstype = 2, charstrings = 0, fdarrayoff = 0, fdselectoff = 0;
      stbtt_uint32 cff;
      cff = stbtt__find_table(data, fontstart, "CFF ");
      if (!cff) return 0;
      info->fontdicts = stbtt__new_buf(nullptr, 0);
      info->fdselect = stbtt__new_buf(nullptr, 0);
      // @TODO this should use size from table (not 512MB)
      // On 8-bit platforms (size_t < 4 bytes), use max size_t value to avoid overflow
      #define STBTT_CFF_SIZE_LIMIT (512L*1024L*1024L)
      info->cff = stbtt__new_buf(data+cff,
         (sizeof(size_t) < 4) ? (size_t)-1 : (size_t)STBTT_CFF_SIZE_LIMIT);
      b = info->cff;
      // read the header
      stbtt__buf_skip(&b, 2);
      stbtt__buf_seek(&b, stbtt__buf_get8(&b)); // hdrsize
      // @TODO the name INDEX could list multiple fonts,
      // but we just use the first one.
      stbtt__cff_get_index(&b);  // name INDEX
      topdictidx = stbtt__cff_get_index(&b);
      topdict = stbtt__cff_index_get(topdictidx, 0);
      stbtt__cff_get_index(&b);  // string INDEX
      info->gsubrs = stbtt__cff_get_index(&b);
      stbtt__dict_get_ints(&topdict, 17, 1, &charstrings);
      stbtt__dict_get_ints(&topdict, 0x100 | 6, 1, &cstype);
      stbtt__dict_get_ints(&topdict, 0x100 | 36, 1, &fdarrayoff);
      stbtt__dict_get_ints(&topdict, 0x100 | 37, 1, &fdselectoff);
      info->subrs = stbtt__get_subrs(b, topdict);
      // we only support Type 2 charstrings
      if (cstype != 2) return 0;
      if (charstrings == 0) return 0;
      if (fdarrayoff) {
         // looks like a CID font
         if (!fdselectoff) return 0;
         stbtt__buf_seek(&b, fdarrayoff);
         info->fontdicts = stbtt__cff_get_index(&b);
         info->fdselect = stbtt__buf_range(&b, fdselectoff, b.size-fdselectoff);
      }
      stbtt__buf_seek(&b, charstrings);
      info->charstrings = stbtt__cff_get_index(&b);
   }
   t = stbtt__find_table(data, fontstart, "maxp");
   if (t)
      info->numGlyphs = ttUSHORT(data+t+4);
   else
      info->numGlyphs = 0xffff;
   info->svg = -1;
   // find a cmap encoding table we understand *now* to avoid searching
   // later. (todo: could make this installable)
   // the same regardless of glyph.
   numTables = ttUSHORT(data + cmap + 2);
   info->index_map = 0;
   for (i=0; i < numTables; ++i) {
      stbtt_uint32 encoding_record = cmap + 4 + 8 * i;
      // find an encoding we understand:
      switch(ttUSHORT(data+encoding_record)) {
         case STBTT_PLATFORM_ID_MICROSOFT:
            switch (ttUSHORT(data+encoding_record+2)) {
               case STBTT_MS_EID_UNICODE_BMP:
               case STBTT_MS_EID_UNICODE_FULL:
                  // MS/Unicode
                  info->index_map = cmap + ttULONG(data+encoding_record+4);
                  break;
            }
            break;
        case STBTT_PLATFORM_ID_UNICODE:
            // Mac/iOS has these
            // all the encodingIDs are unicode, so we don't bother to check it
            info->index_map = cmap + ttULONG(data+encoding_record+4);
            break;
      }
   }
   if (info->index_map == 0)
      return 0;
   info->indexToLocFormat = ttUSHORT(data+info->head + 50);
   return 1;
}
References FL_NOEXCEPT, fl::third_party::truetype::stbtt__buf::size, stbtt__buf_get8(), stbtt__buf_range(), stbtt__buf_seek(), stbtt__buf_skip(), stbtt__cff_get_index(), stbtt__cff_index_get(), stbtt__dict_get_ints(), stbtt__find_table(), stbtt__get_subrs(), stbtt__new_buf(), STBTT_CFF_SIZE_LIMIT, STBTT_MS_EID_UNICODE_BMP, STBTT_MS_EID_UNICODE_FULL, STBTT_PLATFORM_ID_MICROSOFT, STBTT_PLATFORM_ID_UNICODE, fl::t, ttULONG(), and ttUSHORT().
Referenced by stbtt_InitFont().