FastLED: fl::third_party::truetype::stbtt__dict_get_ints
stbtt__dict_get_ints()
static void fl::third_party::truetype::stbtt__dict_get_ints (stbtt__buf * b, int32_t key, int32_t outcount, stbtt_uint32 * out) static
Definition at line 1272 of file stb_truetype.cpp.hpp.
            {
   int32_t i;
   stbtt__buf operands = stbtt__dict_get(b, key);
   for (i = 0; i < outcount && operands.cursor < operands.size; i++)
      out[i] = stbtt__cff_int(&operands);
}
References fl::third_party::truetype::stbtt__buf::cursor, FL_NOEXCEPT, fl::third_party::truetype::stbtt__buf::size, stbtt__cff_int(), and stbtt__dict_get().
Referenced by stbtt__get_subrs(), and stbtt_InitFont_internal().