FastLED: fl::third_party::truetype::stbtt__compute_crossings_x
stbtt__compute_crossings_x()
static int32_t fl::third_party::truetype::stbtt__compute_crossings_x (float x, float y, int32_t nverts, stbtt_vertex * verts) static
Definition at line 4497 of file stb_truetype.cpp.hpp.
            {
   int32_t i;
   float orig[2], ray[2] = { 1, 0 };
   float y_frac;
   int32_t winding = 0;
   // make sure y never passes through a vertex of the shape
   y_frac = (float) STBTT_fmod(y, 1.0f);
   if (y_frac < 0.01f)
      y += 0.01f;
   else if (y_frac > 0.99f)
      y -= 0.01f;
   orig[0] = x;
   orig[1] = y;
   // test a ray from (-infinity,y) to (x,y)
   for (i=0; i < nverts; ++i) {
      if (verts[i].type == STBTT_vline) {
         int32_t x0 = (int) verts[i-1].x, y0 = (int) verts[i-1].y;
         int32_t x1 = (int) verts[i  ].x, y1 = (int) verts[i  ].y;
         if (y > STBTT_min(y0,y1) && y < STBTT_max(y0,y1) && x > STBTT_min(x0,x1)) {
            float x_inter = (y - y0) / (y1 - y0) * (x1-x0) + x0;
            if (x_inter < x)
               winding += (y0 < y1) ? 1 : -1;
         }
      }
      if (verts[i].type == STBTT_vcurve) {
         int32_t x0 = (int) verts[i-1].x , y0 = (int) verts[i-1].y ;
         int32_t x1 = (int) verts[i  ].cx, y1 = (int) verts[i  ].cy;
         int32_t x2 = (int) verts[i  ].x , y2 = (int) verts[i  ].y ;
         int32_t ax = STBTT_min(x0,STBTT_min(x1,x2)), ay = STBTT_min(y0,STBTT_min(y1,y2));
         int32_t by = STBTT_max(y0,STBTT_max(y1,y2));
         if (y > ay && y < by && x > ax) {
            float q0[2],q1[2],q2[2];
            float hits[2][2];
            q0[0] = (float)x0;
            q0[1] = (float)y0;
            q1[0] = (float)x1;
            q1[1] = (float)y1;
            q2[0] = (float)x2;
            q2[1] = (float)y2;
            if (equal(q0,q1) || equal(q1,q2)) {
               x0 = (int)verts[i-1].x;
               y0 = (int)verts[i-1].y;
               x1 = (int)verts[i  ].x;
               y1 = (int)verts[i  ].y;
               if (y > STBTT_min(y0,y1) && y < STBTT_max(y0,y1) && x > STBTT_min(x0,x1)) {
                  float x_inter = (y - y0) / (y1 - y0) * (x1-x0) + x0;
                  if (x_inter < x)
                     winding += (y0 < y1) ? 1 : -1;
               }
            } else {
               int32_t num_hits = stbtt__ray_intersect_bezier(orig, ray, q0, q1, q2, hits);
               if (num_hits >= 1)
                  if (hits[0][0] < 0)
                     winding += (hits[0][1] < 0 ? -1 : 1);
               if (num_hits >= 2)
                  if (hits[1][0] < 0)
                     winding += (hits[1][1] < 0 ? -1 : 1);
            }
         }
      }
   }
   return winding;
}
References equal(), FL_NOEXCEPT, stbtt__ray_intersect_bezier(), STBTT_fmod, STBTT_max, STBTT_min, STBTT_vcurve, STBTT_vline, fl::x, and fl::y.
Referenced by stbtt_GetGlyphSDF().