FastLED: fl::third_party::truetype::stbtt__tesselate_curve
stbtt__tesselate_curve()
static int32_t fl::third_party::truetype::stbtt__tesselate_curve (stbtt__point * points, int32_t * num_points, float x0, float y0, float x1, float y1, float x2, float y2, float objspace_flatness_squared, int32_t n) static
Definition at line 3585 of file stb_truetype.cpp.hpp.
            {
   // midpoint
   float mx = (x0 + 2*x1 + x2)/4;
   float my = (y0 + 2*y1 + y2)/4;
   // versus directly drawn line
   float dx = (x0+x2)/2 - mx;
   float dy = (y0+y2)/2 - my;
   if (n > 16) // 65536 segments on one curve better be enough!
      return 1;
   if (dx*dx+dy*dy > objspace_flatness_squared) { // half-pixel error allowed... need to be smaller if AA
      stbtt__tesselate_curve(points, num_points, x0,y0, (x0+x1)/2.0f,(y0+y1)/2.0f, mx,my, objspace_flatness_squared,n+1);
      stbtt__tesselate_curve(points, num_points, mx,my, (x1+x2)/2.0f,(y1+y2)/2.0f, x2,y2, objspace_flatness_squared,n+1);
   } else {
      stbtt__add_point(points, *num_points,x2,y2);
      *num_points = *num_points+1;
   }
   return 1;
}
References FL_NOEXCEPT, stbtt__add_point(), and stbtt__tesselate_curve().
Referenced by stbtt__tesselate_curve(), and stbtt_FlattenCurves().