FastLED: fl::third_party::truetype::stbtt__csctx_rmove_to
stbtt__csctx_rmove_to()
static void fl::third_party::truetype::stbtt__csctx_rmove_to (stbtt__csctx * ctx, float dx, float dy) static
Definition at line 1971 of file stb_truetype.cpp.hpp.
            {
   stbtt__csctx_close_shape(ctx);
   ctx->first_x = ctx->x = ctx->x + dx;
   ctx->first_y = ctx->y = ctx->y + dy;
   stbtt__csctx_v(ctx, STBTT_vmove, (int)ctx->x, (int)ctx->y, 0, 0, 0, 0);
}
References FL_NOEXCEPT, stbtt__csctx_close_shape(), stbtt__csctx_v(), and STBTT_vmove.
Referenced by stbtt__run_charstring().