FastLED: fl::EngineEvents::onBeginFrame
onBeginFrame()
static void fl::EngineEvents::onBeginFrame () inline static
Definition at line 81 of file engine_events.h.
{
        #if FASTLED_HAS_ENGINE_EVENTS
        EngineEvents::getInstance()->_onBeginFrame();
        #endif
    }
References _onBeginFrame(), and getInstance().
Referenced by CFastLED::show().