FastLED: fl::audio::detector::KeyDetector::initializeProfileStats
initializeProfileStats()
void fl::audio::detector::KeyDetector::initializeProfileStats () private
Definition at line 98 of file key.cpp.hpp.
{
    // Pre-compute statistics for MAJOR_PROFILE
    float majorSum = 0.0f, majorSqSum = 0.0f;
    for (int i = 0; i < 12; i++) {
        majorSum += MAJOR_PROFILE[i];
        majorSqSum += MAJOR_PROFILE[i] * MAJOR_PROFILE[i];
    }
    mMajorProfileMean = majorSum / 12.0f;
    mMajorProfileStdDev = fl::sqrtf(majorSqSum / 12.0f - mMajorProfileMean * mMajorProfileMean);
    // Pre-compute statistics for MINOR_PROFILE
    float minorSum = 0.0f, minorSqSum = 0.0f;
    for (int i = 0; i < 12; i++) {
        minorSum += MINOR_PROFILE[i];
        minorSqSum += MINOR_PROFILE[i] * MINOR_PROFILE[i];
    }
    mMinorProfileMean = minorSum / 12.0f;
    mMinorProfileStdDev = fl::sqrtf(minorSqSum / 12.0f - mMinorProfileMean * mMinorProfileMean);
}
References KeyDetector(), initializeProfileStats(), MAJOR_PROFILE, MINOR_PROFILE, mMajorProfileMean, mMajorProfileStdDev, mMinorProfileMean, mMinorProfileStdDev, and fl::sqrtf().
Referenced by KeyDetector(), and initializeProfileStats().