FastLED: fl::audio::detector::KeyDetector::update
update()
void fl::audio::detector::KeyDetector::update (shared_ptr< Context > context) override virtual
Implements fl::audio::Detector.
Definition at line 118 of file key.cpp.hpp.
{
    // Get fft::FFT data
    mRetainedFFT = context->getFFT(32);  // Use more bins for better pitch resolution
    const fft::Bins& fft = *mRetainedFFT;
    u32 timestamp = context->getTimestamp();
    // Extract chroma features
    float chroma[12] = {0};
    extractChroma(fft, chroma);
    normalizeChroma(chroma);
    // Update temporal averaging
    updateChromaHistory(chroma);
    // Get averaged chroma for stable detection
    float avgChroma[12] = {0};
    getAveragedChroma(avgChroma);
    // Detect key from averaged chroma
    Key detectedKey = detectKey(avgChroma, timestamp);
    // Update key duration if same key
    if (mKeyActive && detectedKey == mCurrentKey) {
        mCurrentKey.duration = timestamp - mKeyStartTime;
    }
    // Check for key change
    if (detectedKey != mCurrentKey) {
        // Only accept key change if:
        // 1. Confidence is above threshold
        // 2. Previous key was held for minimum duration OR new key is much stronger
        bool acceptChange = false;
        if (detectedKey.confidence >= mConfidenceThreshold) {
            if (!mKeyActive) {
                // No previous key, accept new key
                acceptChange = true;
            } else if (mCurrentKey.duration >= mMinKeyDuration) {
                // Previous key held long enough, allow change
                acceptChange = true;
            } else if (detectedKey.confidence > mCurrentKey.confidence * 1.2f) {
                // New key is significantly stronger, allow early change
                acceptChange = true;
            }
        }
        if (acceptChange) {
            mPreviousKey = mCurrentKey;
            mCurrentKey = detectedKey;
            mKeyStartTime = timestamp;
            mKeyActive = true;
            FL_DBG("Key change: " << mCurrentKey.getRootName() << " "
                   << mCurrentKey.getQuality() << " (confidence: "
                   << mCurrentKey.confidence << ")");
            mFireKeyChange = true;
        }
    }
    // Check for key end (confidence drop)
    if (mKeyActive && detectedKey.confidence < mConfidenceThreshold * 0.5f) {
        FL_DBG("Key ended: " << mCurrentKey.getRootName() << " " << mCurrentKey.getQuality());
        mFireKeyEnd = true;
        mKeyActive = false;
        mCurrentKey.confidence = 0.0f;
    }
    // Set onKey flag every frame if key is active
    if (mKeyActive) mFireKey = true;
}
References fl::audio::detector::Key::confidence, detectKey(), extractChroma(), FL_DBG, getAveragedChroma(), mConfidenceThreshold, mCurrentKey, mFireKey, mFireKeyChange, mFireKeyEnd, mKeyActive, mKeyStartTime, mMinKeyDuration, mPreviousKey, mRetainedFFT, normalizeChroma(), and updateChromaHistory().
Referenced by ~KeyDetector().