FastLED: fl::audio::detector::KeyDetector::detectKey
detectKey()
Key fl::audio::detector::KeyDetector::detectKey (const float * chroma, u32 timestamp) private
Definition at line 303 of file key.cpp.hpp.
{
    float bestCorrelation = -1.0f;
    u8 bestRoot = 0;
    bool bestIsMinor = false;
    // Try all 24 possible keys (12 major + 12 minor)
    for (int root = 0; root < 12; root++) {
        // Try major key
        float majorCorr = correlateWithProfile(chroma, MAJOR_PROFILE, root);
        if (majorCorr > bestCorrelation) {
            bestCorrelation = majorCorr;
            bestRoot = root;
            bestIsMinor = false;
        }
        // Try minor key
        float minorCorr = correlateWithProfile(chroma, MINOR_PROFILE, root);
        if (minorCorr > bestCorrelation) {
            bestCorrelation = minorCorr;
            bestRoot = root;
            bestIsMinor = true;
        }
    }
    // Convert correlation to 0-1 confidence
    // Correlation ranges from -1 to 1, but we typically see 0.5-0.9 for good matches
    float confidence = (bestCorrelation + 1.0f) / 2.0f;  // Map [-1,1] to [0,1]
    confidence = fl::max(0.0f, fl::min(1.0f, confidence));
    return Key(bestRoot, bestIsMinor, confidence, timestamp);
}
References correlateWithProfile(), MAJOR_PROFILE, fl::max(), fl::min(), and MINOR_PROFILE.
Referenced by update().