FastLED: fl::audio::detector::FrequencyBands::update
update()
void fl::audio::detector::FrequencyBands::update (shared_ptr< Context > context) override virtual
Implements fl::audio::Detector.
Definition at line 45 of file frequency_bands.cpp.hpp.
{
    // Use sample rate from context if available
    mSampleRate = context->getSampleRate();
    // Use shared master fft::FFT via context (downsampled to our config)
    mRetainedFFT = context->getFFT(kNumBands, kFFTMinFreq, kFFTMaxFreq);
    const fft::Bins& fftBins = *mRetainedFFT;
    sFrequencyBandsFFTCount++;  // Diagnostic counter (no private fft::FFT anymore)
    span<const i16> pcm = context->getPCM();
    // Calculate energy for each band using fractional bin overlap
    float bassEnergy = calculateBandEnergy(fftBins, mBassMin, mBassMax, kFFTMinFreq, kFFTMaxFreq);
    float midEnergy = calculateBandEnergy(fftBins, mMidMin, mMidMax, kFFTMinFreq, kFFTMaxFreq);
    float trebleEnergy = calculateBandEnergy(fftBins, mTrebleMin, mTrebleMax, kFFTMinFreq, kFFTMaxFreq);
    // Compute dt from actual audio buffer duration: pcmSize / sampleRate
    const float dt = computeAudioDt(pcm.size(), mSampleRate);
    mBass = mBassSmoother.update(bassEnergy, dt);
    mMid = mMidSmoother.update(midEnergy, dt);
    mTreble = mTrebleSmoother.update(trebleEnergy, dt);
    // Per-band normalization — mirrors EnergyAnalyzer pattern
    auto normalizeBand = [](float val, AttackDecayFilter<float>& filter,
                            float frameDt) -> float {
        float runningMax = filter.update(val, frameDt);
        if (runningMax < 0.001f) runningMax = 0.001f;
        return fl::min(1.0f, val / runningMax);
    };
    mBassNorm = normalizeBand(mBass, mBassMaxFilter, dt);
    mMidNorm = normalizeBand(mMid, mMidMaxFilter, dt);
    mTrebleNorm = normalizeBand(mTreble, mTrebleMaxFilter, dt);
}
References FrequencyBands(), calculateBandEnergy(), fl::audio::computeAudioDt(), mBass, mBassMax, mBassMaxFilter, mBassMin, mBassNorm, mBassSmoother, fl::min(), mMid, mMidMax, mMidMaxFilter, mMidMin, mMidNorm, mMidSmoother, mRetainedFFT, mSampleRate, mTreble, mTrebleMax, mTrebleMaxFilter, mTrebleMin, mTrebleNorm, mTrebleSmoother, fl::audio::detector::sFrequencyBandsFFTCount, fl::span< T, Extent >::size(), and update().
Referenced by ~FrequencyBands(), and update().