FastLED: fl::Grid::reset
reset()
template<typename T> void fl::Grid< T >::reset (uint32_t width, uint32_t height) inline
Definition at line 15 of file grid.h.
{
        clear();
        if (width != mWidth || height != mHeight) {
            mWidth = width;
            mHeight = height;
            mData.resize(width * height);
        }
        mSlice = fl::MatrixSlice<T>(mData.data(), width, height, 0, 0,
                                    width, height);
    }
References clear(), height(), mData, mHeight, mSlice, mWidth, and width().
Referenced by Grid().