FastLED: setup
setup()
void setup ()
Definition at line 160 of file old.h.
             {
    pinMode(PIN_GRND, OUTPUT);
    digitalWrite(PIN_GRND, LOW); // Set ground pin to low
    button.addRealButton(Button(PIN_BUTTON));
    screenMap = makeScreenMap(args);
    //screenMap = ScreenMap::Circle(NUM_LEDS, 1.5f, 0.5f, 1.0f);
    auto controller = addController();
    // Set the screen map for the controller
    controller->setScreenMap(screenMap);
    // Set power management. This allows this festival stick to conformatable
    // run on any USB battery that can output at least 1A at 5V.
    // Keep in mind that this sketch is designed to use APA102HD mode, which will
    // result in even lowwer run power consumption, since the power mode does not take
    // into account the APA102HD gamma correction. However it is still a correct upper bound
    // that will match the ledset exactly when the display tries to go full white.
    FastLED.setMaxPowerInVoltsAndMilliamps(VOLTS, MAX_AMPS * 1000);
    // set brightness 8
    FastLED.setBrightness(brightness.as_int());
    button.onChanged([](UIButton& but) {
        // This function is called when the button is pressed
        // If the button is pressed, show the generative pattern
        if (but.isPressed()) {
            FASTLED_WARN("Button pressed");
        } else {
            FASTLED_WARN("NOT Button pressed");
        }
    });
}
References addController(), args, brightness(), button(), controller, FastLED, FASTLED_WARN, fl::UIButton::isPressed(), makeScreenMap(), MAX_AMPS, PIN_BUTTON, PIN_GRND, screenMap, and VOLTS.