FastLED: makeCorkScrew
makeCorkScrew()
fl::vector< vec3f > makeCorkScrew (corkscrew_args args = corkscrew_args())
Definition at line 66 of file old.h.
{
    // int num_leds, float leds_per_turn, float width_cm
    int num_leds = args.num_leds;
    float leds_per_turn = args.leds_per_turn;
    float width_cm = args.width_cm;
    const float circumference = leds_per_turn;
    const float radius = circumference / (2.0 * FL_PI);      // radius in mm
    const float angle_per_led = 2.0 * FL_PI / leds_per_turn; // degrees per LED
    const float total_angle_radians = angle_per_led * num_leds;
    const float total_turns = total_angle_radians / (2.0 * FL_PI); // total turns
    const float height_per_turn_cm = width_cm; // 10cm height per turn
    const float height_per_led =
        height_per_turn_cm /
        leds_per_turn; // this is the changing height per led.
    const float total_height =
        height_per_turn_cm * total_turns; // total height of the corkscrew
    fl::vector<vec3f> out;
    for (int i = 0; i < num_leds; i++) {
        float angle = i * angle_per_led; // angle in radians
        float height = (i / leds_per_turn) * height_per_turn_cm; // height in cm
        // Calculate the x, y, z coordinates for the corkscrew
        float x = radius * fl::cos(angle); // x coordinate
        float z = radius * fl::sin(angle); // y coordinate
        float y = height;              // z coordinate
        // Store the 3D coordinates in the fl::vector
        vec3f led_position(x, y, z);
        // screenMap.set(i, led_position);
        out.push_back(led_position);
    }
    return out;
}
References args, fl::cos(), FL_PI, fl::vector< T >::push_back(), fl::sin(), x, y, and z.