FastLED: fl::test::TestContext::matchesFilter
matchesFilter()
bool fl::test::TestContext::matchesFilter (const char * name, const char * filter) const private
Definition at line 161 of file fltest.cpp.hpp.
{
    if (!filter || filter[0] == '\0') {
        return true;  // No filter means match all
    }
    // Simple wildcard matching: * matches any sequence, ? matches one char
    const char* n = name;
    const char* f = filter;
    // Check if filter contains wildcards
    bool hasWildcards = false;
    for (const char* p = filter; *p; ++p) {
        if (*p == '*' || *p == '?') {
            hasWildcards = true;
            break;
        }
    }
    if (!hasWildcards) {
        // No wildcards - do substring match
        while (*n) {
            const char* nn = n;
            const char* ff = filter;
            while (*nn && *ff && *nn == *ff) {
                ++nn;
                ++ff;
            }
            if (*ff == '\0') {
                return true;  // Found substring match
            }
            ++n;
        }
        return false;
    }
    // Wildcard matching using recursion simulation with stack
    while (*f) {
        if (*f == '*') {
            ++f;
            if (*f == '\0') {
                return true;  // Trailing * matches everything
            }
            // Try matching remaining pattern at each position
            while (*n) {
                if (matchesFilter(n, f)) {
                    return true;
                }
                ++n;
            }
            return false;
        } else if (*f == '?') {
            if (*n == '\0') {
                return false;  // ? needs a character to match
            }
            ++f;
            ++n;
        } else {
            if (*n != *f) {
                return false;  // Literal mismatch
            }
            ++f;
            ++n;
        }
    }
    return *n == '\0';  // Both must be exhausted
}
References FL_NOEXCEPT, and matchesFilter().
Referenced by listTests(), matchesFilter(), and run().