FastLED: animartrix_detail::ANIMartRIX::Hot_Blob
Hot_Blob()
void animartrix_detail::ANIMartRIX::Hot_Blob () inline
Definition at line 1389 of file animartrix_detail.hpp.
                    { // nice one
        get_ready();
        run_default_oscillators(0.001);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y];
                animation.angle = polar_theta[x][y];
                animation.scale_x = 0.07 + move.directional[0] * 0.002;
                animation.scale_y = 0.07;
                animation.offset_y = -move.linear[0];
                animation.offset_x = 0;
                animation.offset_z = 0;
                animation.z = 0;
                animation.low_limit = -1;
                float show1 = render_value(animation);
                animation.offset_y = -move.linear[1];
                float show3 = render_value(animation);
                animation.offset_x = show3 / 20;
                animation.offset_y = -move.linear[0] / 2 + show1 / 70;
                animation.low_limit = 0;
                float show2 = render_value(animation);
                animation.offset_x = show3 / 20;
                animation.offset_y = -move.linear[0] / 2 + show1 / 70;
                animation.z = 100;
                float show4 = render_value(animation);
                float radius = radial_filter_radius; // radius of a radial
                                                     // brightness filter
                float radial = (radius - animation.dist) / animation.dist;
                float linear = (y + 1) / (num_y - 1.f);
                pixel.red = radial * show2;
                pixel.green = linear * radial * 0.3 * (show2 - show4);
                pixel.blue = 0;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animation, distance, get_ready(), move, num_x, num_y, pixel, polar_theta, radial_filter_radius, render_value(), rgb_sanity_check(), run_default_oscillators(), setPixelColorInternal(), show1, show2, show3, show4, x, and y.