FastLED: animartrix_detail::ANIMartRIX::Center_Field
Center_Field()
void animartrix_detail::ANIMartRIX::Center_Field () inline
Definition at line 733 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.01; // speed ratios for the oscillators
        timings.ratio[0] = 1;        // higher values = faster transitions
        timings.ratio[1] = 1.1;
        timings.ratio[2] = 1.2;
        timings.offset[1] = 100;
        timings.offset[2] = 200;
        timings.offset[3] = 300;
        calculate_oscillators(
            timings); // get linear movers and oscillators going
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                // describe and render animation layers
                animation.angle = polar_theta[x][y];
                animation.scale_x = 0.07;
                animation.scale_y = 0.07;
                animation.scale_z = 0.1;
                animation.dist = 5 * sqrtf(distance[x][y]);
                animation.offset_y = move.linear[0];
                animation.offset_x = 0;
                animation.z = 0;
                float show1 = render_value(animation);
                animation.angle = polar_theta[x][y];
                animation.scale_x = 0.07;
                animation.scale_y = 0.07;
                animation.scale_z = 0.1;
                animation.dist = 4 * sqrtf(distance[x][y]);
                animation.offset_y = move.linear[0];
                animation.offset_x = 0;
                animation.z = 0;
                float show2 = render_value(animation);
                // colormapping
                pixel.red = show1;
                pixel.green = show2;
                pixel.blue = 0;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animation, calculate_oscillators(), distance, get_ready(), move, num_x, num_y, pixel, polar_theta, render_value(), rgb_sanity_check(), setPixelColorInternal(), show1, show2, timings, x, and y.