FastLED: animartrix_detail::ANIMartRIX::Yves
Yves()
void animartrix_detail::ANIMartRIX::Yves () inline
Definition at line 1174 of file animartrix_detail.hpp.
                {
        get_ready();
        a = micros(); // for time measurement in report_performance()
        timings.master_speed = 0.001; // speed ratios for the oscillators
        timings.ratio[0] = 3;         // higher values = faster transitions
        timings.ratio[1] = 2;
        timings.ratio[2] = 1;
        timings.ratio[3] = 0.13;
        timings.ratio[4] = 0.15;
        timings.ratio[5] = 0.03;
        timings.ratio[6] = 0.025;
        timings.offset[0] = 0;
        timings.offset[1] = 100;
        timings.offset[2] = 200;
        timings.offset[3] = 300;
        timings.offset[4] = 400;
        timings.offset[5] = 500;
        timings.offset[6] = 600;
        calculate_oscillators(
            timings); // get linear movers and oscillators going
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                animation.dist = distance[x][y];
                animation.angle =
                    polar_theta[x][y] + 2 * PI + move.noise_angle[5];
                animation.scale_x = 0.08;
                animation.scale_y = 0.08;
                animation.scale_z = 0.08;
                animation.offset_y = -move.linear[0];
                animation.offset_x = 0;
                animation.offset_z = 0;
                animation.z = 0;
                float show1 = render_value(animation);
                animation.dist = distance[x][y];
                animation.angle =
                    polar_theta[x][y] + 2 * PI + move.noise_angle[6];
                ;
                animation.scale_x = 0.08;
                animation.scale_y = 0.08;
                animation.scale_z = 0.08;
                animation.offset_y = -move.linear[1];
                animation.offset_x = 0;
                animation.offset_z = 0;
                animation.z = 0;
                float show2 = render_value(animation);
                animation.angle = polar_theta[x][y] + show1 / 100 +
                                  move.noise_angle[3] + move.noise_angle[4];
                animation.dist = distance[x][y] + show2 / 50;
                animation.offset_y = -move.linear[2];
                animation.offset_y += show1 / 100;
                animation.offset_x += show2 / 100;
                float show3 = render_value(animation);
                animation.offset_y = 0;
                animation.offset_x = 0;
                float show4 = render_value(animation);
                pixel.red = show3;
                pixel.green = show3 * show4 / 255;
                pixel.blue = 0;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(y, x, pixel);
            }
        }
    }
References a, animation, calculate_oscillators(), distance, get_ready(), move, num_x, num_y, PI, pixel, polar_theta, render_value(), rgb_sanity_check(), setPixelColorInternal(), show1, show2, show3, show4, timings, x, and y.