FastLED: animartrix_detail::ANIMartRIX::Parametric_Water
Parametric_Water()
void animartrix_detail::ANIMartRIX::Parametric_Water () inline
Definition at line 3313 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.003; // master speed
        timings.ratio[0] = 0.025; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[1] = 0.027;
        timings.ratio[2] = 0.029;
        timings.ratio[3] = 0.033; // speed ratios for the oscillators, higher
                                  // values = faster transitions
        timings.ratio[4] = 0.037;
        timings.ratio[5] = 0.15; // wave speed
        timings.ratio[6] = 0.41;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                float s = 4;
                float f = 10 + 2 * move.directional[0];
                animation.dist = (f + move.directional[0]) *
                                 sinf(-move.radial[5] + move.radial[0] +
                                      (distance[x][y] / (s)));
                animation.angle = 1 * polar_theta[x][y];
                animation.z = 5;
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.offset_z = -10;
                animation.offset_y = 20 * move.linear[0];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show2 = render_value(animation);
                animation.dist = (f + move.directional[1]) *
                                 sinf(-move.radial[5] + move.radial[1] +
                                      (distance[x][y] / (s)));
                animation.angle = 1 * polar_theta[x][y];
                animation.z = 500;
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.offset_z = -10;
                animation.offset_y = 20 * move.linear[1];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show3 = render_value(animation);
                animation.dist = (f + move.directional[2]) *
                                 sinf(-move.radial[5] + move.radial[2] +
                                      (distance[x][y] / (s)));
                animation.angle = 1 * polar_theta[x][y];
                animation.z = 5000;
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.offset_z = -10;
                animation.offset_y = 20 * move.linear[2];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show4 = render_value(animation);
                animation.dist = (f + move.directional[3]) *
                                 sinf(-move.radial[5] + move.radial[3] +
                                      (distance[x][y] / (s)));
                animation.angle = 1 * polar_theta[x][y];
                animation.z = 2000;
                animation.scale_x = 0.1;
                animation.scale_y = 0.1;
                animation.offset_z = -10;
                animation.offset_y = 20 * move.linear[3];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show5 = render_value(animation);
                show6 = screen(show4, show5);
                show7 = screen(show2, show3);
                float radius = 40; // radius of a radial brightness filter
                float radial = (radius - distance[x][y]) / radius;
                // pixel.red    = show6;
                // pixel.blue = show7;
                pixel.red = pixel.blue - 40;
                pixel.green = 0;
                pixel.blue = (0.3 * show6 + 0.7 * show7) * radial;
                pixel = rgb_sanity_check(pixel);
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References animation, calculate_oscillators(), distance, get_ready(), move, num_x, num_y, pixel, polar_theta, render_value(), rgb_sanity_check(), screen(), setPixelColorInternal(), show2, show3, show4, show5, show6, show7, timings, x, and y.