FastLED: animartrix_detail::ANIMartRIX::Module_Experiment10
Module_Experiment10()
void animartrix_detail::ANIMartRIX::Module_Experiment10 () inline
Definition at line 3985 of file animartrix_detail.hpp.
{
        get_ready();
        timings.master_speed = 0.01; // master speed 0.031
        float w = 1;
        timings.ratio[0] = 0.01; // speed ratios for the oscillators, higher
                                 // values = faster transitions
        timings.ratio[1] = 0.011;
        timings.ratio[2] = 0.013;
        timings.ratio[3] = 0.33 * w;
        timings.ratio[4] = 0.36 * w; // speed ratios for the oscillators, higher
                                     // values = faster transitions
        timings.ratio[5] = 0.38 * w;
        timings.ratio[6] = 0.0003; // master rotation
        timings.offset[0] = 0;
        timings.offset[1] = 100;
        timings.offset[2] = 200;
        timings.offset[3] = 300;
        timings.offset[4] = 400;
        timings.offset[5] = 500;
        timings.offset[6] = 600;
        calculate_oscillators(timings);
        for (int x = 0; x < num_x; x++) {
            for (int y = 0; y < num_y; y++) {
                float s = 0.4; // scale
                float r = 1.5; // scroll speed
                animation.dist =
                    3 + distance[x][y] +
                    3 * FL_SIN_F(0.25 * distance[x][y] - move.radial[3]);
                animation.angle = polar_theta[x][y] + move.noise_angle[0] +
                                  move.noise_angle[6];
                animation.z = 5;
                animation.scale_x = 0.1 * s;
                animation.scale_y = 0.1 * s;
                animation.offset_z = 10 * move.linear[0];
                animation.offset_y = -5 * r * move.linear[0];
                animation.offset_x = 10;
                animation.low_limit = 0;
                show1 = render_value(animation);
                animation.dist =
                    4 + distance[x][y] +
                    4 * FL_SIN_F(0.24 * distance[x][y] - move.radial[4]);
                animation.angle = polar_theta[x][y] + move.noise_angle[1] +
                                  move.noise_angle[6];
                animation.z = 5;
                animation.scale_x = 0.1 * s;
                animation.scale_y = 0.1 * s;
                animation.offset_z = 0.1 * move.linear[1];
                animation.offset_y = -5 * r * move.linear[1];
                animation.offset_x = 100;
                animation.low_limit = 0;
                show2 = render_value(animation);
                animation.dist =
                    5 + distance[x][y] +
                    5 * FL_SIN_F(0.23 * distance[x][y] - move.radial[5]);
                animation.angle = polar_theta[x][y] + move.noise_angle[2] +
                                  move.noise_angle[6];
                animation.z = 5;
                animation.scale_x = 0.1 * s;
                animation.scale_y = 0.1 * s;
                animation.offset_z = 0.1 * move.linear[2];
                animation.offset_y = -5 * r * move.linear[2];
                animation.offset_x = 1000;
                animation.low_limit = 0;
                show3 = render_value(animation);
                show4 = colordodge(show1, show2);
                float rad = FL_SIN_F(PI / 2 +
                                 distance[x][y] / 14); // better radial filter?!
                /*
                pixel.red    = show1;
                pixel.green  = show1 * 0.3;
                pixel.blue   = show2-show1;
                */
                CHSV(rad * ((show1 + show2) + show3), 255, 255);
                pixel = rgb_sanity_check(pixel);
                uint8_t a = getTime() / 100;
                CRGB p = CRGB(CHSV(((a + show1 + show2) + show3), 255, 255));
                rgb pixel;
                pixel.red = p.red;
                pixel.green = p.green;
                pixel.blue = p.blue;
                setPixelColorInternal(x, y, pixel);
            }
        }
    }
References a, animation, calculate_oscillators(), colordodge(), distance, FL_SIN_F, get_ready(), getTime(), move, num_x, num_y, PI, pixel, polar_theta, render_value(), rgb_sanity_check(), setPixelColorInternal(), show1, show2, show3, show4, timings, x, and y.