FastLED: animartrix_detail::ANIMartRIX::init
init()
void animartrix_detail::ANIMartRIX::init (int w, int h) inline
Definition at line 184 of file animartrix_detail.hpp.
{
        animation = render_parameters();
        timings = oscillators();
        move = modulators();
        pixel = rgb();
        this->num_x = w;
        this->num_y = h;
        if (w <= 16) {
            this->radial_filter_radius = 11;
        } else {
            this->radial_filter_radius = 23; // on 32x32, use 11 for 16x16
        }
        render_polar_lookup_table(
            (num_x / 2) - 0.5,
            (num_y / 2) - 0.5); // precalculate all polar coordinates
                                // polar origin is set to matrix centre
        // set default speed ratio for the oscillators, not all effects set
        // their own, so start from know state
        timings.master_speed = 0.01;
    }
References animation, move, num_x, num_y, pixel, render_polar_lookup_table(), and timings.
Referenced by ANIMartRIX(), and fl::FastLEDANIMartRIX::FastLEDANIMartRIX().