FastLED: animartrix_detail::ANIMartRIX::rgb_sanity_check
rgb_sanity_check()
rgb animartrix_detail::ANIMartRIX::rgb_sanity_check (rgb & pixel) inline
Definition at line 433 of file animartrix_detail.hpp.
{
        // rescue data if possible, return absolute value
        // if (pixel.red < 0)     pixel.red = fabsf(pixel.red);
        // if (pixel.green < 0) pixel.green = fabsf(pixel.green);
        // if (pixel.blue < 0)   pixel.blue = fabsf(pixel.blue);
        // Can never be negative colour
        if (pixel.red < 0)
            pixel.red = 0;
        if (pixel.green < 0)
            pixel.green = 0;
        if (pixel.blue < 0)
            pixel.blue = 0;
        // discard everything above the valid 8 bit colordepth 0-255 range
        if (pixel.red > 255)
            pixel.red = 255;
        if (pixel.green > 255)
            pixel.green = 255;
        if (pixel.blue > 255)
            pixel.blue = 255;
        return pixel;
    }
References pixel.
Referenced by Big_Caleido(), Caleido1(), Caleido2(), Caleido3(), Center_Field(), Chasing_Spirals(), Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Complex_Kaleido_4(), Complex_Kaleido_5(), Complex_Kaleido_6(), Distance_Experiment(), Hot_Blob(), Lava1(), Module_Experiment1(), Module_Experiment10(), Module_Experiment2(), Module_Experiment3(), Module_Experiment4(), Module_Experiment5(), Module_Experiment6(), Module_Experiment7(), Module_Experiment8(), Module_Experiment9(), Parametric_Water(), Polar_Waves(), RGB_Blobs(), RGB_Blobs2(), RGB_Blobs3(), RGB_Blobs4(), RGB_Blobs5(), Rings(), Rotating_Blob(), Scaledemo1(), Slow_Fade(), SM1(), SM10(), SM2(), SM3(), SM4(), SM5(), SM6(), SM8(), SM9(), Spiralus(), Spiralus2(), Water(), Waves(), Yves(), Zoom(), and Zoom2().