FastLED: animartrix_detail::ANIMartRIX::screen
screen()
float animartrix_detail::ANIMartRIX::screen (float & a, float & b) inline
Definition at line 233 of file animartrix_detail.hpp.
{
        return (1 - (1 - a / 255.f) * (1 - b / 255.f)) * 255.f;
    }
References a, and b.
Referenced by Complex_Kaleido(), Complex_Kaleido_2(), Complex_Kaleido_3(), Parametric_Water(), SM10(), SM5(), SM6(), SM8(), and SM9().