FastLED: fl::format_detail::FormatArg::format
format()
fl::string fl::format_detail::FormatArg::format (const FormatSpec & spec) const inline
Definition at line 323 of file format.h.
{
        switch (mType) {
            case Type::Int:       return format_integer(mData.i, spec);
            case Type::UInt:      return format_integer(mData.u, spec);
            case Type::Long:      return format_integer(mData.l, spec);
            case Type::ULong:     return format_integer(mData.ul, spec);
            case Type::LongLong:  return format_integer(mData.ll, spec);
            case Type::ULongLong: return format_integer(mData.ull, spec);
            case Type::Double:    return format_float(mData.d, spec);
            case Type::Char: {
                if (spec.type == 'd' || spec.type == 'x' || spec.type == 'X' ||
                    spec.type == 'b' || spec.type == 'o') {
                    return format_integer(static_cast<int>(mData.c), spec);
                }
                char buf[2] = {mData.c, '\0'};
                return fl::string(buf);
            }
            case Type::CString:   return format_string(mData.s, spec);
            case Type::String:    return format_string(mData.str->c_str(), spec);
            case Type::Pointer:   return format_pointer(mData.p, spec);
            case Type::None:
            default:              return fl::string("<invalid>");
        }
    }
References Char, CString, Double, fl::format_detail::format_float(), fl::format_detail::format_integer(), fl::format_detail::format_pointer(), fl::format_detail::format_string(), Int, Long, LongLong, mData, mType, None, Pointer, String, fl::format_detail::FormatSpec::type, UInt, ULong, and ULongLong.