FastLED: fl::WaveSimulation2D::seti16
seti16()
void fl::WaveSimulation2D::seti16 (fl::size x, fl::size y, i16 value)
Definition at line 160 of file wave_simulation.cpp.hpp.
{
    if (!has(x, y))
        return;
    u8 mult = fl::max(1, mMultiplier);
    // radius in pixels of your diamond
    int rad = static_cast<int>(mult) / 2;
    for (fl::size j = 0; j < mult; ++j) {
        for (fl::size i = 0; i < mult; ++i) {
            // compute offset from the center of this block
            int dx = static_cast<int>(i) - rad;
            int dy = static_cast<int>(j) - rad;
            // keep only those points whose Manhattan distance ≤ rad
            if (fl::abs(dx) + fl::abs(dy) > rad) {
                continue;
            }
            fl::size xx = x * mult + i;
            fl::size yy = y * mult + j;
            if (mSim->has(xx, yy)) {
                if (mUseChangeGrid) {
                    i16 &pt = mChangeGrid.at(xx, yy);
                    if (pt == 0) {
                        // not set yet so set unconditionally.
                        pt = v16;
                    } else {
                        const bool sign_matches = (pt >= 0) == (v16 >= 0);
                        if (!sign_matches) {
                            // opposite signs, so overwrite
                            pt = v16;
                        } else {
                            // if the magnitude of the new pt is greater than what
                            // was already there, then overwrite.
                            u16 abs_pt = static_cast<u16>(fl::abs(pt));
                            u16 abs_v16 = static_cast<u16>(fl::abs(v16));
                            if (abs_v16 > abs_pt) {
                                pt = v16;
                            }
                        }
                    }
                } else {
                    // Directly set the value in the simulation when change grid is disabled
                    mSim->seti16(xx, yy, v16);
                }
            }
        }
    }
}
References fl::abs(), has(), fl::max(), mChangeGrid, mMultiplier, mSim, mUseChangeGrid, fl::x, and fl::y.
Referenced by setf().