FastLED: fl::WaveSimulation2D::geti16
geti16()
int16_t fl::WaveSimulation2D::geti16 (size_t x, size_t y) const
Definition at line 74 of file wave_simulation.cpp.
{
    if (!has(x, y))
        return 0;
    int32_t sum = 0;
    uint8_t mult = MAX(1, mMultiplier);
    for (uint32_t j = 0; j < mult; ++j) {
        for (uint32_t i = 0; i < mult; ++i) {
            uint32_t xx = x * mult + i;
            uint32_t yy = y * mult + j;
            int32_t pt = mSim->geti16(xx, yy);
            // int32_t ch_pt = mChangeGrid[(yy * mMultiplier) + xx];
            int32_t ch_pt = mChangeGrid(xx, yy);
            if (ch_pt != 0) { // we got a hit.
                sum += ch_pt;
            } else {
                sum += pt;
            }
        }
    }
    int16_t out = static_cast<int16_t>(sum / (mult * mult));
    return out;
}
References has(), MAX, mChangeGrid, mMultiplier, mSim, x, and y.
Referenced by geti16All(), geti8(), and getu8().