FastLED: fl::Tile2x2_u8_wrap::Tile2x2_u8_wrap
Tile2x2_u8_wrap() [3/4]
fl::Tile2x2_u8_wrap::Tile2x2_u8_wrap (const Tile2x2_u8 & from, u16 width, u16 height)
Definition at line 88 of file tile2x2.cpp.hpp.
{
    const vec2<u16> origin = from.origin();
    at(0, 0) = {wrap(vec2<u16>(origin.x, origin.y), vec2<u16>(width, height)),
                from.at(0, 0)};
    at(0, 1) = {wrap(vec2<u16>(origin.x, origin.y + 1), vec2<u16>(width, height)),
                from.at(0, 1)};
    at(1, 0) = {wrap(vec2<u16>(origin.x + 1, origin.y), vec2<u16>(width, height)),
                from.at(1, 0)};
    at(1,
       1) = {wrap(vec2<u16>(origin.x + 1, origin.y + 1), vec2<u16>(width, height)),
             from.at(1, 1)};
}
References fl::Tile2x2_u8::at(), at(), fl::height, fl::Tile2x2_u8::origin(), fl::width, fl::vec2< T >::x, and fl::vec2< T >::y.