FastLED: fl::third_party::Mp3HelixDecoder::decode
decode()
template<typename Fn> int fl::third_party::Mp3HelixDecoder::decode (const fl::u8 * data, fl::size len, Fn on_frame) inline
Definition at line 64 of file mp3.h.
{
            if (!mDecoder) {
                return 0;
            }
            const fl::u8* inptr = data;
            fl::size bytes_left = len;
            int frames_decoded = 0;
            while (bytes_left > 0) {
                // Find sync word
                int offset = findSyncWord(inptr, bytes_left);
                if (offset < 0) {
                    break;  // No sync word found
                }
                inptr += offset;
                bytes_left -= offset;
                // Decode one frame
                int result = decodeFrame(&inptr, &bytes_left);
                if (result == 0) {
                    // Successfully decoded a frame
                    Mp3Frame frame;
                    frame.pcm = mPcmBuffer.get();
                    frame.samples = mFrameInfo.outputSamps / mFrameInfo.nChans;
                    frame.channels = mFrameInfo.nChans;
                    frame.sample_rate = mFrameInfo.samprate;
                    frame.bitrate = mFrameInfo.bitrate;
                    frame.version = mFrameInfo.version;
                    frame.layer = mFrameInfo.layer;
                    on_frame(frame);
                    frames_decoded++;
                } else if (result < 0) {
                    // Decode error - skip a bit and try again
                    if (bytes_left > 0) {
                        inptr++;
                        bytes_left--;
                    }
                }
            }
            return frames_decoded;
        }
References fl::third_party::Mp3Frame::bitrate, fl::third_party::Mp3Frame::channels, decodeFrame(), findSyncWord(), fl::third_party::Mp3Frame::layer, mDecoder, mFrameInfo, mPcmBuffer, offset(), fl::third_party::Mp3Frame::pcm, fl::third_party::Mp3Frame::sample_rate, fl::third_party::Mp3Frame::samples, and fl::third_party::Mp3Frame::version.
Referenced by decodeToAudioSamples().