FastLED: fl::third_party::Mp3HelixDecoder::decodeFrame
decodeFrame()
int fl::third_party::Mp3HelixDecoder::decodeFrame (const fl::u8 ** inbuf, fl::size * bytes_left)
Definition at line 65 of file mp3.cpp.hpp.
{
    if (!mDecoder || !mPcmBuffer) {
        return ERR_MP3_NULL_POINTER;
    }
    // Decode one frame
    int result = MP3Decode(
        static_cast<HMP3Decoder>(mDecoder),
        inbuf,
        bytes_left,
        fl::bit_cast<short*>(mPcmBuffer.get()),
        0  // useSize = 0 (use default)
    );
    if (result == ERR_MP3_NONE) {
        // Get frame info
        MP3FrameInfo helix_info;
        MP3GetLastFrameInfo(static_cast<HMP3Decoder>(mDecoder), &helix_info);
        mFrameInfo.bitrate = helix_info.bitrate;
        mFrameInfo.nChans = helix_info.nChans;
        mFrameInfo.samprate = helix_info.samprate;
        mFrameInfo.bitsPerSample = helix_info.bitsPerSample;
        mFrameInfo.outputSamps = helix_info.outputSamps;
        mFrameInfo.layer = helix_info.layer;
        mFrameInfo.version = helix_info.version;
    }
    return result;
}
References fl::bit_cast(), _MP3FrameInfo::bitrate, _MP3FrameInfo::bitsPerSample, ERR_MP3_NONE, ERR_MP3_NULL_POINTER, _MP3FrameInfo::layer, mDecoder, mFrameInfo, fl::third_party::MP3Decode(), fl::third_party::MP3GetLastFrameInfo(), mPcmBuffer, _MP3FrameInfo::nChans, _MP3FrameInfo::outputSamps, _MP3FrameInfo::samprate, and _MP3FrameInfo::version.
Referenced by decode(), and fl::Mp3::parseMp3Info().