FastLED: fl::audio::detector::Vibe::update
update()
void fl::audio::detector::Vibe::update (shared_ptr< Context > context) override virtual
Implements fl::audio::Detector.
Definition at line 45 of file vibe.cpp.hpp.
{
    if (!context) {
        return;
    }
    mFrameCount++;
    mSampleRate = context->getSampleRate();
    // --- Step 1: Get 3-band energy from shared context ---
    BandEnergy energy = context->getBandEnergy();
    sVibeFFTCount++;
    span<const i16> pcm = context->getPCM();
    // --- Step 2: Read bass/mid/treb directly ---
    mImm[0] = energy.bass;
    mImm[1] = energy.mid;
    mImm[2] = energy.treb;
    // --- Step 3: Temporal blending (MilkDrop v2.25c algorithm) ---
    // Compute effective FPS from audio buffer duration
    float dt = computeAudioDt(pcm.size(), mSampleRate);
    float actualFps = (dt > 0.0f) ? (1.0f / dt) : mTargetFps;
    if (mFrameCount == 1) {
        // MilkDrop first-frame initialization: set averages directly
        // Prevents false spikes and startup transients
        for (int i = 0; i < 3; i++) {
            mAvg[i] = mImm[i];
            mLongAvg[i] = mImm[i];
        }
    } else {
        // Pre-compute FPS-adjusted rates (avoids redundant powf in loop)
        float attackRate = adjustRateToFPS(0.2f, 30.0f, actualFps);
        float decayRate = adjustRateToFPS(0.5f, 30.0f, actualFps);
        float longRate = adjustRateToFPS(0.992f, 30.0f, actualFps);
        for (int i = 0; i < 3; i++) {
            // Short-term average: asymmetric attack/decay
            // Fast attack (rate=0.2 at 30fps → ~80% new signal on beats)
            // Slow decay  (rate=0.5 at 30fps → graceful fadeout)
            float rate = (mImm[i] > mAvg[i]) ? attackRate : decayRate;
            mAvg[i] = mAvg[i] * rate + mImm[i] * (1.0f - rate);
            // Long-term average: slow symmetric EMA (MilkDrop v2.25c algorithm)
            // Rate = 0.992 at 30fps → tau ≈ 4.2 seconds
            // Tracks the overall energy level for self-normalization.
            // Unlike a running maximum, this centers relative levels around 1.0,
            // giving beats proper excursions above 1.0 and quiet sections below 1.0.
            mLongAvg[i] = mLongAvg[i] * longRate + mAvg[i] * (1.0f - longRate);
        }
    }
    // --- Step 4: Self-normalizing relative levels ---
    // Division by long-term average makes levels independent of volume/genre.
    // Values hover around 1.0; >1 means louder than average, <1 means quieter.
    for (int i = 0; i < 3; i++) {
        if (mLongAvg[i] < 0.001f) {
            mImmRel[i] = 1.0f;
            mAvgRel[i] = 1.0f;
        } else {
            mImmRel[i] = mImm[i] / mLongAvg[i];
            mAvgRel[i] = mAvg[i] / mLongAvg[i];
        }
    }
    // --- Step 4b: Silence gate ---
    // MilkDrop's self-normalization drives mImmRel toward 1.0 when input is
    // silent (noise / noise → 1.0), and the < 0.001f clamp above also pins
    // to 1.0. Neither is what LED effects want when music stops. Route each
    // band through its SilenceEnvelope: pass-through during audio, exponential
    // decay toward 0 during silence. The Context::isSilent() flag is populated
    // by Processor/Reactive from NoiseFloorTracker. Re-uses dt computed above.
    const bool silent = context->isSilent();
    for (int i = 0; i < 3; i++) {
        mImmRel[i] = mImmRelEnv[i].update(silent, mImmRel[i], dt);
        mAvgRel[i] = mAvgRelEnv[i].update(silent, mAvgRel[i], dt);
    }
    // --- Step 5: Spike detection ---
    // When immediate exceeds smoothed, energy is rising — a beat is in progress.
    mPrevBassSpike = mBassSpike;
    mPrevMidSpike = mMidSpike;
    mPrevTrebSpike = mTrebSpike;
    mBassSpike = mImmRel[0] > mAvgRel[0];
    mMidSpike = mImmRel[1] > mAvgRel[1];
    mTrebSpike = mImmRel[2] > mAvgRel[2];
}
References Vibe(), adjustRateToFPS(), fl::audio::BandEnergy::bass, fl::audio::computeAudioDt(), mAvg, mAvgRel, mAvgRelEnv, mBassSpike, mFrameCount, fl::audio::BandEnergy::mid, mImm, mImmRel, mImmRelEnv, mLongAvg, mMidSpike, mPrevBassSpike, mPrevMidSpike, mPrevTrebSpike, mSampleRate, mTargetFps, mTrebSpike, fl::span< T, Extent >::size(), fl::audio::detector::sVibeFFTCount, fl::audio::BandEnergy::treb, and update().
Referenced by ~Vibe(), and update().