FastLED: fl::third_party::Mp3HelixDecoder::init
init()
bool fl::third_party::Mp3HelixDecoder::init ()
Definition at line 27 of file mp3.cpp.hpp.
{
    if (mDecoder) {
        return true;  // Already initialized
    }
    // Initialize Helix decoder
    mDecoder = MP3InitDecoder();
    if (!mDecoder) {
        return false;
    }
    // Allocate PCM buffer
    mPcmBuffer.reset(new fl::i16[MAX_PCM_SAMPLES]);  // ok bare allocation (array new)
    if (!mPcmBuffer) {
        MP3FreeDecoder(static_cast<HMP3Decoder>(mDecoder));
        mDecoder = nullptr;
        return false;
    }
    return true;
}
References fl::third_party::MAX_PCM_SAMPLES, mDecoder, fl::third_party::MP3FreeDecoder(), fl::third_party::MP3InitDecoder(), and mPcmBuffer.
Referenced by fl::Mp3::parseMp3Info().