FastLED: fl::third_party::Mp3HelixDecoder::reset
reset()
void fl::third_party::Mp3HelixDecoder::reset ()
Definition at line 49 of file mp3.cpp.hpp.
{
    if (mDecoder) {
        MP3FreeDecoder(static_cast<HMP3Decoder>(mDecoder));
        mDecoder = nullptr;
    }
    mPcmBuffer.reset();
    fl::memset(&mFrameInfo, 0, sizeof(mFrameInfo));
}
References mDecoder, fl::memset(), mFrameInfo, fl::third_party::MP3FreeDecoder(), and mPcmBuffer.
Referenced by ~Mp3HelixDecoder().