FastLED: fl::format_detail::format_pointer
format_pointer()
fl::string fl::format_detail::format_pointer (const void * ptr, const FormatSpec & spec) inline
Definition at line 273 of file format.h.
{
    fl::uptr addr = fl::ptr_to_int(const_cast<void*>(ptr));
    FormatSpec hex_spec = spec;
    hex_spec.type = 'x';
    hex_spec.alternate = true;
    return format_integer(addr, hex_spec);
}
References fl::format_detail::FormatSpec::alternate, format_integer(), fl::ptr_to_int(), and fl::format_detail::FormatSpec::type.
Referenced by fl::format_detail::FormatArg::format().