FastLED: fl::format_detail::format_impl
format_impl()
fl::string fl::format_detail::format_impl (const char * fmt, const FormatArg * args, int num_args) inline
Definition at line 368 of file format.h.
{
    fl::string result;
    const char* p = fmt;
    int auto_index = 0;
    while (*p) {
        if (*p == '{') {
            if (*(p + 1) == '{') {
                // Escaped {{
                result.append('{');
                p += 2;
                continue;
            }
            ++p; // Skip '{'
            // Parse argument index
            int arg_index = -1;
            if (*p >= '0' && *p <= '9') {
                arg_index = 0;
                while (*p >= '0' && *p <= '9') {
                    arg_index = arg_index * 10 + (*p - '0');
                    ++p;
                }
            } else {
                arg_index = auto_index++;
            }
            // Parse format spec
            FormatSpec spec;
            if (*p == ':') {
                ++p;
                p = parse_format_spec(p, spec);
            }
            // Skip to '}'
            while (*p && *p != '}') ++p;
            if (*p == '}') ++p;
            // Format the argument
            if (arg_index >= 0 && arg_index < num_args) {
                fl::string formatted = args[arg_index].format(spec);
                apply_width_align(result, formatted, spec);
            } else {
                result.append("<out_of_range>");
            }
        } else if (*p == '}') {
            if (*(p + 1) == '}') {
                // Escaped }}
                result.append('}');
                p += 2;
            } else {
                result.append(*p++);
            }
        } else {
            // Regular character - find next special char
            const char* next = p;
            while (*next && *next != '{' && *next != '}') {
                ++next;
            }
            result.append(p, static_cast<fl::size>(next - p));
            p = next;
        }
    }
    return result;
}
References apply_width_align(), args, and parse_format_spec().
Referenced by fl::format(), and fl::format().