FastLED: fl::WaveFx::WaveFx
WaveFx()
fl::WaveFx::WaveFx (const XYMap & xymap, Args args = Args()) inline
Construct wave effect with given coordinate mapping and parameters.
Parameters
xymap Coordinate mapping from 2D grid to 1D LED array
args Configuration parameters (uses defaults if not specified)
Definition at line 173 of file wave.h.
        : Fx2d(xymap), mWaveSim(xymap.getWidth(), xymap.getHeight(),
                                args.factor, args.speed, args.dampening) {
        // Initialize the wave simulation with the given parameters.
        if (args.crgbMap == nullptr) {
            // Use the default CRGB mapping function.
            mCrgbMap = fl::make_shared<WaveCrgbMapDefault>();
        } else {
            // Set a custom CRGB mapping function.
            mCrgbMap = args.crgbMap;
        }
        setAutoUpdate(args.auto_updates);
        setXCylindrical(args.x_cyclical);
        setUseChangeGrid(args.use_change_grid);
    }
References fl::Fx2d::Fx2d(), args, dampening(), fl::Fx2d::getHeight(), fl::Fx2d::getWidth(), mWaveSim, setAutoUpdate(), setUseChangeGrid(), setXCylindrical(), speed, and xymap.