FastLED: fl::noiseRingHSV16
noiseRingHSV16()
HSV16 fl::noiseRingHSV16 (float angle, u32 time, float radius = 1.0f)
Ring noise functions - sample three z-slices for independent component evolution.
Generate HSV16 noise for a ring pattern.
Samples three z-slices of 3D Perlin noise (at time, time+0x10000, time+0x20000) to create independent hue, saturation, and value components.
Parameters
angle Position around the ring (radians, 0 to 2π)
time Animation time parameter
radius Noise zoom level (level of detail). Larger values = coarser pattern, smaller = more detail (default 1.0)
Returns
HSV16 color with 16-bit components
Definition at line 27 of file noise.cpp.hpp.
{
  // Convert angle to cartesian coordinates
  float x = fl::cosf(angle);
  float y = fl::sinf(angle);
  // Map sin/cos values from [-1, 1] to [0, 0xFFFF]
  // This ensures positive values for uint32_t conversion
  u32 nx = static_cast<u32>((x + 1.0f) * 0.5f * radius * 0xffff);
  u32 ny = static_cast<u32>((y + 1.0f) * 0.5f * radius * 0xffff);
  // Sample three different z-slices for H, S, V components
  // Using offsets 0x0, 0x10000, 0x20000 to separate them in noise space
  u16 h_raw = inoise16(nx, ny, time);
  u16 s_raw = inoise16(nx, ny, time + 0x10000);
  u16 v_raw = inoise16(nx, ny, time + 0x20000);
  // Rescale from observed noise range to full 0-65535 range using global extents
  u16 h = rescaleNoiseValue16(h_raw);
  u16 s = rescaleNoiseValue16(s_raw);
  u16 v = rescaleNoiseValue16(v_raw);
  return HSV16(h, s, v);
}
References cosf(), inoise16(), rescaleNoiseValue16(), sinf(), time(), x, and y.
Referenced by noiseRingHSV8().