FastLED: fl::anonymous_namespace{json.cpp.hpp}::optimize_array
optimize_array()
fl::shared_ptr< json_value > fl::anonymous_namespace{json.cpp.hpp}::optimize_array (fl::shared_ptr< json_value > array_val)
Definition at line 733 of file json.cpp.hpp.
{
    auto arr = array_val->data.ptr<json_array>();
    if (!arr) return array_val;
    ArrayType type = classify_array(*arr);
    switch (type) {
        case ALL_UINT8: {
            fl::vector<u8> vec;
            vec.reserve(arr->size());
            for (const auto& elem : *arr) {
                auto val = elem->as_int();
                if (val) vec.push_back(static_cast<u8>(*val));
            }
            return fl::make_shared<json_value>(fl::move(vec));
        }
        case ALL_INT16: {
            fl::vector<i16> vec;
            vec.reserve(arr->size());
            for (const auto& elem : *arr) {
                auto val = elem->as_int();
                if (val) vec.push_back(static_cast<i16>(*val));
            }
            return fl::make_shared<json_value>(fl::move(vec));
        }
        case ALL_FLOATS: {
            fl::vector<float> vec;
            vec.reserve(arr->size());
            for (const auto& elem : *arr) {
                if (elem->is_float()) {
                    auto val = elem->as_float();
                    if (val) vec.push_back(*val);
                } else if (elem->is_int()) {
                    auto val = elem->as_int();
                    if (val) {
                        // Route i64 -> float via i32 to avoid the direct cast
                        // pulling libgcc-nofp's `_floatdisf.o` (~5 KB of soft-FP
                        // double cascade) on no-FPU targets. ALL_FLOATS
                        // classification only fires when every int is within
                        // +/-2^24 anyway (classify_array line 717), so the int32
                        // narrowing is lossless. See FastLED #3076.
                        vec.push_back(static_cast<float>(static_cast<fl::i32>(*val)));
                    }
                }
            }
            return fl::make_shared<json_value>(fl::move(vec));
        }
        default:
            return array_val;  // Keep as generic array
    }
}
References ALL_FLOATS, ALL_INT16, ALL_UINT8, classify_array(), fl::make_shared(), fl::fl::move(), optimize_array(), fl::vector< T >::push_back(), and fl::vector< T >::reserve().
Referenced by fl::anonymous_namespace{json.cpp.hpp}::JsonBuilder::on_token(), and optimize_array().