FastLED: fl::audio::detector::Downbeat::update
update()
void fl::audio::detector::Downbeat::update (shared_ptr< Context > context) override virtual
Implements fl::audio::Detector.
Definition at line 38 of file downbeat.cpp.hpp.
{
    // Update Beat if we own it
    if (mOwnsBeatDetector) {
        updateBeatDetector(context);
    }
    // Get current state from Beat
    bool beatDetected = mBeatDetector->isBeat();
    u32 timestamp = context->getTimestamp();
    // Reset downbeat flag
    mDownbeatDetected = false;
    // If beat detected, analyze for downbeat
    if (beatDetected) {
        // Get fft::FFT for accent analysis
        mRetainedFFT = context->getFFT16();
        const fft::Bins& fft = *mRetainedFFT;
        // Calculate current energy (bass-weighted for accent detection)
        float bassEnergy = 0.0f;
        for (size i = 0; i < fl::min(static_cast<size>(4), fft.raw().size()); i++) {
            bassEnergy += fft.raw()[i];
        }
        bassEnergy /= 4.0f;
        // Calculate accent strength
        float accent = calculateBeatAccent(fft, bassEnergy);
        // Store accent in history
        if (mBeatAccents.size() >= MAX_BEAT_HISTORY) {
            mBeatAccents.pop_front();
        }
        mBeatAccents.push_back(accent);
        // Detect downbeat
        mDownbeatDetected = detectDownbeat(timestamp, accent);
        if (mDownbeatDetected) {
            mCurrentBeat = 1;
            mBeatsSinceDownbeat = 0;
            mLastDownbeatTime = timestamp;
            // Set callback flags
            mFireDownbeat = true;
            mFireMeasureBeat = true;
            mPendingBeatNumber = 1;
            // Attempt meter detection if enabled
            if (mAutoMeterDetection && !mManualMeter) {
                detectMeter();
            }
        } else {
            // Not a downbeat, increment beat counter
            mBeatsSinceDownbeat++;
            mCurrentBeat = (mBeatsSinceDownbeat % mBeatsPerMeasure) + 1;
            // Set beat callback flag
            mFireMeasureBeat = true;
            mPendingBeatNumber = mCurrentBeat;
            // Check if we should force a downbeat (measure boundary)
            if (mBeatsSinceDownbeat >= mBeatsPerMeasure) {
                // Force downbeat on measure boundary
                mDownbeatDetected = true;
                mCurrentBeat = 1;
                mBeatsSinceDownbeat = 0;
                mLastDownbeatTime = timestamp;
                mFireDownbeat = true;
                mFireMeasureBeat = true;
                mPendingBeatNumber = 1;
            }
        }
        mLastBeatTime = timestamp;
        mPreviousEnergy = bassEnergy;
    }
    // Update measure phase
    updateMeasurePhase(timestamp);
}
References Downbeat(), calculateBeatAccent(), detectDownbeat(), detectMeter(), mAutoMeterDetection, MAX_BEAT_HISTORY, mBeatAccents, mBeatDetector, mBeatsPerMeasure, mBeatsSinceDownbeat, mCurrentBeat, mDownbeatDetected, mFireDownbeat, mFireMeasureBeat, mLastBeatTime, mLastDownbeatTime, mManualMeter, mOwnsBeatDetector, mPendingBeatNumber, mPreviousEnergy, mRetainedFFT, update(), updateBeatDetector(), and updateMeasurePhase().
Referenced by ~Downbeat(), and update().