FastLED: fl::audio::detector::Downbeat::detectMeter
detectMeter()
void fl::audio::detector::Downbeat::detectMeter () private
Definition at line 313 of file downbeat.cpp.hpp.
{
    // Analyze recent beat patterns to detect time signature
    // Look for recurring patterns in beat intervals and accents
    // Add current meter candidate based on beat count
    u8 detectedMeter = mBeatsPerMeasure;
    // Analyze accent patterns to infer meter
    if (mBeatAccents.size() >= 8) {
        // Look for recurring strong accents
        // Common meters: 4/4 (every 4 beats), 3/4 (every 3), 6/8 (every 6)
        size numAccents = mBeatAccents.size();
        fl::array<u8, 5> candidateMeters = {2, 3, 4, 6, 8};
        float bestScore = 0.0f;
        u8 bestMeter = 4;
        for (size m = 0; m < candidateMeters.size(); m++) {
            u8 meter = candidateMeters[m];
            float score = 0.0f;
            // Score based on accent pattern matching
            for (size i = 0; i < numAccents; i++) {
                if (i % meter == 0) {
                    // Expect strong accent at measure start
                    score += mBeatAccents[i];
                } else {
                    // Expect weaker accent elsewhere
                    score += (2.0f - mBeatAccents[i]) * 0.5f;
                }
            }
            if (score > bestScore) {
                bestScore = score;
                bestMeter = meter;
            }
        }
        detectedMeter = bestMeter;
    }
    // Add to meter history
    if (mMeterCandidates.size() >= METER_HISTORY_SIZE) {
        mMeterCandidates.pop_front();
    }
    mMeterCandidates.push_back(detectedMeter);
    // Find most common meter in recent history
    u8 consensusMeter = findMostCommonMeter();
    // Update meter if consensus differs and is stable
    if (consensusMeter != mBeatsPerMeasure && mMeterCandidates.size() >= METER_HISTORY_SIZE / 2) {
        (void)mBeatsPerMeasure;  // Suppress unused warning (used in comparison above)
        mBeatsPerMeasure = consensusMeter;
        // Set meter change callback flag
        mFireMeterChange = true;
        mPendingMeter = mBeatsPerMeasure;
        // Reset beat counter
        mCurrentBeat = 1;
        mBeatsSinceDownbeat = 0;
    }
}
References findMostCommonMeter(), mBeatAccents, mBeatsPerMeasure, mBeatsSinceDownbeat, mCurrentBeat, METER_HISTORY_SIZE, mFireMeterChange, mMeterCandidates, mPendingMeter, and fl::array< T, N >::size().
Referenced by update().