FastLED: fl::PixelIterator::writeAPA102
writeAPA102()
template<typename CONTAINER_UIN8_T> void fl::PixelIterator::writeAPA102 (CONTAINER_UIN8_T * out, bool hd_gamma = false) inline
Encode pixels in APA102/DOTSTAR format (zero allocation)
Parameters
out Output buffer to write encoded bytes
hd_gamma Enable high-definition gamma correction (per-LED brightness)
Note
Protocol: [Start:32b 0x00][LED:[0xE0|bri5][B][G][R]]×N[End:⌈N/32⌉×32b 0xFF]
Definition at line 223 of file pixel_iterator.h.
{
        auto back_ins = fl::back_inserter(*out);
        #if FASTLED_HD_COLOR_MIXING
        if (hd_gamma) {
            // HD gamma mode: per-LED brightness
            auto pixel_range = makeScaledPixelRangeRGB(this);
            auto brightness_range = makeScaledBrightnessRange(this);
            encodeAPA102_HD(pixel_range.first, pixel_range.second,
                                      brightness_range.first, back_ins);
            return;
        }
        #endif
        #if FASTLED_USE_GLOBAL_BRIGHTNESS == 1
        // Global brightness mode: extract from first pixel
        auto pixel_range = makeScaledPixelRangeRGB(this);
        encodeAPA102_AutoBrightness(pixel_range.first, pixel_range.second,
                                              back_ins);
        #else
        // Full brightness mode
        auto pixel_range = makeScaledPixelRangeRGB(this);
        encodeAPA102(pixel_range.first, pixel_range.second,
                               back_ins, 31);
        #endif
    }
References fl::back_inserter(), fl::encodeAPA102(), fl::encodeAPA102_AutoBrightness(), fl::encodeAPA102_HD(), FL_NOEXCEPT, fl::makeScaledBrightnessRange(), and fl::makeScaledPixelRangeRGB().
Referenced by fl::Channel::showPixels().