FastLED: fl::PixelIterator::writeWS2803
writeWS2803()
template<typename CONTAINER_UIN8_T> void fl::PixelIterator::writeWS2803 (CONTAINER_UIN8_T * out) inline
Encode pixels in WS2803 format (zero allocation)
Parameters
out Output buffer to write encoded bytes
Note
Protocol: Identical to WS2801
Uses unified encoder: src/fl/chipsets/encoders/ws2803.h
Definition at line 301 of file pixel_iterator.h.
{
        auto back_ins = fl::back_inserter(*out);
        auto pixel_range = makeScaledPixelRangeRGB(this);
        encodeWS2803(pixel_range.first, pixel_range.second, back_ins);
    }
References fl::back_inserter(), fl::encodeWS2803(), FL_NOEXCEPT, and fl::makeScaledPixelRangeRGB().
Referenced by fl::Channel::showPixels().