FastLED: fl::net::http::execute_fetch_request
execute_fetch_request()
fl::task::Promise< Response > fl::net::http::execute_fetch_request (const fl::string & url, const FetchOptions & request)
Internal helper to execute a fetch request and return a promise.
Definition at line 410 of file fetch.cpp.hpp.
{
    (void)request;
    FL_WARN("HTTP fetch is not supported on this platform. URL: " << url);
    Response error_response(501, "Not Implemented");
    error_response.set_body("HTTP fetch is not available on this platform.");
    return fl::task::Promise<Response>::resolve(error_response);
}
References FL_WARN, fl::task::Promise< T >::resolve(), and fl::net::http::Response::set_body().
Referenced by fetch_delete(), fetch_get(), fetch_head(), fetch_http_options(), fetch_patch(), fetch_post(), fetch_put(), and fetch_request().