FastLED: fl::net::http::fetch_post
fetch_post()
fl::task::Promise< Response > fl::net::http::fetch_post (const fl::string & url, const FetchOptions & request)
HTTP POST request.
Definition at line 527 of file fetch.cpp.hpp.
{
    // Create a new request with POST method
    FetchOptions post_request(url, RequestOptions("POST"));
    // Apply any additional options from the provided request
    const auto& opts = request.options();
    post_request.timeout(opts.timeout_ms);
    for (const auto& header : opts.headers) {
        post_request.header(header.first, header.second);
    }
    if (!opts.body.empty()) {
        post_request.body(opts.body);
    }
    return execute_fetch_request(url, post_request);
}
References fl::net::http::FetchOptions::body(), execute_fetch_request(), fl::net::http::FetchOptions::header(), fl::net::http::FetchOptions::options(), and fl::net::http::FetchOptions::timeout().