FastLED: fl::TaskImpl::TaskImpl
TaskImpl() [1/4]
fl::TaskImpl::TaskImpl (TaskType type, int interval_ms) private
Definition at line 20 of file task.cpp.
    : mType(type),
      mIntervalMs(interval_ms),
      mCanceled(false),
      mTraceLabel(),
      mHasThen(false),
      mHasCatch(false),
      mLastRunTime(UINT32_MAX) {  // Use UINT32_MAX to indicate "never run"
}
References interval_ms(), mCanceled, mHasCatch, mHasThen, mIntervalMs, mLastRunTime, mTraceLabel, mType, and type().
Referenced by TaskImpl(), TaskImpl(), operator=(), and operator=().