FastLED: fl::unordered_map_small::insert
insert() [3/4]
template<typename Key, typename Value, typename Equal = fl::SmallMapEqualTo<Key>> bool fl::unordered_map_small< Key, Value, Equal >::insert (Key && key, Value && value, insert_result * result = nullptr) inline
Definition at line 320 of file unordered_map_small.h.
{
        Key key_copy = key;
        size_type idx = find_index(key_copy);
        if (idx != npos()) {
            if (result) *result = exists;
            return false;
        }
        do_insert(value_type(fl::move(key), fl::move(value)));
        if (result) *result = inserted;
        return true;
    }
References do_insert(), exists, find_index(), FL_NOEXCEPT, inserted, fl::fl::move(), npos(), and fl::type_rank< T >::value.