FastLED: fl::unordered_map_small::emplace
emplace()
template<typename Key, typename Value, typename Equal = fl::SmallMapEqualTo<Key>> template<typename... Args> fl::pair< iterator, bool > fl::unordered_map_small< Key, Value, Equal >::emplace (Args &&... args) inline
Definition at line 334 of file unordered_map_small.h.
{
        value_type kv(fl::forward<Args>(args)...);
        return insert(fl::move(kv));
    }
References args, FL_NOEXCEPT, fl::fl::forward(), insert(), and fl::fl::move().