FastLED: fl::DemoReel100::draw
draw()
void fl::DemoReel100::draw (DrawContext context) inline override virtual
Parameters
now The current time in milliseconds. Fx writers are encouraged to use this instead of millis() directly as this will more deterministic behavior.
Implements fl::Fx.
Definition at line 22 of file demoreel100.h.
{
        fl::span<CRGB> leds = context.leds;
        if (leds.empty() || mNumLeds == 0) {
            return;
        }
        if (start_time == 0) {
            start_time = fl::millis();
        }
        // Call the current pattern function once, updating the 'leds' array
        runPattern(leds);
        // do some periodic updates
        EVERY_N_MILLISECONDS(20) {
            hue++;
        } // slowly cycle the "base color" through the rainbow
        EVERY_N_SECONDS(10) { nextPattern(); } // change patterns periodically
    }
References EVERY_N_MILLISECONDS, EVERY_N_SECONDS, hue, fl::DrawContext::leds, leds, fl::millis(), fl::Fx::mNumLeds, nextPattern(), runPattern(), and start_time.