FastLED: fl::DemoReel100::bpm
bpm()
void fl::DemoReel100::bpm (fl::span< CRGB > leds) inline private
Definition at line 108 of file demoreel100.h.
{
        // colored stripes pulsing at a defined Beats-Per-Minute (BPM)
        u8 BeatsPerMinute = 62;
        CRGBPalette16 palette = PartyColors_p;
        u8 beat = beatsin8(BeatsPerMinute, 64, 255);
        for (u16 i = 0; i < mNumLeds; i++) {
            leds[i] =
                ColorFromPalette(palette, hue + (i * 2), beat - hue + (i * 10));
        }
    }
References fl::beatsin8(), fl::ColorFromPalette(), hue, leds, fl::Fx::mNumLeds, palette(), and PartyColors_p.