FastLED: fl::perlin_q16::pnoise2d_raw
pnoise2d_raw()
fl::i32 fl::perlin_q16::pnoise2d_raw (fl::i32 fx_raw, fl::i32 fy_raw, const fl::i32 * fade_lut, const fl::u8 * perm) static
Definition at line 34 of file perlin_q16.cpp.hpp.
{
    int X, Y;
    fl::i32 x, y;
    floor_frac(fx_raw, X, x);
    floor_frac(fy_raw, Y, y);
    X &= 255;
    Y &= 255;
    fl::i32 u = fade(x, fade_lut);
    fl::i32 v = fade(y, fade_lut);
    int A  = perm[X & 255]       + Y;
    int AA = perm[A & 255];
    int AB = perm[(A + 1) & 255];
    int B  = perm[(X + 1) & 255] + Y;
    int BA = perm[B & 255];
    int BB = perm[(B + 1) & 255];
    fl::i32 result = lerp(v,
        lerp(u, grad(perm[AA & 255], x,          y),
                grad(perm[BA & 255], x - HP_ONE, y)),
        lerp(u, grad(perm[AB & 255], x,          y - HP_ONE),
                grad(perm[BB & 255], x - HP_ONE, y - HP_ONE)));
    // No shift needed: already in Q16 format, matches s16x16::FRAC_BITS
    return result;
}
References fl::B, fade(), floor_frac(), grad(), HP_ONE, lerp(), fl::x, and fl::y.
Referenced by pnoise2d().