FastLED: fl::audio::detector::DropDetector::update
update() [2/2]
void fl::audio::detector::DropDetector::update (shared_ptr< Context > context) override virtual
Implements fl::audio::Detector.
Definition at line 30 of file drop.cpp.hpp.
{
    if (!context) {
        // Null context - nothing to process
        return;
    }
    mRetainedFFT = context->getFFT(32);
    const fft::Bins& fft = *mRetainedFFT;
    float rms = context->getRMS();
    u32 timestamp = context->getTimestamp();
    // Calculate frequency band energies
    float bassEnergy = getBassEnergy(fft);
    float midEnergy = getMidEnergy(fft);
    float trebleEnergy = getTrebleEnergy(fft);
    // Calculate flux values (rate of change)
    float energyFlux = calculateEnergyFlux(rms);
    float bassFlux = calculateBassFlux(bassEnergy);
    // Calculate spectral novelty (how much spectrum changed)
    float spectralNovelty = calculateSpectralNovelty(bassEnergy, midEnergy, trebleEnergy);
    // Calculate drop impact
    float impact = calculateDropImpact(energyFlux, bassFlux, spectralNovelty, rms);
    // Check if we should trigger a drop
    mDropDetectedThisFrame = false;
    if (shouldTriggerDrop(impact, timestamp)) {
        // Create drop event
        Drop dropEvent;
        dropEvent.impact = impact;
        dropEvent.bassEnergy = bassEnergy;
        dropEvent.energyIncrease = energyFlux;
        dropEvent.timestamp = timestamp;
        mLastDrop = dropEvent;
        mDropDetectedThisFrame = true;
        FL_DBG("DropDetector: Drop detected! Impact=" << impact
               << ", Bass=" << bassEnergy
               << ", Energy flux=" << energyFlux);
    }
    // Update baselines (exponential moving average)
    updateBaselines(rms, bassEnergy);
    // Store current values for next frame
    mPrevRMS = rms;
    mPrevBassEnergy = bassEnergy;
    mPrevMidEnergy = midEnergy;
    mPrevTrebleEnergy = trebleEnergy;
}
References DropDetector(), fl::audio::detector::Drop::bassEnergy, calculateBassFlux(), calculateDropImpact(), calculateEnergyFlux(), calculateSpectralNovelty(), fl::audio::detector::Drop::energyIncrease, FL_DBG, getBassEnergy(), getMidEnergy(), getTrebleEnergy(), fl::audio::detector::Drop::impact, mDropDetectedThisFrame, mLastDrop, mPrevBassEnergy, mPrevMidEnergy, mPrevRMS, mPrevTrebleEnergy, mRetainedFFT, rms(), shouldTriggerDrop(), fl::audio::detector::Drop::timestamp, update(), and updateBaselines().
Referenced by ~DropDetector(), update(), and update().