FastLED: scale
scale()
UISlider scale ("Scale" , 1. 0f, 0. 0f, 1. 0f, 0. 01f)
Referenced by DATA_NOP::adjust(), ChangePaletteAndSettingsPeriodically(), CRGB::computeAdjustment(), draw(), fill_noise16(), fill_noise8(), fill_raw_2dnoise16into8(), fill_raw_noise16into8(), fill_raw_noise8(), FillNoise(), fillnoise8(), CLEDController::getAdjustment(), getPaletteIndex(), getPaletteIndex(), HorizontalStream(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale(), loop(), fl::map_range_detail::map_range_math< T, vec2< V > >::map(), Color3i::Mulf(), fl::nscale8(), nscale8_LEAVING_R1_DIRTY(), fl::nscale8_video(), nscale8_video_LEAVING_R1_DIRTY(), nscale8x2(), nscale8x2_video(), nscale8x3(), nscale8x3_constexpr(), nscale8x3_video(), scale16(), scale16by8(), scale8(), scale8_constexpr(), scale8_LEAVING_R1_DIRTY(), scale8_video(), scale8_video_LEAVING_R1_DIRTY(), MidiInterface< Transport, _Settings, _Platform >::sendPitchBend(), CFastLED::setBrightness(), fl::XYPath::setScale(), fl::XYPathRenderer::setScale(), fl::FxEngine::setSpeed(), setup(), CFastLED::show(), CFastLED::showColor(), animartrix_detail::ANIMartRIX::SM10(), and VerticalStream().