FastLED: loop
loop()
void loop ()
Definition at line 117 of file complex.h.
            {
    // Your code here
    clearLeds();
    const uint32_t now = millis();
    uint32_t now_warped = time_warp.update(now);
    auto shape = getShape(whichShape.as<int>());
    shape->setScale(scale.value());
    float curr_alpha = getAnimationTime(now_warped);
    static float s_prev_alpha = 0.0f;
    // unconditionally apply the circle.
    if (trigger) {
        // trigger the transition
        time_warp.reset(now);
        now_warped = time_warp.update(now);
        shapeProgress.trigger(now_warped);
        FASTLED_WARN("Transition triggered on " << shape->name());
        curr_alpha = getAnimationTime(now_warped);
        s_prev_alpha = curr_alpha;
    }
    // FASTLED_WARN("Current alpha: " << curr_alpha);
    // FASTLED_WARN("maxAnimation: " << maxAnimation.value());
    const bool is_active =
        true || curr_alpha < maxAnimation.value() && curr_alpha > 0.0f;
    // if (shapeProgress.isActive(now)) {
    static uint32_t frame = 0;
    frame++;
    clearLeds();
    const CRGB purple = CRGB(255, 0, 255);
    const int number_of_steps = numberOfSteps.value();
    raster.reset();
    // float factor = s_prev_alpha;  // 0->1.f
    // factor = MIN(factor/4.0f, 0.05f);
    float diff = curr_alpha - s_prev_alpha;
    diff *= 1.0f;
    float factor = MAX(s_prev_alpha - diff, 0.f);
    for (int i = 0; i < number_of_steps; ++i) {
        float a =
            fl::map_range<float>(i, 0, number_of_steps - 1, factor, curr_alpha);
        if (a < .04) {
            // shorter tails at first.
            a = map_range<float>(a, 0.0f, .04f, 0.0f, .04f);
        }
        float diff_max_alpha = maxAnimation.value() - curr_alpha;
        if (diff_max_alpha < 0.94) {
            // shorter tails at the end.
            a = map_range<float>(a, curr_alpha, maxAnimation.value(),
                                 curr_alpha, maxAnimation.value());
        }
        uint8_t alpha =
            fl::map_range<float>(i, 0.0f, number_of_steps - 1, 64, 255);
        if (!is_active) {
            alpha = 0;
        }
        Tile2x2_u8 subpixel = shape->at_subpixel(a);
        subpixel.scale(alpha);
        // subpixels.push_back(subpixel);
        raster.rasterize(subpixel);
    }
    s_prev_alpha = curr_alpha;
    if (useWaveFx && is_active) {
        DrawRasterToWaveSimulator draw_wave_fx(&wave_fx);
        raster.draw(xyMap, draw_wave_fx);
    } else {
        raster.draw(purple, xyMap, leds);
    }
    int first = xyMap(1, 1);
    int last = xyMap(WIDTH - 2, HEIGHT - 2);
    leds[first] = CRGB(255, 0, 0);
    leds[last] = CRGB(0, 255, 0);
    if (useWaveFx) {
        // fxBlend.draw(Fx::DrawContext(now, leds));
        wave_fx.draw(Fx::DrawContext(now, leds));
    }
    EVERY_N_SECONDS(1) {
        uint32_t frame_time = millis() - now;
        FASTLED_WARN("Frame time: " << frame_time << "ms");
    }
    FastLED.show();
}
References clearLeds(), EVERY_N_SECONDS, FastLED, FASTLED_WARN, getAnimationTime(), getShape(), HEIGHT, leds, fl::map_range(), MAX, maxAnimation(), numberOfSteps(), raster(), fl::Tile2x2_u8::scale(), scale, shapeProgress(), time_warp, trigger(), useWaveFx(), wave_fx, whichShape(), WIDTH, and xyMap.