FastLED: fl::audio::detector::MusicalBeat::isValidIBI
isValidIBI()
bool fl::audio::detector::MusicalBeat::isValidIBI (float ibi) const private
Check if IBI is within valid BPM range.
Parameters
ibi Inter-beat interval in seconds
Returns
True if IBI corresponds to valid BPM (minBPM-maxBPM)
Definition at line 207 of file musical_beat_detector.cpp.hpp.
{
    if (ibi <= 0.0f) {
        return false;
    }
    // Convert IBI to BPM
    float bpm = 60.0f / ibi;
    // Check if BPM is within valid range
    return (bpm >= mConfig.minBPM) && (bpm <= mConfig.maxBPM);
}
References bpm(), and mConfig.
Referenced by processSample(), and validateBeat().