FastLED: fl::audio::detector::MusicalBeat::processSample
processSample()
void fl::audio::detector::MusicalBeat::processSample (bool onsetDetected, float onsetStrength)
Process one audio frame.
Parameters
onsetDetected True if onset detector triggered
onsetStrength Onset magnitude (spectral flux value)
Definition at line 25 of file musical_beat_detector.cpp.hpp.
{
    mBeatDetected = false;
    mLastBeatConfidence = 0.0f;
    mCurrentFrame++;
    if (!onsetDetected) {
        return;
    }
    mStats.totalOnsets++;
    // Validate if this onset is a true musical beat
    if (validateBeat(onsetStrength)) {
        mBeatDetected = true;
        mStats.validatedBeats++;
        // Calculate inter-beat interval (IBI)
        u32 ibiFrames = mCurrentFrame - mLastBeatFrame;
        mLastBeatFrame = mCurrentFrame;
        // Convert IBI from frames to seconds
        float ibiSeconds = static_cast<float>(ibiFrames * mConfig.samplesPerFrame) /
                          static_cast<float>(mConfig.sampleRate);
        // Validate IBI is within BPM range
        if (isValidIBI(ibiSeconds)) {
            // Add to history
            if (mIBIHistory.size() >= mConfig.maxIBIHistory) {
                // Remove oldest IBI
                mIBIHistory.pop_front();
            }
            mIBIHistory.push_back(ibiFrames);
            // Calculate beat confidence
            mLastBeatConfidence = calculateBeatConfidence(ibiSeconds);
            // Update BPM estimate
            updateBPMEstimate();
            // Update stats
            mStats.currentBPM = mCurrentBPM;
            mStats.averageIBI = getAverageIBI();
            mStats.ibiCount = static_cast<u32>(mIBIHistory.size());
        } else {
            // IBI out of valid range - reject beat
            mBeatDetected = false;
            mStats.rejectedOnsets++;
        }
    } else {
        mStats.rejectedOnsets++;
    }
}
References calculateBeatConfidence(), getAverageIBI(), isValidIBI(), mBeatDetected, mConfig, mCurrentBPM, mCurrentFrame, mIBIHistory, mLastBeatConfidence, mLastBeatFrame, mStats, updateBPMEstimate(), and validateBeat().
Referenced by ~MusicalBeat().