FastLED: fl::s24x8::exp2_fp
exp2_fp()
static FASTLED_FORCE_INLINE s24x8 fl::s24x8::exp2_fp (s24x8 x) inline static private
Definition at line 354 of file s24x8.h.
{
        s24x8 fl_val = floor(x);
        s24x8 fr = x - fl_val;
        i32 n = fl_val.mValue >> FRAC_BITS;
        if (n >= INT_BITS - 1) return from_raw(0x7FFFFFFF);
        if (n < -FRAC_BITS) return s24x8();
        i32 int_pow = 0;
        if (n >= 0) {
            int_pow = static_cast<i32>(SCALE) << n;
        } else {
            int_pow = static_cast<i32>(SCALE) >> (-n);
        }
        // 4-term minimax coefficients for 2^t - 1, t in [0,1).
        // Stored as i64 with 16 fractional bits.
        constexpr int IFRAC = 16;
        constexpr i64 d0 = 45427LL;    // 0.69316 * 2^16
        constexpr i64 d1 = 15775LL;    // 0.24071 * 2^16
        constexpr i64 d2 = 3497LL;     // 0.05336 * 2^16
        constexpr i64 d3 = 836LL;      // 0.01276 * 2^16
        // Extend fr from 8 to 16 frac bits.
        i64 fr16 = static_cast<i64>(fr.mValue) << (IFRAC - FRAC_BITS);
        // Horner: 1 + fr * (d0 + fr * (d1 + fr * (d2 + fr * d3)))
        i64 acc = d3;
        acc = d2 + ((acc * fr16) >> IFRAC);
        acc = d1 + ((acc * fr16) >> IFRAC);
        acc = d0 + ((acc * fr16) >> IFRAC);
        constexpr i64 one16 = 1LL << IFRAC;
        i64 frac_pow16 = one16 + ((acc * fr16) >> IFRAC);
        // Convert from 16 frac bits to 8 frac bits, then scale by int_pow.
        i32 frac_pow8 = static_cast<i32>(frac_pow16 >> (IFRAC - FRAC_BITS));
        i64 result =
            (static_cast<i64>(int_pow) * frac_pow8) >> FRAC_BITS;
        return from_raw(static_cast<i32>(result));
    }
References s24x8(), FASTLED_FORCE_INLINE, FL_NOEXCEPT, floor(), FRAC_BITS, from_raw(), INT_BITS, mValue, SCALE, and fl::x.
Referenced by pow().