FastLED: fl::audio::detector::Backbeat::detectBackbeat
detectBackbeat()
bool fl::audio::detector::Backbeat::detectBackbeat (float accentStrength, const fft::Bins & fft) private
Definition at line 310 of file backbeat.cpp.hpp.
{
    // Check if we're at a backbeat position
    bool atBackbeatPosition = isBackbeatPosition();
    if (!atBackbeatPosition) {
        mConfidence = 0.0f;
        return false;
    }
    // Calculate accent confidence (relative to adaptive threshold)
    float accentConfidence = 0.0f;
    if (mAdaptive && mBackbeatMean > mNonBackbeatMean) {
        // Compare to learned distribution
        float separation = mBackbeatMean - mNonBackbeatMean;
        if (separation > 1e-6f) {
            accentConfidence = (accentStrength - mNonBackbeatMean) / separation;
            accentConfidence = fl::clamp(accentConfidence, 0.0f, 1.0f);
        }
    } else {
        // Use fixed threshold
        accentConfidence = (accentStrength >= mAdaptiveThreshold) ? 1.0f : 0.0f;
    }
    // Position confidence (we're at backbeat position)
    float positionConfidence = 1.0f;
    // Pattern confidence (spectral similarity to learned profile)
    float patternConfidence = calculatePatternConfidence(fft);
    // Combined confidence
    // Weights: accent 40%, position 30%, pattern 30%
    mConfidence = (accentConfidence * 0.4f) +
                  (positionConfidence * 0.3f) +
                  (patternConfidence * 0.3f);
    // Detect backbeat if confidence exceeds threshold
    return (mConfidence >= mConfidenceThreshold);
}
References calculatePatternConfidence(), fl::clamp(), isBackbeatPosition(), mAdaptive, mAdaptiveThreshold, mBackbeatMean, mConfidence, mConfidenceThreshold, and mNonBackbeatMean.
Referenced by update().