FastLED: fl::audio::detector::Backbeat::Backbeat
Backbeat() [1/3]
fl::audio::detector::Backbeat::Backbeat (shared_ptr< Beat > beatDetector) explicit
Construct with shared Beat.
Definition at line 10 of file backbeat.cpp.hpp.
    : mBeatDetector(beatDetector)
    , mDownbeatDetector(nullptr)
    , mOwnsBeatDetector(false)
    , mOwnsDownbeatDetector(false)
    , mBackbeatDetected(false)
    , mLastBackbeatNumber(0)
    , mConfidence(0.0f)
    , mCurrentStrength(0.0f)
    , mBackbeatRatio(1.0f)
    , mConfidenceThreshold(0.6f)
    , mBassThreshold(1.2f)
    , mMidThreshold(1.3f)
    , mHighThreshold(1.1f)
    , mBackbeatMask(0x0A)  // Bits 1 and 3 = beats 2 and 4 in 4/4
    , mAdaptive(true)
    , mCurrentBeat(1)
    , mBeatsPerMeasure(4)
    , mPreviousWasBeat(false)
    , mBackbeatMean(1.0f)
    , mNonBackbeatMean(0.8f)
    , mAdaptiveThreshold(1.0f)
    , mProfileAlpha(0.1f)
{
    mPreviousAccent = {0.0f, 0.0f, 0.0f, 0.0f};
    mBackbeatSpectralProfile.reserve(SPECTRAL_PROFILE_SIZE);
    for (size i = 0; i < SPECTRAL_PROFILE_SIZE; i++) {
        mBackbeatSpectralProfile.push_back(0.0f);
    }
}
References mAdaptive, mAdaptiveThreshold, mBackbeatDetected, mBackbeatMask, mBackbeatMean, mBackbeatRatio, mBackbeatSpectralProfile, mBassThreshold, mBeatDetector, mBeatsPerMeasure, mConfidence, mConfidenceThreshold, mCurrentBeat, mCurrentStrength, mDownbeatDetector, mHighThreshold, mLastBackbeatNumber, mMidThreshold, mNonBackbeatMean, mOwnsBeatDetector, mOwnsDownbeatDetector, mPreviousAccent, mPreviousWasBeat, mProfileAlpha, and SPECTRAL_PROFILE_SIZE.
Referenced by Backbeat(), Backbeat(), and update().