FastLED: fl::audio::detector::Backbeat::update
update()
void fl::audio::detector::Backbeat::update (shared_ptr< Context > context) override virtual
Implements fl::audio::Detector.
Definition at line 57 of file backbeat.cpp.hpp.
{
    // Update Beat if we own it
    if (mOwnsBeatDetector && mBeatDetector) {
        updateBeatDetector(context);
    }
    // Update Downbeat if we own it
    if (mOwnsDownbeatDetector && mDownbeatDetector) {
        mDownbeatDetector->update(context);
    }
    // Reset backbeat flag
    mBackbeatDetected = false;
    // Check if a beat occurred
    bool beatDetected = mBeatDetector && mBeatDetector->isBeat();
    // Update beat position tracking
    updateBeatPosition();
    // Process beat if detected
    if (beatDetected) {
        // Get fft::FFT for multi-band analysis
        mRetainedFFT = context->getFFT16();
        const fft::Bins& fft = *mRetainedFFT;
        // Calculate multi-band accent
        MultibandAccent accent = calculateMultibandAccent(fft);
        // Detect backbeat accent strength
        float accentStrength = detectBackbeatAccent(accent);
        mCurrentStrength = accentStrength;
        // Detect backbeat
        mBackbeatDetected = detectBackbeat(accentStrength, fft);
        if (mBackbeatDetected) {
            mLastBackbeatNumber = mCurrentBeat;
            // Update backbeat profile
            if (mAdaptive) {
                updateBackbeatProfile(fft);
            }
            // Store accent in backbeat history
            if (mBackbeatAccents.size() >= MAX_ACCENT_HISTORY) {
                mBackbeatAccents.pop_front();
            }
            mBackbeatAccents.push_back(accentStrength);
        } else {
            // Store accent in non-backbeat history
            if (mNonBackbeatAccents.size() >= MAX_ACCENT_HISTORY) {
                mNonBackbeatAccents.pop_front();
            }
            mNonBackbeatAccents.push_back(accentStrength);
        }
        // Update adaptive thresholds
        if (mAdaptive) {
            updateAdaptiveThresholds();
        }
        // Store current accent for next frame
        mPreviousAccent = accent;
    }
}
References Backbeat(), calculateMultibandAccent(), detectBackbeat(), detectBackbeatAccent(), mAdaptive, MAX_ACCENT_HISTORY, mBackbeatAccents, mBackbeatDetected, mBeatDetector, mCurrentBeat, mCurrentStrength, mDownbeatDetector, mLastBackbeatNumber, mNonBackbeatAccents, mOwnsBeatDetector, mOwnsDownbeatDetector, mPreviousAccent, mRetainedFFT, update(), updateAdaptiveThresholds(), updateBackbeatProfile(), updateBeatDetector(), and updateBeatPosition().
Referenced by ~Backbeat(), and update().