FastLED: fl::HashMap::find_index
find_index()
template<typename Key, typename T, typename Hash = Hash<Key>, typename KeyEqual = EqualTo<Key>, int INLINED_COUNT = FASTLED_HASHMAP_INLINED_COUNT> size_t fl::HashMap< Key, T, Hash, KeyEqual, INLINED_COUNT >::find_index (const Key & key) const inline private
Definition at line 391 of file hash_map.h.
{
        const size_t cap = _buckets.size();
        const size_t mask = cap - 1;
        const size_t h = _hash(key) & mask;
        if (cap <= kLinearProbingOnlySize) {
            // linear probing
            for (size_t i = 0; i < cap; ++i) {
                const size_t idx = (h + i) & mask;
                if (is_empty(idx))
                    return npos;
                if (is_occupied(idx) && _equal(_buckets[idx].key, key))
                    return idx;
            }
        } else {
            // quadratic probing up to 8 tries
            size_t i = 0;
            for (; i < kQuadraticProbingTries; ++i) {
                const size_t idx = (h + i + i * i) & mask;
                if (is_empty(idx))
                    return npos;
                if (is_occupied(idx) && _equal(_buckets[idx].key, key))
                    return idx;
            }
            // fallback to linear for the rest
            for (; i < cap; ++i) {
                const size_t idx = (h + i) & mask;
                if (is_empty(idx))
                    return npos;
                if (is_occupied(idx) && _equal(_buckets[idx].key, key))
                    return idx;
            }
        }
        return npos;
    }
Referenced by fl::HashMap< Key, T, Hash, KeyEqual >::find(), fl::HashMap< Key, T, Hash, KeyEqual >::find(), fl::HashMap< Key, T, Hash, KeyEqual >::find_value(), fl::HashMap< Key, T, Hash, KeyEqual >::find_value(), and fl::HashMap< Key, T, Hash, KeyEqual >::remove().