FastLED: fl::third_party::SoftwareMpeg1Decoder::decodeNextFrame
decodeNextFrame()
bool fl::third_party::SoftwareMpeg1Decoder::decodeNextFrame () private
Definition at line 356 of file software_decoder.cpp.hpp.
{
    if (!decoderData_->headerParsed || !decoderData_->plmpeg) {
        return false;
    }
    // Reset the new frame flag
    decoderData_->hasNewFrame = false;
    // Decode using pl_mpeg
    fl::third_party::plm_decode(decoderData_->plmpeg, decoderData_->targetFrameDuration);
    // Check if we have reached the end
    if (fl::third_party::plm_has_ended(decoderData_->plmpeg)) {
        return false;
    }
    // If we have a new frame, create the Frame objects
    if (decoderData_->hasNewFrame) {
        return decodeFrame();
    }
    return false;
}
References decodeFrame(), decoderData_, FL_NOEXCEPT, fl::third_party::plm_decode(), and fl::third_party::plm_has_ended().
Referenced by decode().