"""Generate a compile-time C++ header from verifier_known_bad.csv.

The header lives next to the CSV in `tests/misc/golden/` and is consumed by
the colorimetric strategy harness as a `constexpr` array of `VerifierRow`.
Both the CSV and this generated header are vendored; regenerate the header
whenever the CSV changes:

    uv run python ci/tools/gen_colorimetric_fixture_header.py
"""

import argparse
import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CSV = ROOT / "tests" / "misc" / "golden" / "verifier_known_bad.csv"
DEFAULT_HPP = ROOT / "tests" / "misc" / "golden" / "verifier_known_bad.hpp"

HEADER_PROLOGUE = """\
#pragma once
//
// Auto-generated by ci/tools/gen_colorimetric_fixture_header.py from
// tests/misc/golden/verifier_known_bad.csv. Do not hand-edit.
//
// Provenance: see tests/misc/golden/README.md.
// cf_* values are a legacy analytical_strict_rgbw16 verifier snapshot, not
// the current canonical FastLED closed-form reference.

#include "fl/stl/stdint.h"

namespace fl { namespace colorimetric_test { namespace fixture {

struct VerifierRow {
    const char* patch;
    u16 r_in16, g_in16, b_in16;
    float exp_x, exp_y;
    u16 cf_r16, cf_g16, cf_b16, cf_w16;
    float meas_x, meas_y, meas_Y;
    float dE;
    enum Status : u8 { kOk = 0, kFail = 1, kSkip = 2 };
    Status status;
};

static constexpr VerifierRow kVerifierRows[] = {
"""

HEADER_EPILOGUE = """\
};

static constexpr int kVerifierRowCount =
    sizeof(kVerifierRows) / sizeof(kVerifierRows[0]);

} } } // namespace fl::colorimetric_test::fixture
"""


def status_enum(s: str) -> str:
    return {"ok": "VerifierRow::kOk", "fail": "VerifierRow::kFail"}.get(
        s, "VerifierRow::kSkip"
    )


def fmt_float(s: str) -> str:
    if not s:
        return "0.0f"
    return f"{float(s):.6f}f"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", default=str(DEFAULT_CSV))
    ap.add_argument("--out", default=str(DEFAULT_HPP))
    args = ap.parse_args()

    csv_path = Path(args.csv)
    out_path = Path(args.out)

    with csv_path.open("r", encoding="utf-8", newline="") as f:
        rows = list(csv.DictReader(f))

    lines = [HEADER_PROLOGUE]
    for r in rows:
        # Escape any quote/backslash that might appear in patch names.
        patch = r["patch"].replace("\\", "\\\\").replace('"', '\\"')
        row_lit = (
            "    {"
            f'"{patch}", '
            f"{r['r_in16']}, {r['g_in16']}, {r['b_in16']}, "
            f"{fmt_float(r['exp_x'])}, {fmt_float(r['exp_y'])}, "
            f"{r['cf_r16']}, {r['cf_g16']}, {r['cf_b16']}, {r['cf_w16']}, "
            f"{fmt_float(r['meas_x'])}, {fmt_float(r['meas_y'])}, "
            f"{fmt_float(r['meas_Y'])}, "
            f"{fmt_float(r['dE'])}, "
            f"{status_enum(r['status'])}"
            "},\n"
        )
        lines.append(row_lit)
    lines.append(HEADER_EPILOGUE)

    out_path.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {out_path} ({len(rows)} rows, {out_path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
