FastLED: fl::audio::detector::Vocal::computeBroadSpectralFeatures
computeBroadSpectralFeatures()
void fl::audio::detector::Vocal::computeBroadSpectralFeatures (const fft::Bins & broadFft) private
Definition at line 175 of file vocal.cpp.hpp.
{
    // Broad spectral features from low-res wide FFT (16 bins, 174.6-4698.3 Hz).
    // Computes flatness, harmonic density, and spectral flux.
    const auto& bins = broadFft.raw();
    const int n = static_cast<int>(bins.size());
    if (n == 0) {
        mSpectralFlatness = 0.0f;
        mHarmonicDensity = 0.0f;
        mSpectralFlux = 0.0f;
        return;
    }
    // === PASS 1: Flatness + density peak + magnitudeSum ===
    float magnitudeSum = 0.0f;
    float sumLn = 0.0f;
    float sumRaw = 0.0f;
    int flatnessCount = 0;
    float peak = 0.0f;
    for (int i = 0; i < n; ++i) {
        const float mag = bins[i];
        magnitudeSum += mag;
        if (mag > 1e-6f) {
            sumLn += fast_logf_approx(mag);
            sumRaw += mag;
            ++flatnessCount;
        }
        if (mag > peak) peak = mag;
    }
    // --- Flatness result ---
    if (flatnessCount >= 2) {
        float geometricMean = fl::expf(sumLn / static_cast<float>(flatnessCount));
        float arithmeticMean = sumRaw / static_cast<float>(flatnessCount);
        mSpectralFlatness = (arithmeticMean < 1e-6f) ? 0.0f : geometricMean / arithmeticMean;
    } else {
        mSpectralFlatness = 0.0f;
    }
    // === PASS 2: Density count + spectral flux ===
    mHarmonicDensity = 0.0f;
    mSpectralFlux = 0.0f;
    if (magnitudeSum >= 1e-6f) {
        const float densityThreshold = peak * 0.1f;
        const float invSum = 1.0f / magnitudeSum;
        const bool hasPrev = (mPrevBins.size() == static_cast<fl::size>(n));
        int densityCount = 0;
        float flux = 0.0f;
        mFluxNormBins.resize(n);
        for (int i = 0; i < n; ++i) {
            const float mag = bins[i];
            if (mag >= densityThreshold) ++densityCount;
            float norm = mag * invSum;
            mFluxNormBins[i] = norm;
            if (hasPrev) {
                float diff = norm - mPrevBins[i];
                flux += diff * diff;
            }
        }
        mHarmonicDensity = static_cast<float>(densityCount);
        mSpectralFlux = hasPrev ? fl::sqrtf(flux) : 0.0f;
        fl::swap(mPrevBins, mFluxNormBins);
    } else {
        mPrevBins.clear();
    }
}
References fl::expf(), fl::fast_logf_approx(), mFluxNormBins, mHarmonicDensity, mPrevBins, mSpectralFlatness, mSpectralFlux, fl::audio::fft::Bins::raw(), fl::sqrtf(), and fl::fl::swap().
Referenced by update().