FastLED: fl::audio::detector::Vocal::computeFormantRatio
computeFormantRatio()
void fl::audio::detector::Vocal::computeFormantRatio (const fft::Bins & formantFft) private
Definition at line 124 of file vocal.cpp.hpp.
{
    // Formant ratio from high-resolution narrow FFT (64 bins, 200-3500 Hz).
    // All bins concentrated in the formant region — ~94% utilization.
    const auto& bins = formantFft.raw();
    const int n = static_cast<int>(bins.size());
    if (n < 8) {
        mFormantRatio = 0.0f;
        return;
    }
    // Ensure formant bin cache is current (freqToBin uses logf internally)
    if (mFormantCachedBinCount != n) {
        mFormantF1MinBin = fl::max(0, formantFft.freqToBin(250.0f));
        mFormantF1MaxBin = fl::min(n - 1, formantFft.freqToBin(900.0f));
        mFormantF2MinBin = fl::max(0, formantFft.freqToBin(1000.0f));
        mFormantF2MaxBin = fl::min(n - 1, formantFft.freqToBin(3000.0f));
        mFormantCachedBinCount = n;
    }
    float f1Peak = 0.0f, f1Sum = 0.0f;
    int f1Count = 0;
    float f2Peak = 0.0f, f2Sum = 0.0f;
    int f2Count = 0;
    for (int i = 0; i < n; ++i) {
        const float mag = bins[i];
        if (i >= mFormantF1MinBin && i <= mFormantF1MaxBin) {
            f1Peak = fl::max(f1Peak, mag);
            f1Sum += mag;
            ++f1Count;
        }
        if (i >= mFormantF2MinBin && i <= mFormantF2MaxBin) {
            f2Peak = fl::max(f2Peak, mag);
            f2Sum += mag;
            ++f2Count;
        }
    }
    if (f1Count > 0 && f2Count > 0) {
        float f1Avg = f1Sum / static_cast<float>(f1Count);
        float f2Avg = f2Sum / static_cast<float>(f2Count);
        if (f1Peak >= f1Avg * 1.5f && f2Peak >= f2Avg * 1.5f && f1Peak >= 1e-6f) {
            mFormantRatio = f2Peak / f1Peak;
        } else {
            mFormantRatio = 0.0f;
        }
    } else {
        mFormantRatio = 0.0f;
    }
}
References fl::audio::fft::Bins::freqToBin(), fl::max(), mFormantCachedBinCount, mFormantF1MaxBin, mFormantF1MinBin, mFormantF2MaxBin, mFormantF2MinBin, mFormantRatio, fl::min(), and fl::audio::fft::Bins::raw().
Referenced by update().