FastLED: fl::audio::detector::Vocal::update
update() [2/2]
void fl::audio::detector::Vocal::update (shared_ptr< Context > context) override virtual
Implements fl::audio::Detector.
Definition at line 26 of file vocal.cpp.hpp.
{
    mSampleRate = context->getSampleRate();
    // Dual FFT: high-resolution formant analysis + broad spectral features.
    // Formant FFT: 64 CQ bins in 200-3500 Hz — concentrates resolution on
    // F1/F2/F3 formants (94% bin utilization vs 73% with full-range).
    // Broad FFT: 16 LOG_REBIN bins in 174.6-4698.3 Hz — full spectral
    // coverage for flatness, density, flux, and vocal presence ratio.
    mRetainedFormantFFT = context->getFFT(64, 200.0f, 3500.0f);
    mRetainedBroadFFT = context->getFFT(16, 174.6f, 4698.3f);
    const fft::Bins& formantFft = *mRetainedFormantFFT;
    const fft::Bins& broadFft = *mRetainedBroadFFT;
    mFormantNumBins = static_cast<int>(formantFft.raw().size());
    mBroadNumBins = static_cast<int>(broadFft.raw().size());
    // Formant ratio from high-res narrow FFT
    computeFormantRatio(formantFft);
    // Broad spectral features (flatness, density, flux) from wide FFT
    computeBroadSpectralFeatures(broadFft);
    // Vocal presence ratio from broad FFT linear bins (needs 200-4000 Hz coverage)
    mVocalPresenceRatio = calculateVocalPresenceRatio(broadFft);
    mSpectralVariance = mSpectralVarianceFilter.update(broadFft.raw());
    // Calculate time-domain features from raw PCM
    span<const i16> pcm = context->getPCM();
    const float dt = computeAudioDt(pcm.size(), context->getSampleRate());
    // Fused pass: envelope jitter + zero-crossing CV in one PCM traversal
    computePCMTimeDomainFeatures(pcm);
    mEnvelopeJitter = mEnvelopeJitterSmoother.update(mEnvelopeJitter, dt);
    mAutocorrelationIrregularity = mAcfIrregularitySmoother.update(
        calculateAutocorrelationIrregularity(pcm), dt);
    mZeroCrossingCV = mZcCVSmoother.update(mZeroCrossingCV, dt);
    // Calculate raw confidence and apply time-aware smoothing
    float rawConfidence = calculateRawConfidence(
        mFormantRatio, mSpectralFlatness, mHarmonicDensity,
        mVocalPresenceRatio, mSpectralFlux, mSpectralVariance);
    float smoothedConfidence = mConfidenceSmoother.update(rawConfidence, dt);
    // Hysteresis: use separate on/off thresholds to prevent chattering
    bool wantActive;
    if (mVocalActive) {
        wantActive = (smoothedConfidence >= mOffThreshold);
    } else {
        wantActive = (smoothedConfidence >= mOnThreshold);
    }
    // Debounce: require state to persist for MIN_FRAMES_TO_TRANSITION frames
    if (wantActive != mVocalActive) {
        mFramesInState++;
        if (mFramesInState >= MIN_FRAMES_TO_TRANSITION) {
            mVocalActive = wantActive;
            mFramesInState = 0;
        }
    } else {
        mFramesInState = 0;
    }
    // Track state changes for fireCallbacks
    mStateChanged = (mVocalActive != mPreviousVocalActive);
}
References Vocal(), calculateAutocorrelationIrregularity(), calculateRawConfidence(), calculateVocalPresenceRatio(), fl::audio::computeAudioDt(), computeBroadSpectralFeatures(), computeFormantRatio(), computePCMTimeDomainFeatures(), mAcfIrregularitySmoother, mAutocorrelationIrregularity, mBroadNumBins, mConfidenceSmoother, mEnvelopeJitter, mEnvelopeJitterSmoother, mFormantNumBins, mFormantRatio, mFramesInState, mHarmonicDensity, MIN_FRAMES_TO_TRANSITION, mOffThreshold, mOnThreshold, mPreviousVocalActive, mRetainedBroadFFT, mRetainedFormantFFT, mSampleRate, mSpectralFlatness, mSpectralFlux, mSpectralVariance, mSpectralVarianceFilter, mStateChanged, mVocalActive, mVocalPresenceRatio, mZcCVSmoother, mZeroCrossingCV, fl::audio::fft::Bins::raw(), fl::span< T, Extent >::size(), and update().
Referenced by ~Vocal(), update(), and update().