FastLED: fl::audio::detector::Vocal::calculateRawConfidence
calculateRawConfidence()
float fl::audio::detector::Vocal::calculateRawConfidence (float formantRatio, float spectralFlatness, float harmonicDensity, float vocalPresenceRatio, float spectralFlux, float spectralVariance) private
Definition at line 447 of file vocal.cpp.hpp.
{
    // Centroid and rolloff removed from scoring (combined 0.04 weight — negligible
    // impact on accuracy). Centroid still computed for diagnostics.
    // Continuous confidence scores for each feature (no hard binary cutoffs)
    // Formant score: voice has F2/F1 ratio; real audio ratio ~0.14, synthetic ~0.7
    // Ramp zone 0-0.12 catches very low ratios (pure tone, sparse sines).
    // /i/ vowel (form~0.15) and guitar (form~0.17) overlap in formant ratio,
    // so guitar rejection relies on time-domain penalties (jitter, zcCV) instead.
    float formantScore;
    if (formantRatio < 0.12f) {
        formantScore = formantRatio / 0.12f * 0.30f;  // Ramp: very low → 0..0.30
    } else {
        // Peak at 0.5, floor 0.30, width 0.70 (accommodates /i/ vowel)
        float dist = fl::abs(formantRatio - 0.5f);
        formantScore = fl::max(0.30f, 1.0f - dist / 0.70f);
    }
    // Spectral flatness score: wider window to survive mix contamination.
    // Isolated vocal ~0.44, vocal-in-mix ~0.60, backing ~0.57.
    // Peak at 0.43, width ±0.22 — mix vocal (0.60) still scores ~0.22.
    float flatnessScore;
    if (spectralFlatness < 0.20f) {
        // Too tonal (pure tones, sparse sines)
        flatnessScore = spectralFlatness / 0.20f * 0.3f;
    } else if (spectralFlatness <= 0.65f) {
        // Voice range — peak at 0.43, wide window
        float dist = fl::abs(spectralFlatness - 0.43f);
        flatnessScore = fl::max(0.0f, 1.0f - dist / 0.22f);
    } else {
        // Too flat — noise-like (steep decay)
        flatnessScore = fl::max(0.0f, 1.0f - (spectralFlatness - 0.65f) / 0.10f);
    }
    // Harmonic density score: with 16 broad bins (scaled from 64-bin calibration).
    // Real audio: ~6-7, synthetic voice: 8-12, pure tone: ~4, noise: ~15
    float densityScore;
    if (harmonicDensity < 2.5f) {
        // Too sparse — pure tone or near-tonal
        densityScore = harmonicDensity / 2.5f * 0.3f;
    } else if (harmonicDensity <= 12.5f) {
        // Voice-like range
        densityScore = 0.3f + (harmonicDensity - 2.5f) / 10.0f * 0.7f;
    } else {
        // Too dense — noise-like
        densityScore = fl::max(0.0f, 1.0f - (harmonicDensity - 12.5f) / 3.5f);
    }
    // Spectral flux score: voice has higher frame-to-frame spectral change
    // than sustained instruments (phoneme transitions, formant shifts).
    // Thresholds scaled by sqrt(16/64) = 0.5 for 16-bin broad FFT.
    float spectralFluxScore;
    if (spectralFlux < 0.01f) {
        spectralFluxScore = 0.0f;
    } else if (spectralFlux < 0.15f) {
        spectralFluxScore = (spectralFlux - 0.01f) / 0.14f;
    } else {
        spectralFluxScore = 1.0f;
    }
    // Weighted average — centroid/rolloff removed (combined 0.04 weight,
    // 0-5% separation between voice and guitar — not discriminative).
    // Budget redistributed to formant/flatness (best discriminators).
    float weightedAvg = 0.33f * formantScore
                      + 0.35f * flatnessScore
                      + 0.12f * densityScore
                      + 0.10f * spectralFluxScore;
    // Accumulate all multiplicative boosts into totalBoost, then cap.
    // This prevents the theoretical 3.2x runaway when all boosts fire
    // simultaneously. Cap at 1.60x allows two boosts to stack but
    // prevents pathological cases. Synthetic signals trigger zero boosts
    // (jitter <0.15, acfIrreg <0.30), so existing tests are unaffected.
    float totalBoost = 1.0f;
    // Temporal spectral variance boost (not base score).
    // Voice has higher variance (~1.01/~0.84 in 3-way) than guitar (~0.74).
    // Applied only when variance > 0 (real multi-frame audio).
    if (spectralVariance > 0.01f) {
        float varianceBoost = 1.0f + 0.40f * (spectralVariance - 0.74f) / 0.76f;
        varianceBoost = fl::clamp(varianceBoost, 0.90f, 1.25f);
        totalBoost *= varianceBoost;
    }
    // Low-jitter penalty: very periodic signals (guitar jit=0.10) get penalized.
    // Voice jitter is always >0.50, so this only penalizes instruments.
    if (mEnvelopeJitter < 0.15f && mEnvelopeJitter > 0.001f) {
        float periodicPenalty = 1.0f - 0.25f * (0.15f - mEnvelopeJitter) / 0.15f;
        totalBoost *= periodicPenalty;
    }
    // Envelope jitter boost: only for very high jitter (>0.55).
    // Drums alone reach 0.61, so only extreme jitter gets a small boost.
    if (mEnvelopeJitter > 0.55f) {
        float jitterBoost = 1.0f + 0.8f * (mEnvelopeJitter - 0.55f);
        jitterBoost = fl::clamp(jitterBoost, 1.0f, 1.15f);
        totalBoost *= jitterBoost;
    }
    // Autocorrelation irregularity boost: only above 0.75 (above drum baseline).
    if (mAutocorrelationIrregularity > 0.75f) {
        float acfBoost = 1.0f + 1.0f * (mAutocorrelationIrregularity - 0.75f);
        acfBoost = fl::clamp(acfBoost, 1.0f, 1.25f);
        totalBoost *= acfBoost;
    }
    // Low-zcCV penalty: very regular zero-crossings (guitar zcCV=0.05) penalized.
    // Voice zcCV is always >0.30, so this only hits periodic instruments.
    if (mZeroCrossingCV < 0.10f && mZeroCrossingCV > 0.001f) {
        float zcPenalty = 1.0f - 0.20f * (0.10f - mZeroCrossingCV) / 0.10f;
        totalBoost *= zcPenalty;
    }
    // Zero-crossing CV: peaked boost for moderate values, penalty for high.
    if (mZeroCrossingCV > 0.02f) {
        float zcBoost;
        if (mZeroCrossingCV < 0.80f) {
            zcBoost = 1.0f + 0.25f * (mZeroCrossingCV - 0.10f) / 0.70f;
        } else if (mZeroCrossingCV < 1.50f) {
            zcBoost = 1.0f;
        } else {
            zcBoost = 1.0f - 0.15f * (mZeroCrossingCV - 1.50f) / 1.00f;
        }
        zcBoost = fl::clamp(zcBoost, 0.80f, 1.20f);
        totalBoost *= zcBoost;
    }
    // Combined aperiodicity-jitter boost: when BOTH indicate voice.
    if (mAutocorrelationIrregularity > 0.75f && mEnvelopeJitter > 0.55f) {
        float minExcess = fl::min(mAutocorrelationIrregularity - 0.75f,
                                   mEnvelopeJitter - 0.55f);
        float combinedBoost = 1.0f + 1.5f * minExcess;
        combinedBoost = fl::clamp(combinedBoost, 1.0f, 1.20f);
        totalBoost *= combinedBoost;
    }
    // Cap total boost chain to prevent runaway
    totalBoost = fl::clamp(totalBoost, 0.50f, 1.60f);
    weightedAvg *= totalBoost;
    // Formant gate/boost: weak formant → gate down, strong formant → mild boost.
    float formantMultiplier;
    if (formantScore < 0.40f) {
        formantMultiplier = formantScore * 2.5f;  // gate (0.0 to 1.0)
    } else {
        formantMultiplier = 1.0f + 0.40f * (formantScore - 0.40f);  // boost (1.0 to 1.24)
    }
    // Clamp final confidence to [0, 1]
    mConfidence = fl::clamp(weightedAvg * formantMultiplier, 0.0f, 1.0f);
    return mConfidence;
}
References fl::abs(), fl::clamp(), mAutocorrelationIrregularity, fl::max(), mConfidence, mEnvelopeJitter, fl::min(), and mZeroCrossingCV.
Referenced by update().