FastLED: fl::HttpResponseParser::parseStatusLine
parseStatusLine()
bool fl::HttpResponseParser::parseStatusLine () private
Definition at line 389 of file http_parser.cpp.hpp.
{
    auto crlfPos = findCRLF();
    if (!crlfPos.has_value()) {
        return false;  // Need more data
    }
    // Extract status line
    fl::string line(reinterpret_cast<const char*>(mBuffer.data()), crlfPos.value()); // ok reinterpret cast
    consume(crlfPos.value() + 2);  // +2 for CRLF
    // Parse: "VERSION STATUS_CODE REASON_PHRASE"
    size_t versionEnd = line.find(' ');
    if (versionEnd == fl::string::npos) {
        return false;  // Invalid format
    }
    size_t statusEnd = line.find(' ', versionEnd + 1);
    if (statusEnd == fl::string::npos) {
        // No reason phrase (optional in HTTP/1.1)
        statusEnd = line.size();
    }
    resp().version = line.substr(0, versionEnd);
    fl::string statusStr = line.substr(versionEnd + 1, statusEnd - versionEnd - 1);
    if (!parseInt(statusStr, resp().statusCode)) {
        return false;  // Invalid status code
    }
    if (statusEnd < line.size()) {
        resp().reasonPhrase = line.substr(statusEnd + 1);
    }
    return true;
}
References consume(), fl::basic_string::find(), findCRLF(), mBuffer, fl::string::npos, fl::parseInt(), fl::HttpResponse::reasonPhrase, resp(), fl::basic_string::size(), fl::string::substr(), and fl::HttpResponse::version.
Referenced by feed().