FastLED: fl::HttpResponseParser::feed
feed()
void fl::HttpResponseParser::feed (fl::span< const u8 > data)
Definition at line 300 of file http_parser.cpp.hpp.
{
    mBuffer.insert(mBuffer.end(), data.begin(), data.end());
    // State machine: parse incrementally
    bool progress = true;
    while (progress && mState != COMPLETE) {
        progress = false;
        switch (mState) {
            case READ_STATUS_LINE:
                if (parseStatusLine()) {
                    mState = READ_HEADERS;
                    progress = true;
                }
                break;
            case READ_HEADERS:
                if (parseHeaders()) {
                    // Check if body is expected
                    auto contentLength = getHeader("Content-Length");
                    auto transferEncoding = getHeader("Transfer-Encoding");
                    if (transferEncoding.has_value() &&
                        toLower(transferEncoding.value()).find("chunked") != fl::string::npos) {
                        mIsChunked = true;
                        mState = READ_BODY;
                    } else if (contentLength.has_value()) {
                        int contentLengthInt = 0;
                        if (parseInt(contentLength.value(), contentLengthInt)) {
                            mContentLength = static_cast<size_t>(contentLengthInt);
                            mState = READ_BODY;
                        } else {
                            // Invalid Content-Length, skip to complete
                            mState = COMPLETE;
                        }
                    } else {
                        // No body
                        mState = COMPLETE;
                    }
                    progress = true;
                }
                break;
            case READ_BODY:
                parseBody();
                // parseBody() will set mState to COMPLETE when done
                // Continue processing if state changed to COMPLETE
                if (mState == COMPLETE) {
                    progress = true;
                }
                break;
            case COMPLETE:
                // Nothing to do
                break;
        }
    }
}
References HttpResponseParser(), COMPLETE, feed(), fl::basic_string::find(), getHeader(), mBuffer, mContentLength, mIsChunked, mState, fl::string::npos, parseBody(), parseHeaders(), fl::parseInt(), parseStatusLine(), READ_BODY, READ_HEADERS, and READ_STATUS_LINE.
Referenced by ~HttpResponseParser(), and feed().