FastLED: fl::HttpResponseParser::parseHeaders
parseHeaders()
bool fl::HttpResponseParser::parseHeaders () private
Definition at line 425 of file http_parser.cpp.hpp.
{
    while (true) {
        auto crlfPos = findCRLF();
        if (!crlfPos.has_value()) {
            return false;  // Need more data
        }
        // Check for empty line (end of headers)
        if (crlfPos.value() == 0) {
            consume(2);  // Consume final CRLF
            return true;
        }
        // Extract header line
        fl::string line(reinterpret_cast<const char*>(mBuffer.data()), crlfPos.value()); // ok reinterpret cast
        consume(crlfPos.value() + 2);  // +2 for CRLF
        // Parse: "Name: Value"
        size_t colonPos = line.find(':');
        if (colonPos == fl::string::npos) {
            continue;  // Skip invalid header
        }
        fl::string name = http_parser_trim(line.substr(0, colonPos));
        fl::string value = http_parser_trim(line.substr(colonPos + 1));
        resp().headers[name] = value;
    }
}
References consume(), fl::basic_string::find(), findCRLF(), fl::HttpResponse::headers, mBuffer, fl::string::npos, resp(), fl::string::substr(), and fl::type_rank< T >::value.
Referenced by feed().