FastLED: fl::Video::begin
begin()
bool fl::Video::begin (fl::filebuf_ptr h)
Definition at line 38 of file video.cpp.hpp.
{
    if (!mImpl) {
        FL_WARN("Video::begin: mImpl is null, manually constructed videos "
                     "must include full parameters.");
        return false;
    }
    if (!handle) {
        mError = "filebuf is null";
        FL_DBG(mError.c_str());
        return false;
    }
    if (mError.size()) {
        FL_DBG(mError.c_str());
        return false;
    }
    mError.clear();
    mImpl->begin(handle);
    return true;
}
References Video(), begin(), FL_DBG, FL_WARN, mError, and mImpl.
Referenced by begin(), and operator=().