FastLED: fl::Blend2d::draw
draw()
void fl::Blend2d::draw (DrawContext context) override virtual
Parameters
now The current time in milliseconds. Fx writers are encouraged to use this instead of millis() directly as this will more deterministic behavior.
Implements fl::Fx.
Definition at line 56 of file blend.cpp.hpp.
{
    mFrame->clear();
    mFrameTransform->clear();
    // Draw each layer in reverse order and applying the blending.
    bool first = true;
    for (auto it = mLayers.begin(); it != mLayers.end(); ++it) {
        DrawContext tmp_ctx = context;
        tmp_ctx.leds = mFrame->rgb();
        auto &fx = it->fx;
        fx->draw(tmp_ctx);
        DrawMode mode = first ? DrawMode::DRAW_MODE_OVERWRITE
                              : DrawMode::DRAW_MODE_BLEND_BY_MAX_BRIGHTNESS;
        first = false;
        // Apply the blur effect per effect.
        u8 blur_amount = it->blur_amount;
        if (blur_amount > 0) {
            const XYMap &xyMap = fx->getXYMap();
            u8 blur_passes = fl::max(1, it->blur_passes);
            for (u8 i = 0; i < blur_passes; ++i) {
                // Apply the blur effect
                blur2d(mFrame->rgb().data(), mXyMap.getWidth(), mXyMap.getHeight(),
                       blur_amount, xyMap);
            }
        }
        mFrame->draw(mFrameTransform->rgb(), mode);
    }
    if (mGlobalBlurAmount > 0) {
        // Apply the blur effect
        u16 width = mXyMap.getWidth();
        u16 height = mXyMap.getHeight();
        XYMap rect = XYMap::constructRectangularGrid(width, height);
        fl::span<CRGB> rgb = mFrameTransform->rgb();
        u8 blur_passes = fl::max(1, mGlobalBlurPasses);
        for (u8 i = 0; i < blur_passes; ++i) {
            // Apply the blur effect
            blur2d(rgb, width, height, mGlobalBlurAmount, rect);
        }
    }
    // Copy the final result to the output
    // memcpy(mFrameTransform->rgb(), context.leds, sizeof(CRGB) *
    // mXyMap.getTotal());
    mFrameTransform->drawXY(context.leds, mXyMap,
                            DrawMode::DRAW_MODE_OVERWRITE);
}
References fl::blur2d(), fl::blur_amount, fl::XYMap::constructRectangularGrid(), fl::DRAW_MODE_BLEND_BY_MAX_BRIGHTNESS, fl::DRAW_MODE_OVERWRITE, fl::height, fl::DrawContext::leds, fl::max(), mFrame, mFrameTransform, mGlobalBlurAmount, mGlobalBlurPasses, mLayers, fl::Fx2d::mXyMap, fl::width, and fl::Fx2d::xyMap().