FastLED: setup
setup()
void setup ()
Definition at line 290 of file curr.h.
             {
    // Use constexpr dimensions (computed at compile time)
    constexpr int width = CORKSCREW_WIDTH;   // = 16
    constexpr int height = CORKSCREW_HEIGHT; // = 18
    // Noise controls are now automatically grouped by the fl::UIGroup constructor
    // The noiseGroup variadic constructor automatically called setGroup() on all controls
    // Or use runtime corkscrew for dynamic sizing
    // int width = corkscrew.cylinder_width();
    // int height = corkscrew.cylinder_height();
    fl::XYMap xyMap = fl::XYMap::constructRectangularGrid(width, height, 0);
    // Use the corkscrew's internal buffer for the LED strip
    CLEDController *controller =
        &FastLED.addLeds<APA102HD, PIN_DATA, PIN_CLOCK, BGR>(corkscrew.rawData(), NUM_LEDS);
    // CLEDController *controller =
    //     &FastLED.addLeds<WS2812, 3, BGR>(stripLeds, NUM_LEDS);
    // NEW: Create fl::ScreenMap directly from fl::Corkscrew using toScreenMap()
    // This maps each LED index to its exact position on the corkscrew spiral
    // instead of using a rectangular grid mapping
    fl::ScreenMap corkscrewScreenMap = corkscrew.toScreenMap(0.2f);
    // OLD WAY (rectangular grid - not accurate for corkscrew visualization):
    // fl::ScreenMap screenMap = xyMap.toScreenMap();
    // screenMap.setDiameter(.2f);
    // Set the corkscrew screen map for the controller
    // This allows the web interface to display the actual corkscrew spiral shape
    controller->setScreenMap(corkscrewScreenMap);
    // Initialize wave effects for cylindrical surface
    fl::XYMap xyRect(width, height, false); // Rectangular grid for wave simulation
    fl::WaveFx::Args waveArgs;
    waveArgs.factor = fl::SuperSample::SUPER_SAMPLE_2X;  // 2x supersampling for smoother waves
    waveArgs.half_duplex = true;                     // Only positive waves
    waveArgs.auto_updates = true;                    // Auto-update simulation
    waveArgs.speed = 0.16f;                          // Wave propagation speed
    waveArgs.dampening = 6.0f;                       // Wave energy loss
    waveArgs.x_cyclical = true;                      // Enable cylindrical wrapping!
    waveArgs.crgbMap = fl::make_shared<fl::WaveCrgbGradientMap>(waveBluepal); // Default color palette
    // Create wave effect with cylindrical mapping
    waveFx = fl::make_shared<fl::WaveFx>(xyRect, waveArgs);
    // Create blender for wave effects (allows multiple wave layers in future)
    waveBlend = fl::make_shared<fl::Blend2d>(xyRect);
    waveBlend->add(waveFx);
    // Initialize fl::Animartrix effect
    fl::XYMap animartrixXyMap = fl::XYMap::constructRectangularGrid(width, height, 0);
    animartrix.reset(new fl::Animartrix(animartrixXyMap, fl::AnimartrixAnim::POLAR_WAVES));  // ok bare allocation
    fxEngine.reset(new fl::FxEngine(width * height));  // ok bare allocation
    fxEngine->addFx(*animartrix);
    // Demonstrate fl::UIGroup functionality for noise controls
    FL_WARN("Noise UI Group initialized: " << noiseGroup.name());
    FL_WARN("  This group contains noise pattern controls:");
    FL_WARN("  - Use Noise Pattern toggle");
    FL_WARN("  - Noise Scale and Speed sliders");
    FL_WARN("  - Color Palette selection for noise");
    FL_WARN("  fl::UIGroup automatically applied group membership via variadic constructor");
    // Set initial dropdown selections
    paletteDropdown.setSelectedIndex(0);    // Party
    renderModeDropdown.setSelectedIndex(0); // Fire (new default)
    // Add onChange callbacks for dropdowns
    paletteDropdown.onChanged([](fl::UIDropdown &dropdown) {
        fl::string selectedPalette = dropdown.value();
        FL_WARN("Noise palette changed to: " << selectedPalette);
        if (selectedPalette == "Party") {
            noisePalette = PartyColors_p;
        } else if (selectedPalette == "Heat") {
            noisePalette = HeatColors_p;
        } else if (selectedPalette == "Ocean") {
            noisePalette = OceanColors_p;
        } else if (selectedPalette == "Forest") {
            noisePalette = ForestColors_p;
        } else if (selectedPalette == "Rainbow") {
            noisePalette = RainbowColors_p;
        }
    });
    renderModeDropdown.onChanged([](fl::UIDropdown &dropdown) {
        fl::string mode = dropdown.value();
        // Simple example of using getOption()
        for(size_t i = 0; i < dropdown.getOptionCount(); i++) {
            if(dropdown.getOption(i) == mode) {
                FL_WARN("Render mode changed to: " << mode);
            }
        }
    });
    // Add onChange callback for animartrix color order
    animartrixColorOrder.onChanged([](int value) {
        EOrder order = RGB;
        switch(value) {
            case 0: order = RGB; break;
            case 1: order = RBG; break;
            case 2: order = GRB; break;
            case 3: order = GBR; break;
            case 4: order = BRG; break;
            case 5: order = BGR; break;
        }
        if (animartrix.get()) {
            animartrix->setColorOrder(order);
        }
    });
    waveFx->setCrgbMap(crgMap);
    frameBufferPtr = corkscrew.getOrCreateInputSurface();
}
References animartrix, animartrixColorOrder(), APA102HD, fl::WaveFxArgs::auto_updates, BGR, BRG, fl::XYMap::constructRectangularGrid(), controller, corkscrew(), CORKSCREW_HEIGHT, CORKSCREW_WIDTH, fl::WaveFxArgs::crgbMap, crgMap, fl::WaveFxArgs::dampening, fl::WaveFxArgs::factor, FastLED, FL_WARN, ForestColors_p, frameBufferPtr, fxEngine, GBR, fl::UIDropdown::getOption(), fl::UIDropdown::getOptionCount(), GRB, fl::WaveFxArgs::half_duplex, HeatColors_p, fl::make_shared(), noiseGroup(), noisePalette, NUM_LEDS, OceanColors_p, paletteDropdown(), PartyColors_p, PIN_CLOCK, PIN_DATA, fl::POLAR_WAVES, RainbowColors_p, RBG, renderModeDropdown(), RGB, fl::WaveFxArgs::speed, fl::SUPER_SAMPLE_2X, fl::UIDropdown::value(), waveBlend, waveFx, fl::WaveFxArgs::x_cyclical, and xyMap.