FastLED: getEaseType
getEaseType()
fl::EaseType getEaseType (fl::string value)
Definition at line 129 of file curr.h.
{
    if (value == "fl::EaseType::EASE_NONE") {
        return fl::EaseType::EASE_NONE;
    } else if (value == "EASE_IN_QUAD") {
        return fl::EaseType::EASE_IN_QUAD;
    } else if (value == "EASE_OUT_QUAD") {
        return fl::EaseType::EASE_OUT_QUAD;
    } else if (value == "EASE_IN_OUT_QUAD") {
        return fl::EaseType::EASE_IN_OUT_QUAD;
    } else if (value == "EASE_IN_CUBIC") {
        return fl::EaseType::EASE_IN_CUBIC;
    } else if (value == "EASE_OUT_CUBIC") {
        return fl::EaseType::EASE_OUT_CUBIC;
    } else if (value == "EASE_IN_OUT_CUBIC") {
        return fl::EaseType::EASE_IN_OUT_CUBIC;
    } else if (value == "EASE_IN_SINE") {
        return fl::EaseType::EASE_IN_SINE;
    } else if (value == "EASE_OUT_SINE") {
        return fl::EaseType::EASE_OUT_SINE;
    } else if (value == "EASE_IN_OUT_SINE") {
        return fl::EaseType::EASE_IN_OUT_SINE;
    } else {
        return fl::EaseType::EASE_NONE;
    }
}
References fl::EASE_IN_CUBIC, fl::EASE_IN_OUT_CUBIC, fl::EASE_IN_OUT_QUAD, fl::EASE_IN_OUT_SINE, fl::EASE_IN_QUAD, fl::EASE_IN_SINE, fl::EASE_NONE, fl::EASE_OUT_CUBIC, fl::EASE_OUT_QUAD, and fl::EASE_OUT_SINE.
Referenced by draw(), fillFrameBufferFire(), and fillFrameBufferNoise().