FastLED: drawWave
drawWave()
void drawWave (uint32_t now)
Definition at line 705 of file curr.h.
{
    // Update wave parameters from UI
    waveFx->setSpeed(waveSpeed.value());
    waveFx->setDampening(waveDampening.value());
    waveFx->setHalfDuplex(waveHalfDuplex.value());
    waveFx->setXCylindrical(true); // Always keep cylindrical for corkscrew
    waveFx->setStencil(waveIsotropicStencil
                           ? fl::LaplacianStencil::NinePointIsotropic
                           : fl::LaplacianStencil::FivePoint);
    // Update wave color palette
    fl::CRGBPalette16 currentPalette = getWavePalette();
    crgMap->setGradient(currentPalette);
    // Apply blur settings to the wave blend (for smoother wave effects)
    waveBlend->setGlobalBlurAmount(waveBlurAmount.value());
    waveBlend->setGlobalBlurPasses(waveBlurPasses.value());
    // Check if manual trigger button was pressed
    if (waveTriggerButton.value()) {
        triggerWaveRipple();
    }
    // Handle auto-triggering
    processWaveAutoTrigger(now);
    // Draw the wave effect directly to the frame buffer
    // Create a DrawContext for the wave renderer
    fl::Fx::DrawContext waveContext(now, frameBufferPtr->span());
    waveBlend->draw(waveContext);
}
References crgMap, currentPalette, fl::FivePoint, frameBufferPtr, getWavePalette(), fl::NinePointIsotropic, processWaveAutoTrigger(), triggerWaveRipple(), waveBlend, waveBlurAmount(), waveBlurPasses(), waveDampening(), waveFx, waveHalfDuplex(), waveIsotropicStencil(), waveSpeed(), and waveTriggerButton().
Referenced by loop().