FastLED: loop
loop()
void loop ()
Definition at line 764 of file curr.h.
            {
    delay(4);
    uint32_t now = millis();
    frameBufferPtr->clear();
    if (allWhite) {
        CRGB whiteColor = CRGB(8, 8, 8);
        for (u32 x = 0; x < frameBufferPtr->width(); x++) {
            for (u32 y = 0; y < frameBufferPtr->height(); y++) {
                frameBufferPtr->at(x, y) = whiteColor;
            }
        }
    }
    // Update the corkscrew mapping with auto-advance or manual position control
    float combinedPosition = get_position(now);
    float pos = combinedPosition * (corkscrew.size() - 1);
    if (renderModeDropdown.value() == "Noise") {
        drawNoise(now);
    } else if (renderModeDropdown.value() == "Fire") {
        drawFire(now);
    } else if (renderModeDropdown.value() == "Wave") {
        drawWave(now);
    } else if (renderModeDropdown.value() == "Animartrix") {
        drawAnimartrix(now);
    } else {
        draw(pos);
    }
    // Use the new readFrom workflow:
    // 1. Read directly from the frameBuffer Grid into the corkscrew's internal buffer
    // use_multi_sampling = true will use multi-sampling to sample from the source grid,
    // this will give a little bit better accuracy and the screenmap will be more accurate.
    const bool use_multi_sampling = splatRendering;
    // corkscrew.readFrom(frameBuffer, use_multi_sampling);
    corkscrew.draw(use_multi_sampling);
    // The corkscrew's buffer is now populated and FastLED will display it directly
    FastLED.setBrightness(brightness.value());
    FastLED.show();
}
References allWhite(), brightness(), corkscrew(), draw(), drawAnimartrix(), drawFire(), drawNoise(), drawWave(), FastLED, frameBufferPtr, get_position(), pos, renderModeDropdown(), splatRendering(), x, and y.