FastLED: fillFrameBufferFire
fillFrameBufferFire()
void fillFrameBufferFire (uint32_t now)
Definition at line 608 of file curr.h.
{
    fl::CRGBPalette16 myPal = getFirePalette();
    // Calculate the current y-offset for animation (makes the fire move)
    uint32_t y_speed = now * fireSpeedY.value();
    int width = frameBufferPtr->width();
    int height = frameBufferPtr->height();
    // Loop through every pixel in our cylindrical matrix
    for (int w = 0; w < width; w++) {
        for (int h = 0; h < height; h++) {
            // Calculate which color to use from our palette for this pixel
            uint8_t palette_index =
                getFirePaletteIndex(now, w, width, h, height, y_speed);
            // Get the actual RGB color from the palette
            fl::CRGB color = ColorFromPalette(myPal, palette_index, 255);
            // Apply color boost using ease functions
            fl::EaseType sat_ease = getEaseType(saturationFunction.value());
            fl::EaseType lum_ease = getEaseType(luminanceFunction.value());
            color = color.colorBoost(sat_ease, lum_ease);
            // Set the pixel in the frame buffer
            // Flip coordinates to make fire rise from bottom
            frameBufferPtr->at((width - 1) - w, (height - 1) - h) = color;
        }
    }
}
References fl::CRGB::colorBoost(), ColorFromPalette(), fireSpeedY(), frameBufferPtr, getEaseType(), getFirePalette(), getFirePaletteIndex(), luminanceFunction(), saturationFunction(), and y_speed.
Referenced by drawFire().