FastLED: get_position
get_position()
FL_OPTIMIZATION_LEVEL_O0_BEGIN float get_position (uint32_t now)
Definition at line 413 of file curr.h.
{
    if (autoAdvance.value()) {
        // Check if auto-advance was just enabled
        // Auto-advance mode: increment smoothly from current position
        float elapsedSeconds = float(now - lastUpdateTime) / 1000.0f;
        float increment = elapsedSeconds * speed.value() *
                          0.3f; // Make it 1/20th the original speed
        currentPosition = fl::fmodf(currentPosition + increment, 1.0f);
        lastUpdateTime = now;
        return currentPosition;
    } else {
        // Manual mode: use the dual slider control
        float combinedPosition = positionCoarse.value() + positionFine.value() + positionExtraFine.value();
        // Clamp to ensure we don't exceed 1.0
        if (combinedPosition > 1.0f)
            combinedPosition = 1.0f;
        return combinedPosition;
    }
}
References autoAdvance(), currentPosition, fl::fmodf(), lastUpdateTime, positionCoarse(), positionExtraFine(), positionFine(), and speed.
Referenced by loop().