FastLED: processWaveAutoTrigger
processWaveAutoTrigger()
void processWaveAutoTrigger (uint32_t now)
Definition at line 694 of file curr.h.
{
    // Handle automatic wave triggering
    if (waveAutoTrigger.value()) {
        if (now >= nextWaveTrigger) {
            triggerWaveRipple();
            // Calculate next trigger time based on speed
            float speed = 1.0f - waveTriggerSpeed.value();
            uint32_t min_interval = (uint32_t)(500 * speed);   // Minimum 500ms * speed
            uint32_t max_interval = (uint32_t)(3000 * speed);  // Maximum 3000ms * speed
            // Ensure valid range
            uint32_t min = MIN(min_interval, max_interval);
            uint32_t max = MAX(min_interval, max_interval);
            if (min >= max) max = min + 1;
            nextWaveTrigger = now + random16(min, max);
        }
    }
}
References MAX, MIN, nextWaveTrigger, random16(), speed, triggerWaveRipple(), waveAutoTrigger(), and waveTriggerSpeed().
Referenced by drawWave().