FastLED: getFirePaletteIndex
getFirePaletteIndex()
uint8_t getFirePaletteIndex (uint32_t millis32, int width, int max_width, int height, int max_height, uint32_t y_speed)
Definition at line 592 of file curr.h.
{
    uint16_t scale = fireScaleXY.as<uint16_t>();
    float xf = (float)width / (float)max_width;
    uint8_t x = (uint8_t)(xf * 255);
    uint32_t cosx = cos8(x);
    uint32_t sinx = sin8(x);
    float trig_scale = scale * fireScaleX.value();
    cosx *= trig_scale;
    sinx *= trig_scale;
    uint32_t y = height * scale + y_speed;
    uint16_t z = millis32 / fireInvSpeedZ.as<uint16_t>();
    uint16_t noise16 = inoise16(cosx << 8, sinx << 8, y << 8, z << 8);
    uint8_t noise_val = noise16 >> 8;
    int8_t subtraction_factor = abs8(height - (max_height - 1)) * 255 /
                                (max_height - 1);
    return qsub8(noise_val, subtraction_factor);
}
References abs8(), cos8(), fireInvSpeedZ(), fireScaleX(), fireScaleXY(), inoise16(), qsub8(), scale, sin8, x, y, y_speed, and z.
Referenced by fillFrameBufferFire().