FastLED: drawAnimartrix
drawAnimartrix()
void drawAnimartrix (uint32_t now)
Definition at line 748 of file curr.h.
{
    // Update animartrix parameters from UI
    fxEngine->setSpeed(animartrixTimeSpeed.value());
    // Handle animation index changes
    static int lastAnimartrixIndex = -1;
    if (animartrixIndex.value() != lastAnimartrixIndex) {
        lastAnimartrixIndex = animartrixIndex.value();
        animartrix->fxSet(animartrixIndex.value());
    }
    // Draw the animartrix effect directly to the frame buffer
    CRGB* dst = corkscrew.rawData();
    fxEngine->draw(now, dst);
}
References animartrix, animartrixIndex(), animartrixTimeSpeed(), corkscrew(), and fxEngine.
Referenced by loop().