FastLED: draw
draw()
void draw (float pos)
Examples
FxNoiseRing.ino.
Definition at line 526 of file curr.h.
                     {
    if (splatRendering) {
        fl::Tile2x2_u8_wrap pos_tile = corkscrew.at_wrap(pos);
        //FL_WARN("pos_tile: " << pos_tile);
        fl::CRGB color = fl::CRGB::Blue;
        // Apply color boost using ease functions
        fl::EaseType sat_ease = getEaseType(saturationFunction.value());
        fl::EaseType lum_ease = getEaseType(luminanceFunction.value());
        color = color.colorBoost(sat_ease, lum_ease);
        // Draw each pixel in the 2x2 tile using the new wrapping API
        for (int dx = 0; dx < 2; ++dx) {
            for (int dy = 0; dy < 2; ++dy) {
                fl::Tile2x2_u8_wrap::Entry data = pos_tile.at(dx, dy);
                fl::vec2<fl::u16> wrapped_pos = data.first; // Already wrapped position
                uint8_t alpha = data.second;      // Alpha value
                if (alpha > 0) { // Only draw if there's some alpha
                    fl::CRGB c = color;
                    c.nscale8(alpha); // Scale the color by the alpha value
                    frameBufferPtr->at(wrapped_pos.x, wrapped_pos.y) = c;
                }
            }
        }
    } else {
        // None splat rendering, looks aweful.
        fl::vec2f pos_vec2f = corkscrew.at_no_wrap(pos);
        fl::vec2<fl::u16> pos_i16 = fl::vec2<fl::u16>(pos_vec2f.x, pos_vec2f.y);
        fl::CRGB color = fl::CRGB::Blue;
        // Apply color boost using ease functions
        fl::EaseType sat_ease = getEaseType(saturationFunction.value());
        fl::EaseType lum_ease = getEaseType(luminanceFunction.value());
        color = color.colorBoost(sat_ease, lum_ease);
        // Now map the cork screw position to the cylindrical buffer that we
        // will draw.
        frameBufferPtr->at(pos_i16.x, pos_i16.y) = color; // Draw a blue pixel at (w, h)
    }
}
References fl::Tile2x2_u8_wrap::at(), fl::CRGB::Blue, fl::CRGB::colorBoost(), corkscrew(), fl::pair< T1, T2 >::first, frameBufferPtr, getEaseType(), luminanceFunction(), fl::CRGB::nscale8(), pos, saturationFunction(), fl::pair< T1, T2 >::second, splatRendering(), fl::vec2< T >::x, and fl::vec2< T >::y.
Referenced by fl::XYRasterSparse_RGB8::draw(), and loop().