FastLED: fl::CLEDController::visitControllers
visitControllers()
template<typename Visitor> static void fl::CLEDController::visitControllers (Visitor && visitor) inline static
Visit all controllers in the linked list with a visitor The visitor must be a callable that accepts (const CLEDController*, fl::span<const CRGB>)
Parameters
visitor the visitor callable to call for each controller
Template Parameters
Visitor callable type (function, lambda, functor, etc.)
Definition at line 220 of file cled_controller.h.
{
        const CLEDController *pCur = head();
        while(pCur) {
            visitor(pCur, fl::span<const CRGB>(pCur->leds(), pCur->size()));
            pCur = pCur->next();
        }
    }
References CLEDController(), FL_NOEXCEPT, head(), leds(), next(), and size().
Referenced by CFastLED::getEstimatedPowerInMilliWatts().