FastLED: DriverTestRunner::validateExpectedDrivers
validateExpectedDrivers()
void DriverTestRunner::validateExpectedDrivers () inline private
Validate that all expected drivers are present.
Definition at line 153 of file TestRunner.h.
{
        fl::vector<const char*> expected;
        getExpectedDrivers(expected);
        if (expected.empty()) {
            Serial.println("\n[WARNING] Unknown platform - skipping driver validation");
            return;
        }
        fl::sstream ss;
        ss << BOX_TOP;
        ss << "| DRIVER VALIDATION FOR " << getPlatformName() << "\n";
        ss << BOX_BOTTOM;
        Serial.print(ss.str().c_str());
        // Get available drivers from FastLED
        auto drivers = FastLED.getDriverInfos();
        // Print expected drivers
        ss.clear();
        ss << "\nExpected drivers (" << expected.size() << "):\n";
        for (fl::size i = 0; i < expected.size(); i++) {
            ss << "  - " << expected[i] << "\n";
        }
        Serial.print(ss.str().c_str());
        // Print available drivers with details
        ss.clear();
        ss << "\nAvailable drivers (" << drivers.size() << "):\n";
        for (fl::size i = 0; i < drivers.size(); i++) {
            ss << "  - " << drivers[i].name.c_str()
               << " (priority: " << drivers[i].priority
               << ", enabled: " << (drivers[i].enabled ? "yes" : "no") << ")\n";
        }
        Serial.print(ss.str().c_str());
        // Check each expected driver is present
        Serial.println("\nValidation results:");
        for (fl::size i = 0; i < expected.size(); i++) {
            const char* expName = expected[i];
            bool found = false;
            for (fl::size j = 0; j < drivers.size(); j++) {
                if (fl::strcmp(drivers[j].name.c_str(), expName) == 0) {
                    found = true;
                    break;
                }
            }
            fl::sstream resultMsg;
            resultMsg << expName << " driver " << (found ? "found" : "MISSING!");
            recordResult(resultMsg.str().c_str(), found);
        }
    }
References BOX_BOTTOM, BOX_TOP, fl::basic_string::c_str(), fl::sstream::c_str(), fl::sstream::clear(), fl::vector_basic::empty(), FastLED, getExpectedDrivers(), getPlatformName(), recordResult(), Serial, fl::vector_basic::size(), fl::sstream::str(), and fl::strcmp().
Referenced by runAllTests().