FastLED: DriverTestRunner::printSummary
printSummary()
void DriverTestRunner::printSummary () inline
Print final test summary with pass/fail status.
Definition at line 81 of file TestRunner.h.
{
        fl::sstream ss;
        ss << BOX_TOP;
        if (mAllTestsPassed) {
            ss << "|         ALL TESTS PASSED                                       |\n";
        } else {
            ss << "|         SOME TESTS FAILED                                      |\n";
        }
        ss << BOX_MID;
        ss << "| Platform: " << getPlatformName() << "\n";
        ss << "| Tests:    " << mPassedTests << "/" << mTotalTests << " passed\n";
        ss << BOX_BOTTOM;
        Serial.print(ss.str().c_str());
        // Machine-readable output for automated testing
        if (mAllTestsPassed) {
            Serial.println("\nTEST_SUITE_COMPLETE: PASS");
        } else {
            Serial.println("\nTEST_SUITE_COMPLETE: FAIL");
        }
    }
References BOX_BOTTOM, BOX_MID, BOX_TOP, fl::basic_string::c_str(), getPlatformName(), mAllTestsPassed, mPassedTests, mTotalTests, Serial, and fl::sstream::str().
Referenced by setup().