FastLED: DriverTestRunner::testSingleDriver
testSingleDriver()
bool DriverTestRunner::testSingleDriver (const char * driverName) inline private
Test a single driver with LED patterns.
Parameters
driverName Name of driver to test
Returns
true if driver was tested successfully
Definition at line 258 of file TestRunner.h.
{
        fl::sstream ss;
        ss << "\n" << LINE_SEP;
        ss << "Testing driver: " << driverName << "\n";
        ss << LINE_SEP;
        Serial.print(ss.str().c_str());
        // Attempt to set this driver as exclusive. `driverName` is a runtime
        // string (the test iterates over discovered drivers by name), so we use
        // the by-name escape hatch on ChannelManager rather than the typed
        // FastLED.setExclusiveDriver(fl::Bus) overload. Make sure every driver
        // is enrolled first so the lookup can succeed.
        FastLED.enableAllDrivers();
        if (!fl::ChannelManager::instance().setExclusiveDriverByName(driverName)) {
            Serial.print("  [SKIP] Could not set ");
            Serial.print(driverName);
            Serial.println(" as exclusive driver (not available)");
            return false;
        }
        Serial.print("  [INFO] ");
        Serial.print(driverName);
        Serial.println(" set as exclusive driver");
        // Run visual test patterns
        runTestPatterns();
        // Record success
        fl::sstream resultMsg;
        resultMsg << driverName << " driver test completed";
        recordResult(resultMsg.str().c_str(), true);
        return true;
    }
References fl::basic_string::c_str(), FastLED, fl::ChannelManager::instance(), LINE_SEP, recordResult(), runTestPatterns(), Serial, and fl::sstream::str().
Referenced by testAllDrivers().