FastLED: fl::CLEDController::beginShowLeds
beginShowLeds()
virtual void * fl::CLEDController::beginShowLeds (int size) inline virtual
Reimplemented in RGBWEmulatedController< CONTROLLER, RGB_ORDER >.
Definition at line 315 of file cled_controller.h.
{
        FASTLED_UNUSED(size);
        // By default, emit an integer. This integer will, by default, be passed back.
        // If you override beginShowLeds() then
        // you should also override endShowLeds() to match the return state.
        //
        // For async led controllers this should be used as a sync point to block
        // the caller until the leds from the last draw frame have completed drawing.
        // for each controller:
        //   beginShowLeds();
        // for each controller:
        //   showLeds();
        // for each controller:
        //   endShowLeds();
        uintptr_t d = getDither();
        void* out = fl::int_to_ptr<void>(d);
        return out;
    }
References FASTLED_UNUSED, FL_NOEXCEPT, getDither(), fl::int_to_ptr(), and size().
Referenced by CFastLED::show(), CFastLED::showColor(), and showLeds().