FastLED: fl::CLEDController::endShowLeds
endShowLeds()
virtual void fl::CLEDController::endShowLeds (void * data) inline virtual
Reimplemented in RGBWEmulatedController< CONTROLLER, RGB_ORDER >.
Definition at line 334 of file cled_controller.h.
{
        // By default recieves the integer that beginShowLeds() emitted.
        //For async controllers this should be used to signal the controller
        // to begin transmitting the current frame to the leds.
        uintptr_t d = fl::ptr_to_int(data);
        setDither(static_cast<fl::u8>(d));
    }
References FL_NOEXCEPT, fl::ptr_to_int(), and setDither().
Referenced by CFastLED::show(), CFastLED::showColor(), and showLeds().