FastLED: fl::CLEDController::size
size()
virtual int fl::CLEDController::size () const inline virtual
How many LEDs does this controller manage?
Returns
CLEDController::mLeds.size()
Reimplemented in fl::Channel.
Definition at line 263 of file cled_controller.h.
{ return mLeds.size(); }
References FL_NOEXCEPT, and mLeds.
Referenced by beginShowLeds(), RGBWEmulatedController< CONTROLLER, RGB_ORDER >::beginShowLeds(), calculate_max_brightness_for_power_mW(), RGBWEmulatedController< CONTROLLER, RGB_ORDER >::ControllerT::callBeginShowLeds(), fl::Channel::leds(), fl::Channel::leds(), CFastLED::show(), CFastLED::showColor(), fl::Channel::size(), and visitControllers().