FastLED: DriverTestRunner::testAllDrivers
testAllDrivers()
void DriverTestRunner::testAllDrivers () inline private
Test all available drivers.
Definition at line 213 of file TestRunner.h.
{
        auto drivers = FastLED.getDriverInfos();
        fl::sstream ss;
        ss << BOX_TOP;
        ss << "| TESTING ALL AVAILABLE DRIVERS                                  |\n";
        ss << BOX_BOTTOM;
        Serial.print(ss.str().c_str());
        Serial.print("Found ");
        Serial.print(drivers.size());
        Serial.println(" driver(s) to test\n");
        int tested = 0;
        int skipped = 0;
        for (fl::size i = 0; i < drivers.size(); i++) {
            const char* name = drivers[i].name.c_str();
            if (drivers[i].name.empty()) {
                Serial.println("  [SKIP] Unnamed driver");
                skipped++;
                continue;
            }
            if (testSingleDriver(name)) {
                tested++;
            } else {
                skipped++;
            }
            delay(500);  // Brief pause between driver tests
        }
        Serial.print("\n");
        Serial.print(LINE_SEP);
        Serial.print("Driver tests complete: ");
        Serial.print(tested);
        Serial.print(" tested, ");
        Serial.print(skipped);
        Serial.println(" skipped");
    }
References BOX_BOTTOM, BOX_TOP, fl::basic_string::c_str(), FastLED, LINE_SEP, Serial, fl::sstream::str(), and testSingleDriver().
Referenced by runAllTests().