FastLED: DriverTestRunner::runTestPatterns
runTestPatterns()
void DriverTestRunner::runTestPatterns () inline private
Run visual LED test patterns.
Definition at line 294 of file TestRunner.h.
{
        // Clear first
        fill_solid(mLeds, mNumLeds, CRGB::Black);
        FastLED.show();
        delay(50);
        // Pattern 1: Rainbow gradient
        Serial.println("  [INFO] Sending rainbow pattern...");
        fill_rainbow(mLeds, mNumLeds, 0, 256 / mNumLeds);
        FastLED.show();
        delay(100);
        // Pattern 2: Solid red
        Serial.println("  [INFO] Sending solid red...");
        fill_solid(mLeds, mNumLeds, CRGB::Red);
        FastLED.show();
        delay(100);
        // Pattern 3: Solid green
        Serial.println("  [INFO] Sending solid green...");
        fill_solid(mLeds, mNumLeds, CRGB::Green);
        FastLED.show();
        delay(100);
        // Pattern 4: Solid blue
        Serial.println("  [INFO] Sending solid blue...");
        fill_solid(mLeds, mNumLeds, CRGB::Blue);
        FastLED.show();
        delay(100);
        // Clear for next test
        fill_solid(mLeds, mNumLeds, CRGB::Black);
        FastLED.show();
    }
References fl::CRGB::Black, fl::CRGB::Blue, FastLED, fill_rainbow(), fill_solid(), fl::CRGB::Green, mLeds, mNumLeds, fl::CRGB::Red, and Serial.
Referenced by testSingleDriver().