FastLED: qadd8
qadd8()
LIB8STATIC_ALWAYS_INLINE uint8_t qadd8 (uint8_t i, uint8_t j)
Add one byte to another, saturating at 0xFF.
Parameters
i first byte to add
j second byte to add
Returns
the sum of i + j, capped at 0xFF
Examples
Fire2012.ino, Fire2012WithPalette.ino, and Pacifica.ino.
Definition at line 31 of file math8.h.
{
#if QADD8_C == 1
    unsigned int t = i + j;
    if (t > 255)
        t = 255;
    return t;
#elif QADD8_AVRASM == 1
    asm volatile(
        /* First, add j to i, conditioning the C flag */
        "add %0, %1    \n\t"
        /* Now test the C flag.
        If C is clear, we branch around a load of 0xFF into i.
        If C is set, we go ahead and load 0xFF into i.
        */
        "brcc L_%=     \n\t"
        "ldi %0, 0xFF  \n\t"
        "L_%=: "
        : "+d"(i) // r16-r31, restricted by ldi
        : "r"(j));
    return i;
#elif QADD8_ARM_DSP_ASM == 1
    asm volatile("uqadd8 %0, %0, %1" : "+r"(i) : "r"(j));
    return i;
#else
#error "No implementation for qadd8 available."
#endif
}
References LIB8STATIC_ALWAYS_INLINE.
Referenced by CRGB::addToRGB(), PixelController< RGB_ORDER, LANES, MASK >::dither(), PixelController< RGB_ORDER, LANES, MASK >::dither(), fl::Fire2012::draw(), fill_raw_2dnoise16into8(), fill_raw_noise8(), fl::NoisePalette::fillnoise8(), Fire2012(), Fire2012WithPalette(), inoise8(), inoise8(), inoise8(), operator+(), CRGB::operator+=(), fl::Pacifica::pacifica_add_whitecaps(), pacifica_add_whitecaps(), rgb2hsv_approximate(), and wu_water().