FastLED: draw
draw()
void draw (uint32_t now)
Definition at line 628 of file FxNoiseRing.h.
{
    // Configure plasma parameters from UI controls with enhanced scaling
    PlasmaParams plasma_params;
    plasma_params.time_scale = timescale.as<float>();
    plasma_params.noise_intensity = scale.as<float>() * 0.8f; // Slightly reduce for better visual balance
    plasma_params.brightness = brightness.as<float>();
    plasma_params.time_bitshift = timeBitshift.as<int>();
    plasma_params.hue_offset = (now / 100) % 256; // Slow hue rotation for extra dynamism
    plasma_params.noise_amplitude = 0.6f + 0.4f * sin(now * 0.001f); // Breathing noise effect
    // Update palette manager with auto-cycling and manual control
    palette_manager.update(now, autoPalette.value(), getPaletteIndex(palettes.value()));
    // Update variant manager with enhanced parameters
    variant_manager.update(now, autoCycle.value(), getVariantIndex(variants.value()), plasma_params);
    // KICKASS rendering with performance optimizations
    for (int i = 0; i < NUM_LEDS; i++) {
        RingCoord coord = ring_lut.fastRingCoord(i);
        CRGB pixel_color = variant_manager.renderPixel(coord, now);
        // Apply global brightness and gamma correction for better visual quality
        float global_brightness = brightness.as<float>();
        pixel_color.r = (uint8_t)(pixel_color.r * global_brightness);
        pixel_color.g = (uint8_t)(pixel_color.g * global_brightness);
        pixel_color.b = (uint8_t)(pixel_color.b * global_brightness);
        leds[i] = pixel_color;
    }
    // Optional: Add subtle sparkle overlay for extra visual interest
    EVERY_N_MILLISECONDS(50) {
        // Add random sparkles to 1% of LEDs
        int sparkle_count = NUM_LEDS / 100 + 1;
        for (int s = 0; s < sparkle_count; s++) {
            int sparkle_pos = random16() % NUM_LEDS;
            if (random8() > 250) { // Very rare sparkles
                leds[sparkle_pos] = blend(leds[sparkle_pos], CRGB::White, 128);
            }
        }
    }
}
References autoCycle(), autoPalette(), fl::blend(), brightness(), PlasmaParams::brightness, EVERY_N_MILLISECONDS, getPaletteIndex(), getVariantIndex(), PlasmaParams::hue_offset, leds, PlasmaParams::noise_amplitude, PlasmaParams::noise_intensity, NUM_LEDS, palette_manager, palettes(), random16(), random8(), ring_lut, scale, PlasmaParams::time_bitshift, PlasmaParams::time_scale, timeBitshift(), timescale(), variant_manager(), variants(), and CRGB::White.
Referenced by loop().