FastLED: drawFireDance
drawFireDance()
CRGB drawFireDance (const RingCoord & coord, uint32_t time_ms, ColorPaletteManager & palette)
Definition at line 354 of file FxNoiseRing.h.
{
    float vertical_component = sin(coord.angle) * 0.5f + 0.5f;
    float flame_x = coord.x * 1500;
    float flame_y = coord.y * 1500 + time_ms * 0.003f;
    uint16_t turbulence = inoise16(flame_x, flame_y, time_ms);
    float flame_intensity = (turbulence / 65536.0f) * (1.0f - vertical_component * 0.3f);
    float fire_hue = flame_intensity * 0.15f; // Red to orange range
    return palette.mapColor(fire_hue, flame_intensity);
}
References RingCoord::angle, inoise16(), palette(), RingCoord::x, and RingCoord::y.
Referenced by NoiseVariantManager::renderVariant().