FastLED: drawLavaLamp
drawLavaLamp()
CRGB drawLavaLamp (const RingCoord & coord, uint32_t time_ms, ColorPaletteManager & palette)
Definition at line 281 of file FxNoiseRing.h.
{
    float slow_time = time_ms * 0.0002f;
    float blob_scale = 800;
    uint16_t primary_noise = inoise16(coord.x * blob_scale, coord.y * blob_scale, slow_time * 1000);
    uint16_t secondary_noise = inoise16(coord.x * blob_scale * 0.5f, coord.y * blob_scale * 0.5f, slow_time * 1500);
    float blob_value = (primary_noise + secondary_noise * 0.3f) / 65536.0f;
    if (blob_value > 0.6f) {
        // Hot blob center
        float intensity = (blob_value - 0.6f) / 0.4f;
        return palette.mapColor(0.1f, intensity); // Warm colors
    } else if (blob_value > 0.3f) {
        // Blob edge gradient
        float edge_factor = (blob_value - 0.3f) / 0.3f;
        return palette.mapColor(0.2f, edge_factor);
    } else {
        // Background
        return palette.mapColor(0.8f, 0.2f); // Cool background
    }
}
References inoise16(), palette(), RingCoord::x, and RingCoord::y.
Referenced by NoiseVariantManager::renderVariant().