FastLED: drawGlitchCity
drawGlitchCity()
CRGB drawGlitchCity (const RingCoord & coord, uint32_t time_ms, ColorPaletteManager & palette)
Definition at line 323 of file FxNoiseRing.h.
{
    uint32_t glitch_time = (time_ms / 100) * 100; // Quantize time
    uint16_t noise1 = inoise16(coord.x * 3000, coord.y * 3000, glitch_time);
    uint16_t noise2 = inoise16(coord.x * 5000, coord.y * 5000, glitch_time + 1000);
    uint16_t glitch_value = noise1 ^ noise2; // XOR for harsh digital effects
    if ((glitch_value & 0xF000) == 0xF000) {
        return CRGB(255, 255, 255); // Full-bright glitch flash
    }
    float intensity = (glitch_value & 0xFF) / 255.0f;
    float hue_chaos = ((glitch_value >> 8) & 0xFF) / 255.0f;
    return palette.mapColor(hue_chaos, intensity, 0.5f);
}
References inoise16(), noise2, palette(), RingCoord::x, and RingCoord::y.
Referenced by NoiseVariantManager::renderVariant().