FastLED: loop
loop()
void loop ()
Definition at line 671 of file FxNoiseRing.h.
            {
    // Allow the dither to be enabled and disabled.
    controller->setDither(useDither ? BINARY_DITHER : DISABLE_DITHER);
    uint32_t now = millis();
    uint8_t bri = pir.transition(now);
    FastLED.setBrightness(bri * brightness.as<float>());
    // Apply leds generation to the leds.
    draw(now);
    FastLED.show();
}
References BINARY_DITHER, brightness(), controller, DISABLE_DITHER, draw(), FastLED, pir(), and useDither().