FastLED: drawDigitalRain
drawDigitalRain()
CRGB drawDigitalRain (const RingCoord & coord, uint32_t time_ms, ColorPaletteManager & palette)
Definition at line 304 of file FxNoiseRing.h.
{
    float vertical_pos = sin(coord.angle) * 0.5f + 0.5f;
    float cascade_speed = 0.002f;
    float time_offset = time_ms * cascade_speed;
    int stream_id = (int)(coord.angle * 10) % 8;
    float stream_phase = fmod(vertical_pos + time_offset + stream_id * 0.125f, 1.0f);
    uint16_t noise = inoise16(stream_id * 1000, stream_phase * 10000, time_ms / 4);
    uint8_t digital_value = (noise >> 8) > 128 ? 255 : 0;
    if (digital_value > 0) {
        float intensity = 1.0f - stream_phase * 0.8f; // Fade trailing
        return palette.mapColor(0.4f, intensity); // Matrix green area
    } else {
        return CRGB::Black;
    }
}
References RingCoord::angle, CRGB::Black, inoise16(), noise, and palette().
Referenced by NoiseVariantManager::renderVariant().