FastLED: fl::audio::detector::BuildupDetector::update
update()
void fl::audio::detector::BuildupDetector::update (shared_ptr< Context > context) override virtual
Implements fl::audio::Detector.
Definition at line 40 of file buildup.cpp.hpp.
{
    if (!context) {
        FL_WARN("BuildupDetector::update: null context");
        return;
    }
    mRetainedFFT = context->getFFT(32);
    const fft::Bins& fft = *mRetainedFFT;
    float rms = context->getRMS();
    float treble = getTrebleEnergy(fft);
    u32 timestamp = context->getTimestamp();
    // Update history and SG filters
    updateEnergyHistory(rms);
    updateTrebleHistory(treble);
    mEnergySG.update(rms);
    mTrebleSG.update(treble);
    // Calculate trends
    float energyTrend = calculateEnergyTrend();
    float trebleTrend = calculateTrebleTrend();
    // Calculate buildup intensity
    float intensity = calculateBuildupIntensity(energyTrend, trebleTrend, rms);
    if (!mBuildupActive) {
        // Check if we should start a buildup
        if (shouldStartBuildup(intensity)) {
            mBuildupActive = true;
            mPeakFired = false;
            mCurrentBuildup.timestamp = timestamp;
            mCurrentBuildup.intensity = intensity;
            mCurrentBuildup.progress = 0.0f;
            mCurrentBuildup.duration = 0;
            mCurrentBuildup.active = true;
            FL_DBG("BuildupDetector: Buildup started (intensity=" << intensity << ")");
            mFireBuildupStart = true;
        }
    } else {
        // Update existing buildup
        mCurrentBuildup.duration = timestamp - mCurrentBuildup.timestamp;
        mCurrentBuildup.intensity = intensity;
        // Calculate progress (0.0 to 1.0)
        float normalizedDuration = static_cast<float>(mCurrentBuildup.duration) / static_cast<float>(mMaxDuration);
        mCurrentBuildup.progress = fl::min(1.0f, normalizedDuration);
        // Check if we've reached peak (just before drop)
        if (!mPeakFired && shouldPeak()) {
            mPeakFired = true;
            FL_DBG("BuildupDetector: Peak reached");
            mFireBuildupPeak = true;
        }
        // Set progress callback flag
        mFireBuildupProgress = true;
        // Set general buildup callback flag
        mFireBuildup = true;
        // Check if buildup should end
        if (shouldEndBuildup()) {
            FL_DBG("BuildupDetector: Buildup ended (duration=" << mCurrentBuildup.duration << "ms)");
            mBuildupActive = false;
            mCurrentBuildup.active = false;
            mFireBuildupEnd = true;
        }
    }
    mPrevEnergy = rms;
    mPrevTreble = treble;
    mLastUpdateTime = timestamp;
}
References BuildupDetector(), calculateBuildupIntensity(), calculateEnergyTrend(), calculateTrebleTrend(), FL_DBG, FL_WARN, getTrebleEnergy(), mBuildupActive, mCurrentBuildup, mEnergySG, mFireBuildup, mFireBuildupEnd, mFireBuildupPeak, mFireBuildupProgress, mFireBuildupStart, fl::min(), mLastUpdateTime, mMaxDuration, mPeakFired, mPrevEnergy, mPrevTreble, mRetainedFFT, mTrebleSG, rms(), shouldEndBuildup(), shouldPeak(), shouldStartBuildup(), update(), updateEnergyHistory(), and updateTrebleHistory().
Referenced by ~BuildupDetector(), and update().