FastLED: fl::audio::detector::BuildupDetector::calculateBuildupIntensity
calculateBuildupIntensity()
float fl::audio::detector::BuildupDetector::calculateBuildupIntensity (float energyTrend, float trebleTrend, float rms) const private
Definition at line 202 of file buildup.cpp.hpp.
{
    // Buildup intensity is a combination of:
    // - Energy rise trend (50%)
    // - Treble rise trend (30%)
    // - Overall energy level (20%)
    float normalizedEnergy = fl::min(1.0f, rms);
    float normalizedEnergyTrend = energyTrend / 2.0f;  // Normalize from [0, 2] to [0, 1]
    float normalizedTrebleTrend = trebleTrend / 2.0f;
    float intensity = normalizedEnergyTrend * 0.5f +
                      normalizedTrebleTrend * 0.3f +
                      normalizedEnergy * 0.2f;
    return fl::max(0.0f, fl::min(1.0f, intensity));
}
References fl::max(), fl::min(), and rms().
Referenced by update().