FastLED: fl::third_party::TJpgInstanceDecoder::processChunk
processChunk()
bool fl::third_party::TJpgInstanceDecoder::processChunk ()
Definition at line 140 of file driver.cpp.hpp.
{
    if (state_ == State::Complete || state_ == State::Error) {
        return false;
    }
    if (state_ == State::HeaderParsed) {
        state_ = State::Decoding;
    }
    startTick();
    if (use_progressive_) {
        // Progressive decoding with time budget
        fl::u8 more_data_needed = 0;
        fl::u8 processing_complete = 0;
        JRESULT res = jd_decomp_progressive(
            &progressive_state_,
            outputCallback,
            embedded_tjpg_.jpg_scale,
            progressive_config_.max_mcus_per_tick,
            &more_data_needed,
            &processing_complete
        );
        if (processing_complete) {
            state_ = State::Complete;
            progress_ = 1.0f;
            return false;
        }
        if (res == (JRESULT)JDR_SUSPEND) {
            // Time budget exceeded, more work remains
            // Update progress
            if (progressive_state_.total_mcus > 0) {
                progress_ = (float)progressive_state_.mcus_processed /
                           (float)progressive_state_.total_mcus;
            }
            return true; // More work to do
        }
        if (res != JDR_OK) {
            char err_str[32];
            fl::snprintf(err_str, sizeof(err_str), "Progressive decode error: %d", (int)res);
            setError(err_str);
            return false;
        }
        return true; // Continue processing
    } else {
        // Non-progressive decoding (all at once)
        JDEC* jdec = reinterpret_cast<JDEC*>(embedded_tjpg_.workspace);
        JRESULT res = jd_decomp(jdec, outputCallback, embedded_tjpg_.jpg_scale);
        if (res == JDR_OK) {
            // Check if any pixels were actually set by sampling the first pixel
            CRGB* pixels = current_frame_->rgb().data();
            fl::u8 first_pixel_sum = 0;
            if (pixels) {
                first_pixel_sum = pixels[0].r + pixels[0].g + pixels[0].b;
            }
            char debug_str[64];
            fl::snprintf(debug_str, sizeof(debug_str), "JPEG decode OK, first_pixel_sum=%d", first_pixel_sum);
            // If no pixels were set, this indicates the output callback wasn't called
            if (first_pixel_sum == 0) {
                setError("JPEG decode succeeded but output callback was not called");
                return false;
            }
            state_ = State::Complete;
            progress_ = 1.0f;
            return false; // Complete
        } else {
            char err_str[32];
            fl::snprintf(err_str, sizeof(err_str), "Decode error: %d", (int)res);
            setError(err_str);
            return false;
        }
    }
}
References Complete, current_frame_, Decoding, embedded_tjpg_, Error, FL_NOEXCEPT, HeaderParsed, fl::third_party::jd_decomp(), fl::third_party::jd_decomp_progressive(), fl::third_party::JDR_OK, fl::third_party::JDR_SUSPEND, outputCallback(), progress_, progressive_config_, progressive_state_, setError(), fl::snprintf(), startTick(), state_, and use_progressive_.