FastLED: fl::third_party::TJpgInstanceDecoder::initializeDecoder
initializeDecoder()
bool fl::third_party::TJpgInstanceDecoder::initializeDecoder () private
Definition at line 85 of file driver.cpp.hpp.
{
    // Create JDEC instance in our workspace
    JDEC* jdec = reinterpret_cast<JDEC*>(embedded_tjpg_.workspace);
    // Calculate working memory pool (after JDEC struct)
    fl::size jdec_size = sizeof(JDEC);
    fl::u8* pool = embedded_tjpg_.workspace + jdec_size;
    fl::size pool_size = sizeof(embedded_tjpg_.workspace) - jdec_size;
    // Prepare decoder with our input callback
    JRESULT res = jd_prepare(jdec, inputCallback, pool, pool_size, &embedded_tjpg_);
    if (res != JDR_OK) {
        char err_str[32];
        fl::snprintf(err_str, sizeof(err_str), "jd_prepare failed: %d", (int)res);
        setError(err_str);
        return false;
    }
    // Get image dimensions
    fl::u16 width = jdec->width;
    fl::u16 height = jdec->height;
    // Apply scaling based on jpg_scale setting
    if (embedded_tjpg_.jpg_scale > 1) {
        width /= embedded_tjpg_.jpg_scale;
        height /= embedded_tjpg_.jpg_scale;
    }
    // Allocate frame buffer
    allocateFrameBuffer(width, height);
    // Create frame object
    current_frame_ = fl::make_shared<Frame>(frame_buffer_.get(), width, height, pixel_format_);
    if (!current_frame_->isValid()) {
        setError("Failed to create frame");
        return false;
    }
    // Initialize progressive state if needed
    if (use_progressive_) {
        fl::memcpy(&progressive_state_.base, jdec, sizeof(JDEC));
        progressive_state_.current_mcu_x = 0;
        progressive_state_.current_mcu_y = 0;
        progressive_state_.mcus_processed = 0;
        progressive_state_.total_mcus = (jdec->width / jdec->msx / 8) *
                                        (jdec->height / jdec->msy / 8);
    }
    return true;
}
References allocateFrameBuffer(), current_frame_, embedded_tjpg_, FL_NOEXCEPT, frame_buffer_, fl::height, fl::third_party::JDEC::height, inputCallback(), fl::third_party::jd_prepare(), fl::third_party::JDR_OK, fl::make_shared(), fl::memcpy(), fl::third_party::JDEC::msx, fl::third_party::JDEC::msy, pixel_format_, progressive_state_, setError(), fl::snprintf(), use_progressive_, fl::third_party::JDEC::width, and fl::width.
Referenced by beginDecodingStream().