FastLED: fl::third_party::TJpgInstanceDecoder::allocateFrameBuffer
allocateFrameBuffer()
void fl::third_party::TJpgInstanceDecoder::allocateFrameBuffer (fl::u16 width, fl::u16 height) private
Definition at line 271 of file driver.cpp.hpp.
{
    frame_buffer_size_ = static_cast<fl::size>(width) * height * getBytesPerPixel();
    if (frame_buffer_size_ > 0) {
        frame_buffer_.reset(new fl::u8[frame_buffer_size_]);
        fl::memset(frame_buffer_.get(), 0, frame_buffer_size_);
    }
}
References FL_NOEXCEPT, frame_buffer_, frame_buffer_size_, fl::getBytesPerPixel(), fl::height, fl::memset(), and fl::width.
Referenced by initializeDecoder().