FastLED: fl::third_party::TJpgInstanceDecoder::beginDecodingStream
beginDecodingStream()
bool fl::third_party::TJpgInstanceDecoder::beginDecodingStream (fl::filebuf_ptr stream, PixelFormat format)
Definition at line 22 of file driver.cpp.hpp.
{
    if (!stream) {
        setError("Invalid stream provided");
        return false;
    }
    input_stream_ = stream;
    pixel_format_ = format;
    state_ = State::NotStarted;
    progress_ = 0.0f;
    error_message_.clear();
    // Read stream data
    if (!readStreamData()) {
        return false;
    }
    // Initialize decoder
    if (!initializeDecoder()) {
        return false;
    }
    state_ = State::HeaderParsed;
    return true;
}
References error_message_, FL_NOEXCEPT, fl::format(), HeaderParsed, initializeDecoder(), input_stream_, NotStarted, pixel_format_, progress_, readStreamData(), setError(), and state_.