FastLED: fl::audio::clamp01
clamp01()
static float fl::audio::clamp01 (float v) static
Definition at line 457 of file audio_processor.cpp.hpp.
{
    if (v < 0.0f) return 0.0f;
    if (v > 1.0f) return 1.0f;
    return v;
}
References clamp01().
Referenced by clamp01(), fl::audio::Processor::getBackbeatConfidence(), fl::audio::Processor::getBackbeatStrength(), fl::audio::Processor::getBassLevel(), fl::audio::Processor::getBeatConfidence(), fl::audio::Processor::getBuildupIntensity(), fl::audio::Processor::getBuildupProgress(), fl::audio::Processor::getChordConfidence(), fl::audio::Processor::getDownbeatConfidence(), fl::audio::Processor::getDropImpact(), fl::audio::Processor::getEnergy(), fl::audio::Processor::getEqBass(), fl::audio::Processor::getEqBin(), fl::audio::Processor::getEqDominantMagnitude(), fl::audio::Processor::getEqMid(), fl::audio::Processor::getEqTreble(), fl::audio::Processor::getEqVolume(), fl::audio::Processor::getEqVolumeNormFactor(), fl::audio::Processor::getEqZcf(), fl::audio::Processor::getKeyConfidence(), fl::audio::Processor::getMeasurePhase(), fl::audio::Processor::getMidLevel(), fl::audio::Processor::getMoodArousal(), fl::audio::Processor::getPeakLevel(), fl::audio::Processor::getPitchConfidence(), fl::audio::Processor::getTempoConfidence(), fl::audio::Processor::getTransientStrength(), fl::audio::Processor::getTrebleLevel(), and fl::audio::Processor::getVocalConfidence().