FastLED: fl::audio::interpolateMicResponse
interpolateMicResponse()
float fl::audio::interpolateMicResponse (const MicResponseCurve & curve, float freq_hz) inline
Interpolate mic response at an arbitrary frequency (Hz).
Uses log-frequency linear interpolation with binary search. Clamps to endpoint values outside the data range.
Definition at line 229 of file mic_response_data.h.
{
    if (curve.count <= 0 || !curve.freqs || !curve.gains) return 1.0f;
    float f0 = fl_progmem_read_float(&curve.freqs[0]);
    float fN = fl_progmem_read_float(&curve.freqs[curve.count - 1]);
    // Clamp to endpoints
    if (freq_hz <= f0) return fl_progmem_read_float(&curve.gains[0]);
    if (freq_hz >= fN) return fl_progmem_read_float(&curve.gains[curve.count - 1]);
    // Binary search for bracketing interval
    int lo = 0, hi = curve.count - 1;
    while (hi - lo > 1) {
        int mid = (lo + hi) / 2;
        float fMid = fl_progmem_read_float(&curve.freqs[mid]);
        if (freq_hz < fMid) {
            hi = mid;
        } else {
            lo = mid;
        }
    }
    float fLo = fl_progmem_read_float(&curve.freqs[lo]);
    float fHi = fl_progmem_read_float(&curve.freqs[hi]);
    float gLo = fl_progmem_read_float(&curve.gains[lo]);
    float gHi = fl_progmem_read_float(&curve.gains[hi]);
    // Log-frequency linear interpolation
    float logFrac = fl::logf(freq_hz / fLo) / fl::logf(fHi / fLo);
    return gLo + (gHi - gLo) * logFrac;
}
References fl::audio::MicResponseCurve::count, fl_progmem_read_float(), fl::audio::MicResponseCurve::freqs, fl::audio::MicResponseCurve::gains, and fl::logf().
Referenced by downsampleMicResponse().