FastLED: fl::audio::computePinkNoiseGains
computePinkNoiseGains()
void fl::audio::computePinkNoiseGains (const float * binCenters, int numBins, float * out) inline
Compute pink noise compensation gains for all bins.
Normalizes so the geometric mean of all gains ≈ 1.0.
Parameters
binCenters Array of bin center frequencies (Hz)
numBins Number of bins
out Output array of gains (length numBins)
Definition at line 294 of file mic_response_data.h.
{
    if (numBins <= 0) return;
    // Compute geometric mean of bin centers for f_ref
    float logSum = 0.0f;
    int validCount = 0;
    for (int i = 0; i < numBins; ++i) {
        if (binCenters[i] > 0.0f) {
            logSum += fl::logf(binCenters[i]);
            ++validCount;
        }
    }
    float f_ref = (validCount > 0)
        ? fl::expf(logSum / static_cast<float>(validCount))
        : 1000.0f;
    // Compute raw gains
    for (int i = 0; i < numBins; ++i) {
        out[i] = computePinkNoiseGain(binCenters[i], f_ref);
    }
    // Cap individual gains to prevent extreme boosting of high-frequency bins
    static constexpr float kMaxPinkNoiseGain = 3.0f;
    for (int i = 0; i < numBins; ++i) {
        if (out[i] > kMaxPinkNoiseGain) {
            out[i] = kMaxPinkNoiseGain;
        }
    }
    // Normalize so geometric mean of output gains = 1.0
    float outLogSum = 0.0f;
    for (int i = 0; i < numBins; ++i) {
        if (out[i] > 0.0f) {
            outLogSum += fl::logf(out[i]);
        }
    }
    float geoMean = fl::expf(outLogSum / static_cast<float>(numBins));
    if (geoMean > 0.001f) {
        for (int i = 0; i < numBins; ++i) {
            out[i] /= geoMean;
        }
    }
}
References computePinkNoiseGain(), fl::expf(), and fl::logf().
Referenced by fl::audio::Reactive::begin(), and fl::audio::detector::EqualizerDetector::recomputePinkNoiseGains().