FastLED: fl::Remote::scheduleFunction
scheduleFunction()
void fl::Remote::scheduleFunction (u32 timestamp, u32 receivedAt, const fl::json & jsonRpcRequest) protected
Definition at line 195 of file remote.cpp.hpp.
{
    // Make explicit copy for capture (avoid reference issues)
    fl::json requestCopy = jsonRpcRequest;
    fl::string funcName = requestCopy["method"].as_string().value_or("unknown");
    // Wrap RPC execution in lambda and schedule it
    mScheduler.schedule(timestamp, [this, requestCopy, timestamp, receivedAt, funcName]() {
        u32 executedAt = fl::millis();
        // Execute JSON-RPC request
        fl::json response = mRpc.handle(requestCopy);
        // Record result with timing metadata
        if (response.contains("result") && requestCopy.contains("method")) {
            recordResult(funcName, response["result"], timestamp, receivedAt, executedAt, true);
        }
    });
    FL_DBG("Scheduled RPC: " << funcName << " at " << timestamp);
}
References fl::json::as_string(), fl::json::contains(), FL_DBG, fl::millis(), mRpc, mScheduler, and recordResult().
Referenced by processRpc().