FastLED: fl::Remote::Remote
Remote() [1/3]
fl::Remote::Remote (RequestSource source, ResponseSink sink)
Construct with I/O callbacks.
Parameters
source Function that returns next JSON-RPC request (or nullopt if none)
sink Function that handles outgoing JSON-RPC responses
Example (Serial): fl::Remote remote([&]() { return parseJsonRpcFromSerial(); }, [](const fl::json& r) { writeJsonRpcToSerial(r); });
Example (HTTP Streaming): auto transport = fl::make_shared<HttpStreamClient>("localhost", 8080); fl::Remote remote([&transport]() { return transport->readRequest(); }, [&transport](const fl::json& r) { transport->writeResponse(r); }); // In main loop: transport->update(millis()); remote.update(millis());
Definition at line 253 of file remote.cpp.hpp.
    : Server(fl::move(source), fl::move(sink))
{
    // Set request handler to processRpc
    setRequestHandler([this](const fl::json& request) {
        return processRpc(request);
    });
    // Set response sink on Rpc for async ACKs
    mRpc.setResponseSink([this](const fl::json& response) {
        // Send response directly via Server's response sink
        if (mResponseSink) {
            mResponseSink(response);
        }
    });
}
References fl::Server::Server(), fl::move(), fl::Server::mResponseSink, mRpc, processRpc(), and fl::Server::setRequestHandler().
Referenced by Remote(), Remote(), fl::WLED::WLED(), fl::WLED::WLED(), operator=(), and operator=().