FastLED: fl::Remote::methods
methods()
fl::vector< Remote::MethodInfo > fl::Remote::methods () const
Get method information for all registered methods.
Definition at line 291 of file remote.cpp.hpp.
{
    fl::vector<MethodInfo> result;
    // Get flat JSON schema from underlying RPC
    // Format: [["methodName", "returnType", [["param1", "type1"], ...]], ...]
    fl::json jsonMethods = mRpc.methods();
    if (!jsonMethods.is_array()) {
        return result;
    }
    // Convert each flat method array to MethodInfo struct
    for (fl::size i = 0; i < jsonMethods.size(); i++) {
        fl::json method = jsonMethods[i];
        if (!method.is_array() || method.size() < 3) {
            continue;  // Invalid method format
        }
        MethodInfo info;
        // method[0] = method name
        info.name = method[0].as_string().value_or("");
        // method[1] = return type
        info.returnType = method[1].as_string().value_or("void");
        // method[2] = params array: [["param1", "type1"], ["param2", "type2"], ...]
        if (method[2].is_array()) {
            fl::json params = method[2];
            for (fl::size j = 0; j < params.size(); j++) {
                fl::json param = params[j];
                if (param.is_array() && param.size() >= 2) {
                    ParamInfo paramInfo;
                    paramInfo.name = param[0].as_string().value_or("");
                    paramInfo.type = param[1].as_string().value_or("unknown");
                    info.params.push_back(fl::move(paramInfo));
                }
            }
        }
        // Flat schema doesn't include description/tags
        info.description = "";
        info.tags.clear();
        result.push_back(fl::move(info));
    }
    return result;
}
References fl::json::as_string(), fl::vector< T >::clear(), fl::MethodInfo::description, fl::json::is_array(), fl::fl::move(), mRpc, fl::MethodInfo::name, fl::ParamInfo::name, fl::MethodInfo::params, fl::MethodInfo::returnType, fl::json::size(), fl::MethodInfo::tags, and fl::ParamInfo::type.