FastLED: fl::Remote::update
update()
size_t fl::Remote::update (u32 currentTimeMs)
Main update: pull + tick + push (overrides Server::update)
Definition at line 272 of file remote.cpp.hpp.
{
    size_t processed = Server::pull();   // Pull requests from Server
    size_t executed = tick(currentTimeMs);  // Process scheduled tasks
    // Push scheduled results as JSON-RPC responses
    for (const auto& r : mResults) {
        fl::json response = fl::json::object();
        response.set("result", r.result);
        // Note: We don't have the original request ID for scheduled calls
        // This could be improved by storing the ID with RpcResult
        mOutgoingQueue.push_back(response);
    }
    size_t sent = Server::push();        // Push responses from Server
    return processed + executed + sent;
}
References fl::Server::mOutgoingQueue, mResults, fl::json::object(), fl::Server::pull(), fl::Server::push(), and tick().
Referenced by autoResearchLowMemoryLoop(), and sendStreamUpdate().