FastLED: fl::PerlinParticlePunch::circleNoiseGen
circleNoiseGen()
s16x16 fl::PerlinParticlePunch::circleNoiseGen (u32 now, s16x16 theta) const private
Definition at line 231 of file perlin_particle_punch.cpp.hpp.
{
    s16x16 sin_val, cos_val;
    s16x16::sincos(theta, sin_val, cos_val);
    u32 x =
        u32((i64(cos_val.raw() + s16x16::SCALE) * 0xafff) >> s16x16::FRAC_BITS);
    u32 y =
        u32((i64(sin_val.raw() + s16x16::SCALE) * 0xafff) >> s16x16::FRAC_BITS);
    // Time dimension with time-warp multiplier
    u32 z = u32(float(now * 0x000fu) * mTimeMultiplier);
    u16 val = inoise16(x, y, z);
    s16x16 tmp = s16x16::from_raw(
        i32((u32(val) << s16x16::FRAC_BITS) / 0xcfffu));
    constexpr s16x16 one(1.0f);
    if (tmp > one)
        tmp = one;
    tmp = tmp * tmp;
    tmp = tmp * tmp;
    tmp = tmp * s16x16(255);
    return tmp;
}
References fl::s16x16::FRAC_BITS, fl::s16x16::from_raw(), inoise16(), mTimeMultiplier, fl::s16x16::raw(), fl::s16x16::SCALE, fl::s16x16::sincos(), fl::x, fl::y, and z.
Referenced by noiseCircleDraw().