FastLED: fl::PerlinParticlePunch::renderAmbient
renderAmbient()
void fl::PerlinParticlePunch::renderAmbient (const AmbientParticle & p) private
Definition at line 289 of file perlin_particle_punch.cpp.hpp.
{
    int center = int(p.position);
    float frac = p.position - float(center);
    u8 bri = clamp_u8(p.brightness);
    CRGB baseColor =
        ColorFromPalette(mAmbientPalette, p.paletteIndex, bri, LINEARBLEND);
    for (int offset = 0; offset < p.headWidth; ++offset) {
        int idx = center - offset; // trail extends behind (toward pos 0)
        if (idx < 0 || idx >= mNumLeds)
            continue;
        // Linear falloff: 100% at head → 20% at tail of gradient
        float falloff = 1.0f - (float(offset) / float(p.headWidth)) * 0.8f;
        CRGB pixel = baseColor;
        pixel.nscale8(clamp_u8(falloff * 255.0f));
        // Sub-pixel blending for the leading edge
        if (offset == 0 && frac > 0.01f) {
            int nextIdx = center + 1;
            if (nextIdx < mNumLeds) {
                CRGB subPixel = pixel;
                subPixel.nscale8(clamp_u8(frac * 255.0f));
                writeMax(mTrailBuffer[nextIdx], subPixel);
            }
            pixel.nscale8(clamp_u8((1.0f - frac) * 255.0f));
        }
        writeMax(mTrailBuffer[idx], pixel);
    }
}
References fl::PerlinParticlePunch::AmbientParticle::brightness, fl::ColorFromPalette(), fl::PerlinParticlePunch::AmbientParticle::headWidth, mAmbientPalette, fl::Fx::mNumLeds, mTrailBuffer, fl::CRGB::nscale8(), offset(), fl::PerlinParticlePunch::AmbientParticle::paletteIndex, fl::PerlinParticlePunch::AmbientParticle::position, and writeMax().
Referenced by draw().