FastLED: fl::PerlinParticlePunch::noiseCircleDraw
noiseCircleDraw()
void fl::PerlinParticlePunch::noiseCircleDraw (u32 now, fl::span< CRGB > dst) private
Definition at line 252 of file perlin_particle_punch.cpp.hpp.
{
    // Apply time-warp to rotation speed — this is the visible acceleration
    u32 warped_now = u32(float(now) * mTimeMultiplier);
    s16x16 time_factor = s16x16::from_raw(static_cast<i32>(warped_now * 32u));
    constexpr s16x16 two_pi(6.2831853f);
    s16x16 step = two_pi / s16x16(i32(mNumLeds));
    s16x16 theta = -time_factor;
    constexpr s16x16 threshold(32.0f);
    constexpr s16x16 zero(0.0f);
    constexpr s16x16 max_val(255.0f);
    for (u16 i = 0; i < mNumLeds; ++i) {
        s16x16 val = circleNoiseGen(now + 1000, theta);
        if (val < threshold) {
            val = zero;
        } else {
            val = mapf(val, threshold, max_val, zero, max_val);
        }
        u8 val_u8 = u8(val.to_int());
        // Palette lookup: val_u8 selects color AND brightness
        dst[i] = ColorFromPalette(mNoisePalette, val_u8, val_u8, LINEARBLEND);
        theta = theta + step;
    }
}
References circleNoiseGen(), fl::ColorFromPalette(), fl::s16x16::from_raw(), mapf(), mNoisePalette, fl::Fx::mNumLeds, mTimeMultiplier, fl::step(), and fl::s16x16::to_int().
Referenced by draw().