FastLED: fl::PerlinParticlePunch::spawnDebrisFromMeteor
spawnDebrisFromMeteor()
void fl::PerlinParticlePunch::spawnDebrisFromMeteor (MeteorParticle & m, u32 now) private
Definition at line 380 of file perlin_particle_punch.cpp.hpp.
{
    DebrisParticle *d = tryAllocateDebris();
    if (!d)
        return;
    float tailLen = m.tailLength();
    u8 maxOffset = clamp_u8(tailLen);
    if (maxOffset < 3)
        maxOffset = 3;
    float spawnOffset = float(random8(2, maxOffset));
    float spawnPos = m.position - spawnOffset;
    if (spawnPos < 0.0f)
        spawnPos = 0.0f;
    // Interpolate meteor tail color at detach point
    float t = spawnOffset / tailLen;
    if (t > 1.0f)
        t = 1.0f;
    fract8 blendAmt = clamp_u8(t * 255.0f);
    CRGB debrisColor = blend(mMeteorMidColor, mMeteorTailColor, blendAmt);
    d->alive = true;
    d->position = spawnPos;
    d->velocity = float(random8(10, 40)) / 100.0f; // 0.1-0.4 LEDs/frame
    d->brightness = 180.0f;
    d->color = debrisColor;
    m.debrisSpawned++;
}
References fl::PerlinParticlePunch::DebrisParticle::alive, fl::blend(), fl::PerlinParticlePunch::DebrisParticle::brightness, fl::PerlinParticlePunch::DebrisParticle::color, fl::PerlinParticlePunch::MeteorParticle::debrisSpawned, mMeteorMidColor, mMeteorTailColor, fl::PerlinParticlePunch::DebrisParticle::position, fl::PerlinParticlePunch::MeteorParticle::position, random8(), fl::t, fl::PerlinParticlePunch::MeteorParticle::tailLength(), tryAllocateDebris(), and fl::PerlinParticlePunch::DebrisParticle::velocity.
Referenced by draw().