FastLED: fl::PerlinParticlePunch::renderMeteor
renderMeteor()
void fl::PerlinParticlePunch::renderMeteor (const MeteorParticle & m) private
Definition at line 321 of file perlin_particle_punch.cpp.hpp.
{
    int center = int(m.position);
    // --- Head: 5-pixel gaussian kernel ---
    static const float kGaussian[] = {0.15f, 0.60f, 1.0f, 0.60f, 0.15f};
    for (int offset = -2; offset <= 2; ++offset) {
        int idx = center + offset;
        if (idx < 0 || idx >= mNumLeds)
            continue;
        float weight = kGaussian[offset + 2];
        u8 bri = clamp_u8(255.0f * m.intensity * weight);
        // Re-entry sparkle: random brightness jitter per pixel per frame
        bri = scale8(bri, random8(153, 255));
        CRGB headColor = mMeteorHeadColor;
        headColor.nscale8(bri);
        writeMax(mTrailBuffer[idx], headColor);
    }
    // --- Tail: gradient behind the head ---
    float tailLen = m.tailLength();
    int tailPixels = int(tailLen);
    for (int i = 1; i <= tailPixels; ++i) {
        int idx = center - i;
        if (idx < 0)
            break;
        if (idx >= mNumLeds)
            continue;
        // t: 0.0 at head, 1.0 at tail tip
        float t = float(i) / float(tailPixels);
        fract8 blendAmt = clamp_u8(t * 255.0f);
        CRGB tailColor = blend(mMeteorMidColor, mMeteorTailColor, blendAmt);
        // Quadratic brightness falloff along tail
        float bri = (1.0f - t * t) * m.intensity;
        tailColor.nscale8(clamp_u8(bri * 255.0f));
        writeMax(mTrailBuffer[idx], tailColor);
    }
}
References fl::blend(), fl::PerlinParticlePunch::MeteorParticle::intensity, mMeteorHeadColor, mMeteorMidColor, mMeteorTailColor, fl::Fx::mNumLeds, mTrailBuffer, fl::CRGB::nscale8(), offset(), fl::PerlinParticlePunch::MeteorParticle::position, random8(), fl::t, fl::PerlinParticlePunch::MeteorParticle::tailLength(), and writeMax().
Referenced by draw().