FastLED: fl::PerlinParticlePunch::draw
draw()
void fl::PerlinParticlePunch::draw (DrawContext context) override virtual
Parameters
now The current time in milliseconds. Fx writers are encouraged to use this instead of millis() directly as this will more deterministic behavior.
Implements fl::Fx.
Definition at line 413 of file perlin_particle_punch.cpp.hpp.
{
    fl::span<CRGB> leds = context.leds;
    if (leds.empty() || mNumLeds == 0) {
        return;
    }
    u32 now = context.now;
    // --- Layer 1: Perlin noise background (fresh each frame) ---
    noiseCircleDraw(now, leds);
    // --- Trail buffer decay ---
    // Use the larger of the two trail intensities for the shared buffer.
    // Higher intensity value = less fade per frame = longer trails.
    u8 trailIntensity = mAmbientTrailIntensity > mMeteorTrailIntensity
                            ? mAmbientTrailIntensity
                            : mMeteorTrailIntensity;
    u8 decayRate = 255 - trailIntensity;
    fadeToBlackBy(mTrailBuffer.data(), mNumLeds, decayRate);
    // --- Layer 2: Ambient particles ---
    for (u16 i = 0; i < (u16)mAmbientParticles.size(); ++i) {
        AmbientParticle &p = mAmbientParticles[i];
        if (!p.alive)
            continue;
        // Physics update
        p.velocity *= mDrag;
        p.position += p.velocity;
        p.brightness *= mAmbientBrightnessDecay;
        if (p.position >= float(mNumLeds) || p.position < 0.0f ||
            p.brightness < 8.0f || p.velocity < mMinVelocity) {
            p.alive = false;
            continue;
        }
        renderAmbient(p);
    }
    // --- Layer 3: Meteors ---
    for (u16 i = 0; i < (u16)mMeteorParticles.size(); ++i) {
        MeteorParticle &m = mMeteorParticles[i];
        if (!m.alive)
            continue;
        // Debris spawn check before physics update
        if (m.shouldSpawnDebris()) {
            spawnDebrisFromMeteor(m, now);
        }
        // Physics update
        m.velocity *= mMeteorDrag;
        m.position += m.velocity;
        m.frameCounter++;
        if (m.position >= float(mNumLeds) || m.velocity < mMinVelocity) {
            m.alive = false;
            continue;
        }
        renderMeteor(m);
    }
    // --- Debris ---
    for (u16 i = 0; i < (u16)mDebrisParticles.size(); ++i) {
        DebrisParticle &d = mDebrisParticles[i];
        if (!d.alive)
            continue;
        // Physics update
        d.position += d.velocity;
        d.velocity *= mDebrisVelocityDecay;
        d.brightness *= mDebrisBrightnessDecay;
        if (d.brightness < 5.0f || d.position >= float(mNumLeds)) {
            d.alive = false;
            continue;
        }
        renderDebris(d);
    }
    // --- Composite: max(noise, trail) per channel ---
    for (u16 i = 0; i < mNumLeds; ++i) {
        if (mTrailBuffer[i].r > leds[i].r)
            leds[i].r = mTrailBuffer[i].r;
        if (mTrailBuffer[i].g > leds[i].g)
            leds[i].g = mTrailBuffer[i].g;
        if (mTrailBuffer[i].b > leds[i].b)
            leds[i].b = mTrailBuffer[i].b;
    }
}
References fl::PerlinParticlePunch::AmbientParticle::alive, fl::PerlinParticlePunch::DebrisParticle::alive, fl::PerlinParticlePunch::MeteorParticle::alive, fl::PerlinParticlePunch::AmbientParticle::brightness, fl::PerlinParticlePunch::DebrisParticle::brightness, fl::fadeToBlackBy(), fl::PerlinParticlePunch::MeteorParticle::frameCounter, fl::DrawContext::leds, leds, mAmbientBrightnessDecay, mAmbientParticles, mAmbientTrailIntensity, mDebrisBrightnessDecay, mDebrisParticles, mDebrisVelocityDecay, mDrag, mMeteorDrag, mMeteorParticles, mMeteorTrailIntensity, mMinVelocity, fl::Fx::mNumLeds, mTrailBuffer, noiseCircleDraw(), fl::DrawContext::now, fl::PerlinParticlePunch::AmbientParticle::position, fl::PerlinParticlePunch::DebrisParticle::position, fl::PerlinParticlePunch::MeteorParticle::position, renderAmbient(), renderDebris(), renderMeteor(), fl::PerlinParticlePunch::MeteorParticle::shouldSpawnDebris(), spawnDebrisFromMeteor(), fl::PerlinParticlePunch::AmbientParticle::velocity, fl::PerlinParticlePunch::DebrisParticle::velocity, and fl::PerlinParticlePunch::MeteorParticle::velocity.
Referenced by ~PerlinParticlePunch().