FastLED: fl::PerlinParticlePunch::renderDebris
renderDebris()
void fl::PerlinParticlePunch::renderDebris (const DebrisParticle & d) private
Definition at line 360 of file perlin_particle_punch.cpp.hpp.
{
    int idx = int(d.position);
    float frac = d.position - float(idx);
    u8 bri = clamp_u8(d.brightness);
    CRGB pixel = d.color;
    pixel.nscale8(bri);
    if (idx >= 0 && idx < mNumLeds) {
        CRGB main = pixel;
        main.nscale8(clamp_u8((1.0f - frac) * 255.0f));
        writeMax(mTrailBuffer[idx], main);
    }
    int nextIdx = idx + 1;
    if (nextIdx >= 0 && nextIdx < mNumLeds && frac > 0.01f) {
        CRGB sub = pixel;
        sub.nscale8(clamp_u8(frac * 255.0f));
        writeMax(mTrailBuffer[nextIdx], sub);
    }
}
References fl::PerlinParticlePunch::DebrisParticle::brightness, fl::PerlinParticlePunch::DebrisParticle::color, fl::Fx::mNumLeds, mTrailBuffer, fl::CRGB::nscale8(), fl::PerlinParticlePunch::DebrisParticle::position, and writeMax().
Referenced by draw().