FastLED: fl::MultiChannelConfig::MultiChannelConfig
MultiChannelConfig() [4/7]
fl::MultiChannelConfig::MultiChannelConfig (fl::span< ChannelConfigPtr > channels) inline
Definition at line 371 of file config.h.
: mChannels(channels.begin(), channels.end()) {}
References MultiChannelConfig(), fl::begin(), fl::end(), FL_NOEXCEPT, and mChannels.