FastLED: fl::JpegDecoder::Impl::begin
begin()
bool fl::JpegDecoder::Impl::begin (fl::filebuf_ptr stream) inline
Definition at line 71 of file jpeg.cpp.hpp.
{
        if (!mDriver) {
            setError("Driver not initialized");
            return false;
        }
        mState = JpegDecoder::State::NotStarted;
        mHasError = false;
        mErrorMessage.clear();
        mProgress = 0.0f;
        // Configure progressive settings
        fl::third_party::TJpgProgressiveConfig mDriverconfig;
        mDriverconfig.max_mcus_per_tick = progressive_mConfig.max_mcus_per_tick;
        mDriverconfig.max_time_per_tick_ms = progressive_mConfig.max_time_per_tick_ms;
        mDriver->setProgressiveConfig(mDriverconfig);
        // Set scale based on quality setting
        mDriver->setScale(getScale());
        if (!mDriver->beginDecodingStream(stream, mConfig.format)) {
            fl::string err;
            if (mDriver->hasError(&err)) {
                setError(err);
            } else {
                setError("Failed to begin JPEG decoding");
            }
            return false;
        }
        mState = JpegDecoder::State::HeaderParsed;
        return true;
    }
References begin(), getScale(), fl::third_party::TJpgProgressiveConfig::max_mcus_per_tick, fl::third_party::TJpgProgressiveConfig::max_time_per_tick_ms, mConfig, mDriver, mErrorMessage, mHasError, mProgress, mState, fl::JpegDecoder::NotStarted, progressive_mConfig, and setError().
Referenced by begin().