FastLED: fl::test::TAPReporter::testRunStart
testRunStart()
void fl::test::TAPReporter::testRunStart () override virtual
Implements fl::test::IReporter.
Definition at line 845 of file fltest.cpp.hpp.
{
    mTestNumber = 0;
    mStreamingOutput.clear();
    // Output TAP version header
    output("TAP version 13");
    // If we know the total, output the plan at the start
    if (mTotalTests > 0) {
        fl::sstream ss;
        ss << "1.." << mTotalTests;
        output(ss.str().c_str());
    }
}
References fl::basic_string::c_str(), FL_NOEXCEPT, mStreamingOutput, mTestNumber, mTotalTests, output(), and fl::sstream::str().