FastLED: fl::test::TAPReporter::testCaseEnd
testCaseEnd()
void fl::test::TAPReporter::testCaseEnd (bool passed, fl::u32 durationMs = 0) override virtual
Called when a test case ends.
Parameters
passed Whether the test passed
durationMs Duration of the test in milliseconds (0 if no timer available)
Implements fl::test::IReporter.
Definition at line 891 of file fltest.cpp.hpp.
{
    fl::sstream ss;
    if (passed) {
        ss << "ok " << mTestNumber << " - " << mCurrentTestName;
    } else {
        ss << "not ok " << mTestNumber << " - " << mCurrentTestName;
    }
    // TAP supports duration via directive (non-standard but widely recognized)
    if (durationMs > 0) {
        ss << " # (" << durationMs << " ms)";
    }
    output(ss.str().c_str());
    // Output diagnostics for failed tests
    for (fl::size i = 0; i < mDiagnostics.size(); ++i) {
        fl::sstream diag;
        diag << "# " << mDiagnostics[i];
        output(diag.str().c_str());
    }
}
References fl::basic_string::c_str(), FL_NOEXCEPT, mCurrentTestName, mDiagnostics, mTestNumber, output(), and fl::sstream::str().