FastLED: fl::StringInterner::intern
intern() [4/4]
fl::string fl::StringInterner::intern (const string_view & sv)
Definition at line 29 of file string_interner.cpp.hpp.
{
    if (sv.empty()) return fl::string();
    // SSO optimization: strings that fit in the inline buffer don't benefit from interning
    // because fl::string will store them inline (no heap allocation anyway).
    // Interning small strings would just add hash overhead with no memory savings.
    if (sv.size() <= FASTLED_STR_INLINED_SIZE) {
        return fl::string(sv);
    }
    // String is large enough to require heap allocation - check if already interned
    // Try to find existing entry - O(1) average via hash map
    auto it = mEntries.find(sv);
    if (it != mEntries.end()) {
        // Found existing - return fl::string sharing the StringHolder
        return fl::string(it->second);
    }
    // Not found - create new StringHolder (heap-allocated)
    auto holder = fl::make_shared<StringHolder>(sv.data(), sv.size());
    // Create string_view key that points into holder's data
    // This is safe because StringHolder data is heap-allocated and never moves
    string_view key(holder->data(), holder->length());
    // Insert into map - key points into value's data (self-referential)
    mEntries[key] = holder;
    // Return fl::string sharing the StringHolder
    return fl::string(holder);
}
References fl::string_view::data(), fl::string_view::empty(), FASTLED_STR_INLINED_SIZE, fl::make_shared(), mEntries, and fl::string_view::size().
Referenced by fl::intern(), fl::intern(), fl::intern(), fl::intern(), fl::string::intern(), intern(), intern(), intern(), fl::string::interned(), fl::string::interned(), and fl::string::interned().