FastLED: fl::bitset_dynamic::resize
resize()
FL_DISABLE_WARNING_POP FL_DISABLE_WARNING_PUSH FL_DISABLE_WARNING_NULL_DEREFERENCE void fl::bitset_dynamic::resize (fl::u32 new_size) inline
Definition at line 117 of file bitset_dynamic.h.
{
        if (new_size == _size)
            return;
        fl::u32 new_block_count = (new_size + bits_per_block - 1) / bits_per_block;
        if (new_block_count != _block_count) {
            block_type *new_blocks = new block_type[new_block_count];  // ok bare allocation (array new for unique_ptr)
            fl::memset(new_blocks, 0, new_block_count * sizeof(block_type));
            if (_blocks) {
                fl::u32 copy_blocks = fl::min(_block_count, new_block_count);
                fl::memcpy(new_blocks, _blocks.get(), copy_blocks * sizeof(block_type));
            }
            _blocks.reset(new_blocks);
            _block_count = new_block_count;
        }
        _size = new_size;
        // Clear any bits beyond the new size
        if (_blocks && _block_count > 0 && _size % bits_per_block != 0) {
            fl::u32 last_block_idx = (_size - 1) / bits_per_block;
            fl::u32 last_bit_pos = (_size - 1) % bits_per_block;
            block_type mask =
                static_cast<block_type>((static_cast<block_type>(1) << (last_bit_pos + 1)) - 1);
            _blocks[last_block_idx] &= mask;
        }
    }
References _block_count, _blocks, _size, bits_per_block, FL_NOEXCEPT, fl::memcpy(), fl::memset(), and fl::min().
Referenced by bitset_dynamic(), bitset_dynamic(), assign(), operator=(), pop_back(), and push_back().