FastLED: fl::bitset_dynamic::resize
resize()
void fl::bitset_dynamic::resize (uint32_t new_size) inline
Definition at line 94 of file bitset_dynamic.h.
{
        if (new_size == _size)
            return;
        uint32_t new_block_count = calc_block_count(new_size);
        if (new_block_count != _block_count) {
            block_type *new_blocks = nullptr;
            if (new_block_count > 0) {
                new_blocks = new block_type[new_block_count]();
                // Copy existing data if any
                if (_blocks && _block_count > 0) {
                    memcpy(new_blocks, _blocks,
                           MIN(_block_count, new_block_count) *
                               sizeof(block_type));
                }
            }
            delete[] _blocks;
            _blocks = new_blocks;
            _block_count = new_block_count;
        }
        _size = new_size;
        // Clear any bits beyond the new size
        if (_block_count > 0) {
            uint32_t last_block_idx = (_size - 1) / bits_per_block;
            uint32_t last_bit_pos = (_size - 1) % bits_per_block;
            // Create a mask for valid bits in the last block
            block_type mask =
                (static_cast<block_type>(1) << (last_bit_pos + 1)) - 1;
            if (last_block_idx < _block_count) {
                _blocks[last_block_idx] &= mask;
                // Clear any remaining blocks
                for (uint32_t i = last_block_idx + 1; i < _block_count; ++i) {
                    _blocks[i] = 0;
                }
            }
        }
    }
References _block_count, _blocks, _size, bits_per_block, calc_block_count(), and MIN.
Referenced by bitset_dynamic(), bitset_dynamic(), assign(), and operator=().