FastLED: fl::task::TimeTask::TimeTask
TimeTask()
fl::task::TimeTask::TimeTask (TaskType type, int interval_ms, optional< TracePoint > trace = nullopt) inline
Definition at line 116 of file task.cpp.hpp.
        : mTaskId(next_task_id())
        , mType(type)
        , mIntervalMs(interval_ms)
        , mTraceLabel(trace ? make_unique<string>(make_trace_label(*trace)) : nullptr)
        // Use (max)() to prevent macro expansion by Arduino.h's max macro
        , mLastRunTime((numeric_limits<u32>::max)()) {}
References interval_ms(), fl::make_unique(), fl::max(), mIntervalMs, mLastRunTime, mTaskId, mTraceLabel, mType, fl::nullopt, and type().