FastLED: hsv2rgb_rainbow
hsv2rgb_rainbow()
void hsv2rgb_rainbow (const struct CHSV & hsv, struct CRGB & rgb)
Forward declaration of hsv2rgb_rainbow here, to avoid circular dependencies.
Convert an HSV value to RGB using a visually balanced rainbow. This "rainbow" yields better yellow and orange than a straight mathematical "spectrum".
Parameters
hsv CHSV struct to convert to RGB. Max hue supported is HUE_MAX_RAINBOW
rgb CRGB struct to store the result of the conversion (will be modified)
Referenced by CRGB::CRGB(), CRGB::operator=(), CRGB::setHSV(), and CRGB::setHue().