FastLED: loop
loop()
void loop ()
Definition at line 58 of file RGBWW.ino.
            {
    // Animate a slow warm <-> cool transition. The colorimetric solver
    // chooses the warm/cool blend per pixel based on the input chromaticity,
    // so writing CRGB stays the same as a normal sketch — only the wire
    // format and color science change.
    uint32_t ms = millis();
    uint8_t blend = sin8(ms / 16);  // 0..255 triangle-ish
    // Lerp between a warm white tint (255, 200, 130) and a cool one (180, 200, 255).
    CRGB warm(255, 200, 130);
    CRGB cool(180, 200, 255);
    CRGB mixed;
    mixed.r = lerp8by8(warm.r, cool.r, blend);
    mixed.g = lerp8by8(warm.g, cool.g, blend);
    mixed.b = lerp8by8(warm.b, cool.b, blend);
    fill_solid(leds, NUM_LEDS, mixed);
    FastLED.show();
    delay(20);
}
References blend(), FastLED, fill_solid(), leds, lerp8by8(), and NUM_LEDS.