FastLED: test_json_await
test_json_await()
void test_json_await ()
APPROACH 4: JSON Response with await pattern
Same JSON handling but using await_top_level for synchronous-style code.
Definition at line 286 of file ClientReal.h.
                       {
    FL_WARN("APPROACH 4: JSON Response with await pattern");
    // TUTORIAL: Using await pattern with JSON responses
    // fl::net::http::fetch_get() returns fl::task::Promise<fl::net::http::Response>
    fl::task::Promise<fl::net::http::Response> json_promise = fl::net::http::fetch_get("https://httpbin.org/get");
    // TUTORIAL: await_top_level() converts promise to result
    // fl::task::PromiseResult<fl::net::http::Response> contains either response or error
    fl::task::PromiseResult<fl::net::http::Response> result = fl::task::await_top_level(json_promise);
    if (result.ok()) {
        // TUTORIAL: Extract the response from the result
        const fl::net::http::Response& http_response = result.value();
        FL_WARN("SUCCESS [JSON Await] HTTP fetch successful! Status: "
                << http_response.status() << " " << http_response.status_text());
        // TUTORIAL: Check for JSON content and parse if available
        if (http_response.is_json()) {
            FL_WARN("DETECTED [JSON Await] Response contains JSON data");
            // TUTORIAL: Parse JSON with automatic caching
            fl::json data = http_response.json();
            // TUTORIAL: httpbin.org/get returns information about the request
            // Extract data with safe defaults using FastLED's ideal JSON API
            fl::string origin_ip = data["origin"] | fl::string("unknown");
            fl::string request_url = data["url"] | fl::string("unknown");
            FL_WARN("JSON [Await] Request Origin IP: " << origin_ip);
            FL_WARN("JSON [Await] Request URL: " << request_url);
            // TUTORIAL: Access nested headers object safely
            if (data.contains("headers")) {
                fl::json headers = data["headers"];
                fl::string user_agent = headers["User-Agent"] | fl::string("unknown");
                fl::string accept = headers["Accept"] | fl::string("unknown");
                FL_WARN("JSON [Await] User-Agent: " << user_agent);
                FL_WARN("JSON [Await] Accept: " << accept);
            }
            // TUTORIAL: Access query parameters (if any)
            if (data.contains("args")) {
                fl::json args = data["args"];
                if (args.size() > 0) {
                    FL_WARN("JSON [Await] Query parameters found: " << args.size());
                } else {
                    FL_WARN("JSON [Await] No query parameters in request");
                }
            }
            // Visual feedback: Cyan LEDs for successful await JSON processing
            fill_solid(leds, NUM_LEDS, fl::CRGB(0, 128, 128)); // Cyan for await JSON success
        } else {
            FL_WARN("INFO [JSON Await] Response is not JSON format");
            // Visual feedback: Orange for non-JSON with await
            fill_solid(leds, NUM_LEDS, fl::CRGB(128, 32, 0)); // Orange for non-JSON await
        }
    } else {
        // TUTORIAL: Handle request failures (network or HTTP errors)
        FL_WARN("ERROR [JSON Await] Request failed: " << result.error_message());
        // Visual feedback: Red LEDs for any await error
        fill_solid(leds, NUM_LEDS, fl::CRGB(128, 0, 0)); // Red for await error
    }
    FastLED.show();
}
References args, fl::task::await_top_level(), fl::json::contains(), FastLED, fl::net::http::fetch_get(), fill_solid(), FL_WARN, fl::asio::http::Response::json(), leds, NUM_LEDS, and fl::asio::http::Response::status().
Referenced by loop().