FastLED: test_await_approach
test_await_approach()
void test_await_approach ()
Definition at line 164 of file ClientReal.h.
{
    FL_WARN("APPROACH 2: await_top_level pattern with explicit types");
    // TUTORIAL: Create a FetchOptions object to configure the HTTP request
    // FetchOptions is a data container - you can set timeout, headers, etc.
    fl::net::http::FetchOptions request_config("");  // Empty URL - will use the URL passed to fetch_get()
    request_config.timeout(5000)          // 5 second timeout
                  .header("User-Agent", "FastLED/Client-Tutorial");  // Custom user agent
    // TUTORIAL: fetch_get() returns fl::task::Promise<fl::net::http::Response> (explicit type!)
    // This promise represents the future HTTP response
    fl::task::Promise<fl::net::http::Response> http_promise = fl::net::http::fetch_get("http://fastled.io", request_config);
    // TUTORIAL: await_top_level() returns fl::task::PromiseResult<fl::net::http::Response>
    // result wraps either a successful response OR an Error - never both!
    // CRITICAL: await_top_level() blocks until completion - ONLY safe in Arduino loop()!
    fl::task::PromiseResult<fl::net::http::Response> result = fl::task::await_top_level(http_promise);
    // TUTORIAL: Check if the result contains a successful response
    if (result.ok()) {
        // TUTORIAL: Extract the response from the result
        // result.value() returns const fl::net::http::Response& - the actual HTTP response
        const fl::net::http::Response& http_response = result.value();
        FL_WARN("SUCCESS [Await] HTTP fetch successful! Status: "
                << http_response.status() << " " << http_response.status_text());
        // TUTORIAL: Check for optional Content-Type header
        // get_content_type() returns fl::optional<fl::string> - may be empty!
        fl::optional<fl::string> content_type = http_response.get_content_type();
        if (content_type.has_value()) {
            FL_WARN("CONTENT [Await] Content-Type: " << *content_type);
        }
        // TUTORIAL: Get the response body as fl::string
        const fl::string& response_body = http_response.text();
        if (response_body.length() >= 100) {
            FL_WARN("RESPONSE [Await] First 100 characters: " << response_body.substr(0, 100));
        } else {
            FL_WARN("RESPONSE [Await] Full response (" << response_body.length()
                                     << " chars): " << response_body);
        }
        // Visual feedback: Blue LEDs indicate await-based success (different from promise)
        fill_solid(leds, NUM_LEDS, fl::CRGB(0, 0, 64)); // Blue for await success
    } else {
        // Either HTTP error OR network error - both end up here
        // TUTORIAL: result.error_message() is a convenience method for getting error text
        FL_WARN("ERROR [Await] Request failed: " << result.error_message());
        // Visual feedback: Red LEDs for any await error
        fill_solid(leds, NUM_LEDS, fl::CRGB(64, 0, 0)); // Red for any error
    }
}
References fl::task::await_top_level(), fl::net::http::fetch_get(), fill_solid(), FL_WARN, fl::Optional< T >::has_value(), fl::net::http::FetchOptions::header(), leds, fl::basic_string::length(), NUM_LEDS, fl::asio::http::Response::status(), fl::string::substr(), and fl::net::http::FetchOptions::timeout().
Referenced by loop().