FastLED: fl::audio::SynthParams::fromShape
fromShape()
SynthParams fl::audio::SynthParams::fromShape (SynthShape shape) static
Create parameters for a predefined shape.
Definition at line 78 of file synth.cpp.hpp.
{
    switch (shape) {
        case SynthShape::Sawtooth:
            return SynthParams(1, 0.0f, 0.0f, 0.0f);
        case SynthShape::Square:
            return SynthParams(1, 0.0f, 1.0f, 0.0f);
        case SynthShape::Triangle:
            return SynthParams(1, 0.5f, 0.0f, 0.0f);
        case SynthShape::AlternatingSaw:
            return SynthParams(0, 0.0f, 0.0f, 0.0f);
        case SynthShape::Custom:
        default:
            return SynthParams();  // Default to sawtooth
    }
}
References SynthParams(), fl::audio::AlternatingSaw, fl::audio::Custom, fl::audio::Sawtooth, fl::audio::Square, and fl::audio::Triangle.
Referenced by fl::audio::ISynthOscillator::create(), and fl::audio::SynthOscillatorImpl::setShape().