FastLED: fl::wave_detail::compute_damp_decay_q15
compute_damp_decay_q15()
i16 fl::wave_detail::compute_damp_decay_q15 (int damp)
Definition at line 49 of file wave_simulation_real.cpp.hpp.
{
    if (damp <= 0) return INT16_POS;  // ~1.0 — no decay
    const float decay = 1.0f - 1.0f / static_cast<float>(1 << damp);
    return float_to_fixed(decay);
}
References FL_NOEXCEPT, float_to_fixed(), and INT16_POS.
Referenced by fl::WaveSimulation1D_Real::WaveSimulation1D_Real(), fl::WaveSimulation2D_Real::WaveSimulation2D_Real(), fl::WaveSimulation1D_Real::setDampening(), and fl::WaveSimulation2D_Real::setDampening().