FastLED: fl::response::parse_json_body
parse_json_body()
fl::Json fl::response::parse_json_body () const inline private
Parse JSON from response body with error handling.
Definition at line 157 of file fetch.h.
{
        fl::Json parsed = fl::Json::parse(mBody);
        if (parsed.is_null() && (!mBody.empty())) {
            // If parsing failed but we have content, return null JSON
            // This allows safe chaining: resp.json()["key"] | default
            return fl::Json(nullptr);
        }
        return parsed;
    }
References fl::Json::is_null(), mBody, and fl::Json::parse().
Referenced by json().