FastLED: fl::response::is_json
is_json()
bool fl::response::is_json () const inline
Check if response appears to contain JSON content.
Returns
true if Content-Type header indicates JSON or body contains JSON markers
Definition at line 127 of file fetch.h.
{
        auto content_type = get_content_type();
        if (content_type.has_value()) {
            fl::string ct = *content_type;
            // Check for various JSON content types (case-insensitive)
            return ct.find("json") != fl::string::npos;
        }
        return false;
    }
References fl::StrN< SIZE >::find(), get_content_type(), and fl::string::npos.
Referenced by json(), test_json_await(), and test_json_response().