FastLED: fl::Rpc::handle_maybe
handle_maybe()
fl::optional< json > fl::Rpc::handle_maybe (const json & request)
For notifications (no id), returns nullopt.
Definition at line 192 of file rpc.cpp.hpp.
{
    // If no id, this is a notification - process but don't return response
    if (!request.contains("id")) {
        // Still need to execute the method
        if (request.contains("method")) {
            auto methodOpt = request["method"].as_string();
            if (methodOpt.has_value()) {
                fl::string methodName = methodOpt.value();
                auto it = mRegistry.find(methodName);
                if (it != mRegistry.end()) {
                    json params = request.contains("params") ? request["params"] : json::parse("[]");
                    if (params.is_array()) {
                        it->second.mInvoker->invoke(params);
                    }
                }
            }
        }
        return fl::nullopt;
    }
    return handle(request);
}
References fl::json::as_string(), fl::json::contains(), handle(), fl::json::is_array(), mRegistry, fl::nullopt, and fl::json::parse().