FastLED: fl::Rpc::bind
bind() [2/2]
template<typename Callable> void fl::Rpc::bind (const Config< Callable > & config) inline
Bind a method with configuration (name, function, optional metadata).
Supports dot notation for namespacing: "led.setBrightness", "system.status" Use get() to retrieve a callable if you need to invoke the method from C++ code.
Definition at line 234 of file rpc.h.
{
        using Sig = typename callable_traits<typename decay<Callable>::type>::signature;
        RpcFn<Sig> wrapped(config.fn);
        registerMethod<Sig>(config.name.c_str(), wrapped, config.params, config.description, config.tags, config.mode);
    }
References bind(), and registerMethod().
Referenced by bind(), and bind().