FastLED: fl::Rpc::registerMethod
registerMethod()
template<class Sig> bool fl::Rpc::registerMethod (const char * name, RpcFn< Sig > fn, const fl::vector< fl::string > & paramNames, const fl::string & description, const fl::vector< fl::string > & tags, fl::RpcMode mode = fl::RpcMode::SYNC) inline
Definition at line 346 of file rpc.h.
{
        fl::string key(name);
        auto it = mRegistry.find(key);
        if (it != mRegistry.end()) {
            if (it->second.mTypeTag != detail::TypeTag<Sig>::id()) {
                return false;
            }
        }
        detail::RpcEntry entry;
        entry.mTypeTag = detail::TypeTag<Sig>::id();
        entry.mInvoker = fl::make_shared<detail::TypedInvoker<Sig>>(fn);
        entry.mTypedCallable = fl::make_shared<detail::TypedCallableHolder<Sig>>(fn);
#if FL_PLATFORM_HAS_LARGE_MEMORY
        // Schema generator construction gated on Low-memory targets per
        // FastLED #3081 / #3079. The schema generator is only consumed by
        // `rpc.discover` (also gated). Skipping it on Low-memory drops
        // `TypedSchemaGenerator<Sig>::params()` (~800 B per signature).
        entry.mSchemaGenerator = fl::make_shared<detail::TypedSchemaGenerator<Sig>>();
#endif
        entry.mDescription = description;
        entry.mTags = tags;
        entry.mMode = mode;
#if FL_PLATFORM_HAS_LARGE_MEMORY
        if (!paramNames.empty()) {
            entry.mSchemaGenerator->setParamNames(paramNames);
        }
#else
        (void)paramNames;
#endif
        mRegistry[key] = fl::move(entry);
        return true;
    }
References description, fl::vector_basic::empty(), fl::detail::TypeTag< Sig >::id(), fl::make_shared(), fl::detail::RpcEntry::mDescription, fl::detail::RpcEntry::mInvoker, fl::detail::RpcEntry::mMode, fl::fl::move(), mRegistry, fl::detail::RpcEntry::mSchemaGenerator, fl::detail::RpcEntry::mTags, fl::detail::RpcEntry::mTypedCallable, fl::detail::RpcEntry::mTypeTag, fl::SYNC, and tags().
Referenced by bind().