FastLED: fl::Rpc::methods
methods()
json fl::Rpc::methods () const
Returns flat method array: [["name", "returnType", [["param1", "type1"], ...]], ...] Format: Array of method tuples optimized for low-memory devices.
Each method is represented as: ["methodName", "returnType", [["param1", "type1"], ...]]
Definition at line 242 of file rpc.cpp.hpp.
{
    json arr = json::array();
    for (auto it = mRegistry.begin(); it != mRegistry.end(); ++it) {
        // Format: ["methodName", "returnType", [["param1", "type1"], ["param2", "type2"]], "mode"]
        json methodTuple = json::array();
        methodTuple.push_back(it->first.c_str());  // Method name
        methodTuple.push_back(it->second.mSchemaGenerator->resultTypeName());  // Return type
        methodTuple.push_back(it->second.mSchemaGenerator->params());  // Params array
        // Add mode (sync or async)
        const char* modeStr = (it->second.mMode == RpcMode::ASYNC) ? "async" : "sync";
        methodTuple.push_back(modeStr);
        arr.push_back(methodTuple);
    }
    return arr;
}
References fl::json::array(), fl::ASYNC, mRegistry, and fl::json::push_back().
Referenced by schema().