/// @file fl/gfx/_build.cpp.hpp
/// @brief Unity build for fl/gfx/ — graphics types, primitives, and simulators

#pragma once

#include "fl/gfx/blur.cpp.hpp"
#include "fl/gfx/colorutils.cpp.hpp"
#include "fl/gfx/corkscrew.cpp.hpp"
#include "fl/gfx/detail/_build.cpp.hpp"
#include "fl/gfx/downscale.cpp.hpp"
#include "fl/gfx/ease.cpp.hpp"
#include "fl/gfx/fill.cpp.hpp"
#include "fl/gfx/five_bit_hd_gamma.cpp.hpp"
#include "fl/gfx/gradient.cpp.hpp"
#include "fl/gfx/hsv16.cpp.hpp"
#include "fl/gfx/line_simplification.cpp.hpp"
#include "fl/gfx/noise.cpp.hpp"
#include "fl/gfx/noise_woryley.cpp.hpp"
#include "fl/gfx/raster_sparse.cpp.hpp"
#include "fl/gfx/rectangular_draw_buffer.cpp.hpp"
#include "fl/gfx/rgbw.cpp.hpp"
#include "fl/gfx/sample.cpp.hpp"
#include "fl/gfx/screenmap.cpp.hpp"
#include "fl/gfx/splat.cpp.hpp"
#include "fl/gfx/tile2x2.cpp.hpp"
#include "fl/gfx/transform.cpp.hpp"
#include "fl/gfx/upscale.cpp.hpp"
#include "fl/gfx/wave_simulation.cpp.hpp"
#include "fl/gfx/wave_simulation_real.cpp.hpp"
#include "fl/gfx/xmap.cpp.hpp"
#include "fl/gfx/xymap.cpp.hpp"
#include "fl/gfx/xypath.cpp.hpp"
#include "fl/gfx/xypath_impls.cpp.hpp"
#include "fl/gfx/xypath_renderer.cpp.hpp"
