FastLED: fl::NoisePalette::mapNoiseToLEDsUsingPalette
mapNoiseToLEDsUsingPalette()
void fl::NoisePalette::mapNoiseToLEDsUsingPalette (CRGB * leds)
Definition at line 109 of file noisepalette.cpp.
{
    static uint8_t ihue = 0;
    for (uint16_t i = 0; i < width; i++) {
        for (uint16_t j = 0; j < height; j++) {
            // We use the value at the (i,j) coordinate in the noise
            // array for our brightness, and the flipped value from (j,i)
            // for our pixel's index into the color palette.
            uint8_t index = noise.get()[i * height + j];
            uint8_t bri = noise.get()[j * width + i];
            // if this palette is a 'loop', add a slowly-changing base value
            if (colorLoop) {
                index += ihue;
            }
            // brighten up, as the color palette itself often contains the
            // light/dark dynamic range desired
            if (bri > 127) {
                bri = 255;
            } else {
                bri = dim8_raw(bri * 2);
            }
            CRGB color = ColorFromPalette(currentPalette, index, bri);
            leds[XY(i, j)] = color;
        }
    }
    ihue += 1;
}
References ColorFromPalette(), colorLoop, currentPalette, dim8_raw(), height, leds, noise, width, and XY().