FastLED: fl::NoisePalette::mapNoiseToLEDsUsingPalette
mapNoiseToLEDsUsingPalette()
void fl::NoisePalette::mapNoiseToLEDsUsingPalette (fl::span< CRGB > leds)
Definition at line 109 of file noisepalette.cpp.hpp.
{
    static u8 ihue = 0; // okay static in header
    for (u16 i = 0; i < width; i++) {
        for (u16 j = 0; j < height; j++) {
            // We use the value at the (i,j) coordinate in the noise
            // array for our brightness, and the flipped value from (j,i)
            // for our pixel's index into the color palette.
            u8 index = noise[i * height + j];
            u8 bri = noise[j * width + i];
            // if this palette is a 'loop', add a slowly-changing base value
            if (colorLoop) {
                index += ihue;
            }
            // brighten up, as the color palette itself often contains the
            // light/dark dynamic range desired
            if (bri > 127) {
                bri = 255;
            } else {
                bri = dim8_raw(bri * 2);
            }
            CRGB color = ColorFromPalette(currentPalette, index, bri);
            leds[XY(i, j)] = color;
        }
    }
    ihue += 1;
}
References fl::ColorFromPalette(), colorLoop, currentPalette, height, leds, noise, width, and XY().
Referenced by draw().