FastLED: fl::NoisePalette::NoisePalette
NoisePalette()
fl::NoisePalette::NoisePalette (XYMap xyMap, float fps = 60.f)
Definition at line 19 of file noisepalette.cpp.hpp.
    : Fx2d(xyMap), speed(0), scale(0), colorLoop(1), mFps(fps) {
    // currentPalette = PartyColors_p;
    FL_STATIC_ASSERT(sizeof(currentPalette) == sizeof(CRGBPalette16),
                  "Palette size mismatch");
    currentPalette = PartyColors_p;
    width = xyMap.getWidth();
    height = xyMap.getHeight();
    // Initialize our coordinates to some random values
    mX = random16();
    mY = random16();
    mZ = random16();
    setPalettePreset(0);
    // Allocate memory for the noise array using vector
    noise.resize(width * height);
}
References fl::Fx2d::Fx2d(), colorLoop, currentPalette, FL_STATIC_ASSERT, height, mFps, mX, mY, mZ, noise, PartyColors_p, random16(), scale, setPalettePreset(), speed, width, and fl::Fx2d::xyMap().