FastLED: fl::NoisePalette::fillnoise8
fillnoise8()
void fl::NoisePalette::fillnoise8 () private
Definition at line 142 of file noisepalette.cpp.
{
    // If we're running at a low "speed", some 8-bit artifacts become
    // visible from frame-to-frame.  In order to reduce this, we can do some
    // fast data-smoothing. The amount of data smoothing we're doing depends
    // on "speed".
    uint8_t dataSmoothing = 0;
    if (speed < 50) {
        dataSmoothing = 200 - (speed * 4);
    }
    for (uint16_t i = 0; i < width; i++) {
        int ioffset = scale * i;
        for (uint16_t j = 0; j < height; j++) {
            int joffset = scale * j;
            uint8_t data = inoise8(mX + ioffset, mY + joffset, mZ);
            // The range of the inoise8 function is roughly 16-238.
            // These two operations expand those values out to roughly
            // 0..255 You can comment them out if you want the raw noise
            // data.
            data = qsub8(data, 16);
            data = qadd8(data, scale8(data, 39));
            if (dataSmoothing) {
                uint8_t olddata = noise.get()[i * height + j];
                uint8_t newdata = scale8(olddata, dataSmoothing) +
                                  scale8(data, 256 - dataSmoothing);
                data = newdata;
            }
            noise.get()[i * height + j] = data;
        }
    }
    mZ += speed;
    // apply slow drift to X and Y, just for visual variation.
    mX += speed / 8;
    mY -= speed / 16;
}
References height, inoise8(), mX, mY, mZ, noise, qadd8(), qsub8(), scale, scale8(), speed, and width.
Referenced by draw().