FastLED: CRGBPalette16::CRGBPalette16
CRGBPalette16() [1/16]
CRGBPalette16::CRGBPalette16 () inline
Default constructor.
Warning
Default values are UNITIALIZED!
Definition at line 1009 of file colorutils.h.
{};
Referenced by CRGBPalette16(), loadDynamicGradientPalette(), operator!=(), operator=(), operator=(), operator=(), operator=(), operator=(), operator=(), and operator==().