FastLED: PixelController::loadAndScale
loadAndScale() [2/4]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> template<int SLOT> static FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::loadAndScale (PixelController< RGB_ORDER, LANES, MASK > & pc, int lane) inline static
Loads, dithers, and scales a single byte for a given output slot and lane, using class dither and scale values.
Template Parameters
SLOT The data slot in the output stream. This is used to select which byte of the output stream is being processed.
Parameters
pc reference to the pixel controller
lane the parallel output lane to read the byte for
Definition at line 385 of file pixel_controller.h.
{ return scale<SLOT>(pc, pc.dither<SLOT>(pc, pc.loadByte<SLOT>(pc, lane))); }
References PixelController(), dither(), FASTLED_FORCE_INLINE, loadByte(), and scale.