FastLED: PixelController::enable_dithering
enable_dithering()
template<EOrder RGB_ORDER, int LANES = 1, fl::u32 MASK = 0xFFFFFFFF> void PixelController< RGB_ORDER, LANES, MASK >::enable_dithering (EDitherMode dither) inline
Toggle dithering enable/disable.
Parameters
dither BINARY_DITHER (on) or DISABLE_DITHER (off)
Definition at line 374 of file pixel_controller.h.
{
        switch(dither) {
            case BINARY_DITHER: init_binary_dithering(); break;  // Initialize dithering algorithm
            default: d[0]=d[1]=d[2]=e[0]=e[1]=e[2]=0; break;     // Clear dither values (disabled)
        }
    }
References BINARY_DITHER, d, dither(), e, and init_binary_dithering().
Referenced by PixelController(), PixelController(), and PixelController().