FastLED: PixelController::loadAndScaleRGBW
loadAndScaleRGBW()
template<EOrder RGB_ORDER, int LANES = 1, fl::u32 MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE void PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGBW (Rgbw rgbw, fl::u8 * b0_out, fl::u8 * b1_out, fl::u8 * b2_out, fl::u8 * b3_out) inline
Definition at line 591 of file pixel_controller.h.
{
#ifdef FL_IS_AVR
        // Don't do RGBW conversion for AVR, just set the W pixel to black.
        fl::u8 out[4] = {
            // Get the pixels in native order.
            loadAndScale0(),
            loadAndScale1(),
            loadAndScale2(),
            0,
        };
        EOrderW w_placement = rgbw.w_placement;
        // Apply w-component insertion.
        fl::rgbw_partial_reorder(
            w_placement, out[0], out[1], out[2],
            0, // Pre-ordered RGB data with a 0 white component.
            b0_out, b1_out, b2_out, b3_out);
#else
        const fl::u8 b0_index = RGB_BYTE0(RGB_ORDER);  // Needed to re-order RGB back into led native order.
        const fl::u8 b1_index = RGB_BYTE1(RGB_ORDER);
        const fl::u8 b2_index = RGB_BYTE2(RGB_ORDER);
        // Get the naive RGB data order in r,g,b order.
        CRGB rgb(mData[0], mData[1], mData[2]);
        fl::u8 w = 0;
        fl::rgb_2_rgbw(rgbw.rgbw_mode,
                   rgbw.white_color_temp,
                   rgb.r, rgb.g, rgb.b,  // Input colors
                   mColorAdjustment.premixed.r, mColorAdjustment.premixed.g, mColorAdjustment.premixed.b,  // How these colors are scaled for color balance.
                   &rgb.r, &rgb.g, &rgb.b, &w);
        // Now finish the ordering so that the output is in the native led order for all of RGBW.
        fl::rgbw_partial_reorder(
            rgbw.w_placement,
            rgb.raw[b0_index],  // in-place re-ordering for the RGB data.
            rgb.raw[b1_index],
            rgb.raw[b2_index],
            w,  // The white component is not ordered in this call.
            b0_out, b1_out, b2_out, b3_out);  // RGBW data now in total native led order.
#endif
    }
References FASTLED_FORCE_INLINE, loadAndScale0(), loadAndScale1(), loadAndScale2(), mColorAdjustment, mData, fl::rgb_2_rgbw(), RGB_BYTE0, RGB_BYTE1, RGB_BYTE2, RGB_ORDER, rgbw, and fl::rgbw_partial_reorder().
Referenced by RGBWEmulatedController< CONTROLLER, RGB_ORDER >::showPixels().