FastLED: PixelController::PixelController
PixelController() [3/5]
template<EOrder RGB_ORDER, int LANES = 1, fl::u32 MASK = 0xFFFFFFFF> PixelController< RGB_ORDER, LANES, MASK >::PixelController (const fl::u8 * d, int len, ColorAdjustment color_adjustment, EDitherMode dither, bool advance, fl::u8 skip) inline
Constructor.
Parameters
d pointer to LED data
len length of the LED data
color_adjustment LED scale values
dither dither setting for the LEDs
advance whether the pointer (d) should advance per LED
skip if the pointer is advancing, how many bytes to skip in addition to 3
Definition at line 173 of file pixel_controller.h.
                : mData(d), mLen(len), mLenRemaining(len), mColorAdjustment(color_adjustment) {
        enable_dithering(dither);
        mData += skip;
        mAdvance = (advance) ? 3+skip : 0;
        initOffsets(len);
    }
References d, dither(), enable_dithering(), initOffsets(), mAdvance, mColorAdjustment, mData, mLen, and mLenRemaining.