FastLED: PixelController::loadAndScaleRGB
loadAndScaleRGB()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE void PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGB (uint8_t * b0_out, uint8_t * b1_out, uint8_t * b2_out) inline
Definition at line 512 of file pixel_controller.h.
{
        *b0_out = loadAndScale0();
        *b1_out = loadAndScale1();
        *b2_out = loadAndScale2();
    }
References FASTLED_FORCE_INLINE, loadAndScale0(), loadAndScale1(), and loadAndScale2().
Referenced by APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::getGlobalBrightnessAndScalingFactors(), and APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsDefault().