FastLED: PixelController::loadAndScale
loadAndScale() [3/4]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> template<int SLOT> static FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::loadAndScale (PixelController< RGB_ORDER, LANES, MASK > & pc, int lane, uint8_t d, uint8_t scale) inline static
Loads, dithers, and scales a single byte for a given output slot and lane.
Template Parameters
SLOT The data slot in the output stream. This is used to select which byte of the output stream is being processed.
Parameters
pc reference to the pixel controller
lane the parallel output lane to read the byte for
d the dither data for the byte
scale the scale data for the byte
Definition at line 393 of file pixel_controller.h.
{ return scale8(pc.dither<SLOT>(pc, pc.loadByte<SLOT>(pc, lane), d), scale); }
References PixelController(), d, dither(), FASTLED_FORCE_INLINE, loadByte(), scale(), and scale8().