FastLED: PixelController::advanceAndLoadAndScale
advanceAndLoadAndScale() [2/3]
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> template<int SLOT> static FASTLED_FORCE_INLINE uint8_t PixelController< RGB_ORDER, LANES, MASK >::advanceAndLoadAndScale (PixelController< RGB_ORDER, LANES, MASK > & pc, int lane) inline static
A version of loadAndScale() that advances the output data pointer.
Parameters
pc reference to the pixel controller
lane the parallel output lane to read the byte for
Definition at line 415 of file pixel_controller.h.
{ pc.advanceData(); return pc.loadAndScale<SLOT>(pc, lane); }
References PixelController(), advanceData(), FASTLED_FORCE_INLINE, and loadAndScale().