FastLED: PixelController::loadAndScale_WS2816_HD
loadAndScale_WS2816_HD()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE void PixelController< RGB_ORDER, LANES, MASK >::loadAndScale_WS2816_HD (uint16_t * s0_out, uint16_t * s1_out, uint16_t * s2_out) inline
Definition at line 526 of file pixel_controller.h.
{
        // Note that the WS2816 has a 4 bit gamma correction built in. To improve things this algorithm may
        // change in the future with a partial gamma correction that is completed by the chipset gamma
        // correction.
        uint16_t r16 = map8_to_16(mData[0]);
        uint16_t g16 = map8_to_16(mData[1]);
        uint16_t b16 = map8_to_16(mData[2]);
        if (r16 || g16 || b16) {
    #if FASTLED_HD_COLOR_MIXING
            uint8_t brightness = mColorAdjustment.brightness;
            CRGB scale = mColorAdjustment.color;
    #else
            uint8_t brightness = 255;
            CRGB scale = mColorAdjustment.premixed;
    #endif
            if (scale[0] != 255) {
                r16 = scale16by8(r16, scale[0]);
            }
            if (scale[1] != 255) {
                g16 = scale16by8(g16, scale[1]);
            }
            if (scale[2] != 255) {
                b16 = scale16by8(b16, scale[2]);
            }
            if (brightness != 255) {
                r16 = scale16by8(r16, brightness);
                g16 = scale16by8(g16, brightness);
                b16 = scale16by8(b16, brightness);
            }
        }
        uint16_t rgb16[3] = {r16, g16, b16};
        const uint8_t s0_index = RGB_BYTE0(RGB_ORDER);
        const uint8_t s1_index = RGB_BYTE1(RGB_ORDER);
        const uint8_t s2_index = RGB_BYTE2(RGB_ORDER);
        *s0_out = rgb16[s0_index];
        *s1_out = rgb16[s1_index];
        *s2_out = rgb16[s2_index];
    }
References brightness, FASTLED_FORCE_INLINE, map8_to_16(), mColorAdjustment, mData, RGB_BYTE0, RGB_BYTE1, RGB_BYTE2, scale(), and scale16by8().
Referenced by WS2816Controller< DATA_PIN, RGB_ORDER >::showPixels().