FastLED: PixelController::loadAndScaleRGBWW
loadAndScaleRGBWW()
template<EOrder RGB_ORDER, int LANES = 1, fl::u32 MASK = 0xFFFFFFFF> FASTLED_FORCE_INLINE void PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGBWW (fl::Rgbww rgbww, fl::u8 * b0_out, fl::u8 * b1_out, fl::u8 * b2_out, fl::u8 * b3_out, fl::u8 * b4_out) inline
Load + scale a single pixel to 5-channel RGBWW (issue #2558).
Mirrors loadAndScaleRGBW: applies the per-channel premix scale, dispatches to rgb_2_rgbww for the colorimetric solve, then routes the five output bytes through rgbww_partial_reorder for the wire-order placement.
Definition at line 635 of file pixel_controller.h.
{
#ifdef FL_IS_AVR
        // AVR: float colorimetric math is too expensive on the 8-bit core;
        // the strip will get RGB-only output with both white channels black.
        // Surface this with a FL_WARN_ONCE so the silent dropout is visible
        // when debugging — a user configuring RGBWW on an AVR target almost
        // certainly didn't expect their warm/cool W channels to be inert.
        FL_WARN_ONCE("RGBWW colorimetric is not supported on AVR — the warm "
                     "and cool white channels will be black. Use an ESP32 / "
                     "Teensy / RP2040 target for full RGBWW support.");
        fl::u8 r_pre = loadAndScale0();
        fl::u8 g_pre = loadAndScale1();
        fl::u8 b_pre = loadAndScale2();
        fl::rgbww_partial_reorder(
            rgbww.w_placement,
            r_pre, g_pre, b_pre,
            0, 0,
            b0_out, b1_out, b2_out, b3_out, b4_out);
#else
        const fl::u8 b0_index = RGB_BYTE0(RGB_ORDER);
        const fl::u8 b1_index = RGB_BYTE1(RGB_ORDER);
        const fl::u8 b2_index = RGB_BYTE2(RGB_ORDER);
        CRGB rgb(mData[0], mData[1], mData[2]);
        fl::u8 ww = 0;
        fl::u8 wc = 0;
        fl::rgb_2_rgbww(rgbww,
                        rgb.r, rgb.g, rgb.b,
                        mColorAdjustment.premixed.r,
                        mColorAdjustment.premixed.g,
                        mColorAdjustment.premixed.b,
                        &rgb.r, &rgb.g, &rgb.b, &ww, &wc);
        fl::rgbww_partial_reorder(
            rgbww.w_placement,
            rgb.raw[b0_index],
            rgb.raw[b1_index],
            rgb.raw[b2_index],
            ww, wc,
            b0_out, b1_out, b2_out, b3_out, b4_out);
#endif
    }
References FASTLED_FORCE_INLINE, FL_WARN_ONCE, loadAndScale0(), loadAndScale1(), loadAndScale2(), mColorAdjustment, mData, fl::rgb_2_rgbww(), RGB_BYTE0, RGB_BYTE1, RGB_BYTE2, RGB_ORDER, fl::rgbww_partial_reorder(), and fl::Rgbww::w_placement.