FastLED: AVRSoftwareSPIOutput::writeBytes
writeBytes() [1/2]
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> template<class D> void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytes (FASTLED_REGISTER uint8_t * data, int len) inline
Write an array of data to the SPI interface.
Template Parameters
D Per-byte modifier class, e.g. DATA_NOP
Parameters
data pointer to data to write
len number of bytes to write
Todo
Need to type this better so that explicit casts into the call aren't required.
Definition at line 298 of file fastspi_bitbang.h.
{
        select();
#ifdef FAST_SPI_INTERRUPTS_WRITE_PINS
        uint8_t *end = data + len;
        while(data != end) {
            writeByte(D::adjust(*data++));
        }
#else
        FASTLED_REGISTER clock_ptr_t clockpin = FastPin<CLOCK_PIN>::port();
        FASTLED_REGISTER data_ptr_t datapin = FastPin<DATA_PIN>::port();
        if(FastPin<DATA_PIN>::port() != FastPin<CLOCK_PIN>::port()) {
            // If data and clock are on different ports, then writing a bit will consist of writing the value foor
            // the bit (hi or low) to the data pin port, and then two writes to the clock port to strobe the clock line
            FASTLED_REGISTER data_t datahi = FastPin<DATA_PIN>::hival();
            FASTLED_REGISTER data_t datalo = FastPin<DATA_PIN>::loval();
            FASTLED_REGISTER clock_t clockhi = FastPin<CLOCK_PIN>::hival();
            FASTLED_REGISTER clock_t clocklo = FastPin<CLOCK_PIN>::loval();
            uint8_t *end = data + len;
            while(data != end) {
                writeByte(D::adjust(*data++), clockpin, datapin, datahi, datalo, clockhi, clocklo);
            }
        } else {
            // FastPin<CLOCK_PIN>::hi();
            // If data and clock are on the same port then we can combine setting the data and clock pins
            FASTLED_REGISTER data_t datahi_clockhi = FastPin<DATA_PIN>::hival() | FastPin<CLOCK_PIN>::mask();
            FASTLED_REGISTER data_t datalo_clockhi = FastPin<DATA_PIN>::loval() | FastPin<CLOCK_PIN>::mask();
            FASTLED_REGISTER data_t datahi_clocklo = FastPin<DATA_PIN>::hival() & ~FastPin<CLOCK_PIN>::mask();
            FASTLED_REGISTER data_t datalo_clocklo = FastPin<DATA_PIN>::loval() & ~FastPin<CLOCK_PIN>::mask();
            uint8_t *end = data + len;
            while(data != end) {
                writeByte(D::adjust(*data++), datapin, datahi_clockhi, datalo_clockhi, datahi_clocklo, datalo_clocklo);
            }
            // FastPin<CLOCK_PIN>::lo();
        }
#endif
        D::postBlock(len);
        release();
    }
References FASTLED_REGISTER, FastPin< PIN >::hival(), FastPin< PIN >::loval(), FastPin< PIN >::mask(), FastPin< PIN >::port(), release(), select(), and writeByte().
Referenced by writeBytes().