FastLED: AVRSoftwareSPIOutput::writeBytesValue
writeBytesValue()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytesValue (uint8_t value, int len) inline
Write multiple bytes of the given value over SPI.
Useful for quickly flushing, say, a line of 0's down the line.
Parameters
value the value to write to the bus
len how many copies of the value to write
Definition at line 248 of file fastspi_bitbang.h.
{
        select();
        writeBytesValueRaw(value, len);
        release();
    }
References release(), select(), and writeBytesValueRaw().