FastLED: AVRSoftwareSPIOutput::writeBytesValueRaw
writeBytesValueRaw()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, uint32_t SPI_SPEED> static void AVRSoftwareSPIOutput< DATA_PIN, CLOCK_PIN, SPI_SPEED >::writeBytesValueRaw (uint8_t value, int len) inline static
Write multiple bytes of the given value over SPI, without selecting the interface.
Useful for quickly flushing, say, a line of 0's down the line.
Parameters
value the value to write to the bus
len how many copies of the value to write
Definition at line 256 of file fastspi_bitbang.h.
{
#ifdef FAST_SPI_INTERRUPTS_WRITE_PINS
        // TODO: Weird things may happen if software bitbanging SPI output and other pins on the output reigsters are being twiddled.  Need
        // to allow specifying whether or not exclusive i/o access is allowed during this process, and if i/o access is not allowed fall
        // back to the degenerative code below
        while(len--) {
            writeByte(value);
        }
#else
        FASTLED_REGISTER data_ptr_t datapin = FastPin<DATA_PIN>::port();
        if(FastPin<DATA_PIN>::port() != FastPin<CLOCK_PIN>::port()) {
            // If data and clock are on different ports, then writing a bit will consist of writing the value foor
            // the bit (hi or low) to the data pin port, and then two writes to the clock port to strobe the clock line
            FASTLED_REGISTER clock_ptr_t clockpin = FastPin<CLOCK_PIN>::port();
            FASTLED_REGISTER data_t datahi = FastPin<DATA_PIN>::hival();
            FASTLED_REGISTER data_t datalo = FastPin<DATA_PIN>::loval();
            FASTLED_REGISTER clock_t clockhi = FastPin<CLOCK_PIN>::hival();
            FASTLED_REGISTER clock_t clocklo = FastPin<CLOCK_PIN>::loval();
            while(len--) {
                writeByte(value, clockpin, datapin, datahi, datalo, clockhi, clocklo);
            }
        } else {
            // If data and clock are on the same port then we can combine setting the data and clock pins
            FASTLED_REGISTER data_t datahi_clockhi = FastPin<DATA_PIN>::hival() | FastPin<CLOCK_PIN>::mask();
            FASTLED_REGISTER data_t datalo_clockhi = FastPin<DATA_PIN>::loval() | FastPin<CLOCK_PIN>::mask();
            FASTLED_REGISTER data_t datahi_clocklo = FastPin<DATA_PIN>::hival() & ~FastPin<CLOCK_PIN>::mask();
            FASTLED_REGISTER data_t datalo_clocklo = FastPin<DATA_PIN>::loval() & ~FastPin<CLOCK_PIN>::mask();
            while(len--) {
                writeByte(value, datapin, datahi_clockhi, datalo_clockhi, datahi_clocklo, datalo_clocklo);
            }
        }
#endif
    }
References FASTLED_REGISTER, FastPin< PIN >::hival(), FastPin< PIN >::loval(), FastPin< PIN >::mask(), FastPin< PIN >::port(), and writeByte().
Referenced by LPD8806Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::LPD8806_ADJUST::postBlock(), and writeBytesValue().