FastLED: fl::spi::ParallelDevice::ParallelDevice
ParallelDevice() [1/3]
fl::spi::ParallelDevice::ParallelDevice (const Config & config) explicit
Construct parallel device.
Parameters
config Configuration with 1-32 GPIO pins
Definition at line 136 of file parallel_device.cpp.hpp.
    : pImpl(fl::make_unique<Impl>(config)) {
    // Validate configuration
    size_t num_pins = config.gpio_pins.size();
    if (num_pins == 0 || num_pins > 32) {
        FL_WARN("ParallelDevice: Invalid number of GPIO pins (" << num_pins
                << "), must be 1-32");
    }
    FL_DBG("ParallelDevice: Created with " << num_pins << " GPIO pins");
}
References FL_DBG, FL_WARN, fl::spi::ParallelDevice::Config::gpio_pins, fl::make_unique(), pImpl, and fl::vector_basic::size().
Referenced by ParallelDevice(), ParallelDevice(), operator=(), and operator=().