FastLED: fl::spi::ParallelDevice::write
write()
Result< Transaction > fl::spi::ParallelDevice::write (const u8 * data, size_t size)
Write data (single stream drives all pins via LUT)
Parameters
data Data to transmit
size Number of bytes
Returns
Result containing Transaction handle or error
Note
Each byte value is mapped via LUT to GPIO pin states
Definition at line 235 of file parallel_device.cpp.hpp.
{
    if (!isReady()) {
        return Result<Transaction>::failure(SPIError::NOT_INITIALIZED,
            "Device not initialized");
    }
    if (!data || size == 0) {
        return Result<Transaction>::failure(SPIError::ALLOCATION_FAILED,
            "Invalid data or size");
    }
    // Write implementation depends on backend type
    // For now, return not implemented
    return Result<Transaction>::failure(SPIError::NOT_SUPPORTED,
        "ParallelDevice::write() not yet implemented");
}
References fl::expected< T, E >::failure(), and isReady().
Referenced by operator=().