FastLED: fl::JsonArgConverter< R()>::convert
convert()
template<typename R> static fl::tuple< args_tuple, TypeConversionResult > fl::JsonArgConverter< R()>::convert (const json & jsonArgs) inline static
Definition at line 137 of file json_arg_converter.h.
{
        TypeConversionResult result;
        // Value-init so the early-return branches below (not an array,
        // arg-count mismatch) don't return an indeterminate tuple —
        // convertArgs() is the only writer and runs after the bail-outs. #2722
        args_tuple tuple{};
        if (!jsonArgs.is_array()) {
            result.setError("arguments must be a JSON array");
            return fl::make_tuple(tuple, result);
        }
        if (jsonArgs.size() != 0) {
            result.setError("argument count mismatch: expected 0, got " +
                           fl::to_string(static_cast<i64>(jsonArgs.size())));
        }
        return fl::make_tuple(tuple, result);
    }
References fl::json::is_array(), fl::make_tuple(), fl::json::size(), and fl::to_string().