FastLED: fl::anonymous_namespace{mp4_parser.cpp.hpp}::parseAvcC
parseAvcC()
bool fl::anonymous_namespace{mp4_parser.cpp.hpp}::parseAvcC (fl::span< const fl::u8 > data, fl::size offset, fl::size boxEnd, Mp4TrackInfo & info)
Definition at line 46 of file mp4_parser.cpp.hpp.
{
    // avcC box: 8 bytes header, then:
    //   u8 configVersion (1)
    //   u8 profile_idc
    //   u8 profile_compat
    //   u8 level_idc
    //   u8 lengthSizeMinusOne (& 0x03)
    //   u8 numSPS (& 0x1F)
    //   for each SPS: u16 spsLength, u8[] spsData
    //   u8 numPPS
    //   for each PPS: u16 ppsLength, u8[] ppsData
    fl::size pos = offset + 8; // skip box header
    if (pos + 6 > boxEnd) return false;
    fl::u8 configVersion = data[pos++];
    if (configVersion != 1) return false;
    info.profile = data[pos++];
    pos++; // profile_compat
    info.level = data[pos++];
    info.lengthSizeMinusOne = data[pos++] & 0x03;
    fl::u8 numSPS = data[pos++] & 0x1F;
    for (fl::u8 i = 0; i < numSPS; i++) {
        bool ok = true;
        fl::u16 spsLen = readU16BE(data, pos, ok);
        if (!ok) return false;
        pos += 2;
        if (pos + spsLen > boxEnd) return false;
        fl::vector<fl::u8> sps(spsLen);
        for (fl::u16 j = 0; j < spsLen; j++) {
            sps[j] = data[pos + j];
        }
        info.sps.push_back(sps);
        pos += spsLen;
    }
    if (pos >= boxEnd) return false;
    fl::u8 numPPS = data[pos++];
    for (fl::u8 i = 0; i < numPPS; i++) {
        bool ok = true;
        fl::u16 ppsLen = readU16BE(data, pos, ok);
        if (!ok) return false;
        pos += 2;
        if (pos + ppsLen > boxEnd) return false;
        fl::vector<fl::u8> pps(ppsLen);
        for (fl::u16 j = 0; j < ppsLen; j++) {
            pps[j] = data[pos + j];
        }
        info.pps.push_back(pps);
        pos += ppsLen;
    }
    return true;
}
References fl::Mp4TrackInfo::lengthSizeMinusOne, fl::Mp4TrackInfo::level, offset(), parseAvcC(), pos, fl::Mp4TrackInfo::pps, fl::Mp4TrackInfo::profile, fl::vector< T >::push_back(), readU16BE(), and fl::Mp4TrackInfo::sps.
Referenced by parseAvcC().