FastLED: fl::anonymous_namespace{mp4_parser.cpp.hpp}::findBox
findBox()
fl::size fl::anonymous_namespace{mp4_parser.cpp.hpp}::findBox (fl::span< const fl::u8 > data, fl::size start, fl::size end, const char * type)
Definition at line 32 of file mp4_parser.cpp.hpp.
{
    fl::size pos = start;
    while (pos + 8 <= end) {
        bool ok = true;
        fl::u32 boxSize = readU32BE(data, pos, ok);
        if (!ok || boxSize < 8) break;
        if (boxIs(data, pos + 4, type)) return pos;
        pos += boxSize;
    }
    return fl::size(-1); // not found
}
References boxIs(), fl::end(), findBox(), pos, and readU32BE().
Referenced by findBox().