FastLED: fl::Potentiometer::Potentiometer
Potentiometer()
Potentiometer::Potentiometer (int pin, u16 hysteresis = 0)
Definition at line 30 of file potentiometer.cpp.hpp.
    : mPot(pin), mListener(this), mHysteresis(hysteresis) {
    // Initialize calibration range to full ADC range
    mMinValue = 0;
    mMaxValue = getAdcMaxValue();
    // Read initial value
    mCurrentValue = mPot.read();
    mLastValue = mCurrentValue;
    // Auto-calculate hysteresis if not specified (1% of calibrated range)
    if (mHysteresis == 0) {
        mHysteresis = calculateDefaultHysteresis();
    }
}
References calculateDefaultHysteresis(), getAdcMaxValue(), mCurrentValue, mHysteresis, mLastValue, mListener, mMaxValue, mMinValue, and mPot.
Referenced by fl::Potentiometer::Listener::Listener(), and onChange().