FastLED: fl::u24x8::exp2_fp
exp2_fp()
static FASTLED_FORCE_INLINE u24x8 fl::u24x8::exp2_fp (u24x8 x) inline static private
Definition at line 242 of file u24x8.h.
{
        u24x8 fl_val = floor(x);
        u24x8 fr = x - fl_val;
        u32 n = fl_val.mValue >> FRAC_BITS;
        if (n >= INT_BITS) return from_raw(0xFFFFFFFF);
        u32 int_pow;
        int_pow = static_cast<u32>(SCALE) << n;
        // 4-term minimax coefficients for 2^t - 1, t in [0,1).
        // Stored as u64 with 16 fractional bits.
        constexpr int IFRAC = 16;
        constexpr u64 d0 = 45427ULL;    // 0.69316 * 2^16
        constexpr u64 d1 = 15775ULL;    // 0.24071 * 2^16
        constexpr u64 d2 = 3497ULL;     // 0.05336 * 2^16
        constexpr u64 d3 = 836ULL;      // 0.01276 * 2^16
        // Extend fr from 8 to 16 frac bits.
        u64 fr16 = static_cast<u64>(fr.mValue) << (IFRAC - FRAC_BITS);
        // Horner: 1 + fr * (d0 + fr * (d1 + fr * (d2 + fr * d3)))
        u64 acc = d3;
        acc = d2 + ((acc * fr16) >> IFRAC);
        acc = d1 + ((acc * fr16) >> IFRAC);
        acc = d0 + ((acc * fr16) >> IFRAC);
        constexpr u64 one16 = 1ULL << IFRAC;
        u64 frac_pow16 = one16 + ((acc * fr16) >> IFRAC);
        // Convert from 16 frac bits to 8 frac bits, then scale by int_pow.
        u32 frac_pow8 = static_cast<u32>(frac_pow16 >> (IFRAC - FRAC_BITS));
        u64 result =
            (static_cast<u64>(int_pow) * frac_pow8) >> FRAC_BITS;
        return from_raw(static_cast<u32>(result));
    }
References u24x8(), FASTLED_FORCE_INLINE, FL_NOEXCEPT, floor(), FRAC_BITS, from_raw(), INT_BITS, mValue, SCALE, and fl::x.
Referenced by pow().