FastLED: fl::audio::NoiseFloorTracker::updateFloor
updateFloor()
void fl::audio::NoiseFloorTracker::updateFloor (float level) private
Update floor estimate based on current observation.
Parameters
level Observed signal level
Definition at line 76 of file noise_floor_tracker.cpp.hpp.
{
    // Exponential moving average tracking of noise floor
    // with asymmetric rates for rise (attack) and fall (decay)
    //
    // Hysteresis is achieved through the slow attack rate, not through
    // explicit blocking of updates
    if (level < mCurrentFloor) {
        // Signal is below floor - floor should decay (decrease) rapidly toward signal
        // Use decay rate (typically high, like 0.99) for downward movement
        const float decayAlpha = mConfig.decayRate;
        mCurrentFloor = decayAlpha * mCurrentFloor + (1.0f - decayAlpha) * level;
        mBelowFloorCount++;
        mStats.inHysteresis = false;
        // Track floor drops for statistics
        if (mLastHysteresisFloor > 0.0f && (mLastHysteresisFloor - mCurrentFloor) >= mConfig.hysteresisMargin) {
            mLastHysteresisFloor = mCurrentFloor;
        }
    } else {
        // Signal is above floor - floor should rise slowly toward signal
        // Use attack rate (typically low, like 0.01-0.05) for upward movement
        // This slow rise prevents chasing transient peaks
        const float attackAlpha = 1.0f - mConfig.attackRate;
        mCurrentFloor = attackAlpha * mCurrentFloor + mConfig.attackRate * level;
        mBelowFloorCount = 0;
        mStats.inHysteresis = false;
        // Update hysteresis reference when floor rises significantly
        if (mCurrentFloor - mLastHysteresisFloor >= mConfig.hysteresisMargin) {
            mLastHysteresisFloor = mCurrentFloor;
            mStats.inHysteresis = true;  // Indicate significant rise
        }
    }
    // Clamp to configured range
    mCurrentFloor = fl::max(mConfig.minFloor, fl::min(mConfig.maxFloor, mCurrentFloor));
}
References fl::max(), mBelowFloorCount, mConfig, mCurrentFloor, fl::min(), mLastHysteresisFloor, and mStats.
Referenced by update().