FastLED: fl::audio::NoiseFloorTracker::update
update()
void fl::audio::NoiseFloorTracker::update (float timedomainLevel, float frequencydomainLevel = -1.0f)
Update noise floor estimate with new observation.
Parameters
timedomainLevel Time-domain metric (e.g., RMS, peak)
frequencydomainLevel Optional frequency-domain metric (e.g., spectral energy)
Definition at line 36 of file noise_floor_tracker.cpp.hpp.
{
    if (!mConfig.enabled) {
        return;
    }
    // Combine time and frequency domain metrics if both provided
    float combinedLevel = combineDomains(timedomainLevel, frequencydomainLevel);
    // Update statistics
    if (mStats.samplesProcessed == 0) {
        mStats.minObserved = combinedLevel;
        mStats.maxObserved = combinedLevel;
        // Initialize floor to first observed level
        mCurrentFloor = fl::max(mConfig.minFloor, fl::min(mConfig.maxFloor, combinedLevel));
        mLastHysteresisFloor = mCurrentFloor;
    } else {
        mStats.minObserved = fl::min(mStats.minObserved, combinedLevel);
        mStats.maxObserved = fl::max(mStats.maxObserved, combinedLevel);
    }
    mStats.samplesProcessed++;
    // Update floor based on current observation
    updateFloor(combinedLevel);
    // Update stats
    mStats.currentFloor = mCurrentFloor;
}
References combineDomains(), fl::max(), mConfig, mCurrentFloor, fl::min(), mLastHysteresisFloor, mStats, and updateFloor().
Referenced by ~NoiseFloorTracker().