FastLED: fl::SerialPort::parseInt
parseInt()
long fl::SerialPort::parseInt ()
Parse integer from serial input.
Returns
Parsed integer value, or 0 if no valid integer found
Skips non-numeric characters until a number is found, then parses it. Stops at first non-numeric character after the number.
Definition at line 225 of file serial.cpp.hpp.
{
    bool negative = false;
    long value = 0;
    bool foundDigit = false;
    u32 startTime = fl::millis();
    // Skip non-numeric characters
    while (fl::millis() - startTime < mTimeoutMs) {
        if (available() > 0) {
            int c = peek();
            if (c == -1) {
                continue;
            }
            // Check for sign
            if (c == '-') {
                negative = true;
                read();  // Consume the sign
                break;
            } else if (c == '+') {
                read();  // Consume the sign
                break;
            } else if (c >= '0' && c <= '9') {
                break;  // Found a digit
            } else {
                read();  // Skip non-numeric character
                startTime = fl::millis();  // Reset timeout
            }
        }
    }
    // Parse digits
    startTime = fl::millis();
    while (fl::millis() - startTime < mTimeoutMs) {
        if (available() > 0) {
            int c = peek();
            if (c == -1) {
                continue;
            }
            if (c >= '0' && c <= '9') {
                value = value * 10 + (c - '0');
                read();  // Consume the digit
                foundDigit = true;
                startTime = fl::millis();  // Reset timeout
            } else {
                break;  // Non-digit, stop parsing
            }
        }
    }
    return foundDigit ? (negative ? -value : value) : 0;
}
References available(), fl::millis(), mTimeoutMs, peek(), read(), and fl::type_rank< T >::value.