FastLED: fl::SerialPort::parseFloat
parseFloat()
float fl::SerialPort::parseFloat ()
Parse floating-point number from serial input.
Returns
Parsed float value, or 0.0 if no valid float found
Skips non-numeric characters until a number is found, then parses it. Stops at first non-numeric character after the number.
Definition at line 279 of file serial.cpp.hpp.
{
    bool negative = false;
    long intPart = 0;
    long fracPart = 0;
    int fracDigits = 0;
    bool foundDigit = false;
    bool inFraction = false;
    u32 startTime = fl::millis();
    // Skip non-numeric characters
    while (fl::millis() - startTime < mTimeoutMs) {
        if (available() > 0) {
            int c = peek();
            if (c == -1) {
                continue;
            }
            // Check for sign
            if (c == '-') {
                negative = true;
                read();  // Consume the sign
                break;
            } else if (c == '+') {
                read();  // Consume the sign
                break;
            } else if (c >= '0' && c <= '9') {
                break;  // Found a digit
            } else if (c == '.') {
                break;  // Found decimal point
            } else {
                read();  // Skip non-numeric character
                startTime = fl::millis();  // Reset timeout
            }
        }
    }
    // Parse digits (integer and fractional parts)
    startTime = fl::millis();
    while (fl::millis() - startTime < mTimeoutMs) {
        if (available() > 0) {
            int c = peek();
            if (c == -1) {
                continue;
            }
            if (c == '.' && !inFraction) {
                inFraction = true;
                read();  // Consume decimal point
                foundDigit = true;  // Decimal point counts as finding a number
                startTime = fl::millis();  // Reset timeout
            } else if (c >= '0' && c <= '9') {
                if (inFraction) {
                    fracPart = fracPart * 10 + (c - '0');
                    fracDigits++;
                } else {
                    intPart = intPart * 10 + (c - '0');
                }
                read();  // Consume the digit
                foundDigit = true;
                startTime = fl::millis();  // Reset timeout
            } else {
                break;  // Non-digit, stop parsing
            }
        }
    }
    if (!foundDigit) {
        return 0.0f;
    }
    // Calculate float value
    float value = static_cast<float>(intPart);
    if (fracDigits > 0) {
        float divisor = 1.0f;
        for (int i = 0; i < fracDigits; i++) {
            divisor *= 10.0f;
        }
        value += static_cast<float>(fracPart) / divisor;
    }
    return negative ? -value : value;
}
References available(), fl::millis(), mTimeoutMs, peek(), read(), and fl::type_rank< T >::value.