FastLED: fl::detail::BilateralFilterImpl::recompute
recompute()
template<typename T, fl::size N = 0> T fl::detail::BilateralFilterImpl< T, N >::recompute (T reference) inline private
Definition at line 43 of file bilateral_filter_impl.h.
{
        fl::size n = mBuf.size();
        T two_sigma_sq = T(2.0f) * mSigmaRange * mSigmaRange;
        if (two_sigma_sq == T(0)) {
            mLastValue = reference;
            return mLastValue;
        }
        T weighted_sum = T(0);
        T weight_total = T(0);
        for (fl::size i = 0; i < n; ++i) {
            T diff = mBuf[i] - reference;
            T range_weight = fl::exp(-(diff * diff) / two_sigma_sq);
            weighted_sum = weighted_sum + mBuf[i] * range_weight;
            weight_total = weight_total + range_weight;
        }
        if (!(weight_total == T(0))) {
            mLastValue = weighted_sum / weight_total;
        } else {
            mLastValue = reference;
        }
        return mLastValue;
    }
References fl::exp(), mBuf, mLastValue, and mSigmaRange.
Referenced by update(), and update().