FastLED: fmap
fmap()
float fmap (float x, float in_min, float in_max, float out_min, float out_max)
Definition at line 31 of file ripple.h.
{
  return (x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
}
References x.
Referenced by Ripple::advance(), loop(), net_init(), and Ripple::renderLed().