FastLED: fl::audio::Reactive::applyScaling
applyScaling()
void fl::audio::Reactive::applyScaling () private
Definition at line 420 of file audio_reactive.cpp.hpp.
{
    // Apply scaling mode to frequency bins
    for (int i = 0; i < 16; ++i) {
        float value = mCurrentData.frequencyBins[i];
        switch (mConfig.scalingMode) {
            case 1: // Logarithmic scaling
                if (value > 1.0f) {
                    value = logf(value) * 20.0f; // Scale factor
                } else {
                    value = 0.0f;
                }
                break;
            case 2: // Linear scaling (no change)
                // value remains as-is
                break;
            case 3: // Square root scaling
                if (value > 0.0f) {
                    value = sqrtf(value) * 8.0f; // Scale factor
                } else {
                    value = 0.0f;
                }
                break;
            case 0: // No scaling
            default:
                // value remains as-is
                break;
        }
        mCurrentData.frequencyBins[i] = value;
    }
}
References fl::logf(), mConfig, mCurrentData, fl::sqrtf(), and fl::type_rank< T >::value.
Referenced by processSample().