FastLED: fl::audio::Reactive::begin
begin()
void fl::audio::Reactive::begin (const ReactiveConfig & config = ReactiveConfig{})
Definition at line 40 of file audio_reactive.cpp.hpp.
{
    setConfig(config);
    // Reset state
    mCurrentData = Data{};
    mSmoothedData = Data{};
    mLastBeatTime = 0;
    mPreviousVolume = 0.0f;
    // Configure signal conditioning components
    SignalConditionerConfig scConfig;
    scConfig.enableDCRemoval = config.enableSignalConditioning;
    scConfig.enableSpikeFilter = config.enableSignalConditioning;
    scConfig.enableNoiseGate = config.noiseGate && config.enableSignalConditioning;
    mSignalConditioner.configure(scConfig);
    mSignalConditioner.reset();
    NoiseFloorTrackerConfig nfConfig;
    nfConfig.enabled = config.enableNoiseFloorTracking;
    mNoiseFloorTracker.configure(nfConfig);
    mNoiseFloorTracker.reset();
    // Configure frequency bin mapper (obligatory - fixes hardcoded sample rate)
    FrequencyBinMapperConfig fbmConfig;
    fbmConfig.mode = FrequencyBinMode::Bins16;
    fbmConfig.sampleRate = config.sampleRate;
    fbmConfig.useLogSpacing = config.enableLogBinSpacing;
    fbmConfig.minFrequency = 20.0f;
    fbmConfig.maxFrequency = static_cast<float>(config.sampleRate) / 2.0f;  // Nyquist
    // fftBinCount will be set when we know the fft::FFT size (after first processSample)
    fbmConfig.fftBinCount = 256;  // Default, overridden when actual fft::FFT size known
    mFrequencyBinMapper.configure(fbmConfig);
    // Compute pink noise compensation gains from log-spaced CQ bin centers.
    // CQ bins are log-spaced from fmin to fmax (default: 90-14080 Hz),
    // matching Bins::binToFreq().
    {
        const float fmin = fft::Args::DefaultMinFrequency();
        const float fmax = fft::Args::DefaultMaxFrequency();
        const float m = fl::logf(fmax / fmin);
        float binCenters[16];
        for (int i = 0; i < 16; ++i) {
            binCenters[i] = fmin * fl::expf(m * static_cast<float>(i) / 15.0f);
        }
        computePinkNoiseGains(binCenters, 16, mPinkNoiseGains);
        mPinkNoiseComputed = true;
    }
    // Reset enhanced beat detection components
    if (mSpectralFluxDetector) {
        mSpectralFluxDetector->reset();
        mSpectralFluxDetector->setThreshold(config.spectralFluxThreshold);
    }
    // Configure musical beat detection (Phase 3 middleware - lazy creation)
    if (config.enableMusicalBeatDetection) {
        if (!mMusicalBeatDetector) {
            mMusicalBeatDetector = fl::make_unique<detector::MusicalBeat>();
        }
        detector::MusicalBeatDetectorConfig mbdConfig;
        mbdConfig.minBPM = config.musicalBeatMinBPM;
        mbdConfig.maxBPM = config.musicalBeatMaxBPM;
        mbdConfig.minBeatConfidence = config.musicalBeatConfidence;
        mbdConfig.sampleRate = config.sampleRate;
        mbdConfig.samplesPerFrame = 512;  // Typical fft::FFT frame size
        mMusicalBeatDetector->configure(mbdConfig);
        mMusicalBeatDetector->reset();
    } else {
        mMusicalBeatDetector.reset();
    }
    if (config.enableMultiBandBeats) {
        if (!mMultiBandBeatDetector) {
            mMultiBandBeatDetector = fl::make_unique<detector::MultiBandBeat>();
        }
        detector::MultiBandBeatDetectorConfig mbbdConfig;
        mbbdConfig.bassThreshold = config.bassThreshold;
        mbbdConfig.midThreshold = config.midThreshold;
        mbbdConfig.trebleThreshold = config.trebleThreshold;
        mMultiBandBeatDetector->configure(mbbdConfig);
        mMultiBandBeatDetector->reset();
    } else {
        mMultiBandBeatDetector.reset();
    }
    // Configure spectral equalizer (optional - lazy creation)
    if (config.enableSpectralEqualizer) {
        if (!mSpectralEqualizer) {
            mSpectralEqualizer = fl::make_unique<SpectralEqualizer>();
        }
        SpectralEqualizerConfig seConfig;
        seConfig.curve = EqualizationCurve::AWeighting;
        seConfig.numBands = 16;
        mSpectralEqualizer->configure(seConfig);
    } else {
        mSpectralEqualizer.reset();
    }
    // Reset previous magnitudes
    for (fl::size i = 0; i < mPreviousMagnitudes.size(); ++i) {
        mPreviousMagnitudes[i] = 0.0f;
    }
    // Reset silence envelopes for spectral metrics.
    mDominantFrequencyEnvelope.reset(0.0f);
    mMagnitudeEnvelope.reset(0.0f);
    mSpectralFluxEnvelope.reset(0.0f);
    // Update Context sample rate
    mContext->setSampleRate(config.sampleRate);
    // Ensure internal Processor exists and is configured.
    // Eager creation so processSample() can always source volume from it.
    ensureAudioProcessor();
    mAudioProcessor->setSampleRate(config.sampleRate);
    mAudioProcessor->reset();
    // Force EnergyAnalyzer detector registration so updateFromContext() updates it
    mAudioProcessor->getEnergy();
}
References Reactive(), fl::audio::AWeighting, fl::audio::detector::MultiBandBeatDetectorConfig::bassThreshold, begin(), fl::audio::Bins16, fl::audio::computePinkNoiseGains(), fl::audio::SpectralEqualizerConfig::curve, fl::audio::fft::Args::DefaultMaxFrequency(), fl::audio::fft::Args::DefaultMinFrequency(), fl::audio::NoiseFloorTrackerConfig::enabled, fl::audio::SignalConditionerConfig::enableDCRemoval, fl::audio::SignalConditionerConfig::enableNoiseGate, fl::audio::SignalConditionerConfig::enableSpikeFilter, ensureAudioProcessor(), fl::expf(), fl::audio::FrequencyBinMapperConfig::fftBinCount, fl::logf(), fl::make_unique(), mAudioProcessor, fl::audio::detector::MusicalBeatDetectorConfig::maxBPM, fl::audio::FrequencyBinMapperConfig::maxFrequency, mContext, mCurrentData, mDominantFrequencyEnvelope, mFrequencyBinMapper, fl::audio::detector::MultiBandBeatDetectorConfig::midThreshold, fl::audio::detector::MusicalBeatDetectorConfig::minBeatConfidence, fl::audio::detector::MusicalBeatDetectorConfig::minBPM, fl::audio::FrequencyBinMapperConfig::minFrequency, mLastBeatTime, mMagnitudeEnvelope, mMultiBandBeatDetector, mMusicalBeatDetector, mNoiseFloorTracker, fl::audio::FrequencyBinMapperConfig::mode, mPinkNoiseComputed, mPinkNoiseGains, mPreviousMagnitudes, mPreviousVolume, mSignalConditioner, mSmoothedData, mSpectralEqualizer, mSpectralFluxDetector, mSpectralFluxEnvelope, fl::audio::SpectralEqualizerConfig::numBands, fl::audio::detector::MusicalBeatDetectorConfig::sampleRate, fl::audio::FrequencyBinMapperConfig::sampleRate, fl::audio::detector::MusicalBeatDetectorConfig::samplesPerFrame, setConfig(), fl::audio::detector::MultiBandBeatDetectorConfig::trebleThreshold, and fl::audio::FrequencyBinMapperConfig::useLogSpacing.
Referenced by ~Reactive(), and begin().