FastLED: fl::audio::Reactive::mapFFTBinsToFrequencyChannels
mapFFTBinsToFrequencyChannels()
void fl::audio::Reactive::mapFFTBinsToFrequencyChannels () private
Definition at line 293 of file audio_reactive.cpp.hpp.
{
    // Sample::fft() returns CQ-kernel bins that are already
    // frequency-mapped (linearly spaced from fmin to fmax). Copy them
    // directly instead of re-mapping through FrequencyBinMapper, which
    // incorrectly treats CQ bins as raw DFT bins.
    fl::span<const float> rawBins = mFFTBins.raw();
    if (rawBins.empty()) {
        for (int i = 0; i < 16; ++i) {
            mCurrentData.frequencyBins[i] = 0.0f;
        }
        return;
    }
    // Copy CQ bins directly to frequency bins (already frequency-mapped)
    for (int i = 0; i < 16; ++i) {
        if (i < static_cast<int>(rawBins.size())) {
            mCurrentData.frequencyBins[i] = rawBins[i];
        } else {
            mCurrentData.frequencyBins[i] = 0.0f;
        }
    }
    // Note: Pink noise compensation is applied later in processSample(),
    // AFTER band energies are calculated from the raw CQ bins.
    // This ensures bassEnergy/midEnergy/trebleEnergy reflect actual
    // spectral content, not display-oriented compensation.
    // Find dominant frequency bin
    float maxMagnitude = 0.0f;
    int maxBin = 0;
    for (int i = 0; i < 16; ++i) {
        if (mCurrentData.frequencyBins[i] > maxMagnitude) {
            maxMagnitude = mCurrentData.frequencyBins[i];
            maxBin = i;
        }
    }
    // CQ bins are log-spaced — use the same formula as Bins::binToFreq().
    mCurrentData.dominantFrequency = mFFTBins.binToFreq(maxBin);
    mCurrentData.magnitude = maxMagnitude;
}
References fl::span< T, Extent >::empty(), mCurrentData, mFFTBins, and fl::span< T, Extent >::size().
Referenced by processFFT().