FastLED: fl::audio::Reactive::updateVolumeAndPeak
updateVolumeAndPeak()
void fl::audio::Reactive::updateVolumeAndPeak (const Sample & sample) private
Definition at line 335 of file audio_reactive.cpp.hpp.
{
    // Get PCM data from Sample
    const auto& pcmData = sample.pcm();
    if (pcmData.empty()) {
        mCurrentData.volume = 0.0f;
        mCurrentData.volumeRaw = 0.0f;
        mCurrentData.peak = 0.0f;
        return;
    }
    // Raw volume: simple bounded normalization (no adaptive smoothing)
    // 23170 ≈ max RMS of a full-scale 16-bit sine wave (32767 / √2).
    // Clamp so clipped/square-wave input stays at 1.0.
    float rms = sample.rms();
    float raw = rms / 23170.0f;
    mCurrentData.volumeRaw = (raw > 1.0f) ? 1.0f : raw;
    // Normalized volume from Processor's EnergyAnalyzer (adaptive 0.0-1.0).
    // mAudioProcessor is guaranteed non-null: ensureAudioProcessor() is called
    // in processSample() immediately before this method.
    FL_ASSERT(mAudioProcessor, "mAudioProcessor is null — was begin() called before processSample()?");
    mCurrentData.volume = mAudioProcessor->getEnergy();
    // Peak: simple bounded normalization
    float maxSample = 0.0f;
    for (fl::i16 pcmSample : pcmData) {
        float absSample = (pcmSample < 0) ? -static_cast<float>(pcmSample) : static_cast<float>(pcmSample);
        maxSample = (maxSample > absSample) ? maxSample : absSample;
    }
    mCurrentData.peak = maxSample / 32768.0f;
}
References FL_ASSERT, mAudioProcessor, mCurrentData, rms(), and fl::sample().
Referenced by processSample().