FastLED: fl::audio::Reactive::computeRMS
computeRMS()
float fl::audio::Reactive::computeRMS (const fl::vector< fl::i16 > & samples) private
Definition at line 752 of file audio_reactive.cpp.hpp.
{
    if (samples.empty()) return 0.0f;
    float sumSquares = 0.0f;
    for (const auto& sample : samples) {
        float f = static_cast<float>(sample);
        sumSquares += f * f;
    }
    return sqrtf(sumSquares / samples.size());
}
References fl::vector_basic::empty(), fl::sample(), fl::vector_basic::size(), and fl::sqrtf().