FastLED: fl::audio::Reactive::Reactive
Reactive()
fl::audio::Reactive::Reactive ()
Definition at line 16 of file audio_reactive.cpp.hpp.
    : mConfig{}, mContext(fl::make_shared<Context>(Sample())), mFFTBins(16)  // Initialize with 16 frequency bins
{
    // Initialize enhanced beat detection components
    mSpectralFluxDetector = fl::make_unique<SpectralFluxDetector>();
    mPerceptualWeighting = fl::make_unique<PerceptualWeighting>();
    // Initialize previous magnitudes array to zero
    for (fl::size i = 0; i < mPreviousMagnitudes.size(); ++i) {
        mPreviousMagnitudes[i] = 0.0f;
    }
    // Configure spectral silence envelopes — tau=0.2s chosen because FFT noise
    // floor is brittle; these metrics should snap to zero quickly in silence.
    SilenceEnvelope::Config envCfg;
    envCfg.decayTauSeconds = 0.2f;
    envCfg.targetValue = 0.0f;
    mDominantFrequencyEnvelope.configure(envCfg);
    mMagnitudeEnvelope.configure(envCfg);
    mSpectralFluxEnvelope.configure(envCfg);
}
References fl::audio::SilenceEnvelope::Config::decayTauSeconds, fl::make_shared(), fl::make_unique(), mConfig, mContext, mDominantFrequencyEnvelope, mFFTBins, mMagnitudeEnvelope, mPerceptualWeighting, mPreviousMagnitudes, mSpectralFluxDetector, mSpectralFluxEnvelope, and fl::audio::SilenceEnvelope::Config::targetValue.
Referenced by begin().