FastLED: executeToggles
executeToggles()
void executeToggles (fl::RxChannel & rx, fl::span< const PinToggle > toggles, int pin_tx, uint32_t wait_ms)
Execute pin toggles and initialize RX channel for capture.
Reads the current config from the RX channel, sets the TX pin to the initial state, begins capture, and executes the sequence of pin toggles.
Parameters
rx RX channel to initialize and use for capture
toggles Sequence of pin state changes to execute
pin_tx TX pin number to toggle
wait_ms Unused parameter (kept for API compatibility)
Examples
RX.ino.
Definition at line 36 of file test.cpp.
{
    const fl::RxChannelConfig& config = rx.config();
    // Set pin to initial state before begin()
    pinMode(pin_tx, OUTPUT);
    digitalWrite(pin_tx, config.start_low ? LOW : HIGH);
    fl::delayMicroseconds(100);  // Allow pin to settle
    // Initialize RX channel
    if (!rx.begin(config)) {
        FL_ERROR("Failed to initialize RX channel");
        return;
    }
    // Execute pin toggles
    for (size_t i = 0; i < toggles.size(); i++) {
        digitalWrite(pin_tx, toggles[i].is_high ? HIGH : LOW);
        fl::delayMicroseconds(toggles[i].delay_us);
    }
}
References fl::RxChannel::begin(), fl::RxChannel::config(), fl::delayMicroseconds(), FL_ERROR, fl::span< T, Extent >::size(), and fl::RxChannelConfig::start_low.
Referenced by loop().