FastLED: fl::FontImpl::renderGlyph
renderGlyph() [2/2]
GlyphBitmap fl::FontImpl::renderGlyph (i32 codepoint, float scale, i32 oversampleX, i32 oversampleY) const inline override virtual
Implements fl::Font.
Definition at line 88 of file truetype.cpp.hpp.
{
        GlyphBitmap result;
        if (!mValid) return result;
        if (oversampleX <= 1 && oversampleY <= 1) {
            // Simple rendering without oversampling
            unsigned char* bitmap = third_party::truetype::stbtt_GetCodepointBitmap(
                &mFontInfo, scale, scale, codepoint,
                &result.width, &result.height,
                &result.xOffset, &result.yOffset
            );
            if (bitmap && result.width > 0 && result.height > 0) {
                size_t size = static_cast<size_t>(result.width) * static_cast<size_t>(result.height);
                result.data.resize(size);
                for (size_t i = 0; i < size; ++i) {
                    result.data[i] = bitmap[i];
                }
                third_party::truetype::stbtt_FreeBitmap(bitmap, nullptr);
            }
        } else {
            // Rendering with oversampling for smoother antialiasing
            unsigned char* bitmap = third_party::truetype::stbtt_GetCodepointBitmapSubpixel(
                &mFontInfo,
                scale * static_cast<float>(oversampleX),
                scale * static_cast<float>(oversampleY),
                0.0f, 0.0f,
                codepoint,
                &result.width, &result.height,
                &result.xOffset, &result.yOffset
            );
            if (bitmap && result.width > 0 && result.height > 0) {
                // Downsample to final size
                i32 finalWidth = (result.width + oversampleX - 1) / oversampleX;
                i32 finalHeight = (result.height + oversampleY - 1) / oversampleY;
                result.data.resize(
                    static_cast<size_t>(finalWidth) * static_cast<size_t>(finalHeight)
                );
                for (i32 y = 0; y < finalHeight; ++y) {
                    for (i32 x = 0; x < finalWidth; ++x) {
                        i32 sum = 0;
                        i32 count = 0;
                        for (i32 oy = 0; oy < oversampleY; ++oy) {
                            i32 srcY = y * oversampleY + oy;
                            if (srcY >= result.height) break;
                            for (i32 ox = 0; ox < oversampleX; ++ox) {
                                i32 srcX = x * oversampleX + ox;
                                if (srcX >= result.width) break;
                                sum += bitmap[srcY * result.width + srcX];
                                ++count;
                            }
                        }
                        result.data[y * finalWidth + x] = static_cast<u8>(
                            count > 0 ? sum / count : 0
                        );
                    }
                }
                result.width = finalWidth;
                result.height = finalHeight;
                result.xOffset = result.xOffset / oversampleX;
                result.yOffset = result.yOffset / oversampleY;
                third_party::truetype::stbtt_FreeBitmap(bitmap, nullptr);
            }
        }
        return result;
    }
References mFontInfo, mValid, scale, fl::third_party::truetype::stbtt_FreeBitmap(), fl::third_party::truetype::stbtt_GetCodepointBitmap(), fl::third_party::truetype::stbtt_GetCodepointBitmapSubpixel(), fl::x, and fl::y.