FastLED: fl::detail::MethodBuilder::MethodBuilder
MethodBuilder()
template<typename Sig> fl::detail::MethodBuilder< Sig >::MethodBuilder (Rpc * factory, const char * name, RpcFn< Sig > fn) inline
Definition at line 22 of file rpc_method_builder.h.
        : mFactory(factory), mName(name), mFn(fn) {}
References factory(), fn(), mFactory, mFn, mName, and name().
Referenced by description(), params(), and tags().