FastLED: fl::FontImpl::FontImpl
FontImpl()
fl::FontImpl::FontImpl (fl::span< const u8 > fontData, i32 fontIndex = 0) inline
Definition at line 19 of file truetype.cpp.hpp.
        : mFontData(fontData.begin(), fontData.end()) {
        mValid = third_party::truetype::stbtt_InitFont(
            &mFontInfo,
            mFontData.data(),
            third_party::truetype::stbtt_GetFontOffsetForIndex(mFontData.data(), fontIndex)
        ) != 0;
    }
References fl::begin(), fl::end(), mFontData, mFontInfo, mValid, fl::third_party::truetype::stbtt_GetFontOffsetForIndex(), and fl::third_party::truetype::stbtt_InitFont().