FastLED: ColorPaletteManager::mapColor
mapColor()
CRGB ColorPaletteManager::mapColor (float hue_norm, float intensity, float special_param = 0.0f) inline
Definition at line 184 of file FxNoiseRing.h.
{
        switch(current_palette) {
            case 0: return mapSunsetBoulevard(hue_norm, intensity, special_param);
            case 1: return mapOceanBreeze(hue_norm, intensity, special_param);
            case 2: return mapNeonNights(hue_norm, intensity, special_param);
            case 3: return mapForestWhisper(hue_norm, intensity, special_param);
            case 4: return mapGalaxyExpress(hue_norm, intensity, special_param);
            default: return mapSunsetBoulevard(hue_norm, intensity, special_param);
        }
    }
References current_palette, mapForestWhisper(), mapGalaxyExpress(), mapNeonNights(), mapOceanBreeze(), and mapSunsetBoulevard().