FastLED: ColorFromPaletteExtended
ColorFromPaletteExtended() [1/3]
CRGB ColorFromPaletteExtended (const CRGBPalette16 & pal, uint16_t index, uint8_t brightness, TBlendType blendType)
Same as ColorFromPalette, but with uint16_t index to give greater precision.
Author
https://github.com/generalelectrix
See also
https://github.com/FastLED/FastLED/pull/202
https://wokwi.com/projects/285170662915441160
https://wokwi.com/projects/407831886158110721
Definition at line 733 of file colorutils.cpp.
{
  // Extract the four most significant bits of the index as a palette index.
  uint8_t index_4bit = index >> 12;
  // Calculate the 8-bit offset from the palette index.
  uint8_t offset = (uint8_t)(index >> 4);
  // Get the palette entry from the 4-bit index
  const CRGB* entry = &(pal[0]) + index_4bit;
  uint8_t red1   = entry->red;
  uint8_t green1 = entry->green;
  uint8_t blue1  = entry->blue;
  uint8_t blend = offset && (blendType != NOBLEND);
  if (blend) {
    if (index_4bit == 15) {
      entry = &(pal[0]);
    } else {
      entry++;
    }
    // Calculate the scaling factor and scaled values for the lower palette value.
    uint8_t f1 = 255 - offset;
    red1   = scale8_LEAVING_R1_DIRTY(red1,   f1);
    green1 = scale8_LEAVING_R1_DIRTY(green1, f1);
    blue1  = scale8_LEAVING_R1_DIRTY(blue1,  f1);
    // Calculate the scaled values for the neighbouring palette value.
    uint8_t red2   = entry->red;
    uint8_t green2 = entry->green;
    uint8_t blue2  = entry->blue;
    red2   = scale8_LEAVING_R1_DIRTY(red2,   offset);
    green2 = scale8_LEAVING_R1_DIRTY(green2, offset);
    blue2  = scale8_LEAVING_R1_DIRTY(blue2,  offset);
    cleanup_R1();
    // These sums can't overflow, so no qadd8 needed.
    red1   += red2;
    green1 += green2;
    blue1  += blue2;
  }
  if (brightness != 255) {
    // nscale8x3_video(red1, green1, blue1, brightness);
    nscale8x3(red1, green1, blue1, brightness);
  }
  return CRGB(red1, green1, blue1);
}
References blend(), brightness, cleanup_R1(), NOBLEND, nscale8x3(), and scale8_LEAVING_R1_DIRTY().