FastLED: fl::third_party::plm_rewind
plm_rewind()
void fl::third_party::plm_rewind (plm_t * self)
Definition at line 438 of file pl_mpeg.hpp.
{
    if (self->video_decoder) {
        plm_video_rewind(self->video_decoder);
    }
    if (self->audio_decoder) {
        plm_audio_rewind(self->audio_decoder);
    }
    plm_demux_rewind(self->demux);
    self->time = 0;
    self->has_ended = FALSE;
}
References FALSE, FL_NOEXCEPT, plm_audio_rewind(), plm_demux_rewind(), and plm_video_rewind().
Referenced by plm_handle_end().