FastLED: fl::third_party::plm_video_decode_sequence_header
plm_video_decode_sequence_header()
int fl::third_party::plm_video_decode_sequence_header (plm_video_t * self)
Definition at line 2282 of file pl_mpeg.hpp.
{
    int max_header_size = 64 + 2 * 64 * 8; // 64 bit header + 2x 64 byte matrix
    if (!plm_buffer_has(self->buffer, max_header_size)) {
        return FALSE;
    }
    self->width = plm_buffer_read(self->buffer, 12);
    self->height = plm_buffer_read(self->buffer, 12);
    if (self->width <= 0 || self->height <= 0) {
        return FALSE;
    }
    // Get pixel aspect ratio
    int pixel_aspect_ratio_code;
    pixel_aspect_ratio_code = plm_buffer_read(self->buffer, 4);
    pixel_aspect_ratio_code -= 1;
    if (pixel_aspect_ratio_code < 0) {
        pixel_aspect_ratio_code = 0;
    }
    int par_last = (sizeof(PLM_VIDEO_PIXEL_ASPECT_RATIO) /
            sizeof(PLM_VIDEO_PIXEL_ASPECT_RATIO[0]) - 1);
    if (pixel_aspect_ratio_code > par_last) {
        pixel_aspect_ratio_code = par_last;
    }
    self->pixel_aspect_ratio =
        PLM_VIDEO_PIXEL_ASPECT_RATIO[pixel_aspect_ratio_code];
    // Get frame rate
    self->framerate = PLM_VIDEO_PICTURE_RATE[plm_buffer_read(self->buffer, 4)];
    // Skip bit_rate, marker, buffer_size and constrained bit
    plm_buffer_skip(self->buffer, 18 + 1 + 10 + 1);
    // Load custom intra quant matrix?
    if (plm_buffer_read(self->buffer, 1)) {
        for (int i = 0; i < 64; i++) {
            int idx = PLM_VIDEO_ZIG_ZAG[i];
            self->intra_quant_matrix[idx] = plm_buffer_read(self->buffer, 8);
        }
    }
    else {
        fl::memcopy(self->intra_quant_matrix, PLM_VIDEO_INTRA_QUANT_MATRIX, 64);
    }
    // Load custom non intra quant matrix?
    if (plm_buffer_read(self->buffer, 1)) {
        for (int i = 0; i < 64; i++) {
            int idx = PLM_VIDEO_ZIG_ZAG[i];
            self->non_intra_quant_matrix[idx] = plm_buffer_read(self->buffer, 8);
        }
    }
    else {
        fl::memcopy(self->non_intra_quant_matrix, PLM_VIDEO_NON_INTRA_QUANT_MATRIX, 64);
    }
    self->mb_width = (self->width + 15) >> 4;
    self->mb_height = (self->height + 15) >> 4;
    self->mb_size = self->mb_width * self->mb_height;
    self->luma_width = self->mb_width << 4;
    self->luma_height = self->mb_height << 4;
    self->chroma_width = self->mb_width << 3;
    self->chroma_height = self->mb_height << 3;
    // Allocate one big chunk of data for all 3 frames = 9 planes
    size_t luma_plane_size = self->luma_width * self->luma_height;
    size_t chroma_plane_size = self->chroma_width * self->chroma_height;
    size_t frame_data_size = (luma_plane_size + 2 * chroma_plane_size);
    self->frames_data = (uint8_t*)PLM_MALLOC(frame_data_size * 3);
    plm_video_init_frame(self, &self->frame_current, self->frames_data + frame_data_size * 0);
    plm_video_init_frame(self, &self->frame_forward, self->frames_data + frame_data_size * 1);
    plm_video_init_frame(self, &self->frame_backward, self->frames_data + frame_data_size * 2);
    self->has_sequence_header = TRUE;
    return TRUE;
}
References FALSE, FL_NOEXCEPT, fl::memcopy(), plm_buffer_has(), plm_buffer_read(), plm_buffer_skip(), PLM_MALLOC, plm_video_init_frame(), PLM_VIDEO_INTRA_QUANT_MATRIX, PLM_VIDEO_NON_INTRA_QUANT_MATRIX, PLM_VIDEO_PICTURE_RATE, PLM_VIDEO_PIXEL_ASPECT_RATIO, PLM_VIDEO_ZIG_ZAG, and TRUE.
Referenced by plm_video_create_with_buffer(), and plm_video_has_header().