FastLED: fl::third_party::plm_create_with_buffer
plm_create_with_buffer()
plm_t * fl::third_party::plm_create_with_buffer (plm_buffer_t * buffer, int destroy_when_done)
Definition at line 249 of file pl_mpeg.hpp.
{
    plm_t *self = (plm_t *)PLM_MALLOC(sizeof(plm_t));
    fl::memset(self, 0, sizeof(plm_t));
    self->demux = plm_demux_create(buffer, destroy_when_done);
    self->video_enabled = TRUE;
    self->audio_enabled = TRUE;
    plm_init_decoders(self);
    return self;
}
References fl::third_party::plm_t::audio_enabled, fl::third_party::plm_t::demux, FL_NOEXCEPT, fl::memset(), plm_demux_create(), plm_init_decoders(), PLM_MALLOC, TRUE, and fl::third_party::plm_t::video_enabled.
Referenced by plm_create_with_memory().