FastLED: fl::third_party::plm_demux_decode
plm_demux_decode()
plm_packet_t * fl::third_party::plm_demux_decode (plm_demux_t * self)
Definition at line 1517 of file pl_mpeg.hpp.
{
    if (!plm_demux_has_headers(self)) {
        return NULL;
    }
    if (self->current_packet.length) {
        size_t bits_till_next_packet = self->current_packet.length << 3;
        if (!plm_buffer_has(self->buffer, bits_till_next_packet)) {
            return NULL;
        }
        plm_buffer_skip(self->buffer, bits_till_next_packet);
        self->current_packet.length = 0;
    }
    // Pending packet waiting for data?
    if (self->next_packet.length) {
        return plm_demux_get_packet(self);
    }
    // Pending packet waiting for header?
    if (self->start_code != -1) {
        return plm_demux_decode_packet(self, self->start_code);
    }
    do {
        self->start_code = plm_buffer_next_start_code(self->buffer);
        if (
            self->start_code == PLM_DEMUX_PACKET_VIDEO_1 ||
            self->start_code == PLM_DEMUX_PACKET_PRIVATE || (
                self->start_code >= PLM_DEMUX_PACKET_AUDIO_1 &&
                self->start_code <= PLM_DEMUX_PACKET_AUDIO_4
            )
        ) {
            return plm_demux_decode_packet(self, self->start_code);
        }
    } while (self->start_code != -1);
    return NULL;
}
References FL_NOEXCEPT, NULL, plm_buffer_has(), plm_buffer_next_start_code(), plm_buffer_skip(), plm_demux_decode_packet(), plm_demux_get_packet(), plm_demux_has_headers(), PLM_DEMUX_PACKET_AUDIO_1, PLM_DEMUX_PACKET_AUDIO_4, PLM_DEMUX_PACKET_PRIVATE, and PLM_DEMUX_PACKET_VIDEO_1.
Referenced by plm_demux_get_duration(), plm_demux_get_start_time(), plm_read_packets(), and plm_seek().