FastLED: fl::third_party::lzw_decode
lzw_decode()
lzw_result fl::third_party::lzw_decode (struct lzw_ctx * ctx, const fl::u8 **const output_data, fl::u32 * output_written)
Read input codes until end of LZW context owned output buffer.
Ensure anything in output is used before calling this, as anything there before this call will be trampled.
Parameters
[in] ctx LZW reading context, updated.
[out] output_data Returns pointer to array of output values.
[out] output_written Returns the number of values written to data.
Returns
LZW_OK on success, or appropriate error code otherwise.
Definition at line 500 of file lzw.cpp.hpp.
{
    const fl::u32 output_length = sizeof(ctx->stack_base);
    *output_written = 0;
    *output_data = ctx->stack_base;
    if (ctx->output_left != 0) {
        *output_written += lzw__write_fn(ctx,
                ctx->stack_base, output_length, *output_written,
                ctx->output_code, ctx->output_left);
    }
    while (*output_written != output_length) {
        lzw_result res = lzw__decode(ctx, lzw__write_fn,
                ctx->stack_base, output_length, output_written);
        if (res != LZW_OK) {
            return res;
        }
    }
    return LZW_OK;
}
References FL_NOEXCEPT, lzw__decode(), lzw__write_fn(), LZW_OK, fl::third_party::lzw_ctx::output_code, fl::third_party::lzw_ctx::output_left, and fl::third_party::lzw_ctx::stack_base.
Referenced by nsgif__decode_complex().