FastLED: fl::third_party::nsgif__decode_complex
nsgif__decode_complex()
static nsgif_error fl::third_party::nsgif__decode_complex (struct nsgif * gif, fl::u32 width, fl::u32 height, fl::u32 offset_x, fl::u32 offset_y, fl::u32 interlace, const fl::u8 * data, fl::u32 transparency_index, fl::u32 * frame_data, fl::u32 * colour_table) static
Definition at line 446 of file gif.cpp.hpp.
{
    lzw_result res;
    nsgif_error ret = NSGIF_OK;
    fl::u32 clip_x = gif__clip(offset_x, width, gif->info.width);
    fl::u32 clip_y = gif__clip(offset_y, height, gif->info.height);
    const fl::u8 *uncompressed;
    fl::u32 available = 0;
    fl::u8 step = 24;
    fl::u32 skip = 0;
    fl::u32 y = 0;
    if (offset_x >= gif->info.width ||
        offset_y >= gif->info.height) {
        return NSGIF_OK;
    }
    width -= clip_x;
    height -= clip_y;
    if (width == 0 || height == 0) {
        return NSGIF_OK;
    }
    /* Initialise the LZW decoding */
    res = lzw_decode_init(static_cast<struct lzw_ctx*>(gif->lzw_ctx), data[0],
            gif->buf, gif->buf_len,
            data + 1 - gif->buf);
    if (res != LZW_OK) {
        return nsgif__error_from_lzw(res);
    }
    do {
        fl::u32 x;
        fl::u32 *frame_scanline;
        frame_scanline = frame_data + offset_x +
                (y + offset_y) * gif->rowspan;
        x = width;
        while (x > 0) {
            unsigned row_available;
            while (available == 0) {
                if (res != LZW_OK) {
                    /* Unexpected end of frame, try to recover */
                    if (res == LZW_OK_EOD ||
                        res == LZW_EOI_CODE) {
                        ret = NSGIF_OK;
                    } else {
                        ret = nsgif__error_from_lzw(res);
                    }
                    return ret;
                }
                res = lzw_decode(static_cast<struct lzw_ctx*>(gif->lzw_ctx),
                        &uncompressed, &available);
                if (available == 0) {
                    return NSGIF_OK;
                }
                gif__jump_data(&skip, &available, &uncompressed);
            }
            row_available = x < available ? x : available;
            x -= row_available;
            available -= row_available;
            if (transparency_index > 0xFF) {
                while (row_available-- > 0) {
                    *frame_scanline++ =
                        colour_table[*uncompressed++];
                }
            } else {
                while (row_available-- > 0) {
                    fl::u32 colour;
                    colour = *uncompressed++;
                    if (colour != transparency_index) {
                        *frame_scanline =
                            colour_table[colour];
                    }
                    frame_scanline++;
                }
            }
        }
        skip = clip_x;
        gif__jump_data(&skip, &available, &uncompressed);
    } while (nsgif__next_row(interlace, height, &y, &step));
    return ret;
}
References fl::available(), FL_NOEXCEPT, gif__clip(), gif__jump_data(), fl::height, lzw_decode(), lzw_decode_init(), LZW_EOI_CODE, LZW_OK, LZW_OK_EOD, nsgif__error_from_lzw(), nsgif__next_row(), NSGIF_OK, fl::step(), fl::width, fl::x, and fl::y.
Referenced by nsgif__decode().