FastLED: fl::third_party::nsgif__update_bitmap
nsgif__update_bitmap()
static nsgif_error fl::third_party::nsgif__update_bitmap (struct nsgif * gif, struct nsgif_frame * frame, const fl::u8 * data, fl::u32 frame_idx) static
Definition at line 694 of file gif.cpp.hpp.
{
    nsgif_error ret;
    fl::u32 *bitmap;
    gif->decoded_frame = frame_idx;
    bitmap = nsgif__bitmap_get(gif);
    if (bitmap == nullptr) {
        return NSGIF_ERR_OOM;
    }
    /* Handle any bitmap clearing/restoration required before decoding this
     * frame. */
    if (frame_idx == 0 || gif->decoded_frame == NSGIF_FRAME_INVALID) {
        nsgif__restore_bg(gif, nullptr, bitmap);
    } else {
        struct nsgif_frame *prev = &gif->frames[frame_idx - 1];
        if (prev->info.disposal == NSGIF_DISPOSAL_RESTORE_BG) {
            nsgif__restore_bg(gif, prev, bitmap);
        } else if (prev->info.disposal == NSGIF_DISPOSAL_RESTORE_PREV) {
            ret = nsgif__recover_frame(gif, bitmap);
            if (ret != NSGIF_OK) {
                nsgif__restore_bg(gif, prev, bitmap);
            }
        }
    }
    if (frame->info.disposal == NSGIF_DISPOSAL_RESTORE_PREV) {
        /* Store the previous frame for later restoration */
        nsgif__record_frame(gif, bitmap);
    }
    ret = nsgif__decode(gif, frame, data, bitmap);
    nsgif__bitmap_modified(gif);
    if (!frame->decoded) {
        frame->opaque = nsgif__bitmap_get_opaque(gif);
        frame->decoded = true;
    }
    nsgif__bitmap_set_opaque(gif, frame);
    return ret;
}
References fl::third_party::nsgif_frame_info::disposal, FL_NOEXCEPT, fl::third_party::nsgif_frame::info, nsgif__bitmap_get(), nsgif__bitmap_get_opaque(), nsgif__bitmap_modified(), nsgif__bitmap_set_opaque(), nsgif__decode(), nsgif__record_frame(), nsgif__recover_frame(), nsgif__restore_bg(), NSGIF_DISPOSAL_RESTORE_BG, NSGIF_DISPOSAL_RESTORE_PREV, NSGIF_ERR_OOM, NSGIF_FRAME_INVALID, and NSGIF_OK.
Referenced by nsgif__parse_image_data().