FastLED: fl::third_party::plm_buffer_peek_non_zero
plm_buffer_peek_non_zero()
int fl::third_party::plm_buffer_peek_non_zero (plm_buffer_t * self, int bit_count)
Definition at line 1101 of file pl_mpeg.hpp.
{
    if (!plm_buffer_has(self, bit_count)) {
        return FALSE;
    }
    int val = plm_buffer_read(self, bit_count);
    self->bit_index -= bit_count;
    return val != 0;
}
References FALSE, FL_NOEXCEPT, plm_buffer_has(), and plm_buffer_read().
Referenced by plm_video_decode_slice().