FastLED: fl::third_party::plm_audio_decode_header
plm_audio_decode_header()
int fl::third_party::plm_audio_decode_header (plm_audio_t * self)
Definition at line 3339 of file pl_mpeg.hpp.
{
    if (!plm_buffer_has(self->buffer, 48)) {
        return 0;
    }
    plm_buffer_skip_bytes(self->buffer, 0x00);
    int sync = plm_buffer_read(self->buffer, 11);
    // Attempt to resync if no syncword was found. This sucks balls. The MP2
    // stream contains a syncword just before every frame (11 bits set to 1).
    // However, this syncword is not guaranteed to not occur elsewhere in the
    // stream. So, if we have to resync, we also have to check if the header
    // (samplerate, bitrate) differs from the one we had before. This all
    // may still lead to garbage data being decoded :/
    if (sync != PLM_AUDIO_FRAME_SYNC && !plm_audio_find_frame_sync(self)) {
        return 0;
    }
    self->version = plm_buffer_read(self->buffer, 2);
    self->layer = plm_buffer_read(self->buffer, 2);
    int hasCRC = !plm_buffer_read(self->buffer, 1);
    if (
        self->version != PLM_AUDIO_MPEG_1 ||
        self->layer != PLM_AUDIO_LAYER_II
    ) {
        return 0;
    }
    int bitrate_index = plm_buffer_read(self->buffer, 4) - 1;
    if (bitrate_index > 13) {
        return 0;
    }
    int samplerate_index = plm_buffer_read(self->buffer, 2);
    if (samplerate_index == 3) {
        return 0;
    }
    int padding = plm_buffer_read(self->buffer, 1);
    plm_buffer_skip(self->buffer, 1); // f_private
    int mode = plm_buffer_read(self->buffer, 2);
    // If we already have a header, make sure the samplerate, bitrate and mode
    // are still the same, otherwise we might have missed sync.
    if (
        self->has_header && (
            self->bitrate_index != bitrate_index ||
            self->samplerate_index != samplerate_index ||
            self->mode != mode
        )
    ) {
        return 0;
    }
    self->bitrate_index = bitrate_index;
    self->samplerate_index = samplerate_index;
    self->mode = mode;
    self->has_header = TRUE;
    // Parse the mode_extension, set up the stereo bound
    if (mode == PLM_AUDIO_MODE_JOINT_STEREO) {
        self->bound = (plm_buffer_read(self->buffer, 2) + 1) << 2;
    }
    else {
        plm_buffer_skip(self->buffer, 2);
        self->bound = (mode == PLM_AUDIO_MODE_MONO) ? 0 : 32;
    }
    // Discard the last 4 bits of the header and the CRC value, if present
    plm_buffer_skip(self->buffer, 4); // copyright(1), original(1), emphasis(2)
    if (hasCRC) {
        plm_buffer_skip(self->buffer, 16);
    }
    // Compute frame size, check if we have enough data to decode the whole
    // frame.
    int bitrate = PLM_AUDIO_BIT_RATE[self->bitrate_index];
    int samplerate = PLM_AUDIO_SAMPLE_RATE[self->samplerate_index];
    int frame_size = (144000 * bitrate / samplerate) + padding;
    return frame_size - (hasCRC ? 6 : 4);
}
References FL_NOEXCEPT, PLM_AUDIO_BIT_RATE, plm_audio_find_frame_sync(), PLM_AUDIO_FRAME_SYNC, PLM_AUDIO_LAYER_II, PLM_AUDIO_MODE_JOINT_STEREO, PLM_AUDIO_MODE_MONO, PLM_AUDIO_MPEG_1, PLM_AUDIO_SAMPLE_RATE, plm_buffer_has(), plm_buffer_read(), plm_buffer_skip(), plm_buffer_skip_bytes(), and TRUE.
Referenced by plm_audio_create_with_buffer(), plm_audio_decode(), and plm_audio_has_header().