FastLED: fl::third_party::Subband
Subband()
int fl::third_party::Subband (MP3DecInfo * mp3DecInfo, short * pcmBuf)
Definition at line 65 of file subband.hpp.
{
    int b;
    IMDCTInfo *mi;
    SubbandInfo *sbi;
    /* validate pointers */
    if (!mp3DecInfo || !mp3DecInfo->HuffmanInfoPS || !mp3DecInfo->IMDCTInfoPS || !mp3DecInfo->SubbandInfoPS)
        return -1;
    mi = (IMDCTInfo *)(mp3DecInfo->IMDCTInfoPS);
    sbi = (SubbandInfo*)(mp3DecInfo->SubbandInfoPS);
    if (mp3DecInfo->nChans == 2) {
        /* stereo */
        for (b = 0; b < BLOCK_SIZE; b++) {
            FDCT32(mi->outBuf[0][b], sbi->vbuf + 0*32, sbi->vindex, (b & 0x01), mi->gb[0]);
            FDCT32(mi->outBuf[1][b], sbi->vbuf + 1*32, sbi->vindex, (b & 0x01), mi->gb[1]);
            PolyphaseStereo(pcmBuf, sbi->vbuf + sbi->vindex + VBUF_LENGTH * (b & 0x01), polyCoef);
            sbi->vindex = (sbi->vindex - (b & 0x01)) & 7;
            pcmBuf += (2 * NBANDS);
        }
    } else {
        /* mono */
        for (b = 0; b < BLOCK_SIZE; b++) {
            FDCT32(mi->outBuf[0][b], sbi->vbuf + 0*32, sbi->vindex, (b & 0x01), mi->gb[0]);
            PolyphaseMono(pcmBuf, sbi->vbuf + sbi->vindex + VBUF_LENGTH * (b & 0x01), polyCoef);
            sbi->vindex = (sbi->vindex - (b & 0x01)) & 7;
            pcmBuf += NBANDS;
        }
    }
    return 0;
}
References BLOCK_SIZE, FDCT32(), FL_NOEXCEPT, fl::third_party::_IMDCTInfo::gb, NBANDS, fl::third_party::_IMDCTInfo::outBuf, polyCoef, PolyphaseMono(), PolyphaseStereo(), fl::third_party::_SubbandInfo::vbuf, VBUF_LENGTH, and fl::third_party::_SubbandInfo::vindex.
Referenced by MP3Decode().