FastLED: fl::third_party::plm_audio_decode_frame
plm_audio_decode_frame()
void fl::third_party::plm_audio_decode_frame (plm_audio_t * self)
Definition at line 3424 of file pl_mpeg.hpp.
{
    // Prepare the quantizer table lookups
    int tab3 = 0;
    int sblimit = 0;
    int tab1 = (self->mode == PLM_AUDIO_MODE_MONO) ? 0 : 1;
    int tab2 = PLM_AUDIO_QUANT_LUT_STEP_1[tab1][self->bitrate_index];
    tab3 = QUANT_LUT_STEP_2[tab2][self->samplerate_index];
    sblimit = tab3 & 63;
    tab3 >>= 6;
    if (self->bound > sblimit) {
        self->bound = sblimit;
    }
    // Read the allocation information
    for (int sb = 0; sb < self->bound; sb++) {
        self->allocation[0][sb] = plm_audio_read_allocation(self, sb, tab3);
        self->allocation[1][sb] = plm_audio_read_allocation(self, sb, tab3);
    }
    for (int sb = self->bound; sb < sblimit; sb++) {
        self->allocation[0][sb] =
            self->allocation[1][sb] =
            plm_audio_read_allocation(self, sb, tab3);
    }
    // Read scale factor selector information
    int channels = (self->mode == PLM_AUDIO_MODE_MONO) ? 1 : 2;
    for (int sb = 0; sb < sblimit; sb++) {
        for (int ch = 0; ch < channels; ch++) {
            if (self->allocation[ch][sb]) {
                self->scale_factor_info[ch][sb] = plm_buffer_read(self->buffer, 2);
            }
        }
        if (self->mode == PLM_AUDIO_MODE_MONO) {
            self->scale_factor_info[1][sb] = self->scale_factor_info[0][sb];
        }
    }
    // Read scale factors
    for (int sb = 0; sb < sblimit; sb++) {
        for (int ch = 0; ch < channels; ch++) {
            if (self->allocation[ch][sb]) {
                int *sf = self->scale_factor[ch][sb];
                switch (self->scale_factor_info[ch][sb]) {
                    case 0:
                        sf[0] = plm_buffer_read(self->buffer, 6);
                        sf[1] = plm_buffer_read(self->buffer, 6);
                        sf[2] = plm_buffer_read(self->buffer, 6);
                        break;
                    case 1:
                        sf[0] =
                        sf[1] = plm_buffer_read(self->buffer, 6);
                        sf[2] = plm_buffer_read(self->buffer, 6);
                        break;
                    case 2:
                        sf[0] =
                        sf[1] =
                        sf[2] = plm_buffer_read(self->buffer, 6);
                        break;
                    case 3:
                        sf[0] = plm_buffer_read(self->buffer, 6);
                        sf[1] =
                        sf[2] = plm_buffer_read(self->buffer, 6);
                        break;
                }
            }
        }
        if (self->mode == PLM_AUDIO_MODE_MONO) {
            self->scale_factor[1][sb][0] = self->scale_factor[0][sb][0];
            self->scale_factor[1][sb][1] = self->scale_factor[0][sb][1];
            self->scale_factor[1][sb][2] = self->scale_factor[0][sb][2];
        }
    }
    // Coefficient input and reconstruction
    int out_pos = 0;
    for (int part = 0; part < 3; part++) {
        for (int granule = 0; granule < 4; granule++) {
            // Read the samples
            for (int sb = 0; sb < self->bound; sb++) {
                plm_audio_read_samples(self, 0, sb, part);
                plm_audio_read_samples(self, 1, sb, part);
            }
            for (int sb = self->bound; sb < sblimit; sb++) {
                plm_audio_read_samples(self, 0, sb, part);
                self->sample[1][sb][0] = self->sample[0][sb][0];
                self->sample[1][sb][1] = self->sample[0][sb][1];
                self->sample[1][sb][2] = self->sample[0][sb][2];
            }
            for (int sb = sblimit; sb < 32; sb++) {
                self->sample[0][sb][0] = 0;
                self->sample[0][sb][1] = 0;
                self->sample[0][sb][2] = 0;
                self->sample[1][sb][0] = 0;
                self->sample[1][sb][1] = 0;
                self->sample[1][sb][2] = 0;
            }
            // Synthesis loop
            for (int p = 0; p < 3; p++) {
                // Shifting step
                self->v_pos = (self->v_pos - 64) & 1023;
                for (int ch = 0; ch < 2; ch++) {
                    plm_audio_idct36(self->sample[ch], p, self->V[ch], self->v_pos);
                    // Build U, windowing, calculate output
                    fl::memset(self->U, 0, sizeof(self->U));
                    int d_index = 512 - (self->v_pos >> 1);
                    int v_index = (self->v_pos % 128) >> 1;
                    while (v_index < 1024) {
                        for (int i = 0; i < 32; ++i) {
                            self->U[i] += self->D[d_index++] * self->V[ch][v_index++];
                        }
                        v_index += 128 - 32;
                        d_index += 64 - 32;
                    }
                    d_index -= (512 - 32);
                    v_index = (128 - 32 + 1024) - v_index;
                    while (v_index < 1024) {
                        for (int i = 0; i < 32; ++i) {
                            self->U[i] += self->D[d_index++] * self->V[ch][v_index++];
                        }
                        v_index += 128 - 32;
                        d_index += 64 - 32;
                    }
                    // Output samples
                    #ifdef PLM_AUDIO_SEPARATE_CHANNELS
                        float *out_channel = ch == 0
                            ? self->samples.left
                            : self->samples.right;
                        for (int j = 0; j < 32; j++) {
                            out_channel[out_pos + j] = self->U[j] / -1090519040.0f;
                        }
                    #else
                        for (int j = 0; j < 32; j++) {
                            self->samples.interleaved[((out_pos + j) << 1) + ch] =
                                self->U[j] / -1090519040.0f;
                        }
                    #endif
                } // End of synthesis channel loop
                out_pos += 32;
            } // End of synthesis sub-block loop
        } // Decoding of the granule finished
    }
    plm_buffer_align(self->buffer);
}
References FL_NOEXCEPT, fl::memset(), plm_audio_idct36(), PLM_AUDIO_MODE_MONO, PLM_AUDIO_QUANT_LUT_STEP_1, plm_audio_read_allocation(), plm_audio_read_samples(), plm_buffer_align(), plm_buffer_read(), and QUANT_LUT_STEP_2.
Referenced by plm_audio_decode().