FastLED: fl::third_party::nsgif__bitmap_fmt_to_colour_layout
nsgif__bitmap_fmt_to_colour_layout()
static struct nsgif_colour_layout fl::third_party::nsgif__bitmap_fmt_to_colour_layout (nsgif_bitmap_fmt_t bitmap_fmt) static
Definition at line 1434 of file gif.cpp.hpp.
{
    bool le = nsgif__host_is_little_endian();
    /* Map endian-dependant formats to byte-wise format for the host. */
    switch (bitmap_fmt) {
    case NSGIF_BITMAP_FMT_RGBA8888:
        bitmap_fmt = (le) ? NSGIF_BITMAP_FMT_A8B8G8R8
                          : NSGIF_BITMAP_FMT_R8G8B8A8;
        break;
    case NSGIF_BITMAP_FMT_BGRA8888:
        bitmap_fmt = (le) ? NSGIF_BITMAP_FMT_A8R8G8B8
                          : NSGIF_BITMAP_FMT_B8G8R8A8;
        break;
    case NSGIF_BITMAP_FMT_ARGB8888:
        bitmap_fmt = (le) ? NSGIF_BITMAP_FMT_B8G8R8A8
                          : NSGIF_BITMAP_FMT_A8R8G8B8;
        break;
    case NSGIF_BITMAP_FMT_ABGR8888:
        bitmap_fmt = (le) ? NSGIF_BITMAP_FMT_R8G8B8A8
                          : NSGIF_BITMAP_FMT_A8B8G8R8;
        break;
    case NSGIF_BITMAP_FMT_R8G8B8A8:
    case NSGIF_BITMAP_FMT_B8G8R8A8:
    case NSGIF_BITMAP_FMT_A8R8G8B8:
    case NSGIF_BITMAP_FMT_A8B8G8R8:
        /* These are already byte-wise formats, no conversion needed */
        break;
    default:
        break;
    }
    /* Set up colour component order for bitmap format. */
    switch (bitmap_fmt) {
    default:
        /* Fall through. */
    case NSGIF_BITMAP_FMT_R8G8B8A8:
            { struct nsgif_colour_layout result = {0, 1, 2, 3}; return result; }
    case NSGIF_BITMAP_FMT_B8G8R8A8:
            { struct nsgif_colour_layout result = {2, 1, 0, 3}; return result; }
    case NSGIF_BITMAP_FMT_A8R8G8B8:
            { struct nsgif_colour_layout result = {1, 2, 3, 0}; return result; }
    case NSGIF_BITMAP_FMT_A8B8G8R8:
            { struct nsgif_colour_layout result = {3, 2, 1, 0}; return result; }
    case NSGIF_BITMAP_FMT_RGBA8888:
    case NSGIF_BITMAP_FMT_BGRA8888:
    case NSGIF_BITMAP_FMT_ARGB8888:
    case NSGIF_BITMAP_FMT_ABGR8888:
        /* These should have been converted to byte-wise formats above */
        { struct nsgif_colour_layout result = {0, 1, 2, 3}; return result; }
    }
}
References FL_NOEXCEPT, nsgif__bitmap_fmt_to_colour_layout(), nsgif__host_is_little_endian(), NSGIF_BITMAP_FMT_A8B8G8R8, NSGIF_BITMAP_FMT_A8R8G8B8, NSGIF_BITMAP_FMT_ABGR8888, NSGIF_BITMAP_FMT_ARGB8888, NSGIF_BITMAP_FMT_B8G8R8A8, NSGIF_BITMAP_FMT_BGRA8888, NSGIF_BITMAP_FMT_R8G8B8A8, and NSGIF_BITMAP_FMT_RGBA8888.
Referenced by nsgif__bitmap_fmt_to_colour_layout(), and nsgif_create().