FastLED: fl::third_party::plm_video_decode_slice
plm_video_decode_slice()
void fl::third_party::plm_video_decode_slice (plm_video_t * self, int slice)
Definition at line 2453 of file pl_mpeg.hpp.
{
    self->slice_begin = TRUE;
    self->macroblock_address = (slice - 1) * self->mb_width - 1;
    // Reset motion vectors and DC predictors
    self->motion_backward.h = self->motion_forward.h = 0;
    self->motion_backward.v = self->motion_forward.v = 0;
    self->dc_predictor[0] = 128;
    self->dc_predictor[1] = 128;
    self->dc_predictor[2] = 128;
    self->quantizer_scale = plm_buffer_read(self->buffer, 5);
    // Skip extra
    while (plm_buffer_read(self->buffer, 1)) {
        plm_buffer_skip(self->buffer, 8);
    }
    do {
        plm_video_decode_macroblock(self);
    } while (
        self->macroblock_address < self->mb_size - 1 &&
        plm_buffer_peek_non_zero(self->buffer, 23)
    );
}
References FL_NOEXCEPT, plm_buffer_peek_non_zero(), plm_buffer_read(), plm_buffer_skip(), plm_video_decode_macroblock(), and TRUE.
Referenced by plm_video_decode_picture().