FastLED: fl::third_party::nsgif__bitmap_get
nsgif__bitmap_get()
static fl::u32 * fl::third_party::nsgif__bitmap_get (struct nsgif * gif) inline static
Helper to get the rendering bitmap for a gif.
Parameters
[in] gif The gif object we're decoding.
Returns
Client pixel buffer for rendering into.
Definition at line 233 of file gif.cpp.hpp.
{
    nsgif_error ret;
    /* Make sure we have a buffer to decode to. */
    ret = nsgif__initialise_sprite(gif, gif->info.width, gif->info.height);
    if (ret != NSGIF_OK) {
        return nullptr;
    }
    gif->rowspan = gif->info.width;
    if (gif->bitmap.get_rowspan) {
        gif->rowspan = gif->bitmap.get_rowspan(gif->frame_image);
    }
    /* Get the frame data */
    FL_ASSERT(gif->bitmap.get_buffer, "GIF bitmap get_buffer function required");
    return reinterpret_cast<fl::u32*>(gif->bitmap.get_buffer(gif->frame_image));
}
References FL_ASSERT, FL_NOEXCEPT, nsgif__initialise_sprite(), and NSGIF_OK.
Referenced by nsgif__record_frame(), and nsgif__update_bitmap().