FastLED: fl::third_party::alloc_pool
alloc_pool()
static void * fl::third_party::alloc_pool (JDEC * jd, size_t ndata) static
Definition at line 141 of file tjpgd.cpp.hpp.
{
    char *rp = 0;
    ndata = (ndata + 3) & ~3;           /* Align block size to the word boundary */
    if (jd->sz_pool >= ndata) {
        jd->sz_pool -= ndata;
        rp = (char*)jd->pool;           /* Get start of available memory pool */
        jd->pool = (void*)(rp + ndata); /* Allocate requierd bytes */
    }
    return (void*)rp;   /* Return allocated memory block (NULL:no memory to allocate) */
}
References FL_NOEXCEPT.
Referenced by create_huffman_tbl(), create_qt_tbl(), and jd_prepare().