FastLED: fl::third_party::plm_has_headers
plm_has_headers()
int fl::third_party::plm_has_headers (plm_t * self)
Definition at line 312 of file pl_mpeg.hpp.
{
    if (!plm_demux_has_headers(self->demux)) {
        return FALSE;
    }
    if (!plm_init_decoders(self)) {
        return FALSE;
    }
    if (
        (self->video_decoder && !plm_video_has_header(self->video_decoder)) ||
        (self->audio_decoder && !plm_audio_has_header(self->audio_decoder))
    ) {
        return FALSE;
    }
    return TRUE;
}
References FALSE, FL_NOEXCEPT, plm_audio_has_header(), plm_demux_has_headers(), plm_init_decoders(), plm_video_has_header(), and TRUE.
Referenced by fl::third_party::SoftwareMpeg1Decoder::initializeDecoder().