FastLED: fl::third_party::plm_decode
plm_decode()
void fl::third_party::plm_decode (plm_t * self, double seconds)
Definition at line 474 of file pl_mpeg.hpp.
{
    if (!plm_init_decoders(self)) {
        return;
    }
    int decode_video = (self->video_decode_callback && self->video_packet_type);
    int decode_audio = (self->audio_decode_callback && self->audio_packet_type);
    if (!decode_video && !decode_audio) {
        // Nothing to do here
        return;
    }
    int did_decode = FALSE;
    int decode_video_failed = FALSE;
    int decode_audio_failed = FALSE;
    double video_target_time = self->time + tick;
    double audio_target_time = self->time + tick + self->audio_lead_time;
    do {
        did_decode = FALSE;
        if (decode_video && plm_video_get_time(self->video_decoder) < video_target_time) {
            plm_frame_t *frame = plm_video_decode(self->video_decoder);
            if (frame) {
                self->video_decode_callback(self, frame, self->video_decode_callback_user_data);
                did_decode = TRUE;
            }
            else {
                decode_video_failed = TRUE;
            }
        }
        if (decode_audio && plm_audio_get_time(self->audio_decoder) < audio_target_time) {
            plm_samples_t *samples = plm_audio_decode(self->audio_decoder);
            if (samples) {
                self->audio_decode_callback(self, samples, self->audio_decode_callback_user_data);
                did_decode = TRUE;
            }
            else {
                decode_audio_failed = TRUE;
            }
        }
    } while (did_decode);
    // Did all sources we wanted to decode fail and the demuxer is at the end?
    if (
        (!decode_video || decode_video_failed) &&
        (!decode_audio || decode_audio_failed) &&
        plm_demux_has_ended(self->demux)
    ) {
        plm_handle_end(self);
        return;
    }
    self->time += tick;
}
References FALSE, FL_NOEXCEPT, plm_audio_decode(), plm_audio_get_time(), plm_demux_has_ended(), plm_handle_end(), plm_init_decoders(), plm_video_decode(), plm_video_get_time(), and TRUE.
Referenced by fl::third_party::SoftwareMpeg1Decoder::decodeNextFrame(), fl::third_party::SoftwareMpeg1Decoder::initializeDecoder(), and plm_seek().