FastLED: fl::third_party::IntensityProcMPEG2
IntensityProcMPEG2()
void fl::third_party::IntensityProcMPEG2 (int32_t x[MAX_NCHAN][MAX_NSAMP], int32_t nSamps, FrameHeader * fh, ScaleFactorInfoSub * sfis, CriticalBandInfo * cbi, ScaleFactorJS * sfjs, int32_t midSideFlag, int32_t mixFlag, int32_t mOut[2])
Definition at line 220 of file stproc.hpp.
{
    (void)mixFlag;  // Unused parameter - reserved for future use
    int32_t i, j, k, n, r, cb, w;
    int32_t fl, fr, mOutL, mOutR, xl, xr;
    int32_t sampsLeft;
    int32_t isf, sfIdx, tmp, il[23];
    int32_t *isfTab;
    int32_t cbStartL, cbStartS, cbEndL, cbEndS;
    isfTab = (int32_t *)ISFMpeg2[sfjs->intensityScale][midSideFlag];
    mOutL = mOutR = 0;
    /* fill buffer with illegal intensity positions (depending on slen) */
    for (k = r = 0; r < 4; r++) {
        tmp = (1 << sfjs->slen[r]) - 1;
        for (j = 0; j < sfjs->nr[r]; j++, k++)
            il[k] = tmp;
    }
    if (cbi[1].cbType == 0) {
        /* long blocks */
        il[21] = il[22] = 1;
        cbStartL = cbi[1].cbEndL + 1; /* start at end of right */
        cbEndL =   cbi[0].cbEndL + 1; /* process to end of left */
        i = fh->sfBand->l[cbStartL];
        sampsLeft = nSamps - i;
        for(cb = cbStartL; cb < cbEndL; cb++) {
            sfIdx = sfis->l[cb];
            if (sfIdx == il[cb]) {
                fl = ISFIIP[midSideFlag][0];
                fr = ISFIIP[midSideFlag][1];
            } else {
                isf = (sfis->l[cb] + 1) >> 1;
                fl = isfTab[(sfIdx & 0x01 ? isf : 0)];
                fr = isfTab[(sfIdx & 0x01 ? 0 : isf)];
            }
            n = MIN(fh->sfBand->l[cb + 1] - fh->sfBand->l[cb], sampsLeft);
            for(j = 0; j < n; j++, i++) {
                xr = MULSHIFT32(fr, x[0][i]) << 2;   x[1][i] = xr;  mOutR |= FASTABS(xr);
                xl = MULSHIFT32(fl, x[0][i]) << 2; x[0][i] = xl;  mOutL |= FASTABS(xl);
            }
            /* early exit once we've used all the non-zero samples */
            sampsLeft -= n;
            if (sampsLeft == 0)
                break;
        }
    } else {
        /* short or mixed blocks */
        il[12] = 1;
        for(w = 0; w < 3; w++) {
            cbStartS = cbi[1].cbEndS[w] + 1;      /* start at end of right */
            cbEndS =   cbi[0].cbEndS[w] + 1;      /* process to end of left */
            i = 3 * fh->sfBand->s[cbStartS] + w;
            /* skip through sample array by 3, so early-exit logic would be more tricky */
            for(cb = cbStartS; cb < cbEndS; cb++) {
                sfIdx = sfis->s[cb][w];
                if (sfIdx == il[cb]) {
                    fl = ISFIIP[midSideFlag][0];
                    fr = ISFIIP[midSideFlag][1];
                } else {
                    isf = (sfis->s[cb][w] + 1) >> 1;
                    fl = isfTab[(sfIdx & 0x01 ? isf : 0)];
                    fr = isfTab[(sfIdx & 0x01 ? 0 : isf)];
                }
                n = fh->sfBand->s[cb + 1] - fh->sfBand->s[cb];
                for(j = 0; j < n; j++, i+=3) {
                    xr = MULSHIFT32(fr, x[0][i]) << 2;   x[1][i] = xr;  mOutR |= FASTABS(xr);
                    xl = MULSHIFT32(fl, x[0][i]) << 2; x[0][i] = xl;  mOutL |= FASTABS(xl);
                }
            }
        }
    }
    mOut[0] = mOutL;
    mOut[1] = mOutR;
    return;
}
References FASTABS(), FL_NOEXCEPT, ISFIIP, ISFMpeg2, MAX_NCHAN, MAX_NSAMP, MIN, MULSHIFT32(), and fl::x.
Referenced by Dequantize().