FastLED: fl::third_party::plm_demux_decode_packet
plm_demux_decode_packet()
plm_packet_t * fl::third_party::plm_demux_decode_packet (plm_demux_t * self, int type)
Definition at line 1567 of file pl_mpeg.hpp.
{
    if (!plm_buffer_has(self->buffer, 16 << 3)) {
        return NULL;
    }
    self->start_code = -1;
    self->next_packet.type = type;
    self->next_packet.length = plm_buffer_read(self->buffer, 16);
    self->next_packet.length -= plm_buffer_skip_bytes(self->buffer, 0xff); // stuffing
    // skip P-STD
    if (plm_buffer_read(self->buffer, 2) == 0x01) {
        plm_buffer_skip(self->buffer, 16);
        self->next_packet.length -= 2;
    }
    int pts_dts_marker = plm_buffer_read(self->buffer, 2);
    if (pts_dts_marker == 0x03) {
        self->next_packet.pts = plm_demux_decode_time(self);
        self->last_decoded_pts = self->next_packet.pts;
        plm_buffer_skip(self->buffer, 40); // skip dts
        self->next_packet.length -= 10;
    }
    else if (pts_dts_marker == 0x02) {
        self->next_packet.pts = plm_demux_decode_time(self);
        self->last_decoded_pts = self->next_packet.pts;
        self->next_packet.length -= 5;
    }
    else if (pts_dts_marker == 0x00) {
        self->next_packet.pts = PLM_PACKET_INVALID_TS;
        plm_buffer_skip(self->buffer, 4);
        self->next_packet.length -= 1;
    }
    else {
        return NULL; // invalid
    }
    return plm_demux_get_packet(self);
}
References FL_NOEXCEPT, NULL, plm_buffer_has(), plm_buffer_read(), plm_buffer_skip(), plm_buffer_skip_bytes(), plm_demux_decode_time(), plm_demux_get_packet(), and PLM_PACKET_INVALID_TS.
Referenced by plm_demux_decode(), and plm_demux_seek().