FastLED: fl::third_party::plm_buffer_seek
plm_buffer_seek()
void fl::third_party::plm_buffer_seek (plm_buffer_t * self, size_t pos)
Definition at line 923 of file pl_mpeg.hpp.
{
    self->has_ended = FALSE;
    if (self->seek_callback) {
        self->seek_callback(self, pos, self->load_callback_user_data);
        self->bit_index = 0;
        self->length = 0;
    }
    else if (self->mode == PLM_BUFFER_MODE_RING) {
        if (pos != 0) {
            // Seeking to non-0 is forbidden for dynamic-mem buffers
            return;
        }
        self->bit_index = 0;
        self->length = 0;
        self->total_size = 0;
    }
    else if (pos < self->length) {
        self->bit_index = pos << 3;
    }
}
References FALSE, FL_NOEXCEPT, length(), PLM_BUFFER_MODE_RING, and pos.
Referenced by plm_buffer_rewind(), and plm_demux_buffer_seek().