FastLED: fl::third_party::plm_video_decode
plm_video_decode()
plm_frame_t * fl::third_party::plm_video_decode (plm_video_t * self)
Definition at line 2197 of file pl_mpeg.hpp.
{
    if (!plm_video_has_header(self)) {
        return NULL;
    }
    plm_frame_t *frame = NULL;
    do {
        if (self->start_code != PLM_START_PICTURE) {
            self->start_code = plm_buffer_find_start_code(self->buffer, PLM_START_PICTURE);
            if (self->start_code == -1) {
                // If we reached the end of the file and the previously decoded
                // frame was a reference frame, we still have to return it.
                if (
                    self->has_reference_frame &&
                    !self->assume_no_b_frames &&
                    plm_buffer_has_ended(self->buffer) && (
                        self->picture_type == PLM_VIDEO_PICTURE_TYPE_INTRA ||
                        self->picture_type == PLM_VIDEO_PICTURE_TYPE_PREDICTIVE
                    )
                ) {
                    self->has_reference_frame = FALSE;
                    frame = &self->frame_backward;
                    break;
                }
                return NULL;
            }
        }
        // Make sure we have a full picture in the buffer before attempting to
        // decode it. Sadly, this can only be done by seeking for the start code
        // of the next picture. Also, if we didn't find the start code for the
        // next picture, but the source has ended, we assume that this last
        // picture is in the buffer.
        if (
            plm_buffer_has_start_code(self->buffer, PLM_START_PICTURE) == -1 &&
            !plm_buffer_has_ended(self->buffer)
        ) {
            return NULL;
        }
        plm_buffer_discard_read_bytes(self->buffer);
        plm_video_decode_picture(self);
        if (self->assume_no_b_frames) {
            frame = &self->frame_backward;
        }
        else if (self->picture_type == PLM_VIDEO_PICTURE_TYPE_B) {
            frame = &self->frame_current;
        }
        else if (self->has_reference_frame) {
            frame = &self->frame_forward;
        }
        else {
            self->has_reference_frame = TRUE;
        }
    } while (!frame);
    frame->time = self->time;
    self->frames_decoded++;
    self->time = (double)self->frames_decoded / self->framerate;
    return frame;
}
References FALSE, FL_NOEXCEPT, NULL, plm_buffer_discard_read_bytes(), plm_buffer_find_start_code(), plm_buffer_has_ended(), plm_buffer_has_start_code(), PLM_START_PICTURE, plm_video_decode_picture(), plm_video_has_header(), PLM_VIDEO_PICTURE_TYPE_B, PLM_VIDEO_PICTURE_TYPE_INTRA, PLM_VIDEO_PICTURE_TYPE_PREDICTIVE, fl::third_party::plm_frame_t::time, and TRUE.
Referenced by plm_decode(), plm_decode_video(), and plm_seek_frame().