FastLED: fl::third_party::jd_decomp
jd_decomp()
JRESULT fl::third_party::jd_decomp (JDEC * jd, int(* outfunc)(JDEC *, void *, JRECT *), uint8_t scale)
Definition at line 1144 of file tjpgd.cpp.hpp.
{
    unsigned int x, y, mx, my;
    uint16_t rst, rsc;
    JRESULT rc;
    if (scale > (JD_USE_SCALE ? 3 : 0)) return JDR_PAR;
    jd->scale = scale;
    mx = jd->msx * 8; my = jd->msy * 8;           /* Size of the MCU (pixel) */
    jd->dcv[2] = jd->dcv[1] = jd->dcv[0] = 0;  /* Initialize DC values */
    rst = rsc = 0;
    rc = JDR_OK;
    for (y = 0; y < jd->height; y += my) {     /* Vertical loop of MCUs */
        for (x = 0; x < jd->width; x += mx) {   /* Horizontal loop of MCUs */
            if (jd->nrst && rst++ == jd->nrst) {    /* Process restart interval if enabled */
                rc = restart(jd, rsc++);
                if (rc != JDR_OK) return rc;
                rst = 1;
            }
            rc = mcu_load(jd);                  /* Load an MCU (decompress huffman coded stream, dequantize and apply IDCT) */
            if (rc != JDR_OK) return rc;
            rc = mcu_output(jd, outfunc, x, y); /* Output the MCU (YCbCr to RGB, scaling and output) */
            if (rc != JDR_OK) return rc;
        }
    }
    return rc;
}
References fl::third_party::JDEC::dcv, FL_NOEXCEPT, fl::third_party::JDEC::height, JD_USE_SCALE, JDR_OK, JDR_PAR, mcu_load(), mcu_output(), fl::third_party::JDEC::msx, fl::third_party::JDEC::msy, fl::third_party::JDEC::nrst, restart(), fl::third_party::JDEC::scale, scale, fl::third_party::JDEC::width, fl::x, and fl::y.
Referenced by fl::third_party::TJpg_Decoder::drawJpg(), and fl::third_party::TJpgInstanceDecoder::processChunk().