FastLED: fl::third_party::plm_seek
plm_seek()
int fl::third_party::plm_seek (plm_t * self, double time, int seek_exact)
Definition at line 672 of file pl_mpeg.hpp.
{
    plm_frame_t *frame = plm_seek_frame(self, time, seek_exact);
    if (!frame) {
        return FALSE;
    }
    if (self->video_decode_callback) {
        self->video_decode_callback(self, frame, self->video_decode_callback_user_data);
    }
    // If audio is not enabled we are done here.
    if (!self->audio_packet_type) {
        return TRUE;
    }
    // Sync up Audio. This demuxes more packets until the first audio packet
    // with a PTS greater than the current time is found. plm_decode() is then
    // called to decode enough audio data to satisfy the audio_lead_time.
    double start_time = plm_demux_get_start_time(self->demux, self->video_packet_type);
    plm_audio_rewind(self->audio_decoder);
    plm_packet_t *packet = NULL;
    while ((packet = plm_demux_decode(self->demux))) {
        if (packet->type == self->video_packet_type) {
            plm_buffer_write(self->video_buffer, packet->data, packet->length);
        }
        else if (
            packet->type == self->audio_packet_type &&
            packet->pts - start_time > self->time
        ) {
            plm_audio_set_time(self->audio_decoder, packet->pts - start_time);
            plm_buffer_write(self->audio_buffer, packet->data, packet->length);
            plm_decode(self, 0);
            break;
        }
    }
    return TRUE;
}
References fl::third_party::plm_packet_t::data, FALSE, FL_NOEXCEPT, fl::third_party::plm_packet_t::length, NULL, plm_audio_rewind(), plm_audio_set_time(), plm_buffer_write(), plm_decode(), plm_demux_decode(), plm_demux_get_start_time(), plm_seek_frame(), fl::third_party::plm_packet_t::pts, fl::time(), TRUE, and fl::third_party::plm_packet_t::type.