FastLED: fl::third_party::DecodeHuffman
DecodeHuffman()
int fl::third_party::DecodeHuffman (MP3DecInfo * mp3DecInfo, const unsigned char * buf, int * bitOffset, int huffBlockBits, int gr, int ch)
Definition at line 385 of file huffman.hpp.
{
    int r1Start, r2Start, rEnd[4];  /* region boundaries */
    int i, w, bitsUsed, bitsLeft;
    const unsigned char *startBuf = buf;
    FrameHeader *fh;
    SideInfo *si;
    SideInfoSub *sis;
    HuffmanInfo *hi;
    /* validate pointers */
    if (!mp3DecInfo || !mp3DecInfo->FrameHeaderPS || !mp3DecInfo->SideInfoPS || !mp3DecInfo->ScaleFactorInfoPS || !mp3DecInfo->HuffmanInfoPS)
        return -1;
    fh = ((FrameHeader *)(mp3DecInfo->FrameHeaderPS));
    si = ((SideInfo *)(mp3DecInfo->SideInfoPS));
    sis = &si->sis[gr][ch];
    hi = (HuffmanInfo*)(mp3DecInfo->HuffmanInfoPS);
    if (huffBlockBits < 0)
        return -1;
    /* figure out region boundaries (the first 2*bigVals coefficients divided into 3 regions) */
    if (sis->winSwitchFlag && sis->blockType == 2) {
        if (sis->mixedBlock == 0) {
            r1Start = fh->sfBand->s[(sis->region0Count + 1)/3] * 3;
        } else {
            if (fh->ver == MPEG1) {
                r1Start = fh->sfBand->l[sis->region0Count + 1];
            } else {
                /* see MPEG2 spec for explanation */
                w = fh->sfBand->s[4] - fh->sfBand->s[3];
                r1Start = fh->sfBand->l[6] + 2*w;
            }
        }
        r2Start = MAX_NSAMP;   /* short blocks don't have region 2 */
    } else {
        r1Start = fh->sfBand->l[sis->region0Count + 1];
        r2Start = fh->sfBand->l[sis->region0Count + 1 + sis->region1Count + 1];
    }
    /* offset rEnd index by 1 so first region = rEnd[1] - rEnd[0], etc. */
    rEnd[3] = MIN(MAX_NSAMP, 2 * sis->nBigvals);
    rEnd[2] = MIN(r2Start, rEnd[3]);
    rEnd[1] = MIN(r1Start, rEnd[3]);
    rEnd[0] = 0;
    /* rounds up to first all-zero pair (we don't check last pair for (x,y) == (non-zero, zero)) */
    hi->nonZeroBound[ch] = rEnd[3];
    /* decode Huffman pairs (rEnd[i] are always even numbers) */
    bitsLeft = huffBlockBits;
    for (i = 0; i < 3; i++) {
        bitsUsed = DecodeHuffmanPairs(hi->huffDecBuf[ch] + rEnd[i], rEnd[i+1] - rEnd[i], sis->tableSelect[i], bitsLeft, buf, *bitOffset);
        if (bitsUsed < 0 || bitsUsed > bitsLeft)    /* error - overran end of bitstream */
            return -1;
        /* update bitstream position */
        buf += (bitsUsed + *bitOffset) >> 3;
        *bitOffset = (bitsUsed + *bitOffset) & 0x07;
        bitsLeft -= bitsUsed;
    }
    /* decode Huffman quads (if any) */
    hi->nonZeroBound[ch] += DecodeHuffmanQuads(hi->huffDecBuf[ch] + rEnd[3], MAX_NSAMP - rEnd[3], sis->count1TableSelect, bitsLeft, buf, *bitOffset);
    ASSERT(hi->nonZeroBound[ch] <= MAX_NSAMP);
    for (i = hi->nonZeroBound[ch]; i < MAX_NSAMP; i++)
        hi->huffDecBuf[ch][i] = 0;
    /* If bits used for 576 samples < huffBlockBits, then the extras are considered
     *  to be stuffing bits (throw away, but need to return correct bitstream position)
     */
    buf += (bitsLeft + *bitOffset) >> 3;
    *bitOffset = (bitsLeft + *bitOffset) & 0x07;
    return (buf - startBuf);
}
References ASSERT, fl::third_party::_SideInfoSub::blockType, fl::third_party::_SideInfoSub::count1TableSelect, DecodeHuffmanPairs(), DecodeHuffmanQuads(), FL_NOEXCEPT, fl::third_party::_HuffmanInfo::huffDecBuf, fl::third_party::_SFBandTable::l, MAX_NSAMP, MIN, fl::third_party::_SideInfoSub::mixedBlock, MPEG1, fl::third_party::_SideInfoSub::nBigvals, fl::third_party::_HuffmanInfo::nonZeroBound, fl::third_party::_SideInfoSub::region0Count, fl::third_party::_SideInfoSub::region1Count, fl::third_party::_SFBandTable::s, fl::third_party::_FrameHeader::sfBand, fl::third_party::_SideInfo::sis, fl::third_party::_SideInfoSub::tableSelect, fl::third_party::_FrameHeader::ver, and fl::third_party::_SideInfoSub::winSwitchFlag.
Referenced by MP3Decode().