FastLED: fl::third_party::plm_read_packets
plm_read_packets()
void fl::third_party::plm_read_packets (plm_t * self, int requested_type)
Definition at line 592 of file pl_mpeg.hpp.
{
    plm_packet_t *packet;
    while ((packet = plm_demux_decode(self->demux))) {
        if (packet->type == self->video_packet_type) {
            plm_buffer_write(self->video_buffer, packet->data, packet->length);
        }
        else if (packet->type == self->audio_packet_type) {
            plm_buffer_write(self->audio_buffer, packet->data, packet->length);
        }
        if (packet->type == requested_type) {
            return;
        }
    }
    if (plm_demux_has_ended(self->demux)) {
        if (self->video_buffer) {
            plm_buffer_signal_end(self->video_buffer);
        }
        if (self->audio_buffer) {
            plm_buffer_signal_end(self->audio_buffer);
        }
    }
}
References fl::third_party::plm_packet_t::data, FL_NOEXCEPT, fl::third_party::plm_packet_t::length, plm_buffer_signal_end(), plm_buffer_write(), plm_demux_decode(), plm_demux_has_ended(), and fl::third_party::plm_packet_t::type.
Referenced by plm_read_audio_packet(), and plm_read_video_packet().