FastLED: fl::third_party::AllocateBuffers
AllocateBuffers()
MP3DecInfo * fl::third_party::AllocateBuffers (void)
Definition at line 99 of file buffers.hpp.
{
    MP3DecInfo *mp3DecInfo;
    FrameHeader *fh;
    SideInfo *si;
    ScaleFactorInfo *sfi;
    HuffmanInfo *hi;
    DequantInfo *di;
    IMDCTInfo *mi;
    SubbandInfo *sbi;
    mp3DecInfo = (MP3DecInfo *)malloc(sizeof(MP3DecInfo));
    if (!mp3DecInfo)
        return 0;
    ClearBuffer(mp3DecInfo, sizeof(MP3DecInfo));
    fh =  (FrameHeader *)     malloc(sizeof(FrameHeader));
    si =  (SideInfo *)        malloc(sizeof(SideInfo));
    sfi = (ScaleFactorInfo *) malloc(sizeof(ScaleFactorInfo));
    hi =  (HuffmanInfo *)     malloc(sizeof(HuffmanInfo));
    di =  (DequantInfo *)     malloc(sizeof(DequantInfo));
    mi =  (IMDCTInfo *)       malloc(sizeof(IMDCTInfo));
    sbi = (SubbandInfo *)     malloc(sizeof(SubbandInfo));
    mp3DecInfo->FrameHeaderPS =     (void *)fh;
    mp3DecInfo->SideInfoPS =        (void *)si;
    mp3DecInfo->ScaleFactorInfoPS = (void *)sfi;
    mp3DecInfo->HuffmanInfoPS =     (void *)hi;
    mp3DecInfo->DequantInfoPS =     (void *)di;
    mp3DecInfo->IMDCTInfoPS =       (void *)mi;
    mp3DecInfo->SubbandInfoPS =     (void *)sbi;
    if (!fh || !si || !sfi || !hi || !di || !mi || !sbi) {
        FreeBuffers(mp3DecInfo); /* safe to call - only frees memory that was successfully allocated */
        return 0;
    }
    /* important to do this - DSP primitives assume a bunch of state variables are 0 on first use */
    ClearBuffer(fh,  sizeof(FrameHeader));
    ClearBuffer(si,  sizeof(SideInfo));
    ClearBuffer(sfi, sizeof(ScaleFactorInfo));
    ClearBuffer(hi,  sizeof(HuffmanInfo));
    ClearBuffer(di,  sizeof(DequantInfo));
    ClearBuffer(mi,  sizeof(IMDCTInfo));
    ClearBuffer(sbi, sizeof(SubbandInfo));
    return mp3DecInfo;
}
References ClearBuffer(), _MP3DecInfo::DequantInfoPS, FL_NOEXCEPT, _MP3DecInfo::FrameHeaderPS, FreeBuffers(), _MP3DecInfo::HuffmanInfoPS, _MP3DecInfo::IMDCTInfoPS, fl::malloc(), _MP3DecInfo::ScaleFactorInfoPS, _MP3DecInfo::SideInfoPS, and _MP3DecInfo::SubbandInfoPS.
Referenced by MP3InitDecoder().