FastLED: fl::third_party::nsgif__get_frame
nsgif__get_frame()
static struct nsgif_frame * fl::third_party::nsgif__get_frame (struct nsgif * gif, fl::u32 frame_idx) static
Definition at line 1273 of file gif.cpp.hpp.
{
    struct nsgif_frame *frame;
    if (gif->frame_holders > frame_idx) {
        frame = &gif->frames[frame_idx];
    } else {
        /* Allocate more memory */
        fl::size count = frame_idx + 1;
        struct nsgif_frame *temp;
        temp = static_cast<struct nsgif_frame*>(fl::Malloc(count * sizeof(*frame)));
        if (temp == nullptr) {
            return nullptr;
        }
        if (gif->frames) {
            fl::memcpy(temp, gif->frames, gif->frame_holders * sizeof(*frame));
            fl::Free(gif->frames);
        }
        gif->frames = temp;
        gif->frame_holders = count;
        frame = &gif->frames[frame_idx];
        frame->info.local_palette = false;
        frame->info.transparency = false;
        frame->info.display = false;
        frame->info.disposal = 0;
        frame->info.delay = 10;
        frame->transparency_index = NSGIF_NO_TRANSPARENCY;
        frame->frame_offset = gif->buf_pos;
        frame->redraw_required = false;
        frame->lzw_data_length = 0;
        frame->decoded = false;
    }
    return frame;
}
References fl::third_party::nsgif_frame::decoded, fl::third_party::nsgif_frame_info::delay, fl::third_party::nsgif_frame_info::display, fl::third_party::nsgif_frame_info::disposal, FL_NOEXCEPT, fl::third_party::nsgif_frame::frame_offset, fl::Free(), fl::third_party::nsgif_frame::info, fl::third_party::nsgif_frame_info::local_palette, fl::third_party::nsgif_frame::lzw_data_length, fl::Malloc(), fl::memcpy(), NSGIF_NO_TRANSPARENCY, fl::third_party::nsgif_frame::redraw_required, fl::third_party::nsgif_frame_info::transparency, and fl::third_party::nsgif_frame::transparency_index.
Referenced by nsgif__process_frame().