FastLED: fl::third_party::plm_demux_rewind
plm_demux_rewind()
void fl::third_party::plm_demux_rewind (plm_demux_t * self)
Definition at line 1286 of file pl_mpeg.hpp.
{
    plm_buffer_rewind(self->buffer);
    self->current_packet.length = 0;
    self->next_packet.length = 0;
    self->start_code = -1;
}
References FL_NOEXCEPT, and plm_buffer_rewind().
Referenced by plm_demux_get_start_time(), and plm_rewind().