FastLED: fl::third_party::lzw__decode
lzw__decode()
static lzw_result fl::third_party::lzw__decode (struct lzw_ctx * ctx, lzw_writer_fn write_fn, void * output_data, fl::u32 output_length, fl::u32 * output_written) inline static
Get the next LZW code and write its value(s) to output buffer.
Parameters
[in] ctx LZW reading context, updated.
[in] write_fn Function for writing pixels to output.
[in] output_data Array to write output values into.
[in] output_length Size of output array.
[in,out] output_written Number of values written. Updated on exit.
Returns
LZW_OK on success, or appropriate error code otherwise.
Definition at line 389 of file lzw.cpp.hpp.
{
    lzw_result res;
    fl::u16 code = 0;
    /* Get a new code from the input */
    res = lzw__read_code(&ctx->input, ctx->code_size, &code);
    if (res != LZW_OK) {
        return res;
    }
    /* Handle the new code */
    if (code == ctx->eoi_code) {
        /* Got End of Information code */
        return LZW_EOI_CODE;
    } else if (code > ctx->table_size) {
        /* Code is invalid */
        return LZW_BAD_CODE;
    } else if (code == ctx->clear_code) {
        res = lzw__handle_clear(ctx, &code);
        if (res != LZW_OK) {
            return res;
        }
    } else if (ctx->table_size < LZW_TABLE_ENTRY_MAX) {
        fl::u16 size = ctx->table_size;
        lzw__table_add_entry(ctx, (code < size) ?
                ctx->table[code].first :
                ctx->prev_code_first);
        /* Ensure code size is increased, if needed. */
        if (size == ctx->code_max && ctx->code_size < LZW_CODE_MAX) {
            ctx->code_size++;
            ctx->code_max = (1 << ctx->code_size) - 1;
        }
    }
    *output_written += write_fn(ctx,
            output_data, output_length, *output_written,
            code, ctx->table[code].count);
    /* Store details of this code as "previous code" to the context. */
    ctx->prev_code_first = ctx->table[code].first;
    ctx->prev_code_count = ctx->table[code].count;
    ctx->prev_code = code;
    return LZW_OK;
}
References fl::third_party::lzw_ctx::clear_code, fl::third_party::lzw_ctx::code_max, fl::third_party::lzw_ctx::code_size, fl::third_party::lzw_table_entry::count, fl::third_party::lzw_ctx::eoi_code, fl::third_party::lzw_table_entry::first, FL_NOEXCEPT, fl::third_party::lzw_ctx::input, lzw__handle_clear(), lzw__read_code(), lzw__table_add_entry(), LZW_BAD_CODE, LZW_CODE_MAX, LZW_EOI_CODE, LZW_OK, LZW_TABLE_ENTRY_MAX, fl::third_party::lzw_ctx::prev_code, fl::third_party::lzw_ctx::prev_code_count, fl::third_party::lzw_ctx::prev_code_first, fl::third_party::lzw_ctx::table, and fl::third_party::lzw_ctx::table_size.
Referenced by lzw_decode(), and lzw_decode_map().