FastLED: fl::third_party::lzw__handle_clear
lzw__handle_clear()
static lzw_result fl::third_party::lzw__handle_clear (struct lzw_ctx * ctx, fl::u16 * code_out) inline static
Handle clear code.
Parameters
[in] ctx LZW reading context, updated.
[out] code_out Returns next code after a clear code.
Returns
LZW_OK or error code.
Definition at line 233 of file lzw.cpp.hpp.
{
    fl::u16 code = 0;
    /* Reset table building context */
    ctx->code_size = ctx->initial_code_size;
    ctx->code_max = (1 << ctx->initial_code_size) - 1;
    ctx->table_size = ctx->eoi_code + 1;
    /* There might be a sequence of clear codes, so process them all */
    do {
        lzw_result res = lzw__read_code(&ctx->input,
                ctx->code_size, &code);
        if (res != LZW_OK) {
            return res;
        }
    } while (code == ctx->clear_code);
    /* The initial code must be from the initial table. */
    if (code > ctx->clear_code) {
        return LZW_BAD_ICODE;
    }
    *code_out = code;
    return LZW_OK;
}
References FL_NOEXCEPT, lzw__read_code(), LZW_BAD_ICODE, and LZW_OK.
Referenced by lzw__decode(), and lzw_decode_init().