FastLED: fl::third_party::IntensityProcMPEG1
IntensityProcMPEG1()
void fl::third_party::IntensityProcMPEG1 (int32_t x[MAX_NCHAN][MAX_NSAMP], int32_t nSamps, FrameHeader * fh, ScaleFactorInfoSub * sfis, CriticalBandInfo * cbi, int32_t midSideFlag, int32_t mixFlag, int32_t mOut[2])
Definition at line 113 of file stproc.hpp.
{
    (void)mixFlag;  // Unused parameter - reserved for future use
    int32_t i=0, j=0, n=0, cb=0, w=0;
    int32_t sampsLeft, isf, mOutL, mOutR, xl, xr;
    int32_t fl, fr, fls[3], frs[3];
    int32_t cbStartL=0, cbStartS=0, cbEndL=0, cbEndS=0;
    int32_t *isfTab;
    /* NOTE - this works fine for mixed blocks, as long as the switch point starts in the
     *  short block section (i.e. on or after sample 36 = sfBand->l[8] = 3*sfBand->s[3]
     * is this a safe assumption?
     * TODO - intensity + mixed not quite right (diff = 11 on he_mode)
     *  figure out correct implementation (spec ambiguous about when to do short block reorder)
     */
    if (cbi[1].cbType == 0) {
        /* long block */
        cbStartL = cbi[1].cbEndL + 1;
        cbEndL =   cbi[0].cbEndL + 1;
        cbStartS = cbEndS = 0;
        i = fh->sfBand->l[cbStartL];
    } else if (cbi[1].cbType == 1 || cbi[1].cbType == 2) {
        /* short or mixed block */
        cbStartS = cbi[1].cbEndSMax + 1;
        cbEndS =   cbi[0].cbEndSMax + 1;
        cbStartL = cbEndL = 0;
        i = 3 * fh->sfBand->s[cbStartS];
    }
    sampsLeft = nSamps - i;     /* process to length of left */
    isfTab = (int32_t *)ISFMpeg1[midSideFlag];
    mOutL = mOutR = 0;
    /* long blocks */
    for (cb = cbStartL; cb < cbEndL && sampsLeft > 0; cb++) {
        isf = sfis->l[cb];
        if (isf == 7) {
            fl = ISFIIP[midSideFlag][0];
            fr = ISFIIP[midSideFlag][1];
        } else {
            fl = isfTab[isf];
            fr = isfTab[6] - isfTab[isf];
        }
        n = fh->sfBand->l[cb + 1] - fh->sfBand->l[cb];
        for (j = 0; j < n && sampsLeft > 0; j++, i++) {
            xr = MULSHIFT32(fr, x[0][i]) << 2;   x[1][i] = xr; mOutR |= FASTABS(xr);
            xl = MULSHIFT32(fl, x[0][i]) << 2; x[0][i] = xl; mOutL |= FASTABS(xl);
            sampsLeft--;
        }
    }
    /* short blocks */
    for (cb = cbStartS; cb < cbEndS && sampsLeft >= 3; cb++) {
        for (w = 0; w < 3; w++) {
            isf = sfis->s[cb][w];
            if (isf == 7) {
                fls[w] = ISFIIP[midSideFlag][0];
                frs[w] = ISFIIP[midSideFlag][1];
            } else {
                fls[w] = isfTab[isf];
                frs[w] = isfTab[6] - isfTab[isf];
            }
        }
        n = fh->sfBand->s[cb + 1] - fh->sfBand->s[cb];
        for (j = 0; j < n && sampsLeft >= 3; j++, i+=3) {
            xr = MULSHIFT32(frs[0], x[0][i+0]) << 2; x[1][i+0] = xr;    mOutR |= FASTABS(xr);
            xl = MULSHIFT32(fls[0], x[0][i+0]) << 2; x[0][i+0] = xl;    mOutL |= FASTABS(xl);
            xr = MULSHIFT32(frs[1], x[0][i+1]) << 2; x[1][i+1] = xr;    mOutR |= FASTABS(xr);
            xl = MULSHIFT32(fls[1], x[0][i+1]) << 2; x[0][i+1] = xl;    mOutL |= FASTABS(xl);
            xr = MULSHIFT32(frs[2], x[0][i+2]) << 2; x[1][i+2] = xr;    mOutR |= FASTABS(xr);
            xl = MULSHIFT32(fls[2], x[0][i+2]) << 2; x[0][i+2] = xl;    mOutL |= FASTABS(xl);
            sampsLeft -= 3;
        }
    }
    mOut[0] = mOutL;
    mOut[1] = mOutR;
    return;
}
References FASTABS(), FL_NOEXCEPT, ISFIIP, ISFMpeg1, MAX_NCHAN, MAX_NSAMP, MULSHIFT32(), and fl::x.
Referenced by Dequantize().