FastLED: fl::third_party::plm_audio_read_samples
plm_audio_read_samples()
void fl::third_party::plm_audio_read_samples (plm_audio_t * self, int ch, int sb, int part)
Definition at line 3588 of file pl_mpeg.hpp.
{
    const plm_quantizer_spec_t *q = self->allocation[ch][sb];
    int sf = self->scale_factor[ch][sb][part];
    int *sample = self->sample[ch][sb];
    int val = 0;
    if (!q) {
        // No bits allocated for this subband
        sample[0] = sample[1] = sample[2] = 0;
        return;
    }
    // Resolve scalefactor
    if (sf == 63) {
        sf = 0;
    }
    else {
        int shift = (sf / 3) | 0;
        sf = (PLM_AUDIO_SCALEFACTOR_BASE[sf % 3] + ((1 << shift) >> 1)) >> shift;
    }
    // Decode samples
    int adj = q->levels;
    if (q->group) {
        // Decode grouped samples
        val = plm_buffer_read(self->buffer, q->bits);
        sample[0] = val % adj;
        val /= adj;
        sample[1] = val % adj;
        sample[2] = val / adj;
    }
    else {
        // Decode direct samples
        sample[0] = plm_buffer_read(self->buffer, q->bits);
        sample[1] = plm_buffer_read(self->buffer, q->bits);
        sample[2] = plm_buffer_read(self->buffer, q->bits);
    }
    // Postmultiply samples
    int scale = 65536 / (adj + 1);
    adj = ((adj + 1) >> 1) - 1;
    val = (adj - sample[0]) * scale;
    sample[0] = (val * (sf >> 12) + ((val * (sf & 4095) + 2048) >> 12)) >> 12;
    val = (adj - sample[1]) * scale;
    sample[1] = (val * (sf >> 12) + ((val * (sf & 4095) + 2048) >> 12)) >> 12;
    val = (adj - sample[2]) * scale;
    sample[2] = (val * (sf >> 12) + ((val * (sf & 4095) + 2048) >> 12)) >> 12;
}
References fl::third_party::plm_quantizer_spec_t::bits, FL_NOEXCEPT, fl::third_party::plm_quantizer_spec_t::group, fl::third_party::plm_quantizer_spec_t::levels, PLM_AUDIO_SCALEFACTOR_BASE, plm_buffer_read(), fl::sample(), and scale.
Referenced by plm_audio_decode_frame().