FastLED: fl::third_party::plm_demux_buffer_seek
plm_demux_buffer_seek()
void fl::third_party::plm_demux_buffer_seek (plm_demux_t * self, size_t pos)
Definition at line 1297 of file pl_mpeg.hpp.
{
    plm_buffer_seek(self->buffer, pos);
    self->current_packet.length = 0;
    self->next_packet.length = 0;
    self->start_code = -1;
}
References FL_NOEXCEPT, plm_buffer_seek(), and pos.
Referenced by plm_demux_get_duration(), plm_demux_get_start_time(), plm_demux_probe(), and plm_demux_seek().