FastLED: fl::third_party::UnpackSideInfo
UnpackSideInfo()
int fl::third_party::UnpackSideInfo (MP3DecInfo * mp3DecInfo, const unsigned char * buf)
Definition at line 304 of file bitstream.hpp.
{
    int gr, ch, bd, nBytes;
    BitStreamInfo bitStreamInfo, *bsi;
    FrameHeader *fh;
    SideInfo *si;
    SideInfoSub *sis;
    /* validate pointers and sync word */
    if (!mp3DecInfo || !mp3DecInfo->FrameHeaderPS || !mp3DecInfo->SideInfoPS)
        return -1;
    fh = ((FrameHeader *)(mp3DecInfo->FrameHeaderPS));
    si = ((SideInfo *)(mp3DecInfo->SideInfoPS));
    bsi = &bitStreamInfo;
    if (fh->ver == MPEG1) {
        /* MPEG 1 */
        nBytes = (fh->sMode == Mono ? SIBYTES_MPEG1_MONO : SIBYTES_MPEG1_STEREO);
        SetBitstreamPointer(bsi, nBytes, buf);
        si->mainDataBegin = GetBits(bsi, 9);
        si->privateBits =   GetBits(bsi, (fh->sMode == Mono ? 5 : 3));
        for (ch = 0; ch < mp3DecInfo->nChans; ch++)
            for (bd = 0; bd < MAX_SCFBD; bd++)
                si->scfsi[ch][bd] = GetBits(bsi, 1);
    } else {
        /* MPEG 2, MPEG 2.5 */
        nBytes = (fh->sMode == Mono ? SIBYTES_MPEG2_MONO : SIBYTES_MPEG2_STEREO);
        SetBitstreamPointer(bsi, nBytes, buf);
        si->mainDataBegin = GetBits(bsi, 8);
        si->privateBits =   GetBits(bsi, (fh->sMode == Mono ? 1 : 2));
    }
    for(gr =0; gr < mp3DecInfo->nGrans; gr++) {
        for (ch = 0; ch < mp3DecInfo->nChans; ch++) {
            sis = &si->sis[gr][ch];                      /* side info subblock for this granule, channel */
            sis->part23Length =    GetBits(bsi, 12);
            sis->nBigvals =        GetBits(bsi, 9);
            sis->globalGain =      GetBits(bsi, 8);
            sis->sfCompress =      GetBits(bsi, (fh->ver == MPEG1 ? 4 : 9));
            sis->winSwitchFlag =   GetBits(bsi, 1);
            if(sis->winSwitchFlag) {
                /* this is a start, stop, short, or mixed block */
                sis->blockType =       GetBits(bsi, 2);     /* 0 = normal, 1 = start, 2 = short, 3 = stop */
                sis->mixedBlock =      GetBits(bsi, 1);        /* 0 = not mixed, 1 = mixed */
                sis->tableSelect[0] =  GetBits(bsi, 5);
                sis->tableSelect[1] =  GetBits(bsi, 5);
                sis->tableSelect[2] =  0;                    /* unused */
                sis->subBlockGain[0] = GetBits(bsi, 3);
                sis->subBlockGain[1] = GetBits(bsi, 3);
                sis->subBlockGain[2] = GetBits(bsi, 3);
                /* TODO - check logic */
                if (sis->blockType == 0) {
                    /* this should not be allowed, according to spec */
                    sis->nBigvals = 0;
                    sis->part23Length = 0;
                    sis->sfCompress = 0;
                } else if (sis->blockType == 2 && sis->mixedBlock == 0) {
                    /* short block, not mixed */
                    sis->region0Count = 8;
                } else {
                    /* start, stop, or short-mixed */
                    sis->region0Count = 7;
                }
                sis->region1Count = 20 - sis->region0Count;
            } else {
                /* this is a normal block */
                sis->blockType = 0;
                sis->mixedBlock = 0;
                sis->tableSelect[0] =  GetBits(bsi, 5);
                sis->tableSelect[1] =  GetBits(bsi, 5);
                sis->tableSelect[2] =  GetBits(bsi, 5);
                sis->region0Count =    GetBits(bsi, 4);
                sis->region1Count =    GetBits(bsi, 3);
            }
            sis->preFlag =           (fh->ver == MPEG1 ? GetBits(bsi, 1) : 0);
            sis->sfactScale =        GetBits(bsi, 1);
            sis->count1TableSelect = GetBits(bsi, 1);
        }
    }
    mp3DecInfo->mainDataBegin = si->mainDataBegin;    /* needed by main decode loop */
    ASSERT(nBytes == CalcBitsUsed(bsi, buf, 0) >> 3);
    return nBytes;
}
References ASSERT, fl::third_party::_SideInfoSub::blockType, CalcBitsUsed(), fl::third_party::_SideInfoSub::count1TableSelect, FL_NOEXCEPT, GetBits(), fl::third_party::_SideInfoSub::globalGain, fl::third_party::_SideInfo::mainDataBegin, MAX_SCFBD, fl::third_party::_SideInfoSub::mixedBlock, Mono, MPEG1, fl::third_party::_SideInfoSub::nBigvals, fl::third_party::_SideInfoSub::part23Length, fl::third_party::_SideInfoSub::preFlag, fl::third_party::_SideInfo::privateBits, fl::third_party::_SideInfoSub::region0Count, fl::third_party::_SideInfoSub::region1Count, fl::third_party::_SideInfo::scfsi, SetBitstreamPointer(), fl::third_party::_SideInfoSub::sfactScale, fl::third_party::_SideInfoSub::sfCompress, SIBYTES_MPEG1_MONO, SIBYTES_MPEG1_STEREO, SIBYTES_MPEG2_MONO, SIBYTES_MPEG2_STEREO, fl::third_party::_SideInfo::sis, fl::third_party::_FrameHeader::sMode, fl::third_party::_SideInfoSub::subBlockGain, fl::third_party::_SideInfoSub::tableSelect, fl::third_party::_FrameHeader::ver, and fl::third_party::_SideInfoSub::winSwitchFlag.
Referenced by MP3Decode().