FastLED: fl::third_party::nsgif__record_frame
nsgif__record_frame()
static void fl::third_party::nsgif__record_frame (struct nsgif * gif, const fl::u32 * bitmap) static
Definition at line 302 of file gif.cpp.hpp.
{
    fl::size pixel_bytes = sizeof(*bitmap);
    fl::size height = gif->info.height;
    fl::size width  = gif->info.width;
    fl::u32 *prev_frame;
    if (gif->decoded_frame == NSGIF_FRAME_INVALID ||
        gif->decoded_frame == gif->prev_index) {
        /* No frame to copy, or already have this frame recorded. */
        return;
    }
    bitmap = nsgif__bitmap_get(gif);
    if (bitmap == nullptr) {
        return;
    }
    if (gif->prev_frame == nullptr) {
        prev_frame = static_cast<fl::u32*>(fl::Malloc(width * height * pixel_bytes));
        if (prev_frame == nullptr) {
            return;
        }
        gif->prev_frame = prev_frame;
    } else {
        prev_frame = static_cast<fl::u32*>(gif->prev_frame);
    }
    fl::memcpy(prev_frame, bitmap, width * height * pixel_bytes);
    gif->prev_frame  = prev_frame;
    gif->prev_index  = gif->decoded_frame;
}
References FL_NOEXCEPT, fl::height, fl::Malloc(), fl::memcpy(), nsgif__bitmap_get(), NSGIF_FRAME_INVALID, and fl::width.
Referenced by nsgif__update_bitmap().