FastLED: fl::third_party::plm_init_decoders
plm_init_decoders()
int fl::third_party::plm_init_decoders (plm_t * self)
Definition at line 261 of file pl_mpeg.hpp.
{
    if (self->has_decoders) {
        return TRUE;
    }
    if (!plm_demux_has_headers(self->demux)) {
        return FALSE;
    }
    if (plm_demux_get_num_video_streams(self->demux) > 0) {
        if (self->video_enabled) {
            self->video_packet_type = PLM_DEMUX_PACKET_VIDEO_1;
        }
        if (!self->video_decoder) {
            self->video_buffer = plm_buffer_create_with_capacity(PLM_BUFFER_DEFAULT_SIZE);
            plm_buffer_set_load_callback(self->video_buffer, plm_read_video_packet, self);
            self->video_decoder = plm_video_create_with_buffer(self->video_buffer, TRUE);
        }
    }
    if (plm_demux_get_num_audio_streams(self->demux) > 0) {
        if (self->audio_enabled) {
            self->audio_packet_type = PLM_DEMUX_PACKET_AUDIO_1 + self->audio_stream_index;
        }
        if (!self->audio_decoder) {
            self->audio_buffer = plm_buffer_create_with_capacity(PLM_BUFFER_DEFAULT_SIZE);
            plm_buffer_set_load_callback(self->audio_buffer, plm_read_audio_packet, self);
            self->audio_decoder = plm_audio_create_with_buffer(self->audio_buffer, TRUE);
        }
    }
    self->has_decoders = TRUE;
    return TRUE;
}
References FALSE, FL_NOEXCEPT, plm_audio_create_with_buffer(), plm_buffer_create_with_capacity(), PLM_BUFFER_DEFAULT_SIZE, plm_buffer_set_load_callback(), plm_demux_get_num_audio_streams(), plm_demux_get_num_video_streams(), plm_demux_has_headers(), PLM_DEMUX_PACKET_AUDIO_1, PLM_DEMUX_PACKET_VIDEO_1, plm_read_audio_packet(), plm_read_video_packet(), plm_video_create_with_buffer(), and TRUE.
Referenced by plm_create_with_buffer(), plm_decode(), plm_decode_audio(), plm_decode_video(), plm_get_framerate(), plm_get_height(), plm_get_pixel_aspect_ratio(), plm_get_samplerate(), plm_get_width(), plm_has_headers(), plm_probe(), plm_seek_frame(), plm_set_audio_enabled(), and plm_set_video_enabled().