FastLED: fl::third_party::plm_demux_probe
plm_demux_probe()
int fl::third_party::plm_demux_probe (plm_demux_t * self, size_t probesize)
Definition at line 1241 of file pl_mpeg.hpp.
{
    int previous_pos = plm_buffer_tell(self->buffer);
    int video_stream = FALSE;
    int audio_streams[4] = {FALSE, FALSE, FALSE, FALSE};
    do {
        self->start_code = plm_buffer_next_start_code(self->buffer);
        if (self->start_code == PLM_DEMUX_PACKET_VIDEO_1) {
            video_stream = TRUE;
        }
        else if (
            self->start_code >= PLM_DEMUX_PACKET_AUDIO_1 &&
            self->start_code <= PLM_DEMUX_PACKET_AUDIO_4
        ) {
            audio_streams[self->start_code - PLM_DEMUX_PACKET_AUDIO_1] = TRUE;
        }
    } while (
        self->start_code != -1 &&
        plm_buffer_tell(self->buffer) - previous_pos < probesize
    );
    self->num_video_streams = video_stream ? 1 : 0;
    self->num_audio_streams = 0;
    for (int i = 0; i < 4; i++) {
        if (audio_streams[i]) {
            self->num_audio_streams++;
        }
    }
    plm_demux_buffer_seek(self, previous_pos);
    return (self->num_video_streams || self->num_audio_streams);
}
References FALSE, FL_NOEXCEPT, plm_buffer_next_start_code(), plm_buffer_tell(), plm_demux_buffer_seek(), PLM_DEMUX_PACKET_AUDIO_1, PLM_DEMUX_PACKET_AUDIO_4, PLM_DEMUX_PACKET_VIDEO_1, and TRUE.
Referenced by plm_probe().