FastLED: fl::third_party::nsgif__process_frame
nsgif__process_frame()
static nsgif_error fl::third_party::nsgif__process_frame (struct nsgif * gif, fl::u32 frame_idx, bool decode) static
Attempts to initialise the next frame.
Parameters
[in] gif The animation context
[in] frame_idx The frame number to decode.
[in] decode Whether to decode the graphical image data.
Returns
NSGIF_OK on success, appropriate error otherwise.
Definition at line 1323 of file gif.cpp.hpp.
{
    nsgif_error ret;
    const fl::u8 *pos;
    const fl::u8 *end;
    struct nsgif_frame *frame;
    frame = nsgif__get_frame(gif, frame_idx);
    if (frame == nullptr) {
        return NSGIF_ERR_OOM;
    }
    end = gif->buf + gif->buf_len;
    if (decode) {
        pos = gif->buf + frame->frame_offset;
        /* Ensure this frame is supposed to be decoded */
        if (frame->info.display == false) {
            return NSGIF_OK;
        }
        /* Ensure the frame is in range to decode */
        if (frame_idx > gif->frame_count_partial) {
            return NSGIF_ERR_END_OF_DATA;
        }
        /* Done if frame is already decoded */
        if (frame_idx == gif->decoded_frame) {
            return NSGIF_OK;
        }
    } else {
        pos = gif->buf + gif->buf_pos;
        /* Check if we've finished */
        if (pos < end && pos[0] == NSGIF_TRAILER) {
            return NSGIF_OK;
        }
    }
    ret = nsgif__parse_frame_extensions(gif, frame, &pos, !decode);
    if (ret != NSGIF_OK) {
        goto cleanup;
    }
    ret = nsgif__parse_image_descriptor(gif, frame, &pos, !decode);
    if (ret != NSGIF_OK) {
        goto cleanup;
    }
    ret = nsgif__parse_colour_table(gif, frame, &pos, decode);
    if (ret != NSGIF_OK) {
        goto cleanup;
    }
    ret = nsgif__parse_image_data(gif, frame, &pos, decode);
    if (ret != NSGIF_OK) {
        goto cleanup;
    }
cleanup:
    if (!decode) {
        gif->buf_pos = pos - gif->buf;
    }
    return ret;
}
References fl::third_party::nsgif_frame_info::display, fl::end(), FL_NOEXCEPT, fl::third_party::nsgif_frame::frame_offset, fl::third_party::nsgif_frame::info, nsgif__get_frame(), nsgif__parse_colour_table(), nsgif__parse_frame_extensions(), nsgif__parse_image_data(), nsgif__parse_image_descriptor(), NSGIF_ERR_END_OF_DATA, NSGIF_ERR_OOM, NSGIF_OK, NSGIF_TRAILER, and pos.
Referenced by nsgif_data_scan(), and nsgif_frame_decode().