FastLED: fl::third_party::plm_video_decode_picture
plm_video_decode_picture()
void fl::third_party::plm_video_decode_picture (plm_video_t * self)
Definition at line 2382 of file pl_mpeg.hpp.
{
    plm_buffer_skip(self->buffer, 10); // skip temporalReference
    self->picture_type = plm_buffer_read(self->buffer, 3);
    plm_buffer_skip(self->buffer, 16); // skip vbv_delay
    // D frames or unknown coding type
    if (self->picture_type <= 0 || self->picture_type > PLM_VIDEO_PICTURE_TYPE_B) {
        return;
    }
    // Forward full_px, f_code
    if (
        self->picture_type == PLM_VIDEO_PICTURE_TYPE_PREDICTIVE ||
        self->picture_type == PLM_VIDEO_PICTURE_TYPE_B
    ) {
        self->motion_forward.full_px = plm_buffer_read(self->buffer, 1);
        int f_code = plm_buffer_read(self->buffer, 3);
        if (f_code == 0) {
            // Ignore picture with zero f_code
            return;
        }
        self->motion_forward.r_size = f_code - 1;
    }
    // Backward full_px, f_code
    if (self->picture_type == PLM_VIDEO_PICTURE_TYPE_B) {
        self->motion_backward.full_px = plm_buffer_read(self->buffer, 1);
        int f_code = plm_buffer_read(self->buffer, 3);
        if (f_code == 0) {
            // Ignore picture with zero f_code
            return;
        }
        self->motion_backward.r_size = f_code - 1;
    }
    plm_frame_t frame_temp = self->frame_forward;
    if (
        self->picture_type == PLM_VIDEO_PICTURE_TYPE_INTRA ||
        self->picture_type == PLM_VIDEO_PICTURE_TYPE_PREDICTIVE
    ) {
        self->frame_forward = self->frame_backward;
    }
    // Find first slice start code; skip extension and user data
    do {
        self->start_code = plm_buffer_next_start_code(self->buffer);
    } while (
        self->start_code == PLM_START_EXTENSION ||
        self->start_code == PLM_START_USER_DATA
    );
    // Decode all slices
    while (PLM_START_IS_SLICE(self->start_code)) {
        plm_video_decode_slice(self, self->start_code & 0x000000FF);
        if (self->macroblock_address >= self->mb_size - 2) {
            break;
        }
        self->start_code = plm_buffer_next_start_code(self->buffer);
    }
    // If this is a reference picture rotate the prediction pointers
    if (
        self->picture_type == PLM_VIDEO_PICTURE_TYPE_INTRA ||
        self->picture_type == PLM_VIDEO_PICTURE_TYPE_PREDICTIVE
    ) {
        self->frame_backward = self->frame_current;
        self->frame_current = frame_temp;
    }
}
References FL_NOEXCEPT, plm_buffer_next_start_code(), plm_buffer_read(), plm_buffer_skip(), PLM_START_EXTENSION, PLM_START_IS_SLICE, PLM_START_USER_DATA, plm_video_decode_slice(), PLM_VIDEO_PICTURE_TYPE_B, PLM_VIDEO_PICTURE_TYPE_INTRA, and PLM_VIDEO_PICTURE_TYPE_PREDICTIVE.
Referenced by plm_video_decode().