FastLED: fl::third_party::plm_video_create_with_buffer
plm_video_create_with_buffer()
plm_video_t * fl::third_party::plm_video_create_with_buffer (plm_buffer_t * buffer, int destroy_when_done)
Definition at line 2121 of file pl_mpeg.hpp.
{
    plm_video_t *self = (plm_video_t *)PLM_MALLOC(sizeof(plm_video_t));
    fl::memset(self, 0, sizeof(plm_video_t));
    self->buffer = buffer;
    self->destroy_buffer_when_done = destroy_when_done;
    // Attempt to decode the sequence header
    self->start_code = plm_buffer_find_start_code(self->buffer, PLM_START_SEQUENCE);
    if (self->start_code != -1) {
        plm_video_decode_sequence_header(self);
    }
    return self;
}
References fl::third_party::plm_video_t::buffer, fl::third_party::plm_video_t::destroy_buffer_when_done, FL_NOEXCEPT, fl::memset(), plm_buffer_find_start_code(), PLM_MALLOC, PLM_START_SEQUENCE, plm_video_decode_sequence_header(), and fl::third_party::plm_video_t::start_code.
Referenced by plm_init_decoders().