FastLED: fl::third_party::Dequantize
Dequantize()
int fl::third_party::Dequantize (MP3DecInfo * mp3DecInfo, int gr)
Definition at line 78 of file dequant.hpp.
{
    int i, ch, nSamps;
    int32_t mOut[2];
    FrameHeader *fh;
    SideInfo *si;
    ScaleFactorInfo *sfi;
    HuffmanInfo *hi;
    DequantInfo *di;
    CriticalBandInfo *cbi;
    /* validate pointers */
    if (!mp3DecInfo || !mp3DecInfo->FrameHeaderPS || !mp3DecInfo->SideInfoPS || !mp3DecInfo->ScaleFactorInfoPS ||
        !mp3DecInfo->HuffmanInfoPS || !mp3DecInfo->DequantInfoPS)
        return -1;
    fh = (FrameHeader *)(mp3DecInfo->FrameHeaderPS);
    /* si is an array of up to 4 structs, stored as gr0ch0, gr0ch1, gr1ch0, gr1ch1 */
    si = (SideInfo *)(mp3DecInfo->SideInfoPS);
    sfi = (ScaleFactorInfo *)(mp3DecInfo->ScaleFactorInfoPS);
    hi = (HuffmanInfo *)mp3DecInfo->HuffmanInfoPS;
    di = (DequantInfo *)mp3DecInfo->DequantInfoPS;
    cbi = di->cbi;
    mOut[0] = mOut[1] = 0;
    /* dequantize all the samples in each channel */
    for (ch = 0; ch < mp3DecInfo->nChans; ch++) {
        hi->gb[ch] = DequantChannel(hi->huffDecBuf[ch], di->workBuf, &hi->nonZeroBound[ch], fh,
            &si->sis[gr][ch], &sfi->sfis[gr][ch], &cbi[ch]);
    }
    /* joint stereo processing assumes one guard bit in input samples
     * it's extremely rare not to have at least one gb, so if this is the case
     *   just make a pass over the data and clip to [-2^30+1, 2^30-1]
     * in practice this may never happen
     */
    if (fh->modeExt && (hi->gb[0] < 1 || hi->gb[1] < 1)) {
        /* Clip to range [-2^30+1, 2^30-1] */
        const int32_t max_clip = (int32_t)0x3FFFFFFFL;  /* 2^30 - 1 */
        const int32_t min_clip = (int32_t)(-0x40000000L); /* -(2^30) */
        for (i = 0; i < hi->nonZeroBound[0]; i++) {
            if (hi->huffDecBuf[0][i] < min_clip)  hi->huffDecBuf[0][i] = min_clip;
            if (hi->huffDecBuf[0][i] > max_clip)  hi->huffDecBuf[0][i] = max_clip;
        }
        for (i = 0; i < hi->nonZeroBound[1]; i++) {
            if (hi->huffDecBuf[1][i] < min_clip)  hi->huffDecBuf[1][i] = min_clip;
            if (hi->huffDecBuf[1][i] > max_clip)  hi->huffDecBuf[1][i] = max_clip;
        }
    }
    /* do mid-side stereo processing, if enabled */
    if (fh->modeExt >> 1) {
        if (fh->modeExt & 0x01) {
            /* intensity stereo enabled - run mid-side up to start of right zero region */
            if (cbi[1].cbType == 0)
                nSamps = fh->sfBand->l[cbi[1].cbEndL + 1];
            else
                nSamps = 3 * fh->sfBand->s[cbi[1].cbEndSMax + 1];
        } else {
            /* intensity stereo disabled - run mid-side on whole spectrum */
            nSamps = MAX(hi->nonZeroBound[0], hi->nonZeroBound[1]);
        }
        MidSideProc(hi->huffDecBuf, nSamps, mOut);
    }
    /* do intensity stereo processing, if enabled */
    if (fh->modeExt & 0x01) {
        nSamps = hi->nonZeroBound[0];
        if (fh->ver == MPEG1) {
            IntensityProcMPEG1(hi->huffDecBuf, nSamps, fh, &sfi->sfis[gr][1], di->cbi,
                fh->modeExt >> 1, si->sis[gr][1].mixedBlock, mOut);
        } else {
            IntensityProcMPEG2(hi->huffDecBuf, nSamps, fh, &sfi->sfis[gr][1], di->cbi, &sfi->sfjs,
                fh->modeExt >> 1, si->sis[gr][1].mixedBlock, mOut);
        }
    }
    /* adjust guard bit count and nonZeroBound if we did any stereo processing */
    if (fh->modeExt) {
        hi->gb[0] = CLZ(mOut[0]) - 1;
        hi->gb[1] = CLZ(mOut[1]) - 1;
        nSamps = MAX(hi->nonZeroBound[0], hi->nonZeroBound[1]);
        hi->nonZeroBound[0] = nSamps;
        hi->nonZeroBound[1] = nSamps;
    }
    /* output format Q(DQ_FRACBITS_OUT) */
    return 0;
}
References fl::third_party::CriticalBandInfo::cbEndL, fl::third_party::CriticalBandInfo::cbEndSMax, fl::third_party::_DequantInfo::cbi, CLZ(), DequantChannel(), FL_NOEXCEPT, fl::third_party::_HuffmanInfo::gb, fl::third_party::_HuffmanInfo::huffDecBuf, IntensityProcMPEG1(), IntensityProcMPEG2(), fl::third_party::_SFBandTable::l, MAX, MidSideProc(), fl::third_party::_SideInfoSub::mixedBlock, fl::third_party::_FrameHeader::modeExt, MPEG1, fl::third_party::_HuffmanInfo::nonZeroBound, fl::third_party::_SFBandTable::s, fl::third_party::_FrameHeader::sfBand, fl::third_party::_ScaleFactorInfo::sfis, fl::third_party::_ScaleFactorInfo::sfjs, fl::third_party::_SideInfo::sis, fl::third_party::_FrameHeader::ver, and fl::third_party::_DequantInfo::workBuf.
Referenced by MP3Decode().