FastLED: fl::third_party::PolyphaseStereo
PolyphaseStereo()
void fl::third_party::PolyphaseStereo (short * pcm, int32_t * vbuf, const int32_t * coefBase)
Definition at line 243 of file polyphase.hpp.
{
    int i;
    const int32_t *coef;
    int32_t *vb1;
    int vLo, vHi, c1, c2;
    Word64 sum1L, sum2L, sum1R, sum2R, rndVal;
    rndVal = (Word64)( (i64)1 << (DEF_NFRACBITS - 1 + (32 - CSHIFT)) );
    /* special case, output sample 0 */
    coef = coefBase;
    vb1 = vbuf;
    sum1L = sum1R = rndVal;
    MC0S(0)
    MC0S(1)
    MC0S(2)
    MC0S(3)
    MC0S(4)
    MC0S(5)
    MC0S(6)
    MC0S(7)
    *(pcm + 0) = ClipToShort((int)SAR64(sum1L, (32-CSHIFT)), DEF_NFRACBITS);
    *(pcm + 1) = ClipToShort((int)SAR64(sum1R, (32-CSHIFT)), DEF_NFRACBITS);
    /* special case, output sample 16 */
    coef = coefBase + 256;
    vb1 = vbuf + 64*16;
    sum1L = sum1R = rndVal;
    MC1S(0)
    MC1S(1)
    MC1S(2)
    MC1S(3)
    MC1S(4)
    MC1S(5)
    MC1S(6)
    MC1S(7)
    *(pcm + 2*16 + 0) = ClipToShort((int)SAR64(sum1L, (32-CSHIFT)), DEF_NFRACBITS);
    *(pcm + 2*16 + 1) = ClipToShort((int)SAR64(sum1R, (32-CSHIFT)), DEF_NFRACBITS);
    /* main convolution loop: sum1L = samples 1, 2, 3, ... 15   sum2L = samples 31, 30, ... 17 */
    coef = coefBase + 16;
    vb1 = vbuf + 64;
    pcm += 2;
    /* right now, the compiler creates bad asm from this... */
    for (i = 15; i > 0; i--) {
        sum1L = sum2L = rndVal;
        sum1R = sum2R = rndVal;
        MC2S(0)
        MC2S(1)
        MC2S(2)
        MC2S(3)
        MC2S(4)
        MC2S(5)
        MC2S(6)
        MC2S(7)
        vb1 += 64;
        *(pcm + 0)         = ClipToShort((int)SAR64(sum1L, (32-CSHIFT)), DEF_NFRACBITS);
        *(pcm + 1)         = ClipToShort((int)SAR64(sum1R, (32-CSHIFT)), DEF_NFRACBITS);
        *(pcm + 2*2*i + 0) = ClipToShort((int)SAR64(sum2L, (32-CSHIFT)), DEF_NFRACBITS);
        *(pcm + 2*2*i + 1) = ClipToShort((int)SAR64(sum2R, (32-CSHIFT)), DEF_NFRACBITS);
        pcm += 2;
    }
}
References ClipToShort(), CSHIFT, DEF_NFRACBITS, FL_NOEXCEPT, MC0S, MC1S, MC2S, and SAR64().
Referenced by Subband().