FastLED: fl::third_party::plm_destroy
plm_destroy()
void fl::third_party::plm_destroy (plm_t * self)
Definition at line 296 of file pl_mpeg.hpp.
{
    if (self->video_decoder) {
        plm_video_destroy(self->video_decoder);
    }
    if (self->audio_decoder) {
        plm_audio_destroy(self->audio_decoder);
    }
    plm_demux_destroy(self->demux);
    PLM_FREE(self);
}
References FL_NOEXCEPT, plm_audio_destroy(), plm_demux_destroy(), PLM_FREE, and plm_video_destroy().
Referenced by fl::third_party::SoftwareMpeg1Decoder::cleanupDecoder().