FastLED: fl::third_party::nsgif_create
nsgif_create()
nsgif_error fl::third_party::nsgif_create (const nsgif_bitmap_cb_vt * bitmap_vt, nsgif_bitmap_fmt_t bitmap_fmt, nsgif_t ** gif_out)
Create the NSGIF object.
Parameters
[in] bitmap_vt Bitmap operation functions v-table.
[in] bitmap_fmt Bitmap pixel format specification.
[out] gif_out Return nsgif_t object on success.
Returns
NSGIF_OK on success, or appropriate error otherwise.
Definition at line 1493 of file gif.cpp.hpp.
{
    nsgif_t *gif;
    gif = static_cast<nsgif_t*>(fl::Malloc(sizeof(*gif)));
    if (gif) {
        fl::memset(gif, 0, sizeof(*gif));
    }
    if (gif == nullptr) {
        return NSGIF_ERR_OOM;
    }
    gif->bitmap = *bitmap_vt;
    gif->decoded_frame = NSGIF_FRAME_INVALID;
    gif->prev_index = NSGIF_FRAME_INVALID;
    gif->delay_min = NSGIF_FRAME_DELAY_MIN;
    gif->delay_default = NSGIF_FRAME_DELAY_DEFAULT;
    gif->colour_layout = nsgif__bitmap_fmt_to_colour_layout(bitmap_fmt);
    *gif_out = gif;
    return NSGIF_OK;
}
References fl::third_party::nsgif::bitmap, fl::third_party::nsgif::colour_layout, fl::third_party::nsgif::decoded_frame, fl::third_party::nsgif::delay_default, fl::third_party::nsgif::delay_min, FL_NOEXCEPT, fl::Malloc(), fl::memset(), nsgif__bitmap_fmt_to_colour_layout(), NSGIF_ERR_OOM, NSGIF_FRAME_DELAY_DEFAULT, NSGIF_FRAME_DELAY_MIN, NSGIF_FRAME_INVALID, NSGIF_OK, and fl::third_party::nsgif::prev_index.
Referenced by fl::third_party::SoftwareGifDecoder::initializeDecoder().