FastLED: fl::third_party::nsgif__colour_table_extract
nsgif__colour_table_extract()
static nsgif_error fl::third_party::nsgif__colour_table_extract (fl::u32 colour_table[NSGIF_MAX_COLOURS], const struct nsgif_colour_layout * layout, fl::size colour_table_entries, const fl::u8 * data, fl::size data_len, fl::size * used, bool decode) inline static
Extract a GIF colour table into a LibNSGIF colour table buffer.
Parameters
[in] colour_table The colour table to populate.
[in] layout The target pixel format to decode to.
[in] colour_table_entries The number of colour table entries.
[in] data Current position in data.
[in] data_len The available length of data.
[out] used Number of colour table bytes read.
[in] decode Whether to decode the colour table.
Returns
NSGIF_OK on success, appropriate error otherwise.
Definition at line 1115 of file gif.cpp.hpp.
{
    if (data_len < colour_table_entries * 3) {
        return NSGIF_ERR_END_OF_DATA;
    }
    if (decode) {
        nsgif__colour_table_decode(colour_table, layout,
                colour_table_entries, data);
    }
    *used = colour_table_entries * 3;
    return NSGIF_OK;
}
References FL_NOEXCEPT, nsgif__colour_table_decode(), NSGIF_ERR_END_OF_DATA, NSGIF_MAX_COLOURS, and NSGIF_OK.
Referenced by nsgif__parse_colour_table(), and nsgif_data_scan().