FastLED: fl::third_party::plm_video_predict_macroblock
plm_video_predict_macroblock()
void fl::third_party::plm_video_predict_macroblock (plm_video_t * self)
Definition at line 2628 of file pl_mpeg.hpp.
{
    int fw_h = self->motion_forward.h;
    int fw_v = self->motion_forward.v;
    if (self->motion_forward.full_px) {
        fw_h <<= 1;
        fw_v <<= 1;
    }
    if (self->picture_type == PLM_VIDEO_PICTURE_TYPE_B) {
        int bw_h = self->motion_backward.h;
        int bw_v = self->motion_backward.v;
        if (self->motion_backward.full_px) {
            bw_h <<= 1;
            bw_v <<= 1;
        }
        if (self->motion_forward.is_set) {
            plm_video_copy_macroblock(self, &self->frame_forward, fw_h, fw_v);
            if (self->motion_backward.is_set) {
                plm_video_interpolate_macroblock(self, &self->frame_backward, bw_h, bw_v);
            }
        }
        else {
            plm_video_copy_macroblock(self, &self->frame_backward, bw_h, bw_v);
        }
    }
    else {
        plm_video_copy_macroblock(self, &self->frame_forward, fw_h, fw_v);
    }
}
References FL_NOEXCEPT, plm_video_copy_macroblock(), plm_video_interpolate_macroblock(), and PLM_VIDEO_PICTURE_TYPE_B.
Referenced by plm_video_decode_macroblock().