FastLED: fl::third_party::lzw_decode_map
lzw_decode_map()
lzw_result fl::third_party::lzw_decode_map (struct lzw_ctx * ctx, fl::u32 * output_data, fl::u32 output_length, fl::u32 * output_written)
Read LZW codes into client buffer, mapping output to colours.
The context must have been initialised using lzw_decode_init_map before calling this function, in order to provide the colour mapping table and any transparency index.
Ensure anything in output is used before calling this, as anything there before this call will be trampled.
Parameters
[in] ctx LZW reading context, updated.
[in] output_data Client buffer to fill with colour mapped values.
[in] output_length Size of output array.
[out] output_written Returns the number of values written to data.
Returns
LZW_OK on success, or appropriate error code otherwise.
Definition at line 591 of file lzw.cpp.hpp.
{
    *output_written = 0;
    if (ctx->colour_map == nullptr) {
        return LZW_NO_COLOUR;
    }
    if (ctx->output_left != 0) {
        *output_written += lzw__map_write_fn(ctx,
                output_data, output_length, *output_written,
                ctx->output_code, ctx->output_left);
    }
    while (*output_written != output_length) {
        lzw_result res = lzw__decode(ctx, lzw__map_write_fn,
                output_data, output_length, output_written);
        if (res != LZW_OK) {
            return res;
        }
    }
    return LZW_OK;
}
References fl::third_party::lzw_ctx::colour_map, FL_NOEXCEPT, lzw__decode(), lzw__map_write_fn(), LZW_NO_COLOUR, LZW_OK, fl::third_party::lzw_ctx::output_code, and fl::third_party::lzw_ctx::output_left.
Referenced by nsgif__decode_simple().