FastLED: fl::third_party::plm_demux_get_start_time
plm_demux_get_start_time()
double fl::third_party::plm_demux_get_start_time (plm_demux_t * self, int type)
Definition at line 1304 of file pl_mpeg.hpp.
{
    if (self->start_time != PLM_PACKET_INVALID_TS) {
        return self->start_time;
    }
    int previous_pos = plm_buffer_tell(self->buffer);
    int previous_start_code = self->start_code;
    // Find first video PTS
    plm_demux_rewind(self);
    do {
        plm_packet_t *packet = plm_demux_decode(self);
        if (!packet) {
            break;
        }
        if (packet->type == type) {
            self->start_time = packet->pts;
        }
    } while (self->start_time == PLM_PACKET_INVALID_TS);
    plm_demux_buffer_seek(self, previous_pos);
    self->start_code = previous_start_code;
    return self->start_time;
}
References FL_NOEXCEPT, plm_buffer_tell(), plm_demux_buffer_seek(), plm_demux_decode(), plm_demux_rewind(), PLM_PACKET_INVALID_TS, fl::third_party::plm_packet_t::pts, and fl::third_party::plm_packet_t::type.
Referenced by plm_demux_get_duration(), plm_seek(), and plm_seek_frame().