FastLED: fl::third_party::nsgif__decode
nsgif__decode()
static nsgif_error fl::third_party::nsgif__decode (struct nsgif * gif, struct nsgif_frame * frame, const fl::u8 * data, fl::u32 * frame_data) inline static
Definition at line 605 of file gif.cpp.hpp.
{
    nsgif_error ret;
    fl::u32 width  = frame->info.rect.x1 - frame->info.rect.x0;
    fl::u32 height = frame->info.rect.y1 - frame->info.rect.y0;
    fl::u32 offset_x = frame->info.rect.x0;
    fl::u32 offset_y = frame->info.rect.y0;
    fl::u32 transparency_index = frame->transparency_index;
    fl::u32 * colour_table = gif->colour_table;
    if (frame->info.interlaced == false && offset_x == 0 &&
            width == gif->info.width &&
            width == gif->rowspan) {
        ret = nsgif__decode_simple(gif, height, offset_y,
                data, transparency_index,
                frame_data, colour_table);
    } else {
        ret = nsgif__decode_complex(gif, width, height,
                offset_x, offset_y, frame->info.interlaced,
                data, transparency_index,
                frame_data, colour_table);
    }
    if (gif->data_complete && ret == NSGIF_ERR_END_OF_DATA) {
        /* This is all the data there is, so make do. */
        ret = NSGIF_OK;
    }
    return ret;
}
References FL_NOEXCEPT, fl::height, nsgif__decode_complex(), nsgif__decode_simple(), NSGIF_ERR_END_OF_DATA, NSGIF_OK, and fl::width.
Referenced by nsgif__update_bitmap().