FastLED: fl::third_party::plm_decode_video
plm_decode_video()
plm_frame_t * fl::third_party::plm_decode_video (plm_t * self)
Definition at line 533 of file pl_mpeg.hpp.
{
    if (!plm_init_decoders(self)) {
        return NULL;
    }
    if (!self->video_packet_type) {
        return NULL;
    }
    plm_frame_t *frame = plm_video_decode(self->video_decoder);
    if (frame) {
        self->time = frame->time;
    }
    else if (plm_demux_has_ended(self->demux)) {
        plm_handle_end(self);
    }
    return frame;
}
References FL_NOEXCEPT, NULL, plm_demux_has_ended(), plm_handle_end(), plm_init_decoders(), plm_video_decode(), and fl::third_party::plm_frame_t::time.