FastLED: fl::third_party::PolyphaseMono
PolyphaseMono()
void fl::third_party::PolyphaseMono (short * pcm, int32_t * vbuf, const int32_t * coefBase)
Definition at line 130 of file polyphase.hpp.
{
    int i;
    const int32_t *coef;
    int32_t *vb1;
    int vLo, vHi, c1, c2;
    Word64 sum1L, sum2L, rndVal;
    rndVal = (Word64)( (i64)1 << (DEF_NFRACBITS - 1 + (32 - CSHIFT)) );
    /* special case, output sample 0 */
    coef = coefBase;
    vb1 = vbuf;
    sum1L = rndVal;
    MC0M(0)
    MC0M(1)
    MC0M(2)
    MC0M(3)
    MC0M(4)
    MC0M(5)
    MC0M(6)
    MC0M(7)
    *(pcm + 0) = ClipToShort((int)SAR64(sum1L, (32-CSHIFT)), DEF_NFRACBITS);
    /* special case, output sample 16 */
    coef = coefBase + 256;
    vb1 = vbuf + 64*16;
    sum1L = rndVal;
    MC1M(0)
    MC1M(1)
    MC1M(2)
    MC1M(3)
    MC1M(4)
    MC1M(5)
    MC1M(6)
    MC1M(7)
    *(pcm + 16) = ClipToShort((int)SAR64(sum1L, (32-CSHIFT)), DEF_NFRACBITS);
    /* main convolution loop: sum1L = samples 1, 2, 3, ... 15   sum2L = samples 31, 30, ... 17 */
    coef = coefBase + 16;
    vb1 = vbuf + 64;
    pcm++;
    /* right now, the compiler creates bad asm from this... */
    for (i = 15; i > 0; i--) {
        sum1L = sum2L = rndVal;
        MC2M(0)
        MC2M(1)
        MC2M(2)
        MC2M(3)
        MC2M(4)
        MC2M(5)
        MC2M(6)
        MC2M(7)
        vb1 += 64;
        *(pcm)       = ClipToShort((int)SAR64(sum1L, (32-CSHIFT)), DEF_NFRACBITS);
        *(pcm + 2*i) = ClipToShort((int)SAR64(sum2L, (32-CSHIFT)), DEF_NFRACBITS);
        pcm++;
    }
}
References ClipToShort(), CSHIFT, DEF_NFRACBITS, FL_NOEXCEPT, MC0M, MC1M, MC2M, and SAR64().
Referenced by Subband().