FastLED: fl::third_party::nsgif_destroy
nsgif_destroy()
void fl::third_party::nsgif_destroy (nsgif_t * gif)
Free a NSGIF object.
Parameters
[in] gif The NSGIF to free.
Definition at line 1395 of file gif.cpp.hpp.
{
    if (gif == nullptr) {
        return;
    }
    /* Release all our memory blocks */
    if (gif->frame_image) {
        FL_ASSERT(gif->bitmap.destroy, "GIF bitmap destroy function required");
        gif->bitmap.destroy(gif->frame_image);
        gif->frame_image = nullptr;
    }
    fl::Free(gif->frames);
    gif->frames = nullptr;
    fl::Free(gif->prev_frame);
    gif->prev_frame = nullptr;
    lzw_context_destroy(static_cast<struct lzw_ctx*>(gif->lzw_ctx));
    gif->lzw_ctx = nullptr;
    fl::Free(gif);
}
References FL_ASSERT, FL_NOEXCEPT, fl::Free(), and lzw_context_destroy().
Referenced by fl::third_party::SoftwareGifDecoder::cleanupDecoder().