FastLED: fl::third_party::nsgif__restore_bg
nsgif__restore_bg()
static void fl::third_party::nsgif__restore_bg (struct nsgif * gif, struct nsgif_frame * frame, fl::u32 * bitmap) static
Restore a GIF to the background colour.
Parameters
[in] gif The gif object we're decoding.
[in] frame The frame to clear, or NULL.
[in] bitmap The bitmap to clear the frame in.
Definition at line 647 of file gif.cpp.hpp.
{
    fl::size pixel_bytes = sizeof(*bitmap);
    if (frame == nullptr) {
        fl::size width  = gif->info.width;
        fl::size height = gif->info.height;
        fl::memset(bitmap, NSGIF_TRANSPARENT_COLOUR,
                width * height * pixel_bytes);
    } else {
        fl::u32 width  = frame->info.rect.x1 - frame->info.rect.x0;
        fl::u32 height = frame->info.rect.y1 - frame->info.rect.y0;
        fl::u32 offset_x = frame->info.rect.x0;
        fl::u32 offset_y = frame->info.rect.y0;
        if (frame->info.display == false ||
            frame->info.rect.x0 >= gif->info.width ||
            frame->info.rect.y0 >= gif->info.height) {
            return;
        }
        width -= gif__clip(offset_x, width, gif->info.width);
        height -= gif__clip(offset_y, height, gif->info.height);
        if (frame->info.transparency) {
            for (fl::u32 y = 0; y < height; y++) {
                fl::u32 *scanline = bitmap + offset_x +
                        (offset_y + y) * gif->info.width;
                fl::memset(scanline, NSGIF_TRANSPARENT_COLOUR,
                        width * pixel_bytes);
            }
        } else {
            for (fl::u32 y = 0; y < height; y++) {
                fl::u32 *scanline = bitmap + offset_x +
                        (offset_y + y) * gif->info.width;
                for (fl::u32 x = 0; x < width; x++) {
                    scanline[x] = gif->info.background;
                }
            }
        }
    }
}
References FL_NOEXCEPT, gif__clip(), fl::height, fl::memset(), NSGIF_TRANSPARENT_COLOUR, fl::width, fl::x, and fl::y.
Referenced by nsgif__update_bitmap().