FastLED: fl::third_party::nsgif__error_from_lzw
nsgif__error_from_lzw()
static nsgif_error fl::third_party::nsgif__error_from_lzw (lzw_result l_res) static
Convert an LZW result code to equivalent GIF result code.
Parameters
[in] l_res LZW response code.
Returns
GIF result code.
Definition at line 182 of file gif.cpp.hpp.
{
    static const nsgif_error g_res[] = {
        NSGIF_OK,                 /* LZW_OK */
        NSGIF_ERR_END_OF_DATA,    /* LZW_OK_EOD */
        NSGIF_ERR_OOM,            /* LZW_NO_MEM */
        NSGIF_ERR_END_OF_DATA,    /* LZW_NO_DATA */
        NSGIF_ERR_DATA_FRAME,     /* LZW_EOI_CODE */
        NSGIF_ERR_DATA_FRAME,     /* LZW_NO_COLOUR */
        NSGIF_ERR_DATA_FRAME,     /* LZW_BAD_ICODE */
        NSGIF_ERR_DATA_FRAME,     /* LZW_BAD_PARAM */
        NSGIF_ERR_DATA_FRAME,     /* LZW_BAD_CODE */
    };
    FL_ASSERT(l_res != LZW_BAD_PARAM, "LZW bad parameter");
    FL_ASSERT(l_res != LZW_NO_COLOUR, "LZW no colour");
    return g_res[l_res];
}
References FL_ASSERT, FL_NOEXCEPT, LZW_BAD_PARAM, LZW_NO_COLOUR, NSGIF_ERR_DATA_FRAME, NSGIF_ERR_END_OF_DATA, NSGIF_ERR_OOM, and NSGIF_OK.
Referenced by nsgif__decode_complex(), nsgif__decode_simple(), and nsgif_data_scan().