FastLED: fl::third_party::lzw_decode_init
lzw_decode_init()
lzw_result fl::third_party::lzw_decode_init (struct lzw_ctx * ctx, fl::u8 minimum_code_size, const fl::u8 * input_data, fl::size input_length, fl::size input_pos)
Initialise an LZW decompression context for decoding.
Parameters
[in] ctx The LZW decompression context to initialise.
[in] minimum_code_size The LZW Minimum Code Size.
[in] input_data The compressed data.
[in] input_length Byte length of compressed data.
[in] input_pos Start position in data. Must be position of a size byte at sub-block start.
Returns
LZW_OK on success, or appropriate error code otherwise.
Definition at line 263 of file lzw.cpp.hpp.
{
    struct lzw_table_entry *table = ctx->table;
    lzw_result res;
    fl::u16 code;
    if (minimum_code_size >= LZW_CODE_MAX) {
        return LZW_BAD_ICODE;
    }
    /* Initialise the input reading context */
    ctx->input.data = input_data;
    ctx->input.data_len = input_length;
    ctx->input.data_sb_next = input_pos;
    ctx->input.sb_bit = 0;
    ctx->input.sb_bit_count = 0;
    /* Initialise the table building context */
    ctx->initial_code_size = minimum_code_size + 1;
    ctx->clear_code = (1 << minimum_code_size) + 0;
    ctx->eoi_code   = (1 << minimum_code_size) + 1;
    ctx->output_left = 0;
    /* Initialise the standard table entries */
    for (fl::u16 i = 0; i < ctx->clear_code; i++) {
        table[i].first = i;
        table[i].value = i;
        table[i].count = 1;
    }
    res = lzw__handle_clear(ctx, &code);
    if (res != LZW_OK) {
        return res;
    }
    /* Store details of this code as "previous code" to the context. */
    ctx->prev_code_first = ctx->table[code].first;
    ctx->prev_code_count = ctx->table[code].count;
    ctx->prev_code = code;
    /* Add code to context for immediate output. */
    ctx->output_code = code;
    ctx->output_left = 1;
    ctx->has_transparency = false;
    ctx->transparency_idx = 0;
    ctx->colour_map = nullptr;
    return LZW_OK;
}
References fl::third_party::lzw_table_entry::count, fl::third_party::lzw_table_entry::first, FL_NOEXCEPT, lzw__handle_clear(), LZW_BAD_ICODE, LZW_CODE_MAX, LZW_OK, and fl::third_party::lzw_table_entry::value.
Referenced by lzw_decode_init_map(), and nsgif__decode_complex().