FastLED: fl::third_party::GetBits
GetBits()
uint32_t fl::third_party::GetBits (BitStreamInfo * bsi, int32_t nBits)
Definition at line 134 of file bitstream.hpp.
{
    uint32_t data, lowBits;
    nBits &= 0x1f;                          /* nBits mod 32 to avoid unpredictable results like >> by negative amount */
    data = bsi->iCache >> (31 - nBits);       /* unsigned >> so zero-extend */
    data >>= 1;                             /* do as >> 31, >> 1 so that nBits = 0 works okay (returns 0) */
    bsi->iCache <<= nBits;                    /* left-justify cache */
    bsi->cachedBits -= nBits;             /* how many bits have we drawn from the cache so far */
    /* if we cross an int boundary, refill the cache */
    if (bsi->cachedBits < 0) {
        lowBits = -bsi->cachedBits;
        RefillBitstreamCache(bsi);
        data |= bsi->iCache >> (32 - lowBits);        /* get the low-order bits */
        bsi->cachedBits -= lowBits;           /* how many bits have we drawn from the cache so far */
        bsi->iCache <<= lowBits;          /* left-justify cache */
    }
    return data;
}
References FL_NOEXCEPT, and RefillBitstreamCache().
Referenced by UnpackScaleFactors(), UnpackSFMPEG1(), UnpackSFMPEG2(), and UnpackSideInfo().