FastLED: fl::third_party::nsgif_frame_decode
nsgif_frame_decode()
nsgif_error fl::third_party::nsgif_frame_decode (nsgif_t * gif, fl::u32 frame, nsgif_bitmap_t ** bitmap)
Decodes a GIF frame.
Parameters
[in] gif The nsgif_t object.
[in] frame The frame number to decode.
[out] bitmap On success, returns pointer to the client-allocated, nsgif-owned client bitmap structure.
Returns
NSGIF_OK on success, or appropriate error otherwise.
Definition at line 1953 of file gif.cpp.hpp.
{
    fl::u32 start_frame;
    nsgif_error ret = NSGIF_OK;
    if (frame >= gif->info.frame_count) {
        return NSGIF_ERR_BAD_FRAME;
    }
    if (gif->decoded_frame == frame) {
        *bitmap = gif->frame_image;
        return NSGIF_OK;
    } else if (gif->decoded_frame >= frame ||
               gif->decoded_frame == NSGIF_FRAME_INVALID) {
        /* Can skip to first frame or restart. */
        start_frame = 0;
    } else {
        start_frame = nsgif__frame_next(
                gif, false, gif->decoded_frame);
    }
    for (fl::u32 f = start_frame; f <= frame; f++) {
        ret = nsgif__process_frame(gif, f, true);
        if (ret != NSGIF_OK) {
            return ret;
        }
    }
    *bitmap = gif->frame_image;
    return ret;
}
References FL_NOEXCEPT, nsgif__frame_next(), nsgif__process_frame(), NSGIF_ERR_BAD_FRAME, NSGIF_FRAME_INVALID, and NSGIF_OK.
Referenced by fl::third_party::SoftwareGifDecoder::decode().