FastLED: fl::third_party::plm_buffer_write
plm_buffer_write()
size_t fl::third_party::plm_buffer_write (plm_buffer_t * self, uint8_t * bytes, size_t length)
Definition at line 877 of file pl_mpeg.hpp.
{
    if (self->mode == PLM_BUFFER_MODE_FIXED_MEM) {
        return 0;
    }
    if (self->discard_read_bytes) {
        // This should be a ring buffer, but instead it just shifts all unread
        // data to the beginning of the buffer and appends new data at the end.
        // Seems to be good enough.
        plm_buffer_discard_read_bytes(self);
        if (self->mode == PLM_BUFFER_MODE_RING) {
            self->total_size = 0;
        }
    }
    // Do we have to resize to fit the new data?
    size_t bytes_available = self->capacity - self->length;
    if (bytes_available < length) {
        size_t new_size = self->capacity;
        do {
            new_size *= 2;
        } while (new_size - self->length < length);
        self->bytes = (uint8_t *)PLM_REALLOC(self->bytes, new_size);
        self->capacity = new_size;
    }
    fl::memcopy(self->bytes + self->length, bytes, length);
    self->length += length;
    self->has_ended = FALSE;
    return length;
}
References FALSE, FL_NOEXCEPT, length(), fl::memcopy(), plm_buffer_discard_read_bytes(), PLM_BUFFER_MODE_FIXED_MEM, PLM_BUFFER_MODE_RING, and PLM_REALLOC.
Referenced by plm_read_packets(), plm_seek(), and plm_seek_frame().