FastLED: fl::third_party::nsgif_frame_prepare
nsgif_frame_prepare()
nsgif_error fl::third_party::nsgif_frame_prepare (nsgif_t * gif, nsgif_rect_t * area, fl::u32 * delay_cs, fl::u32 * frame_new)
Prepare to show a frame.
If this is the last frame of an animation with a finite loop count, the returned delay_cs will be NSGIF_INFINITE, indicating that the frame should be shown forever.
Note that if nsgif_data_complete has not been called on this gif, animated GIFs will not loop back to the start. Instead it will return NSGIF_ERR_END_OF_DATA.
Parameters
[in] gif The nsgif_t object.
[out] area The area in pixels that must be redrawn.
[out] delay_cs Time to wait after frame_new before next frame in cs.
[out] frame_new The frame to decode.
Returns
NSGIF_OK on success, or appropriate error otherwise.
Definition at line 1882 of file gif.cpp.hpp.
{
    nsgif_error ret;
    nsgif_rect_t rect = {0, 0, 0, 0};
    fl::u32 delay = 0;
    fl::u32 frame = gif->frame;
    if (gif->frame != NSGIF_FRAME_INVALID &&
        gif->frame < gif->info.frame_count &&
        gif->frames[gif->frame].info.display) {
        rect = gif->frames[gif->frame].info.rect;
    }
    if (nsgif__animation_complete(
            gif->loop_count,
            gif->info.loop_max)) {
        return NSGIF_ERR_ANIMATION_END;
    }
    ret = nsgif__next_displayable_frame(gif, &frame, &delay);
    if (ret != NSGIF_OK) {
        return ret;
    }
    if (gif->frame != NSGIF_FRAME_INVALID && frame < gif->frame) {
        gif->loop_count++;
    }
    if (gif->data_complete) {
        /* Check for last frame, which has infinite delay. */
        if (gif->info.frame_count == 1) {
            delay = NSGIF_INFINITE;
        } else if (gif->info.loop_max != 0) {
            fl::u32 frame_next = frame;
            ret = nsgif__next_displayable_frame(gif,
                    &frame_next, nullptr);
            if (ret != NSGIF_OK) {
                return ret;
            }
            if (gif->data_complete && frame_next < frame) {
                if (nsgif__animation_complete(
                        gif->loop_count + 1,
                        gif->info.loop_max)) {
                    delay = NSGIF_INFINITE;
                }
            }
        }
    }
    gif->frame = frame;
    nsgif__redraw_rect_extend(&gif->frames[frame].info.rect, &rect);
    if (delay < gif->delay_min) {
        delay = gif->delay_default;
    }
    *frame_new = gif->frame;
    *delay_cs = delay;
    *area = rect;
    return NSGIF_OK;
}
References fl::rect< T >::rect(), fl::delay(), FL_NOEXCEPT, nsgif__animation_complete(), nsgif__next_displayable_frame(), nsgif__redraw_rect_extend(), NSGIF_ERR_ANIMATION_END, NSGIF_FRAME_INVALID, NSGIF_INFINITE, and NSGIF_OK.