FastLED: fl::third_party::nsgif__decode_simple
nsgif__decode_simple()
static nsgif_error fl::third_party::nsgif__decode_simple (struct nsgif * gif, fl::u32 height, fl::u32 offset_y, const fl::u8 * data, fl::u32 transparency_index, fl::u32 * frame_data, fl::u32 * colour_table) static
Definition at line 546 of file gif.cpp.hpp.
{
    fl::u32 pixels;
    fl::u32 written = 0;
    nsgif_error ret = NSGIF_OK;
    lzw_result res;
    if (offset_y >= gif->info.height) {
        return NSGIF_OK;
    }
    height -= gif__clip(offset_y, height, gif->info.height);
    if (height == 0) {
        return NSGIF_OK;
    }
    /* Initialise the LZW decoding */
    res = lzw_decode_init_map(static_cast<struct lzw_ctx*>(gif->lzw_ctx), data[0],
            transparency_index, colour_table,
            gif->buf, gif->buf_len,
            data + 1 - gif->buf);
    if (res != LZW_OK) {
        return nsgif__error_from_lzw(res);
    }
    frame_data += (offset_y * gif->info.width);
    pixels = gif->info.width * height;
    while (pixels > 0) {
        res = lzw_decode_map(static_cast<struct lzw_ctx*>(gif->lzw_ctx),
                frame_data, pixels, &written);
        pixels -= written;
        frame_data += written;
        if (res != LZW_OK) {
            /* Unexpected end of frame, try to recover */
            if (res == LZW_OK_EOD || res == LZW_EOI_CODE) {
                ret = NSGIF_OK;
            } else {
                ret = nsgif__error_from_lzw(res);
            }
            break;
        }
    }
    if (pixels == 0) {
        ret = NSGIF_OK;
    }
    return ret;
}
References FL_NOEXCEPT, gif__clip(), fl::height, lzw_decode_init_map(), lzw_decode_map(), LZW_EOI_CODE, LZW_OK, LZW_OK_EOD, nsgif__error_from_lzw(), and NSGIF_OK.
Referenced by nsgif__decode().