FastLED: fl::third_party::plm_create_with_memory
plm_create_with_memory()
plm_t * fl::third_party::plm_create_with_memory (uint8_t * bytes, size_t length, int free_when_done)
Definition at line 244 of file pl_mpeg.hpp.
{
    plm_buffer_t *buffer = plm_buffer_create_with_memory(bytes, length, free_when_done);
    return plm_create_with_buffer(buffer, TRUE);
}
References FL_NOEXCEPT, length(), plm_buffer_create_with_memory(), plm_create_with_buffer(), and TRUE.
Referenced by fl::third_party::SoftwareMpeg1Decoder::initializeDecoder().