FastLED: fl::third_party::plm_demux_has_headers
plm_demux_has_headers()
int fl::third_party::plm_demux_has_headers (plm_demux_t * self)
Definition at line 1181 of file pl_mpeg.hpp.
{
    if (self->has_headers) {
        return TRUE;
    }
    // Decode pack header
    if (!self->has_pack_header) {
        if (
            self->start_code != PLM_START_PACK &&
            plm_buffer_find_start_code(self->buffer, PLM_START_PACK) == -1
        ) {
            return FALSE;
        }
        self->start_code = PLM_START_PACK;
        if (!plm_buffer_has(self->buffer, 64)) {
            return FALSE;
        }
        self->start_code = -1;
        if (plm_buffer_read(self->buffer, 4) != 0x02) {
            return FALSE;
        }
        self->system_clock_ref = plm_demux_decode_time(self);
        plm_buffer_skip(self->buffer, 1);
        plm_buffer_skip(self->buffer, 22); // mux_rate * 50
        plm_buffer_skip(self->buffer, 1);
        self->has_pack_header = TRUE;
    }
    // Decode system header
    if (!self->has_system_header) {
        if (
            self->start_code != PLM_START_SYSTEM &&
            plm_buffer_find_start_code(self->buffer, PLM_START_SYSTEM) == -1
        ) {
            return FALSE;
        }
        self->start_code = PLM_START_SYSTEM;
        if (!plm_buffer_has(self->buffer, 56)) {
            return FALSE;
        }
        self->start_code = -1;
        plm_buffer_skip(self->buffer, 16); // header_length
        plm_buffer_skip(self->buffer, 24); // rate bound
        self->num_audio_streams = plm_buffer_read(self->buffer, 6);
        plm_buffer_skip(self->buffer, 5); // misc flags
        self->num_video_streams = plm_buffer_read(self->buffer, 5);
        self->has_system_header = TRUE;
    }
    self->has_headers = TRUE;
    return TRUE;
}
References FALSE, FL_NOEXCEPT, plm_buffer_find_start_code(), plm_buffer_has(), plm_buffer_read(), plm_buffer_skip(), plm_demux_decode_time(), PLM_START_PACK, PLM_START_SYSTEM, and TRUE.
Referenced by plm_demux_create(), plm_demux_decode(), plm_demux_get_num_audio_streams(), plm_demux_get_num_video_streams(), plm_demux_seek(), plm_has_headers(), and plm_init_decoders().