FastLED: fl::third_party::UnpackScaleFactors
UnpackScaleFactors()
int fl::third_party::UnpackScaleFactors (MP3DecInfo * mp3DecInfo, const unsigned char * buf, int * bitOffset, int bitsAvail, int gr, int ch)
Definition at line 357 of file scalfact.hpp.
{
    int bitsUsed;
    const unsigned char *startBuf;
    BitStreamInfo bitStreamInfo, *bsi;
    FrameHeader *fh;
    SideInfo *si;
    ScaleFactorInfo *sfi;
    /* validate pointers */
    if (!mp3DecInfo || !mp3DecInfo->FrameHeaderPS || !mp3DecInfo->SideInfoPS || !mp3DecInfo->ScaleFactorInfoPS)
        return -1;
    fh = ((FrameHeader *)(mp3DecInfo->FrameHeaderPS));
    si = ((SideInfo *)(mp3DecInfo->SideInfoPS));
    sfi = ((ScaleFactorInfo *)(mp3DecInfo->ScaleFactorInfoPS));
    /* init GetBits reader */
    startBuf = buf;
    bsi = &bitStreamInfo;
    SetBitstreamPointer(bsi, (bitsAvail + *bitOffset + 7) / 8, buf);
    if (*bitOffset)
        GetBits(bsi, *bitOffset);
    if (fh->ver == MPEG1)
        UnpackSFMPEG1(bsi, &si->sis[gr][ch], &sfi->sfis[gr][ch], si->scfsi[ch], gr, &sfi->sfis[0][ch]);
    else
        UnpackSFMPEG2(bsi, &si->sis[gr][ch], &sfi->sfis[gr][ch], gr, ch, fh->modeExt, &sfi->sfjs);
    mp3DecInfo->part23Length[gr][ch] = si->sis[gr][ch].part23Length;
    bitsUsed = CalcBitsUsed(bsi, buf, *bitOffset);
    buf += (bitsUsed + *bitOffset) >> 3;
    *bitOffset = (bitsUsed + *bitOffset) & 0x07;
    return (buf - startBuf);
}
References CalcBitsUsed(), FL_NOEXCEPT, GetBits(), fl::third_party::_FrameHeader::modeExt, MPEG1, fl::third_party::_SideInfoSub::part23Length, fl::third_party::_SideInfo::scfsi, SetBitstreamPointer(), fl::third_party::_ScaleFactorInfo::sfis, fl::third_party::_ScaleFactorInfo::sfjs, fl::third_party::_SideInfo::sis, UnpackSFMPEG1(), UnpackSFMPEG2(), and fl::third_party::_FrameHeader::ver.
Referenced by MP3Decode().