FastLED: fl::third_party::nsgif__parse_frame_extensions
nsgif__parse_frame_extensions()
static nsgif_error fl::third_party::nsgif__parse_frame_extensions (struct nsgif * gif, struct nsgif_frame * frame, const fl::u8 ** pos, bool decode) static
Parse the frame's extensions.
Parameters
[in] gif The gif object we're decoding.
[in] frame The frame to parse extensions for.
[in] pos Current position in data, updated on exit.
[in] decode Whether to decode or skip over the extension.
Returns
NSGIF_ERR_END_OF_DATA if more data is needed, NSGIF_OK for success.
Definition at line 896 of file gif.cpp.hpp.
{
    enum {
        GIF_EXT_INTRODUCER      = 0x21,
        GIF_EXT_GRAPHIC_CONTROL = 0xf9,
        GIF_EXT_COMMENT         = 0xfe,
        GIF_EXT_PLAIN_TEXT      = 0x01,
        GIF_EXT_APPLICATION     = 0xff,
    };
    const fl::u8 *nsgif_data = *pos;
    const fl::u8 *nsgif_end = gif->buf + gif->buf_len;
    int nsgif_bytes = nsgif_end - nsgif_data;
    /* Initialise the extensions */
    while (nsgif_bytes > 0 && nsgif_data[0] == GIF_EXT_INTRODUCER) {
        bool block_step = true;
        nsgif_error ret;
        nsgif_data++;
        nsgif_bytes--;
        if (nsgif_bytes == 0) {
            return NSGIF_ERR_END_OF_DATA;
        }
        /* Switch on extension label */
        switch (nsgif_data[0]) {
        case GIF_EXT_GRAPHIC_CONTROL:
            if (decode) {
                ret = nsgif__parse_extension_graphic_control(
                        frame,
                        nsgif_data,
                        nsgif_bytes);
                if (ret != NSGIF_OK) {
                    return ret;
                }
            }
            break;
        case GIF_EXT_APPLICATION:
            if (decode) {
                ret = nsgif__parse_extension_application(
                        gif, nsgif_data, nsgif_bytes);
                if (ret != NSGIF_OK) {
                    return ret;
                }
            }
            break;
        case GIF_EXT_COMMENT:
            /* Move the pointer to the first data sub-block Skip 1
             * byte for the extension label. */
            ++nsgif_data;
            block_step = false;
            break;
        default:
            break;
        }
        if (block_step) {
            /* Move the pointer to the first data sub-block Skip 2
             * bytes for the extension label and size fields Skip
             * the extension size itself
             */
            if (nsgif_bytes < 2) {
                return NSGIF_ERR_END_OF_DATA;
            }
            nsgif_data += 2 + nsgif_data[1];
        }
        /* Repeatedly skip blocks until we get a zero block or run out
         * of data.  This data is ignored by this gif decoder. */
        while (nsgif_data < nsgif_end && nsgif_data[0] != NSGIF_BLOCK_TERMINATOR) {
            nsgif_data += nsgif_data[0] + 1;
            if (nsgif_data >= nsgif_end) {
                return NSGIF_ERR_END_OF_DATA;
            }
        }
        nsgif_data++;
        nsgif_bytes = nsgif_end - nsgif_data;
    }
    if (nsgif_data > nsgif_end) {
        nsgif_data = nsgif_end;
    }
    /* Set buffer position and return */
    *pos = nsgif_data;
    return NSGIF_OK;
}
References FL_NOEXCEPT, nsgif__parse_extension_application(), nsgif__parse_extension_graphic_control(), NSGIF_BLOCK_TERMINATOR, NSGIF_ERR_END_OF_DATA, NSGIF_OK, and pos.
Referenced by nsgif__process_frame().