FastLED: fl::third_party::plm_demux_get_packet
plm_demux_get_packet()
plm_packet_t * fl::third_party::plm_demux_get_packet (plm_demux_t * self)
Definition at line 1608 of file pl_mpeg.hpp.
{
    if (!plm_buffer_has(self->buffer, self->next_packet.length << 3)) {
        return NULL;
    }
    self->current_packet.data = self->buffer->bytes + (self->buffer->bit_index >> 3);
    self->current_packet.length = self->next_packet.length;
    self->current_packet.type = self->next_packet.type;
    self->current_packet.pts = self->next_packet.pts;
    self->next_packet.length = 0;
    return &self->current_packet;
}
References FL_NOEXCEPT, NULL, and plm_buffer_has().
Referenced by plm_demux_decode(), and plm_demux_decode_packet().