FastLED: fl::third_party::plm_video_decode_motion_vector
plm_video_decode_motion_vector()
int fl::third_party::plm_video_decode_motion_vector (plm_video_t * self, int r_size, int motion)
Definition at line 2600 of file pl_mpeg.hpp.
{
    int fscale = 1 << r_size;
    int m_code = plm_buffer_read_vlc(self->buffer, PLM_VIDEO_MOTION);
    int r = 0;
    int d;
    if ((m_code != 0) && (fscale != 1)) {
        r = plm_buffer_read(self->buffer, r_size);
        d = ((fl::abs(m_code) - 1) << r_size) + r + 1;
        if (m_code < 0) {
            d = -d;
        }
    }
    else {
        d = m_code;
    }
    motion += d;
    if (motion > (fscale << 4) - 1) {
        motion -= fscale << 5;
    }
    else if (motion < (int)((unsigned)(-fscale) << 4)) {
        motion += fscale << 5;
    }
    return motion;
}
References fl::abs(), FL_NOEXCEPT, plm_buffer_read(), plm_buffer_read_vlc(), and PLM_VIDEO_MOTION.
Referenced by plm_video_decode_motion_vectors().