FastLED: fl::Channel::Channel
Channel() [3/5]
fl::Channel::Channel (int pin, const ChipsetTimingConfig & timing, fl::span< CRGB > leds, EOrder rgbOrder, const ChannelOptions & options) private
Backwards-compatible constructor (deprecated)
Deprecated
Use variant-based constructor instead
Definition at line 253 of file channel.cpp.hpp.
    : CPixelLEDController<RGB>(RegistrationMode::DeferRegister)  // Defer registration until FastLED.add()
    , mChipset(ClocklessChipset(pin, timing))  // Convert to variant
    , mRgbOrder(rgbOrder)
    , mDriver()  // Empty weak_ptr - late binding on first showPixels()
    , mBus(options.mBus)  // Bus selection (#2459)
    , mId(nextId())
    , mName(makeName(mId)) {
    // NOTE: Do NOT call fl::pinMode() here — see comment in the
    // Channel(ChipsetVariant, span, EOrder, ChannelOptions) constructor.
    // Set the LED data array
    setLeds(leds);
    // Sync mSettings from ChannelOptions so the mWhiteCfg variant survives
    // to showPixels(). See sibling ChipsetVariant constructor for rationale.
    mSettings = options;
    // Set color correction/temperature/dither/rgbw from ChannelOptions
    setCorrection(options.mCorrection);
    setTemperature(options.mTemperature);
    setDither(options.mDitherMode);
    applyWhiteCfg(*this, options);
    // Create ChannelData during construction
    mChannelData = ChannelData::create(mChipset);
}
References CPixelLEDController< RGB >::CPixelLEDController(), fl::ChannelData::create(), fl::CLEDController::DeferRegister, leds(), makeName(), mBus, mChannelData, mChipset, fl::ChannelOptions::mCorrection, fl::ChannelOptions::mDitherMode, mDriver, mId, mName, mRgbOrder, mSettings, fl::ChannelOptions::mTemperature, nextId(), fl::RGB, fl::CLEDController::setCorrection(), fl::CLEDController::setDither(), fl::CLEDController::setLeds(), and fl::CLEDController::setTemperature().