FastLED: fl::Channel::applyConfig
applyConfig()
void fl::Channel::applyConfig (const ChannelConfig & config)
Apply reconfigurable settings from a ChannelConfig.
Parameters
config The configuration to apply
Note
Does NOT change: mChipset, mDriver, mId
Definition at line 287 of file channel.cpp.hpp.
{
    mRgbOrder = config.rgb_order;
    if (config.mName.has_value()) {
        mName = config.mName.value();
    }
    setLeds(config.mLeds);
    // Sync mSettings from incoming options so the mWhiteCfg variant survives
    // to showPixels(). Setters below are idempotent overlays on the same data.
    mSettings = config.options;
    setCorrection(config.options.mCorrection);
    setTemperature(config.options.mTemperature);
    setDither(config.options.mDitherMode);
    applyWhiteCfg(*this, config.options);
    auto& events = ChannelEvents::instance();
    events.onChannelConfigured(*this, config);
}
References fl::ChannelEvents::instance(), fl::ChannelOptions::mCorrection, fl::ChannelOptions::mDitherMode, fl::ChannelConfig::mLeds, mName, fl::ChannelConfig::mName, mRgbOrder, mSettings, fl::ChannelOptions::mTemperature, fl::ChannelConfig::options, fl::ChannelConfig::rgb_order, fl::CLEDController::setCorrection(), fl::CLEDController::setDither(), fl::CLEDController::setLeds(), and fl::CLEDController::setTemperature().