FastLED: fl::Channel::Channel
Channel() [1/5]
fl::Channel::Channel (const ChipsetVariant & chipset, EOrder rgbOrder, RegistrationMode mode) protected
Protected constructor for template subclasses (e.g., ClocklessIdf5)
Parameters
chipset Chipset configuration (clockless or SPI)
rgbOrder RGB channel ordering
mode Registration mode (AutoRegister or DeferRegister)
Note
Does not set LED data or channel options - caller must do that
Definition at line 206 of file channel.cpp.hpp.
    : CPixelLEDController<RGB>(mode)
    , mChipset(chipset)
    , mRgbOrder(rgbOrder)
    , mDriver()
    , mBus(Bus::AUTO)
    , mId(nextId())
    , mName(makeName(mId)) {
    // NOTE: Do NOT call fl::pinMode() here — see comment in the
    // Channel(ChipsetVariant, span, EOrder, ChannelOptions) constructor.
    mChannelData = ChannelData::create(mChipset);
}
References CPixelLEDController< RGB >::CPixelLEDController(), fl::AUTO, fl::ChannelData::create(), makeName(), mBus, mChannelData, mChipset, mDriver, mId, mName, mRgbOrder, nextId(), and fl::RGB.
Referenced by Channel(), Channel(), operator=(), operator=(), setGamma(), setScreenMap(), setScreenMap(), setScreenMap(), and setScreenMap().