FastLED: fl::Channel::setScreenMap
setScreenMap() [3/4]
Channel & fl::Channel::setScreenMap (const fl::XYMap & map, float diameter = -1.f)
Set screen map for JS canvas visualization from XYMap.
Parameters
map 2D addressing mode (serpentine, line-by-line, etc.)
diameter Optional LED diameter for canvas rendering
Returns
Reference to this channel for method chaining
Definition at line 803 of file channel.cpp.hpp.
{
    fl::ScreenMap screenmap = map.toScreenMap();
    if (diameter <= 0.0f) {
        screenmap.setDiameter(.15f);  // Default diameter for small matrices
    } else {
        screenmap.setDiameter(diameter);
    }
    mScreenMap = screenmap;
    fl::EngineEvents::onCanvasUiSet(asController(), screenmap);
    return *this;
}
References Channel(), asController(), mScreenMap, fl::EngineEvents::onCanvasUiSet(), and screenmap.
Referenced by setScreenMap(), and setScreenMap().