FastLED: fl::Channel::addToDrawList
addToDrawList()
void fl::Channel::addToDrawList ()
Add this channel to the global controller draw list.
Definition at line 724 of file channel.cpp.hpp.
{
    if (isInList()) {
        FL_WARN("Channel '" << mName << "': Skipping addToDrawList() - already in draw list");
        return;
    }
    CPixelLEDController<RGB>::addToList();
    // Fire event after adding to draw list (detectable even if user bypasses FastLED.add())
    auto& events = ChannelEvents::instance();
    events.onChannelAdded(*this);
}
References fl::CLEDController::addToList(), FL_WARN, fl::ChannelEvents::instance(), fl::CLEDController::isInList(), and mName.