FastLED: fl::Channel::create
create()
ChannelPtr fl::Channel::create (const ChannelConfig & config) static
Create a new channel with optional mBus driver pinning.
Parameters
config Channel configuration. If config.options.mBus is not Bus::AUTO, the channel pins itself to the driver named by busName(mBus) via ChannelManager::findDriverByName(). On a miss, showPixels() falls back to AUTO/priority dispatch and emits a one-shot FL_ERROR (see channel.cpp.hpp).
Returns
Shared pointer to channel (auto-cleanup when out of scope)
Note
Channels always use ChannelManager by default.
Definition at line 174 of file channel.cpp.hpp.
{
    // Late binding strategy: Always create with empty driver
    // Engine binding happens on first showPixels() call:
    // - Affinity channels: Look up by name and cache
    // - Non-affinity channels: Select dynamically each frame
    auto channel = fl::make_shared<Channel>(config.chipset, config.mLeds,
                                              config.rgb_order, config.options);
    channel->mName = makeName(channel->mId, config.mName);
    auto& events = ChannelEvents::instance();
    events.onChannelCreated(*channel);
    return channel;
}
References fl::ChannelConfig::chipset, fl::ChannelEvents::instance(), fl::make_shared(), makeName(), fl::ChannelConfig::mLeds, fl::ChannelConfig::mName, fl::ChannelConfig::options, and fl::ChannelConfig::rgb_order.