FastLED: loop
loop()
void loop ()
Definition at line 89 of file Wave2d.h.
            {
    // Your code here
    waveSim.setXCylindrical(xCyclical.value());
    waveSim.setSpeed(slider);
    waveSim.setDampening(dampening);
    waveSim.setHalfDuplex(halfDuplex);
    waveSim.setSuperSample(getSuperSample());
    // Apply after setSuperSample() so the user's choice survives the
    // wrapper's multiplier-based auto-select for the stencil.
    waveSim.setStencil(isotropicStencil
                           ? fl::LaplacianStencil::NinePointIsotropic
                           : fl::LaplacianStencil::FivePoint);
    if (button) {
        triggerRipple(waveSim);
    }
    EVERY_N_MILLISECONDS(400) {
        if (autoTrigger) {
            triggerRipple(waveSim);
        }
    }
    waveSim.update();
    for (int y = 0; y < HEIGHT; y++) {
        for (int x = 0; x < WIDTH; x++) {
            uint8_t value8 = waveSim.getu8(x, y);
            uint32_t idx = xyMap.mapToIndex(x, y);
            leds[idx] = fl::CRGB(value8, value8, value8);
        }
    }
    FastLED.show();
}
References autoTrigger(), button(), dampening(), EVERY_N_MILLISECONDS, FastLED, fl::FivePoint, getSuperSample(), halfDuplex(), HEIGHT, isotropicStencil(), leds, fl::NinePointIsotropic, slider(), triggerRipple(), waveSim(), WIDTH, x, xCyclical(), xyMap, and y.