FastLED: fl::WaveSimulation2D_Real::WaveSimulation2D_Real
WaveSimulation2D_Real()
fl::WaveSimulation2D_Real::WaveSimulation2D_Real (u32 W, u32 H, float speed = 0.16f, float dampening = 6.0f)
Definition at line 182 of file wave_simulation_real.cpp.hpp.
    : width(W), height(H), stride(W + 2),
      grid1((W + 2) * (H + 2)),
      grid2((W + 2) * (H + 2)), whichGrid(0),
      // CFL stability bound for the explicit leapfrog 5-point stencil in 2D
      // is C^2 <= 1/2. Negative speed has no physical meaning. Clamp at the
      // boundary to keep the Q15 fixed-point kernel both stable and within
      // i32 overflow margins (paired with the i64 promote in update()).
      mCourantSq(wave_detail::float_to_fixed(fl::clamp(speed, 0.0f, 0.5f))),
      // Dampening exponent; e.g., 6 means a factor of 2^6 = 64.
      mDampening(static_cast<int>(dampening)),
      mDampDecayQ15(wave_detail::compute_damp_decay_q15(static_cast<int>(dampening))) {}
References fl::clamp(), fl::wave_detail::compute_damp_decay_q15(), dampening(), FL_NOEXCEPT, fl::wave_detail::float_to_fixed(), grid1, grid2, H, mCourantSq, mDampDecayQ15, mDampening, speed, stride, W, and whichGrid.