FastLED: fl::ScaleUp::expand
expand()
void fl::ScaleUp::expand (const CRGB * input, CRGB * output, uint16_t width, uint16_t height, XYMap mXyMap)
Definition at line 64 of file scale_up.cpp.
{
#if FASTLED_SCALE_UP == FASTLED_SCALE_UP_ALWAYS_POWER_OF_2
    fl::upscalePowerOf2(input, output, static_cast<uint8_t>(width), static_cast<uint8_t>(height), mXyMap);
#elif FASTLED_SCALE_UP == FASTLED_SCALE_UP_HIGH_PRECISION
    fl::upscaleArbitrary(input, output, width, height, mXyMap);
#elif FASTLED_SCALE_UP == FASTLED_SCALE_UP_DECIDE_AT_RUNTIME
    fl::upscale(input, output, width, height, mXyMap);
#elif FASTLED_SCALE_UP == FASTLED_SCALE_UP_FORCE_FLOATING_POINT
    fl::upscaleFloat(input, output, static_cast<uint8_t>(width), static_cast<uint8_t>(height), mXyMap);
#else
#error "Invalid FASTLED_SCALE_UP"
#endif
}
References fl::Fx2d::mXyMap, fl::upscale(), fl::upscaleArbitrary(), fl::upscaleFloat(), and fl::upscalePowerOf2().
Referenced by draw().