FastLED: fl::ScaleUp::draw
draw()
void fl::ScaleUp::draw (DrawContext context) override virtual
Render the effect by drawing delegate at low-res and scaling up.
Parameters
context Drawing context containing the target XYMap and frame buffer
Implements fl::Fx.
Definition at line 41 of file scale_up.cpp.hpp.
{
    if (mSurface.empty()) {
        mSurface.resize(mDelegate->getNumLeds());
    }
    DrawContext delegateContext = context;
    delegateContext.leds = fl::span<CRGB>(mSurface);
    mDelegate->draw(delegateContext);
    u16 in_w = mDelegate->getWidth();
    u16 in_h = mDelegate->getHeight();
    u16 out_w = getWidth();
    u16 out_h = getHeight();
    ;
    if (in_w == out_w && in_h == out_h) {
        noExpand(fl::span<const CRGB>(mSurface), context.leds, in_w, in_h);
    } else {
        expand(fl::span<const CRGB>(mSurface), context.leds, in_w, in_h, mXyMap);
    }
}
References expand(), fl::Fx2d::getHeight(), fl::Fx2d::getWidth(), fl::DrawContext::leds, mDelegate, mSurface, fl::Fx2d::mXyMap, and noExpand().