FastLED: fl::ScaleUp::expand
expand()
void fl::ScaleUp::expand (fl::span< const CRGB > input, fl::span< CRGB > output, u16 width, u16 height, const XYMap & mXyMap)
Expand a low-resolution buffer to high-resolution using bilinear interpolation.
Performs bilinear filtering to smoothly upscale pixel data from a source buffer to a destination buffer. Each output pixel is calculated by interpolating the four nearest input pixels, creating smooth transitions and reducing blocky artifacts.
The actual interpolation algorithm used depends on the FASTLED_SCALE_UP compile-time setting:
POWER_OF_2: Fast bit-shift version (requires power-of-2 dimensions)
HIGH_PRECISION: Integer math for arbitrary dimensions
DECIDE_AT_RUNTIME: Automatically selects based on input dimensions
FORCE_FLOATING_POINT: Floating-point math (slowest, not recommended)
Note
This method is exposed primarily for unit testing and is not part of the public API. Normal usage should go through draw() which handles buffer management automatically.
Parameters
input Source buffer containing low-resolution pixel data
output Destination buffer for high-resolution output (must be pre-allocated)
width Width of the low-resolution input buffer
height Height of the low-resolution input buffer
mXyMap The target high-resolution XYMap defining output dimensions and layout
Definition at line 61 of file scale_up.cpp.hpp.
{
#if FASTLED_SCALE_UP == FASTLED_SCALE_UP_ALWAYS_POWER_OF_2
    fl::upscalePowerOf2(input.data(), output.data(), static_cast<u8>(width), static_cast<u8>(height), mXyMap);
#elif FASTLED_SCALE_UP == FASTLED_SCALE_UP_HIGH_PRECISION
    fl::upscaleArbitrary(input.data(), output.data(), width, height, mXyMap);
#elif FASTLED_SCALE_UP == FASTLED_SCALE_UP_DECIDE_AT_RUNTIME
    fl::upscale(input.data(), output.data(), width, height, mXyMap);
#elif FASTLED_SCALE_UP == FASTLED_SCALE_UP_FORCE_FLOATING_POINT
    fl::upscaleFloat(input.data(), output.data(), static_cast<u8>(width), static_cast<u8>(height), mXyMap);
#else
#error "Invalid FASTLED_SCALE_UP"
#endif
}
References fl::span< T, Extent >::data(), fl::height, fl::Fx2d::mXyMap, fl::upscale(), fl::upscaleArbitrary(), fl::upscaleFloat(), fl::upscalePowerOf2(), and fl::width.
Referenced by draw().