FastLED: fl::UIElement::setGroup
setGroup()
virtual void fl::UIElement::setGroup (const fl::string & groupName) inline virtual
Reimplemented in fl::UIAudio, fl::UIButton, fl::UICheckbox, fl::UIDescription, fl::UIDropdown, fl::UIHelp, fl::UINumberField, fl::UISlider, fl::UITitle, UIButton, UICheckbox, UIDescription, UIDropdown, UIHelp, UINumberField, UISlider, and UITitle.
Definition at line 32 of file ui.h.
{ mGroupName = groupName; }
References mGroupName.
Referenced by fl::UIAudio::setGroup(), fl::UIButton::setGroup(), fl::UICheckbox::setGroup(), fl::UIDescription::setGroup(), fl::UIDropdown::setGroup(), fl::UIHelp::setGroup(), fl::UINumberField::setGroup(), fl::UISlider::setGroup(), and fl::UITitle::setGroup().