FastLED: fl::UIElement::setGroup
setGroup()
virtual void fl::UIElement::setGroup (const fl::string & groupName) inline virtual
Reimplemented in fl::UIAudio, fl::UIButton, fl::UICheckbox, fl::UIDescription, fl::UIDropdown, fl::UIHelp, fl::UINumberField, fl::UISlider, and fl::UITitle.
Definition at line 31 of file element.h.
{ mGroupName = groupName; }
References FL_NOEXCEPT, and mGroupName.
Referenced by fl::UIAudio::setGroup(), fl::UIButton::setGroup(), fl::UICheckbox::setGroup(), fl::UIDescription::setGroup(), fl::UIDropdown::setGroup(), fl::UIHelp::setGroup(), fl::UINumberField::setGroup(), fl::UISlider::setGroup(), and fl::UITitle::setGroup().