FastLED: hsv2rgb_fullspectrum
hsv2rgb_fullspectrum() [2/3]
void hsv2rgb_fullspectrum (const CHSV & hsv, CRGB & rgb)
Converts an HSV value to RGB using the algorithm from here: https://en.wikipedia.org/wiki/HSL_and_HSV#HSV_to_RGB_alternative By Shawn Silverman.
Parameters
hsv CHSV struct to convert to RGB
rgb CRGB struct to store the result of the conversion (will be modified)
Definition at line 495 of file hsv2rgb.cpp.hpp.
{
  const auto f = [](const int n, const fl::u8 h) -> fl::u32 {
    constexpr int kZero = 0 << 8;
    constexpr int kOne  = 1 << 8;
    constexpr int kFour = 4 << 8;
    constexpr int kSix  = 6 << 8;
    const int k = ((n << 8) + 6*h) % kSix;
    const int k2 = kFour - k;
    return fl::max(kZero, fl::min(kOne, fl::min(k, k2)));
  };
  const fl::u32 chroma = hsv.v * hsv.s / 255;
  rgb.r = hsv.v - ((chroma * f(5, hsv.h)) >> 8);
  rgb.g = hsv.v - ((chroma * f(3, hsv.h)) >> 8);
  rgb.b = hsv.v - ((chroma * f(1, hsv.h)) >> 8);
}
References fl::max(), and fl::min().
Referenced by hsv2rgb_dispatch(), hsv2rgb_dispatch(), hsv2rgb_fullspectrum(), hsv2rgb_fullspectrum(), and loop().