FastLED: fl::Mpeg1FileHandle::read
read() [1/3]
fl::size_t fl::Mpeg1FileHandle::read (char * dst, fl::size_t bytesToRead) inline override virtual
Implements fl::filebuf.
Definition at line 48 of file file_system_codecs.cpp.hpp.
{
        if (!mDecoder || !mHasValidFrame) return 0;
        fl::size totalRead = 0;
        while (bytesToRead > 0 && mHasValidFrame) {
            fl::size rem = mFrameSize - mCurrentPos;
            if (rem == 0) { if (!decodeNextFrameIfNeeded()) break; rem = mFrameSize - mCurrentPos; }
            fl::size toRead = fl::min(bytesToRead, rem);
            if (toRead > 0 && mCurrentFrame && mCurrentFrame->rgb().data()) {
                fl::memcpy(dst + totalRead, (fl::u8*)mCurrentFrame->rgb().data() + mCurrentPos, toRead);
                mCurrentPos += toRead; totalRead += toRead; bytesToRead -= toRead;
            } else break;
        }
        return totalRead;
    }
References decodeNextFrameIfNeeded(), mCurrentFrame, mCurrentPos, mDecoder, fl::memcpy(), mFrameSize, mHasValidFrame, and fl::min().