FastLED: fl::audio::detector::Note::update
update() [2/2]
void fl::audio::detector::Note::update (shared_ptr< Context > context) override virtual
Implements fl::audio::Detector.
Definition at line 48 of file note.cpp.hpp.
{
    // Update pitch detector if we own it
    if (mOwnsPitchDetector && mPitchDetector) {
        mPitchDetector->update(context);
    }
    // Get pitch detection results
    if (!mPitchDetector) {
        return;  // No pitch detector available
    }
    float pitch = mPitchDetector->getPitch();
    float confidence = mPitchDetector->getConfidence();
    bool voiced = mPitchDetector->isVoiced();
    u32 timestamp = context->getTimestamp();
    float energy = context->getRMS();
    mCurrentPitch = pitch;
    mLastUpdateTime = timestamp;
    // State machine: note-on, note-off, note-change detection
    if (!mNoteActive) {
        // No note currently active - check for note-on
        if (shouldTriggerNoteOn(confidence, pitch)) {
            u8 newNote = frequencyToMidiNote(pitch);
            u8 velocity = calculateVelocity(energy, confidence);
            mCurrentNote = newNote;
            mLastVelocity = velocity;
            mNoteActive = true;
            mNoteOnTime = timestamp;
            mNoteOnEnergy = energy;
            mPitchBend = calculatePitchBend(pitch, newNote);
            mFireNoteOn = true;
            mPendingOnNote = newNote;
            mPendingOnVelocity = velocity;
        }
    } else {
        // Note currently active - check for note-off or note-change
        if (shouldTriggerNoteOff(confidence, voiced)) {
            // Check minimum note duration to prevent flicker
            u32 noteDuration = timestamp - mNoteOnTime;
            if (noteDuration >= mMinNoteDuration) {
                mFireNoteOff = true;
                mPendingOffNote = mCurrentNote;
                mCurrentNote = NO_NOTE;
                mLastVelocity = 0;
                mNoteActive = false;
                mPitchBend = 0.0f;
            }
        } else if (voiced && confidence >= mNoteOnThreshold) {
            // Note still active - check for note change
            u8 newNote = frequencyToMidiNote(pitch);
            mPitchBend = calculatePitchBend(pitch, mCurrentNote);
            if (shouldTriggerNoteChange(newNote, mCurrentNote)) {
                u8 velocity = calculateVelocity(energy, confidence);
                // Set pending note-off for old note
                mFireNoteOff = true;
                mPendingOffNote = mCurrentNote;
                // Update to new note
                mCurrentNote = newNote;
                mLastVelocity = velocity;
                mNoteOnTime = timestamp;
                mPitchBend = calculatePitchBend(pitch, newNote);
                // Set pending note-on for new note
                mFireNoteOn = true;
                mPendingOnNote = newNote;
                mPendingOnVelocity = velocity;
                mFireNoteChange = true;
            }
        }
    }
}
References Note(), calculatePitchBend(), calculateVelocity(), frequencyToMidiNote(), mCurrentNote, mCurrentPitch, mFireNoteChange, mFireNoteOff, mFireNoteOn, mLastUpdateTime, mLastVelocity, mMinNoteDuration, mNoteActive, mNoteOnEnergy, mNoteOnThreshold, mNoteOnTime, mOwnsPitchDetector, mPendingOffNote, mPendingOnNote, mPendingOnVelocity, mPitchBend, mPitchDetector, NO_NOTE, shouldTriggerNoteChange(), shouldTriggerNoteOff(), shouldTriggerNoteOn(), and update().
Referenced by ~Note(), update(), and update().