FastLED: fl::ChannelConfig::ChannelConfig
ChannelConfig() [1/8]
fl::ChannelConfig::ChannelConfig (const fl::string & name, const ChipsetVariant & chipset, fl::span< CRGB > leds, EOrder rgbOrder = RGB, const ChannelOptions & options = ChannelOptions())
Named constructor with chipset variant.
Parameters
name User-specified channel name
chipset Chipset configuration (clockless or SPI)
leds LED data array
rgbOrder RGB channel ordering
options Channel options (correction, temperature, dither, affinity)
Examples
/home/runner/work/FastLED/FastLED/src/fl/channels/config.h.
Definition at line 10 of file config.cpp.hpp.
    : ChannelConfig(chipset, leds, rgbOrder, options) {
    mName = name;
}
References ChannelConfig(), chipset, leds, mName, and options.
Referenced by ChannelConfig(), ChannelConfig(), ChannelConfig(), ChannelConfig(), operator=(), and operator=().