FastLED: fl::isr::memcpy
memcpy()
FL_OPTIMIZE_FUNCTION FL_IRAM FASTLED_FORCE_INLINE void fl::isr::memcpy (void *FL_RESTRICT_PARAM dst, const void *FL_RESTRICT_PARAM src, size_t num_bytes)
ISR-optimized memcpy with alignment detection and switch dispatch.
Parameters
dst Destination pointer
src Source pointer
num_bytes Number of bytes to copy
Note
Automatically uses 32-bit, 16-bit, or byte copy based on alignment
Uses switch for dispatch (compiler may optimize to jump table)
Definition at line 75 of file memcpy.h.
{
    uintptr_t dst_addr = fl::ptr_to_int(dst);
    uintptr_t src_addr = fl::ptr_to_int(src);
    size_t align2 = (((dst_addr | src_addr | num_bytes) & 1) == 0);
    size_t align4 = (((dst_addr | src_addr | num_bytes) & 3) == 0);
    int index = align2 + align4;
    switch (index) {
        case 2:
            memcpy_32(static_cast<u32*>(dst),
                      static_cast<const u32*>(src),
                      num_bytes >> 2);
            break;
        case 1:
            memcpy_16(static_cast<u16*>(dst),
                      static_cast<const u16*>(src),
                      num_bytes >> 1);
            break;
        case 0:
        default:
            memcpy_byte(static_cast<u8*>(dst),
                        static_cast<const u8*>(src),
                        num_bytes);
            break;
    }
}
References FL_RESTRICT_PARAM, memcpy_16(), memcpy_32(), memcpy_byte(), and fl::ptr_to_int().
Referenced by fl::wave3Untranspose_16(), fl::wave3Untranspose_2(), fl::wave3Untranspose_4(), fl::wave3Untranspose_8(), fl::wave8Untranspose_16(), fl::wave8Untranspose_2(), fl::wave8Untranspose_4(), and fl::wave8Untranspose_8().