FastLED: fl::Animartrix::AnimartrixLoop
AnimartrixLoop
void AnimartrixLoop (Animartrix & self, uint32_t now) friend
Definition at line 155 of file animartrix.hpp.
{
    if (self.prev_animation != self.current_animation) {
        if (self.impl) {
            // Re-initialize object.
            self.impl->init(self.getWidth(), self.getHeight());
        }
        self.prev_animation = self.current_animation;
    }
    if (!self.impl) {
        self.impl.reset(new FastLEDANIMartRIX(&self));
    }
    self.impl->setTime(now);
    self.impl->loop();
}
References Animartrix(), current_animation, FastLEDANIMartRIX, fl::Fx2d::getHeight(), fl::Fx2d::getWidth(), impl, and prev_animation.
Referenced by draw().