FastLED: fl::Animartrix::draw
draw()
void fl::Animartrix::draw (DrawContext context) inline override virtual
Parameters
now The current time in milliseconds. Fx writers are encouraged to use this instead of millis() directly as this will more deterministic behavior.
Implements fl::Fx.
Definition at line 223 of file animartrix.hpp.
{
        if (!mXyMap.isLUT()) {
            mXyMap.convertToLookUpTable();
        }
        // Set up context for rendering
        mCtx.leds = ctx.leds;
        mCtx.xyMapFn = &xyMapCallbackAdapter;
        mCtx.xyMapUserData = this;
        // Initialize or reinitialize engine on animation change
        const bool anim_changed = (mPrevAnimation != mCurrentAnimation);
        if (anim_changed) {
            init(mCtx, getWidth(), getHeight());
            mPrevAnimation = mCurrentAnimation;
        }
        if (mCtx.mEngine == nullptr) {
            init(mCtx, getWidth(), getHeight());
        }
        // Create (or recreate after animation change) the visualizer instance.
        if (anim_changed || !mViz) {
            mViz.reset(createViz(mCurrentAnimation));
        }
        setTime(mCtx, ctx.now);
        // Dispatch to the selected animation.
        // Custom viz takes precedence; otherwise use the table-created viz.
        if (mCustomViz) {
            mCustomViz->draw(mCtx);
        } else if (mViz) {
            mViz->draw(mCtx);
        }
        // Apply color order if not RGB
        if (mColorOrder != RGB) {
            for (int i = 0; i < mXyMap.getTotal(); ++i) {
                CRGB &pixel = ctx.leds[i];
                const u8 b0_index = RGB_BYTE0(mColorOrder);
                const u8 b1_index = RGB_BYTE1(mColorOrder);
                const u8 b2_index = RGB_BYTE2(mColorOrder);
                pixel = CRGB(pixel.raw[b0_index], pixel.raw[b1_index],
                             pixel.raw[b2_index]);
            }
        }
        mCtx.leds = fl::span<CRGB>();
    }
References createViz(), fl::Fx2d::getHeight(), fl::Fx2d::getWidth(), fl::init(), fl::DrawContext::leds, mColorOrder, mCtx, mCurrentAnimation, mCustomViz, mPrevAnimation, mViz, fl::Fx2d::mXyMap, fl::DrawContext::now, fl::RGB, RGB_BYTE0, RGB_BYTE1, RGB_BYTE2, fl::setTime(), and fl::xyMapCallbackAdapter().