FastLED: fl::Animartrix::fxSet
fxSet()
void fl::Animartrix::fxSet (int fx)
Definition at line 142 of file animartrix.hpp.
{
    int curr = fxGet();
    if (fx < 0) {
        fx = curr + fx;
        if (fx < 0) {
            fx = NUM_ANIMATIONS - 1;
        }
    }
    fx = fx % NUM_ANIMATIONS;
    current_animation = static_cast<AnimartrixAnim>(fx);
    FASTLED_DBG("Setting animation to " << getAnimationName(current_animation));
}
References current_animation, FASTLED_DBG, fxGet(), getAnimationName(), and fl::NUM_ANIMATIONS.
Referenced by fxNext().