FastLED: fl::Animartrix::Animartrix
Animartrix() [1/2]
fl::Animartrix::Animartrix (const XYMap & xyMap, AnimartrixAnim which_animation) inline
Definition at line 214 of file animartrix.hpp.
        : Fx2d(xyMap) {
        mCurrentAnimation = which_animation;
        // convertToLookUpTable() is deferred to draw() to avoid
        // cross-DLL static initialization order issues on Windows.
    }
References fl::Fx2d::Fx2d(), mCurrentAnimation, and fl::Fx2d::xyMap().
Referenced by Animartrix().