FastLED: fl::perlin_i16_optimized::pnoise2d_raw
pnoise2d_raw()
fl::i32 fl::perlin_i16_optimized::pnoise2d_raw (fl::i32 fx_raw, fl::i32 fy_raw, const fl::i32 * fade_lut, const fl::u8 * perm) static
Definition at line 34 of file perlin_i16_optimized.cpp.hpp.
{
    int X, Y;
    fl::i16 x16, y16;  // i16 fractional parts!
    floor_frac_i16(fx_raw, X, x16);
    floor_frac_i16(fy_raw, Y, y16);
    X &= 255;
    Y &= 255;
    // Fade values can be up to 65536, need to stay i32
    // But we can still optimize grad and internal lerp to use i16
    fl::i32 u = fade(x16, fade_lut);
    fl::i32 v = fade(y16, fade_lut);
    int A  = perm[X & 255]       + Y;
    int AA = perm[A & 255];
    int AB = perm[(A + 1) & 255];
    int B  = perm[(X + 1) & 255] + Y;
    int BA = perm[B & 255];
    int BB = perm[(B + 1) & 255];
    // grad returns i16 (coordinates are i16), lerp takes i32 fade values
    fl::i32 g00 = grad_i16(perm[AA & 255], x16,              y16);
    fl::i32 g10 = grad_i16(perm[BA & 255], x16 - HP_ONE_I16, y16);
    fl::i32 g01 = grad_i16(perm[AB & 255], x16,              y16 - HP_ONE_I16);
    fl::i32 g11 = grad_i16(perm[BB & 255], x16 - HP_ONE_I16, y16 - HP_ONE_I16);
    // Lerp with i32 (grad results fit in i16 range but lerp needs i32 for fade values)
    fl::i32 lerp0 = lerp(u, g00, g10);
    fl::i32 lerp1 = lerp(u, g01, g11);
    fl::i32 result = lerp(v, lerp0, lerp1);
    return result;
}
References fl::B, fade(), floor_frac_i16(), grad_i16(), HP_ONE_I16, and lerp().
Referenced by pnoise2d(), and autoresearch::animartrix_check::runPerlinBenchmark().