FastLED: fl::WeakPtr::lock
lock()
template<typename T> Ptr< T > fl::WeakPtr< T >::lock () const inline
Definition at line 354 of file ptr.h.
{
        if (!mWeakPtr) {
            return Ptr<T>();
        }
        T* out = static_cast<T*>(mWeakPtr->getReferent());
        if (out->ref_count() == 0) {
            // This is a static object, so the refcount is 0.
            return Ptr<T>::NoTracking(*out);
        }
        // This is a heap object, so we need to ref it.
        return Ptr<T>::TakeOwnership(static_cast<T *>(out));
    }
References mWeakPtr, fl::Ptr< T >::NoTracking(), and fl::Ptr< T >::TakeOwnership().
Referenced by operator==().