FastLED: test_get_endpoint
test_get_endpoint()
void test_get_endpoint ()
Definition at line 124 of file ClientValidationReal.h.
{
    FL_WARN("\n=== Test 2: GET /get (Request Echo) ===");
    fl::task::Promise<fl::net::http::Response> promise = fl::net::http::fetch_get("http://localhost:8081/get");
    fl::task::PromiseResult<fl::net::http::Response> result = fl::task::await_top_level(promise);
    if (!result.ok()) {
        FL_WARN("✗ FAILED: " << result.error_message());
        tests_failed++;
        state = FAILED;
        return;
    }
    const fl::net::http::Response& resp = result.value();
    if (resp.status() != 200) {
        FL_WARN("✗ FAILED: Status " << resp.status() << " " << resp.status_text());
        tests_failed++;
        state = FAILED;
        return;
    }
    if (!resp.is_json()) {
        FL_WARN("✗ FAILED: Response is not JSON");
        tests_failed++;
        state = FAILED;
        return;
    }
    fl::json data = resp.json();
    fl::string origin = data["origin"] | fl::string("unknown");
    fl::string url = data["url"] | fl::string("unknown");
    if (origin == "unknown" || url == "unknown") {
        FL_WARN("✗ FAILED: Invalid response structure");
        tests_failed++;
        state = FAILED;
        return;
    }
    FL_WARN("✓ PASSED");
    FL_WARN("  Origin: " << origin);
    FL_WARN("  URL: " << url);
    tests_passed++;
}
References fl::task::await_top_level(), FAILED, fl::net::http::fetch_get(), FL_WARN, fl::net::http::Response::is_json(), fl::net::http::Response::json(), state, fl::net::http::Response::status(), fl::net::http::Response::status_text(), tests_failed, and tests_passed.
Referenced by loop().