FastLED: test_ping_endpoint
test_ping_endpoint()
void test_ping_endpoint ()
Definition at line 169 of file ClientValidationReal.h.
{
    FL_WARN("\n=== Test 3: GET /ping (Health Check) ===");
    fl::task::Promise<fl::net::http::Response> promise = fl::net::http::fetch_get("http://localhost:8081/ping");
    fl::task::PromiseResult<fl::net::http::Response> result = fl::task::await_top_level(promise);
    if (!result.ok()) {
        FL_WARN("✗ FAILED: " << result.error_message());
        tests_failed++;
        state = FAILED;
        return;
    }
    const fl::net::http::Response& resp = result.value();
    if (resp.status() != 200) {
        FL_WARN("✗ FAILED: Status " << resp.status() << " " << resp.status_text());
        tests_failed++;
        state = FAILED;
        return;
    }
    fl::string body = resp.text();
    if (body != "pong\n") {
        FL_WARN("✗ FAILED: Expected 'pong\\n', got '" << body << "'");
        tests_failed++;
        state = FAILED;
        return;
    }
    FL_WARN("✓ PASSED");
    FL_WARN("  Response: " << body.substr(0, body.length() - 1));  // Strip newline for display
    tests_passed++;
}
References fl::task::await_top_level(), FAILED, fl::net::http::fetch_get(), FL_WARN, fl::basic_string::length(), state, fl::net::http::Response::status(), fl::net::http::Response::status_text(), fl::string::substr(), tests_failed, tests_passed, and fl::net::http::Response::text().
Referenced by loop().