FastLED: loop
loop()
void loop ()
Definition at line 269 of file ClientValidationReal.h.
            {
    // Server updates are now handled by the task (every 1ms)
    // No need for manual server.update() here
    // Wait 1 second after startup before starting tests
    if (state == SERVER_STARTING && (fl::millis() - test_start_time > 1000)) {
        FL_WARN("=================================");
        FL_WARN("Starting HTTP Client Tests");
        FL_WARN("=================================");
        state = TEST_JSON;
    }
    // Run tests sequentially
    if (state == TEST_JSON) {
        test_json_endpoint();
        if (state != FAILED) state = TEST_GET;
        delay(500);
    }
    else if (state == TEST_GET) {
        test_get_endpoint();
        if (state != FAILED) state = TEST_PING;
        delay(500);
    }
    else if (state == TEST_PING) {
        test_ping_endpoint();
        if (state != FAILED) {
            // All tests passed!
            state = ALL_PASSED;
            FL_WARN("\n=================================");
            FL_WARN("Test Results");
            FL_WARN("=================================");
            FL_WARN("Passed: " << tests_passed);
            FL_WARN("Failed: " << tests_failed);
            FL_WARN("Total:  " << (tests_passed + tests_failed));
            FL_WARN("=================================");
            FL_WARN("✓ All tests PASSED");
        }
        delay(500);
    }
    else if (state == FAILED && !done) {
        FL_WARN("\n=================================");
        FL_WARN("Test Results");
        FL_WARN("=================================");
        FL_WARN("Passed: " << tests_passed);
        FL_WARN("Failed: " << tests_failed);
        FL_WARN("Total:  " << (tests_passed + tests_failed));
        FL_WARN("=================================");
        FL_WARN("✗ Some tests FAILED");
        done = true;
        // Signal completion - cleanup happens automatically via ScopedEngineCleanup
        #ifdef FASTLED_STUB
        fl::stub_main::stop_loop();
        #endif
    }
    else if (state == ALL_PASSED && !done) {
        done = true;
        // Signal completion - cleanup happens automatically via ScopedEngineCleanup
        #ifdef FASTLED_STUB
        fl::stub_main::stop_loop();
        #endif
    }
    // Keep updating LEDs on hardware
    updateLEDs();
    FastLED.show();
    delay(100);
}
References ALL_PASSED, done, FAILED, FastLED, FL_WARN, fl::millis(), SERVER_STARTING, state, TEST_GET, test_get_endpoint(), TEST_JSON, test_json_endpoint(), TEST_PING, test_ping_endpoint(), test_start_time, tests_failed, tests_passed, and updateLEDs().