FastLED: fl::SlabAllocator::allocateFromSlab
allocateFromSlab()
template<typename T, fl::size SLAB_SIZE = FASTLED_DEFAULT_SLAB_SIZE> void * fl::SlabAllocator< T, SLAB_SIZE >::allocateFromSlab (fl::size n = 1) inline private
Definition at line 513 of file allocator.h.
{
        // Try to find n contiguous free blocks in existing slabs
        for (Slab* slab = mSlabs; slab; slab = slab->next) {
            void* ptr = findContiguousBlocks(slab, n);
            if (ptr) {
                return ptr;
            }
        }
        // No contiguous blocks found, create new slab if n fits
        if (n <= BLOCKS_PER_SLAB) {
            if (!createSlab()) {
                return nullptr; // Out of memory
            }
            // Try again with the new slab
            return findContiguousBlocks(mSlabs, n);
        }
        // Request too large for slab, fall back to malloc
        return nullptr;
    }
References BLOCKS_PER_SLAB, createSlab(), findContiguousBlocks(), FL_NOEXCEPT, and mSlabs.
Referenced by allocate().