FastLED: fl::audio::FrequencyBinMapper::mapBins
mapBins()
void fl::audio::FrequencyBinMapper::mapBins (span< const float > fftBins, span< float > outputBins) const
Map FFT bins to frequency channels.
Parameters
fftBins Input FFT bins (magnitude spectrum)
outputBins Output frequency bins (16 or 32 bins depending on mode)
Definition at line 121 of file frequency_bin_mapper.cpp.hpp.
{
    const size numBins = static_cast<size>(mConfig.mode);
    // Validate output buffer size
    if (outputBins.size() < numBins) {
        FL_WARN("FrequencyBinMapper: output buffer too small (" << outputBins.size()
                << " < " << numBins << ")");
        return;
    }
    // Track maximum magnitude for stats
    float maxMag = 0.0f;
    u32 fftBinsUsed = 0;
    // Map fft::FFT bins to frequency bins by averaging
    for (size i = 0; i < numBins; ++i) {
        const BinMapping& mapping = mBinMappings[i];
        float sum = 0.0f;
        u32 count = 0;
        // Average fft::FFT bins in this range
        for (u32 j = mapping.startBin; j < mapping.endBin && j < fftBins.size(); ++j) {
            sum += fftBins[j];
            ++count;
            ++fftBinsUsed;
            if (fftBins[j] > maxMag) {
                maxMag = fftBins[j];
            }
        }
        // Calculate average
        if (count > 0) {
            outputBins[i] = sum / static_cast<float>(count);
        } else {
            outputBins[i] = 0.0f;
        }
    }
    // Update stats (mutable in const method for statistics)
    const_cast<FrequencyBinMapper*>(this)->mStats.binMappingCount++;
    const_cast<FrequencyBinMapper*>(this)->mStats.lastFFTBinsUsed = fftBinsUsed;
    const_cast<FrequencyBinMapper*>(this)->mStats.maxMagnitude = maxMag;
}
References FrequencyBinMapper(), fl::audio::FrequencyBinMapper::BinMapping::endBin, FL_WARN, mBinMappings, mConfig, mStats, fl::span< T, Extent >::size(), and fl::audio::FrequencyBinMapper::BinMapping::startBin.
Referenced by ~FrequencyBinMapper().