FastLED: fl::audio::FrequencyBinMapper::FrequencyBinMapper
FrequencyBinMapper() [1/2]
fl::audio::FrequencyBinMapper::FrequencyBinMapper ()
Definition at line 13 of file frequency_bin_mapper.cpp.hpp.
{
    configure(FrequencyBinMapperConfig());
}
References configure().
Referenced by configure(), and mapBins().