FastLED: fl::audio::FrequencyBinMapper::calculateBinBoundaries
calculateBinBoundaries()
void fl::audio::FrequencyBinMapper::calculateBinBoundaries () private
Calculate frequency bin boundaries (linear or logarithmic spacing)
Definition at line 36 of file frequency_bin_mapper.cpp.hpp.
{
    const size numBins = static_cast<size>(mConfig.mode);
    // Allocate space for bin boundaries (numBins + 1 edges)
    mBinFrequencies.clear();
    mBinFrequencies.reserve(numBins + 1);
    if (mConfig.useLogSpacing) {
        calculateLogFrequencies();
    } else {
        calculateLinearFrequencies();
    }
}
References calculateLinearFrequencies(), calculateLogFrequencies(), mBinFrequencies, and mConfig.
Referenced by configure().