FastLED: fl::audio::FrequencyBinMapper::configure
configure()
void fl::audio::FrequencyBinMapper::configure (const FrequencyBinMapperConfig & config)
Configure the frequency bin mapper This calculates bin boundaries and FFT-to-frequency bin mappings.
Definition at line 23 of file frequency_bin_mapper.cpp.hpp.
{
    mConfig = config;
    // Reset stats
    mStats = Stats();
    // Calculate frequency boundaries for output bins
    calculateBinBoundaries();
    // Calculate fft::FFT bin to frequency bin mappings
    calculateBinMappings();
}
References FrequencyBinMapper(), calculateBinBoundaries(), calculateBinMappings(), configure(), mConfig, and mStats.
Referenced by FrequencyBinMapper(), FrequencyBinMapper(), ~FrequencyBinMapper(), and configure().