FastLED: fl::net::http::Response::json
json()
fl::json fl::net::http::Response::json () const
Response body parsed as JSON (JavaScript-like API)
Returns
fl::json object for safe, ergonomic access
Note
Automatically parses JSON on first call, caches result
Returns null JSON object for non-JSON or malformed content
Definition at line 649 of file fetch.cpp.hpp.
{
    if (!mJsonParsed) {
        if (is_json() || mBody.find("{") != fl::string::npos || mBody.find("[") != fl::string::npos) {
            mCachedJson = parse_json_body();
        } else {
            FL_WARN("Response is not JSON: " << mBody);
            mCachedJson = fl::json(nullptr);  // Not JSON content
        }
        mJsonParsed = true;
    }
    return mCachedJson.has_value() ? *mCachedJson : fl::json(nullptr);
}
References FL_WARN, is_json(), mBody, mCachedJson, mJsonParsed, fl::string::npos, and parse_json_body().
Referenced by test_get_endpoint(), and test_json_endpoint().