FastLED: showGenerative
showGenerative()
void showGenerative ()
Definition at line 156 of file FestivalStick.ino.
                      {
    // This function is called to show the generative pattern
    uint32_t now = millis();
    fl::clear(leds);
    for (int i = 0; i < NUM_LEDS; i++) {
        // Get the 2D position of this LED from the screen map
        fl::vec3f pos = mapCorkScrew[i];
        float x = pos.x;
        float y = pos.y;
        float z = pos.z;
        x*= 20.0f * ledsScale.value();
        y*= 20.0f * ledsScale.value();
        z*= 20.0f * ledsScale.value();
        uint16_t noise_value = inoise16(x,y,z, now / 100);
        // Normalize the noise value to 0-255
        uint8_t brightness = map(noise_value, 0, 65535, 0, 255);
        // Create a hue that changes with position and time
        uint8_t sat = int32_t((x * 10 + y * 5 + now / 5)) % 256;
        // Set the color
        leds[i] = CHSV(170, sat, fl::clamp(255- sat, 64, 255));
    }
    FastLED.show();
}
References brightness, fl::clamp(), fl::clear(), FastLED, inoise16(), leds, ledsScale, mapCorkScrew, NUM_LEDS, pos, x, y, and z.
Referenced by loop().