FastLED: fl::audio::SignalConditioner::processSample
processSample()
Sample fl::audio::SignalConditioner::processSample (const Sample & sample)
Process a raw audio sample through the conditioning pipeline.
Parameters
sample Raw audio sample from microphone/I2S
Returns
Cleaned audio sample (DC-removed, spike-filtered, gated)
Definition at line 33 of file signal_conditioner.cpp.hpp.
{
    if (!sample.isValid() || sample.size() == 0) {
        return Sample();  // Return empty sample
    }
    const auto pcm = sample.pcm();
    const size sampleCount = pcm.size();
    // Reserve buffers to avoid repeated allocations
    mValidMask.clear();
    mValidMask.reserve(sampleCount);
    mTempBuffer.clear();
    mTempBuffer.reserve(sampleCount);
    mOutputBuffer.clear();
    mOutputBuffer.reserve(sampleCount);
    // Stage 1: Spike filtering (if enabled)
    if (mConfig.enableSpikeFilter) {
        filterSpikes(pcm, mValidMask);
    } else {
        // All samples valid if spike filtering disabled
        mValidMask.assign(sampleCount, true);
    }
    // Stage 2: DC offset removal (if enabled)
    // Uses per-buffer instantaneous DC calculation for accuracy,
    // plus per-sample DCBlocker for cross-buffer continuity.
    i32 dcOffset = 0;
    if (mConfig.enableDCRemoval) {
        dcOffset = calculateDCOffset(pcm, mValidMask);
        removeDCOffset(pcm, dcOffset, mTempBuffer);
    } else {
        // Copy samples to temp buffer without DC removal
        mTempBuffer.assign(pcm.begin(), pcm.end());
    }
    // Stage 3: Noise gate (if enabled)
    if (mConfig.enableNoiseGate) {
        applyNoiseGate(mTempBuffer, mOutputBuffer);
    } else {
        // Copy temp buffer to output without gating
        mOutputBuffer = mTempBuffer;
    }
    // Update stats
    mStats.dcOffset = dcOffset;
    mStats.noiseGateOpen = mNoiseGateOpen;
    mStats.samplesProcessed += sampleCount;
    // Create new Sample from cleaned PCM
    SampleImplPtr impl = fl::make_shared<SampleImpl>();
    impl->assign(mOutputBuffer.begin(), mOutputBuffer.end(), sample.timestamp());
    return Sample(impl);
}
References applyNoiseGate(), calculateDCOffset(), filterSpikes(), fl::make_shared(), mConfig, mNoiseGateOpen, mOutputBuffer, mStats, mTempBuffer, mValidMask, removeDCOffset(), and fl::sample().
Referenced by ~SignalConditioner().