FastLED: openVideoEitherFormat
openVideoEitherFormat()
fl::Video openVideoEitherFormat (const char * fledPath, const char * rgbPath, const char * sidecarScreenmapPath, fl::ScreenMap * outScreenMap)
Definition at line 95 of file FxSdCard.ino.
{
    // Try FLED first.
    fl::Video v = filesystem.openVideo(fledPath, NUM_LEDS, FPS, NUM_VIDEO_FRAMES);
    if (v && v.hasEmbeddedScreenMap()) {
        const fl::string &json = v.embeddedScreenMapJson();
        fl::string parseErr;
        if (!fl::ScreenMap::ParseJson(json.c_str(), "strip1", outScreenMap, &parseErr)) {
            FL_WARN("FLED embedded screenmap parse failed: " << parseErr.c_str());
            gError = true;
            return v;
        }
        validateScreenMapSize(*outScreenMap, fledPath);
        return v;
    }
    // No .fled (or it lacks an embedded map). Fall back to legacy .rgb.
    fl::Video legacy = filesystem.openVideo(rgbPath, NUM_LEDS, FPS, NUM_VIDEO_FRAMES);
    if (!legacy) {
        FL_WARN("Failed to open " << rgbPath << " (and no " << fledPath << " either)");
        gError = true;
        return legacy;
    }
    if (!filesystem.readScreenMap(sidecarScreenmapPath, "strip1", outScreenMap)) {
        FL_WARN("Failed to read sidecar " << sidecarScreenmapPath);
        gError = true;
        return legacy;
    }
    validateScreenMapSize(*outScreenMap, sidecarScreenmapPath);
    return legacy;
}
References fl::basic_string::c_str(), fl::Video::embeddedScreenMapJson(), filesystem, FL_WARN, FPS, gError, fl::Video::hasEmbeddedScreenMap(), NUM_LEDS, NUM_VIDEO_FRAMES, fl::ScreenMap::ParseJson(), and validateScreenMapSize().
Referenced by setup().