[platformio]
default_envs = lpc845


[env:lpc845]
platform = nxplpc
board = lpc845
framework = cmsis
upload_protocol = cmsis-dap
debug_tool = cmsis-dap
build_type = debug
build_flags =
    -I$PROJECT_DIR/include
    -I$PROJECT_DIR/../../src
    -g3
    -Og
    -DDEBUG
