FastLED: fl::anonymous_namespace{json.cpp.hpp}::JsonTokenizer::parse
parse() [2/2]
bool fl::anonymous_namespace{json.cpp.hpp}::JsonTokenizer::parse (fl::string_view input, JsonVisitor & visitor) inline
Definition at line 481 of file json.cpp.hpp.
{
        mInput = input.data();
        mLen = input.size();
        mPos = 0;
        while (true) {
            fl::span<const char> token_value;
            JsonToken token = next_token(token_value);
            if (token == JsonToken::ERROR) {
                return false;
            }
            ParseState result = visitor.on_token(token, token_value);
            if (result == ParseState::ERROR) {
                return false;
            }
            if (token == JsonToken::END_OF_INPUT) {
                break;
            }
        }
        return true;
    }
References fl::string_view::data(), fl::anonymous_namespace{json.cpp.hpp}::END_OF_INPUT, fl::anonymous_namespace{json.cpp.hpp}::ERROR, mInput, mLen, mPos, next_token(), fl::anonymous_namespace{json.cpp.hpp}::JsonVisitor::on_token(), and fl::string_view::size().