FastLED: fl::anonymous_namespace{json.cpp.hpp}::JsonTokenizer::next_token
next_token()
JsonToken fl::anonymous_namespace{json.cpp.hpp}::JsonTokenizer::next_token (fl::span< const char > & out_value) inline private
Definition at line 313 of file json.cpp.hpp.
{
        skip_whitespace();
        if (mPos >= mLen) {
            out_value = fl::span<const char>();
            return JsonToken::END_OF_INPUT;
        }
        char c = mInput[mPos];
        // Structural tokens
        switch (c) {
            case '{':
                out_value = fl::span<const char>(&mInput[mPos], 1);
                mPos++;
                return JsonToken::LBRACE;
            case '}':
                out_value = fl::span<const char>(&mInput[mPos], 1);
                mPos++;
                return JsonToken::RBRACE;
            case '[': {
                size_t saved_pos = mPos;
                mPos++;  // Skip '['
                JsonToken array_token = scan_array_lookahead(out_value);
                if (array_token != JsonToken::LBRACKET) {
                    // Specialized array token - mPos now points at ']'
                    mPos++;  // Skip ']'
                    return array_token;
                }
                // Slow path - restore position
                mPos = saved_pos;
                out_value = fl::span<const char>(&mInput[mPos], 1);
                mPos++;
                return JsonToken::LBRACKET;
            }
            case ']':
                out_value = fl::span<const char>(&mInput[mPos], 1);
                mPos++;
                return JsonToken::RBRACKET;
            case ':':
                out_value = fl::span<const char>(&mInput[mPos], 1);
                mPos++;
                return JsonToken::COLON;
            case ',':
                out_value = fl::span<const char>(&mInput[mPos], 1);
                mPos++;
                return JsonToken::COMMA;
            default:
                break;  // Fall through to other token types
        }
        // STRING tokenization
        if (c == '"') {
            size_t start = mPos + 1;  // After opening quote
            mPos++;
            while (mPos < mLen) {
                if (mInput[mPos] == '\\') {
                    // Skip escape sequence
                    mPos++;
                    if (mPos >= mLen) {
                        out_value = fl::span<const char>();
                        return JsonToken::ERROR;  // Unclosed string
                    }
                    mPos++;  // Skip escaped character
                } else if (mInput[mPos] == '"') {
                    // Found closing quote
                    out_value = fl::span<const char>(&mInput[start], mPos - start);
                    mPos++;  // Move past closing quote
                    return JsonToken::STRING;
                } else {
                    mPos++;
                }
            }
            // Unclosed string
            out_value = fl::span<const char>();
            return JsonToken::ERROR;
        }
        // NUMBER tokenization
        if (c == '-' || (c >= '0' && c <= '9')) {
            size_t start = mPos;
            // Optional minus
            if (c == '-') mPos++;
            // Require at least one digit
            if (mPos >= mLen || !(mInput[mPos] >= '0' && mInput[mPos] <= '9')) {
                out_value = fl::span<const char>();
                return JsonToken::ERROR;
            }
            // Digits before decimal
            while (mPos < mLen && mInput[mPos] >= '0' && mInput[mPos] <= '9') {
                mPos++;
            }
            // Optional decimal point
            if (mPos < mLen && mInput[mPos] == '.') {
                mPos++;
                // Require digits after decimal
                if (mPos >= mLen || !(mInput[mPos] >= '0' && mInput[mPos] <= '9')) {
                    out_value = fl::span<const char>();
                    return JsonToken::ERROR;
                }
                while (mPos < mLen && mInput[mPos] >= '0' && mInput[mPos] <= '9') {
                    mPos++;
                }
            }
            // Optional exponent
            if (mPos < mLen && (mInput[mPos] == 'e' || mInput[mPos] == 'E')) {
                mPos++;
                // Optional sign
                if (mPos < mLen && (mInput[mPos] == '+' || mInput[mPos] == '-')) {
                    mPos++;
                }
                // Require exponent digits
                if (mPos >= mLen || !(mInput[mPos] >= '0' && mInput[mPos] <= '9')) {
                    out_value = fl::span<const char>();
                    return JsonToken::ERROR;
                }
                while (mPos < mLen && mInput[mPos] >= '0' && mInput[mPos] <= '9') {
                    mPos++;
                }
            }
            out_value = fl::span<const char>(&mInput[start], mPos - start);
            return JsonToken::NUMBER;
        }
        // Keyword: true
        if (c == 't' && mPos + 3 < mLen &&
            mInput[mPos+1] == 'r' && mInput[mPos+2] == 'u' && mInput[mPos+3] == 'e') {
            out_value = fl::span<const char>(&mInput[mPos], 4);
            mPos += 4;
            return JsonToken::TRUE;
        }
        // Keyword: false
        if (c == 'f' && mPos + 4 < mLen &&
            mInput[mPos+1] == 'a' && mInput[mPos+2] == 'l' &&
            mInput[mPos+3] == 's' && mInput[mPos+4] == 'e') {
            out_value = fl::span<const char>(&mInput[mPos], 5);
            mPos += 5;
            return JsonToken::FALSE;
        }
        // Keyword: null
        if (c == 'n' && mPos + 3 < mLen &&
            mInput[mPos+1] == 'u' && mInput[mPos+2] == 'l' && mInput[mPos+3] == 'l') {
            out_value = fl::span<const char>(&mInput[mPos], 4);
            mPos += 4;
            return JsonToken::NULL_VALUE;
        }
        // Unknown token
        out_value = fl::span<const char>();
        return JsonToken::ERROR;
    }
References fl::anonymous_namespace{json.cpp.hpp}::COLON, fl::anonymous_namespace{json.cpp.hpp}::COMMA, fl::anonymous_namespace{json.cpp.hpp}::END_OF_INPUT, fl::anonymous_namespace{json.cpp.hpp}::ERROR, fl::anonymous_namespace{json.cpp.hpp}::FALSE, fl::anonymous_namespace{json.cpp.hpp}::LBRACE, fl::anonymous_namespace{json.cpp.hpp}::LBRACKET, mInput, mLen, mPos, fl::anonymous_namespace{json.cpp.hpp}::NULL_VALUE, fl::anonymous_namespace{json.cpp.hpp}::NUMBER, fl::anonymous_namespace{json.cpp.hpp}::RBRACE, fl::anonymous_namespace{json.cpp.hpp}::RBRACKET, scan_array_lookahead(), skip_whitespace(), fl::anonymous_namespace{json.cpp.hpp}::STRING, and fl::anonymous_namespace{json.cpp.hpp}::TRUE.
Referenced by parse().