FastLED: fl::anonymous_namespace{json.cpp.hpp}::JsonTokenizer::scan_array_lookahead
scan_array_lookahead()
JsonToken fl::anonymous_namespace{json.cpp.hpp}::JsonTokenizer::scan_array_lookahead (fl::span< const char > & out_span) inline private
Definition at line 138 of file json.cpp.hpp.
{
        if (!mEnableLookahead) {
            return JsonToken::LBRACKET;  // Lookahead disabled
        }
        size_t start_pos = mPos;  // Position after '['
        // Track element types and ranges
        bool has_int = false;
        bool has_float = false;
        bool has_float_beyond_precision = false;  // Track floats > 2^24
        bool has_string = false;
        bool has_bool = false;
        bool has_null = false;
        i64 int_min = fl::numeric_limits<i64>::max();
        i64 int_max = fl::numeric_limits<i64>::min();
        skip_whitespace();
        // Empty array - use slow path
        if (mPos < mLen && mInput[mPos] == ']') {
            out_span = fl::span<const char>();
            return JsonToken::LBRACKET;
        }
        // Scan elements
        while (mPos < mLen) {
            skip_whitespace();
            // Check for array end
            if (mInput[mPos] == ']') {
                break;
            }
            char c = mInput[mPos];
            // Abort on nested structures
            if (c == '[' || c == '{') {
                return JsonToken::LBRACKET;
            }
            // STRING
            if (c == '"') {
                has_string = true;
                mPos++;
                while (mPos < mLen) {
                    if (mInput[mPos] == '\\') {
                        mPos += 2;  // Skip escape sequence
                    } else if (mInput[mPos] == '"') {
                        mPos++;
                        break;
                    } else {
                        mPos++;
                    }
                }
            }
            // NUMBER
            else if (c == '-' || (c >= '0' && c <= '9')) {
                size_t num_start = mPos;
                bool is_float = false;
                if (c == '-') mPos++;
                while (mPos < mLen && mInput[mPos] >= '0' && mInput[mPos] <= '9') mPos++;
                if (mPos < mLen && mInput[mPos] == '.') {
                    is_float = true;
                    mPos++;
                    while (mPos < mLen && mInput[mPos] >= '0' && mInput[mPos] <= '9') mPos++;
                }
                if (mPos < mLen && (mInput[mPos] == 'e' || mInput[mPos] == 'E')) {
                    is_float = true;
                    mPos++;
                    if (mPos < mLen && (mInput[mPos] == '+' || mInput[mPos] == '-')) mPos++;
                    while (mPos < mLen && mInput[mPos] >= '0' && mInput[mPos] <= '9') mPos++;
                }
                if (is_float) {
                    has_float = true;
#if FL_PLATFORM_HAS_LARGE_MEMORY
                    // Bit-twiddling parse -- never reaches libgcc soft-FP. The
                    // resulting u32 carries the same IEEE 754 single-precision
                    // bit pattern strtof would produce (+/-1 ULP). The magnitude
                    // check rides on the biased exponent so we avoid `fl::abs`.
                    const u32 f_bits = fl::ieee754_parse_decimal(&mInput[num_start], mPos - num_start);
                    if (float_bits_magnitude_exceeds_2_24(f_bits)) {
                        has_float_beyond_precision = true;
                    }
#else
                    // Low-memory gate per FastLED #3082: assume float values
                    // exceed 2^24 (forces slow path / generic array fallback).
                    // Drops `ieee754_parse_decimal` (598 B) + `kPow10Mant` LUT
                    // (824 B) + `kPow10BExp` (206 B) from the link.
                    has_float_beyond_precision = true;
#endif
                } else {
                    has_int = true;
                    // Parse actual value to get accurate range
                    // fl::parseInt doesn't allocate (Phase 1 test confirms zero allocations)
                    i64 val = fl::parseInt(&mInput[num_start], mPos - num_start);
                    if (val < int_min) int_min = val;
                    if (val > int_max) int_max = val;
                }
            }
            // TRUE
            else if (c == 't' && mPos + 3 < mLen &&
                     mInput[mPos+1] == 'r' && mInput[mPos+2] == 'u' && mInput[mPos+3] == 'e') {
                has_bool = true;
                mPos += 4;
            }
            // FALSE
            else if (c == 'f' && mPos + 4 < mLen &&
                     mInput[mPos+1] == 'a' && mInput[mPos+2] == 'l' &&
                     mInput[mPos+3] == 's' && mInput[mPos+4] == 'e') {
                has_bool = true;
                mPos += 5;
            }
            // NULL
            else if (c == 'n' && mPos + 3 < mLen &&
                     mInput[mPos+1] == 'u' && mInput[mPos+2] == 'l' && mInput[mPos+3] == 'l') {
                has_null = true;
                mPos += 4;
            }
            else {
                return JsonToken::LBRACKET;  // Unknown token
            }
            skip_whitespace();
            // Check for comma or end
            if (mPos < mLen) {
                if (mInput[mPos] == ',') {
                    mPos++;
                } else if (mInput[mPos] == ']') {
                    break;
                } else {
                    return JsonToken::LBRACKET;  // Invalid syntax
                }
            }
        }
        // Determine array type
        int type_count = (has_int ? 1 : 0) + (has_float ? 1 : 0) +
                         (has_string ? 1 : 0) + (has_bool ? 1 : 0) + (has_null ? 1 : 0);
        out_span = fl::span<const char>(&mInput[start_pos], mPos - start_pos);
        // Only emit specialized tokens for types json_value supports
        if (type_count == 1 || (type_count == 2 && has_int && has_float)) {
            if (has_float || (has_int && has_float)) {
                // Don't optimize floats beyond integer precision
                if (has_float_beyond_precision) {
                    return JsonToken::LBRACKET;  // Use slow path
                }
                return JsonToken::ARRAY_FLOAT;  // vector<float>
            }
            if (has_int) {
                // Determine optimal integer type
                if (int_min >= 0 && int_max <= 255) {
                    return JsonToken::ARRAY_UINT8;  // vector<u8>
                }
                if (int_min >= -32768 && int_max <= 32767) {
                    return JsonToken::ARRAY_INT16;  // vector<i16>
                }
                // Larger ints fall back to slow path
                return JsonToken::LBRACKET;
            }
            // Strings, bools - use slow path
            return JsonToken::LBRACKET;
        }
        // Mixed types - use slow path
        return JsonToken::LBRACKET;
    }
References fl::anonymous_namespace{json.cpp.hpp}::ARRAY_FLOAT, fl::anonymous_namespace{json.cpp.hpp}::ARRAY_INT16, fl::anonymous_namespace{json.cpp.hpp}::ARRAY_UINT8, fl::float_bits_magnitude_exceeds_2_24(), fl::ieee754_parse_decimal(), fl::anonymous_namespace{json.cpp.hpp}::LBRACKET, fl::numeric_limits< T >::max(), mEnableLookahead, fl::numeric_limits< T >::min(), mInput, mLen, mPos, fl::parseInt(), and skip_whitespace().
Referenced by next_token().