FastLED: fl::HeapVector::ensure_size
ensure_size()
template<typename T, typename Allocator = fl::allocator<T>> void fl::HeapVector< T, Allocator >::ensure_size (size_t n) inline
Definition at line 373 of file vector.h.
{
        if (n > mCapacity) {
            size_t new_capacity = (3 * mCapacity) / 2;
            if (new_capacity < n) {
                new_capacity = n;
            }
            T* new_array = mAlloc.allocate(new_capacity);
            // Copy existing elements to new array
            for (size_t i = 0; i < mSize; ++i) {
                mAlloc.construct(&new_array[i], mArray[i]);
            }
            // Clean up old array
            if (mArray) {
                for (size_t i = 0; i < mSize; ++i) {
                    mAlloc.destroy(&mArray[i]);
                }
                mAlloc.deallocate(mArray, mCapacity);
            }
            mArray = new_array;
            mCapacity = new_capacity;
        }
    }
Referenced by fl::HeapVector< DrawItem >::push_back(), fl::HeapVector< DrawItem >::reserve(), and fl::HeapVector< DrawItem >::resize().