FastLED: fl::spi::Device::Device
Device() [1/2]
fl::spi::Device::Device (const Config & config) explicit
Construct SPI device with configuration.
Parameters
config Pin and speed configuration
Definition at line 21 of file device.cpp.hpp.
    : pImpl(fl::make_unique<Impl>(config)) {
    FL_LOG_SPI("SPI Device: Created with clock=" << config.clock_pin
           << " data_pins.size()=" << config.data_pins.size());
}
References fl::SpiConfig::clock_pin, fl::SpiConfig::data_pins, FL_LOG_SPI, fl::make_unique(), pImpl, and fl::vector_basic::size().
Referenced by Device(), and operator=().