FastLED: fl::XYMap::mapToIndex
mapToIndex() [1/2]
u16 fl::XYMap::mapToIndex (const u16 & x, const u16 & y) const
Definition at line 116 of file xymap.cpp.hpp.
{
    u16 index;
    switch (type) {
    case kSerpentine: {
        u16 xx = x % width;
        u16 yy = y % height;
        index = xy_serpentine(xx, yy, width, height);
        break;
    }
    case kLineByLine: {
        u16 xx = x % width;
        u16 yy = y % height;
        index = xy_line_by_line(xx, yy, width, height);
        break;
    }
    case kFunction:
        if (xyFunction) {
            index = xyFunction(x, y, width, height);
        } else {
            // Null function pointer — fall back to line-by-line to avoid crash.
            // This can happen due to cross-DLL static initialization order issues.
            index = xy_line_by_line(x, y, width, height);
        }
        break;
    case kLookUpTable:
        index = mLookUpTable->getData()[y * width + x];
        break;
    default:
        return 0;
    }
    return index + mOffset;
}
References height, kFunction, kLineByLine, kLookUpTable, kSerpentine, mLookUpTable, mOffset, type, width, fl::x, fl::xy_line_by_line(), fl::xy_serpentine(), xyFunction, and fl::y.
Referenced by fl::anonymous_namespace{channel.cpp.hpp}::ReorderingPixelIteratorAny::ReorderingPixelIteratorAny(), convertToLookUpTable(), mapPixels(), mapToIndex(), operator()(), and toScreenMap().