FastLED: fl::XYMap::mapToIndex
mapToIndex() [2/2]
uint16_t fl::XYMap::mapToIndex (uint16_t x, uint16_t y) const
Definition at line 106 of file xymap.cpp.
{
    uint16_t index;
    switch (type) {
    case kSerpentine:
        x = x % width;
        y = y % height;
        index = xy_serpentine(x, y, width, height);
        break;
    case kLineByLine:
        index = xy_line_by_line(x, y, width, height);
        break;
    case kFunction:
        x = x % width;
        y = y % height;
        index = xyFunction(x, y, width, height);
        break;
    case kLookUpTable:
        index = mLookUpTable->getData()[y * width + x];
        break;
    default:
        return 0;
    }
    return index + mOffset;
}
References height, kFunction, kLineByLine, kLookUpTable, kSerpentine, mLookUpTable, mOffset, type, width, x, fl::xy_line_by_line(), fl::xy_serpentine(), xyFunction, and y.
Referenced by convertToLookUpTable(), mapPixels(), mapToIndex(), operator()(), and toScreenMap().