FastLED: fl::XYMap::toScreenMap
toScreenMap()
ScreenMap fl::XYMap::toScreenMap () const
Definition at line 12 of file xymap.cpp.hpp.
{
    const u16 length = width * height;
    ScreenMap out(length);
    for (u16 w = 0; w < width; w++) {
        for (u16 h = 0; h < height; h++) {
            u16 index = mapToIndex(w, h);
            vec2f p = {static_cast<float>(w), static_cast<float>(h)};
            out.set(index, p);
        }
    }
    // Store a shared_ptr to this XYMap so it can be used for encoding
    out.setSourceXYMap(fl::make_shared<XYMap>(*this));
    return out;
}
References height, length(), fl::make_shared(), mapToIndex(), fl::ScreenMap::set(), fl::ScreenMap::setSourceXYMap(), and width.
Referenced by operator=().