FastLED: fl::XYMap::constructWithUserFunction
constructWithUserFunction()
XYMap fl::XYMap::constructWithUserFunction (u16 width, u16 height, XYFunction xyFunction, u16 offset = 0) static
Definition at line 27 of file xymap.cpp.hpp.
{
    XYMap out(width, height, kFunction);
    out.xyFunction = xyFunction;
    out.mOffset = offset;
    return out;
}
References XYMap(), height, kFunction, mOffset, offset(), width, and xyFunction.
Referenced by fl::gfx::blur2d().