FastLED: fl::XYMap::fromXMap
fromXMap()
XYMap fl::XYMap::fromXMap (const XMap & xmap) static
Create an XYMap from an XMap (treats 1D as 2D with height=1)
Parameters
xmap 1D addressing map
Returns
XYMap with width=xmap.length and height=1
Definition at line 60 of file xymap.cpp.hpp.
{
    // Create an XYMap with width=xmap.length and height=1
    // This treats the 1D strip as a 2D grid with height 1
    u16 length = xmap.getLength();
    // Create a user function that dispatches to the XMap
    // Since we can't capture xmap directly, we create a LUT and use that
    auto out = XYMap::constructWithLookUpTable(length, 1, nullptr);
    fl::shared_ptr<LUT16> lut = fl::make_shared<LUT16>(length);
    u16* data = lut->getDataMutable();
    // Fill the LUT with xmap's mappings
    for (u16 i = 0; i < length; i++) {
        data[i] = xmap.mapToIndex(i);
    }
    out.mLookUpTable = lut;
    return out;
}
References XYMap(), constructWithLookUpTable(), fl::XMap::getLength(), length(), fl::make_shared(), and fl::XMap::mapToIndex().
Referenced by fl::Channel::setScreenMap().