FastLED: fl::platforms::scopedWatchdogFirstInit
scopedWatchdogFirstInit()
void fl::platforms::scopedWatchdogFirstInit (fl::u32 timeout_ms) inline
Definition at line 129 of file watchdog.cpp.hpp.
{
    Watchdog& wdt = Watchdog::instance();
    wdt.begin(timeout_ms);
    ResetInfo info = wdt.lastResetInfo();
    if (info.cause == ResetCause::WATCHDOG ||
        info.cause == ResetCause::PANIC    ||
        info.cause == ResetCause::LOCKUP) {
        char buf[128];
        fl::size n = info.describe(fl::span<char>(buf, sizeof(buf)), /*verbose=*/true);
        scopedWatchdogPrintLine(fl::string_view("[FastLED.watchdog] recovered from:"));
        scopedWatchdogPrintLine(fl::string_view(buf, n));
        if (wdt.hasCrashReport()) {
            // Hook for Tier 2 platforms. Future revision: also emit a
            // multi-line CrashReport::describe() result here. For now the
            // bare cause + raw register is the documented contract.
        }
        scopedWatchdogPause3s();
    }
    scopedWatchdogPrintLine(fl::string_view("[FastLED.watchdog] armed via FL_WATCHDOG_AUTO()"));
}
References fl::Watchdog::begin(), fl::ResetInfo::cause, fl::ResetInfo::describe(), FL_NOEXCEPT, fl::Watchdog::hasCrashReport(), fl::Watchdog::instance(), fl::Watchdog::lastResetInfo(), fl::LOCKUP, fl::PANIC, scopedWatchdogPause3s(), scopedWatchdogPrintLine(), and fl::WATCHDOG.
Referenced by fl::ScopedWatchdog::ScopedWatchdog().