FastLED: loop
loop()
void loop ()
Definition at line 233 of file OTA.ino.
            {
  // Service OTA (low overhead: ~73µs when idle)
  ota.poll();
#if USE_WIFI
  // Async WiFi mode: Show connection status via LEDs
  if (!ota.isConnected()) {
    // Connecting: Show pulsing blue animation
    uint8_t brightness = beatsin8(60, 30, 255);  // Pulse at 60 BPM
    fill_solid(leds, NUM_LEDS, CRGB::Blue);
    FastLED.setBrightness(brightness);
    FastLED.show();
    delay(20);
    return;  // Skip normal animation while connecting
  } else if (!wifi_connected_notified) {
    // Just connected: Show success and print info
    wifi_connected_notified = true;
    Serial.println("\nWi-Fi connected!");
    Serial.print("Access web interface at: http://");
    Serial.print(HOSTNAME);
    Serial.println(".local/");
    // Brief celebration: Green flash
    fill_solid(leds, NUM_LEDS, CRGB::Green);
    FastLED.setBrightness(255);
    FastLED.show();
    delay(500);
    // Restore normal brightness for animation
    FastLED.setBrightness(50);
  }
#endif
  // Normal LED animation (rainbow)
  fill_rainbow(leds, NUM_LEDS, hue, 7);
  FastLED.show();
  hue++;
  // Small delay for animation speed
  delay(20);
}
References beatsin8(), fl::CRGB::Blue, brightness, FastLED, fill_rainbow(), fill_solid(), fl::CRGB::Green, HOSTNAME, hue, leds, NUM_LEDS, ota, Serial, and wifi_connected_notified.