FastLED: fl::SPITransposer::getLaneByte
getLaneByte()
u8 fl::SPITransposer::getLaneByte (const LaneData & lane, size_t byte_idx, size_t max_size) static private
Get byte from lane at given index, handling padding automatically.
Examples
/home/runner/work/FastLED/FastLED/src/fl/math/transposition.h.
Definition at line 300 of file transposition.cpp.hpp.
{
    // Calculate padding needed for this lane
    const size_t lane_size = lane.payload.size();
    const size_t padding_bytes = max_size - lane_size;
    // If we're in the padding region (prepended to beginning)
    if (byte_idx < padding_bytes) {
        // Return padding frame byte (repeating pattern)
        if (!lane.padding_frame.empty()) {
            return lane.padding_frame[byte_idx % lane.padding_frame.size()];
        }
        return 0x00;  // Fallback to zero
    }
    // We're in the data region
    const size_t data_idx = byte_idx - padding_bytes;
    if (data_idx < lane_size) {
        return lane.payload[data_idx];
    }
    // Should never reach here if max_size is correct
    return 0x00;
}
References fl::span< T, Extent >::empty(), fl::SPITransposer::LaneData::padding_frame, fl::SPITransposer::LaneData::payload, and fl::span< T, Extent >::size().
Referenced by transpose16(), transpose2(), transpose4(), and transpose8().