FastLED: fl::SPITransposer::transpose2
transpose2()
FL_DISABLE_WARNING_POP bool fl::SPITransposer::transpose2 (const fl::optional< LaneData > & lane0, const fl::optional< LaneData > & lane1, fl::span< u8 > output, const char ** error = nullptr) static
Transpose 2 lanes of data into interleaved dual-SPI format.
Parameters
lane0 Lane 0 data (use fl::nullopt for unused lane)
lane1 Lane 1 data (use fl::nullopt for unused lane)
output Output buffer to write interleaved data (size must be divisible by 2)
error Optional pointer to receive error message (set to nullptr if unused)
Returns
true on success, false if output buffer size is invalid
Note
Output buffer size determines max lane size: max_size = output.size() / 2
Shorter lanes are padded at the beginning with repeating padding_frame pattern
Empty lanes (nullopt) are filled with zeros or first lane's padding
Examples
/home/runner/work/FastLED/FastLED/src/fl/math/transposition.h.
Definition at line 53 of file transposition.cpp.hpp.
{
    // Validate output buffer size (must be divisible by 2)
    if (output.size() % 2 != 0) {
        if (error) {
            *error = "Output buffer size must be divisible by 2";
        }
        return false;
    }
    // Calculate max lane size from output buffer
    const size_t max_size = output.size() / 2;
    // Handle empty case
    if (max_size == 0) {
        if (error) {
            *error = nullptr;  // No error, just empty
        }
        return true;
    }
    // Create array of lane references for easier iteration
    const fl::optional<LaneData>* lanes[2] = {&lane0, &lane1};
    // Determine default padding byte from first available lane
    u8 default_padding = 0x00;
    for (size_t i = 0; i < 2; i++) {
        if (lanes[i]->has_value() && !(*lanes[i])->padding_frame.empty()) {
            default_padding = (*lanes[i])->padding_frame[0];
            break;
        }
    }
    // Gather all bytes from each lane into temporary buffers
    fl::vector<u8> lane0_buffer(max_size);
    fl::vector<u8> lane1_buffer(max_size);
    for (size_t byte_idx = 0; byte_idx < max_size; byte_idx++) {
        lane0_buffer[byte_idx] = lanes[0]->has_value() ?
            getLaneByte(**lanes[0], byte_idx, max_size) : default_padding;
        lane1_buffer[byte_idx] = lanes[1]->has_value() ?
            getLaneByte(**lanes[1], byte_idx, max_size) : default_padding;
    }
    // Perform transposition using ISR-safe primitive
    transpose_2lane_inline(lane0_buffer.data(), lane1_buffer.data(), output.data(), max_size);
    if (error) {
        *error = nullptr;  // Success, no error
    }
    return true;
}
References fl::vector< T >::data(), fl::Optional< T >::empty(), getLaneByte(), fl::Optional< T >::has_value(), and fl::transpose_2lane_inline().
Referenced by fl::spi::MultiLaneDevice::flush().