FastLED: fl::audio::fft::Bins::setNormFactors
setNormFactors()
void fl::audio::fft::Bins::setNormFactors (const fl::vector< float > & factors) private
Definition at line 157 of file fft.cpp.hpp.
{
    if (mNormFactors.capacity() == 0) {
        mNormFactors = pool().acquire(mBands);
    }
    mNormFactors.resize(factors.size());
    for (fl::size i = 0; i < factors.size(); ++i) {
        mNormFactors[i] = factors[i];
    }
    mNormalizedDirty = true;
}
References fl::audio::fft::FloatVectorPool::acquire(), mBands, mNormalizedDirty, mNormFactors, pool(), and fl::vector_basic::size().
Referenced by operator=(), fl::audio::fft::Context::runHybrid(), and fl::audio::fft::Context::runLogRebin().