FastLED: fl::audio::fft::Bins::db
db()
fl::span< const float > fl::audio::fft::Bins::db () const
Definition at line 65 of file fft.cpp.hpp.
{
    if (!mDbDirty) {
        return mBinsDb;
    }
    if (mBinsDb.capacity() == 0) {
        mBinsDb = pool().acquire(mBands);
    }
    mBinsDb.resize(mBinsRaw.size());
    for (fl::size i = 0; i < mBinsRaw.size(); ++i) {
        float x = mBinsRaw[i];
        mBinsDb[i] = (x > 0.0f) ? 20.0f * fl::log10f(x) : 0.0f;
    }
    mDbDirty = false;
    return mBinsDb;
}
References fl::audio::fft::FloatVectorPool::acquire(), fl::log10f(), mBands, mBinsDb, mBinsRaw, mDbDirty, pool(), and fl::x.
Referenced by fl::string::append(), fl::sstream::operator<<(), and operator=().