FastLED: fl::Fire2012::draw
draw()
void fl::Fire2012::draw (DrawContext context) inline override virtual
Parameters
now The current time in milliseconds. Fx writers are encouraged to use this instead of millis() directly as this will more deterministic behavior.
Implements fl::Fx.
Definition at line 61 of file fire2012.h.
{
        CRGB *leds = context.leds;
        if (leds == nullptr) {
            return;
        }
        // Step 1.  Cool down every cell a little
        for (uint16_t i = 0; i < mNumLeds; i++) {
            heat[i] =
                qsub8(heat[i], random8(0, ((cooling * 10) / mNumLeds) + 2));
        }
        // Step 2.  Heat from each cell drifts 'up' and diffuses a little
        for (uint16_t k = mNumLeds - 1; k >= 2; k--) {
            heat[k] = (heat[k - 1] + heat[k - 2] + heat[k - 2]) / 3;
        }
        // Step 3.  Randomly ignite new 'sparks' of heat near the bottom
        if (random8() < sparking) {
            int y = random8(7);
            heat[y] = qadd8(heat[y], random8(160, 255));
        }
        // Step 4.  Map from heat cells to LED colors
        for (uint16_t j = 0; j < mNumLeds; j++) {
            // Scale the heat value from 0-255 down to 0-240
            // for best results with color palettes.
            uint8_t colorindex = scale8(heat[j], 240);
            CRGB color = ColorFromPalette(palette, colorindex);
            int pixelnumber;
            if (reverse_direction) {
                pixelnumber = (mNumLeds - 1) - j;
            } else {
                pixelnumber = j;
            }
            leds[pixelnumber] = color;
        }
    }
References fl::ColorFromPalette(), cooling, heat, fl::_DrawContext::leds, leds, fl::Fx::mNumLeds, palette, qadd8(), qsub8(), random8(), reverse_direction, scale8(), sparking, and y.