FastLED: RGBWEmulatedController::showPixels
showPixels()
template<typename CONTROLLER, EOrder RGB_ORDER = GRB> virtual void RGBWEmulatedController< CONTROLLER, RGB_ORDER >::showPixels (PixelController< RGB_ORDER, LANES, MASK > & pixels) inline override virtual
Main rendering function that converts RGB to RGBW and shows pixels.
This function:
Converts each RGB pixel to RGBW format based on the configured conversion mode
Packs the RGBW data into a format the RGB controller can transmit
Temporarily bypasses color correction/temperature on the base controller
Sends the packed data to the physical LED strip
Parameters
pixels The pixel controller containing RGB data to be converted
Implements CPixelLEDController< GRB, CONTROLLER::LANES_VALUE, CONTROLLER::MASK_VALUE >.
Definition at line 244 of file chipsets.h.
{
        // Ensure buffer is large enough
        ensureBuffer(pixels.size());
        Rgbw rgbw = this->getRgbw();
        fl::u8 *data = fl::bit_cast_ptr<fl::u8>(mRGBWPixels.get());
        while (pixels.has(1)) {
            pixels.stepDithering();
            pixels.loadAndScaleRGBW(rgbw, data, data + 1, data + 2, data + 3);
            data += 4;
            pixels.advanceData();
        }
        // Force the device controller to a state where it passes data through
        // unmodified: color correction, color temperature, dither, and brightness
        // (passed as an argument to show()).  Temporarily enable the controller,
        // show the LEDs, and disable it again.
        //
        // The device controller is in the global controller list, so if we
        // don't keep it disabled, it will refresh again with unknown brightness,
        // temperature, etc.
        mController.setCorrection(CRGB(255, 255, 255));
        mController.setTemperature(CRGB(255, 255, 255));
        mController.setDither(DISABLE_DITHER);
        mController.setEnabled(true);
        mController.callShow(mRGBWPixels.get(), Rgbw::size_as_rgb(pixels.size()), 255);
        mController.setEnabled(false);
    }
References PixelController< RGB_ORDER, LANES, MASK >::advanceData(), fl::bit_cast_ptr(), DISABLE_DITHER, ensureBuffer(), fl::CLEDController::getRgbw(), PixelController< RGB_ORDER, LANES, MASK >::has(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGBW(), mController, mRGBWPixels, rgbw, PixelController< RGB_ORDER, LANES, MASK >::size(), Rgbw::size_as_rgb(), and PixelController< RGB_ORDER, LANES, MASK >::stepDithering().