FastLED: CRGB::CRGB
CRGB() [1/8]
FASTLED_FORCE_INLINE CRGB::CRGB () inline
Default constructor.
Definition at line 158 of file crgb.h.
{
        r = 0;
        g = 0;
        b = 0;
    }
References FASTLED_FORCE_INLINE.
Referenced by CRGB(), addToRGB(), blend(), blendAlphaMaxChannel(), colorBoost(), colorBoost(), computeAdjustment(), downscale(), fadeLightBy(), fadeToBlackBy(), lerp16(), lerp8(), nscale8(), nscale8(), nscale8_constexpr(), nscale8_video(), operator%=(), operator&=(), operator&=(), operator*=(), operator++(), operator++(), operator+=(), operator-(), operator--(), operator--(), operator-=(), operator/=(), operator=(), operator=(), operator=(), operator>>=(), operator|=(), operator|=(), scale8(), scale8(), setColorCode(), setHSV(), setHue(), setRGB(), subtractFromRGB(), and upscale().