FastLED: CRGB::CRGB
CRGB() [1/7]
FASTLED_FORCE_INLINE CRGB::CRGB () default
Default constructor.
Warning
Default values are UNITIALIZED!
References FASTLED_FORCE_INLINE.
Referenced by CRGB(), addToRGB(), blend(), blendAlphaMaxChannel(), computeAdjustment(), downscale(), fadeLightBy(), fadeToBlackBy(), lerp16(), lerp8(), nscale8(), nscale8(), nscale8_constexpr(), nscale8_video(), operator%=(), operator&=(), operator&=(), operator*=(), operator++(), operator++(), operator+=(), operator-(), operator--(), operator--(), operator-=(), operator/=(), operator=(), operator=(), operator=(), operator>>=(), operator|=(), operator|=(), scale8(), scale8(), setColorCode(), setHSV(), setHue(), setRGB(), subtractFromRGB(), and upscale().