FastLED: CRGB::getAverageLight
getAverageLight()
FASTLED_FORCE_INLINE uint8_t CRGB::getAverageLight () const
Get the average of the R, G, and B values.
Examples
TwinkleFox.ino.
Definition at line 149 of file crgb.hpp.
{
#if FASTLED_SCALE8_FIXED == 1
    const uint8_t eightyfive = 85;
#else
    const uint8_t eightyfive = 86;
#endif
    uint8_t avg = scale8_LEAVING_R1_DIRTY( r, eightyfive) + \
    scale8_LEAVING_R1_DIRTY( g, eightyfive) + \
    scale8_LEAVING_R1_DIRTY( b, eightyfive);
    cleanup_R1();
    return avg;
}
References cleanup_R1(), FASTLED_FORCE_INLINE, and scale8_LEAVING_R1_DIRTY().
Referenced by fl::TwinkleFox::drawTwinkleFox(), and drawTwinkles().