FastLED: CRGB::upscale
upscale()
void CRGB::upscale (const CRGB * src, const fl::XYMap & srcXY, CRGB * dst, const fl::XYMap & dstXY) static
Definition at line 78 of file crgb.cpp.
{
    FASTLED_WARN_IF(
        srcXY.getType() != fl::XYMap::kLineByLine,
        "Upscaling only works with a src matrix that is rectangular");
    uint16_t w = srcXY.getWidth();
    uint16_t h = srcXY.getHeight();
    fl::bilinearExpand(src, dst, w, h, dstXY);
}
References CRGB(), fl::bilinearExpand(), FASTLED_WARN_IF, fl::XYMap::getHeight(), fl::XYMap::getType(), fl::XYMap::getWidth(), and fl::XYMap::kLineByLine.