FastLED: CRGB::nscale8_video
nscale8_video()
FASTLED_FORCE_INLINE CRGB & CRGB::nscale8_video (fl::u8 scaledown)
Scale down a RGB to N/256ths of it's current brightness using "video" dimming rules.
"Video" dimming rules means that unless the scale factor is ZERO each channel is guaranteed NOT to dim down to zero. If it's already nonzero, it'll stay nonzero, even if that means the hue shifts a little at low brightness levels.
See also
nscale8x3_video
Examples
TwinkleFox.ino.
References CRGB(), and FASTLED_FORCE_INLINE.
Referenced by fl::TwinkleFox::drawTwinkleFox(), drawTwinkles(), and operator%().