FastLED: CRGB::colorBoost
colorBoost() [2/2]
FASTLED_NAMESPACE_BEGIN CRGB CRGB::colorBoost (fl::EaseType saturation_function = fl::EASE_NONE, fl::EaseType luminance_function = fl::EASE_NONE) const
Definition at line 11 of file crgb_hsv16.cpp.
{
    fl::HSV16 hsv(*this);
    return hsv.colorBoost(saturation_function, luminance_function);
}
References CRGB(), and fl::HSV16::colorBoost().
Referenced by colorBoost(), draw(), fillFrameBufferFire(), fillFrameBufferNoise(), and rainbowWave().