FastLED: fl::LineSimplifier::simplifyT
simplifyT()
template<typename NumberT = float> template<typename VectorType> void fl::LineSimplifier< NumberT >::simplifyT (const fl::Slice< const Point > & polyLine, VectorType * out) inline private
Definition at line 120 of file line_simplification.h.
{
        // run the simplification algorithm
        simplifyInternal(polyLine);
        // copy the result to the output slice
        out->assign(mSimplified.begin(), mSimplified.end());
    }
References mSimplified, and simplifyInternal().
Referenced by simplify(), simplify(), and simplifyInplaceT().