FastLED: fl::fl_random::random8
random8() [1/3]
u8 fl::fl_random::random8 () inline
Generate an 8-bit random number.
Returns
A random 8-bit unsigned integer (0-255)
Definition at line 109 of file random.h.
                 {
        u16 r = next_random16();
        // return the sum of the high and low bytes, for better mixing
        return (u8)(((u8)(r & 0xFF)) + ((u8)(r >> 8)));
    }
References next_random16().
Referenced by random8(), and random8().