FastLED: fl::fl_random::next_random16
next_random16()
u16 fl::fl_random::next_random16 () inline private
Generate next 16-bit random number using this instance's seed.
Returns
The next 16-bit random number
Definition at line 27 of file random.h.
{
        seed_ = APPLY_FASTLED_RAND16_2053(seed_) + FASTLED_RAND16_13849;
        return seed_;
    }
References APPLY_FASTLED_RAND16_2053, FASTLED_RAND16_13849, and seed_.
Referenced by next_random32(), random16(), and random8().