FastLED: fl::Fx2d::Fx2d
Fx2d()
fl::Fx2d::Fx2d (const XYMap & xyMap) inline
Definition at line 20 of file fx2d.h.
: Fx(xyMap.getTotal()), mXyMap(xyMap) {}
References fl::Fx::Fx(), mXyMap, and xyMap().
Referenced by fl::Animartrix::Animartrix(), fl::Blend2d::Blend2d(), fl::NoisePalette::NoisePalette(), fl::RedSquare::RedSquare(), fl::ScaleUp::ScaleUp(), fl::WaveFx::WaveFx(), fl::Blend2d::add(), and fl::Blend2d::setParams().