FastLED: fl::Fx2d::xyMap
xyMap()
uint16_t fl::Fx2d::xyMap (uint16_t x, uint16_t y) const inline
Definition at line 21 of file fx2d.h.
{
        return mXyMap.mapToIndex(x, y);
    }
References mXyMap, x, and y.
Referenced by fl::Animartrix::Animartrix(), Fx2d(), fl::NoisePalette::NoisePalette(), fl::Blend2d::draw(), and setXYMap().