FastLED: fl::WLED::getPlaylistConfig
getPlaylistConfig()
fl::json fl::WLED::getPlaylistConfig () const
Get playlist configuration.
Returns
JSON object with playlist settings (ps, dur, transition, repeat, end, r)
Definition at line 510 of file wled.cpp.hpp.
{
    fl::json playlist = fl::json::object();
    // Preset IDs
    if (!mPlaylistPresets.empty()) {
        fl::json ps = fl::json::array();
        for (const auto& preset : mPlaylistPresets) {
            ps.push_back(fl::json(static_cast<i64>(preset)));
        }
        playlist.set("ps", ps);
    }
    // Durations
    if (!mPlaylistDurations.empty()) {
        fl::json dur = fl::json::array();
        for (const auto& duration : mPlaylistDurations) {
            dur.push_back(fl::json(static_cast<i64>(duration)));
        }
        playlist.set("dur", dur);
    }
    // Transitions
    if (!mPlaylistTransitions.empty()) {
        fl::json trans = fl::json::array();
        for (const auto& transition : mPlaylistTransitions) {
            trans.push_back(fl::json(static_cast<i64>(transition)));
        }
        playlist.set("transition", trans);
    }
    // Other properties
    playlist.set("repeat", static_cast<i64>(mPlaylistRepeat));
    playlist.set("end", static_cast<i64>(mPlaylistEnd));
    playlist.set("r", mPlaylistRandomize);
    return playlist;
}
References fl::json::array(), mPlaylistDurations, mPlaylistEnd, mPlaylistPresets, mPlaylistRandomize, mPlaylistRepeat, mPlaylistTransitions, fl::json::object(), ps, fl::json::push_back(), fl::json::set(), and transition().
Referenced by getState().