FastLED: fl::WLED::getState
getState()
fl::json fl::WLED::getState () const
Get current WLED state as JSON object.
Returns
JSON object with "on" and "bri" fields
Example: fl::json state = remote.getState(); // Returns: {"on":true,"bri":128}
Definition at line 405 of file wled.cpp.hpp.
{
    fl::json state = fl::json::object();
    state.set("on", mWledOn);
    state.set("bri", static_cast<i64>(mWledBri));
    state.set("transition", static_cast<i64>(mTransition));
    state.set("ps", static_cast<i64>(mPreset));
    state.set("pl", static_cast<i64>(mPlaylist));
    state.set("lor", static_cast<i64>(mLiveOverride));
    state.set("mainseg", static_cast<i64>(mMainSegment));
    // Nightlight object
    fl::json nl = fl::json::object();
    nl.set("on", mNightlightOn);
    nl.set("dur", static_cast<i64>(mNightlightDuration));
    nl.set("mode", static_cast<i64>(mNightlightMode));
    nl.set("tbri", static_cast<i64>(mNightlightTargetBrightness));
    state.set("nl", nl);
    // UDP sync settings
    fl::json udpn = fl::json::object();
    udpn.set("send", mUdpSend);
    udpn.set("recv", mUdpReceive);
    state.set("udpn", udpn);
    // Playlist configuration (if present)
    if (hasPlaylistConfig()) {
        state.set("playlist", getPlaylistConfig());
    }
    // Segments
    if (!mSegments.empty()) {
        fl::json segments = fl::json::array();
        for (const auto& seg : mSegments) {
            fl::json segJson = fl::json::object();
            segJson.set("id", static_cast<i64>(seg.mId));
            segJson.set("start", static_cast<i64>(seg.mStart));
            segJson.set("stop", static_cast<i64>(seg.mStop));
            segJson.set("len", static_cast<i64>(seg.mLen));
            segJson.set("grp", static_cast<i64>(seg.mGrp));
            segJson.set("spc", static_cast<i64>(seg.mSpc));
            segJson.set("of", static_cast<i64>(seg.mOf));
            segJson.set("on", seg.mOn);
            segJson.set("bri", static_cast<i64>(seg.mBri));
            segJson.set("cct", static_cast<i64>(seg.mCct));
            // Effect properties
            segJson.set("fx", static_cast<i64>(seg.mFx));
            segJson.set("sx", static_cast<i64>(seg.mSx));
            segJson.set("ix", static_cast<i64>(seg.mIx));
            segJson.set("pal", static_cast<i64>(seg.mPal));
            segJson.set("c1", static_cast<i64>(seg.mC1));
            segJson.set("c2", static_cast<i64>(seg.mC2));
            segJson.set("c3", static_cast<i64>(seg.mC3));
            // Boolean flags
            segJson.set("sel", seg.mSel);
            segJson.set("rev", seg.mRev);
            segJson.set("mi", seg.mMi);
            segJson.set("o1", seg.mO1);
            segJson.set("o2", seg.mO2);
            segJson.set("o3", seg.mO3);
            segJson.set("si", static_cast<i64>(seg.mSi));
            segJson.set("m12", static_cast<i64>(seg.mM12));
            segJson.set("rpt", seg.mRpt);
            if (!seg.mName.empty()) {
                segJson.set("n", seg.mName);
            }
            // Colors
            if (!seg.mColors.empty()) {
                fl::json colors = fl::json::array();
                for (const auto& color : seg.mColors) {
                    if (color.size() >= 3) {
                        fl::json colorArray = fl::json::array();
                        for (size_t i = 0; i < color.size(); i++) {
                            colorArray.push_back(fl::json(static_cast<i64>(color[i])));
                        }
                        colors.push_back(colorArray);
                    }
                }
                segJson.set("col", colors);
            }
            // Individual LEDs
            if (!seg.mIndividualLeds.empty()) {
                fl::json leds = fl::json::array();
                for (const auto& led : seg.mIndividualLeds) {
                    if (led.size() >= 3) {
                        fl::string hexColor = wled::rgbToHex(led[0], led[1], led[2]);
                        leds.push_back(fl::json(hexColor.c_str()));
                    }
                }
                segJson.set("i", leds);
            }
            segments.push_back(segJson);
        }
        state.set("seg", segments);
    }
    return state;
}
References fl::json::array(), fl::basic_string::c_str(), getPlaylistConfig(), hasPlaylistConfig(), leds, mLiveOverride, mMainSegment, mNightlightDuration, mNightlightMode, mNightlightOn, mNightlightTargetBrightness, mPlaylist, mPreset, mSegments, mTransition, mUdpReceive, mUdpSend, mWledBri, mWledOn, fl::json::object(), fl::json::push_back(), fl::wled::rgbToHex(), fl::json::set(), and state.