FastLED: PrintPins
PrintPins()
template<uint8_t PIN> void PrintPins ()
Examples
Pintest.ino.
Definition at line 141 of file Pintest.ino.
{
    PrintPins<PIN - 1>();
    RwReg *systemThinksPortIs = portOutputRegister(digitalPinToPort(PIN));
    RwReg systemThinksMaskIs = digitalPinToBitMask(PIN);
    int maskBit = 0;
    while(systemThinksMaskIs > 1) { systemThinksMaskIs >>= 1; maskBit++; }
    const char *pinport = GetPinPort((void*)systemThinksPortIs);
    if (pinport) {
        Serial.print("__FL_DEFPIN("); Serial.print(PIN);
        Serial.print(","); Serial.print(maskBit);
        Serial.print(","); Serial.print(pinport);
        Serial.print("); ");
        pcount++;
        if(pcount == 4) { pcount = 0; Serial.println(""); }
    } else {
        // Serial.print("Not found for pin "); Serial.println(PIN);
    }
}
References GetPinPort(), pcount, PIN, and PrintPins().
Referenced by loop(), and PrintPins().