FastLED: CheckPin
CheckPin()
template<uint8_t PIN> void CheckPin ()
Examples
Pintest.ino.
Definition at line 96 of file Pintest.ino.
{
    CheckPin<PIN - 1>();
    void *systemThinksPortIs = (void*)portOutputRegister(digitalPinToPort(PIN));
    RwReg systemThinksMaskIs = digitalPinToBitMask(PIN);
    Serial.print("Pin "); Serial.print(PIN); Serial.print(": Port ");
    if(systemThinksPortIs == (void*)FastPin<PIN>::port()) {
        Serial.print("valid & mask ");
    } else {
        Serial.print("invalid, is "); Serial.print(getPort((void*)FastPin<PIN>::port())); Serial.print(" should be ");
        Serial.print(getPort((void*)systemThinksPortIs));
        Serial.print(" & mask ");
    }
    if(systemThinksMaskIs == FastPin<PIN>::mask()) {
        Serial.println("valid.");
    } else {
        Serial.print("invalid, is "); Serial.print(FastPin<PIN>::mask()); Serial.print(" should be "); Serial.println(systemThinksMaskIs);
    }
}
References CheckPin(), getPort(), FastPin< PIN >::mask(), PIN, and FastPin< PIN >::port().
Referenced by CheckPin(), and loop().