FastLED: fl::audio::detector::Transient::update
update() [2/2]
void fl::audio::detector::Transient::update (shared_ptr< Context > context) override virtual
Implements fl::audio::Detector.
Definition at line 27 of file transient.cpp.hpp.
{
    mRetainedFFT = context->getFFT16();
    const fft::Bins& fft = *mRetainedFFT;
    u32 timestamp = context->getTimestamp();
    // Calculate high-frequency energy (transients have strong high-freq components)
    mCurrentEnergy = calculateHighFreqEnergy(fft);
    // Calculate energy flux (rate of change)
    float flux = calculateEnergyFlux(mCurrentEnergy);
    // Detect transient
    mTransientDetected = detectTransient(flux, timestamp);
    if (mTransientDetected) {
        updateAttackTime(flux);
        mLastTransientTime = timestamp;
    }
    // Update previous energy for next frame
    mPreviousEnergy = mCurrentEnergy;
    // Filter energy through HampelFilter to reject outliers before history
    float filteredEnergy = mEnergyOutlierFilter.update(mCurrentEnergy);
    // Update energy history with outlier-rejected values
    if (mEnergyHistory.size() >= ENERGY_HISTORY_SIZE) {
        mEnergyHistory.pop_front();
    }
    mEnergyHistory.push_back(filteredEnergy);
}
References Transient(), calculateEnergyFlux(), calculateHighFreqEnergy(), detectTransient(), ENERGY_HISTORY_SIZE, mCurrentEnergy, mEnergyHistory, mEnergyOutlierFilter, mLastTransientTime, mPreviousEnergy, mRetainedFFT, mTransientDetected, update(), and updateAttackTime().
Referenced by ~Transient(), update(), and update().