FastLED: fl::UINumberField::setValue
setValue()
void fl::UINumberField::setValue (double value) inline
Definition at line 121 of file ui.h.
{ mValue = MAX(mMin, MIN(mMax, value)); }
References MAX, MIN, mMax, mMin, mValue, and value().
Referenced by operator=(), and operator=().