FastLED: set_power_model
set_power_model() [1/3]
void set_power_model (const PowerModelRGB & model)
Set custom RGB LED power consumption model.
Parameters
model RGB power consumption model. The model's exponent field drives the brightness-to-power response curve used by estimation and limiting; pass PowerModelRGB(r, g, b, d, e) to set channel weights + response curve in a single call.
Note
exponent <= 0 or values within 1e-4 of 1.0 fall back to linear (identity tables) rather than rebuilding with a degenerate curve.
Definition at line 275 of file power_mgt.cpp.hpp.
{
    gPowerModel() = model;
#if SKETCH_HAS_LARGE_MEMORY
    rebuild_power_scaling_tables(model.exponent);
#else
    // Small-memory targets ignore non-linear exponent and keep linear behavior;
    // clamp the stored field so get_power_scaling_exponent() reports the truth.
    gPowerModel().exponent = kLinearPowerScalingExponent;
#endif
}
References PowerModelRGB::exponent, gPowerModel(), and kLinearPowerScalingExponent.
Referenced by set_power_model(), set_power_model(), set_power_scaling_exponent(), CFastLED::setPowerModel(), CFastLED::setPowerModel(), and CFastLED::setPowerModel().