FastLED: AutoResearchRemoteControl::startBleRemote
startBleRemote()
fl::json AutoResearchRemoteControl::startBleRemote ()
Start BLE remote (creates BLE GATT server + second Remote instance)
Returns
JSON result from startBle()
Definition at line 3662 of file AutoResearchRemote.cpp.
{
    if (mBleRemote) {
        fl::json response = fl::json::object();
        response.set("success", true);
        response.set("message", "BLE remote already active");
        response.set("device_name", AUTORESEARCH_BLE_DEVICE_NAME);
        return response;
    }
    // Create BLE GATT server (heap-allocates transport state)
    // On stub platforms, createTransport returns nullptr and logs FL_ERROR.
    mBleState = fl::net::ble::createTransport(AUTORESEARCH_BLE_DEVICE_NAME);
    if (!mBleState) {
        fl::json response = fl::json::object();
        response.set("success", false);
        response.set("error", "BLE not available on this platform");
        return response;
    }
    // Get transport lambdas that capture mBleState
    auto callbacks = fl::net::ble::getTransportCallbacks(mBleState);
    // Create BLE Remote instance with BLE transport
    mBleRemote = fl::make_unique<fl::Remote>(callbacks.first, callbacks.second);
    // Register RPC methods on the BLE remote
    registerAllMethods(mBleRemote.get());
    mState->ble_server_active = true;
    getBleState().ble_server_active = true;
    fl::json response = fl::json::object();
    response.set("success", true);
    response.set("device_name", AUTORESEARCH_BLE_DEVICE_NAME);
    response.set("service_uuid", FL_BLE_SERVICE_UUID);
    response.set("rx_uuid", FL_BLE_CHAR_RX_UUID);
    response.set("tx_uuid", FL_BLE_CHAR_TX_UUID);
    FL_WARN("[BLE] Remote created and advertising");
    return response;
}
References AUTORESEARCH_BLE_DEVICE_NAME, AutoResearchBleState::ble_server_active, fl::net::ble::createTransport(), FL_BLE_CHAR_RX_UUID, FL_BLE_CHAR_TX_UUID, FL_BLE_SERVICE_UUID, FL_WARN, getBleState(), fl::net::ble::getTransportCallbacks(), fl::make_unique(), mBleRemote, mBleState, mState, fl::json::object(), and registerAllMethods().
Referenced by registerFunctions().