FastLED: AutoResearchRemoteControl::tick
tick()
void AutoResearchRemoteControl::tick (uint32_t current_millis)
Process RPC system (pull + tick + push)
Parameters
current_millis Current timestamp in milliseconds
Note
This function is automatically called by the async task registered in setup()
Definition at line 3614 of file AutoResearchRemote.cpp.
{
    if (mRemote) {
        // Remote::update() does pull + tick + push
        mRemote->update(current_millis);
    }
    if (mBleRemote) {
        mBleRemote->update(current_millis);
    }
    // Deferred BLE teardown: stopBle RPC sets this flag so the response
    // is sent (via push() above) before we call ble::destroyTransport().
    if (mPendingBleStop) {
        mPendingBleStop = false;
        mBleRemote.reset();  // destroy lambdas before freeing state they capture
        fl::net::ble::destroyTransport(mBleState);
        mBleState = nullptr;
        mState->ble_server_active = false;
        getBleState().ble_server_active = false;
        FL_WARN("[BLE] Deferred teardown complete");
    }
}
References AutoResearchBleState::ble_server_active, fl::net::ble::destroyTransport(), FL_WARN, getBleState(), mBleRemote, mBleState, mPendingBleStop, mRemote, and mState.
Referenced by autoresearch::setupRpcAsyncTask().