FastLED: XY
XY()
int XY (int x, int y)
Definition at line 190 of file funky.cpp.
                     {
    if (y > HEIGHT) {
        y = HEIGHT;
    }
    if (y < 0) {
        y = 0;
    }
    if (x > WIDTH) {
        x = WIDTH;
    }
    if (x < 0) {
        x = 0;
    }
    // for a serpentine layout reverse every 2nd row:
    if (x % 2 == 1) {
        return (x * (WIDTH) + (HEIGHT - y - 1));
    } else {
        // use that line only, if you have all rows beginning at the same side
        return (x * (WIDTH) + y);
    }
}
References HEIGHT, WIDTH, x, and y.
Referenced by Audio3(), AudioSpiral(), Caleidoscope1(), Caleidoscope2(), Caleidoscope3(), Caleidoscope4(), Caleidoscope5(), Caleidoscope6(), Copy(), Dots1(), HorizontalStream(), Line(), MirrorTriangle(), MSGEQtest9(), NoiseExample1(), NoiseExample2(), NoiseExample3(), NoiseExample4(), NoiseExample5(), NoiseExample6(), NoiseExample7(), NoiseExample8(), Pixel(), RenderCustomMatrix(), RotateTriangle(), Scale(), SpiralStream(), VerticalMove(), and VerticalStream().