FastLED: Pixel
Pixel()
void Pixel (int x, int y, byte color)
Definition at line 234 of file funky.cpp.
{ leds[XY(x, y)] = CHSV(color, 255, 255); }
References leds, x, XY(), and y.
Referenced by Dots1(), Dots2(), Mandala8(), MSGEQtest(), MSGEQtest2(), MSGEQtest3(), MSGEQtest4(), MSGEQtest7(), MSGEQtest8(), RainbowTriangle(), SlowMandala(), SlowMandala2(), and SlowMandala3().