FastLED: Dots1
Dots1()
void Dots1 ()
Definition at line 642 of file funky.cpp.
             {
    MoveOscillators();
    // 2 lissajous dots red
    leds[XY(p[0], p[1])] = CHSV(1, 255, 255);
    leds[XY(p[2], p[3])] = CHSV(1, 255, 150);
    // average of the coordinates in yellow
    Pixel((p[2] + p[0]) / 2, (p[1] + p[3]) / 2, 50);
    ShowFrame();
    HorizontalStream(125);
}
References HorizontalStream(), leds, MoveOscillators(), p, Pixel(), ShowFrame(), and XY().