FastLED: NoiseExample1
NoiseExample1()
void NoiseExample1 ()
Definition at line 1024 of file funky.cpp.
                     {
    MoveOscillators();
    scale2 = 30 + p[1] * 3;
    x = p[0] * 16;
    fillnoise8();
    fillnoise82();
    for (int i = 0; i < kMatrixWidth; i++) {
        for (int j = 0; j < kMatrixHeight; j++) {
            leds[XY(i, j)] =
                CHSV(noise[i][j] << 1, 255, (noise2[i][j] + noise[i][j]) / 2);
        }
    }
    ShowFrame();
}
References fillnoise8(), fillnoise82(), kMatrixHeight, kMatrixWidth, leds, MoveOscillators(), noise, noise2, p, scale2, ShowFrame(), x, and XY().