FastLED: FillNoise
FillNoise()
void FillNoise (uint16_t x, uint16_t y, uint16_t z, uint16_t scale)
Definition at line 1040 of file funky.cpp.
{
    for (int i = 0; i < MAX_DIMENSION; i++) {
        int ioffset = scale * i;
        for (int j = 0; j < MAX_DIMENSION; j++) {
            int joffset = scale * j;
            noise[i][j] = inoise8(x + ioffset, y + joffset, z);
        }
    }
}
References inoise8(), MAX_DIMENSION, noise, scale, x, y, and z.
Referenced by NoiseExample2(), NoiseExample3(), NoiseExample4(), NoiseExample5(), NoiseExample6(), NoiseExample7(), and NoiseExample8().