FastLED: NoiseExample3
NoiseExample3()
void NoiseExample3 ()
Definition at line 1067 of file funky.cpp.
                     {
    MoveOscillators();
    FillNoise(p[1] * 100, p[2] * 100, 100, 100);
    for (int i = 0; i < p[1]; i++) {
        for (int j = 0; j < kMatrixHeight; j++) {
            leds[XY(i, j)] = CHSV(noise[i][j], 255, 200);
        }
    }
    for (int i = 0; i < p[3]; i++) {
        for (int j = 0; j < kMatrixHeight; j++) {
            leds[XY(j, i)] += CHSV(128 + noise[i][j], 255, 200);
        }
    }
    ShowFrame();
    ClearAll();
}
References ClearAll(), FillNoise(), kMatrixHeight, leds, MoveOscillators(), noise, p, ShowFrame(), and XY().