FastLED: MSGEQtest7
MSGEQtest7()
void MSGEQtest7 ()
Definition at line 798 of file funky.cpp.
                  {
    MoveOscillators();
    ReadAudio();
    for (int i = 0; i < 7; i++) {
        Pixel(7 - i, 8 - right[i] / 128, i * 10 + right[1] / 8);
    }
    Caleidoscope5();
    Caleidoscope1();
    ShowFrame();
    DimAll(240);
}
References Caleidoscope1(), Caleidoscope5(), DimAll(), MoveOscillators(), Pixel(), ReadAudio(), right, and ShowFrame().