FastLED: NoiseExample8
NoiseExample8()
void NoiseExample8 ()
Definition at line 1284 of file funky.cpp.
                     {
    ChangePalettePeriodically();
    x++;
    z++;
    FillNoise(x * 3, x * 3, z, sin8(x) >> 1);
    for (int i = 0; i < kMatrixWidth; i++) {
        for (int j = 0; j < kMatrixHeight; j++) {
            leds[XY(i, j)] = ColorFromPalette(currentPalette, noise[i][j], 255,
                                              currentBlending);
        }
    }
    ShowFrame();
}
References ChangePalettePeriodically(), ColorFromPalette(), currentBlending, currentPalette, FillNoise(), kMatrixHeight, kMatrixWidth, leds, noise, ShowFrame(), sin8, x, XY(), and z.