FastLED: fl::result::value
value() [2/2]
template<typename T> const T & fl::result< T >::value () const inline
Get the success value (const)
Returns
Reference to the success value
Warning
Returns static empty object if called on an error result
Note
Use ok() to check before calling for proper error handling
Definition at line 76 of file promise_result.h.
{
        if (!ok()) {
            // Return static empty object instead of crashing
            static const T empty{};
            return empty;
        }
        return mResult.template get<T>();
    }
References fl::get(), mResult, and ok().
Referenced by result(), result(), test_await_approach(), and test_json_await().