FastLED: fl::spi::MultiLaneDevice::lane
lane()
Lane & fl::spi::MultiLaneDevice::lane (size_t lane_id)
Get access to a specific lane.
Parameters
lane_id Lane index (0 to numLanes()-1)
Returns
Reference to Lane object
Note
Panics if lane_id is out of range
Definition at line 287 of file multi_lane_device.cpp.hpp.
{
    if (!pImpl || lane_id >= pImpl->lanes.size()) {
        FL_WARN("MultiLaneDevice: Invalid lane ID " << lane_id);
        // Return first lane as fallback (avoid crash)
        static Lane dummy_lane(0, nullptr); // okay static in header
        return dummy_lane;
    }
    return pImpl->lanes[lane_id];
}
References FL_WARN, and pImpl.
Referenced by end(), flush(), and operator=().