FastLED: fl::spi::MultiLaneDevice::MultiLaneDevice
MultiLaneDevice() [1/3]
fl::spi::MultiLaneDevice::MultiLaneDevice (const Config & config) explicit
Construct multi-lane device.
Parameters
config Configuration with 1-8 data pins
Definition at line 59 of file multi_lane_device.cpp.hpp.
    : pImpl(fl::make_unique<Impl>(config)) {
    // Validate configuration
    size_t num_lanes = config.data_pins.size();
    if (num_lanes < 1 || num_lanes > 8) {
        FL_WARN("MultiLaneDevice: Invalid number of data pins (" << num_lanes
                << "), must be 1-8");
    }
    FL_DBG("MultiLaneDevice: Created with " << num_lanes << " lane(s)");
}
References fl::spi::MultiLaneDevice::Config::data_pins, FL_DBG, FL_WARN, fl::make_unique(), pImpl, and fl::vector_basic::size().
Referenced by MultiLaneDevice(), MultiLaneDevice(), operator=(), and operator=().