FastLED: fl::FxCompositor::draw
draw()
void fl::FxCompositor::draw (fl::u32 now, fl::u32 warpedTime, fl::span< CRGB > finalBuffer, float speed = 1.0f, const AudioBatch * audio = nullptr) inline
Definition at line 60 of file fx_compositor.h.
{
    if (!mLayers[0]->getFx()) {
        return;
    }
    mLayers[0]->draw(warpedTime, speed, audio);
    u8 progress = mTransition.getProgress(now);
    if (!progress) {
        fl::span<CRGB> surface0 = mLayers[0]->getSurface();
        fl::memcpy(finalBuffer.data(), surface0.data(), sizeof(CRGB) * mNumLeds);
        return;
    }
    mLayers[1]->draw(warpedTime, speed, audio);
    fl::span<CRGB> surface0 = mLayers[0]->getSurface();
    fl::span<CRGB> surface1 = mLayers[1]->getSurface();
    for (fl::u32 i = 0; i < mNumLeds; i++) {
        const CRGB &p0 = surface0[i];
        const CRGB &p1 = surface1[i];
        CRGB out = CRGB::blend(p0, p1, progress);
        finalBuffer[i] = out;
    }
    if (progress == 255) {
        completeTransition();
    }
}
References fl::CRGB::blend(), completeTransition(), fl::span< T, Extent >::data(), fl::memcpy(), mLayers, mNumLeds, mTransition, and speed.