FastLED: fl::test::XMLReporter::testCaseEnd
testCaseEnd()
void fl::test::XMLReporter::testCaseEnd (bool passed, fl::u32 durationMs = 0) override virtual
Called when a test case ends.
Parameters
passed Whether the test passed
durationMs Duration of the test in milliseconds (0 if no timer available)
Implements fl::test::IReporter.
Definition at line 649 of file fltest.cpp.hpp.
{
    fl::sstream ss;
    ss << "  <testcase name=\"" << escapeXml(mCurrentTestName.c_str()) << "\"";
    // Add time attribute if duration is available (convert ms to seconds)
    if (durationMs > 0) {
        // Format as seconds with millisecond precision
        fl::u32 secs = durationMs / 1000;
        fl::u32 millis = durationMs % 1000;
        ss << " time=\"" << secs << "." << (millis < 100 ? (millis < 10 ? "00" : "0") : "") << millis << "\"";
    }
    if (passed) {
        ss << "/>\n";
    } else {
        ss << ">\n";
        ss << "    <failure message=\"Test failed\">\n";
        ss << "<![CDATA[" << mCurrentTestFailures << "]]>\n";
        ss << "    </failure>\n";
        ss << "  </testcase>\n";
    }
    mTestCaseResults.push_back(ss.str());
}
References escapeXml(), FL_NOEXCEPT, mCurrentTestFailures, mCurrentTestName, fl::millis(), mTestCaseResults, and fl::sstream::str().