#ifdef GPIOA
_FL_IO(A);
#endif
#ifdef GPIOB
_FL_IO(B);
#endif
#ifdef GPIOC
_FL_IO(C);
#endif
#ifdef GPIOD
_FL_IO(D);
#endif
#ifdef GPIOE
_FL_IO(E);
#endif
#ifdef GPIOF
_FL_IO(F);
#endif
#ifdef GPIOG
_FL_IO(G);
#endif

#define MAX_PIN 46

_FL_DEFPIN(PA0, 0, A);	// PA0 - PA7
_FL_DEFPIN(PA1, 1, A);
_FL_DEFPIN(PA2, 2, A);
_FL_DEFPIN(PA3, 3, A);
_FL_DEFPIN(PA4, 4, A);
_FL_DEFPIN(PA5, 5, A);
_FL_DEFPIN(PA6, 6, A);
_FL_DEFPIN(PA7, 7, A);
_FL_DEFPIN(PA8, 8, A);	// PA8 - PA15
_FL_DEFPIN(PA9, 9, A);
_FL_DEFPIN(PA10, 10, A);
_FL_DEFPIN(PA11, 11, A);
_FL_DEFPIN(PA12, 12, A);
_FL_DEFPIN(PA13, 13, A);
_FL_DEFPIN(PA14, 14, A);
_FL_DEFPIN(PA15, 15, A);

_FL_DEFPIN(PB0, 0, B);	// PB0 - PB11
_FL_DEFPIN(PB1, 1, B);
_FL_DEFPIN(PB2, 2, B);
_FL_DEFPIN(PB3, 3, B);
_FL_DEFPIN(PB4, 4, B);
_FL_DEFPIN(PB5, 5, B);
_FL_DEFPIN(PB6, 6, B);
_FL_DEFPIN(PB7, 7, B);
_FL_DEFPIN(PB8, 8, B);
_FL_DEFPIN(PB9, 9, B);
_FL_DEFPIN(PB10, 10, B);
_FL_DEFPIN(PB11, 11, B);

_FL_DEFPIN(PC13, 13, C);	// PC13 - PC15
_FL_DEFPIN(PC14, 14, C);
_FL_DEFPIN(PC15, 15, C);

#define SPI_DATA PIN_SPI_MOSI
#define SPI_CLOCK PIN_SPI_SCK

#define HAS_HARDWARE_PIN_SUPPORT
