FastLED: setup
setup()
void setup ()
Definition at line 55 of file Remote.ino.
             {
    Serial.begin(115200);
    while (!Serial) {
        ; // Wait for serial port to connect (needed for some boards)
    }
    FastLED.addLeds<WS2812, DATA_PIN, GRB>(leds, NUM_LEDS);
    // Register RPC functions (commands - no return value)
    remote.bind("setLed", [](int index, int r, int g, int b) {
        if (index >= 0 && index < NUM_LEDS) {
            leds[index] = CRGB(r, g, b);
            FL_DBG("Set LED " << index << " to RGB(" << r << ", " << g << ", " << b << ")");
        }
    });
    remote.bind("fill", [](int r, int g, int b) {
        fill_solid(leds, NUM_LEDS, CRGB(r, g, b));
        FL_DBG("Filled all LEDs with RGB(" << r << ", " << g << ", " << b << ")");
    });
    remote.bind("setBrightness", [](int brightness) {
        FastLED.setBrightness(brightness);
        FL_DBG("Set brightness to " << brightness);
    });
    // Register RPC query functions (with return values)
    // Match Arduino function names for consistency
    remote.bind("millis", []() -> int64_t {
        return static_cast<int64_t>(millis());
    });
    remote.bind("micros", []() -> int64_t {
        return static_cast<int64_t>(micros());
    });
    remote.bind("getStatus", []() -> fl::json {
        fl::json result = fl::json::object();
        result.set("numLeds", NUM_LEDS);
        result.set("brightness", FastLED.getBrightness());
        result.set("millis", static_cast<int64_t>(millis()));
        return result;
    });
    remote.bind("getLed", [](int index) -> fl::json {
        fl::json result = fl::json::object();
        if (index >= 0 && index < NUM_LEDS) {
            result.set("r", leds[index].r);
            result.set("g", leds[index].g);
            result.set("b", leds[index].b);
        } else {
            result.set("error", "Index out of range");
        }
        return result;
    });
    Serial.println("Remote RPC example ready");
    Serial.println();
    // Show schema (flat tuple format optimized for low-memory devices)
    Serial.println("=== RPC Schema ===");
    fl::json schema = remote.schema();
    fl::string schemaStr = schema.to_string();
    Serial.print("Schema size: ");
    Serial.print(schemaStr.size());
    Serial.println(" bytes (flat tuple format)");
    Serial.println();
    Serial.println("Send JSON over serial, e.g.:");
    Serial.println("  Commands (no return):");
    Serial.println(R"(    {"function":"fill","args":[255,0,0]})");
    Serial.println(R"(    {"timestamp":5000,"function":"setBrightness","args":[64]})");
    Serial.println("  Queries (with return):");
    Serial.println(R"(    {"function":"millis","args":[]})");
    Serial.println(R"(    {"function":"getStatus","args":[]})");
    Serial.println(R"(    {"function":"getLed","args":[0]})");
    Serial.println("  Schema:");
    Serial.println(R"raw(    {"method":"rpc.discover","id":1})raw"  " // Get RPC schema");
}
References brightness, DATA_PIN, FastLED, fill_solid(), FL_DBG, GRB, leds, NUM_LEDS, fl::json::object(), remote, Serial, fl::basic_string::size(), and fl::json::to_string().