FastLED: fl::anonymous_namespace{chasing_spirals.cpp.hpp}::simd4_processChannel
simd4_processChannel()
simd::simd_u32x4 fl::anonymous_namespace{chasing_spirals.cpp.hpp}::simd4_processChannel (simd::simd_u32x4 base_vec, simd::simd_u32x4 dist_vec, i32 radial_offset, i32 linear_offset, const i32 * fade_lut, const u8 * perm, i32 cx_raw, i32 cy_raw, simd::simd_u32x4 rf_vec)
Definition at line 108 of file chasing_spirals.cpp.hpp.
{
    constexpr i32 RAD_TO_A24 = 2670177;
    // Angle conversion: Q16.16 → A24
    auto offset_vec    = simd::set1_u32_4(static_cast<u32>(radial_offset));
    auto sum_vec       = simd::add_i32_4(base_vec, offset_vec);
    auto rad_const_vec = simd::set1_u32_4(static_cast<u32>(RAD_TO_A24));
    auto angles_vec    = simd::mulhi_su32_4(sum_vec, rad_const_vec);
    SinCos32_simd sc = sincos32_simd(angles_vec);
    // Perlin coordinates: nx = lin+cx - cos*dist, ny = cy - sin*dist
    auto lin_cx  = simd::set1_u32_4(static_cast<u32>(linear_offset + cx_raw));
    auto cy_vec  = simd::set1_u32_4(static_cast<u32>(cy_raw));
    auto nx_vec  = simd::sub_i32_4(lin_cx,
        simd::sll_u32_4(simd::mulhi32_i32_4(sc.cos_vals, dist_vec), 1));
    auto ny_vec  = simd::sub_i32_4(cy_vec,
        simd::sll_u32_4(simd::mulhi32_i32_4(sc.sin_vals, dist_vec), 1));
    // Perlin noise (SIMD floor/frac/wrap, scalar fade/perm/grad/lerp per lane)
    auto raw_vec = perlin_s16x16_simd::pnoise2d_raw_simd4_vec(
        nx_vec, ny_vec, fade_lut, perm);
    // Clamp [0, FP_ONE], scale ×255, apply radial filter, clamp [0, 255]
    auto zero   = simd::set1_u32_4(0u);
    auto fp_one = simd::set1_u32_4(static_cast<u32>(static_cast<i32>(1) << FP::FRAC_BITS));
    auto clamped = simd::min_i32_4(simd::max_i32_4(raw_vec, zero), fp_one);
    auto noise_scaled = simd::sub_i32_4(simd::sll_u32_4(clamped, 8), clamped);
    auto max255 = simd::set1_u32_4(255u);
    auto result = simd::mulhi32_i32_4(noise_scaled, rf_vec);
    return simd::min_i32_4(simd::max_i32_4(result, zero), max255);
}
References fl::s16x16::FRAC_BITS, fl::perlin_s16x16_simd::pnoise2d_raw_simd4_vec(), simd4_processChannel(), and fl::sincos32_simd().
Referenced by simd4_processChannel().