FastLED: rainbowWave
rainbowWave()
void rainbowWave ()
Definition at line 93 of file ColorBoost.h.
                   {
    // Use millis() for consistent timing across different devices
    // Scale down millis() to get appropriate animation speed
    uint16_t time = fl::millis() / 16;  // Adjust divisor to control wave speed
    uint8_t hueOffset = fl::millis() / 32; // Adjust divisor to control hue rotation speed
    // Iterate through the entire matrix
    for (uint16_t y = 0; y < HEIGHT; y++) {
        for (uint16_t x = 0; x < WIDTH; x++) {
            // Create a wave pattern using sine function based on position and time
            uint8_t wave = sin8(time + (x * 8));
            // Calculate hue based on position and time for rainbow effect
            uint8_t hue = hueOffset + (x * 255 / WIDTH);
            // Use wave for both saturation and brightness variation
            // uint8_t sat = 255 - (wave / 4); // Subtle saturation variation
            uint8_t bri = 128 + (wave / 2); // Brightness wave from 128 to 255
            // Create the original color using HSV
            fl::CRGB original_color = CHSV(hue, satSlider.value(), bri);
            if (y > HEIGHT / 3 * 2) {
                // Upper third - original colors
                leds[xyMap(x, y)] = original_color;
            } else if (y > HEIGHT / 3) {
                // Middle third - colors transformed with colorBoost()
                fl::EaseType sat_ease = getEaseType(saturationFunction.as_int());
                fl::EaseType lum_ease = getEaseType(luminanceFunction.as_int());
                leds[xyMap(x, y)] = original_color.colorBoost(sat_ease, lum_ease);
            } else {
                // Lower third - colors transformed using gamma correction
                float r = original_color.r / 255.f;
                float g = original_color.g / 255.f;
                float b = original_color.b / 255.f;
                r = fl::pow(r, 2.0f);
                g = fl::pow(g, 2.0f);
                b = fl::pow(b, 2.0f);
                r = r * 255.f;
                g = g * 255.f;
                b = b * 255.f;
                leds[xyMap(x, y)] = fl::CRGB(r, g, b);
            }
        }
    }
}
References fl::CRGB::colorBoost(), getEaseType(), HEIGHT, hue, leds, luminanceFunction(), fl::millis(), fl::pow(), satSlider(), saturationFunction(), WIDTH, x, xyMap, and y.
Referenced by loop().