FastLED: fl::FFT_Args::FFT_Args
FFT_Args()
fl::FFT_Args::FFT_Args (int samples = DefaultSamples(), int bands = DefaultBands(), float fmin = DefaultMinFrequency(), float fmax = DefaultMaxFrequency(), int sample_rate = DefaultSampleRate()) inline
Definition at line 48 of file fft.h.
{
        // Memset so that this object can be hashed without garbage from packed
        // in data.
        memset(this, 0, sizeof(FFT_Args));
        this->samples = samples;
        this->bands = bands;
        this->fmin = fmin;
        this->fmax = fmax;
        this->sample_rate = sample_rate;
    }
References FFT_Args(), bands, fmax, fmin, sample_rate, and samples.
Referenced by FFT_Args(), operator!=(), and operator==().