FastLED: setup
setup()
void setup ()
Definition at line 86 of file Sailboat.ino.
             {
    Serial.begin(115200);
    //FastLED.setExclusiveDriver(fl::Bus::SPI);
    fl::ChannelOptions opts;
    opts.mCorrection = TypicalLEDStrip;
    auto timing = fl::makeTimingConfig<fl::TIMING_WS2812_800KHZ>();
    fl::ClocklessChipset chipset(DATA_PIN, timing);
    fl::ChannelConfig config(chipset, fl::span<CRGB>(leds, NUM_LEDS), COLOR_ORDER, opts);
    config.setScreenMap(screenMap);
    FastLED.add(config);
    FastLED.setBrightness(BRIGHTNESS);
    // Group UI elements
    enableAmbient.setGroup("Features");
    enableMeteors.setGroup("Features");
    enableTimeWarp.setGroup("Features");
    meteorThreshold.setGroup("Audio Detection");
    ambientThreshold.setGroup("Audio Detection");
    dragSlider.setGroup("Physics");
    speedSlider.setGroup("Physics");
    minVelocitySlider.setGroup("Physics");
    ambientTrailSlider.setGroup("Trails");
    meteorTrailSlider.setGroup("Trails");
    ambientDecaySlider.setGroup("Trails");
    debrisDecaySlider.setGroup("Trails");
    debrisVelDecaySlider.setGroup("Trails");
    // Blue-white palettes
    CRGBPalette16 bluePalette(CRGB(0, 0, 40), CRGB(0, 40, 120),
                              CRGB(100, 160, 255), CRGB(255, 255, 255));
    sailboatFx.setNoisePalette(bluePalette);
    sailboatFx.setAmbientPalette(bluePalette);
    sailboatFx.setMeteorGradient(CRGB(255, 255, 255),  // white-hot head
                                 CRGB(140, 180, 255),   // light blue mid
                                 CRGB(0, 40, 120));     // deep blue tail
    // Register effect with engine
    fxEngine.addFx(sailboatFx);
    // --- Wire up audio detector callbacks ---
    // Uses the Vibe detector which self-normalizes bass levels:
    //   getVibeBass() ~1.0 = average for current song
    //   >1.0 = louder than average, <1.0 = quieter
    // This approach works across all music volumes and styles.
    auto audio = FastLED.add(audio_ui);
    fxEngine.setAudio(audio); // delivers AudioBatch to effects via DrawContext
    if (audio) {
        // Called every frame with full vibe data — we do threshold
        // checks here for both ambient and meteor spawning.
        audio->onVibeLevels(
            [&](const fl::audio::detector::VibeLevels &levels) {
                float bass = levels.bass; // self-normalizing, ~1.0 avg
                // Ambient: spawn on bass spikes above ambient threshold
                if (enableAmbient && levels.bassSpike &&
                    bass > ambientThreshold.value()) {
                    // Scale intensity: map bass from threshold..threshold*2
                    // to 0.3..1.0
                    float thresh = ambientThreshold.value();
                    float intensity =
                        fl::clamp((bass - thresh) / thresh, 0.3f, 1.0f);
                    int count = 1 + int(intensity * 2.0f); // 1-3 particles
                    for (int i = 0; i < count; i++) {
                        sailboatFx.spawnAmbient(intensity);
                    }
                }
                // Meteor: spawn only on very strong bass hits
                if (enableMeteors && levels.bassSpike &&
                    bass > meteorThreshold.value()) {
                    float thresh = meteorThreshold.value();
                    // Map bass from threshold..threshold*2 to 0.4..1.0
                    float intensity =
                        fl::clamp((bass - thresh) / thresh, 0.4f, 1.0f);
                    sailboatFx.spawnMeteor(intensity);
                    if (enableTimeWarp)
                        noiseTimeMultiplier = 1.0f + intensity * 2.0f;
                }
            });
        // Drop detector: biggest moments (has built-in 2s cooldown)
        audio->onDropImpact([&](float impact) {
            if (enableMeteors)
                sailboatFx.spawnMeteor(impact);
            if (enableTimeWarp)
                noiseTimeMultiplier = 2.0f + impact;
        });
    }
}
References ambientDecaySlider, ambientThreshold, ambientTrailSlider, audio, audio_ui, fl::audio::detector::VibeLevels::bass, fl::audio::detector::VibeLevels::bassSpike, BRIGHTNESS, fl::clamp(), COLOR_ORDER, DATA_PIN, debrisDecaySlider, debrisVelDecaySlider, dragSlider, enableAmbient, enableMeteors, enableTimeWarp, FastLED, fxEngine, leds, fl::makeTimingConfig(), fl::ChannelOptions::mCorrection, meteorThreshold, meteorTrailSlider, minVelocitySlider, noiseTimeMultiplier, NUM_LEDS, sailboatFx, screenMap, Serial, fl::ChannelConfig::setScreenMap(), speedSlider, and TypicalLEDStrip.