FastLED: fl::third_party::SoftwareGifDecoder::initializeDecoder
initializeDecoder()
bool fl::third_party::SoftwareGifDecoder::initializeDecoder () private
Definition at line 206 of file software_decoder.cpp.hpp.
{
    // Determine bitmap format based on output format
    // Use R8G8B8A8 explicitly to ensure byte order: 0xRR, 0xGG, 0xBB, 0xAA
    nsgif_bitmap_fmt_t bitmapFormat = NSGIF_BITMAP_FMT_R8G8B8A8;
    nsgif_error result = nsgif_create(&bitmapCallbacks_, bitmapFormat, &gif_);
    if (result != NSGIF_OK) {
        setError(fl::string("Failed to create GIF decoder: ") + nsgif_strerror(result));
        return false;
    }
    ready_ = true;
    return true;
}
References bitmapCallbacks_, FL_NOEXCEPT, gif_, fl::third_party::NSGIF_BITMAP_FMT_R8G8B8A8, fl::third_party::nsgif_create(), fl::third_party::NSGIF_OK, fl::third_party::nsgif_strerror(), ready_, and setError().
Referenced by begin().