FastLED: fl::third_party::SoftwareGifDecoder::convertBitmapToFrame
convertBitmapToFrame()
fl::shared_ptr< fl::Frame > fl::third_party::SoftwareGifDecoder::convertBitmapToFrame (nsgif_bitmap_t * bitmap) private
Definition at line 277 of file software_decoder.cpp.hpp.
{
    if (!bitmap) {
        setError("convertBitmapToFrame called with null bitmap");
        return nullptr;
    }
    GifBitmap* gifBitmap = static_cast<GifBitmap*>(bitmap);
    // Validate bitmap data
    if (!gifBitmap->pixels || gifBitmap->width == 0 || gifBitmap->height == 0) {
        setError("GIF bitmap has invalid data or dimensions");
        return nullptr;
    }
    fl::u8* rawData = gifBitmap->pixels.get();
    // Since libnsgif outputs RGBA8888, we need to handle the conversion properly
    // The Frame constructor expects the format we specify (outputFormat_)
    // but libnsgif always gives us RGBA8888 data
    // Create Frame with RGBA8888 format since that's what libnsgif provides
    // The Frame constructor will handle conversion to outputFormat_ via convertPixelsToRgb
    auto frame = fl::make_shared<fl::Frame>(
        rawData,
        gifBitmap->width,
        gifBitmap->height,
        fl::PixelFormat::RGBA8888,  // What libnsgif actually provides
        currentFrameIndex_ // Use frame index as timestamp
    );
    if (!frame || !frame->isValid()) {
        setError("Failed to create valid Frame from GIF bitmap");
        return nullptr;
    }
    return frame;
}
References currentFrameIndex_, FL_NOEXCEPT, fl::unique_ptr< T, Deleter >::get(), fl::third_party::GifBitmap::height, fl::make_shared(), fl::third_party::GifBitmap::pixels, fl::RGBA8888, setError(), and fl::third_party::GifBitmap::width.
Referenced by decode().