FastLED: fl::third_party::SoftwareGifDecoder::decode
decode()
fl::DecodeResult fl::third_party::SoftwareGifDecoder::decode () override virtual
Implements fl::IDecoder.
Definition at line 72 of file software_decoder.cpp.hpp.
{
    if (hasError_) {
        return fl::DecodeResult::Error;
    }
    if (!ready_) {
        setError("Decoder not ready");
        return fl::DecodeResult::Error;
    }
    if (endOfStream_) {
        return fl::DecodeResult::EndOfStream;
    }
    // Try to decode current frame
    nsgif_bitmap_t* bitmap = nullptr;
    nsgif_error result = nsgif_frame_decode(gif_, currentFrameIndex_, &bitmap);
    switch (result) {
        case NSGIF_OK:
            currentFrame_ = convertBitmapToFrame(bitmap);
            if (!currentFrame_) {
                setError("Failed to convert bitmap to frame");
                return fl::DecodeResult::Error;
            }
            currentFrameIndex_++;
            return fl::DecodeResult::Success;
        case NSGIF_ERR_END_OF_DATA:
            if (!dataComplete_) {
                // Try to load more data
                if (loadMoreData()) {
                    return decode(); // Retry
                }
            }
            endOfStream_ = true;
            return fl::DecodeResult::EndOfStream;
        case NSGIF_ERR_ANIMATION_END:
            endOfStream_ = true;
            return fl::DecodeResult::EndOfStream;
        case NSGIF_ERR_OOM:
        case NSGIF_ERR_DATA:
        case NSGIF_ERR_BAD_FRAME:
        case NSGIF_ERR_DATA_FRAME:
        case NSGIF_ERR_DATA_COMPLETE:
        case NSGIF_ERR_FRAME_DISPLAY:
        default:
            setError(fl::string("GIF decode error: ") + nsgif_strerror(result));
            return fl::DecodeResult::Error;
    }
}
References convertBitmapToFrame(), currentFrame_, currentFrameIndex_, dataComplete_, decode(), fl::EndOfStream, endOfStream_, fl::Error, FL_NOEXCEPT, gif_, hasError_, loadMoreData(), fl::third_party::NSGIF_ERR_ANIMATION_END, fl::third_party::NSGIF_ERR_BAD_FRAME, fl::third_party::NSGIF_ERR_DATA, fl::third_party::NSGIF_ERR_DATA_COMPLETE, fl::third_party::NSGIF_ERR_DATA_FRAME, fl::third_party::NSGIF_ERR_END_OF_DATA, fl::third_party::NSGIF_ERR_FRAME_DISPLAY, fl::third_party::NSGIF_ERR_OOM, fl::third_party::nsgif_frame_decode(), fl::third_party::NSGIF_OK, fl::third_party::nsgif_strerror(), ready_, setError(), and fl::Success.
Referenced by decode().