FastLED: fl::third_party::SoftwareGifDecoder::loadMoreData
loadMoreData()
bool fl::third_party::SoftwareGifDecoder::loadMoreData () private
Definition at line 235 of file software_decoder.cpp.hpp.
{
    if (!stream_ || !gif_) {
        return false;
    }
    // Read available data from stream in chunks and accumulate
    const fl::size bufferSize = 4096; // Read in chunks
    fl::u8 buffer[bufferSize];
    fl::size bytesRead = stream_->read(buffer, bufferSize);
    if (bytesRead == 0) {
        // No more data available, mark as complete
        nsgif_data_complete(gif_);
        dataComplete_ = true;
        return false;
    }
    // Append new data to accumulated buffer
    // libnsgif requires ALL data to be provided in each call to nsgif_data_scan
    fl::size oldSize = dataBuffer_.size();
    dataBuffer_.resize(oldSize + bytesRead);
    fl::memcpy(dataBuffer_.data() + oldSize, buffer, bytesRead);
    // Feed ALL accumulated data to libnsgif
    nsgif_error result = nsgif_data_scan(gif_, dataBuffer_.size(), dataBuffer_.data());
    // Check if we've read less than requested (likely end of stream)
    if (bytesRead < bufferSize) {
        nsgif_data_complete(gif_);
        dataComplete_ = true;
    }
    if (result != NSGIF_OK && result != NSGIF_ERR_END_OF_DATA) {
        setError(fl::string("GIF data scan error: ") + nsgif_strerror(result));
        return false;
    }
    // Frame count is available via nsgif_get_info() if needed in the future
    return true;
}
References dataBuffer_, dataComplete_, FL_NOEXCEPT, gif_, fl::memcpy(), fl::third_party::nsgif_data_complete(), fl::third_party::nsgif_data_scan(), fl::third_party::NSGIF_ERR_END_OF_DATA, fl::third_party::NSGIF_OK, fl::third_party::nsgif_strerror(), setError(), and stream_.
Referenced by begin(), and decode().