FastLED: fl::u4x12::sqrt
sqrt()
static constexpr FASTLED_FORCE_INLINE u4x12 fl::u4x12::sqrt (u4x12 x) inline static constexpr
Definition at line 162 of file u4x12.h.
{
        return x.mValue == 0 ? u4x12() : from_raw(static_cast<u16>(
            fl::isqrt32(static_cast<u32>(x.mValue) << FRAC_BITS)));
    }
References u4x12(), FASTLED_FORCE_INLINE, FL_NOEXCEPT, FRAC_BITS, from_raw(), fl::isqrt32(), and fl::x.
Referenced by rsqrt().