FastLED: fl::u4x12::log2_fp
log2_fp()
static FASTLED_FORCE_INLINE u4x12 fl::u4x12::log2_fp (u4x12 x) inline static private
Definition at line 209 of file u4x12.h.
{
        u32 val = static_cast<u32>(x.mValue);
        int msb = highest_bit(val);
        i32 int_part = msb - FRAC_BITS;
        i32 t;
        if (msb >= FRAC_BITS) {
            t = static_cast<i32>(
                (val >> (msb - FRAC_BITS)) - (SCALE));
        } else {
            t = static_cast<i32>(
                (val << (FRAC_BITS - msb)) - (SCALE));
        }
        // 4-term minimax coefficients for log2(1+t), t in [0,1).
        // Stored as i32 with 20 fractional bits. Max product ~2^33, fits i64 intermediate.
        constexpr int IFRAC = 20;
        constexpr i32 c0 = 1512456;   // 1.44179 * 2^20
        constexpr i32 c1 = -733024;   // -0.69907 * 2^20
        constexpr i32 c2 = 381136;    // 0.36348 * 2^20
        constexpr i32 c3 = -111776;   // -0.10660 * 2^20
        // Extend t from 12 to 20 frac bits.
        i32 t20 = static_cast<i32>(t) << (IFRAC - FRAC_BITS);
        // Horner: t * (c0 + t * (c1 + t * (c2 + t * c3)))
        i32 acc = c3;
        acc = c2 + static_cast<i32>((static_cast<i64>(acc) * t20) >> IFRAC);
        acc = c1 + static_cast<i32>((static_cast<i64>(acc) * t20) >> IFRAC);
        acc = c0 + static_cast<i32>((static_cast<i64>(acc) * t20) >> IFRAC);
        i32 frac_part = static_cast<i32>((static_cast<i64>(acc) * t20) >> IFRAC);
        // Convert from 20 frac bits back to 12.
        u16 frac12 = static_cast<u16>(frac_part >> (IFRAC - FRAC_BITS));
        return from_raw(static_cast<u16>((static_cast<i32>(static_cast<u32>(int_part) << FRAC_BITS)) + frac12));
    }
References u4x12(), FASTLED_FORCE_INLINE, FL_NOEXCEPT, FRAC_BITS, from_raw(), highest_bit(), SCALE, fl::t, and fl::x.
Referenced by pow().