FastLED: scale
scale
fl::UISlider scale("Scale", 4,.1, 4,.1) ("Scale" , 4 , . 1, 4 , . 1)
Examples
FxNoiseRing.ino.
Referenced by fl::CRGB::computeAdjustment(), fl::third_party::DequantBlock(), draw(), fl::SpiralMatrix10::draw(), fl::SpiralMatrix10_FP::draw(), fill_noise16(), fill_noise8(), fill_raw_2dnoise16into8(), fill_raw_noise16into8(), fill_raw_noise8(), fillnoise8(), fl::anonymous_namespace{five_bit_hd_gamma.cpp.hpp}::five_bit_impl::five_bit_pixel(), FL_DISABLE_WARNING(), FL_DISABLE_WARNING(), fl::CLEDController::getAdjustment(), getFirePaletteIndex(), getPaletteIndex(), getPaletteIndex(), fl::third_party::hexwave::hex_add_oversampled_bleplike(), fl::third_party::hexwave::hex_blamp(), fl::third_party::hexwave::hex_blep(), fl::third_party::jd_decomp(), fl::third_party::jd_decomp_progressive(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale(), loop(), fl::map_range_detail::map_range_math< T, vec2< V > >::map(), Color3i::Mulf(), noiseControls(), fl::CRGB16::nscale(), fl::CRGB16::nscale8(), fl::nscale8(), fl::nscale8_video(), fl::third_party::plm_audio_read_samples(), autoresearch::simd_check::ref_scale_u8_16(), fl::Font::renderGlyph(), fl::Font::renderGlyph(), fl::FontImpl::renderGlyph(), fl::FontImpl::renderGlyph(), fl::anonymous_namespace{colorutils.cpp.hpp}::scale_hd_channel(), MidiInterface< Transport, _Settings, _Platform >::sendPitchBend(), fl::third_party::TJpgInstanceDecoder::setScale(), fl::XYPath::setScale(), fl::XYPathRenderer::setScale(), fl::FxEngine::setSpeed(), setup(), fl::anonymous_namespace{chasing_spirals.cpp.hpp}::setupChasingSpiralFrame(), CFastLED::show(), CFastLED::showColor(), fl::third_party::truetype::stbtt_BakeFontBitmap_internal(), fl::third_party::truetype::stbtt_GetCodepointSDF(), fl::third_party::truetype::stbtt_GetGlyphSDF(), fl::third_party::truetype::stbtt_GetScaledFontVMetrics(), fl::third_party::truetype::stbtt_PackFontRangesGatherRects(), fl::third_party::truetype::stbtt_PackFontRangesRenderIntoRects(), and fl::third_party::truetype::stbtt_Rasterize().