FastLED: draw
draw()
void draw (uint32_t now)
Definition at line 76 of file FxNoiseRing.ino.
{
    double angle_offset = double(now) / 32000.0 * 2 * FL_M_PI;
    now = (now << timeBitshift.as<int>()) * timescale.as<double>();
    // get radius/zoom level from slider
    float noise_radius = scale.as<float>();
    // go in circular formation and set the leds
    for (int i = 0; i < NUM_LEDS; i++) {
        float angle = i * 2 * FL_M_PI / NUM_LEDS + angle_offset;
        // Use the new noiseRingHSV8 function to sample three z-slices for HSV components
        CHSV hsv = fl::noiseRingHSV8(angle, now, noise_radius);
        // Apply same constraints as before: minimum saturation and adjusted value
        hsv.s = fl::max(128u, (unsigned)hsv.s);
        // Apply value mapping similar to original: map from 0-255 to -64-255, clamp to 0-255
        uint16_t val = hsv.v;
        int16_t adjusted_val = map(val, 0, 255, -64, 255);
        if (adjusted_val < 0) {
            adjusted_val = 0;
        }
        hsv.v = adjusted_val;
        leds[i] = hsv;
    }
}
References FL_M_PI, leds, fl::max(), fl::noiseRingHSV8(), NUM_LEDS, scale, timeBitshift, and timescale.
Referenced by loop().