FastLED: fill_raw_2dnoise16into8
fill_raw_2dnoise16into8() [1/2]
void fill_raw_2dnoise16into8 (fl::u8 * pData, int width, int height, fl::u8 octaves, fl::q44 freq44, fract8 amplitude, int skip, fl::u32 x, fl::i32 scalex, fl::u32 y, fl::i32 scaley, fl::u32 time)
Fill a 2D 8-bit buffer with noise, using inoise16()
Parameters
freq44 starting octave frequency
amplitude noise amplitude
skip how many noise maps to skip over, incremented recursively per octave
Definition at line 794 of file noise.cpp.hpp.
{
  if(octaves > 1) {
    fill_raw_2dnoise16into8(pData, width, height, octaves-1, freq44, amplitude, skip+1, x*freq44, scalex *freq44, y*freq44, scaley * freq44, time);
  } else {
    // amplitude is always 255 on the lowest level
    amplitude=255;
  }
  scalex *= skip;
  scaley *= skip;
  fl::u32 xx;
  fract8 invamp = 255-amplitude;
  for(int i = 0; i < height; i+=skip, y+=scaley) {
    fl::u8 *pRow = pData + (i*width);
    xx = x;
    for(int j = 0; j < width; j+=skip, xx+=scalex) {
      fl::u16 noise_base = inoise16(xx,y,time);
      noise_base = (0x8000 & noise_base) ? noise_base - (32767) : 32767 - noise_base;
      noise_base = scale8(noise_base>>7,amplitude);
      if(skip==1) {
        pRow[j] = qadd8(scale8(pRow[j],invamp),noise_base);
      } else {
        for(int ii = i; ii<(i+skip) && ii<height; ++ii) {
          fl::u8 *pRow = pData + (ii*width);
          for(int jj=j; jj<(j+skip) && jj<width; ++jj) {
            pRow[jj] = scale8(pRow[jj],invamp) + noise_base;
          }
        }
      }
    }
  }
}
References fill_raw_2dnoise16into8(), inoise16(), octaves, x, and y.
Referenced by fill_2dnoise16(), fill_raw_2dnoise16into8(), and fill_raw_2dnoise16into8().