FastLED: fill_noise16
fill_noise16()
void fill_noise16 (CRGB * leds, int num_leds, fl::u8 octaves, fl::u16 x, int scale, fl::u8 hue_octaves, fl::u16 hue_x, int hue_scale, fl::u16 time, fl::u8 hue_shift = 0)
Fill an LED array with random colors, using 16-bit noise.
Parameters
leds pointer to LED array
num_leds the number of LEDs to fill
octaves the number of octaves to use for value (brightness) noise
x x-axis coordinate on noise map for value (brightness) noise
scale the scale (distance) between x points when filling in value (brightness) noise
hue_octaves the number of octaves to use for color hue noise
hue_x x-axis coordinate on noise map for color hue noise
hue_scale the scale (distance) between x points when filling in color hue noise
time the time position for the noise field
hue_shift how much to shift the final hues by for every LED
Definition at line 858 of file noise.cpp.hpp.
{
    if (num_leds <= 0) return;
    for (int j = 0; j < num_leds; j += 255) {
        const int LedsRemaining = num_leds - j;
        const int LedsPer = LedsRemaining > 255 ? 255 : LedsRemaining;  // limit to 255 max
        if (LedsPer <= 0) continue;
        FASTLED_STACK_ARRAY(fl::u8, V, LedsPer);
        FASTLED_STACK_ARRAY(fl::u8, H, LedsPer);
        fl::memset(V, 0, LedsPer);
        fl::memset(H, 0, LedsPer);
        fill_raw_noise16into8(V, LedsPer, octaves, x, scale, time);
        fill_raw_noise8(H, LedsPer, hue_octaves, hue_x, hue_scale, time);
        for (int i = 0; i < LedsPer; ++i) {
            leds[i + j] = CHSV(H[i] + hue_shift, 255, V[i]);
        }
    }
}
References FASTLED_STACK_ARRAY, fill_raw_noise16into8(), fill_raw_noise8(), H, hue_octaves, hue_scale, leds, fl::memset(), octaves, scale, and x.