FastLED: fill_raw_2dnoise8
fill_raw_2dnoise8() [1/3]
void fill_raw_2dnoise8 (uint8_t * pData, int width, int height, uint8_t octaves, q44 freq44, fract8 amplitude, int skip, uint16_t x, int16_t scalex, uint16_t y, int16_t scaley, uint16_t time)
Fill a 2D 8-bit buffer with noise, using inoise8()
Parameters
pData the array of data to fill with noise values
width the width of the 2D buffer
height the height of the 2D buffer
octaves the number of octaves to use for noise. More octaves = more noise.
freq44 starting octave frequency
amplitude noise amplitude
skip how many noise maps to skip over, incremented recursively per octave
x x-axis coordinate on noise map (1D)
scalex the scale (distance) between x points when filling in noise
y y-axis coordinate on noise map (2D)
scaley the scale (distance) between y points when filling in noise
time the time position for the noise field
pData the array of data to fill with noise values
width the width of the 2D buffer
height the height of the 2D buffer
octaves the number of octaves to use for noise. More octaves = more noise.
freq44 starting octave frequency
amplitude noise amplitude
skip how many noise maps to skip over, incremented recursively per octave
x x-axis coordinate on noise map (1D)
scalex the scale (distance) between x points when filling in noise
y y-axis coordinate on noise map (2D)
scaley the scale (distance) between y points when filling in noise
time the time position for the noise field
Todo
Why isn't this declared in the header (noise.h)?
Definition at line 663 of file noise.cpp.
{
  if(octaves > 1) {
    fill_raw_2dnoise8(pData, width, height, octaves-1, freq44, amplitude, skip+1, x*freq44, freq44 * scalex, y*freq44, freq44 * scaley, time);
  } else {
    // amplitude is always 255 on the lowest level
    amplitude=255;
  }
  scalex *= skip;
  scaley *= skip;
  fract8 invamp = 255-amplitude;
  uint16_t xx = x;
  for(int i = 0; i < height; ++i, y+=scaley) {
    uint8_t *pRow = pData + (i*width);
    xx = x;
    for(int j = 0; j < width; ++j, xx+=scalex) {
      uint8_t noise_base = inoise8(xx,y,time);
      noise_base = (0x80 & noise_base) ? (noise_base - 127) : (127 - noise_base);
      noise_base = scale8(noise_base<<1,amplitude);
      if(skip == 1) {
        pRow[j] = scale8(pRow[j],invamp) + noise_base;
      } else {
        for(int ii = i; ii<(i+skip) && ii<height; ++ii) {
          uint8_t *pRow = pData + (ii*width);
          for(int jj=j; jj<(j+skip) && jj<width; ++jj) {
            pRow[jj] = scale8(pRow[jj],invamp) + noise_base;
          }
        }
      }
    }
  }
}
References fill_raw_2dnoise8(), inoise8(), octaves, scale8(), x, and y.
Referenced by fill_2dnoise16(), fill_2dnoise8(), fill_raw_2dnoise8(), and fill_raw_2dnoise8().