FastLED: fill_2dnoise16
fill_2dnoise16()
void fill_2dnoise16 (CRGB * leds, int width, int height, bool serpentine, uint8_t octaves, uint32_t x, int xscale, uint32_t y, int yscale, uint32_t time, uint8_t hue_octaves, uint16_t hue_x, int hue_xscale, uint16_t hue_y, uint16_t hue_yscale, uint16_t hue_time, bool blend, uint16_t hue_shift = 0)
Fill an LED matrix with random colors, using 16-bit noise.
Parameters
leds pointer to LED array
width the width of the LED matrix
height the height of the LED matrix
serpentine whether the matrix is laid out in a serpentine pattern (alternating left/right directions per row)
octaves the number of octaves to use for value (brightness) noise
x x-axis coordinate on noise map for value (brightness) noise
xscale the scale (distance) between x points when filling in value (brightness) noise
y y-axis coordinate on noise map for value (brightness) noise
yscale the scale (distance) between y points when filling in value (brightness) noise
time the time position for the value (brightness) noise field
hue_octaves the number of octaves to use for color hue noise
hue_x x-axis coordinate on noise map for color hue noise
hue_xscale the scale (distance) between x points when filling in color hue noise
hue_y y-axis coordinate on noise map for color hue noise.
hue_yscale the scale (distance) between y points when filling in color hue noise
hue_time the time position for the color hue noise field
blend if true, will blend the newly generated LED values into the array. If false, will overwrite the array values directly.
hue_shift how much to shift the final hues by for every LED
Definition at line 938 of file noise.cpp.
{
  FASTLED_STACK_ARRAY(uint8_t, V, height*width);
  FASTLED_STACK_ARRAY(uint8_t, H, height*width);
  memset(V,0,height*width);
  memset(H,0,height*width);
  fill_raw_2dnoise16into8((uint8_t*)V,width,height,octaves,q44(2,0),171,1,x,xscale,y,yscale,time);
  // fill_raw_2dnoise16into8((uint8_t*)V,width,height,octaves,x,xscale,y,yscale,time);
  // fill_raw_2dnoise8((uint8_t*)V,width,height,hue_octaves,x,xscale,y,yscale,time);
  fill_raw_2dnoise8((uint8_t*)H,width,height,hue_octaves,hue_x,hue_xscale,hue_y,hue_yscale,hue_time);
  int w1 = width-1;
  int h1 = height-1;
  hue_shift >>= 8;
  for(int i = 0; i < height; ++i) {
    int wb = i*width;
    for(int j = 0; j < width; ++j) {
      CRGB led(CHSV(hue_shift + (H[(h1-i)*width + (w1-j)]), 196, V[i*width + j]));
      int pos = j;
      if(serpentine && (i & 0x1)) {
        pos = w1-j;
      }
      if(blend) {
        leds[wb+pos] >>= 1; leds[wb+pos] += (led>>=1);
      } else {
        leds[wb+pos] = led;
      }
    }
  }
}
References blend(), FASTLED_STACK_ARRAY, fill_raw_2dnoise16into8(), fill_raw_2dnoise8(), hue_octaves, hue_time, leds, octaves, pos, x, xscale, y, and yscale.
Referenced by loop().