FastLED: fill_raw_noise8
fill_raw_noise8()
void fill_raw_noise8 (uint8_t * pData, uint8_t num_points, uint8_t octaves, uint16_t x, int scalex, uint16_t time)
Fill a 1D 8-bit buffer with noise, using inoise8()
Parameters
pData the array of data to fill with noise values
num_points the number of points of noise to compute
octaves the number of octaves to use for noise. More octaves = more noise.
x x-axis coordinate on noise map (1D)
scalex the scale (distance) between x points when filling in noise
time the time position for the noise field
Definition at line 689 of file noise.cpp.
{
  uint32_t _xx = x;
  uint32_t scx = scale;
  for(int o = 0; o < octaves; ++o) {
    for(int i = 0,xx=_xx; i < num_points; ++i, xx+=scx) {
          pData[i] = qadd8(pData[i],inoise8(xx,time)>>o);
    }
    _xx <<= 1;
    scx <<= 1;
  }
}
References inoise8(), octaves, qadd8(), scale, and x.
Referenced by fill_noise16(), and fill_noise8().