FastLED: fl::Frame::draw
draw()
void fl::Frame::draw (fl::span< CRGB > leds, DrawMode draw_mode = DrawMode::DRAW_MODE_OVERWRITE) const
Definition at line 49 of file frame.cpp.hpp.
{
    if (!mRgb.empty()) {
        switch (draw_mode) {
        case DrawMode::DRAW_MODE_BLEND:  // DRAW_MODE_BLEND is for gfx primitives; treat as overwrite for Frame
        case DrawMode::DRAW_MODE_OVERWRITE: {
            fl::memcpy(leds.data(), mRgb.data(), mPixelsCount * sizeof(CRGB));
            break;
        }
        case DrawMode::DRAW_MODE_BLEND_BY_MAX_BRIGHTNESS: {
            for (size_t i = 0; i < mPixelsCount; ++i) {
                leds[i] = CRGB::blendAlphaMaxChannel(mRgb[i], leds[i]);
            }
            break;
        }
        }
    }
}
References fl::CRGB::blendAlphaMaxChannel(), fl::DRAW_MODE_BLEND, fl::DRAW_MODE_BLEND_BY_MAX_BRIGHTNESS, fl::DRAW_MODE_OVERWRITE, leds, fl::memcpy(), mPixelsCount, and mRgb.
Referenced by fl::video::FrameInterpolator::draw().