FastLED: fl::Frame::interpolate
interpolate() [1/2]
void fl::Frame::interpolate (const Frame & frame1, const Frame & frame2, u8 amountOfFrame2)
Definition at line 127 of file frame.cpp.hpp.
{
    if (frame1.size() != frame2.size() || frame1.size() != mPixelsCount) {
        FL_DBG("Frames must have the same size");
        return; // Frames must have the same size
    }
    interpolate(frame1, frame2, amountOfFrame2, rgb());
}
References Frame(), FL_DBG, interpolate(), mPixelsCount, rgb(), and size().
Referenced by fl::video::FrameInterpolator::draw(), and interpolate().