FastLED: fl::Frame::convertPixelsToRgb
convertPixelsToRgb()
void fl::Frame::convertPixelsToRgb (fl::u8 * pixels, PixelFormat format) private
Definition at line 143 of file frame.cpp.hpp.
{
    CRGB* rgbData = mRgb.data();
    switch (format) {
        case PixelFormat::RGB888: {
            for (size_t i = 0; i < mPixelsCount; i++) {
                fl::u8* pixel = &pixels[i * 3];
                rgbData[i] = CRGB(pixel[0], pixel[1], pixel[2]);
            }
            break;
        }
        case PixelFormat::RGB565: {
            fl::u16* pixel565 = fl::bit_cast<fl::u16*>(pixels);
            for (size_t i = 0; i < mPixelsCount; i++) {
                fl::u8 r, g, b;
                rgb565ToRgb888(pixel565[i], r, g, b);
                rgbData[i] = CRGB(r, g, b);
            }
            break;
        }
        case PixelFormat::RGBA8888: {
            for (size_t i = 0; i < mPixelsCount; i++) {
                fl::u8* pixel = &pixels[i * 4];
                rgbData[i] = CRGB(pixel[0], pixel[1], pixel[2]);
                // Ignoring alpha channel for now
            }
            break;
        }
        case PixelFormat::YUV420: {
            // Basic YUV420 to RGB conversion - simplified implementation
            // For now, just use the Y (luminance) component as grayscale
            for (size_t i = 0; i < mPixelsCount; i++) {
                fl::u8 y = pixels[i];
                rgbData[i] = CRGB(y, y, y);
            }
            break;
        }
        default: {
            // Fallback: fill with black
            if (mPixelsCount > 0 && !mRgb.empty()) {
                fl::memset((u8*)rgbData, 0, mPixelsCount * sizeof(CRGB));
            }
            break;
        }
    }
}
References fl::bit_cast(), fl::format(), fl::memset(), mPixelsCount, mRgb, fl::RGB565, fl::rgb565ToRgb888(), fl::RGB888, fl::RGBA8888, fl::y, and fl::YUV420.
Referenced by Frame().