FastLED: fl::task::then
then()
task & fl::task::then (fl::function< void()> on_then)
Definition at line 188 of file task.cpp.
{
    if (mImpl) {
        mImpl->set_then(fl::move(on_then));
        // Auto-register with scheduler when callback is set
        if (!mImpl->is_auto_registered()) {
            mImpl->auto_register_with_scheduler();
            fl::Scheduler::instance().add_task(*this);
        }
    }
    return *this;
}
References task(), fl::Scheduler::add_task(), fl::Scheduler::instance(), mImpl, and fl::move().
Referenced by after_frame(), after_frame(), and setup().