FastLED: InitFunky
InitFunky()
void InitFunky ()
Definition at line 1298 of file funky.cpp.
                 {
    InitMSGEQ7();
    x = random16();
    y = random16();
    z = random16();
    x2 = random16();
    y2 = random16();
    z2 = random16();
    InitGraphics();
}
References InitGraphics(), InitMSGEQ7(), random16(), x, x2, y, y2, z, and z2.
Referenced by setup().