FastLED: fl::perlin_s8x8::pnoise2d_raw
pnoise2d_raw()
fl::i32 fl::perlin_s8x8::pnoise2d_raw (fl::i32 fx_raw, fl::i32 fy_raw, const fl::i32 * fade_lut, const fl::u8 * perm) static
Definition at line 34 of file perlin_s8x8.cpp.hpp.
{
    int X, Y;
    fl::i16 x, y;
    floor_frac(fx_raw, X, x);
    floor_frac(fy_raw, Y, y);
    X &= 255;
    Y &= 255;
    fl::i16 u = fade(x, fade_lut);
    fl::i16 v = fade(y, fade_lut);
    int A  = perm[X & 255]       + Y;
    int AA = perm[A & 255];
    int AB = perm[(A + 1) & 255];
    int B  = perm[(X + 1) & 255] + Y;
    int BA = perm[B & 255];
    int BB = perm[(B + 1) & 255];
    fl::i16 result = lerp(v,
        lerp(u, grad(perm[AA & 255], x,          y),
                grad(perm[BA & 255], x - HP_ONE, y)),
        lerp(u, grad(perm[AB & 255], x,          y - HP_ONE),
                grad(perm[BB & 255], x - HP_ONE, y - HP_ONE)));
    // Shift from Q8 to s16x16's Q16 format
    return static_cast<fl::i32>(static_cast<fl::u32>(static_cast<fl::i32>(result)) << (fl::s16x16::FRAC_BITS - HP_BITS));
}
References fl::B, fade(), floor_frac(), fl::s16x16::FRAC_BITS, grad(), HP_BITS, HP_ONE, lerp(), fl::x, and fl::y.
Referenced by pnoise2d().