FastLED: fl::audio::Context::getFFT16
getFFT16()
shared_ptr< const fft::Bins > fl::audio::Context::getFFT16 (fft::Mode mode = fft::Mode::LOG_REBIN, fft::Window window = fft::Window::BLACKMAN_HARRIS)
Definition at line 106 of file audio_context.cpp.hpp.
{
    return getFFT(16, fft::Args::DefaultMinFrequency(),
                  fft::Args::DefaultMaxFrequency(), mode, window);
}
References fl::audio::fft::Args::DefaultMaxFrequency(), fl::audio::fft::Args::DefaultMinFrequency(), and getFFT().