FastLED: fl::audio::Context::getFFT
getFFT()
shared_ptr< const fft::Bins > fl::audio::Context::getFFT (int bands = 16, float fmin = fft::Args::DefaultMinFrequency(), float fmax = fft::Args::DefaultMaxFrequency(), fft::Mode mode = fft::Mode::AUTO, fft::Window window = fft::Window::BLACKMAN_HARRIS)
Definition at line 35 of file audio_context.cpp.hpp.
{
    fft::Args args(mSample.size(), bands, fmin, fmax, mSampleRate, mode, window);
    // O(1) cache lookup using hash map
    fl::size argsHash = hashFFTArgs(args);
    auto it = mFFTCacheMap.find(argsHash);
    if (it != mFFTCacheMap.end()) {
        int idx = it->second;
        if (idx >= 0 && idx < static_cast<int>(mFFTCache.size())) {
            // Double-check args match in case of hash collision
            if (mFFTCache[idx].args == args) {
                return mFFTCache[idx].bins;
            }
        }
    }
    // Not cached — try to recycle a previously-used fft::Bins with matching band count
    shared_ptr<fft::Bins> bins;
    for (size i = 0; i < mRecyclePool.size(); i++) {
        if (static_cast<int>(mRecyclePool[i]->bands()) == bands) {
            bins = fl::move(mRecyclePool[i]);
            mRecyclePool.erase(mRecyclePool.begin() + i);
            bins->clear(); // Vectors keep capacity — zero allocs
            break;
        }
    }
    if (!bins) {
        bins = fl::make_shared<fft::Bins>(bands);
    }
    fl::span<const fl::i16> sample = mSample.pcm();
    mFFT.run(sample, bins.get(), args);
    // Evict oldest if at capacity
    if (static_cast<int>(mFFTCache.size()) >= MAX_FFT_CACHE_ENTRIES) {
        // Remove the oldest entry's hash from hash map
        fl::size oldHash = hashFFTArgs(mFFTCache[0].args);
        mFFTCacheMap.erase(oldHash);
        // Shift all remaining entries and update map indices
        for (size i = 1; i < mFFTCache.size(); i++) {
            fl::size key = hashFFTArgs(mFFTCache[i].args);
            mFFTCacheMap[key] = static_cast<int>(i - 1);
        }
        mFFTCache.erase(mFFTCache.begin());
    }
    FFTCacheEntry entry;
    entry.args = args;
    entry.bins = bins;
    int newIndex = static_cast<int>(mFFTCache.size());
    mFFTCache.push_back(fl::move(entry));
    // Add to hash map for O(1) future lookups
    mFFTCacheMap[argsHash] = newIndex;
    return bins;
}
References Context(), args, fl::audio::Context::FFTCacheEntry::args, fl::audio::Context::FFTCacheEntry::bins, fl::shared_ptr< T >::get(), getFFT(), hashFFTArgs(), fl::make_shared(), MAX_FFT_CACHE_ENTRIES, mFFT, mFFTCache, mFFTCacheMap, fl::fl::move(), mRecyclePool, mSample, mSampleRate, and fl::sample().
Referenced by getBandEnergy(), getFFT(), and getFFT16().