FastLED: setup
setup()
void setup ()
Definition at line 70 of file NoisePlayground.ino.
             {
  // initialize the x/y and time values
  random16_set_seed(8934);
  random16_add_entropy(analogRead(3));
  Serial.begin(57600);
  Serial.println("resetting!");
  delay(3000);
  FastLED.addLeds<WS2811,2,GRB>(leds,NUM_LEDS);
  FastLED.setBrightness(96);
  hxy = (uint32_t)((uint32_t)random16() << 16) + (uint32_t)random16();
  x = (uint32_t)((uint32_t)random16() << 16) + (uint32_t)random16();
  y = (uint32_t)((uint32_t)random16() << 16) + (uint32_t)random16();
  v_time = (uint32_t)((uint32_t)random16() << 16) + (uint32_t)random16();
  hue_time = (uint32_t)((uint32_t)random16() << 16) + (uint32_t)random16();
}
References FastLED, GRB, hue_time, hxy, leds, NUM_LEDS, random16(), random16_add_entropy(), random16_set_seed(), v_time, x, and y.