FastLED: setup
setup()
void setup ()
Definition at line 82 of file SIMD.ino.
             {
    Serial.begin(115200);
    delay(2000);
    fl::sstream ss;
    ss << "\n╔════════════════════════════════════════════════════════════════╗\n";
    ss << "║ FastLED SIMD Operations Test Suite                            ║\n";
    ss << "╚════════════════════════════════════════════════════════════════╝\n";
    FL_PRINT(ss.str());
    FL_PRINT("\nStarting SIMD operation tests...\n");
    // ========================================================================
    // Load/Store Tests
    // ========================================================================
    FL_PRINT("\n[CATEGORY] Load/Store Operations");
    FL_PRINT("────────────────────────────────────────────────────────────────");
    run_test("load/store u8x16", test_load_store_u8_16, test_results, total_tests, passed_tests, failed_tests);
    run_test("load/store u32x4", test_load_store_u32_4, test_results, total_tests, passed_tests, failed_tests);
    run_test("load/store f32x4", test_load_store_f32_4, test_results, total_tests, passed_tests, failed_tests);
    // ========================================================================
    // Arithmetic Tests
    // ========================================================================
    FL_PRINT("\n[CATEGORY] Arithmetic Operations");
    FL_PRINT("────────────────────────────────────────────────────────────────");
    run_test("add_sat u8x16", test_add_sat_u8_16, test_results, total_tests, passed_tests, failed_tests);
    run_test("sub_sat u8x16", test_sub_sat_u8_16, test_results, total_tests, passed_tests, failed_tests);
    run_test("scale u8x16", test_scale_u8_16, test_results, total_tests, passed_tests, failed_tests);
    run_test("blend u8x16", test_blend_u8_16, test_results, total_tests, passed_tests, failed_tests);
    // ========================================================================
    // Comparison Tests
    // ========================================================================
    FL_PRINT("\n[CATEGORY] Comparison Operations");
    FL_PRINT("────────────────────────────────────────────────────────────────");
    run_test("min u8x16", test_min_u8_16, test_results, total_tests, passed_tests, failed_tests);
    run_test("max u8x16", test_max_u8_16, test_results, total_tests, passed_tests, failed_tests);
    run_test("avg u8x16", test_avg_u8_16, test_results, total_tests, passed_tests, failed_tests);
    run_test("avg_round u8x16", test_avg_round_u8_16, test_results, total_tests, passed_tests, failed_tests);
    // ========================================================================
    // Bitwise Tests
    // ========================================================================
    FL_PRINT("\n[CATEGORY] Bitwise Operations");
    FL_PRINT("────────────────────────────────────────────────────────────────");
    run_test("and u8x16", test_and_u8_16, test_results, total_tests, passed_tests, failed_tests);
    run_test("or u8x16", test_or_u8_16, test_results, total_tests, passed_tests, failed_tests);
    run_test("xor u8x16", test_xor_u8_16, test_results, total_tests, passed_tests, failed_tests);
    run_test("andnot u8x16", test_andnot_u8_16, test_results, total_tests, passed_tests, failed_tests);
    // ========================================================================
    // Broadcast Tests
    // ========================================================================
    FL_PRINT("\n[CATEGORY] Broadcast Operations");
    FL_PRINT("────────────────────────────────────────────────────────────────");
    run_test("set1 u32x4", test_set1_u32_4, test_results, total_tests, passed_tests, failed_tests);
    run_test("set1 f32x4", test_set1_f32_4, test_results, total_tests, passed_tests, failed_tests);
    // ========================================================================
    // Float Tests
    // ========================================================================
    FL_PRINT("\n[CATEGORY] Floating Point Operations");
    FL_PRINT("────────────────────────────────────────────────────────────────");
    run_test("add f32x4", test_add_f32_4, test_results, total_tests, passed_tests, failed_tests);
    run_test("sub f32x4", test_sub_f32_4, test_results, total_tests, passed_tests, failed_tests);
    run_test("mul f32x4", test_mul_f32_4, test_results, total_tests, passed_tests, failed_tests);
    run_test("div f32x4", test_div_f32_4, test_results, total_tests, passed_tests, failed_tests);
    run_test("sqrt f32x4", test_sqrt_f32_4, test_results, total_tests, passed_tests, failed_tests);
    run_test("min f32x4", test_min_f32_4, test_results, total_tests, passed_tests, failed_tests);
    run_test("max f32x4", test_max_f32_4, test_results, total_tests, passed_tests, failed_tests);
    // ========================================================================
    // Print Summary
    // ========================================================================
    print_summary(test_results, total_tests, passed_tests, failed_tests);
    print_final_banner(failed_tests);
    // Signal completion
    if (failed_tests == 0) {
        FL_PRINT("\nSIMD_TEST_SUITE_COMPLETE");
    } else {
        fl::sstream err;
        err << "\nSIMD test suite failed with " << failed_tests << " error(s)";
        FL_ERROR(err.str().c_str());
    }
}
References fl::basic_string::c_str(), failed_tests, FL_ERROR, FL_PRINT, passed_tests, simd_test::print_final_banner(), simd_test::print_summary(), simd_test::run_test(), Serial, fl::sstream::str(), simd_test::test_add_f32_4(), simd_test::test_add_sat_u8_16(), simd_test::test_and_u8_16(), simd_test::test_andnot_u8_16(), simd_test::test_avg_round_u8_16(), simd_test::test_avg_u8_16(), simd_test::test_blend_u8_16(), simd_test::test_div_f32_4(), simd_test::test_load_store_f32_4(), simd_test::test_load_store_u32_4(), simd_test::test_load_store_u8_16(), simd_test::test_max_f32_4(), simd_test::test_max_u8_16(), simd_test::test_min_f32_4(), simd_test::test_min_u8_16(), simd_test::test_mul_f32_4(), simd_test::test_or_u8_16(), test_results, simd_test::test_scale_u8_16(), simd_test::test_set1_f32_4(), simd_test::test_set1_u32_4(), simd_test::test_sqrt_f32_4(), simd_test::test_sub_f32_4(), simd_test::test_sub_sat_u8_16(), simd_test::test_xor_u8_16(), and total_tests.