FastLED: fl::audio::detector::TempoAnalyzer::updateHypotheses
updateHypotheses()
void fl::audio::detector::TempoAnalyzer::updateHypotheses (u32 timestamp) private
Definition at line 172 of file tempo_analyzer.cpp.hpp.
{
    // For each existing onset, create/update hypotheses
    for (size i = 0; i < mOnsetTimes.size(); i++) {
        if (i == mOnsetTimes.size() - 1) continue;  // Skip the just-added onset
        u32 interval = timestamp - mOnsetTimes[i];
        // Check if interval is in valid BPM range
        if (interval < MIN_BEAT_INTERVAL_MS || interval > MAX_BEAT_INTERVAL_MS) {
            continue;
        }
        float bpm = 60000.0f / static_cast<float>(interval);
        // Check if this BPM is within user-defined range
        if (bpm < mMinBPM || bpm > mMaxBPM) {
            continue;
        }
        // Check if we already have a similar hypothesis
        bool foundExisting = false;
        for (size j = 0; j < mHypotheses.size(); j++) {
            float bpmDiff = fl::abs(mHypotheses[j].bpm - bpm);
            if (bpmDiff < 3.0f) {  // Within 3 BPM tolerance
                // Update existing hypothesis
                mHypotheses[j].bpm = (mHypotheses[j].bpm + bpm) * 0.5f;
                mHypotheses[j].score += calculateIntervalScore(interval);
                mHypotheses[j].lastOnsetTime = timestamp;
                mHypotheses[j].onsetCount++;
                foundExisting = true;
                break;
            }
        }
        // Create new hypothesis if not found and we have room
        if (!foundExisting && mHypotheses.size() < MAX_HYPOTHESES) {
            TempoHypothesis hyp;
            hyp.bpm = bpm;
            hyp.score = calculateIntervalScore(interval);
            hyp.lastOnsetTime = timestamp;
            hyp.onsetCount = 1;
            mHypotheses.push_back(hyp);
        }
    }
}
References fl::abs(), bpm(), fl::audio::detector::TempoAnalyzer::TempoHypothesis::bpm, calculateIntervalScore(), fl::audio::detector::TempoAnalyzer::TempoHypothesis::lastOnsetTime, MAX_BEAT_INTERVAL_MS, MAX_HYPOTHESES, mHypotheses, mMaxBPM, mOnsetTimes, fl::audio::detector::TempoAnalyzer::TempoHypothesis::onsetCount, and fl::audio::detector::TempoAnalyzer::TempoHypothesis::score.
Referenced by update().