FastLED: fl::audio::detector::TempoAnalyzer::update
update()
void fl::audio::detector::TempoAnalyzer::update (shared_ptr< Context > context) override virtual
Implements fl::audio::Detector.
Definition at line 37 of file tempo_analyzer.cpp.hpp.
{
    mRetainedFFT = context->getFFT16();
    const fft::Bins& fft = *mRetainedFFT;
    u32 timestamp = context->getTimestamp();
    // Calculate spectral flux for onset detection
    float flux = calculateSpectralFlux(fft);
    // Update adaptive threshold
    updateAdaptiveThreshold();
    // Detect onsets
    if (detectOnset(timestamp)) {
        mOnsetTimes.push_back(timestamp);
        if (mOnsetTimes.size() > MAX_ONSET_HISTORY) {
            mOnsetTimes.pop_front();
        }
        // Update tempo hypotheses
        updateHypotheses(timestamp);
    }
    mPreviousFlux = flux;
    // Update per-bin magnitudes for next frame's spectral flux calculation
    size numBins = fl::min(static_cast<size>(8), fft.raw().size());
    for (size i = 0; i < numBins && i < mPreviousMagnitudes.size(); i++) {
        mPreviousMagnitudes[i] = fft.raw()[i];
    }
    // Prune weak hypotheses
    pruneHypotheses();
    // Update current tempo based on best hypothesis
    updateCurrentTempo();
    // Update stability analysis
    updateStability();
    // Silence gate: fade confidence toward 0 during silence. The BPM estimate
    // itself survives unchanged so beat sync is seamless on audio re-entry.
    // dt derived from timestamp deltas (ms→s). First frame: dt=0 → pass-through.
    float dt = 0.0f;
    if (mHasPrevTimestamp && timestamp >= mPrevTimestamp) {
        dt = static_cast<float>(timestamp - mPrevTimestamp) * 0.001f;
    }
    mPrevTimestamp = timestamp;
    mHasPrevTimestamp = true;
    const bool isSilent = context->isSilent();
    mConfidence = mConfidenceEnvelope.update(isSilent, mConfidence, dt);
    // Track state changes for fireCallbacks()
    float bpmDiff = fl::abs(mCurrentBPM - mPreviousBPM);
    mBpmChanged = (bpmDiff > 5.0f);
    mPreviousBPM = mCurrentBPM;
}
References TempoAnalyzer(), fl::abs(), calculateSpectralFlux(), detectOnset(), isSilent, MAX_ONSET_HISTORY, mBpmChanged, mConfidence, mConfidenceEnvelope, mCurrentBPM, mHasPrevTimestamp, fl::min(), mOnsetTimes, mPreviousBPM, mPreviousFlux, mPreviousMagnitudes, mPrevTimestamp, mRetainedFFT, pruneHypotheses(), update(), updateAdaptiveThreshold(), updateCurrentTempo(), updateHypotheses(), and updateStability().
Referenced by ~TempoAnalyzer(), and update().