FastLED: fl::audio::detector::TempoAnalyzer::updateStability
updateStability()
void fl::audio::detector::TempoAnalyzer::updateStability () private
Definition at line 266 of file tempo_analyzer.cpp.hpp.
{
    if (mBPMHistory.size() < 5) {
        mStability = 0.0f;
        mIsStable = false;
        mStableFrameCount = 0;
        return;
    }
    // Calculate variance of recent BPM estimates
    float sum = 0.0f;
    for (size i = 0; i < mBPMHistory.size(); i++) {
        sum += mBPMHistory[i];
    }
    float mean = sum / static_cast<float>(mBPMHistory.size());
    float variance = 0.0f;
    for (size i = 0; i < mBPMHistory.size(); i++) {
        float diff = mBPMHistory[i] - mean;
        variance += diff * diff;
    }
    variance /= static_cast<float>(mBPMHistory.size());
    // Convert variance to stability score (low variance = high stability)
    float stddev = fl::sqrt(variance);
    mStability = fl::max(0.0f, 1.0f - (stddev / 10.0f));
    // Check if stable
    if (mStability >= mStabilityThreshold) {
        mStableFrameCount++;
        if (mStableFrameCount >= STABLE_FRAMES_REQUIRED) {
            mIsStable = true;
        }
    } else {
        mStableFrameCount = 0;
        mIsStable = false;
    }
}
References fl::max(), mBPMHistory, mIsStable, mStability, mStabilityThreshold, mStableFrameCount, fl::sqrt(), and STABLE_FRAMES_REQUIRED.
Referenced by update().