FastLED: setup
setup()
void setup ()
Definition at line 77 of file RX.ino.
             {
    Serial.begin(115200);
    while (!Serial && millis() < 3000);
    const char* loop_back_mode = PIN_TX == PIN_RX ? "INTERNAL" : "JUMPER WIRE";
    FL_WARN("\n=== FastLED RX Channel Test ===");
    FL_WARN("Platform: ESP32");
    FL_WARN("TX Pin: GPIO " << PIN_TX);
    FL_WARN("RX Pin: GPIO " << PIN_RX);
    FL_WARN("RX Backend: " << (RX_BACKEND == fl::RxBackend::RMT ? "RMT" : "ISR"));
    FL_WARN("LOOP BACK MODE: " << loop_back_mode);
    // Sanity check: Verify jumper wire connection when TX and RX are different pins
    if (PIN_TX != PIN_RX) {
        if (!verifyJumperWire(PIN_TX, PIN_RX)) {
            halt.error("Missing jumper wire between TX and RX pins");
            return;
        }
    } else {
        FL_WARN("TX and RX use same pin (" << PIN_TX << ") - no jumper wire needed");
    }
    FL_WARN("");
    // Create RX channel for testing
    // Use 1MHz resolution for better timing accuracy (1us per tick)
    FL_WARN("Creating RX channel for testing...");
    fl::RxChannelConfig test_channel_config(PIN_RX, RX_BACKEND);
    auto rx_test = FastLED.addRx(test_channel_config);
    if (!rx_test) {
        halt.error("Failed to create RX channel for testing");
        return;
    }
    // Initialize test RX channel with config
    fl::RxChannelConfig test_config(PIN_RX, RX_BACKEND);
    test_config.edge_capacity = 10;
    test_config.hz = 1000000;  // 1MHz resolution for better timing accuracy
    test_config.signal_range_min_ns = 100;
    test_config.signal_range_max_ns = 10000000;
    test_config.start_low = true;
    if (!rx_test->begin(test_config)) {
        halt.error("Failed to initialize test RX channel");
        return;
    }
    // Test RX channel functionality
    if (!testRxChannelSanity(rx_test, PIN_TX)) {
        halt.error("RX channel sanity check failed - RX not working");
        return;
    }
    FL_WARN("");
    // Create main RX channel for the loop
    // Use 1MHz resolution to allow longer timeouts (40MHz = ~819us max, 1MHz = ~32ms max)
    FL_WARN("Creating main RX channel...");
    fl::RxChannelConfig main_channel_config(PIN_RX, RX_BACKEND);
    rxChannelSingleton() = FastLED.addRx(main_channel_config);
    if (!rxChannelSingleton()) {
        halt.error("Failed to create main RX channel");
        return;
    }
    FL_WARN("✓ Main RX channel created\n");
    delay(1000);
}
References fl::RxChannelConfig::edge_capacity, FastLED, FL_WARN, halt, fl::RxChannelConfig::hz, PIN_RX, PIN_TX, fl::RMT, RX_BACKEND, rxChannelSingleton(), Serial, fl::RxChannelConfig::signal_range_max_ns, fl::RxChannelConfig::signal_range_min_ns, fl::RxChannelConfig::start_low, testRxChannelSanity(), and verifyJumperWire().