FastLED: loop
loop()
void loop ()
Definition at line 145 of file RX.ino.
            {
    // IMPORTANT: Must be first line - handles halt state and prevents watchdog resets
    if (halt.check()) return;
    FL_WARN("\n╔════════════════════════════════════════════════════════════════╗");
    FL_WARN("║  RX DEVICE TEST");
    FL_WARN("╚════════════════════════════════════════════════════════════════╝\n");
    // Configure RX channel
    fl::RxChannelConfig config(PIN_RX, RX_BACKEND);
    config.edge_capacity = EDGE_BUFFER_SIZE;
    config.hz = 1000000;                     // 1MHz resolution (allows up to ~32ms timeout)
    config.signal_range_min_ns = 100;       // 100ns glitch filter
    config.signal_range_max_ns = 10000000;  // 10ms idle timeout (1MHz RMT allows up to ~32ms)
    config.start_low = true;                 // Pin starts LOW
    // Execute toggles and capture data
    FL_WARN("[TEST] Initializing RX channel and executing toggles...");
    auto& rx_channel = rxChannelSingleton();
    rx_channel->setConfig(config);
    executeToggles(*rx_channel, TEST_PATTERN, PIN_TX, WAIT_TIMEOUT_MS);
    // Wait for capture completion
    FL_WARN("[TEST] Waiting for capture (timeout: " << WAIT_TIMEOUT_MS << "ms)...");
    auto wait_result = rx_channel->wait(WAIT_TIMEOUT_MS);
    if (wait_result == fl::RxWaitResult::TIMEOUT) {
        FL_ERROR("Timeout waiting for data");
    } else if (wait_result == fl::RxWaitResult::BUFFER_OVERFLOW) {
        FL_ERROR("Buffer overflow during capture");
    } else {
        FL_WARN("[TEST] ✓ Data captured successfully");
        // Get edge timings
        fl::array<fl::EdgeTime, EDGE_BUFFER_SIZE> edge_buffer;
        size_t edge_count = rx_channel->getRawEdgeTimes(edge_buffer);
        // Validate edge timing against expected pattern
        const uint32_t TOLERANCE_PERCENT = 15;  // ±15% tolerance for timing jitter
        validateEdgeTiming(edge_buffer, edge_count, TEST_PATTERN, TOLERANCE_PERCENT);
    }
    FL_WARN("\n╔════════════════════════════════════════════════════════════════╗");
    FL_WARN("║ TEST COMPLETE - Waiting 5 seconds...");
    FL_WARN("╚════════════════════════════════════════════════════════════════╝\n");
    delay(5000);
}
References fl::BUFFER_OVERFLOW, EDGE_BUFFER_SIZE, fl::RxChannelConfig::edge_capacity, executeToggles(), FL_ERROR, FL_WARN, halt, fl::RxChannelConfig::hz, PIN_RX, PIN_TX, RX_BACKEND, rxChannelSingleton(), fl::RxChannelConfig::signal_range_max_ns, fl::RxChannelConfig::signal_range_min_ns, fl::RxChannelConfig::start_low, TEST_PATTERN, fl::TIMEOUT, validateEdgeTiming(), and WAIT_TIMEOUT_MS.