FastLED: loop
loop()
void loop ()
Definition at line 42 of file HSVTest.h.
            {
    uint8_t hue = hueSlider.value();
    uint8_t saturation = saturationSlider.value();
    uint8_t value = valueSlider.value();
    if (autoHue.value()) {
        uint32_t now = millis();
        uint32_t hue_offset = (now / 100) % 256;
        hue = hue_offset;
        hueSlider.setValue(hue);
    }
    CHSV hsv(hue, saturation, value);
    leds[0] = hsv2rgb_spectrum(hsv);
    leds[2] = hsv2rgb_rainbow(hsv);
    leds[4] = hsv2rgb_fullspectrum(hsv);
    FastLED.show();
}
References autoHue(), FastLED, hsv2rgb_fullspectrum(), hsv2rgb_rainbow(), hsv2rgb_spectrum(), hue, hueSlider(), leds, saturationSlider(), and valueSlider().