FastLED: Painter::PaintBrightSurprise
PaintBrightSurprise()
void Painter::PaintBrightSurprise (const KeyboardState & keyboard, const int * led_column_table, int led_column_table_length, LedRopeInterface * led_rope) static private
Definition at line 401 of file Painter.cpp.
{
  led_rope->RawBeginDraw();
  int total_counted = 0;
  float r, g, b;
  r = g = b = 0;
  for (int i = 0; i < KeyboardState::kNumKeys; ++i) {
    const Key& key = keyboard.keys_[i];
    if (key.curr_color_.v_ > 0.0f) {
      const Color3i rgb = key.curr_color_.ToRGB();
      r += rgb.r_;
      g += rgb.g_;
      b += rgb.b_;
      ++total_counted;
    }
  }
  float denom = total_counted ? total_counted : 1;
  r /= denom;
  g /= denom;
  b /= denom;
  const Color3i rgb(r, g, b);
  for (int i = 0; i < led_column_table_length; ++i) {
    const int n = led_column_table[i];
    for (int i = 0; i < n; ++i) {
      led_rope->RawDrawPixel(rgb);
    }
  }
  led_rope->RawCommitDraw();
}
References Color3i::b_, Key::curr_color_, Color3i::g_, KeyboardState::keys_, KeyboardState::kNumKeys, Color3i::r_, LedRopeInterface::RawBeginDraw(), LedRopeInterface::RawCommitDraw(), LedRopeInterface::RawDrawPixel(), ColorHSV::ToRGB(), and ColorHSV::v_.
Referenced by Paint().