FastLED: fl::ClocklessChipset::ClocklessChipset
ClocklessChipset() [1/5]
fl::ClocklessChipset::ClocklessChipset (int pin, const ChipsetTimingConfig & timing, ClocklessEncoder encoder) inline constexpr
Constructor with explicit encoder.
Definition at line 38 of file config.h.
        : pin(pin), timing(timing), encoder(encoder) {}
References encoder, FL_NOEXCEPT, pin, and timing.
Referenced by ClocklessChipset(), ClocklessChipset(), operator!=(), operator=(), operator=(), and operator==().