FastLED: Painter::Paint
Paint()
void Painter::Paint (uint32_t now_ms, uint32_t delta_ms, VisState vis_state, KeyboardState * keyboard, LedRopeInterface * light_rope) static
Definition at line 98 of file Painter.cpp.
{
  for (int i = 0; i < KeyboardState::kNumKeys; ++i) {
    Key& key = keyboard->keys_[i];
    const float time_delta_ms = static_cast<float>(now_ms - key.event_time_);
    const float lum = CalcLuminance(time_delta_ms, keyboard->sustain_pedal_, key, i);
    const float sat = CalcSaturation(time_delta_ms, key.curr_color_, key.on_);
    //if (key.idx_ == 56) {
    //  dprint("lum: "); dprint(lum*255.f); dprint(" sat:"); dprintln(sat*255.f);
    //}
    key.curr_color_.v_ = lum;
    key.curr_color_.s_ = sat;
    // Removing this line breaks one of the visualizers...
    // TODO: Figure out a cleaner solution.
    light_rope->Set(i, key.curr_color_.ToRGB());
  }
  LedColumns led_columns = LedLayoutArray();
  switch (vis_state) {
    case Painter::kBlockNote: {
      light_rope->DrawSequentialRepeat(kNumLightsPerNote);
      break;
    }
    case Painter::kColumnNote: {
      light_rope->DrawRepeat(led_columns.array, kNumKeys);
      break;
    }
    case Painter::kVUNote: {
      PaintVuNotes(now_ms, *keyboard, led_columns.array, kNumKeys, light_rope);
      break;
    }
    case Painter::kVUMidNote: {
      PaintVuMidNotesFade(delta_ms, *keyboard, led_columns.array, kNumKeys, light_rope);
      break;
    }
    case Painter::kVegas: { // aka "vegas mode?"
      VegasVisualizer(*keyboard, led_columns.array, kNumKeys, light_rope);
      break;
    }
    case Painter::kBrightSurprise: {
      PaintBrightSurprise(*keyboard, led_columns.array, kNumKeys, light_rope);
      break;
    }
    case Painter::kVUSpaceInvaders: {
      PaintVuSpaceInvaders(now_ms, *keyboard, led_columns.array, kNumKeys, light_rope);
      break;
    }
    default:
      dprint("Unknown mode: "); dprint(vis_state); dprint(".\n");
      break;
  }
}
References LedColumns::array, Key::curr_color_, dprint, LedRopeInterface::DrawRepeat(), LedRopeInterface::DrawSequentialRepeat(), Key::event_time_, kBlockNote, kBrightSurprise, kColumnNote, KeyboardState::keys_, KeyboardState::kNumKeys, kNumKeys, kNumLightsPerNote, kVegas, kVUMidNote, kVUNote, kVUSpaceInvaders, LedLayoutArray(), Key::on_, PaintBrightSurprise(), PaintVuMidNotesFade(), PaintVuNotes(), PaintVuSpaceInvaders(), ColorHSV::s_, LedRopeInterface::Set(), KeyboardState::sustain_pedal_, ColorHSV::ToRGB(), ColorHSV::v_, and VegasVisualizer().