FastLED: Painter::PaintVuNotes
PaintVuNotes()
void Painter::PaintVuNotes (uint32_t now_ms, const KeyboardState & keyboard, const int * led_column_table, int led_column_table_length, LedRopeInterface * led_rope) static private
Definition at line 164 of file Painter.cpp.
{
 FASTLED_WARN("\n\n############## VU NOTES ################\n\n");
 led_rope->RawBeginDraw();
 for (int i = 0; i < led_column_table_length; ++i) {
    const Key& key = keyboard.keys_[i];
    // Map the white keys to the bottom and the black keys to the top.
    bool black_key = false;
    switch (key.idx_ % 12) {
      case 1:
      case 4:
      case 6:
      case 9:
      case 11:
        black_key = true;
        break;
    }
    const int pixel_count = led_column_table[i];
    const int draw_pixel_count = ceil(pixel_count * sqrt(key.curr_color_.v_));
    const int black_pixel_count = pixel_count - draw_pixel_count;
    const Color3i& c = *led_rope->GetIterator(i);
    const bool reverse_correct = black_key == (key.idx_ % 2);
    if (reverse_correct) {
      for (int j = 0; j < draw_pixel_count; ++j) {
        if (j < draw_pixel_count - 1) {
          led_rope->RawDrawPixel(c);
        } else {
          // Last pixel.
          ColorHSV hsv(random(512) / 512.f, random(512) / 512.f, 1.0);
          led_rope->RawDrawPixel(hsv.ToRGB());
        }
      }
      for (int j = 0; j < black_pixel_count; ++j) {
        led_rope->RawDrawPixel(Color3i::Black());
      }
    } else {
      for (int j = 0; j < black_pixel_count; ++j) {
        led_rope->RawDrawPixel(Color3i::Black());
      }
      for (int j = draw_pixel_count - 1; j >= 0; --j) {
        if (j < draw_pixel_count - 1) {
          led_rope->RawDrawPixel(c);
        } else {
          // Last pixel.
          ColorHSV hsv(random(512) / 512.f, random(512) / 512.f, 1.0);
          led_rope->RawDrawPixel(hsv.ToRGB());
        }
      }
    }
  }
  led_rope->RawCommitDraw();
}
References Color3i::Black(), Key::curr_color_, FASTLED_WARN, LedRopeInterface::GetIterator(), Key::idx_, KeyboardState::keys_, LedRopeInterface::RawBeginDraw(), LedRopeInterface::RawCommitDraw(), LedRopeInterface::RawDrawPixel(), ColorHSV::ToRGB(), and ColorHSV::v_.
Referenced by Paint().