FastLED: Painter::VegasVisualizer
VegasVisualizer()
void Painter::VegasVisualizer (const KeyboardState & keyboard, const int * led_column_table, int led_column_table_length, LedRopeInterface * led_rope) static private
Definition at line 360 of file Painter.cpp.
{
 led_rope->RawBeginDraw();
 uint32_t skipped_lights = 0;
 for (int i = 0; i < led_column_table_length; ++i) {
    const Key& key = keyboard.keys_[i];
    uint32_t painted_lights = 0;
    // % of lights that are active.
    const float active_lights_factor = led_column_table[i] * sqrt(key.curr_color_.v_);
    const float inactive_lights_factor = 1.0f - active_lights_factor;
    const float taper_point_1 = inactive_lights_factor / 2.0f;
    const float taper_point_2 = taper_point_1 + active_lights_factor;
    const int taper_idx_1 = static_cast<int>(floor(taper_point_1 * led_column_table[i]));
    const int taper_idx_2 = static_cast<int>(floor(taper_point_2 * led_column_table[i]));
    const Color3i c = key.curr_color_.ToRGB();
    for (int i = 0; i < taper_idx_1 / 2; ++i) {
      led_rope->RawDrawPixel(Color3i::Black());
      painted_lights++;
    }
    int length = taper_idx_2 - taper_idx_1;
    for (int i = 0; i < min(200, length); ++i) {
      led_rope->RawDrawPixel(c);
      painted_lights++;
    }
    length = led_column_table[i] - taper_idx_2;
    for (int i = 0; i < length; ++i) {
      led_rope->RawDrawPixel(Color3i::Black());
      painted_lights++;
    }
    skipped_lights += MAX(0, static_cast<int32_t>(led_column_table[i]) - static_cast<int32_t>(painted_lights));
  }
  for (uint32_t i = 0; i < skipped_lights; ++i) {
    led_rope->RawDrawPixel(Color3i::Black());
  }
  led_rope->RawCommitDraw();
}
References Color3i::Black(), Key::curr_color_, KeyboardState::keys_, length(), MAX, LedRopeInterface::RawBeginDraw(), LedRopeInterface::RawCommitDraw(), LedRopeInterface::RawDrawPixel(), ColorHSV::ToRGB(), and ColorHSV::v_.
Referenced by Paint().