FastLED: computeOneTwinkle
computeOneTwinkle()
CRGB computeOneTwinkle (uint32_t ms, uint8_t salt)
Examples
TwinkleFox.ino.
Definition at line 221 of file TwinkleFox.ino.
{
  uint16_t ticks = ms >> (8-TWINKLE_SPEED);
  uint8_t fastcycle8 = ticks;
  uint16_t slowcycle16 = (ticks >> 8) + salt;
  slowcycle16 += sin8( slowcycle16);
  slowcycle16 =  (slowcycle16 * 2053) + 1384;
  uint8_t slowcycle8 = (slowcycle16 & 0xFF) + (slowcycle16 >> 8);
  uint8_t bright = 0;
  if( ((slowcycle8 & 0x0E)/2) < TWINKLE_DENSITY) {
    bright = attackDecayWave8( fastcycle8);
  }
  uint8_t hue = slowcycle8 - salt;
  CRGB c;
  if( bright > 0) {
    c = ColorFromPalette( gCurrentPalette, hue, bright, NOBLEND);
    if( COOL_LIKE_INCANDESCENT == 1 ) {
      coolLikeIncandescent( c, fastcycle8);
    }
  } else {
    c = CRGB::Black;
  }
  return c;
}
References attackDecayWave8(), CRGB::Black, ColorFromPalette(), COOL_LIKE_INCANDESCENT, coolLikeIncandescent(), gCurrentPalette, sin8, TWINKLE_DENSITY, and TWINKLE_SPEED.
Referenced by drawTwinkles().