FastLED: chooseNextColorPalette
chooseNextColorPalette()
void chooseNextColorPalette (CRGBPalette16 & pal)
Examples
TwinkleFox.ino.
Definition at line 376 of file TwinkleFox.ino.
{
  const uint8_t numberOfPalettes = sizeof(ActivePaletteList) / sizeof(ActivePaletteList[0]);
  static uint8_t whichPalette = -1;
  whichPalette = addmod8( whichPalette, 1, numberOfPalettes);
  pal = *(ActivePaletteList[whichPalette]);
}
References ActivePaletteList, and addmod8().
Referenced by loop(), and setup().