FastLED: loop
loop()
void loop ()
Definition at line 126 of file TwinkleFox.ino.
{
  EVERY_N_SECONDS( SECONDS_PER_PALETTE ) {
    chooseNextColorPalette( gTargetPalette );
  }
  EVERY_N_MILLISECONDS( 10 ) {
    nblendPaletteTowardPalette( gCurrentPalette, gTargetPalette, 12);
  }
  drawTwinkles( leds);
  FastLED.show();
}
References chooseNextColorPalette(), drawTwinkles(), EVERY_N_MILLISECONDS, EVERY_N_SECONDS, FastLED, gCurrentPalette, gTargetPalette, leds, nblendPaletteTowardPalette(), and SECONDS_PER_PALETTE.