FastLED: fl::XYPath::drawGradient
drawGradient()
void fl::XYPath::drawGradient (const Gradient & gradient, float from, float to, Leds * leds, int steps = -1)
Definition at line 280 of file xypath.cpp.
{
    XYRasterU8Sparse &raster = get_tls_raster().access();
    raster.clear();
    steps = steps > 0 ? steps : calculateSteps(from, to);
    rasterize(from, to, steps, raster);
    raster.drawGradient(gradient, leds->xymap(), leds->rgb());
}
References calculateSteps(), leds, raster, rasterize(), and steps().