FastLED: fl::XYPath::NewCustomPath
NewCustomPath()
XYPathPtr fl::XYPath::NewCustomPath (const fl::function< vec2f(float)> & path, const rect< i16 > & drawbounds = rect<i16>(), const TransformFloat & transform = TransformFloat(), const char * name = nullptr) static
Definition at line 240 of file xypath.cpp.
{
    XYPathFunctionPtr path = fl::make_shared<XYPathFunction>(f);
    path->setName(name);
    if (!drawbounds.empty()) {
        path->setDrawBounds(drawbounds);
    }
    XYPathPtr out = fl::make_shared<XYPath>(path);
    if (!transform.is_identity()) {
        out->setTransform(transform);
    }
    rect<i16> bounds;
    if (path->hasDrawBounds(&bounds)) {
        if (!bounds.mMin.is_zero()) {
            // Set the bounds to the path's bounds
            FASTLED_WARN(
                "Bounds with an origin other than 0,0 is not supported yet");
        }
        auto w = bounds.width();
        auto h = bounds.height();
        out->setDrawBounds(w, h);
    }
    return out;
}
References fl::rect< T >::empty(), FASTLED_WARN, fl::rect< T >::height(), fl::make_shared(), fl::rect< T >::mMin, name(), transform(), and fl::rect< T >::width().