FastLED: fl::XYPath::rasterize
rasterize()
void fl::XYPath::rasterize (float from, float to, int steps, XYRasterU8Sparse & raster, XYPath::AlphaFunction * optional_alpha_gen = nullptr)
Definition at line 60 of file xypath.cpp.
{
    mPathRenderer->rasterize(from, to, steps, raster, optional_alpha_gen);
}
References mPathRenderer, raster, and steps().
Referenced by drawColor(), and drawGradient().