FastLED: fl::XYPath::drawColor
drawColor()
void fl::XYPath::drawColor (const CRGB & color, float from, float to, Leds * leds, int steps = -1)
Definition at line 273 of file xypath.cpp.hpp.
{
    XYRasterU8Sparse &raster = get_tls_raster();
    raster.clear();
    steps = steps > 0 ? steps : calculateSteps(from, to);
    rasterize(from, to, steps, raster);
    raster.draw(color, leds);
}
References calculateSteps(), leds, raster(), rasterize(), and steps().