FastLED: fl::XYPath::NewCustomPath
NewCustomPath()
XYPathPtr fl::XYPath::NewCustomPath (const fl::function< vec2f(float)> & path, const rect< int16_t > & drawbounds = rect<int16_t>(), const TransformFloat & transform = TransformFloat(), const char * name = nullptr) static
Definition at line 239 of file xypath.cpp.
{
    XYPathFunctionPtr path = NewPtr<XYPathFunction>(f);
    path->setName(name);
    if (!drawbounds.empty()) {
        path->setDrawBounds(drawbounds);
    }
    XYPathPtr out = XYPathPtr::New(path);
    if (!transform.is_identity()) {
        out->setTransform(transform);
    }
    rect<int16_t> bounds;
    if (path->hasDrawBounds(&bounds)) {
        if (!bounds.mMin.is_zero()) {
            // Set the bounds to the path's bounds
            FASTLED_WARN(
                "Bounds with an origin other than 0,0 is not supported yet");
        }
        auto w = bounds.width();
        auto h = bounds.height();
        out->setDrawBounds(w, h);
    }
    return out;
}
References fl::rect< T >::empty(), FASTLED_WARN, fl::rect< T >::height(), fl::rect< T >::mMin, name(), fl::NewPtr(), transform(), and fl::rect< T >::width().