FastLED: xymap
xymap
XYMap xymap(WIDTH, HEIGHT, SERPENTINE) (WIDTH , HEIGHT , SERPENTINE)
Referenced by fl::Blend2d::Blend2d(), fl::RedSquare::RedSquare(), fl::ScaleUp::ScaleUp(), fl::WaveFx::WaveFx(), fl::XYDrawComposited::XYDrawComposited(), fl::XYDrawGradient::XYDrawGradient(), fl::EngineEvents::_onCanvasUiSet(), fl::blur2d(), fl::Tile2x2_u8::draw(), fl::Tile2x2_u8::draw(), fl::XYRasterU8Sparse::draw(), fl::XYRasterU8Sparse::draw(), fl::XYRasterU8Sparse::drawGradient(), loop(), fl::WaveCrgbGradientMap::mapWaveToLEDs(), fl::WaveCrgbMap::mapWaveToLEDs(), fl::WaveCrgbMapDefault::mapWaveToLEDs(), NewWaveSimulation2D(), fl::EngineEvents::onCanvasUiSet(), and setup().