FastLED: RGBWEmulatedController::showPixels
showPixels()
template<typename CONTROLLER, EOrder RGB_ORDER = GRB> virtual void RGBWEmulatedController< CONTROLLER, RGB_ORDER >::showPixels (PixelController< RGB_ORDER, LANES, MASK > & pixels) inline override virtual
Send the LED data to the strip.
Parameters
pixels the PixelController object for the LED data
Implements CPixelLEDController< GRB, CONTROLLER::LANES_VALUE, CONTROLLER::MASK_VALUE >.
Definition at line 153 of file chipsets.h.
{
        // Ensure buffer is large enough
        ensureBuffer(pixels.size());
        Rgbw rgbw = this->getRgbw();
        uint8_t *data = reinterpret_cast<uint8_t *>(mRGBWPixels);
        while (pixels.has(1)) {
            pixels.stepDithering();
            pixels.loadAndScaleRGBW(rgbw, data, data + 1, data + 2, data + 3);
            data += 4;
            pixels.advanceData();
        }
        // Force the device controller to a state where it passes data through
        // unmodified: color correction, color temperature, dither, and brightness
        // (passed as an argument to show()).  Temporarily enable the controller,
        // show the LEDs, and disable it again.
        //
        // The device controller is in the global controller list, so if we
        // don't keep it disabled, it will refresh again with unknown brightness,
        // temperature, etc.
        mController.setCorrection(CRGB(255, 255, 255));
        mController.setTemperature(CRGB(255, 255, 255));
        mController.setDither(DISABLE_DITHER);
        mController.setEnabled(true);
        mController.callShow(mRGBWPixels, Rgbw::size_as_rgb(pixels.size()), 255);
        mController.setEnabled(false);
    }
References PixelController< RGB_ORDER, LANES, MASK >::advanceData(), DISABLE_DITHER, ensureBuffer(), CLEDController::getRgbw(), PixelController< RGB_ORDER, LANES, MASK >::has(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGBW(), mController, mRGBWPixels, rgbw, PixelController< RGB_ORDER, LANES, MASK >::size(), Rgbw::size_as_rgb(), and PixelController< RGB_ORDER, LANES, MASK >::stepDithering().