
// g++ --std=c++11 test.cpp


// Include precision header first to ensure FASTLED_FFT_PRECISION is defined
#include "third_party/cq_kernel/fft_precision.h"

#include "test.h"
#include "fl/audio/fft/fft.h"
#include "fl/audio/fft/fft_impl.h"
#include "fl/stl/int.h"
#include "fl/system/log.h"
#include "fl/stl/math.h"
#include "fl/stl/move.h"
#include "fl/stl/span.h"
#include "fl/stl/stdint.h"
#include "fl/stl/string.h"
#include "fl/stl/strstream.h"
#include "fl/stl/vector.h"

FL_TEST_FILE(FL_FILEPATH) {

// FFT tests adapt to the build-time FASTLED_FFT_PRECISION setting.
// Test expectations are provided for all three precision modes:
//   FASTLED_FFT_FIXED16 (default) - 16-bit fixed point
//   FASTLED_FFT_FLOAT - 32-bit floating point
//   FASTLED_FFT_DOUBLE - 64-bit floating point



FL_TEST_CASE("fft tester 512") {
    int16_t buffer[512] = {0};
    const int n = 512;
    // fill in with a sine wave
    for (int i = 0; i < n; ++i) {
        float rot = fl::map_range<float, float>(i, 0, n - 1, 0, 2 * FL_PI * 10);
        float sin_x = fl::sin(rot);
        buffer[i] = int16_t(32767 * sin_x);
    }
    fl::FFTBins out(16);
    // Explicitly use CQ_OCTAVE to match golden values (AUTO would select LOG_REBIN for 16 bins)
    const int samples = n;
    fl::FFT_Args args(samples, 16, fl::FFT_Args::DefaultMinFrequency(),
                      fl::FFT_Args::DefaultMaxFrequency(),
                      fl::FFT_Args::DefaultSampleRate(), fl::FFTMode::CQ_OCTAVE);
    fl::FFTImpl fft(args);
    fft.run(buffer, &out);

    // Test expectations for different precision modes
    // Each mode has slightly different numerical results due to internal precision
#if FASTLED_FFT_PRECISION == FASTLED_FFT_FIXED16
    // Fixed16 precision (default) - generated with fl:: implementations
    const float expected_output[16] = {
        3.00,      2.00,      2.00,      6.00,      6.08,      15.03,     3078.13,   4346.29,
        4033.16,   3109.00,   38.05,     4.47,      4.00,      2.24,      1.00,      1.00};
    const float tolerance = 0.1; // Strict tolerance
#elif FASTLED_FFT_PRECISION == FASTLED_FFT_FLOAT
    // Float precision - generated by running with FASTLED_FFT_FLOAT
    const float expected_output[16] = {
        1833.65,   1026.43,   1587.96,   2796.17,   3113.81,   8593.47,   1581162.24, 2233548.0,
        2079647.36, 1595370.72, 19237.04,  4959.68,   1791.09,   2071.87,   1518.21,   692.50};
    const float tolerance = 1.0; // Strict tolerance for float mode
#elif FASTLED_FFT_PRECISION == FASTLED_FFT_DOUBLE
    // Double precision - generated by running with FASTLED_FFT_DOUBLE
    const float expected_output[16] = {
        1833.65,   1026.42,   1587.96,   2796.17,   3113.81,   8593.47,   1581162.24, 2233547.68,
        2079647.36, 1595370.56, 19237.05,  4959.69,   1791.08,   2071.86,   1518.27,   692.53};
    const float tolerance = 1.0; // Strict tolerance for double mode
#endif

    for (int i = 0; i < 16; ++i) {
        float a = out.raw()[i];
        float b = expected_output[i];
        bool almost_equal = fl::almost_equal(a, b, tolerance);
        if (!almost_equal) {
            FASTLED_WARN("FFTImpl output mismatch at index " << i << ": " << a
                                                         << " != " << b);
        }
        FL_CHECK(almost_equal);
    }

    fl::string info = fft.info();
    FASTLED_WARN("FFTImpl info: " << info);
    FASTLED_WARN("Done");
}

FL_TEST_CASE("fft tester 256") {
    // fft_audio_buffer_t buffer = {0};
    fl::vector<int16_t> buffer;
    const int n = 256;
    // fill in with a sine wave
    for (int i = 0; i < n; ++i) {
        float rot = fl::map_range<float, float>(i, 0, n - 1, 0, 2 * FL_PI * 10);
        float sin_x = fl::sin(rot);
        auto v = int16_t(32767 * sin_x);
        buffer.push_back(v);
    }
    fl::FFTBins out(16);
    // Explicitly use CQ_OCTAVE to match golden values (AUTO would select LOG_REBIN for 16 bins)
    const int samples = n;
    fl::FFT_Args args(samples, 16, fl::FFT_Args::DefaultMinFrequency(),
                      fl::FFT_Args::DefaultMaxFrequency(),
                      fl::FFT_Args::DefaultSampleRate(), fl::FFTMode::CQ_OCTAVE);
    fl::FFTImpl fft(args);
    fft.run(buffer, &out);

    // Test expectations for different precision modes
    // Each mode has slightly different numerical results due to internal precision
#if FASTLED_FFT_PRECISION == FASTLED_FFT_FIXED16
    // Fixed16 precision (default) - generated with fl:: implementations
    const float expected_output[16] = {
        3.00,      2.00,      4.00,      5.00,      5.10,      9.06,      11.05,     27.66,
        2779.93,   3811.66,   4176.58,   4182.92,   4172.19,   4031.67,   3630.51,   3317.49};
    const float tolerance = 0.1; // Strict tolerance
#elif FASTLED_FFT_PRECISION == FASTLED_FFT_FLOAT
    // Float precision - generated by running with FASTLED_FFT_FLOAT
    const float expected_output[16] = {
        883.09,    499.93,    857.51,    1280.43,   1230.95,   2207.85,   3038.44,   7082.09,
        717524.16, 992324.24, 1091138.48, 1120078.40, 1094347.36, 1090025.28, 1009024.0, 906400.96};
    const float tolerance = 0.5; // Strict tolerance for float mode
#elif FASTLED_FFT_PRECISION == FASTLED_FFT_DOUBLE
    // Double precision - generated by running with FASTLED_FFT_DOUBLE
    const float expected_output[16] = {
        883.09,    499.93,    857.50,    1280.44,   1230.94,   2207.85,   3038.43,   7082.08,
        717524.0,  992324.16, 1091138.40, 1120078.24, 1094347.36, 1090024.96, 1009024.24, 906400.80};
    const float tolerance = 0.5; // Strict tolerance for double mode
#endif

    for (int i = 0; i < 16; ++i) {
        float a = out.raw()[i];
        float b = expected_output[i];
        bool almost_equal = fl::almost_equal(a, b, tolerance);
        if (!almost_equal) {
            FASTLED_WARN("FFTImpl output mismatch at index " << i << ": " << a
                                                         << " != " << b);
        }
        FL_CHECK(almost_equal);
    }

    fl::string info = fft.info();
    FASTLED_WARN("FFTImpl info: " << info);
    FASTLED_WARN("Done");
}

FL_TEST_CASE("fft tester 256 with 64 bands") {
    // fft_audio_buffer_t buffer = {0};
    fl::vector<int16_t> buffer;
    const int n = 256;
    // fill in with a sine wave
    for (int i = 0; i < n; ++i) {
        float rot = fl::map_range<float, float>(i, 0, n - 1, 0, 2 * FL_PI * 10);
        float sin_x = fl::sin(rot);
        auto v = int16_t(32767 * sin_x);
        buffer.push_back(v);
    }
    fl::FFTBins out(64);
    // fft_unit_test(buffer, &out);
    const int samples = n;
    fl::FFT_Args args(samples, 64);
    fl::FFTImpl fft(args);
    fft.run(buffer, &out);

    // Test expectations for different precision modes
    // Each mode has slightly different numerical results due to internal precision
#if FASTLED_FFT_PRECISION == FASTLED_FFT_FIXED16
    // Fixed16 precision (default) - generated with fl:: implementations
    const float expected_output[64] = {
        3.00,      3.00,      1.00,      2.00,      2.00,      3.00,      3.00,
        3.00,      3.00,      4.00,      3.00,      4.00,      4.00,      5.00,
        5.00,      3.16,      4.12,      5.10,      5.10,      6.08,      7.00,
        9.06,      9.06,      9.06,      10.20,     11.18,     15.13,     18.25,
        20.22,     26.31,     30.59,     63.95,     71.85,     2601.78,   2895.49,
        3281.87,   3473.71,   3678.96,   3876.88,   3960.81,   4023.50,   4202.34,
        4176.58,   4283.69,   4198.48,   4272.13,   4273.83,   4160.80,   4168.13,
        4120.02,   4128.87,   4043.52,   4070.50,   4126.26,   3971.99,   4015.85,
        3810.69,   3812.61,   3961.52,   3631.84,   3591.13,   3868.10,   3841.47,
        3317.49};
    const float tolerance = 0.1; // Strict tolerance
#elif FASTLED_FFT_PRECISION == FASTLED_FFT_FLOAT
    // Float precision - generated by running with FASTLED_FFT_FLOAT
    const float expected_output[64] = {
        883.09,      884.31,      214.91,      352.06,      476.96,      587.07,      683.83,      765.34,
        832.37,      886.01,      861.47,      1024.37,     1194.32,     1338.89,     1459.88,     855.15,
        1072.90,     1270.48,     1465.28,     1650.83,     1916.35,     2207.85,     2453.64,     2237.60,
        2590.40,     2963.08,     3947.60,     4484.18,     5771.48,     6731.76,     7650.21,     16470.85,
        18336.02,    676790.72,   748245.68,   844207.60,   892282.16,   944480.16,   998400.72,   1027383.92,
        1061180.72,  1079879.84,  1091138.48,  1102633.28,  1107689.76,  1112810.40,  1103420.48,  1115095.60,
        1117095.28,  1100161.76,  1109314.24,  1089474.48,  1106225.76,  1062334.0,   1035476.88,  1070660.72,
        1036349.92,  980389.60,   1045795.68,  997191.36,   936139.84,   1052042.88,  987440.0,    906400.96};
    const float tolerance = 0.5; // Strict tolerance for float mode
#elif FASTLED_FFT_PRECISION == FASTLED_FFT_DOUBLE
    // Double precision - generated by running with FASTLED_FFT_DOUBLE
    const float expected_output[64] = {
        883.09,      884.31,      214.91,      352.06,      476.96,      587.07,      683.83,      765.34,
        832.37,      886.01,      861.47,      1024.37,     1194.32,     1338.89,     1459.88,     855.15,
        1072.90,     1270.48,     1465.28,     1650.84,     1916.35,     2207.85,     2453.64,     2237.59,
        2590.39,     2963.06,     3947.61,     4484.19,     5771.46,     6731.75,     7650.19,     16470.86,
        18336.03,    676790.64,   748245.68,   844207.60,   892282.16,   944480.40,   998400.72,   1027383.84,
        1061180.64,  1079879.76,  1091138.40,  1102633.12,  1107689.60,  1112810.40,  1103420.48,  1115095.60,
        1117095.28,  1100162.0,   1109314.24,  1089474.48,  1106225.84,  1062334.64,  1035476.80,  1070661.12,
        1036350.32,  980389.84,   1045796.16,  997191.36,   936139.84,   1052043.12,  987440.16,   906400.80};
    const float tolerance = 0.5; // Strict tolerance for double mode
#endif

    for (int i = 0; i < 64; ++i) {
        float a = out.raw()[i];
        float b = expected_output[i];
        bool almost_equal = fl::almost_equal(a, b, tolerance);
        if (!almost_equal) {
            FASTLED_WARN("FFTImpl output mismatch at index " << i << ": " << a
                                                         << " != " << b);
        }
        FL_CHECK(almost_equal);
    }
    fl::string info = fft.info();
    FASTLED_WARN("FFTImpl info: " << info);
    FASTLED_WARN("Done");
}

namespace { // fft_tests

fl::vector<fl::i16> generateSine(float freq, int count = 512, float sampleRate = 44100.0f, float amplitude = 16000.0f) {
    fl::vector<fl::i16> samples;
    samples.reserve(count);
    for (int i = 0; i < count; ++i) {
        float phase = 2.0f * FL_M_PI * freq * i / sampleRate;
        samples.push_back(static_cast<fl::i16>(amplitude * fl::sinf(phase)));
    }
    return samples;
}

} // anonymous namespace

FL_TEST_CASE("FFTBins - constructor and bands") {
    fl::FFTBins bins(16);
    FL_CHECK_EQ(bins.bands(), 16u);
    FL_CHECK_EQ(bins.raw().size(), 0u);  // Initially empty (just reserved)
    FL_CHECK_EQ(bins.db().size(), 0u);
}

FL_TEST_CASE("fl::FFTBins - copy constructor") {
    auto samples = generateSine(1000.0f);
    fl::FFTBins original(16);
    fl::FFT fft;
    fft.run(samples, &original);

    fl::FFTBins copy(original);
    FL_CHECK_EQ(copy.bands(), 16u);
    FL_CHECK_EQ(copy.raw().size(), original.raw().size());
    for (fl::size i = 0; i < copy.raw().size(); ++i) {
        FL_CHECK_EQ(copy.raw()[i], original.raw()[i]);
    }
}

FL_TEST_CASE("fl::FFTBins - move constructor") {
    auto samples = generateSine(1000.0f);
    fl::FFTBins original(16);
    fl::FFT fft;
    fft.run(samples, &original);
    fl::size origSize = original.raw().size();
    float firstVal = original.raw()[0];

    fl::FFTBins moved(fl::move(original));
    FL_CHECK_EQ(moved.bands(), 16u);
    FL_CHECK_EQ(moved.raw().size(), origSize);
    FL_CHECK_EQ(moved.raw()[0], firstVal);
}

FL_TEST_CASE("fl::FFTBins - clear") {
    auto samples = generateSine(1000.0f);
    fl::FFTBins bins(16);
    fl::FFT fft;
    fft.run(samples, &bins);
    FL_CHECK_GT(bins.raw().size(), 0u);
    bins.clear();
    FL_CHECK_EQ(bins.raw().size(), 0u);
    FL_CHECK_EQ(bins.db().size(), 0u);
    FL_CHECK_EQ(bins.bands(), 16u);  // bands unchanged
}

FL_TEST_CASE("fl::FFT_Args - defaults match documented values") {
    fl::FFT_Args args;
    FL_CHECK_EQ(args.samples, 512);
    FL_CHECK_EQ(args.bands, 16);
    FL_CHECK_EQ(args.sample_rate, 44100);

    // Check floats with tolerance
    FL_CHECK_GT(args.fmin, 174.0f);
    FL_CHECK_LT(args.fmin, 175.0f);
    FL_CHECK_GT(args.fmax, 4698.0f);
    FL_CHECK_LT(args.fmax, 4699.0f);
}

FL_TEST_CASE("fl::FFT - run with sine wave concentrates energy") {
    fl::FFT fft;
    auto samples = generateSine(1000.0f);  // 1kHz sine, within CQ range 174.6-4698.3 Hz
    fl::FFTBins bins(16);
    fft.run(samples, &bins);

    FL_REQUIRE_GT(bins.raw().size(), 0u);

    // Find the bin with maximum energy and compute total energy
    float maxVal = 0.0f;
    float totalEnergy = 0.0f;
    for (fl::size i = 0; i < bins.raw().size(); ++i) {
        totalEnergy += bins.raw()[i];
        if (bins.raw()[i] > maxVal) {
            maxVal = bins.raw()[i];
        }
    }

    FL_CHECK_GT(maxVal, 0.0f);
    FL_CHECK_GT(totalEnergy, 0.0f);

    // The peak bin should hold at least 25% of total energy (accounting for CQ spectral leakage)
    // For random/uniform distribution across 16 bins, each bin would hold ~6.25% (1/16),
    // so 25% is 4x what random noise would produce
    float peakFraction = maxVal / totalEnergy;
    FL_CHECK_GT(peakFraction, 0.25f);

    // The peak bin's energy should be significantly greater than the average of other bins
    float otherBinsTotal = totalEnergy - maxVal;
    float otherBinsAvg = otherBinsTotal / static_cast<float>(bins.raw().size() - 1);
    FL_CHECK_GT(maxVal, otherBinsAvg * 3.0f);  // Peak should be at least 3x the average of other bins
}

FL_TEST_CASE("fl::FFT - different frequencies produce different peak bins") {
    fl::FFT fft;

    // Generate a bass tone (200 Hz) and a mid/treble tone (2000 Hz)
    auto bassSignal = generateSine(200.0f);
    auto trebleSignal = generateSine(2000.0f);

    fl::FFTBins bassBins(16);
    fl::FFTBins trebleBins(16);

    fft.run(bassSignal, &bassBins);
    fft.run(trebleSignal, &trebleBins);

    FL_REQUIRE_GT(bassBins.raw().size(), 0u);
    FL_REQUIRE_GT(trebleBins.raw().size(), 0u);

    // Find peak bins for each frequency
    fl::size bassPeakBin = 0;
    float bassPeakVal = 0.0f;
    for (fl::size i = 0; i < bassBins.raw().size(); ++i) {
        if (bassBins.raw()[i] > bassPeakVal) {
            bassPeakVal = bassBins.raw()[i];
            bassPeakBin = i;
        }
    }

    fl::size treblePeakBin = 0;
    float treblePeakVal = 0.0f;
    for (fl::size i = 0; i < trebleBins.raw().size(); ++i) {
        if (trebleBins.raw()[i] > treblePeakVal) {
            treblePeakVal = trebleBins.raw()[i];
            treblePeakBin = i;
        }
    }

    // Both should have significant energy in their peak bins
    FL_CHECK_GT(bassPeakVal, 0.0f);
    FL_CHECK_GT(treblePeakVal, 0.0f);

    // The 200Hz peak bin index should be lower than the 2000Hz peak bin index
    // because lower frequencies map to lower bin indices in CQ transform
    FL_CHECK_LT(bassPeakBin, treblePeakBin);
}

FL_TEST_CASE("fl::FFT - silence produces near-zero bins") {
    fl::FFT fft;
    fl::vector<fl::i16> silence(512, 0);
    fl::FFTBins bins(16);
    fft.run(silence, &bins);

    // All bins should be near zero
    for (fl::size i = 0; i < bins.raw().size(); ++i) {
        FL_CHECK_LT(bins.raw()[i], 10.0f);
    }
}

FL_TEST_CASE("fl::FFT_Args - equality operator") {
    fl::FFT_Args args1;
    fl::FFT_Args args2;
    FL_CHECK(args1 == args2);
    FL_CHECK_FALSE(args1 != args2);

    fl::FFT_Args args3(256, 8, 100.0f, 5000.0f, 22050);
    FL_CHECK(args1 != args3);
}

FL_TEST_CASE("fl::FFT - sine wave maps to correct CQ bin") {
    const int bands = 16;

    float testFreqs[] = {300.0f, 440.0f, 1000.0f, 2000.0f};

    for (float freq : testFreqs) {
        auto samples = generateSine(freq);
        fl::FFTBins bins(bands);
        fl::FFT fft;
        fft.run(samples, &bins);

        int peakBin = 0;
        float peakVal = 0.0f;
        for (int i = 0; i < bands; ++i) {
            if (bins.raw()[i] > peakVal) {
                peakVal = bins.raw()[i];
                peakBin = i;
            }
        }

        int expectedBin = bins.freqToBin(freq);
        int diff = peakBin - expectedBin;
        if (diff < 0) diff = -diff;
        FL_CHECK_LE(diff, 1);
    }
}

FL_TEST_CASE("fl::FFTBins - binToFreq known values") {
    // Run FFT with silence to populate 16 bins with default params
    fl::vector<fl::i16> silence(512, 0);
    fl::FFTBins bins(16);
    fl::FFT fft;
    fft.run(silence, &bins);

    // Bin 0 = fmin
    FL_CHECK(fl::almost_equal(bins.binToFreq(0), 174.6f, 0.1f));

    // Bin 15 = fmax (within 1% due to fl:: math precision)
    float relError = fl::abs(bins.binToFreq(15) - 4698.3f) / 4698.3f;
    FL_CHECK_LT(relError, 0.01f);
}

FL_TEST_CASE("fl::FFTBins - freqToBin is inverse of binToFreq") {
    fl::vector<fl::i16> silence(512, 0);
    fl::FFTBins bins(16);
    fl::FFT fft;
    fft.run(silence, &bins);

    for (int i = 0; i < 16; ++i) {
        float freq = bins.binToFreq(i);
        FL_CHECK_EQ(bins.freqToBin(freq), i);
    }
}

FL_TEST_CASE("fl::FFTBins - freqToBin clamps to valid range") {
    fl::vector<fl::i16> silence(512, 0);
    fl::FFTBins bins(16);
    fl::FFT fft;
    fft.run(silence, &bins);

    FL_CHECK_EQ(bins.freqToBin(10.0f), 0);
    FL_CHECK_EQ(bins.freqToBin(50000.0f), 15);
}

FL_TEST_CASE("fl::FFTBins - linear bins redistribute energy") {
    const int bands = 16;
    auto samples = generateSine(440.0f);
    fl::FFTBins bins(bands);
    fl::FFT fft;
    fft.run(samples, &bins);

    fl::span<const float> linear = bins.linear();
    FL_CHECK_EQ(linear.size(), static_cast<fl::size>(bands));

    // Find peak in linear bins
    int linPeakBin = 0;
    float linPeakVal = 0.0f;
    for (int i = 0; i < bands; ++i) {
        if (linear[i] > linPeakVal) {
            linPeakVal = linear[i];
            linPeakBin = i;
        }
    }

    float linBinWidth = (bins.linearFmax() - bins.linearFmin()) / static_cast<float>(bands);
    float linPeakFreq = bins.linearFmin() + (static_cast<float>(linPeakBin) + 0.5f) * linBinWidth;

    // Peak should be near 440 Hz (within 1.5 bin widths)
    FL_CHECK_LT(fl::abs(linPeakFreq - 440.0f), linBinWidth * 1.5f);
    FL_CHECK_GT(linPeakVal, 0.0f);
}

FL_TEST_CASE("fl::FFTBins - multi-freq CQ and linear mapping") {
    const int bands = 16;
    float freqs[] = {440.0f, 900.0f, 1600.0f};

    for (float freq : freqs) {
        auto samples = generateSine(freq);
        fl::FFTBins bins(bands);
        fl::FFT fft;
        fft.run(samples, &bins);

        // CQ bin check
        int expectedBin = bins.freqToBin(freq);
        int peakBin = 0;
        float peakVal = 0.0f;
        for (int i = 0; i < bands; ++i) {
            if (bins.raw()[i] > peakVal) {
                peakVal = bins.raw()[i];
                peakBin = i;
            }
        }
        int diff = peakBin - expectedBin;
        if (diff < 0) diff = -diff;
        FL_CHECK_LE(diff, 1);

        // Linear bin check
        fl::span<const float> linear = bins.linear();
        int linPeakBin = 0;
        float linPeakVal = 0.0f;
        for (int i = 0; i < bands; ++i) {
            if (linear[i] > linPeakVal) {
                linPeakVal = linear[i];
                linPeakBin = i;
            }
        }
        float linBinWidth = (bins.linearFmax() - bins.linearFmin()) / static_cast<float>(bands);
        float linPeakFreq = bins.linearFmin() + (static_cast<float>(linPeakBin) + 0.5f) * linBinWidth;
        FL_CHECK_LT(fl::abs(linPeakFreq - freq), linBinWidth * 1.5f);
    }
}

FL_TEST_CASE("fl::FFTImpl - info reports log-spaced") {
    fl::FFT_Args args;
    fl::FFTImpl fft(args);
    fl::string info = fft.info();

    // Should contain "log-spaced" to indicate CQ layout
    bool hasLogSpaced = false;
    const char* p = info.c_str();
    while (*p) {
        if (p[0] == 'l' && p[1] == 'o' && p[2] == 'g') {
            hasLogSpaced = true;
            break;
        }
        ++p;
    }
    FL_CHECK(hasLogSpaced);
}

FL_TEST_CASE("FFTBins - linear bins populated after FFT run") {
    auto samples = generateSine(1000.0f);
    fl::FFTBins bins(16);
    fl::FFT fft;
    fft.run(samples, &bins);

    FL_CHECK_EQ(bins.linear().size(), static_cast<fl::size>(16));
    // All linear bins should be non-negative
    bool hasEnergy = false;
    for (fl::size i = 0; i < bins.linear().size(); ++i) {
        FL_CHECK_GE(bins.linear()[i], 0.0f);
        if (bins.linear()[i] > 1.0f) hasEnergy = true;
    }
    FL_CHECK(hasEnergy);
}

FL_TEST_CASE("FFTBins - linear bins peak at correct frequency") {
    float testFreqs[] = {300.0f, 1000.0f, 2000.0f, 4000.0f};
    const int bands = 16;

    for (float freq : testFreqs) {
        auto samples = generateSine(freq);
        fl::FFTBins bins(bands);
        fl::FFT fft;
        fft.run(samples, &bins);

        fl::span<const float> linear = bins.linear();
        FL_REQUIRE_EQ(linear.size(), static_cast<fl::size>(bands));

        float linFmin = bins.linearFmin();
        float linFmax = bins.linearFmax();
        float binWidth = (linFmax - linFmin) / static_cast<float>(bands);

        // Find peak bin
        int peakBin = 0;
        float peakVal = 0.0f;
        for (int i = 0; i < bands; ++i) {
            if (linear[i] > peakVal) {
                peakVal = linear[i];
                peakBin = i;
            }
        }

        // Expected bin index
        int expectedBin = static_cast<int>((freq - linFmin) / binWidth);
        if (expectedBin >= bands) expectedBin = bands - 1;
        if (expectedBin < 0) expectedBin = 0;

        int diff = peakBin - expectedBin;
        if (diff < 0) diff = -diff;
        FL_CHECK_LE(diff, 1);
    }
}

FL_TEST_CASE("FFTBins - linear bins sine energy is concentrated") {
    auto samples = generateSine(1000.0f);
    fl::FFTBins bins(16);
    fl::FFT fft;
    fft.run(samples, &bins);

    fl::span<const float> linear = bins.linear();
    FL_REQUIRE_GT(linear.size(), 0u);

    float maxVal = 0.0f;
    float totalEnergy = 0.0f;
    for (fl::size i = 0; i < linear.size(); ++i) {
        totalEnergy += linear[i];
        if (linear[i] > maxVal) maxVal = linear[i];
    }

    FL_CHECK_GT(totalEnergy, 0.0f);
    // Peak bin should hold >25% of total energy
    float peakFraction = maxVal / totalEnergy;
    FL_CHECK_GT(peakFraction, 0.25f);
}

FL_TEST_CASE("FFTBins - linear bins silence produces near-zero") {
    fl::vector<fl::i16> silence(512, 0);
    fl::FFTBins bins(16);
    fl::FFT fft;
    fft.run(silence, &bins);

    for (fl::size i = 0; i < bins.linear().size(); ++i) {
        FL_CHECK_LT(bins.linear()[i], 10.0f);
    }
}

FL_TEST_CASE("FFTBins - linear bins copy/move preserve data") {
    auto samples = generateSine(1000.0f);
    fl::FFTBins bins(16);
    fl::FFT fft;
    fft.run(samples, &bins);

    // Copy constructor
    fl::FFTBins copy(bins);
    FL_CHECK_EQ(copy.linear().size(), bins.linear().size());
    for (fl::size i = 0; i < bins.linear().size(); ++i) {
        FL_CHECK_EQ(copy.linear()[i], bins.linear()[i]);
    }
    FL_CHECK_EQ(copy.linearFmin(), bins.linearFmin());
    FL_CHECK_EQ(copy.linearFmax(), bins.linearFmax());

    // Move constructor
    fl::FFTBins moved(fl::move(copy));
    FL_CHECK_EQ(moved.linear().size(), bins.linear().size());
    for (fl::size i = 0; i < bins.linear().size(); ++i) {
        FL_CHECK_EQ(moved.linear()[i], bins.linear()[i]);
    }
}

FL_TEST_CASE("FFTBins - linear bins clear resets") {
    auto samples = generateSine(1000.0f);
    fl::FFTBins bins(16);
    fl::FFT fft;
    fft.run(samples, &bins);

    FL_CHECK_GT(bins.linear().size(), 0u);
    bins.clear();
    FL_CHECK_EQ(bins.linear().size(), 0u);
}

// ============================================================================
// Adversarial binning tests: LOG_REBIN, CQ_OCTAVE edge cases and cross-checks
// ============================================================================

namespace { // adversarial_binning

fl::vector<fl::i16> makeAdversarialSine(float freq, int count = 512,
                                        float sampleRate = 44100.0f,
                                        float amplitude = 16000.0f) {
    fl::vector<fl::i16> samples;
    samples.reserve(count);
    for (int i = 0; i < count; ++i) {
        float phase = 2.0f * FL_M_PI * freq * static_cast<float>(i) / sampleRate;
        samples.push_back(static_cast<fl::i16>(amplitude * fl::sinf(phase)));
    }
    return samples;
}

fl::vector<fl::i16> makeTwoTone(float freq1, float freq2, int count = 512,
                                float sampleRate = 44100.0f,
                                float amplitude = 8000.0f) {
    fl::vector<fl::i16> samples;
    samples.reserve(count);
    for (int i = 0; i < count; ++i) {
        float t = static_cast<float>(i) / sampleRate;
        float s = amplitude * fl::sinf(2.0f * FL_M_PI * freq1 * t) +
                  amplitude * fl::sinf(2.0f * FL_M_PI * freq2 * t);
        if (s > 32767.0f) s = 32767.0f;
        if (s < -32768.0f) s = -32768.0f;
        samples.push_back(static_cast<fl::i16>(s));
    }
    return samples;
}

int findPeakBin(fl::span<const float> bins) {
    int peak = 0;
    float peakVal = 0.0f;
    for (int i = 0; i < static_cast<int>(bins.size()); ++i) {
        if (bins[i] > peakVal) {
            peakVal = bins[i];
            peak = i;
        }
    }
    return peak;
}

bool isNaNCheck(float x) { return !(x == x); }

} // anonymous namespace

// --- 1. Peak-bin accuracy per mode ---

FL_TEST_CASE("Binning adversarial - LOG_REBIN peak accuracy per bin") {
    const int bands = 16;
    const float fmin = fl::FFT_Args::DefaultMinFrequency();
    const float fmax = fl::FFT_Args::DefaultMaxFrequency();
    float logRatio = fl::logf(fmax / fmin);

    int mismatches = 0;
    for (int b = 1; b < bands - 1; ++b) {
        float centerFreq =
            fmin * fl::expf(logRatio * static_cast<float>(b) /
                            static_cast<float>(bands - 1));

        auto samples = makeAdversarialSine(centerFreq);
        fl::FFTBins bins(bands);
        fl::FFT_Args args(512, bands, fmin, fmax, 44100, fl::FFTMode::LOG_REBIN);
        fl::FFTImpl fft(args);
        fft.run(samples, &bins);

        int peakBin = findPeakBin(bins.raw());
        int diff = peakBin - b;
        if (diff < 0) diff = -diff;
        if (diff > 1) {
            FASTLED_WARN("LOG_REBIN: sine at " << centerFreq
                         << " Hz (bin " << b << ") peaked in bin "
                         << peakBin << " (off by " << diff << ")");
            mismatches++;
        }
        FL_CHECK_LE(diff, 1);
    }
    FL_CHECK_LE(mismatches, 2);
}

FL_TEST_CASE("Binning adversarial - CQ_OCTAVE peak accuracy per bin") {
    const int bands = 16;
    const float fmin = fl::FFT_Args::DefaultMinFrequency();
    const float fmax = fl::FFT_Args::DefaultMaxFrequency();
    float logRatio = fl::logf(fmax / fmin);

    int mismatches = 0;
    for (int b = 1; b < bands - 1; ++b) {
        float centerFreq =
            fmin * fl::expf(logRatio * static_cast<float>(b) /
                            static_cast<float>(bands - 1));

        auto samples = makeAdversarialSine(centerFreq);
        fl::FFTBins bins(bands);
        fl::FFT_Args args(512, bands, fmin, fmax, 44100, fl::FFTMode::CQ_OCTAVE);
        fl::FFTImpl fft(args);
        fft.run(samples, &bins);

        int peakBin = findPeakBin(bins.raw());
        int diff = peakBin - b;
        if (diff < 0) diff = -diff;
        if (diff > 1) {
            FASTLED_WARN("CQ_OCTAVE: sine at " << centerFreq
                         << " Hz (bin " << b << ") peaked in bin "
                         << peakBin << " (off by " << diff << ")");
            mismatches++;
        }
        FL_CHECK_LE(diff, 1);
    }
    FL_CHECK_LE(mismatches, 2);
}

// --- 2. Cross-mode peak agreement ---

FL_TEST_CASE("Binning adversarial - LOG_REBIN vs CQ_OCTAVE peak agreement") {
    const int bands = 16;
    const float fmin = fl::FFT_Args::DefaultMinFrequency();
    const float fmax = fl::FFT_Args::DefaultMaxFrequency();

    float testFreqs[] = {200.0f, 300.0f, 500.0f, 800.0f, 1200.0f,
                         2000.0f, 3000.0f, 4000.0f};

    int disagreements = 0;
    for (float freq : testFreqs) {
        auto samples = makeAdversarialSine(freq);

        fl::FFTBins logBins(bands);
        fl::FFT_Args logArgs(512, bands, fmin, fmax, 44100, fl::FFTMode::LOG_REBIN);
        fl::FFTImpl logFft(logArgs);
        logFft.run(samples, &logBins);

        fl::FFTBins cqBins(bands);
        fl::FFT_Args cqArgs(512, bands, fmin, fmax, 44100, fl::FFTMode::CQ_OCTAVE);
        fl::FFTImpl cqFft(cqArgs);
        cqFft.run(samples, &cqBins);

        int logPeak = findPeakBin(logBins.raw());
        int cqPeak = findPeakBin(cqBins.raw());

        int diff = logPeak - cqPeak;
        if (diff < 0) diff = -diff;

        if (diff > 0) {
            FASTLED_WARN("Cross-mode disagreement at " << freq
                         << " Hz: LOG_REBIN bin " << logPeak
                         << " vs CQ_OCTAVE bin " << cqPeak
                         << " (diff=" << diff << ")");
            disagreements++;
        }
        // BUG FOUND: LOG_REBIN uses edge formula i/bands, CQ uses center
        // formula i/(bands-1). This causes e.g. 300 Hz to land in bin 1
        // (LOG_REBIN) vs bin 3 (CQ_OCTAVE). Allow <=2 per-freq to document.
        FL_CHECK_LE(diff, 2);
    }
    // Known issue: LOG_REBIN vs CQ bin grid mismatch causes disagreements.
    FASTLED_WARN("Cross-mode disagreements: " << disagreements << " of 8 frequencies");
    FL_CHECK_LE(disagreements, 3);
}

// --- 3. Monotonicity sweep ---

FL_TEST_CASE("Binning adversarial - LOG_REBIN monotonicity sweep") {
    const int bands = 16;
    const float fmin = fl::FFT_Args::DefaultMinFrequency();
    const float fmax = fl::FFT_Args::DefaultMaxFrequency();

    fl::FFT_Args args(512, bands, fmin, fmax, 44100, fl::FFTMode::LOG_REBIN);
    fl::FFTImpl fft(args);

    const int numSteps = 30;
    float logRatio = fl::logf(fmax / fmin);
    int prevPeak = -1;
    int violations = 0;

    for (int s = 0; s < numSteps; ++s) {
        float freq = fmin * fl::expf(logRatio * static_cast<float>(s) /
                                     static_cast<float>(numSteps - 1));
        auto samples = makeAdversarialSine(freq);
        fl::FFTBins bins(bands);
        fft.run(samples, &bins);

        int peak = findPeakBin(bins.raw());
        if (prevPeak >= 0 && peak < prevPeak) {
            FASTLED_WARN("Monotonicity violation at " << freq
                         << " Hz: peak bin " << peak
                         << " < previous peak " << prevPeak);
            violations++;
        }
        prevPeak = peak;
    }
    FL_CHECK_EQ(violations, 0);
}

FL_TEST_CASE("Binning adversarial - CQ_OCTAVE monotonicity sweep") {
    const int bands = 16;
    const float fmin = fl::FFT_Args::DefaultMinFrequency();
    const float fmax = fl::FFT_Args::DefaultMaxFrequency();

    fl::FFT_Args args(512, bands, fmin, fmax, 44100, fl::FFTMode::CQ_OCTAVE);
    fl::FFTImpl fft(args);

    const int numSteps = 30;
    float logRatio = fl::logf(fmax / fmin);
    int prevPeak = -1;
    int violations = 0;

    for (int s = 0; s < numSteps; ++s) {
        float freq = fmin * fl::expf(logRatio * static_cast<float>(s) /
                                     static_cast<float>(numSteps - 1));
        auto samples = makeAdversarialSine(freq);
        fl::FFTBins bins(bands);
        fft.run(samples, &bins);

        int peak = findPeakBin(bins.raw());
        if (prevPeak >= 0 && peak < prevPeak) {
            FASTLED_WARN("CQ monotonicity violation at " << freq
                         << " Hz: peak bin " << peak
                         << " < previous peak " << prevPeak);
            violations++;
        }
        prevPeak = peak;
    }
    FL_CHECK_EQ(violations, 0);
}

// --- 4. White noise energy uniformity (catches LOG_REBIN high-bin bias) ---

FL_TEST_CASE("Binning adversarial - LOG_REBIN energy bias check") {
    // Test that LOG_REBIN doesn't have extreme energy bias across bins.
    // Feed one sine per bin center, record peak energy in its expected bin.
    const int bands = 16;
    const float fmin = fl::FFT_Args::DefaultMinFrequency();
    const float fmax = fl::FFT_Args::DefaultMaxFrequency();
    float logRatio = fl::logf(fmax / fmin);

    float peakEnergies[16] = {};
    int validBins = 0;

    for (int b = 0; b < bands; ++b) {
        // Use bin center in the LOG_REBIN edge grid (midpoint of edges b and b+1)
        float edgeB = fmin * fl::expf(logRatio * static_cast<float>(b) /
                                      static_cast<float>(bands));
        float edgeB1 = fmin * fl::expf(logRatio * static_cast<float>(b + 1) /
                                       static_cast<float>(bands));
        float freq = fl::sqrtf(edgeB * edgeB1); // geometric center

        auto samples = makeAdversarialSine(freq, 512, 44100.0f, 20000.0f);
        fl::FFTBins bins(bands);
        fl::FFT_Args args(512, bands, fmin, fmax, 44100, fl::FFTMode::LOG_REBIN);
        fl::FFTImpl fft(args);
        fft.run(samples, &bins);

        FL_REQUIRE_EQ(bins.raw().size(), static_cast<fl::size>(bands));
        int peak = findPeakBin(bins.raw());
        peakEnergies[b] = bins.raw()[peak];

        if (peakEnergies[b] > 0.0f) {
            validBins++;
        }
    }

    // All bins should produce measurable energy when their center freq plays
    FASTLED_WARN("LOG_REBIN valid bins with energy: " << validBins << "/" << bands);
    FL_CHECK_GE(validBins, bands - 2); // Allow up to 2 edge bins to be weak

    // Check energy ratio among valid bins
    float minE = 1e30f;
    float maxE = 0.0f;
    for (int i = 0; i < bands; ++i) {
        if (peakEnergies[i] > 0.0f) {
            if (peakEnergies[i] < minE) minE = peakEnergies[i];
            if (peakEnergies[i] > maxE) maxE = peakEnergies[i];
        }
    }

    if (minE > 0.0f) {
        float ratio = maxE / minE;
        FASTLED_WARN("LOG_REBIN peak energy ratio (max/min): " << ratio);
        // For a pure sine, peak bin energy should be similar across bins
        FL_CHECK_LT(ratio, 20.0f);
    }
}

// --- 5. Two-tone separation ---

FL_TEST_CASE("Binning adversarial - two-tone separation LOG_REBIN") {
    const int bands = 16;
    const float fmin = fl::FFT_Args::DefaultMinFrequency();
    const float fmax = fl::FFT_Args::DefaultMaxFrequency();

    float logRatio = fl::logf(fmax / fmin);
    float freq1 = fmin * fl::expf(logRatio * 3.0f / 15.0f);
    float freq2 = fmin * fl::expf(logRatio * 12.0f / 15.0f);

    auto samples = makeTwoTone(freq1, freq2);
    fl::FFTBins bins(bands);
    fl::FFT_Args args(512, bands, fmin, fmax, 44100, fl::FFTMode::LOG_REBIN);
    fl::FFTImpl fft(args);
    fft.run(samples, &bins);

    // Find two largest peaks
    int peak1 = -1, peak2 = -1;
    float val1 = 0.0f, val2 = 0.0f;
    for (int i = 0; i < bands; ++i) {
        if (bins.raw()[i] > val1) {
            val2 = val1;
            peak2 = peak1;
            val1 = bins.raw()[i];
            peak1 = i;
        } else if (bins.raw()[i] > val2) {
            val2 = bins.raw()[i];
            peak2 = i;
        }
    }

    int separation = peak1 - peak2;
    if (separation < 0) separation = -separation;
    FL_CHECK_GE(separation, 4);
    FL_CHECK_GT(val1, 0.0f);
    FL_CHECK_GT(val2, 0.0f);
}

// --- 6. Odd band counts ---

FL_TEST_CASE("Binning adversarial - odd band count 7 LOG_REBIN") {
    const int bands = 7;
    auto samples = makeAdversarialSine(1000.0f);
    fl::FFTBins bins(bands);
    fl::FFT_Args args(512, bands, fl::FFT_Args::DefaultMinFrequency(),
                      fl::FFT_Args::DefaultMaxFrequency(), 44100,
                      fl::FFTMode::LOG_REBIN);
    fl::FFTImpl fft(args);
    fft.run(samples, &bins);

    FL_CHECK_EQ(bins.raw().size(), static_cast<fl::size>(bands));
    float maxVal = 0.0f;
    float totalEnergy = 0.0f;
    for (int i = 0; i < bands; ++i) {
        FL_CHECK_FALSE(isNaNCheck(bins.raw()[i]));
        totalEnergy += bins.raw()[i];
        if (bins.raw()[i] > maxVal) maxVal = bins.raw()[i];
    }
    FL_CHECK_GT(maxVal, 0.0f);
    FL_CHECK_GT(maxVal / totalEnergy, 0.25f);
}

FL_TEST_CASE("Binning adversarial - odd band count 13 CQ_OCTAVE") {
    const int bands = 13;
    auto samples = makeAdversarialSine(1000.0f);
    fl::FFTBins bins(bands);
    fl::FFT_Args args(512, bands, fl::FFT_Args::DefaultMinFrequency(),
                      fl::FFT_Args::DefaultMaxFrequency(), 44100,
                      fl::FFTMode::CQ_OCTAVE);
    fl::FFTImpl fft(args);
    fft.run(samples, &bins);

    FL_CHECK_EQ(bins.raw().size(), static_cast<fl::size>(bands));
    float maxVal = 0.0f;
    float totalEnergy = 0.0f;
    for (int i = 0; i < bands; ++i) {
        FL_CHECK_FALSE(isNaNCheck(bins.raw()[i]));
        totalEnergy += bins.raw()[i];
        if (bins.raw()[i] > maxVal) maxVal = bins.raw()[i];
    }
    FL_CHECK_GT(maxVal, 0.0f);
    FL_CHECK_GT(maxVal / totalEnergy, 0.20f);
}

// --- 7. Bin boundary frequency assignment ---

FL_TEST_CASE("Binning adversarial - bin boundary frequency assignment") {
    const int bands = 16;
    const float fmin = fl::FFT_Args::DefaultMinFrequency();
    const float fmax = fl::FFT_Args::DefaultMaxFrequency();
    float logRatio = fl::logf(fmax / fmin);

    fl::FFT_Args args(512, bands, fmin, fmax, 44100, fl::FFTMode::LOG_REBIN);
    fl::FFTImpl fft(args);

    for (int b = 0; b < bands - 1; ++b) {
        float centerB = fmin * fl::expf(logRatio * static_cast<float>(b) /
                                        static_cast<float>(bands - 1));
        float centerB1 = fmin * fl::expf(logRatio * static_cast<float>(b + 1) /
                                         static_cast<float>(bands - 1));
        float boundary = fl::sqrtf(centerB * centerB1);

        auto samples = makeAdversarialSine(boundary);
        fl::FFTBins bins(bands);
        fft.run(samples, &bins);

        int peak = findPeakBin(bins.raw());
        bool inRange = (peak == b || peak == b + 1);
        if (!inRange) {
            FASTLED_WARN("Boundary freq " << boundary << " Hz between bins "
                         << b << " and " << (b + 1) << " peaked in bin "
                         << peak);
        }
        FL_CHECK(inRange);
    }
}

// --- 8. fmin/fmax edge tones ---

FL_TEST_CASE("Binning adversarial - sine at fmin lands in bin 0") {
    const int bands = 16;
    auto samples = makeAdversarialSine(fl::FFT_Args::DefaultMinFrequency());
    fl::FFTBins bins(bands);
    fl::FFT_Args args(512, bands, fl::FFT_Args::DefaultMinFrequency(),
                      fl::FFT_Args::DefaultMaxFrequency(), 44100,
                      fl::FFTMode::LOG_REBIN);
    fl::FFTImpl fft(args);
    fft.run(samples, &bins);
    int peak = findPeakBin(bins.raw());
    FL_CHECK_LE(peak, 1);
}

FL_TEST_CASE("Binning adversarial - sine at fmax lands in last bin") {
    const int bands = 16;
    auto samples = makeAdversarialSine(fl::FFT_Args::DefaultMaxFrequency());
    fl::FFTBins bins(bands);
    fl::FFT_Args args(512, bands, fl::FFT_Args::DefaultMinFrequency(),
                      fl::FFT_Args::DefaultMaxFrequency(), 44100,
                      fl::FFTMode::LOG_REBIN);
    fl::FFTImpl fft(args);
    fft.run(samples, &bins);
    int peak = findPeakBin(bins.raw());
    FL_CHECK_GE(peak, bands - 2);
}

FL_TEST_CASE("Binning adversarial - sine below fmin has minimal energy") {
    const int bands = 16;
    const float fmin = fl::FFT_Args::DefaultMinFrequency();
    const float fmax = fl::FFT_Args::DefaultMaxFrequency();

    fl::FFT_Args args(512, bands, fmin, fmax, 44100, fl::FFTMode::LOG_REBIN);
    fl::FFTImpl fft(args);

    auto belowSamples = makeAdversarialSine(50.0f);
    fl::FFTBins belowBins(bands);
    fft.run(belowSamples, &belowBins);

    float totalBelow = 0.0f;
    for (int i = 0; i < bands; ++i) {
        totalBelow += belowBins.raw()[i];
    }

    auto inRangeSamples = makeAdversarialSine(1000.0f);
    fl::FFTBins inRangeBins(bands);
    fft.run(inRangeSamples, &inRangeBins);

    float totalInRange = 0.0f;
    for (int i = 0; i < bands; ++i) {
        totalInRange += inRangeBins.raw()[i];
    }

    // 50 Hz is only ~3.5x below fmin (174.6 Hz), so some spectral leakage
    // is expected. With Hanning window the leakage should be < 20%.
    FL_CHECK_LT(totalBelow, totalInRange * 0.20f);
}

// --- 9. freqToBin consistency with actual LOG_REBIN peak ---

FL_TEST_CASE("Binning adversarial - freqToBin matches actual LOG_REBIN peak") {
    const int bands = 16;
    const float fmin = fl::FFT_Args::DefaultMinFrequency();
    const float fmax = fl::FFT_Args::DefaultMaxFrequency();

    float testFreqs[] = {200.0f, 400.0f, 800.0f, 1500.0f, 3000.0f, 4500.0f};
    int mismatches = 0;

    for (float freq : testFreqs) {
        auto samples = makeAdversarialSine(freq);
        fl::FFTBins bins(bands);
        fl::FFT_Args args(512, bands, fmin, fmax, 44100, fl::FFTMode::LOG_REBIN);
        fl::FFTImpl fft(args);
        fft.run(samples, &bins);

        int actualPeak = findPeakBin(bins.raw());
        int reportedBin = bins.freqToBin(freq);

        int diff = actualPeak - reportedBin;
        if (diff < 0) diff = -diff;

        if (diff > 1) {
            FASTLED_WARN("freqToBin(" << freq << ") = " << reportedBin
                         << " but LOG_REBIN peak at bin " << actualPeak
                         << " (off by " << diff << ")");
            mismatches++;
        }
        FL_CHECK_LE(diff, 1);
    }
    FL_CHECK_LE(mismatches, 1);
}

// --- 10. 64-bin CQ_OCTAVE peak accuracy ---

FL_TEST_CASE("Binning adversarial - 64 bins CQ_OCTAVE peak accuracy") {
    const int bands = 64;
    const float fmin = fl::FFT_Args::DefaultMinFrequency();
    const float fmax = fl::FFT_Args::DefaultMaxFrequency();

    float testFreqs[] = {200.0f, 500.0f, 1000.0f, 2000.0f, 4000.0f};

    for (float freq : testFreqs) {
        auto samples = makeAdversarialSine(freq);
        fl::FFTBins bins(bands);
        fl::FFT_Args args(512, bands, fmin, fmax, 44100, fl::FFTMode::CQ_OCTAVE);
        fl::FFTImpl fft(args);
        fft.run(samples, &bins);

        FL_CHECK_EQ(bins.raw().size(), static_cast<fl::size>(bands));

        int peak = findPeakBin(bins.raw());
        int expected = bins.freqToBin(freq);

        int diff = peak - expected;
        if (diff < 0) diff = -diff;

        if (diff > 2) {
            FASTLED_WARN("64-bin CQ: sine at " << freq << " Hz: expected bin "
                         << expected << " got bin " << peak);
        }
        FL_CHECK_LE(diff, 2);
    }
}

// --- 11. No NaN/Inf for edge signals ---

FL_TEST_CASE("Binning adversarial - no NaN in any output for edge signals") {
    const int bands = 16;
    const float fmin = fl::FFT_Args::DefaultMinFrequency();
    const float fmax = fl::FFT_Args::DefaultMaxFrequency();

    fl::vector<fl::i16> silence(512, 0);
    fl::vector<fl::i16> dc(512, 32767);
    fl::vector<fl::i16> impulse(512, 0);
    impulse[0] = 32767;
    fl::vector<fl::i16> nyquist(512);
    for (int i = 0; i < 512; ++i) {
        nyquist[i] = (i % 2 == 0) ? 32767 : -32768;
    }

    fl::vector<fl::i16>* signals[] = {&silence, &dc, &impulse, &nyquist};
    const char* names[] = {"silence", "DC", "impulse", "nyquist"};
    fl::FFTMode modes[] = {fl::FFTMode::LOG_REBIN, fl::FFTMode::CQ_OCTAVE};
    const char* modeNames[] = {"LOG_REBIN", "CQ_OCTAVE"};

    for (int m = 0; m < 2; ++m) {
        for (int s = 0; s < 4; ++s) {
            fl::FFTBins bins(bands);
            fl::FFT_Args args(512, bands, fmin, fmax, 44100, modes[m]);
            fl::FFTImpl fft(args);
            fft.run(*signals[s], &bins);

            for (int i = 0; i < bands; ++i) {
                if (isNaNCheck(bins.raw()[i])) {
                    FASTLED_WARN("NaN in " << modeNames[m] << " " << names[s]
                                 << " raw bin " << i);
                }
                FL_CHECK_FALSE(isNaNCheck(bins.raw()[i]));
                FL_CHECK_FALSE(isNaNCheck(bins.db()[i]));
            }
            for (int i = 0; i < static_cast<int>(bins.linear().size()); ++i) {
                FL_CHECK_FALSE(isNaNCheck(bins.linear()[i]));
            }
        }
    }
}

// --- 12. Narrow frequency range ---

FL_TEST_CASE("Binning adversarial - narrow frequency range 1000-2000 Hz") {
    const int bands = 8;

    auto samples = makeAdversarialSine(1414.0f);

    fl::FFTBins logBins(bands);
    fl::FFT_Args logArgs(512, bands, 1000.0f, 2000.0f, 44100, fl::FFTMode::LOG_REBIN);
    fl::FFTImpl logFft(logArgs);
    logFft.run(samples, &logBins);

    FL_CHECK_EQ(logBins.raw().size(), static_cast<fl::size>(bands));
    int logPeak = findPeakBin(logBins.raw());
    FL_CHECK_GE(logPeak, 1);
    FL_CHECK_LE(logPeak, bands - 2);
    for (int i = 0; i < bands; ++i) {
        FL_CHECK_FALSE(isNaNCheck(logBins.raw()[i]));
    }

    fl::FFTBins cqBins(bands);
    fl::FFT_Args cqArgs(512, bands, 1000.0f, 2000.0f, 44100, fl::FFTMode::CQ_OCTAVE);
    fl::FFTImpl cqFft(cqArgs);
    cqFft.run(samples, &cqBins);

    FL_CHECK_EQ(cqBins.raw().size(), static_cast<fl::size>(bands));
    int cqPeak = findPeakBin(cqBins.raw());
    FL_CHECK_GE(cqPeak, 1);
    FL_CHECK_LE(cqPeak, bands - 2);
    for (int i = 0; i < bands; ++i) {
        FL_CHECK_FALSE(isNaNCheck(cqBins.raw()[i]));
    }
}

// --- 13. Energy concentration ---

FL_TEST_CASE("Binning adversarial - LOG_REBIN energy concentration") {
    const int bands = 16;
    auto samples = makeAdversarialSine(1000.0f);
    fl::FFTBins bins(bands);
    fl::FFT_Args args(512, bands, fl::FFT_Args::DefaultMinFrequency(),
                      fl::FFT_Args::DefaultMaxFrequency(), 44100,
                      fl::FFTMode::LOG_REBIN);
    fl::FFTImpl fft(args);
    fft.run(samples, &bins);

    float totalEnergy = 0.0f;
    float maxBinEnergy = 0.0f;
    for (int i = 0; i < bands; ++i) {
        totalEnergy += bins.raw()[i];
        if (bins.raw()[i] > maxBinEnergy) maxBinEnergy = bins.raw()[i];
    }

    float concentration = maxBinEnergy / totalEnergy;
    if (concentration < 0.50f) {
        FASTLED_WARN("LOG_REBIN: 1kHz sine energy concentration = "
                     << (concentration * 100.0f) << "% (expected > 50%)");
    }
    FL_CHECK_GT(concentration, 0.50f);
}

// --- 14. binToFreq/freqToBin roundtrip ---

FL_TEST_CASE("Binning adversarial - binToFreq/freqToBin roundtrip LOG_REBIN") {
    const int bands = 16;
    auto samples = makeAdversarialSine(1000.0f);
    fl::FFTBins bins(bands);
    fl::FFT_Args args(512, bands, fl::FFT_Args::DefaultMinFrequency(),
                      fl::FFT_Args::DefaultMaxFrequency(), 44100,
                      fl::FFTMode::LOG_REBIN);
    fl::FFTImpl fft(args);
    fft.run(samples, &bins);

    for (int i = 0; i < bands; ++i) {
        float freq = bins.binToFreq(i);
        int recoveredBin = bins.freqToBin(freq);
        FL_CHECK_EQ(recoveredBin, i);
    }
}

} // FL_TEST_FILE
