"""The banned-build-tools lint keeps the PlatformIO tool out of the tree.

fbuild is the only board build backend. These tests pin the rule: the
words `platformio` (any case) and `pio` (whole word) fail the lint
everywhere except the project-file name fbuild reads, the env var fbuild
honours, and the allowlisted user-facing surfaces.
"""

from pathlib import Path

from ci.lint.banned_build_tools import (
    ALLOWED_PATHS,
    ALLOWED_PREFIXES,
    find_banned_words,
    run_banned_build_tools_lint,
    scan,
)


def _words(text: str) -> list[str]:
    return [w for _, w, _ in find_banned_words(text)]


def test_tool_name_is_banned_in_any_case() -> None:
    assert _words("pip install platformio") == ["platformio"]
    assert _words("Use PlatformIO for this") == ["PlatformIO"]
    assert _words("PLATFORMIO_BUILD_FLAGS") == ["PLATFORMIO"]
    assert _words("from ci.compiler.platformio_ini import X") == ["platformio"]


def test_project_file_name_is_allowed() -> None:
    assert _words("paths: - 'platformio.ini'") == []
    assert _words("hashFiles('platformio.ini', 'platformio.lock')") == []
    assert _words("[platformio.ini] ; section") == []


def test_fbuild_env_var_is_allowed() -> None:
    assert _words('env["PLATFORMIO_SRC_DIR"] = str(src)') == []


def test_allowed_token_does_not_excuse_a_second_hit_on_the_line() -> None:
    assert _words("platformio.ini is read by pio run") == ["pio"]
    assert _words("platformio.ini generated by PlatformIO") == ["PlatformIO"]


def test_pio_is_banned_only_as_a_whole_lowercase_word() -> None:
    assert _words("uv run pio pkg install") == ["pio"]
    assert _words(".build/pio/uno/firmware.elf") == ["pio"]
    assert _words("pio_sm_init(pio0, sm)") == []
    assert _words("GPIO and PIO peripherals") == []
    assert _words("radio scorpio") == []


def test_rp2040_peripheral_spellings_are_allowed() -> None:
    assert _words('#include "hardware/pio.h"') == []
    assert _words("bash autoresearch rp2350w --rp-pio-index 2") == []
    assert _words("--rp-pio-both selects PIO0 + PIO1") == []
    # but the tool next to them still fails
    assert _words("--rp-pio-index 2 then pio run") == ["pio"]


def test_one_hit_per_word_per_line() -> None:
    assert _words("platformio platformio pio pio") == ["platformio", "pio"]


def test_scan_reports_paths_and_lines(tmp_path: Path) -> None:
    (tmp_path / "ci").mkdir()
    (tmp_path / "ci" / "bad.py").write_text("x = 1\ncmd = ['pio', 'run']\n")
    (tmp_path / "ok.py").write_text("ini = 'platformio.ini'\n")

    violations = scan(tmp_path, files=["ci/bad.py", "ok.py"])

    assert [(v.path, v.line_no, v.word) for v in violations] == [
        ("ci/bad.py", 2, "pio")
    ]


def test_scan_skips_allowed_paths_and_binaries(tmp_path: Path) -> None:
    for rel in ("library.json", "src/platforms/arm/rp/pio_tx.h", "assets/x.png"):
        p = tmp_path / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text("platformio pio\n")
    (tmp_path / "blob.dat").write_bytes(b"pio\0platformio")
    files = [
        "library.json",
        "src/platforms/arm/rp/pio_tx.h",
        "assets/x.png",
        "blob.dat",
    ]

    assert scan(tmp_path, files=files) == []


def test_allowlist_is_small_and_explicit() -> None:
    # Growth here means the tool is creeping back in; every entry needs a reason.
    assert len(ALLOWED_PATHS) <= 14
    assert len(ALLOWED_PREFIXES) <= 6
    assert "src/platforms/arm/rp/" in ALLOWED_PREFIXES


def test_run_fails_on_violation(tmp_path: Path, capsys) -> None:  # type: ignore[no-untyped-def]
    (tmp_path / "notes.md").write_text("we still call pio here\n")

    assert run_banned_build_tools_lint(tmp_path) is False
    assert "notes.md:1: [pio]" in capsys.readouterr().out


def test_run_passes_on_clean_tree(tmp_path: Path) -> None:
    (tmp_path / "notes.md").write_text("fbuild builds everything\n")

    assert run_banned_build_tools_lint(tmp_path) is True
