FastLED: fl::HSV16::colorBoost
colorBoost()
CRGB fl::HSV16::colorBoost (EaseType saturation_function = EASE_IN_QUAD, EaseType luminance_function = EASE_NONE) const
Definition at line 181 of file hsv16.cpp.
{
    HSV16 hsv = *this;
    if (saturation_function != EASE_NONE) {
        u16 inv_sat = 65535 - hsv.s;
        inv_sat = ease16(saturation_function, inv_sat);
        hsv.s = (65535 - inv_sat);
    }
    if (luminance_function != EASE_NONE) {
        hsv.v = ease16(luminance_function, hsv.v);
    }
    return hsv.ToRGB();
}
References HSV16(), fl::ease16(), fl::EASE_NONE, s, ToRGB(), and v.
Referenced by CRGB::colorBoost().