FastLED: fl::video::PixelStream::bytesRemaining
bytesRemaining()
i32 fl::video::PixelStream::bytesRemaining () const
Definition at line 186 of file pixel_stream.cpp.hpp.
{
    if (mType == kStreaming) {
        // Use (max)() to prevent macro expansion by Arduino.h's max macro
        return (fl::numeric_limits<i32>::max)();
    }
    return mHandle->bytesLeft();
}
References kStreaming, fl::numeric_limits< T >::max(), mHandle, and mType.
Referenced by bytesRemainingInFrame(), and framesRemaining().