FastLED: fl::HttpRequestParser::parseBody
parseBody()
void fl::HttpRequestParser::parseBody () private
Definition at line 220 of file http_parser.cpp.hpp.
{
    if (mIsChunked) {
        // Feed buffer to chunked reader
        if (!mBuffer.empty()) {
            mChunkedReader->feed(mBuffer);
            mBuffer.clear();
        }
        // Read all available chunks
        while (mChunkedReader->hasChunk()) {
            size_t chunkSz = mChunkedReader->nextChunkSize();
            size_t offset = req().body.size();
            req().body.resize(offset + chunkSz);
            auto result = mChunkedReader->readChunk(
                fl::span<u8>(req().body.data() + offset, chunkSz));
            (void)result;
        }
        // Check if final chunk received
        if (mChunkedReader->isFinal()) {
            mState = COMPLETE;
        }
    } else {
        // Read Content-Length bytes
        if (mBuffer.size() >= mContentLength) {
            req().body.insert(req().body.end(),
                              mBuffer.begin(),
                              mBuffer.begin() + mContentLength);
            consume(mContentLength);
            mState = COMPLETE;
        }
    }
}
References fl::HttpRequest::body, COMPLETE, consume(), fl::vector< T >::insert(), mBuffer, mChunkedReader, mContentLength, mIsChunked, mState, offset(), req(), fl::vector< T >::resize(), and fl::vector_basic::size().
Referenced by feed().