FastLED: fl::HttpRequestParser::parseRequestLine
parseRequestLine()
bool fl::HttpRequestParser::parseRequestLine () private
Definition at line 161 of file http_parser.cpp.hpp.
{
    auto crlfPos = findCRLF();
    if (!crlfPos.has_value()) {
        return false;  // Need more data
    }
    // Extract request line
    fl::string line(reinterpret_cast<const char*>(mBuffer.data()), crlfPos.value()); // ok reinterpret cast
    consume(crlfPos.value() + 2);  // +2 for CRLF
    // Parse: "METHOD URI VERSION"
    size_t methodEnd = line.find(' ');
    if (methodEnd == fl::string::npos) {
        return false;  // Invalid format
    }
    size_t uriEnd = line.find(' ', methodEnd + 1);
    if (uriEnd == fl::string::npos) {
        return false;  // Invalid format
    }
    req().method = line.substr(0, methodEnd);
    req().uri = line.substr(methodEnd + 1, uriEnd - methodEnd - 1);
    req().version = line.substr(uriEnd + 1);
    return true;
}
References consume(), fl::basic_string::find(), findCRLF(), mBuffer, fl::HttpRequest::method, fl::string::npos, req(), fl::string::substr(), fl::HttpRequest::uri, and fl::HttpRequest::version.
Referenced by feed().