FastLED: fl::NoiseBias1D::trigger
trigger()
void fl::NoiseBias1D::trigger (float center, float width, float amplitude, BumpShape shape = BumpShape::HalfSine) inline
Inject a shaped bump. Multiple triggers per frame accumulate additively.
Definition at line 52 of file flowfield.h.
{
        if (width <= 0.0f || amplitude == 0.0f || mSize == 0) {
            return;
        }
        const float halfWidth = width * 0.5f;
        int iStart = fl::max(0, static_cast<int>(fl::floorf(center - halfWidth)));
        int iEnd = fl::min(static_cast<int>(mSize) - 1,
                           static_cast<int>(fl::ceilf(center + halfWidth)));
        for (int i = iStart; i <= iEnd; ++i) {
            float t = (static_cast<float>(i) - (center - halfWidth)) / width;
            t = fl::clamp(t, 0.0f, 1.0f);
            float shaped = 0.0f;
            switch (shape) {
            case BumpShape::HalfSine:
                shaped = fl::sinf(static_cast<float>(FL_PI) * t);
                break;
            case BumpShape::Gaussian: {
                float u = (t - 0.5f) / 0.2f;
                shaped = fl::expf(-0.5f * u * u);
                break;
            }
            }
            mPending[i] += amplitude * shaped;
        }
    }
References fl::ceilf(), fl::clamp(), fl::expf(), FL_PI, fl::floorf(), fl::Gaussian, fl::HalfSine, fl::max(), fl::min(), mPending, mSize, fl::sinf(), fl::t, and fl::width.