FastLED: LPD6803Controller::showPixels
showPixels()
template<uint8_t DATA_PIN, uint8_t CLOCK_PIN, EOrder RGB_ORDER = RGB, uint32_t SPI_SPEED = DATA_RATE_MHZ(12)> virtual void LPD6803Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED >::showPixels (PixelController< RGB_ORDER > & pixels) inline protected virtual
Send the LED data to the strip.
Parameters
pixels the PixelController object for the LED data
Definition at line 326 of file chipsets.h.
{
        mSPI.select();
        startBoundary();
        while(pixels.has(1)) {
            FASTLED_REGISTER uint16_t command;
            command = 0x8000;
            command |= (pixels.loadAndScale0() & 0xF8) << 7; // red is the high 5 bits
            command |= (pixels.loadAndScale1() & 0xF8) << 2; // green is the middle 5 bits
            mSPI.writeByte((command >> 8) & 0xFF);
            command |= pixels.loadAndScale2() >> 3 ; // blue is the low 5 bits
            mSPI.writeByte(command & 0xFF);
            pixels.stepDithering();
            pixels.advanceData();
        }
        endBoundary(pixels.size());
        mSPI.waitFully();
        mSPI.release();
    }
References PixelController< RGB_ORDER, LANES, MASK >::advanceData(), endBoundary(), FASTLED_REGISTER, PixelController< RGB_ORDER, LANES, MASK >::has(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale0(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale1(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale2(), mSPI, PixelController< RGB_ORDER, LANES, MASK >::size(), startBoundary(), and PixelController< RGB_ORDER, LANES, MASK >::stepDithering().