FastLED: fl::InlinedMemoryBlock::InlinedMemoryBlock
InlinedMemoryBlock() [1/3]
template<typename T, size_t N> fl::InlinedMemoryBlock< T, N >::InlinedMemoryBlock () inline
Definition at line 29 of file vector.h.
{
        memset(mMemoryBlock, 0, sizeof(mMemoryBlock));
#ifdef FASTLED_TESTING
        __data = memory();
#endif
    }
References memory(), and mMemoryBlock.
Referenced by InlinedMemoryBlock(), and InlinedMemoryBlock().