FastLED: fl::StringHolder::StringHolder
StringHolder() [1/4]
fl::StringHolder::StringHolder (const char * str)
Definition at line 16 of file string_holder.cpp.hpp.
    : mData((char*)fl::malloc(strlen(str) + 1))
    , mLength(strlen(str))
    , mCapacity(mLength + 1) {
    fl::memcpy(mData, str, mLength);
    mData[mLength] = '\0';
}
References fl::malloc(), mCapacity, mData, fl::memcpy(), mLength, and fl::strlen().
Referenced by StringHolder(), and operator=().