FastLED: kiss_fftr_alloc
kiss_fftr_alloc()
kiss_fftr_cfg kiss_fftr_alloc (int nfft, int inverse_fft, void * mem, size_t * lenmem)
Definition at line 35 of file kiss_fftr.cpp.hpp.
{
    int i;
    kiss_fftr_cfg st = NULL;
    size_t subsize = 0, memneeded;
    if (nfft & 1) {
        //fprintf(stderr,"Real FFT optimization must be even.\n");
        FL_WARN("Real FFT optimization must be even.");
        return NULL;
    }
    nfft >>= 1;
    kiss_fft_alloc (nfft, inverse_fft, NULL, &subsize);
    memneeded = sizeof(struct kiss_fftr_state) + subsize + sizeof(kiss_fft_cpx) * ( nfft * 3 / 2);
    if (lenmem == NULL) {
        st = (kiss_fftr_cfg) KISS_FFT_MALLOC (memneeded);
    } else {
        if (*lenmem >= memneeded)
            st = (kiss_fftr_cfg) mem;
        *lenmem = memneeded;
    }
    if (!st)
        return NULL;
    st->substate = (kiss_fft_cfg) (st + 1); /*just beyond kiss_fftr_state struct */
    #pragma GCC diagnostic push
    #pragma GCC diagnostic ignored "-Wcast-align"
    // This cast alginment might be a problem, kiss_fft_cpx has alignment-2.
    st->tmpbuf = (kiss_fft_cpx *) (((char *) st->substate) + subsize);
    #pragma GCC diagnostic pop
    st->super_twiddles = st->tmpbuf + nfft;
    kiss_fft_alloc(nfft, inverse_fft, st->substate, &subsize);
    for (i = 0; i < nfft/2; ++i) {
        double phase =
            -3.14159265358979323846264338327 * ((double) (i+1) / nfft + .5);
        if (inverse_fft)
            phase *= -1;
        kf_cexp (st->super_twiddles+i,phase);
    }
    return st;
}
References FL_NOEXCEPT, FL_WARN, kf_cexp, kiss_fft_alloc(), KISS_FFT_MALLOC, NULL, kiss_fftr_state::substate, kiss_fftr_state::super_twiddles, and kiss_fftr_state::tmpbuf.
Referenced by fl::audio::fft::Context::Context(), generate_kernels(), and fl::audio::fft::Context::initHybrid().