FastLED: loop
loop()
void loop ()
Definition at line 68 of file Codec.ino.
            {
    // Check for button clicks
    if (jpegButton.clicked()) {
        CodecProcessor::processCodecWithTiming("JPEG", []() { CodecProcessor::processJpeg(); });
    }
    if (gifButton.clicked()) {
        CodecProcessor::processCodecWithTiming("GIF", []() { CodecProcessor::processGif(); });
    }
    if (mpeg1Button.clicked()) {
        CodecProcessor::processCodecWithTiming("MPEG1", []() { CodecProcessor::processMpeg1(); });
    }
}
References gifButton, jpegButton, mpeg1Button, CodecProcessor::processCodecWithTiming(), CodecProcessor::processGif(), CodecProcessor::processJpeg(), and CodecProcessor::processMpeg1().