FastLED: fl::audio::Processor::onDropImpact
onDropImpact()
void fl::audio::Processor::onDropImpact (function< void(float impact)> callback)
References FL_NOEXCEPT, getBackbeatConfidence(), getBackbeatStrength(), getBassLevel(), getBassRaw(), getBeatConfidence(), getBPM(), getBuildupIntensity(), getBuildupProgress(), getChordConfidence(), getCurrentBeatNumber(), getCurrentNote(), getDownbeatConfidence(), getDropImpact(), getDynamicTrend(), getEnergy(), getEqAutoGain(), getEqBass(), getEqBin(), getEqDominantFreqHz(), getEqDominantMagnitude(), getEqIsSilence(), getEqMid(), getEqTreble(), getEqVolume(), getEqVolumeDb(), getEqVolumeNormFactor(), getEqZcf(), getGain(), getKeyConfidence(), getMeasurePhase(), getMidLevel(), getMidRaw(), getMoodArousal(), getMoodValence(), getNoteConfidence(), getNoteVelocity(), getPeakLevel(), getPitch(), getPitchConfidence(), getSampleRate(), getSilenceDuration(), getTempoBPM(), getTempoConfidence(), getTransientStrength(), getTrebleLevel(), getTrebleRaw(), getVibeBass(), getVibeBassAtt(), getVibeMid(), getVibeMidAtt(), getVibeTreb(), getVibeTrebAtt(), getVibeVol(), getVibeVolAtt(), getVocalConfidence(), isCrescendo(), isDiminuendo(), isHiHat(), isKick(), isSilent(), isSnare(), isTom(), isVibeBassSpike(), isVibeMidSpike(), isVibeTrebSpike(), onDropImpact(), onVibeBassSpike(), onVibeLevels(), onVibeMidSpike(), onVibeTrebSpike(), setGain(), setMicProfile(), setNoiseFloorTrackingEnabled(), setSampleRate(), and setSignalConditioningEnabled().
Referenced by onDropImpact().