FastLED: fl::FlowFieldFloat::Perlin2D::noise
noise()
float fl::FlowFieldFloat::Perlin2D::noise (float x, float y) const
Definition at line 78 of file flowfield.cpp.hpp.
{
    int xi = ((int)floorf(x)) & 255;
    int yi = ((int)floorf(y)) & 255;
    float xf = x - floorf(x);
    float yf = y - floorf(y);
    float u = fade(xf);
    float v = fade(yf);
    int aa = perm[perm[xi] + yi];
    int ab = perm[perm[xi] + yi + 1];
    int ba = perm[perm[xi + 1] + yi];
    int bb = perm[perm[xi + 1] + yi + 1];
    float x1 = lerp(grad(aa, xf, yf), grad(ba, xf - 1.0f, yf), u);
    float x2 = lerp(grad(ab, xf, yf - 1.0f),
                     grad(bb, xf - 1.0f, yf - 1.0f), u);
    return lerp(x1, x2, v);
}
References fl::fade(), fl::floorf(), fl::grad(), fl::lerp(), perm, fl::x, and fl::y.