FastLED: fl::audio::Processor::update
update()
void fl::audio::Processor::update (const Sample & sample)
Definition at line 39 of file audio_processor.cpp.hpp.
{
    // Signal conditioning pipeline: raw sample → conditioned sample
    Sample conditioned = sample;
    // Stage 1: Signal conditioning (DC removal, spike filtering, noise gate)
    if (mSignalConditioningEnabled && conditioned.isValid()) {
        conditioned = mSignalConditioner.processSample(conditioned);
        if (!conditioned.isValid()) {
            return;  // Signal was entirely filtered out
        }
    }
    // Stage 2: Digital gain (simple multiplier)
    if (mGain != 1.0f && conditioned.isValid()) {
        conditioned.applyGain(mGain);
    }
    // Stage 3: Noise floor tracking (passive — updates estimate but doesn't modify signal)
    if (mNoiseFloorTrackingEnabled && conditioned.isValid()) {
        mNoiseFloorTracker.update(conditioned.rms());
    }
    mContext->setSample(conditioned);
    // Stage 4: Silence flag — detectors use this to gate outputs when audio stops.
    // Only populated when NFT is enabled; otherwise silence is unknowable and
    // stays at its default (false) after setSample() above.
    //
    // Uses an absolute RMS threshold rather than NFT.isAboveFloor(): the
    // adaptive floor's first-sample init matches the current level, so
    // isAboveFloor() stays false for any steady signal. Absolute RMS is the
    // right silence primitive — a loud constant tone has large RMS.
    if (mNoiseFloorTrackingEnabled && conditioned.isValid()) {
        constexpr float kSilenceRmsThreshold = 10.0f;
        mContext->setSilent(conditioned.rms() < kSilenceRmsThreshold);
    }
    // Phase 1: Compute state for all active detector
    for (auto& d : mActiveDetectors) {
        d->update(mContext);
    }
    // Phase 2: Fire callbacks for all active detector
    for (auto& d : mActiveDetectors) {
        d->fireCallbacks();
    }
}
References Processor(), fl::audio::Sample::isValid(), mSignalConditioningEnabled, fl::sample(), and update().
Referenced by ~Processor(), and update().