FastLED: fl::audio::Processor::createWithAutoInput
createWithAutoInput()
shared_ptr< Processor > fl::audio::Processor::createWithAutoInput (fl::shared_ptr< IInput > input) static private
Definition at line 980 of file audio_processor.cpp.hpp.
{
    auto processor = make_shared<Processor>();
    processor->mAudioInput = input;
    // weak_ptr so the lambda doesn't prevent Processor destruction
    weak_ptr<Processor> weak = processor;
    weak_ptr<IInput> weakInput = input;
    processor->mAutoTask = fl::task::every_ms(1).then([weak, weakInput]() {
        auto proc = weak.lock();
        auto inp = weakInput.lock();
        if (!proc || !inp) {
            return;
        }
        vector_inlined<Sample, 16> samples;
        inp->readAll(&samples);
        for (const auto& sample : samples) {
            proc->update(sample);
        }
    });
    return processor;
}
References createWithAutoInput(), fl::task::every_ms(), fl::weak_ptr< T >::lock(), fl::make_shared(), fl::sample(), and fl::task::Handle::then().
Referenced by fl::audio::AudioManager::add(), fl::audio::AudioManager::add(), and createWithAutoInput().