FastLED: fl::ScreenMap::ParseJson
ParseJson() [2/2]
bool fl::ScreenMap::ParseJson (const char * jsonStrScreenMap, fl::fl_map< string, ScreenMap > * segmentMaps, string * err = nullptr) static
Definition at line 82 of file screenmap.cpp.
{
#if FASTLED_NO_JSON
    FL_UNUSED(jsonStrScreenMap);
    FL_UNUSED(segmentMaps);
    FL_UNUSED(err);
    FL_WARN("ScreenMap::ParseJson called with FASTLED_NO_JSON");
    if (err) {
        *err = "JSON is not supported in this build";
    }
    return false;
#else
    //FL_WARN_SCREENMAP("ParseJson called with JSON: " << jsonStrScreenMap);
    string _err;
    if (!err) {
        err = &_err;
    }
    auto jsonDoc = fl::Json::parse(jsonStrScreenMap);
    if (!jsonDoc.has_value()) {
        *err = "Failed to parse JSON";
        FL_WARN("Failed to parse JSON");
        return false;
    }
    if (!jsonDoc.is_object()) {
        *err = "JSON root is not an object";
        FL_WARN("JSON root is not an object");
        return false;
    }
    // Check if "map" key exists and is an object
    if (!jsonDoc.contains("map")) {
        *err = "Missing 'map' key in JSON";
        FL_WARN("Missing 'map' key in JSON");
        return false;
    }
    // Get the map object
    auto mapObj = jsonDoc["map"];
    if (!mapObj.has_value() || !mapObj.is_object()) {
        *err = "Invalid 'map' object in JSON";
        FL_WARN("Invalid 'map' object in JSON");
        return false;
    }
    auto jsonMapOpt = mapObj.as_object();
    if (!jsonMapOpt || jsonMapOpt->empty()) {
        *err = "Failed to parse map from JSON or map is empty";
        FL_WARN("Failed to parse map from JSON or map is empty");
        return false;
    }
    auto& jsonMap = *jsonMapOpt;
    for (const auto& kv : jsonMap) {
        auto name = kv.first;
        // Check that the value is not null before creating Json object
        if (!kv.second) {
            *err = "Null value for segment " + name;
            return false;
        }
        // Create Json object directly from shared_ptr
        fl::Json val(kv.second);
        if (!val.has_value()) {
            *err = "Invalid value for segment " + name;
            return false;
        }
        if (!val.is_object()) {
            *err = "Segment value for " + name + " is not an object";
            return false;
        }
        // Check if x array exists and is actually an array
        if (!val.contains("x")) {
            *err = "Missing x array for " + name;
            return false;
        }
        if (!val["x"].has_value() || !val["x"].is_array()) {
            *err = "Invalid x array for " + name;
            return false;
        }
        // Extract x array using our helper function
        fl::vector<float> x_array = jsonArrayToFloatVector(val["x"]);
        // Check if y array exists and is actually an array
        if (!val.contains("y")) {
            *err = "Missing y array for " + name;
            return false;
        }
        if (!val["y"].has_value() || !val["y"].is_array()) {
            *err = "Invalid y array for " + name;
            return false;
        }
        // Extract y array using our helper function
        fl::vector<float> y_array = jsonArrayToFloatVector(val["y"]);
        // Get diameter (optional) with default value
        float diameter = -1.0f; // default value
        if (val.contains("diameter") && val["diameter"].has_value()) {
                            auto diameterOpt = val["diameter"].as_float();
            if (diameterOpt) {
                diameter = static_cast<float>(*diameterOpt);
            }
        }
        auto n = MIN(x_array.size(), y_array.size());
        if (n != x_array.size() || n != y_array.size()) {
            if (n != x_array.size()) {
            }
            if (n != y_array.size()) {
            }
        }
        ScreenMap segment_map(n, diameter);
        for (size_t i = 0; i < n; i++) {
            segment_map.set(i, vec2f{x_array[i], y_array[i]});
        }
        (*segmentMaps)[name] = fl::move(segment_map);
    }
    return true;
#endif
}
References ScreenMap(), fl::Json::as_float(), fl::Json::contains(), FL_UNUSED, FL_WARN, fl::Json::has_value(), fl::Json::is_object(), fl::jsonArrayToFloatVector(), MIN, fl::move(), fl::Json::parse(), set(), and fl::HeapVector< T, Allocator >::size().
Referenced by ParseJson(), fl::FileSystem::readScreenMap(), and fl::FileSystem::readScreenMaps().