FastLED: fl::ScreenMap::DefaultStrip
DefaultStrip()
static ScreenMap fl::ScreenMap::DefaultStrip (int numLeds, float cm_between_leds = 1.5f, float cm_led_diameter = 0.2f, float completion = .9f) inline static
Definition at line 33 of file screenmap.h.
{
        return Circle(numLeds, cm_between_leds, cm_led_diameter, completion);
    }
References ScreenMap(), and Circle().
Referenced by setup().