FastLED: fl::ScreenMap::toJson
toJson()
void fl::ScreenMap::toJson (const fl::fl_map< string, ScreenMap > & segmentMaps, fl::Json * doc) static
Definition at line 242 of file screenmap.cpp.
{
#if FASTLED_NO_JSON
    FL_WARN("ScreenMap::toJson called with FASTLED_NO_JSON");
    return;
#else
    if (!doc) {
        FL_WARN("ScreenMap::toJson called with nullptr doc");
        return;
    }
    // Create the root object
    *doc = fl::Json::object();
    // Create the map object
    fl::Json mapObj = fl::Json::object();
    // Populate the map object with segments
    for (const auto& kv : segmentMaps) {
        if (kv.second.getLength() == 0) {
            FL_WARN("ScreenMap::toJson called with empty segment: " << fl::string(kv.first));
            continue;
        }
        auto& name = kv.first;
        auto& segment = kv.second;
        float diameter = segment.getDiameter();
        // Create x array
        fl::Json xArray = fl::Json::array();
        for (u16 i = 0; i < segment.getLength(); i++) {
            xArray.push_back(fl::Json(static_cast<double>(segment[i].x)));
        }
        // Create y array
        fl::Json yArray = fl::Json::array();
        for (u16 i = 0; i < segment.getLength(); i++) {
            yArray.push_back(fl::Json(static_cast<double>(segment[i].y)));
        }
        // Create segment object
        fl::Json segmentObj = fl::Json::object();
        // Add arrays and diameter to segment object
        segmentObj.set("x", xArray);
        segmentObj.set("y", yArray);
        segmentObj.set("diameter", fl::Json(static_cast<double>(diameter)));
        // Add segment to map object
        mapObj.set(name, segmentObj);
    }
    // Add map object to root
    doc->set("map", mapObj);
    // Debug output
    fl::string debugStr = doc->to_string();
    FL_WARN("ScreenMap::toJson generated JSON: " << debugStr);
#endif
}
References fl::Json::array(), FL_WARN, fl::Json::object(), fl::Json::push_back(), fl::Json::set(), fl::Json::to_string(), x, and y.
Referenced by toJsonStr().