FastLED: fl::ScreenMap::ParseJson
ParseJson() [2/2]
bool fl::ScreenMap::ParseJson (const char * jsonStrScreenMap, fl::flat_map< string, ScreenMap > * segmentMaps, string * err = nullptr) static
Examples
Chromancer.ino.
Definition at line 186 of file screenmap.cpp.hpp.
{
#if FASTLED_NO_JSON
    FL_UNUSED(jsonStrScreenMap);
    FL_UNUSED(segmentMaps);
    FL_UNUSED(err);
    FL_WARN("ScreenMap::ParseJson called with FASTLED_NO_JSON");
    if (err) {
        *err = "JSON is not supported in this build";
    }
    return false;
#else
    //FL_WARN_SCREENMAP("ParseJson called with JSON: " << jsonStrScreenMap);
    string _err;
    if (!err) {
        err = &_err;
    }
    auto jsonDoc = fl::json::parse(jsonStrScreenMap);
    if (!jsonDoc.has_value()) {
        *err = "Failed to parse JSON";
        FL_WARN("Failed to parse JSON");
        return false;
    }
    if (!jsonDoc.is_object()) {
        *err = "JSON root is not an object";
        FL_WARN("JSON root is not an object");
        return false;
    }
    // ── v2 dispatch ──────────────────────────────────────────────────────
    // v2 if: explicit "version": 2  OR  has top-level "segments" array.
    // v1 if: explicit "version": 1  OR  has top-level "map" object.
    bool explicitV2 = false;
    bool explicitV1 = false;
    if (jsonDoc.contains("version") && jsonDoc["version"].has_value()) {
        auto versionOpt = jsonDoc["version"].as_int();
        if (versionOpt) {
            int v = static_cast<int>(*versionOpt);
            if (v == 2) explicitV2 = true;
            else if (v == 1) explicitV1 = true;
        }
    }
    bool hasSegments = jsonDoc.contains("segments") && jsonDoc["segments"].has_value()
                       && jsonDoc["segments"].is_array();
    bool hasMap = jsonDoc.contains("map") && jsonDoc["map"].has_value()
                  && jsonDoc["map"].is_object();
    if (explicitV2 || (!explicitV1 && hasSegments && !hasMap)) {
        return parseV2SegmentArray(jsonDoc["segments"], segmentMaps, err);
    }
    // Fall through to v1 path.
    // Check if "map" key exists and is an object
    if (!jsonDoc.contains("map")) {
        *err = "Missing 'map' key in JSON";
        FL_WARN("Missing 'map' key in JSON");
        return false;
    }
    // Get the map object
    auto mapObj = jsonDoc["map"];
    if (!mapObj.has_value() || !mapObj.is_object()) {
        *err = "Invalid 'map' object in JSON";
        FL_WARN("Invalid 'map' object in JSON");
        return false;
    }
    auto jsonMapPtr = mapObj.as_object();
    if (!jsonMapPtr || jsonMapPtr->empty()) {
        *err = "Failed to parse map from JSON or map is empty";
        FL_WARN("Failed to parse map from JSON or map is empty");
        return false;
    }
    auto& jsonMap = *jsonMapPtr;
    for (const auto& kv : jsonMap) {
        auto name = kv.first;
        // Check that the value is not null before creating json object
        if (!kv.second) {
            *err = "Null value for segment " + name;
            return false;
        }
        // Create json object directly from shared_ptr
        fl::json val(kv.second);
        if (!val.has_value()) {
            *err = "Invalid value for segment " + name;
            return false;
        }
        if (!val.is_object()) {
            *err = "Segment value for " + name + " is not an object";
            return false;
        }
        // Check if x array exists and is actually an array
        if (!val.contains("x")) {
            *err = "Missing x array for " + name;
            return false;
        }
        if (!val["x"].has_value() || !val["x"].is_array()) {
            *err = "Invalid x array for " + name;
            return false;
        }
        // Extract x array using our helper function
        fl::vector<float> x_array = jsonArrayToFloatVector(val["x"]);
        // Check if y array exists and is actually an array
        if (!val.contains("y")) {
            *err = "Missing y array for " + name;
            return false;
        }
        if (!val["y"].has_value() || !val["y"].is_array()) {
            *err = "Invalid y array for " + name;
            return false;
        }
        // Extract y array using our helper function
        fl::vector<float> y_array = jsonArrayToFloatVector(val["y"]);
        // Get diameter (optional) with default value
        float diameter = -1.0f; // default value
        if (val.contains("diameter") && val["diameter"].has_value()) {
                            auto diameterOpt = val["diameter"].as_float();
            if (diameterOpt) {
                diameter = static_cast<float>(*diameterOpt);
            }
        }
        auto n = fl::min(x_array.size(), y_array.size());
        if (n != x_array.size() || n != y_array.size()) {
            if (n != x_array.size()) {
            }
            if (n != y_array.size()) {
            }
        }
        ScreenMap segment_map(n, diameter);
        for (size_t i = 0; i < n; i++) {
            segment_map.set(i, vec2f{x_array[i], y_array[i]});
        }
        (*segmentMaps)[name] = fl::move(segment_map);
    }
    return true;
#endif
}
References ScreenMap(), fl::json::as_float(), fl::json::contains(), FL_UNUSED, FL_WARN, fl::json::has_value(), fl::json::is_object(), fl::jsonArrayToFloatVector(), fl::min(), fl::fl::move(), fl::json::parse(), fl::parseV2SegmentArray(), set(), and fl::vector_basic::size().
Referenced by openVideoEitherFormat(), ParseJson(), fl::FileSystem::readScreenMap(), fl::FileSystem::readScreenMaps(), and setup().