FastLED: fl::ScreenMap::toJson
toJson()
void fl::ScreenMap::toJson (const fl::flat_map< string, ScreenMap > & segmentMaps, fl::json * doc) static
Definition at line 369 of file screenmap.cpp.hpp.
{
#if FASTLED_NO_JSON
    FL_WARN("ScreenMap::toJson called with FASTLED_NO_JSON");
    return;
#else
    if (!doc) {
        FL_WARN("ScreenMap::toJson called with nullptr doc");
        return;
    }
    // Emits the v2 screenmap shape (issue ledmapper#143):
    //   { "version": 2,
    //     "groups": { "<name>": { "color": "#hex" } },
    //     "segments": [ { "id": "<name>", "pin": "pin1", "group": "<name>",
    //                     "x": [...], "y": [...], "diameter": ... } ] }
    // Bilingual readers (`ScreenMap::ParseJson`, ledmapper) accept both v1
    // and v2, so any existing on-disk v1 JSON keeps loading. v1 emission
    // is no longer supported.
    *doc = fl::json::object();
    fl::json groupsObj = fl::json::object();
    fl::json segmentsArr = fl::json::array();
    // Distinct palette so each strip lights up differently in the editor
    // preview without the user having to pick a colour. Cycle on overflow.
    static const char *const kPalette[] = {
        "#3b82f6", "#10b981", "#f59e0b", "#ef4444",
        "#a855f7", "#06b6d4", "#ec4899", "#84cc16",
    };
    constexpr size_t kPaletteSize = sizeof(kPalette) / sizeof(kPalette[0]);
    size_t idx = 0;
    for (const auto& kv : segmentMaps) {
        if (kv.second.getLength() == 0) {
            FL_WARN("ScreenMap::toJson called with empty segment: " << fl::string(kv.first));
            continue;
        }
        const auto& name = kv.first;
        const auto& segment = kv.second;
        const float diameter = segment.getDiameter();
        fl::json xArray = fl::json::array();
        for (u16 i = 0; i < segment.getLength(); i++) {
            xArray.push_back(fl::json(static_cast<double>(segment[i].x)));
        }
        fl::json yArray = fl::json::array();
        for (u16 i = 0; i < segment.getLength(); i++) {
            yArray.push_back(fl::json(static_cast<double>(segment[i].y)));
        }
        fl::json groupObj = fl::json::object();
        groupObj.set("color", fl::json(fl::string(kPalette[idx % kPaletteSize])));
        groupsObj.set(name, groupObj);
        fl::json segmentObj = fl::json::object();
        segmentObj.set("id", fl::json(fl::string(name)));
        segmentObj.set("pin", fl::json(fl::string("pin1")));
        segmentObj.set("group", fl::json(fl::string(name)));
        segmentObj.set("x", xArray);
        segmentObj.set("y", yArray);
        segmentObj.set("diameter", fl::json(static_cast<double>(diameter)));
        segmentsArr.push_back(segmentObj);
        idx++;
    }
    doc->set("version", fl::json(static_cast<double>(2)));
    doc->set("groups", groupsObj);
    doc->set("segments", segmentsArr);
    fl::string debugStr = doc->to_string();
    FL_WARN("ScreenMap::toJson generated JSON: " << debugStr);
#endif
}
References fl::json::array(), FL_WARN, fl::json::object(), fl::json::push_back(), fl::json::set(), fl::json::to_string(), fl::x, and fl::y.
Referenced by toJsonStr().