FastLED: fl::ScreenMap::Circle
Circle()
ScreenMap fl::ScreenMap::Circle (int numLeds, float cm_between_leds = 1.5f, float cm_led_diameter = 0.5f, float completion = 1.0f) static
Definition at line 21 of file screenmap.cpp.
{
    ScreenMap screenMap(numLeds);
    // radius from LED spacing
    float circumference = numLeds * cm_between_leds;
    float radius = circumference / (2 * PI);
    // how big an arc we light vs leave dark
    float totalAngle = completion * 2 * PI;
    float gapAngle = 2 * PI - totalAngle;
    // shift so the dark gap is centered at the bottom (й/2)
    float startAngle = -PI / 2 + gapAngle / 2.0f;
    // if partial, land last LED exactly at startAngle+totalAngle
    float divisor =
        (completion < 1.0f && numLeds > 1) ? (numLeds - 1) : numLeds;
    for (int i = 0; i < numLeds; ++i) {
        float angle = startAngle + (i * totalAngle) / divisor;
        float x = radius * cos(angle) * 2;
        float y = radius * sin(angle) * 2;
        screenMap[i] = {x, y};
    }
    screenMap.setDiameter(cm_led_diameter);
    return screenMap;
}
References ScreenMap(), PI, screenMap, x, and y.
Referenced by DefaultStrip(), and setup().