FastLED: fl::ScreenMap::ParseJson
ParseJson() [1/2]
bool fl::ScreenMap::ParseJson (const char * jsonStrScreenMap, const char * screenMapName, ScreenMap * screenmap, string * err = nullptr) static
Definition at line 217 of file screenmap.cpp.
{
    fl::fl_map<string, ScreenMap> segmentMaps;
    bool ok = ParseJson(jsonStrScreenMap, &segmentMaps, err);
    if (!ok) {
        return false;
    }
    if (segmentMaps.size() == 0) {
        return false;
    }
    if (segmentMaps.contains(screenMapName)) {
        *screenmap = segmentMaps[screenMapName];
        return true;
    }
    string _err = "ScreenMap not found: ";
    _err.append(screenMapName);
    if (err) {
        *err = _err;
    }
    return false;
}
References ScreenMap(), fl::string::append(), fl::MapRedBlackTree< Key, Value, Compare, Allocator >::contains(), ParseJson(), and fl::MapRedBlackTree< Key, Value, Compare, Allocator >::size().