FastLED: fl::ScreenMap::Circle
Circle()
ScreenMap fl::ScreenMap::Circle (int numLeds, float cm_between_leds = 1.5f, float cm_led_diameter = 0.5f, float completion = 1.0f) static
Examples
FxNoiseRing.ino.
Definition at line 63 of file screenmap.cpp.hpp.
{
    ScreenMap screenMap(numLeds);
    // radius from LED spacing
    float circumference = numLeds * cm_between_leds;
    float radius = circumference / (2 * FL_PI);
    // how big an arc we light vs leave dark
    float totalAngle = completion * 2 * FL_PI;
    float gapAngle = 2 * FL_PI - totalAngle;
    // shift so the dark gap is centered at the bottom (й/2)
    float startAngle = -FL_PI / 2 + gapAngle / 2.0f;
    // if partial, land last LED exactly at startAngle+totalAngle
    float divisor =
        (completion < 1.0f && numLeds > 1) ? (numLeds - 1) : numLeds;
    for (int i = 0; i < numLeds; ++i) {
        float angle = startAngle + (i * totalAngle) / divisor;
        float x = radius * cos(angle) * 2;
        float y = radius * sin(angle) * 2;
        screenMap[i] = {x, y};
    }
    screenMap.setDiameter(cm_led_diameter);
    return screenMap;
}
References ScreenMap(), fl::cos(), FL_PI, screenMap, fl::sin(), fl::x, and fl::y.
Referenced by DefaultStrip(), and setup().