FastLED: fl::GielisCurvePath::compute
compute()
vec2f fl::GielisCurvePath::compute (float alpha) override virtual
Implements fl::XYPathGenerator.
Definition at line 163 of file xypath_impls.cpp.hpp.
{
    // 1) map alpha to angle θ ∈ [0 … 2π)
    constexpr float kTwoPi = 6.283185307179586f;
    float theta = alpha * kTwoPi;
    // 2) superformula parameters (members of your path)
    //    a, b control the “shape scale” (often both = 1)
    //    m  controls symmetry (integer number of lobes)
    //    n1,n2,n3 control curvature/sharpness
    float a = params().a;
    float b = params().b;
    float m = params().m;
    float n1 = params().n1;
    float n2 = params().n2;
    float n3 = params().n3;
    // 3) compute radius from superformula
    float t2 = m * theta / 4.0f;
    float part1 = powf(fabsf(cosf(t2) / a), n2);
    float part2 = powf(fabsf(sinf(t2) / b), n3);
    float r = powf(part1 + part2, -1.0f / n1);
    // 4) polar → Cartesian in unit circle
    float x = r * cosf(theta);
    float y = r * sinf(theta);
    return vec2f{x, y};
}
References fl::GielisCurveParams::a, fl::GielisCurveParams::b, fl::cosf(), fl::fabsf(), fl::GielisCurveParams::m, fl::GielisCurveParams::n1, fl::GielisCurveParams::n2, fl::GielisCurveParams::n3, params(), fl::powf(), fl::sinf(), fl::x, and fl::y.