FastLED: fl::audio::BeatDetectors::reset
reset()
void fl::audio::BeatDetectors::reset ()
Definition at line 865 of file audio_reactive.cpp.hpp.
{
#if SKETCH_HAS_LARGE_MEMORY
    bass.reset();
    mid.reset();
    treble.reset();
#else
    combined.reset();
#endif
    mBassEnergy = 0.0f;
    mMidEnergy = 0.0f;
    mTrebleEnergy = 0.0f;
    mPreviousBassEnergy = 0.0f;
    mPreviousMidEnergy = 0.0f;
    mPreviousTrebleEnergy = 0.0f;
}
References BeatDetectors(), combined, mBassEnergy, mMidEnergy, mPreviousBassEnergy, mPreviousMidEnergy, mPreviousTrebleEnergy, mTrebleEnergy, and reset().
Referenced by ~BeatDetectors(), and reset().