FastLED: loop
loop()
void loop ()
Definition at line 74 of file Wave.h.
            {
    // Allow the waveSimulator to respond to the current slider value each frame.
    waveSim.setSpeed(slider);
    waveSim.setDampening(dampening);
    // Pretty much you always want half duplex to be true, otherwise you get a gray
    // wave effect that doesn't look good.
    waveSim.setHalfDuplex(halfDuplex);
    waveSim.setSuperSample(getSuperSample());
    static int x = 0; // okay static in header
    if (button.clicked()) {
        // If button click then select a random position in the wave.
        x = random(NUM_LEDS);
    }
    if (button.isPressed()) {
        FL_WARN("Button is pressed at " << x);
        triggerRipple(waveSim, x);
    }
    waveSim.update();
    for (int i = 0; i < extraFrames.value(); i++) {
        waveSim.update();
    }
    for (int x = 0; x < NUM_LEDS; x++) {
        // float value = waveSim.get(x);
        uint8_t value8 = waveSim.getu8(x);
        leds[x] = fl::CRGB(value8, value8, value8);
    }
    FastLED.show();
}
References button(), dampening(), extraFrames(), FastLED, FL_WARN, getSuperSample(), halfDuplex(), leds, NUM_LEDS, slider(), triggerRipple(), waveSim(), and x.