FastLED: fl::FetchManager::update
update()
void fl::FetchManager::update () override virtual
Update this async runner (called during async pumping)
Implements fl::async_runner.
Definition at line 130 of file fetch.cpp.
{
    // Update all active promises first
    for (auto& promise : mActivePromises) {
        if (promise.valid()) {
            promise.update();
        }
    }
    // Then clean up completed/invalid promises in a separate pass
    cleanup_completed_promises();
    // Auto-unregister from async system when no more promises
    if (mActivePromises.empty()) {
        AsyncManager::instance().unregister_runner(this);
        if (mEngineListener) {
            EngineEvents::removeListener(mEngineListener.get());
            mEngineListener.reset();
        }
    }
}
References cleanup_completed_promises(), fl::AsyncManager::instance(), mActivePromises, mEngineListener, fl::EngineEvents::removeListener(), fl::AsyncManager::unregister_runner(), fl::promise< T >::update(), and fl::promise< T >::valid().