FastLED: XY
XY()
FL_LINK_WEAK fl::u16 XY (fl::u8 x, fl::u8 y)
Examples
Noise.ino, and XYMatrix.ino.
Definition at line 35 of file blur.cpp.hpp.
{
    FASTLED_UNUSED(x);
    FASTLED_UNUSED(y);
    FL_ERROR("XY function not provided - using default [0][0]. Use blur2d with XYMap instead");
    return 0;
}
References FASTLED_UNUSED, FL_ERROR, FL_LINK_WEAK, x, and y.
Referenced by DrawOneFrame(), loop(), and XYsafe().