FastLED: fl::Mp3::parseMp3Info
parseMp3Info()
Mp3Info fl::Mp3::parseMp3Info (fl::span< const fl::u8 > data, fl::string * error_message = nullptr) static
Definition at line 410 of file mp3.cpp.hpp.
{
    Mp3Info info;
    // Validate input data
    if (data.empty()) {
        if (error_message) {
            *error_message = "Empty MP3 data";
        }
        return info; // returns invalid info
    }
    // Minimum size check - need at least an MP3 frame header (4 bytes) + some data
    if (data.size() < 128) {
        if (error_message) {
            *error_message = "MP3 data too small";
        }
        return info;
    }
    // Look for MP3 sync word (11 bits set: 0xFFE or 0xFFF)
    bool foundSync = false;
    fl::size syncOffset = 0;
    for (fl::size i = 0; i <= data.size() - 4; i++) {
        if (data[i] == 0xFF && (data[i + 1] & 0xE0) == 0xE0) {
            foundSync = true;
            syncOffset = i;
            break;
        }
    }
    if (!foundSync) {
        if (error_message) {
            *error_message = "Invalid MP3 stream - no sync word found";
        }
        return info;
    }
    // Use the decoder to parse the first frame
    third_party::Mp3HelixDecoder decoder;
    if (!decoder.init()) {
        if (error_message) {
            *error_message = "Failed to initialize MP3 decoder";
        }
        return info;
    }
    const fl::u8* inptr = data.data() + syncOffset;
    fl::size bytes_left = data.size() - syncOffset;
    // Try to decode first frame to get metadata
    int offset = decoder.findSyncWord(inptr, bytes_left);
    if (offset >= 0) {
        inptr += offset;
        bytes_left -= offset;
        int result = decoder.decodeFrame(&inptr, &bytes_left);
        if (result == 0) {
            // Successfully decoded - extract metadata
            info.sampleRate = decoder.mFrameInfo.samprate;
            info.channels = static_cast<fl::u8>(decoder.mFrameInfo.nChans);
            info.bitrate = decoder.mFrameInfo.bitrate;
            info.version = static_cast<fl::u8>(decoder.mFrameInfo.version);
            info.layer = static_cast<fl::u8>(decoder.mFrameInfo.layer);
            info.isValid = true;
        } else if (error_message) {
            *error_message = "Failed to decode MP3 frame header";
        }
    } else if (error_message) {
        *error_message = "Failed to find MP3 sync word";
    }
    return info;
}
References fl::Mp3Info::bitrate, fl::third_party::Mp3HelixDecoder::FrameInfo::bitrate, fl::Mp3Info::channels, fl::span< T, Extent >::data(), fl::third_party::Mp3HelixDecoder::decodeFrame(), fl::span< T, Extent >::empty(), fl::third_party::Mp3HelixDecoder::findSyncWord(), fl::third_party::Mp3HelixDecoder::init(), fl::Mp3Info::isValid, fl::Mp3Info::layer, fl::third_party::Mp3HelixDecoder::FrameInfo::layer, fl::third_party::Mp3HelixDecoder::mFrameInfo, fl::third_party::Mp3HelixDecoder::FrameInfo::nChans, offset(), fl::Mp3Info::sampleRate, fl::third_party::Mp3HelixDecoder::FrameInfo::samprate, fl::span< T, Extent >::size(), fl::Mp3Info::version, and fl::third_party::Mp3HelixDecoder::FrameInfo::version.