FastLED: CPixelLEDController::showColor
showColor()
template<EOrder RGB_ORDER, int LANES = 1, uint32_t MASK = 0xFFFFFFFF> virtual void CPixelLEDController< RGB_ORDER, LANES, MASK >::showColor (const CRGB & data, int nLeds, uint8_t brightness) inline override protected virtual
Set all the LEDs on the controller to a given color.
Parameters
data the CRGB color to set the LEDs to
nLeds the number of LEDs to set to this color
scale_pre_mixed the RGB scaling of color adjustment + global brightness to apply to each LED (in RGB8 mode).
Implements CLEDController.
Definition at line 34 of file cpixel_ledcontroller.h.
{
        // CRGB premixed, color_correction;
        // getAdjustmentData(brightness, &premixed, &color_correction);
        // ColorAdjustment color_adjustment = {premixed, color_correction, brightness};
        ColorAdjustment color_adjustment = getAdjustmentData(brightness);
        PixelController<RGB_ORDER, LANES, MASK> pixels(data, nLeds, color_adjustment, getDither());
        showPixels(pixels);
    }
References brightness, CLEDController::getAdjustmentData(), CLEDController::getDither(), and showPixels().