FastLED: kiss_fft
kiss_fft()
void kiss_fft (kiss_fft_cfg cfg, const kiss_fft_cpx * fin, kiss_fft_cpx * fout)
Definition at line 379 of file kiss_fft.c.
{
    kiss_fft_stride(cfg,fin,fout,1);
}
References kiss_fft_stride().
Referenced by kiss_fftr(), and kiss_fftri().