FastLED: fl::FlowFieldFP::drawImpl
drawImpl()
void fl::FlowFieldFP::drawImpl (DrawContext context, u32 dt_ms, u32 t_ms) override protected virtual
Subclasses implement rendering given the time delta and total time.
Parameters
dt_ms Milliseconds since last draw (capped to prevent huge jumps).
t_ms Milliseconds since first draw.
Implements fl::FlowField.
Definition at line 983 of file flowfield.cpp.hpp.
{
    syncParams();
    s16x16 dt = s16x16(dt_ms * 0.001f);
    s16x16 t = s16x16(t_ms * 0.001f);
    i32 dt_raw = dt.raw();
    flowPrepare(t);
    switch (mParams.emitter_mode) {
    case 0:
        emitLissajousLine(t);
        break;
    case 1:
        emitOrbitalDots(t);
        break;
    case 2:
        emitLissajousLine(t);
        emitOrbitalDots(t);
        break;
    default:
        emitLissajousLine(t);
        break;
    }
    flowAdvect(dt_raw);
    // Output: convert Q16.16 grids to LED pixels
    int w = mState.width;
    int h = mState.height;
    const i32 *rp = mState.r.data();
    const i32 *gp = mState.g.data();
    const i32 *bp = mState.b.data();
    fl::span<CRGB> out = context.leds;
    for (int y = 0; y < h; y++) {
        int row_base = y * w;
        for (int x = 0; x < w; x++) {
            int i = row_base + x;
            u16 ledIdx = mXyMap.mapToIndex(static_cast<u16>(x), static_cast<u16>(y));
            out[ledIdx].r = q16_to_u8(rp[i]);
            out[ledIdx].g = q16_to_u8(gp[i]);
            out[ledIdx].b = q16_to_u8(bp[i]);
        }
    }
    if (mParams.show_flow_vectors) {
        drawFlowVectors(context.leds);
    }
}
References drawFlowVectors(), emitLissajousLine(), emitOrbitalDots(), flowAdvect(), flowPrepare(), fl::DrawContext::leds, fl::FlowField::mParams, mState, fl::Fx2d::mXyMap, q16_to_u8(), fl::s16x16::raw(), syncParams(), fl::t, fl::x, and fl::y.