FastLED: fl::FlowFieldFP::flowPrepare
flowPrepare()
void fl::FlowFieldFP::flowPrepare (s16x16 t) private
Definition at line 753 of file flowfield.cpp.hpp.
{
    int w = mState.width;
    int h = mState.height;
    constexpr s16x16 kBaseFreq(0.23f);
    constexpr s16x16 neg_one(-1.0f);
    constexpr s16x16 one(1.0f);
    const i32 *fade_lut = mState.fade_lut;
    // Hoist loop-invariant products
    s16x16 freqX = kBaseFreq * mNoiseFreqX_fp;
    s16x16 scrollX = t * mFlowSpeedX_fp;  // time offset added to spatial coord
    for (int i = 0; i < w; i++) {
        s16x16 fx = s16x16(i) * freqX + scrollX;
        i32 noise_raw = perlin_s16x16::pnoise2d_raw(
            fx.raw(), 0, fade_lut, mPermX);
        s16x16 v = s16x16::from_raw(noise_raw);
        s16x16 clamped = s16x16::clamp(v * mFlowAmpX_fp, neg_one, one);
        mState.x_prof[i] = clamped.raw();
    }
    if (mParams.reverse_x_profile) {
        for (int i = 0; i < w / 2; i++) {
            i32 tmp = mState.x_prof[i];
            mState.x_prof[i] = mState.x_prof[w - 1 - i];
            mState.x_prof[w - 1 - i] = tmp;
        }
    }
    // Hoist loop-invariant products
    s16x16 freqY = kBaseFreq * mNoiseFreqY_fp;
    s16x16 scrollY = t * mFlowSpeedY_fp;  // time offset added to spatial coord
    for (int i = 0; i < h; i++) {
        s16x16 fx = s16x16(i) * freqY + scrollY;
        i32 noise_raw = perlin_s16x16::pnoise2d_raw(
            fx.raw(), 0, fade_lut, mPermY);
        s16x16 v = s16x16::from_raw(noise_raw);
        s16x16 clamped = s16x16::clamp(v * mFlowAmpY_fp, neg_one, one);
        mState.y_prof[i] = clamped.raw();
    }
    // Apply noise bias (attack/decay bumps from noisePunch triggers).
    for (int i = 0; i < w; i++) {
        i32 bias_raw = s16x16(mNoiseBias.getX(i)).raw();
        mState.x_prof[i] = clamp_q16(mState.x_prof[i] + bias_raw,
                                      neg_one.raw(), one.raw());
    }
    for (int i = 0; i < h; i++) {
        i32 bias_raw = s16x16(mNoiseBias.getY(i)).raw();
        mState.y_prof[i] = clamp_q16(mState.y_prof[i] + bias_raw,
                                      neg_one.raw(), one.raw());
    }
}
References fl::s16x16::clamp(), clamp_q16(), fl::s16x16::from_raw(), mFlowAmpX_fp, mFlowAmpY_fp, mFlowSpeedX_fp, mFlowSpeedY_fp, fl::FlowField::mNoiseBias, mNoiseFreqX_fp, mNoiseFreqY_fp, fl::FlowField::mParams, mPermX, mPermY, mState, fl::perlin_s16x16::pnoise2d_raw(), fl::s16x16::raw(), and fl::t.
Referenced by drawImpl().