FastLED: fl::FlowFieldFP::drawDot
drawDot()
void fl::FlowFieldFP::drawDot (s16x16 cx, s16x16 cy, s16x16 diam, u8 cr, u8 cg, u8 cb) private
Definition at line 568 of file flowfield.cpp.hpp.
{
    int w = mState.width;
    int h = mState.height;
    constexpr s16x16 half(0.5f);
    constexpr s16x16 one(1.0f);
    s16x16 rad = diam * half;
    int x0 = fl::max(0, s16x16::floor(cx - rad - one).to_int());
    int x1 = fl::min(w - 1, s16x16::ceil(cx + rad + one).to_int());
    int y0 = fl::max(0, s16x16::floor(cy - rad - one).to_int());
    int y1 = fl::min(h - 1, s16x16::ceil(cy + rad + one).to_int());
    s16x16 rad_plus_half = rad + half;
    // Hoist loop-invariant computations
    i32 threshold_sq_raw = (rad_plus_half * rad_plus_half).raw();
    i32 cr_raw = static_cast<i32>(cr) << 16;
    i32 cg_raw = static_cast<i32>(cg) << 16;
    i32 cb_raw = static_cast<i32>(cb) << 16;
    i32 *__restrict__ rp = mState.r.data();
    i32 *__restrict__ gp = mState.g.data();
    i32 *__restrict__ bp = mState.b.data();
    for (int y = y0; y <= y1; y++) {
        s16x16 dy = s16x16(y) + half - cy;
        i32 dy_sq_raw = (dy * dy).raw();
        // Early-out: if dy^2 alone exceeds threshold, skip entire row
        if (dy_sq_raw >= threshold_sq_raw) continue;
        int row_base = y * w;
        for (int x = x0; x <= x1; x++) {
            s16x16 dx = s16x16(x) + half - cx;
            i32 dist_sq_raw = dy_sq_raw + (dx * dx).raw();
            if (dist_sq_raw >= threshold_sq_raw)
                continue;
            s16x16 dist = s16x16::sqrt(s16x16::from_raw(dist_sq_raw));
            s16x16 cov = s16x16::clamp(rad_plus_half - dist, s16x16(), one);
            if (cov.raw() <= 0) continue;
            int i = row_base + x;
            // Lerp: old + (new - old) * cov — 1 i64 mul per channel instead of 2
            i32 cov_q16 = cov.raw();
            rp[i] += static_cast<i32>((static_cast<i64>(cr_raw - rp[i]) * cov_q16) >> 16);
            gp[i] += static_cast<i32>((static_cast<i64>(cg_raw - gp[i]) * cov_q16) >> 16);
            bp[i] += static_cast<i32>((static_cast<i64>(cb_raw - bp[i]) * cov_q16) >> 16);
        }
    }
}
References fl::s16x16::ceil(), fl::s16x16::clamp(), fl::s16x16::floor(), fl::s16x16::from_raw(), fl::max(), fl::min(), mState, fl::s16x16::raw(), fl::s16x16::sqrt(), fl::x, and fl::y.
Referenced by emitLissajousLine(), and emitOrbitalDots().