FastLED: fl::FlowFieldFP::emitLissajousLine
emitLissajousLine()
void fl::FlowFieldFP::emitLissajousLine (s16x16 t) private
Definition at line 678 of file flowfield.cpp.hpp.
{
    int w = mState.width;
    int h = mState.height;
    constexpr s16x16 half(0.5f);
    s16x16 cx = s16x16(w - 1) * half;
    s16x16 cy = s16x16(h - 1) * half;
    // Pre-multiply t * s once (was computed 4 times)
    s16x16 ts = t * mEndpointSpeed_fp;
    // Pre-multiply center * radius constants (was computing cx*k and cy*k each time)
    constexpr s16x16 k_0742(0.742f);
    constexpr s16x16 k_0677(0.677f);
    constexpr s16x16 k_0774(0.774f);
    constexpr s16x16 k_0710(0.710f);
    s16x16 cx_r1 = cx * k_0742;
    s16x16 cy_r1 = cy * k_0677;
    s16x16 cx_r2 = cx * k_0774;
    s16x16 cy_r2 = cy * k_0710;
    // Pre-multiply ts * frequency constants (was computing ts*k each time)
    constexpr s16x16 k_113(1.13f);
    constexpr s16x16 k_171(1.71f);
    constexpr s16x16 k_189(1.89f);
    constexpr s16x16 k_137(1.37f);
    constexpr s16x16 k_020(0.20f);
    constexpr s16x16 k_130(1.30f);
    constexpr s16x16 k_220(2.20f);
    constexpr s16x16 k_070(0.70f);
    s16x16 x1 = cx + cx_r1 * s16x16::sin(ts * k_113 + k_020);
    s16x16 y1 = cy + cy_r1 * s16x16::sin(ts * k_171 + k_130);
    s16x16 x2 = cx + cx_r2 * s16x16::sin(ts * k_189 + k_220);
    s16x16 y2 = cy + cy_r2 * s16x16::sin(ts * k_137 + k_070);
    drawAALine(x1, y1, x2, y2, t, mColorShift_fp);
    CRGB endA = rainbow(t, mColorShift_fp, s16x16());
    CRGB endB = rainbow(t, mColorShift_fp, half);
    constexpr s16x16 discDiam(1.7f);
    drawDot(x1, y1, discDiam, endA.r, endA.g, endA.b);
    drawDot(x2, y2, discDiam, endB.r, endB.g, endB.b);
}
References drawAALine(), drawDot(), mColorShift_fp, mEndpointSpeed_fp, mState, rainbow(), fl::s16x16::sin(), and fl::t.
Referenced by drawImpl().