FastLED: fl::vector::vector
vector() [1/12]
template<typename T> fl::vector< T >::vector () inline
Definition at line 492 of file vector.h.
        : vector_basic(sizeof(T), default_memory_resource(),
                        vector_element_ops_for<T>()) {}
Referenced by fl::vector_psram< T >::vector_psram(), fl::vector_psram< T >::vector_psram(), fl::VectorN< T, INLINED_SIZE >::VectorN(), fl::VectorN< T, INLINED_SIZE >::VectorN(), fl::VectorN< T, INLINED_SIZE >::VectorN(), fl::VectorN< T, INLINED_SIZE >::VectorN(), fl::VectorN< T, INLINED_SIZE >::VectorN(), fl::VectorN< T, INLINED_SIZE >::VectorN(), fl::VectorN< T, INLINED_SIZE >::VectorN(), and fl::VectorN< T, INLINED_SIZE >::VectorN().