FastLED: fl::vector::reserve
reserve()
template<typename T> void fl::vector< T >::reserve (fl::size n) inline
Definition at line 591 of file vector.h.
{ reserve_impl(n); }
Referenced by fl::audio::fft::FloatVectorPool::acquire(), fl::third_party::SoftwareMpeg1Decoder::audioDecodeCallback(), fl::base64_decode(), fl::net::http::ChunkedReader::consume(), fl::Vorbis::decodeAll(), fl::VorbisDecoderImpl::decodeNextFrame(), decodeSpiEdges(), fl::third_party::Mp3HelixDecoder::decodeToAudioSamples(), fl::audio::SignalConditioner::filterSpikes(), fl::third_party::Mp3StreamDecoderImpl::findAndDecodeFrame(), fl::FileSystem::loadJpeg(), fl::anonymous_namespace{json.cpp.hpp}::optimize_array(), fl::net::http::HttpStreamTransport::readRequest(), fl::third_party::TJpgInstanceDecoder::readStreamData(), and AutoResearchRemoteControl::registerFunctions().