FastLED: fl::FlowFieldFP::FlowFieldFP
FlowFieldFP()
fl::FlowFieldFP::FlowFieldFP (const XYMap & xyMap, const Params & params = Params()) explicit
Definition at line 508 of file flowfield.cpp.hpp.
    : FlowField(xyMap, params) {
    int w = (int)getWidth();
    int h = (int)getHeight();
    mState.init(w, h);
    initPerm256(mPermX, 42);
    initPerm256(mPermY, 1337);
    syncParams();
    if (!mState.fade_lut_initialized) {
        perlin_s16x16::init_fade_lut(mState.fade_lut);
        mState.fade_lut_initialized = true;
    }
}
References fl::FlowField::FlowField(), fl::Fx2d::getHeight(), fl::Fx2d::getWidth(), fl::perlin_s16x16::init_fade_lut(), initPerm256(), mPermX, mPermY, mState, syncParams(), and fl::Fx2d::xyMap().