FastLED: fl::FlowFieldFP::drawFlowVectors
drawFlowVectors()
void fl::FlowFieldFP::drawFlowVectors (fl::span< CRGB > leds) private
Definition at line 903 of file flowfield.cpp.hpp.
{
    int w = mState.width;
    int h = mState.height;
    // Helper: plot a single subpixel point via Tile2x2 through the XYMap.
    // Uses float for the interpolation math (unoptimized debug overlay).
    auto plotTile = [&](const CRGB &color, float px, float py,
                        bool horiz) {
        int ix = (int)floorf(px);
        int iy = (int)floorf(py);
        float fx = px - (float)ix;
        float fy = py - (float)iy;
        Tile2x2_u8 tile;
        tile.setOrigin((u16)ix, (u16)iy);
        if (horiz) {
            tile.at(0, 0) = (u8)((1.0f - fy) * 255.0f);
            tile.at(1, 0) = 0;
            tile.at(0, 1) = (u8)(fy * 255.0f);
            tile.at(1, 1) = 0;
        } else {
            tile.at(0, 0) = (u8)((1.0f - fx) * 255.0f);
            tile.at(1, 0) = (u8)(fx * 255.0f);
            tile.at(0, 1) = 0;
            tile.at(1, 1) = 0;
        }
        tile.draw(color, mXyMap, leds);
    };
    // Display amplitude: 0.3 = profile uses ~30% of the display around center.
    constexpr float amp = 0.3f;
    // X profile (per-column): plot value as y-position — cyan.
    // Interpolate between consecutive columns to fill gaps.
    CRGB xColor(0, 255, 255);
    float centerY = (float)(h - 1) * 0.5f;
    float prevPy = 0.0f;
    for (int x = 0; x < w; x++) {
        s16x16 val = s16x16::from_raw(mState.x_prof[x]); // [-1, 1]
        float py = centerY - val.to_float() * amp * centerY;
        plotTile(xColor, (float)x, py, true);
        if (x > 0) {
            float dy = py - prevPy;
            int gap = (int)fabsf(dy);
            for (int s = 1; s < gap; s++) {
                float t = (float)s / (float)gap;
                float midY = prevPy + dy * t;
                float midX = (float)(x - 1) + t;
                plotTile(xColor, midX, midY, true);
            }
        }
        prevPy = py;
    }
    // Y profile (per-row): plot value as x-position — yellow.
    // Interpolate between consecutive rows to fill gaps.
    CRGB yColor(255, 255, 0);
    float centerX = (float)(w - 1) * 0.5f;
    float prevPx = 0.0f;
    for (int y = 0; y < h; y++) {
        s16x16 val = s16x16::from_raw(mState.y_prof[y]); // [-1, 1]
        float px = centerX + val.to_float() * amp * centerX;
        plotTile(yColor, px, (float)y, false);
        if (y > 0) {
            float dx = px - prevPx;
            int gap = (int)fabsf(dx);
            for (int s = 1; s < gap; s++) {
                float t = (float)s / (float)gap;
                float midX = prevPx + dx * t;
                float midY = (float)(y - 1) + t;
                plotTile(yColor, midX, midY, false);
            }
        }
        prevPx = px;
    }
}
References fl::fabsf(), fl::floorf(), fl::s16x16::from_raw(), leds, mState, fl::Fx2d::mXyMap, fl::Tile2x2_u8::setOrigin(), fl::t, fl::s16x16::to_float(), fl::x, and fl::y.
Referenced by drawImpl().