FastLED: loop
loop()
void loop ()
Definition at line 105 of file FireMatrix.ino.
            {
    FastLED.setBrightness(brightness);
    CRGBPalette16 myPal = getPalette();
    uint32_t now = millis();
    timeScale.setSpeed(speedY);
    uint32_t y_speed = timeScale.update(now);
    for (int i = 0; i < HEIGHT; i++) {
        for (int j = 0; j < WIDTH; j++) {
            uint8_t palette_index = getPaletteIndex(now, i, j, y_speed);
            CRGB c = ColorFromPalette(myPal, palette_index, BRIGHTNESS);
            int index = xyMap((HEIGHT - 1) - i, (WIDTH - 1) - j);
            leds[index] = c;
        }
    }
    FastLED.show();
}
References BRIGHTNESS, brightness, fl::ColorFromPalette(), FastLED, getPalette(), getPaletteIndex(), HEIGHT, leds, speedY, timeScale, WIDTH, xyMap, and y_speed.