FastLED: fl::ChannelManager::findDriverByName
findDriverByName()
fl::shared_ptr< IChannelDriver > fl::ChannelManager::findDriverByName (const fl::string & name) const
Silent counterpart to getDriverByName().
Same lookup, no logging on miss. Lets callers that handle the "missing driver" case themselves (e.g. Channel::showPixels()'s one-shot affinity-miss diagnostic from #2455) probe the registry without triggering the per-frame FL_ERROR stream that getDriverByName() emits.
Definition at line 356 of file manager.cpp.hpp.
{
    if (name.empty()) {
        return fl::shared_ptr<IChannelDriver>();
    }
    for (const auto& entry : mDrivers) {
        if (entry.enabled && entry.name == name) {
            return entry.driver;
        }
    }
    return fl::shared_ptr<IChannelDriver>();
}
References fl::basic_string::empty(), and mDrivers.
Referenced by getDriverByName(), fl::Channel::resolveDynamicDriver(), and selectDriverForChannel().