FastLED: fl::detail::AsyncLoggerServiceTask::AsyncLoggerServiceTask
AsyncLoggerServiceTask()
fl::detail::AsyncLoggerServiceTask::AsyncLoggerServiceTask () private
Definition at line 234 of file async_logger.cpp.hpp.
    : mIntervalMs(16)
    , mMessagesPerTick(5)
    , mTask()
{
    // Create and register task with scheduler
    // Default 16ms interval = 60 Hz (one frame at 60fps)
    mTask = fl::task::every_ms(mIntervalMs)
        .then([this]() {
            // Service all registered async loggers
            this->serviceLoggers();
        });
    fl::task::Scheduler::instance().add_task(mTask);
}
References fl::task::Scheduler::add_task(), fl::task::every_ms(), fl::task::Scheduler::instance(), mIntervalMs, mMessagesPerTick, mTask, serviceLoggers(), and fl::task::Handle::then().
Referenced by ~AsyncLoggerServiceTask(), fl::SingletonShared< AsyncLoggerServiceTask >, and instance().