FastLED: reallocate_kernels
reallocate_kernels()
struct sparse_arr * reallocate_kernels (struct sparse_arr * old_ptr, struct cq_kernel_cfg cfg)
Definition at line 143 of file cq_kernel.cpp.hpp.
{
    struct sparse_arr *new_ptr = (struct sparse_arr*)fl::malloc(cfg.bands*sizeof(struct sparse_arr));
    for(int i = 0; i < cfg.bands; i++){
        new_ptr[i].n_elems = old_ptr[i].n_elems;
        new_ptr[i].elems = (struct sparse_arr_elem*)fl::malloc(old_ptr[i].n_elems*sizeof(struct sparse_arr_elem));
        fl::memcpy(new_ptr[i].elems, old_ptr[i].elems, old_ptr[i].n_elems*sizeof(struct sparse_arr_elem));
        fl::free(old_ptr[i].elems);
    }
    fl::free(old_ptr);
    return new_ptr;
}
References sparse_arr::elems, FL_NOEXCEPT, fl::free(), fl::malloc(), fl::memcpy(), and sparse_arr::n_elems.