FastLED: setup
setup()
void setup ()
Definition at line 79 of file Loopback.ino.
             {
    Serial.begin(115200);
    Serial.println("HTTP Server Loopback Test");
    // Initialize LED strip
    FastLED.addLeds<WS2812, DATA_PIN, GRB>(leds, NUM_LEDS);
    FastLED.setBrightness(64);
    // Register HTTP server routes inline (clear and simple)
    server.get("/", [](const fl::http_request& req) {
        return fl::http_response::ok("Hello from loopback test!\n");
    });
    server.get("/ping", [](const fl::http_request& req) {
        return fl::http_response::ok("pong\n");
    });
    server.get("/test", [](const fl::http_request& req) {
        return fl::http_response::ok("test response\n");
    });
    // Start HTTP server
    if (server.start(8080)) {
        Serial.println("Server started on http://localhost:8080/");
        state = WAITING_FOR_TESTS;
        startup_time = fl::millis();
    } else {
        Serial.println("ERROR: Failed to start server");
        Serial.print("Error: ");
        Serial.println(server.last_error().c_str());
        state = FAILED;
    }
    updateLEDs();
    FastLED.show();
}
References DATA_PIN, FAILED, FastLED, GRB, leds, fl::millis(), NUM_LEDS, fl::asio::http::Response::ok(), Serial, server, startup_time, state, updateLEDs(), and WAITING_FOR_TESTS.