FastLED: loop
loop()
void loop ()
Definition at line 116 of file Loopback.ino.
            {
    // Pump async task queue (async fetch tasks + server)
    fl::task::run();
    // State: WAITING_FOR_TESTS -> wait 1 second after startup -> start tests
    if (state == WAITING_FOR_TESTS && (fl::millis() - startup_time > 1000)) {
        // Start test sequence with completion callback
        testRunner.startTests([](bool success, int passed, int total) {
            // Called when all tests complete
            state = success ? ALL_PASSED : FAILED;
            server.stop();
        });
        state = TESTS_RUNNING;
    }
    // Update test runner state machine (advances tests, processes callbacks)
    if (state == TESTS_RUNNING) {
        testRunner.update();
    }
    if (state == ALL_PASSED || state == FAILED) {
        updateLEDs();
        FastLED.show();
        delay(100);
        return;  // Stay in terminal state, let the framework break from this test.
    }
    // Update LED feedback and show
    updateLEDs();
    FastLED.show();
    // Small delay allows async promise callbacks to process
    // On WASM, delay() automatically pumps async tasks every 1ms
    delay(10);
}
References ALL_PASSED, FAILED, FastLED, fl::millis(), fl::task::run(), server, startup_time, state, testRunner, TESTS_RUNNING, updateLEDs(), and WAITING_FOR_TESTS.