FastLED: fl::Json::parse
parse()
static Json fl::Json::parse (const fl::string & txt) inline static
Definition at line 2126 of file json.h.
{
        auto parsed = JsonValue::parse(txt);
        if (parsed) {
            Json result;
            result.m_value = parsed;
            return result;
        }
References Json(), and fl::JsonValue::parse().
Referenced by fl::response::parse_json_body(), fl::ScreenMap::ParseJson(), fl::FileSystem::readJson(), and setup().