FastLED: fl::unsorted_map_fixed::insert
insert() [2/2]
template<typename Key, typename Value, fl::size N> pair< bool, iterator > fl::unsorted_map_fixed< Key, Value, N >::insert (Key && key, Value && value, insert_result * result = nullptr) inline
Definition at line 147 of file map.h.
{
        iterator it = find(key);
        if (it != end()) {
            if (result) {
                *result = exists;
            }
            return {false, it};
        }
        if (data.size() < N) {
            data.push_back(PairKV(fl::move(key), fl::move(value)));
            if (result) {
                *result = inserted;
            }
            return {true, data.end() - 1};
        }
        if (result) {
            *result = at_capacity;
        }
        return {false, end()};
    }
References at_capacity, data, end(), exists, find(), inserted, fl::fl::move(), and fl::type_rank< T >::value.