FastLED: simd_test::print_test_result
print_test_result()
void simd_test::print_test_result (const TestResult & result)
Print test result to serial.
Parameters
result Test result to print
Definition at line 38 of file test_helpers.cpp.
{
    fl::sstream ss;
    if (result.passed) {
        ss << "  ✓ PASS: " << result.test_name;
        FL_PRINT(ss.str());
    } else {
        ss << "  ✗ FAIL: " << result.test_name;
        FL_PRINT(ss.str());
        if (result.error_msg) {
            fl::sstream err;
            err << "    ERROR: " << result.error_msg;
            FL_ERROR(err.str().c_str());
        }
    }
}
References fl::basic_string::c_str(), FL_ERROR, FL_PRINT, and fl::sstream::str().
Referenced by run_test().