FastLED: simd_test::print_summary
print_summary()
void simd_test::print_summary (const fl::vector< TestResult > & test_results, int total_tests, int passed_tests, int failed_tests)
Print summary table of all test results.
Parameters
test_results All test results
total_tests Total number of tests
passed_tests Number of passed tests
failed_tests Number of failed tests
Definition at line 58 of file test_helpers.cpp.
{
    fl::sstream ss;
    ss << "\n╔════════════════════════════════════════════════════════════════╗\n";
    ss << "║ SIMD TEST SUMMARY                                              ║\n";
    ss << "╚════════════════════════════════════════════════════════════════╝\n";
    FL_PRINT(ss.str());
    ss.clear();
    ss << "Total Tests:  " << total_tests << "\n";
    ss << "Passed:       " << passed_tests << " ("
       << (total_tests > 0 ? (passed_tests * 100 / total_tests) : 0) << "%)\n";
    ss << "Failed:       " << failed_tests << " ("
       << (total_tests > 0 ? (failed_tests * 100 / total_tests) : 0) << "%)";
    FL_PRINT(ss.str());
    if (failed_tests > 0) {
        FL_PRINT("\nFailed Tests:");
        for (size_t i = 0; i < test_results.size(); i++) {
            if (!test_results[i].passed) {
                fl::sstream fail_ss;
                fail_ss << "  - " << test_results[i].test_name;
                if (test_results[i].error_msg) {
                    fail_ss << ": " << test_results[i].error_msg;
                }
                FL_PRINT(fail_ss.str());
            }
        }
    }
}
References fl::sstream::clear(), failed_tests, FL_PRINT, passed_tests, fl::sstream::str(), test_results, and total_tests.
Referenced by setup().