FastLED: fl::Particles1d::draw
draw()
void fl::Particles1d::draw (DrawContext context) override virtual
Update and render all particles with overdraw technique.
Parameters
context Draw context containing current time and LED buffer
Implements fl::Fx.
Definition at line 19 of file particles.cpp.hpp.
{
    if (context.leds.empty() || mNumLeds == 0) return;
    u32 now = context.now;
    // Overdraw loop: multiple updates per frame for smooth trails
    for (int overdraw = 0; overdraw < mOverdrawCount; overdraw++) {
        // Fade trails
        for (u16 i = 0; i < mNumLeds; i++) {
            context.leds[i].nscale8(255 - mFadeRate);
        }
        // Update and draw all particles
        for (size_t i = 0; i < mParticles.size(); i++) {
            mParticles[i].update(now, mNumLeds, mSpeedMultiplier, mCyclical);
            mParticles[i].draw(context.leds, now, mNumLeds);
        }
    }
    // Soften composite with blur
    blur1d(context.leds, 64);
}
References Particles1d(), fl::blur1d(), draw(), mCyclical, mFadeRate, fl::Fx::mNumLeds, mOverdrawCount, mParticles, and mSpeedMultiplier.
Referenced by ~Particles1d(), and draw().