FastLED: CLEDController::beginShowLeds
beginShowLeds()
virtual void * CLEDController::beginShowLeds (int size) inline virtual
Reimplemented in RGBWEmulatedController< CONTROLLER, RGB_ORDER >, WS2816Controller< DATA_PIN, RGB_ORDER >, and WS2816Controller< DATA_PIN, RGB_ORDER >.
Definition at line 214 of file cled_controller.h.
{
        FASTLED_UNUSED(size);
        // By default, emit an integer. This integer will, by default, be passed back.
        // If you override beginShowLeds() then
        // you should also override endShowLeds() to match the return state.
        //
        // For async led controllers this should be used as a sync point to block
        // the caller until the leds from the last draw frame have completed drawing.
        // for each controller:
        //   beginShowLeds();
        // for each controller:
        //   showLeds();
        // for each controller:
        //   endShowLeds();
        uintptr_t d = getDither();
        void* out = reinterpret_cast<void*>(d);
        return out;
    }
References FASTLED_UNUSED, getDither(), and size().
Referenced by CFastLED::show(), CFastLED::showColor(), and showLeds().