FastLED: CLEDController::showLeds
showLeds()
VIRTUAL_IF_NOT_AVR void CLEDController::showLeds (uint8_t brightness) inline
Definition at line 98 of file cled_controller.h.
{
        void* data = beginShowLeds(m_nLeds);
        showLedsInternal(brightness);
        endShowLeds(data);
    }
References beginShowLeds(), brightness, endShowLeds(), m_nLeds, showLedsInternal(), and VIRTUAL_IF_NOT_AVR.
Referenced by clearLeds().