FastLED: CLEDController::CLEDController
CLEDController()
CLEDController::CLEDController ()
Create an led controller object, add it to the chain of controllers.
Definition at line 14 of file cled_controller.cpp.
                               : m_Data(NULL), m_ColorCorrection(UncorrectedColor), m_ColorTemperature(UncorrectedTemperature), m_DitherMode(BINARY_DITHER), m_nLeds(0) {
    m_pNext = NULL;
    if(m_pHead==NULL) { m_pHead = this; }
    if(m_pTail != NULL) { m_pTail->m_pNext = this; }
    m_pTail = this;
}
References BINARY_DITHER, m_ColorCorrection, m_ColorTemperature, m_Data, m_DitherMode, m_nLeds, m_pHead, m_pNext, m_pTail, UncorrectedColor, and UncorrectedTemperature.
Referenced by CPixelLEDController< RGB_ORDER, LANES, MASK >::CPixelLEDController(), head(), next(), setCorrection(), setCorrection(), setDither(), setLeds(), setRgbw(), setScreenMap(), setScreenMap(), setScreenMap(), setTemperature(), and setTemperature().