FastLED: CLEDController::endShowLeds
endShowLeds()
virtual void CLEDController::endShowLeds (void * data) inline virtual
Reimplemented in RGBWEmulatedController< CONTROLLER, RGB_ORDER >, WS2816Controller< DATA_PIN, RGB_ORDER >, and WS2816Controller< DATA_PIN, RGB_ORDER >.
Definition at line 239 of file cled_controller.h.
{
        // By default recieves the integer that beginShowLeds() emitted.
        //For async controllers this should be used to signal the controller
        // to begin transmitting the current frame to the leds.
        uintptr_t d = reinterpret_cast<uintptr_t>(data);
        setDither(static_cast<uint8_t>(d));
    }
References setDither().
Referenced by CFastLED::show(), CFastLED::showColor(), and showLeds().