FastLED: fl::Tile2x2_u8::at
at() [1/2]
uint8_t & fl::Tile2x2_u8::at (int x, int y) inline
Definition at line 35 of file tile2x2.h.
{ return mTile[y][x]; }
References mTile, x, and y.
Referenced by draw(), lower_left(), lower_right(), Max(), maxValue(), operator()(), fl::StrStream::operator<<(), fl::XYRasterU8Sparse::rasterize_internal(), scale(), upper_left(), and upper_right().