FastLED: CodecProcessor::processMpeg1
processMpeg1()
void CodecProcessor::processMpeg1 ()
Definition at line 148 of file codec_processor.cpp.
                    {
    Serial.println("\n=== Processing MPEG1 ===");
    if (!fl::Mpeg1::isSupported()) {
        Serial.println("MPEG1 decoding not supported on this platform");
        return;
    }
    // Copy data from PROGMEM to RAM
    fl::vector<fl::u8> mpegData(CodecData::sampleMpeg1DataLength);
    fl::memcopy(mpegData.data(), CodecData::sampleMpeg1Data, CodecData::sampleMpeg1DataLength);
    // Configure MPEG1 decoder
    fl::Mpeg1Config config;
    config.mode = fl::Mpeg1Config::SingleFrame;
    config.targetFps = TARGET_FPS;
    config.looping = false;
    config.skipAudio = true;
    // Create decoder
    fl::string error_msg;
    fl::shared_ptr<fl::IDecoder> decoder = fl::Mpeg1::createDecoder(config, &error_msg);
    if (!decoder) {
        Serial.print("Failed to create MPEG1 decoder: ");
        Serial.println(error_msg.c_str());
        return;
    }
    // Create byte stream from data
    auto stream = fl::make_shared<fl::memorybuf>(mpegData.size());
    stream->write(mpegData);
    // Begin decoding
    if (!decoder->begin(stream)) {
        fl::string error;
        decoder->hasError(&error);
        Serial.print("Failed to begin MPEG1 decoding: ");
        Serial.println(error.c_str());
        return;
    }
    // Decode first frame
    fl::DecodeResult result = decoder->decode();
    if (result == fl::DecodeResult::Success) {
        fl::Frame frame = decoder->getCurrentFrame();
        if (frame.isValid()) {
            displayFrameOnLEDs(frame);
            showDecodedMessage("MPEG1 decoded successfully!");
        } else {
            Serial.println("Invalid MPEG1 frame received");
        }
    } else {
        fl::string error;
        decoder->hasError(&error);
        Serial.print("MPEG1 frame decode error: ");
        Serial.println(error.c_str());
    }
    decoder->end();
}
References fl::basic_string::c_str(), fl::Mpeg1::createDecoder(), fl::vector< T >::data(), displayFrameOnLEDs(), fl::Mpeg1::isSupported(), fl::Frame::isValid(), fl::third_party::Mpeg1Config::looping, fl::make_shared(), fl::memcopy(), fl::third_party::Mpeg1Config::mode, CodecData::sampleMpeg1Data, CodecData::sampleMpeg1DataLength, Serial, showDecodedMessage(), fl::third_party::Mpeg1Config::SingleFrame, fl::vector_basic::size(), fl::third_party::Mpeg1Config::skipAudio, fl::Success, TARGET_FPS, and fl::third_party::Mpeg1Config::targetFps.
Referenced by loop().