FastLED: CodecProcessor::displayFrameOnLEDs
displayFrameOnLEDs()
void CodecProcessor::displayFrameOnLEDs (const fl::Frame & frame)
Definition at line 211 of file codec_processor.cpp.
{
    for (int y = 0; y < ledHeight; y++) {
        for (int x = 0; x < ledWidth; x++) {
            // Calculate source pixel coordinates (with scaling)
            int srcX = (x * (int)frame.getWidth()) / ledWidth;
            int srcY = (y * (int)frame.getHeight()) / ledHeight;
            // Get pixel from frame
            CRGB color = getPixelFromFrame(frame, srcX, srcY);
            // Set LED color
            int ledIndex = y * ledWidth + x;
            if (ledIndex < numLeds) {
                leds[ledIndex] = color;
            }
        }
    }
}
References fl::Frame::getHeight(), getPixelFromFrame(), fl::Frame::getWidth(), ledHeight, leds, ledWidth, numLeds, x, and y.
Referenced by processGif(), processJpeg(), and processMpeg1().