FastLED: CodecProcessor::processGif
processGif()
void CodecProcessor::processGif ()
Definition at line 87 of file codec_processor.cpp.
                  {
    Serial.println("\n=== Processing GIF ===");
    if (!fl::Gif::isSupported()) {
        Serial.println("GIF decoding not supported on this platform");
        return;
    }
    // Copy data from PROGMEM to RAM
    fl::vector<fl::u8> gifData(CodecData::sampleGifDataLength);
    fl::memcopy(gifData.data(), CodecData::sampleGifData, CodecData::sampleGifDataLength);
    // Configure GIF decoder
    fl::GifConfig config;
    config.mode = fl::GifConfig::SingleFrame;
    config.format = fl::PixelFormat::RGB888;
    // Create decoder
    fl::string error_msg;
    fl::shared_ptr<fl::IDecoder> decoder = fl::Gif::createDecoder(config, &error_msg);
    if (!decoder) {
        Serial.print("Failed to create GIF decoder: ");
        Serial.println(error_msg.c_str());
        return;
    }
    // Create byte stream from data
    auto stream = fl::make_shared<fl::memorybuf>(gifData.size());
    stream->write(gifData);
    // Begin decoding
    if (!decoder->begin(stream)) {
        fl::string error;
        decoder->hasError(&error);
        Serial.print("Failed to begin GIF decoding: ");
        Serial.println(error.c_str());
        return;
    }
    // Decode first frame
    fl::DecodeResult result = decoder->decode();
    if (result == fl::DecodeResult::Success) {
        fl::Frame frame = decoder->getCurrentFrame();
        if (frame.isValid()) {
            displayFrameOnLEDs(frame);
            showDecodedMessage("GIF decoded successfully!");
        } else {
            Serial.println("Invalid GIF frame received");
        }
    } else {
        fl::string error;
        decoder->hasError(&error);
        Serial.print("GIF frame decode error: ");
        Serial.println(error.c_str());
    }
    decoder->end();
}
References fl::basic_string::c_str(), fl::Gif::createDecoder(), fl::vector< T >::data(), displayFrameOnLEDs(), fl::GifConfig::format, fl::Gif::isSupported(), fl::Frame::isValid(), fl::make_shared(), fl::memcopy(), fl::GifConfig::mode, fl::RGB888, CodecData::sampleGifData, CodecData::sampleGifDataLength, Serial, showDecodedMessage(), fl::GifConfig::SingleFrame, fl::vector_basic::size(), and fl::Success.
Referenced by loop().