FastLED: CodecProcessor::processCodecWithTiming
processCodecWithTiming()
void CodecProcessor::processCodecWithTiming (const char * codecName, fl::function< void()> codecFunc)
Definition at line 18 of file codec_processor.cpp.
{
    FL_WARN("Starting format " << codecName);
    fl::u32 start_time = millis();
    // Execute the codec processing function
    codecFunc();
    fl::u32 diff_time = millis() - start_time;
    FL_WARN("Format took " << diff_time << "ms to process " << codecName);
    // Now build up the message to display the current leds
    fl::sstream message;
    message << "Format: " << codecName << "\n";
    message << "LEDs: " << numLeds << " (" << ledWidth << "x" << ledHeight << ")\n";
    // For 32x32, just show a summary rather than all pixels
    if (numLeds > 16) {
        // Show first few pixels as a sample
        message << "First 4 pixels: ";
        for (int i = 0; i < 4 && i < numLeds; i++) {
            message << "RGB(" << (int)leds[i].r << "," << (int)leds[i].g << "," << (int)leds[i].b << ") ";
        }
        message << "\n";
    } else {
        // For small displays, show all LEDs
        for (int i = 0; i < numLeds; i++) {
            message << "LED " << i << ": " << leds[i] << "\n";
        }
    }
    FL_WARN(message.str().c_str());
    FastLED.show();
}
References fl::basic_string::c_str(), FastLED, FL_WARN, ledHeight, leds, ledWidth, numLeds, and fl::sstream::str().
Referenced by loop().