FastLED: fl::DigitalMultiWrite8::init
init()
void fl::DigitalMultiWrite8::init (const Pins8 & pins)
Initialize from 8 pin numbers. -1 means "skip this bit position".
Definition at line 157 of file pins.cpp.hpp.
{
    for (u8 i = 0; i < 8; ++i) {
        mPins[i] = pins.pins[i];
    }
    // Find the majority port and disable pins on other ports.
    int port_counts[32] = {};
    int port_ids[8] = {};
    int num_active = 0;
    for (u8 i = 0; i < 8; ++i) {
        if (mPins[i] < 0) {
            port_ids[i] = -1;
            continue;
        }
        int p = fl::pinToPort(mPins[i]);
        port_ids[i] = p;
        if (p >= 0 && p < 32) {
            port_counts[p]++;
        }
        num_active++;
    }
    // Find the port with the highest pin count.
    int best_port = -1;
    int best_count = 0;
    for (int p = 0; p < 32; ++p) {
        if (port_counts[p] > best_count) {
            best_count = port_counts[p];
            best_port = p;
        }
    }
    // Disable pins that aren't on the majority port and warn.
    if (best_port >= 0 && best_count < num_active) {
        for (u8 i = 0; i < 8; ++i) {
            if (mPins[i] < 0) {
                continue;
            }
            if (port_ids[i] != best_port) {
                FL_WARN("digitalMultiWrite8: pin "
                        << mPins[i] << " (port " << port_ids[i]
                        << ") disabled — not on majority port "
                        << best_port);
                mPins[i] = -1;
            }
        }
    }
    buildNibbleLut(0, mSetLo, mClrLo); // bits 0-3
    buildNibbleLut(4, mSetHi, mClrHi); // bits 4-7
}
References buildNibbleLut(), FL_WARN, mClrHi, mClrLo, mPins, mSetHi, mSetLo, pins, and fl::pinToPort().
Referenced by DigitalMultiWrite8(), and fl::digitalMultiWrite8().