FastLED: fl::audio::detector::Beat::update
update()
void fl::audio::detector::Beat::update (shared_ptr< Context > context) override virtual
Implements fl::audio::Detector.
Definition at line 28 of file beat.cpp.hpp.
{
    // Use 30 Hz min frequency so bass bins actually cover sub-bass (20-60 Hz).
    // Default fmin (90 Hz) covers most bass but misses the deepest sub-bass.
    // CQ_NAIVE provides bass/treble discrimination via CQ kernels
    // (which include built-in Hamming windowing), while being faster
    // than CQ_OCTAVE. The 16-bin / 30-14080Hz range has N_window=1,
    // which is borderline for CQ_NAIVE but acceptable for beat detection.
    mRetainedFFT = context->getFFT(16, 30.0f,
                                   fft::Args::DefaultMaxFrequency(),
                                   fft::Mode::CQ_NAIVE);
    const fft::Bins& fft = *mRetainedFFT;
    u32 timestamp = context->getTimestamp();
    // Calculate spectral flux
    mSpectralFlux = calculateSpectralFlux(fft);
    // Detect beat BEFORE updating adaptive threshold.
    // If we update the threshold first, the current frame's (potentially
    // high) spectral flux inflates the running average, raising the
    // threshold at the exact moment we need it lowest (onset detection).
    mBeatDetected = detectBeat(timestamp);
    // Update adaptive threshold AFTER beat detection
    updateAdaptiveThreshold();
    if (mBeatDetected) {
        updateTempo(timestamp);
        mLastBeatTime = timestamp;
    }
    // Update phase regardless of beat detection
    updatePhase(timestamp);
    // Update previous magnitudes for next frame
    for (size i = 0; i < fft.raw().size() && i < mPreviousMagnitudes.size(); i++) {
        mPreviousMagnitudes[i] = fft.raw()[i];
    }
}
References Beat(), calculateSpectralFlux(), fl::audio::fft::CQ_NAIVE, fl::audio::fft::Args::DefaultMaxFrequency(), detectBeat(), mBeatDetected, mLastBeatTime, mPreviousMagnitudes, mRetainedFFT, mSpectralFlux, update(), updateAdaptiveThreshold(), updatePhase(), and updateTempo().
Referenced by ~Beat(), and update().