FastLED: fl::AudioReactive::processFFT
processFFT()
void fl::AudioReactive::processFFT (const AudioSample & sample) private
Definition at line 90 of file audio_reactive.cpp.
{
    // Get PCM data from AudioSample
    const auto& pcmData = sample.pcm();
    if (pcmData.empty()) return;
    // Use AudioSample's built-in FFT capability
    sample.fft(&mFFTBins);
    // Map FFT bins to frequency channels using WLED-compatible mapping
    mapFFTBinsToFrequencyChannels();
}
References fl::AudioSample::fft(), mapFFTBinsToFrequencyChannels(), mFFTBins, and fl::AudioSample::pcm().
Referenced by processSample().