FastLED: fl::AudioReactive::processSample
processSample()
void fl::AudioReactive::processSample (const AudioSample & sample)
Definition at line 53 of file audio_reactive.cpp.
{
    if (!sample.isValid()) {
        return; // Invalid sample, ignore
    }
    // Extract timestamp from the AudioSample
    fl::u32 currentTimeMs = sample.timestamp();
    // Process the AudioSample immediately - timing is gated by sample availability
    processFFT(sample);
    updateVolumeAndPeak(sample);
    // Enhanced processing pipeline
    calculateBandEnergies();
    updateSpectralFlux();
    // Enhanced beat detection (includes original)
    detectBeat(currentTimeMs);
    detectEnhancedBeats(currentTimeMs);
    // Apply perceptual weighting if enabled
    applyPerceptualWeighting();
    applyGain();
    applyScaling();
    smoothResults();
    mCurrentData.timestamp = currentTimeMs;
}
References applyGain(), applyPerceptualWeighting(), applyScaling(), calculateBandEnergies(), detectBeat(), detectEnhancedBeats(), fl::AudioSample::isValid(), mCurrentData, processFFT(), smoothResults(), fl::AudioSample::timestamp(), updateSpectralFlux(), and updateVolumeAndPeak().