FastLED: fl::AudioReactive::updateVolumeAndPeak
updateVolumeAndPeak()
void fl::AudioReactive::updateVolumeAndPeak (const AudioSample & sample) private
Definition at line 152 of file audio_reactive.cpp.
{
    // Get PCM data from AudioSample
    const auto& pcmData = sample.pcm();
    if (pcmData.empty()) {
        mCurrentData.volume = 0.0f;
        mCurrentData.volumeRaw = 0.0f;
        mCurrentData.peak = 0.0f;
        return;
    }
    // Use AudioSample's built-in RMS calculation
    float rms = sample.rms();
    // Calculate peak from PCM data
    float maxSample = 0.0f;
    for (fl::i16 pcmSample : pcmData) {
        float absSample = (pcmSample < 0) ? -pcmSample : pcmSample;
        maxSample = (maxSample > absSample) ? maxSample : absSample;
    }
    // Scale to 0-255 range (approximately)
    mCurrentData.volumeRaw = rms / 128.0f;  // Rough scaling
    mCurrentData.volume = mCurrentData.volumeRaw;
    // Peak detection
    mCurrentData.peak = maxSample / 32768.0f * 255.0f;
    // Update AGC tracking
    if (mConfig.agcEnabled) {
        // AGC with attack/decay behavior
        float agcAttackRate = mConfig.attack / 255.0f * 0.2f + 0.01f;  // 0.01 to 0.21
        float agcDecayRate = mConfig.decay / 255.0f * 0.05f + 0.001f;  // 0.001 to 0.051
        // Track maximum level with attack/decay
        if (maxSample > mMaxSample) {
            // Rising - use attack rate (faster response)
            mMaxSample = mMaxSample * (1.0f - agcAttackRate) + maxSample * agcAttackRate;
        } else {
            // Falling - use decay rate (slower response)
            mMaxSample = mMaxSample * (1.0f - agcDecayRate) + maxSample * agcDecayRate;
        }
        // Update AGC multiplier with proper bounds
        if (mMaxSample > 1000.0f) {
            float targetLevel = 16384.0f; // Half of full scale
            float newMultiplier = targetLevel / mMaxSample;
            // Smooth AGC multiplier changes using attack/decay
            if (newMultiplier > mAGCMultiplier) {
                // Increasing gain - use attack rate
                mAGCMultiplier = mAGCMultiplier * (1.0f - agcAttackRate) + newMultiplier * agcAttackRate;
            } else {
                // Decreasing gain - use decay rate
                mAGCMultiplier = mAGCMultiplier * (1.0f - agcDecayRate) + newMultiplier * agcDecayRate;
            }
            // Clamp multiplier to reasonable bounds
            mAGCMultiplier = (mAGCMultiplier < 0.1f) ? 0.1f : ((mAGCMultiplier > 10.0f) ? 10.0f : mAGCMultiplier);
        }
    }
}
References mAGCMultiplier, mConfig, mCurrentData, mMaxSample, fl::AudioSample::pcm(), fl::AudioSample::rms(), and rms().
Referenced by processSample().