FastLED: animartrix_ring::SoundOrchestrator::tick
tick()
float animartrix_ring::SoundOrchestrator::tick (fl::u32 nowMs, float manualSpeedScalar)
Per-frame tick.
Pass the current millis() and a manual-speed scalar (so the existing "Time Speed" slider still composes). Returns the engine speed actually applied this tick.
Definition at line 233 of file sound_orchestrator.cpp.
{
    if (mStateEnteredAtMs == 0) mStateEnteredAtMs = nowMs;
    const SoundState newState = classify(nowMs);
    if (newState != mState) {
        mState = newState;
        mStateEnteredAtMs = nowMs;
    }
    switchAnimationIfNeeded(mState, nowMs);
    float speed;
    switch (mState) {
    case SoundState::Silence:      speed = driveSilence(nowMs, manualSpeedScalar);      break;
    case SoundState::Disorganized: speed = driveDisorganized(nowMs, manualSpeedScalar); break;
    case SoundState::BpmLocked:    speed = driveBpmLocked(nowMs, manualSpeedScalar);    break;
    default:                       speed = manualSpeedScalar;                            break;
    }
    if (mEngine) mEngine->setSpeed(speed);
    mLastEngineSpeed = speed;
    return speed;
}
References animartrix_ring::BpmLocked, classify(), animartrix_ring::Disorganized, driveBpmLocked(), driveDisorganized(), driveSilence(), mEngine, mLastEngineSpeed, mState, mStateEnteredAtMs, animartrix_ring::Silence, speed, and switchAnimationIfNeeded().