FastLED: CreateXYPaths
CreateXYPaths()
fl::vector< XYPathPtr > CreateXYPaths (int width, int height)
Definition at line 31 of file xypaths.cpp.
{
    fl::vector<XYPathPtr> out;
    out.push_back(XYPath::NewCirclePath(width, height));
    out.push_back(XYPath::NewRosePath(width, height));
    out.push_back(XYPath::NewHeartPath(width, height));
    out.push_back(XYPath::NewArchimedeanSpiralPath(width, height));
    out.push_back(XYPath::NewPhyllotaxisPath(width, height));
    out.push_back(XYPath::NewGielisCurvePath(width, height));
    out.push_back(XYPath::NewCatmullRomPath(width, height, make_path(width, height)));
    return out;
}
References anonymous_namespace{xypaths.cpp}::make_path(), fl::XYPath::NewArchimedeanSpiralPath(), fl::XYPath::NewCatmullRomPath(), fl::XYPath::NewCirclePath(), fl::XYPath::NewGielisCurvePath(), fl::XYPath::NewHeartPath(), fl::XYPath::NewPhyllotaxisPath(), fl::XYPath::NewRosePath(), and fl::HeapVector< T >::push_back().