"""One registry for FastLED's opt-in board CI labels and generated job gates.

Run through ``bash ci-labels``.  The board wrappers remain the executable
source of board arguments; this module derives labels from those wrappers and
checks that their generated guards have not drifted from the catalog.
"""

import argparse
import json
import os
from dataclasses import dataclass
from pathlib import Path

import yaml
from running_process import RunningProcess


ROOT = Path(__file__).resolve().parent.parent
WORKFLOWS = ROOT / ".github" / "workflows"
PREFIXES = ("esp", "teensy", "attiny", "samd", "stm", "nrf", "rp")
TEST_WORKFLOWS = {
    "qemu_esp32c3_test.yml": ("ci-test:qemu*", "esp32c3"),
    "qemu_esp32dev_test.yml": ("ci-test:qemu*", "esp32dev"),
    "qemu_esp32s3_test.yml": ("ci-test:qemu*", "esp32s3"),
    "build_wasm.yml": ("ci-test:wasm", "wasm"),
    "build_wasm_compilers.yml": ("ci-test:wasm", "wasm"),
    "bloat_regression_esp32s3.yml": ("ci-test:bloat", "esp32s3"),
    "avr8js_uno_test.yml": ("ci-test:avr8js", "uno"),
}
# Host-only mode labels. `ci-platforms-unit-test` runs the full native unit
# suites (Linux, Windows, Intel + Apple Silicon macOS), the full Python suite
# and the host example suites without any board, QEMU, bloat or WASM job; its
# gates are hand-written in the native workflows. `ci-platforms-wasm` is an
# alias of the `ci-test:wasm` family and selects only the WASM tests.
HOST_MODE_LABELS = ("ci-platforms-unit-test",)
FAMILY_ALIASES = {"ci-test:wasm": ("ci-platforms-wasm",)}
EVENTS = "  pull_request:\n    types: [opened, synchronize, reopened, labeled, unlabeled]\n    branches: [master]\n"
MARKER = "    # Generated by bash ci-labels sync; verify with bash ci-labels check.\n"


def board_jobs(root: Path = ROOT) -> dict[str, dict[str, str]]:
    """Map workflow/job to its canonical fbuild board ID."""
    result: dict[str, dict[str, str]] = {}
    for path in sorted((root / ".github" / "workflows").glob("*.yml")):
        data = yaml.load(path.read_text(encoding="utf-8"), Loader=yaml.BaseLoader)
        events = data.get("on", {}) if isinstance(data, dict) else {}
        if "push" not in events and "pull_request" not in events:
            continue
        jobs = data.get("jobs", {}) if isinstance(data, dict) else {}
        for job_id, job in jobs.items():
            if not isinstance(job, dict) or "build_template" not in job.get("uses", ""):
                continue
            values = job.get("with", {})
            board = values.get("board") or values.get("args", "").split(" ", 1)[0]
            if not board or "${{" in board:
                raise ValueError(f"{path.name}/{job_id} has no literal board ID")
            result.setdefault(path.name, {})[job_id] = board
    return result


def test_jobs(root: Path = ROOT) -> dict[str, dict[str, str]]:
    result: dict[str, dict[str, str]] = {}
    for filename, (label, board) in TEST_WORKFLOWS.items():
        path = root / ".github" / "workflows" / filename
        data = yaml.load(path.read_text(encoding="utf-8"), Loader=yaml.BaseLoader)
        result[filename] = {job: f"{label}|{board}" for job in data["jobs"]}
    return result


def catalog(jobs: dict[str, dict[str, str]]) -> dict[str, list[str]]:
    by_board: dict[str, set[str]] = {}
    for workflow, entries in jobs.items():
        for job, board in entries.items():
            if board.startswith("ci-test:"):
                board = board.split("|", 1)[1]
            by_board.setdefault(board, set()).add(f"{workflow}/{job}")
    labels = {
        f"ci-platform:{board}": sorted(cells) for board, cells in by_board.items()
    }
    for prefix in PREFIXES:
        cells = {
            cell
            for board, found in by_board.items()
            if board.startswith(prefix)
            for cell in found
        }
        if cells:
            labels[f"ci-platform:{prefix}*"] = sorted(cells)
    for workflow, entries in jobs.items():
        for job, selector in entries.items():
            if selector.startswith("ci-test:"):
                labels.setdefault(selector.split("|", 1)[0], []).append(
                    f"{workflow}/{job}"
                )
    for family, aliases in FAMILY_ALIASES.items():
        for alias in aliases:
            if family in labels:
                labels[alias] = list(labels[family])
    for label in labels:
        labels[label] = sorted(labels[label])
    return dict(sorted(labels.items()))


def expand(label: str, labels: dict[str, list[str]]) -> list[str]:
    if label not in labels:
        raise ValueError(
            f"unknown or empty CI label: {label}; run bash ci-labels list --json"
        )
    return labels[label]


@dataclass(frozen=True)
class Selection:
    mode: str
    sha: str
    cells: list[str]


def select(event_name: str, event: dict, labels: dict[str, list[str]]) -> Selection:
    """Resolve one event; the YAML gates are generated from this catalog."""
    if event_name == "workflow_dispatch":
        # Manually dispatching the validator does not launch the matrix.
        return Selection("manual-catalog", event.get("after", ""), [])
    if event_name == "push":
        return Selection("minimal", event.get("after", ""), [])
    if event_name != "pull_request":
        raise ValueError(f"unsupported event: {event_name}")
    pr = event["pull_request"]
    sha = pr["head"]["sha"]
    names = {item["name"] for item in pr.get("labels", [])}
    unknown = sorted(
        item
        for item in names
        if (
            item.startswith(("ci-platform:", "ci-test:", "ci-platforms-"))
            and item not in labels
            and item not in HOST_MODE_LABELS
        )
    )
    if unknown:
        raise ValueError("unknown CI labels: " + ", ".join(unknown))
    if pr["head"]["repo"]["full_name"] != event["repository"]["full_name"]:
        return Selection("fork-blocked", sha, [])
    if "ci-full" in names:
        return Selection("full", sha, sorted({c for v in labels.values() for c in v}))
    requested = sorted(
        {cell for name in names if name in labels for cell in labels[name]}
    )
    return Selection("selected" if requested else "minimal", sha, requested)


def gate(board: str, labels: dict[str, list[str]]) -> str:
    family = None
    if board.startswith("ci-test:"):
        family, board = board.split("|", 1)
    candidates = ([family, *FAMILY_ALIASES.get(family, ())] if family else []) + [
        f"ci-platform:{board}"
    ]
    candidates += [
        f"ci-platform:{prefix}*" for prefix in PREFIXES if board.startswith(prefix)
    ]
    for candidate in candidates:
        if candidate not in labels:
            raise ValueError(f"missing registry label {candidate}")
    tests = ["contains(github.event.pull_request.labels.*.name, 'ci-full')"]
    tests += [
        f"contains(github.event.pull_request.labels.*.name, '{item}')"
        for item in candidates
    ]
    return (
        MARKER
        + "    if: >-\n"
        + "      github.event_name == 'workflow_dispatch' ||\n"
        + "      (github.event_name == 'pull_request' &&\n"
        + "       github.event.pull_request.head.repo.full_name == github.repository &&\n"
        + "       ("
        + " ||\n        ".join(tests)
        + "))\n"
    )


def rendered(path: Path, entries: dict[str, str], labels: dict[str, list[str]]) -> str:
    """Mechanically update only event and job-gate blocks, retaining hand edits."""
    source = path.read_text(encoding="utf-8")
    lines = source.splitlines(keepends=True)
    on_start = next(i for i, line in enumerate(lines) if line == "on:\n")
    on_end = next(
        i
        for i in range(on_start + 1, len(lines))
        if lines[i] and not lines[i][0].isspace()
    )
    event_start = next(
        (i for i in range(on_start + 1, on_end) if lines[i] == "  pull_request:\n"),
        None,
    )
    if event_start is not None:
        event_end = next(
            (
                i
                for i in range(event_start + 1, on_end)
                if lines[i].startswith("  ")
                and not lines[i].startswith("    ")
                and lines[i].strip()
            ),
            on_end,
        )
        lines[event_start:event_end] = EVENTS.splitlines(keepends=True)
    else:
        lines[on_end:on_end] = EVENTS.splitlines(keepends=True)
    source = "".join(lines)
    for job_id, board in entries.items():
        lines = source.splitlines(keepends=True)
        job_start = next(
            i
            for i, line in enumerate(lines)
            if line == f"  {job_id}:\n"
            and i > next(j for j, x in enumerate(lines) if x == "jobs:\n")
        )
        job_end = next(
            (
                i
                for i in range(job_start + 1, len(lines))
                if lines[i].startswith("  ")
                and not lines[i].startswith("    ")
                and lines[i].strip()
            ),
            len(lines),
        )
        old_marker = next(
            (i for i in range(job_start + 1, job_end) if lines[i] == MARKER), None
        )
        if old_marker is not None:
            old_if = old_marker + 1
        else:
            old_if = next(
                (
                    i
                    for i in range(job_start + 1, job_end)
                    if lines[i].startswith("    if:")
                ),
                None,
            )
        if old_if is not None:
            old_end = next(
                (
                    i
                    for i in range(old_if + 1, job_end)
                    if lines[i].startswith("    ")
                    and not lines[i].startswith("      ")
                    and lines[i].strip()
                ),
                job_end,
            )
            lines[old_marker if old_marker is not None else old_if : old_end] = []
        insert = next(
            i
            for i in range(job_start + 1, job_end)
            if lines[i].startswith(("    uses:", "    runs-on:"))
        )
        lines[insert:insert] = gate(board, labels).splitlines(keepends=True)
        source = "".join(lines)
    return source


def github_labels(repo: str) -> set[str]:
    result = RunningProcess.run(
        ["gh", "label", "list", "-R", repo, "--limit", "500", "--json", "name"],
        capture_output=True,
        encoding="utf-8",
        errors="replace",
        timeout=30,
    )
    return {item["name"] for item in json.loads(result.stdout)}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "command",
        choices=(
            "list",
            "expand",
            "select",
            "check",
            "sync",
            "labels-check",
            "labels-sync",
        ),
    )
    parser.add_argument("label", nargs="?")
    parser.add_argument("--json", action="store_true")
    parser.add_argument("--event-file", type=Path)
    parser.add_argument("--event-name")
    parser.add_argument("--repo", default="FastLED/FastLED")
    args = parser.parse_args()
    boards = board_jobs()
    jobs = boards | test_jobs()
    labels = catalog(jobs)
    from ci.boards import _BOARD_MAP

    unknown_boards = sorted(
        {board for entries in boards.values() for board in entries.values()}
        - set(_BOARD_MAP)
    )
    if unknown_boards:
        raise SystemExit(
            "board wrappers missing from ci/boards.py: " + ", ".join(unknown_boards)
        )
    if args.command == "list":
        print(json.dumps(labels, indent=2) if args.json else "\n".join(labels))
    elif args.command == "expand":
        print(json.dumps(expand(args.label or "", labels), indent=2))
    elif args.command == "select":
        if not args.event_file:
            parser.error("select requires --event-file")
        event = json.loads(args.event_file.read_text(encoding="utf-8"))
        result = select(
            args.event_name or os.environ.get("GITHUB_EVENT_NAME", ""), event, labels
        )
        print(
            json.dumps(
                {"mode": result.mode, "head_sha": result.sha, "cells": result.cells}
            )
        )
    elif args.command in ("labels-check", "labels-sync"):
        missing = sorted(
            (set(labels) | set(HOST_MODE_LABELS)) - github_labels(args.repo)
        )
        if args.command == "labels-check" and missing:
            raise SystemExit(
                "missing GitHub labels: "
                + ", ".join(missing)
                + "; run bash ci-labels labels-sync"
            )
        for name in missing:
            RunningProcess.run(
                [
                    "gh",
                    "label",
                    "create",
                    name,
                    "-R",
                    args.repo,
                    "--color",
                    "2563EB",
                    "--description",
                    "Select FastLED board CI cells",
                ],
                capture_output=True,
                encoding="utf-8",
                errors="replace",
                timeout=30,
            )
        print(f"{len(labels)} valid CI labels; {len(missing)} created")
    else:
        stale = []
        for filename, entries in jobs.items():
            path = WORKFLOWS / filename
            expected = rendered(path, entries, labels)
            if expected != path.read_text(encoding="utf-8"):
                stale.append(filename)
                if args.command == "sync":
                    path.write_text(expected, encoding="utf-8")
        if args.command == "check" and stale:
            raise SystemExit(
                "stale board CI gates: "
                + ", ".join(stale)
                + "; run bash ci-labels sync"
            )
        print(
            f"{len(jobs)} board workflows, {sum(map(len, jobs.values()))} jobs, {len(labels)} labels; {len(stale)} updated"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
