FastLED: setup
setup()
void setup ()
Definition at line 115 of file simple.h.
             {
    Serial.begin(115200);
    // auto screenmap = frameBufferXY.toScreenMap();
    // screenmap.setDiameter(.2);
    // FastLED.addLeds<NEOPIXEL, 2>(framebuffer,
    // NUM_LEDS).setScreenMap(screenmap);
    auto screenmap = ledsXY.toScreenMap();
    screenmap.setDiameter(.2);
    decayTimeSeconds.onChanged([](float value) {
        audioFadeTracker.setDecayTime(value);
        FL_WARN("Fade time seconds: " << value);
    });
    attackTimeSeconds.onChanged([](float value) {
        audioFadeTracker.setAttackTime(value);
        FL_WARN("Attack time seconds: " << value);
    });
    outputTimeSec.onChanged([](float value) {
        audioFadeTracker.setOutputTime(value);
        FL_WARN("Output time seconds: " << value);
    });
    // Initialize pitch detection
    pitchConfig.sample_rate_hz = 44100.0f;
    pitchEngine = new fl::SoundToMIDIEngine(pitchConfig);  // ok bare allocation
    pitchEngine->onNoteOn = [](uint8_t note, uint8_t velocity) {
        currentMIDINote = note;
        noteIsOn = true;
        Serial.print("Note ON: ");
        Serial.print(note);
        Serial.print(" vel: ");
        Serial.println(velocity);
    };
    pitchEngine->onNoteOff = [](uint8_t note) {
        noteIsOn = false;
        Serial.print("Note OFF: ");
        Serial.println(note);
    };
    FastLED.addLeds<NEOPIXEL, PIN_DATA>(leds, ledsXY.getTotal())
        .setScreenMap(screenmap);
}
References attackTimeSeconds(), audioFadeTracker(), currentMIDINote, decayTimeSeconds(), FastLED, FL_WARN, leds, ledsXY(), noteIsOn, outputTimeSec(), PIN_DATA, pitchConfig, pitchEngine, screenmap, and Serial.