FastLED: loop
loop()
void loop ()
Definition at line 188 of file simple.h.
            {
    if (triggered) {
        FL_WARN("Triggered");
    }
    // x = pointX.as_int();
    y = HEIGHT / 2;
    bool do_frame = doFrame();
    while (fl::audio::Sample sample = audio.next()) {
        if (!do_frame) {
            continue;
        }
        // Process pitch detection if enabled
        if (enablePitchDetect && pitchEngine) {
            // Convert int16_t samples to float for pitch detection
            static float floatBuffer[512];
            size_t numSamples = fl::min(sample.pcm().size(), (size_t)512);
            for (size_t i = 0; i < numSamples; i++) {
                floatBuffer[i] = sample.pcm()[i] / 32768.0f;
            }
            pitchEngine->processFrame(floatBuffer, numSamples);
        }
        float fade = audioFadeTracker(sample.pcm().data(), sample.pcm().size());
        shiftUp();
        // FL_WARN("Audio sample size: " << sample.pcm().size());
        soundLevelMeter.processBlock(sample.pcm());
        // FL_WARN("")
        auto dbfs = soundLevelMeter.getDBFS();
        FASTLED_UNUSED(dbfs);
        // FL_WARN("getDBFS: " << dbfs);
        int32_t max = 0;
        for (size_t i = 0; i < sample.pcm().size(); ++i) {
            int32_t x = ABS(sample.pcm()[i]);
            if (x > max) {
                max = x;
            }
        }
        float anim =
            fl::map_range<float, float>(max, 0.0f, 32768.0f, 0.0f, 1.0f);
        anim = fl::clamp(anim, 0.0f, 1.0f);
        x = fl::map_range<float, float>(anim, 0.0f, 1.0f, 0.0f, WIDTH - 1);
        // FL_WARN("x: " << x);
        // fft.run(sample.pcm(), &fftOut);
        sample.fft(&fftOut);
        if (enableFFT) {
            auto max_x = fftOut.raw().size() - 1;
            FASTLED_UNUSED(max_x);
            for (size_t i = 0; i < fftOut.raw().size(); ++i) {
                auto x = i;
                auto v = fftOut.db()[i];
                // Map audio intensity to a position in the heat palette (0-255)
                v = fl::map_range<float, float>(v, 45, 70, 0, 1.f);
                v = fl::clamp(v, 0.0f, 1.0f);
                uint8_t heatIndex =
                    fl::map_range<float, uint8_t>(v, 0, 1, 0, 255);
                // FL_WARN(v);
                // Use FastLED's built-in HeatColors palette
                auto c = ColorFromPalette(HeatColors_p, heatIndex);
                c.fadeToBlackBy(255 - heatIndex);
                framebuffer[frameBufferXY(x, 0)] = c;
                // FL_WARN("y: " << i << " b: " << b);
            }
        }
        if (enableVolumeVis) {
            framebuffer[frameBufferXY(x, HEIGHT / 2)] = fl::CRGB(0, 255, 0);
        }
        if (enableRMS) {
            float rms = sample.rms();
            FL_WARN("RMS: " << rms);
            rms = fl::map_range<float, float>(rms, 0.0f, 32768.0f, 0.0f, 1.0f);
            rms = fl::clamp(rms, 0.0f, 1.0f) * WIDTH;
            framebuffer[frameBufferXY(rms, HEIGHT * 3 / 4)] = fl::CRGB(0, 0, 255);
        }
        // Display pitch detection result
        if (enablePitchDetect && noteIsOn) {
            // Map MIDI note to position (common range: 40-88)
            float notePos = fl::map_range<float, float>(currentMIDINote, 40.0f, 88.0f, 0.0f, 1.0f);
            notePos = fl::clamp(notePos, 0.0f, 1.0f);
            uint16_t note_x = notePos * (WIDTH - 1);
            uint16_t h = HEIGHT / 8;
            // magenta color for pitch
            framebuffer[frameBufferXY(note_x, h)] = fl::CRGB(255, 0, 255);
        }
        if (true) {
            uint16_t fade_width = fade * (WIDTH - 1);
            uint16_t h = HEIGHT / 4;
            // yellow
            int index = frameBufferXY(fade_width, h);
            auto c = fl::CRGB(255, 255, 0);
            framebuffer[index] = c;
        }
    }
    // now downscale the framebuffer to the led matrix
    downscale(framebuffer, frameBufferXY, leds, ledsXY);
    FastLED.show();
}
References audio, audioFadeTracker(), fl::clamp(), ColorFromPalette(), currentMIDINote, doFrame(), enableFFT(), enablePitchDetect(), enableRMS(), enableVolumeVis(), FastLED, FASTLED_UNUSED, fftOut(), FL_WARN, framebuffer, frameBufferXY(), HeatColors_p, HEIGHT, leds, ledsXY(), fl::map_range(), max(), fl::min(), noteIsOn, pitchEngine, rms(), shiftUp(), soundLevelMeter(), triggered, WIDTH, x, and y.