FastLED: rms
rms()
float rms (fl::span< const int16_t > data)
Definition at line 104 of file simple.h.
{
    double sumSq = 0.0;
    const int N = data.size();
    for (int i = 0; i < N; ++i) {
        int32_t x32 = int32_t(data[i]);
        sumSq += x32 * x32;
    }
    float rms = fl::sqrt(float(sumSq) / N);
    return rms;
}
References rms(), fl::span< T, Extent >::size(), and fl::sqrt().
Referenced by fl::audio::detector::MoodAnalyzer::calculateArousal(), fl::audio::detector::BuildupDetector::calculateBuildupIntensity(), fl::audio::detector::DropDetector::calculateDropImpact(), drawVUMeter(), loop(), fl::audio::Processor::onEnergy(), fl::audio::Reactive::processSample(), rms(), fl::audio::detector::BuildupDetector::update(), fl::audio::detector::DropDetector::update(), fl::audio::detector::EqualizerDetector::update(), fl::audio::detector::DropDetector::updateBaselines(), fl::audio::detector::DynamicsAnalyzer::updatePeak(), and fl::audio::Reactive::updateVolumeAndPeak().