FastLED: fl::Vorbis::decodeAll
decodeAll()
fl::vector< audio::Sample > fl::Vorbis::decodeAll (fl::span< const fl::u8 > data, fl::string * errorMessage = nullptr) static
Definition at line 276 of file vorbis.cpp.hpp.
{
    fl::vector<audio::Sample> samples;
    StbVorbisDecoder decoder;
    if (!decoder.openMemory(data)) {
        if (errorMessage) *errorMessage = "Failed to open Vorbis stream";
        return samples;
    }
    VorbisInfo info = decoder.getInfo();
    const fl::i32 channels = info.channels > 0 ? info.channels : 1;
    constexpr fl::i32 FRAME_SIZE = 1024;
    fl::vector<fl::i16> buffer(FRAME_SIZE * 2);
    while (true) {
        fl::i32 samplesDecoded = decoder.getSamplesShortInterleaved(
            channels, buffer.data(), static_cast<fl::i32>(buffer.size())
        );
        if (samplesDecoded == 0) break;
        // Convert stereo to mono
        if (channels == 2) {
            fl::vector<fl::i16> mono;
            mono.reserve(samplesDecoded);
            for (fl::i32 i = 0; i < samplesDecoded; ++i) {
                fl::i32 left = buffer[i * 2];
                fl::i32 right = buffer[i * 2 + 1];
                mono.push_back(static_cast<fl::i16>((left + right) / 2));
            }
            samples.push_back(audio::Sample(mono));
        } else {
            samples.push_back(audio::Sample(fl::span<const fl::i16>(buffer.data(), samplesDecoded)));
        }
    }
    return samples;
}
References fl::VorbisInfo::channels, fl::vector< T >::data(), fl::StbVorbisDecoder::getInfo(), fl::StbVorbisDecoder::getSamplesShortInterleaved(), fl::StbVorbisDecoder::openMemory(), fl::vector< T >::push_back(), fl::vector< T >::reserve(), and fl::vector_basic::size().