FastLED: blend
blend()
CRGB fl::blend (const CRGB & p1, const CRGB & p2, fract8 amountOfP2)
Examples
TwinkleFox.ino.
Definition at line 60 of file colorutils.cpp.
{
    CRGB nu(p1);
    nblend(nu, p2, amountOfP2);
    return nu;
}
Referenced by drawTwinkles(), fill_2dnoise16(), fill_2dnoise8(), and fill_raw_2dnoise16into8().