FastLED: test_promise_approach
test_promise_approach()
void test_promise_approach ()
Definition at line 109 of file NetTestReal.h.
{
    FL_WARN("APPROACH 1: Promise-based pattern with explicit types");
    // TUTORIAL: fetch_get() returns fl::promise<fl::response> (not auto!)
    // The promise represents a future HTTP response that may succeed or fail
    // Chain .then() for success handling and the lambda receives a
    // const fl::response& when the fetch succeeds. error_ will handle network device
    // failures (no connection, DNS failure, etc, but not HTTP errors like 404, 500, etc.)
    fl::fetch_get("http://fastled.io").then([](const fl::response& response) {
        // TUTORIAL: Check if HTTP request was successful
        if (response.ok()) {
            FL_WARN("SUCCESS [Promise] HTTP fetch successful! Status: "
                    << response.status() << " " << response.status_text());
            // TUTORIAL: get_content_type() returns fl::optional<fl::string>
            // Optional types may or may not contain a value - always check!
            fl::optional<fl::string> content_type = response.get_content_type();
            if (content_type.has_value()) {
                FL_WARN("CONTENT [Promise] Content-Type: " << *content_type);
            }
            // TUTORIAL: response.text() returns fl::string with response body
            const fl::string& response_body = response.text();
            if (response_body.length() >= 100) {
                FL_WARN("RESPONSE [Promise] First 100 characters: " << response_body.substr(0, 100));
            } else {
                FL_WARN("RESPONSE [Promise] Full response (" << response_body.length()
                                         << " chars): " << response_body);
            }
            // Visual feedback: Green LEDs indicate promise-based success
            fill_solid(leds, NUM_LEDS, CRGB(0, 64, 0)); // Green for promise success
        } else {
            // HTTP error (like 404, 500, etc.) - still a valid response, just an error status
            FL_WARN("ERROR [Promise] HTTP Error! Status: "
                    << response.status() << " " << response.status_text());
            FL_WARN("CONTENT [Promise] Error content: " << response.text());
            // Visual feedback: Orange LEDs indicate HTTP error
            fill_solid(leds, NUM_LEDS, CRGB(64, 32, 0)); // Orange for HTTP error
        }
    })
    // TUTORIAL: Chain .catch_() for network/connection error handling
    // The lambda receives a const fl::Error& when the fetch fails completely
    .catch_([](const fl::Error& network_error) {
        // Network error (no connection, DNS failure, etc.)
        FL_WARN("ERROR [Promise] Network Error: " << network_error.message);
        // Visual feedback: Red LEDs indicate network failure
        fill_solid(leds, NUM_LEDS, CRGB(64, 0, 0)); // Red for network error
    });
}
References fl::fetch_get(), fl::fill_solid(), FL_WARN, fl::response::get_content_type(), fl::Optional< T >::has_value(), leds, fl::StrN< SIZE >::length(), fl::Error::message, NUM_LEDS, fl::response::ok(), fl::response::status(), fl::response::status_text(), fl::StrN< SIZE >::substr(), and fl::response::text().
Referenced by loop().