FastLED: loop
loop()
void loop ()
Definition at line 358 of file NetTestReal.h.
            {
    // TUTORIAL: Cycle between different async approaches every 10 seconds
    // This allows you to see both promise-based and await-based patterns in action
    // The LEDs provide visual feedback about which approach succeeded
    unsigned long current_time = millis();
    // Switch approaches every 10 seconds
    // 4 different approaches: Promise, Await, JSON Promise, JSON Await
    if (current_time - last_request_time >= 10000) {
        last_request_time = current_time;
        // Cycle through 4 different approaches
        if (approach_counter % 4 == 0) {
            test_promise_approach();
            FL_WARN("CYCLE: Demonstrated Promise-based pattern (Green LEDs on success)");
        } else if (approach_counter % 4 == 1) {
            test_await_approach();
            FL_WARN("CYCLE: Demonstrated Await-based pattern (Blue LEDs on success)");
        } else if (approach_counter % 4 == 2) {
            test_json_response();
            FL_WARN("CYCLE: Demonstrated JSON Promise pattern (Blue LEDs on success)");
        } else if (approach_counter % 4 == 3) {
            test_json_await();
            FL_WARN("CYCLE: Demonstrated JSON Await pattern (Cyan LEDs on success)");
        }
        approach_counter++;
        FL_WARN("NEXT: Will switch to next approach in 10 seconds...");
    }
    // TUTORIAL NOTE: Async operations are automatically managed!
    // * On WASM: delay() pumps async tasks every 1ms automatically
    // * On all platforms: FastLED.show() triggers async updates via engine events
    // * No manual async updates needed - everything happens behind the scenes!
    // TUTORIAL: This delay automatically pumps async tasks on WASM!
    // The delay is broken into 1ms chunks with async processing between chunks.
    // This isn't necessary when calling the await approach, but is critical
    // the standard promise.then() approach.
    // Note: In the future loop() may become a macro to inject auto pumping
    // of the async tasks.
    delay(10);
}
References approach_counter, FL_WARN, last_request_time, test_await_approach(), test_json_await(), test_json_response(), and test_promise_approach().