FastLED: test_json_response
test_json_response()
void test_json_response ()
APPROACH 3: JSON Response Handling with FastLED's ideal JSON API This demonstrates fetch responses with automatic JSON parsing.
Definition at line 221 of file NetTestReal.h.
{
    FL_WARN("APPROACH 3: JSON Response handling with fl::Json integration");
    // TUTORIAL: Fetch a JSON API endpoint (httpbin.org provides test JSON)
    // This endpoint returns JSON with request information
    fl::fetch_get("https://httpbin.org/json").then([](const fl::response& response) {
        if (response.ok()) {
            FL_WARN("SUCCESS [JSON Promise] HTTP fetch successful! Status: "
                    << response.status() << " " << response.status_text());
            // TUTORIAL: Check if response contains JSON content
            // is_json() checks Content-Type header and body content
            if (response.is_json()) {
                FL_WARN("DETECTED [JSON Promise] Response contains JSON data");
                // TUTORIAL: response.json() returns fl::Json with FastLED's ideal API
                // Automatic parsing, caching, and safe access with defaults using operator|
                fl::Json data = response.json();
                // TUTORIAL: Safe JSON access with defaults - never crashes!
                // Uses FastLED's proven pattern: json["path"]["to"]["key"] | default_value
                fl::string slideshow_url = data["slideshow"]["author"] | fl::string("unknown");
                fl::string slideshow_title = data["slideshow"]["title"] | fl::string("untitled");
                int slide_count = data["slideshow"]["slides"].size();
                FL_WARN("JSON [Promise] Slideshow Author: " << slideshow_url);
                FL_WARN("JSON [Promise] Slideshow Title: " << slideshow_title);
                FL_WARN("JSON [Promise] Slide Count: " << slide_count);
                // TUTORIAL: Access nested arrays safely
                if (data.contains("slideshow") && data["slideshow"].contains("slides")) {
                    fl::Json slides = data["slideshow"]["slides"];
                    if (slides.is_array() && slides.size() > 0) {
                        // Get first slide information with safe defaults
                        fl::string first_slide_title = slides[0]["title"] | fl::string("no title");
                        fl::string first_slide_type = slides[0]["type"] | fl::string("unknown");
                        FL_WARN("JSON [Promise] First slide: " << first_slide_title << " (" << first_slide_type << ")");
                    }
                }
                // Visual feedback: Blue LEDs for successful JSON parsing
                fill_solid(leds, NUM_LEDS, CRGB(0, 0, 128)); // Blue for JSON success
            } else {
                FL_WARN("INFO [JSON Promise] Response is not JSON format");
                // Visual feedback: Yellow for non-JSON response
                fill_solid(leds, NUM_LEDS, CRGB(64, 64, 0)); // Yellow for non-JSON
            }
        } else {
            FL_WARN("ERROR [JSON Promise] HTTP error: " << response.status()
                    << " " << response.status_text());
            // Visual feedback: Red LEDs for HTTP error
            fill_solid(leds, NUM_LEDS, CRGB(64, 0, 0)); // Red for HTTP error
        }
    }).catch_([](const fl::Error& error) {
        FL_WARN("ERROR [JSON Promise] Network error: " << error.message);
        // Visual feedback: Purple LEDs for network error
        fill_solid(leds, NUM_LEDS, CRGB(64, 0, 64)); // Purple for network error
    });
    FastLED.show();
}
References fl::Json::contains(), FastLED, fl::fetch_get(), fl::fill_solid(), FL_WARN, fl::Json::is_array(), fl::response::is_json(), fl::response::json(), leds, fl::Error::message, NUM_LEDS, fl::response::ok(), fl::Json::size(), fl::response::status(), and fl::response::status_text().
Referenced by loop().