FastLED: fl::ease8
ease8() [1/2]
void fl::ease8 (EaseType type, u8 * src, u8 * dst, u8 count) inline
Definition at line 224 of file ease.h.
{
    switch (type) {
        case EaseType::EASE_NONE: return;
        case EaseType::EASE_IN_QUAD: {
            for (u8 i = 0; i < count; i++) {
                dst[i] = easeInQuad8(src[i]);
            }
            break;
        }
        case EaseType::EASE_OUT_QUAD: {
            for (u8 i = 0; i < count; i++) {
                dst[i] = easeOutQuad8(src[i]);
            }
            break;
        }
        case EaseType::EASE_IN_OUT_QUAD: {
            for (u8 i = 0; i < count; i++) {
                dst[i] = easeInOutQuad8(src[i]);
            }
            break;
        }
        case EaseType::EASE_IN_CUBIC: {
            for (u8 i = 0; i < count; i++) {
                dst[i] = easeInCubic8(src[i]);
            }
            break;
        }
        case EaseType::EASE_OUT_CUBIC: {
            for (u8 i = 0; i < count; i++) {
                dst[i] = easeOutCubic8(src[i]);
            }
            break;
        }
        case EaseType::EASE_IN_OUT_CUBIC: {
            for (u8 i = 0; i < count; i++) {
                dst[i] = easeInOutCubic8(src[i]);
            }
            break;
        }
        case EaseType::EASE_IN_SINE: {
            for (u8 i = 0; i < count; i++) {
                dst[i] = easeInSine8(src[i]);
            }
            break;
        }
        case EaseType::EASE_OUT_SINE: {
            for (u8 i = 0; i < count; i++) {
                dst[i] = easeOutSine8(src[i]);
            }
            break;
        }
        case EaseType::EASE_IN_OUT_SINE: {
            for (u8 i = 0; i < count; i++) {
                dst[i] = easeInOutSine8(src[i]);
            }
            break;
        }
    }
}
References EASE_IN_CUBIC, EASE_IN_OUT_CUBIC, EASE_IN_OUT_QUAD, EASE_IN_OUT_SINE, EASE_IN_QUAD, EASE_IN_SINE, EASE_NONE, EASE_OUT_CUBIC, EASE_OUT_QUAD, EASE_OUT_SINE, easeInCubic8(), easeInOutCubic8(), easeInOutQuad8(), easeInOutSine8(), easeInQuad8(), easeInSine8(), easeOutCubic8(), easeOutQuad8(), easeOutSine8(), and FL_NOEXCEPT.