FastLED: fl::vector_element_ops_for
vector_element_ops_for()
template<typename T> const vector_element_ops * fl::vector_element_ops_for ()
Generate a static ops table for type T.
Returns nullptr for trivially copyable types (fast path).
Definition at line 312 of file basic_vector.h.
{
    // Trivially copyable types use the fast path (mOps == nullptr)
    if (fl::is_trivially_copyable<T>::value) {
        return nullptr;
    }
    static const vector_element_ops ops = {
        detail::get_copy_construct_fn<T>(),       // copy_construct
        detail::get_move_construct_fn<T>(),       // move_construct
        [](void* ptr) { static_cast<T*>(ptr)->~T(); }, // destroy
        detail::get_default_construct_fn<T>(),    // default_construct
        detail::get_swap_fn<T>(),                 // swap_elements
        detail::get_uninitialized_move_n_fn<T>(), // uninitialized_move_n
        // destroy_n
        [](void* first, fl::size count) FL_NOEXCEPT {
            T* p = static_cast<T*>(first);
            for (fl::size i = 0; i < count; ++i) {
                p[i].~T();
            }
        }
    };
    return &ops;
}
References FL_NOEXCEPT, fl::detail::get_copy_construct_fn(), fl::detail::get_default_construct_fn(), fl::detail::get_move_construct_fn(), fl::detail::get_swap_fn(), fl::detail::get_uninitialized_move_n_fn(), and fl::fl::is_trivially_copyable< T >::value.
Referenced by fl::vector< fl::i16 >::vector(), fl::vector< fl::i16 >::vector(), fl::vector< fl::i16 >::vector(), fl::vector< fl::i16 >::vector(), fl::vector< fl::i16 >::vector(), fl::vector< fl::i16 >::vector(), fl::vector< fl::i16 >::vector(), fl::vector< fl::i16 >::vector(), fl::vector< fl::i16 >::vector(), fl::vector< fl::i16 >::vector(), fl::vector< fl::i16 >::vector(), and fl::vector< fl::i16 >::vector().