FastLED: fl::isqrt32
isqrt32()
FL_OPTIMIZE_FUNCTION constexpr u16 fl::isqrt32 (u32 x) inline constexpr
Definition at line 53 of file isqrt.h.
{
    return x == 0 ? u16(0)
                  : _isqrt32_step(x, 0, _isqrt32_start(x, u32(1) << 30));
}
References _isqrt32_start(), _isqrt32_step(), FL_NOEXCEPT, FL_OPTIMIZE_FUNCTION, and x.
Referenced by fl::gfx::detail::drawStrokeLineCore(), fl::s12x4::sqrt(), fl::s4x12::sqrt(), fl::s8x8::sqrt(), fl::u12x4::sqrt(), fl::u4x12::sqrt(), fl::u8x8::sqrt(), and fl::fixed_point_base< Derived, IntBits, FracBits >::sqrt_impl().