FastLED: fl Namespace Reference
fl Namespace Reference
Detailed Description
Implements a simple red square effect for 2D LED grids.
Namespaces
namespace anonymous_namespace{allocator.cpp}
namespace anonymous_namespace{blur.cpp}
namespace anonymous_namespace{five_bit_hd_gamma.cpp}
namespace anonymous_namespace{frame_tracker.cpp}
namespace anonymous_namespace{gradient.cpp}
namespace anonymous_namespace{line_simplification.cpp}
namespace anonymous_namespace{noise_woryley.cpp}
namespace anonymous_namespace{pir.cpp}
namespace anonymous_namespace{wave.cpp}
namespace anonymous_namespace{xypath.cpp}
namespace anonymous_namespace{xypath_renderer.cpp}
namespace map_range_detail
namespace string_functions
namespace wave_detail
namespace xypath_detail
Classes
struct _DrawContext
struct add_pointer
struct add_pointer< T & >
struct add_pointer< T && >
class Animartrix
struct AnimartrixEntry
################################################## Details with the implementation of Animartrix
class ArchimedeanSpiralPath
class array
A fixed-size array implementation similar to std::array.
struct ArrayDeleter
class AudioSample
class AudioSampleImpl
class bitset_dynamic
A dynamic bitset implementation that can be resized at runtime.
class BitsetFixed
A simple fixed-size Bitset implementation similar to std::Bitset.
class BitsetInlined
A Bitset implementation with inline storage that can grow if needed.
class Blend2d
struct Blend2dParams
class ByteStream
class ByteStreamMemory
class CatmullRomParams
class CatmullRomPath
Catmull–Rom spline through arbitrary points.
class CirclePath
class CircularBuffer
struct conditional
struct conditional< false, T, F >
struct contains_type
struct contains_type< T >
struct contains_type< T, U, Rest... >
class Cylon
An animation that moves a single LED back and forth (Larson Scanner effect)
struct decay
struct DefaultLess
class DemoReel100
class DigitalPin
class DigitalPinImpl
struct DrawItem
struct Empty
struct enable_if
struct enable_if< true, T >
class EngineEvents
struct EqualTo
class FakeStrStream
struct FastHash
struct FastHash< vec2< T > >
class FastLEDANIMartRIX
class FFT
struct FFT_Args
struct FFTBins
class FFTContext
class FFTImpl
class FileHandle
class FileSystem
class Fire2012
class FixedMap
class FixedSet
class FixedVector
class Frame
class FrameInterpolator
class FrameTracker
class FsImpl
class function
class function< R(Args...)>
class FunctionList
class FunctionList< void >
class FunctionListBase
class Fx
class Fx1d
class Fx2d
class FxCompositor
class FxEngine
Manages and renders multiple visual effects (Fx) for LED strips.
class FxLayer
class GielisCurveParams
class GielisCurvePath
class Gradient
class GradientInlined
class Grid
struct has_member_swap
struct Hash
struct Hash< FFT_Args >
struct Hash< Ptr< T > >
struct Hash< T * >
struct Hash< vec2< T > >
class HashMap
class HashMapLru
class HashSet
class HeapVector
class HeartPath
struct InlinedMemoryBlock
class InlinedVector
struct is_array
struct is_array< T[]>
struct is_array< T[N]>
struct is_base_of
struct is_base_of_v_helper
struct is_function
struct is_function< Ret(Args...) const >
struct is_function< Ret(Args...) const volatile >
struct is_function< Ret(Args...) volatile >
struct is_function< Ret(Args...)>
struct is_integral
struct is_integral< bool >
struct is_integral< char >
struct is_integral< const T >
struct is_integral< int >
struct is_integral< long >
struct is_integral< long long >
struct is_integral< short >
struct is_integral< signed char >
struct is_integral< T & >
struct is_integral< unsigned char >
struct is_integral< unsigned int >
struct is_integral< unsigned long >
struct is_integral< unsigned long long >
struct is_integral< unsigned short >
struct is_integral< volatile T >
struct is_lvalue_reference
struct is_lvalue_reference< T & >
struct is_member_function_pointer
struct is_member_function_pointer< Ret(C::*)(A...) const >
struct is_member_function_pointer< Ret(C::*)(A...)>
struct is_pod
struct is_pod< bool >
struct is_pod< char >
struct is_pod< double >
struct is_pod< float >
struct is_pod< int >
struct is_pod< long >
struct is_pod< long double >
struct is_pod< long long >
struct is_pod< short >
struct is_pod< signed char >
struct is_pod< unsigned char >
struct is_pod< unsigned int >
struct is_pod< unsigned long >
struct is_pod< unsigned long long >
struct is_pod< unsigned short >
struct is_pod_v_helper
struct is_same
struct is_same< T, T >
struct is_same_v_helper
class JsonDocument
class LargeBlockAllocator
class Leds
class LedsXY
struct less
Binary function object that returns whether the first argument is less than the second.
struct less< void >
Specialization of less for void, allowing for transparent comparisons.
struct line_xy
class LinePath
class LinePathParams
class LineSimplifier
class LineSimplifierExact
class LUT
struct Matrix3x3f
class MatrixSlice
struct max_align
struct max_align< T, Rest... >
struct max_align<>
struct max_size
struct max_size< T, Rest... >
struct max_size<>
class NoisePalette
class NoiseWave
class NullFileHandle
class NullFileSystem
class ObjectFLED
class Optional
class Pacifica
struct Pair
struct pair_xy
class PhyllotaxisParams
class PhyllotaxisPath
class Pir
class PirAdvanced
struct Pixel
union Pixel.__unnamed0__
struct Pixel.__unnamed0__.__unnamed0__
class Pixels
class PixelStream
struct PointerDeleter
class PointPath
class Pride2015
class PriorityQueue
class Ptr
class PtrTraits
struct rect
class RectangularDrawBuffer
class RedSquare
class Referent
struct remove_const
struct remove_const< const T >
struct remove_cv
struct remove_cv< const T >
struct remove_cv< const volatile T >
struct remove_cv< volatile T >
struct remove_extent
struct remove_extent< T[]>
struct remove_extent< T[N]>
struct remove_reference
struct remove_reference< T & >
struct remove_reference< T && >
class RosePath
class RosePathParams
class ScaleUp
class scoped_array
class scoped_ptr
class ScreenMap
class Singleton
class Slice
class SortedHeapMap
class SortedHeapVector
class SoundLevelMeter
class Str
class StringFormatter
class StringHolder
class StrN
class StrStream
struct StrStreamHelper
struct StrStreamHelper< char >
struct StrStreamHelper< int >
struct StrStreamHelper< uint8_t >
struct StrStreamHelper< unsigned int >
struct swap_impl
struct swap_impl< T, false >
struct swap_impl< T, true >
class ThreadLocalFake
class Tile2x2_u8
class TimeAlpha
class TimeClampedTransition
class TimeFunction
class TimeRamp
class TimeWarp
struct Transform16
struct TransformFloat
class TransformFloatImpl
class Transition
class TwinkleFox
class UIAudio
class UIAudioImpl
class UIButton
class UIButtonImpl
class UICheckbox
class UICheckboxImpl
class UIDescription
class UIDescriptionImpl
class UINumberField
class UINumberFieldImpl
class UISlider
class UISliderImpl
class UITitle
class UITitleImpl
class Variant
struct vec2
struct vec3
class Video
class VideoFxWrapper
class WaveCrgbGradientMap
class WaveCrgbMap
class WaveCrgbMapDefault
class WaveFx
struct WaveFxArgs
class WaveSimulation1D
class WaveSimulation1D_Real
class WaveSimulation2D
class WaveSimulation2D_Real
class WeakPtr
class WeakReferent
class XMap
struct XYDrawComposited
struct XYDrawGradient
class XYMap
class XYPath
class XYPathFunction
class XYPathGenerator
class XYPathParams
class XYPathRenderer
class XYRasterU8Sparse
Typedefs
template<typename T>
using add_pointer_t = typename add_pointer<T>::type
using alpha16
template<uint32_t N = 256>
using bitset = BitsetInlined<N>
template<uint32_t N>
using bitset_fixed = BitsetFixed<N>
template<bool B, typename T, typename F>
using conditional_t = typename conditional<B, T, F>::type
typedef int64_t cycle_t
8.8 fixed point (signed) value
template<typename T>
using decay_t = typename decay<T>::type
template<bool Condition, typename T = void>
using enable_if_t = typename enable_if<Condition, T>::type
template<typename T>
using equal_to = EqualTo<T>
template<typename Key, typename T, typename Hash = Hash<Key>, typename KeyEqual = equal_to<Key>>
using hash_map = HashMap<Key, T, Hash, KeyEqual>
template<typename Key, typename Hash = Hash<Key>, typename KeyEqual = EqualTo<Key>>
using hash_set = HashSet<Key, Hash, KeyEqual>
template<typename Base, typename Derived>
using is_derived = enable_if_t<is_base_of<Base, Derived>::value>
typedef LUT< uint16_t > LUT16
typedef LUT< vec2< uint16_t > > LUTXY16
typedef LUT< vec2f > LUTXYFLOAT
typedef LUT< vec3f > LUTXYZFLOAT
template<typename T>
using optional = Optional<T>
template<typename Key, typename Value>
using pair = Pair<Key, Value>
using pair_xy_float = vec2<float>
using pair_xyz_float = vec3<float>
template<typename T>
using remove_cv_t = typename remove_cv<T>::type
template<typename T>
using remove_reference_t = typename remove_reference<T>::type
using string = fl::Str
template<typename T>
using ThreadLocal = ThreadLocalFake<T>
template<typename Key, typename T, typename Hash = Hash<Key>, typename KeyEqual = equal_to<Key>>
using unordered_map = HashMap<Key, T, Hash, KeyEqual>
using vec2f = vec2<float>
using vec3f = vec3<float>
template<typename T>
using vector = HeapVector<T>
template<typename T, size_t INLINED_SIZE>
using vector_fixed = FixedVector<T, INLINED_SIZE>
template<typename T, size_t INLINED_SIZE = 64>
using vector_inlined = InlinedVector<T, INLINED_SIZE>
typedef uint16_t(* XFunction) (uint16_t x, uint16_t length)
typedef uint16_t(* XYFunction) (uint16_t x, uint16_t y, uint16_t width, uint16_t height)
using XYRaster = XYRasterU8Sparse
Enumerations
enum AnimartrixAnim {
RGB_BLOBS5 = 0 , RGB_BLOBS4 , RGB_BLOBS3 , RGB_BLOBS2 ,
RGB_BLOBS , POLAR_WAVES , SLOW_FADE , ZOOM2 ,
ZOOM , HOT_BLOB , SPIRALUS2 , SPIRALUS ,
YVES , SCALEDEMO1 , LAVA1 , CALEIDO3 ,
CALEIDO2 , CALEIDO1 , DISTANCE_EXPERIMENT , CENTER_FIELD ,
WAVES , CHASING_SPIRALS , ROTATING_BLOB , RINGS ,
COMPLEX_KALEIDO , COMPLEX_KALEIDO_2 , COMPLEX_KALEIDO_3 , COMPLEX_KALEIDO_4 ,
COMPLEX_KALEIDO_5 , COMPLEX_KALEIDO_6 , WATER , PARAMETRIC_WATER ,
MODULE_EXPERIMENT1 , MODULE_EXPERIMENT2 , MODULE_EXPERIMENT3 , MODULE_EXPERIMENT4 ,
MODULE_EXPERIMENT5 , MODULE_EXPERIMENT6 , MODULE_EXPERIMENT7 , MODULE_EXPERIMENT8 ,
MODULE_EXPERIMENT9 , MODULE_EXPERIMENT10 , MODULE_EXPERIMENT_SM1 , MODULE_EXPERIMENT_SM2 ,
MODULE_EXPERIMENT_SM3 , MODULE_EXPERIMENT_SM4 , MODULE_EXPERIMENT_SM5 , MODULE_EXPERIMENT_SM6 ,
MODULE_EXPERIMENT_SM8 , MODULE_EXPERIMENT_SM9 , MODULE_EXPERIMENT_SM10 , NUM_ANIMATIONS
}
enum DrawMode { DRAW_MODE_OVERWRITE , DRAW_MODE_BLEND_BY_MAX_BRIGHTNESS }
enum FiveBitGammaCorrectionMode { kFiveBitGammaCorrectionMode_Null = 0 , kFiveBitGammaCorrectionMode_BitShift = 1 }
enum InsertResult { kInserted = 0 , kExists = 1 , kMaxSize = 2 }
enum class leddirection { FORWARD , BACKWARD , MAP }
enum SuperSample { SUPER_SAMPLE_NONE = 1 , SUPER_SAMPLE_2X = 2 , SUPER_SAMPLE_4X = 4 , SUPER_SAMPLE_8X = 8 }
enum TGradientDirectionCode { FORWARD_HUES , BACKWARD_HUES , SHORTEST_HUES , LONGEST_HUES }
Hue direction for calculating fill gradients.
enum U8EasingFunction { WAVE_U8_MODE_LINEAR , WAVE_U8_MODE_SQRT }
Functions
void __builtin_five_bit_hd_gamma_bitshift (CRGB colors, CRGB colors_scale, uint8_t global_brightness, CRGB *out_colors, uint8_t *out_power_5bit)
void AnimartrixLoop (Animartrix &self, uint32_t now)
CRGB applyGamma_video (const CRGB &orig, float gamma)
CRGB applyGamma_video (const CRGB &orig, float gammaR, float gammaG, float gammaB)
uint8_t applyGamma_video (uint8_t brightness, float gamma)
void bilinearExpand (const CRGB *input, CRGB *output, uint16_t inputWidth, uint16_t inputHeight, fl::XYMap xyMap)
void bilinearExpandArbitrary (const CRGB *input, CRGB *output, uint16_t inputWidth, uint16_t inputHeight, fl::XYMap xyMap)
Performs bilinear interpolation for upscaling an image.
void bilinearExpandArbitraryFloat (const CRGB *input, CRGB *output, uint16_t inputWidth, uint16_t inputHeight, XYMap xyMap)
void bilinearExpandFloat (const CRGB *input, CRGB *output, uint8_t inputWidth, uint8_t inputHeight, XYMap xyMap)
void bilinearExpandPowerOf2 (const CRGB *input, CRGB *output, uint8_t inputWidth, uint8_t inputHeight, fl::XYMap xyMap)
Performs bilinear interpolation for upscaling an image.
uint8_t bilinearInterpolate (uint8_t v00, uint8_t v10, uint8_t v01, uint8_t v11, uint16_t dx, uint16_t dy)
uint8_t bilinearInterpolateFloat (uint8_t v00, uint8_t v10, uint8_t v01, uint8_t v11, float dx, float dy)
uint8_t bilinearInterpolatePowerOf2 (uint8_t v00, uint8_t v10, uint8_t v01, uint8_t v11, uint8_t dx, uint8_t dy)
CHSV blend (const CHSV &p1, const CHSV &p2, fract8 amountOfP2, TGradientDirectionCode directionCode)
CHSV * blend (const CHSV *src1, const CHSV *src2, CHSV *dest, uint16_t count, fract8 amountOfsrc2, TGradientDirectionCode directionCode)
CRGB blend (const CRGB &p1, const CRGB &p2, fract8 amountOfP2)
CRGB * blend (const CRGB *src1, const CRGB *src2, CRGB *dest, uint16_t count, fract8 amountOfsrc2)
void blur1d (CRGB *leds, uint16_t numLeds, fract8 blur_amount)
One-dimensional blur filter.
void blur2d (CRGB *leds, uint8_t width, uint8_t height, fract8 blur_amount) FASTLED_DEPRECATED("Use blur2d(...
Legacy version of blur2d, which does not require an XYMap but instead implicitly binds to XY() function.
void blur2d (CRGB *leds, uint8_t width, uint8_t height, fract8 blur_amount, const fl::XYMap &xymap)
Two-dimensional blur filter.
void blurColumns (CRGB *leds, uint8_t width, uint8_t height, fract8 blur_amount, const fl::XYMap &xymap)
Perform a blur1d() on every column of a rectangular matrix.
void blurRows (CRGB *leds, uint8_t width, uint8_t height, fract8 blur_amount, const fl::XYMap &xymap)
Perform a blur1d() on every row of a rectangular matrix.
template<typename T>
T ceil (T value)
template<typename T>
FASTLED_FORCE_INLINE T clamp (T value, T min, T max)
template<int N>
void clear (CRGB(&arr)[N])
void clear (Leds &leds)
CHSV ColorFromPalette (const CHSVPalette16 &pal, uint8_t index, uint8_t brightness, TBlendType blendType)
CHSV ColorFromPalette (const CHSVPalette256 &pal, uint8_t index, uint8_t brightness, TBlendType)
CHSV ColorFromPalette (const CHSVPalette32 &pal, uint8_t index, uint8_t brightness, TBlendType blendType)
CRGB ColorFromPalette (const CRGBPalette16 &pal, uint8_t index, uint8_t brightness, TBlendType blendType)
CRGB ColorFromPalette (const CRGBPalette256 &pal, uint8_t index, uint8_t brightness, TBlendType)
CRGB ColorFromPalette (const CRGBPalette32 &pal, uint8_t index, uint8_t brightness, TBlendType blendType)
CRGB ColorFromPalette (const TProgmemRGBPalette16 &pal, uint8_t index, uint8_t brightness, TBlendType blendType)
CRGB ColorFromPalette (const TProgmemRGBPalette32 &pal, uint8_t index, uint8_t brightness, TBlendType blendType)
CRGB ColorFromPaletteExtended (const CRGBPalette16 &pal, uint16_t index, uint8_t brightness, TBlendType blendType)
CRGB ColorFromPaletteExtended (const CRGBPalette256 &pal, uint16_t index, uint8_t brightness, TBlendType blendType)
CRGB ColorFromPaletteExtended (const CRGBPalette32 &pal, uint16_t index, uint8_t brightness, TBlendType blendType)
static FASTLED_FORCE_INLINE int16_t cos16lut (uint16_t angle)
static FASTLED_FORCE_INLINE int32_t cos32 (uint32_t angle)
void downscale (const CRGB *src, const XYMap &srcXY, CRGB *dst, const XYMap &dstXY)
void downscaleArbitrary (const CRGB *src, const XYMap &srcXY, CRGB *dst, const XYMap &dstXY)
void downscaleHalf (const CRGB *src, const XYMap &srcXY, CRGB *dst, const XYMap &dstXY)
void downscaleHalf (const CRGB *src, uint16_t srcWidth, uint16_t srcHeight, CRGB *dst)
void drawSquare (void *, uint16_t, uint16_t, int, int, uint32_t, uint32_t)
void fade_raw (CRGB *leds, uint16_t num_leds, uint8_t fadeBy)
void fade_video (CRGB *leds, uint16_t num_leds, uint8_t fadeBy)
void fadeLightBy (CRGB *leds, uint16_t num_leds, uint8_t fadeBy)
void fadeToBlackBy (CRGB *leds, uint16_t num_leds, uint8_t fadeBy)
void fadeToColorBy (void *, uint16_t, uint32_t, uint8_t)
void fadeUsingColor (CRGB *leds, uint16_t numLeds, const CRGB &colormask)
static uint32_t fast_hash32 (uint32_t x) noexcept
const char * fastled_file_offset (const char *file)
FASTLED_SMART_PTR (Animartrix)
FASTLED_SMART_PTR (ArchimedeanSpiralPath)
FASTLED_SMART_PTR (AudioSampleImpl)
FASTLED_SMART_PTR (Blend2d)
FASTLED_SMART_PTR (ByteStream)
FASTLED_SMART_PTR (ByteStreamMemory)
FASTLED_SMART_PTR (CatmullRomParams)
FASTLED_SMART_PTR (CatmullRomPath)
FASTLED_SMART_PTR (CirclePath)
FASTLED_SMART_PTR (Cylon)
FASTLED_SMART_PTR (DemoReel100)
FASTLED_SMART_PTR (DigitalPinImpl)
FASTLED_SMART_PTR (FileHandle)
FASTLED_SMART_PTR (FileSystem)
FASTLED_SMART_PTR (Fire2012)
Simple one-dimensional fire animation function.
FASTLED_SMART_PTR (Frame)
FASTLED_SMART_PTR (FrameInterpolator)
FASTLED_SMART_PTR (FsImpl)
FASTLED_SMART_PTR (Fx)
FASTLED_SMART_PTR (Fx2d)
FASTLED_SMART_PTR (FxLayer)
FASTLED_SMART_PTR (GielisCurvePath)
FASTLED_SMART_PTR (HeartPath)
FASTLED_SMART_PTR (LinePath)
FASTLED_SMART_PTR (LinePathParams)
FASTLED_SMART_PTR (NoisePalette)
FASTLED_SMART_PTR (NoiseWave)
FASTLED_SMART_PTR (Pacifica)
FASTLED_SMART_PTR (PhyllotaxisPath)
FASTLED_SMART_PTR (PixelStream)
FASTLED_SMART_PTR (PointPath)
FASTLED_SMART_PTR (Pride2015)
FASTLED_SMART_PTR (RedSquare)
FASTLED_SMART_PTR (RosePath)
FASTLED_SMART_PTR (RosePathParams)
FASTLED_SMART_PTR (ScaleUp)
FASTLED_SMART_PTR (StringHolder)
FASTLED_SMART_PTR (TimeFunction)
FASTLED_SMART_PTR (TimeWarp)
FASTLED_SMART_PTR (TransformFloatImpl)
FASTLED_SMART_PTR (TwinkleFox)
FASTLED_SMART_PTR (VideoFxWrapper)
FASTLED_SMART_PTR (VideoImpl)
FASTLED_SMART_PTR (WaveCrgbGradientMap)
FASTLED_SMART_PTR (WaveCrgbMap)
FASTLED_SMART_PTR (WaveCrgbMapDefault)
FASTLED_SMART_PTR (WaveFx)
FASTLED_SMART_PTR (XYPath)
FASTLED_SMART_PTR (XYPathFunction)
FASTLED_SMART_PTR (XYPathGenerator)
FASTLED_SMART_PTR (XYPathRenderer)
FASTLED_SMART_PTR_NO_FWD (LUT16)
FASTLED_SMART_PTR_NO_FWD (LUTXY16)
FASTLED_SMART_PTR_NO_FWD (LUTXYFLOAT)
FASTLED_SMART_PTR_NO_FWD (LUTXYZFLOAT)
FASTLED_UI_DEFINE_OPERATORS (UIButton)
FASTLED_UI_DEFINE_OPERATORS (UICheckbox)
FASTLED_UI_DEFINE_OPERATORS (UINumberField)
FASTLED_UI_DEFINE_OPERATORS (UISlider)
template<typename T>
void fill_gradient (T *targetArray, uint16_t numLeds, const CHSV &c1, const CHSV &c2, const CHSV &c3, const CHSV &c4, TGradientDirectionCode directionCode=SHORTEST_HUES)
Fill a range of LEDs with a smooth HSV gradient between four HSV colors.
template<typename T>
void fill_gradient (T *targetArray, uint16_t numLeds, const CHSV &c1, const CHSV &c2, const CHSV &c3, TGradientDirectionCode directionCode=SHORTEST_HUES)
Fill a range of LEDs with a smooth HSV gradient between three HSV colors.
template<typename T>
void fill_gradient (T *targetArray, uint16_t numLeds, const CHSV &c1, const CHSV &c2, TGradientDirectionCode directionCode=SHORTEST_HUES)
Fill a range of LEDs with a smooth HSV gradient between two HSV colors.
template<typename T>
void fill_gradient (T *targetArray, uint16_t startpos, CHSV startcolor, uint16_t endpos, CHSV endcolor, TGradientDirectionCode directionCode=SHORTEST_HUES)
Fill a range of LEDs with a smooth HSV gradient between two HSV colors.
void fill_gradient_RGB (CRGB *leds, uint16_t numLeds, const CRGB &c1, const CRGB &c2)
Fill a range of LEDs with a smooth RGB gradient between two RGB colors.
void fill_gradient_RGB (CRGB *leds, uint16_t numLeds, const CRGB &c1, const CRGB &c2, const CRGB &c3)
Fill a range of LEDs with a smooth RGB gradient between three RGB colors.
void fill_gradient_RGB (CRGB *leds, uint16_t numLeds, const CRGB &c1, const CRGB &c2, const CRGB &c3, const CRGB &c4)
Fill a range of LEDs with a smooth RGB gradient between four RGB colors.
void fill_gradient_RGB (CRGB *leds, uint16_t startpos, CRGB startcolor, uint16_t endpos, CRGB endcolor)
Fill a range of LEDs with a smooth RGB gradient between two RGB colors.
void fill_rainbow (struct CHSV *targetArray, int numToFill, uint8_t initialhue, uint8_t deltahue=5)
Fill a range of LEDs with a rainbow of colors.
void fill_rainbow (struct CRGB *targetArray, int numToFill, uint8_t initialhue, uint8_t deltahue=5)
Fill a range of LEDs with a rainbow of colors.
void fill_rainbow_circular (struct CHSV *targetArray, int numToFill, uint8_t initialhue, bool reversed=false)
Fill a range of LEDs with a rainbow of colors, so that the hues are continuous between the end of the strip and the beginning.
void fill_rainbow_circular (struct CRGB *targetArray, int numToFill, uint8_t initialhue, bool reversed=false)
Fill a range of LEDs with a rainbow of colors, so that the hues are continuous between the end of the strip and the beginning.
void fill_solid (struct CHSV *targetArray, int numToFill, const struct CHSV &color)
Fill a range of LEDs with a solid color.
void fill_solid (struct CRGB *targetArray, int numToFill, const struct CRGB &color)
Fill a range of LEDs with a solid color.
uint8_t five_bit_bitshift (uint16_t r16, uint16_t g16, uint16_t b16, uint8_t brightness, CRGB *out, uint8_t *out_power_5bit)
FASTLED_FORCE_INLINE void five_bit_hd_gamma_bitshift (CRGB colors, CRGB colors_scale, uint8_t global_brightness, CRGB *out_colors, uint8_t *out_power_5bit)
void five_bit_hd_gamma_function (CRGB color, uint16_t *r16, uint16_t *g16, uint16_t *b16)
template<typename T>
T fl_abs (T value)
template<typename T>
T floor (T value)
template<typename T>
constexpr T && forward (typename remove_reference< T >::type &&t) noexcept
template<typename T>
constexpr T && forward (typename remove_reference< T >::type &t) noexcept
static uint32_t hash_pair (uint32_t a, uint32_t b, uint32_t seed=0) noexcept
CRGB HeatColor (uint8_t temperature)
void * LargeBlockAllocate (size_t size, bool zero)
void LargeBlockDeallocate (void *ptr)
uint8_t lsrX4 (uint8_t dividend)
Helper function to divide a number by 16, aka four logical shift right (LSR)'s.
FsImplPtr make_sdcard_filesystem (int cs_pin)
template<typename T, typename U>
FASTLED_FORCE_INLINE U map_range (T value, T in_min, T in_max, U out_min, U out_max)
template<typename T, typename U>
FASTLED_FORCE_INLINE U map_range_clamped (T value, T in_min, T in_max, U out_min, U out_max)
template<typename T>
constexpr remove_reference< T >::type && move (T &&t) noexcept
static uint32_t MurmurHash3_x86_32 (const void *key, size_t len, uint32_t seed=0)
CRGB & napplyGamma_video (CRGB &rgb, float gamma)
CRGB & napplyGamma_video (CRGB &rgb, float gammaR, float gammaG, float gammaB)
void napplyGamma_video (CRGB *rgbarray, uint16_t count, float gamma)
void napplyGamma_video (CRGB *rgbarray, uint16_t count, float gammaR, float gammaG, float gammaB)
CHSV & nblend (CHSV &existing, const CHSV &overlay, fract8 amountOfOverlay, TGradientDirectionCode directionCode)
void nblend (CHSV *existing, const CHSV *overlay, uint16_t count, fract8 amountOfOverlay, TGradientDirectionCode directionCode)
CRGB & nblend (CRGB &existing, const CRGB &overlay, fract8 amountOfOverlay)
void nblend (CRGB *existing, const CRGB *overlay, uint16_t count, fract8 amountOfOverlay)
void nblendPaletteTowardPalette (CRGBPalette16 &current, CRGBPalette16 &target, uint8_t maxChanges)
template<typename T, typename... Args>
Ptr< T > NewPtr (Args... args)
template<typename T, typename... Args>
Ptr< T > NewPtrNoTracking (Args... args)
template<typename T>
Ptr< T > NewPtrNoTracking (T &obj)
void nscale8 (CRGB *leds, uint16_t num_leds, uint8_t scale)
void nscale8_video (CRGB *leds, uint16_t num_leds, uint8_t scale)
template<typename T, size_t N>
bool operator!= (const array< T, N > &lhs, const array< T, N > &rhs)
template<typename T, size_t N>
bool operator== (const array< T, N > &lhs, const array< T, N > &rhs)
bool parseJson (const char *json, fl::JsonDocument *doc, Str *_error)
template<typename Iterator>
void pop_heap (Iterator first, Iterator last)
template<typename Iterator, typename Compare>
void pop_heap (Iterator first, Iterator last, Compare comp)
template<typename Iterator>
void push_heap (Iterator first, Iterator last)
template<typename Iterator, typename Compare>
void push_heap (Iterator first, Iterator last, Compare comp)
void SetLargeBlockAllocator (void *(*alloc)(size_t), void(*free)(void *))
template<typename Iterator, typename Compare>
void sift_down (Iterator first, Iterator last, Iterator start, Compare comp)
static FASTLED_FORCE_INLINE int16_t sin16lut (uint16_t angle)
static FASTLED_FORCE_INLINE int32_t sin32 (uint32_t angle)
template<typename T, size_t N>
void swap (array< T, N > &lhs, array< T, N > &rhs) noexcept(noexcept(lhs.swap(rhs)))
template<typename T>
void swap (T &a, T &b)
template<typename T>
void swap_by_copy (T &a, T &b)
uint16_t time_alpha16 (uint32_t now, uint32_t start, uint32_t end)
uint8_t time_alpha8 (uint32_t now, uint32_t start, uint32_t end)
float time_alphaf (uint32_t now, uint32_t start, uint32_t end)
void toJson (const fl::JsonDocument &doc, Str *jsonBuffer)
template<typename GridVisitor>
void traverseGridSegment (const vec2f &start, const vec2f &end, GridVisitor &visitor)
Traverse a grid segment by selecting the cells that are crossed.
template<typename GridVisitor>
void traverseGridSegment16 (const vec2f &start, const vec2f &end, GridVisitor &visitor)
Traverse a grid segment using fixed-point 8.8 arithmetic.
template<typename GridVisitor>
void traverseGridSegment32 (const vec2f &start, const vec2f &end, GridVisitor &visitor)
template<typename GridVisitor>
void traverseGridSegmentFloat (const vec2f &start, const vec2f &end, GridVisitor &visitor)
Traverse a grid segment using floating point arithmetic.
void UpscalePalette (const class CHSVPalette16 &srcpal16, class CHSVPalette256 &destpal256)
void UpscalePalette (const class CHSVPalette16 &srcpal16, class CHSVPalette32 &destpal32)
void UpscalePalette (const class CHSVPalette32 &srcpal32, class CHSVPalette256 &destpal256)
void UpscalePalette (const class CRGBPalette16 &srcpal16, class CRGBPalette256 &destpal256)
void UpscalePalette (const class CRGBPalette16 &srcpal16, class CRGBPalette32 &destpal32)
void UpscalePalette (const class CRGBPalette32 &srcpal32, class CRGBPalette256 &destpal256)
int32_t worley_noise_2d_q15 (int32_t x, int32_t y)
FASTLED_FORCE_INLINE uint16_t x_linear (uint16_t x, uint16_t length)
FASTLED_FORCE_INLINE uint16_t x_reverse (uint16_t x, uint16_t length)
uint16_t XY (uint8_t x, uint8_t y)
FASTLED_FORCE_INLINE uint16_t xy_line_by_line (uint16_t x, uint16_t y, uint16_t width, uint16_t height)
FASTLED_FORCE_INLINE uint16_t xy_serpentine (uint16_t x, uint16_t y, uint16_t width, uint16_t height)
Variables
const TProgmemRGBPalette16 * ActivePaletteList []
static const AnimartrixEntry ANIMATION_TABLE []
const TProgmemRGBPalette16 BlueWhite_p
const int16_t * cosArray = &sinLut[64]
const TProgmemRGBPalette16 FairyLight_p
static FFT gFlexFFT
const TProgmemRGBPalette16 Holly_p
const TProgmemRGBPalette16 Ice_p
void const fl::XYMap &xymap instead
const TProgmemRGBPalette16 RedGreenWhite_p
const TProgmemRGBPalette16 RedWhite_p
const TProgmemRGBPalette16 RetroC9_p
const int16_t * sinArray = &sinLut[0]
const int16_t sinLut []
const TProgmemRGBPalette16 Snow_p
Class Members
typedef T * type T *
fl::add_pointer< T & >
struct fl::add_pointer< T & >
Class Members
typedef T * type
typedef T * type T *
fl::add_pointer< T && >
struct fl::add_pointer< T && >
Class Members
typedef T * type
typedef T * type T *
fl::AnimartrixEntry
struct fl::AnimartrixEntry
Class Members
AnimartrixAnim anim
void(FastLEDANIMartRIX::*)() func
const char * name
fl::Blend2dParams
struct fl::Blend2dParams
Class Members
uint8_t blur_amount = 0
uint8_t blur_passes = 1
fl::conditional
struct fl::conditional
Class Members
typedef T type T
fl::conditional< false, T, F >
struct fl::conditional< false, T, F >
Class Members
typedef T type
typedef F type F
fl::contains_type
struct fl::contains_type
fl::Empty
struct fl::Empty
fl::enable_if
struct fl::enable_if
fl::enable_if< true, T >
struct fl::enable_if< true, T >
Class Members
typedef T type T
fl::function
class fl::function
fl::JsonDocument
class fl::JsonDocument
fl::max_align
struct fl::max_align
fl::max_size
struct fl::max_size
fl::Pixel.__unnamed0__
union fl::Pixel.__unnamed0__
Class Members
struct Pixel.__unnamed0__.__unnamed0__ __unnamed__
uint8_t raw[3]
fl::Pixel.__unnamed0__.__unnamed0__
struct fl::Pixel.__unnamed0__.__unnamed0__
Class Members
uint8_t blue
uint8_t green
uint8_t red
fl::remove_const
struct fl::remove_const
Class Members
typedef T type T
fl::remove_const< const T >
struct fl::remove_const< const T >
Class Members
typedef T type
typedef T type T
fl::remove_cv
struct fl::remove_cv
Class Members
typedef T type T
fl::remove_cv< const T >
struct fl::remove_cv< const T >
Class Members
typedef T type
typedef T type T
fl::remove_cv< const volatile T >
struct fl::remove_cv< const volatile T >
Class Members
typedef const volatile T type
typedef T type T
fl::remove_cv< volatile T >
struct fl::remove_cv< volatile T >
Class Members
typedef T type
typedef T type T
fl::remove_extent
struct fl::remove_extent
Class Members
typedef T type T
fl::remove_extent< T[]>
struct fl::remove_extent< T[]>
Class Members
typedef T type
typedef T type T
fl::remove_extent< T[N]>
struct fl::remove_extent< T[N]>
Class Members
typedef T type
typedef T type T
fl::remove_reference
struct fl::remove_reference
Class Members
typedef T type T
fl::remove_reference< T & >
struct fl::remove_reference< T & >
Class Members
typedef T type
typedef T type T
fl::remove_reference< T && >
struct fl::remove_reference< T && >
Class Members
typedef T type
typedef T type T
fl::swap_impl
struct fl::swap_impl
Typedef Documentation
add_pointer_t
template<typename T> using fl::add_pointer_t = typename add_pointer<T>::type
Definition at line 161 of file type_traits.h.
alpha16
using fl::alpha16
Initial value:
    uint16_t
Definition at line 21 of file transform.h.
bitset
template<uint32_t N = 256> using fl::bitset = BitsetInlined<N>
Definition at line 15 of file bitset.h.
bitset_fixed
template<uint32_t N> using fl::bitset_fixed = BitsetFixed<N>
Definition at line 18 of file bitset.h.
conditional_t
template<bool B, typename T, typename F> using fl::conditional_t = typename conditional<B, T, F>::type
Definition at line 96 of file type_traits.h.
cycle_t
typedef int64_t fl::cycle_t
8.8 fixed point (signed) value
Definition at line 11 of file types.h.
decay_t
template<typename T> using fl::decay_t = typename decay<T>::type
Definition at line 233 of file type_traits.h.
enable_if_t
template<bool Condition, typename T = void> using fl::enable_if_t = typename enable_if<Condition, T>::type
Definition at line 29 of file type_traits.h.
equal_to
template<typename T> using fl::equal_to = EqualTo<T>
Definition at line 587 of file hash_map.h.
hash_map
template<typename Key, typename T, typename Hash = Hash<Key>, typename KeyEqual = equal_to<Key>> using fl::hash_map = HashMap<Key, T, Hash, KeyEqual>
Definition at line 591 of file hash_map.h.
hash_set
template<typename Key, typename Hash = Hash<Key>, typename KeyEqual = EqualTo<Key>> using fl::hash_set = HashSet<Key, Hash, KeyEqual>
Definition at line 30 of file hash_set.h.
is_derived
template<typename Base, typename Derived> using fl::is_derived = enable_if_t<is_base_of<Base, Derived>::value>
Definition at line 385 of file type_traits.h.
LUT16
typedef LUT<uint16_t> fl::LUT16
Definition at line 23 of file lut.h.
LUTXY16
typedef LUT<vec2<uint16_t> > fl::LUTXY16
Definition at line 24 of file lut.h.
LUTXYFLOAT
typedef LUT<vec2f> fl::LUTXYFLOAT
Definition at line 25 of file lut.h.
LUTXYZFLOAT
typedef LUT<vec3f> fl::LUTXYZFLOAT
Definition at line 26 of file lut.h.
optional
template<typename T> using fl::optional = Optional<T>
Definition at line 10 of file optional.h.
pair
template<typename Key, typename Value> using fl::pair = Pair<Key, Value>
Definition at line 13 of file pair.h.
pair_xy_float
using fl::pair_xy_float = vec2<float>
Definition at line 308 of file geometry.h.
pair_xyz_float
using fl::pair_xyz_float = vec3<float>
Definition at line 304 of file geometry.h.
remove_cv_t
template<typename T> using fl::remove_cv_t = typename remove_cv<T>::type
Definition at line 218 of file type_traits.h.
remove_reference_t
template<typename T> using fl::remove_reference_t = typename remove_reference<T>::type
Definition at line 84 of file type_traits.h.
string
using fl::string = fl::Str
Definition at line 25 of file str.h.
ThreadLocal
template<typename T> using fl::ThreadLocal = ThreadLocalFake<T>
Definition at line 14 of file thread_local.h.
unordered_map
template<typename Key, typename T, typename Hash = Hash<Key>, typename KeyEqual = equal_to<Key>> using fl::unordered_map = HashMap<Key, T, Hash, KeyEqual>
Definition at line 595 of file hash_map.h.
vec2f
using fl::vec2f = vec2<float>
Definition at line 301 of file geometry.h.
vec3f
using fl::vec3f = vec3<float>
Definition at line 156 of file geometry.h.
vector
template<typename T> using fl::vector = HeapVector<T>
Definition at line 1028 of file vector.h.
vector_fixed
template<typename T, size_t INLINED_SIZE> using fl::vector_fixed = FixedVector<T, INLINED_SIZE>
Definition at line 1031 of file vector.h.
vector_inlined
template<typename T, size_t INLINED_SIZE = 64> using fl::vector_inlined = InlinedVector<T, INLINED_SIZE>
Definition at line 1034 of file vector.h.
XFunction
typedef uint16_t(* fl::XFunction) (uint16_t x, uint16_t length)
Definition at line 24 of file xmap.h.
XYFunction
typedef uint16_t(* fl::XYFunction) (uint16_t x, uint16_t y, uint16_t width, uint16_t height)
Definition at line 34 of file xymap.h.
XYRaster
using fl::XYRaster = XYRasterU8Sparse
Definition at line 8 of file raster.h.
Enumeration Type Documentation
AnimartrixAnim
enum fl::AnimartrixAnim
Enumerator
RGB_BLOBS5
RGB_BLOBS4
RGB_BLOBS3
RGB_BLOBS2
RGB_BLOBS
POLAR_WAVES
SLOW_FADE
ZOOM2
ZOOM
HOT_BLOB
SPIRALUS2
SPIRALUS
YVES
SCALEDEMO1
LAVA1
CALEIDO3
CALEIDO2
CALEIDO1
DISTANCE_EXPERIMENT
CENTER_FIELD
WAVES
CHASING_SPIRALS
ROTATING_BLOB
RINGS
COMPLEX_KALEIDO
COMPLEX_KALEIDO_2
COMPLEX_KALEIDO_3
COMPLEX_KALEIDO_4
COMPLEX_KALEIDO_5
COMPLEX_KALEIDO_6
WATER
PARAMETRIC_WATER
MODULE_EXPERIMENT1
MODULE_EXPERIMENT2
MODULE_EXPERIMENT3
MODULE_EXPERIMENT4
MODULE_EXPERIMENT5
MODULE_EXPERIMENT6
MODULE_EXPERIMENT7
MODULE_EXPERIMENT8
MODULE_EXPERIMENT9
MODULE_EXPERIMENT10
MODULE_EXPERIMENT_SM1
MODULE_EXPERIMENT_SM2
MODULE_EXPERIMENT_SM3
MODULE_EXPERIMENT_SM4
MODULE_EXPERIMENT_SM5
MODULE_EXPERIMENT_SM6
MODULE_EXPERIMENT_SM8
MODULE_EXPERIMENT_SM9
MODULE_EXPERIMENT_SM10
NUM_ANIMATIONS
Definition at line 25 of file animartrix.hpp.
                    {
    RGB_BLOBS5 = 0,
    RGB_BLOBS4,
    RGB_BLOBS3,
    RGB_BLOBS2,
    RGB_BLOBS,
    POLAR_WAVES,
    SLOW_FADE,
    ZOOM2,
    ZOOM,
    HOT_BLOB,
    SPIRALUS2,
    SPIRALUS,
    YVES,
    SCALEDEMO1,
    LAVA1,
    CALEIDO3,
    CALEIDO2,
    CALEIDO1,
    DISTANCE_EXPERIMENT,
    CENTER_FIELD,
    WAVES,
    CHASING_SPIRALS,
    ROTATING_BLOB,
    RINGS,
    COMPLEX_KALEIDO,
    COMPLEX_KALEIDO_2,
    COMPLEX_KALEIDO_3,
    COMPLEX_KALEIDO_4,
    COMPLEX_KALEIDO_5,
    COMPLEX_KALEIDO_6,
    WATER,
    PARAMETRIC_WATER,
    MODULE_EXPERIMENT1,
    MODULE_EXPERIMENT2,
    MODULE_EXPERIMENT3,
    MODULE_EXPERIMENT4,
    MODULE_EXPERIMENT5,
    MODULE_EXPERIMENT6,
    MODULE_EXPERIMENT7,
    MODULE_EXPERIMENT8,
    MODULE_EXPERIMENT9,
    MODULE_EXPERIMENT10,
    MODULE_EXPERIMENT_SM1,
    MODULE_EXPERIMENT_SM2,
    MODULE_EXPERIMENT_SM3,
    MODULE_EXPERIMENT_SM4,
    MODULE_EXPERIMENT_SM5,
    MODULE_EXPERIMENT_SM6,
    MODULE_EXPERIMENT_SM8,
    MODULE_EXPERIMENT_SM9,
    MODULE_EXPERIMENT_SM10,
    NUM_ANIMATIONS
};
DrawMode
enum fl::DrawMode
Enumerator
DRAW_MODE_OVERWRITE
DRAW_MODE_BLEND_BY_MAX_BRIGHTNESS
Definition at line 5 of file draw_mode.h.
{ DRAW_MODE_OVERWRITE, DRAW_MODE_BLEND_BY_MAX_BRIGHTNESS };
FiveBitGammaCorrectionMode
enum fl::FiveBitGammaCorrectionMode
Enumerator
kFiveBitGammaCorrectionMode_Null
kFiveBitGammaCorrectionMode_BitShift
Definition at line 14 of file five_bit_hd_gamma.h.
{
    kFiveBitGammaCorrectionMode_Null = 0,
    kFiveBitGammaCorrectionMode_BitShift = 1
};
InsertResult
enum fl::InsertResult
Enumerator
kInserted
kExists
kMaxSize
Definition at line 10 of file insert_result.h.
                  {
    kInserted = 0,
    kExists = 1,
    kMaxSize = 2,
};
leddirection
enum class fl::leddirection strong
Enumerator
FORWARD
BACKWARD
MAP
Definition at line 139 of file ___pixeltypes.h.
{ FORWARD, BACKWARD, MAP };
SuperSample
enum fl::SuperSample
Enumerator
SUPER_SAMPLE_NONE
SUPER_SAMPLE_2X
SUPER_SAMPLE_4X
SUPER_SAMPLE_8X
Definition at line 4 of file supersample.h.
                 {
    SUPER_SAMPLE_NONE = 1, // 1x supersampling (no supersampling)
    SUPER_SAMPLE_2X = 2,   // 2x supersampling
    SUPER_SAMPLE_4X = 4,   // 4x supersampling
    SUPER_SAMPLE_8X = 8    // 8x supersampling
};
TGradientDirectionCode
enum fl::TGradientDirectionCode
Hue direction for calculating fill gradients.
Since "hue" is a value around a color wheel, there are always two directions to sweep from one hue to another.
Enumerator
FORWARD_HUES
Hue always goes clockwise around the color wheel.
BACKWARD_HUES
Hue always goes counter-clockwise around the color wheel.
SHORTEST_HUES
Hue goes whichever way is shortest.
LONGEST_HUES
Hue goes whichever way is longest.
Definition at line 33 of file colorutils_misc.h.
             {
    FORWARD_HUES,
    BACKWARD_HUES,
    SHORTEST_HUES,
    LONGEST_HUES
} TGradientDirectionCode;
U8EasingFunction
enum fl::U8EasingFunction
Enumerator
WAVE_U8_MODE_LINEAR
WAVE_U8_MODE_SQRT
Definition at line 32 of file wave_simulation.h.
{ WAVE_U8_MODE_LINEAR, WAVE_U8_MODE_SQRT };
Function Documentation
__builtin_five_bit_hd_gamma_bitshift()
void fl::__builtin_five_bit_hd_gamma_bitshift (CRGB colors, CRGB colors_scale, uint8_t global_brightness, CRGB * out_colors, uint8_t * out_power_5bit)
Definition at line 128 of file five_bit_hd_gamma.cpp.
{
    if (global_brightness == 0) {
        *out_colors = CRGB(0, 0, 0);
        *out_power_5bit = 0;
        return;
    }
    // Step 1: Gamma Correction
    uint16_t r16, g16, b16;
    five_bit_hd_gamma_function(colors, &r16, &g16, &b16);
    // Step 2: Color correction step comes after gamma correction. These values
    // are assumed to be be relatively close to 255.
    if (colors_scale.r != 0xff) {
        r16 = scale16by8(r16, colors_scale.r);
    }
    if (colors_scale.g != 0xff) {
        g16 = scale16by8(g16, colors_scale.g);
    }
    if (colors_scale.b != 0xff) {
        b16 = scale16by8(b16, colors_scale.b);
    }
    five_bit_bitshift(r16, g16, b16, global_brightness, out_colors,
                      out_power_5bit);
}
References five_bit_bitshift(), five_bit_hd_gamma_function(), and scale16by8().
Referenced by five_bit_hd_gamma_bitshift().
AnimartrixLoop()
void fl::AnimartrixLoop (Animartrix & self, uint32_t now)
Definition at line 155 of file animartrix.hpp.
{
    if (self.prev_animation != self.current_animation) {
        if (self.impl) {
            // Re-initialize object.
            self.impl->init(self.getWidth(), self.getHeight());
        }
        self.prev_animation = self.current_animation;
    }
    if (!self.impl) {
        self.impl.reset(new FastLEDANIMartRIX(&self));
    }
    self.impl->setTime(now);
    self.impl->loop();
}
applyGamma_video() [1/3]
CRGB fl::applyGamma_video (const CRGB & orig, float gamma)
Definition at line 1068 of file colorutils.cpp.
{
    CRGB adj;
    adj.r = applyGamma_video(orig.r, gamma);
    adj.g = applyGamma_video(orig.g, gamma);
    adj.b = applyGamma_video(orig.b, gamma);
    return adj;
}
References applyGamma_video().
applyGamma_video() [2/3]
CRGB fl::applyGamma_video (const CRGB & orig, float gammaR, float gammaG, float gammaB)
Definition at line 1076 of file colorutils.cpp.
{
    CRGB adj;
    adj.r = applyGamma_video(orig.r, gammaR);
    adj.g = applyGamma_video(orig.g, gammaG);
    adj.b = applyGamma_video(orig.b, gammaB);
    return adj;
}
References applyGamma_video().
applyGamma_video() [3/3]
uint8_t fl::applyGamma_video (uint8_t brightness, float gamma)
Definition at line 1056 of file colorutils.cpp.
{
    float orig;
    float adj;
    orig = (float)(brightness) / (255.0);
    adj = pow(orig, gamma) * (255.0);
    uint8_t result = (uint8_t)(adj);
    if ((brightness > 0) && (result == 0)) {
        result = 1; // never gamma-adjust a positive number down to zero
    }
    return result;
}
References brightness.
Referenced by applyGamma_video(), applyGamma_video(), napplyGamma_video(), napplyGamma_video(), napplyGamma_video(), and napplyGamma_video().
bilinearExpand()
void fl::bilinearExpand (const CRGB * input, CRGB * output, uint16_t inputWidth, uint16_t inputHeight, fl::XYMap xyMap) inline
Definition at line 37 of file bilinear_expansion.h.
{
    uint16_t outputWidth = xyMap.getWidth();
    uint16_t outputHeight = xyMap.getHeight();
    const bool wontFit =
        (outputWidth != xyMap.getWidth() || outputHeight != xyMap.getHeight());
    // if the input dimensions are not a power of 2 then we can't use the
    // optimized version.
    if (wontFit || (inputWidth & (inputWidth - 1)) ||
        (inputHeight & (inputHeight - 1))) {
        bilinearExpandArbitrary(input, output, inputWidth, inputHeight, xyMap);
    } else {
        bilinearExpandPowerOf2(input, output, inputWidth, inputHeight, xyMap);
    }
}
References bilinearExpandArbitrary(), bilinearExpandPowerOf2(), and xyMap.
Referenced by fl::ScaleUp::expand(), and CRGB::upscale().
bilinearExpandArbitrary()
void fl::bilinearExpandArbitrary (const CRGB * input, CRGB * output, uint16_t inputWidth, uint16_t inputHeight, fl::XYMap xyMap)
Performs bilinear interpolation for upscaling an image.
Parameters
output The output grid to write into the interpolated values.
input The input grid to read from.
inputWidth The width of the input grid.
inputHeight The height of the input grid.
xyMap The XYMap to use to determine where to write the pixel. If the pixel is mapped outside of the range then it is clipped.
Definition at line 20 of file bilinear_expansion.cpp.
{
    uint16_t n = xyMap.getTotal();
    uint16_t outputWidth = xyMap.getWidth();
    uint16_t outputHeight = xyMap.getHeight();
    const uint16_t scale_factor = 256; // Using 8 bits for the fractional part
    for (uint16_t y = 0; y < outputHeight; y++) {
        for (uint16_t x = 0; x < outputWidth; x++) {
            // Calculate the corresponding position in the input grid
            uint32_t fx = ((uint32_t)x * (inputWidth - 1) * scale_factor) /
                          (outputWidth - 1);
            uint32_t fy = ((uint32_t)y * (inputHeight - 1) * scale_factor) /
                          (outputHeight - 1);
            uint16_t ix = fx / scale_factor; // Integer part of x
            uint16_t iy = fy / scale_factor; // Integer part of y
            uint16_t dx = fx % scale_factor; // Fractional part of x
            uint16_t dy = fy % scale_factor; // Fractional part of y
            uint16_t ix1 = (ix + 1 < inputWidth) ? ix + 1 : ix;
            uint16_t iy1 = (iy + 1 < inputHeight) ? iy + 1 : iy;
            uint16_t i00 = iy * inputWidth + ix;
            uint16_t i10 = iy * inputWidth + ix1;
            uint16_t i01 = iy1 * inputWidth + ix;
            uint16_t i11 = iy1 * inputWidth + ix1;
            CRGB c00 = input[i00];
            CRGB c10 = input[i10];
            CRGB c01 = input[i01];
            CRGB c11 = input[i11];
            CRGB result;
            result.r = bilinearInterpolate(c00.r, c10.r, c01.r, c11.r, dx, dy);
            result.g = bilinearInterpolate(c00.g, c10.g, c01.g, c11.g, dx, dy);
            result.b = bilinearInterpolate(c00.b, c10.b, c01.b, c11.b, dx, dy);
            uint16_t idx = xyMap.mapToIndex(x, y);
            if (idx < n) {
                output[idx] = result;
            }
        }
    }
}
References bilinearInterpolate(), x, xyMap, and y.
Referenced by bilinearExpand(), and fl::ScaleUp::expand().
bilinearExpandArbitraryFloat()
void fl::bilinearExpandArbitraryFloat (const CRGB * input, CRGB * output, uint16_t inputWidth, uint16_t inputHeight, XYMap xyMap)
Definition at line 182 of file bilinear_expansion.cpp.
{
    uint16_t n = xyMap.getTotal();
    uint16_t outputWidth = xyMap.getWidth();
    uint16_t outputHeight = xyMap.getHeight();
    for (uint16_t y = 0; y < outputHeight; y++) {
        for (uint16_t x = 0; x < outputWidth; x++) {
            // Map output pixel to input grid position
            float fx =
                static_cast<float>(x) * (inputWidth - 1) / (outputWidth - 1);
            float fy =
                static_cast<float>(y) * (inputHeight - 1) / (outputHeight - 1);
            uint16_t ix = static_cast<uint16_t>(fx);
            uint16_t iy = static_cast<uint16_t>(fy);
            float dx = fx - ix;
            float dy = fy - iy;
            uint16_t ix1 = (ix + 1 < inputWidth) ? ix + 1 : ix;
            uint16_t iy1 = (iy + 1 < inputHeight) ? iy + 1 : iy;
            uint16_t i00 = iy * inputWidth + ix;
            uint16_t i10 = iy * inputWidth + ix1;
            uint16_t i01 = iy1 * inputWidth + ix;
            uint16_t i11 = iy1 * inputWidth + ix1;
            CRGB c00 = input[i00];
            CRGB c10 = input[i10];
            CRGB c01 = input[i01];
            CRGB c11 = input[i11];
            CRGB result;
            result.r =
                bilinearInterpolateFloat(c00.r, c10.r, c01.r, c11.r, dx, dy);
            result.g =
                bilinearInterpolateFloat(c00.g, c10.g, c01.g, c11.g, dx, dy);
            result.b =
                bilinearInterpolateFloat(c00.b, c10.b, c01.b, c11.b, dx, dy);
            uint16_t idx = xyMap.mapToIndex(x, y);
            if (idx < n) {
                output[idx] = result;
            }
        }
    }
}
References bilinearInterpolateFloat(), x, xyMap, and y.
bilinearExpandFloat()
void fl::bilinearExpandFloat (const CRGB * input, CRGB * output, uint8_t inputWidth, uint8_t inputHeight, XYMap xyMap)
Definition at line 232 of file bilinear_expansion.cpp.
{
    uint8_t outputWidth = xyMap.getWidth();
    uint8_t outputHeight = xyMap.getHeight();
    if (outputWidth != xyMap.getWidth() || outputHeight != xyMap.getHeight()) {
        // xyMap has width and height that do not fit in a uint8_t.
        return;
    }
    uint16_t n = xyMap.getTotal();
    for (uint8_t y = 0; y < outputHeight; y++) {
        for (uint8_t x = 0; x < outputWidth; x++) {
            // Map output pixel to input grid position
            float fx =
                static_cast<float>(x) * (inputWidth - 1) / (outputWidth - 1);
            float fy =
                static_cast<float>(y) * (inputHeight - 1) / (outputHeight - 1);
            uint8_t ix = static_cast<uint8_t>(fx);
            uint8_t iy = static_cast<uint8_t>(fy);
            float dx = fx - ix;
            float dy = fy - iy;
            uint8_t ix1 = (ix + 1 < inputWidth) ? ix + 1 : ix;
            uint8_t iy1 = (iy + 1 < inputHeight) ? iy + 1 : iy;
            uint16_t i00 = iy * inputWidth + ix;
            uint16_t i10 = iy * inputWidth + ix1;
            uint16_t i01 = iy1 * inputWidth + ix;
            uint16_t i11 = iy1 * inputWidth + ix1;
            CRGB c00 = input[i00];
            CRGB c10 = input[i10];
            CRGB c01 = input[i01];
            CRGB c11 = input[i11];
            CRGB result;
            result.r =
                bilinearInterpolateFloat(c00.r, c10.r, c01.r, c11.r, dx, dy);
            result.g =
                bilinearInterpolateFloat(c00.g, c10.g, c01.g, c11.g, dx, dy);
            result.b =
                bilinearInterpolateFloat(c00.b, c10.b, c01.b, c11.b, dx, dy);
            uint16_t idx = xyMap.mapToIndex(x, y);
            if (idx < n) {
                output[idx] = result;
            }
        }
    }
}
References bilinearInterpolateFloat(), x, xyMap, and y.
Referenced by fl::ScaleUp::expand().
bilinearExpandPowerOf2()
void fl::bilinearExpandPowerOf2 (const CRGB * input, CRGB * output, uint8_t inputWidth, uint8_t inputHeight, fl::XYMap xyMap)
Performs bilinear interpolation for upscaling an image.
Parameters
output The output grid to write into the interpolated values.
input The input grid to read from.
inputWidth The width of the input grid.
inputHeight The height of the input grid.
xyMap The XYMap to use to determine where to write the pixel. If the pixel is mapped outside of the range then it is clipped.
Definition at line 85 of file bilinear_expansion.cpp.
{
    uint8_t width = xyMap.getWidth();
    uint8_t height = xyMap.getHeight();
    if (width != xyMap.getWidth() || height != xyMap.getHeight()) {
        // xyMap has width and height that do not fit in an uint16_t.
        return;
    }
    uint16_t n = xyMap.getTotal();
    for (uint8_t y = 0; y < height; y++) {
        for (uint8_t x = 0; x < width; x++) {
            // Use 8-bit fixed-point arithmetic with 8 fractional bits
            // (scale factor of 256)
            uint16_t fx = ((uint16_t)x * (inputWidth - 1) * 256) / (width - 1);
            uint16_t fy =
                ((uint16_t)y * (inputHeight - 1) * 256) / (height - 1);
            uint8_t ix = fx >> 8; // Integer part
            uint8_t iy = fy >> 8;
            uint8_t dx = fx & 0xFF; // Fractional part
            uint8_t dy = fy & 0xFF;
            uint8_t ix1 = (ix + 1 < inputWidth) ? ix + 1 : ix;
            uint8_t iy1 = (iy + 1 < inputHeight) ? iy + 1 : iy;
            uint16_t i00 = iy * inputWidth + ix;
            uint16_t i10 = iy * inputWidth + ix1;
            uint16_t i01 = iy1 * inputWidth + ix;
            uint16_t i11 = iy1 * inputWidth + ix1;
            CRGB c00 = input[i00];
            CRGB c10 = input[i10];
            CRGB c01 = input[i01];
            CRGB c11 = input[i11];
            CRGB result;
            result.r =
                bilinearInterpolatePowerOf2(c00.r, c10.r, c01.r, c11.r, dx, dy);
            result.g =
                bilinearInterpolatePowerOf2(c00.g, c10.g, c01.g, c11.g, dx, dy);
            result.b =
                bilinearInterpolatePowerOf2(c00.b, c10.b, c01.b, c11.b, dx, dy);
            uint16_t idx = xyMap.mapToIndex(x, y);
            if (idx < n) {
                output[idx] = result;
            }
        }
    }
}
References bilinearInterpolatePowerOf2(), x, xyMap, and y.
Referenced by bilinearExpand(), and fl::ScaleUp::expand().
bilinearInterpolate()
uint8_t fl::bilinearInterpolate (uint8_t v00, uint8_t v10, uint8_t v01, uint8_t v11, uint16_t dx, uint16_t dy)
Definition at line 66 of file bilinear_expansion.cpp.
{
    uint16_t dx_inv = 256 - dx;
    uint16_t dy_inv = 256 - dy;
    uint32_t w00 = (uint32_t)dx_inv * dy_inv;
    uint32_t w10 = (uint32_t)dx * dy_inv;
    uint32_t w01 = (uint32_t)dx_inv * dy;
    uint32_t w11 = (uint32_t)dx * dy;
    uint32_t sum = v00 * w00 + v10 * w10 + v01 * w01 + v11 * w11;
    // Normalize the result by dividing by 65536 (shift right by 16 bits),
    // with rounding
    uint8_t result = (uint8_t)((sum + 32768) >> 16);
    return result;
}
Referenced by bilinearExpandArbitrary().
bilinearInterpolateFloat()
uint8_t fl::bilinearInterpolateFloat (uint8_t v00, uint8_t v10, uint8_t v01, uint8_t v11, float dx, float dy)
Definition at line 161 of file bilinear_expansion.cpp.
{
    float dx_inv = 1.0f - dx;
    float dy_inv = 1.0f - dy;
    // Calculate the weights for each corner
    float w00 = dx_inv * dy_inv;
    float w10 = dx * dy_inv;
    float w01 = dx_inv * dy;
    float w11 = dx * dy;
    // Compute the weighted sum
    float sum = v00 * w00 + v10 * w10 + v01 * w01 + v11 * w11;
    // Clamp the result to [0, 255] and round
    uint8_t result = static_cast<uint8_t>(sum + 0.5f);
    return result;
}
Referenced by bilinearExpandArbitraryFloat(), and bilinearExpandFloat().
bilinearInterpolatePowerOf2()
uint8_t fl::bilinearInterpolatePowerOf2 (uint8_t v00, uint8_t v10, uint8_t v01, uint8_t v11, uint8_t dx, uint8_t dy)
Definition at line 137 of file bilinear_expansion.cpp.
{
    uint16_t dx_inv = 256 - dx; // 0 to 256
    uint16_t dy_inv = 256 - dy; // 0 to 256
    // Scale down weights to fit into uint16_t
    uint16_t w00 = (dx_inv * dy_inv) >> 8; // Max value 256
    uint16_t w10 = (dx * dy_inv) >> 8;
    uint16_t w01 = (dx_inv * dy) >> 8;
    uint16_t w11 = (dx * dy) >> 8;
    // Sum of weights should be approximately 256
    uint16_t weight_sum = w00 + w10 + w01 + w11;
    // Compute the weighted sum of pixel values
    uint16_t sum = v00 * w00 + v10 * w10 + v01 * w01 + v11 * w11;
    // Normalize the result
    uint8_t result = (sum + (weight_sum >> 1)) / weight_sum;
    return result;
}
Referenced by bilinearExpandPowerOf2().
blend() [1/4]
CHSV fl::blend (const CHSV & p1, const CHSV & p2, fract8 amountOfP2, TGradientDirectionCode directionCode)
Definition at line 132 of file colorutils.cpp.
{
    CHSV nu(p1);
    nblend(nu, p2, amountOfP2, directionCode);
    return nu;
}
References nblend().
blend() [2/4]
CHSV * fl::blend (const CHSV * src1, const CHSV * src2, CHSV * dest, uint16_t count, fract8 amountOfsrc2, TGradientDirectionCode directionCode)
Definition at line 139 of file colorutils.cpp.
{
    for (uint16_t i = 0; i < count; ++i) {
        dest[i] = blend(src1[i], src2[i], amountOfsrc2, directionCode);
    }
    return dest;
}
References blend().
blend() [3/4]
CRGB fl::blend (const CRGB & p1, const CRGB & p2, fract8 amountOfP2)
Definition at line 60 of file colorutils.cpp.
{
    CRGB nu(p1);
    nblend(nu, p2, amountOfP2);
    return nu;
}
References nblend().
Referenced by blend(), blend(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPalette(), ColorFromPaletteExtended(), ColorFromPaletteExtended(), ColorFromPaletteExtended(), fl::TwinkleFox::drawTwinkleFox(), fl::LUT< uint16_t >::interp16(), fl::LUT< uint16_t >::interp8(), and MyColorFromPaletteExtended().
blend() [4/4]
CRGB * fl::blend (const CRGB * src1, const CRGB * src2, CRGB * dest, uint16_t count, fract8 amountOfsrc2)
Definition at line 66 of file colorutils.cpp.
{
    for (uint16_t i = 0; i < count; ++i) {
        dest[i] = blend(src1[i], src2[i], amountOfsrc2);
    }
    return dest;
}
References blend().
blur1d()
void fl::blur1d (CRGB * leds, uint16_t numLeds, fract8 blur_amount)
One-dimensional blur filter.
Spreads light to 2 line neighbors.
0 = no spread at all
64 = moderate spreading
172 = maximum smooth, even spreading
173..255 = wider spreading, but increasing flicker
Total light is NOT entirely conserved, so many repeated calls to 'blur' will also result in the light fading, eventually all the way to black; this is by design so that it can be used to (slowly) clear the LEDs to black.
Parameters
leds a pointer to the LED array to blur
numLeds the number of LEDs to blur
blur_amount the amount of blur to apply
Definition at line 54 of file blur.cpp.
{
    uint8_t keep = 255 - blur_amount;
    uint8_t seep = blur_amount >> 1;
    CRGB carryover = CRGB::Black;
    for (uint16_t i = 0; i < numLeds; ++i) {
        CRGB cur = leds[i];
        CRGB part = cur;
        part.nscale8(seep);
        cur.nscale8(keep);
        cur += carryover;
        if (i)
            leds[i - 1] += part;
        leds[i] = cur;
        carryover = part;
    }
}
References CRGB::Black, leds, and CRGB::nscale8().
blur2d() [1/2]
void fl::blur2d (CRGB * leds, uint8_t width, uint8_t height, fract8 blur_amount)
Legacy version of blur2d, which does not require an XYMap but instead implicitly binds to XY() function.
If you are hitting a linker error here, then use blur2d(..., const fl::XYMap& xymap) instead.
Definition at line 77 of file blur.cpp.
{
    XYMap xy =
        XYMap::constructWithUserFunction(width, height, xy_legacy_wrapper);
    blur2d(leds, width, height, blur_amount, xy);
}
References blur2d(), fl::XYMap::constructWithUserFunction(), leds, and xy().
blur2d() [2/2]
void fl::blur2d (CRGB * leds, uint8_t width, uint8_t height, fract8 blur_amount, const fl::XYMap & xymap)
Two-dimensional blur filter.
Spreads light to 8 XY neighbors.
0 = no spread at all
64 = moderate spreading
172 = maximum smooth, even spreading
173..255 = wider spreading, but increasing flicker
Total light is NOT entirely conserved, so many repeated calls to 'blur' will also result in the light fading, eventually all the way to black; this is by design so that it can be used to (slowly) clear the LEDs to black.
Parameters
leds a pointer to the LED array to blur
width the width of the matrix
height the height of the matrix
blur_amount the amount of blur to apply
Definition at line 71 of file blur.cpp.
{
    blurRows(leds, width, height, blur_amount, xymap);
    blurColumns(leds, width, height, blur_amount, xymap);
}
References blurColumns(), blurRows(), leds, and xymap.
Referenced by blur2d(), fl::Blend2d::draw(), and loop().
blurColumns()
void fl::blurColumns (CRGB * leds, uint8_t width, uint8_t height, fract8 blur_amount, const fl::XYMap & xymap)
Perform a blur1d() on every column of a rectangular matrix.
See also
blur1d()
Parameters
leds a pointer to the LED array to blur
width the width of the matrix
height the height of the matrix
blur_amount the amount of blur to apply
Definition at line 111 of file blur.cpp.
{
    // blur columns
    uint8_t keep = 255 - blur_amount;
    uint8_t seep = blur_amount >> 1;
    for (uint8_t col = 0; col < width; ++col) {
        CRGB carryover = CRGB::Black;
        for (uint8_t i = 0; i < height; ++i) {
            CRGB cur = leds[xyMap.mapToIndex(col, i)];
            CRGB part = cur;
            part.nscale8(seep);
            cur.nscale8(keep);
            cur += carryover;
            if (i)
                leds[xyMap.mapToIndex(col, i - 1)] += part;
            leds[xyMap.mapToIndex(col, i)] = cur;
            carryover = part;
        }
    }
}
References CRGB::Black, leds, CRGB::nscale8(), and xyMap.
Referenced by blur2d().
blurRows()
void fl::blurRows (CRGB * leds, uint8_t width, uint8_t height, fract8 blur_amount, const fl::XYMap & xymap)
Perform a blur1d() on every row of a rectangular matrix.
See also
blur1d()
Parameters
leds a pointer to the LED array to blur
width the width of the matrix
height the height of the matrix
blur_amount the amount of blur to apply
Definition at line 83 of file blur.cpp.
{
    /*    for( uint8_t row = 0; row < height; row++) {
            CRGB* rowbase = leds + (row * width);
            blur1d( rowbase, width, blur_amount);
        }
    */
    // blur rows same as columns, for irregular matrix
    uint8_t keep = 255 - blur_amount;
    uint8_t seep = blur_amount >> 1;
    for (uint8_t row = 0; row < height; row++) {
        CRGB carryover = CRGB::Black;
        for (uint8_t i = 0; i < width; i++) {
            CRGB cur = leds[xyMap.mapToIndex(i, row)];
            CRGB part = cur;
            part.nscale8(seep);
            cur.nscale8(keep);
            cur += carryover;
            if (i)
                leds[xyMap.mapToIndex(i - 1, row)] += part;
            leds[xyMap.mapToIndex(i, row)] = cur;
            carryover = part;
        }
    }
}
References CRGB::Black, leds, CRGB::nscale8(), and xyMap.
Referenced by blur2d().
ceil()
template<typename T> T fl::ceil (T value) inline
Definition at line 18 of file math.h.
{
    if (value <= 0) {
        return static_cast<T>(static_cast<int>(value));
    }
    return static_cast<T>(::ceil(static_cast<float>(value)));
}
References ceil().
Referenced by ceil().
clamp()
template<typename T> FASTLED_FORCE_INLINE T fl::clamp (T value, T min, T max)
Definition at line 10 of file clamp.h.
{
    if (value < min) {
        return min;
    }
    if (value > max) {
        return max;
    }
    return value;
}
References FASTLED_FORCE_INLINE.
Referenced by fl::XYPath::calculateSteps(), fl::wave_detail::float_to_fixed(), fl::MatrixSlice< T >::getLocalCoord(), loop(), map_range_clamped(), fl::XYMap::mapToIndex(), fl::WaveSimulation1D::setf(), fl::WaveSimulation2D::setf(), fl::HashMap< Key, T, Hash, KeyEqual >::setLoadFactor(), and showGenerative().
clear() [1/2]
template<int N> void fl::clear (CRGB(&) arr[N]) inline
Definition at line 8 of file clear.h.
{
    for (int i = 0; i < N; ++i) {
        arr[i] = CRGB::Black;
    }
}
References CRGB::Black.
Referenced by clearLeds(), loop(), and showGenerative().
clear() [2/2]
void fl::clear (Leds & leds) inline
Definition at line 14 of file clear.h.
{ leds.fill(CRGB::Black); }
References CRGB::Black, and leds.
ColorFromPalette() [1/8]
CHSV fl::ColorFromPalette (const CHSVPalette16 & pal, uint8_t index, uint8_t brightness, TBlendType blendType)
Definition at line 771 of file colorutils.cpp.
{
    if (blendType == LINEARBLEND_NOWRAP) {
        index = map8(index, 0, 239); // Blend range is affected by lo4 blend of
                                     // values, remap to avoid wrapping
    }
    //      hi4 = index >> 4;
    uint8_t hi4 = lsrX4(index);
    uint8_t lo4 = index & 0x0F;
    //  CRGB rgb1 = pal[ hi4];
    const CHSV *entry = &(pal[0]) + hi4;
    uint8_t hue1 = entry->hue;
    uint8_t sat1 = entry->sat;
    uint8_t val1 = entry->val;
    uint8_t blend = lo4 && (blendType != NOBLEND);
    if (blend) {
        if (hi4 == 15) {
            entry = &(pal[0]);
        } else {
            ++entry;
        }
        uint8_t f2 = lo4 << 4;
        uint8_t f1 = 255 - f2;
        uint8_t hue2 = entry->hue;
        uint8_t sat2 = entry->sat;
        uint8_t val2 = entry->val;
        // Now some special casing for blending to or from
        // either black or white.  Black and white don't have
        // proper 'hue' of their own, so when ramping from
        // something else to/from black/white, we set the 'hue'
        // of the black/white color to be the same as the hue
        // of the other color, so that you get the expected
        // brightness or saturation ramp, with hue staying
        // constant:
        // If we are starting from white (sat=0)
        // or black (val=0), adopt the target hue.
        if (sat1 == 0 || val1 == 0) {
            hue1 = hue2;
        }
        // If we are ending at white (sat=0)
        // or black (val=0), adopt the starting hue.
        if (sat2 == 0 || val2 == 0) {
            hue2 = hue1;
        }
        sat1 = scale8_LEAVING_R1_DIRTY(sat1, f1);
        val1 = scale8_LEAVING_R1_DIRTY(val1, f1);
        sat2 = scale8_LEAVING_R1_DIRTY(sat2, f2);
        val2 = scale8_LEAVING_R1_DIRTY(val2, f2);
        //    cleanup_R1();
        // These sums can't overflow, so no qadd8 needed.
        sat1 += sat2;
        val1 += val2;
        uint8_t deltaHue = (uint8_t)(hue2 - hue1);
        if (deltaHue & 0x80) {
            // go backwards
            hue1 -= scale8(256 - deltaHue, f2);
        } else {
            // go forwards
            hue1 += scale8(deltaHue, f2);
        }
        cleanup_R1();
    }
    if (brightness != 255) {
        val1 = scale8_video(val1, brightness);
    }
    return CHSV(hue1, sat1, val1);
}
References blend(), brightness, cleanup_R1(), lsrX4(), map8(), scale8(), scale8_LEAVING_R1_DIRTY(), and scale8_video().
ColorFromPalette() [2/8]
CHSV fl::ColorFromPalette (const CHSVPalette256 & pal, uint8_t index, uint8_t brightness, TBlendType)
Definition at line 951 of file colorutils.cpp.
{
    CHSV hsv = *(&(pal[0]) + index);
    if (brightness != 255) {
        hsv.value = scale8_video(hsv.value, brightness);
    }
    return hsv;
}
References brightness, and scale8_video().
ColorFromPalette() [3/8]
CHSV fl::ColorFromPalette (const CHSVPalette32 & pal, uint8_t index, uint8_t brightness, TBlendType blendType)
Definition at line 858 of file colorutils.cpp.
{
    if (blendType == LINEARBLEND_NOWRAP) {
        index = map8(index, 0, 247); // Blend range is affected by lo3 blend of
                                     // values, remap to avoid wrapping
    }
    uint8_t hi5 = index;
#if defined(__AVR__)
    hi5 /= 2;
    hi5 /= 2;
    hi5 /= 2;
#else
    hi5 >>= 3;
#endif
    uint8_t lo3 = index & 0x07;
    uint8_t hi5XsizeofCHSV = hi5 * sizeof(CHSV);
    const CHSV *entry = (CHSV *)((uint8_t *)(&(pal[0])) + hi5XsizeofCHSV);
    uint8_t hue1 = entry->hue;
    uint8_t sat1 = entry->sat;
    uint8_t val1 = entry->val;
    uint8_t blend = lo3 && (blendType != NOBLEND);
    if (blend) {
        if (hi5 == 31) {
            entry = &(pal[0]);
        } else {
            ++entry;
        }
        uint8_t f2 = lo3 << 5;
        uint8_t f1 = 255 - f2;
        uint8_t hue2 = entry->hue;
        uint8_t sat2 = entry->sat;
        uint8_t val2 = entry->val;
        // Now some special casing for blending to or from
        // either black or white.  Black and white don't have
        // proper 'hue' of their own, so when ramping from
        // something else to/from black/white, we set the 'hue'
        // of the black/white color to be the same as the hue
        // of the other color, so that you get the expected
        // brightness or saturation ramp, with hue staying
        // constant:
        // If we are starting from white (sat=0)
        // or black (val=0), adopt the target hue.
        if (sat1 == 0 || val1 == 0) {
            hue1 = hue2;
        }
        // If we are ending at white (sat=0)
        // or black (val=0), adopt the starting hue.
        if (sat2 == 0 || val2 == 0) {
            hue2 = hue1;
        }
        sat1 = scale8_LEAVING_R1_DIRTY(sat1, f1);
        val1 = scale8_LEAVING_R1_DIRTY(val1, f1);
        sat2 = scale8_LEAVING_R1_DIRTY(sat2, f2);
        val2 = scale8_LEAVING_R1_DIRTY(val2, f2);
        //    cleanup_R1();
        // These sums can't overflow, so no qadd8 needed.
        sat1 += sat2;
        val1 += val2;
        uint8_t deltaHue = (uint8_t)(hue2 - hue1);
        if (deltaHue & 0x80) {
            // go backwards
            hue1 -= scale8(256 - deltaHue, f2);
        } else {
            // go forwards
            hue1 += scale8(deltaHue, f2);
        }
        cleanup_R1();
    }
    if (brightness != 255) {
        val1 = scale8_video(val1, brightness);
    }
    return CHSV(hue1, sat1, val1);
}
References blend(), brightness, cleanup_R1(), map8(), scale8(), scale8_LEAVING_R1_DIRTY(), and scale8_video().
ColorFromPalette() [4/8]
CRGB fl::ColorFromPalette (const CRGBPalette16 & pal, uint8_t index, uint8_t brightness, TBlendType blendType)
Definition at line 299 of file colorutils.cpp.
{
    if (blendType == LINEARBLEND_NOWRAP) {
        index = map8(index, 0, 239); // Blend range is affected by lo4 blend of
                                     // values, remap to avoid wrapping
    }
    //      hi4 = index >> 4;
    uint8_t hi4 = lsrX4(index);
    uint8_t lo4 = index & 0x0F;
    // const CRGB* entry = &(pal[0]) + hi4;
    // since hi4 is always 0..15, hi4 * sizeof(CRGB) can be a single-byte value,
    // instead of the two byte 'int' that avr-gcc defaults to.
    // So, we multiply hi4 X sizeof(CRGB), giving hi4XsizeofCRGB;
    uint8_t hi4XsizeofCRGB = hi4 * sizeof(CRGB);
    // We then add that to a base array pointer.
    const CRGB *entry = (CRGB *)((uint8_t *)(&(pal[0])) + hi4XsizeofCRGB);
    uint8_t blend = lo4 && (blendType != NOBLEND);
    uint8_t red1 = entry->red;
    uint8_t green1 = entry->green;
    uint8_t blue1 = entry->blue;
    if (blend) {
        if (hi4 == 15) {
            entry = &(pal[0]);
        } else {
            ++entry;
        }
        uint8_t f2 = lo4 << 4;
        uint8_t f1 = 255 - f2;
        //    rgb1.nscale8(f1);
        uint8_t red2 = entry->red;
        red1 = scale8_LEAVING_R1_DIRTY(red1, f1);
        red2 = scale8_LEAVING_R1_DIRTY(red2, f2);
        red1 += red2;
        uint8_t green2 = entry->green;
        green1 = scale8_LEAVING_R1_DIRTY(green1, f1);
        green2 = scale8_LEAVING_R1_DIRTY(green2, f2);
        green1 += green2;
        uint8_t blue2 = entry->blue;
        blue1 = scale8_LEAVING_R1_DIRTY(blue1, f1);
        blue2 = scale8_LEAVING_R1_DIRTY(blue2, f2);
        blue1 += blue2;
        cleanup_R1();
    }
    if (brightness != 255) {
        if (brightness) {
            ++brightness; // adjust for rounding
            // Now, since brightness is nonzero, we don't need the full
            // scale8_video logic; we can just to scale8 and then add one
            // (unless scale8 fixed) to all nonzero inputs.
            if (red1) {
                red1 = scale8_LEAVING_R1_DIRTY(red1, brightness);
#if !(FASTLED_SCALE8_FIXED == 1)
                ++red1;
#endif
            }
            if (green1) {
                green1 = scale8_LEAVING_R1_DIRTY(green1, brightness);
#if !(FASTLED_SCALE8_FIXED == 1)
                ++green1;
#endif
            }
            if (blue1) {
                blue1 = scale8_LEAVING_R1_DIRTY(blue1, brightness);
#if !(FASTLED_SCALE8_FIXED == 1)
                ++blue1;
#endif
            }
            cleanup_R1();
        } else {
            red1 = 0;
            green1 = 0;
            blue1 = 0;
        }
    }
    return CRGB(red1, green1, blue1);
}
References blend(), brightness, cleanup_R1(), lsrX4(), map8(), and scale8_LEAVING_R1_DIRTY().
Referenced by fl::DemoReel100::bpm(), fl::TwinkleFox::computeOneTwinkle(), fl::Fire2012::draw(), Fire2023(), loop(), fl::NoisePalette::mapNoiseToLEDsUsingPalette(), fl::Pacifica::pacifica_one_layer(), UpscalePalette(), UpscalePalette(), UpscalePalette(), and UpscalePalette().
ColorFromPalette() [5/8]
CRGB fl::ColorFromPalette (const CRGBPalette256 & pal, uint8_t index, uint8_t brightness, TBlendType)
Definition at line 704 of file colorutils.cpp.
{
    const CRGB *entry = &(pal[0]) + index;
    uint8_t red = entry->red;
    uint8_t green = entry->green;
    uint8_t blue = entry->blue;
    if (brightness != 255) {
        ++brightness; // adjust for rounding
        red = scale8_video_LEAVING_R1_DIRTY(red, brightness);
        green = scale8_video_LEAVING_R1_DIRTY(green, brightness);
        blue = scale8_video_LEAVING_R1_DIRTY(blue, brightness);
        cleanup_R1();
    }
    return CRGB(red, green, blue);
}
References brightness, cleanup_R1(), and scale8_video_LEAVING_R1_DIRTY().
ColorFromPalette() [6/8]
CRGB fl::ColorFromPalette (const CRGBPalette32 & pal, uint8_t index, uint8_t brightness, TBlendType blendType)
Definition at line 520 of file colorutils.cpp.
{
    if (blendType == LINEARBLEND_NOWRAP) {
        index = map8(index, 0, 247); // Blend range is affected by lo3 blend of
                                     // values, remap to avoid wrapping
    }
    uint8_t hi5 = index;
#if defined(__AVR__)
    hi5 /= 2;
    hi5 /= 2;
    hi5 /= 2;
#else
    hi5 >>= 3;
#endif
    uint8_t lo3 = index & 0x07;
    // const CRGB* entry = &(pal[0]) + hi5;
    // since hi5 is always 0..31, hi4 * sizeof(CRGB) can be a single-byte value,
    // instead of the two byte 'int' that avr-gcc defaults to.
    // So, we multiply hi5 X sizeof(CRGB), giving hi5XsizeofCRGB;
    uint8_t hi5XsizeofCRGB = hi5 * sizeof(CRGB);
    // We then add that to a base array pointer.
    const CRGB *entry = (CRGB *)((uint8_t *)(&(pal[0])) + hi5XsizeofCRGB);
    uint8_t red1 = entry->red;
    uint8_t green1 = entry->green;
    uint8_t blue1 = entry->blue;
    uint8_t blend = lo3 && (blendType != NOBLEND);
    if (blend) {
        if (hi5 == 31) {
            entry = &(pal[0]);
        } else {
            ++entry;
        }
        uint8_t f2 = lo3 << 5;
        uint8_t f1 = 255 - f2;
        uint8_t red2 = entry->red;
        red1 = scale8_LEAVING_R1_DIRTY(red1, f1);
        red2 = scale8_LEAVING_R1_DIRTY(red2, f2);
        red1 += red2;
        uint8_t green2 = entry->green;
        green1 = scale8_LEAVING_R1_DIRTY(green1, f1);
        green2 = scale8_LEAVING_R1_DIRTY(green2, f2);
        green1 += green2;
        uint8_t blue2 = entry->blue;
        blue1 = scale8_LEAVING_R1_DIRTY(blue1, f1);
        blue2 = scale8_LEAVING_R1_DIRTY(blue2, f2);
        blue1 += blue2;
        cleanup_R1();
    }
    if (brightness != 255) {
        if (brightness) {
            ++brightness; // adjust for rounding
            // Now, since brightness is nonzero, we don't need the full
            // scale8_video logic; we can just to scale8 and then add one
            // (unless scale8 fixed) to all nonzero inputs.
            if (red1) {
                red1 = scale8_LEAVING_R1_DIRTY(red1, brightness);
#if !(FASTLED_SCALE8_FIXED == 1)
                ++red1;
#endif
            }
            if (green1) {
                green1 = scale8_LEAVING_R1_DIRTY(green1, brightness);
#if !(FASTLED_SCALE8_FIXED == 1)
                ++green1;
#endif
            }
            if (blue1) {
                blue1 = scale8_LEAVING_R1_DIRTY(blue1, brightness);
#if !(FASTLED_SCALE8_FIXED == 1)
                ++blue1;
#endif
            }
            cleanup_R1();
        } else {
            red1 = 0;
            green1 = 0;
            blue1 = 0;
        }
    }
    return CRGB(red1, green1, blue1);
}
References blend(), brightness, cleanup_R1(), map8(), and scale8_LEAVING_R1_DIRTY().
ColorFromPalette() [7/8]
CRGB fl::ColorFromPalette (const TProgmemRGBPalette16 & pal, uint8_t index, uint8_t brightness, TBlendType blendType)
Definition at line 437 of file colorutils.cpp.
{
    if (blendType == LINEARBLEND_NOWRAP) {
        index = map8(index, 0, 239); // Blend range is affected by lo4 blend of
                                     // values, remap to avoid wrapping
    }
    //      hi4 = index >> 4;
    uint8_t hi4 = lsrX4(index);
    uint8_t lo4 = index & 0x0F;
    CRGB entry(FL_PGM_READ_DWORD_NEAR(&(pal[0]) + hi4));
    uint8_t red1 = entry.red;
    uint8_t green1 = entry.green;
    uint8_t blue1 = entry.blue;
    uint8_t blend = lo4 && (blendType != NOBLEND);
    if (blend) {
        if (hi4 == 15) {
            entry = FL_PGM_READ_DWORD_NEAR(&(pal[0]));
        } else {
            entry = FL_PGM_READ_DWORD_NEAR(&(pal[1]) + hi4);
        }
        uint8_t f2 = lo4 << 4;
        uint8_t f1 = 255 - f2;
        uint8_t red2 = entry.red;
        red1 = scale8_LEAVING_R1_DIRTY(red1, f1);
        red2 = scale8_LEAVING_R1_DIRTY(red2, f2);
        red1 += red2;
        uint8_t green2 = entry.green;
        green1 = scale8_LEAVING_R1_DIRTY(green1, f1);
        green2 = scale8_LEAVING_R1_DIRTY(green2, f2);
        green1 += green2;
        uint8_t blue2 = entry.blue;
        blue1 = scale8_LEAVING_R1_DIRTY(blue1, f1);
        blue2 = scale8_LEAVING_R1_DIRTY(blue2, f2);
        blue1 += blue2;
        cleanup_R1();
    }
    if (brightness != 255) {
        if (brightness) {
            ++brightness; // adjust for rounding
            // Now, since brightness is nonzero, we don't need the full
            // scale8_video logic; we can just to scale8 and then add one
            // (unless scale8 fixed) to all nonzero inputs.
            if (red1) {
                red1 = scale8_LEAVING_R1_DIRTY(red1, brightness);
#if !(FASTLED_SCALE8_FIXED == 1)
                ++red1;
#endif
            }
            if (green1) {
                green1 = scale8_LEAVING_R1_DIRTY(green1, brightness);
#if !(FASTLED_SCALE8_FIXED == 1)
                ++green1;
#endif
            }
            if (blue1) {
                blue1 = scale8_LEAVING_R1_DIRTY(blue1, brightness);
#if !(FASTLED_SCALE8_FIXED == 1)
                ++blue1;
#endif
            }
            cleanup_R1();
        } else {
            red1 = 0;
            green1 = 0;
            blue1 = 0;
        }
    }
    return CRGB(red1, green1, blue1);
}
References blend(), brightness, cleanup_R1(), FL_PGM_READ_DWORD_NEAR, lsrX4(), map8(), and scale8_LEAVING_R1_DIRTY().
ColorFromPalette() [8/8]
CRGB fl::ColorFromPalette (const TProgmemRGBPalette32 & pal, uint8_t index, uint8_t brightness, TBlendType blendType)
Definition at line 615 of file colorutils.cpp.
{
    if (blendType == LINEARBLEND_NOWRAP) {
        index = map8(index, 0, 247); // Blend range is affected by lo3 blend of
                                     // values, remap to avoid wrapping
    }
    uint8_t hi5 = index;
#if defined(__AVR__)
    hi5 /= 2;
    hi5 /= 2;
    hi5 /= 2;
#else
    hi5 >>= 3;
#endif
    uint8_t lo3 = index & 0x07;
    CRGB entry(FL_PGM_READ_DWORD_NEAR(&(pal[0]) + hi5));
    uint8_t red1 = entry.red;
    uint8_t green1 = entry.green;
    uint8_t blue1 = entry.blue;
    uint8_t blend = lo3 && (blendType != NOBLEND);
    if (blend) {
        if (hi5 == 31) {
            entry = FL_PGM_READ_DWORD_NEAR(&(pal[0]));
        } else {
            entry = FL_PGM_READ_DWORD_NEAR(&(pal[1]) + hi5);
        }
        uint8_t f2 = lo3 << 5;
        uint8_t f1 = 255 - f2;
        uint8_t red2 = entry.red;
        red1 = scale8_LEAVING_R1_DIRTY(red1, f1);
        red2 = scale8_LEAVING_R1_DIRTY(red2, f2);
        red1 += red2;
        uint8_t green2 = entry.green;
        green1 = scale8_LEAVING_R1_DIRTY(green1, f1);
        green2 = scale8_LEAVING_R1_DIRTY(green2, f2);
        green1 += green2;
        uint8_t blue2 = entry.blue;
        blue1 = scale8_LEAVING_R1_DIRTY(blue1, f1);
        blue2 = scale8_LEAVING_R1_DIRTY(blue2, f2);
        blue1 += blue2;
        cleanup_R1();
    }
    if (brightness != 255) {
        if (brightness) {
            ++brightness; // adjust for rounding
            // Now, since brightness is nonzero, we don't need the full
            // scale8_video logic; we can just to scale8 and then add one
            // (unless scale8 fixed) to all nonzero inputs.
            if (red1) {
                red1 = scale8_LEAVING_R1_DIRTY(red1, brightness);
#if !(FASTLED_SCALE8_FIXED == 1)
                ++red1;
#endif
            }
            if (green1) {
                green1 = scale8_LEAVING_R1_DIRTY(green1, brightness);
#if !(FASTLED_SCALE8_FIXED == 1)
                ++green1;
#endif
            }
            if (blue1) {
                blue1 = scale8_LEAVING_R1_DIRTY(blue1, brightness);
#if !(FASTLED_SCALE8_FIXED == 1)
                ++blue1;
#endif
            }
            cleanup_R1();
        } else {
            red1 = 0;
            green1 = 0;
            blue1 = 0;
        }
    }
    return CRGB(red1, green1, blue1);
}
References blend(), brightness, cleanup_R1(), FL_PGM_READ_DWORD_NEAR, map8(), and scale8_LEAVING_R1_DIRTY().
ColorFromPaletteExtended() [1/3]
CRGB fl::ColorFromPaletteExtended (const CRGBPalette16 & pal, uint16_t index, uint8_t brightness, TBlendType blendType)
Definition at line 389 of file colorutils.cpp.
{
    // Extract the four most significant bits of the index as a palette index.
    uint8_t index_4bit = index >> 12;
    // Calculate the 8-bit offset from the palette index.
    uint8_t offset = (uint8_t)(index >> 4);
    // Get the palette entry from the 4-bit index
    const CRGB *entry = &(pal[0]) + index_4bit;
    uint8_t red1 = entry->red;
    uint8_t green1 = entry->green;
    uint8_t blue1 = entry->blue;
    uint8_t blend = offset && (blendType != NOBLEND);
    if (blend) {
        if (index_4bit == 15) {
            entry = &(pal[0]);
        } else {
            entry++;
        }
        // Calculate the scaling factor and scaled values for the lower palette
        // value.
        uint8_t f1 = 255 - offset;
        red1 = scale8_LEAVING_R1_DIRTY(red1, f1);
        green1 = scale8_LEAVING_R1_DIRTY(green1, f1);
        blue1 = scale8_LEAVING_R1_DIRTY(blue1, f1);
        // Calculate the scaled values for the neighbouring palette value.
        uint8_t red2 = entry->red;
        uint8_t green2 = entry->green;
        uint8_t blue2 = entry->blue;
        red2 = scale8_LEAVING_R1_DIRTY(red2, offset);
        green2 = scale8_LEAVING_R1_DIRTY(green2, offset);
        blue2 = scale8_LEAVING_R1_DIRTY(blue2, offset);
        cleanup_R1();
        // These sums can't overflow, so no qadd8 needed.
        red1 += red2;
        green1 += green2;
        blue1 += blue2;
    }
    if (brightness != 255) {
        // nscale8x3_video(red1, green1, blue1, brightness);
        nscale8x3(red1, green1, blue1, brightness);
    }
    return CRGB(red1, green1, blue1);
}
References blend(), brightness, cleanup_R1(), nscale8x3(), offset(), and scale8_LEAVING_R1_DIRTY().
ColorFromPaletteExtended() [2/3]
CRGB fl::ColorFromPaletteExtended (const CRGBPalette256 & pal, uint16_t index, uint8_t brightness, TBlendType blendType)
Definition at line 723 of file colorutils.cpp.
{
    // Extract the eight most significant bits of the index as a palette index.
    uint8_t index_8bit = index >> 8;
    // Calculate the 8-bit offset from the palette index.
    uint8_t offset = index & 0xff;
    // Get the palette entry from the 8-bit index
    const CRGB *entry = &(pal[0]) + index_8bit;
    uint8_t red1 = entry->red;
    uint8_t green1 = entry->green;
    uint8_t blue1 = entry->blue;
    uint8_t blend = offset && (blendType != NOBLEND);
    if (blend) {
        if (index_8bit == 255) {
            entry = &(pal[0]);
        } else {
            entry++;
        }
        // Calculate the scaling factor and scaled values for the lower palette
        // value.
        uint8_t f1 = 255 - offset;
        red1 = scale8_LEAVING_R1_DIRTY(red1, f1);
        green1 = scale8_LEAVING_R1_DIRTY(green1, f1);
        blue1 = scale8_LEAVING_R1_DIRTY(blue1, f1);
        // Calculate the scaled values for the neighbouring palette value.
        uint8_t red2 = entry->red;
        uint8_t green2 = entry->green;
        uint8_t blue2 = entry->blue;
        red2 = scale8_LEAVING_R1_DIRTY(red2, offset);
        green2 = scale8_LEAVING_R1_DIRTY(green2, offset);
        blue2 = scale8_LEAVING_R1_DIRTY(blue2, offset);
        cleanup_R1();
        // These sums can't overflow, so no qadd8 needed.
        red1 += red2;
        green1 += green2;
        blue1 += blue2;
    }
    if (brightness != 255) {
        // nscale8x3_video(red1, green1, blue1, brightness);
        nscale8x3(red1, green1, blue1, brightness);
    }
    return CRGB(red1, green1, blue1);
}
References blend(), brightness, cleanup_R1(), nscale8x3(), offset(), and scale8_LEAVING_R1_DIRTY().
ColorFromPaletteExtended() [3/3]
CRGB fl::ColorFromPaletteExtended (const CRGBPalette32 & pal, uint16_t index, uint8_t brightness, TBlendType blendType)
Definition at line 252 of file colorutils.cpp.
{
    // Extract the five most significant bits of the index as a palette index.
    uint8_t index_5bit = (index >> 11);
    // Calculate the 8-bit offset from the palette index.
    uint8_t offset = (uint8_t)(index >> 3);
    // Get the palette entry from the 5-bit index
    const CRGB *entry = &(pal[0]) + index_5bit;
    uint8_t red1 = entry->red;
    uint8_t green1 = entry->green;
    uint8_t blue1 = entry->blue;
    uint8_t blend = offset && (blendType != NOBLEND);
    if (blend) {
        if (index_5bit == 31) {
            entry = &(pal[0]);
        } else {
            entry++;
        }
        // Calculate the scaling factor and scaled values for the lower palette
        // value.
        uint8_t f1 = 255 - offset;
        red1 = scale8_LEAVING_R1_DIRTY(red1, f1);
        green1 = scale8_LEAVING_R1_DIRTY(green1, f1);
        blue1 = scale8_LEAVING_R1_DIRTY(blue1, f1);
        // Calculate the scaled values for the neighbouring palette value.
        uint8_t red2 = entry->red;
        uint8_t green2 = entry->green;
        uint8_t blue2 = entry->blue;
        red2 = scale8_LEAVING_R1_DIRTY(red2, offset);
        green2 = scale8_LEAVING_R1_DIRTY(green2, offset);
        blue2 = scale8_LEAVING_R1_DIRTY(blue2, offset);
        cleanup_R1();
        // These sums can't overflow, so no qadd8 needed.
        red1 += red2;
        green1 += green2;
        blue1 += blue2;
    }
    if (brightness != 255) {
        nscale8x3_video(red1, green1, blue1, brightness);
    }
    return CRGB(red1, green1, blue1);
}
References blend(), brightness, cleanup_R1(), nscale8x3_video(), offset(), and scale8_LEAVING_R1_DIRTY().
cos16lut()
static FASTLED_FORCE_INLINE int16_t fl::cos16lut (uint16_t angle) static
Definition at line 63 of file sin32.h.
{
    uint8_t angle256 = angle / 256;
    int32_t subAngle = angle % 256;
    return (cosArray[angle256] * (256 - subAngle) +
            cosArray[angle256 + 1] * subAngle) /
           256;
}
References cosArray, and FASTLED_FORCE_INLINE.
cos32()
static FASTLED_FORCE_INLINE int32_t fl::cos32 (uint32_t angle) static
Definition at line 44 of file sin32.h.
{
    uint8_t angle256 = angle / 65536;
    int32_t subAngle = angle % 65536;
    return cosArray[angle256] * (65536 - subAngle) +
           cosArray[angle256 + 1] * subAngle;
}
References cosArray, and FASTLED_FORCE_INLINE.
downscale()
void fl::downscale (const CRGB * src, const XYMap & srcXY, CRGB * dst, const XYMap & dstXY)
Definition at line 153 of file downscale.cpp.
{
    uint16_t srcWidth = srcXY.getWidth();
    uint16_t srcHeight = srcXY.getHeight();
    uint16_t dstWidth = dstXY.getWidth();
    uint16_t dstHeight = dstXY.getHeight();
    FASTLED_ASSERT(dstWidth <= srcWidth,
                   "Destination width must be <= source width");
    FASTLED_ASSERT(dstHeight <= srcHeight,
                   "Destination height must be <= source height");
    const bool destination_is_half_of_source =
        (dstWidth * 2 == srcWidth) && (dstHeight * 2 == srcHeight);
    // Attempt to use the downscaleHalf function if the destination is half the
    // size of the source.
    if (destination_is_half_of_source) {
        const bool both_rectangles = (srcXY.getType() == XYMap::kLineByLine) &&
                                     (dstXY.getType() == XYMap::kLineByLine);
        if (both_rectangles) {
            // If both source and destination are rectangular, we can use the
            // optimized version
            downscaleHalf(src, srcWidth, srcHeight, dst);
        } else {
            // Otherwise, we need to use the mapped version
            downscaleHalf(src, srcXY, dst, dstXY);
        }
        return;
    }
    downscaleArbitrary(src, srcXY, dst, dstXY);
}
References downscaleArbitrary(), downscaleHalf(), fl::XYMap::getHeight(), fl::XYMap::getType(), fl::XYMap::getWidth(), and fl::XYMap::kLineByLine.
Referenced by CRGB::downscale(), and loop().
downscaleArbitrary()
void fl::downscaleArbitrary (const CRGB * src, const XYMap & srcXY, CRGB * dst, const XYMap & dstXY)
Definition at line 81 of file downscale.cpp.
{
    const uint16_t srcWidth = srcXY.getWidth();
    const uint16_t srcHeight = srcXY.getHeight();
    const uint16_t dstWidth = dstXY.getWidth();
    const uint16_t dstHeight = dstXY.getHeight();
    const uint32_t FP_ONE = 256; // Q8.8 fixed-point multiplier
    FASTLED_ASSERT(dstWidth <= srcWidth,
                   "Destination width must be <= source width");
    FASTLED_ASSERT(dstHeight <= srcHeight,
                   "Destination height must be <= source height");
    for (uint16_t dy = 0; dy < dstHeight; ++dy) {
        // Fractional boundaries in Q8.8
        uint32_t dstY0 = (dy * srcHeight * FP_ONE) / dstHeight;
        uint32_t dstY1 = ((dy + 1) * srcHeight * FP_ONE) / dstHeight;
        for (uint16_t dx = 0; dx < dstWidth; ++dx) {
            uint32_t dstX0 = (dx * srcWidth * FP_ONE) / dstWidth;
            uint32_t dstX1 = ((dx + 1) * srcWidth * FP_ONE) / dstWidth;
            uint64_t rSum = 0, gSum = 0, bSum = 0;
            uint32_t totalWeight = 0;
            // Find covered source pixels
            uint16_t srcY_start = dstY0 / FP_ONE;
            uint16_t srcY_end = (dstY1 + FP_ONE - 1) / FP_ONE; // ceil
            uint16_t srcX_start = dstX0 / FP_ONE;
            uint16_t srcX_end = (dstX1 + FP_ONE - 1) / FP_ONE; // ceil
            for (uint16_t sy = srcY_start; sy < srcY_end; ++sy) {
                // Calculate vertical overlap in Q8.8
                uint32_t sy0 = sy * FP_ONE;
                uint32_t sy1 = (sy + 1) * FP_ONE;
                uint32_t y_overlap = MIN(dstY1, sy1) - MAX(dstY0, sy0);
                if (y_overlap == 0)
                    continue;
                for (uint16_t sx = srcX_start; sx < srcX_end; ++sx) {
                    uint32_t sx0 = sx * FP_ONE;
                    uint32_t sx1 = (sx + 1) * FP_ONE;
                    uint32_t x_overlap = MIN(dstX1, sx1) - MAX(dstX0, sx0);
                    if (x_overlap == 0)
                        continue;
                    uint32_t weight = (x_overlap * y_overlap + (FP_ONE >> 1)) >>
                                      8; // Q8.8 * Q8.8 → Q16.16 → Q8.8
                    const CRGB &p = src[srcXY.mapToIndex(sx, sy)];
                    rSum += p.r * weight;
                    gSum += p.g * weight;
                    bSum += p.b * weight;
                    totalWeight += weight;
                }
            }
            // Final division, rounding
            uint8_t r =
                totalWeight ? (rSum + (totalWeight >> 1)) / totalWeight : 0;
            uint8_t g =
                totalWeight ? (gSum + (totalWeight >> 1)) / totalWeight : 0;
            uint8_t b =
                totalWeight ? (bSum + (totalWeight >> 1)) / totalWeight : 0;
            dst[dstXY.mapToIndex(dx, dy)] = CRGB(r, g, b);
        }
    }
}
References fl::XYMap::getHeight(), fl::XYMap::getWidth(), fl::XYMap::mapToIndex(), MAX, MIN, and p.
Referenced by downscale().
downscaleHalf() [1/2]
void fl::downscaleHalf (const CRGB * src, const XYMap & srcXY, CRGB * dst, const XYMap & dstXY)
Definition at line 46 of file downscale.cpp.
{
    uint16_t dstWidth = dstXY.getWidth();
    uint16_t dstHeight = dstXY.getHeight();
    FASTLED_ASSERT(srcXY.getWidth() == dstXY.getWidth() * 2,
                   "Source width must be double the destination width");
    FASTLED_ASSERT(srcXY.getHeight() == dstXY.getHeight() * 2,
                   "Source height must be double the destination height");
    for (uint16_t y = 0; y < dstHeight; ++y) {
        for (uint16_t x = 0; x < dstWidth; ++x) {
            // Map to top-left of the 2x2 block in source
            uint16_t srcX = x * 2;
            uint16_t srcY = y * 2;
            // Fetch 2x2 block
            const CRGB &p00 = src[srcXY.mapToIndex(srcX, srcY)];
            const CRGB &p10 = src[srcXY.mapToIndex(srcX + 1, srcY)];
            const CRGB &p01 = src[srcXY.mapToIndex(srcX, srcY + 1)];
            const CRGB &p11 = src[srcXY.mapToIndex(srcX + 1, srcY + 1)];
            // Average each color channel
            uint16_t r =
                (p00.r + p10.r + p01.r + p11.r + 2) / 4; // +2 for rounding
            uint16_t g = (p00.g + p10.g + p01.g + p11.g + 2) / 4;
            uint16_t b = (p00.b + p10.b + p01.b + p11.b + 2) / 4;
            // Store result
            dst[dstXY.mapToIndex(x, y)] =
                CRGB((uint8_t)r, (uint8_t)g, (uint8_t)b);
        }
    }
}
References fl::XYMap::getHeight(), fl::XYMap::getWidth(), fl::XYMap::mapToIndex(), x, and y.
downscaleHalf() [2/2]
void fl::downscaleHalf (const CRGB * src, uint16_t srcWidth, uint16_t srcHeight, CRGB * dst)
Definition at line 17 of file downscale.cpp.
{
    uint16_t dstWidth = srcWidth / 2;
    uint16_t dstHeight = srcHeight / 2;
    for (uint16_t y = 0; y < dstHeight; ++y) {
        for (uint16_t x = 0; x < dstWidth; ++x) {
            // Map to top-left of the 2x2 block in source
            uint16_t srcX = x * 2;
            uint16_t srcY = y * 2;
            // Fetch 2x2 block
            const CRGB &p00 = src[(srcY)*srcWidth + (srcX)];
            const CRGB &p10 = src[(srcY)*srcWidth + (srcX + 1)];
            const CRGB &p01 = src[(srcY + 1) * srcWidth + (srcX)];
            const CRGB &p11 = src[(srcY + 1) * srcWidth + (srcX + 1)];
            // Average each color channel
            uint16_t r =
                (p00.r + p10.r + p01.r + p11.r + 2) / 4; // +2 for rounding
            uint16_t g = (p00.g + p10.g + p01.g + p11.g + 2) / 4;
            uint16_t b = (p00.b + p10.b + p01.b + p11.b + 2) / 4;
            // Store result
            dst[y * dstWidth + x] = CRGB((uint8_t)r, (uint8_t)g, (uint8_t)b);
        }
    }
}
References x, and y.
Referenced by downscale(), and loop().
drawSquare()
void fl::drawSquare (void * , uint16_t , uint16_t , int , int , uint32_t , uint32_t)
fade_raw()
void fl::fade_raw (CRGB * leds, uint16_t num_leds, uint8_t fadeBy)
Definition at line 165 of file colorutils.cpp.
{
    nscale8(leds, num_leds, 255 - fadeBy);
}
References leds, and nscale8().
fade_video()
void fl::fade_video (CRGB * leds, uint16_t num_leds, uint8_t fadeBy)
Definition at line 153 of file colorutils.cpp.
{
    nscale8_video(leds, num_leds, 255 - fadeBy);
}
References leds, and nscale8_video().
fadeLightBy()
void fl::fadeLightBy (CRGB * leds, uint16_t num_leds, uint8_t fadeBy)
Definition at line 157 of file colorutils.cpp.
{
    nscale8_video(leds, num_leds, 255 - fadeBy);
}
References leds, and nscale8_video().
fadeToBlackBy()
void fl::fadeToBlackBy (CRGB * leds, uint16_t num_leds, uint8_t fadeBy)
Definition at line 161 of file colorutils.cpp.
{
    nscale8(leds, num_leds, 255 - fadeBy);
}
References leds, and nscale8().
Referenced by fl::DemoReel100::confetti(), fl::DemoReel100::juggle(), and fl::DemoReel100::sinelon().
fadeToColorBy()
void fl::fadeToColorBy (void * , uint16_t , uint32_t , uint8_t)
fadeUsingColor()
void fl::fadeUsingColor (CRGB * leds, uint16_t numLeds, const CRGB & colormask)
Definition at line 175 of file colorutils.cpp.
{
    uint8_t fr, fg, fb;
    fr = colormask.r;
    fg = colormask.g;
    fb = colormask.b;
    for (uint16_t i = 0; i < numLeds; ++i) {
        leds[i].r = scale8_LEAVING_R1_DIRTY(leds[i].r, fr);
        leds[i].g = scale8_LEAVING_R1_DIRTY(leds[i].g, fg);
        leds[i].b = scale8(leds[i].b, fb);
    }
}
References leds, scale8(), and scale8_LEAVING_R1_DIRTY().
fast_hash32()
static uint32_t fl::fast_hash32 (uint32_t x) inline static noexcept
Definition at line 76 of file hash.h.
{
    x = (x ^ 61u) ^ (x >> 16);
    x = x + (x << 3);
    x = x ^ (x >> 4);
    x = x * 0x27d4eb2dU;
    x = x ^ (x >> 15);
    return x;
}
References x.
Referenced by hash_pair(), fl::FastHash< Key >::operator()(), fl::FastHash< vec2< T > >::operator()(), and fl::Hash< T * >::operator()().
fastled_file_offset()
const char * fl::fastled_file_offset (const char * file) inline
Definition at line 8 of file dbg.h.
{
    const char *p = file;
    const char *last_slash = nullptr;
    while (*p) {
        if (p[0] == 's' && p[1] == 'r' && p[2] == 'c' && p[3] == '/') {
            return p; // Skip past "src/"
        }
        if (*p == '/') { // fallback to using last slash
            last_slash = p;
        }
        p++;
    }
    // If "src/" not found but we found at least one slash, return after the
    // last slash
    if (last_slash) {
        return last_slash + 1;
    }
    return file; // If no slashes found at all, return original path
}
References p.
FASTLED_SMART_PTR() [1/51]
fl::FASTLED_SMART_PTR (Animartrix)
FASTLED_SMART_PTR() [2/51]
fl::FASTLED_SMART_PTR (ArchimedeanSpiralPath)
FASTLED_SMART_PTR() [3/51]
fl::FASTLED_SMART_PTR (AudioSampleImpl)
FASTLED_SMART_PTR() [4/51]
fl::FASTLED_SMART_PTR (Blend2d)
FASTLED_SMART_PTR() [5/51]
fl::FASTLED_SMART_PTR (ByteStream)
FASTLED_SMART_PTR() [6/51]
fl::FASTLED_SMART_PTR (ByteStreamMemory)
FASTLED_SMART_PTR() [7/51]
fl::FASTLED_SMART_PTR (CatmullRomParams)
FASTLED_SMART_PTR() [8/51]
fl::FASTLED_SMART_PTR (CatmullRomPath)
FASTLED_SMART_PTR() [9/51]
fl::FASTLED_SMART_PTR (CirclePath)
FASTLED_SMART_PTR() [10/51]
fl::FASTLED_SMART_PTR (Cylon)
FASTLED_SMART_PTR() [11/51]
fl::FASTLED_SMART_PTR (DemoReel100)
FASTLED_SMART_PTR() [12/51]
fl::FASTLED_SMART_PTR (DigitalPinImpl)
FASTLED_SMART_PTR() [13/51]
fl::FASTLED_SMART_PTR (FileHandle)
FASTLED_SMART_PTR() [14/51]
fl::FASTLED_SMART_PTR (FileSystem)
FASTLED_SMART_PTR() [15/51]
fl::FASTLED_SMART_PTR (Fire2012)
Simple one-dimensional fire animation function.
FASTLED_SMART_PTR() [16/51]
fl::FASTLED_SMART_PTR (Frame)
FASTLED_SMART_PTR() [17/51]
fl::FASTLED_SMART_PTR (FrameInterpolator)
FASTLED_SMART_PTR() [18/51]
fl::FASTLED_SMART_PTR (FsImpl)
FASTLED_SMART_PTR() [19/51]
fl::FASTLED_SMART_PTR (Fx)
FASTLED_SMART_PTR() [20/51]
fl::FASTLED_SMART_PTR (Fx2d)
FASTLED_SMART_PTR() [21/51]
fl::FASTLED_SMART_PTR (FxLayer)
FASTLED_SMART_PTR() [22/51]
fl::FASTLED_SMART_PTR (GielisCurvePath)
FASTLED_SMART_PTR() [23/51]
fl::FASTLED_SMART_PTR (HeartPath)
FASTLED_SMART_PTR() [24/51]
fl::FASTLED_SMART_PTR (LinePath)
FASTLED_SMART_PTR() [25/51]
fl::FASTLED_SMART_PTR (LinePathParams)
FASTLED_SMART_PTR() [26/51]
fl::FASTLED_SMART_PTR (NoisePalette)
FASTLED_SMART_PTR() [27/51]
fl::FASTLED_SMART_PTR (NoiseWave)
FASTLED_SMART_PTR() [28/51]
fl::FASTLED_SMART_PTR (Pacifica)
FASTLED_SMART_PTR() [29/51]
fl::FASTLED_SMART_PTR (PhyllotaxisPath)
FASTLED_SMART_PTR() [30/51]
fl::FASTLED_SMART_PTR (PixelStream)
FASTLED_SMART_PTR() [31/51]
fl::FASTLED_SMART_PTR (PointPath)
FASTLED_SMART_PTR() [32/51]
fl::FASTLED_SMART_PTR (Pride2015)
FASTLED_SMART_PTR() [33/51]
fl::FASTLED_SMART_PTR (RedSquare)
FASTLED_SMART_PTR() [34/51]
fl::FASTLED_SMART_PTR (RosePath)
FASTLED_SMART_PTR() [35/51]
fl::FASTLED_SMART_PTR (RosePathParams)
FASTLED_SMART_PTR() [36/51]
fl::FASTLED_SMART_PTR (ScaleUp)
FASTLED_SMART_PTR() [37/51]
fl::FASTLED_SMART_PTR (StringHolder)
FASTLED_SMART_PTR() [38/51]
fl::FASTLED_SMART_PTR (TimeFunction)
FASTLED_SMART_PTR() [39/51]
fl::FASTLED_SMART_PTR (TimeWarp)
FASTLED_SMART_PTR() [40/51]
fl::FASTLED_SMART_PTR (TransformFloatImpl)
FASTLED_SMART_PTR() [41/51]
fl::FASTLED_SMART_PTR (TwinkleFox)
FASTLED_SMART_PTR() [42/51]
fl::FASTLED_SMART_PTR (VideoFxWrapper)
FASTLED_SMART_PTR() [43/51]
fl::FASTLED_SMART_PTR (VideoImpl)
FASTLED_SMART_PTR() [44/51]
fl::FASTLED_SMART_PTR (WaveCrgbGradientMap)
FASTLED_SMART_PTR() [45/51]
fl::FASTLED_SMART_PTR (WaveCrgbMap)
FASTLED_SMART_PTR() [46/51]
fl::FASTLED_SMART_PTR (WaveCrgbMapDefault)
FASTLED_SMART_PTR() [47/51]
fl::FASTLED_SMART_PTR (WaveFx)
FASTLED_SMART_PTR() [48/51]
fl::FASTLED_SMART_PTR (XYPath)
FASTLED_SMART_PTR() [49/51]
fl::FASTLED_SMART_PTR (XYPathFunction)
FASTLED_SMART_PTR() [50/51]
fl::FASTLED_SMART_PTR (XYPathGenerator)
FASTLED_SMART_PTR() [51/51]
fl::FASTLED_SMART_PTR (XYPathRenderer)
FASTLED_SMART_PTR_NO_FWD() [1/4]
fl::FASTLED_SMART_PTR_NO_FWD (LUT16)
FASTLED_SMART_PTR_NO_FWD() [2/4]
fl::FASTLED_SMART_PTR_NO_FWD (LUTXY16)
FASTLED_SMART_PTR_NO_FWD() [3/4]
fl::FASTLED_SMART_PTR_NO_FWD (LUTXYFLOAT)
FASTLED_SMART_PTR_NO_FWD() [4/4]
fl::FASTLED_SMART_PTR_NO_FWD (LUTXYZFLOAT)
FASTLED_UI_DEFINE_OPERATORS() [1/4]
fl::FASTLED_UI_DEFINE_OPERATORS (UIButton)
FASTLED_UI_DEFINE_OPERATORS() [2/4]
fl::FASTLED_UI_DEFINE_OPERATORS (UICheckbox)
FASTLED_UI_DEFINE_OPERATORS() [3/4]
fl::FASTLED_UI_DEFINE_OPERATORS (UINumberField)
FASTLED_UI_DEFINE_OPERATORS() [4/4]
fl::FASTLED_UI_DEFINE_OPERATORS (UISlider)
fill_gradient() [1/4]
template<typename T> void fl::fill_gradient (T * targetArray, uint16_t numLeds, const CHSV & c1, const CHSV & c2, const CHSV & c3, const CHSV & c4, TGradientDirectionCode directionCode = SHORTEST_HUES)
Fill a range of LEDs with a smooth HSV gradient between four HSV colors.
See also
fill_gradient()
Parameters
targetArray a pointer to the color array to fill
numLeds the number of LEDs to fill
c1 the starting color in the gradient
c2 the first middle color for the gradient
c3 the second middle color for the gradient
c4 the end color for the gradient
directionCode the direction to travel around the color wheel
Definition at line 223 of file fill.h.
{
    uint16_t onethird = (numLeds / 3);
    uint16_t twothirds = ((numLeds * 2) / 3);
    uint16_t last = numLeds - 1;
    fill_gradient(targetArray, 0, c1, onethird, c2, directionCode);
    fill_gradient(targetArray, onethird, c2, twothirds, c3, directionCode);
    fill_gradient(targetArray, twothirds, c3, last, c4, directionCode);
}
References fill_gradient(), and SHORTEST_HUES.
fill_gradient() [2/4]
template<typename T> void fl::fill_gradient (T * targetArray, uint16_t numLeds, const CHSV & c1, const CHSV & c2, const CHSV & c3, TGradientDirectionCode directionCode = SHORTEST_HUES)
Fill a range of LEDs with a smooth HSV gradient between three HSV colors.
See also
fill_gradient()
Parameters
targetArray a pointer to the color array to fill
numLeds the number of LEDs to fill
c1 the starting color in the gradient
c2 the middle color for the gradient
c3 the end color for the gradient
directionCode the direction to travel around the color wheel
Definition at line 204 of file fill.h.
{
    uint16_t half = (numLeds / 2);
    uint16_t last = numLeds - 1;
    fill_gradient(targetArray, 0, c1, half, c2, directionCode);
    fill_gradient(targetArray, half, c2, last, c3, directionCode);
}
References fill_gradient(), and SHORTEST_HUES.
fill_gradient() [3/4]
template<typename T> void fl::fill_gradient (T * targetArray, uint16_t numLeds, const CHSV & c1, const CHSV & c2, TGradientDirectionCode directionCode = SHORTEST_HUES)
Fill a range of LEDs with a smooth HSV gradient between two HSV colors.
See also
fill_gradient()
Parameters
targetArray a pointer to the color array to fill
numLeds the number of LEDs to fill
c1 the starting color in the gradient
c2 the end color for the gradient
directionCode the direction to travel around the color wheel
Definition at line 188 of file fill.h.
{
    uint16_t last = numLeds - 1;
    fill_gradient(targetArray, 0, c1, last, c2, directionCode);
}
References fill_gradient(), and SHORTEST_HUES.
fill_gradient() [4/4]
template<typename T> void fl::fill_gradient (T * targetArray, uint16_t startpos, CHSV startcolor, uint16_t endpos, CHSV endcolor, TGradientDirectionCode directionCode = SHORTEST_HUES)
Fill a range of LEDs with a smooth HSV gradient between two HSV colors.
This function can write the gradient colors either:
Into an array of CRGBs (e.g., an leds[] array, or a CRGB palette)
Into an array of CHSVs (e.g. a CHSV palette).
In the case of writing into a CRGB array, the gradient is computed in HSV space, and then HSV values are converted to RGB as they're written into the CRGB array.
Parameters
targetArray a pointer to the color array to fill
startpos the starting position in the array
startcolor the starting color for the gradient
endpos the ending position in the array
endcolor the end color for the gradient
directionCode the direction to travel around the color wheel
Definition at line 77 of file fill.h.
{
    // if the points are in the wrong order, straighten them
    if (endpos < startpos) {
        uint16_t t = endpos;
        CHSV tc = endcolor;
        endcolor = startcolor;
        endpos = startpos;
        startpos = t;
        startcolor = tc;
    }
    // If we're fading toward black (val=0) or white (sat=0),
    // then set the endhue to the starthue.
    // This lets us ramp smoothly to black or white, regardless
    // of what 'hue' was set in the endcolor (since it doesn't matter)
    if (endcolor.value == 0 || endcolor.saturation == 0) {
        endcolor.hue = startcolor.hue;
    }
    // Similarly, if we're fading in from black (val=0) or white (sat=0)
    // then set the starthue to the endhue.
    // This lets us ramp smoothly up from black or white, regardless
    // of what 'hue' was set in the startcolor (since it doesn't matter)
    if (startcolor.value == 0 || startcolor.saturation == 0) {
        startcolor.hue = endcolor.hue;
    }
    saccum87 huedistance87;
    saccum87 satdistance87;
    saccum87 valdistance87;
    satdistance87 = (endcolor.sat - startcolor.sat) << 7;
    valdistance87 = (endcolor.val - startcolor.val) << 7;
    uint8_t huedelta8 = endcolor.hue - startcolor.hue;
    if (directionCode == SHORTEST_HUES) {
        directionCode = FORWARD_HUES;
        if (huedelta8 > 127) {
            directionCode = BACKWARD_HUES;
        }
    }
    if (directionCode == LONGEST_HUES) {
        directionCode = FORWARD_HUES;
        if (huedelta8 < 128) {
            directionCode = BACKWARD_HUES;
        }
    }
    if (directionCode == FORWARD_HUES) {
        huedistance87 = huedelta8 << 7;
    } else /* directionCode == BACKWARD_HUES */
    {
        huedistance87 = (uint8_t)(256 - huedelta8) << 7;
        huedistance87 = -huedistance87;
    }
    uint16_t pixeldistance = endpos - startpos;
    int16_t divisor = pixeldistance ? pixeldistance : 1;
#if FASTLED_USE_32_BIT_GRADIENT_FILL
    // Use higher precision 32 bit math for new micros.
    int32_t huedelta823 = (huedistance87 * 65536) / divisor;
    int32_t satdelta823 = (satdistance87 * 65536) / divisor;
    int32_t valdelta823 = (valdistance87 * 65536) / divisor;
    huedelta823 *= 2;
    satdelta823 *= 2;
    valdelta823 *= 2;
    uint32_t hue824 = static_cast<uint32_t>(startcolor.hue) << 24;
    uint32_t sat824 = static_cast<uint32_t>(startcolor.sat) << 24;
    uint32_t val824 = static_cast<uint32_t>(startcolor.val) << 24;
    for (uint16_t i = startpos; i <= endpos; ++i) {
        targetArray[i] = CHSV(hue824 >> 24, sat824 >> 24, val824 >> 24);
        hue824 += huedelta823;
        sat824 += satdelta823;
        val824 += valdelta823;
    }
#else
    // Use 8-bit math for older micros.
    saccum87 huedelta87 = huedistance87 / divisor;
    saccum87 satdelta87 = satdistance87 / divisor;
    saccum87 valdelta87 = valdistance87 / divisor;
    huedelta87 *= 2;
    satdelta87 *= 2;
    valdelta87 *= 2;
    accum88 hue88 = startcolor.hue << 8;
    accum88 sat88 = startcolor.sat << 8;
    accum88 val88 = startcolor.val << 8;
    for (uint16_t i = startpos; i <= endpos; ++i) {
        targetArray[i] = CHSV(hue88 >> 8, sat88 >> 8, val88 >> 8);
        hue88 += huedelta87;
        sat88 += satdelta87;
        val88 += valdelta87;
    }
#endif // defined(__AVR__)
}
References BACKWARD_HUES, FORWARD_HUES, LONGEST_HUES, saccum87, and SHORTEST_HUES.
Referenced by fill_gradient(), fill_gradient(), and fill_gradient().
fill_gradient_RGB() [1/4]
void fl::fill_gradient_RGB (CRGB * leds, uint16_t numLeds, const CRGB & c1, const CRGB & c2)
Fill a range of LEDs with a smooth RGB gradient between two RGB colors.
See also
fill_gradient_RGB()
Parameters
leds a pointer to the LED array to fill
numLeds the number of LEDs to fill
c1 the starting color in the gradient
c2 the end color for the gradient
Definition at line 149 of file fill.cpp.
{
    uint16_t last = numLeds - 1;
    fill_gradient_RGB(leds, 0, c1, last, c2);
}
References fill_gradient_RGB(), and leds.
fill_gradient_RGB() [2/4]
void fl::fill_gradient_RGB (CRGB * leds, uint16_t numLeds, const CRGB & c1, const CRGB & c2, const CRGB & c3)
Fill a range of LEDs with a smooth RGB gradient between three RGB colors.
See also
fill_gradient_RGB()
Parameters
leds a pointer to the LED array to fill
numLeds the number of LEDs to fill
c1 the starting color in the gradient
c2 the middle color for the gradient
c3 the end color for the gradient
Definition at line 155 of file fill.cpp.
{
    uint16_t half = (numLeds / 2);
    uint16_t last = numLeds - 1;
    fill_gradient_RGB(leds, 0, c1, half, c2);
    fill_gradient_RGB(leds, half, c2, last, c3);
}
References fill_gradient_RGB(), and leds.
fill_gradient_RGB() [3/4]
void fl::fill_gradient_RGB (CRGB * leds, uint16_t numLeds, const CRGB & c1, const CRGB & c2, const CRGB & c3, const CRGB & c4)
Fill a range of LEDs with a smooth RGB gradient between four RGB colors.
See also
fill_gradient_RGB()
Parameters
leds a pointer to the LED array to fill
numLeds the number of LEDs to fill
c1 the starting color in the gradient
c2 the first middle color for the gradient
c3 the second middle color for the gradient
c4 the end color for the gradient
Definition at line 163 of file fill.cpp.
{
    uint16_t onethird = (numLeds / 3);
    uint16_t twothirds = ((numLeds * 2) / 3);
    uint16_t last = numLeds - 1;
    fill_gradient_RGB(leds, 0, c1, onethird, c2);
    fill_gradient_RGB(leds, onethird, c2, twothirds, c3);
    fill_gradient_RGB(leds, twothirds, c3, last, c4);
}
References fill_gradient_RGB(), and leds.
fill_gradient_RGB() [4/4]
void fl::fill_gradient_RGB (CRGB * leds, uint16_t startpos, CRGB startcolor, uint16_t endpos, CRGB endcolor)
Fill a range of LEDs with a smooth RGB gradient between two RGB colors.
Unlike HSV, there is no "color wheel" in RGB space, and therefore there's only one "direction" for the gradient to go. This means there's no TGradientDirectionCode parameter for direction.
Parameters
leds a pointer to the LED array to fill
startpos the starting position in the array
startcolor the starting color for the gradient
endpos the ending position in the array
endcolor the end color for the gradient
Definition at line 107 of file fill.cpp.
{
    // if the points are in the wrong order, straighten them
    if (endpos < startpos) {
        uint16_t t = endpos;
        CRGB tc = endcolor;
        endcolor = startcolor;
        endpos = startpos;
        startpos = t;
        startcolor = tc;
    }
    saccum87 rdistance87;
    saccum87 gdistance87;
    saccum87 bdistance87;
    rdistance87 = (endcolor.r - startcolor.r) << 7;
    gdistance87 = (endcolor.g - startcolor.g) << 7;
    bdistance87 = (endcolor.b - startcolor.b) << 7;
    uint16_t pixeldistance = endpos - startpos;
    int16_t divisor = pixeldistance ? pixeldistance : 1;
    saccum87 rdelta87 = rdistance87 / divisor;
    saccum87 gdelta87 = gdistance87 / divisor;
    saccum87 bdelta87 = bdistance87 / divisor;
    rdelta87 *= 2;
    gdelta87 *= 2;
    bdelta87 *= 2;
    accum88 r88 = startcolor.r << 8;
    accum88 g88 = startcolor.g << 8;
    accum88 b88 = startcolor.b << 8;
    for (uint16_t i = startpos; i <= endpos; ++i) {
        leds[i] = CRGB(r88 >> 8, g88 >> 8, b88 >> 8);
        r88 += rdelta87;
        g88 += gdelta87;
        b88 += bdelta87;
    }
}
References leds, and saccum87.
Referenced by fill_gradient_RGB(), fill_gradient_RGB(), and fill_gradient_RGB().
fill_rainbow() [1/2]
void fl::fill_rainbow (struct CHSV * targetArray, int numToFill, uint8_t initialhue, uint8_t deltahue = 5)
Fill a range of LEDs with a rainbow of colors.
The colors making up the rainbow are at full saturation and full value (brightness).
Parameters
targetArray a pointer to the LED array to fill
numToFill the number of LEDs to fill in the array
initialhue the starting hue for the rainbow
deltahue how many hue values to advance for each LED
Definition at line 41 of file fill.cpp.
{
    CHSV hsv;
    hsv.hue = initialhue;
    hsv.val = 255;
    hsv.sat = 240;
    for (int i = 0; i < numToFill; ++i) {
        targetArray[i] = hsv;
        hsv.hue += deltahue;
    }
}
fill_rainbow() [2/2]
void fl::fill_rainbow (struct CRGB * targetArray, int numToFill, uint8_t initialhue, uint8_t deltahue = 5)
Fill a range of LEDs with a rainbow of colors.
The colors making up the rainbow are at full saturation and full value (brightness).
Parameters
targetArray a pointer to the LED array to fill
numToFill the number of LEDs to fill in the array
initialhue the starting hue for the rainbow
deltahue how many hue values to advance for each LED
Definition at line 29 of file fill.cpp.
{
    CHSV hsv;
    hsv.hue = initialhue;
    hsv.val = 255;
    hsv.sat = 240;
    for (int i = 0; i < numToFill; ++i) {
        targetArray[i] = hsv;
        hsv.hue += deltahue;
    }
}
Referenced by fl::DemoReel100::rainbow().
fill_rainbow_circular() [1/2]
void fl::fill_rainbow_circular (struct CHSV * targetArray, int numToFill, uint8_t initialhue, bool reversed = false)
Fill a range of LEDs with a rainbow of colors, so that the hues are continuous between the end of the strip and the beginning.
The colors making up the rainbow are at full saturation and full value (brightness).
Parameters
targetArray a pointer to the LED array to fill
numToFill the number of LEDs to fill in the array
initialhue the starting hue for the rainbow
reversed whether to progress through the rainbow hues backwards
Definition at line 80 of file fill.cpp.
{
    if (numToFill == 0)
        return; // avoiding div/0
    CHSV hsv;
    hsv.hue = initialhue;
    hsv.val = 255;
    hsv.sat = 240;
    const uint16_t hueChange =
        65535 / (uint16_t)numToFill; // hue change for each LED, * 256 for
                                     // precision (256 * 256 - 1)
    uint16_t hueOffset = 0; // offset for hue value, with precision (*256)
    for (int i = 0; i < numToFill; ++i) {
        targetArray[i] = hsv;
        if (reversed)
            hueOffset -= hueChange;
        else
            hueOffset += hueChange;
        hsv.hue = initialhue +
                  (uint8_t)(hueOffset >>
                            8); // assign new hue with precise offset (as 8-bit)
    }
}
fill_rainbow_circular() [2/2]
void fl::fill_rainbow_circular (struct CRGB * targetArray, int numToFill, uint8_t initialhue, bool reversed = false)
Fill a range of LEDs with a rainbow of colors, so that the hues are continuous between the end of the strip and the beginning.
The colors making up the rainbow are at full saturation and full value (brightness).
Parameters
targetArray a pointer to the LED array to fill
numToFill the number of LEDs to fill in the array
initialhue the starting hue for the rainbow
reversed whether to progress through the rainbow hues backwards
Definition at line 53 of file fill.cpp.
{
    if (numToFill == 0)
        return; // avoiding div/0
    CHSV hsv;
    hsv.hue = initialhue;
    hsv.val = 255;
    hsv.sat = 240;
    const uint16_t hueChange =
        65535 / (uint16_t)numToFill; // hue change for each LED, * 256 for
                                     // precision (256 * 256 - 1)
    uint16_t hueOffset = 0; // offset for hue value, with precision (*256)
    for (int i = 0; i < numToFill; ++i) {
        targetArray[i] = hsv;
        if (reversed)
            hueOffset -= hueChange;
        else
            hueOffset += hueChange;
        hsv.hue = initialhue +
                  (uint8_t)(hueOffset >>
                            8); // assign new hue with precise offset (as 8-bit)
    }
}
fill_solid() [1/2]
void fl::fill_solid (struct CHSV * targetArray, int numToFill, const struct CHSV & color)
Fill a range of LEDs with a solid color.
Parameters
targetArray a pointer to the LED array to fill
numToFill the number of LEDs to fill in the array
color the color to fill with
Definition at line 16 of file fill.cpp.
{
    for (int i = 0; i < numToFill; ++i) {
        targetArray[i] = color;
    }
}
fill_solid() [2/2]
void fl::fill_solid (struct CRGB * targetArray, int numToFill, const struct CRGB & color)
Fill a range of LEDs with a solid color.
Parameters
targetArray a pointer to the LED array to fill
numToFill the number of LEDs to fill in the array
color the color to fill with
Definition at line 9 of file fill.cpp.
{
    for (int i = 0; i < numToFill; ++i) {
        targetArray[i] = color;
    }
}
Referenced by fl::Pacifica::draw(), and fl::NoisePalette::SetupBlackAndWhiteStripedPalette().
five_bit_bitshift()
uint8_t fl::five_bit_bitshift (uint16_t r16, uint16_t g16, uint16_t b16, uint8_t brightness, CRGB * out, uint8_t * out_power_5bit)
Definition at line 72 of file five_bit_hd_gamma.cpp.
{
    if (brightness == 0) {
        *out = CRGB(0, 0, 0);
        *out_power_5bit = 0;
        return 0;
    }
    if (r16 == 0 && g16 == 0 && b16 == 0) {
        *out = CRGB(0, 0, 0);
        *out_power_5bit = (brightness <= 31) ? brightness : 31;
        return brightness;
    }
    // Note: One day someone smarter than me will come along and invent a closed
    // form solution for this. However, the numerical method works extremely
    // well and has been optimized to avoid division performance penalties as
    // much as possible.
    // Step 1: Initialize brightness
    static const uint8_t kStartBrightness = 0b00010000;
    uint8_t v5 = kStartBrightness;
    // Step 2: Boost brightness by swapping power with the driver brightness.
    brightness_bitshifter8(&v5, &brightness, 4);
    // Step 3: Boost brightness of the color channels by swapping power with the
    // driver brightness.
    uint16_t max_component = max3(r16, g16, b16);
    // five_bit_color_bitshift(&r16, &g16, &b16, &v5);
    uint8_t shifts = brightness_bitshifter16(&v5, &max_component, 4, 2);
    if (shifts) {
        r16 = r16 << shifts;
        g16 = g16 << shifts;
        b16 = b16 << shifts;
    }
    // Step 4: scale by final brightness factor.
    if (brightness != 0xff) {
        r16 = scale16by8(r16, brightness);
        g16 = scale16by8(g16, brightness);
        b16 = scale16by8(b16, brightness);
    }
    // brighten hardware brightness by turning on low order bits
    if (v5 > 1) {
        // since v5 is a power of two, subtracting one will invert the leading
        // bit and invert all the bits below it. Example: 0b00010000 -1 =
        // 0b00001111 So 0b00010000 | 0b00001111 = 0b00011111
        v5 = v5 | (v5 - 1);
    }
    // Step 5: Convert back to 8-bit and output.
    *out = CRGB(map16_to_8(r16), map16_to_8(g16), map16_to_8(b16));
    *out_power_5bit = v5;
    return brightness;
}
References brightness, brightness_bitshifter16(), brightness_bitshifter8(), map16_to_8(), and scale16by8().
Referenced by __builtin_five_bit_hd_gamma_bitshift().
five_bit_hd_gamma_bitshift()
void fl::five_bit_hd_gamma_bitshift (CRGB colors, CRGB colors_scale, uint8_t global_brightness, CRGB * out_colors, uint8_t * out_power_5bit)
Definition at line 55 of file five_bit_hd_gamma.h.
{
    __builtin_five_bit_hd_gamma_bitshift(
        colors, colors_scale, global_brightness, out_colors, out_power_5bit);
}
References __builtin_five_bit_hd_gamma_bitshift(), and FASTLED_FORCE_INLINE.
Referenced by PixelController< RGB_ORDER, LANES, MASK >::loadAndScale_APA102_HD().
five_bit_hd_gamma_function()
void fl::five_bit_hd_gamma_function (CRGB color, uint16_t * r16, uint16_t * g16, uint16_t * b16)
Definition at line 27 of file five_bit_hd_gamma.cpp.
{
    uint16_t _r16 = map8_to_16(color.r);
    uint16_t _g16 = map8_to_16(color.g);
    uint16_t _b16 = map8_to_16(color.b);
    *r16 = scale16by8(_r16, color.r);
    *g16 = scale16by8(_g16, color.g);
    *b16 = scale16by8(_b16, color.b);
}
References map8_to_16(), and scale16by8().
Referenced by __builtin_five_bit_hd_gamma_bitshift().
fl_abs()
template<typename T> T fl::fl_abs (T value) inline
Definition at line 5 of file math_macros.h.
{
    return value < 0 ? -value : value;
}
floor()
template<typename T> T fl::floor (T value) inline
Definition at line 11 of file math.h.
{
    if (value >= 0) {
        return static_cast<T>(static_cast<int>(value));
    }
    return static_cast<T>(::floor(static_cast<float>(value)));
}
References floor().
Referenced by floor(), and traverseGridSegmentFloat().
forward() [1/2]
template<typename T> T && fl::forward (typename remove_reference< T >::type && t) constexpr noexcept
Definition at line 195 of file type_traits.h.
{
    static_assert(!is_lvalue_reference<T>::value,
                  "Cannot forward an rvalue as an lvalue");
    return static_cast<T &&>(t);
}
References fl::is_lvalue_reference< T >::value.
forward() [2/2]
template<typename T> T && fl::forward (typename remove_reference< T >::type & t) constexpr noexcept
Definition at line 189 of file type_traits.h.
{
    return static_cast<T &&>(t);
}
Referenced by fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::construct(), fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::emplace(), and fl::less< void >::operator()().
hash_pair()
static uint32_t fl::hash_pair (uint32_t a, uint32_t b, uint32_t seed = 0) inline static noexcept
Definition at line 86 of file hash.h.
{
    // mix in 'a', then mix in 'b'
    uint32_t h = fast_hash32(seed ^ a);
    return fast_hash32(h ^ b);
}
References fast_hash32().
Referenced by fl::FastHash< vec2< T > >::operator()().
HeatColor()
CRGB fl::HeatColor (uint8_t temperature)
Definition at line 199 of file colorutils.cpp.
{
    CRGB heatcolor;
    // Scale 'heat' down from 0-255 to 0-191,
    // which can then be easily divided into three
    // equal 'thirds' of 64 units each.
    uint8_t t192 = scale8_video(temperature, 191);
    // calculate a value that ramps up from
    // zero to 255 in each 'third' of the scale.
    uint8_t heatramp = t192 & 0x3F; // 0..63
    heatramp <<= 2;                 // scale up to 0..252
    // now figure out which third of the spectrum we're in:
    if (t192 & 0x80) {
        // we're in the hottest third
        heatcolor.r = 255;      // full red
        heatcolor.g = 255;      // full green
        heatcolor.b = heatramp; // ramp up blue
    } else if (t192 & 0x40) {
        // we're in the middle third
        heatcolor.r = 255;      // full red
        heatcolor.g = heatramp; // ramp up green
        heatcolor.b = 0;        // no blue
    } else {
        // we're in the coolest third
        heatcolor.r = heatramp; // ramp up red
        heatcolor.g = 0;        // no green
        heatcolor.b = 0;        // no blue
    }
    return heatcolor;
}
References scale8_video().
LargeBlockAllocate()
void * fl::LargeBlockAllocate (size_t size, bool zero)
Definition at line 41 of file allocator.cpp.
{
    void *ptr = Alloc(size);
    if (zero) {
        memset(ptr, 0, size);
    }
    return ptr;
}
Referenced by fl::Frame::Frame(), and fl::LargeBlockAllocator< T >::Alloc().
LargeBlockDeallocate()
void fl::LargeBlockDeallocate (void * ptr)
Definition at line 49 of file allocator.cpp.
{ Free(ptr); }
Referenced by fl::Frame::~Frame(), and fl::LargeBlockAllocator< T >::Free().
lsrX4()
uint8_t fl::lsrX4 (uint8_t dividend) inline
Helper function to divide a number by 16, aka four logical shift right (LSR)'s.
On avr-gcc, "u8 >> 4" generates a loop, which is big, and slow. merely forcing it to be four /=2's causes avr-gcc to emit a SWAP instruction followed by an AND 0x0F, which is faster, and smaller.
Definition at line 240 of file colorutils.cpp.
{
#if defined(__AVR__)
    dividend /= 2;
    dividend /= 2;
    dividend /= 2;
    dividend /= 2;
#else
    dividend >>= 4;
#endif
    return dividend;
}
Referenced by ColorFromPalette(), ColorFromPalette(), and ColorFromPalette().
make_sdcard_filesystem()
FsImplPtr fl::make_sdcard_filesystem (int cs_pin)
Definition at line 188 of file file_system.cpp.
{
    FASTLED_UNUSED(cs_pin);
    FsImplPtr out = FsImplPtr::TakeOwnership(new NullFileSystem());
    return out;
}
References FASTLED_UNUSED.
Referenced by fl::FileSystem::beginSd().
map_range()
template<typename T, typename U> FASTLED_FORCE_INLINE U fl::map_range (T value, T in_min, T in_max, U out_min, U out_max)
Definition at line 26 of file map_range.h.
{
    // Not fully tested with all unsigned types, so watch out if you use this
    // with uint16_t and you value < in_min.
    using namespace map_range_detail;
    if (equals(value, in_min)) {
        return out_min;
    }
    if (equals(value, in_max)) {
        return out_max;
    }
    return map_range_math<T, U>::map(value, in_min, in_max, out_min, out_max);
}
References FASTLED_FORCE_INLINE.
Referenced by loop(), anonymous_namespace{xypaths.cpp}::make_path(), fl::map_range_detail::map_range_math< uint8_t, uint8_t >::map(), map_range_clamped(), fl::XYPathRenderer::rasterize(), and fl::HashMap< Key, T, Hash, KeyEqual >::setLoadFactor().
map_range_clamped()
template<typename T, typename U> FASTLED_FORCE_INLINE U fl::map_range_clamped (T value, T in_min, T in_max, U out_min, U out_max)
Definition at line 41 of file map_range.h.
{
    // Not fully tested with all unsigned types, so watch out if you use this
    // with uint16_t and you value < in_min.
    using namespace map_range_detail;
    value = clamp(value, in_min, in_max);
    return map_range<T, U>(value, in_min, in_max, out_min, out_max);
}
References clamp(), FASTLED_FORCE_INLINE, and map_range().
move()
template<typename T> remove_reference< T >::type && fl::move (T && t) constexpr noexcept
Definition at line 174 of file type_traits.h.
{
    return static_cast<typename remove_reference<T>::type &&>(t);
}
Referenced by fl::BitsetInlined< N >::BitsetInlined(), fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::Variant(), fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::move_fn(), fl::BitsetInlined< N >::operator=(), and fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::operator=().
MurmurHash3_x86_32()
static uint32_t fl::MurmurHash3_x86_32 (const void * key, size_t len, uint32_t seed = 0) inline static
Definition at line 18 of file hash.h.
{
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wimplicit-fallthrough"
    const uint8_t *data = static_cast<const uint8_t *>(key);
    const int nblocks = int(len / 4);
    uint32_t h1 = seed;
    const uint32_t c1 = 0xcc9e2d51;
    const uint32_t c2 = 0x1b873593;
    // body
    const uint32_t *blocks = reinterpret_cast<const uint32_t *>(data);
    for (int i = 0; i < nblocks; ++i) {
        uint32_t k1 = blocks[i];
        k1 *= c1;
        k1 = (k1 << 15) | (k1 >> 17);
        k1 *= c2;
        h1 ^= k1;
        h1 = (h1 << 13) | (h1 >> 19);
        h1 = h1 * 5 + 0xe6546b64;
    }
    // tail
    const uint8_t *tail = data + (nblocks * 4);
    uint32_t k1 = 0;
    switch (len & 3) {
    case 3:
        k1 ^= uint32_t(tail[2]) << 16;
    case 2:
        k1 ^= uint32_t(tail[1]) << 8;
    case 1:
        k1 ^= uint32_t(tail[0]);
        k1 *= c1;
        k1 = (k1 << 15) | (k1 >> 17);
        k1 *= c2;
        h1 ^= k1;
    }
    // finalization
    h1 ^= uint32_t(len);
    // fmix32
    h1 ^= h1 >> 16;
    h1 *= 0x85ebca6b;
    h1 ^= h1 >> 13;
    h1 *= 0xc2b2ae35;
    h1 ^= h1 >> 16;
    return h1;
#pragma GCC diagnostic pop
}
Referenced by fl::FastHash< vec2< T > >::operator()(), fl::Hash< FFT_Args >::operator()(), fl::Hash< Key >::operator()(), and fl::Hash< vec2< T > >::operator()().
napplyGamma_video() [1/4]
CRGB & fl::napplyGamma_video (CRGB & rgb, float gamma)
Definition at line 1085 of file colorutils.cpp.
{
    rgb = applyGamma_video(rgb, gamma);
    return rgb;
}
References applyGamma_video().
napplyGamma_video() [2/4]
CRGB & fl::napplyGamma_video (CRGB & rgb, float gammaR, float gammaG, float gammaB)
Definition at line 1090 of file colorutils.cpp.
{
    rgb = applyGamma_video(rgb, gammaR, gammaG, gammaB);
    return rgb;
}
References applyGamma_video().
napplyGamma_video() [3/4]
void fl::napplyGamma_video (CRGB * rgbarray, uint16_t count, float gamma)
Definition at line 1095 of file colorutils.cpp.
{
    for (uint16_t i = 0; i < count; ++i) {
        rgbarray[i] = applyGamma_video(rgbarray[i], gamma);
    }
}
References applyGamma_video().
napplyGamma_video() [4/4]
void fl::napplyGamma_video (CRGB * rgbarray, uint16_t count, float gammaR, float gammaG, float gammaB)
Definition at line 1101 of file colorutils.cpp.
{
    for (uint16_t i = 0; i < count; ++i) {
        rgbarray[i] = applyGamma_video(rgbarray[i], gammaR, gammaG, gammaB);
    }
}
References applyGamma_video().
nblend() [1/4]
CHSV & fl::nblend (CHSV & existing, const CHSV & overlay, fract8 amountOfOverlay, TGradientDirectionCode directionCode)
Definition at line 74 of file colorutils.cpp.
{
    if (amountOfOverlay == 0) {
        return existing;
    }
    if (amountOfOverlay == 255) {
        existing = overlay;
        return existing;
    }
    fract8 amountOfKeep = 255 - amountOfOverlay;
    uint8_t huedelta8 = overlay.hue - existing.hue;
    if (directionCode == SHORTEST_HUES) {
        directionCode = FORWARD_HUES;
        if (huedelta8 > 127) {
            directionCode = BACKWARD_HUES;
        }
    }
    if (directionCode == LONGEST_HUES) {
        directionCode = FORWARD_HUES;
        if (huedelta8 < 128) {
            directionCode = BACKWARD_HUES;
        }
    }
    if (directionCode == FORWARD_HUES) {
        existing.hue = existing.hue + scale8(huedelta8, amountOfOverlay);
    } else /* directionCode == BACKWARD_HUES */
    {
        huedelta8 = -huedelta8;
        existing.hue = existing.hue - scale8(huedelta8, amountOfOverlay);
    }
    existing.sat = scale8_LEAVING_R1_DIRTY(existing.sat, amountOfKeep) +
                   scale8_LEAVING_R1_DIRTY(overlay.sat, amountOfOverlay);
    existing.val = scale8_LEAVING_R1_DIRTY(existing.val, amountOfKeep) +
                   scale8_LEAVING_R1_DIRTY(overlay.val, amountOfOverlay);
    cleanup_R1();
    return existing;
}
References BACKWARD_HUES, cleanup_R1(), FORWARD_HUES, LONGEST_HUES, scale8(), scale8_LEAVING_R1_DIRTY(), and SHORTEST_HUES.
nblend() [2/4]
void fl::nblend (CHSV * existing, const CHSV * overlay, uint16_t count, fract8 amountOfOverlay, TGradientDirectionCode directionCode)
Definition at line 121 of file colorutils.cpp.
{
    if (existing == overlay)
        return;
    for (uint16_t i = count; i; --i) {
        nblend(*existing, *overlay, amountOfOverlay, directionCode);
        ++existing;
        ++overlay;
    }
}
References nblend().
nblend() [3/4]
CRGB & fl::nblend (CRGB & existing, const CRGB & overlay, fract8 amountOfOverlay)
Definition at line 19 of file colorutils.cpp.
{
    if (amountOfOverlay == 0) {
        return existing;
    }
    if (amountOfOverlay == 255) {
        existing = overlay;
        return existing;
    }
#if 0
    // Old blend method which unfortunately had some rounding errors
    fract8 amountOfKeep = 255 - amountOfOverlay;
    existing.red   = scale8_LEAVING_R1_DIRTY( existing.red,   amountOfKeep)
                    + scale8_LEAVING_R1_DIRTY( overlay.red,    amountOfOverlay);
    existing.green = scale8_LEAVING_R1_DIRTY( existing.green, amountOfKeep)
                    + scale8_LEAVING_R1_DIRTY( overlay.green,  amountOfOverlay);
    existing.blue  = scale8_LEAVING_R1_DIRTY( existing.blue,  amountOfKeep)
                    + scale8_LEAVING_R1_DIRTY( overlay.blue,   amountOfOverlay);
    cleanup_R1();
#else
    // Corrected blend method, with no loss-of-precision rounding errors
    existing.red = blend8(existing.red, overlay.red, amountOfOverlay);
    existing.green = blend8(existing.green, overlay.green, amountOfOverlay);
    existing.blue = blend8(existing.blue, overlay.blue, amountOfOverlay);
#endif
    return existing;
}
References blend8(), cleanup_R1(), and scale8_LEAVING_R1_DIRTY().
Referenced by blend(), blend(), fl::Pride2015::draw(), nblend(), and nblend().
nblend() [4/4]
void fl::nblend (CRGB * existing, const CRGB * overlay, uint16_t count, fract8 amountOfOverlay)
Definition at line 51 of file colorutils.cpp.
{
    for (uint16_t i = count; i; --i) {
        nblend(*existing, *overlay, amountOfOverlay);
        ++existing;
        ++overlay;
    }
}
References nblend().
nblendPaletteTowardPalette()
void fl::nblendPaletteTowardPalette (CRGBPalette16 & current, CRGBPalette16 & target, uint8_t maxChanges)
Definition at line 1017 of file colorutils.cpp.
{
    uint8_t *p1;
    uint8_t *p2;
    uint8_t changes = 0;
    p1 = (uint8_t *)current.entries;
    p2 = (uint8_t *)target.entries;
    const uint8_t totalChannels = sizeof(CRGBPalette16);
    for (uint8_t i = 0; i < totalChannels; ++i) {
        // if the values are equal, no changes are needed
        if (p1[i] == p2[i]) {
            continue;
        }
        // if the current value is less than the target, increase it by one
        if (p1[i] < p2[i]) {
            ++p1[i];
            ++changes;
        }
        // if the current value is greater than the target,
        // increase it by one (or two if it's still greater).
        if (p1[i] > p2[i]) {
            --p1[i];
            ++changes;
            if (p1[i] > p2[i]) {
                --p1[i];
            }
        }
        // if we've hit the maximum number of changes, exit
        if (changes >= maxChanges) {
            break;
        }
    }
}
Referenced by fl::TwinkleFox::draw().
NewPtr()
template<typename T, typename... Args> Ptr< T > fl::NewPtr (Args... args)
Definition at line 451 of file ptr.h.
{
    return Ptr<T>::New(args...);
}
References args, and fl::PtrTraits< T >::New().
Referenced by fl::function< R(Args...)>::function(), fl::function< R(Args...)>::function(), fl::function< R(Args...)>::function(), fl::LinePath::LinePath(), fl::RosePath::RosePath(), fl::FFT::get_or_create(), anonymous_namespace{xypaths.cpp}::make_path(), fl::XYPath::NewCustomPath(), fl::XYPath::NewLinePath(), and NewWaveSimulation2D().
NewPtrNoTracking() [1/2]
template<typename T, typename... Args> Ptr< T > fl::NewPtrNoTracking (Args... args)
References args.
NewPtrNoTracking() [2/2]
template<typename T> Ptr< T > fl::NewPtrNoTracking (T & obj)
Definition at line 455 of file ptr.h.
{
    return Ptr<T>::NoTracking(obj);
}
References fl::Ptr< T >::NoTracking().
nscale8()
void fl::nscale8 (CRGB * leds, uint16_t num_leds, uint8_t scale)
Definition at line 169 of file colorutils.cpp.
{
    for (uint16_t i = 0; i < num_leds; ++i) {
        leds[i].nscale8(scale);
    }
}
References leds, and scale.
Referenced by fade_raw(), and fadeToBlackBy().
nscale8_video()
void fl::nscale8_video (CRGB * leds, uint16_t num_leds, uint8_t scale)
Definition at line 147 of file colorutils.cpp.
{
    for (uint16_t i = 0; i < num_leds; ++i) {
        leds[i].nscale8_video(scale);
    }
}
References leds, and scale.
Referenced by fade_video(), and fadeLightBy().
operator!=()
template<typename T, size_t N> bool fl::operator!= (const array< T, N > & lhs, const array< T, N > & rhs)
Definition at line 135 of file array.h.
{
    return !(lhs == rhs);
}
operator==()
template<typename T, size_t N> bool fl::operator== (const array< T, N > & lhs, const array< T, N > & rhs)
Definition at line 125 of file array.h.
{
    // return std::equal(lhs.begin(), lhs.end(), rhs.begin());
    for (size_t i = 0; i < N; ++i) {
        if (lhs[i] != rhs[i]) {
            return false;
        }
    }
}
parseJson()
bool fl::parseJson (const char * json, fl::JsonDocument * doc, Str * _error)
Definition at line 6 of file json.cpp.
{
#if !FASTLED_ENABLE_JSON
    if (_error) {
        *_error = "JSON not enabled";
    }
    return false;
#else
    FLArduinoJson::DeserializationError error = deserializeJson(*doc, json);
    if (error) {
        if (_error) {
            *_error = error.c_str();
        }
        return false;
    }
    return true;
#endif
}
References fl::StrN< SIZE >::c_str().
Referenced by fl::ScreenMap::ParseJson(), and fl::FileSystem::readJson().
pop_heap() [1/2]
template<typename Iterator> void fl::pop_heap (Iterator first, Iterator last)
Definition at line 61 of file priority_queue.h.
{
    pop_heap(first, last, [](const auto &a, const auto &b) { return a < b; });
}
References pop_heap().
pop_heap() [2/2]
template<typename Iterator, typename Compare> void fl::pop_heap (Iterator first, Iterator last, Compare comp)
Definition at line 52 of file priority_queue.h.
{
    --last;
    auto tmp = *first;
    *first = *last;
    *last = tmp;
    sift_down(first, last, first, comp);
}
References sift_down().
Referenced by fl::PriorityQueue< T, Compare, VectorT >::pop(), and pop_heap().
push_heap() [1/2]
template<typename Iterator> void fl::push_heap (Iterator first, Iterator last)
Definition at line 47 of file priority_queue.h.
{
    push_heap(first, last, [](const auto &a, const auto &b) { return a < b; });
}
References push_heap().
push_heap() [2/2]
template<typename Iterator, typename Compare> void fl::push_heap (Iterator first, Iterator last, Compare comp)
Definition at line 33 of file priority_queue.h.
{
    auto pos = last - 1;
    auto parent = first + ((pos - first) - 1) / 2;
    while (pos > first && comp(*parent, *pos)) {
        auto tmp = *parent;
        *parent = *pos;
        *pos = tmp;
        pos = parent;
        parent = first + ((pos - first) - 1) / 2;
    }
}
References pos.
Referenced by fl::PriorityQueue< T, Compare, VectorT >::push(), and push_heap().
SetLargeBlockAllocator()
void fl::SetLargeBlockAllocator (void *(* alloc)(size_t), void(* free)(void *))
Definition at line 36 of file allocator.cpp.
{
    Alloc = alloc;
    Free = free;
}
sift_down()
template<typename Iterator, typename Compare> void fl::sift_down (Iterator first, Iterator last, Iterator start, Compare comp)
Definition at line 10 of file priority_queue.h.
{
    auto root = start;
    auto child = first + 2 * (root - first) + 1;
    while (child < last) {
        if (child + 1 < last && comp(*child, *(child + 1))) {
            ++child;
        }
        if (comp(*root, *child)) {
            auto tmp = *root;
            *root = *child;
            *child = tmp;
            root = child;
            child = first + 2 * (root - first) + 1;
        } else {
            break;
        }
    }
}
Referenced by pop_heap().
sin16lut()
static FASTLED_FORCE_INLINE int16_t fl::sin16lut (uint16_t angle) static
Definition at line 53 of file sin32.h.
{
    uint8_t angle256 = angle / 256;
    int32_t subAngle = angle % 256;
    return (sinArray[angle256] * (256 - subAngle) +
            sinArray[angle256 + 1] * subAngle) /
           256;
}
References FASTLED_FORCE_INLINE, and sinArray.
sin32()
static FASTLED_FORCE_INLINE int32_t fl::sin32 (uint32_t angle) static
Definition at line 35 of file sin32.h.
{
    uint8_t angle256 = angle / 65536;
    int32_t subAngle = angle % 65536;
    return sinArray[angle256] * (65536 - subAngle) +
           sinArray[angle256 + 1] * subAngle;
}
References FASTLED_FORCE_INLINE, and sinArray.
swap() [1/2]
template<typename T, size_t N> void fl::swap (array< T, N > & lhs, array< T, N > & rhs) noexcept
Definition at line 140 of file array.h.
{
    lhs.swap(rhs);
}
Referenced by fl::FixedVector< PairKV, N >::FixedVector(), fl::InlinedVector< T, INLINED_SIZE >::InlinedVector(), fl::array< T, N >::swap(), fl::FixedVector< PairKV, N >::swap(), fl::HashMap< Key, T, Hash, KeyEqual, INLINED_COUNT >::Entry::swap(), fl::HashMapLru< Key, T, Hash, KeyEqual, INLINED_COUNT >::swap(), fl::InlinedVector< T, INLINED_SIZE >::swap(), and fl::Str::swap().
swap() [2/2]
template<typename T> void fl::swap (T & a, T & b)
Definition at line 428 of file type_traits.h.
{
    // if T is a POD, use use a simple data copy swap.
    // if T is not a POD, use the T::Swap method.
    swap_impl<T>::apply(a, b);
}
swap_by_copy()
template<typename T> void fl::swap_by_copy (T & a, T & b)
Definition at line 434 of file type_traits.h.
{
    // if T is a POD, use use a simple data copy swap.
    // if T is not a POD, use the T::Swap method.
    T tmp = a;
    a = b;
    b = tmp;
}
time_alpha16()
uint16_t fl::time_alpha16 (uint32_t now, uint32_t start, uint32_t end)
Definition at line 24 of file time_alpha.cpp.
{
    if (now < start) {
        return 0;
    }
    if (now > end) {
        return 65535;
    }
    uint32_t elapsed = now - start;
    uint32_t total = end - start;
    uint32_t out = (elapsed * 65535) / total;
    if (out > 65535) {
        out = 65535;
    }
    return static_cast<uint16_t>(out);
}
time_alpha8()
uint8_t fl::time_alpha8 (uint32_t now, uint32_t start, uint32_t end)
Definition at line 8 of file time_alpha.cpp.
{
    if (now < start) {
        return 0;
    }
    if (now > end) {
        return 255;
    }
    uint32_t elapsed = now - start;
    uint32_t total = end - start;
    uint32_t out = (elapsed * 255) / total;
    if (out > 255) {
        out = 255;
    }
    return static_cast<uint8_t>(out);
}
Referenced by fl::TimeClampedTransition::update8(), and fl::TimeRamp::update8().
time_alphaf()
float fl::time_alphaf (uint32_t now, uint32_t start, uint32_t end) inline
Definition at line 17 of file time_alpha.h.
{
    if (now < start) {
        return 0.0f;
    }
    uint32_t elapsed = now - start;
    uint32_t total = end - start;
    float out = static_cast<float>(elapsed) / static_cast<float>(total);
    return out;
}
Referenced by fl::TimeClampedTransition::updatef().
toJson()
void fl::toJson (const fl::JsonDocument & doc, Str * jsonBuffer)
Definition at line 24 of file json.cpp.
{
#if !FASTLED_ENABLE_JSON
    return;
#else
    serializeJson(doc, *jsonBuffer);
#endif
}
Referenced by fl::ScreenMap::toJsonStr().
traverseGridSegment()
template<typename GridVisitor> void fl::traverseGridSegment (const vec2f & start, const vec2f & end, GridVisitor & visitor) inline
Traverse a grid segment by selecting the cells that are crossed.
This version will select the fastest integer implementation based on the length of the segment. Most of the time it will call traverseGridSegment16() since segment spans are typically < 256 pixels.
Template Parameters
GridVisitor
Parameters
start start point
end end point
visitor called for each cell visited.
Fully tested.
Definition at line 275 of file traverse_grid.h.
{
    float dx = ABS(end.x - start.x);
    float dy = ABS(end.y - start.y);
    float maxRange = MAX(dx, dy);
    // if (maxRange < 256.0f) {
    //     // Use Q8.8 (16-bit signed) if within ±127
    //     traverseGridSegment16(start, end, visitor);
    // }
    // else if (maxRange < 16777216.0f) {
    //     // Use Q24.8 (32-bit signed) if within ±8 million
    //     traverseGridSegment32(start, end, visitor);
    // }
    // else {
    //     // Fall back to floating-point
    //     traverseGridSegment(start, end, visitor);
    // }
    if (maxRange < 256.0f) {
        // Use Q8.8 (16-bit signed) if within ±127
        traverseGridSegment16(start, end, visitor);
    } else {
        // Use Q24.8 (32-bit signed) if within ±8 million
        traverseGridSegment32(start, end, visitor);
    }
}
References ABS, MAX, traverseGridSegment16(), traverseGridSegment32(), fl::vec2< T >::x, and fl::vec2< T >::y.
traverseGridSegment16()
template<typename GridVisitor> void fl::traverseGridSegment16 (const vec2f & start, const vec2f & end, GridVisitor & visitor) inline
Traverse a grid segment using fixed-point 8.8 arithmetic.
Template Parameters
GridVisitor
Parameters
start start point
end end point
visitor called for each cell visited.
UNTESTED!!!!
Definition at line 122 of file traverse_grid.h.
{
    const int16_t FP_SHIFT = 8;
    const int16_t FP_ONE = 1 << FP_SHIFT;
    // const int16_t FP_MASK = FP_ONE - 1;
    // Convert to fixed-point (Q8.8), signed
    int16_t startX_fp = static_cast<int16_t>(start.x * FP_ONE);
    int16_t startY_fp = static_cast<int16_t>(start.y * FP_ONE);
    int16_t endX_fp = static_cast<int16_t>(end.x * FP_ONE);
    int16_t endY_fp = static_cast<int16_t>(end.y * FP_ONE);
    int16_t x0 = startX_fp >> FP_SHIFT;
    int16_t y0 = startY_fp >> FP_SHIFT;
    int16_t x1 = endX_fp >> FP_SHIFT;
    int16_t y1 = endY_fp >> FP_SHIFT;
    int16_t stepX = (x1 > x0) ? 1 : (x1 < x0) ? -1 : 0;
    int16_t stepY = (y1 > y0) ? 1 : (y1 < y0) ? -1 : 0;
    int16_t deltaX_fp = endX_fp - startX_fp;
    int16_t deltaY_fp = endY_fp - startY_fp;
    uint16_t absDeltaX_fp =
        (deltaX_fp != 0) ? static_cast<uint16_t>(
                               ABS((int32_t(FP_ONE) << FP_SHIFT) / deltaX_fp))
                         : UINT16_MAX;
    uint16_t absDeltaY_fp =
        (deltaY_fp != 0) ? static_cast<uint16_t>(
                               ABS((int32_t(FP_ONE) << FP_SHIFT) / deltaY_fp))
                         : UINT16_MAX;
    int16_t nextX_fp = (stepX > 0) ? ((x0 + 1) << FP_SHIFT) : (x0 << FP_SHIFT);
    int16_t nextY_fp = (stepY > 0) ? ((y0 + 1) << FP_SHIFT) : (y0 << FP_SHIFT);
    uint16_t tMaxX_fp =
        (deltaX_fp != 0)
            ? static_cast<uint16_t>(
                  ABS(int32_t(nextX_fp - startX_fp)) * absDeltaX_fp >> FP_SHIFT)
            : UINT16_MAX;
    uint16_t tMaxY_fp =
        (deltaY_fp != 0)
            ? static_cast<uint16_t>(
                  ABS(int32_t(nextY_fp - startY_fp)) * absDeltaY_fp >> FP_SHIFT)
            : UINT16_MAX;
    const uint16_t maxT_fp = FP_ONE;
    int16_t currentX = x0;
    int16_t currentY = y0;
    while (true) {
        visitor.visit(currentX, currentY);
        uint16_t t_fp = (tMaxX_fp < tMaxY_fp) ? tMaxX_fp : tMaxY_fp;
        if (t_fp > maxT_fp)
            break;
        if (tMaxX_fp < tMaxY_fp) {
            tMaxX_fp += absDeltaX_fp;
            currentX += stepX;
        } else {
            tMaxY_fp += absDeltaY_fp;
            currentY += stepY;
        }
    }
    // Ensure the end cell (x1, y1) is visited at least once
    if (currentX != x1 || currentY != y1) {
        visitor.visit(x1, y1);
    }
}
References ABS, fl::vec2< T >::x, and fl::vec2< T >::y.
Referenced by traverseGridSegment().
traverseGridSegment32()
template<typename GridVisitor> void fl::traverseGridSegment32 (const vec2f & start, const vec2f & end, GridVisitor & visitor) inline
Template Parameters
GridVisitor
Parameters
start start point
end end point
visitor called for each cell visited.
UNTESTED!!!!
Definition at line 202 of file traverse_grid.h.
{
    const int32_t FP_SHIFT = 8;
    const int32_t FP_ONE = 1 << FP_SHIFT;
    // const int32_t FP_MASK = FP_ONE - 1;
    // Convert to fixed-point (Q24.8) signed
    int32_t startX_fp = static_cast<int32_t>(start.x * FP_ONE);
    int32_t startY_fp = static_cast<int32_t>(start.y * FP_ONE);
    int32_t endX_fp = static_cast<int32_t>(end.x * FP_ONE);
    int32_t endY_fp = static_cast<int32_t>(end.y * FP_ONE);
    int32_t x0 = startX_fp >> FP_SHIFT;
    int32_t y0 = startY_fp >> FP_SHIFT;
    int32_t x1 = endX_fp >> FP_SHIFT;
    int32_t y1 = endY_fp >> FP_SHIFT;
    int32_t stepX = (x1 > x0) ? 1 : (x1 < x0) ? -1 : 0;
    int32_t stepY = (y1 > y0) ? 1 : (y1 < y0) ? -1 : 0;
    int32_t deltaX_fp = endX_fp - startX_fp;
    int32_t deltaY_fp = endY_fp - startY_fp;
    uint32_t absDeltaX_fp =
        (deltaX_fp != 0) ? static_cast<uint32_t>(
                               ABS((int64_t(FP_ONE) << FP_SHIFT) / deltaX_fp))
                         : UINT32_MAX;
    uint32_t absDeltaY_fp =
        (deltaY_fp != 0) ? static_cast<uint32_t>(
                               ABS((int64_t(FP_ONE) << FP_SHIFT) / deltaY_fp))
                         : UINT32_MAX;
    int32_t nextX_fp = (stepX > 0) ? ((x0 + 1) << FP_SHIFT) : (x0 << FP_SHIFT);
    int32_t nextY_fp = (stepY > 0) ? ((y0 + 1) << FP_SHIFT) : (y0 << FP_SHIFT);
    uint32_t tMaxX_fp =
        (deltaX_fp != 0)
            ? static_cast<uint32_t>(
                  ABS(int64_t(nextX_fp - startX_fp)) * absDeltaX_fp >> FP_SHIFT)
            : UINT32_MAX;
    uint32_t tMaxY_fp =
        (deltaY_fp != 0)
            ? static_cast<uint32_t>(
                  ABS(int64_t(nextY_fp - startY_fp)) * absDeltaY_fp >> FP_SHIFT)
            : UINT32_MAX;
    const uint32_t maxT_fp = FP_ONE;
    int32_t currentX = x0;
    int32_t currentY = y0;
    while (true) {
        visitor.visit(currentX, currentY);
        uint32_t t_fp = (tMaxX_fp < tMaxY_fp) ? tMaxX_fp : tMaxY_fp;
        if (t_fp > maxT_fp)
            break;
        if (tMaxX_fp < tMaxY_fp) {
            tMaxX_fp += absDeltaX_fp;
            currentX += stepX;
        } else {
            tMaxY_fp += absDeltaY_fp;
            currentY += stepY;
        }
    }
    if (currentX != x1 || currentY != y1) {
        visitor.visit(x1, y1);
    }
}
References ABS, fl::vec2< T >::x, and fl::vec2< T >::y.
Referenced by traverseGridSegment().
traverseGridSegmentFloat()
template<typename GridVisitor> void fl::traverseGridSegmentFloat (const vec2f & start, const vec2f & end, GridVisitor & visitor) inline
Traverse a grid segment using floating point arithmetic.
Traverse a grid segment using fixed-point 8.8 arithmetic.
Useful for testing.
Template Parameters
GridVisitor
Parameters
start start point
end end point
visitor called for each cell visited.
Fully tested.
Template Parameters
GridVisitor
Parameters
start start point
end end point
visitor called for each cell visited.
Fully tested.
Definition at line 67 of file traverse_grid.h.
{
    int x0 = static_cast<int>(fl::floor(start.x));
    int y0 = static_cast<int>(fl::floor(start.y));
    int x1 = static_cast<int>(fl::floor(end.x));
    int y1 = static_cast<int>(fl::floor(end.y));
    int stepX = (x1 > x0) ? 1 : (x1 < x0) ? -1 : 0;
    int stepY = (y1 > y0) ? 1 : (y1 < y0) ? -1 : 0;
    float dx = end.x - start.x;
    float dy = end.y - start.y;
    float tDeltaX = (dx != 0.0f) ? ABS(1.0f / dx) : FLT_MAX;
    float tDeltaY = (dy != 0.0f) ? ABS(1.0f / dy) : FLT_MAX;
    float nextX = (stepX > 0) ? (fl::floor(start.x) + 1) : fl::floor(start.x);
    float nextY = (stepY > 0) ? (fl::floor(start.y) + 1) : fl::floor(start.y);
    float tMaxX = (dx != 0.0f) ? ABS((nextX - start.x) / dx) : FLT_MAX;
    float tMaxY = (dy != 0.0f) ? ABS((nextY - start.y) / dy) : FLT_MAX;
    float maxT = 1.0f;
    int currentX = x0;
    int currentY = y0;
    while (true) {
        visitor.visit(currentX, currentY);
        float t = MIN(tMaxX, tMaxY);
        if (t > maxT)
            break;
        if (tMaxX < tMaxY) {
            tMaxX += tDeltaX;
            currentX += stepX;
        } else {
            tMaxY += tDeltaY;
            currentY += stepY;
        }
    }
    // Ensure the end cell (x1, y1) is visited at least once
    if (currentX != x1 || currentY != y1) {
        visitor.visit(x1, y1);
    }
}
References ABS, floor(), FLT_MAX, MIN, fl::vec2< T >::x, and fl::vec2< T >::y.
UpscalePalette() [1/6]
void fl::UpscalePalette (const class CHSVPalette16 & srcpal16, class CHSVPalette256 & destpal256)
Definition at line 969 of file colorutils.cpp.
{
    for (int i = 0; i < 256; ++i) {
        destpal256[(uint8_t)(i)] = ColorFromPalette(srcpal16, i);
    }
}
References ColorFromPalette().
UpscalePalette() [2/6]
void fl::UpscalePalette (const class CHSVPalette16 & srcpal16, class CHSVPalette32 & destpal32)
Definition at line 985 of file colorutils.cpp.
{
    for (uint8_t i = 0; i < 16; ++i) {
        uint8_t j = i * 2;
        destpal32[j + 0] = srcpal16[i];
        destpal32[j + 1] = srcpal16[i];
    }
}
UpscalePalette() [3/6]
void fl::UpscalePalette (const class CHSVPalette32 & srcpal32, class CHSVPalette256 & destpal256)
Definition at line 1001 of file colorutils.cpp.
{
    for (int i = 0; i < 256; ++i) {
        destpal256[(uint8_t)(i)] = ColorFromPalette(srcpal32, i);
    }
}
References ColorFromPalette().
UpscalePalette() [4/6]
void fl::UpscalePalette (const class CRGBPalette16 & srcpal16, class CRGBPalette256 & destpal256)
Definition at line 962 of file colorutils.cpp.
{
    for (int i = 0; i < 256; ++i) {
        destpal256[(uint8_t)(i)] = ColorFromPalette(srcpal16, i);
    }
}
References ColorFromPalette().
UpscalePalette() [5/6]
void fl::UpscalePalette (const class CRGBPalette16 & srcpal16, class CRGBPalette32 & destpal32)
Definition at line 976 of file colorutils.cpp.
{
    for (uint8_t i = 0; i < 16; ++i) {
        uint8_t j = i * 2;
        destpal32[j + 0] = srcpal16[i];
        destpal32[j + 1] = srcpal16[i];
    }
}
UpscalePalette() [6/6]
void fl::UpscalePalette (const class CRGBPalette32 & srcpal32, class CRGBPalette256 & destpal256)
Definition at line 994 of file colorutils.cpp.
{
    for (int i = 0; i < 256; ++i) {
        destpal256[(uint8_t)(i)] = ColorFromPalette(srcpal32, i);
    }
}
References ColorFromPalette().
worley_noise_2d_q15()
int32_t fl::worley_noise_2d_q15 (int32_t x, int32_t y)
Definition at line 33 of file noise_woryley.cpp.
{
    int32_t cell_x = x >> 15;
    int32_t cell_y = y >> 15;
    int32_t min_dist = INT32_MAX;
    // Check surrounding 9 cells
    for (int dy = -1; dy <= 1; ++dy) {
        for (int dx = -1; dx <= 1; ++dx) {
            int32_t gx = cell_x + dx;
            int32_t gy = cell_y + dy;
            int32_t fx, fy;
            feature_point(gx, gy, fx, fy);
            int32_t feature_x = (gx << 15) + fx;
            int32_t feature_y = (gy << 15) + fy;
            int32_t dx_q15 = x - feature_x;
            int32_t dy_q15 = y - feature_y;
            // Approximate distance using Manhattan (faster) or Euclidean
            // (costlier)
            int32_t dist =
                q15_abs(dx_q15) + q15_abs(dy_q15); // Manhattan distance
            if (dist < min_dist)
                min_dist = dist;
        }
    }
    // Normalize: maximum possible distance is roughly 2*Q15_ONE
    return (min_dist << 15) / (2 * Q15_ONE);
}
References INT32_MAX, x, and y.
x_linear()
FASTLED_FORCE_INLINE uint16_t fl::x_linear (uint16_t x, uint16_t length)
Definition at line 14 of file xmap.h.
{
    (void)length;
    return x;
}
References FASTLED_FORCE_INLINE, length(), and x.
Referenced by fl::XMap::mapToIndex().
x_reverse()
FASTLED_FORCE_INLINE uint16_t fl::x_reverse (uint16_t x, uint16_t length)
Definition at line 19 of file xmap.h.
{
    return length - 1 - x;
}
References FASTLED_FORCE_INLINE, length(), and x.
Referenced by fl::XMap::mapToIndex().
XY()
uint8_t XY (uint8_t x, uint8_t y)
Definition at line 21 of file blur.cpp.
{
    FASTLED_UNUSED(x);
    FASTLED_UNUSED(y);
    FASTLED_ASSERT(false, "the user didn't provide an XY function");
    return 0;
}
References FASTLED_UNUSED, x, and y.
Referenced by Fire2023(), loop(), and fl::anonymous_namespace{blur.cpp}::xy_legacy_wrapper().
xy_line_by_line()
FASTLED_FORCE_INLINE uint16_t fl::xy_line_by_line (uint16_t x, uint16_t y, uint16_t width, uint16_t height)
Definition at line 27 of file xymap.h.
{
    (void)height;
    return y * width + x;
}
References FASTLED_FORCE_INLINE, x, and y.
Referenced by fl::XYMap::mapToIndex().
xy_serpentine()
FASTLED_FORCE_INLINE uint16_t fl::xy_serpentine (uint16_t x, uint16_t y, uint16_t width, uint16_t height)
Definition at line 17 of file xymap.h.
{
    (void)height;
    if (y & 1) // Even or odd row?
        // reverse every second line for a serpentine lled layout
        return (y + 1) * width - 1 - x;
    else
        return y * width + x;
}
References FASTLED_FORCE_INLINE, x, and y.
Referenced by fl::XYMap::mapToIndex().
Variable Documentation
ActivePaletteList
const TProgmemRGBPalette16* fl::ActivePaletteList[]
Initial value:
= {
    &RetroC9_p,       &BlueWhite_p,   &RainbowColors_p, &FairyLight_p,
    &RedGreenWhite_p, &PartyColors_p, &RedWhite_p,      &Snow_p,
    &Holly_p,         &Ice_p}
Definition at line 293 of file twinklefox.h.
{
    &RetroC9_p,       &BlueWhite_p,   &RainbowColors_p, &FairyLight_p,
    &RedGreenWhite_p, &PartyColors_p, &RedWhite_p,      &Snow_p,
    &Holly_p,         &Ice_p};
Referenced by fl::TwinkleFox::chooseNextColorPalette().
ANIMATION_TABLE
const AnimartrixEntry fl::ANIMATION_TABLE[] static
Definition at line 170 of file animartrix.hpp.
{
    {RGB_BLOBS5, "RGB_BLOBS5", &FastLEDANIMartRIX::RGB_Blobs5},
    {RGB_BLOBS4, "RGB_BLOBS4", &FastLEDANIMartRIX::RGB_Blobs4},
    {RGB_BLOBS3, "RGB_BLOBS3", &FastLEDANIMartRIX::RGB_Blobs3},
    {RGB_BLOBS2, "RGB_BLOBS2", &FastLEDANIMartRIX::RGB_Blobs2},
    {RGB_BLOBS, "RGB_BLOBS", &FastLEDANIMartRIX::RGB_Blobs},
    {POLAR_WAVES, "POLAR_WAVES", &FastLEDANIMartRIX::Polar_Waves},
    {SLOW_FADE, "SLOW_FADE", &FastLEDANIMartRIX::Slow_Fade},
    {ZOOM2, "ZOOM2", &FastLEDANIMartRIX::Zoom2},
    {ZOOM, "ZOOM", &FastLEDANIMartRIX::Zoom},
    {HOT_BLOB, "HOT_BLOB", &FastLEDANIMartRIX::Hot_Blob},
    {SPIRALUS2, "SPIRALUS2", &FastLEDANIMartRIX::Spiralus2},
    {SPIRALUS, "SPIRALUS", &FastLEDANIMartRIX::Spiralus},
    {YVES, "YVES", &FastLEDANIMartRIX::Yves},
    {SCALEDEMO1, "SCALEDEMO1", &FastLEDANIMartRIX::Scaledemo1},
    {LAVA1, "LAVA1", &FastLEDANIMartRIX::Lava1},
    {CALEIDO3, "CALEIDO3", &FastLEDANIMartRIX::Caleido3},
    {CALEIDO2, "CALEIDO2", &FastLEDANIMartRIX::Caleido2},
    {CALEIDO1, "CALEIDO1", &FastLEDANIMartRIX::Caleido1},
    {DISTANCE_EXPERIMENT, "DISTANCE_EXPERIMENT",
     &FastLEDANIMartRIX::Distance_Experiment},
    {CENTER_FIELD, "CENTER_FIELD", &FastLEDANIMartRIX::Center_Field},
    {WAVES, "WAVES", &FastLEDANIMartRIX::Waves},
    {CHASING_SPIRALS, "CHASING_SPIRALS", &FastLEDANIMartRIX::Chasing_Spirals},
    {ROTATING_BLOB, "ROTATING_BLOB", &FastLEDANIMartRIX::Rotating_Blob},
    {RINGS, "RINGS", &FastLEDANIMartRIX::Rings},
    {COMPLEX_KALEIDO, "COMPLEX_KALEIDO", &FastLEDANIMartRIX::Complex_Kaleido},
    {COMPLEX_KALEIDO_2, "COMPLEX_KALEIDO_2",
     &FastLEDANIMartRIX::Complex_Kaleido_2},
    {COMPLEX_KALEIDO_3, "COMPLEX_KALEIDO_3",
     &FastLEDANIMartRIX::Complex_Kaleido_3},
    {COMPLEX_KALEIDO_4, "COMPLEX_KALEIDO_4",
     &FastLEDANIMartRIX::Complex_Kaleido_4},
    {COMPLEX_KALEIDO_5, "COMPLEX_KALEIDO_5",
     &FastLEDANIMartRIX::Complex_Kaleido_5},
    {COMPLEX_KALEIDO_6, "COMPLEX_KALEIDO_6",
     &FastLEDANIMartRIX::Complex_Kaleido_6},
    {WATER, "WATER", &FastLEDANIMartRIX::Water},
    {PARAMETRIC_WATER, "PARAMETRIC_WATER",
     &FastLEDANIMartRIX::Parametric_Water},
    {MODULE_EXPERIMENT1, "MODULE_EXPERIMENT1",
     &FastLEDANIMartRIX::Module_Experiment1},
    {MODULE_EXPERIMENT2, "MODULE_EXPERIMENT2",
     &FastLEDANIMartRIX::Module_Experiment2},
    {MODULE_EXPERIMENT3, "MODULE_EXPERIMENT3",
     &FastLEDANIMartRIX::Module_Experiment3},
    {MODULE_EXPERIMENT4, "MODULE_EXPERIMENT4",
     &FastLEDANIMartRIX::Module_Experiment4},
    {MODULE_EXPERIMENT5, "MODULE_EXPERIMENT5",
     &FastLEDANIMartRIX::Module_Experiment5},
    {MODULE_EXPERIMENT6, "MODULE_EXPERIMENT6",
     &FastLEDANIMartRIX::Module_Experiment6},
    {MODULE_EXPERIMENT7, "MODULE_EXPERIMENT7",
     &FastLEDANIMartRIX::Module_Experiment7},
    {MODULE_EXPERIMENT8, "MODULE_EXPERIMENT8",
     &FastLEDANIMartRIX::Module_Experiment8},
    {MODULE_EXPERIMENT9, "MODULE_EXPERIMENT9",
     &FastLEDANIMartRIX::Module_Experiment9},
    {MODULE_EXPERIMENT10, "MODULE_EXPERIMENT10",
     &FastLEDANIMartRIX::Module_Experiment10},
    {MODULE_EXPERIMENT_SM1, "MODULE_EXPERIMENT_SM1", &FastLEDANIMartRIX::SM1},
    {MODULE_EXPERIMENT_SM2, "MODULE_EXPERIMENT_SM2", &FastLEDANIMartRIX::SM2},
    {MODULE_EXPERIMENT_SM3, "MODULE_EXPERIMENT_SM3", &FastLEDANIMartRIX::SM3},
    {MODULE_EXPERIMENT_SM4, "MODULE_EXPERIMENT_SM4", &FastLEDANIMartRIX::SM4},
    {MODULE_EXPERIMENT_SM5, "MODULE_EXPERIMENT_SM5", &FastLEDANIMartRIX::SM5},
    {MODULE_EXPERIMENT_SM6, "MODULE_EXPERIMENT_SM6", &FastLEDANIMartRIX::SM6},
    {MODULE_EXPERIMENT_SM8, "MODULE_EXPERIMENT_SM8", &FastLEDANIMartRIX::SM8},
    {MODULE_EXPERIMENT_SM9, "MODULE_EXPERIMENT_SM9", &FastLEDANIMartRIX::SM9},
    {MODULE_EXPERIMENT_SM10, "MODULE_EXPERIMENT_SM10",
     &FastLEDANIMartRIX::SM10},
};
Referenced by fl::Animartrix::getAnimationName(), and fl::FastLEDANIMartRIX::loop().
BlueWhite_p
const TProgmemRGBPalette16 fl::BlueWhite_p
Initial value:
= {
    CRGB::Blue, CRGB::Blue, CRGB::Blue, CRGB::Blue, CRGB::Blue, CRGB::Blue,
    CRGB::Blue, CRGB::Blue, CRGB::Blue, CRGB::Blue, CRGB::Blue, CRGB::Blue,
    CRGB::Blue, CRGB::Gray, CRGB::Gray, CRGB::Gray}
Definition at line 253 of file twinklefox.h.
{
    CRGB::Blue, CRGB::Blue, CRGB::Blue, CRGB::Blue, CRGB::Blue, CRGB::Blue,
    CRGB::Blue, CRGB::Blue, CRGB::Blue, CRGB::Blue, CRGB::Blue, CRGB::Blue,
    CRGB::Blue, CRGB::Gray, CRGB::Gray, CRGB::Gray};
cosArray
const int16_t * fl::cosArray = &sinLut[64]
Definition at line 47 of file sin32.cpp.
Referenced by cos16lut(), and cos32().
FairyLight_p
const TProgmemRGBPalette16 fl::FairyLight_p
Initial value:
= {
    CRGB::FairyLight,
    CRGB::FairyLight,
    CRGB::FairyLight,
    CRGB::FairyLight,
    CRGB(CRGB::FairyLight).nscale8_constexpr(uint8_t(128)).as_uint32_t(),
    CRGB(CRGB::FairyLight).nscale8_constexpr(uint8_t(128)).as_uint32_t(),
    CRGB::FairyLight,
    CRGB::FairyLight,
    CRGB(CRGB::FairyLight).nscale8_constexpr(64).as_uint32_t(),
    CRGB(CRGB::FairyLight).nscale8_constexpr(64).as_uint32_t(),
    CRGB::FairyLight,
    CRGB::FairyLight,
    CRGB::FairyLight,
    CRGB::FairyLight,
    CRGB::FairyLight,
    CRGB::FairyLight}
Definition at line 258 of file twinklefox.h.
{
    CRGB::FairyLight,
    CRGB::FairyLight,
    CRGB::FairyLight,
    CRGB::FairyLight,
    CRGB(CRGB::FairyLight).nscale8_constexpr(uint8_t(128)).as_uint32_t(),
    CRGB(CRGB::FairyLight).nscale8_constexpr(uint8_t(128)).as_uint32_t(),
    CRGB::FairyLight,
    CRGB::FairyLight,
    CRGB(CRGB::FairyLight).nscale8_constexpr(64).as_uint32_t(),
    CRGB(CRGB::FairyLight).nscale8_constexpr(64).as_uint32_t(),
    CRGB::FairyLight,
    CRGB::FairyLight,
    CRGB::FairyLight,
    CRGB::FairyLight,
    CRGB::FairyLight,
    CRGB::FairyLight};
gFlexFFT
FFT fl::gFlexFFT static
Definition at line 110 of file audio.cpp.
Referenced by fl::AudioSample::fft().
Holly_p
const TProgmemRGBPalette16 fl::Holly_p
Initial value:
= {
    0x00580c, 0x00580c, 0x00580c, 0x00580c, 0x00580c, 0x00580c,
    0x00580c, 0x00580c, 0x00580c, 0x00580c, 0x00580c, 0x00580c,
    0x00580c, 0x00580c, 0x00580c, 0xB00402}
Definition at line 243 of file twinklefox.h.
{
    0x00580c, 0x00580c, 0x00580c, 0x00580c, 0x00580c, 0x00580c,
    0x00580c, 0x00580c, 0x00580c, 0x00580c, 0x00580c, 0x00580c,
    0x00580c, 0x00580c, 0x00580c, 0xB00402};
Ice_p
const TProgmemRGBPalette16 fl::Ice_p
Initial value:
= {
    0x0C1040, 0x0C1040, 0x0C1040, 0x0C1040, 0x0C1040, 0x0C1040,
    0x0C1040, 0x0C1040, 0x0C1040, 0x0C1040, 0x0C1040, 0x0C1040,
    0x182080, 0x182080, 0x182080, 0x5080C0}
Definition at line 286 of file twinklefox.h.
{
    0x0C1040, 0x0C1040, 0x0C1040, 0x0C1040, 0x0C1040, 0x0C1040,
    0x0C1040, 0x0C1040, 0x0C1040, 0x0C1040, 0x0C1040, 0x0C1040,
    0x182080, 0x182080, 0x182080, 0x5080C0};
instead
void const fl::XYMap& xymap fl::instead
Definition at line 52 of file blur.h.
RedGreenWhite_p
const TProgmemRGBPalette16 fl::RedGreenWhite_p
Initial value:
= {
    CRGB::Red,   CRGB::Red,   CRGB::Red,   CRGB::Red,  CRGB::Red,  CRGB::Red,
    CRGB::Red,   CRGB::Red,   CRGB::Red,   CRGB::Red,  CRGB::Gray, CRGB::Gray,
    CRGB::Green, CRGB::Green, CRGB::Green, CRGB::Green}
Definition at line 238 of file twinklefox.h.
{
    CRGB::Red,   CRGB::Red,   CRGB::Red,   CRGB::Red,  CRGB::Red,  CRGB::Red,
    CRGB::Red,   CRGB::Red,   CRGB::Red,   CRGB::Red,  CRGB::Gray, CRGB::Gray,
    CRGB::Green, CRGB::Green, CRGB::Green, CRGB::Green};
RedWhite_p
const TProgmemRGBPalette16 fl::RedWhite_p
Initial value:
= {
    CRGB::Red,  CRGB::Red,  CRGB::Red,  CRGB::Red, CRGB::Gray, CRGB::Gray,
    CRGB::Gray, CRGB::Gray, CRGB::Red,  CRGB::Red, CRGB::Red,  CRGB::Red,
    CRGB::Gray, CRGB::Gray, CRGB::Gray, CRGB::Gray}
Definition at line 248 of file twinklefox.h.
{
    CRGB::Red,  CRGB::Red,  CRGB::Red,  CRGB::Red, CRGB::Gray, CRGB::Gray,
    CRGB::Gray, CRGB::Gray, CRGB::Red,  CRGB::Red, CRGB::Red,  CRGB::Red,
    CRGB::Gray, CRGB::Gray, CRGB::Gray, CRGB::Gray};
RetroC9_p
const TProgmemRGBPalette16 fl::RetroC9_p
Initial value:
= {
    0xB80400, 0x902C02, 0xB80400, 0x902C02, 0x902C02, 0xB80400,
    0x902C02, 0xB80400, 0x046002, 0x046002, 0x046002, 0x046002,
    0x070758, 0x070758, 0x070758, 0x606820}
Definition at line 281 of file twinklefox.h.
{
    0xB80400, 0x902C02, 0xB80400, 0x902C02, 0x902C02, 0xB80400,
    0x902C02, 0xB80400, 0x046002, 0x046002, 0x046002, 0x046002,
    0x070758, 0x070758, 0x070758, 0x606820};
sinArray
const int16_t * fl::sinArray = &sinLut[0]
Definition at line 45 of file sin32.cpp.
Referenced by sin16lut(), and sin32().
sinLut
const int16_t fl::sinLut[]
Definition at line 7 of file sin32.cpp.
{
    0,      804,    1608,   2410,   3212,   4011,   4808,   5602,   6393,
    7179,   7962,   8739,   9512,   10278,  11039,  11793,  12539,  13279,
    14010,  14732,  15446,  16151,  16846,  17530,  18204,  18868,  19519,
    20159,  20787,  21403,  22005,  22594,  23170,  23731,  24279,  24811,
    25329,  25832,  26319,  26790,  27245,  27683,  28105,  28510,  28898,
    29268,  29621,  29956,  30273,  30571,  30852,  31113,  31356,  31580,
    31785,  31971,  32137,  32285,  32412,  32521,  32609,  32678,  32728,
    32757,  32767,  32757,  32728,  32678,  32609,  32521,  32412,  32285,
    32137,  31971,  31785,  31580,  31356,  31113,  30852,  30571,  30273,
    29956,  29621,  29268,  28898,  28510,  28105,  27683,  27245,  26790,
    26319,  25832,  25329,  24811,  24279,  23731,  23170,  22594,  22005,
    21403,  20787,  20159,  19519,  18868,  18204,  17530,  16846,  16151,
    15446,  14732,  14010,  13279,  12539,  11793,  11039,  10278,  9512,
    8739,   7962,   7179,   6393,   5602,   4808,   4011,   3212,   2410,
    1608,   804,    0,      -804,   -1608,  -2410,  -3212,  -4011,  -4808,
    -5602,  -6393,  -7179,  -7962,  -8739,  -9512,  -10278, -11039, -11793,
    -12539, -13279, -14010, -14732, -15446, -16151, -16846, -17530, -18204,
    -18868, -19519, -20159, -20787, -21403, -22005, -22594, -23170, -23731,
    -24279, -24811, -25329, -25832, -26319, -26790, -27245, -27683, -28105,
    -28510, -28898, -29268, -29621, -29956, -30273, -30571, -30852, -31113,
    -31356, -31580, -31785, -31971, -32137, -32285, -32412, -32521, -32609,
    -32678, -32728, -32757, -32767, -32757, -32728, -32678, -32609, -32521,
    -32412, -32285, -32137, -31971, -31785, -31580, -31356, -31113, -30852,
    -30571, -30273, -29956, -29621, -29268, -28898, -28510, -28105, -27683,
    -27245, -26790, -26319, -25832, -25329, -24811, -24279, -23731, -23170,
    -22594, -22005, -21403, -20787, -20159, -19519, -18868, -18204, -17530,
    -16846, -16151, -15446, -14732, -14010, -13279, -12539, -11793, -11039,
    -10278, -9512,  -8739,  -7962,  -7179,  -6393,  -5602,  -4808,  -4011,
    -3212,  -2410,  -1608,  -804,   0,      804,    1608,   2410,   3212,
    4011,   4808,   5602,   6393,   7179,   7962,   8739,   9512,   10278,
    11039,  11793,  12539,  13279,  14010,  14732,  15446,  16151,  16846,
    17530,  18204,  18868,  19519,  20159,  20787,  21403,  22005,  22594,
    23170,  23731,  24279,  24811,  25329,  25832,  26319,  26790,  27245,
    27683,  28105,  28510,  28898,  29268,  29621,  29956,  30273,  30571,
    30852,  31113,  31356,  31580,  31785,  31971,  32137,  32285,  32412,
    32521,  32609,  32678,  32728,  32757,  32767};
Snow_p
const TProgmemRGBPalette16 fl::Snow_p
Initial value:
= {
    0x304048, 0x304048, 0x304048, 0x304048, 0x304048, 0x304048,
    0x304048, 0x304048, 0x304048, 0x304048, 0x304048, 0x304048,
    0x304048, 0x304048, 0x304048, 0xE0F0FF}
Definition at line 276 of file twinklefox.h.
{
    0x304048, 0x304048, 0x304048, 0x304048, 0x304048, 0x304048,
    0x304048, 0x304048, 0x304048, 0x304048, 0x304048, 0x304048,
    0x304048, 0x304048, 0x304048, 0xE0F0FF};