FastLED: fl::createSerialRequestSource
createSerialRequestSource()
fl::function< fl::optional< fl::json >()> fl::createSerialRequestSource (const char * prefix = "") inline
Create a JSON-RPC RequestSource that reads from fl:: serial input.
Parameters
prefix Optional prefix to strip from input lines (default: "")
Returns
RequestSource callback suitable for fl::Remote constructor
Note
Composes transport layer (serial I/O) with protocol layer (JSON-RPC normalization)
Example:
auto requestSource = fl::createSerialRequestSource();
auto responseSink = fl::createSerialResponseSink("REMOTE: ");
fl::Remote remote(requestSource, responseSink);
Definition at line 109 of file serial.h.
{
    return [prefix]() -> fl::optional<fl::json> {
        // Non-blocking check - any data available?
        int avail = fl::available();
        if (avail <= 0) {
            return fl::nullopt;
        }
        // Data available - read a complete line.
        // On Arduino platforms, fl::readLine() delegates to Serial.readStringUntil()
        // which uses yield() (immediate context switch) for fast USB CDC multi-packet
        // assembly. On other platforms, falls back to character-by-character reading.
        auto line = fl::readLine('\n', '\r', fl::optional<u32>(1000));
        if (!line.has_value() || line->empty()) {
            return fl::nullopt;
        }
        // Use string_view for zero-copy prefix stripping and trimming
        fl::string_view view = *line;
        // Strip prefix if present
        if (prefix && prefix[0] != '\0') {
            if (view.starts_with(prefix)) {
                view.remove_prefix(fl::strlen(prefix));
            }
        }
        // Trim leading whitespace
        while (!view.empty() && fl::isspace(view.front())) {
            view.remove_prefix(1);
        }
        // Trim trailing whitespace
        while (!view.empty() && fl::isspace(view.back())) {
            view.remove_suffix(1);
        }
        // Only parse if input starts with '{'
        if (view.empty() || view[0] != '{') {
            return fl::nullopt;
        }
        // Single copy when parsing JSON (unavoidable - JSON needs owned string)
        fl::string input(view);
        return fl::json::parse(input);
    };
}
References available(), fl::string_view::back(), fl::string_view::empty(), fl::string_view::front(), isspace(), nullopt, fl::json::parse(), readLine(), fl::string_view::remove_prefix(), fl::string_view::remove_suffix(), fl::string_view::starts_with(), and strlen().
Referenced by autoResearchLowMemorySetup(), and createSerialTransport().