FastLED: fl::downscaleHalf
downscaleHalf() [1/2]
void fl::downscaleHalf (const CRGB * src, const XYMap & srcXY, CRGB * dst, const XYMap & dstXY)
Definition at line 46 of file downscale.cpp.
{
    uint16_t dstWidth = dstXY.getWidth();
    uint16_t dstHeight = dstXY.getHeight();
    FASTLED_ASSERT(srcXY.getWidth() == dstXY.getWidth() * 2,
                   "Source width must be double the destination width");
    FASTLED_ASSERT(srcXY.getHeight() == dstXY.getHeight() * 2,
                   "Source height must be double the destination height");
    for (uint16_t y = 0; y < dstHeight; ++y) {
        for (uint16_t x = 0; x < dstWidth; ++x) {
            // Map to top-left of the 2x2 block in source
            uint16_t srcX = x * 2;
            uint16_t srcY = y * 2;
            // Fetch 2x2 block
            const CRGB &p00 = src[srcXY.mapToIndex(srcX, srcY)];
            const CRGB &p10 = src[srcXY.mapToIndex(srcX + 1, srcY)];
            const CRGB &p01 = src[srcXY.mapToIndex(srcX, srcY + 1)];
            const CRGB &p11 = src[srcXY.mapToIndex(srcX + 1, srcY + 1)];
            // Average each color channel
            uint16_t r =
                (p00.r + p10.r + p01.r + p11.r + 2) / 4; // +2 for rounding
            uint16_t g = (p00.g + p10.g + p01.g + p11.g + 2) / 4;
            uint16_t b = (p00.b + p10.b + p01.b + p11.b + 2) / 4;
            // Store result
            dst[dstXY.mapToIndex(x, y)] =
                CRGB((uint8_t)r, (uint8_t)g, (uint8_t)b);
        }
    }
}
References fl::XYMap::getHeight(), fl::XYMap::getWidth(), fl::XYMap::mapToIndex(), x, and y.