FastLED: fl::x
x
fl::x = *(u32*)(A+4)
Definition at line 24 of file transposition.cpp.hpp.
Referenced by fl::Gamma8Impl::Gamma8Impl(), fl::Leds::Leds(), fl::PointPath::PointPath(), fl::anonymous_namespace{channel.cpp.hpp}::ReorderingPixelIteratorAny::ReorderingPixelIteratorAny(), fl::ScreenMap::ScreenMap(), fl::ScreenMap::ScreenMap(), fl::WaveSimulation1D::~WaveSimulation1D(), fl::WaveSimulation2D_Real::~WaveSimulation2D_Real(), _isqrt32_start(), _isqrt32_step(), _isqrt64_start(), _isqrt64_step(), abs(), abs(), fl::fixed_point< IntBits, FracBits, Sign::SIGNED >< IntBits, FracBits >::abs(), fl::fixed_point_base< Derived, IntBits, FracBits >::abs(), fl::s0x32::abs(), fl::s12x4::abs(), fl::s16x16::abs(), fl::s24x8::abs(), fl::s4x12::abs(), fl::s8x24::abs(), fl::s8x8::abs(), fl::u12x4::abs(), fl::u24x8::abs(), fl::u4x12::abs(), fl::u8x8::abs(), fl::Grid< T >::access(), fl::Grid< T >::access(), acos(), fl::fixed_point< IntBits, FracBits, Sign::SIGNED >< IntBits, FracBits >::acos(), fl::fixed_point_base< Derived, IntBits, FracBits >::acos(), fl::s12x4::acos(), fl::s16x16::acos(), fl::s24x8::acos(), fl::s4x12::acos(), fl::s8x24::acos(), fl::s8x8::acos(), fl::Engine::add(), fl::WaveFx::addf(), fl::ScreenMap::addOffsetX(), fl::gfx::addPixelToBuffer(), fl::CatmullRomParams::addPoint(), fl::CatmullRomPath::addPoint(), fl::third_party::AntiAlias(), fl::gfx::blur_detail::interior_row< 0, RGB_T, acc_t >::apply(), fl::gfx::blur_detail::interior_row< 1, RGB_T, acc_t >::apply(), fl::gfx::blur_detail::interior_row< 2, RGB_T, acc_t >::apply(), fl::gfx::blur_detail::interior_row< 3, RGB_T, acc_t >::apply(), fl::gfx::blur_detail::interior_row< 4, RGB_T, acc_t >::apply(), fl::gfx::blur_detail::vpass_pixel_kernel< 0, RGB_T, acc_t >::apply(), fl::gfx::blur_detail::vpass_pixel_kernel< 1, RGB_T, acc_t >::apply(), fl::gfx::blur_detail::vpass_pixel_kernel< 2, RGB_T, acc_t >::apply(), fl::gfx::blur_detail::vpass_pixel_kernel< 3, RGB_T, acc_t >::apply(), fl::gfx::blur_detail::vpass_pixel_kernel< 4, RGB_T, acc_t >::apply(), applyGamma_video(), asin(), fl::fixed_point< IntBits, FracBits, Sign::SIGNED >< IntBits, FracBits >::asin(), fl::fixed_point_base< Derived, IntBits, FracBits >::asin(), fl::s12x4::asin(), fl::s16x16::asin(), fl::s24x8::asin(), fl::s4x12::asin(), fl::s8x24::asin(), fl::s8x8::asin(), fl::Canvas< RGB_T >::at(), fl::Canvas< RGB_T >::at(), fl::gfx::Canvas< RGB_T >::at(), fl::gfx::Canvas< RGB_T >::at(), fl::gfx::CanvasMapped< RGB_T >::at(), fl::gfx::CanvasMapped< RGB_T >::at(), fl::Grid< T >::at(), fl::Grid< T >::at(), fl::Leds::at(), fl::Leds::at(), fl::MatrixSlice< T >::at(), fl::MatrixSlice< T >::at(), fl::Tile2x2_u8::at(), fl::Tile2x2_u8::at(), fl::Tile2x2_u8_wrap::at(), fl::Tile2x2_u8_wrap::at(), fl::XYRasterSparse_RGB8::at(), fl::XYRasterU8Sparse::at(), atan(), fl::fixed_point< IntBits, FracBits, Sign::SIGNED >< IntBits, FracBits >::atan(), fl::fixed_point_base< Derived, IntBits, FracBits >::atan(), fl::s12x4::atan(), fl::s16x16::atan(), fl::s24x8::atan(), fl::s4x12::atan(), fl::s8x24::atan(), fl::s8x8::atan(), atan2(), atan2(), fl::fixed_point< IntBits, FracBits, Sign::SIGNED >< IntBits, FracBits >::atan2(), fl::fixed_point_base< Derived, IntBits, FracBits >::atan2(), fl::s12x4::atan2(), fl::s16x16::atan2(), fl::s24x8::atan2(), fl::s4x12::atan2(), fl::s8x24::atan2(), fl::s8x8::atan2(), fl::detail::atan2_full_(), atan2_impl_double(), atan2_impl_float(), atan2f(), fl::gfx::blurGaussianMappedImpl(), fl::Corkscrew::calculateTileAtWrap(), ceil(), fl::fixed_point< IntBits, FracBits, Sign::SIGNED >< IntBits, FracBits >::ceil(), fl::fixed_point_base< Derived, IntBits, FracBits >::ceil(), fl::s12x4::ceil(), fl::s16x16::ceil(), fl::s24x8::ceil(), fl::s4x12::ceil(), fl::s8x24::ceil(), fl::s8x8::ceil(), fl::u12x4::ceil(), fl::u16x16::ceil(), fl::u24x8::ceil(), fl::u4x12::ceil(), fl::u8x24::ceil(), fl::u8x8::ceil(), fl::ScreenMap::Circle(), fl::PerlinParticlePunch::circleNoiseGen(), clamp(), fl::fixed_point< IntBits, FracBits, Sign::SIGNED >< IntBits, FracBits >::clamp(), fl::fixed_point_base< Derived, IntBits, FracBits >::clamp(), fl::s12x4::clamp(), fl::s16x16::clamp(), fl::s24x8::clamp(), fl::s4x12::clamp(), fl::s8x24::clamp(), fl::s8x8::clamp(), fl::u12x4::clamp(), fl::u16x16::clamp(), fl::u24x8::clamp(), fl::u4x12::clamp(), fl::u8x24::clamp(), fl::u8x8::clamp(), fl::third_party::ClipToShort(), fl::third_party::CLZ(), fl::third_party::vorbis::codebook_decode_scalar_raw(), fl::Engine::colorburn(), fl::Engine::colordodge(), fl::ArchimedeanSpiralPath::compute(), fl::CatmullRomPath::compute(), fl::CirclePath::compute(), fl::GielisCurvePath::compute(), fl::HeartPath::compute(), fl::LinePath::compute(), fl::PhyllotaxisPath::compute(), fl::RosePath::compute(), fl::third_party::vorbis::compute_sorted_huffman(), fl::rect< T >::contains(), fl::XMap::convertToLookUpTable(), fl::XYMap::convertToLookUpTable(), fl::detail::cos_poly_quarterturn_(), fl::detail::cos_reduce_(), fl::audio::fft::Bins::db(), fl::third_party::DecodeHuffmanPairs(), fl::third_party::DecodeHuffmanQuads(), fl::RedBlackTree< value_type, PairCompare, Allocator >::deleteFixup(), fl::third_party::DequantBlock(), fl::anonymous_namespace{rgbw.cpp.hpp}::divide_by_3(), fl::Big_Caleido::draw(), fl::Big_Caleido_FP::draw(), fl::Caleido1::draw(), fl::Caleido1_FP::draw(), fl::Caleido2::draw(), fl::Caleido2_FP::draw(), fl::Caleido3::draw(), fl::Caleido3_FP::draw(), fl::Center_Field::draw(), fl::Chasing_Spirals_Float::draw(), fl::Complex_Kaleido::draw(), fl::Complex_Kaleido_2::draw(), fl::Complex_Kaleido_2_FP::draw(), fl::Complex_Kaleido_3::draw(), fl::Complex_Kaleido_3_FP::draw(), fl::Complex_Kaleido_4::draw(), fl::Complex_Kaleido_4_FP::draw(), fl::Complex_Kaleido_5::draw(), fl::Complex_Kaleido_6::draw(), fl::Complex_Kaleido_6_FP::draw(), fl::Complex_Kaleido_FP::draw(), fl::Corkscrew::draw(), fl::Distance_Experiment::draw(), fl::Distance_Experiment_FP::draw(), fl::Fluffy_Blobs::draw(), fl::Fluffy_Blobs_FP::draw(), fl::Hot_Blob::draw(), fl::Hot_Blob_FP::draw(), fl::Lava1::draw(), fl::Lava1_FP::draw(), fl::Module_Experiment10::draw(), fl::Module_Experiment1::draw(), fl::Module_Experiment1_FP::draw(), fl::Module_Experiment2::draw(), fl::Module_Experiment3::draw(), fl::Module_Experiment4::draw(), fl::Module_Experiment4_FP::draw(), fl::Module_Experiment5::draw(), fl::Module_Experiment5_FP::draw(), fl::Module_Experiment6::draw(), fl::Module_Experiment6_FP::draw(), fl::Module_Experiment7::draw(), fl::Module_Experiment7_FP::draw(), fl::Module_Experiment8::draw(), fl::Module_Experiment8_FP::draw(), fl::Module_Experiment9::draw(), fl::Module_Experiment9_FP::draw(), fl::Parametric_Water::draw(), fl::Parametric_Water_FP::draw(), fl::Polar_Waves::draw(), fl::Polar_Waves_FP::draw(), fl::RedSquare::draw(), fl::RGB_Blobs2::draw(), fl::RGB_Blobs2_FP::draw(), fl::RGB_Blobs3::draw(), fl::RGB_Blobs3_FP::draw(), fl::RGB_Blobs4::draw(), fl::RGB_Blobs4_FP::draw(), fl::RGB_Blobs5::draw(), fl::RGB_Blobs5_FP::draw(), fl::RGB_Blobs::draw(), fl::RGB_Blobs_FP::draw(), fl::Rings::draw(), fl::Rings_FP::draw(), fl::Rotating_Blob::draw(), fl::Rotating_Blob_FP::draw(), fl::Scaledemo1::draw(), fl::Slow_Fade::draw(), fl::Slow_Fade_FP::draw(), fl::SpiralMatrix10::draw(), fl::SpiralMatrix10_FP::draw(), fl::SpiralMatrix1::draw(), fl::SpiralMatrix1_FP::draw(), fl::SpiralMatrix2::draw(), fl::SpiralMatrix2_FP::draw(), fl::SpiralMatrix3::draw(), fl::SpiralMatrix3_FP::draw(), fl::SpiralMatrix4::draw(), fl::SpiralMatrix5::draw(), fl::SpiralMatrix5_FP::draw(), fl::SpiralMatrix6::draw(), fl::SpiralMatrix6_FP::draw(), fl::SpiralMatrix8::draw(), fl::SpiralMatrix8_FP::draw(), fl::SpiralMatrix9::draw(), fl::SpiralMatrix9_FP::draw(), fl::Spiralus2::draw(), fl::Spiralus2_FP::draw(), fl::Spiralus::draw(), fl::Spiralus_FP::draw(), fl::Tile2x2_u8::draw(), fl::Water::draw(), fl::Water_FP::draw(), fl::Waves::draw(), fl::Waves_FP::draw(), fl::Yves::draw(), fl::Yves_FP::draw(), fl::Zoom2::draw(), fl::Zoom2_FP::draw(), fl::Zoom::draw(), fl::Zoom_FP::draw(), fl::third_party::vorbis::draw_line(), fl::FlowFieldFloat::drawDot(), fl::FlowFieldFP::drawDot(), fl::FlowFieldFloat::drawFlowVectors(), fl::FlowFieldFP::drawFlowVectors(), fl::FlowFieldFloat::drawImpl(), fl::FlowFieldFP::drawImpl(), fl::third_party::TJpg_Decoder::drawJpg(), fl::gfx::detail::drawLineCore(), easeInOutCubic16(), easeInOutQuad16(), fl::RedBlackTree< value_type, PairCompare, Allocator >::erase(), fl::detail::gamma_constexpr::eval(), fl::detail::gamma_constexpr::eval16(), exp(), fl::detail::gamma_constexpr::exp2_fp(), fl::fixed_point_base< Derived, IntBits, FracBits >::exp2_fp(), fl::s12x4::exp2_fp(), fl::s16x16::exp2_fp(), fl::s24x8::exp2_fp(), fl::s4x12::exp2_fp(), fl::s8x24::exp2_fp(), fl::s8x8::exp2_fp(), fl::u12x4::exp2_fp(), fl::u16x16::exp2_fp(), fl::u24x8::exp2_fp(), fl::u4x12::exp2_fp(), fl::u8x24::exp2_fp(), fl::u8x8::exp2_fp(), fl::detail::gamma_constexpr::exp2_pos(), fl::rect< T >::expand(), expfp(), fast_hash32(), fast_hash64(), fast_logf_approx(), fl::third_party::FASTABS(), fl::audio::fft::Context::fastDb(), fl::third_party::vorbis::float32_unpack(), fl::fixed_point< IntBits, FracBits, Sign::SIGNED >< IntBits, FracBits >::floor(), fl::fixed_point_base< Derived, IntBits, FracBits >::floor(), floor(), fl::s12x4::floor(), fl::s16x16::floor(), fl::s24x8::floor(), fl::s4x12::floor(), fl::s8x24::floor(), fl::s8x8::floor(), fl::u12x4::floor(), fl::u16x16::floor(), fl::u24x8::floor(), fl::u4x12::floor(), fl::u8x24::floor(), fl::u8x8::floor(), fl::FlowFieldFloat::flowAdvect(), fl::FlowFieldFP::flowAdvect(), fmod(), fmod< double >(), fmod_impl_double(), fmod_impl_float(), fmodf(), fl::FlowFieldFloat::fmodPos(), fl::fixed_point< IntBits, FracBits, Sign::SIGNED >< IntBits, FracBits >::fract(), fl::fixed_point_base< Derived, IntBits, FracBits >::fract(), fract(), fl::s12x4::fract(), fl::s16x16::fract(), fl::s24x8::fract(), fl::s4x12::fract(), fl::s8x24::fract(), fl::s8x8::fract(), fl::u12x4::fract(), fl::u16x16::fract(), fl::u24x8::fract(), fl::u4x12::fract(), fl::u8x24::fract(), fl::u8x8::fract(), fl::third_party::vorbis::get32(), fl::third_party::vorbis::get32_packet(), fl::third_party::vorbis::get8_packet(), fl::WaveSimulation1D::getf(), fl::WaveSimulation1D_Real::getf(), fl::WaveSimulation2D::getf(), fl::WaveSimulation2D_Real::getf(), fl::WaveSimulation1D::geti16(), fl::WaveSimulation1D_Real::geti16(), fl::WaveSimulation2D::geti16(), fl::WaveSimulation2D_Real::geti16(), fl::WaveSimulation1D::geti16All(), fl::WaveSimulation2D::geti16All(), fl::WaveSimulation1D::geti16Previous(), fl::WaveSimulation1D_Real::geti16Previous(), fl::WaveSimulation2D::geti16Previous(), fl::WaveSimulation2D_Real::geti16Previous(), fl::WaveSimulation1D::geti8(), fl::WaveSimulation1D_Real::geti8(), fl::WaveSimulation2D::geti8(), fl::WaveSimulation2D_Real::geti8(), fl::GlyphBitmap::getPixel(), fl::WaveFx::getu8(), fl::WaveSimulation1D::getu8(), fl::WaveSimulation1D_Real::getu8(), fl::WaveSimulation2D::getu8(), fl::WaveSimulation2D_Real::getu8(), fl::FlowFieldFloat::Perlin2D::grad(), grad(), fl::perlin_q16::grad(), fl::perlin_s16x16::grad(), fl::perlin_s8x8::grad(), fl::perlin_s16x16::grad3d(), fl::perlin_i16_optimized::grad_i16(), fl::Canvas< RGB_T >::has(), fl::gfx::Canvas< RGB_T >::has(), fl::gfx::CanvasMapped< RGB_T >::has(), fl::WaveSimulation1D::has(), fl::WaveSimulation1D_Real::has(), fl::WaveSimulation2D::has(), fl::WaveSimulation2D_Real::has(), fl::XYMap::has(), fl::XYMap::has(), fl::anonymous_namespace{noise_woryley.cpp.hpp}::hash(), HSV16toRGB(), hypot(), hypot(), hypot_impl_double(), hypot_impl_float(), hypotf(), fl::third_party::idct9(), fl::FlowFieldFloat::idx(), fl::FlowFieldFP::idx(), fl::third_party::imdct12(), fl::third_party::IntensityProcMPEG1(), fl::third_party::IntensityProcMPEG2(), fl::Tile2x2_u8_wrap::Interpolate(), fl::CatmullRomPath::interpolate(), isqrt32(), fl::gfx::detail::isqrt32_ceil(), isqrt64(), fl::third_party::jd_decomp(), fl::third_party::jd_decomp_progressive(), fl::third_party::TJpg_Decoder::jd_output(), fl::fixed_point_base< Derived, IntBits, FracBits >::log2_fp(), fl::s12x4::log2_fp(), fl::s16x16::log2_fp(), fl::s24x8::log2_fp(), fl::s4x12::log2_fp(), fl::s8x24::log2_fp(), fl::s8x8::log2_fp(), fl::u12x4::log2_fp(), fl::u16x16::log2_fp(), fl::u24x8::log2_fp(), fl::u4x12::log2_fp(), fl::u8x24::log2_fp(), fl::u8x8::log2_fp(), fl::third_party::MADD64(), fl::map_range_detail::map_range_math< T, vec2< V > >::map(), map16_to_32(), map16_to_8(), map32_to_16(), map32_to_8(), map8_to_16(), map8_to_32(), map_float(), fl::PerlinParticlePunch::mapf(), fl::XYMap::mapPixels(), fl::ScreenMap::mapToIndex(), fl::XMap::mapToIndex(), fl::XYMap::mapToIndex(), fl::XYMap::mapToIndex(), fl::WaveCrgbGradientMap::mapWaveToLEDs(), fl::WaveCrgbMapDefault::mapWaveToLEDs(), fl::RedBlackTree< value_type, PairCompare, Allocator >::maximum(), fl::Tile2x2_u8::MaxTile(), fl::third_party::vorbis::maybe_start_packet(), fl::third_party::mcu_output(), fl::third_party::MidSideProc(), fl::RedBlackTree< value_type, PairCompare, Allocator >::minimum(), fl::third_party::MULSHIFT32(), fl::Engine::multiply(), fl::third_party::vorbis::neighbors(), fl::XYPath::NewPointPath(), fl::FlowFieldFloat::Perlin2D::noise(), noiseCylinderCRGB(), noiseCylinderHSV16(), noiseRingCRGB(), noiseRingHSV16(), noiseSphereCRGB(), noiseSphereHSV16(), fl::third_party::nsgif__decode_complex(), fl::third_party::nsgif__parse_image_descriptor(), fl::third_party::nsgif__restore_bg(), fl::FastHash< vec2< T > >::operator()(), fl::GammaEval16< GammaRaw >::operator()(), fl::GammaEval< GammaRaw >::operator()(), fl::Grid< T >::operator()(), fl::Grid< T >::operator()(), fl::Leds::operator()(), fl::Leds::operator()(), fl::MapRedBlackTree< Key, Value, Compare, Allocator >::value_compare::operator()(), fl::MatrixSlice< T >::operator()(), fl::MultiMapTree< Key, Value, Compare, Allocator >::value_compare::operator()(), fl::Tile2x2_u8::operator()(), fl::XMap::operator()(), fl::XYMap::operator()(), fl::CLEDController::operator[](), fl::CRGB::operator[](), fl::CRGB::operator[](), fl::hsv8::operator[](), fl::hsv8::operator[](), fl::ScreenMap::operator[](), fl::ScreenMap::operator[](), fl::third_party::TJpgInstanceDecoder::outputCallback(), P(), fl::Luminova::plotDot(), pnoise(), fl::perlin_q16::pnoise2d_raw(), fl::perlin_s16x16::pnoise2d_raw(), fl::perlin_s8x8::pnoise2d_raw(), fl::perlin_s16x16::pnoise3d_raw(), fl::RedBlackTree< T, Compare, Allocator >::const_iterator::predecessor(), fl::RedBlackTree< T, Compare, Allocator >::const_reverse_iterator::predecessor(), fl::RedBlackTree< T, Compare, Allocator >::iterator::predecessor(), fl::RedBlackTree< T, Compare, Allocator >::reverse_iterator::predecessor(), fl::third_party::vorbis::predict_point(), fl::XYRasterU8Sparse::rasterize_internal(), fl::Corkscrew::readFromMulti(), fl::FontImpl::renderGlyph(), fl::RedBlackTree< value_type, PairCompare, Allocator >::rotateLeft(), fl::RedBlackTree< value_type, PairCompare, Allocator >::rotateRight(), fl::fixed_point< IntBits, FracBits, Sign::SIGNED >< IntBits, FracBits >::rsqrt(), fl::fixed_point_base< Derived, IntBits, FracBits >::rsqrt(), rsqrt(), fl::s12x4::rsqrt(), fl::s16x16::rsqrt(), fl::s24x8::rsqrt(), fl::s4x12::rsqrt(), fl::s8x24::rsqrt(), fl::s8x8::rsqrt(), fl::u12x4::rsqrt(), fl::u16x16::rsqrt(), fl::u24x8::rsqrt(), fl::u4x12::rsqrt(), fl::u8x24::rsqrt(), fl::u8x8::rsqrt(), sample(), sampleBilinear(), sampleNearest(), fl::third_party::SAR64(), fl::Tile2x2_u8::scale(), scale8_to_16_accurate(), fl::Engine::screen(), fl::PointPath::set(), fl::WaveSimulation1D_Real::set(), fl::WaveFx::setf(), fl::WaveSimulation1D::setf(), fl::WaveSimulation2D::setf(), fl::WaveSimulation2D_Real::setf(), fl::WaveSimulation2D::seti16(), fl::WaveSimulation2D_Real::seti16(), fl::Tile2x2_u8::setOrigin(), fl::Engine::setPixelColorInternal(), fl::anonymous_namespace{chasing_spirals.cpp.hpp}::setupChasingSpiralFrame(), fl::third_party::SHL64(), fl::fixed_point< IntBits, FracBits, Sign::SIGNED >< IntBits, FracBits >::sign(), fl::fixed_point_base< Derived, IntBits, FracBits >::sign(), fl::s12x4::sign(), fl::s16x16::sign(), fl::s24x8::sign(), fl::s4x12::sign(), fl::s8x24::sign(), fl::s8x8::sign(), sign(), fl::detail::sin_poly_quarterturn_(), fl::detail::sin_reduce_(), fl::third_party::vorbis::skip(), smap16_to_32(), smap16_to_8(), smap32_to_16(), smap32_to_8(), smap8_to_16(), smap8_to_32(), fl::fixed_point< IntBits, FracBits, Sign::SIGNED >< IntBits, FracBits >::smoothstep(), fl::fixed_point_base< Derived, IntBits, FracBits >::smoothstep(), fl::s12x4::smoothstep(), fl::s16x16::smoothstep(), fl::s24x8::smoothstep(), fl::s4x12::smoothstep(), fl::s8x24::smoothstep(), fl::s8x8::smoothstep(), smoothstep(), fl::u12x4::smoothstep(), fl::u16x16::smoothstep(), fl::u24x8::smoothstep(), fl::u4x12::smoothstep(), fl::u8x24::smoothstep(), fl::u8x8::smoothstep(), splat(), fl::fixed_point< IntBits, FracBits, Sign::SIGNED >< IntBits, FracBits >::sqrt(), fl::fixed_point_base< Derived, IntBits, FracBits >::sqrt(), fl::s12x4::sqrt(), fl::s16x16::sqrt(), fl::s24x8::sqrt(), fl::s4x12::sqrt(), fl::s8x24::sqrt(), fl::s8x8::sqrt(), sqrt(), fl::u12x4::sqrt(), fl::u16x16::sqrt(), fl::u24x8::sqrt(), fl::u4x12::sqrt(), fl::u8x24::sqrt(), fl::u8x8::sqrt(), fl::fixed_point_base< Derived, IntBits, FracBits >::sqrt_impl(), fl::fixed_point_base< Derived, IntBits, FracBits >::sqrt_impl(), fl::detail::sqrt_newton_(), fl::third_party::vorbis::square(), fl::third_party::vorbis::start_decoder(), fl::third_party::truetype::stbtt__add_point(), fl::third_party::truetype::stbtt__compute_crossings_x(), fl::third_party::truetype::stbtt__csctx_v(), fl::third_party::truetype::stbtt__cuberoot(), fl::third_party::truetype::stbtt__GetGlyphShapeTT(), fl::third_party::truetype::stbtt__track_vertex(), fl::third_party::truetype::stbtt_BakeFontBitmap_internal(), fl::third_party::truetype::stbtt_FlattenCurves(), fl::third_party::truetype::stbtt_GetGlyphSDF(), fl::third_party::truetype::stbtt_GetPackedQuad(), fl::third_party::truetype::stbtt_setvertex(), fl::fixed_point< IntBits, FracBits, Sign::SIGNED >< IntBits, FracBits >::step(), fl::fixed_point_base< Derived, IntBits, FracBits >::step(), fl::s12x4::step(), fl::s16x16::step(), fl::s24x8::step(), fl::s4x12::step(), fl::s8x24::step(), fl::s8x8::step(), step(), fl::u12x4::step(), fl::u16x16::step(), fl::u24x8::step(), fl::u4x12::step(), fl::u8x24::step(), fl::u8x8::step(), fl::Engine::subtract(), fl::RedBlackTree< T, Compare, Allocator >::const_iterator::successor(), fl::RedBlackTree< T, Compare, Allocator >::const_reverse_iterator::successor(), fl::RedBlackTree< T, Compare, Allocator >::iterator::successor(), fl::RedBlackTree< T, Compare, Allocator >::reverse_iterator::successor(), fl::ScreenMap::toJson(), transpose8(), transpose8x1(), transpose8x1_MSB(), fl::third_party::vorbis::uint32_compare(), fl::WaveSimulation2D::update(), upscaleArbitrary(), upscaleArbitraryFloat(), upscaleFloat(), upscalePowerOf2(), upscaleRectangular(), upscaleRectangularPowerOf2(), fl::gfx::blur_detail::vpass_full(), fl::gfx::blur_detail::vpass_rowmajor_impl(), fl::third_party::WinPrevious(), worley_noise_2d_q15(), x_linear(), x_reverse(), fl::NoisePalette::XY(), XY(), fl::anonymous_namespace{blur.cpp.hpp}::xy_legacy_wrapper(), xy_line_by_line(), xy_serpentine(), fl::Engine::xyMap(), fl::Fx1d::xyMap(), fl::Fx2d::xyMap(), xyMapCallbackAdapter(), fl::colorimetric_detail::xyY_to_XYZ(), and fl::third_party::yuv_to_rgb().