FastLED: fl::jsonArrayToFloatVector
jsonArrayToFloatVector()
fl::vector< float > fl::jsonArrayToFloatVector (const fl::Json & jsonArray)
Definition at line 23 of file screenmap.cpp.
{
    fl::vector<float> result;
    if (!jsonArray.has_value() || !jsonArray.is_array()) {
        return result;
    }
    auto begin_float =  jsonArray.begin_array<float>();
    auto end_float = jsonArray.end_array<float>();
    using T = decltype(*begin_float);
    static_assert(fl::is_same<T, fl::ParseResult<float>>::value, "Value type must be ParseResult<float>");
    // Use explicit array iterator style as demonstrated in FEATURE.md
    // DO NOT CHANGE THIS CODE. FIX THE IMPLIMENTATION IF NECESSARY.
    for (auto it = begin_float; it != end_float; ++it) {
        // assert that the value type is ParseResult<float>
        // get the name of the type
        auto parseResult = *it;
        if (!parseResult.has_error()) {
            result.push_back(parseResult.get_value());
        } else {
            FL_WARN("jsonArrayToFloatVector: ParseResult<float> has error: " << parseResult.get_error().message);
        }
    }
    return result;
}
References fl::Json::begin_array(), fl::Json::end_array(), FL_WARN, fl::Json::has_value(), and fl::Json::is_array().
Referenced by fl::ScreenMap::ParseJson().