FastLED: fl::readSerialStringUntil
readSerialStringUntil()
template<typename SerialIn> fl::optional< fl::string > fl::readSerialStringUntil (SerialIn & serial, char delimiter, char skipChar, fl::optional< u32 > timeoutMs)
Definition at line 197 of file serial.h.
{
    // Follows Arduino Serial.readStringUntil() API - blocks until delimiter found
    fl::sstream buffer;
    u32 startTime = fl::millis();
    // Read characters until we find delimiter or timeout
    while (true) {
        // Check timeout (only if timeout is set)
        if (timeoutMs.has_value()) {
            if (fl::millis() - startTime >= timeoutMs.value()) {
                // Timeout occurred - return nullopt
                return fl::nullopt;
            }
        }
        // Try to read next character
        int c = serial.read();
        // Handle -1 (no data available) like Arduino's timedRead():
        // Keep trying until timeout (or forever if no timeout set)
        if (c == -1) {
            // Brief 1us yield instead of 1ms delay for fast USB CDC polling.
            fl::delayMicroseconds(1);
            continue;
        }
        // Found delimiter - complete
        if (c == delimiter) {
            break;
        }
        // Skip specified character (e.g., '\r' for cross-platform line endings)
        if (c == skipChar) {
            continue;
        }
        // Valid character - add to buffer
        buffer << static_cast<char>(c);
    }
    // Convert to string and trim whitespace
    fl::string result = buffer.str();
    result.trim();
    return result;
}
References delayMicroseconds(), fl::Optional< T >::has_value(), millis(), nullopt, fl::sstream::str(), and fl::Optional< T >::value().
Referenced by readSerialLine().