FastLED: fl::y
y
fl::y = *(u32*)(A)
Definition at line 23 of file transposition.cpp.hpp.
Referenced by fl::Leds::Leds(), fl::PointPath::PointPath(), fl::anonymous_namespace{channel.cpp.hpp}::ReorderingPixelIteratorAny::ReorderingPixelIteratorAny(), fl::WaveSimulation2D_Real::~WaveSimulation2D_Real(), fl::Grid< T >::access(), fl::Grid< T >::access(), fl::Engine::add(), fl::WaveFx::addf(), fl::ScreenMap::addOffsetY(), fl::gfx::addPixelToBuffer(), fl::CatmullRomParams::addPoint(), fl::CatmullRomPath::addPoint(), fl::Canvas< RGB_T >::at(), fl::Canvas< RGB_T >::at(), fl::gfx::Canvas< RGB_T >::at(), fl::gfx::Canvas< RGB_T >::at(), fl::gfx::CanvasMapped< RGB_T >::at(), fl::gfx::CanvasMapped< RGB_T >::at(), fl::Grid< T >::at(), fl::Grid< T >::at(), fl::Leds::at(), fl::Leds::at(), fl::MatrixSlice< T >::at(), fl::MatrixSlice< T >::at(), fl::Tile2x2_u8::at(), fl::Tile2x2_u8::at(), fl::Tile2x2_u8_wrap::at(), fl::Tile2x2_u8_wrap::at(), fl::XYRasterSparse_RGB8::at(), fl::XYRasterU8Sparse::at(), atan2(), atan2(), fl::fixed_point< IntBits, FracBits, Sign::SIGNED >< IntBits, FracBits >::atan2(), fl::fixed_point_base< Derived, IntBits, FracBits >::atan2(), fl::s12x4::atan2(), fl::s16x16::atan2(), fl::s24x8::atan2(), fl::s4x12::atan2(), fl::s8x24::atan2(), fl::s8x8::atan2(), fl::detail::atan2_full_(), atan2_impl_double(), atan2_impl_float(), atan2f(), fl::gfx::blurGaussianImpl(), fl::gfx::blurGaussianMappedImpl(), fl::Corkscrew::calculateTileAtWrap(), fl::ScreenMap::Circle(), fl::PerlinParticlePunch::circleNoiseGen(), fl::Engine::colorburn(), fl::Engine::colordodge(), fl::ArchimedeanSpiralPath::compute(), fl::CatmullRomPath::compute(), fl::CirclePath::compute(), fl::GielisCurvePath::compute(), fl::HeartPath::compute(), fl::LinePath::compute(), fl::PhyllotaxisPath::compute(), fl::RosePath::compute(), fl::third_party::vorbis::compute_codewords(), fl::rect< T >::contains(), fl::Frame::convertPixelsToRgb(), fl::XYMap::convertToLookUpTable(), fl::third_party::DecodeHuffmanPairs(), fl::third_party::DecodeHuffmanQuads(), fl::third_party::DequantBlock(), fl::anonymous_namespace{rgbw.cpp.hpp}::divide_by_3(), fl::Big_Caleido::draw(), fl::Big_Caleido_FP::draw(), fl::Caleido1::draw(), fl::Caleido1_FP::draw(), fl::Caleido2::draw(), fl::Caleido2_FP::draw(), fl::Caleido3::draw(), fl::Caleido3_FP::draw(), fl::Center_Field::draw(), fl::Chasing_Spirals_Float::draw(), fl::Complex_Kaleido::draw(), fl::Complex_Kaleido_2::draw(), fl::Complex_Kaleido_2_FP::draw(), fl::Complex_Kaleido_3::draw(), fl::Complex_Kaleido_3_FP::draw(), fl::Complex_Kaleido_4::draw(), fl::Complex_Kaleido_4_FP::draw(), fl::Complex_Kaleido_5::draw(), fl::Complex_Kaleido_6::draw(), fl::Complex_Kaleido_6_FP::draw(), fl::Complex_Kaleido_FP::draw(), fl::Corkscrew::draw(), fl::Distance_Experiment::draw(), fl::Distance_Experiment_FP::draw(), fl::Fire2012::draw(), fl::Fluffy_Blobs::draw(), fl::Fluffy_Blobs_FP::draw(), fl::Hot_Blob::draw(), fl::Hot_Blob_FP::draw(), fl::Lava1::draw(), fl::Lava1_FP::draw(), fl::Module_Experiment10::draw(), fl::Module_Experiment1::draw(), fl::Module_Experiment1_FP::draw(), fl::Module_Experiment2::draw(), fl::Module_Experiment3::draw(), fl::Module_Experiment4::draw(), fl::Module_Experiment4_FP::draw(), fl::Module_Experiment5::draw(), fl::Module_Experiment5_FP::draw(), fl::Module_Experiment6::draw(), fl::Module_Experiment6_FP::draw(), fl::Module_Experiment7::draw(), fl::Module_Experiment7_FP::draw(), fl::Module_Experiment8::draw(), fl::Module_Experiment8_FP::draw(), fl::Module_Experiment9::draw(), fl::Module_Experiment9_FP::draw(), fl::Parametric_Water::draw(), fl::Parametric_Water_FP::draw(), fl::Polar_Waves::draw(), fl::Polar_Waves_FP::draw(), fl::RedSquare::draw(), fl::RGB_Blobs2::draw(), fl::RGB_Blobs2_FP::draw(), fl::RGB_Blobs3::draw(), fl::RGB_Blobs3_FP::draw(), fl::RGB_Blobs4::draw(), fl::RGB_Blobs4_FP::draw(), fl::RGB_Blobs5::draw(), fl::RGB_Blobs5_FP::draw(), fl::RGB_Blobs::draw(), fl::RGB_Blobs_FP::draw(), fl::Rings::draw(), fl::Rings_FP::draw(), fl::Rotating_Blob::draw(), fl::Rotating_Blob_FP::draw(), fl::Scaledemo1::draw(), fl::Slow_Fade::draw(), fl::Slow_Fade_FP::draw(), fl::SpiralMatrix10::draw(), fl::SpiralMatrix10_FP::draw(), fl::SpiralMatrix1::draw(), fl::SpiralMatrix1_FP::draw(), fl::SpiralMatrix2::draw(), fl::SpiralMatrix2_FP::draw(), fl::SpiralMatrix3::draw(), fl::SpiralMatrix3_FP::draw(), fl::SpiralMatrix4::draw(), fl::SpiralMatrix5::draw(), fl::SpiralMatrix5_FP::draw(), fl::SpiralMatrix6::draw(), fl::SpiralMatrix6_FP::draw(), fl::SpiralMatrix8::draw(), fl::SpiralMatrix8_FP::draw(), fl::SpiralMatrix9::draw(), fl::SpiralMatrix9_FP::draw(), fl::Spiralus2::draw(), fl::Spiralus2_FP::draw(), fl::Spiralus::draw(), fl::Spiralus_FP::draw(), fl::Tile2x2_u8::draw(), fl::Water::draw(), fl::Water_FP::draw(), fl::Waves::draw(), fl::Waves_FP::draw(), fl::Yves::draw(), fl::Yves_FP::draw(), fl::Zoom2::draw(), fl::Zoom2_FP::draw(), fl::Zoom::draw(), fl::Zoom_FP::draw(), fl::third_party::vorbis::draw_line(), fl::FlowFieldFloat::drawDot(), fl::FlowFieldFP::drawDot(), fl::FlowFieldFloat::drawFlowVectors(), fl::FlowFieldFP::drawFlowVectors(), fl::FlowFieldFloat::drawImpl(), fl::FlowFieldFP::drawImpl(), fl::third_party::TJpg_Decoder::drawJpg(), fl::gfx::detail::drawLineCore(), fl::RedBlackTree< value_type, PairCompare, Allocator >::erase(), fl::rect< T >::expand(), fl::FlowFieldFloat::flowAdvect(), fl::FlowFieldFP::flowAdvect(), fmod(), fmod< double >(), fmod_impl_double(), fmod_impl_float(), fmodf(), fl::third_party::FreqInvertRescale(), fl::WaveSimulation2D::getf(), fl::WaveSimulation2D_Real::getf(), fl::WaveSimulation2D::geti16(), fl::WaveSimulation2D_Real::geti16(), fl::WaveSimulation2D::geti16All(), fl::WaveSimulation2D::geti16Previous(), fl::WaveSimulation2D_Real::geti16Previous(), fl::WaveSimulation2D::geti8(), fl::WaveSimulation2D_Real::geti8(), fl::GlyphBitmap::getPixel(), fl::WaveFx::getu8(), fl::WaveSimulation2D::getu8(), fl::WaveSimulation2D_Real::getu8(), fl::FlowFieldFloat::Perlin2D::grad(), grad(), fl::perlin_q16::grad(), fl::perlin_s16x16::grad(), fl::perlin_s8x8::grad(), fl::perlin_s16x16::grad3d(), fl::perlin_i16_optimized::grad_i16(), fl::Canvas< RGB_T >::has(), fl::gfx::Canvas< RGB_T >::has(), fl::gfx::CanvasMapped< RGB_T >::has(), fl::WaveSimulation2D::has(), fl::WaveSimulation2D_Real::has(), fl::XYMap::has(), fl::XYMap::has(), fl::anonymous_namespace{noise_woryley.cpp.hpp}::hash(), fl::third_party::HybridTransform(), hypot(), hypot(), hypot_impl_double(), hypot_impl_float(), hypotf(), fl::FlowFieldFloat::idx(), fl::FlowFieldFP::idx(), fl::third_party::IMDCT12x3(), fl::third_party::IMDCT36(), fl::RedBlackTree< value_type, PairCompare, Allocator >::insertFixup(), fl::Tile2x2_u8_wrap::Interpolate(), fl::CatmullRomPath::interpolate(), fl::third_party::jd_decomp(), fl::third_party::jd_decomp_progressive(), fl::third_party::TJpg_Decoder::jd_output(), fl::third_party::MADD64(), fl::map_range_detail::map_range_math< T, vec2< V > >::map(), fl::XYMap::mapPixels(), fl::XYMap::mapToIndex(), fl::XYMap::mapToIndex(), fl::WaveCrgbGradientMap::mapWaveToLEDs(), fl::WaveCrgbMapDefault::mapWaveToLEDs(), fl::Tile2x2_u8::MaxTile(), fl::third_party::mcu_output(), fl::third_party::MULSHIFT32(), fl::Engine::multiply(), fl::XYPath::NewPointPath(), fl::FlowFieldFloat::Perlin2D::noise(), noiseCylinderCRGB(), noiseCylinderHSV16(), noiseRingCRGB(), noiseRingHSV16(), noiseSphereCRGB(), noiseSphereHSV16(), fl::third_party::nsgif__decode_complex(), fl::third_party::nsgif__deinterlace(), fl::third_party::nsgif__next_row(), fl::third_party::nsgif__parse_image_descriptor(), fl::third_party::nsgif__restore_bg(), fl::Grid< T >::operator()(), fl::Grid< T >::operator()(), fl::Leds::operator()(), fl::Leds::operator()(), fl::MapRedBlackTree< Key, Value, Compare, Allocator >::value_compare::operator()(), fl::MatrixSlice< T >::operator()(), fl::MultiMapTree< Key, Value, Compare, Allocator >::value_compare::operator()(), fl::Tile2x2_u8::operator()(), fl::XYMap::operator()(), fl::Leds::operator[](), fl::Leds::operator[](), fl::third_party::TJpgInstanceDecoder::outputCallback(), fl::Luminova::plotDot(), pnoise(), fl::perlin_q16::pnoise2d_raw(), fl::perlin_s16x16::pnoise2d_raw(), fl::perlin_s8x8::pnoise2d_raw(), fl::perlin_s16x16::pnoise3d_raw(), fl::RedBlackTree< T, Compare, Allocator >::const_iterator::predecessor(), fl::RedBlackTree< T, Compare, Allocator >::const_reverse_iterator::predecessor(), fl::RedBlackTree< T, Compare, Allocator >::iterator::predecessor(), fl::RedBlackTree< T, Compare, Allocator >::reverse_iterator::predecessor(), fl::XYRasterU8Sparse::rasterize_internal(), fl::Corkscrew::readFromMulti(), fl::FontImpl::renderGlyph(), fl::RedBlackTree< value_type, PairCompare, Allocator >::rotateLeft(), fl::RedBlackTree< value_type, PairCompare, Allocator >::rotateRight(), sample(), sampleBilinear(), sampleNearest(), fl::Tile2x2_u8::scale(), fl::Engine::screen(), fl::PointPath::set(), fl::WaveFx::setf(), fl::WaveSimulation2D::setf(), fl::WaveSimulation2D_Real::setf(), fl::WaveSimulation2D::seti16(), fl::WaveSimulation2D_Real::seti16(), fl::Tile2x2_u8::setOrigin(), fl::Engine::setPixelColorInternal(), fl::anonymous_namespace{chasing_spirals.cpp.hpp}::setupChasingSpiralFrame(), splat(), fl::third_party::vorbis::start_decoder(), fl::third_party::truetype::stbtt__add_point(), fl::third_party::truetype::stbtt__compute_crossings_x(), fl::third_party::truetype::stbtt__csctx_v(), fl::third_party::truetype::stbtt__GetGlyphShapeTT(), fl::third_party::truetype::stbtt__rasterize(), fl::third_party::truetype::stbtt__track_vertex(), fl::third_party::truetype::stbtt_BakeFontBitmap_internal(), fl::third_party::truetype::stbtt_FlattenCurves(), fl::third_party::truetype::stbtt_GetGlyphSDF(), fl::third_party::truetype::stbtt_GetPackedQuad(), fl::third_party::truetype::stbtt_setvertex(), fl::Engine::subtract(), fl::RedBlackTree< T, Compare, Allocator >::const_iterator::successor(), fl::RedBlackTree< T, Compare, Allocator >::const_reverse_iterator::successor(), fl::RedBlackTree< T, Compare, Allocator >::iterator::successor(), fl::RedBlackTree< T, Compare, Allocator >::reverse_iterator::successor(), fl::ScreenMap::toJson(), transpose8(), transpose8x1(), transpose8x1_MSB(), fl::third_party::vorbis::uint32_compare(), fl::WaveSimulation2D::update(), upscaleArbitrary(), upscaleArbitraryFloat(), upscaleFloat(), upscalePowerOf2(), upscaleRectangular(), upscaleRectangularPowerOf2(), fl::gfx::blur_detail::vpass_rowmajor_impl(), worley_noise_2d_q15(), fl::NoisePalette::XY(), XY(), fl::anonymous_namespace{blur.cpp.hpp}::xy_legacy_wrapper(), xy_line_by_line(), xy_serpentine(), fl::Engine::xyMap(), fl::Fx2d::xyMap(), xyMapCallbackAdapter(), fl::colorimetric_detail::xyY_to_XYZ(), and fl::third_party::yuv_to_rgb().