FastLED: fl::read
read()
int fl::read ()
Definition at line 148 of file io.cpp.
           {
#ifdef FASTLED_TESTING
    // Check for injected handler first
    if (get_read_handler()) {
        return get_read_handler()();
    }
#endif
#ifdef __EMSCRIPTEN__
    return read_wasm();
#elif defined(FASTLED_TESTING) || defined(__linux__) || defined(__APPLE__) || defined(_WIN32)
    return read_native();
#elif defined(ESP32) || defined(ESP8266)
    return read_esp();
#elif defined(__AVR__) && !defined(ARDUINO_ARCH_MEGAAVR)
    return read_avr();
#elif defined(__MKL26Z64__)
    // Teensy LC uses special no-op functions to avoid _write linker issues
    return read_teensy_lc();
#elif defined(__IMXRT1062__) || defined(__MK66FX1M0__) || defined(__MK64FX512__) || defined(__MK20DX256__) || defined(__MK20DX128__)
    // All other Teensy platforms use lightweight implementation
    return read_teensy();
#else
    // Use generic Arduino input for all other platforms including:
    // - STM32 (STM32F1, STM32F4, STM32H7, ARDUINO_GIGA)
    // - NRF (NRF52, NRF52832, NRF52840, ARDUINO_NRF52_DK)
    // - All other Arduino-compatible platforms
    return read_arduino();
#endif
}
Referenced by fl::istream_real::get(), fl::istream_real::getline(), fl::ByteStream::readCRGB(), fl::FileHandle::readCRGB(), fl::PixelStream::readFrameAt(), and fl::istream_real::readLine().