FastLED: fl::runSingleValidationTest
runSingleValidationTest()
SingleTestResult fl::runSingleValidationTest (const SingleTestConfig & config)
Run a single stateless validation test.
Parameters
config Test configuration
Returns
Test result with pass/fail information
Definition at line 13 of file validation.cpp.hpp.
{
    SingleTestResult result;
    result.driver = config.driver_name;
    result.lane_count = static_cast<int>(config.lane_sizes.size());
    result.lane_sizes = config.lane_sizes;
    result.pattern = config.pattern;
    // ========================================================================
    // Input Validation
    // ========================================================================
    // Validate driver name
    if (config.driver_name.empty()) {
        result.success = false;
        result.error_message = "Driver name cannot be empty";
        return result;
    }
    // Validate lane count (1-16 lanes)
    if (config.lane_sizes.empty()) {
        result.success = false;
        result.error_message = "Lane count must be at least 1";
        return result;
    }
    if (config.lane_sizes.size() > 16) {
        result.success = false;
        result.error_message = "Lane count cannot exceed 16";
        return result;
    }
    // Validate individual lane sizes (must be > 0)
    for (size_t i = 0; i < config.lane_sizes.size(); i++) {
        if (config.lane_sizes[i] <= 0) {
            result.success = false;
            fl::sstream ss;
            ss << "Lane size at index " << i << " must be positive (got " << config.lane_sizes[i] << ")";
            result.error_message = ss.str();
            return result;
        }
    }
    // Validate iterations (must be > 0)
    if (config.iterations <= 0) {
        result.success = false;
        result.error_message = "Iterations must be positive";
        return result;
    }
    // Validate pattern name (must not be empty)
    if (config.pattern.empty()) {
        result.success = false;
        result.error_message = "Pattern name cannot be empty";
        return result;
    }
    // ========================================================================
    // Test Execution (Placeholder)
    // ========================================================================
    // NOTE: Actual hardware validation logic (LED array creation, channel
    // configuration, loopback testing) is implemented in the validation
    // example sketch. This library function focuses on configuration
    // validation and test orchestration.
    result.success = true;
    result.passed = true;
    result.total_tests = 4 * config.iterations;  // 4 patterns per iteration
    result.passed_tests = result.total_tests;
    result.duration_ms = 100;  // Placeholder duration
    return result;
}
References fl::SingleTestConfig::driver_name, fl::basic_string::empty(), fl::vector_basic::empty(), fl::SingleTestConfig::iterations, fl::SingleTestConfig::lane_sizes, fl::SingleTestConfig::pattern, fl::vector_basic::size(), and fl::sstream::str().