FastLED: fl::itoa64
itoa64()
int fl::itoa64 (i64 value, char * buffer, int radix)
Convert signed 64-bit integer to string buffer in given radix.
Parameters
value The signed 64-bit integer value to convert
buffer Output buffer (must be at least 66 bytes for base 2 with sign, 21 for base 10)
radix Number base (2-36, typically 10 for decimal, 16 for hex, 8 for octal)
Returns
Number of characters written (excluding null terminator)
Definition at line 103 of file charconv.cpp.hpp.
{
    char tmp[32]; // Buffer for 64-bit integer (max 65 chars for base 2 + sign)
    char *tp = tmp;
    int i;
    u64 v;
    int sign = (radix == 10 && value < 0);
    if (sign)
        v = -static_cast<u64>(value);
    else
        v = static_cast<u64>(value);
    while (v || tp == tmp) {
        i = v % radix;
        v = radix ? v / radix : 0;
        if (i < 10)
            *tp++ = i + '0';
        else
            *tp++ = i + 'a' - 10;
    }
    int len = tp - tmp;
    if (sign) {
        *sp++ = '-';
        len++;
    }
    while (tp > tmp)
        *sp++ = *--tp;
    *sp = '\0';  // Null-terminate the string
    return len;
}
References sign(), and type_rank< T >::value.
Referenced by fl::basic_string::appendHex(), fl::basic_string::appendOct(), fl::SerialPort::print(), and fl::SerialPort::println().