FastLED: fl::transpose_8strips
transpose_8strips()
FASTLED_FORCE_INLINE void fl::transpose_8strips (const u8 *const input[8], u8 * output, u16 num_leds, u8 bytes_per_led)
Transpose 8 LED strips into parallel bit format.
This function transposes 8 LED strips from standard byte-sequential format to bit-parallel format suitable for 8-way PIO output. It uses the highly optimized transpose8x1_MSB() function (Hacker's Delight algorithm).
Input: 8 strips, each with num_leds * bytes_per_led bytes Output: num_leds * bytes_per_led * 8 bytes
Parameters
input Array of 8 pointers to LED strip data
output Pointer to output buffer
num_leds Number of LEDs per strip (all strips padded to this length)
bytes_per_led Number of bytes per LED (3 for RGB, 4 for RGBW, etc.)
Note
All strips must be pre-padded to the same length
Output buffer must be pre-allocated by caller
Examples
/home/runner/work/FastLED/FastLED/src/fl/math/transposition.h.
Definition at line 680 of file transposition.h.
              {
    // Process each LED
    for (u16 led = 0; led < num_leds; led++) {
        u8 temp_input[8];
        // Process each byte in the LED
        for (u8 byte_idx = 0; byte_idx < bytes_per_led; byte_idx++) {
            // Collect one byte from each strip for this byte position
            for (int strip = 0; strip < 8; strip++) {
                temp_input[strip] = input[strip][led * bytes_per_led + byte_idx];
            }
            // Transpose 8 bytes → 8 bytes (1 bit from each strip per output byte)
            transpose8x1_MSB(temp_input, output);
            // Advance output pointer by 8 bytes
            output += 8;
        }
    }
}
References FASTLED_FORCE_INLINE, FL_NOEXCEPT, transpose8x1_MSB(), and transpose_8strips().
Referenced by transpose_8strips(), and transpose_strips().