FastLED: fl::async_log_service
async_log_service()
void fl::async_log_service ()
Definition at line 203 of file async_logger.cpp.hpp.
{
    // Get background flush state
    detail::BackgroundFlushState& state = Singleton<detail::BackgroundFlushState>::instance();
    // Quick check - return immediately if no flush needed
    if (!state.mNeedsFlush) {
        return;
    }
    // Clear flag
    state.mNeedsFlush = false;
    // Flush all instantiated async loggers (uses ActiveLoggerRegistry)
    // Only flushes loggers that have been accessed via template functions
    fl::size n = state.mMessagesPerTick;
    detail::ActiveLoggerRegistry::instance().forEach([n](AsyncLogger& logger) {
        logger.flushN(n);
    });
}
References fl::AsyncLogger::flushN(), fl::detail::ActiveLoggerRegistry::forEach(), fl::detail::ActiveLoggerRegistry::instance(), fl::Singleton< T, N >::instance(), and state.