FastLED: fl::to_hex
to_hex()
template<typename T> fl::string fl::to_hex (T value, bool uppercase = false, bool pad_to_width = false)
Convert an integer value to hexadecimal string representation.
Template Parameters
T Integral type
Parameters
value The integer value to convert
uppercase If true, use uppercase hex digits (A-F), otherwise lowercase (a-f)
pad_to_width If true, pad with leading zeros to full type width (default: false for minimal representation)
Returns
Hexadecimal string representation of the value
Example usage:
fl::string hex = fl::to_hex(255, false);              // "ff" (minimal)
fl::string hex_upper = fl::to_hex(255, true);         // "FF" (minimal uppercase)
fl::string hex_padded = fl::to_hex(255, false, true); // "000000ff" (padded to int width)
fl::string hex_neg = fl::to_hex(-16, false);          // "-10"
Definition at line 517 of file string.h.
{
    constexpr auto width = detail::get_hex_int_width<sizeof(T)>();
    bool is_negative = false;
    u64 unsigned_value;
    if (static_cast<i64>(value) < 0 && sizeof(T) <= 8) {
        is_negative = true;
        unsigned_value = static_cast<u64>(-static_cast<i64>(value));
    } else {
        unsigned_value = static_cast<u64>(value);
    }
    return detail::hex(unsigned_value, width, is_negative, uppercase, pad_to_width);
}
References FL_NOEXCEPT, fl::detail::get_hex_int_width(), fl::detail::hex(), type_rank< T >::value, and width.
Referenced by fl::printf_detail::format_arg(), and fl::printf_detail::format_arg().