FastLED: fl::delayMicroseconds
delayMicroseconds()
void fl::delayMicroseconds (u32 us)
Delay for a given number of microseconds.
Parameters
us Microseconds to delay
Definition at line 206 of file delay.cpp.hpp.
{
  // Direct pass-through to platform layer (no async pumping for microsecond precision)
  fl::platforms::delayMicroseconds(us);
}
References FL_NOEXCEPT.
Referenced by delayUs(), fl::third_party::ezWS2812::end_transfer(), fl::third_party::ezWS2812gpio::end_transfer(), executeToggles(), readSerialStringUntil(), readStringUntil(), and fl::validation::testRxChannel().