FastLED: fl::printf
printf()
template<typename... Args> void fl::printf (const char * format, const Args &... args)
Printf-like formatting function that prints directly to the platform output.
Parameters
format Format string with placeholders like "%d", "%s", "%f" etc.
args Arguments to format
Supported format specifiers:
d, i: integers (all integral types)
u: unsigned integers
o: octal integers
f: floating point numbers
s: strings (const char*, fl::string)
c: characters
x: hexadecimal (lowercase)
X: hexadecimal (uppercase)
p: pointers (formatted as 0x... hex)
%%: literal % character
Example usage:
fl::printf("Value: %d, Name: %s", 42, "test");
fl::printf("Float: %.2f", 3.14159);
int* ptr = &value;
fl::printf("Pointer: %p", ptr);
Parameters
format Format string with placeholders like "%d", "%s", "%f" etc.
args Arguments to format
Supported format specifiers:
d, i: integers (all integral types)
u: unsigned integers
o: octal integers
f: floating point numbers
s: strings (const char*, fl::string)
c: characters
x: hexadecimal (lowercase)
X: hexadecimal (uppercase)
p: pointers (formatted as 0x... hex)
%%: literal % character
Example usage:
fl::printf("Value: %d, Name: %s", 42, "test");
fl::printf("Float: %.2f", 3.14159);
Examples
Chromancer.ino.
Definition at line 635 of file stdio.h.
{
    sstream stream;
    printf_detail::format_impl(stream, format, args...);
    fl::print(stream.str().c_str());
}
References args, fl::basic_string::c_str(), FL_NOEXCEPT, format(), fl::printf_detail::format_impl(), print(), and fl::sstream::str().
Referenced by fl::test::DefaultReporter::assertResult(), fl::test::TestContext::checkTimeout(), fl::test::fail(), handleClientResponse(), handleResponse(), fl::test::TestContext::listTests(), fl::third_party::MP3Decode(), fl::test::outputCapture(), fl::test::outputMessage(), fl::test::SerialReporter::print(), sendAsyncRequest(), sendAsyncStreamRequest(), sendSyncRequest(), setup(), fl::test::skipTest(), fl::test::DefaultReporter::subcaseStart(), fl::test::DefaultReporter::testCaseEnd(), fl::test::DefaultReporter::testCaseStart(), fl::test::DefaultReporter::testRunEnd(), and fl::test::DefaultReporter::testRunStart().