FastLED: fl::snprintf
snprintf()
template<typename... Args> int fl::snprintf (char * buffer, fl::size size, const char * format, const Args &... args)
Snprintf-like formatting function that writes to a buffer.
Parameters
buffer Output buffer to write formatted string to
size Maximum number of characters to write (including null terminator)
format Format string with placeholders like "%d", "%s", "%f" etc.
args Arguments to format
Returns
Number of characters that would have been written if buffer was large enough
Supported format specifiers:
d, i: integers (all integral types)
u: unsigned integers
o: octal integers
f: floating point numbers
s: strings (const char*, fl::string)
c: characters
x: hexadecimal (lowercase)
X: hexadecimal (uppercase)
p: pointers (formatted as 0x... hex)
%%: literal % character
Example usage:
char buffer[100];
int len = fl::snprintf(buffer, sizeof(buffer), "Value: %d, Name: %s", 42, "test");
Definition at line 666 of file stdio.h.
{
    // Handle null buffer or zero size
    if (!buffer || size == 0) {
        return 0;
    }
    // Format to internal string stream
    sstream stream;
    printf_detail::format_impl(stream, format, args...);
    fl::string result = stream.str();
    // Get the formatted string length
    fl::size formatted_len = result.size();
    // Copy to buffer, ensuring null termination
    fl::size copy_len = (formatted_len < size - 1) ? formatted_len : size - 1;
    // Copy characters
    for (fl::size i = 0; i < copy_len; ++i) {
        buffer[i] = result[i];
    }
    // Null terminate
    buffer[copy_len] = '\0';
    // Return the number of characters actually written (excluding null terminator)
    // This respects the buffer size limit instead of returning the full formatted length
    return static_cast<int>(copy_len);
}
References args, FL_NOEXCEPT, format(), fl::printf_detail::format_impl(), and fl::sstream::str().
Referenced by fl::net::http::ChunkedWriter::chunkOverhead(), fl::audio::detector::Key::getKeyName(), getPort(), fl::net::http::HttpStreamTransport::idToString(), fl::third_party::TJpgInstanceDecoder::initializeDecoder(), fl::SerialPort::printf(), fl::third_party::TJpgInstanceDecoder::processChunk(), sprintf(), and fl::net::http::ChunkedWriter::writeChunk().