FastLED: fl::configureAsyncLogService
configureAsyncLogService()
void fl::configureAsyncLogService (u32 interval_ms = 16, fl::size messages_per_tick = 5)
Configure async logger automatic servicing task.
Parameters
interval_ms Service interval in milliseconds (default 16ms = 60fps)
messages_per_tick Messages to flush per service call (default 5)
Note
Can be called at any time to dynamically adjust servicing rate
If not called, defaults are used (16ms interval, 5 messages/tick)
Example:
void setup() {
    // Configure before accessing any loggers
    fl::configureAsyncLogService(50, 10);  // 50ms interval, 10 msgs/tick
    FL_LOG_PARLIO_ASYNC_MAIN("Setup complete");
}
void loop() {
    fl::delay(10);  // Loggers serviced automatically!
}
Definition at line 276 of file async_logger.cpp.hpp.
{
    detail::AsyncLoggerServiceTask::instance().setInterval(interval_ms);
    detail::AsyncLoggerServiceTask::instance().setMessagesPerTick(messages_per_tick);
}
References fl::detail::AsyncLoggerServiceTask::instance(), fl::detail::AsyncLoggerServiceTask::setInterval(), and fl::detail::AsyncLoggerServiceTask::setMessagesPerTick().