FastLED: fl::map_range
map_range()
template<typename T, typename U> FASTLED_FORCE_INLINE U fl::map_range (T value, T in_min, T in_max, U out_min, U out_max)
Definition at line 174 of file math.h.
{
    if (map_range_detail::equals(value, in_min)) {
        return out_min;
    }
    if (map_range_detail::equals(value, in_max)) {
        return out_max;
    }
    return map_range_detail::map_range_math<T, U>::map(value, in_min, in_max, out_min, out_max);
}
References FASTLED_FORCE_INLINE, FL_NOEXCEPT, and type_rank< T >::value.
Referenced by fl::Corkscrew::at_splat_extrapolate(), drawRadialSpectrum(), drawSpectrumBars(), drawVUMeter(), drawWaveform(), fl::video::FrameTracker::get_interval_frames(), loop(), anonymous_namespace{xypaths.cpp}::make_path(), map_range_clamped(), fl::XYPathRenderer::rasterize(), and fl::iterator<, u8 >::setLoadFactor().