FastLED: fl::__builtin_five_bit_hd_gamma_bitshift
__builtin_five_bit_hd_gamma_bitshift()
void fl::__builtin_five_bit_hd_gamma_bitshift (CRGB colors, CRGB colors_scale, uint8_t global_brightness, CRGB * out_colors, uint8_t * out_power_5bit)
Definition at line 128 of file five_bit_hd_gamma.cpp.
{
    if (global_brightness == 0) {
        *out_colors = CRGB(0, 0, 0);
        *out_power_5bit = 0;
        return;
    }
    // Step 1: Gamma Correction
    uint16_t r16, g16, b16;
    five_bit_hd_gamma_function(colors, &r16, &g16, &b16);
    // Step 2: Color correction step comes after gamma correction. These values
    // are assumed to be be relatively close to 255.
    if (colors_scale.r != 0xff) {
        r16 = scale16by8(r16, colors_scale.r);
    }
    if (colors_scale.g != 0xff) {
        g16 = scale16by8(g16, colors_scale.g);
    }
    if (colors_scale.b != 0xff) {
        b16 = scale16by8(b16, colors_scale.b);
    }
    five_bit_bitshift(r16, g16, b16, global_brightness, out_colors,
                      out_power_5bit);
}
References five_bit_bitshift(), five_bit_hd_gamma_function(), and scale16by8().
Referenced by five_bit_hd_gamma_bitshift().