FastLED: fl::pnoise
pnoise()
FASTLED_FORCE_INLINE float fl::pnoise (float x, float y, float z)
Definition at line 65 of file perlin_float.h.
{
    int X = (int)fl::floorf(x) & 255, /* FIND UNIT CUBE THAT */
        Y = (int)fl::floorf(y) & 255, /* CONTAINS POINT.     */
        Z = (int)fl::floorf(z) & 255;
    x -= fl::floorf(x); /* FIND RELATIVE X,Y,Z */
    y -= fl::floorf(y); /* OF POINT IN CUBE.   */
    z -= fl::floorf(z);
    float u = fade(x), /* COMPUTE FADE CURVES */
        v = fade(y),   /* FOR EACH OF X,Y,Z.  */
        w = fade(z);
    int A = P(X) + Y, AA = P(A) + Z,
        AB = P(A + 1) + Z, /* HASH COORDINATES OF */
        B = P(X + 1) + Y, BA = P(B) + Z,
        BB = P(B + 1) + Z; /* THE 8 CUBE CORNERS, */
    return lerp(w,
                lerp(v,
                     lerp(u, grad(P(AA), x, y, z),        /* AND ADD */
                          grad(P(BA), x - 1, y, z)),      /* BLENDED */
                     lerp(u, grad(P(AB), x, y - 1, z),    /* RESULTS */
                          grad(P(BB), x - 1, y - 1, z))), /* FROM  8 */
                lerp(v,
                     lerp(u, grad(P(AA + 1), x, y, z - 1),   /* CORNERS */
                          grad(P(BA + 1), x - 1, y, z - 1)), /* OF CUBE */
                     lerp(u, grad(P(AB + 1), x, y - 1, z - 1),
                          grad(P(BB + 1), x - 1, y - 1, z - 1))));
}
References B, fade(), FASTLED_FORCE_INLINE, floorf(), grad(), lerp(), P(), x, y, and z.
Referenced by calculate_oscillators(), render_value(), and autoresearch::animartrix_check::runPerlinBenchmark().