FastLED: fl::sprintf
sprintf()
template<fl::size N, typename... Args> int fl::sprintf (char(&) buffer[N], const char * format, const Args &... args)
Sprintf-like formatting function that writes to a buffer.
Parameters
buffer Output buffer to write formatted string to
format Format string with placeholders like "%d", "%s", "%f" etc.
args Arguments to format
Returns
Number of characters written (excluding null terminator)
This function writes a formatted string to the provided buffer. The buffer size is deduced at compile time from the array reference, providing automatic safety against buffer overflows.
Example usage:
char buffer[100];
int len = fl::sprintf(buffer, "Value: %d, Name: %s", 42, "test");
Definition at line 712 of file stdio.h.
{
    // Use the compile-time known buffer size for safety
    return snprintf(buffer, N, format, args...);
}
References args, FL_NOEXCEPT, format(), and snprintf().
Referenced by fl::ScopedTrace::dump().