FastLED: fl::makeClockless
makeClockless()
template<typename TIMING> ClocklessChipset fl::makeClockless (int pin) constexpr
Build a ClocklessChipset from a compile-time TIMING trait.
Collapses the historical two-step pattern:
auto timing = fl::makeTimingConfig<fl::TIMING_WS2812_800KHZ>();
fl::ClocklessChipset chipset(PIN, timing);
into a single expression:
auto chipset = fl::makeClockless<fl::TIMING_WS2812_800KHZ>(PIN);
The encoder selector is extracted from the TIMING trait via encoder_for<>(): timings with a static ENCODER member (e.g., TIMING_UCS7604_800KHZ) yield that encoder; others default to CLOCKLESS_ENCODER_WS2812.
Template Parameters
TIMING Compile-time chipset timing trait (e.g., TIMING_WS2812_800KHZ)
Parameters
pin GPIO data pin
Examples
/home/runner/work/FastLED/FastLED/src/fl/channels/config.h.
Definition at line 94 of file config.h.
{
    return ClocklessChipset(pin, makeTimingConfig<TIMING>(), encoder_for<TIMING>());
}
References encoder_for(), FL_NOEXCEPT, and makeTimingConfig().
Referenced by fl::ChannelConfig::ChannelConfig().