FastLED: fl::render_value_fp_from_float
render_value_fp_from_float()
FASTLED_FORCE_INLINE fl::i32 fl::render_value_fp_from_float (const render_parameters & anim, const fl::i32 * fade_lut, const fl::u8 * perm)
Definition at line 180 of file render_value_fp.h.
{
    using FP = fl::s16x16;
    render_parameters_fp p;
    p.angle_raw = FP(anim.angle).raw();
    p.dist_raw = FP(anim.dist).raw();
    p.scale_x_raw = FP(anim.scale_x).raw();
    p.scale_y_raw = FP(anim.scale_y).raw();
    p.scale_z_raw = FP(anim.scale_z).raw();
    p.offset_x_raw = FP(anim.offset_x).raw();
    p.offset_y_raw = FP(anim.offset_y).raw();
    p.offset_z_raw = FP(anim.offset_z).raw();
    p.z_raw = FP(anim.z).raw();
    p.center_x_raw = FP(anim.center_x).raw();
    p.center_y_raw = FP(anim.center_y).raw();
    p.low_limit_raw = FP(anim.low_limit).raw();
    p.high_limit_raw = FP(anim.high_limit).raw();
    return render_value_fp(p, fade_lut, perm);
}
References fl::render_parameters::angle, fl::render_parameters_fp::angle_raw, fl::render_parameters::center_x, fl::render_parameters_fp::center_x_raw, fl::render_parameters::center_y, fl::render_parameters_fp::center_y_raw, fl::render_parameters::dist, fl::render_parameters_fp::dist_raw, FASTLED_FORCE_INLINE, fl::render_parameters::high_limit, fl::render_parameters_fp::high_limit_raw, fl::render_parameters::low_limit, fl::render_parameters_fp::low_limit_raw, fl::render_parameters::offset_x, fl::render_parameters_fp::offset_x_raw, fl::render_parameters::offset_y, fl::render_parameters_fp::offset_y_raw, fl::render_parameters::offset_z, fl::render_parameters_fp::offset_z_raw, fl::s16x16::raw(), render_value_fp(), fl::render_parameters::scale_x, fl::render_parameters_fp::scale_x_raw, fl::render_parameters::scale_y, fl::render_parameters_fp::scale_y_raw, fl::render_parameters::scale_z, fl::render_parameters_fp::scale_z_raw, fl::render_parameters::z, and fl::render_parameters_fp::z_raw.
Referenced by fl::Big_Caleido_FP::draw(), fl::Caleido1_FP::draw(), fl::Caleido2_FP::draw(), fl::Caleido3_FP::draw(), fl::Complex_Kaleido_2_FP::draw(), fl::Complex_Kaleido_3_FP::draw(), fl::Complex_Kaleido_4_FP::draw(), fl::Complex_Kaleido_6_FP::draw(), fl::Complex_Kaleido_FP::draw(), fl::Distance_Experiment_FP::draw(), fl::Fluffy_Blobs_FP::draw(), fl::Hot_Blob_FP::draw(), fl::Lava1_FP::draw(), fl::Module_Experiment1_FP::draw(), fl::Module_Experiment4_FP::draw(), fl::Module_Experiment5_FP::draw(), fl::Module_Experiment6_FP::draw(), fl::Module_Experiment7_FP::draw(), fl::Module_Experiment8_FP::draw(), fl::Module_Experiment9_FP::draw(), fl::Parametric_Water_FP::draw(), fl::Polar_Waves_FP::draw(), fl::RGB_Blobs2_FP::draw(), fl::RGB_Blobs3_FP::draw(), fl::RGB_Blobs4_FP::draw(), fl::RGB_Blobs5_FP::draw(), fl::RGB_Blobs_FP::draw(), fl::Rings_FP::draw(), fl::Rotating_Blob_FP::draw(), fl::Slow_Fade_FP::draw(), fl::SpiralMatrix10_FP::draw(), fl::SpiralMatrix1_FP::draw(), fl::SpiralMatrix2_FP::draw(), fl::SpiralMatrix3_FP::draw(), fl::SpiralMatrix5_FP::draw(), fl::SpiralMatrix6_FP::draw(), fl::SpiralMatrix8_FP::draw(), fl::SpiralMatrix9_FP::draw(), fl::Spiralus2_FP::draw(), fl::Spiralus_FP::draw(), fl::Water_FP::draw(), fl::Waves_FP::draw(), fl::Yves_FP::draw(), fl::Zoom2_FP::draw(), and fl::Zoom_FP::draw().