FastLED: fl::sqrtf
sqrtf()
float fl::sqrtf (float value) inline
Definition at line 453 of file math.h.
{ return sqrt_impl_float(value); }
References FL_NOEXCEPT, sqrt_impl_float(), and type_rank< T >::value.
Referenced by fl::audio::detector::anonymous_namespace{equalizer.cpp.hpp}::applyScaling(), fl::audio::Reactive::applyScaling(), fl::audio::fft::Bins::binBoundary(), fl::PhyllotaxisPath::compute(), fl::audio::detector::Vocal::computeBroadSpectralFeatures(), fl::audio::detector::Vocal::computePCMTimeDomainFeatures(), fl::audio::computePinkNoiseGain(), fl::audio::Reactive::computeRMS(), fl::audio::detector::KeyDetector::correlateWithProfile(), fl::Center_Field::draw(), fl::RGB_Blobs2::draw(), fl::RGB_Blobs2_FP::draw(), fl::RGB_Blobs3::draw(), fl::RGB_Blobs3_FP::draw(), fl::RGB_Blobs4::draw(), fl::RGB_Blobs4_FP::draw(), fl::RGB_Blobs5::draw(), fl::RGB_Blobs5_FP::draw(), fl::RGB_Blobs::draw(), fl::RGB_Blobs_FP::draw(), fl::Slow_Fade::draw(), fl::Slow_Fade_FP::draw(), fl::FlowFieldFloat::drawDot(), drawPlasmaWave(), fl::audio::detector::KeyDetector::initializeProfileStats(), fl::audio::SampleImpl::initRms(), and fl::audio::AutoGain::process().