FastLED: fl::ColorFromPalette
ColorFromPalette() [4/8]
CRGB fl::ColorFromPalette (const CRGBPalette16 & pal, fl::u8 index, fl::u8 brightness, TBlendType blendType)
Definition at line 395 of file colorutils.cpp.hpp.
{
    if (blendType == LINEARBLEND_NOWRAP) {
        index = map8(index, 0, 239); // Blend range is affected by lo4 blend of
                                     // values, remap to avoid wrapping
    }
    //      hi4 = index >> 4;
    fl::u8 hi4 = lsrX4(index);
    fl::u8 lo4 = index & 0x0F;
    // const CRGB* entry = &(pal[0]) + hi4;
    // since hi4 is always 0..15, hi4 * sizeof(CRGB) can be a single-byte value,
    // instead of the two byte 'int' that avr-gcc defaults to.
    // So, we multiply hi4 X sizeof(CRGB), giving hi4XsizeofCRGB;
    fl::u8 hi4XsizeofCRGB = hi4 * sizeof(CRGB);
    // We then add that to a base array pointer.
    const CRGB *entry = (CRGB *)((fl::u8 *)(&(pal[0])) + hi4XsizeofCRGB);
    fl::u8 blend = lo4 && (blendType != NOBLEND);
    fl::u8 red1 = entry->red;
    fl::u8 green1 = entry->green;
    fl::u8 blue1 = entry->blue;
    if (blend) {
        if (hi4 == 15) {
            entry = &(pal[0]);
        } else {
            ++entry;
        }
        fl::u8 f2 = lo4 << 4;
        fl::u8 f1 = 255 - f2;
        //    rgb1.nscale8(f1);
        fl::u8 red2 = entry->red;
        red1 = scale8_LEAVING_R1_DIRTY(red1, f1);
        red2 = scale8_LEAVING_R1_DIRTY(red2, f2);
        red1 += red2;
        fl::u8 green2 = entry->green;
        green1 = scale8_LEAVING_R1_DIRTY(green1, f1);
        green2 = scale8_LEAVING_R1_DIRTY(green2, f2);
        green1 += green2;
        fl::u8 blue2 = entry->blue;
        blue1 = scale8_LEAVING_R1_DIRTY(blue1, f1);
        blue2 = scale8_LEAVING_R1_DIRTY(blue2, f2);
        blue1 += blue2;
        cleanup_R1();
    }
    if (brightness != 255) {
        if (brightness) {
            ++brightness; // adjust for rounding
            // Now, since brightness is nonzero, we don't need the full
            // scale8_video logic; we can just to scale8 and then add one
            // (unless scale8 fixed) to all nonzero inputs.
            if (red1) {
                red1 = scale8_LEAVING_R1_DIRTY(red1, brightness);
#if !(FASTLED_SCALE8_FIXED == 1)
                ++red1;
#endif
            }
            if (green1) {
                green1 = scale8_LEAVING_R1_DIRTY(green1, brightness);
#if !(FASTLED_SCALE8_FIXED == 1)
                ++green1;
#endif
            }
            if (blue1) {
                blue1 = scale8_LEAVING_R1_DIRTY(blue1, brightness);
#if !(FASTLED_SCALE8_FIXED == 1)
                ++blue1;
#endif
            }
            cleanup_R1();
        } else {
            red1 = 0;
            green1 = 0;
            blue1 = 0;
        }
    }
    return CRGB(red1, green1, blue1);
}
References blend(), brightness, lsrX4(), and map8().
Referenced by fl::DemoReel100::bpm(), fl::TwinkleFox::computeOneTwinkle(), fl::Fire2012::draw(), FL_DISABLE_WARNING(), fl::NoisePalette::mapNoiseToLEDsUsingPalette(), fl::PerlinParticlePunch::noiseCircleDraw(), fl::Pacifica::pacifica_one_layer(), fl::PerlinParticlePunch::renderAmbient(), and fl::detail::UpscalePaletteInterpolated().