FastLED: fl::encodeHD108_HD
encodeHD108_HD()
template<typename InputIterator, typename BrightnessIterator, typename OutputIterator> void fl::encodeHD108_HD (InputIterator first, InputIterator last, BrightnessIterator brightness_first, OutputIterator out)
Encode pixel data in HD108 format with per-LED brightness.
Template Parameters
InputIterator Iterator yielding fl::array<u8, 3> (3 bytes in wire order)
BrightnessIterator Iterator yielding uint8_t brightness values
OutputIterator Output iterator accepting uint8_t
Parameters
first Iterator to first pixel
last Iterator past last pixel
brightness_first Iterator to first brightness value (8-bit, 0-255)
out Output iterator for encoded bytes
Note
HD108 uses RGB wire order: pixel[0]=Red, pixel[1]=Green, pixel[2]=Blue
Definition at line 90 of file hd108.h.
{
    // Start frame: 64 bits (8 bytes) of 0x00
    for (int i = 0; i < 8; i++) {
        *out++ = 0x00;
    }
    // Brightness conversion cache (avoid recomputing same values)
    u8 lastBrightness8 = 0;
    u8 lastF0 = 0xFF, lastF1 = 0xFF;  // Invalid markers
    // LED data: 2-byte header + 6-byte RGB16 (count as we go)
    size_t num_leds = 0;
    while (first != last) {
        const fl::array<u8, BYTES_PER_PIXEL_RGB>& pixel = *first;
        u8 brightness = *brightness_first;
        // Apply gamma correction (2.8) to 16-bit (RGB order: 0=R, 1=G, 2=B)
        u16 r16 = hd108GammaCorrect(pixel[0]);  // Red
        u16 g16 = hd108GammaCorrect(pixel[1]);  // Green
        u16 b16 = hd108GammaCorrect(pixel[2]);  // Blue
        // Compute brightness header (with caching)
        u8 f0, f1;
        if (brightness == lastBrightness8 && lastF0 != 0xFF) {
            f0 = lastF0;
            f1 = lastF1;
        } else {
            hd108BrightnessHeader(brightness, &f0, &f1);
            lastBrightness8 = brightness;
            lastF0 = f0;
            lastF1 = f1;
        }
        // Transmit: 2 header + 6 color bytes (16-bit RGB, big-endian)
        *out++ = f0;
        *out++ = f1;
        *out++ = static_cast<u8>(r16 >> 8);
        *out++ = static_cast<u8>(r16 & 0xFF);
        *out++ = static_cast<u8>(g16 >> 8);
        *out++ = static_cast<u8>(g16 & 0xFF);
        *out++ = static_cast<u8>(b16 >> 8);
        *out++ = static_cast<u8>(b16 & 0xFF);
        ++first;
        ++brightness_first;
        ++num_leds;
    }
    // End frame: (num_leds / 2) + 4 bytes of 0xFF
    const size_t latch = num_leds / 2 + 4;
    for (size_t i = 0; i < latch; i++) {
        *out++ = 0xFF;
    }
}
References brightness, FL_NOEXCEPT, hd108BrightnessHeader(), and hd108GammaCorrect().
Referenced by fl::PixelIterator::writeHD108().