FastLED: fl::ease16
ease16() [2/2]
u16 fl::ease16 (EaseType type, u16 i) inline
Definition at line 132 of file ease.h.
{
    switch (type) {
        case EaseType::EASE_NONE: return i;
        case EaseType::EASE_IN_QUAD: return easeInQuad16(i);
        case EaseType::EASE_OUT_QUAD: return easeOutQuad16(i);
        case EaseType::EASE_IN_OUT_QUAD: return easeInOutQuad16(i);
        case EaseType::EASE_IN_CUBIC: return easeInCubic16(i);
        case EaseType::EASE_OUT_CUBIC: return easeOutCubic16(i);
        case EaseType::EASE_IN_OUT_CUBIC: return easeInOutCubic16(i);
        case EaseType::EASE_IN_SINE: return easeInSine16(i);
        case EaseType::EASE_OUT_SINE: return easeOutSine16(i);
        case EaseType::EASE_IN_OUT_SINE: return easeInOutSine16(i);
        default: return i;
    }
}
References EASE_IN_CUBIC, EASE_IN_OUT_CUBIC, EASE_IN_OUT_QUAD, EASE_IN_OUT_SINE, EASE_IN_QUAD, EASE_IN_SINE, EASE_NONE, EASE_OUT_CUBIC, EASE_OUT_QUAD, EASE_OUT_SINE, easeInCubic16(), easeInOutCubic16(), easeInOutQuad16(), easeInOutSine16(), easeInQuad16(), easeInSine16(), easeOutCubic16(), easeOutQuad16(), easeOutSine16(), and FL_NOEXCEPT.
Referenced by fl::HSV16::colorBoost().