FastLED: fl::fetch_head
fetch_head()
fl::promise< response > fl::fetch_head (const fl::string & url, const fetch_options & request)
HTTP HEAD request.
Definition at line 248 of file fetch.cpp.
{
    // Create a new request with HEAD method
    fetch_options head_request(url, RequestOptions("HEAD"));
    // Apply any additional options from the provided request
    const auto& opts = request.options();
    head_request.timeout(opts.timeout_ms);
    for (const auto& header : opts.headers) {
        head_request.header(header.first, header.second);
    }
    if (!opts.body.empty()) {
        head_request.body(opts.body);
    }
    return execute_fetch_request(url, head_request);
}
References fl::fetch_options::body(), execute_fetch_request(), fl::fetch_options::header(), fl::fetch_options::options(), and fl::fetch_options::timeout().