FastLED: fl::sinf
sinf()
float fl::sinf (float value) inline
Definition at line 352 of file math.h.
{ return sin_impl_float(value); }
References FL_NOEXCEPT, sin_impl_float(), and type_rank< T >::value.
Referenced by fl::detail::BiquadFilterImpl< T >::bandpass(), fl::detail::BiquadFilterImpl< T >::butterworth(), fl::ArchimedeanSpiralPath::compute(), fl::CirclePath::compute(), fl::GielisCurvePath::compute(), fl::HeartPath::compute(), fl::PhyllotaxisPath::compute(), fl::RosePath::compute(), fl::Luminova::draw(), fl::Module_Experiment10::draw(), fl::Module_Experiment10_FP::draw(), fl::Module_Experiment5::draw(), fl::Module_Experiment5_FP::draw(), fl::Module_Experiment6::draw(), fl::Module_Experiment6_FP::draw(), fl::Module_Experiment7::draw(), fl::Module_Experiment7_FP::draw(), fl::Module_Experiment8::draw(), fl::Module_Experiment8_FP::draw(), fl::Parametric_Water::draw(), fl::Parametric_Water_FP::draw(), fl::Water::draw(), fl::Water_FP::draw(), drawPlasmaWave(), drawRadialSpectrum(), fl::FlowFieldFloat::emitLissajousLine(), fl::FlowFieldFloat::emitOrbitalDots(), FL_DISABLE_WARNING(), fl::detail::BiquadFilterImpl< T >::highpass(), loop(), noiseCylinderCRGB(), noiseCylinderHSV16(), noiseRingCRGB(), noiseRingHSV16(), noiseSphereCRGB(), noiseSphereHSV16(), fl::detail::BiquadFilterImpl< T >::notch(), sincos(), sincos(), and fl::NoiseBias1D::trigger().