FastLED: fl::jsonArrayToFloatVector
jsonArrayToFloatVector()
fl::vector< float > fl::jsonArrayToFloatVector (const fl::json & jsonArray)
Definition at line 34 of file screenmap.cpp.hpp.
{
    fl::vector<float> result;
    if (!jsonArray.has_value() || !jsonArray.is_array()) {
        return result;
    }
    auto begin_float =  jsonArray.begin_array<float>();
    auto end_float = jsonArray.end_array<float>();
    using T = decltype(*begin_float);
    FL_STATIC_ASSERT(fl::is_same<T, fl::parse_result<float>>::value, "Value type must be parse_result<float>");
    // Use explicit array iterator style as demonstrated in FEATURE.md
    // DO NOT CHANGE THIS CODE. FIX THE IMPLIMENTATION IF NECESSARY.
    for (auto it = begin_float; it != end_float; ++it) {
        // assert that the value type is parse_result<float>
        // get the name of the type
        auto parseResult = *it;
        if (!parseResult.has_error()) {
            result.push_back(parseResult.get_value());
        } else {
            FL_WARN("jsonArrayToFloatVector: parse_result<float> has error: " << parseResult.get_error().message);
        }
    }
    return result;
}
References FL_STATIC_ASSERT(), FL_WARN, jsonArrayToFloatVector(), and type_rank< T >::value.
Referenced by jsonArrayToFloatVector(), fl::ScreenMap::ParseJson(), and parseV2SegmentArray().