FastLED: fl::min
min()
FL_DISABLE_WARNING_PUSH U constexpr common_type_t< T, U > fl::min (T a, U b) inline constexpr
Definition at line 71 of file math.h.
{
    return (a < b) ? a : b;
}
References FL_NOEXCEPT.
Referenced by fl::rect< T >::rect(), fl::UINumberField::UINumberField(), fl::UINumberFieldImpl::UINumberFieldImpl(), fl::UISliderImpl::UISliderImpl(), fl::anonymous_namespace{gradient.cpp.hpp}::VisitorFill::VisitorFill(), fl::WaveFx::addf(), fl::Tile2x2_u8::bounds(), anonymous_namespace{Painter.cpp}::CalcSaturation(), fl::audio::detector::MoodAnalyzer::calculateArousal(), fl::audio::detector::Vocal::calculateAutocorrelationIrregularity(), fl::audio::detector::FrequencyBands::calculateBandEnergy(), fl::audio::detector::DropDetector::calculateBassFlux(), fl::audio::detector::BuildupDetector::calculateBuildupIntensity(), fl::audio::detector::MoodAnalyzer::calculateConfidence(), fl::audio::detector::Pitch::calculateConfidence(), fl::audio::detector::DropDetector::calculateDropImpact(), fl::audio::detector::DropDetector::calculateEnergyFlux(), fl::audio::detector::BuildupDetector::calculateEnergyTrend(), fl::audio::detector::Backbeat::calculateMultibandAccent(), fl::audio::detector::Backbeat::calculatePatternConfidence(), fl::audio::detector::Vocal::calculateRawConfidence(), fl::audio::detector::Beat::calculateSpectralFlux(), fl::audio::detector::TempoAnalyzer::calculateSpectralFlux(), fl::audio::detector::DropDetector::calculateSpectralNovelty(), fl::audio::detector::TempoAnalyzer::calculateTempoConfidence(), fl::audio::detector::BuildupDetector::calculateTrebleTrend(), fl::audio::detector::DynamicsAnalyzer::calculateTrend(), fl::audio::detector::MoodAnalyzer::calculateValence(), fl::audio::detector::Vocal::calculateVocalPresenceRatio(), fl::audio::detector::Percussion::computeConfidences(), fl::audio::detector::Percussion::computeFeatures(), fl::audio::detector::Vocal::computeFormantRatio(), fl::audio::detector::Beat::detectBeat(), fl::audio::detector::KeyDetector::detectKey(), fl::audio::detector::Transient::detectTransient(), fl::Corkscrew::draw(), fl::FlowFieldFloat::drawDot(), fl::FlowFieldFP::drawDot(), drawFireEffect(), drawRadialSpectrum(), LedRopeTCL::DrawRepeat(), drawVUMeter(), fl::FlowFieldFloat::emitOrbitalDots(), fl::FlowFieldFP::emitOrbitalDots(), fl::rect< T >::expand(), FL_DISABLE_WARNING(), FL_DISABLE_WARNING(), fl::AsyncLogger::flush(), fl::AsyncLogger::flushN(), fl::Transform16::From(), ColorHSV::FromRGB(), fl::math::random::generate_nolock(), fl::ScreenMap::getBounds(), fl::vec2< u16 >::getMin(), fl::vec2< u16 >::getMin(), fl::vec3< float >::getMin(), fl::vec3< float >::getMin(), anonymous_namespace{wave_simulation.cpp.hpp}::half_duplex_blend_linear(), anonymous_namespace{wave_simulation.cpp.hpp}::half_duplex_blend_sqrt_q15(), hsv2rgb_fullspectrum(), fl::Engine::init(), fl::FileSystem::loadJpeg(), loop(), makeRingScreenMap(), fl::bitset_dynamic::operator&(), fl::math::random::operator()(), fl::bitset_dynamic::operator^(), fl::bitset_dynamic::operator|(), fl::ScreenMap::ParseJson(), parseV2SegmentArray(), fl::audio::AutoGain::process(), processWaveAutoTrigger(), fl::math::random::random16(), fl::math::random::random8(), fl::math::random::random8_nolock(), fl::Mpeg1FileHandle::read(), fl::Corkscrew::readFrom(), fl::detail::TriangularFilterImpl< T, N >::recompute(), Ripple::renderLed(), fl::bitset_dynamic::resize(), RGBtoHSV16(), fl::task::run(), sampleBilinear(), sampleNearest(), fl::TransformFloat::scale(), fl::audio::detector::FrequencyBands::setBassRange(), fl::audio::detector::FrequencyBands::setMidRange(), fl::Potentiometer::setRange(), fl::audio::detector::DynamicsAnalyzer::setSmoothingFactor(), fl::audio::detector::FrequencyBands::setTrebleRange(), fl::UINumberFieldImpl::setValue(), fl::UISliderImpl::setValue(), fl::LineSimplifierExact< NumberT >::simplify(), fl::FixedVector< fl::u32, kMaxBatchSize >::swap(), to_uint8(), fl::Transform16::ToBounds(), traverseGridSegmentFloat(), fl::NoiseBias1D::trigger(), fl::audio::detector::BuildupDetector::update(), fl::audio::detector::EnergyAnalyzer::update(), fl::audio::detector::EqualizerDetector::update(), fl::audio::detector::FrequencyBands::update(), fl::audio::detector::TempoAnalyzer::update(), fl::audio::NoiseFloorTracker::update(), fl::audio::detector::Transient::updateAttackTime(), fl::audio::detector::Backbeat::updateBackbeatProfile(), fl::audio::detector::MusicalBeat::updateBPMEstimate(), fl::audio::detector::DynamicsAnalyzer::updateCompression(), fl::TimeClampedTransition::updatef(), fl::audio::NoiseFloorTracker::updateFloor(), fl::audio::AutoGain::updatePIController(), and Painter::VegasVisualizer().