FastLED: fl::clamp
clamp()
template<typename T> FASTLED_FORCE_INLINE T fl::clamp (T value, T min, T max)
Definition at line 10 of file clamp.h.
{
    if (value < min) {
        return min;
    }
    if (value > max) {
        return max;
    }
    return value;
}
References FASTLED_FORCE_INLINE.
Referenced by fl::XYPath::calculateSteps(), fl::wave_detail::float_to_fixed(), fl::MatrixSlice< T >::getLocalCoord(), loop(), map_range_clamped(), fl::XYMap::mapToIndex(), fl::WaveSimulation1D::setf(), fl::WaveSimulation2D::setf(), fl::HashMap< Key, T, Hash, KeyEqual >::setLoadFactor(), and showGenerative().