FastLED: fl::transpose_strips
transpose_strips()
bool fl::transpose_strips (u8 num_strips, const u8 *const * input, u8 * output, u16 num_leds, u8 bytes_per_led) inline
Helper to transpose N strips with automatic dispatch.
Parameters
num_strips Number of strips (must be 2, 4, or 8)
input Array of pointers to LED strip data
output Pointer to output buffer
num_leds Number of LEDs per strip
bytes_per_led Number of bytes per LED (3 for RGB, 4 for RGBW, etc.)
Returns
true if successful, false if invalid strip count
Examples
/home/runner/work/FastLED/FastLED/src/fl/math/transposition.h.
Definition at line 812 of file transposition.h.
              {
    switch (num_strips) {
        case 8:
            transpose_8strips(input, output, num_leds, bytes_per_led);
            return true;
        case 4:
            transpose_4strips(input, output, num_leds, bytes_per_led);
            return true;
        case 2:
            transpose_2strips(input, output, num_leds, bytes_per_led);
            return true;
        default:
            return false;  // Invalid strip count
    }
}
References FL_NOEXCEPT, transpose_2strips(), transpose_4strips(), and transpose_8strips().