FastLED: fl::map_range_clamped
map_range_clamped()
template<typename T, typename U> FASTLED_FORCE_INLINE U fl::map_range_clamped (T value, T in_min, T in_max, U out_min, U out_max)
Examples
ElPanelReactive.ino.
Definition at line 186 of file math.h.
{
    value = clamp(value, in_min, in_max);
    return map_range<T, U>(value, in_min, in_max, out_min, out_max);
}
References clamp(), FASTLED_FORCE_INLINE, FL_NOEXCEPT, map_range(), and type_rank< T >::value.
Referenced by rescaleNoiseValue16(), and setup().