FastLED: fl::get_async_logger_by_index
get_async_logger_by_index()
template<fl::size N, typename InfoProvider> AsyncLogger & fl::get_async_logger_by_index () inline
Template-based logger accessor with auto-registration and enablement check.
Template Parameters
N Logger index (0-15, maps to Singleton<AsyncLogger, N>)
InfoProvider Type providing category name and define name via static methods
Returns
Reference to AsyncLogger singleton instance
Note
Only instantiated template indices are compiled - linker removes unused ones
Prints error message once if logging is disabled for this category
Definition at line 249 of file async_logger.h.
{
    // Get singleton instance (only this specific N is instantiated)
    static AsyncLogger* logger_ptr = []() {
        AsyncLogger* ptr = &SingletonShared<AsyncLogger, N>::instance();
        detail::ActiveLoggerRegistry::instance().registerLogger(ptr);
        // Auto-instantiate service task on first logger access
        // This ensures automatic background servicing via fl::delay() and fl::task::Scheduler
        (void)detail::AsyncLoggerServiceTask::instance();
        return ptr;
    }();
    // Check if logging is enabled, print error once if not
    // (Implementation in async_logger.cpp.hpp uses FL_ERROR)
    detail::checkLoggerEnabled<InfoProvider>();
    return *logger_ptr;
}
References fl::detail::checkLoggerEnabled(), get_async_logger_by_index(), fl::detail::ActiveLoggerRegistry::instance(), fl::detail::AsyncLoggerServiceTask::instance(), and fl::SingletonShared< T, N >::instance().
Referenced by get_async_logger_by_index(), get_audio_async_logger_isr(), get_audio_async_logger_main(), get_flexio_async_logger_isr(), get_flexio_async_logger_main(), get_interrupt_async_logger_isr(), get_interrupt_async_logger_main(), get_objectfled_async_logger_isr(), get_objectfled_async_logger_main(), get_parlio_async_logger_isr(), get_parlio_async_logger_main(), get_rmt_async_logger_isr(), get_rmt_async_logger_main(), get_spi_async_logger_isr(), and get_spi_async_logger_main().