FastLED: fl::setPwmFrequency
setPwmFrequency()
int fl::setPwmFrequency (int pin, u32 frequency_hz)
Set PWM frequency for a pin.
Subsequent analogWrite()/setPwm16() calls use this frequency. Automatically selects native hardware PWM or ISR-based software PWM depending on platform.
Parameters
pin Pin number (platform-specific numbering)
frequency_hz Desired PWM frequency in Hz (1-500 Hz for ISR, platform-dependent for native HW)
Returns
0 on success, negative error code on failure (-1: invalid freq, -2: all channels in use, -3: ISR setup failed, -4: native HW failed)
Definition at line 274 of file pin.cpp.hpp.
{
    // Check if pin already has a channel
    pwm_state::PwmPinState* ch = pwm_state::findByPin(pin);
    if (ch) {
        // Pin already configured — release and reconfigure
        pwm_state::releaseChannel(ch);
        ch = nullptr;
    }
    // Validate frequency
    if (frequency_hz == 0) {
        FL_WARN("setPwmFrequency: Frequency must be > 0");
        return -1;
    }
    // Query platform: can it handle this natively?
    bool needs_isr = platforms::needsPwmIsrFallback(pin, frequency_hz);
    if (!needs_isr) {
        // Native path
        int result = platforms::setPwmFrequencyNative(pin, frequency_hz);
        if (result != 0) {
            FL_WARN("setPwmFrequency: Native backend failed: " << result);
            return result;
        }
        // Allocate tracking slot
        ch = pwm_state::allocate();
        if (!ch) {
            FL_WARN("setPwmFrequency: All " << static_cast<int>(pwm_state::MAX_PWM_CHANNELS) << " channels in use");
            return -2;
        }
        ch->pin = pin;
        ch->frequency_hz = frequency_hz;
        ch->backend = pwm_state::PwmBackend::Native;
        ch->duty_cycle = 0;
        return 0;
    }
    // ISR software fallback path
    if (frequency_hz > pwm_state::MAX_ISR_PWM_FREQUENCY) {
        FL_WARN("setPwmFrequency: ISR fallback max " << pwm_state::MAX_ISR_PWM_FREQUENCY << " Hz, requested " << frequency_hz);
        return -1;
    }
    // Allocate channel
    ch = pwm_state::allocate();
    if (!ch) {
        FL_WARN("setPwmFrequency: All " << static_cast<int>(pwm_state::MAX_PWM_CHANNELS) << " channels in use");
        return -2;
    }
    // Ensure ISR is running
    int isr_result = pwm_state::ensureIsrActive();
    if (isr_result != 0) {
        return -3;
    }
    // Configure GPIO
    fl::pinMode(pin, fl::PinMode::Output);
    fl::digitalWrite(pin, fl::PinValue::Low);
    // Initialize channel (atomic)
    {
        fl::isr::critical_section cs;
        ch->pin = pin;
        ch->frequency_hz = frequency_hz;
        ch->backend = pwm_state::PwmBackend::IsrSoftware;
        ch->period_ticks = pwm_state::ISR_FREQUENCY_HZ / frequency_hz;
        ch->duty_cycle = 0;
        ch->high_ticks = 0;
        ch->tick_counter = 0;
        ch->pin_state = false;
    }
    return 0;
}
References fl::pwm_state::allocate(), fl::pwm_state::PwmPinState::backend, digitalWrite(), fl::pwm_state::PwmPinState::duty_cycle, fl::pwm_state::ensureIsrActive(), fl::pwm_state::findByPin(), FL_WARN, fl::pwm_state::PwmPinState::frequency_hz, fl::pwm_state::PwmPinState::high_ticks, fl::pwm_state::ISR_FREQUENCY_HZ, fl::pwm_state::IsrSoftware, Low, fl::pwm_state::MAX_ISR_PWM_FREQUENCY, fl::pwm_state::MAX_PWM_CHANNELS, fl::pwm_state::Native, Output, fl::pwm_state::PwmPinState::period_ticks, fl::pwm_state::PwmPinState::pin, fl::pwm_state::PwmPinState::pin_state, pinMode(), fl::pwm_state::releaseChannel(), and fl::pwm_state::PwmPinState::tick_counter.
Referenced by initPanels().