FastLED: fl::parseV2SegmentArray
parseV2SegmentArray()
static bool fl::parseV2SegmentArray (const fl::json & segmentsArr, fl::flat_map< string, ScreenMap > * segmentMaps, string * err) static
Definition at line 114 of file screenmap.cpp.hpp.
{
    if (!segmentsArr.has_value() || !segmentsArr.is_array()) {
        *err = "v2 'segments' is not an array";
        return false;
    }
    auto arrPtr = segmentsArr.as_array();
    if (!arrPtr) {
        *err = "v2 'segments' array could not be read";
        return false;
    }
    for (const auto& elem : *arrPtr) {
        if (!elem) {
            *err = "v2 segment is null";
            return false;
        }
        fl::json segVal(elem);
        if (!segVal.has_value() || !segVal.is_object()) {
            *err = "v2 segment is not an object";
            return false;
        }
        // Required: id
        if (!segVal.contains("id") || !segVal["id"].has_value()) {
            *err = "v2 segment missing 'id'";
            return false;
        }
        auto idOpt = segVal["id"].as_string();
        if (!idOpt) {
            *err = "v2 segment 'id' is not a string";
            return false;
        }
        string id = *idOpt;
        // Required: x
        if (!segVal.contains("x") || !segVal["x"].has_value() || !segVal["x"].is_array()) {
            *err = "v2 segment '" + id + "' missing or invalid 'x' array";
            return false;
        }
        fl::vector<float> x_array = jsonArrayToFloatVector(segVal["x"]);
        // Required: y
        if (!segVal.contains("y") || !segVal["y"].has_value() || !segVal["y"].is_array()) {
            *err = "v2 segment '" + id + "' missing or invalid 'y' array";
            return false;
        }
        fl::vector<float> y_array = jsonArrayToFloatVector(segVal["y"]);
        // Optional: diameter (not in canonical v2 but accepted as a backward-compat
        // hint when present; otherwise the per-group `diameter` could be wired here
        // in a future iteration).
        float diameter = -1.0f;
        if (segVal.contains("diameter") && segVal["diameter"].has_value()) {
            auto diameterOpt = segVal["diameter"].as_float();
            if (diameterOpt) {
                diameter = static_cast<float>(*diameterOpt);
            }
        }
        auto n = fl::min(x_array.size(), y_array.size());
        ScreenMap segment_map(n, diameter);
        for (size_t i = 0; i < n; i++) {
            segment_map.set(i, vec2f{x_array[i], y_array[i]});
        }
        (*segmentMaps)[id] = fl::move(segment_map);
    }
    return true;
}
References fl::json::as_float(), fl::json::as_string(), fl::json::contains(), FL_NOEXCEPT, fl::json::has_value(), fl::json::is_array(), fl::json::is_object(), jsonArrayToFloatVector(), min(), fl::fl::move(), fl::ScreenMap::set(), and fl::vector_basic::size().
Referenced by fl::ScreenMap::ParseJson().