FastLED: fl::memcpy
memcpy()
void * fl::memcpy (void * dest, const void * src, size_t n)
Examples
/home/runner/work/FastLED/FastLED/src/fl/math/transposition.h.
Definition at line 110 of file cstring.cpp.hpp.
{
    if (n == 0) return dest;
    return ::memcpy(dest, src, n);
}
References FL_NOEXCEPT.
Referenced by fl::bitset_dynamic::bitset_dynamic(), fl::StringHolder::StringHolder(), fl::StringHolder::StringHolder(), fl::basic_string::assign(), fl::string::assign(), autoresearch::simd_check::benchFloat4(), bit_cast(), fl::XYMap::constructWithLookUpTable(), fl::basic_string::copy(), fl::basic_string::copy(), fl::basic_string::copy(), fl::Frame::copy(), fl::string_view::copy(), fl::StringHolder::copy(), fl::Frame::draw(), fl::FxCompositor::draw(), fl::basic_string::erase(), FL_DISABLE_WARNING(), fl::AsyncLogger::flush(), fl::AsyncLogger::flushN(), fl::audio::Context::hashFFTArgs(), fl::third_party::SoftwareMpeg1Decoder::initializeDecoder(), fl::third_party::TJpgInstanceDecoder::initializeDecoder(), fl::third_party::TJpgInstanceDecoder::inputCallback(), fl::basic_string::insert(), fl::basic_string::insert(), fl::vector_basic::insert_copy_impl(), fl::vector_basic::insert_move_impl(), fl::third_party::TJpg_Decoder::jd_input(), kiss_fft_stride(), fl::third_party::SoftwareGifDecoder::loadMoreData(), fl::basic_string::materialize(), memcopy(), fl::basic_string::moveAssign(), fl::basic_string::moveFrom(), fl::third_party::nsgif__get_frame(), fl::third_party::nsgif__record_frame(), fl::third_party::nsgif__recover_frame(), fl::third_party::nsgif_global_palette(), fl::bitset_dynamic::operator=(), fl::bitset_dynamic::operator^(), fl::bitset_dynamic::operator|(), fl::vector_basic::push_back_copy_impl(), fl::vector_basic::push_back_move_impl(), qsort_insertion_sort(), fl::detail::qsort_swap(), fl::Mpeg1FileHandle::read(), fl::net::http::ChunkedReader::readChunk(), fl::third_party::TJpgInstanceDecoder::readStreamData(), reallocate_kernels(), fl::basic_string::replace(), fl::basic_string::replace(), fl::basic_string::reserve(), fl::bitset_dynamic::resize(), fl::vector_basic::resize_value_impl(), fl::basic_string::shrink_to_fit(), fl::vector_basic::swap_impl(), fl::basic_string::swapWith(), fl::SpiChannelEngineAdapter::transmitBatch(), transpose_wave8byte_parlio_template(), fl::vector_basic::trivial_copy(), fl::vector_basic::trivial_swap(), fl::net::http::ChunkedWriter::writeChunk(), and fl::net::http::ChunkedWriter::writeFinal().