FastLED: fl::downscale
downscale()
void fl::downscale (const CRGB * src, const XYMap & srcXY, CRGB * dst, const XYMap & dstXY)
Definition at line 153 of file downscale.cpp.
{
    uint16_t srcWidth = srcXY.getWidth();
    uint16_t srcHeight = srcXY.getHeight();
    uint16_t dstWidth = dstXY.getWidth();
    uint16_t dstHeight = dstXY.getHeight();
    FASTLED_ASSERT(dstWidth <= srcWidth,
                   "Destination width must be <= source width");
    FASTLED_ASSERT(dstHeight <= srcHeight,
                   "Destination height must be <= source height");
    const bool destination_is_half_of_source =
        (dstWidth * 2 == srcWidth) && (dstHeight * 2 == srcHeight);
    // Attempt to use the downscaleHalf function if the destination is half the
    // size of the source.
    if (destination_is_half_of_source) {
        const bool both_rectangles = (srcXY.getType() == XYMap::kLineByLine) &&
                                     (dstXY.getType() == XYMap::kLineByLine);
        if (both_rectangles) {
            // If both source and destination are rectangular, we can use the
            // optimized version
            downscaleHalf(src, srcWidth, srcHeight, dst);
        } else {
            // Otherwise, we need to use the mapped version
            downscaleHalf(src, srcXY, dst, dstXY);
        }
        return;
    }
    downscaleArbitrary(src, srcXY, dst, dstXY);
}
References downscaleArbitrary(), downscaleHalf(), fl::XYMap::getHeight(), fl::XYMap::getType(), fl::XYMap::getWidth(), and fl::XYMap::kLineByLine.
Referenced by CRGB::downscale(), and loop().