FastLED: fl::println
println()
void fl::println (const char * str)
Definition at line 94 of file cstdio.cpp.hpp.
{
    if (!str) return;
    // Check global log level - if NONE, suppress all output
    if (gLogLevel == static_cast<u8>(LogLevel::FL_LOG_LEVEL_NONE)) return;
#ifdef FASTLED_TESTING
    // Check for injected handler first
    if (get_println_handler()) {
        get_println_handler()(str);
        return;
    }
#endif
    // Delegate to platform implementation
    platforms::println(str);
}
References FL_LOG_LEVEL_NONE, and gLogLevel.
Referenced by fl::AsyncLogger::flush(), fl::AsyncLogger::flushN(), fl::detail::log_emit(), printJsonRaw(), fl::SerialPort::println(), fl::SerialPort::println(), fl::SerialWriter::println(), and printStreamRaw().