FastLED: fl::exp_impl_double
exp_impl_double()
double fl::exp_impl_double (double value)
Definition at line 101 of file math.cpp.hpp.
{
    if (value > 10.0)
        return 22026.465794806718; // e^10 approx
    if (value < -10.0)
        return 0.0000453999297625; // e^-10 approx
    // For negative values, use exp(x) = 1/exp(-x) to keep the Taylor series
    // input non-negative where it converges well with limited terms.
    if (value < 0.0) {
        return 1.0 / exp_impl_double(-value);
    }
    double result = 1.0;
    double term = 1.0;
    for (int i = 1; i < 10; ++i) {
        term *= value / static_cast<double>(i);
        result += term;
    }
    return result;
}
References exp_impl_double(), and type_rank< T >::value.
Referenced by exp(), exp_impl_double(), and pow_impl_double().