FastLED: fl::calloc
calloc()
void * fl::calloc (size_t nmemb, size_t size)
Definition at line 17 of file malloc.cpp.hpp.
{
        size_t total_size = nmemb * size;
        void* ptr = malloc(total_size);
        if (ptr != nullptr) {
            memset(ptr, 0, total_size);
        }
        return ptr;
    }
References malloc(), and memset().
Referenced by _generate_kernel().