FastLED: fl::getBytesPerPixel
getBytesPerPixel()
fl::u8 fl::getBytesPerPixel (PixelFormat format) inline
Definition at line 15 of file pixel.h.
{
    switch (format) {
        case PixelFormat::RGB565: return 2;
        case PixelFormat::RGB888: return 3;
        case PixelFormat::RGBA8888: return 4;
        case PixelFormat::YUV420: return 1; // Simplified for luminance component
        default: return 3;
    }
}
References format(), RGB565, RGB888, RGBA8888, and YUV420.
Referenced by fl::third_party::TJpgInstanceDecoder::allocateFrameBuffer(), and fl::third_party::TJpgInstanceDecoder::getBytesPerPixel().