FastLED: fl::easeInOutSine8
easeInOutSine8()
u8 fl::easeInOutSine8 (u8 i)
8-bit sine ease-in/ease-out function Takes an input value 0-255 and returns an eased value 0-255 Smooth sinusoidal acceleration and deceleration
Definition at line 179 of file ease.cpp.hpp.
{
    // ease-in-out sine: -(cos(π*t) - 1) / 2
    // Delegate to 16-bit version for consistency and accuracy
    // Scale 8-bit input to 16-bit range, call 16-bit function, scale result back
    u16 input16 = map8_to_16(i);
    u16 result16 = easeInOutSine16(input16);
    return map16_to_8(result16);
}
References easeInOutSine16(), map16_to_8(), and map8_to_16().
Referenced by ease8(), and ease8().