FastLED: fl::generateState
generateState()
void fl::generateState (const Corkscrew::Input & input, CorkscrewState * output)
Definition at line 15 of file corkscrew.cpp.
{
    // Calculate vertical segments based on number of turns
    // For a single turn (2π), we want exactly 1 vertical segment
    // For two turns (4π), we want exactly 2 vertical segments
    // uint16_t verticalSegments = ceil(input.totalTurns);
    // Calculate width based on LED density per turn
    // float ledsPerTurn = static_cast<float>(input.numLeds) / verticalSegments;
    output->mapping.clear();
    output->width = 0; // we will change this below.
    output->height = 0;
    // If numLeds is specified, use that for mapping size instead of grid
    output->mapping.reserve(input.numLeds);
    // Generate LED mapping based on numLeds
    // Note that width_step should be 1.0f/float(input.numLeds) so last led in a
    // turn does not wrap around.
    const float width_step =
        1.0f / float(input.numLeds); // Corkscrew reaches max width on last led.
    const float height_step =
        1.0f /
        float(input.numLeds - 1); // Corkscrew reaches max height on last led.
    // const float led_width_factor = circumferencePerTurn / TWO_PI;
    const float length_per_turn = input.numLeds / input.totalTurns;
    for (uint16_t i = 0; i < input.numLeds; ++i) {
        // Calculate position along the corkscrew (0.0 to 1.0)
        const float i_f = static_cast<float>(i);
        const float alpha_width = i_f * width_step;
        const float alpha_height = i_f * height_step;
        const float width_before_mod = alpha_width * input.totalLength;
        const float height = alpha_height * input.totalHeight;
        const float width = fmodf(width_before_mod, length_per_turn);
        output->mapping.push_back({width, height});
    }
    if (!output->mapping.empty()) {
        float max_width = 0.0f;
        float max_height = 0.0f;
        for (const auto &point : output->mapping) {
            max_width = MAX(max_width, point.x);
            max_height = MAX(max_height, point.y);
        }
        output->width = static_cast<uint16_t>(ceilf(max_width)) + 1;
        output->height = static_cast<uint16_t>(ceilf(max_height)) + 1;
    }
    // Apply inversion if requested
    if (input.invert) {
        fl::reverse(output->mapping.begin(), output->mapping.end());
    }
}
References fl::CorkscrewState::height, fl::CorkscrewInput::invert, fl::CorkscrewState::mapping, MAX, fl::CorkscrewInput::numLeds, reverse(), fl::CorkscrewInput::totalHeight, fl::CorkscrewInput::totalLength, fl::CorkscrewInput::totalTurns, and fl::CorkscrewState::width.
Referenced by fl::Corkscrew::Corkscrew(), and fl::Corkscrew::generateState().