FastLED: fl::rgb_2_rgbw
rgb_2_rgbw() [1/2]
FASTLED_FORCE_INLINE void fl::rgb_2_rgbw (RGBW_MODE mode, u16 w_color_temperature, u8 r, u8 g, u8 b, u8 r_scale, u8 g_scale, u8 b_scale, u8 * out_r, u8 * out_g, u8 * out_b, u8 * out_w)
Converts RGB to RGBW using one of the functions.
Dynamic version of the rgb_w_rgbw function with less chance for the compiler to optimize.
Definition at line 317 of file rgbw.h.
{
    switch (mode) {
    case RGBW_MODE::kRGBWInvalid:
    case RGBW_MODE::kRGBWNullWhitePixel:
        rgb_2_rgbw_null_white_pixel(w_color_temperature, r, g, b, r_scale,
                                    g_scale, b_scale, out_r, out_g, out_b,
                                    out_w);
        return;
    case RGBW_MODE::kRGBWExactColors:
        rgb_2_rgbw_exact(w_color_temperature, r, g, b, r_scale, g_scale,
                         b_scale, out_r, out_g, out_b, out_w);
        return;
    case RGBW_MODE::kRGBWBoostedWhite:
        rgb_2_rgbw_white_boosted(w_color_temperature, r, g, b, r_scale, g_scale,
                                 b_scale, out_r, out_g, out_b, out_w);
        return;
    case RGBW_MODE::kRGBWMaxBrightness:
        rgb_2_rgbw_max_brightness(w_color_temperature, r, g, b, r_scale,
                                  g_scale, b_scale, out_r, out_g, out_b, out_w);
        return;
    case RGBW_MODE::kRGBWUserFunction:
        rgb_2_rgbw_user_function(w_color_temperature, r, g, b, r_scale, g_scale,
                                 b_scale, out_r, out_g, out_b, out_w);
        return;
    case RGBW_MODE::kRGBWColorimetric:
        rgb_2_rgbw_colorimetric(w_color_temperature, r, g, b, r_scale, g_scale,
                                b_scale, out_r, out_g, out_b, out_w);
        return;
    case RGBW_MODE::kRGBWColorimetricBoosted:
        rgb_2_rgbw_colorimetric_boosted(w_color_temperature, r, g, b, r_scale,
                                        g_scale, b_scale, out_r, out_g, out_b,
                                        out_w);
        return;
    }
    rgb_2_rgbw_null_white_pixel(w_color_temperature, r, g, b, r_scale, g_scale,
                                b_scale, out_r, out_g, out_b, out_w);
}
References FL_NOEXCEPT, kRGBWBoostedWhite, kRGBWColorimetric, kRGBWColorimetricBoosted, kRGBWExactColors, kRGBWInvalid, kRGBWMaxBrightness, kRGBWNullWhitePixel, kRGBWUserFunction, rgb_2_rgbw_colorimetric(), rgb_2_rgbw_colorimetric_boosted(), rgb_2_rgbw_exact(), rgb_2_rgbw_max_brightness(), rgb_2_rgbw_null_white_pixel(), rgb_2_rgbw_user_function(), and rgb_2_rgbw_white_boosted().
Referenced by PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGBW(), and rgb_2_rgbw().