FastLED: fl::parseInt
parseInt() [2/2]
int fl::parseInt (const char * str, fl::size len)
Parse an integer from a character buffer.
Parameters
str The character buffer to parse
len The length of the buffer
Returns
The parsed integer value (0 if parsing fails)
Definition at line 253 of file charconv.cpp.hpp.
{
    int result = 0;
    int sign = 1;
    fl::size pos = 0;
    // Handle empty input
    if (len == 0) {
        return 0;
    }
    // Skip leading whitespace
    while (pos < len &&
           (str[pos] == ' ' || str[pos] == '\t' || str[pos] == '\n' ||
            str[pos] == '\r' || str[pos] == '\f' || str[pos] == '\v')) {
        pos++;
    }
    // Handle optional sign
    if (pos < len && str[pos] == '-') {
        sign = -1;
        pos++;
    } else if (pos < len && str[pos] == '+') {
        pos++;
    }
    // Parse digits
    while (pos < len && str[pos] >= '0' && str[pos] <= '9') {
        result = result * 10 + (str[pos] - '0');
        pos++;
    }
    return sign * result;
}
References pos, and sign().
Referenced by fl::HttpRequestParser::feed(), fl::HttpResponseParser::feed(), fl::anonymous_namespace{json.cpp.hpp}::JsonBuilder::on_token(), fl::int_conversion_visitor< IntType >::operator()(), fl::int_conversion_visitor< i64 >::operator()(), fl::anonymous_namespace{json.cpp.hpp}::JsonBuilder::parse_float_array(), fl::anonymous_namespace{json.cpp.hpp}::JsonBuilder::parse_int_array(), parseInt(), fl::HttpResponseParser::parseStatusLine(), and fl::anonymous_namespace{json.cpp.hpp}::JsonTokenizer::scan_array_lookahead().