FastLED: fl::bilinearExpand
bilinearExpand()
void fl::bilinearExpand (const CRGB * input, CRGB * output, uint16_t inputWidth, uint16_t inputHeight, fl::XYMap xyMap) inline
Definition at line 37 of file bilinear_expansion.h.
{
    uint16_t outputWidth = xyMap.getWidth();
    uint16_t outputHeight = xyMap.getHeight();
    const bool wontFit =
        (outputWidth != xyMap.getWidth() || outputHeight != xyMap.getHeight());
    // if the input dimensions are not a power of 2 then we can't use the
    // optimized version.
    if (wontFit || (inputWidth & (inputWidth - 1)) ||
        (inputHeight & (inputHeight - 1))) {
        bilinearExpandArbitrary(input, output, inputWidth, inputHeight, xyMap);
    } else {
        bilinearExpandPowerOf2(input, output, inputWidth, inputHeight, xyMap);
    }
}
References bilinearExpandArbitrary(), bilinearExpandPowerOf2(), and xyMap.
Referenced by fl::ScaleUp::expand(), and CRGB::upscale().