FastLED: fl::make_unique
make_unique() [1/2]
template<typename T, typename... Args> fl::enable_if<!fl::is_array< T >::value, unique_ptr< T > >::type fl::make_unique (Args &&... args)
Definition at line 42 of file memory.h.
{
    return unique_ptr<T>(new T(fl::forward<Args>(args)...));
}
References args, and forward().
Referenced by fl::AudioReactive::AudioReactive(), fl::TaskImpl::TaskImpl(), and fl::FetchManager::register_promise().