FastLED: fl::async_run
async_run()
void fl::async_run ()
Run all registered async tasks once.
This function updates all registered async runners (fetch, timers, etc.) and is automatically called during:
FastLED engine events (onEndFrame)
delay() calls on WASM platforms (every 1ms)
Manual calls for custom async pumping
Note
This replaces the old fetch_update() function with a generic approach
Definition at line 63 of file async.cpp.
                 {
    fl::Scheduler::instance().update();
    AsyncManager::instance().update_all();
}
References fl::AsyncManager::instance(), fl::Scheduler::instance(), fl::Scheduler::update(), and fl::AsyncManager::update_all().
Referenced by async_yield(), fetch_update(), loop(), and fl::FetchEngineListener::onEndFrame().