FastLED: fl::hd108GammaCorrect
hd108GammaCorrect()
u16 fl::hd108GammaCorrect (u8 value) inline
Convert 8-bit color to HD108 16-bit gamma-corrected value (gamma 2.8)
Parameters
value 8-bit color value (0-255)
Returns
16-bit gamma-corrected value
Definition at line 68 of file encoder_utils.h.
{
    return Gamma28LUT16::read(value);
}
References FL_NOEXCEPT, fl::ProgmemLUT16< GammaEval16< gamma< u8x24 >(2.8f)>, 256 >::read(), and type_rank< T >::value.
Referenced by encodeHD108(), and encodeHD108_HD().