FastLED: fl::utoa64
utoa64()
int fl::utoa64 (u64 value, char * buffer, int radix)
Convert unsigned 64-bit integer to string buffer in given radix.
Parameters
value The unsigned 64-bit integer value to convert
buffer Output buffer (must be at least 65 bytes for base 2, 21 for base 10, 17 for base 16)
radix Number base (2-36, typically 10 for decimal, 16 for hex, 8 for octal)
Returns
Number of characters written (excluding null terminator)
Definition at line 162 of file charconv.cpp.hpp.
{
    char tmp[32]; // larger buffer for 64-bit values
    char *tp = tmp;
    int i;
    u64 v = value;
    while (v || tp == tmp) {
        i = v % radix;
        v = radix ? v / radix : 0;
        if (i < 10)
            *tp++ = i + '0';
        else
            *tp++ = i + 'a' - 10;
    }
    int len = tp - tmp;
    while (tp > tmp)
        *sp++ = *--tp;
    *sp = '\0';  // Null-terminate the string
    return len;
}
References type_rank< T >::value.
Referenced by append_u64_decimal(), fl::sstream::appendFormatted(), fl::sstream::appendFormatted(), fl::basic_string::appendHex(), fl::basic_string::appendOct(), ieee754_format_decimal(), fl::SerialPort::print(), and fl::SerialPort::println().