FastLED: fl::resolve_asset
resolve_asset()
fl::url fl::resolve_asset (const asset_ref & a)
Resolve an asset handle to a URL (or local file path) at runtime.
Resolution rules:
WASM: consults the build-time manifest injected as window.fastledAssetManifest (mirrored into the C++ registry by generated code from ci/compiler/asset_scanner.py).
Host/stub (FASTLED_TESTING, FL_IS_STUB): returns the file path as a fl::url if the file exists on disk. Otherwise, if a sibling <path>.lnk exists, returns the URL from the .lnk — same fallback as WASM.
Other platforms (e.g., ESP32): v1 returns an empty url(). ESP32 LittleFS / SD-card resolution is tracked as future work.
The runtime ignores any sha256= / fallback= metadata in .lnk files. These are parsed by fl::parse_lnk_with_metadata() for forward-compat and reserved for future integrity/retry features.
Declared here; defined in fl/asset/asset.cpp.hpp.
Definition at line 123 of file asset.cpp.hpp.
{
    if (!a) {
        return fl::url();
    }
    const fl::string_view p = a.path();
    // 1. Registry always wins. On WASM this is populated by generated code
    //    from the asset scanner; on host/stub tests may populate it manually.
    fl::url fromRegistry = asset_detail::lookup_registry(p);
    if (fromRegistry.isValid()) {
        return fromRegistry;
    }
    // 2. Host/stub: fall back to filesystem probe + sibling .lnk.
#if defined(FASTLED_TESTING) || defined(FL_IS_STUB)
    return asset_detail::resolve_host(p);
#else
    // 3. Other platforms (WASM without manifest, ESP32 v1): no fallback.
    //    TODO(#2284): ESP32 LittleFS / SD-card resolution.
    return fl::url();
#endif
}
References FL_NOEXCEPT, fl::url::isValid(), and fl::asset_detail::lookup_registry().
Referenced by fl::UIAudio::UIAudio().