FastLED: fl::base64_encode
base64_encode()
fl::string fl::base64_encode (fl::span< const fl::u8 > data)
Definition at line 22 of file base64.cpp.hpp.
{
    fl::string out;
    if (data.empty()) return out;
    fl::size encoded_len = 4 * ((data.size() + 2) / 3);
    out.reserve(encoded_len);
    fl::size i = 0;
    fl::size len = data.size();
    while (i + 2 < len) {
        fl::u32 triple = (fl::u32(data[i]) << 16) |
                         (fl::u32(data[i + 1]) << 8) |
                          fl::u32(data[i + 2]);
        out += kBase64Chars[(triple >> 18) & 0x3F];
        out += kBase64Chars[(triple >> 12) & 0x3F];
        out += kBase64Chars[(triple >> 6) & 0x3F];
        out += kBase64Chars[triple & 0x3F];
        i += 3;
    }
    // Handle remaining bytes
    if (i < len) {
        fl::u32 triple = fl::u32(data[i]) << 16;
        if (i + 1 < len) {
            triple |= fl::u32(data[i + 1]) << 8;
        }
        out += kBase64Chars[(triple >> 18) & 0x3F];
        out += kBase64Chars[(triple >> 12) & 0x3F];
        if (i + 1 < len) {
            out += kBase64Chars[(triple >> 6) & 0x3F];
        } else {
            out += '=';
        }
        out += '=';
    }
    return out;
}
References fl::span< T, Extent >::empty(), fl::basic_string::reserve(), and fl::span< T, Extent >::size().
Referenced by fl::detail::TypeToJson< fl::vector< fl::u8 > >::convert().