FastLED: fl::rgb_2_rgbww
rgb_2_rgbww()
FASTLED_FORCE_INLINE void fl::rgb_2_rgbww (const Rgbww & cfg, fl::u8 r, fl::u8 g, fl::u8 b, fl::u8 r_scale, fl::u8 g_scale, fl::u8 b_scale, fl::u8 * out_r, fl::u8 * out_g, fl::u8 * out_b, fl::u8 * out_ww, fl::u8 * out_wc)
Definition at line 173 of file rgbww.h.
{
    switch (cfg.rgbww_mode) {
    case RGBWW_MODE::kRGBWWInvalid:
        // Inactive: emit zeros across all five channels.
        *out_r = *out_g = *out_b = *out_ww = *out_wc = 0;
        return;
    case RGBWW_MODE::kRGBWWColorimetric:
        rgb_2_rgbww_colorimetric(cfg, r, g, b, r_scale, g_scale, b_scale,
                                 out_r, out_g, out_b, out_ww, out_wc);
        return;
    case RGBWW_MODE::kRGBWWColorimetricBoosted:
        rgb_2_rgbww_colorimetric_boosted(cfg, r, g, b, r_scale, g_scale, b_scale,
                                         out_r, out_g, out_b, out_ww, out_wc);
        return;
    case RGBWW_MODE::kRGBWWUserFunction:
        rgb_2_rgbww_user_function(cfg, r, g, b, r_scale, g_scale, b_scale,
                                  out_r, out_g, out_b, out_ww, out_wc);
        return;
    }
    *out_r = *out_g = *out_b = *out_ww = *out_wc = 0;
}
References FL_NOEXCEPT, and rgb_2_rgbww().
Referenced by PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGBWW(), and rgb_2_rgbww().