FastLED: fl::operator<
operator<() [4/8]
template<typename Key, typename Less> bool fl::operator< (const flat_set< Key, Less > & lhs, const flat_set< Key, Less > & rhs)
Definition at line 339 of file flat_set.h.
{
    return fl::lexicographical_compare(lhs.begin(), lhs.end(),
                                       rhs.begin(), rhs.end());
}
References fl::flat_set< Key, Less >::begin(), fl::flat_set< Key, Less >::end(), and lexicographical_compare().