FastLED: fl::readLine
readLine()
fl::optional< fl::string > fl::readLine (char delimiter, char skipChar, fl::optional< u32 > timeoutMs)
Definition at line 185 of file cstdio.cpp.hpp.
{
    // Try platform-native line reading first (e.g., Arduino's Serial.readStringUntil).
    // This is critical for USB CDC platforms (ESP32-C6/S3) where the native
    // implementation uses yield() (immediate context switch) instead of
    // delay(1) (1ms FreeRTOS sleep), enabling correct multi-packet assembly.
    char nativeBuf[512];
    int nativeLen = platforms::readLineNative(delimiter, nativeBuf, sizeof(nativeBuf));
    if (nativeLen >= 0) {
        fl::string result(nativeBuf, nativeLen);
        return fl::string(result.trim());
    }
    // Fallback: character-by-character reading for non-Arduino platforms
    sstream buffer;
    if (!readStringUntil(buffer, delimiter, skipChar, timeoutMs)) {
        return fl::nullopt;  // Timeout occurred
    }
    // Convert to string and trim whitespace (trim() returns a new fl::string)
    fl::string result = buffer.str();
    return fl::string(result.trim());
}
References nullopt, readStringUntil(), and fl::sstream::str().
Referenced by createSerialRequestSource(), and readSerialLine().