FastLED: fl::splat
splat()
Tile2x2_u8 fl::splat (vec2f xy)
"Splat" as in "splat pixel rendering" takes a pixel value in float x,y coordinates and "splats" it into a 2x2 tile of pixel values.
Each of the four pixels in the tile is a uint8_t value in the range [0..255] that represents the intensity of the pixel at that point. Tile2x2_u8 splat(vec2f xy);
Definition at line 14 of file splat.cpp.
{
    // 1) collect values.
    float x = xy.x;
    float y = xy.y;
    // 2) integer cell indices
    int16_t cx = static_cast<int16_t>(floorf(x));
    int16_t cy = static_cast<int16_t>(floorf(y));
    // 3) fractional offsets in [0..1)
    float fx = x - cx;
    float fy = y - cy;
    // 4) bilinear weights
    float w_ll = (1 - fx) * (1 - fy); // lower‑left
    float w_lr = fx * (1 - fy);       // lower‑right
    float w_ul = (1 - fx) * fy;       // upper‑left
    float w_ur = fx * fy;             // upper‑right
    // 5) build Tile2x2_u8 anchored at (cx,cy)
    Tile2x2_u8 out(vec2<int16_t>(cx, cy));
    out.lower_left() = to_uint8(w_ll);
    out.lower_right() = to_uint8(w_lr);
    out.upper_left() = to_uint8(w_ul);
    out.upper_right() = to_uint8(w_ur);
    return out;
}
References fl::Tile2x2_u8::lower_left(), fl::Tile2x2_u8::lower_right(), to_uint8(), fl::Tile2x2_u8::upper_left(), fl::Tile2x2_u8::upper_right(), x, xy(), and y.
Referenced by fl::Corkscrew::at_splat_extrapolate(), and fl::XYPathRenderer::at_subpixel().