FastLED: fl::sampleNearest
sampleNearest()
CRGB fl::sampleNearest (const CRGB * grid, const XYMap & xyMap, float x, float y)
Nearest-neighbor sample from a 2D CRGB grid.
Definition at line 42 of file sample.cpp.hpp.
{
    int xi = static_cast<int>(x + 0.5f); // Round to nearest
    int yi = static_cast<int>(y + 0.5f);
    xi = max(0, min(xi, static_cast<int>(xyMap.getWidth()) - 1));
    yi = max(0, min(yi, static_cast<int>(xyMap.getHeight()) - 1));
    return grid[xyMap.mapToIndex(xi, yi)];
}
References max(), min(), x, xyMap, and y.
Referenced by sample().