FastLED: fl::MurmurHash3_x86_32
MurmurHash3_x86_32()
static u32 fl::MurmurHash3_x86_32 (const void * key, fl::size len, u32 seed = 0) inline static
Definition at line 23 of file hash.h.
{
    FL_DISABLE_WARNING_PUSH;
    FL_DISABLE_WARNING_IMPLICIT_FALLTHROUGH;
    const fl::u8 *data = static_cast<const fl::u8 *>(key);
    const int nblocks = int(len / 4);
    u32 h1 = seed;
    const u32 c1 = 0xcc9e2d51;
    const u32 c2 = 0x1b873593;
    // body
    const u32 *blocks = reinterpret_cast<const u32 *>(data);
    for (int i = 0; i < nblocks; ++i) {
        u32 k1 = blocks[i];
        k1 *= c1;
        k1 = (k1 << 15) | (k1 >> 17);
        k1 *= c2;
        h1 ^= k1;
        h1 = (h1 << 13) | (h1 >> 19);
        h1 = h1 * 5 + 0xe6546b64;
    }
    // tail
    const fl::u8 *tail = data + (nblocks * 4);
    u32 k1 = 0;
    switch (len & 3) {
    case 3:
        k1 ^= u32(tail[2]) << 16;
    case 2:
        k1 ^= u32(tail[1]) << 8;
    case 1:
        k1 ^= u32(tail[0]);
        k1 *= c1;
        k1 = (k1 << 15) | (k1 >> 17);
        k1 *= c2;
        h1 ^= k1;
    }
    // finalization
    h1 ^= u32(len);
    // fmix32
    h1 ^= h1 >> 16;
    h1 *= 0x85ebca6b;
    h1 ^= h1 >> 13;
    h1 *= 0xc2b2ae35;
    h1 ^= h1 >> 16;
    return h1;
    FL_DISABLE_WARNING_POP;
}
References FL_DISABLE_WARNING_POP, and FL_DISABLE_WARNING_PUSH.
Referenced by fl::FastHash< vec2< T > >::operator()(), fl::Hash< double >::operator()(), fl::Hash< FFT_Args >::operator()(), fl::Hash< fl::string >::operator()(), fl::Hash< fl::WeakPtr< T > >::operator()(), fl::Hash< Key >::operator()(), fl::Hash< T * >::operator()(), and fl::Hash< vec2< T > >::operator()().