FastLED: fl::pow_impl_double
pow_impl_double()
double fl::pow_impl_double (double base, double exponent)
Definition at line 338 of file math.cpp.hpp.
{
#if FL_MATH_USE_LIBM
    return ::pow(base, exponent);
#else
    if (exponent == 0.0) return 1.0;
    int ie = static_cast<int>(exponent);
    if (static_cast<double>(ie) == exponent && ie >= -8 && ie <= 8) {
        double r = 1.0;
        if (ie > 0)  { for (int i = 0; i < ie; ++i) r *= base; return r; }
        if (ie < 0)  { for (int i = 0; i < -ie; ++i) r *= base; return 1.0 / r; }
    }
    if (base <= 0.0) return 0.0;
    return exp_impl_double(exponent * detail::log_natural_<double>(base));
#endif
}
References exp_impl_double(), and fl::detail::log_natural_().
Referenced by pow().