FastLED: fl::itoa
itoa()
int fl::itoa (i32 value, char * buffer, int radix)
Convert signed 32-bit integer to string buffer in given radix.
Parameters
value The integer value to convert
buffer Output buffer (must be at least 34 bytes for base 2, 12 for base 10, 12 for base 16)
radix Number base (2-36, typically 10 for decimal, 16 for hex, 8 for octal)
Returns
Number of characters written (excluding null terminator)
Definition at line 68 of file charconv.cpp.hpp.
{
    char tmp[16]; // be careful with the length of the buffer
    char *tp = tmp;
    int i;
    u32 v;
    int sign = (radix == 10 && value < 0);
    if (sign)
        v = -static_cast<u32>(value);
    else
        v = static_cast<u32>(value);
    while (v || tp == tmp) {
        i = v % radix;
        v = radix ? v / radix : 0;
        if (i < 10)
            *tp++ = i + '0';
        else
            *tp++ = i + 'a' - 10;
    }
    int len = tp - tmp;
    if (sign) {
        *sp++ = '-';
        len++;
    }
    while (tp > tmp)
        *sp++ = *--tp;
    *sp = '\0';  // Null-terminate the string
    return len;
}
References sign(), and type_rank< T >::value.
Referenced by fl::sstream::appendFormatted(), fl::basic_string::appendHex(), fl::basic_string::appendOct(), fl::ostream::operator<<(), fl::ostream::operator<<(), fl::ostream::operator<<(), fl::SerialPort::print(), fl::SerialPort::println(), fl::basic_string::write(), and fl::basic_string::write().