FastLED: fl::five_bit_bitshift
five_bit_bitshift()
uint8_t fl::five_bit_bitshift (uint16_t r16, uint16_t g16, uint16_t b16, uint8_t brightness, CRGB * out, uint8_t * out_power_5bit)
Definition at line 73 of file five_bit_hd_gamma.cpp.
{
    if (brightness == 0) {
        *out = CRGB(0, 0, 0);
        *out_power_5bit = 0;
        return 0;
    }
    if (r16 == 0 && g16 == 0 && b16 == 0) {
        *out = CRGB(0, 0, 0);
        *out_power_5bit = (brightness <= 31) ? brightness : 31;
        return brightness;
    }
    // Note: One day someone smarter than me will come along and invent a closed
    // form solution for this. However, the numerical method works extremely
    // well and has been optimized to avoid division performance penalties as
    // much as possible.
    // Step 1: Initialize brightness
    static const uint8_t kStartBrightness = 0b00010000;
    uint8_t v5 = kStartBrightness;
    // Step 2: Boost brightness by swapping power with the driver brightness.
    brightness_bitshifter8(&v5, &brightness, 4);
    // Step 3: Boost brightness of the color channels by swapping power with the
    // driver brightness.
    uint16_t max_component = max3(r16, g16, b16);
    // five_bit_color_bitshift(&r16, &g16, &b16, &v5);
    uint8_t shifts = brightness_bitshifter16(&v5, &max_component, 4, 2);
    if (shifts) {
        r16 = r16 << shifts;
        g16 = g16 << shifts;
        b16 = b16 << shifts;
    }
    // Step 4: scale by final brightness factor.
    if (brightness != 0xff) {
        r16 = scale16by8(r16, brightness);
        g16 = scale16by8(g16, brightness);
        b16 = scale16by8(b16, brightness);
    }
    // brighten hardware brightness by turning on low order bits
    if (v5 > 1) {
        // since v5 is a power of two, subtracting one will invert the leading bit
        // and invert all the bits below it.
        // Example: 0b00010000 -1 = 0b00001111
        // So 0b00010000 | 0b00001111 = 0b00011111
        v5 = v5 | (v5 - 1);
    }
    // Step 5: Convert back to 8-bit and output.
    *out = CRGB(map16_to_8(r16), map16_to_8(g16), map16_to_8(b16));
    *out_power_5bit = v5;
    return brightness;
}
References brightness, brightness_bitshifter16(), brightness_bitshifter8(), map16_to_8(), and scale16by8().
Referenced by __builtin_five_bit_hd_gamma_bitshift().