FastLED: fl::upscale
upscale()
void fl::upscale (const CRGB * input, CRGB * output, u16 inputWidth, u16 inputHeight, const fl::XYMap & xyMap) inline
Definition at line 58 of file upscale.h.
{
    u16 outputWidth = xyMap.getWidth();
    u16 outputHeight = xyMap.getHeight();
    const bool wontFit =
        (outputWidth != xyMap.getWidth() || outputHeight != xyMap.getHeight());
    // Check if we can use the optimized rectangular version
    const bool isRectangular = (xyMap.getType() == XYMap::kLineByLine);
    if (isRectangular) {
        // Use optimized rectangular version that bypasses XY mapping
        if (wontFit || (inputWidth & (inputWidth - 1)) ||
            (inputHeight & (inputHeight - 1))) {
            upscaleRectangular(input, output, inputWidth, inputHeight,
                              outputWidth, outputHeight);
        } else {
            upscaleRectangularPowerOf2(input, output, inputWidth, inputHeight,
                                      outputWidth, outputHeight);
        }
    } else {
        // Use the original XY-mapped versions
    if (wontFit || (inputWidth & (inputWidth - 1)) ||
        (inputHeight & (inputHeight - 1))) {
        upscaleArbitrary(input, output, inputWidth, inputHeight, xyMap);
    } else {
        upscalePowerOf2(input, output, inputWidth, inputHeight, xyMap);
        }
    }
}
References fl::XYMap::kLineByLine, upscaleArbitrary(), upscalePowerOf2(), upscaleRectangular(), upscaleRectangularPowerOf2(), and xyMap.
Referenced by fl::ScaleUp::expand(), and CRGB::upscale().