FastLED: fl::t
t
fl::t = (x ^ (x >> 7)) & 0x00AA00AA
Definition at line 27 of file transposition.cpp.hpp.
Referenced by fl::AutoResearchConfig::AutoResearchConfig(), fl::audio::detector::Chord::Chord(), fl::Rpc::Config< Callable >::Config(), fl::RedBlackTree< T, Compare, Allocator >::const_iterator::const_iterator(), fl::RedBlackTree< T, Compare, Allocator >::const_reverse_iterator::const_reverse_iterator(), fl::printf_detail::FormatSpec::FormatSpec(), fl::printf_detail::FormatSpec::FormatSpec(), fl::RedBlackTree< T, Compare, Allocator >::iterator::iterator(), fl::RedBlackTree< T, Compare, Allocator >::reverse_iterator::reverse_iterator(), fl::tuple< Head, Tail... >::tuple(), fl::tuple< Head, Tail... >::tuple(), fl::task::Scheduler::add_task(), fl::task::after_frame(), fl::task::after_frame(), fl::Corkscrew::at_splat_extrapolate(), fl::fixed_point_base< Derived, IntBits, FracBits >::atan_unit(), fl::s12x4::atan_unit(), fl::s16x16::atan_unit(), fl::s24x8::atan_unit(), fl::s4x12::atan_unit(), fl::s8x24::atan_unit(), fl::s8x8::atan_unit(), fl::colorimetric_detail::barycentric_xy(), fl::filebuf::bytes_left(), fl::Engine::calculate_oscillators(), fl::CatmullRomPath::compute(), fl::CirclePath::compute(), fl::HeartPath::compute(), fl::audio::detector::ChordDetector::detectChord(), fl::line_xy< T >::distance_to_line_with_point(), fl::FlowFieldFloat::drawAALine(), fl::FlowFieldFP::drawAALine(), fl::FlowFieldFloat::drawFlowVectors(), fl::FlowFieldFP::drawFlowVectors(), fl::FlowFieldFloat::drawImpl(), fl::FlowFieldFP::drawImpl(), easeInOutQuad8(), fl::FlowFieldFloat::emitLissajousLine(), fl::FlowFieldFP::emitLissajousLine(), fl::FlowFieldFloat::emitOrbitalDots(), fl::FlowFieldFP::emitOrbitalDots(), fade(), fl::FlowFieldFloat::Perlin2D::fade(), fl::perlin_i16_optimized::fade(), fl::perlin_q16::fade(), fl::perlin_s16x16::fade(), fl::perlin_s8x8::fade(), fast_logf_approx(), fl::audio::fft::Context::fastDb(), fill_gradient(), fill_gradient_RGB(), fl::FlowFieldFloat::flowPrepare(), fl::FlowFieldFP::flowPrepare(), fmod_impl_double(), fmod_impl_float(), forward(), forward(), get(), get(), get(), fl::colorimetric_detail::hermite_basis(), fl::third_party::hexwave::hexwave_generate_linesegs(), fl::third_party::hexwave::hexwave_generate_samples(), fl::third_party::IMDCT36(), fl::perlin_i16_optimized::init_fade_lut(), fl::perlin_q16::init_fade_lut(), fl::perlin_s16x16::init_fade_lut(), fl::perlin_s8x8::init_fade_lut(), fl::Tile2x2_u8_wrap::Interpolate(), fl::CatmullRomPath::interpolate(), fl::gfx::detail::isqrt32_floor(), fl::fixed_point< IntBits, FracBits, Sign::SIGNED >< IntBits, FracBits >::lerp(), fl::fixed_point_base< Derived, IntBits, FracBits >::lerp(), fl::FlowFieldFloat::Perlin2D::lerp(), lerp(), lerp(), fl::perlin_i16_optimized::lerp(), fl::perlin_q16::lerp(), fl::perlin_s16x16::lerp(), fl::perlin_s8x8::lerp(), fl::s12x4::lerp(), fl::s16x16::lerp(), fl::s16x16x4::lerp(), fl::s24x8::lerp(), fl::s4x12::lerp(), fl::s8x24::lerp(), fl::s8x8::lerp(), fl::u12x4::lerp(), fl::u16x16::lerp(), fl::u24x8::lerp(), fl::u4x12::lerp(), fl::u8x24::lerp(), fl::u8x8::lerp(), fl::fixed_point_base< Derived, IntBits, FracBits >::log2_fp(), fl::s12x4::log2_fp(), fl::s16x16::log2_fp(), fl::s24x8::log2_fp(), fl::s4x12::log2_fp(), fl::s8x24::log2_fp(), fl::s8x8::log2_fp(), fl::u12x4::log2_fp(), fl::u16x16::log2_fp(), fl::u24x8::log2_fp(), fl::u4x12::log2_fp(), fl::u8x24::log2_fp(), fl::u8x8::log2_fp(), fl::detail::gamma_constexpr::log2_h0(), fl::detail::gamma_constexpr::log2_h1(), fl::detail::gamma_constexpr::log2_h2(), fl::detail::gamma_constexpr::log2_h3(), make_pair(), move(), fl::colorimetric_detail::nnls3(), fl::alpha16::operator++(), fl::alpha8::operator++(), fl::unordered_map_small< Key, Value, Equal >::const_iterator::operator++(), fl::unordered_map_small< Key, Value, Equal >::iterator::operator++(), fl::alpha16::operator--(), fl::alpha8::operator--(), fl::third_party::plm_video_decode_macroblock(), fl::detail::qsort_swap(), fl::FlowFieldFloat::rainbow(), fl::FlowFieldFP::rainbow(), fl::PerlinParticlePunch::renderMeteor(), fl::colorimetric_detail::rgbcct_eta_for_cct(), fl::circular_buffer_core< T >::setTail(), fl::Engine::setTime(), setTime(), sin32(), sin32_interp(), sincos32(), fl::fixed_point_base< Derived, IntBits, FracBits >::smoothstep(), fl::s12x4::smoothstep(), fl::s16x16::smoothstep(), fl::s24x8::smoothstep(), fl::s4x12::smoothstep(), fl::s8x24::smoothstep(), fl::s8x8::smoothstep(), fl::u12x4::smoothstep(), fl::u16x16::smoothstep(), fl::u24x8::smoothstep(), fl::u4x12::smoothstep(), fl::u8x24::smoothstep(), fl::u8x8::smoothstep(), fl::PerlinParticlePunch::spawnDebrisFromMeteor(), fl::third_party::truetype::stbtt__get_svg(), fl::third_party::truetype::stbtt__sort_edges_ins_sort(), fl::third_party::truetype::stbtt__sort_edges_quicksort(), fl::third_party::truetype::stbtt_GetGlyphSDF(), fl::third_party::truetype::stbtt_InitFont_internal(), fl::detail::MethodBuilder< Sig >::tags(), transpose8(), transpose8x1(), transpose8x1_MSB(), transpose_wave8byte_parlio_template(), traverseGridSegmentFloat(), fl::NoiseBias1D::trigger(), fl::task::Scheduler::update(), and fl::task::Scheduler::update_tasks_of_type().