FastLED: fl::get
get() [7/12]
template<fl::size I, typename T1, typename T2> pair_element< I, T1, T2 >::type & fl::get (pair< T1, T2 > & p) noexcept
Definition at line 113 of file pair.h.
{
    static_assert(I < 2, "Index out of bounds for pair");
    if (I == 0) {
        return p.first;
    } else {
        return p.second;
    }
}
Referenced by fl::Corkscrew::clear(), fl::Corkscrew::data(), fl::result< T >::error(), get(), get(), get(), fl::anonymous_namespace{task.cpp}::make_trace_label(), fl::Corkscrew::pixelCount(), fl::Corkscrew::rawData(), fl::result< T >::value(), fl::result< T >::value(), and fl::Ptr< T >::weakRefNoCreate().