FastLED: fl::set_input_gamut
set_input_gamut() [2/2]
void fl::set_input_gamut (DiodeProfile * profile, InputGamut g, const float white_xy[2])
Definition at line 242 of file rgbw.cpp.hpp.
{
    if (profile == nullptr) return;
    auto apply = [profile](const float r[2], const float gp[2],
                           const float b[2], const float w[2]) {
        profile->input_xy_r[0] = r[0];  profile->input_xy_r[1] = r[1];
        profile->input_xy_g[0] = gp[0]; profile->input_xy_g[1] = gp[1];
        profile->input_xy_b[0] = b[0];  profile->input_xy_b[1] = b[1];
        profile->input_xy_w[0] = w[0];  profile->input_xy_w[1] = w[1];
    };
    switch (g) {
    case InputGamut::Native: {
        // For Native, the input gamut tracks this profile's LED primaries —
        // copy them over rather than picking a fixed sRGB-like fallback.
        const float d65[2] = {0.31272f, 0.32903f};
        const float* w = (white_xy != nullptr) ? white_xy : d65;
        apply(profile->xy_r, profile->xy_g, profile->xy_b, w);
        invalidate_colorimetric_caches_for(profile);
        return;
    }
    case InputGamut::Rec709:   apply(kRec709.xy_r,   kRec709.xy_g,   kRec709.xy_b,
                                     white_xy != nullptr ? white_xy : kRec709.xy_w);
                                invalidate_colorimetric_caches_for(profile);   return;
    case InputGamut::Rec2020:  apply(kRec2020.xy_r,  kRec2020.xy_g,  kRec2020.xy_b,
                                     white_xy != nullptr ? white_xy : kRec2020.xy_w);
                                invalidate_colorimetric_caches_for(profile);  return;
    case InputGamut::DciP3D65: apply(kDciP3D65.xy_r, kDciP3D65.xy_g, kDciP3D65.xy_b,
                                     white_xy != nullptr ? white_xy : kDciP3D65.xy_w);
                                invalidate_colorimetric_caches_for(profile); return;
    case InputGamut::DciP3D60: apply(kDciP3D60.xy_r, kDciP3D60.xy_g, kDciP3D60.xy_b,
                                     white_xy != nullptr ? white_xy : kDciP3D60.xy_w);
                                invalidate_colorimetric_caches_for(profile); return;
    }
    // Default-fallthrough for forward-compat with future enum additions:
    // leave the profile's input_xy_* untouched — also nothing to invalidate.
}
References DciP3D60, DciP3D65, FL_NOEXCEPT, Native, Rec2020, Rec709, fl::anonymous_namespace{rgbw.cpp.hpp}::NamedGamut::xy_b, fl::anonymous_namespace{rgbw.cpp.hpp}::NamedGamut::xy_g, fl::anonymous_namespace{rgbw.cpp.hpp}::NamedGamut::xy_r, and fl::anonymous_namespace{rgbw.cpp.hpp}::NamedGamut::xy_w.
Referenced by set_input_gamut(), CFastLED::setInputGamut(), and CFastLED::setInputGamut().