FastLED: fl::execute_fetch_request
execute_fetch_request()
fl::promise< response > fl::execute_fetch_request (const fl::string & url, const fetch_options & request)
Internal helper to execute a fetch request and return a promise.
Definition at line 72 of file fetch.cpp.
{
    (void)request; // Unused in stub implementation
    FL_WARN("HTTP fetch is not supported on non-WASM platforms. URL: " << url);
    // Create error response
    response error_response(501, "Not Implemented");
    error_response.set_body("HTTP fetch is only available in WASM/browser builds. This platform does not support network requests.");
    // Create resolved promise with error response
    auto promise = fl::promise<response>::resolve(error_response);
    return promise;
}
References FL_WARN, fl::promise< T >::resolve(), and fl::response::set_body().
Referenced by fetch_delete(), fetch_get(), fetch_head(), fetch_http_options(), fetch_patch(), fetch_post(), fetch_put(), and fetch_request().