FastLED: fl::printf
printf()
template<typename... Args> void fl::printf (const char * format, const Args &... args)
Printf-like formatting function that prints directly to the platform output.
Parameters
format Format string with placeholders like "%d", "%s", "%f" etc.
args Arguments to format
Supported format specifiers:
d, i: integers (all integral types)
u: unsigned integers
f: floating point numbers
s: strings (const char*, fl::string)
c: characters
x: hexadecimal (lowercase)
X: hexadecimal (uppercase)
%%: literal % character
Example usage:
fl::printf("Value: %d, Name: %s", 42, "test");
fl::printf("Float: %.2f", 3.14159);
Definition at line 393 of file printf.h.
{
    StrStream stream;
    printf_detail::format_impl(stream, format, args...);
    fl::print(stream.str().c_str());
}
References args, fl::StrN< SIZE >::c_str(), fl::printf_detail::format_impl(), print(), and fl::StrStream::str().