FastLED: fl::init
init()
void fl::init (Context & ctx, int w, int h) inline
Definition at line 133 of file engine.h.
{
    if (!ctx.mEngine) {
        ctx.mEngine = fl::make_unique<Engine>(&ctx);
    }
    ctx.num_x = w;
    ctx.num_y = h;
    ctx.mEngine->init(w, h);
}
References init().
Referenced by fl::deque< int >::deque(), fl::FixedVector< fl::u32, kMaxBatchSize >::FixedVector(), fl::list< T >::list(), fl::MapRedBlackTree< Key, T, Compare, fl::allocator_slab< char > >< Key, T, Compare >::MapRedBlackTree(), fl::MultiMapTree< Key, T, Compare, fl::allocator_slab< char > >::MultiMapTree(), fl::MultiSetTree< Key, Compare, fl::allocator_slab< char > >::MultiSetTree(), fl::set< T, fl::allocator_inlined_slab< T, N > >::set(), fl::span< T, dynamic_extent >::span(), fl::vector< fl::i16 >::vector(), fl::vector_psram< T >::vector_psram(), fl::VectorN< T, INLINED_SIZE >::VectorN(), fl::Animartrix::draw(), init(), fl::iterator<, u8 >::insert(), fl::iterator<, u8 >::operator=(), fl::set< T, fl::allocator_inlined_slab< T, N > >::operator=(), and fl::iterator<, u8 >::unordered_map().