FastLED: fl::abs
abs() [3/3]
template<typename T> enable_if< is_fixed_point< T >::value, T >::type fl::abs (T x) inline constexpr
Definition at line 525 of file fixed_point.h.
{ return T::abs(x); }
References FL_NOEXCEPT, and x.
Referenced by almost_equal(), almost_equal(), almost_equal(), fl::audio::detector::MusicalBeat::calculateBeatConfidence(), fl::audio::detector::Vocal::calculateRawConfidence(), fl::audio::detector::DropDetector::calculateSpectralNovelty(), fl::XYPath::calculateSteps(), fl::audio::detector::Percussion::computeConfidences(), fl::audio::detector::Vocal::computePCMTimeDomainFeatures(), fl::audio::detector::Downbeat::detectDownbeat(), fl::third_party::vorbis::draw_line(), fl::gfx::detail::drawLineCore(), fl::audio::detector::Mood::getCategory(), MaxFadeTracker::operator()(), fl::third_party::plm_video_decode_motion_vector(), fl::third_party::vorbis::predict_point(), fl::audio::AutoGain::process(), fl::WaveSimulation2D::seti16(), fl::audio::detector::Pitch::shouldReportPitchChange(), fl::audio::detector::Note::shouldTriggerNoteChange(), CPixelView< CRGB >::size(), traverseGridSegment(), traverseGridSegment16(), traverseGridSegment32(), traverseGridSegmentFloat(), fl::audio::detector::TempoAnalyzer::update(), fl::detail::HampelFilterImpl< T, N >::update(), fl::detail::OneEuroFilterImpl< T >::update(), fl::audio::detector::TempoAnalyzer::updateHypotheses(), fl::audio::AutoGain::updatePIController(), and fl::audio::detector::Beat::updateTempo().