FastLED: fl::traverseGridSegment32
traverseGridSegment32()
template<typename GridVisitor> void fl::traverseGridSegment32 (const vec2f & start, const vec2f & end, GridVisitor & visitor)
Template Parameters
GridVisitor
Parameters
start start point
end end point
visitor called for each cell visited.
UNTESTED!!!!
Definition at line 207 of file traverse_grid.h.
{
    const i32 FP_SHIFT = 8;
    const i32 FP_ONE = 1 << FP_SHIFT;
    // const i32 FP_MASK = FP_ONE - 1;
    // Convert to fixed-point (Q24.8) signed
    i32 startX_fp = static_cast<i32>(start.x * FP_ONE);
    i32 startY_fp = static_cast<i32>(start.y * FP_ONE);
    i32 endX_fp = static_cast<i32>(end.x * FP_ONE);
    i32 endY_fp = static_cast<i32>(end.y * FP_ONE);
    i32 x0 = startX_fp >> FP_SHIFT;
    i32 y0 = startY_fp >> FP_SHIFT;
    i32 x1 = endX_fp >> FP_SHIFT;
    i32 y1 = endY_fp >> FP_SHIFT;
    i32 stepX = (x1 > x0) ? 1 : (x1 < x0) ? -1 : 0;
    i32 stepY = (y1 > y0) ? 1 : (y1 < y0) ? -1 : 0;
    i32 deltaX_fp = endX_fp - startX_fp;
    i32 deltaY_fp = endY_fp - startY_fp;
    // Use (max)() to prevent macro expansion by Arduino.h's max macro
    u32 absDeltaX_fp =
        (deltaX_fp != 0) ? static_cast<u32>(
                               fl::abs((fl::i64(FP_ONE) << FP_SHIFT) / deltaX_fp))
                         : (fl::numeric_limits<u32>::max)();
    u32 absDeltaY_fp =
        (deltaY_fp != 0) ? static_cast<u32>(
                               fl::abs((fl::i64(FP_ONE) << FP_SHIFT) / deltaY_fp))
                         : (fl::numeric_limits<u32>::max)();
    i32 nextX_fp = (stepX > 0) ? ((x0 + 1) << FP_SHIFT) : (x0 << FP_SHIFT);
    i32 nextY_fp = (stepY > 0) ? ((y0 + 1) << FP_SHIFT) : (y0 << FP_SHIFT);
    // Use (max)() to prevent macro expansion by Arduino.h's max macro
    u32 tMaxX_fp =
        (deltaX_fp != 0)
            ? static_cast<u32>(
                  fl::abs(fl::i64(nextX_fp - startX_fp)) * absDeltaX_fp >> FP_SHIFT)
            : (fl::numeric_limits<u32>::max)();
    u32 tMaxY_fp =
        (deltaY_fp != 0)
            ? static_cast<u32>(
                  fl::abs(fl::i64(nextY_fp - startY_fp)) * absDeltaY_fp >> FP_SHIFT)
            : (fl::numeric_limits<u32>::max)();
    const u32 maxT_fp = FP_ONE;
    i32 currentX = x0;
    i32 currentY = y0;
    while (true) {
        visitor.visit(currentX, currentY);
        u32 t_fp = (tMaxX_fp < tMaxY_fp) ? tMaxX_fp : tMaxY_fp;
        if (t_fp > maxT_fp)
            break;
        if (tMaxX_fp < tMaxY_fp) {
            tMaxX_fp += absDeltaX_fp;
            currentX += stepX;
        } else {
            tMaxY_fp += absDeltaY_fp;
            currentY += stepY;
        }
    }
    if (currentX != x1 || currentY != y1) {
        visitor.visit(x1, y1);
    }
}
References abs(), end(), FP_ONE, fl::numeric_limits< T >::max(), fl::vec2< T >::x, and fl::vec2< T >::y.
Referenced by traverseGridSegment().