FastLED: fl::traverseGridSegment
traverseGridSegment()
template<typename GridVisitor> void fl::traverseGridSegment (const vec2f & start, const vec2f & end, GridVisitor & visitor) inline
Traverse a grid segment by selecting the cells that are crossed.
This version will select the fastest integer implementation based on the length of the segment. Most of the time it will call traverseGridSegment16() since segment spans are typically < 256 pixels.
Template Parameters
GridVisitor
Parameters
start start point
end end point
visitor called for each cell visited.
Fully tested.
Definition at line 282 of file traverse_grid.h.
{
    float dx = fl::abs(end.x - start.x);
    float dy = fl::abs(end.y - start.y);
    float maxRange = fl::max(dx, dy);
    // if (maxRange < 256.0f) {
    //     // Use Q8.8 (16-bit signed) if within ±127
    //     traverseGridSegment16(start, end, visitor);
    // }
    // else if (maxRange < 16777216.0f) {
    //     // Use Q24.8 (32-bit signed) if within ±8 million
    //     traverseGridSegment32(start, end, visitor);
    // }
    // else {
    //     // Fall back to floating-point
    //     traverseGridSegment(start, end, visitor);
    // }
    if (maxRange < 256.0f) {
        // Use Q8.8 (16-bit signed) if within ±127
        traverseGridSegment16(start, end, visitor);
    } else {
        // Use Q24.8 (32-bit signed) if within ±8 million
        traverseGridSegment32(start, end, visitor);
    }
}
References abs(), end(), max(), traverseGridSegment16(), traverseGridSegment32(), fl::vec2< T >::x, and fl::vec2< T >::y.