FastLED: makeRingScreenMap
makeRingScreenMap()
fl::ScreenMap makeRingScreenMap (int numLeds, int gridWidth, int gridHeight, float diameter)
Definition at line 10 of file ring_screenmap.cpp.
{
    return fl::ScreenMap(numLeds, diameter, [=](int index, fl::vec2f &pt_out) {
        float centerX = gridWidth / 2.0f;
        float centerY = gridHeight / 2.0f;
        float radius = fl::min(gridWidth, gridHeight) / 2.0f - 1;
        float angle = (TWO_PI * index) / numLeds;
        pt_out.x = centerX + fl::cos(angle) * radius;
        pt_out.y = centerY + fl::sin(angle) * radius;
    });
}
References fl::cos(), fl::min(), fl::sin(), TWO_PI, fl::vec2< T >::x, and fl::vec2< T >::y.