FastLED: pacifica_add_whitecaps
pacifica_add_whitecaps()
void pacifica_add_whitecaps ()
Examples
Pacifica.ino.
Definition at line 131 of file Pacifica.ino.
{
  uint8_t basethreshold = beatsin8( 9, 55, 65);
  uint8_t wave = beat8( 7 );
  for( uint16_t i = 0; i < NUM_LEDS; i++) {
    uint8_t threshold = scale8( sin8( wave), 20) + basethreshold;
    wave += 7;
    uint8_t l = leds[i].getAverageLight();
    if( l > threshold) {
      uint8_t overage = l - threshold;
      uint8_t overage2 = qadd8( overage, overage);
      leds[i] += CRGB( overage, overage2, qadd8( overage2, overage2));
    }
  }
}
References beat8(), beatsin8(), leds, NUM_LEDS, qadd8(), scale8(), and sin8.
Referenced by fl::Pacifica::draw(), and pacifica_loop().