FastLED: fl::map8_to_16
map8_to_16()
u16 fl::map8_to_16 (u8 x) inline
Deprecated
Use int_scale<uint8_t, uint16_t>() instead
Examples
/home/runner/work/FastLED/FastLED/src/fl/math/intmap.h.
Definition at line 48 of file intmap.h.
{
    return fl::int_scale<u8, u16>(x);
}
References FL_NOEXCEPT, and x.
Referenced by fl::detail::ScaledPixelIteratorRGB16::advance(), easeInOutSine8(), and easeOutSine8().