FastLED: drawSpectrumBars
drawSpectrumBars()
void drawSpectrumBars (fl::audio::fft::Bins * fft, float)
Definition at line 182 of file advanced.h.
{
    clearDisplay();
    fl::CRGBPalette16 palette = getCurrentPalette();
    int barWidth = WIDTH / NUM_BANDS;
    auto bands = fft->db();
    for (size_t band = 0; band < NUM_BANDS && band < bands.size(); band++) {
        float magnitude = bands[band];
        // Apply noise floor
        magnitude = magnitude / 100.0f;  // Normalize from dB
        magnitude = fl::max(0.0f, magnitude - noiseFloor.value());
        // Smooth the FFT
        fftSmooth[band] = fftSmooth[band] * 0.8f + magnitude * 0.2f;
        magnitude = fftSmooth[band];
        // Apply gain
        magnitude *= audioGain.value() * autoGainValue;
        magnitude = fl::clamp(magnitude, 0.0f, 1.0f);
        int barHeight = magnitude * HEIGHT;
        int xStart = band * barWidth;
        for (int x = 0; x < fl::max(barWidth, 1); x++) {
            for (int y = 0; y < barHeight; y++) {
                uint8_t colorIndex = fl::map_range<float, uint8_t>(
                    float(y) / HEIGHT, 0, 1, 0, 255
                );
                fl::CRGB color = ColorFromPalette(palette, colorIndex + hue);
                int ledIndex = xyMap(xStart + x, y);
                if (ledIndex >= 0 && ledIndex < NUM_LEDS) {
                    leds[ledIndex] = color;
                }
                if (mirrorMode) {
                    int mirrorIndex = xyMap(WIDTH - 1 - (xStart + x), y);
                    if (mirrorIndex >= 0 && mirrorIndex < NUM_LEDS) {
                        leds[mirrorIndex] = color;
                    }
                }
            }
        }
    }
}
References audioGain(), autoGainValue, fl::clamp(), clearDisplay(), ColorFromPalette(), fft, fftSmooth, getCurrentPalette(), HEIGHT, hue, leds, fl::map_range(), fl::max(), mirrorMode(), noiseFloor(), NUM_BANDS, NUM_LEDS, palette(), WIDTH, x, xyMap, and y.
Referenced by loop().