FastLED: drawFireEffect
drawFireEffect()
void drawFireEffect (float peak)
Definition at line 398 of file advanced.h.
{
    // Simple fire effect without buffer
    clearDisplay();
    // Add heat at bottom based on audio
    int heat = 100 + (peak * 155 * audioGain.value() * autoGainValue);
    heat = MIN(heat, 255);
    for (int x = 0; x < WIDTH; x++) {
        for (int y = 0; y < HEIGHT; y++) {
            // Simple gradient from bottom to top
            int heatLevel = heat * (HEIGHT - y) / HEIGHT;
            heatLevel = heatLevel * random(80, 120) / 100;  // Add randomness
            heatLevel = MIN(heatLevel, 255);
            int ledIndex = xyMap(x, y);
            if (ledIndex >= 0 && ledIndex < NUM_LEDS) {
                leds[ledIndex] = HeatColor(heatLevel);
            }
        }
    }
}
References audioGain(), autoGainValue, clearDisplay(), heat, HeatColor(), HEIGHT, leds, MIN, NUM_LEDS, WIDTH, x, xyMap, and y.
Referenced by loop().