FastLED: drawPlasmaWave
drawPlasmaWave()
void drawPlasmaWave (float peak)
Definition at line 432 of file advanced.h.
{
    static float time = 0; // okay static in header
    time += 0.05f + (peak * 0.2f);
    fl::CRGBPalette16 palette = getCurrentPalette();
    for (int x = 0; x < WIDTH; x++) {
        for (int y = 0; y < HEIGHT; y++) {
            float value = fl::sinf(x * 0.1f + time) +
                         fl::sinf(y * 0.1f - time) +
                         fl::sinf((x + y) * 0.1f + time) +
                         fl::sinf(fl::sqrtf(x * x + y * y) * 0.1f - time);
            value = (value + 4) / 8;  // Normalize to 0-1
            value *= audioGain.value() * autoGainValue;
            uint8_t colorIndex = value * 255;
            int ledIndex = xyMap(x, y);
            if (ledIndex >= 0 && ledIndex < NUM_LEDS) {
                leds[ledIndex] = ColorFromPalette(palette, colorIndex + hue);
            }
        }
    }
}
References audioGain(), autoGainValue, ColorFromPalette(), getCurrentPalette(), HEIGHT, hue, leds, NUM_LEDS, palette(), fl::sinf(), fl::sqrtf(), WIDTH, x, xyMap, and y.
Referenced by loop().