FastLED: getCurrentPalette
getCurrentPalette()
fl::CRGBPalette16 getCurrentPalette ()
Definition at line 109 of file advanced.h.
{
    switch(colorPalette.as_int()) {
        case 0: return fl::CRGBPalette16(fl::RainbowColors_p);
        case 1: return fl::CRGBPalette16(fl::HeatColors_p);
        case 2: return fl::CRGBPalette16(fl::OceanColors_p);
        case 3: return fl::CRGBPalette16(fl::ForestColors_p);
        case 4: return fl::CRGBPalette16(fl::PartyColors_p);
        case 5: return fl::CRGBPalette16(fl::LavaColors_p);
        case 6: return fl::CRGBPalette16(fl::CloudColors_p);
        default: return fl::CRGBPalette16(fl::RainbowColors_p);
    }
}
References colorPalette().
Referenced by drawPlasmaWave(), drawRadialSpectrum(), drawSpectrumBars(), drawVUMeter(), and drawWaveform().