FastLED: drawRadialSpectrum
drawRadialSpectrum()
void drawRadialSpectrum (fl::audio::fft::Bins * fft, float)
Definition at line 232 of file advanced.h.
{
    clearDisplay();
    fl::CRGBPalette16 palette = getCurrentPalette();
    int centerX = WIDTH / 2;
    int centerY = HEIGHT / 2;
    auto bands = fft->db();
    for (size_t angle = 0; angle < 360; angle += 6) {  // Reduced resolution
        size_t band = (angle / 6) % NUM_BANDS;
        if (band >= bands.size()) continue;
        float magnitude = bands[band] / 100.0f;
        magnitude = fl::max(0.0f, magnitude - noiseFloor.value());
        magnitude *= audioGain.value() * autoGainValue;
        magnitude = fl::clamp(magnitude, 0.0f, 1.0f);
        int radius = magnitude * (fl::min(WIDTH, HEIGHT) / 2);
        for (int r = 0; r < radius; r++) {
            int x = centerX + (r * fl::cosf(angle * FL_PI / 180.0f));
            int y = centerY + (r * fl::sinf(angle * FL_PI / 180.0f));
            if (x >= 0 && x < WIDTH && y >= 0 && y < HEIGHT) {
                uint8_t colorIndex = fl::map_range<int, uint8_t>(r, 0, radius, 255, 0);
                int ledIndex = xyMap(x, y);
                if (ledIndex >= 0 && ledIndex < NUM_LEDS) {
                    leds[ledIndex] = ColorFromPalette(palette, colorIndex + hue);
                }
            }
        }
    }
}
References audioGain(), autoGainValue, fl::clamp(), clearDisplay(), ColorFromPalette(), fl::cosf(), fft, FL_PI, getCurrentPalette(), HEIGHT, hue, leds, fl::map_range(), fl::max(), fl::min(), noiseFloor(), NUM_BANDS, NUM_LEDS, palette(), fl::sinf(), WIDTH, x, xyMap, and y.
Referenced by loop().