FastLED: clearDisplay
clearDisplay()
void clearDisplay ()
Definition at line 167 of file advanced.h.
                    {
    if (fadeSpeed.as_int() == 0) {
        fill_solid(leds, NUM_LEDS, CRGB::Black);
    } else {
        fadeToBlackBy(leds, NUM_LEDS, fadeSpeed.as_int());
    }
}
References CRGB::Black, fadeSpeed(), fadeToBlackBy(), fill_solid(), leds, and NUM_LEDS.
Referenced by drawFireEffect(), drawRadialSpectrum(), drawSpectrumBars(), drawVUMeter(), and drawWaveform().