FastLED: drawWaveform
drawWaveform()
void drawWaveform (const fl::span< const int16_t > & pcm, float)
Definition at line 268 of file advanced.h.
{
    clearDisplay();
    fl::CRGBPalette16 palette = getCurrentPalette();
    int samplesPerPixel = pcm.size() / WIDTH;
    int centerY = HEIGHT / 2;
    for (size_t x = 0; x < WIDTH; x++) {
        size_t sampleIndex = x * samplesPerPixel;
        if (sampleIndex >= pcm.size()) break;
        // Get the raw sample value
        float sample = float(pcm[sampleIndex]) / 32768.0f;  // Normalize to -1.0 to 1.0
        // Apply logarithmic scaling to prevent saturation
        float absSample = fl::fabsf(sample);
        float logAmplitude = 0.0f;
        if (absSample > 0.001f) {  // Avoid log(0)
            // Logarithmic compression: log10(1 + gain * sample)
            float scaledSample = absSample * audioGain.value() * autoGainValue;
            logAmplitude = fl::log10f(1.0f + scaledSample * 9.0f) / fl::log10f(10.0f);  // Normalize to 0-1
        }
        // Apply smooth sensitivity curve
        logAmplitude = fl::powf(logAmplitude, 0.7f);  // Gamma correction for better visual response
        // Calculate amplitude in pixels
        int amplitude = int(logAmplitude * (HEIGHT / 2));
        amplitude = fl::clamp(amplitude, 0, HEIGHT / 2);
        // Preserve the sign for proper waveform display
        if (sample < 0) amplitude = -amplitude;
        // Color mapping based on amplitude intensity
        uint8_t colorIndex = fl::map_range<int, uint8_t>(abs(amplitude), 0, HEIGHT/2, 40, 255);
        fl::CRGB color = ColorFromPalette(palette, colorIndex + hue);
        // Apply brightness scaling for low amplitudes
        if (abs(amplitude) < HEIGHT / 4) {
            color.fadeToBlackBy(128 - (abs(amplitude) * 512 / HEIGHT));
        }
        // Draw vertical line from center
        if (amplitude == 0) {
            // Draw center point for zero amplitude
            int ledIndex = xyMap(x, centerY);
            if (ledIndex >= 0 && ledIndex < NUM_LEDS) {
                leds[ledIndex] = color.fadeToBlackBy(200);
            }
        } else {
            // Draw line from center to amplitude
            int startY = (amplitude > 0) ? centerY : centerY + amplitude;
            int endY = (amplitude > 0) ? centerY + amplitude : centerY;
            for (int y = startY; y <= endY; y++) {
                if (y >= 0 && y < HEIGHT) {
                    int ledIndex = xyMap(x, y);
                    if (ledIndex >= 0 && ledIndex < NUM_LEDS) {
                        // Fade edges for smoother appearance
                        fl::CRGB pixelColor = color;
                        if (y == startY || y == endY) {
                            pixelColor.fadeToBlackBy(100);
                        }
                        leds[ledIndex] = pixelColor;
                    }
                }
            }
        }
    }
}
References abs(), audioGain(), autoGainValue, fl::clamp(), clearDisplay(), ColorFromPalette(), fl::fabsf(), fl::CRGB::fadeToBlackBy(), getCurrentPalette(), HEIGHT, hue, leds, fl::log10f(), fl::map_range(), NUM_LEDS, palette(), fl::powf(), fl::span< T, Extent >::size(), WIDTH, x, xyMap, and y.
Referenced by loop().