FastLED: loop
loop()
void loop ()
Definition at line 501 of file advanced.h.
            {
    // Check if audio is enabled
    if (!enableAudio) {
        // Show a simple test pattern
        fill_rainbow(leds, NUM_LEDS, hue++, 7);
        FastLED.show();
        delay(20);
        return;
    }
    // Process only one audio sample per frame to avoid accumulation
    fl::audio::Sample sample = audio.next();
    if (sample.isValid()) {
        // Process pitch detection if enabled
        if (pitchDetectEnable && pitchEngine) {
            // Convert int16_t samples to float for pitch detection
            static float floatBuffer[FFT_SIZE];
            size_t numSamples = fl::min(sample.pcm().size(), (size_t)FFT_SIZE);
            for (size_t i = 0; i < numSamples; i++) {
                floatBuffer[i] = sample.pcm()[i] / 32768.0f;
            }
            pitchEngine->processFrame(floatBuffer, numSamples);
        }
        // Update sound meter
        soundMeter.processBlock(sample.pcm());
        // Get audio levels
        float rms = sample.rms() / 32768.0f;
        // Calculate peak
        int32_t maxSample = 0;
        for (size_t i = 0; i < sample.pcm().size(); i++) {
            int32_t absSample = fl::fabsf(sample.pcm()[i]);
            if (absSample > maxSample) {
                maxSample = absSample;
            }
        }
        float peak = float(maxSample) / 32768.0f;
        peakLevel = peakLevel * 0.9f + peak * 0.1f;  // Smooth peak
        // Update auto gain
        updateAutoGain(rms);
        // Beat detection
        if (beatDetect) {
            isBeat = detectBeat(peak);
        }
        // Get FFT data - create local Bins to avoid accumulation
        fl::audio::fft::Bins fftBins(NUM_BANDS);
        sample.fft(&fftBins);
        // Update color animation
        hue += 1;
        // Apply beat flash
        if (isBeat && beatFlash) {
            for (int i = 0; i < NUM_LEDS; i++) {
                leds[i].fadeLightBy(-50);  // Make brighter
            }
        }
        // Draw selected visualization
        switch (visualMode.as_int()) {
            case 0:  // Spectrum Bars
                drawSpectrumBars(&fftBins, peakLevel);
                break;
            case 1:  // Radial Spectrum
                drawRadialSpectrum(&fftBins, peakLevel);
                break;
            case 2:  // Waveform
                drawWaveform(sample.pcm(), peakLevel);
                break;
            case 3:  // VU Meter
                drawVUMeter(rms, peakLevel);
                break;
            case 4:  // Matrix Rain
                drawMatrixRain(peakLevel);
                break;
            case 5:  // Fire Effect
                drawFireEffect(peakLevel);
                break;
            case 6:  // Plasma Wave
                drawPlasmaWave(peakLevel);
                break;
        }
        // Add pitch visualizer overlay if enabled
        if (pitchVisualizer && pitchDetectEnable && noteIsOn) {
            // Display pitch as a horizontal line at a specific height
            int noteY = HEIGHT - 4;  // Near the top
            // Map MIDI note to X position (common singing range: 40-88)
            float notePos = fl::map_range<float, float>(currentMIDINote, 40.0f, 88.0f, 0.0f, 1.0f);
            notePos = fl::clamp(notePos, 0.0f, 1.0f);
            int noteX = notePos * (WIDTH - 1);
            // Draw pitch indicator - brightness based on velocity
            uint8_t brightness = fl::map_range<uint8_t, uint8_t>(currentVelocity, 0, 127, 50, 255);
            fl::CRGB pitchColor = fl::CRGB(255, 0, 255);  // Magenta
            pitchColor.fadeToBlackBy(255 - brightness);
            // Draw a small cross at the pitch position
            for (int dx = -2; dx <= 2; dx++) {
                int x = noteX + dx;
                if (x >= 0 && x < WIDTH) {
                    int ledIndex = xyMap(x, noteY);
                    if (ledIndex >= 0 && ledIndex < NUM_LEDS) {
                        leds[ledIndex] = pitchColor;
                    }
                }
            }
            for (int dy = -2; dy <= 2; dy++) {
                int y = noteY + dy;
                if (y >= 0 && y < HEIGHT) {
                    int ledIndex = xyMap(noteX, y);
                    if (ledIndex >= 0 && ledIndex < NUM_LEDS) {
                        leds[ledIndex] = pitchColor;
                    }
                }
            }
        }
    }
    FastLED.show();
    // Add a small delay to prevent tight loops in WebAssembly
    #ifdef __EMSCRIPTEN__
    delay(1);
    #endif
}
References audio, beatDetect(), beatFlash(), brightness, fl::clamp(), currentMIDINote, currentVelocity, detectBeat(), drawFireEffect(), drawMatrixRain(), drawPlasmaWave(), drawRadialSpectrum(), drawSpectrumBars(), drawVUMeter(), drawWaveform(), enableAudio(), fl::fabsf(), fl::CRGB::fadeToBlackBy(), FastLED, FFT_SIZE, fill_rainbow(), HEIGHT, hue, isBeat, leds, fl::map_range(), fl::min(), noteIsOn, NUM_BANDS, NUM_LEDS, peakLevel, pitchDetectEnable(), pitchEngine, pitchVisualizer(), rms(), soundMeter(), updateAutoGain(), visualMode(), WIDTH, x, xyMap, and y.