FastLED: drawVUMeter
drawVUMeter()
void drawVUMeter (float rms, float peak)
Definition at line 341 of file advanced.h.
{
    clearDisplay();
    fl::CRGBPalette16 palette = getCurrentPalette();
    // RMS level bar
    int rmsWidth = rms * WIDTH * audioGain.value() * autoGainValue;
    rmsWidth = fl::min(rmsWidth, WIDTH);
    for (int x = 0; x < rmsWidth; x++) {
        for (int y = HEIGHT/3; y < 2*HEIGHT/3; y++) {
            uint8_t colorIndex = fl::map_range<int, uint8_t>(x, 0, WIDTH, 0, 255);
            int ledIndex = xyMap(x, y);
            if (ledIndex >= 0 && ledIndex < NUM_LEDS) {
                leds[ledIndex] = ColorFromPalette(palette, colorIndex);
            }
        }
    }
    // Peak indicator
    int peakX = peak * WIDTH * audioGain.value() * autoGainValue;
    peakX = fl::min(peakX, WIDTH - 1);
    for (int y = HEIGHT/4; y < 3*HEIGHT/4; y++) {
        int ledIndex = xyMap(peakX, y);
        if (ledIndex >= 0 && ledIndex < NUM_LEDS) {
            leds[ledIndex] = fl::CRGB::White;
        }
    }
    // Beat indicator
    if (isBeat && beatFlash) {
        for (int x = 0; x < WIDTH; x++) {
            int ledIndex1 = xyMap(x, 0);
            int ledIndex2 = xyMap(x, HEIGHT - 1);
            if (ledIndex1 >= 0 && ledIndex1 < NUM_LEDS) leds[ledIndex1] = fl::CRGB::White;
            if (ledIndex2 >= 0 && ledIndex2 < NUM_LEDS) leds[ledIndex2] = fl::CRGB::White;
        }
    }
}
References audioGain(), autoGainValue, beatFlash(), clearDisplay(), ColorFromPalette(), getCurrentPalette(), HEIGHT, isBeat, leds, fl::map_range(), fl::min(), NUM_LEDS, palette(), rms(), fl::CRGB::White, WIDTH, x, xyMap, and y.
Referenced by loop().