FastLED: brightness
brightness()
UISlider brightness ("Brightness" , 128 , 0 , 255 , 1)
Examples
Animartrix.ino.
Referenced by fl::applyGamma_video(), RGBWEmulatedController< CONTROLLER, RGB_ORDER >::ControllerT::callShow(), WS2816Controller< DATA_PIN, RGB_ORDER >::ControllerT::callShow(), fl::ColorFromPalette(), fl::ColorFromPalette(), fl::ColorFromPalette(), fl::ColorFromPalette(), fl::ColorFromPalette(), fl::ColorFromPalette(), fl::ColorFromPalette(), fl::ColorFromPalette(), fl::ColorFromPaletteExtended(), fl::ColorFromPaletteExtended(), fl::ColorFromPaletteExtended(), displayControls(), draw(), FillLEDsFromPaletteColors(), fl::five_bit_bitshift(), fl::five_bit_bitshift(), CLEDController::getAdjustmentData(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::getGlobalBrightnessAndScalingFactors(), KeyboardState::HandleNoteOn(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale_APA102_HD(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScale_WS2816_HD(), loop(), MyColorFromPaletteExtended(), renderGroup(), SelectColor(), setup(), CLEDController::show(), CPixelLEDController< RGB_ORDER, LANES, MASK >::show(), CLEDController::showColor(), CPixelLEDController< RGB_ORDER, LANES, MASK >::showColor(), CLEDController::showColorInternal(), CLEDController::showColorInternal(), showGenerative(), CLEDController::showInternal(), CLEDController::showLeds(), CLEDController::showLedsInternal(), APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsGammaBitShift(), and APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::writeLed().