FastLED: fl::FrameInterpolator::draw
draw() [1/2]
bool fl::FrameInterpolator::draw (uint32_t adjustable_time, CRGB * leds)
Definition at line 27 of file frame_interpolator.cpp.
{
    uint32_t frameNumber, nextFrameNumber;
    uint8_t amountOfNextFrame;
    // DBG("now: " << now);
    mFrameTracker.get_interval_frames(now, &frameNumber, &nextFrameNumber,
                                      &amountOfNextFrame);
    if (!has(frameNumber)) {
        return false;
    }
    if (has(frameNumber) && !has(nextFrameNumber)) {
        // just paint the current frame
        Frame *frame = get(frameNumber).get();
        frame->draw(leds);
        return true;
    }
    Frame *frame1 = get(frameNumber).get();
    Frame *frame2 = get(nextFrameNumber).get();
    Frame::interpolate(*frame1, *frame2, amountOfNextFrame, leds);
    return true;
}
References fl::Frame::draw(), get(), has(), fl::Frame::interpolate(), leds, and mFrameTracker.