FastLED: fl::detail::posix_filebuf::read
read() [1/3]
fl::size_t fl::detail::posix_filebuf::read (char * buffer, fl::size_t count) override virtual
Implements fl::filebuf.
Definition at line 79 of file file_handle.cpp.hpp.
{
    if (!mFile) {
        return 0;
    }
    fl::size_t bytes_read = fl::fread(buffer, 1, count, mFile);
    // fread can return short at EOF - not an error
    if (fl::feof(mFile) || bytes_read > 0) {
        mLastError = 0;
    } else if (fl::ferror(mFile)) {
        captureError();
    }
    return bytes_read;
}
References captureError(), fl::feof(), fl::ferror(), fl::fread(), mFile, and mLastError.
Referenced by operator=().