FastLED: fl::detail::posix_filebuf::posix_filebuf
posix_filebuf() [2/4]
fl::detail::posix_filebuf::posix_filebuf (const char * path, const char * mode) explicit
Definition at line 32 of file file_handle.cpp.hpp.
    : mFile(nullptr), mLastError(0), mPath(path ? path : "") {
    mFile = fl::fopen(path, mode);
    if (!mFile) {
        captureError();
    }
}
References captureError(), fl::fopen(), mFile, mLastError, mPath, and path().