FastLED: fl::detail::posix_filebuf::operator=
operator=() [2/2]
posix_filebuf & fl::detail::posix_filebuf::operator= (posix_filebuf && other)
Definition at line 51 of file file_handle.cpp.hpp.
{
    if (this != &other) {
        close();
        mFile = other.mFile;
        mLastError = other.mLastError;
        mPath = fl::move(other.mPath);
        other.mFile = nullptr;
        other.mLastError = 0;
    }
    return *this;
}
References posix_filebuf(), close(), FL_NOEXCEPT, mFile, mLastError, fl::fl::move(), and mPath.