FastLED: fl::anonymous_namespace{channel.cpp.hpp}::writeUCS7604
writeUCS7604()
void fl::anonymous_namespace{channel.cpp.hpp}::writeUCS7604 (fl::vector_psram< u8 > * data, PixelIterator & pixelIterator, ClocklessEncoder encoder, const ChannelOptions & settings, EOrder rgbOrder)
Encode UCS7604 pixel data into the channel data buffer.
Parameters
data Output byte vector (cleared by caller)
pixelIterator Pixel iterator with color order and RGBW conversion
encoder ClocklessEncoder value identifying the UCS7604 mode
settings Channel settings (for gamma override)
rgbOrder RGB ordering for current control reordering
Definition at line 320 of file channel.cpp.hpp.
{
    // Map encoder enum to UCS7604Mode
    UCS7604Mode mode;
    switch (encoder) {
        case ClocklessEncoder::CLOCKLESS_ENCODER_UCS7604_8BIT:
            mode = UCS7604Mode::UCS7604_MODE_8BIT_800KHZ;
            break;
        case ClocklessEncoder::CLOCKLESS_ENCODER_UCS7604_16BIT:
            mode = UCS7604Mode::UCS7604_MODE_16BIT_800KHZ;
            break;
        case ClocklessEncoder::CLOCKLESS_ENCODER_UCS7604_16BIT_1600:
            mode = UCS7604Mode::UCS7604_MODE_16BIT_1600KHZ;
            break;
        default:
            // Should never happen — caller already checked
            mode = UCS7604Mode::UCS7604_MODE_16BIT_800KHZ;
            break;
    }
    // Get current control from global UCS7604 brightness
    UCS7604CurrentControl current = ucs7604::brightness();
    // Reorder current control values to match wire order (same logic as UCS7604ControllerT)
    u8 rgb_currents[3] = {current.r, current.g, current.b};
    u8 pos0 = (static_cast<int>(rgbOrder) >> 6) & 0x3;
    u8 pos1 = (static_cast<int>(rgbOrder) >> 3) & 0x3;
    u8 pos2 = (static_cast<int>(rgbOrder) >> 0) & 0x3;
    UCS7604CurrentControl wire_current(
        rgb_currents[pos0], rgb_currents[pos1], rgb_currents[pos2], current.w);
    // Get gamma LUT
    float gamma = settings.mGamma.value_or(2.8f);
    fl::shared_ptr<const Gamma8> gamma8 = Gamma8::getOrCreate(gamma);
    bool is_rgbw = pixelIterator.get_rgbw().active();
    size_t num_leds = pixelIterator.size();
    // (#2558) UCS7604 is a 4-channel chipset (always RGBW). If the user
    // configured this channel for 5-channel RGBWW (warm-W + cool-W), the
    // chipset can't carry the second W byte. Warn loudly — silently dropping
    // the white channels would be very hard to diagnose. The pixel iterator
    // continues to emit RGB-only bytes (is_rgbw=false) so the strip still
    // lights up, just without the W diode.
    if (pixelIterator.get_rgbww().active() && !is_rgbw) {
        FL_WARN_ONCE("UCS7604 cannot carry 5-channel RGBWW — this chipset "
                     "always emits 4-channel RGBW. The warm/cool white "
                     "channels in your Rgbww config will be dropped. "
                     "Set ChannelOptions.mWhiteCfg = Rgbw{...} instead to "
                     "silence this warning.");
    }
    // Encode into the data buffer
    encodeUCS7604(pixelIterator, num_leds, fl::back_inserter(*data),
                  mode, wire_current, is_rgbw, gamma8.get());
}
References fl::Rgbw::active(), fl::Rgbww::active(), fl::UCS7604CurrentControl::b, fl::back_inserter(), fl::ucs7604::brightness(), fl::CLOCKLESS_ENCODER_UCS7604_16BIT, fl::CLOCKLESS_ENCODER_UCS7604_16BIT_1600, fl::CLOCKLESS_ENCODER_UCS7604_8BIT, fl::encodeUCS7604(), FL_WARN_ONCE, fl::UCS7604CurrentControl::g, fl::gamma(), fl::shared_ptr< T >::get(), fl::PixelIterator::get_rgbw(), fl::PixelIterator::get_rgbww(), fl::Gamma8::getOrCreate(), fl::ChannelOptions::mGamma, fl::UCS7604CurrentControl::r, fl::PixelIterator::size(), fl::UCS7604_MODE_16BIT_1600KHZ, fl::UCS7604_MODE_16BIT_800KHZ, fl::UCS7604_MODE_8BIT_800KHZ, fl::UCS7604CurrentControl::w, and writeUCS7604().
Referenced by writeUCS7604().