FastLED: fl::anonymous_namespace{channel.cpp.hpp}::createBackendDevice
createBackendDevice()
static fl::shared_ptr< RxDevice > fl::anonymous_namespace{channel.cpp.hpp}::createBackendDevice (const RxChannelConfig & config) static
Definition at line 24 of file channel.cpp.hpp.
{
    switch (config.backend) {
    case RxBackend::PLATFORM_DEFAULT:
        return RxDevice::create<RxDeviceType::PLATFORM_DEFAULT>(config.pin);
    case RxBackend::RMT:
        return RxDevice::create<RxDeviceType::RMT>(config.pin);
    case RxBackend::ISR:
        return RxDevice::create<RxDeviceType::ISR>(config.pin);
    case RxBackend::FLEXPWM:
        return RxDevice::create<RxDeviceType::FLEXPWM>(config.pin);
    case RxBackend::FLEXIO:
        return RxDevice::create<RxDeviceType::FLEXIO>(config.pin);
    case RxBackend::LPC_SCT_CAPTURE:
        return RxDevice::create<RxDeviceType::LPC_SCT_CAPTURE>(config.pin);
    }
    return RxDevice::create<RxDeviceType::PLATFORM_DEFAULT>(config.pin);
}
References fl::RxDevice::create(), createBackendDevice(), FL_NOEXCEPT, fl::FLEXIO, fl::FLEXPWM, fl::ISR, fl::LPC_SCT_CAPTURE, fl::PLATFORM_DEFAULT, and fl::RMT.
Referenced by createBackendDevice().