FastLED: fl::beatsin88
beatsin88()
LIB8STATIC u16 fl::beatsin88 (accum88 beats_per_minute_88, u16 lowest = 0, u16 highest = 65535, u32 timebase = 0, u16 phase_offset = 0)
Generates a 16-bit sine wave at a given BPM that oscillates within a given range.
Parameters
beats_per_minute_88 the frequency of the wave, in Q8.8 format
lowest the lowest output value of the sine wave
highest the highest output value of the sine wave
timebase the time offset of the wave from the millis() timer
phase_offset phase offset of the wave from the current position
Warning
The BPM parameter MUST be provided in Q8.8 format!
Definition at line 63 of file beat.h.
{
    u16 beat = beat88(beats_per_minute_88, timebase);
    u16 beatsin = (sin16(beat + phase_offset) + 32768);
    u16 rangewidth = highest - lowest;
    u16 scaledbeat = scale16(beatsin, rangewidth);
    u16 result = lowest + scaledbeat;
    if (result > highest) {
        result = highest;
    }
    return result;
}
References beat88(), FL_NOEXCEPT, and LIB8STATIC.
Referenced by fl::Pacifica::draw(), and fl::Pride2015::draw().