FastLED: fl::beatsin8
beatsin8()
LIB8STATIC u8 fl::beatsin8 (accum88 beats_per_minute, u8 lowest = 0, u8 highest = 255, u32 timebase = 0, u8 phase_offset = 0)
Generates an 8-bit sine wave at a given BPM that oscillates within a given range.
Parameters
beats_per_minute the frequency of the wave, in decimal
lowest the lowest output value of the sine wave
highest the highest output value of the sine wave
timebase the time offset of the wave from the millis() timer
phase_offset phase offset of the wave from the current position
Definition at line 105 of file beat.h.
{
    u8 beat = beat8(beats_per_minute, timebase);
    u8 beatsin = sin8(beat + phase_offset);
    u8 rangewidth = highest - lowest;
    u8 scaledbeat = scale8(beatsin, rangewidth);
    u8 result = lowest + scaledbeat;
    if (result > highest) {
        result = highest;
    }
    return result;
}
References beat8(), FL_NOEXCEPT, and LIB8STATIC.
Referenced by fl::DemoReel100::bpm(), fl::Pacifica::draw(), and fl::Pacifica::pacifica_add_whitecaps().