FastLED: beatsin16
beatsin16()
LIB8STATIC uint16_t beatsin16 (accum88 beats_per_minute, uint16_t lowest = 0, uint16_t highest = 65535, uint32_t timebase = 0, uint16_t phase_offset = 0)
Generates a 16-bit sine wave at a given BPM that oscillates within a given range.
Parameters
beats_per_minute the frequency of the wave, in decimal
lowest the lowest output value of the sine wave
highest the highest output value of the sine wave
timebase the time offset of the wave from the millis() timer
phase_offset phase offset of the wave from the current position
Examples
DemoReel100.ino, and Pacifica.ino.
Definition at line 939 of file lib8tion.h.
{
    uint16_t beat = beat16( beats_per_minute, timebase);
    uint16_t beatsin = (sin16( beat + phase_offset) + 32768);
    uint16_t rangewidth = highest - lowest;
    uint16_t scaledbeat = scale16( beatsin, rangewidth);
    uint16_t result = lowest + scaledbeat;
    return result;
}
References beat16(), LIB8STATIC, scale16(), and sin16.
Referenced by fl::Pacifica::draw(), fl::DemoReel100::juggle(), juggle(), loop(), pacifica_loop(), fl::DemoReel100::sinelon(), and sinelon().