FastLED: fl::anonymous_namespace{noise_woryley.cpp}::hash
hash()
uint16_t fl::anonymous_namespace{noise_woryley.cpp}::hash (int32_t x, int32_t y)
Definition at line 18 of file noise_woryley.cpp.
{
    uint32_t n = (uint32_t)(x * 374761393 + y * 668265263);
    n = (n ^ (n >> 13)) * 1274126177;
    return (uint16_t)((n ^ (n >> 16)) & 0xFFFF);
}
References hash(), x, and y.
Referenced by feature_point(), and hash().