FastLED: loop
loop()
void loop ()
Examples
AnalogOutput.ino, Animartrix.ino, ArrayOfLedArrays.ino, Audio.ino, BeatDetection.ino, Blink.ino, BlinkParallel.ino, Blur2d.ino, Chromancer.ino, ColorPalette.ino, ColorTemperature.ino, Cylon.ino, DemoReel100.ino, ElPanelReactive.ino, Fire2012.ino, Fire2012WithPalette.ino, FirstLight.ino, FlowField.ino, FxCylon.ino, FxDemoReel100.ino, FxEngine.ino, FxFire2012.ino, FxGfx2Video.ino, FxNoisePlusPalette.ino, FxNoiseRing.ino, FxPacifica.ino, FxPride2015.ino, MirroringSample.ino, MultiArrays.ino, MultipleStripsInOneArray.ino, Noise.ino, Overclock.ino, Pacifica.ino, ParallelSPI.ino, PerfDisc.ino, Pride2015.ino, RGBCalibrate.ino, RGBSetDemo.ino, RX.ino, Sailboat.ino, SmartMatrix.ino, Test.ino, TwinkleFox.ino, WS2816.ino, WasmScreenCoords.ino, and XYMatrix.ino.
Definition at line 54 of file AnalogOutput.ino.
{
  static uint8_t hue;
  hue = hue + 1;
  // Use FastLED automatic HSV->RGB conversion
  showAnalogRGB( CHSV( hue, 255, 255) );
  delay(20);
}
References hue, and showAnalogRGB().
Referenced by fl::third_party::plm_set_loop(), and setup().