FastLED: fl::audio::detector::MultiBandBeat::detectBeats
detectBeats()
void fl::audio::detector::MultiBandBeat::detectBeats (span< const float > frequencyBins)
Detect beats in all frequency bands.
Parameters
frequencyBins 16-element array of frequency bin magnitudes
Definition at line 22 of file multiband_beat_detector.cpp.hpp.
{
    // Verify input size
    if (frequencyBins.size() < 16) {
        // Invalid input - reset beat flags
        mBassBeat = false;
        mMidBeat = false;
        mTrebleBeat = false;
        return;
    }
    // Calculate current energies
    float bassEnergy = calculateBassEnergy(frequencyBins);
    float midEnergy = calculateMidEnergy(frequencyBins);
    float trebleEnergy = calculateTrebleEnergy(frequencyBins);
    // Decrement cooldown counters
    if (mBassCooldown > 0) mBassCooldown--;
    if (mMidCooldown > 0) mMidCooldown--;
    if (mTrebleCooldown > 0) mTrebleCooldown--;
    // Detect beats in each band
    mBassBeat = detectBandBeat(bassEnergy, mPreviousBassEnergy,
                               mConfig.bassThreshold, mBassCooldown);
    mMidBeat = detectBandBeat(midEnergy, mPreviousMidEnergy,
                              mConfig.midThreshold, mMidCooldown);
    mTrebleBeat = detectBandBeat(trebleEnergy, mPreviousTrebleEnergy,
                                 mConfig.trebleThreshold, mTrebleCooldown);
    // Cross-band correlation: if multiple bands trigger, boost confidence
    if (mConfig.enableCrossBandCorrelation) {
        u32 bandCount = 0;
        if (mBassBeat) bandCount++;
        if (mMidBeat) bandCount++;
        if (mTrebleBeat) bandCount++;
        // Multi-band beat detected
        if (bandCount >= 2) {
            mStats.multiBandBeats++;
        }
    }
    // Update statistics
    if (mBassBeat) mStats.bassBeats++;
    if (mMidBeat) mStats.midBeats++;
    if (mTrebleBeat) mStats.trebleBeats++;
    // Store current energies for next frame
    mPreviousBassEnergy = bassEnergy;
    mPreviousMidEnergy = midEnergy;
    mPreviousTrebleEnergy = trebleEnergy;
    // Update current energies in stats
    mBassEnergy = bassEnergy;
    mMidEnergy = midEnergy;
    mTrebleEnergy = trebleEnergy;
    mStats.bassEnergy = bassEnergy;
    mStats.midEnergy = midEnergy;
    mStats.trebleEnergy = trebleEnergy;
    mCurrentFrame++;
}
References calculateBassEnergy(), calculateMidEnergy(), calculateTrebleEnergy(), detectBandBeat(), mBassBeat, mBassCooldown, mBassEnergy, mConfig, mCurrentFrame, mMidBeat, mMidCooldown, mMidEnergy, mPreviousBassEnergy, mPreviousMidEnergy, mPreviousTrebleEnergy, mStats, mTrebleBeat, mTrebleCooldown, mTrebleEnergy, and fl::span< T, Extent >::size().
Referenced by ~MultiBandBeat().