FastLED: delaycycles
delaycycles() [1/2]
template<fl::cycle_t CYCLES> void delaycycles () inline
Delay N clock cycles.
Template Parameters
CYCLES the number of clock cycles to delay
Note
No delay is applied if CYCLES is less than or equal to zero.
Definition at line 136 of file fastled_delay.h.
{
    // _delaycycles_ARM<CYCLES / 3, CYCLES % 3>();
    FL_NOP; delaycycles<CYCLES-1>();
}
References delaycycles(), FASTLED_FORCE_INLINE, and FL_NOP.
Referenced by delaycycles(), and delaycycles_min1().