FastLED: fl::task::detail::PromiseImpl::resolve
resolve() [2/2]
template<typename T> bool fl::task::detail::PromiseImpl< T >::resolve (T && value) inline
Definition at line 293 of file promise.h.
{
        if (state() != PromiseState_t::PENDING) return false;
        mValue = fl::move(value);
        set_state(PromiseState_t::RESOLVED);
        if (mThenCallback && !mCallbacksProcessed) {
            process_callbacks();
        }
        return true;
    }
References FL_NOEXCEPT, mCallbacksProcessed, fl::fl::move(), mThenCallback, mValue, fl::task::detail::PENDING, process_callbacks(), fl::task::detail::RESOLVED, set_state(), state(), and value().