FastLED: fl::task::detail::PromiseImpl::process_callbacks
process_callbacks()
template<typename T> void fl::task::detail::PromiseImpl< T >::process_callbacks () inline private
Process pending callbacks.
Definition at line 366 of file promise.h.
{
        if (mCallbacksProcessed) return;
        PromiseState_t s = state();
        if (s == PromiseState_t::RESOLVED && mThenCallback) {
            mThenCallback(mValue);
        } else if (s == PromiseState_t::REJECTED && mCatchCallback) {
            mCatchCallback(mError);
        }
        mCallbacksProcessed = true;
    }
References FL_NOEXCEPT, mCallbacksProcessed, mCatchCallback, mError, mThenCallback, mValue, fl::task::detail::REJECTED, fl::task::detail::RESOLVED, and state().
Referenced by reject(), resolve(), resolve(), set_catch_callback(), set_then_callback(), and update().