FastLED: fl::IFastLED::setSegment
setSegment()
virtual void fl::IFastLED::setSegment (size_t start, size_t end) pure virtual
Set a segment range for subsequent operations.
Parameters
start Starting LED index (inclusive)
end Ending LED index (exclusive)
After calling this, getLEDs() and getNumLEDs() will operate on the specified segment only.
Implemented in fl::FastLEDAdapter.
References fl::end(), and setSegment().
Referenced by setSegment().