FastLED: fl::Spi::Spi
Spi() [3/4]
fl::Spi::Spi (const SpiConfig & config) explicit
Construct from SpiConfig.
Parameters
config SPI configuration
Definition at line 24 of file spi.cpp.hpp.
    : is_ok(false), error_code(SPIError::NOT_INITIALIZED) {
    // Validate number of lanes
    size_t num_lanes = config.data_pins.size();
    if (num_lanes < 1 || num_lanes > 8) {
        FL_WARN("fl::Spi: Invalid number of data pins (" << num_lanes << "), must be 1-8");
        error_code = SPIError::NOT_INITIALIZED;
        return;
    }
    // Convert SpiConfig to MultiLaneDevice::Config
    spi::MultiLaneDevice::Config ml_config;
    ml_config.clock_pin = static_cast<u8>(config.clock_pin);
    ml_config.data_pins.resize(config.data_pins.size());
    for (size_t i = 0; i < config.data_pins.size(); i++) {
        ml_config.data_pins[i] = static_cast<u8>(config.data_pins[i]);
    }
    ml_config.clock_speed_hz = config.clock_speed_hz;
    ml_config.mode = config.spi_mode;
    // Create device
    device = fl::make_unique<spi::MultiLaneDevice>(ml_config);
    FL_DBG("fl::Spi: Created MultiLaneDevice with " << num_lanes << " lane(s)");
    // Initialize device
    auto begin_result = device->begin();
    if (begin_result) {
        // begin() returned an error (optional has a value)
        FL_WARN("fl::Spi: begin() failed");
        error_code = SPIError::NOT_INITIALIZED;
        device.reset();
        return;
    }
    is_ok = true;
}
References fl::spi::MultiLaneDevice::Config::clock_pin, fl::SpiConfig::clock_pin, fl::spi::MultiLaneDevice::Config::clock_speed_hz, fl::SpiConfig::clock_speed_hz, fl::spi::MultiLaneDevice::Config::data_pins, fl::SpiConfig::data_pins, device, error_code, FL_DBG, FL_WARN, is_ok, fl::make_unique(), fl::spi::MultiLaneDevice::Config::mode, fl::NOT_INITIALIZED, fl::vector< T >::resize(), fl::vector_basic::size(), and fl::SpiConfig::spi_mode.