FastLED: APA102Controller::showPixelsGammaBitShift
showPixelsGammaBitShift()
template<fl::u8 DATA_PIN, fl::u8 CLOCK_PIN, EOrder RGB_ORDER = RGB, fl::u32 SPI_SPEED = DATA_RATE_MHZ(6), fl::FiveBitGammaCorrectionMode GAMMA_CORRECTION_MODE = fl::FiveBitGammaCorrectionMode::kFiveBitGammaCorrectionMode_Null, fl::u32 START_FRAME = 0x00000000, fl::u32 END_FRAME = 0xFF000000> void APA102Controller< DATA_PIN, CLOCK_PIN, RGB_ORDER, SPI_SPEED, GAMMA_CORRECTION_MODE, START_FRAME, END_FRAME >::showPixelsGammaBitShift (PixelController< RGB_ORDER > & pixels) inline private
Definition at line 174 of file apa102.h.
{
        static constexpr fl::u16 kBatchSize = 8;
        const fl::u16 n = static_cast<fl::u16>(pixels.size());
        // Extract uniform color scale and brightness (constant across all pixels)
        fl::u8 scale_r, scale_g, scale_b, global_brightness;
        #if FASTLED_HD_COLOR_MIXING
        pixels.loadRGBScaleAndBrightness(&scale_r, &scale_g, &scale_b, &global_brightness);
        #else
        pixels.loadAndScaleRGB(&scale_r, &scale_g, &scale_b);
        global_brightness = 255;
        #endif
        const CRGB colors_scale(scale_r, scale_g, scale_b);
        // RGB reorder indices (compile-time constant from RGB_ORDER template param)
        const fl::u8 b0_index = (static_cast<int>(RGB_ORDER) >> 6) & 0x3;
        const fl::u8 b1_index = (static_cast<int>(RGB_ORDER) >> 3) & 0x3;
        const fl::u8 b2_index = static_cast<int>(RGB_ORDER) & 0x3;
        mSPI.select();
        startBoundary();
        // Process pixels in batches of 8 using stack-allocated buffers
        fl::u16 remaining = n;
        while (remaining > 0) {
            const fl::u16 batch = (remaining < kBatchSize) ? remaining : kBatchSize;
            CRGB input_buf[kBatchSize];
            fl::CRGBA5 gamma_buf[kBatchSize];
            // Copy raw pixel bytes into CRGB input buffer
            for (fl::u16 i = 0; i < batch; ++i) {
                const fl::u8* raw = pixels.getRawPixelData();
                input_buf[i] = CRGB(raw[0], raw[1], raw[2]);
                pixels.advanceData();
            }
            fl::five_bit_hd_gamma_bitshift(
                fl::span<const CRGB>(input_buf, batch), colors_scale, global_brightness,
                fl::span<fl::CRGBA5>(gamma_buf, batch));
            for (fl::u16 i = 0; i < batch; ++i) {
                const CRGB& rgb = gamma_buf[i].color;
                writeLed(gamma_buf[i].brightness_5bit,
                         rgb.raw[b0_index], rgb.raw[b1_index], rgb.raw[b2_index]);
            }
            remaining -= batch;
        }
        endBoundary(n);
        mSPI.endTransaction();
        mSPI.finalizeTransmission();
    }
References PixelController< RGB_ORDER, LANES, MASK >::advanceData(), fl::CRGBA5::color, endBoundary(), fl::five_bit_hd_gamma_bitshift(), PixelController< RGB_ORDER, LANES, MASK >::getRawPixelData(), PixelController< RGB_ORDER, LANES, MASK >::loadAndScaleRGB(), mSPI, RGB_ORDER, PixelController< RGB_ORDER, LANES, MASK >::size(), startBoundary(), and writeLed().
Referenced by showPixels().