FastLED: fl::audio::AudioManager::add
add() [1/3]
shared_ptr< Processor > fl::audio::AudioManager::add (const Config & config)
Definition at line 18 of file audio_manager.cpp.hpp.
{
#if FASTLED_HAS_AUDIO_INPUT
    fl::string errorMsg;
    auto input = IInput::create(config, &errorMsg);
    if (!input) {
        FL_WARN("Failed to create audio input: " << errorMsg);
        return nullptr;
    }
    input->start();
    auto proc = Processor::createWithAutoInput(fl::move(input));
    if (config.getMicProfile() != MicProfile::None) {
        proc->setMicProfile(config.getMicProfile());
    }
    if (processor()) {
        FL_WARN("Replacing existing audio processor");
    }
    processor() = proc;
    return proc;
#else
    (void)config;
    auto proc = fl::make_shared<Processor>();
    if (processor()) {
        FL_WARN("Replacing existing audio processor");
    }
    processor() = proc;
    return proc;
#endif
}
References fl::audio::IInput::create(), fl::audio::Processor::createWithAutoInput(), FL_WARN, fl::audio::Config::getMicProfile(), fl::make_shared(), fl::fl::move(), fl::audio::None, and processor().
Referenced by CFastLED::add(), CFastLED::add(), CFastLED::add(), add(), and fl::UIAudio::processor().