FastLED: fl::net::http::ChunkedReader::parseChunkSize
parseChunkSize()
bool fl::net::http::ChunkedReader::parseChunkSize (size_t & outSize) private
Definition at line 125 of file chunked_encoding.cpp.hpp.
{
    // Find CRLF in buffer
    for (size_t i = 0; i + 1 < mBuffer.size(); i++) {
        if (mBuffer[i] == '\r' && mBuffer[i + 1] == '\n') {
            // Found CRLF, parse hex size
            fl::string sizeStr(reinterpret_cast<const char*>(mBuffer.data()), i); // ok reinterpret cast
            // Parse hex (ignore chunk extensions after ';')
            size_t semicolon = sizeStr.find(';');
            if (semicolon != fl::string::npos) {
                sizeStr = sizeStr.substr(0, semicolon);
            }
            // Convert hex to size_t
            char* end = nullptr;
            outSize = static_cast<size_t>(strtoul(sizeStr.c_str(), &end, 16));
            if (end == sizeStr.c_str()) {
                // Invalid hex
                return false;
            }
            // Consume size line + CRLF
            consume(i + 2);
            return true;
        }
    }
    // No CRLF found
    return false;
}
References fl::basic_string::c_str(), consume(), fl::end(), fl::basic_string::find(), mBuffer, fl::string::npos, fl::strtoul(), and fl::string::substr().
Referenced by feed().