FastLED: fl::third_party::Mp3StreamDecoderImpl::decodeNextFrame
decodeNextFrame()
bool fl::third_party::Mp3StreamDecoderImpl::decodeNextFrame (audio::Sample * out_sample)
Definition at line 332 of file mp3.cpp.hpp.
{
    if (!isReady()) {
        mErrorMsg = "Decoder not ready";
        mHasError = true;
        return false;
    }
    if (mEndOfStream) {
        return false;
    }
    // Try to decode from existing buffer
    if (findAndDecodeFrame(out_sample)) {
        return true;
    }
    // Need more data - try to fill buffer and decode again
    while (fillBuffer()) {
        if (findAndDecodeFrame(out_sample)) {
            return true;
        }
    }
    // No more data available
    mEndOfStream = true;
    return false;
}
References fillBuffer(), findAndDecodeFrame(), isReady(), mEndOfStream, mErrorMsg, and mHasError.