FastLED: fl::audio::SpectralEqualizer::apply
apply()
void fl::audio::SpectralEqualizer::apply (span< const float > inputBins, span< float > outputBins) const
Apply equalization to frequency bins.
Parameters
inputBins Input frequency bins (from FrequencyBinMapper)
outputBins Output equalized frequency bins
Definition at line 122 of file spectral_equalizer.cpp.hpp.
{
    if (inputBins.size() != mConfig.numBands) {
        FL_WARN("SpectralEqualizer: input size mismatch ("
                << inputBins.size() << " != " << mConfig.numBands << ")");
        return;
    }
    if (outputBins.size() < mConfig.numBands) {
        FL_WARN("SpectralEqualizer: output buffer too small ("
                << outputBins.size() << " < " << mConfig.numBands << ")");
        return;
    }
    // Track input/output levels for stats
    float inputPeak = 0.0f;
    float outputPeak = 0.0f;
    float inputSum = 0.0f;
    float outputSum = 0.0f;
    // Apply per-band gains
    for (size i = 0; i < mConfig.numBands; ++i) {
        float inputValue = inputBins[i];
        float gain = mGains[i];
        float outputValue = inputValue * gain;
        // Apply compression if enabled
        if (mConfig.enableCompression) {
            outputValue = applyCompression(outputValue);
        }
        outputBins[i] = outputValue;
        // Track levels
        if (inputValue > inputPeak) {
            inputPeak = inputValue;
        }
        if (outputValue > outputPeak) {
            outputPeak = outputValue;
        }
        inputSum += inputValue;
        outputSum += outputValue;
    }
    // Calculate makeup gain if enabled
    float makeupGain = 1.0f;
    if (mConfig.applyMakeupGain) {
        makeupGain = calculateMakeupGain(inputBins, outputBins);
        // Apply makeup gain to all output bins
        for (size i = 0; i < mConfig.numBands; ++i) {
            outputBins[i] *= makeupGain;
        }
        // Adjust output stats
        outputPeak *= makeupGain;
        outputSum *= makeupGain;
    }
    // Update mutable stats
    mStats.applicationsCount++;
    mStats.lastInputPeak = inputPeak;
    mStats.lastOutputPeak = outputPeak;
    mStats.lastMakeupGain = makeupGain;
    mStats.avgInputLevel = inputSum / static_cast<float>(mConfig.numBands);
    mStats.avgOutputLevel = outputSum / static_cast<float>(mConfig.numBands);
}
References applyCompression(), calculateMakeupGain(), FL_WARN, mConfig, mGains, mStats, and fl::span< T, Extent >::size().
Referenced by ~SpectralEqualizer().