FastLED: MidiInterface::read
read() [2/2]
template<class Transport, class Settings, class Platform> bool MidiInterface< Transport, Settings, Platform >::read (Channel inChannel) inline
Read messages on a specified channel.
Definition at line 712 of file MIDI.hpp.
{
    #ifndef RegionActiveSending
    // Active Sensing. This message is intended to be sent
    // repeatedly to tell the receiver that a connection is alive. Use
    // of this message is optional. When initially received, the
    // receiver will expect to receive another Active Sensing
    // message each 300ms (max), and if it does not then it will
    // assume that the connection has been terminated. At
    // termination, the receiver will turn off all voices and return to
    // normal (non- active sensing) operation.
    if (Settings::UseSenderActiveSensing && (mSenderActiveSensingPeriodicity > 0) && (Platform::now() - mLastMessageSentTime) > mSenderActiveSensingPeriodicity)
    {
        sendActiveSensing();
        mLastMessageSentTime = Platform::now();
    }
    if (Settings::UseReceiverActiveSensing && mReceiverActiveSensingActivated && (mLastMessageReceivedTime + ActiveSensingTimeout < Platform::now()))
    {
        mReceiverActiveSensingActivated = false;
        mLastError |= 1UL << ErrorActiveSensingTimeout; // set the ErrorActiveSensingTimeout bit
        if (mErrorCallback)
            mErrorCallback(mLastError);
    }
    #endif
    if (inChannel >= MIDI_CHANNEL_OFF)
        return false; // MIDI Input disabled.
    if (!parse())
        return false;
    #ifndef RegionActiveSending
    if (Settings::UseReceiverActiveSensing && mMessage.type == ActiveSensing)
    {
        // When an ActiveSensing message is received, the time keeping is activated.
        // When a timeout occurs, an error message is send and time keeping ends.
        mReceiverActiveSensingActivated = true;
        // is ErrorActiveSensingTimeout bit in mLastError on
        if (mLastError & (1 << (ErrorActiveSensingTimeout - 1)))
        {
            mLastError &= ~(1UL << ErrorActiveSensingTimeout); // clear the ErrorActiveSensingTimeout bit
            if (mErrorCallback)
                mErrorCallback(mLastError);
        }
    }
    // Keep the time of the last received message, so we can check for the timeout
    if (Settings::UseReceiverActiveSensing && mReceiverActiveSensingActivated)
        mLastMessageReceivedTime = Platform::now();
    #endif
    handleNullVelocityNoteOnAsNoteOff();
    const bool channelMatch = inputFilter(inChannel);
    if (channelMatch)
        launchCallback();
    thruFilter(inChannel);
    return channelMatch;
}
References ActiveSensing, ActiveSensingTimeout, ErrorActiveSensingTimeout, handleNullVelocityNoteOnAsNoteOff(), inputFilter(), launchCallback(), mErrorCallback, MIDI_CHANNEL_OFF, mLastError, mLastMessageReceivedTime, mLastMessageSentTime, mMessage, mReceiverActiveSensingActivated, mSenderActiveSensingPeriodicity, parse(), sendActiveSensing(), and thruFilter().