FastLED: fl::s16x16::log2_fp
log2_fp()
static FASTLED_FORCE_INLINE s16x16 fl::s16x16::log2_fp (s16x16 x) inline static private
Definition at line 340 of file s16x16.h.
{
        u32 val = static_cast<u32>(x.mValue);
        int msb = highest_bit(val);
        i32 int_part = msb - FRAC_BITS;
        i32 t;
        if (msb >= FRAC_BITS) {
            t = static_cast<i32>(
                (val >> (msb - FRAC_BITS)) - (SCALE));
        } else {
            t = static_cast<i32>(
                (val << (FRAC_BITS - msb)) - (SCALE));
        }
        // 4-term minimax coefficients for log2(1+t), t in [0,1).
        // Stored as i64 with 24 fractional bits. Max product ~2^49, fits i64.
        constexpr int IFRAC = 24;
        constexpr i64 c0 = 24189248LL;  // 1.44179 * 2^24
        constexpr i64 c1 = -11728384LL; // -0.69907 * 2^24
        constexpr i64 c2 = 6098176LL;   // 0.36348 * 2^24
        constexpr i64 c3 = -1788416LL;  // -0.10660 * 2^24
        // Extend t from 16 to 24 frac bits.
        i64 t24 = static_cast<i64>(t) << (IFRAC - FRAC_BITS);
        // Horner: t * (c0 + t * (c1 + t * (c2 + t * c3)))
        i64 acc = c3;
        acc = c2 + ((acc * t24) >> IFRAC);
        acc = c1 + ((acc * t24) >> IFRAC);
        acc = c0 + ((acc * t24) >> IFRAC);
        i64 frac_part = (acc * t24) >> IFRAC;
        // Convert from 24 frac bits back to 16.
        i32 frac16 = static_cast<i32>(frac_part >> (IFRAC - FRAC_BITS));
        return from_raw(static_cast<i32>(static_cast<u32>(int_part) << FRAC_BITS) + frac16);
    }
References s16x16(), FASTLED_FORCE_INLINE, FL_NOEXCEPT, FRAC_BITS, from_raw(), highest_bit(), SCALE, fl::t, and fl::x.
Referenced by pow().