FastLED: fl::s16x16::exp2_fp
exp2_fp()
static FASTLED_FORCE_INLINE s16x16 fl::s16x16::exp2_fp (s16x16 x) inline static private
Definition at line 375 of file s16x16.h.
{
        s16x16 fl_val = floor(x);
        s16x16 fr = x - fl_val;
        i32 n = fl_val.mValue >> FRAC_BITS;
        if (n >= INT_BITS - 1) return from_raw(0x7FFFFFFF);
        if (n < -FRAC_BITS) return s16x16();
        i32 int_pow;
        if (n >= 0) {
            int_pow = static_cast<i32>(SCALE) << n;
        } else {
            int_pow = static_cast<i32>(SCALE) >> (-n);
        }
        // 4-term minimax coefficients for 2^t - 1, t in [0,1).
        // Stored as i64 with 24 fractional bits. Max product ~2^48, fits i64.
        constexpr int IFRAC = 24;
        constexpr i64 d0 = 11629376LL;  // 0.69316 * 2^24
        constexpr i64 d1 = 4038400LL;   // 0.24071 * 2^24
        constexpr i64 d2 = 895232LL;    // 0.05336 * 2^24
        constexpr i64 d3 = 214016LL;    // 0.01276 * 2^24
        // Extend fr from 16 to 24 frac bits.
        i64 fr24 = static_cast<i64>(fr.mValue) << (IFRAC - FRAC_BITS);
        // Horner: 1 + fr * (d0 + fr * (d1 + fr * (d2 + fr * d3)))
        i64 acc = d3;
        acc = d2 + ((acc * fr24) >> IFRAC);
        acc = d1 + ((acc * fr24) >> IFRAC);
        acc = d0 + ((acc * fr24) >> IFRAC);
        constexpr i64 one24 = 1LL << IFRAC;
        i64 frac_pow24 = one24 + ((acc * fr24) >> IFRAC);
        // Convert from 24 frac bits to 16 frac bits, then scale by int_pow.
        i32 frac_pow16 = static_cast<i32>(frac_pow24 >> (IFRAC - FRAC_BITS));
        i64 result =
            (static_cast<i64>(int_pow) * frac_pow16) >> FRAC_BITS;
        return from_raw(static_cast<i32>(result));
    }
References s16x16(), FASTLED_FORCE_INLINE, FL_NOEXCEPT, floor(), FRAC_BITS, from_raw(), INT_BITS, mValue, SCALE, and fl::x.
Referenced by pow().