FastLED: fl::json::operator[]
operator[]() [4/4]
json fl::json::operator[] (size_t idx) inline
Definition at line 538 of file json.h.
{
        if (!mValue) {
            mValue = fl::make_shared<json_value>(json_array{});
        }
        // If we're indexing into a specialized array, convert it to regular json_array first
        if (mValue->data.is<fl::vector<i16>>() ||
            mValue->data.is<fl::vector<u8>>() ||
            mValue->data.is<fl::vector<float>>()) {
            // Convert to regular json_array (needs a copy/conversion)
            auto arr = mValue->clone_array();
            if (arr) {
                mValue = fl::make_shared<json_value>(fl::move(*arr));
            }
        }
        // Get pointer directly to avoid copying - fixes silent mutation bug
        auto arrPtr = mValue->as_array();
        if (arrPtr) {
            // Ensure the array is large enough
            if (idx >= arrPtr->size()) {
                for (size_t i = arrPtr->size(); i <= idx; i++) {
                    arrPtr->push_back(fl::make_shared<json_value>(nullptr));
                }
            }
            return json((*arrPtr)[idx]);
        }
References json(), FL_NOEXCEPT, fl::make_shared(), fl::fl::move(), and mValue.