FastLED: fl::json::set
set() [4/10]
void fl::json::set (const fl::string & key, const json & value) inline
Definition at line 701 of file json.h.
{
        if (!mValue || !mValue->is_object()) {
            mValue = fl::make_shared<json_value>(json_object{});
        }
        // Directly assign the value to the object without going through json::operator[]
        auto objPtr = mValue->data.ptr<json_object>();
        if (objPtr) {
            // Create or update the entry directly
            if (value.mValue) {
                (*objPtr)[key] = value.mValue;
            } else {
                // If value has null mValue, create a null json_value
                (*objPtr)[key] = fl::make_shared<json_value>(nullptr);
            }
References json(), FL_NOEXCEPT, fl::make_shared(), mValue, and value().
Referenced by AutoResearchRemoteControl::findConnectedPinsImpl(), fl::WLED::getPlaylistConfig(), fl::WLED::getState(), fl::Rpc::handle(), loop(), fl::detail::makeJsonRpcError(), makeResponse(), anonymous_namespace{AutoResearchRemote.cpp}::measureTightTiming(), fl::Remote::processRpc(), AutoResearchRemoteControl::registerAllMethods(), AutoResearchRemoteControl::registerFunctions(), fl::Remote::reportError(), fl::Remote::reportError(), fl::net::http::HttpStreamTransport::rpc(), fl::net::http::HttpStreamTransport::rpcStream(), AutoResearchRemoteControl::runParallelTestImpl(), AutoResearchRemoteControl::runSingleTestImpl(), fl::Rpc::schema(), fl::ResponseSend::sendFinal(), fl::net::http::HttpStreamTransport::sendHeartbeat(), fl::Remote::sendStreamFinal(), fl::Remote::sendStreamUpdate(), set(), setup(), fl::RpcResult::to_json(), and fl::ScreenMap::toJson().