FastLED: fl::audio::detector::Percussion::computeFeatures
computeFeatures()
void fl::audio::detector::Percussion::computeFeatures (const fft::Bins & fft) private
Definition at line 146 of file percussion.cpp.hpp.
{
    auto bins = fft.raw();
    int n = static_cast<int>(bins.size());
    if (n < 16) {
        mBassToTotal = 0.0f;
        mTrebleToTotal = 0.0f;
        mClickRatio = 0.0f;
        mTrebleFlatness = 0.0f;
        mMidToTreble = 0.0f;
        mSubBassProxy = 0.0f;
        return;
    }
    // Frequency-based band boundaries (range-agnostic).
    // Bass: fmin–300 Hz  (kick body, sub-bass)
    // Mid:  300–2000 Hz  (snare body, tom)
    // Treble: 2000+ Hz   (click transients, hi-hat, cymbals)
    // Click: 1500–4500 Hz (kick beater attack, snare crack)
    int bassCutBin = fl::max(1, fft.freqToBin(300.0f));
    int trebleCutBin = fl::max(bassCutBin + 1, fft.freqToBin(2000.0f));
    int clickLoBin = fl::max(bassCutBin, fft.freqToBin(1500.0f));
    int clickHiBin = fl::min(n - 1, fft.freqToBin(4500.0f));
    float bassSum = 0.0f;
    for (int i = 0; i <= bassCutBin; ++i) bassSum += bins[i];
    float midSum = 0.0f;
    for (int i = bassCutBin + 1; i < trebleCutBin; ++i) midSum += bins[i];
    float trebleSum = 0.0f;
    for (int i = trebleCutBin; i < n; ++i) trebleSum += bins[i];
    // Click band: 1500–4500 Hz (kick click, snare crack)
    float clickBandSum = 0.0f;
    for (int i = clickLoBin; i <= clickHiBin; ++i) clickBandSum += bins[i];
    // Upper-mid for click ratio denominator
    float upperMidSum = midSum;
    float total = bassSum + midSum + trebleSum;
    // Bass/Total ratio
    mBassToTotal = (total > 1e-6f) ? bassSum / total : 0.0f;
    // Treble/Total ratio
    mTrebleToTotal = (total > 1e-6f) ? trebleSum / total : 0.0f;
    // Click ratio: treble click band vs upper-mid notch region
    mClickRatio = (upperMidSum > 1e-6f) ? clickBandSum / upperMidSum : 0.0f;
    // Mid/Treble ratio
    mMidToTreble = (trebleSum > 1e-6f) ? midSum / trebleSum : 0.0f;
    // Sub-bass proxy: lowest bin / first mid bin
    int firstMidBin = bassCutBin + 1;
    mSubBassProxy = (firstMidBin < n && bins[firstMidBin] > 1e-6f)
                        ? bins[0] / bins[firstMidBin]
                        : 0.0f;
    // Treble flatness: geometric_mean / arithmetic_mean of treble bins
    int trebleBinCount = n - trebleCutBin;
    float trebleArithMean = (trebleBinCount > 0) ? trebleSum / static_cast<float>(trebleBinCount) : 0.0f;
    if (trebleArithMean > 1e-6f) {
        float sumLog = 0.0f;
        int validCount = 0;
        for (int i = trebleCutBin; i < n; ++i) {
            if (bins[i] > 1e-6f) {
                sumLog += fl::logf(bins[i]);
                ++validCount;
            }
        }
        if (validCount > 0) {
            float geoMean = fl::expf(sumLog / static_cast<float>(validCount));
            mTrebleFlatness = geoMean / trebleArithMean;
        } else {
            mTrebleFlatness = 0.0f;
        }
    } else {
        mTrebleFlatness = 0.0f;
    }
}
References fl::expf(), fl::logf(), fl::max(), mBassToTotal, mClickRatio, fl::min(), mMidToTreble, mSubBassProxy, mTrebleFlatness, and mTrebleToTotal.
Referenced by update().