FastLED: fl::audio::detector::Percussion::update
update() [2/2]
void fl::audio::detector::Percussion::update (shared_ptr< Context > context) override virtual
Implements fl::audio::Detector.
Definition at line 42 of file percussion.cpp.hpp.
{
    mRetainedFFT = context->getFFT16(fft::Mode::CQ_NAIVE);
    const fft::Bins& fft = *mRetainedFFT;
    u32 timestamp = context->getTimestamp();
    // Step 0: Get zero-crossing factor from raw audio sample
    mZeroCrossingFactor = context->getZCF();
    // Step 1: Compute spectral features from 16-bin fft::FFT
    computeFeatures(fft);
    // Step 2: Compute total energy and onset sharpness via envelope
    float totalEnergy = 0.0f;
    for (fl::size i = 0; i < fft.raw().size(); ++i) {
        totalEnergy += fft.raw()[i];
    }
    const float dt = computeAudioDt(context->getPCM().size(), context->getSampleRate());
    float envValue = mTotalEnvelope.update(totalEnergy, dt);
    float flux = fl::max(0.0f, totalEnergy - envValue);
    mOnsetSharpness = (totalEnergy > 1e-6f) ? flux / totalEnergy : 0.0f;
    // Step 3: Gate on onset — no onset means no percussion
    static constexpr float kOnsetGate = 0.05f;
    if (mOnsetSharpness < kOnsetGate) {
        mKickDetected = false;
        mSnareDetected = false;
        mHiHatDetected = false;
        mTomDetected = false;
        mKickConfidence = 0.0f;
        mSnareConfidence = 0.0f;
        mHiHatConfidence = 0.0f;
        mTomConfidence = 0.0f;
        return;
    }
    // Step 4: Compute per-type confidence scores
    computeConfidences();
    // Step 5: Apply cross-band rejection
    applyCrossBandRejection();
    // Step 6: Threshold + cooldown → boolean state
    mKickDetected = (mKickConfidence >= mKickThreshold) &&
                    (timestamp - mLastKickTime >= KICK_COOLDOWN_MS);
    mSnareDetected = (mSnareConfidence >= mSnareThreshold) &&
                     (timestamp - mLastSnareTime >= SNARE_COOLDOWN_MS);
    mHiHatDetected = (mHiHatConfidence >= mHiHatThreshold) &&
                     (timestamp - mLastHiHatTime >= HIHAT_COOLDOWN_MS);
    mTomDetected = (mTomConfidence >= mTomThreshold) &&
                   (timestamp - mLastTomTime >= TOM_COOLDOWN_MS);
    // Update timestamps
    if (mKickDetected) mLastKickTime = timestamp;
    if (mSnareDetected) mLastSnareTime = timestamp;
    if (mHiHatDetected) mLastHiHatTime = timestamp;
    if (mTomDetected) mLastTomTime = timestamp;
}
References Percussion(), applyCrossBandRejection(), fl::audio::computeAudioDt(), computeConfidences(), computeFeatures(), fl::audio::fft::CQ_NAIVE, HIHAT_COOLDOWN_MS, KICK_COOLDOWN_MS, fl::max(), mHiHatConfidence, mHiHatDetected, mHiHatThreshold, mKickConfidence, mKickDetected, mKickThreshold, mLastHiHatTime, mLastKickTime, mLastSnareTime, mLastTomTime, mOnsetSharpness, mRetainedFFT, mSnareConfidence, mSnareDetected, mSnareThreshold, mTomConfidence, mTomDetected, mTomThreshold, mTotalEnvelope, mZeroCrossingFactor, SNARE_COOLDOWN_MS, TOM_COOLDOWN_MS, and update().
Referenced by ~Percussion(), update(), and update().