FastLED: fl::audio::detector::Percussion::computeConfidences
computeConfidences()
void fl::audio::detector::Percussion::computeConfidences () private
Definition at line 228 of file percussion.cpp.hpp.
{
    // Feature distributions with frequency-based bands (90-14080 Hz, 16 CQ bins):
    //
    // Type     | bassToTotal | trebleToTotal | clickRatio | trebleFlatness | midToTreble | subBassProxy
    // ---------|-------------|---------------|------------|----------------|-------------|-------------
    // Kick     |   0.30-0.45 |    0.30-0.50  |  1.0-2.0   |   0.9-1.0      |   0.5-0.9   |   0.5-3
    // Snare    |   0.10-0.25 |    0.55-0.75  |  1.5-2.5   |   0.9-1.0      |   0.2-0.5   |   0.0-0.2
    // HiHat    |   0.03-0.10 |    0.70-0.90  |  2.5-5.0   |   0.9-1.0      |   0.1-0.2   |   0.2-1.5
    // Tom      |   0.25-0.45 |    0.30-0.50  |  0.8-1.5   |   0.9-1.0      |   0.5-1.0   |   0.0-0.3
    // Kick: bass-dominant with high sub-bass proxy (distinguishes from tom)
    // Key discriminants from tom: subBassProxy (kick > 0.5, tom < 0.3)
    {
        // Bass score: peaks at 0.35 (kick range 0.25-0.50)
        float bassScore = fl::max(0.0f, 1.0f - fl::abs(mBassToTotal - 0.35f) / 0.20f);
        // Sub-bass proxy: kick has notable sub-bass energy (> 0.5)
        float subBassScore = fl::min(1.0f, mSubBassProxy / 2.0f);
        // Moderate treble (0.30-0.50 — higher than tom due to click)
        float trebleScore = fl::max(0.0f, 1.0f - fl::abs(mTrebleToTotal - 0.40f) / 0.20f);
        // ZCF: kick has low-moderate zero crossings (~0.1-0.4)
        float zcfScore = fl::max(0.0f, 1.0f - fl::abs(mZeroCrossingFactor - 0.25f) / 0.25f);
        mKickConfidence = 0.25f * bassScore + 0.35f * subBassScore +
                          0.20f * trebleScore + 0.20f * zcfScore;
    }
    // Snare: low-moderate bass + high treble from noise rattles
    {
        // Bass score: low bass (0.10-0.25) — lower than kick/tom
        float bassScore = fl::max(0.0f, 1.0f - fl::abs(mBassToTotal - 0.15f) / 0.15f);
        // Treble presence: snare has high treble (0.55-0.75)
        float trebleScore = fl::max(0.0f, 1.0f - fl::abs(mTrebleToTotal - 0.65f) / 0.20f);
        // Mid/Treble ratio: snare ~0.2-0.5 (moderate)
        float midTrebleScore = fl::max(0.0f, 1.0f - fl::abs(mMidToTreble - 0.30f) / 0.25f);
        // Very low sub-bass (< 0.2 — no body resonance)
        float noSubBassScore = fl::max(0.0f, 1.0f - mSubBassProxy / 0.5f);
        // ZCF: moderate (noise has many zero crossings)
        float zcfScore = fl::max(0.0f, (mZeroCrossingFactor - 0.20f) / 0.40f);
        zcfScore = fl::min(1.0f, zcfScore);
        mSnareConfidence = 0.20f * bassScore + 0.25f * trebleScore +
                           0.15f * midTrebleScore + 0.20f * noSubBassScore +
                           0.20f * zcfScore;
    }
    // HiHat: treble-dominant with high ZCF
    {
        // Treble dominance: hi-hat is mostly treble (0.70-0.90)
        float trebleScore = fl::max(0.0f, (mTrebleToTotal - 0.60f) / 0.30f);
        trebleScore = fl::min(1.0f, trebleScore);
        // No bass
        float noBassScore = fl::max(0.0f, 1.0f - mBassToTotal / 0.15f);
        // Very high click ratio (> 2.5 — all energy in click band)
        float highClickScore = fl::max(0.0f, (mClickRatio - 2.0f) / 3.0f);
        highClickScore = fl::min(1.0f, highClickScore);
        // ZCF: hi-hat has very high zero crossings (~0.5-0.8)
        float zcfScore = fl::max(0.0f, (mZeroCrossingFactor - 0.35f) / 0.45f);
        zcfScore = fl::min(1.0f, zcfScore);
        mHiHatConfidence = 0.30f * trebleScore + 0.20f * noBassScore +
                           0.25f * highClickScore + 0.25f * zcfScore;
    }
    // Tom: bass with NO sub-bass, low mid-to-treble discriminates from kick
    {
        // Moderate bass (0.25-0.45) — similar range to kick
        float bassScore = fl::max(0.0f, 1.0f - fl::abs(mBassToTotal - 0.35f) / 0.20f);
        // NO sub-bass: key discriminant from kick (tom < 0.3, kick > 0.5)
        float noSubBassScore = fl::max(0.0f, 1.0f - mSubBassProxy / 0.5f);
        // High mid-to-treble ratio (tom body resonance in mid)
        float midTrebleScore = fl::max(0.0f, (mMidToTreble - 0.50f) / 0.50f);
        midTrebleScore = fl::min(1.0f, midTrebleScore);
        // ZCF: tom has very low zero crossings (~0.05-0.15)
        float zcfScore = fl::max(0.0f, 1.0f - mZeroCrossingFactor / 0.25f);
        mTomConfidence = 0.25f * bassScore + 0.30f * noSubBassScore +
                         0.20f * midTrebleScore + 0.25f * zcfScore;
    }
    // Clamp all to [0, 1]
    mKickConfidence = fl::clamp(mKickConfidence, 0.0f, 1.0f);
    mSnareConfidence = fl::clamp(mSnareConfidence, 0.0f, 1.0f);
    mHiHatConfidence = fl::clamp(mHiHatConfidence, 0.0f, 1.0f);
    mTomConfidence = fl::clamp(mTomConfidence, 0.0f, 1.0f);
}
References fl::abs(), fl::clamp(), fl::max(), mBassToTotal, mClickRatio, mHiHatConfidence, fl::min(), mKickConfidence, mMidToTreble, mSnareConfidence, mSubBassProxy, mTomConfidence, mTrebleToTotal, and mZeroCrossingFactor.
Referenced by update().