FastLED: fl::anonymous_namespace{audio.cpp}::get_flex_fft
get_flex_fft()
FFT & fl::anonymous_namespace{audio.cpp}::get_flex_fft ()
Definition at line 9 of file audio.cpp.
                    {
    // This is a singleton for the FFT implementation.
    // It is used to avoid creating multiple FFT instances.
    static ThreadLocal<FFT> gFlexFFT;
    return gFlexFFT.access();
}
References fl::ThreadLocalFake< T >::access(), and get_flex_fft().
Referenced by get_flex_fft().