FastLED: fl::FlowFieldFloat::FlowFieldFloat
FlowFieldFloat()
fl::FlowFieldFloat::FlowFieldFloat (const XYMap & xyMap, const Params & params = Params()) explicit
Definition at line 118 of file flowfield.cpp.hpp.
    : FlowField(xyMap, params) {
    int w = (int)getWidth();
    int h = (int)getHeight();
    int n = w * h;
    mR.resize(n, 0.0f);
    mG.resize(n, 0.0f);
    mB.resize(n, 0.0f);
    mTR.resize(n, 0.0f);
    mTG.resize(n, 0.0f);
    mTB.resize(n, 0.0f);
    mXProf.resize(w, 0.0f);
    mYProf.resize(h, 0.0f);
    mNoiseGenX.init(42);
    mNoiseGenY.init(1337);
}
References fl::FlowField::FlowField(), fl::Fx2d::getHeight(), fl::Fx2d::getWidth(), mB, mG, mNoiseGenX, mNoiseGenY, mR, mTB, mTG, mTR, mXProf, mYProf, and fl::Fx2d::xyMap().