FastLED: fl::FlowFieldFloat::emitOrbitalDots
emitOrbitalDots()
void fl::FlowFieldFloat::emitOrbitalDots (float t) private
Definition at line 257 of file flowfield.cpp.hpp.
{
    int w = (int)getWidth();
    int h = (int)getHeight();
    int minDim = fl::min(w, h);
    int n = mParams.dot_count;
    float fn = (float)n;
    float ocx = w * 0.5f - 0.5f;
    float ocy = h * 0.5f - 0.5f;
    float orad = minDim * 0.35f;
    float base = t * 3.0f;
    float dotDiam = 1.5f;
    for (int i = 0; i < n; i++) {
        float a = base + i * (2.0f * FL_PI / fn);
        float cx = ocx + cosf(a) * orad;
        float cy = ocy + sinf(a) * orad;
        CRGB c = rainbow(t, mParams.color_shift, (float)i / fn);
        drawDot(cx, cy, dotDiam, c.r, c.g, c.b);
    }
}
References fl::cosf(), drawDot(), FL_PI, fl::Fx2d::getHeight(), fl::Fx2d::getWidth(), fl::min(), fl::FlowField::mParams, rainbow(), fl::sinf(), and fl::t.
Referenced by drawImpl().