FastLED: fl::FlowFieldFloat::drawImpl
drawImpl()
void fl::FlowFieldFloat::drawImpl (DrawContext context, u32 dt_ms, u32 t_ms) override protected virtual
Subclasses implement rendering given the time delta and total time.
Parameters
dt_ms Milliseconds since last draw (capped to prevent huge jumps).
t_ms Milliseconds since first draw.
Implements fl::FlowField.
Definition at line 434 of file flowfield.cpp.hpp.
{
    float dt = dt_ms * 0.001f;
    float t = t_ms * 0.001f;
    flowPrepare(t);
    switch (mParams.emitter_mode) {
    case 0:
        emitLissajousLine(t);
        break;
    case 1:
        emitOrbitalDots(t);
        break;
    case 2:
        emitLissajousLine(t);
        emitOrbitalDots(t);
        break;
    default:
        emitLissajousLine(t);
        break;
    }
    flowAdvect(dt);
    int w = (int)getWidth();
    int h = (int)getHeight();
    for (int y = 0; y < h; y++) {
        for (int x = 0; x < w; x++) {
            int ledIdx = mXyMap.mapToIndex(x, y);
            int i = idx(y, x);
            context.leds.data()[ledIdx].r = f2u8(mR[i]);
            context.leds.data()[ledIdx].g = f2u8(mG[i]);
            context.leds.data()[ledIdx].b = f2u8(mB[i]);
        }
    }
    if (mParams.show_flow_vectors) {
        drawFlowVectors(context.leds);
    }
}
References drawFlowVectors(), emitLissajousLine(), emitOrbitalDots(), f2u8(), flowAdvect(), flowPrepare(), fl::Fx2d::getHeight(), fl::Fx2d::getWidth(), idx(), fl::DrawContext::leds, mB, mG, fl::FlowField::mParams, mR, fl::Fx2d::mXyMap, fl::t, fl::x, and fl::y.