FastLED: fl::FlowFieldFloat::flowAdvect
flowAdvect()
void fl::FlowFieldFloat::flowAdvect (float dt) private
Definition at line 313 of file flowfield.cpp.hpp.
{
    int w = (int)getWidth();
    int h = (int)getHeight();
    float halfLife = fl::max(mParams.persistence, 0.001f);
    float fade = powf(0.5f, dt / halfLife);
    float shift = mParams.flow_shift;
    // Pass 1: horizontal row shift.
    for (int y = 0; y < h; y++) {
        float sh = mYProf[y] * shift;
        for (int x = 0; x < w; x++) {
            float sx = fmodPos((float)x - sh, (float)w);
            int ix0 = (int)floorf(sx) % w;
            int ix1 = (ix0 + 1) % w;
            float f = sx - floorf(sx);
            float inv = 1.0f - f;
            int src0 = idx(y, ix0);
            int src1 = idx(y, ix1);
            int dst = idx(y, x);
            mTR[dst] = mR[src0] * inv + mR[src1] * f;
            mTG[dst] = mG[src0] * inv + mG[src1] * f;
            mTB[dst] = mB[src0] * inv + mB[src1] * f;
        }
    }
    // Pass 2: vertical column shift + fade.
    for (int x = 0; x < w; x++) {
        float sh = mXProf[x] * shift;
        for (int y = 0; y < h; y++) {
            float sy = fmodPos((float)y - sh, (float)h);
            int iy0 = (int)floorf(sy) % h;
            int iy1 = (iy0 + 1) % h;
            float f = sy - floorf(sy);
            float inv = 1.0f - f;
            int src0 = idx(iy0, x);
            int src1 = idx(iy1, x);
            int dst = idx(y, x);
            mR[dst] = (mTR[src0] * inv + mTR[src1] * f) * fade;
            mG[dst] = (mTG[src0] * inv + mTG[src1] * f) * fade;
            mB[dst] = (mTB[src0] * inv + mTB[src1] * f) * fade;
        }
    }
}
References fl::fade(), fl::floorf(), fmodPos(), fl::Fx2d::getHeight(), fl::Fx2d::getWidth(), idx(), fl::max(), mB, mG, fl::FlowField::mParams, mR, mTB, mTG, mTR, mXProf, mYProf, fl::powf(), fl::x, and fl::y.
Referenced by drawImpl().