FastLED: fl::FlowFieldFloat::flowPrepare
flowPrepare()
void fl::FlowFieldFloat::flowPrepare (float t) private
Definition at line 277 of file flowfield.cpp.hpp.
{
    int w = (int)getWidth();
    int h = (int)getHeight();
    const float kBaseFreq = 0.23f;
    for (int i = 0; i < w; i++) {
        float v = mNoiseGenX.noise(
            i * kBaseFreq * mParams.noise_freq_x + t * mParams.flow_speed_x,
            0.0f);
        mXProf[i] = clampf(v * mParams.flow_amp_x, -1.0f, 1.0f);
    }
    if (mParams.reverse_x_profile) {
        for (int i = 0; i < w / 2; i++) {
            float tmp = mXProf[i];
            mXProf[i] = mXProf[w - 1 - i];
            mXProf[w - 1 - i] = tmp;
        }
    }
    for (int i = 0; i < h; i++) {
        float v = mNoiseGenY.noise(
            i * kBaseFreq * mParams.noise_freq_y + t * mParams.flow_speed_y,
            0.0f);
        mYProf[i] = clampf(v * mParams.flow_amp_y, -1.0f, 1.0f);
    }
    // Apply noise bias (attack/decay bumps from noisePunch triggers).
    for (int i = 0; i < w; i++) {
        mXProf[i] = clampf(mXProf[i] + mNoiseBias.getX(i), -1.0f, 1.0f);
    }
    for (int i = 0; i < h; i++) {
        mYProf[i] = clampf(mYProf[i] + mNoiseBias.getY(i), -1.0f, 1.0f);
    }
}
References clampf(), fl::Fx2d::getHeight(), fl::Fx2d::getWidth(), fl::FlowField::mNoiseBias, mNoiseGenX, mNoiseGenY, fl::FlowField::mParams, mXProf, mYProf, and fl::t.
Referenced by drawImpl().