// This file includes all FastLED implementation files for allsrc build.
// All .cpp files have been converted to .hpp files to enable header-only builds
// across all platforms without conditional compilation.

// FL library implementation files
#include "fl/allocator.hpp"
#if !(defined(__arm__) && defined(TEENSYDUINO))
// Audio functionality has static initialization conflicts with Teensy framework
#include "fl/audio.hpp"
#endif
#include "fl/blur.hpp"
#include "fl/bytestreammemory.hpp"
#include "fl/colorutils.hpp"
#include "fl/corkscrew.hpp"
#include "fl/downscale.hpp"
#include "fl/ease.hpp"
#include "fl/engine_events.hpp"
#include "fl/fft.hpp"
#include "fl/fft_impl.hpp"
#include "fl/file_system.hpp"
#include "fl/fill.hpp"
#include "fl/gamma.hpp"
#include "fl/gradient.hpp"
#include "fl/hsv16.hpp"
#include "fl/io.hpp"
#include "fl/istream.hpp"
#include "fl/json.hpp"
#include "fl/json_console.hpp"
#include "fl/leds.hpp"
#include "fl/line_simplification.hpp"
#include "fl/noise_woryley.hpp"
#include "fl/ostream.hpp"
#include "fl/ptr.hpp"
#include "fl/raster_sparse.hpp"
#include "fl/rectangular_draw_buffer.hpp"
#include "fl/screenmap.hpp"
#include "fl/sin32.hpp"
#include "fl/splat.hpp"
#include "fl/str.hpp"
#include "fl/strstream.hpp"
#include "fl/stub_main.hpp"
#include "fl/tile2x2.hpp"
#include "fl/time_alpha.hpp"
#include "fl/transform.hpp"
#include "fl/type_traits.hpp"
#include "fl/ui.hpp"
#include "fl/upscale.hpp"
#include "fl/wave_simulation.hpp"
#include "fl/wave_simulation_real.hpp"
#include "fl/xmap.hpp"
#include "fl/xymap.hpp"
#include "fl/xypath.hpp"
#include "fl/xypath_impls.hpp"
#include "fl/xypath_renderer.hpp"

// Sensors
#include "sensors/button.hpp"
#include "sensors/digital_pin.hpp"
#include "sensors/pir.hpp"
