// FastLED All Source Build File
// This file includes all .cpp.hpp files for unified compilation
// Generated automatically by scripts/all_source_build.py

#include "fl/compiler_control.h"

#if FASTLED_ALL_SRC

#include "fl/allocator.cpp.hpp"
#include "fl/ptr.cpp.hpp"
#include "fl/str.cpp.hpp"
#include "fl/io.cpp.hpp"
#include "fl/engine_events.cpp.hpp"
#include "fl/wave_simulation.cpp.hpp"
#include "fl/xymap.cpp.hpp"
#include "fl/colorutils.cpp.hpp"
#include "fl/tile2x2.cpp.hpp"
#include "fl/corkscrew.cpp.hpp"
#include "fl/gradient.cpp.hpp"
#include "fl/ease.cpp.hpp"
#include "fl/wave_simulation_real.cpp.hpp"
#include "fl/screenmap.cpp.hpp"
#include "fl/splat.cpp.hpp"
#include "fx/fx_engine.cpp.hpp"
#include "fx/time.cpp.hpp"
#include "fx/2d/blend.cpp.hpp"
#include "fx/2d/wave.cpp.hpp"
#include "fl/fill.cpp.hpp"
#include "fx/frame.cpp.hpp"
#include "fx/detail/fx_layer.cpp.hpp"
#include "fl/blur.cpp.hpp"
#include "fx/video.cpp.hpp"
#include "fl/crgb_hsv16.cpp.hpp"
#include "fl/ui.cpp.hpp"
#include "fx/video/video_impl.cpp.hpp"
#include "fl/transform.cpp.hpp"
#include "fl/noise_woryley.cpp.hpp"
#include "fl/hsv16.cpp.hpp"
#include "fl/xmap.cpp.hpp"
#include "fx/video/pixel_stream.cpp.hpp"
#include "fx/video/frame_interpolator.cpp.hpp"
#include "fx/video/frame_tracker.cpp.hpp"
#include "fl/bytestreammemory.cpp.hpp"
#include "fl/leds.cpp.hpp"
#include "fl/audio.cpp.hpp"
#include "fl/json.cpp.hpp"
#include "fl/random.cpp.hpp"
#include "fl/gamma.cpp.hpp"
#include "fl/istream.cpp.hpp"
#include "fl/ostream.cpp.hpp"
#include "fl/file_system.cpp.hpp"
#include "fl/strstream.cpp.hpp"
#include "fl/line_simplification.cpp.hpp"
#include "fl/downscale.cpp.hpp"
#include "fl/upscale.cpp.hpp"
#include "fl/xypath.cpp.hpp"
#include "fl/xypath_impls.cpp.hpp"
#include "fl/sin32.cpp.hpp"
#include "fl/audio_reactive.cpp.hpp"
#include "fl/fft.cpp.hpp"
#include "fl/fft_impl.cpp.hpp"
#include "fl/raster_sparse.cpp.hpp"
#include "fl/xypath_renderer.cpp.hpp"
#include "fl/rectangular_draw_buffer.cpp.hpp"
#include "fl/json_console.cpp.hpp"
#include "fl/time_alpha.cpp.hpp"
#include "fl/stub_main.cpp.hpp"

// Platform implementations (auto-generated)
#include "platforms/arm/k20/clockless_objectfled.cpp.hpp"
#include "platforms/avr/avr_millis_timer_source.cpp.hpp"
#include "platforms/compile_test.cpp.hpp"
#include "platforms/esp/32/clockless_i2s_esp32s3.cpp.hpp"
#include "platforms/esp/32/i2s/i2s_esp32dev.cpp.hpp"
#include "platforms/esp/32/rmt_4/idf4_rmt.cpp.hpp"
#include "platforms/esp/32/rmt_4/idf4_rmt_impl.cpp.hpp"
#include "platforms/esp/32/rmt_5/idf5_rmt.cpp.hpp"
#include "platforms/esp/32/rmt_5/strip_rmt.cpp.hpp"
#include "platforms/esp/32/spi_ws2812/strip_spi.cpp.hpp"
#include "platforms/shared/ui/json/audio.cpp.hpp"
#include "platforms/shared/ui/json/button.cpp.hpp"
#include "platforms/shared/ui/json/checkbox.cpp.hpp"
#include "platforms/shared/ui/json/description.cpp.hpp"
#include "platforms/shared/ui/json/dropdown.cpp.hpp"
#include "platforms/shared/ui/json/help.cpp.hpp"
#include "platforms/shared/ui/json/number_field.cpp.hpp"
#include "platforms/shared/ui/json/slider.cpp.hpp"
#include "platforms/shared/ui/json/title.cpp.hpp"
#include "platforms/shared/ui/json/ui.cpp.hpp"
#include "platforms/shared/ui/json/ui_internal.cpp.hpp"
#include "platforms/shared/ui/json/ui_manager.cpp.hpp"
#include "platforms/stub/led_sysdefs_stub.cpp.hpp"
#include "platforms/wasm/active_strip_data.cpp.hpp"
#include "platforms/wasm/compiler/Arduino.cpp.hpp"
#include "platforms/wasm/engine_listener.cpp.hpp"
#include "platforms/wasm/fastspi_wasm.cpp.hpp"
#include "platforms/wasm/fs_wasm.cpp.hpp"
#include "platforms/wasm/js.cpp.hpp"
#include "platforms/wasm/js_bindings.cpp.hpp"
#include "platforms/wasm/timer.cpp.hpp"
#include "platforms/wasm/ui.cpp.hpp"

// Third-party implementations (auto-generated, excluding FFT)
#include "third_party/object_fled/src/OjectFLED.cpp.hpp"

// SENSORS MODULE (hierarchical)
#ifdef FASTLED_ALL_SRC
#include "sensors/sensors_compile.hpp"
#endif // FASTLED_ALL_SRC



#endif // FASTLED_ALL_SRC
