// FastLED All Source Build File
// This file includes all .cpp.hpp files for unified compilation
// Generated automatically by scripts/all_source_build.py

#include "fl/compiler_control.h"

#if FASTLED_ALL_SRC

#include "fl/allocator.cpp.hpp"
#include "fl/ptr.cpp.hpp"
#include "fl/str.cpp.hpp"
#include "fl/io.cpp.hpp"
#include "fl/engine_events.cpp.hpp"
#include "fl/wave_simulation.cpp.hpp"
#include "fl/xymap.cpp.hpp"
#include "fl/colorutils.cpp.hpp"
#include "fl/tile2x2.cpp.hpp"
#include "fl/corkscrew.cpp.hpp"
#include "fl/gradient.cpp.hpp"
#include "fl/ease.cpp.hpp"
#include "fl/wave_simulation_real.cpp.hpp"
#include "fl/screenmap.cpp.hpp"
#include "fl/splat.cpp.hpp"
#include "fx/fx_engine.cpp.hpp"
#include "fx/time.cpp.hpp"
#include "fx/2d/blend.cpp.hpp"
#include "fx/2d/wave.cpp.hpp"
#include "sensors/button.cpp.hpp"
#include "fl/fill.cpp.hpp"
#include "sensors/digital_pin.cpp.hpp"
#include "fx/frame.cpp.hpp"
#include "fx/detail/fx_layer.cpp.hpp"
#include "fl/blur.cpp.hpp"
#include "fx/video.cpp.hpp"
#include "fl/crgb_hsv16.cpp.hpp"
#include "fl/ui.cpp.hpp"
#include "fx/video/video_impl.cpp.hpp"
#include "fl/transform.cpp.hpp"
#include "fl/noise_woryley.cpp.hpp"
#include "fl/hsv16.cpp.hpp"
#include "fl/xmap.cpp.hpp"
#include "fx/video/pixel_stream.cpp.hpp"
#include "fx/video/frame_interpolator.cpp.hpp"
#include "fx/video/frame_tracker.cpp.hpp"
#include "fl/bytestreammemory.cpp.hpp"
#include "fl/leds.cpp.hpp"
#include "fl/audio.cpp.hpp"
#include "fl/json.cpp.hpp"
#include "fl/random.cpp.hpp"
#include "fl/gamma.cpp.hpp"
#include "fl/istream.cpp.hpp"
#include "fl/ostream.cpp.hpp"
#include "fl/file_system.cpp.hpp"
#include "fl/strstream.cpp.hpp"
#include "fl/line_simplification.cpp.hpp"
#include "fl/downscale.cpp.hpp"
#include "fl/upscale.cpp.hpp"
#include "fl/xypath.cpp.hpp"
#include "fl/xypath_impls.cpp.hpp"
#include "fl/sin32.cpp.hpp"
#include "fl/audio_reactive.cpp.hpp"
#include "fl/fft.cpp.hpp"
#include "fl/fft_impl.cpp.hpp"
#include "fl/raster_sparse.cpp.hpp"
#include "fl/xypath_renderer.cpp.hpp"
#include "fl/rectangular_draw_buffer.cpp.hpp"
#include "fl/json_console.cpp.hpp"
#include "fl/time_alpha.cpp.hpp"
#include "fl/stub_main.cpp.hpp"

#endif // FASTLED_ALL_SRC
