FastLED: fl::ScopedTrace::push
push()
void fl::ScopedTrace::push (const char * function, int line) static
Push a function name onto the call stack.
Parameters
function Function name (must be string literal or have static lifetime)
line Line number (from LINE)
Definition at line 53 of file trace.cpp.hpp.
{
    if (!function) {
        return;  // Ignore null function names
    }
    auto& storage = getTraceStorage();
    // Always increment depth counter (tracks true depth even on overflow)
    storage.stackDepth++;
    // Only push to storage if we have capacity
    if (storage.callStack.size() < FL_STACK_TRACE_MAX_DEPTH) {
        storage.callStack.push_back(TraceEntry(function, line));
    }
    // If size >= MAX_DEPTH, we're in overflow - just track depth
}
References FL_NOEXCEPT, FL_STACK_TRACE_MAX_DEPTH, and fl::getTraceStorage().
Referenced by ScopedTrace(), and operator=().