FastLED: loop
loop()
void loop ()
Definition at line 173 of file LuminescentGrand.ino.
            {
  //FL_DBG("loop");
  // Calculate dt.
  static uint32_t s_prev_time = 0;
  uint32_t prev_time = 0;
  FASTLED_UNUSED(prev_time);  // actually used in perf tests.
  uint32_t now_ms = fl::millis();
  uint32_t delta_ms = now_ms - s_prev_time;
  s_prev_time = now_ms;
  if (!is_debugging) {
    if (Serial.available() > 0) {
      int v = Serial.read();
      if (v == 'd') {
        is_debugging = true;
      }
    }
  }
  DbgDoSimulatedKeyboardPress();
  const unsigned long start_time = fl::millis();
  // Each frame we call the midi processor 100 times to make sure that all notes
  // are processed.
  for (int i = 0; i < 100; ++i) {
    MY_MIDI.read();
  }
  const unsigned long midi_time = fl::millis() - start_time;
  // Updates keyboard: releases sustained keys that.
  const uint32_t keyboard_time_start = fl::millis();
  // This is kind of a hack... but give the keyboard a future time
  // so that all keys just pressed get a value > 0 for their time
  // durations.
  keyboard.Update(now_ms + delta_ms, delta_ms);
  const uint32_t keyboard_delta_time = fl::millis() - keyboard_time_start;
  ui_state ui_st = ui_update(now_ms, delta_ms);
  //dprint("vis selector = ");
  //dprintln(vis_state);
  // These int values are for desting the performance of the
  // app. If the app ever runs slow then set kShowFps to 1
  // in the settings.h file.
  const unsigned long start_painting = fl::millis();
  FASTLED_UNUSED(start_painting);
  // Paints the keyboard using the led_rope.
  Painter::VisState which_vis = Painter::VisState(ui_st.which_visualizer);
  Painter::Paint(now_ms, delta_ms, which_vis, &keyboard, &led_rope);
  const unsigned long paint_time = fl::millis() - start_time;
  const unsigned long total_time = midi_time + paint_time + keyboard_delta_time;
  if (kShowFps) {
    float fps = 1.0f/(float(total_time) / 1000.f);
    Serial.print("fps                  - "); Serial.println(fps);
    Serial.print("midi time            - "); Serial.println(midi_time);
    Serial.print("keyboard update time - "); Serial.println(keyboard_delta_time);
    Serial.print("draw & paint time    - "); Serial.println(paint_time);
  }
  EVERY_N_SECONDS(1) {
    FL_DBG("is_debugging = " << is_debugging);
  }
  FastLED.show();
}
References DbgDoSimulatedKeyboardPress(), EVERY_N_SECONDS, FastLED, FASTLED_UNUSED, FL_DBG, is_debugging, keyboard, kShowFps, led_rope, fl::millis(), Painter::Paint(), Serial, ui_update(), and ui_state::which_visualizer.