FastLED: DbgDoSimulatedKeyboardPress
DbgDoSimulatedKeyboardPress()
void DbgDoSimulatedKeyboardPress ()
Definition at line 139 of file LuminescentGrand.ino.
{
#ifdef DEBUG_FORCED_KEYBOARD
  static uint32_t start_time = 0;
  static bool toggle = 0;
  const uint32_t time_on = 25;
  const uint32_t time_off = 500;
  // Just force it on whenever this function is called.
  is_debugging = true;
  uint32_t now = fl::millis();
  uint32_t delta_time = now - start_time;
  uint32_t threshold_time = toggle ? time_off : time_on;
  if (delta_time < threshold_time) {
    return;
  }
  int random_key = random(0, 88);
  start_time = now;
  if (toggle) {
    HandleNoteOn(0, random_key, 64);
  } else {
    HandleNoteOff(0, random_key, 82);
  }
  toggle = !toggle;
#endif
}
References HandleNoteOff(), HandleNoteOn(), is_debugging, fl::millis(), and toggle.
Referenced by loop().