FastLED: HandleNoteOn
HandleNoteOn()
void HandleNoteOn (byte channel, byte midi_note, byte velocity)
Definition at line 69 of file LuminescentGrand.ino.
{
  FL_UNUSED(channel);
  FL_DBG("HandleNoteOn: midi_note = " << int(midi_note) << ", velocity = " << int(velocity));
  keyboard.HandleNoteOn(midi_note, velocity, color_selector.curr_val(), fl::millis());
}
References color_selector, FL_DBG, FL_UNUSED, keyboard, and fl::millis().
Referenced by DbgDoSimulatedKeyboardPress(), and setup().