FastLED: fl::test::detail::getTypeName
getTypeName()
template<typename T> fl::string fl::test::detail::getTypeName () inline
Definition at line 1751 of file fltest.h.
{
#if defined(__clang__) || defined(__GNUC__)
    // FL_PRETTY_FUNCTION format: "fl::string fl::test::detail::getTypeName() [T = int]"
    const char* func = FL_PRETTY_FUNCTION;
    const char* begin = func;
    // Find "T = "
    while (*begin && !(begin[0] == 'T' && begin[1] == ' ' && begin[2] == '=' && begin[3] == ' '))
        ++begin;
    if (*begin) {
        begin += 4;  // Skip "T = "
        const char* end = begin;
        int depth = 0;
        while (*end) {
            if (*end == '<') ++depth;
            else if (*end == '>') {
                if (depth == 0) break;
                --depth;
            }
            else if (*end == ']' && depth == 0) break;
            ++end;
        }
        return fl::string(begin, static_cast<fl::size>(end - begin));
    }
#elif defined(_MSC_VER)
    // FL_PRETTY_FUNCTION format: "class fl::string __cdecl fl::test::detail::getTypeName<int>(void)"
    const char* func = FL_PRETTY_FUNCTION;
    const char* begin = func;
    // Find "getTypeName<"
    while (*begin && !(begin[0] == 'g' && begin[1] == 'e' && begin[2] == 't' && begin[3] == 'T' &&
                       begin[4] == 'y' && begin[5] == 'p' && begin[6] == 'e' && begin[7] == 'N' &&
                       begin[8] == 'a' && begin[9] == 'm' && begin[10] == 'e' && begin[11] == '<'))
        ++begin;
    if (*begin) {
        begin += 12;  // Skip "getTypeName<"
        const char* end = begin;
        int depth = 1;  // We're inside the first <
        while (*end && depth > 0) {
            if (*end == '<') ++depth;
            else if (*end == '>') --depth;
            ++end;
        }
        if (end > begin && depth == 0) --end;  // Back up before final >
        return fl::string(begin, static_cast<fl::size>(end - begin));
    }
#endif
    return fl::string("{unknown}");
}
References fl::begin(), fl::end(), FL_NOEXCEPT, FL_PRETTY_FUNCTION, and getTypeName().
Referenced by getTypeName(), and fl::test::detail::TypeNameHolder< T >::name().