FastLED: fl::FileSystem::openMp3
openMp3()
fl::Mp3DecoderPtr fl::FileSystem::openMp3 (const char * path, fl::string * error_message = nullptr)
Definition at line 142 of file file_system_codecs.cpp.hpp.
{
    fl::ifstream file = openRead(path);
    if (!file.is_open()) {
        if (error_message) { *error_message = "Failed to open file: "; error_message->append(path); }
        FL_WARN("Failed to open MP3 file: " << path); return fl::Mp3DecoderPtr();
    }
    fl::Mp3DecoderPtr decoder = fl::Mp3::createDecoder(error_message);
    if (!decoder->begin(file.rdbuf())) {
        fl::string decoder_error; decoder->hasError(&decoder_error);
        if (error_message) { *error_message = "Failed to initialize MP3 decoder: "; error_message->append(decoder_error); }
        FL_WARN("Failed to initialize MP3 decoder for: " << path); return fl::Mp3DecoderPtr();
    }
    return decoder;
}
References fl::string::append(), fl::Mp3Decoder::begin(), fl::Mp3::createDecoder(), FL_WARN, fl::Mp3Decoder::hasError(), fl::ifstream::is_open(), openRead(), and fl::ifstream::rdbuf().