FastLED: fl::FileSystem::readText
readText()
bool fl::FileSystem::readText (const char * path, fl::string * out)
Definition at line 180 of file file_system.cpp.hpp.
{
    fl::ifstream file = openRead(path);
    if (!file.is_open()) {
        FL_WARN("Failed to open file: " << path);
        return false;
    }
    fl::size size = file.size();
    out->reserve(size + out->size());
    bool wrote = false;
    while (file.available()) {
        u8 buf[64];
        fl::size n = file.read(buf, sizeof(buf));
        out->append((const char *)buf, n);
        wrote = true;
    }
    file.close();
    FL_DBG_IF(!wrote, "Failed to write any data to the output string.");
    return wrote;
}
References fl::string::append(), fl::ifstream::available(), fl::ifstream::close(), FL_DBG_IF, FL_WARN, fl::ifstream::is_open(), openRead(), fl::ifstream::read(), fl::basic_string::reserve(), fl::basic_string::size(), and fl::ifstream::size().
Referenced by readJson(), readScreenMap(), and readScreenMaps().