"""Stage a synthesised ``.build/pio/<board>/`` project for ``bash autoresearch``.

This is the autoresearch-side counterpart of the staging logic ``bash compile``
already performs via ``ci/compiler/pio.py::_init_platformio_build``. Pulling
autoresearch off root ``./platformio.ini`` (issue #3281) means autoresearch must
synthesise its own per-board ``platformio.ini`` from ``ci/boards.py`` before
fbuild is invoked.

The output of :func:`synthesise_autoresearch_project` is a build directory at
``<project_root>/.build/pio/<board>/`` containing:

- ``platformio.ini`` — generated by ``Board.to_platformio_ini()`` exactly the
  same way ``bash compile --backend platformio`` would, EXCEPT we deliberately
  suppress the ``get_root_platformio_build_flags`` merge so this path has zero
  read-side dependency on root ``./platformio.ini``.
- ``src/sketch/`` — populated by copying ``examples/AutoResearch/`` so that
  autoresearch's existing sketch-resolver fallback (``build_dir / "src" /
  "sketch"``) sees the sketch where it expects.

Callers normally invoke this once per autoresearch run, after the board name
has been determined (positional, ``--env``, ``--lcd*`` default, or chip
auto-detect).
"""

from __future__ import annotations

from pathlib import Path

from ci.boards import create_board
from ci.compiler.path_manager import FastLEDPaths, resolve_project_root


def synthesise_autoresearch_project(
    board_name: str,
    project_root: Path | None,
    verbose: bool,
) -> Path:
    """Stage ``.build/pio/<board>/`` and write a synthesised ``platformio.ini``.

    Args:
        board_name: PlatformIO env name (e.g. ``"esp32c6"``, ``"esp32s3"``).
            Must resolve via ``ci.boards.create_board``.
        project_root: FastLED project root. ``None`` => resolve automatically.
        verbose: Forwarded to ``_init_platformio_build`` for diagnostic prints.

    Returns:
        Absolute path to the staged build directory, ready to be handed to
        fbuild via ``run_fbuild_deploy(build_dir, environment=board_name, ...)``.

    Raises:
        RuntimeError: If board lookup fails or staging cannot complete.
    """
    # Local import keeps the autoresearch import graph slim until staging is
    # actually requested -- _init_platformio_build pulls in PlatformIO cache
    # machinery that we don't want to load just to print --help.
    from ci.compiler.pio import _init_platformio_build

    root = (project_root or resolve_project_root()).resolve()
    board = create_board(board_name)

    paths = FastLEDPaths(board.board_name, project_root=root)
    build_dir = paths.build_dir

    # PR #3291 (#3278 Phase 2) severed the root platformio.ini merge in
    # `_init_platformio_build`; PR #3295 (#3279 Phase 4) deleted the
    # `get_root_platformio_build_flags` function entirely. The previous
    # monkeypatch bridge that lived here is obsolete — autoresearch's
    # fbuild path no longer reads root platformio.ini regardless.
    init_result = _init_platformio_build(
        board,
        verbose,
        "AutoResearch",
        paths,
        build_dir=build_dir,
        additional_defines=["FASTLED_OBJECTFLED_DIAGNOSTICS=1"],
        use_fbuild=True,
    )
    if not init_result.success:
        raise RuntimeError(
            f"Failed to synthesise autoresearch project for board "
            f"'{board_name}': {init_result.output}"
        )

    return build_dir
