"""Stage a synthesised ``.build/pio/<board>/`` project for ``bash autoresearch``.

This is the autoresearch-side counterpart of the staging logic ``bash compile``
already performs via ``ci/compiler/pio.py::_init_platformio_build``. Pulling
autoresearch off root ``./platformio.ini`` (issue #3281) means autoresearch must
synthesise its own per-board ``platformio.ini`` from ``ci/boards.py`` before
fbuild is invoked.

The output of :func:`synthesise_autoresearch_project` is a build directory at
``<project_root>/.build/pio/<board>/`` containing:

- ``platformio.ini`` — generated by ``Board.to_platformio_ini()`` exactly the
  same way ``bash compile --backend platformio`` would, EXCEPT we deliberately
  suppress the ``get_root_platformio_build_flags`` merge so this path has zero
  read-side dependency on root ``./platformio.ini``.
- ``src/sketch/`` — populated by copying ``examples/AutoResearch/`` so that
  autoresearch's existing sketch-resolver fallback (``build_dir / "src" /
  "sketch"``) sees the sketch where it expects.

Callers normally invoke this once per autoresearch run, after the board name
has been determined (positional, ``--env``, ``--lcd*`` default, or chip
auto-detect).
"""

from __future__ import annotations

from contextlib import contextmanager
from pathlib import Path
from typing import Iterator

from ci.boards import create_board
from ci.compiler.path_manager import FastLEDPaths, resolve_project_root


@contextmanager
def _suppress_root_platformio_merge(project_root: Path) -> Iterator[None]:
    """Make ``get_root_platformio_build_flags`` see no root ``platformio.ini``.

    ``ci/compiler/pio.py::_init_platformio_build`` unconditionally merges
    ``build_flags`` from root ``./platformio.ini`` via
    :func:`get_root_platformio_build_flags`. That behaviour is exactly what
    issue #3281 wants to eliminate from the autoresearch path. Until #3278
    introduces an opt-out parameter, the simplest non-invasive bridge is to
    point ``get_root_platformio_build_flags`` at a project root with no root
    ``platformio.ini`` for the duration of the synthesis call — which is the
    documented "missing root ini" code path the function already handles
    correctly (returns ``[]``).

    We do this by monkey-patching the function symbol in ``ci.compiler.pio``
    (the import site used by ``_init_platformio_build``) to a stub that
    returns an empty list. Restoration is unconditional, even on exception.
    """
    # Local import — keeps the autoresearch import graph slim until staging
    # is actually requested.
    from ci.compiler import pio as _pio

    _ = project_root  # currently unused; reserved for future direct-arg suppression
    original = _pio.get_root_platformio_build_flags
    _pio.get_root_platformio_build_flags = lambda _board, _root: []  # type: ignore[assignment]
    try:
        yield
    finally:
        _pio.get_root_platformio_build_flags = original  # type: ignore[assignment]


def synthesise_autoresearch_project(
    board_name: str,
    project_root: Path | None,
    verbose: bool,
) -> Path:
    """Stage ``.build/pio/<board>/`` and write a synthesised ``platformio.ini``.

    Args:
        board_name: PlatformIO env name (e.g. ``"esp32c6"``, ``"esp32s3"``).
            Must resolve via ``ci.boards.create_board``.
        project_root: FastLED project root. ``None`` => resolve automatically.
        verbose: Forwarded to ``_init_platformio_build`` for diagnostic prints.

    Returns:
        Absolute path to the staged build directory, ready to be handed to
        fbuild via ``run_fbuild_deploy(build_dir, environment=board_name, ...)``.

    Raises:
        RuntimeError: If board lookup fails or staging cannot complete.
    """
    # Local import keeps the autoresearch import graph slim until staging is
    # actually requested -- _init_platformio_build pulls in PlatformIO cache
    # machinery that we don't want to load just to print --help.
    from ci.compiler.pio import _init_platformio_build

    root = (project_root or resolve_project_root()).resolve()
    board = create_board(board_name)

    paths = FastLEDPaths(board.board_name, project_root=root)
    build_dir = paths.build_dir

    with _suppress_root_platformio_merge(root):
        init_result = _init_platformio_build(
            board,
            verbose,
            "AutoResearch",
            paths,
            build_dir=build_dir,
            use_fbuild=True,
        )
    if not init_result.success:
        raise RuntimeError(
            f"Failed to synthesise autoresearch project for board "
            f"'{board_name}': {init_result.output}"
        )

    return build_dir
