FastLED: fl::CopyToVisitor::copy_vec
copy_vec()
template<typename T> template<typename ElemT> void fl::CopyToVisitor< T >::copy_vec (const fl::vector< ElemT > & vec) inline private
Definition at line 1671 of file types.h.
{
        size_t n = (vec.size() < dst.size()) ? vec.size() : dst.size();
        for (size_t i = 0; i < n; ++i) {
            dst[i] = static_cast<T>(vec[i]);
        }
        result = n;
    }
References dst, FL_NOEXCEPT, and result.
Referenced by operator()(), operator()(), and operator()().