FastLED: loop
loop()
void loop ()
Definition at line 80 of file FlowField.ino.
            {
    fl::Fx::DrawContext ctx(millis(), leds);
    // Use base class reference for uniform parameter setting + draw
    fl::FlowField &fx = (computeMode.as_int() == 0)
        ? static_cast<fl::FlowField &>(flowFieldFloat)
        : static_cast<fl::FlowField &>(flowFieldFP);
    fx.setFlowSpeedX(flowSpeedX);
    fx.setFlowAmplitudeX(flowAmpX);
    fx.setNoiseFrequencyX(flowFreqX);
    fx.setFlowSpeedY(flowSpeedY);
    fx.setFlowAmplitudeY(flowAmpY);
    fx.setNoiseFrequencyY(flowFreqY);
    fx.setEndpointSpeed(endpointSpeed);
    fx.setColorShift(colorShift);
    fx.setPersistence(persistence);
    fx.setFlowShift(flowShift);
    fx.setDotCount(numDots.as<int>());
    fx.setEmitterMode(emitterMode.as_int());
    fx.setShowFlowVectors(showFlowVectors);
    if (noisePunch.clicked()) {
        // 50% X axis, 50% Y axis; random position; random sign
        bool pickX = random8() < 128;
        float sign = (random8() < 128) ? 1.0f : -1.0f;
        if (pickX) {
            float cx = random8(0, fx.getWidth());
            float w = fx.getWidth() * 0.4f;
            fx.noisePunchX(cx, w, sign);
        } else {
            float cy = random8(0, fx.getHeight());
            float h = fx.getHeight() * 0.4f;
            fx.noisePunchY(cy, h, sign);
        }
    }
    fx.draw(ctx);
    FastLED.show();
}
References colorShift, computeMode, fl::FlowField::draw(), emitterMode, endpointSpeed, FastLED, flowAmpX, flowAmpY, flowFieldFloat, flowFieldFP, flowFreqX, flowFreqY, flowShift, flowSpeedX, flowSpeedY, fl::Fx2d::getHeight(), fl::Fx2d::getWidth(), leds, noisePunch, fl::FlowField::noisePunchX(), fl::FlowField::noisePunchY(), numDots, persistence, random8(), fl::FlowField::setColorShift(), fl::FlowField::setDotCount(), fl::FlowField::setEmitterMode(), fl::FlowField::setEndpointSpeed(), fl::FlowField::setFlowAmplitudeX(), fl::FlowField::setFlowAmplitudeY(), fl::FlowField::setFlowShift(), fl::FlowField::setFlowSpeedX(), fl::FlowField::setFlowSpeedY(), fl::FlowField::setNoiseFrequencyX(), fl::FlowField::setNoiseFrequencyY(), fl::FlowField::setPersistence(), fl::FlowField::setShowFlowVectors(), and showFlowVectors.