FastLED: fl::detail::ScaledPixelIteratorRGB::advance
advance()
void fl::detail::ScaledPixelIteratorRGB::advance () inline private
Advance to next pixel (or mark as end)
Definition at line 398 of file pixel_iterator.h.
{
    if (!mPixels) {
        mHasValue = false;
        return;
    }
    if (mPixels->has(1)) {
        u8 b0, b1, b2;
        mPixels->loadAndScaleRGB(&b0, &b1, &b2);
        mCurrent = array<u8, 3>{{b0, b1, b2}};  // Wire order bytes
        mPixels->stepDithering();
        mPixels->advanceData();
        mHasValue = true;
    } else {
        mHasValue = false;
    }
}
References FL_NOEXCEPT, mCurrent, mHasValue, and mPixels.
Referenced by fl::detail::ScaledPixelIteratorBrightness::ScaledPixelIteratorBrightness(), ScaledPixelIteratorRGB(), fl::detail::ScaledPixelIteratorRGB16::ScaledPixelIteratorRGB16(), fl::detail::ScaledPixelIteratorRGBW::ScaledPixelIteratorRGBW(), fl::detail::ScaledPixelIteratorRGBWW::ScaledPixelIteratorRGBWW(), fl::detail::ScaledPixelIteratorBrightness::operator++(), fl::detail::ScaledPixelIteratorBrightness::operator++(), fl::detail::ScaledPixelIteratorRGB16::operator++(), fl::detail::ScaledPixelIteratorRGB16::operator++(), operator++(), operator++(), fl::detail::ScaledPixelIteratorRGBW::operator++(), fl::detail::ScaledPixelIteratorRGBW::operator++(), fl::detail::ScaledPixelIteratorRGBWW::operator++(), and fl::detail::ScaledPixelIteratorRGBWW::operator++().