FastLED: fl::audio::detector::MoodAnalyzer::update
update()
void fl::audio::detector::MoodAnalyzer::update (shared_ptr< Context > context) override virtual
Implements fl::audio::Detector.
Definition at line 30 of file mood_analyzer.cpp.hpp.
{
    mRetainedFFT = context->getFFT(32);  // Higher resolution for mood analysis
    const fft::Bins& fft = *mRetainedFFT;
    const fft::Bins* prevFFT = context->getHistoricalFFT(1);
    // Extract audio features
    mSpectralCentroid = calculateSpectralCentroid(fft);
    mSpectralRolloff = calculateSpectralRolloff(fft);
    mSpectralFlux = calculateSpectralFlux(fft, prevFFT);
    mZeroCrossingRate = context->getZCF();
    mRMSEnergy = context->getRMS();
    // Calculate mood dimensions
    float valence = calculateValence(mSpectralCentroid, mSpectralRolloff, mSpectralFlux);
    float arousal = calculateArousal(mRMSEnergy, mZeroCrossingRate, mSpectralFlux);
    // Add to history for temporal averaging
    if (static_cast<int>(mValenceHistory.size()) < mAveragingFrames) {
        mValenceHistory.push_back(valence);
        mArousalHistory.push_back(arousal);
        mHistoryIndex = static_cast<int>(mValenceHistory.size()) % mAveragingFrames;
    } else {
        mValenceHistory[mHistoryIndex] = valence;
        mArousalHistory[mHistoryIndex] = arousal;
        mHistoryIndex = (mHistoryIndex + 1) % mAveragingFrames;
    }
    // Average over history for stability
    float avgValence = 0.0f;
    float avgArousal = 0.0f;
    for (size_t i = 0; i < mValenceHistory.size(); i++) {
        avgValence += mValenceHistory[i];
        avgArousal += mArousalHistory[i];
    }
    avgValence /= mValenceHistory.size();
    avgArousal /= mArousalHistory.size();
    // Update current mood
    mPreviousMood = mCurrentMood;
    mCurrentMood.valence = avgValence;
    mCurrentMood.arousal = avgArousal;
    mCurrentMood.confidence = calculateConfidence(avgValence, avgArousal);
    mCurrentMood.timestamp = context->getTimestamp();
    // Update duration if mood is stable
    if (mPreviousMood.getCategory() == mCurrentMood.getCategory()) {
        mCurrentMood.duration = mPreviousMood.duration +
            (mCurrentMood.timestamp - mPreviousMood.timestamp);
    } else {
        mCurrentMood.duration = 0;
    }
    // Check for mood changes (store result for fireCallbacks)
    mMoodChanged = shouldChangeMood(mCurrentMood);
}
References MoodAnalyzer(), calculateArousal(), calculateConfidence(), calculateSpectralCentroid(), calculateSpectralFlux(), calculateSpectralRolloff(), calculateValence(), mArousalHistory, mAveragingFrames, mCurrentMood, mHistoryIndex, mMoodChanged, mPreviousMood, mRetainedFFT, mRMSEnergy, mSpectralCentroid, mSpectralFlux, mSpectralRolloff, mValenceHistory, mZeroCrossingRate, shouldChangeMood(), and update().
Referenced by ~MoodAnalyzer(), and update().