FastLED: fl::audio::detector::MoodAnalyzer::calculateSpectralFlux
calculateSpectralFlux()
float fl::audio::detector::MoodAnalyzer::calculateSpectralFlux (const fft::Bins & fft, const fft::Bins * prevFFT) private
Definition at line 148 of file mood_analyzer.cpp.hpp.
{
    if (!prevFFT || prevFFT->raw().size() != fft.raw().size()) {
        return 0.0f;
    }
    float flux = 0.0f;
    for (size_t i = 0; i < fft.raw().size(); i++) {
        float diff = fft.raw()[i] - prevFFT->raw()[i];
        flux += diff * diff;
    }
    return fl::sqrt(flux);
}
References fl::audio::fft::Bins::raw(), and fl::sqrt().
Referenced by update().