FastLED: calculate_max_brightness_for_power_mW
calculate_max_brightness_for_power_mW() [2/2]
fl::u8 calculate_max_brightness_for_power_mW (fl::u8 target_brightness, fl::u32 max_power_mW)
Determines the highest brightness level you can use and still stay under the specified power budget for all sets of LEDs.
Unlike the other internal power functions which use a pointer to a specific set of LED data, this function uses the CFastLED linked list of LED controllers and their attached data.
Parameters
target_brightness the brightness you'd ideally like to use
max_power_mW the max power draw desired, in milliwatts
Returns
a limited brightness value. No higher than the target brightness, but may be lower depending on the power limit.
Definition at line 210 of file power_mgt.cpp.hpp.
{
    fl::u32 total_mW = gMCU_mW;
    CLEDController *pCur = CLEDController::head();
    while(pCur) {
        total_mW += calculate_unscaled_power_mW( pCur->leds(), pCur->size());
        pCur = pCur->next();
    }
#if POWER_DEBUG_PRINT == 1
    Serial.print("power demand at full brightness mW = ");
    Serial.println( total_mW);
#endif
    fl::u8 target_brightness_scaled = map_power_value(target_brightness);
    fl::u32 requested_power_mW = scale_power_for_brightness(total_mW, target_brightness);
#if POWER_DEBUG_PRINT == 1
    if( target_brightness != 255 ) {
        Serial.print("power demand at scaled brightness mW = ");
        Serial.println( requested_power_mW);
    }
    Serial.print("power limit mW = ");
    Serial.println( max_power_mW);
#endif
    if( requested_power_mW < max_power_mW) {
#if POWER_LED > 0
        if( gMaxPowerIndicatorLEDPinNumber ) {
            Pin(gMaxPowerIndicatorLEDPinNumber).lo(); // turn the LED off
        }
#endif
#if POWER_DEBUG_PRINT == 1
        Serial.print("demand is under the limit");
#endif
        return target_brightness;
    }
    fl::u8 recommended_scaled = (fl::u32)(target_brightness_scaled * (fl::u32)(max_power_mW)) / ((fl::u32)(requested_power_mW));
    fl::u8 recommended_brightness = unmap_power_value(recommended_scaled);
#if POWER_DEBUG_PRINT == 1
    Serial.print("recommended brightness # = ");
    Serial.println( recommended_brightness);
    fl::u32 resultant_power_mW = scale_power_for_brightness(total_mW, recommended_brightness);
    Serial.print("resultant power demand mW = ");
    Serial.println( resultant_power_mW);
    Serial.println();
#endif
#if POWER_LED > 0
    if( gMaxPowerIndicatorLEDPinNumber ) {
        Pin(gMaxPowerIndicatorLEDPinNumber).hi(); // turn the LED on
    }
#endif
    return recommended_brightness;
}
References calculate_unscaled_power_mW(), gMaxPowerIndicatorLEDPinNumber, gMCU_mW, fl::CLEDController::head(), fl::CLEDController::leds(), map_power_value(), fl::CLEDController::next(), scale_power_for_brightness(), Serial, fl::CLEDController::size(), and unmap_power_value().