FastLED: calculate_max_brightness_for_power_mW
calculate_max_brightness_for_power_mW() [1/2]
fl::u8 calculate_max_brightness_for_power_mW (const CRGB * ledbuffer, fl::u16 numLeds, fl::u8 target_brightness, fl::u32 max_power_mW)
Determines the highest brightness level you can use and still stay under the specified power budget for a given set of LEDs.
Parameters
ledbuffer the LED data to check
numLeds the number of LEDs in the data array
target_brightness the brightness you'd ideally like to use
max_power_mW the max power draw desired, in milliwatts
Returns
a limited brightness value. No higher than the target brightness, but may be lower depending on the power limit.
Definition at line 192 of file power_mgt.cpp.hpp.
{
    fl::u32 total_mW = calculate_unscaled_power_mW( ledbuffer, numLeds);
    fl::u8 target_brightness_scaled = map_power_value(target_brightness);
    fl::u32 requested_power_mW = scale_power_for_brightness(total_mW, target_brightness);
    fl::u8 recommended_brightness = target_brightness;
    if(requested_power_mW > max_power_mW) {
        fl::u8 recommended_scaled = (fl::u32)(target_brightness_scaled * (fl::u32)(max_power_mW)) / requested_power_mW;
        recommended_brightness = unmap_power_value(recommended_scaled);
    }
    return recommended_brightness;
}
References calculate_unscaled_power_mW(), map_power_value(), scale_power_for_brightness(), and unmap_power_value().
Referenced by calculate_max_brightness_for_power_vmA(), and CFastLED::setMaxPowerInMilliWatts().