FastLED: calculate_unscaled_power_mW
calculate_unscaled_power_mW() [2/2]
fl::u32 calculate_unscaled_power_mW (fl::span< const CRGB > leds)
Parameters
leds span of LED data to check
Definition at line 158 of file power_mgt.cpp.hpp.
{
    fl::u32 red32 = 0, green32 = 0, blue32 = 0;
    // Iterate using span's safe indexing
    for(size_t i = 0; i < leds.size(); i++) {
        red32   += map_power_value(leds[i].r);
        green32 += map_power_value(leds[i].g);
        blue32  += map_power_value(leds[i].b);
    }
    red32   *= gPowerModel().red_mW;
    green32 *= gPowerModel().green_mW;
    blue32  *= gPowerModel().blue_mW;
    red32   >>= 8;
    green32 >>= 8;
    blue32  >>= 8;
    fl::u32 total = red32 + green32 + blue32 + (gPowerModel().dark_mW * leds.size());
    return total;
}
References PowerModelRGB::blue_mW, PowerModelRGB::dark_mW, gPowerModel(), PowerModelRGB::green_mW, leds, map_power_value(), and PowerModelRGB::red_mW.
Referenced by calculate_max_brightness_for_power_mW(), calculate_max_brightness_for_power_mW(), calculate_unscaled_power_mW(), and CFastLED::getEstimatedPowerInMilliWatts().