FastLED: fl::anonymous_namespace{http_parser.cpp.hpp}::parseInt
parseInt()
bool fl::anonymous_namespace{http_parser.cpp.hpp}::parseInt (const fl::string & str, int & out)
Definition at line 41 of file http_parser.cpp.hpp.
{
    if (str.empty()) return false;
    int value = 0;
    for (size_t i = 0; i < str.size(); i++) {
        if (!fl::isdigit(str[i])) {
            return false;
        }
        value = value * 10 + (str[i] - '0');
    }
    out = value;
    return true;
}
References fl::basic_string::empty(), fl::isdigit(), fl::basic_string::size(), and fl::type_rank< T >::value.