FastLED: fl::XYPathRenderer::rasterize
rasterize()
void fl::XYPathRenderer::rasterize (float from, float to, int steps, XYRasterU8Sparse & raster, fl::function< u8(float)> * optional_alpha_gen = nullptr)
Definition at line 79 of file xypath.cpp.hpp.
{
    for (int i = 0; i < steps; ++i) {
        float alpha = fl::map_range<int, float>(i, 0, steps - 1, from, to);
        Tile2x2_u8 tile = at_subpixel(alpha);
        if (optional_alpha_gen) {
            // Scale the tile based on the alpha value.
            u8 a8 = (*optional_alpha_gen)(alpha);
            tile.scale(a8);
        }
        raster.rasterize(tile);
    }
}
References at_subpixel(), fl::map_range(), raster(), fl::Tile2x2_u8::scale(), and steps().
Referenced by ~XYPathRenderer().