FastLED: fl::XYPathRenderer::at_subpixel
at_subpixel()
Tile2x2_u8 fl::XYPathRenderer::at_subpixel (float alpha)
Definition at line 31 of file xypath_renderer.cpp.
{
    // 1) continuous point, in “pixel‐centers” coordinates [0.5 … W–0.5]
    if (!mDrawBoundsSet) {
        FASTLED_WARN("XYPathRenderer::at_subpixel: draw bounds not set");
        return Tile2x2_u8();
    }
    vec2f xy = at(alpha);
    // 2) shift back so whole‐pixels go 0…W–1, 0…H–1
    float x = xy.x - 0.5f;
    float y = xy.y - 0.5f;
    // 3) integer cell indices
    int cx = static_cast<int>(floorf(x));
    int cy = static_cast<int>(floorf(y));
    // 4) fractional offsets in [0..1)
    float fx = x - cx;
    float fy = y - cy;
    // 5) bilinear weights
    float w_ll = (1 - fx) * (1 - fy); // lower‑left
    float w_lr = fx * (1 - fy);       // lower‑right
    float w_ul = (1 - fx) * fy;       // upper‑left
    float w_ur = fx * fy;             // upper‑right
    // 6) build Tile2x2_u8 anchored at (cx,cy)
    Tile2x2_u8 out(vec2<int>(cx, cy));
    out.lower_left() = to_uint8(w_ll);
    out.lower_right() = to_uint8(w_lr);
    out.upper_left() = to_uint8(w_ul);
    out.upper_right() = to_uint8(w_ur);
    return out;
}
References at(), FASTLED_WARN, fl::Tile2x2_u8::lower_left(), fl::Tile2x2_u8::lower_right(), mDrawBoundsSet, fl::Tile2x2_u8::upper_left(), fl::Tile2x2_u8::upper_right(), x, xy(), and y.
Referenced by rasterize().