FastLED: fl::XYPathRenderer::compute_float
compute_float()
vec2f fl::XYPathRenderer::compute_float (float alpha, const TransformFloat & tx) private
Definition at line 24 of file xypath_renderer.cpp.
{
    vec2f xy = mPath->compute(alpha);
    vec2f out = tx.transform(xy);
    out = mGridTransform.transform(out);
    return out;
}
References mGridTransform, mPath, fl::TransformFloat::transform(), and xy().
Referenced by at(), and compute().