FastLED: fl::XYPathRenderer::rasterize
rasterize()
void fl::XYPathRenderer::rasterize (float from, float to, int steps, XYRasterU8Sparse & raster, fl::function< uint8_t(float)> * optional_alpha_gen = nullptr)
Definition at line 77 of file xypath.cpp.
{
    for (int i = 0; i < steps; ++i) {
        float alpha = fl::map_range<int, float>(i, 0, steps - 1, from, to);
        Tile2x2_u8 tile = at_subpixel(alpha);
        if (optional_alpha_gen) {
            // Scale the tile based on the alpha value.
            uint8_t a8 = (*optional_alpha_gen)(alpha);
            tile.scale(a8);
        }
        raster.rasterize(tile);
    }
}
References at_subpixel(), fl::map_range(), raster, fl::Tile2x2_u8::scale(), and steps().