FastLED: loop
loop()
void loop ()
Definition at line 97 of file EaseInOut.h.
            {
    // Clear the matrix using fl::clear for LedsXY
    fl::clear(leds);
    // Get the current slider value (0.0 to 1.0)
    float sliderValue = xPosition.value();
    // Map slider value to X coordinate (0 to width-1)
    uint8_t x = map(sliderValue * 1000, 0, 1000, 0, MATRIX_WIDTH - 1);
    // Get the selected ease type using the dropdown index
    EaseType selectedEaseType = getEaseType(easeTypeDropdown.as_int());
    uint8_t y;
    if (use16Bit.value()) {
        // Use 16-bit precision
        uint16_t easeInput = map(sliderValue * 1000, 0, 1000, 0, 65535);
        uint16_t easeOutput = ease16(selectedEaseType, easeInput);
        y = map(easeOutput, 0, 65535, 0, MATRIX_HEIGHT - 1);
    } else {
        // Use 8-bit precision
        uint8_t easeInput = map(sliderValue * 1000, 0, 1000, 0, 255);
        uint8_t easeOutput = ease8(selectedEaseType, easeInput);
        y = map(easeOutput, 0, 255, 0, MATRIX_HEIGHT - 1);
    }
    // Draw white dot at the calculated position using splat rendering
    if (x < MATRIX_WIDTH && y < MATRIX_HEIGHT) {
        leds(x, y) = CRGB::White;
    }
    FastLED.show();
}
References fl::clear(), fl::ease16(), fl::ease8(), easeTypeDropdown(), FastLED, getEaseType(), leds, MATRIX_HEIGHT, MATRIX_WIDTH, use16Bit(), CRGB::White, x, xPosition(), and y.