FastLED: printJsonRaw
printJsonRaw()
void printJsonRaw (const fl::json & json, const char * prefix = "REMOTE: ")
Print JSON directly to Serial, bypassing fl::println and ScopedLogDisable This ensures RPC responses are always visible regardless of log level.
Parameters
json JSON object to output
prefix Optional prefix (default: "REMOTE: ")
Definition at line 54 of file AutoResearchRemote.cpp.
{
    // Serialize and print response
    fl::string formatted = fl::formatJsonResponse(json, prefix);
    fl::println(formatted.c_str());
    fl::flush();
}
References fl::basic_string::c_str(), fl::flush(), fl::formatJsonResponse(), and fl::println().