FastLED: loop
loop()
void loop ()
Definition at line 70 of file AudioInput.ino.
            {
    EVERY_N_MILLIS(1000) {
        Serial.println("Loop active...");
    }
    // Check if audio source is valid
    if (!audioSource) {
        Serial.println("Audio source is null!");
        delay(1000);
        return;
    }
    // Check for audio errors
    fl::string errorMsg;
    if (audioSource->error(&errorMsg)) {
        Serial.print("Audio error: ");
        Serial.println(errorMsg.c_str());
        delay(100);
        return;
    }
    // Read audio data
    fl::audio::Sample sample = audioSource->read();
    if (sample.isValid()) {
        EVERY_N_MILLIS(100) {
            const auto& audioBuffer = sample.pcm();
            const i16* max_sample = fl::max_element(audioBuffer.begin(), audioBuffer.end());
            const i16* min_sample = fl::min_element(audioBuffer.begin(), audioBuffer.end());
            fl::sstream ss;
            ss << "\n--- Audio Sample ---\n";
            ss << "Samples: " << audioBuffer.size() << "\n";
            ss << "Timestamp: " << sample.timestamp() << " ms\n";
            ss << "Max: " << *max_sample << "\n";
            ss << "Min: " << *min_sample << "\n";
            ss << "RMS: " << sample.rms() << "\n";
            ss << "Zero Crossing Frequency: " << sample.zcf() << " Hz\n";
            FL_WARN(ss.str());
        }
    }
}
References audioSource, fl::basic_string::c_str(), EVERY_N_MILLIS, FL_WARN, fl::max_element(), fl::min_element(), Serial, and fl::sstream::str().