FastLED: fl::list::erase
erase() [2/2]
template<typename T> iterator fl::list< T >::erase (iterator pos) inline
Definition at line 352 of file list.h.
{
        if (pos == end()) {
            return end();
        }
        Node* node = pos.mNode;
        Node* next_node = node->next;
        unlink(node);
        destroy_node(node);
        --mSize;
        return iterator(next_node);
    }
References destroy_node(), end(), mSize, fl::list< T >::Node::next, pos, and unlink().
Referenced by erase(), pop_back(), pop_front(), remove(), remove_if(), and unique().