FastLED: inoise16_raw
inoise16_raw() [3/4]
fl::i16 inoise16_raw (fl::u32 x, fl::u32 y, fl::u32 z) extern
Parameters
z z-axis coordinate on noise map (3D)
Definition at line 303 of file noise.cpp.hpp.
{
    // Find the unit cube containing the point
    fl::u8 X = (x>>16)&0xFF;
    fl::u8 Y = (y>>16)&0xFF;
    fl::u8 Z = (z>>16)&0xFF;
    // Hash cube corner coordinates
    fl::u8 A = NOISE_P(X)+Y;
    fl::u8 AA = NOISE_P(A)+Z;
    fl::u8 AB = NOISE_P(A+1)+Z;
    fl::u8 B = NOISE_P(X+1)+Y;
    fl::u8 BA = NOISE_P(B) + Z;
    fl::u8 BB = NOISE_P(B+1)+Z;
    // Get the relative position of the point in the cube
    fl::u16 u = x & 0xFFFF;
    fl::u16 v = y & 0xFFFF;
    fl::u16 w = z & 0xFFFF;
    // Get a signed version of the above for the grad function
    fl::i16 xx = (u >> 1) & 0x7FFF;
    fl::i16 yy = (v >> 1) & 0x7FFF;
    fl::i16 zz = (w >> 1) & 0x7FFF;
    fl::u16 N = 0x8000L;
    u = EASE16(u); v = EASE16(v); w = EASE16(w);
    // skip the log fade adjustment for the moment, otherwise here we would
    // adjust fade values for u,v,w
    fl::i16 X1 = LERP(grad16(NOISE_P(AA), xx, yy, zz), grad16(NOISE_P(BA), xx - N, yy, zz), u);
    fl::i16 X2 = LERP(grad16(NOISE_P(AB), xx, yy-N, zz), grad16(NOISE_P(BB), xx - N, yy - N, zz), u);
    fl::i16 X3 = LERP(grad16(NOISE_P(AA+1), xx, yy, zz-N), grad16(NOISE_P(BA+1), xx - N, yy, zz-N), u);
    fl::i16 X4 = LERP(grad16(NOISE_P(AB+1), xx, yy-N, zz-N), grad16(NOISE_P(BB+1), xx - N, yy - N, zz - N), u);
    fl::i16 Y1 = LERP(X1,X2,v);
    fl::i16 Y2 = LERP(X3,X4,v);
    fl::i16 ans = LERP(Y1,Y2,w);
    return ans;
}
References grad16(), NOISE_P, x, y, and z.
Referenced by inoise16(), inoise16(), inoise16(), and inoise16().