FastLED: inoise16
inoise16() [4/4]
uint16_t inoise16 (uint32_t x, uint32_t y, uint32_t z, uint32_t t) extern
16-bit, fixed point implementation of Perlin's noise.
See also
inoise16_raw()
Returns
scaled noise value as an unsigned integer, 0-65535
Parameters
x x-axis coordinate on noise map (1D)
y y-axis coordinate on noise map (2D)
t t-axis coordinate on noise map (3D)
Definition at line 420 of file noise.cpp.
{
    int32_t ans = inoise16_raw(x,y,z,t);
    ans = ans + 19052L;
    uint32_t pan = ans;
    // pan = (ans * 220L) >> 7.  That's the same as:
    // pan = (ans * 440L) >> 8.  And this way avoids a 7X four-byte shift-loop on AVR.
    // Identical math, except for the highest bit, which we don't care about anyway,
    // since we're returning the 'middle' 16 out of a 32-bit value anyway.
    pan *= 440L;
    return (pan>>8);
    // return scale16by8(pan,220)<<1;
    // return ((inoise16_raw(x,y,z)+19052)*220)>>7;
    // return scale16by8(inoise16_raw(x,y,z)+19052,220)<<1;
}
References inoise16_raw(), t, x, y, and z.
Referenced by PlasmaWaveGenerator::calculatePlasmaPixel(), drawBinaryPulse(), drawCosmicSwirl(), drawDigitalRain(), drawElectricStorm(), drawFireDance(), drawGlitchCity(), drawLavaLamp(), drawNebulaDrift(), drawOceanDepths(), fill_raw_2dnoise16(), fill_raw_2dnoise16into8(), fill_raw_noise16into8(), Fire2023(), getFirePaletteIndex(), getPaletteIndex(), getPaletteIndex(), loop(), showGenerative(), and NoiseGenerator::Value().