FastLED: inoise8
inoise8() [3/3]
uint8_t inoise8 (uint16_t x, uint16_t y, uint16_t z) extern
8-Bit, fixed point implementation of Perlin's noise.
See also
inoise8_raw()
Returns
scaled noise value as an unsigned integer, 0-255
Parameters
x x-axis coordinate on noise map (1D)
y y-axis coordinate on noise map (2D)
z z-axis coordinate on noise map (3D)
Definition at line 590 of file noise.cpp.
{
    //return scale8(76+(inoise8_raw(x,y,z)),215)<<1;
    int8_t n = inoise8_raw( x, y, z);  // -64..+64
    n+= 64;                            //   0..128
    uint8_t ans = qadd8( n, n);        //   0..255
    return ans;
}
References inoise8_raw(), qadd8(), x, y, and z.
Referenced by fill_raw_2dnoise8(), fill_raw_noise8(), FillNoise(), fillnoise8(), fl::NoisePalette::fillnoise8(), and fillnoise82().