FastLED: plotSoftDot
plotSoftDot()
void plotSoftDot (float fx, float fy, float s)
Definition at line 85 of file Luminova.h.
{
    // map s (decays from 5) to a pixel radius 1..3
    float r = constrain(s * 0.5f, 1.0f, 3.0f);
    int R = (int)fl::ceilf(r);
    int cx = (int)fl::roundf(fx);
    int cy = (int)fl::roundf(fy);
    float r2 = r * r;
    for (int dy = -R; dy <= R; ++dy) {
        for (int dx = -R; dx <= R; ++dx) {
            float d2 = dx * dx + dy * dy;
            if (d2 <= r2) {
                // falloff toward edge
                float fall = 1.0f - (d2 / (r2 + 0.0001f));
                uint8_t v = (uint8_t)constrain(255.0f * fall, 0.0f, 255.0f);
                plotDot(cx + dx, cy + dy, v);
            }
        }
    }
}
References fl::ceilf(), plotDot(), and fl::roundf().
Referenced by loop().