FastLED: loop
loop()
void loop ()
Definition at line 129 of file Luminova.h.
            {
    // Processing does: background(0, t?9:!createCanvas(...)+W); filter(BLUR)
    // We emulate a very light global fade + blur to leave trails.
    // First a tiny global fade, then a mild Gaussian-ish blur.
    fadeToBlackBy(leds, NUM_LEDS, 18);      // stronger fade to prevent blowout
    blur2d(leds, WIDTH, HEIGHT, 24, xymap); // slightly gentler blur for 32x32
    // Spawn/overwrite one particle per frame, round-robin
    resetParticle(ps[t % MAXP], t);
    // Update & draw all particles
    for (int i = 0; i < MAXP; ++i) {
        if (!ps[i].alive)
            continue;
        P &p = ps[i];
        // strokeWeight(p.s *= .997)
        p.s *= 0.997f;
        if (p.s < 0.5f) {
            p.alive = false;
            continue;
        } // cheap cull
        // a += (noise(t/99, p.g) - .5) / 9
        // Use 2D noise: (t/99, g). inoise8 returns 0..255; center at ~128.
        float tOver99 = (float)t / 99.0f;
        uint8_t n2 = inoise8((uint16_t)(tOver99 * 4096), (uint16_t)(p.g * 37));
        float n2c = ((int)n2 - 128) / 255.0f; // ~ -0.5 .. +0.5
        p.a += (n2c) / 9.0f;
        // x += cos((a)*f), y += sin(a*f)   (original had (a+=...)*f inside cos)
        float aa = p.a * (float)p.f;
        p.x += fl::cosf(aa);
        p.y += fl::sinf(aa);
        // draw white point with softness according to s
        plotSoftDot(p.x, p.y, p.s);
    }
    FastLED.show();
    t++;
    // Cap frame rate a bit like Processing's draw loop
    FastLED.delay(16); // ~60 FPS
}
References P::a, P::alive, blur2d(), fl::cosf(), P::f, fadeToBlackBy(), FastLED, P::g, HEIGHT, inoise8(), leds, MAXP, NUM_LEDS, plotSoftDot(), ps, resetParticle(), P::s, fl::sinf(), t, WIDTH, P::x, xymap, and P::y.