FastLED: setup
setup()
void setup ()
Definition at line 105 of file Luminova.h.
             {
    CLEDController *controller =
        &FastLED.addLeds<LED_TYPE, DATA_PIN, COLOR_ORDER>(leds, NUM_LEDS);
    FastLED.setBrightness(BRIGHTNESS);
    FastLED.clear(true);
    // When user adjusts UI, reflect into model speed
    // Provide screen map to UI with a specific LED diameter
    fl::XYMap xy = kMatrixSerpentineLayout
                       ? fl::XYMap::constructSerpentine(WIDTH, HEIGHT)
                       : fl::XYMap::constructRectangularGrid(WIDTH, HEIGHT);
    fl::ScreenMap screenmap = xy.toScreenMap();
    screenmap.setDiameter(0.15f);
    controller->setScreenMap(screenmap);
    // init particles as "dead"
    for (int i = 0; i < MAXP; ++i)
        ps[i].alive = false;
}
References BRIGHTNESS, COLOR_ORDER, fl::XYMap::constructRectangularGrid(), fl::XYMap::constructSerpentine(), controller, DATA_PIN, FastLED, HEIGHT, kMatrixSerpentineLayout, LED_TYPE, leds, MAXP, NUM_LEDS, ps, screenmap, WIDTH, and xy().