FastLED: noiseControls
noiseControls()
UIGroup noiseControls ("Noise Controls" , speed , changePallete , changePalletTime , scale , changePalette)
References changePalette(), changePallete(), changePalletTime(), scale, and speed.