FastLED: loop
loop()
void loop ()
Definition at line 124 of file wasm_impl.h.
            {
    uint32_t now = millis();
    FastLED.setBrightness(!isOff ? brightness.as<uint8_t>() : 0);
    noisePalette.setSpeed(speed);
    noisePalette.setScale(scale);
    fxEngine.setSpeed(timeSpeed);
    if (changeFx) {
        fxEngine.nextFx();
    }
    // We use the dynamic version here which allows the change time to respond
    // to changes from the UI element.
    EVERY_N_MILLISECONDS_DYNAMIC(changePalletTime.as<int>() * 1000) {
        if (changePallete) {
            noisePalette.changeToRandomPalette();
        }
    }
    if (changePalette) {
        noisePalette.changeToRandomPalette();
    }
    // Do a change of palette if the button is pressed.
    static int lastFxIndex = -1;
    if (fxIndex.value() != lastFxIndex) {
        lastFxIndex = fxIndex;
        animartrix.fxSet(fxIndex);
    }
    fxEngine.draw(now, leds);
    FastLED.show();
}
References animartrix, brightness(), changeFx(), changePalette(), changePallete(), changePalletTime(), EVERY_N_MILLISECONDS_DYNAMIC, FastLED, fxEngine, fxIndex(), isOff(), leds, noisePalette, scale, speed, and timeSpeed().