FastLED: fl::InlinedVector::assign
assign() [2/2]
template<typename T, size_t INLINED_SIZE> void fl::InlinedVector< T, INLINED_SIZE >::assign (size_t new_cap, const T & value) inline
Definition at line 871 of file vector.h.
{
        clear();
        if (INLINED_SIZE > new_cap) {
            // mFixed.assign(value);
            while (size() < new_cap) {
                mFixed.push_back(value);
            }
            return;
        }
        // mHeap.assign(value);
        mHeap.reserve(new_cap);
        mUsingHeap = true;
        while (size() < new_cap) {
            mHeap.push_back(value);
        }
    }
References clear(), mFixed, mHeap, mUsingHeap, and size().
Referenced by operator=(), and fl::LineSimplifierExact< NumberT >::safeCopy().