FastLED: fl::Variant::reset
reset()
template<typename... Types> void fl::Variant< Types >::reset () inline noexcept
Definition at line 92 of file variant.h.
{
        if (!empty()) {
            destroy_current();
            _tag = Empty;
        }
    }
Referenced by fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::~Variant(), fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::emplace(), fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::operator=(), fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::operator=(), fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::operator=(), and fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::operator=().