FastLED: fl::Variant< Types > Class Template Reference
fl::Variant< Types > Class Template Reference
Detailed Description
template<typename... Types>
class fl::Variant< Types >
Definition at line 9 of file variant.h.
#include <variant.h>
Classes
struct type_to_tag_impl
struct type_to_tag_impl< T >
struct type_to_tag_impl< T, U, Rest... >
Public Types
using Tag = uint8_t
Public Member Functions
Variant () noexcept
template<typename T, typename = typename fl::enable_if< contains_type<T, Types...>::value>::type>
Variant (const T &value)
Variant (const Variant &other)
template<typename T, typename = typename fl::enable_if< contains_type<T, Types...>::value>::type>
Variant (T &&value)
Variant (Variant &&other) noexcept
~Variant ()
template<typename T, typename... Args>
fl::enable_if< contains_type< T, Types... >::value, T & >::type emplace (Args &&...args)
bool empty () const noexcept
template<typename T>
bool equals (const T &other) const
template<typename T>
bool is () const noexcept
template<typename T, typename = typename fl::enable_if< contains_type<T, Types...>::value>::type>
Variant & operator= (const T &value)
Variant & operator= (const Variant &other)
template<typename T, typename = typename fl::enable_if< contains_type<T, Types...>::value>::type>
Variant & operator= (T &&value)
Variant & operator= (Variant &&other) noexcept
template<typename T>
T * ptr ()
template<typename T>
const T * ptr () const
void reset () noexcept
Tag tag () const noexcept
template<typename Visitor>
void visit (Visitor &visitor)
template<typename Visitor>
void visit (Visitor &visitor) const
Static Public Attributes
static constexpr Tag Empty = 0
Private Member Functions
template<typename T, typename... Args>
void construct (Args &&...args)
void copy_construct_from (const Variant &other)
void destroy_current () noexcept
void move_construct_from (Variant &other) noexcept
Static Private Member Functions
template<typename T>
static void copy_fn (void *storage, const Variant &other)
template<typename T>
static void destroy_fn (void *storage)
template<typename T>
static void move_fn (void *storage, Variant &other)
template<typename T>
static constexpr Tag type_to_tag ()
template<typename T, typename Visitor>
static void visit_fn (void *storage, Visitor &v)
template<typename T, typename Visitor>
static void visit_fn_const (const void *storage, Visitor &v)
Private Attributes
char _storage [max_size< Types... >::value]
Tag _tag
Member Typedef Documentation
Tag
template<typename... Types> using fl::Variant< Types >::Tag = uint8_t
Definition at line 11 of file variant.h.
Constructor & Destructor Documentation
Variant() [1/5]
template<typename... Types> fl::Variant< Types >::Variant () inline noexcept
Definition at line 16 of file variant.h.
: _tag(Empty) {}
Variant() [2/5]
template<typename... Types> template<typename T, typename = typename fl::enable_if< contains_type<T, Types...>::value>::type> fl::Variant< Types >::Variant (const T & value) inline
Definition at line 20 of file variant.h.
                            : _tag(Empty) {
        construct<T>(value);
    }
Variant() [3/5]
template<typename... Types> template<typename T, typename = typename fl::enable_if< contains_type<T, Types...>::value>::type> fl::Variant< Types >::Variant (T && value) inline
Definition at line 26 of file variant.h.
                       : _tag(Empty) {
        construct<T>(fl::move(value));
    }
Variant() [4/5]
template<typename... Types> fl::Variant< Types >::Variant (const Variant< Types > & other) inline
Definition at line 30 of file variant.h.
                                  : _tag(Empty) {
        if (!other.empty()) {
            copy_construct_from(other);
        }
    }
Variant() [5/5]
template<typename... Types> fl::Variant< Types >::Variant (Variant< Types > && other) inline noexcept
Definition at line 36 of file variant.h.
                                      : _tag(Empty) {
        if (!other.empty()) {
            move_construct_from(other);
            other.reset();
        }
    }
~Variant()
template<typename... Types> fl::Variant< Types >::~Variant () inline
Definition at line 43 of file variant.h.
{ reset(); }
Member Function Documentation
construct()
template<typename... Types> template<typename T, typename... Args> void fl::Variant< Types >::construct (Args &&... args) inline private
Definition at line 249 of file variant.h.
{
        new (&_storage) T(fl::forward<Args>(args)...);
        _tag = type_to_tag<T>();
    }
Referenced by fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::Variant(), fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::Variant(), fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::emplace(), fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::operator=(), and fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::operator=().
copy_construct_from()
template<typename... Types> void fl::Variant< Types >::copy_construct_from (const Variant< Types > & other) inline private
Definition at line 196 of file variant.h.
{
        using Fn = void (*)(void *, const Variant &);
        static constexpr Fn table[] = {&Variant::template copy_fn<Types>...};
        table[other._tag - 1](&_storage, other);
        _tag = other._tag;
    }
Referenced by fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::operator=().
copy_fn()
template<typename... Types> template<typename T> static void fl::Variant< Types >::copy_fn (void * storage, const Variant< Types > & other) inline static private
Definition at line 204 of file variant.h.
{
        new (storage) T(*reinterpret_cast<const T *>(&other._storage));
    }
destroy_current()
template<typename... Types> void fl::Variant< Types >::destroy_current () inline private noexcept
Definition at line 183 of file variant.h.
{
        using Fn = void (*)(void *);
        static constexpr Fn table[] = {&Variant::template destroy_fn<Types>...};
        if (_tag != Empty) {
            table[_tag - 1](&_storage);
        }
    }
Referenced by fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::reset().
destroy_fn()
template<typename... Types> template<typename T> static void fl::Variant< Types >::destroy_fn (void * storage) inline static private
Definition at line 191 of file variant.h.
{
        reinterpret_cast<T *>(storage)->~T();
    }
emplace()
template<typename... Types> template<typename T, typename... Args> fl::enable_if< contains_type< T, Types... >::value, T & >::type fl::Variant< Types >::emplace (Args &&... args) inline
Definition at line 86 of file variant.h.
{
        reset();
        construct<T>(fl::forward<Args>(args)...);
        return ptr<T>();
    }
empty()
template<typename... Types> bool fl::Variant< Types >::empty () const inline noexcept
Definition at line 100 of file variant.h.
{ return _tag == Empty; }
Referenced by fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::Variant(), fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::operator=(), fl::Optional< T >::operator==(), and fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::reset().
equals()
template<typename... Types> template<typename T> bool fl::Variant< Types >::equals (const T & other) const inline
Definition at line 128 of file variant.h.
{
        if (auto p = ptr<T>()) {
            return *p == other;
        }
        return false;
    }
is()
template<typename... Types> template<typename T> bool fl::Variant< Types >::is () const inline noexcept
Definition at line 102 of file variant.h.
{
        return _tag == type_to_tag<T>();
    }
Referenced by fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::ptr(), and fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::ptr().
move_construct_from()
template<typename... Types> void fl::Variant< Types >::move_construct_from (Variant< Types > & other) inline private noexcept
Definition at line 209 of file variant.h.
{
        using Fn = void (*)(void *, Variant &);
        static constexpr Fn table[] = {&Variant::template move_fn<Types>...};
        table[other._tag - 1](&_storage, other);
        _tag = other._tag;
        other.reset();
    }
Referenced by fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::Variant(), and fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::operator=().
move_fn()
template<typename... Types> template<typename T> static void fl::Variant< Types >::move_fn (void * storage, Variant< Types > & other) inline static private
Definition at line 217 of file variant.h.
{
        new (storage) T(fl::move(*reinterpret_cast<T *>(&other._storage)));
    }
operator=() [1/4]
template<typename... Types> template<typename T, typename = typename fl::enable_if< contains_type<T, Types...>::value>::type> Variant & fl::Variant< Types >::operator= (const T & value) inline
Definition at line 68 of file variant.h.
{
        reset();
        construct<T>(value);
        return *this;
    }
operator=() [2/4]
template<typename... Types> Variant & fl::Variant< Types >::operator= (const Variant< Types > & other) inline
Definition at line 45 of file variant.h.
{
        if (this != &other) {
            reset();
            if (!other.empty()) {
                copy_construct_from(other);
            }
        }
        return *this;
    }
operator=() [3/4]
template<typename... Types> template<typename T, typename = typename fl::enable_if< contains_type<T, Types...>::value>::type> Variant & fl::Variant< Types >::operator= (T && value) inline
Definition at line 76 of file variant.h.
{
        reset();
        construct<T>(fl::move(value));
        return *this;
    }
operator=() [4/4]
template<typename... Types> Variant & fl::Variant< Types >::operator= (Variant< Types > && other) inline noexcept
Definition at line 55 of file variant.h.
{
        if (this != &other) {
            reset();
            if (!other.empty()) {
                move_construct_from(other);
                other.reset();
            }
        }
        return *this;
    }
ptr() [1/2]
template<typename... Types> template<typename T> T * fl::Variant< Types >::ptr () inline
Definition at line 106 of file variant.h.
{
        return is<T>() ? reinterpret_cast<T *>(&_storage) : nullptr;
    }
Referenced by fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::emplace().
ptr() [2/2]
template<typename... Types> template<typename T> const T * fl::Variant< Types >::ptr () const inline
Definition at line 110 of file variant.h.
{
        return is<T>() ? reinterpret_cast<const T *>(&_storage) : nullptr;
    }
reset()
template<typename... Types> void fl::Variant< Types >::reset () inline noexcept
Definition at line 92 of file variant.h.
{
        if (!empty()) {
            destroy_current();
            _tag = Empty;
        }
    }
Referenced by fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::~Variant(), fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::emplace(), fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::operator=(), fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::operator=(), fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::operator=(), and fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::operator=().
tag()
template<typename... Types> Tag fl::Variant< Types >::tag () const inline noexcept
Definition at line 99 of file variant.h.
{ return _tag; }
type_to_tag()
template<typename... Types> template<typename T> static constexpr Tag fl::Variant< Types >::type_to_tag () inline static constexpr private
Definition at line 228 of file variant.h.
{
        return type_to_tag_impl<T, Types...>::value;
    }
Referenced by fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::construct(), and fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::is().
visit() [1/2]
template<typename... Types> template<typename Visitor> void fl::Variant< Types >::visit (Visitor & visitor) inline
Definition at line 136 of file variant.h.
{
        if (_tag == Empty)
            return;
        // Fn is "a pointer to function taking (void* storage, Visitor&)"
        using Fn = void (*)(void *, Visitor &);
        // Build a constexpr array of one thunk per type in Types...
        // Each thunk casts the storage back to the right T* and calls
        // visitor.accept
        static constexpr Fn table[] = {
            &Variant::template visit_fn<Types, Visitor>...};
        // _tag is 1-based, so dispatch in O(1) via one indirect call:
        table[_tag - 1](&_storage, visitor);
    }
Referenced by fl::Gradient::Gradient().
visit() [2/2]
template<typename... Types> template<typename Visitor> void fl::Variant< Types >::visit (Visitor & visitor) const inline
Definition at line 153 of file variant.h.
{
        if (_tag == Empty)
            return;
        // Fn is "a pointer to function taking (const void* storage, Visitor&)"
        using Fn = void (*)(const void *, Visitor &);
        // Build a constexpr array of one thunk per type in Types...
        static constexpr Fn table[] = {
            &Variant::template visit_fn_const<Types, Visitor>...};
        // _tag is 1-based, so dispatch in O(1) via one indirect call:
        table[_tag - 1](&_storage, visitor);
    }
visit_fn()
template<typename... Types> template<typename T, typename Visitor> static void fl::Variant< Types >::visit_fn (void * storage, Visitor & v) inline static private
Definition at line 171 of file variant.h.
{
        // unsafe_cast is OK here because we know _tag matched T
        v.accept(*reinterpret_cast<T *>(storage));
    }
visit_fn_const()
template<typename... Types> template<typename T, typename Visitor> static void fl::Variant< Types >::visit_fn_const (const void * storage, Visitor & v) inline static private
Definition at line 177 of file variant.h.
{
        // unsafe_cast is OK here because we know _tag matched T
        v.accept(*reinterpret_cast<const T *>(storage));
    }
Member Data Documentation
_storage
template<typename... Types> char fl::Variant< Types >::_storage[max_size< Types... >::value] private
Definition at line 255 of file variant.h.
Referenced by fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::copy_fn(), and fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::move_fn().
_tag
template<typename... Types> Tag fl::Variant< Types >::_tag private
Definition at line 257 of file variant.h.
Referenced by fl::Variant< const CRGBPalette16 *, const CRGBPalette32 *, const CRGBPalette256 *, GradientFunction >::copy_construct_from().
Empty
template<typename... Types> Tag fl::Variant< Types >::Empty = 0 static constexpr
Definition at line 12 of file variant.h.
The documentation for this class was generated from the following file:
fl/variant.h