FastLED: fl::third_party::ezWS2812::color_to_spi
color_to_spi()
void fl::third_party::ezWS2812::color_to_spi (uint8_t color, uint8_t * buffer) const inline private
Convert color byte to SPI bit pattern.
Definition at line 81 of file ezWS2812.h.
{
        for (int i = 7; i >= 0; i--) {
            buffer[7-i] = (color & (1 << i)) ? one() : zero();
        }
    }
References one(), and zero().
Referenced by set_pixel().