FastLED: setup
setup()
void setup ()
Definition at line 14 of file Async.h.
             {
    FastLED.addLeds<WS2812B, DATA_PIN, GRB>(leds, NUM_LEDS);
    FastLED.setBrightness(16);
    // Create a task that runs every 100ms to change color
    auto colorPicker = fl::task::every_ms(100, FL_TRACE)
      .then([] {
          current_color = CHSV(random8(), 255, 255);
      });
    // Create a task that runs at 60fps to update the LEDs
    auto displayTask = fl::task::at_framerate(60, FL_TRACE)
      .then([] {
          fill_solid(leds, NUM_LEDS, current_color);
          FastLED.show();
      });
}
References fl::task::at_framerate(), current_color, DATA_PIN, fl::task::every_ms(), FastLED, fill_solid(), FL_TRACE, GRB, leds, NUM_LEDS, random8(), and fl::task::Handle::then().