FastLED: fl::third_party::TJpg_Decoder::jd_input
jd_input()
size_t fl::third_party::TJpg_Decoder::jd_input (JDEC * jdec, uint8_t * buf, size_t len) static
Definition at line 81 of file TJpg_Decoder.cpp.hpp.
{
  // Retrieve instance pointer from JDEC device context
  TJpg_Decoder *thisPtr = static_cast<TJpg_Decoder*>(jdec->device);
  // Handle an array input
  if (thisPtr->jpg_source == TJPG_ARRAY) {
    // Avoid running off end of array
    if (thisPtr->array_index + len > thisPtr->array_size) {
      len = thisPtr->array_size - thisPtr->array_index;
    }
    // If buf is valid then copy len bytes to buffer
    if (buf) fl::memcpy(buf, (const uint8_t *)(thisPtr->array_data + thisPtr->array_index), len);
    // Move pointer
    thisPtr->array_index += len;
  }
  return len;
}
References TJpg_Decoder(), array_data, array_index, array_size, FL_NOEXCEPT, jpg_source, fl::memcpy(), and fl::third_party::TJPG_ARRAY.
Referenced by drawJpg(), and getJpgSize().