FastLED: fl::third_party::TJpg_Decoder::drawJpg
drawJpg()
JRESULT fl::third_party::TJpg_Decoder::drawJpg (int32_t x, int32_t y, const uint8_t array[], size_t array_size)
Definition at line 137 of file TJpg_Decoder.cpp.hpp.
{
  JDEC jdec;
  JRESULT jresult = JDR_OK;
  jpg_source = TJPG_ARRAY;
  array_index = 0;
  array_data  = jpeg_data;
  array_size  = data_size;
  jpeg_x = x;
  jpeg_y = y;
  jdec.swap = _swap;
  // Analyse input data - pass 'this' as device pointer for callbacks
  jresult = jd_prepare(&jdec, jd_input, workspace, TJPGD_WORKSPACE_SIZE, this);
  // Extract image and render
  if (jresult == JDR_OK) {
    // Debug: Check image dimensions from jdec
    // jdec should now have width/height populated
    jresult = jd_decomp(&jdec, jd_output, jpgScale);
  }
  return jresult;
}
References _swap, array_data, array_index, array_size, FL_NOEXCEPT, fl::third_party::jd_decomp(), jd_input(), jd_output(), fl::third_party::jd_prepare(), fl::third_party::JDR_OK, jpeg_x, jpeg_y, jpg_source, jpgScale, fl::third_party::JDEC::swap, fl::third_party::TJPG_ARRAY, TJPGD_WORKSPACE_SIZE, workspace, fl::x, and fl::y.