FastLED: fl::net::http::HttpStreamTransport::rpcStream
rpcStream() [1/2]
StreamHandle fl::net::http::HttpStreamTransport::rpcStream (const fl::json & fullRequest)
Send a streaming pre-built JSON-RPC request.
Definition at line 246 of file stream_transport.cpp.hpp.
{
    auto updateCb = fl::make_shared<fl::function<void(const fl::json&)>>();
    fl::task::Promise<fl::json> p = fl::task::Promise<fl::json>::create();
    if (!isConnected()) {
        p.complete_with_error(fl::task::Error("Not connected"));
        return StreamHandle(fl::move(p), fl::move(updateCb));
    }
    fl::string idKey = idToString(fullRequest["id"]);
    PendingStream ps;
    ps.promise = p;
    ps.updateCallback = updateCb;
    mPendingStreams.insert(idKey, fl::move(ps));
    writeResponse(fullRequest);
    return StreamHandle(p, updateCb);
}
References fl::task::Promise< T >::create(), idToString(), isConnected(), fl::make_shared(), fl::fl::move(), mPendingStreams, ps, and writeResponse().