FastLED: fl::net::http::HttpStreamTransport::rpc
rpc() [1/2]
fl::task::Promise< fl::json > fl::net::http::HttpStreamTransport::rpc (const fl::json & fullRequest)
Send a pre-built JSON-RPC request.
Definition at line 219 of file stream_transport.cpp.hpp.
{
    fl::task::Promise<fl::json> p = fl::task::Promise<fl::json>::create();
    if (!isConnected()) {
        p.complete_with_error(fl::task::Error("Not connected"));
        return p;
    }
    fl::string idKey = idToString(fullRequest["id"]);
    PendingCall pc;
    pc.promise = p;
    mPendingCalls.insert(idKey, fl::move(pc));
    writeResponse(fullRequest);
    return p;
}
References fl::task::Promise< T >::complete_with_error(), fl::task::Promise< T >::create(), idToString(), isConnected(), fl::fl::move(), mPendingCalls, fl::net::http::HttpStreamTransport::PendingCall::promise, and writeResponse().