FastLED: fl::net::http::HttpStreamTransport::update
update()
void fl::net::http::HttpStreamTransport::update (u32 currentTimeMs)
Update connection state (handles reconnection, heartbeat) Call this in main loop.
Parameters
currentTimeMs Current time in milliseconds
Definition at line 324 of file stream_transport.cpp.hpp.
{
    // Update connection state
    mConnection.update(currentTimeMs);
    bool nowConnected = isConnected();
    // Handle state changes
    if (mWasConnected != nowConnected) {
        handleConnectionStateChange(currentTimeMs);
        mWasConnected = nowConnected;
    }
    if (!isConnected()) {
        // Attempt reconnection if needed
        if (mConnection.shouldReconnect()) {
            triggerReconnect();
        }
        return;
    }
    // Send heartbeat if needed
    u32 timeSinceLastSent = currentTimeMs - mLastHeartbeatSent;
    if (timeSinceLastSent >= mHeartbeatInterval) {
        sendHeartbeat();
    }
    // Check for heartbeat timeout
    checkHeartbeatTimeout(currentTimeMs);
    // Process incoming data and drain messages (resolves promises)
    processIncomingData();
    parseChunkedMessages();
}
References checkHeartbeatTimeout(), handleConnectionStateChange(), isConnected(), mConnection, mHeartbeatInterval, mLastHeartbeatSent, mWasConnected, parseChunkedMessages(), processIncomingData(), sendHeartbeat(), and triggerReconnect().
Referenced by isConnected().