const BANNED_HEADERS_COMMON_RS: &[&str] = &[
    "pthread.h",
    "assert.h",
    "iostream",
    "stdio.h",
    "cstdio",
    "cstdlib",
    "vector",
    "list",
    "map",
    "unordered_map",
    "set",
    "unordered_set",
    "multimap",
    "multiset",
    "queue",
    "deque",
    "algorithm",
    "memory",
    "thread",
    "mutex",
    "chrono",
    "fstream",
    "sstream",
    "iomanip",
    "exception",
    "stdexcept",
    "typeinfo",
    "ctime",
    "cmath",
    "math.h",
    "complex",
    "valarray",
    "cfloat",
    "cassert",
    "cerrno",
    "cctype",
    "cwctype",
    "cstring",
    "cwchar",
    "cuchar",
    "cstdint",
    "stdint.h",
    "stddef.h",
    "cstddef",
    "stdlib.h",
    "malloc.h",
    "string.h",
    "type_traits",
    "new",
];

const BANNED_HEADERS_CORE_RS: &[&str] = &[
    "pthread.h",
    "assert.h",
    "iostream",
    "stdio.h",
    "cstdio",
    "cstdlib",
    "vector",
    "list",
    "map",
    "unordered_map",
    "set",
    "unordered_set",
    "multimap",
    "multiset",
    "queue",
    "deque",
    "algorithm",
    "memory",
    "thread",
    "mutex",
    "chrono",
    "fstream",
    "sstream",
    "iomanip",
    "exception",
    "stdexcept",
    "typeinfo",
    "ctime",
    "cmath",
    "math.h",
    "complex",
    "valarray",
    "cfloat",
    "cassert",
    "cerrno",
    "cctype",
    "cwctype",
    "cstring",
    "cwchar",
    "cuchar",
    "cstdint",
    "stdint.h",
    "stddef.h",
    "cstddef",
    "stdlib.h",
    "malloc.h",
    "string.h",
    "type_traits",
    "new",
    "Arduino.h",
];

const BANNED_HEADER_RECOMMENDATIONS: &[(&str, &str)] = &[
    (
        "Arduino.h",
        "fl/system/arduino.h (trampoline that includes Arduino.h + cleans up macros)",
    ),
    (
        "pthread.h",
        "fl/stl/thread.h or fl/stl/mutex.h (depending on what you need)",
    ),
    (
        "assert.h",
        "FL_CHECK or FL_ASSERT macros (check fl/stl/compiler_control.h)",
    ),
    ("iostream", "fl/stl/iostream.h or fl/str.h"),
    (
        "stdio.h",
        "fl/stl/stdio.h (provides fl::printf, fl::snprintf, fl::sprintf)",
    ),
    (
        "cstdio",
        "fl/stl/cstdio.h (provides fl::print, fl::println)",
    ),
    ("cstdlib", "fl/stl/cstdlib.h or fl/string operations"),
    ("vector", "fl/stl/vector.h"),
    ("list", "fl/stl/list.h or fl/stl/vector.h"),
    (
        "map",
        "fl/stl/map.h (check fl/stl/hash_map.h for hash-based)",
    ),
    ("unordered_map", "fl/stl/unordered_map.h"),
    ("set", "fl/stl/set.h"),
    ("unordered_set", "fl/stl/unordered_set.h"),
    ("multimap", "fl/stl/multi_map.h"),
    ("multiset", "fl/stl/multi_set.h"),
    (
        "queue",
        "fl/stl/queue.h or fl/stl/vector.h with manual queue semantics",
    ),
    ("deque", "fl/stl/deque.h"),
    ("algorithm", "fl/stl/algorithm.h"),
    ("memory", "fl/stl/shared_ptr.h or fl/stl/unique_ptr.h"),
    ("thread", "fl/stl/thread.h"),
    ("mutex", "fl/stl/mutex.h"),
    ("chrono", "fl/time.h"),
    ("fstream", "fl/file.h or platform file operations"),
    ("sstream", "fl/stl/sstream.h"),
    ("iomanip", "fl/stl/iostream.h stream manipulators"),
    (
        "exception",
        "Use error codes or fl/stl/exception.h if available",
    ),
    ("stdexcept", "Use error codes instead"),
    (
        "typeinfo",
        "Use fl/stl/type_traits.h or RTTI if unavoidable",
    ),
    ("ctime", "fl/time.h"),
    ("cmath", "fl/math.h"),
    ("math.h", "fl/math.h"),
    ("complex", "Custom complex number class or fl/geometry.h"),
    ("valarray", "fl/stl/vector.h"),
    ("cfloat", "fl/stl/limits.h or platform-specific headers"),
    ("cassert", "FL_CHECK macros from fl/stl/compiler_control.h"),
    ("cerrno", "Error handling through return codes"),
    ("cctype", "Character classification (implement if needed)"),
    (
        "cwctype",
        "Wide character classification (implement if needed)",
    ),
    ("cstring", "fl/str.h or fl/stl/cstring.h"),
    ("cwchar", "Wide character support (implement if needed)"),
    ("cuchar", "Character support (implement if needed)"),
    ("cstdint", "fl/stl/stdint.h"),
    ("stdint.h", "fl/stl/stdint.h"),
    ("stddef.h", "fl/stl/stddef.h or fl/stl/cstddef.h"),
    ("cstddef", "fl/stl/cstddef.h"),
    (
        "stdlib.h",
        "fl/stl/cstdlib.h (provides fl::aligned_alloc, fl::strtol, fl::atoi, etc.)",
    ),
    (
        "malloc.h",
        "fl/stl/cstdlib.h (provides fl::aligned_alloc / fl::aligned_free)",
    ),
    (
        "string.h",
        "fl/str.h (or use extern declarations for memset/memcpy if only C functions needed)",
    ),
    ("type_traits", "fl/stl/type_traits.h"),
    (
        "new",
        "Use stack allocation or custom allocators (placement new allowed in inplacenew.h)",
    ),
];

const PRIVATE_LIBCPP_HEADER_MAPPINGS_RS: &[(&str, &str)] = &[
    ("__algorithm", "\"fl/stl/algorithm.h\""),
    ("__atomic", "\"fl/stl/atomic.h\""),
    ("__chrono", "\"fl/stl/thread.h\""),
    ("__functional", "\"fl/stl/functional.h\""),
    ("__fwd/string", "\"fl/stl/string.h\""),
    ("__iterator", "\"fl/stl/iterator.h\""),
    ("__numeric", "\"fl/stl/algorithm.h\""),
    ("__ostream", "\"fl/stl/ostream.h\""),
    ("__random", "\"fl/math/random.h\""),
    ("__thread", "\"fl/stl/thread.h\""),
    ("__type_traits", "\"fl/stl/type_traits.h\""),
    ("__utility", "\"fl/stl/utility.h\""),
    ("__vector", "\"fl/stl/vector.h\""),
    ("__hash_table", "\"fl/stl/unordered_map.h\""),
    ("__tree", "\"fl/stl/map.h\""),
    ("__node_handle", "\"fl/stl/unordered_map.h\""),
];

const BANNED_HEADER_EXCEPTIONS: &[(&str, &str)] = &[
    ("new", "inplacenew.h"),
    ("new", "platforms/wasm/new.h"),
    ("new", "platforms/arm/new.h"),
    ("new", "platforms/esp/new.h"),
    ("new", "platforms/shared/new.h"),
    ("Arduino.h", "fl/system/arduino.h"),
    ("Arduino.h", "third_party/ezws2812/ezWS2812.h"),
    (
        "Arduino.h",
        "third_party/object_fled/src/ObjectFLEDDmaManager.h",
    ),
    ("Arduino.h", "platforms/wasm/compiler/Arduino.h"),
    ("Arduino.h", "platforms/wasm/led_sysdefs_wasm.h"),
    ("pthread.h", "fl/stl/thread_local.h"),
    ("mutex", "fl/stl/mutex.h"),
    ("mutex", "platforms/stub/thread_stub_stl.h"),
    ("mutex", "platforms/stub/mutex_stub_stl.h"),
    ("mutex", "platforms/esp/32/mutex_esp32.h"),
    ("mutex", "platforms/arm/stm32/mutex_stm32.h"),
    ("mutex", "platforms/arm/d21/mutex_samd.h"),
    ("mutex", "platforms/arm/rp/mutex_rp.h"),
    ("thread", "fl/async.cpp.hpp"),
    ("thread", "platforms/stub/isr_stub.hpp"),
    ("thread", "platforms/stub/time_stub.cpp"),
    ("thread", "platforms/stub/thread_stub_stl.h"),
    ("thread", "platforms/wasm/timer.cpp"),
    ("iostream", "platforms/stub/isr_stub.hpp"),
    ("algorithm", "fl/stl/mutex.h"),
    ("algorithm", "platforms/stub/fs_stub.hpp"),
    ("stdint.h", "fl/stl/stdint.h"),
    ("stdint.h", "fl/stl/time.cpp"),
    ("stdint.h", "fl/stl/time.cpp.hpp"),
    ("chrono", "fl/stl/time.cpp"),
    ("chrono", "fl/stl/time.cpp.hpp"),
    ("chrono", "platforms/stub/isr_stub.hpp"),
    ("chrono", "platforms/stub/time_stub.cpp"),
    ("chrono", "platforms/esp/32/condition_variable_esp32.h"),
    ("chrono", "platforms/esp/32/semaphore_esp32.h"),
    ("string.h", "fl/stl/str.cpp"),
    ("string.h", "fl/stl/cstring.cpp.hpp"),
    ("string.h", "fl/stl/detail/string_holder.cpp.hpp"),
    ("stdlib.h", "fl/stl/str.cpp"),
    ("stdlib.h", "fl/stl/cstdlib.cpp.hpp"),
    ("stdlib.h", "fl/stl/cstring.cpp.hpp"),
    ("stdlib.h", "fl/stl/detail/string_holder.cpp.hpp"),
    ("stdlib.h", "fl/stl/malloc.cpp.hpp"),
    ("stdlib.h", "fl/stl/undef.h"),
    ("stdlib.h", "platforms/arm/teensy/coroutine_teensy.impl.hpp"),
    (
        "stdlib.h",
        "platforms/shared/mock/esp/32/drivers/spi_peripheral_mock.cpp.hpp",
    ),
    ("stdlib.h", "platforms/shared/ui/json/json_console.cpp.hpp"),
    ("stdlib.h", "third_party/libhelix_mp3/real/buffers.hpp"),
    ("stdlib.h", "third_party/stb/truetype/stb_truetype.cpp.hpp"),
    ("malloc.h", "fl/stl/cstdlib.cpp.hpp"),
    ("malloc.h", "fl/stl/alloca.h"),
    (
        "malloc.h",
        "platforms/shared/mock/esp/32/drivers/spi_peripheral_mock.cpp.hpp",
    ),
    ("malloc.h", "third_party/stb/stb_vorbis.cpp.hpp"),
    ("math.h", "fl/math/math.cpp"),
    ("math.h", "fl/math/math.cpp.hpp"),
    ("math.h", "fl/audio/audio_reactive.cpp"),
    ("math.h", "fl/colorutils.cpp"),
    ("math.h", "fl/transform.cpp"),
    ("math.h", "fl/xypath.cpp"),
    ("math.h", "fl/xypath_impls.cpp"),
    ("math.h", "fl/xypath_renderer.cpp"),
    ("math.h", "fx/video/frame_interpolator.cpp"),
    ("cmath", "platforms/wasm/timer.cpp"),
    ("cerrno", "fl/stl/cerrno.h"),
    ("cerrno", "fl/stl/fstream.h"),
    ("cstdio", "fl/stl/detail/file_io.h"),
    ("cstdio", "platforms/stub/fs_stub.hpp"),
    ("cstdio", "platforms/wasm/io_wasm.h"),
    ("cstdio", "platforms/wasm/compiler/wasm_pch.h"),
    ("cstdlib", "fl/stl/cstdlib.cpp.hpp"),
];

