use glob::glob;
use rayon::prelude::*;
use regex::Regex;
use serde::{Deserialize, Serialize};
use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};
use std::error::Error;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;
use walkdir::WalkDir;

type DynError = Box<dyn Error + Send + Sync>;

const CPP_EXTENSIONS: &[&str] = &["cpp", "h", "hpp", "ino", "cpp.hpp"];

const EXCLUDED_FILES: &[&str] = &[
    "stub_main.cpp",
    "doctest_main.cpp",
    "fltest.h",
    "doctest.h",
    "crash_handler_execinfo.h",
    "crash_handler_libunwind.h",
    "crash_handler_noop.h",
    "crash_handler_win.h",
    "run_example.h",
    "run_unit_test.h",
    "platforms/apple/run_example.hpp",
    "platforms/apple/run_unit_test.hpp",
    "platforms/posix/run_example.hpp",
    "platforms/posix/run_unit_test.hpp",
    "platforms/win/run_example.hpp",
    "platforms/win/run_unit_test.hpp",
];

const BARE_ALLOCATION_WHITELISTED_SUFFIXES: &[&str] = &[
    "fl/stl/allocator.h",
    "fl/stl/allocator.cpp.hpp",
    "fl/stl/malloc.h",
    "fl/stl/malloc.cpp.hpp",
    "fl/stl/new.h",
    "fl/stl/unique_ptr.h",
    "fl/stl/shared_ptr.h",
    "fl/stl/shared_ptr.cpp.hpp",
    "fl/stl/scoped_ptr.h",
    "fl/stl/weak_ptr.h",
    "fl/stl/detail/string_holder.cpp.hpp",
    "fl/system/heap.h",
    "fl/system/heap.cpp.hpp",
];

const SLEEP_FOR_WHITELISTED_SUFFIXES: &[&str] = &[
    "fl/stl/thread.h",
    "platforms/stub/thread_stub_stl.h",
    "platforms/stub/thread_stub_noop.h",
    "platforms/stub/platform_time.cpp.hpp",
    "fl/async.cpp.hpp",
    "platforms/shared/spi_bitbang/host_timer.cpp.hpp",
    "platforms/stub/coroutine_stub.impl.hpp",
];

const VALID_INCLUDE_PREFIXES: &[&str] = &["fl/", "platforms/", "fx/", "sensors/", "third_party/"];

const EXTERNAL_SDK_PREFIXES: &[&str] = &[
    "driver/",
    "esp_",
    "esp32/",
    "freertos/",
    "hal/",
    "soc/",
    "rom/",
    "sdkconfig",
    "xtensa/",
    "riscv/",
    "hardware/",
    "pico/",
    "boards/",
    "cmsis/",
    "class/",
    "tusb_",
    "Arduino.h",
    "Wire.h",
    "SPI.h",
    "pins_arduino.h",
    "util/",
    "core_",
    "cmsis_",
    "nrf_",
    "nrf52",
    "nrfx",
    "stm32",
    "core_pins.h",
    "usb_",
    "kinetis.h",
    "imxrt.h",
    "RP2040.h",
    "RP2350.h",
    "bsp_",
    "r_",
    "fsp/",
];

const AMBIGUOUS_INCLUDE_PREFIXES: &[&str] = &["avr/", "arm/"];

const FASTLED_PLATFORM_SUBDIRS: &[&str] = &[
    "adafruit/",
    "apollo3/",
    "arm/",
    "avr/",
    "esp/",
    "shared/",
    "stub/",
    "wasm/",
    "posix/",
];

const BANNED_INTERNAL_SUBPATHS: &[(&str, &str)] = &[("fl/math/lib8tion/", "fl/math/")];

const TYPO_INCLUDE_PREFIXES: &[(&str, &str)] = &[
    ("fL/", "fl/"),
    ("FL/", "fl/"),
    ("Fl/", "fl/"),
    ("platform/", "platforms/"),
    ("Platform/", "platforms/"),
    ("PLATFORMS/", "platforms/"),
];

const ARDUINO_BANNED_MACROS: &[&str] = &["INPUT", "OUTPUT", "DEFAULT"];

const ATTRIBUTE_MAPPINGS: &[(&str, &str)] = &[
    ("maybe_unused", "FL_MAYBE_UNUSED"),
    ("nodiscard", "FL_NODISCARD"),
    ("fallthrough", "FL_FALLTHROUGH"),
    ("deprecated", "FL_DEPRECATED"),
    ("noreturn", "FL_NORETURN"),
    ("likely", "FL_LIKELY"),
    ("unlikely", "FL_UNLIKELY"),
    ("no_unique_address", "FL_NO_UNIQUE_ADDRESS"),
];

const NUMERIC_LIMIT_MACROS: &[&str] = &[
    "UINT8_MAX",
    "UINT16_MAX",
    "UINT32_MAX",
    "UINT64_MAX",
    "UINTMAX_MAX",
    "UINTPTR_MAX",
    "SIZE_MAX",
    "INT8_MAX",
    "INT16_MAX",
    "INT32_MAX",
    "INT64_MAX",
    "INTMAX_MAX",
    "INTPTR_MAX",
    "INT8_MIN",
    "INT16_MIN",
    "INT32_MIN",
    "INT64_MIN",
    "INTMAX_MIN",
    "INTPTR_MIN",
    "UCHAR_MAX",
    "USHRT_MAX",
    "UINT_MAX",
    "ULONG_MAX",
    "ULLONG_MAX",
    "CHAR_MAX",
    "SHRT_MAX",
    "INT_MAX",
    "LONG_MAX",
    "LLONG_MAX",
    "CHAR_MIN",
    "SHRT_MIN",
    "INT_MIN",
    "LONG_MIN",
    "LLONG_MIN",
];

const NUMERIC_LIMIT_EXCLUDED_SUFFIXES: &[&str] =
    &["tests/fl/stl/cstdint.cpp", "tests/fl/stl/stdint.cpp"];

const STD_BRIDGE_FILE_WHITELIST: &[&str] = &[
    "platforms/stub/mutex_stub_stl.h",
    "platforms/stub/mutex_stub_noop.h",
    "platforms/esp/32/mutex_esp32.h",
    "platforms/arm/rp/mutex_rp.h",
    "platforms/arm/stm32/mutex_stm32.h",
    "platforms/arm/stm32/mutex_stm32_rtos.h",
    "platforms/arm/d21/mutex_samd.h",
    "platforms/arm/nrf52/mutex_nrf52.h",
    "platforms/stub/condition_variable_stub.h",
    "platforms/esp/32/condition_variable_esp32.h",
    "platforms/esp/32/condition_variable_esp32.cpp.hpp",
    "platforms/stub/thread_stub_stl.h",
    "platforms/stub/thread_stub_noop.h",
    "platforms/stub/semaphore_stub_stl.h",
    "platforms/stub/semaphore_stub_noop.h",
    "platforms/esp/32/semaphore_esp32.h",
    "platforms/arm/d21/semaphore_samd.h",
    "platforms/arm/d21/semaphore_samd.cpp.hpp",
    "platforms/arm/rp/semaphore_rp.h",
    "platforms/arm/rp/semaphore_rp.cpp.hpp",
    "platforms/arm/stm32/semaphore_stm32.h",
    "platforms/arm/stm32/semaphore_stm32.cpp.hpp",
    "platforms/stub/platform_time.cpp.hpp",
    "platforms/apple/run_example.hpp",
    "platforms/apple/run_unit_test.hpp",
    "platforms/posix/run_example.hpp",
    "platforms/posix/run_unit_test.hpp",
    "platforms/win/run_example.hpp",
    "platforms/win/run_unit_test.hpp",
];

const ALLOWED_STD_SYMBOLS: &[&str] = &[
    "std::atomic_thread_fence",
    "std::memory_order_acquire",
    "std::memory_order_release",
    "std::memory_order_seq_cst",
    "std::memory_order_relaxed",
    "std::memory_order_acq_rel",
    "std::memory_order_consume",
];

const FORBIDDEN_SERIAL_METHODS: &[&str] = &[
    "print",
    "println",
    "printf",
    "write",
    "read",
    "available",
    "peek",
    "readStringUntil",
    "flush",
    "begin",
];

const ALLOWED_SERIAL_METHODS: &[&str] = &["setTxBufferSize", "setTxTimeoutMs"];

const INCLUDE_AFTER_NAMESPACE_SKIP_PATTERNS: &[&str] = &[
    ".venv",
    "node_modules",
    "build",
    ".build",
    "third_party",
    "ziglang",
    "greenlet",
    ".git",
];

const PLATFORM_INCLUDE_LOCATIONS: &[&str] = &[
    "/src/fl/",
    "/src/fx/",
    "/src/lib8tion/",
    "/src/sensors/",
    "/tests/fl/",
    "/tests/fx/",
    "/examples/",
];

const DEEP_PLATFORM_REPLACEMENTS: &[(&str, &str)] = &[
    ("platforms/shared/int_windows.h", "platforms/int.h"),
    ("platforms/shared/int.h", "platforms/int.h"),
    ("platforms/esp/", "platforms/init.h"),
    ("platforms/arm/", "platforms/init.h"),
    ("platforms/stub/", "platforms/init.h"),
    ("platforms/avr/", "platforms/init.h"),
    ("platforms/wasm/", "platforms/init.h"),
];

const SIMD_PATTERNS: &[(&str, &str)] = &[
    (
        "__m128i",
        "x86 SSE type — use fl::simd::simd_u8x16 / simd_u16x8 / simd_u32x4",
    ),
    ("__m128", "x86 SSE type — use fl::simd types"),
    ("__m256i", "x86 AVX type — use fl::simd types"),
    ("__m256", "x86 AVX type — use fl::simd types"),
    ("_mm_", "x86 SSE intrinsic — use fl::simd operations"),
    ("_mm256_", "x86 AVX2 intrinsic — use fl::simd operations"),
    ("_mm512_", "x86 AVX-512 intrinsic — use fl::simd operations"),
    ("_MM_HINT", "x86 prefetch hint — use __builtin_prefetch"),
    ("<emmintrin.h>", "SSE2 header — use fl/math/simd.h"),
    ("<immintrin.h>", "AVX header — use fl/math/simd.h"),
    ("<smmintrin.h>", "SSE4.1 header — use fl/math/simd.h"),
    ("<xmmintrin.h>", "SSE header — use fl/math/simd.h"),
    ("<tmmintrin.h>", "SSSE3 header — use fl/math/simd.h"),
    ("<arm_neon.h>", "ARM NEON header — use fl/math/simd.h"),
    ("vld1q_", "ARM NEON intrinsic — use fl::simd operations"),
    ("vst1q_", "ARM NEON intrinsic — use fl::simd operations"),
    ("vaddq_", "ARM NEON intrinsic — use fl::simd operations"),
    ("vmulq_", "ARM NEON intrinsic — use fl::simd operations"),
    ("vmovl_", "ARM NEON intrinsic — use fl::simd operations"),
    ("vqmovn_", "ARM NEON intrinsic — use fl::simd operations"),
    ("vcombine_", "ARM NEON intrinsic — use fl::simd operations"),
    ("vdupq_", "ARM NEON intrinsic — use fl::simd operations"),
    ("ee.vadds", "Xtensa PIE intrinsic — use fl::simd operations"),
    ("ee.vld", "Xtensa PIE intrinsic — use fl::simd operations"),
    ("ee.vst", "Xtensa PIE intrinsic — use fl::simd operations"),
];

const CTYPE_FUNCTIONS: &[&str] = &[
    "isspace", "isdigit", "isalpha", "isalnum", "isupper", "islower", "tolower", "toupper",
];

const CSTRING_FUNCTIONS: &[&str] = &[
    "strlen", "strcmp", "strncmp", "strcpy", "strncpy", "strcat", "strncat", "strstr", "strchr",
    "strrchr", "strspn", "strcspn", "strpbrk", "strtok", "strerror", "memcpy", "memcmp", "memmove",
    "memset", "memchr",
];

const CTYPE_WHITELISTED_SUFFIXES: &[&str] = &[
    "fl/stl/cctype.h",
    "fl/stl/cstring.h",
    "fl/stl/cstring.cpp.hpp",
];

const STDINT_TYPE_MAPPINGS: &[(&str, &str)] = &[
    ("uint8_t", "u8"),
    ("uint16_t", "u16"),
    ("uint32_t", "u32"),
    ("uint64_t", "u64"),
    ("int8_t", "i8"),
    ("int16_t", "i16"),
    ("int32_t", "i32"),
    ("int64_t", "i64"),
    ("unsigned int", "u32"),
    ("signed int", "i32"),
];

const STDINT_EXCLUDED_FILENAMES: &[&str] = &[
    "stdint.h",
    "int.h",
    "run_unit_test.hpp",
    "dual_isr_context.h",
    "mcpwm_timer.h",
];

const UNIT_TEST_EXEMPT_FILES: &[&str] = &["test.h", "doctest.h", "doctest_main.cpp"];

const UNIT_TEST_BANNED_MACROS: &[(&str, &str)] = &[
    ("TEST_CASE_TEMPLATE", "FL_TEST_CASE_TEMPLATE"),
    ("TEST_CASE_FIXTURE", "FL_TEST_CASE_FIXTURE"),
    (
        "REQUIRE_THROWS_WITH_MESSAGE",
        "FL_REQUIRE_THROWS_WITH_MESSAGE",
    ),
    ("CHECK_FALSE_MESSAGE", "FL_CHECK_FALSE_MESSAGE"),
    ("REQUIRE_FALSE_MESSAGE", "FL_REQUIRE_FALSE_MESSAGE"),
    ("WARN_FALSE_MESSAGE", "FL_WARN_FALSE_MESSAGE"),
    ("REQUIRE_THROWS_WITH", "FL_REQUIRE_THROWS_WITH"),
    ("CHECK_FALSE", "FL_CHECK_FALSE"),
    ("CHECK_MESSAGE", "FL_CHECK_MESSAGE"),
    ("CHECK_THROWS_AS", "FL_CHECK_THROWS_AS"),
    ("CHECK_THROWS_WITH", "FL_CHECK_THROWS_WITH"),
    ("REQUIRE_FALSE", "FL_REQUIRE_FALSE"),
    ("REQUIRE_MESSAGE", "FL_REQUIRE_MESSAGE"),
    ("REQUIRE_THROWS_AS", "FL_REQUIRE_THROWS_AS"),
    ("WARN_FALSE", "FL_DWARN_FALSE"),
    ("WARN_MESSAGE", "FL_WARN_MESSAGE"),
    ("WARN_THROWS_AS", "FL_WARN_THROWS_AS"),
    ("WARN_THROWS_WITH", "FL_WARN_THROWS_WITH"),
    ("TYPE_TO_STRING", "FL_TYPE_TO_STRING"),
    ("CHECK_UNARY_FALSE", "FL_CHECK_UNARY_FALSE"),
    ("REQUIRE_UNARY_FALSE", "FL_REQUIRE_UNARY_FALSE"),
    ("WARN_UNARY_FALSE", "FL_WARN_UNARY_FALSE"),
    ("TEST_CASE", "FL_TEST_CASE"),
    ("TEST_SUITE", "FL_TEST_SUITE"),
    ("CHECK_CLOSE", "FL_CHECK_CLOSE"),
    ("CHECK_DOUBLE_EQ", "FL_CHECK_DOUBLE_EQ"),
    ("CHECK_APPROX", "FL_CHECK_APPROX"),
    ("CHECK_STREQ", "FL_CHECK_STREQ"),
    ("CHECK_THROWS", "FL_CHECK_THROWS"),
    ("CHECK_NOTHROW", "FL_CHECK_NOTHROW"),
    ("CHECK_TRAIT", "FL_CHECK_TRAIT"),
    ("REQUIRE_CLOSE", "FL_REQUIRE_CLOSE"),
    ("REQUIRE_APPROX", "FL_REQUIRE_APPROX"),
    ("REQUIRE_THROWS", "FL_REQUIRE_THROWS"),
    ("REQUIRE_NOTHROW", "FL_REQUIRE_NOTHROW"),
    ("WARN_UNARY", "FL_WARN_UNARY"),
    ("WARN_THROWS", "FL_WARN_THROWS"),
    ("WARN_NOTHROW", "FL_WARN_NOTHROW"),
    ("AND_WHEN", "FL_AND_WHEN"),
    ("AND_THEN", "FL_AND_THEN"),
    ("SUBCASE", "FL_SUBCASE"),
    ("MESSAGE", "FL_MESSAGE"),
    ("CAPTURE", "FL_CAPTURE"),
    ("FAIL_CHECK", "FL_FAIL_CHECK"),
    ("CHECK_UNARY", "FL_CHECK_UNARY"),
    ("CHECK_EQ", "FL_CHECK_EQ"),
    ("CHECK_NE", "FL_CHECK_NE"),
    ("CHECK_GT", "FL_CHECK_GT"),
    ("CHECK_GE", "FL_CHECK_GE"),
    ("CHECK_LT", "FL_CHECK_LT"),
    ("CHECK_LE", "FL_CHECK_LE"),
    ("REQUIRE_UNARY", "FL_REQUIRE_UNARY"),
    ("REQUIRE_EQ", "FL_REQUIRE_EQ"),
    ("REQUIRE_NE", "FL_REQUIRE_NE"),
    ("REQUIRE_GT", "FL_REQUIRE_GT"),
    ("REQUIRE_GE", "FL_REQUIRE_GE"),
    ("REQUIRE_LT", "FL_REQUIRE_LT"),
    ("REQUIRE_LE", "FL_REQUIRE_LE"),
    ("WARN_FALSE", "FL_DWARN_FALSE"),
    ("WARN_EQ", "FL_WARN_EQ"),
    ("WARN_NE", "FL_WARN_NE"),
    ("WARN_GT", "FL_WARN_GT"),
    ("WARN_GE", "FL_WARN_GE"),
    ("WARN_LT", "FL_WARN_LT"),
    ("WARN_LE", "FL_WARN_LE"),
    ("SCENARIO", "FL_SCENARIO"),
    ("REQUIRE", "FL_REQUIRE"),
    ("CHECK", "FL_CHECK"),
    ("GIVEN", "FL_GIVEN"),
    ("WHEN", "FL_WHEN"),
    ("THEN", "FL_THEN"),
    ("INFO", "FL_DINFO"),
    ("FAIL", "FL_FAIL"),
    ("WARN", "FL_DWARN"),
];

const UNIT_TEST_FAST_PREFIXES: &[&str] = &[
    "CHECK",
    "REQUIRE",
    "WARN",
    "TEST_",
    "SUBCASE",
    "FAIL",
    "SCENARIO",
    "GIVEN",
    "WHEN",
    "THEN",
    "AND_",
    "MESSAGE",
    "INFO",
    "CAPTURE",
    "TYPE_TO_STRING",
];

const FL_IS_PREFIX_TO_HEADER: &[(&str, &str)] = &[
    ("FL_IS_RENESAS", "is_renesas.h"),
    ("FL_IS_APOLLO3", "is_apollo3.h"),
    ("FL_IS_STM32", "is_stm32.h"),
    ("FL_IS_TEENSY", "is_teensy.h"),
    ("FL_IS_NRF52", "is_nrf52.h"),
    ("FL_IS_SILABS", "is_silabs.h"),
    ("FL_IS_POSIX", "is_posix.h"),
    ("FL_IS_WASM", "is_wasm.h"),
    ("FL_IS_STUB", "is_stub.h"),
    ("FL_IS_AVR", "is_avr.h"),
    ("FL_IS_ESP", "is_esp.h"),
    ("FL_IS_ARM", "is_arm.h"),
    ("FL_IS_SAMD", "is_samd.h"),
    ("FL_IS_SAM", "is_sam.h"),
    ("FL_IS_WIN", "is_win.h"),
    ("FL_IS_RP", "is_rp.h"),
];

const IWYU_INTERNAL_HEADER_PREFIXES: &[&str] = &["fl/", "fx/", "sensors/", "lib8tion/"];

const TEST_PATH_EXCLUDED_FILES: &[&str] = &[
    "doctest_main.cpp",
    "audio.cpp",
    "codec.cpp",
    "log.cpp",
    "detectors.cpp",
    "encoders.cpp",
    "2d.cpp",
    "validation.cpp",
    "draw_ring.hpp",
    "draw_thick_line.hpp",
    "draw_line.hpp",
    "draw_disc.hpp",
    "draw_disc_16.hpp",
    "perf_primitives.hpp",
    "gain.hpp",
    "test_helpers.hpp",
    "vocal_real_audio.hpp",
    "map_range.hpp",
    "assume_aligned.hpp",
    "insert_result.hpp",
    "active_strip_data_json.cpp",
    "audio_url.cpp",
    "bytestream.cpp",
    "clamp.cpp",
    "force_inline.cpp",
    "hsv2rgb_accuracy.cpp",
    "noise_range.cpp",
    "noise_ring.cpp",
    "power_estimation.cpp",
    "slice.cpp",
    "unused.cpp",
    "channel_manager.cpp",
    "spi_channel.cpp",
    "wave8_spi.cpp",
    "loopback.cpp",
    "rpc.cpp",
    "rpc_http_stream.cpp",
    "adversarial.cpp",
    "deficiencies.cpp",
    "sound_level_meter.cpp",
    "allocator_move.cpp",
    "cstdint.cpp",
    "function_list.cpp",
    "strstream_integers.cpp",
    "test_tcp_socket.cpp",
    "test_tcp_acceptor.cpp",
    "http_promise.cpp",
    "http_transport.cpp",
    "server_loopback.cpp",
];

const HEADERS_EXIST_EXCLUDED_FILES: &[&str] = &[
    "doctest_main.cpp",
    "sketch_runner.cpp",
    "spi_batching_logic.cpp",
    "serial_printf.cpp",
    "test_runner.cpp",
    "runner.cpp",
    "crash_handler_main.cpp",
    "example_runner.cpp",
    "fltest_self_test.cpp",
    "asan_leak.cpp",
    "test_helpers.hpp",
    "codec.cpp",
    "log.cpp",
    "detectors.cpp",
    "encoders.cpp",
    "2d.cpp",
    "validation.cpp",
    "rpc.cpp",
];

const TEST_CONFIG_EXCLUDED_DIRS: &[&str] = &[
    "tests/shared",
    "tests/testing",
    "tests/data",
    "tests/manual",
    "tests/profile",
    "tests/build",
    "tests/builddir",
    "tests/x64",
    "tests/bin",
    "tests/example_compile_direct",
    "tests/fastled_js",
    "tests/fl/chipsets/encoders",
    "tests/fl/log",
    "tests/fl/channels/detail/validation",
    "tests/fl/remote/rpc",
    "tests/fl/codec",
    "tests/fl/fx/2d",
    "tests/fbuild_qemu_smoke",
];

const TEST_AGGREGATED_DIRS: &[&str] = &[
    "tests/fl/chipsets/encoders",
    "tests/fl/log",
    "tests/fl/channels/detail/validation",
    "tests/fl/remote/rpc",
    "tests/fl/codec",
    "tests/fl/fx/2d",
];

const TEST_INCLUDE_VALID_PREFIXES: &[&str] = &[
    "fl/",
    "platforms/",
    "fx/",
    "sensors/",
    "third_party/",
    "tests/",
];

const NOEXCEPT_CTOR_QUALS: &[&str] = &[
    "",
    "explicit",
    "virtual",
    "inline",
    "constexpr",
    "explicit constexpr",
    "constexpr explicit",
    "inline explicit",
    "explicit inline",
    "inline constexpr",
    "constexpr inline",
    "virtual explicit",
    "explicit virtual",
    "inline virtual",
    "virtual inline",
];

const NATIVE_TO_MODERN_DEFINES: &[(&str, &str)] = &[
    ("__AVR__", "FL_IS_AVR"),
    ("__AVR_ATmega328P__", "FL_IS_AVR_ATMEGA_328P"),
    ("__AVR_ATmega328PB__", "FL_IS_AVR_ATMEGA_328P"),
    ("__AVR_ATmega328__", "FL_IS_AVR_ATMEGA_328P"),
    ("__AVR_ATmega168P__", "FL_IS_AVR_ATMEGA_328P"),
    ("__AVR_ATmega168__", "FL_IS_AVR_ATMEGA_328P"),
    ("__AVR_ATmega8__", "FL_IS_AVR_ATMEGA_328P"),
    ("__AVR_ATmega8A__", "FL_IS_AVR_ATMEGA_328P"),
    ("__AVR_ATmega2560__", "FL_IS_AVR_ATMEGA_2560"),
    ("__AVR_ATmega1280__", "FL_IS_AVR_ATMEGA_2560"),
    ("__AVR_ATmega32U4__", "FL_IS_AVR_ATMEGA"),
    ("__AVR_ATmega1284__", "FL_IS_AVR_ATMEGA"),
    ("__AVR_ATmega1284P__", "FL_IS_AVR_ATMEGA"),
    ("__AVR_ATmega644P__", "FL_IS_AVR_ATMEGA"),
    ("__AVR_ATmega644__", "FL_IS_AVR_ATMEGA"),
    ("__AVR_ATmega32__", "FL_IS_AVR_ATMEGA"),
    ("__AVR_ATmega16__", "FL_IS_AVR_ATMEGA"),
    ("__AVR_ATmega128__", "FL_IS_AVR_ATMEGA"),
    ("__AVR_ATmega64__", "FL_IS_AVR_ATMEGA"),
    ("__AVR_ATmega32U2__", "FL_IS_AVR_ATMEGA"),
    ("__AVR_ATmega16U2__", "FL_IS_AVR_ATMEGA"),
    ("__AVR_ATmega8U2__", "FL_IS_AVR_ATMEGA"),
    ("__AVR_AT90USB1286__", "FL_IS_AVR_ATMEGA"),
    ("__AVR_AT90USB646__", "FL_IS_AVR_ATMEGA"),
    ("__AVR_AT90USB162__", "FL_IS_AVR_ATMEGA"),
    ("__AVR_AT90USB82__", "FL_IS_AVR_ATMEGA"),
    ("__AVR_ATmega128RFA1__", "FL_IS_AVR_ATMEGA"),
    ("__AVR_ATmega256RFR2__", "FL_IS_AVR_ATMEGA"),
    ("__AVR_ATmega4809__", "FL_IS_AVR_MEGAAVR"),
    ("__AVR_ATmega4808__", "FL_IS_AVR_MEGAAVR"),
    ("__AVR_ATmega3209__", "FL_IS_AVR_MEGAAVR"),
    ("__AVR_ATmega3208__", "FL_IS_AVR_MEGAAVR"),
    ("__AVR_ATmega1609__", "FL_IS_AVR_MEGAAVR"),
    ("__AVR_ATmega1608__", "FL_IS_AVR_MEGAAVR"),
    ("__AVR_ATmega809__", "FL_IS_AVR_MEGAAVR"),
    ("__AVR_ATmega808__", "FL_IS_AVR_MEGAAVR"),
    ("__AVR_ATtiny13__", "FL_IS_AVR_ATTINY"),
    ("__AVR_ATtiny13A__", "FL_IS_AVR_ATTINY"),
    ("__AVR_ATtiny24__", "FL_IS_AVR_ATTINY"),
    ("__AVR_ATtiny44__", "FL_IS_AVR_ATTINY"),
    ("__AVR_ATtiny84__", "FL_IS_AVR_ATTINY"),
    ("__AVR_ATtiny25__", "FL_IS_AVR_ATTINY"),
    ("__AVR_ATtiny45__", "FL_IS_AVR_ATTINY"),
    ("__AVR_ATtiny85__", "FL_IS_AVR_ATTINY"),
    ("__AVR_ATtiny48__", "FL_IS_AVR_ATTINY"),
    ("__AVR_ATtiny87__", "FL_IS_AVR_ATTINY"),
    ("__AVR_ATtiny88__", "FL_IS_AVR_ATTINY"),
    ("__AVR_ATtiny167__", "FL_IS_AVR_ATTINY"),
    ("__AVR_ATtiny261__", "FL_IS_AVR_ATTINY"),
    ("__AVR_ATtiny441__", "FL_IS_AVR_ATTINY"),
    ("__AVR_ATtiny841__", "FL_IS_AVR_ATTINY"),
    ("__AVR_ATtiny861__", "FL_IS_AVR_ATTINY"),
    ("__AVR_ATtiny2313__", "FL_IS_AVR_ATTINY"),
    ("__AVR_ATtiny2313A__", "FL_IS_AVR_ATTINY"),
    ("__AVR_ATtiny4313__", "FL_IS_AVR_ATTINY"),
    ("__AVR_ATtinyX41__", "FL_IS_AVR_ATTINY"),
    ("__AVR_ATtiny202__", "FL_IS_AVR_ATTINY_MODERN"),
    ("__AVR_ATtiny204__", "FL_IS_AVR_ATTINY_MODERN"),
    ("__AVR_ATtiny212__", "FL_IS_AVR_ATTINY_MODERN"),
    ("__AVR_ATtiny214__", "FL_IS_AVR_ATTINY_MODERN"),
    ("__AVR_ATtiny402__", "FL_IS_AVR_ATTINY_MODERN"),
    ("__AVR_ATtiny404__", "FL_IS_AVR_ATTINY_MODERN"),
    ("__AVR_ATtiny406__", "FL_IS_AVR_ATTINY_MODERN"),
    ("__AVR_ATtiny407__", "FL_IS_AVR_ATTINY_MODERN"),
    ("__AVR_ATtiny412__", "FL_IS_AVR_ATTINY_MODERN"),
    ("__AVR_ATtiny414__", "FL_IS_AVR_ATTINY_MODERN"),
    ("__AVR_ATtiny416__", "FL_IS_AVR_ATTINY_MODERN"),
    ("__AVR_ATtiny417__", "FL_IS_AVR_ATTINY_MODERN"),
    ("__AVR_ATtiny1604__", "FL_IS_AVR_ATTINY_MODERN"),
    ("__AVR_ATtiny1616__", "FL_IS_AVR_ATTINY_MODERN"),
    ("__AVR_ATtiny3216__", "FL_IS_AVR_ATTINY_MODERN"),
    ("__AVR_ATtiny3217__", "FL_IS_AVR_ATTINY_MODERN"),
    ("__AVR_ATtinyxy4__", "FL_IS_AVR_ATTINY_MODERN"),
    ("__AVR_ATtinyxy6__", "FL_IS_AVR_ATTINY_MODERN"),
    ("__AVR_ATtinyxy7__", "FL_IS_AVR_ATTINY_MODERN"),
    ("__AVR_ATtinyxy2__", "FL_IS_AVR_ATTINY_MODERN"),
    ("ARDUINO_AVR_DIGISPARK", "FL_IS_AVR_ATTINY"),
    ("ARDUINO_AVR_DIGISPARKPRO", "FL_IS_AVR_ATTINY"),
    ("IS_BEAN", "FL_IS_AVR_ATTINY"),
    ("ESP32", "FL_IS_ESP32"),
    ("ESP8266", "FL_IS_ESP8266"),
    ("ESP_PLATFORM", "FL_IS_ESP32"),
    ("ARDUINO_ARCH_ESP32", "FL_IS_ESP32"),
    ("ARDUINO_ARCH_ESP8266", "FL_IS_ESP8266"),
    ("CONFIG_IDF_TARGET_ESP32", "FL_IS_ESP_32DEV"),
    ("CONFIG_IDF_TARGET_ESP32S2", "FL_IS_ESP_32S2"),
    ("CONFIG_IDF_TARGET_ESP32S3", "FL_IS_ESP_32S3"),
    ("CONFIG_IDF_TARGET_ESP32C2", "FL_IS_ESP_32C2"),
    ("CONFIG_IDF_TARGET_ESP32C3", "FL_IS_ESP_32C3"),
    ("CONFIG_IDF_TARGET_ESP32C5", "FL_IS_ESP_32C5"),
    ("CONFIG_IDF_TARGET_ESP32C6", "FL_IS_ESP_32C6"),
    ("CONFIG_IDF_TARGET_ESP32H2", "FL_IS_ESP_32H2"),
    ("CONFIG_IDF_TARGET_ESP32P4", "FL_IS_ESP_32P4"),
    ("CONFIG_IDF_TARGET_ESP8266", "FL_IS_ESP8266"),
    ("CONFIG_IDF_TARGET_ARCH_XTENSA", "FL_IS_ESP32_XTENSA"),
    ("CONFIG_IDF_TARGET_ARCH_RISCV", "FL_IS_ESP32_RISCV"),
    ("ESP32S3", "FL_IS_ESP_32S3"),
    ("ESP32C3", "FL_IS_ESP_32C3"),
    ("ESP32C6", "FL_IS_ESP_32C6"),
    ("__MK20DX128__", "FL_IS_TEENSY_30"),
    ("__MK20DX256__", "FL_IS_TEENSY_3X"),
    ("__MKL26Z64__", "FL_IS_TEENSY_LC"),
    ("__MK64FX512__", "FL_IS_TEENSY_35"),
    ("__MK66FX1M0__", "FL_IS_TEENSY_36"),
    ("__IMXRT1062__", "FL_IS_TEENSY_4X"),
    ("__IMXRT1052__", "FL_IS_TEENSY_4X"),
    ("__arm__", "FL_IS_ARM"),
    ("__SAM3X8E__", "FL_IS_SAM"),
    ("STM32F10X_MD", "FL_IS_STM32_F1"),
    ("__STM32F1__", "FL_IS_STM32_F1"),
    ("STM32F1", "FL_IS_STM32_F1"),
    ("STM32F1xx", "FL_IS_STM32_F1"),
    ("STM32F2XX", "FL_IS_STM32_F2"),
    ("STM32F2xx", "FL_IS_STM32_F2"),
    ("STM32F4", "FL_IS_STM32_F4"),
    ("STM32F4xx", "FL_IS_STM32_F4"),
    ("STM32F7", "FL_IS_STM32_F7"),
    ("STM32F7xx", "FL_IS_STM32_F7"),
    ("STM32L4", "FL_IS_STM32_L4"),
    ("STM32L4xx", "FL_IS_STM32_L4"),
    ("STM32H7", "FL_IS_STM32_H7"),
    ("STM32H7xx", "FL_IS_STM32_H7"),
    ("STM32G4", "FL_IS_STM32_G4"),
    ("STM32G4xx", "FL_IS_STM32_G4"),
    ("STM32U5", "FL_IS_STM32_U5"),
    ("STM32U5xx", "FL_IS_STM32_U5"),
    ("STM32U585xx", "FL_IS_STM32_U5"),
    ("STM32U585XX", "FL_IS_STM32_U5"),
    ("ARDUINO_UNO_Q", "FL_IS_STM32_U5"),
    ("CONFIG_BOARD_ARDUINO_UNO_Q", "FL_IS_STM32_U5"),
    ("CONFIG_SOC_STM32U585XX", "FL_IS_STM32_U5"),
    ("NRF51", "FL_IS_NRF52"),
    ("NRF52_SERIES", "FL_IS_NRF52"),
    ("NRF52840_XXAA", "FL_IS_NRF52840"),
    ("NRF52833_XXAA", "FL_IS_NRF52833"),
    ("NRF52832_XXAA", "FL_IS_NRF52832"),
    ("NRF52", "FL_IS_NRF52"),
    ("NRF52840", "FL_IS_NRF52840"),
    ("NRF52833", "FL_IS_NRF52833"),
    ("NRF52832", "FL_IS_NRF52832"),
    ("__SAMD21G18A__", "FL_IS_SAMD21"),
    ("__SAMD21J18A__", "FL_IS_SAMD21"),
    ("__SAMD21E17A__", "FL_IS_SAMD21"),
    ("__SAMD21E18A__", "FL_IS_SAMD21"),
    ("__SAMD21__", "FL_IS_SAMD21"),
    ("__SAMD51G19A__", "FL_IS_SAMD51"),
    ("__SAMD51J19A__", "FL_IS_SAMD51"),
    ("__SAME51J19A__", "FL_IS_SAMD51"),
    ("__SAMD51P19A__", "FL_IS_SAMD51"),
    ("__SAMD51P20A__", "FL_IS_SAMD51"),
    ("__SAMD51J20A__", "FL_IS_SAMD51"),
    ("__SAMD51__", "FL_IS_SAMD51"),
    ("TARGET_RP2040", "FL_IS_RP2040"),
    ("ARDUINO_ARCH_RP2040", "FL_IS_RP2040"),
    ("PICO_RP2040", "FL_IS_RP2040"),
    ("ARDUINO_ARCH_RP2350", "FL_IS_RP2350"),
    ("PICO_RP2350", "FL_IS_RP2350"),
    ("ARDUINO_ARCH_SAMD", "FL_IS_SAMD"),
    ("ARDUINO_ARCH_STM32", "FL_IS_STM32"),
    ("ARDUINO_ARCH_NRF52", "FL_IS_NRF52"),
    ("ARDUINO_ARCH_APOLLO3", "FL_IS_APOLLO3"),
    ("ARDUINO_ARCH_RENESAS", "FL_IS_RENESAS"),
    ("ARDUINO_ARCH_RENESAS_UNO", "FL_IS_RENESAS"),
    ("ARDUINO_ARCH_RENESAS_PORTENTA", "FL_IS_RENESAS"),
    ("ARDUINO_ARCH_SILABS", "FL_IS_SILABS"),
    ("ARDUINO_ARCH_AVR", "FL_IS_AVR"),
    ("ARDUINO_ARCH_MBED", "FL_IS_STM32_MBED"),
    ("ARDUINO_SAM_DUE", "FL_IS_SAM"),
    ("ARDUINO_GIGA", "FL_IS_STM32_H7"),
    ("ARDUINO_GIGA_M7", "FL_IS_STM32_H7"),
    ("ARDUINO_NRF52_ADAFRUIT", "FL_IS_NRF52"),
    ("__EMSCRIPTEN__", "FL_IS_WASM"),
    ("SPARK", "FL_IS_STM32_F2"),
    ("APOLLO3", "FL_IS_APOLLO3"),
    ("TEENSYDUINO", "FL_IS_TEENSY"),
    ("CORE_TEENSY", "FL_IS_TEENSY"),
    ("FASTLED_TEENSY3", "FL_IS_TEENSY_3X"),
    ("FASTLED_TEENSY4", "FL_IS_TEENSY_4X"),
    ("FASTLED_TEENSYLC", "FL_IS_TEENSY_LC"),
    ("__RFduino__", "FL_IS_NRF52"),
    ("__Simblee__", "FL_IS_NRF52"),
    ("__APPLE__", "FL_IS_APPLE"),
    ("__linux__", "FL_IS_LINUX"),
    ("__unix__", "FL_IS_POSIX"),
    ("_WIN32", "FL_IS_WIN"),
    ("_WIN64", "FL_IS_WIN"),
    ("__CYGWIN__", "FL_IS_WIN"),
    ("__MINGW32__", "FL_IS_WIN_MINGW"),
    ("__MINGW64__", "FL_IS_WIN_MINGW"),
    ("_MSC_VER", "FL_IS_WIN_MSVC"),
    ("__FreeBSD__", "FL_IS_BSD"),
    ("__OpenBSD__", "FL_IS_BSD"),
    ("__NetBSD__", "FL_IS_BSD"),
    ("__DragonFly__", "FL_IS_BSD"),
    ("__wasm__", "FL_IS_WASM"),
    ("EMSCRIPTEN", "FL_IS_WASM"),
    ("__clang__", "FL_IS_CLANG"),
    ("__GNUC__", "FL_IS_GCC"),
    ("__GNUG__", "FL_IS_GCC"),
];

const NATIVE_ROOT_DISPATCH_HEADERS: &[&str] = &[
    "platforms.h",
    "led_sysdefs.h",
    "fastspi.h",
    "fastled_progmem.h",
];

const NATIVE_DISPATCH_CONFIG_FILES: &[&str] = &["config.h"];

const NATIVE_COMPILER_ABSTRACTION_FILES: &[&str] = &[
    "deprecated.h",
    "align.h",
    "export.h",
    "fltest.h",
    "type_traits.h",
    "m0clockless_c.h",
];

