FastLED: fl::RedBlackTree::Node::Node
Node() [1/2]
template<typename T, typename Compare = less<T>, typename Allocator = allocator_slab<char>> fl::RedBlackTree< T, Compare, Allocator >::Node::Node (const value_type & val, Color c = RED, Node * p = nullptr) inline
Definition at line 44 of file rbtree.h.
            : data(val), color(c), left(nullptr), right(nullptr), parent(p) {}
References Node(), color, data, left, parent, fl::RedBlackTree< T, Compare, Allocator >::RED, and right.
Referenced by Node(), and Node().