FastLED: fl::ScopedWatchdog::ScopedWatchdog
ScopedWatchdog() [2/3]
fl::ScopedWatchdog::ScopedWatchdog (fl::u32 timeout_ms) explicit
Construct with an explicit timeout.
Same semantics as the default constructor — first-call init, feed on construction.
Definition at line 154 of file watchdog.cpp.hpp.
{
    static bool sInitialized = false;
    if (!sInitialized) {
        sInitialized = true;
        platforms::scopedWatchdogFirstInit(timeout_ms);
    }
    // Single-instance enforcement. A second simultaneously-alive ScopedWatchdog
    // is almost always a bug — the timeout argument here was silently ignored
    // (only the first instance gets to arm the WDT). Warn once per process so
    // the developer notices, but still feed so the program survives.
    int& count = platforms::scopedWatchdogActiveCount();
    if (count >= 1) {
        static bool sWarnedOnce = false;
        if (!sWarnedOnce) {
            sWarnedOnce = true;
            platforms::scopedWatchdogPrintLine(fl::string_view(
                "[FastLED.watchdog] WARN: nested FL_WATCHDOG_AUTO() detected — "
                "only one scoped guard should be alive at a time"));
        }
    }
    ++count;
    Watchdog::instance().feed();
}
References fl::Watchdog::feed(), FL_NOEXCEPT, fl::Watchdog::instance(), fl::platforms::scopedWatchdogActiveCount(), fl::platforms::scopedWatchdogFirstInit(), and fl::platforms::scopedWatchdogPrintLine().