FastLED: anonymous_namespace{xypaths.cpp}::make_path
make_path()
fl::shared_ptr< fl::CatmullRomParams > anonymous_namespace{xypaths.cpp}::make_path (int width, int height)
Definition at line 11 of file xypaths.cpp.
{
        // make a triangle.
        fl::shared_ptr<fl::CatmullRomParams> params = fl::make_shared<fl::CatmullRomParams>();
        fl::vector_inlined<fl::vec2f, 5> points;
        points.push_back(fl::vec2f(0.0f, 0.0f));
        points.push_back(fl::vec2f(width / 3, height / 2));
        points.push_back(fl::vec2f(width - 3, height - 1));
        points.push_back(fl::vec2f(0.0f, height - 1));
        points.push_back(fl::vec2f(0.0f, 0.0f));
        for (auto &p : points) {
            p.x = fl::map_range<float, float>(p.x, 0.0f, width - 1, -1.0f, 1.0f);
            p.y = fl::map_range<float, float>(p.y, 0.0f, height - 1, -1.0f, 1.0f);
            params->addPoint(p);
        }
        return params;
    }
References fl::make_shared(), fl::map_range(), and fl::vector< T >::push_back().
Referenced by CreateXYPaths().