FastLED: fl::Server::update
update()
size_t fl::Server::update ()
Main update: pull + push.
Definition at line 32 of file server.cpp.hpp.
                      {
    size_t processed = pull();
    size_t sent = push();
    return processed + sent;
}
References pull(), and push().
Referenced by operator=().