FastLED: fl::detail::TriangularFilterImpl::recompute
recompute()
template<typename T, fl::size N = 0> T fl::detail::TriangularFilterImpl< T, N >::recompute () inline private
Definition at line 56 of file triangular_filter_impl.h.
                  {
        fl::size n = mBuf.size();
        T weighted_sum = T(0);
        T weight_total = T(0);
        for (fl::size i = 0; i < n; ++i) {
            fl::size w_int = fl::min(i + 1, n - i);
            T w = T(static_cast<float>(w_int));
            weighted_sum = weighted_sum + mBuf[i] * w;
            weight_total = weight_total + w;
        }
        mLastValue = weighted_sum / weight_total;
        return mLastValue;
    }
References mBuf, fl::min(), and mLastValue.
Referenced by update(), and update().