FastLED: nblend
nblend() [3/4]
CRGB & nblend (CRGB & existing, const CRGB & overlay, fract8 amountOfOverlay)
Destructively modifies one color, blending in a given fraction of an overlay color.
Parameters
existing the color to modify
overlay the color to blend into existing
amountOfOverlay the fraction of overlay to blend into existing
Definition at line 303 of file colorutils.cpp.
{
    if( amountOfOverlay == 0) {
        return existing;
    }
    if( amountOfOverlay == 255) {
        existing = overlay;
        return existing;
    }
#if 0
    // Old blend method which unfortunately had some rounding errors
    fract8 amountOfKeep = 255 - amountOfOverlay;
    existing.red   = scale8_LEAVING_R1_DIRTY( existing.red,   amountOfKeep)
                    + scale8_LEAVING_R1_DIRTY( overlay.red,    amountOfOverlay);
    existing.green = scale8_LEAVING_R1_DIRTY( existing.green, amountOfKeep)
                    + scale8_LEAVING_R1_DIRTY( overlay.green,  amountOfOverlay);
    existing.blue  = scale8_LEAVING_R1_DIRTY( existing.blue,  amountOfKeep)
                    + scale8_LEAVING_R1_DIRTY( overlay.blue,   amountOfOverlay);
    cleanup_R1();
#else
    // Corrected blend method, with no loss-of-precision rounding errors
    existing.red   = blend8( existing.red,   overlay.red,   amountOfOverlay);
    existing.green = blend8( existing.green, overlay.green, amountOfOverlay);
    existing.blue  = blend8( existing.blue,  overlay.blue,  amountOfOverlay);
#endif
    return existing;
}
References blend8(), cleanup_R1(), and scale8_LEAVING_R1_DIRTY().
Referenced by blend(), blend(), fl::Pride2015::draw(), nblend(), nblend(), and pride().