FastLED: nblend
nblend() [1/4]
CHSV & nblend (CHSV & existing, const CHSV & overlay, fract8 amountOfOverlay, TGradientDirectionCode directionCode = SHORTEST_HUES)
Destructively modifies one color, blending in a given fraction of an overlay color.
Parameters
existing the color to modify
overlay the color to blend into existing
amountOfOverlay the fraction of overlay to blend into existing
directionCode the direction to travel around the color wheel
Definition at line 364 of file colorutils.cpp.
{
    if( amountOfOverlay == 0) {
        return existing;
    }
    if( amountOfOverlay == 255) {
        existing = overlay;
        return existing;
    }
    fract8 amountOfKeep = 255 - amountOfOverlay;
    uint8_t huedelta8 = overlay.hue - existing.hue;
    if( directionCode == SHORTEST_HUES ) {
        directionCode = FORWARD_HUES;
        if( huedelta8 > 127) {
            directionCode = BACKWARD_HUES;
        }
    }
    if( directionCode == LONGEST_HUES ) {
        directionCode = FORWARD_HUES;
        if( huedelta8 < 128) {
            directionCode = BACKWARD_HUES;
        }
    }
    if( directionCode == FORWARD_HUES) {
        existing.hue = existing.hue + scale8( huedelta8, amountOfOverlay);
    }
    else /* directionCode == BACKWARD_HUES */
    {
        huedelta8 = -huedelta8;
        existing.hue = existing.hue - scale8( huedelta8, amountOfOverlay);
    }
    existing.sat   = scale8_LEAVING_R1_DIRTY( existing.sat,   amountOfKeep)
    + scale8_LEAVING_R1_DIRTY( overlay.sat,    amountOfOverlay);
    existing.val = scale8_LEAVING_R1_DIRTY( existing.val, amountOfKeep)
    + scale8_LEAVING_R1_DIRTY( overlay.val,  amountOfOverlay);
    cleanup_R1();
    return existing;
}
References BACKWARD_HUES, cleanup_R1(), FORWARD_HUES, LONGEST_HUES, scale8(), scale8_LEAVING_R1_DIRTY(), and SHORTEST_HUES.