FastLED: fl::audio::Sample::fft
fft()
void fl::audio::Sample::fft (fft::Bins * out) const
Definition at line 178 of file audio.cpp.hpp.
{
    fl::span<const fl::i16> sample = pcm();
    fft::Args args;
    args.samples = sample.size();
    args.bands = out->bands();
    args.fmin = fft::Args::DefaultMinFrequency();
    args.fmax = fft::Args::DefaultMaxFrequency();
    args.sample_rate =
        fft::Args::DefaultSampleRate(); // TODO: get sample rate from Sample
    fl::Singleton<GuardedFFT>::instance().run(sample, out, args);
}
References args, fl::audio::fft::Bins::bands(), fl::audio::fft::Args::DefaultMaxFrequency(), fl::audio::fft::Args::DefaultMinFrequency(), fl::audio::fft::Args::DefaultSampleRate(), fl::Singleton< T, N >::instance(), pcm(), and fl::sample().