FastLED: juggle
juggle()
void juggle ()
Examples
DemoReel100.ino.
Definition at line 116 of file DemoReel100.ino.
              {
  // eight colored dots, weaving in and out of sync with each other
  fadeToBlackBy( leds, NUM_LEDS, 20);
  uint8_t dothue = 0;
  for( int i = 0; i < 8; i++) {
    leds[beatsin16( i+7, 0, NUM_LEDS-1 )] |= CHSV(dothue, 200, 255);
    dothue += 32;
  }
}
References beatsin16(), fadeToBlackBy(), leds, and NUM_LEDS.
Referenced by fl::DemoReel100::runPattern().