FastLED: bpm
bpm()
void bpm ()
Examples
DemoReel100.ino.
Definition at line 105 of file DemoReel100.ino.
{
  // colored stripes pulsing at a defined Beats-Per-Minute (BPM)
  uint8_t BeatsPerMinute = 62;
  CRGBPalette16 palette = PartyColors_p;
  uint8_t beat = beatsin8( BeatsPerMinute, 64, 255);
  for( int i = 0; i < NUM_LEDS; i++) { //9948
    leds[i] = ColorFromPalette(palette, gHue+(i*2), beat-gHue+(i*10));
  }
}
References beatsin8(), ColorFromPalette(), gHue, leds, NUM_LEDS, palette, and PartyColors_p.
Referenced by fl::DemoReel100::runPattern().