FastLED: addGlitter
addGlitter()
void addGlitter (fract8 chanceOfGlitter)
Examples
DemoReel100.ino.
Definition at line 93 of file DemoReel100.ino.
{
  if( random8() < chanceOfGlitter) {
    leds[ random16(NUM_LEDS) ] += CRGB::White;
  }
}
References leds, NUM_LEDS, random16(), random8(), and fl::CRGB::White.
Referenced by rainbowWithGlitter().