FastLED: fl::gfx::detail::renderRingRow
renderRingRow()
template<typename PixelT, bool Overwrite> void fl::gfx::detail::renderRingRow (PixelT * buf, int w, int py, fl::i32 d2_row, const RingCtx< PixelT > & g) inline
Render one scanline of a ring using incremental d² with phase-based scanning.
Templated on Overwrite for compile-time dispatch (no per-pixel branch). Zones (left to right): outside → outer-AA → solid → inner-AA → hole → inner-AA → solid → outer-AA → outside.
Definition at line 317 of file primitives.h.
{
    PixelT* ptr = &buf[py * w + g.xmin];
    fl::i32 d2 = d2_row;
    fl::i32 xd = g.xdelta0;
    int px = g.xmin;
    // Preamble: left exterior (d2 >= oo2)
    while (px <= g.xmax && d2 >= g.oo2) {
        d2 += xd; xd += 131072; ++ptr; ++px;
    }
    // Phase 1: outer-left AA fringe (oi2 <= d2 < oo2)
    while (px <= g.xmax && d2 >= g.oi2 && d2 < g.oo2) {
        fl::u16 diff = static_cast<fl::u16>(static_cast<fl::u32>(g.oo2 - d2) >> g.outer_shift);
        fl::u8 br = static_cast<fl::u8>((diff * g.outer_inv) >> 8);
        PixelT c = g.color; c.nscale8(br);
        if (Overwrite) *ptr = c; else *ptr += c;
        d2 += xd; xd += 131072; ++ptr; ++px;
    }
    // Phase 2: full-brightness band left (io2 <= d2 < oi2)
    while (px <= g.xmax && d2 >= g.io2 && d2 < g.oi2) {
        if (Overwrite) *ptr = g.color; else *ptr += g.color;
        d2 += xd; xd += 131072; ++ptr; ++px;
    }
    // Phase 3: inner-left AA fringe (ii2 <= d2 < io2)
    while (px <= g.xmax && d2 >= g.ii2 && d2 < g.io2) {
        fl::u16 diff = static_cast<fl::u16>(static_cast<fl::u32>(d2 - g.ii2) >> g.inner_shift);
        fl::u8 br = static_cast<fl::u8>((diff * g.inner_inv) >> 8);
        PixelT c = g.color; c.nscale8(br);
        if (Overwrite) *ptr = c; else *ptr += c;
        d2 += xd; xd += 131072; ++ptr; ++px;
    }
    // Phase 4: transparent hole (d2 < ii2)
    while (px <= g.xmax && d2 < g.ii2) {
        d2 += xd; xd += 131072; ++ptr; ++px;
    }
    // Phase 5: inner-right AA fringe (ii2 <= d2 < io2)
    while (px <= g.xmax && d2 >= g.ii2 && d2 < g.io2) {
        fl::u16 diff = static_cast<fl::u16>(static_cast<fl::u32>(d2 - g.ii2) >> g.inner_shift);
        fl::u8 br = static_cast<fl::u8>((diff * g.inner_inv) >> 8);
        PixelT c = g.color; c.nscale8(br);
        if (Overwrite) *ptr = c; else *ptr += c;
        d2 += xd; xd += 131072; ++ptr; ++px;
    }
    // Phase 6: full-brightness band right (io2 <= d2 < oi2)
    while (px <= g.xmax && d2 >= g.io2 && d2 < g.oi2) {
        if (Overwrite) *ptr = g.color; else *ptr += g.color;
        d2 += xd; xd += 131072; ++ptr; ++px;
    }
    // Phase 7: outer-right AA fringe (oi2 <= d2 < oo2)
    while (px <= g.xmax && d2 >= g.oi2 && d2 < g.oo2) {
        fl::u16 diff = static_cast<fl::u16>(static_cast<fl::u32>(g.oo2 - d2) >> g.outer_shift);
        fl::u8 br = static_cast<fl::u8>((diff * g.outer_inv) >> 8);
        PixelT c = g.color; c.nscale8(br);
        if (Overwrite) *ptr = c; else *ptr += c;
        d2 += xd; xd += 131072; ++ptr; ++px;
    }
}
References fl::gfx::detail::RingCtx< PixelT >::color, fl::gfx::detail::RingCtx< PixelT >::ii2, fl::gfx::detail::RingCtx< PixelT >::inner_inv, fl::gfx::detail::RingCtx< PixelT >::inner_shift, fl::gfx::detail::RingCtx< PixelT >::io2, fl::gfx::detail::RingCtx< PixelT >::oi2, fl::gfx::detail::RingCtx< PixelT >::oo2, fl::gfx::detail::RingCtx< PixelT >::outer_inv, fl::gfx::detail::RingCtx< PixelT >::outer_shift, renderRingRow(), fl::gfx::detail::RingCtx< PixelT >::xdelta0, fl::gfx::detail::RingCtx< PixelT >::xmax, and fl::gfx::detail::RingCtx< PixelT >::xmin.
Referenced by drawRingCore(), and renderRingRow().