FastLED: fl::gfx::detail::drawDiscCore
drawDiscCore()
template<typename PixelT, typename Coord, bool Overwrite> void fl::gfx::detail::drawDiscCore (Canvas< PixelT > & canvas, const PixelT & color, Coord cx, Coord cy, Coord r) inline
Definition at line 656 of file primitives.h.
{
    PixelT* pixels = canvas.pixels;
    int width = canvas.width;
    int height = canvas.height;
    fl::i32 cx8 = detail::toFixed8(cx);
    fl::i32 cy8 = detail::toFixed8(cy);
    fl::i32 r8 = detail::toFixed8(r);
    fl::i32 rin8 = r8 - 128;   // r - 0.5 in 8.8
    fl::i32 rout8 = r8 + 128;  // r + 0.5 in 8.8
    fl::i32 rin2 = rin8 * rin8;
    fl::i32 rout2 = rout8 * rout8;
    fl::i32 band = rout2 - rin2;
    if (band <= 0) return;
    int ri = (rout8 >> 8) + 1;
    int cxi = cx8 >> 8;
    int cyi = cy8 >> 8;
    int xmin = cxi - ri; if (xmin < 0) xmin = 0;
    int xmax = cxi + ri; if (xmax >= width) xmax = width - 1;
    if (xmin > xmax) return;
    if (cyi + ri < 0 || cyi - ri >= height) return;
    fl::i32 dx8 = (static_cast<fl::i32>(xmin) << 8) - cx8;
    fl::i32 dx2 = dx8 * dx8;
    detail::DiscCtx<PixelT> fc;
    fc.xdelta0 = 512 * dx8 + 65536;
    fc.xmin = xmin; fc.xmax = xmax;
    fc.rin2 = rin2; fc.rout2 = rout2;
    detail::computeBandShift(band, fc.band_shift, fc.band_inv);
    fc.color = color;
    fl::i32 cyfrac = (static_cast<fl::i32>(cyi) << 8) - cy8;
    fl::i32 d2c = dx2 + cyfrac * cyfrac;
    if (cyi >= 0 && cyi < height)
        detail::renderDiscRow<PixelT, Overwrite>(pixels, width, cyi, d2c, fc);
    fl::i32 botd2 = d2c, botdelta = 512 * cyfrac + 65536;
    fl::i32 topd2 = d2c, topdelta = -512 * cyfrac + 65536;
    botd2 += botdelta; botdelta += 131072;
    topd2 += topdelta; topdelta += 131072;
    for (int dy = 1; dy <= ri; ++dy) {
        bool cbot = (botd2 - dx2 <= rout2);
        bool ctop = (topd2 - dx2 <= rout2);
        if (!cbot && !ctop) break;
        int pyb = cyi + dy, pyt = cyi - dy;
        if (cbot && pyb >= 0 && pyb < height)
            detail::renderDiscRow<PixelT, Overwrite>(pixels, width, pyb, botd2, fc);
        if (ctop && pyt >= 0 && pyt < height)
            detail::renderDiscRow<PixelT, Overwrite>(pixels, width, pyt, topd2, fc);
        botd2 += botdelta; botdelta += 131072;
        topd2 += topdelta; topdelta += 131072;
    }
}
References fl::gfx::detail::DiscCtx< PixelT >::band_inv, fl::gfx::detail::DiscCtx< PixelT >::band_shift, fl::gfx::detail::DiscCtx< PixelT >::color, computeBandShift(), fl::gfx::Canvas< RGB_T >::height, fl::height, fl::gfx::Canvas< RGB_T >::pixels, renderDiscRow(), fl::gfx::detail::DiscCtx< PixelT >::rin2, fl::gfx::detail::DiscCtx< PixelT >::rout2, toFixed8(), fl::gfx::Canvas< RGB_T >::width, fl::width, fl::gfx::detail::DiscCtx< PixelT >::xdelta0, fl::gfx::detail::DiscCtx< PixelT >::xmax, and fl::gfx::detail::DiscCtx< PixelT >::xmin.
Referenced by fl::gfx::drawDisc().