FastLED: fl::gfx::detail::drawStrokeLineCore
drawStrokeLineCore()
template<typename PixelT, typename Coord, bool Overwrite> void fl::gfx::detail::drawStrokeLineCore (Canvas< PixelT > & canvas, const PixelT & color, Coord x0, Coord y0, Coord x1, Coord y1, Coord thickness, LineCap cap) inline
Definition at line 820 of file primitives.h.
{
    PixelT* pixels = canvas.pixels;
    int width = canvas.width;
    int height = canvas.height;
    fl::i32 x0_8 = detail::toFixed8(x0), y0_8 = detail::toFixed8(y0);
    fl::i32 x1_8 = detail::toFixed8(x1), y1_8 = detail::toFixed8(y1);
    fl::i32 dx_8 = x1_8 - x0_8;
    fl::i32 dy_8 = y1_8 - y0_8;
    if (dx_8 == 0 && dy_8 == 0) return;
    fl::i32 len2_16 = dx_8 * dx_8 + dy_8 * dy_8;
    fl::i32 len_8 = static_cast<fl::i32>(
        fl::isqrt32(static_cast<fl::u32>(len2_16)));
    fl::i32 thickness_8 = detail::toFixed8(thickness);
    fl::i32 r_max_8 = thickness_8 >> 1;
    fl::i32 threshold_q = r_max_8 * len_8;
    if (threshold_q <= 0) return;
    int x0i = x0_8 >> 8, y0i = y0_8 >> 8;
    int x1i = x1_8 >> 8, y1i = y1_8 >> 8;
    int margin = ((r_max_8 + 255) >> 8) + 2;
    int xmin = (x0i < x1i ? x0i : x1i) - margin;
    int xmax = (x0i > x1i ? x0i : x1i) + margin;
    int ymin = (y0i < y1i ? y0i : y1i) - margin;
    int ymax = (y0i > y1i ? y0i : y1i) + margin;
    if (xmin < 0) xmin = 0;
    if (xmax >= width) xmax = width - 1;
    if (ymin < 0) ymin = 0;
    if (ymax >= height) ymax = height - 1;
    if (xmin > xmax || ymin > ymax) return;
    fl::i32 dx_q = dx_8 << 8;
    fl::i32 dy_q = dy_8 << 8;
    fl::i32 rx_base_8 = (static_cast<fl::i32>(xmin) << 8) - x0_8;
    fl::i32 ry_row_8 = (static_cast<fl::i32>(ymin) << 8) - y0_8;
    fl::i32 cross_row_q = rx_base_8 * dy_8 - ry_row_8 * dx_8;
    fl::i32 dot_row_q = rx_base_8 * dx_8 + ry_row_8 * dy_8;
    fl::i32 len2_q = len_8 * len_8;
    fl::i32 dot_ext_q = (cap == LineCap::SQUARE) ? threshold_q : 0;
    detail::StrokeCtx<PixelT> sc;
    sc.threshold_q = threshold_q;
    sc.len2_q = len2_q;
    sc.dx_q = dx_q;
    sc.dy_q = dy_q;
    sc.dot_ext_q = dot_ext_q;
    detail::computeBandShift(threshold_q, sc.aa_shift, sc.aa_inv);
    sc.x0_8 = x0_8; sc.y0_8 = y0_8;
    sc.x1_8 = x1_8; sc.y1_8 = y1_8;
    sc.r_max2_8 = r_max_8 * r_max_8;
    sc.cap_shift = 0; sc.cap_inv = 0;
    if (cap == LineCap::ROUND && sc.r_max2_8 > 0) {
        detail::computeBandShift(sc.r_max2_8, sc.cap_shift, sc.cap_inv);
    }
    sc.cap = cap;
    sc.color = color;
    sc.xmin = xmin; sc.xmax = xmax;
    for (int py = ymin; py <= ymax; ++py) {
        if (py >= 0 && py < height) {
            detail::renderStrokeRow<PixelT, Overwrite>(pixels, width, py,
                                                       cross_row_q, dot_row_q, sc);
        }
        cross_row_q -= sc.dx_q;
        dot_row_q += sc.dy_q;
    }
}
References fl::gfx::detail::StrokeCtx< PixelT >::aa_inv, fl::gfx::detail::StrokeCtx< PixelT >::aa_shift, fl::gfx::detail::StrokeCtx< PixelT >::cap, fl::gfx::detail::StrokeCtx< PixelT >::cap_inv, fl::gfx::detail::StrokeCtx< PixelT >::cap_shift, fl::gfx::detail::StrokeCtx< PixelT >::color, computeBandShift(), fl::gfx::detail::StrokeCtx< PixelT >::dot_ext_q, fl::gfx::detail::StrokeCtx< PixelT >::dx_q, fl::gfx::detail::StrokeCtx< PixelT >::dy_q, fl::gfx::Canvas< RGB_T >::height, fl::height, fl::isqrt32(), fl::gfx::detail::StrokeCtx< PixelT >::len2_q, fl::gfx::Canvas< RGB_T >::pixels, fl::gfx::detail::StrokeCtx< PixelT >::r_max2_8, renderStrokeRow(), fl::gfx::detail::StrokeCtx< PixelT >::threshold_q, toFixed8(), fl::gfx::Canvas< RGB_T >::width, fl::width, fl::gfx::detail::StrokeCtx< PixelT >::x0_8, fl::gfx::detail::StrokeCtx< PixelT >::x1_8, fl::gfx::detail::StrokeCtx< PixelT >::xmax, fl::gfx::detail::StrokeCtx< PixelT >::xmin, fl::gfx::detail::StrokeCtx< PixelT >::y0_8, and fl::gfx::detail::StrokeCtx< PixelT >::y1_8.
Referenced by fl::gfx::drawStrokeLine().