FastLED: fl::FontRenderer::getScaledMetrics
getScaledMetrics()
FontRenderer::ScaledMetrics fl::FontRenderer::getScaledMetrics () const
Definition at line 200 of file truetype.cpp.hpp.
{
    ScaledMetrics result = {};
    if (!mFont) return result;
    FontMetrics metrics = mFont->getMetrics();
    result.ascent = static_cast<float>(metrics.ascent) * mScale;
    result.descent = static_cast<float>(metrics.descent) * mScale;
    result.lineGap = static_cast<float>(metrics.lineGap) * mScale;
    return result;
}
References FontRenderer(), fl::FontMetrics::ascent, fl::FontMetrics::descent, getScaledMetrics(), fl::FontMetrics::lineGap, mFont, and mScale.
Referenced by getScaledMetrics().