FastLED: fl::Luminova::resetParticle
resetParticle()
void fl::Luminova::resetParticle (Particle & p, fl::u32 tick) private
Definition at line 36 of file luminova.cpp.
{
    // Position at center
    const float cx = static_cast<float>(getWidth() - 1) * 0.5f;
    const float cy = static_cast<float>(getHeight() - 1) * 0.5f;
    p.x = cx;
    p.y = cy;
    // Original used noise(I)*W, we approximate with 1D noise scaled to width
    int I = static_cast<int>(tt / 50);
    uint8_t n1 = inoise8(static_cast<uint16_t>(I * 19));
    float noiseW = (static_cast<float>(n1) / 255.0f) * static_cast<float>(getWidth());
    p.a = static_cast<float>(tt) * 1.25f + noiseW;
    p.f = (tt & 1u) ? +1 : -1;
    p.g = I;
    p.s = 3.0f;
    p.alive = true;
}
References fl::Luminova::Particle::a, fl::Luminova::Particle::alive, fl::Luminova::Particle::f, fl::Luminova::Particle::g, fl::Fx2d::getHeight(), fl::Fx2d::getWidth(), inoise8(), fl::Luminova::Particle::s, fl::Luminova::Particle::x, and fl::Luminova::Particle::y.
Referenced by draw().