FastLED: fl::Luminova::draw
draw()
void fl::Luminova::draw (DrawContext context) override virtual
Parameters
now The current time in milliseconds. Fx writers are encouraged to use this instead of millis() directly as this will more deterministic behavior.
Implements fl::Fx.
Definition at line 86 of file luminova.cpp.
{
    // Fade + blur trails each frame
    fadeToBlackBy(context.leds, getNumLeds(), mParams.fade_amount);
    blur2d(context.leds, static_cast<fl::u8>(getWidth()), static_cast<fl::u8>(getHeight()),
           mParams.blur_amount, mXyMap);
    // Spawn/overwrite one particle per frame, round-robin across pool
    if (!mParticles.empty()) {
        size_t idx = static_cast<size_t>(mTick % static_cast<fl::u32>(mParticles.size()));
        resetParticle(mParticles[idx], mTick);
    }
    // Update and draw all particles
    for (size_t i = 0; i < mParticles.size(); ++i) {
        Particle &p = mParticles[i];
        if (!p.alive) {
            continue;
        }
        // s *= 0.997
        p.s *= 0.997f;
        if (p.s < 0.5f) {
            p.alive = false;
            continue;
        }
        // angle jitter using 2D noise: (t/99, g)
        float tOver99 = static_cast<float>(mTick) / 99.0f;
        uint8_t n2 = inoise8(static_cast<uint16_t>(tOver99 * 4096.0f), static_cast<uint16_t>(p.g * 37));
        float n2c = (static_cast<int>(n2) - 128) / 255.0f; // ~ -0.5 .. +0.5
        p.a += (n2c) / 9.0f;
        float aa = p.a * static_cast<float>(p.f);
        p.x += ::cosf(aa);
        p.y += ::sinf(aa);
        plotSoftDot(context.leds, p.x, p.y, p.s);
    }
    ++mTick;
}
References fl::Luminova::Particle::a, fl::Luminova::Particle::alive, fl::blur2d(), fl::Luminova::Particle::f, fl::fadeToBlackBy(), fl::Luminova::Particle::g, fl::Fx2d::getHeight(), fl::Fx::getNumLeds(), fl::Fx2d::getWidth(), inoise8(), fl::_DrawContext::leds, mParams, mParticles, mTick, fl::Fx2d::mXyMap, plotSoftDot(), resetParticle(), fl::Luminova::Particle::s, fl::Luminova::Particle::x, and fl::Luminova::Particle::y.