FastLED: fl::Luminova::plotSoftDot
plotSoftDot()
void fl::Luminova::plotSoftDot (CRGB * leds, float fx, float fy, float s) const private
Definition at line 63 of file luminova.cpp.
{
    // Map s (decays from ~3) to a pixel radius 1..3
    float r = fl::clamp<float>(s * 0.5f, 1.0f, 3.0f);
    int R = static_cast<int>(fl::ceil(r));
    // Avoid roundf() to prevent AVR macro conflicts; do manual symmetric rounding
    int cx = static_cast<int>(fx + (fx >= 0.0f ? 0.5f : -0.5f));
    int cy = static_cast<int>(fy + (fy >= 0.0f ? 0.5f : -0.5f));
    float r2 = r * r;
    for (int dy = -R; dy <= R; ++dy) {
        for (int dx = -R; dx <= R; ++dx) {
            float d2 = static_cast<float>(dx * dx + dy * dy);
            if (d2 <= r2) {
                float fall = 1.0f - (d2 / (r2 + 0.0001f));
                float vf = 255.0f * fall;
                if (vf < 0.0f) vf = 0.0f;
                if (vf > 255.0f) vf = 255.0f;
                uint8_t v = static_cast<uint8_t>(vf);
                plotDot(leds, cx + dx, cy + dy, v);
            }
        }
    }
}
References fl::ceil(), fl::clamp(), leds, and plotDot().
Referenced by draw().