name: esp32c2

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    uses: ./.github/workflows/build_template_custom_board.yml
    with:
      args: --boards esp32-c2-devkitm-1
      platform: https://github.com/pioarduino/platform-espressif32.git#develop

