name: stm32f411ce_blackpill

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'examples/**'
      - 'ci/**'
      - '.github/workflows/build_blackpill_stm32f4.yml'
      - '.github/workflows/build_template.yml'
      - 'CMakeLists.txt'
      - 'platformio.ini'
      - 'library.json'
      - 'library.properties'
jobs:
  build:
    uses: ./.github/workflows/build_template.yml
    with:
      args: stm32f411ce all