name: uno_r4_wifi

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'examples/**'
      - 'ci/**'
      - '.github/workflows/build_uno_r4_wifif.yml'
      - '.github/workflows/build_template.yml'
      - 'CMakeLists.txt'
      - 'platformio.ini'
      - 'library.json'
      - 'library.properties'
  pull_request:
    branches:
      - master
    paths:
      - 'src/**'
      - 'examples/**'
      - 'ci/**'
      - '.github/workflows/build_uno_r4_wifif.yml'
      - '.github/workflows/build_template.yml'
      - 'CMakeLists.txt'
      - 'platformio.ini'
      - 'library.json'
      - 'library.properties'

jobs:
  build:
    uses: ./.github/workflows/build_template.yml
    with:
      args: uno_r4_wifi all
