name: nano_every

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - fix-nano-every-build

jobs:
  build:
    uses: ./.github/workflows/build_template.yml
    with:
      args: nano_every
