name: lpc845brk

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'examples/**'
      - 'ci/**'
      - '.github/workflows/build_lpc845brk.yml'
      - '.github/workflows/build_template.yml'
      - 'CMakeLists.txt'
      - 'platformio.ini'
      - 'library.json'
      - 'library.properties'
      - 'pyproject.toml'
      - 'uv.lock'
jobs:
  build:
    uses: ./.github/workflows/build_template.yml
    with:
      args: lpc845brk Blink
