name: example tests windows

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'examples/**'
      - 'ci/**'
      - 'ci/examples/example_groups.py'
      - 'ci/meson/compile_tests/**'
      - '.github/workflows/example_test*.yml'
      - '.github/workflows/template_example_test.yml'
      - 'CMakeLists.txt'
      - 'meson.build'
      - 'examples/meson.build'
      - 'pyproject.toml'
      - 'test'
      - 'test.py'
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, labeled, unlabeled]
jobs:
  test:
    if: github.event_name == 'workflow_dispatch' || (github.event.pull_request.head.repo.full_name == github.repository && (contains(github.event.pull_request.labels.*.name, 'ci-full') || contains(github.event.pull_request.labels.*.name, 'ci-platforms-unit-test')))
    uses: ./.github/workflows/template_example_test.yml
    with:
      os: windows-latest
      build-mode: debug
      example-group: CompileTests
