name: nightly examples linux

on:
  workflow_dispatch:
  schedule:
    - cron: '20 3 * * *'
      timezone: America/Los_Angeles

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  examples:
    uses: ./.github/workflows/template_example_test.yml
    with:
      os: ubuntu-latest
      build-mode: debug-thin
      example-group: Nightly
