name: Stale issues and pull requests
on:
  schedule:
    # Every day at 00:00
    - cron: '0 0 * * *'

jobs:
  stale:
    name: Check issues and pull requests
    runs-on: ubuntu-latest
    steps:
      - name: No priority specified
        uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 60
          days-before-close: 7
          stale-issue-message: This issue had no activity for **2 months**. It will be closed in **one week** unless there is some new activity.
          stale-issue-label: stale
          exempt-issue-labels: high-priority,medium-priority,low-priority
          stale-pr-message: This pull request had no activity for **2 months**. It will be closed in **one week** unless there is some new activity.
          stale-pr-label: stale
          exempt-pr-labels: high-priority,medium-priority,low-priority

      - name: Low-priority
        uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          only-labels: low-priority
          days-before-stale: 90
          days-before-close: 7
          stale-issue-message: This issue had no activity for **3 months**. It will be closed in **one week** unless there is some new activity.
          stale-issue-label: stale
          stale-pr-message: This pull request had no activity for **3 months**. It will be closed in **one week** unless there is some new activity.
          stale-pr-label: stale

      - name: Medium-priority
        uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          only-labels: medium-priority
          days-before-stale: 90
          days-before-close: 14
          stale-issue-message: This issue had no activity for **3 months**. It will be closed in **two weeks** unless there is some new activity.
          stale-issue-label: stale
          stale-pr-message: This pull request had no activity for **3 months**. It will be closed in **two weeks** unless there is some new activity.
          stale-pr-label: stale

      - name: High-priority
        uses: actions/stale@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          only-labels: high-priority
          days-before-stale: 90
          days-before-close: 21
          stale-issue-message: This issue had no activity for **3 months**. It will be closed in **three weeks** unless there is some new activity.
          stale-issue-label: stale
          stale-pr-message: This pull request had no activity for **3 months**. It will be closed in **three weeks** unless there is some new activity.
          stale-pr-label: stale
