FastLED: fl::Mpeg1::createDecoder
createDecoder() [1/2]
IDecoderPtr fl::Mpeg1::createDecoder (const Mpeg1Config & config, fl::string * error_message = nullptr) static
Definition at line 8 of file mpeg1.cpp.hpp.
{
    FL_UNUSED(error_message);
    // MPEG1 is currently supported via software decoder on all platforms
    return fl::make_shared<third_party::SoftwareMpeg1Decoder>(config);
}
References FL_UNUSED, and fl::make_shared().
Referenced by createDecoder(), fl::FileSystem::openMpeg1Video(), and CodecProcessor::processMpeg1().