FastLED: autoResearchChipsetTimingLegacy
autoResearchChipsetTimingLegacy()
void autoResearchChipsetTimingLegacy (fl::AutoResearchConfig & config, int & driver_total, int & driver_passed, uint32_t & out_show_duration_ms, fl::vector< fl::RunResult > * out_results, int num_runs_per_pattern)
Definition at line 1125 of file AutoResearchTest.cpp.
{
    fl::sstream ss;
    ss << "\n========================================\n";
    ss << "Testing (LEGACY API): " << config.timing_name << "\n";
    ss << "  T0H: " << config.timing.t1_ns << "ns\n";
    ss << "  T1H: " << (config.timing.t1_ns + config.timing.t2_ns) << "ns\n";
    ss << "  T0L: " << config.timing.t3_ns << "ns\n";
    ss << "  RESET: " << config.timing.reset_us << "us\n";
    ss << "  Lanes: " << config.tx_configs.size() << "\n";
    for (size_t i = 0; i < config.tx_configs.size(); i++) {
        ss << "  Lane " << i << ": pin=" << config.tx_configs[i].getDataPin()
           << " LEDs=" << config.tx_configs[i].mLeds.size() << "\n";
    }
    ss << "========================================";
    FL_WARN(ss.str());
    // Create one legacy proxy per lane (each maps runtime pin to WS2812B<PIN> template)
    fl::vector<fl::unique_ptr<LegacyClocklessProxy>> proxies;
    for (size_t i = 0; i < config.tx_configs.size(); i++) {
        int pin = config.tx_configs[i].getDataPin();
        CRGB* leds = config.tx_configs[i].mLeds.data();
        int numLeds = static_cast<int>(config.tx_configs[i].mLeds.size());
        auto proxy = fl::make_unique<LegacyClocklessProxy>(pin, leds, numLeds);
        if (!proxy->valid()) {
            FL_ERROR("Legacy proxy invalid for lane " << i << " (pin " << pin << " out of range 0-8)");
            return;  // vector destructor cleans up already-created proxies
        }
        proxies.push_back(fl::move(proxy));
    }
    FastLED.setBrightness(255);
    // Pre-initialize the TX engine to avoid first-call setup delays
    for (size_t i = 0; i < config.tx_configs.size(); i++) {
        fill_solid(config.tx_configs[i].mLeds.data(), config.tx_configs[i].mLeds.size(), CRGB::Black);
    }
    FastLED.show();
    if (!FastLED.wait(1000)) {
        FL_ERROR("[LEGACY] TX wait timeout - driver may be stalled");
        return;  // vector destructor cleans up proxies
    }
    delay(5);  // Buffer drain (same as autoResearchChipsetTiming)
    // Run test patterns (identical to autoResearchChipsetTiming)
    int total = 0;
    int passed = 0;
    fl::MultiRunConfig multi_config;
    multi_config.num_runs = (num_runs_per_pattern > 0) ? num_runs_per_pattern : 1;
    multi_config.print_all_runs = (multi_config.num_runs > 1);
    multi_config.print_per_led_errors = false;
    multi_config.max_errors_per_run = 10;
    // Measure show-only duration (excludes setup/teardown overhead)
    uint32_t show_start_ms = millis();
    for (int pattern_id = 0; pattern_id < 4; pattern_id++) {
        // Apply pattern to all lanes
        for (size_t i = 0; i < config.tx_configs.size(); i++) {
            setMixedBitPattern(
                config.tx_configs[i].mLeds.data(),
                config.tx_configs[i].mLeds.size(),
                pattern_id
            );
        }
        runMultiTest(getBitPatternName(pattern_id), config, multi_config, total, passed, out_results);
    }
    out_show_duration_ms += millis() - show_start_ms;
    driver_total += total;
    driver_passed += passed;
    // proxies vector destructor deletes all controllers → ~CLEDController removes from draw list
}
References fl::CRGB::Black, fl::span< T, Extent >::data(), FastLED, fill_solid(), FL_ERROR, FL_WARN, getBitPatternName(), leds, fl::make_unique(), fl::MultiRunConfig::max_errors_per_run, fl::move(), fl::MultiRunConfig::num_runs, fl::MultiRunConfig::print_all_runs, fl::MultiRunConfig::print_per_led_errors, fl::vector< T >::push_back(), fl::ChipsetTimingConfig::reset_us, runMultiTest(), setMixedBitPattern(), fl::span< T, Extent >::size(), fl::sstream::str(), fl::ChipsetTimingConfig::t1_ns, fl::ChipsetTimingConfig::t2_ns, fl::ChipsetTimingConfig::t3_ns, fl::AutoResearchConfig::timing, fl::AutoResearchConfig::timing_name, and fl::AutoResearchConfig::tx_configs.
Referenced by AutoResearchRemoteControl::runSingleTestImpl().