FastLED: buildExpectedUCS7604
buildExpectedUCS7604()
static fl::vector< uint8_t > buildExpectedUCS7604 (fl::span< CRGB > leds, fl::ClocklessEncoder encoder) static
Build expected UCS7604 encoded bytes from LED data.
Parameters
leds LED data span
encoder Encoder selector identifying the UCS7604 variant
Returns
Vector of expected encoded bytes (preamble + padding + pixel data)
Definition at line 129 of file AutoResearchTest.cpp.
{
    fl::vector<uint8_t> expected;
    // Map encoder to UCS7604Mode
    fl::UCS7604Mode mode;
    switch (encoder) {
        case fl::ClocklessEncoder::CLOCKLESS_ENCODER_UCS7604_8BIT:
            mode = fl::UCS7604Mode::UCS7604_MODE_8BIT_800KHZ;
            break;
        case fl::ClocklessEncoder::CLOCKLESS_ENCODER_UCS7604_16BIT:
            mode = fl::UCS7604Mode::UCS7604_MODE_16BIT_800KHZ;
            break;
        case fl::ClocklessEncoder::CLOCKLESS_ENCODER_UCS7604_16BIT_1600:
            mode = fl::UCS7604Mode::UCS7604_MODE_16BIT_1600KHZ;
            break;
        default:
            return expected;
    }
    // Default current control (0x0F for all channels) matching channel.cpp.hpp defaults
    fl::UCS7604CurrentControl current;  // defaults to 0xF for all channels
    // Create PixelIterator from LED data (RGB order, no color adjustment, no dithering)
    PixelController<RGB> pc(leds.data(), leds.size(), ColorAdjustment::noAdjustment(), DISABLE_DITHER);
    auto pixel_iter = pc.as_iterator(RgbwInvalid());
    // For 16-bit modes, use default gamma 2.8
    fl::shared_ptr<const fl::Gamma8> gamma;
    bool use_gamma = (mode != fl::UCS7604Mode::UCS7604_MODE_8BIT_800KHZ);
    if (use_gamma) {
        gamma = fl::Gamma8::getOrCreate(2.8f);
    }
    // Encode using the same function the driver uses
    fl::encodeUCS7604(pixel_iter, leds.size(), fl::back_inserter(expected),
                      mode, current, false /* is_rgbw */, gamma.get());
    return expected;
}
References PixelController< RGB_ORDER, LANES, MASK >::as_iterator(), fl::back_inserter(), fl::CLOCKLESS_ENCODER_UCS7604_16BIT, fl::CLOCKLESS_ENCODER_UCS7604_16BIT_1600, fl::CLOCKLESS_ENCODER_UCS7604_8BIT, DISABLE_DITHER, fl::encodeUCS7604(), fl::Gamma8::getOrCreate(), leds, ColorAdjustment::noAdjustment(), fl::UCS7604_MODE_16BIT_1600KHZ, fl::UCS7604_MODE_16BIT_800KHZ, and fl::UCS7604_MODE_8BIT_800KHZ.
Referenced by runMultiTest(), and runTest().