FastLED: fl::Rgbww::Rgbww
Rgbww()
fl::Rgbww::Rgbww (fl::u16 warm = kRGBWWDefaultWarmCct, fl::u16 cool = kRGBWWDefaultCoolCct, RGBWW_MODE mode = RGBWW_MODE::kRGBWWColorimetric, EOrderWW placement = EOrderWW::WWDefault) inline explicit
Definition at line 61 of file rgbww.h.
        : warm_cct(warm), cool_cct(cool),
          rgbww_mode(mode), w_placement(placement),
          profile(nullptr) {}
References FL_NOEXCEPT, fl::kRGBWWColorimetric, fl::kRGBWWDefaultCoolCct, fl::kRGBWWDefaultWarmCct, and fl::WWDefault.
Referenced by fl::RgbwwDefault::RgbwwDefault(), fl::RgbwwInvalid::RgbwwInvalid(), fl::RgbwwDefault::value(), and fl::RgbwwInvalid::value().