FastLED: fl::HashMap::const_iterator::const_iterator
const_iterator() [1/3]
template<typename Key, typename T, typename Hash = Hash<Key>, typename KeyEqual = EqualTo<Key>, int INLINED_COUNT = FASTLED_HASHMAP_INLINED_COUNT> fl::HashMap< Key, T, Hash, KeyEqual, INLINED_COUNT >::const_iterator::const_iterator () inline
Definition at line 127 of file hash_map.h.
: _map(nullptr), _idx(0) {}
References _idx, and _map.
Referenced by operator!=(), operator++(), operator++(), and operator==().