FastLED: fl::UICheckbox::UICheckbox
UICheckbox()
fl::UICheckbox::UICheckbox (const char * name, bool value = false) inline
Definition at line 194 of file ui.h.
        : UICheckboxImpl(name, value), mListener(this) {}
References fl::UICheckboxImpl::UICheckboxImpl(), mListener, and fl::UICheckboxImpl::value().
Referenced by fl::UICheckbox::Listener::Listener(), FL_NO_COPY(), fl::UICheckbox::Listener::onBeginFrame(), onChanged(), and operator=().